mono/mono

mono/utils/mono-merp.c
This might invalidate all existing data however and perhaps 32bits is enough.
```
/s/mono/mono/utils/mono-merp.c:227:63: warning: format specifies type 'unsigned int' but the argument has type 'size_t' (aka 'unsigned long') [-Wformat]
g_string_append_printf (output, "BlameModuleOffset: 0x%x\n", merp->moduleOffset);
~~     ^~~~~~~~~~~~~~~~~~
%zx
/s/mono/mono/utils/mono-merp.c:231:59: warning: format specifies type 'unsigned int' but the argument has type 'guint64' (aka 'unsigned long long')
[-Wformat]
g_string_append_printf (output, "StackChecksum: 0x%x\n", merp->hashes.offset_free_hash);
~~     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%llx
/s/mono/mono/utils/mono-merp.c:232:55: warning: format specifies type 'unsigned int' but the argument has type 'guint64' (aka 'unsigned long long')
[-Wformat] …
```
=> Do not truncate 64bit MERP hashes to 32bits.

mono/mini/mini-amd64.c, mono/mini/mini-llvm.c
* Add support for additional calling conventions supported on Windows x64.
* Add support for more call info storage types used on Windows x64.
=> Increase number of compiled LLVM methods on Windows x64.

mono/metadata/marshal-internals.h, mono/metadata/marshal-windows.c, mono/metadata/marshal.c
Fix https://github.com/mono/mono/issues/11898
This regressed six months ago at https://github.com/mono/mono/pull/9503/files#r238093574.
There are two identical sounding functions:
mono_string_handle_to_utf8:
What we usually use. Sounds reasonable. Usually is reasonable.
Allocates with malloc.
mono_string_to_utf8str_handle:
What should be used here. Allocates with CoTaskMemAlloc.
So it can be freed with marshal_free => CoTaskMemFree.
i.e. The allocator and the freeer need to agree.
=> Fix https://github.com/mono/mono/issues/11898

mono/native/Makefile.am
I forgot to fix Makefile.am to check for AIX and include the unix
sources if so. Actually fixes #11895.
=> Fix lack of symbols in System.Native support lib on AIX

mono/mini/mini-posix.c, mono/mini/mini-runtime.c, mono/mini/mini.h, mono/mini/unwind.c, mono/utils/mono-logger-internals.h, mono/utils/mono-logger.c
Historically very common and hard to reproduce assertion, which, in some cases, could be fixed just from this logging. Log example :
```
Unset cfa_reg in method <0x40011220 - (null) trampoline>. Memory around ip (0x40011220):
0x40011210  41 89 07 4c 8b 3c 24 48 83 c4 08 c3 00 00 00 00  A..L.<$H........
0x40011220  48 83 c7 10 b8 00 12 01 40 ff e0 00 00 00 00 00  H.......@.......
0x40011230  00 00 00 00 e8 c7 ef fe ff 08 f8 34 e0 55 55 55  ...........4.UUU
0x40011240  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
* Assertion: should not be reached at unwind.c:664
```
=> [exceptions] Verbose logging for cfa_reg assertion

mono/mini/exceptions-x86.c, mono/mini/local-propagation.c, mono/mini/mini-riscv.c, mono/mini/mini-x86.c, mono/mini/mini-x86.h, mono/mini/ssa.c
`uintptr_t` or `intptr_t`?
```
/s/mono/mono/mini/ssa.c:1119:35: warning: cast to 'gpointer' (aka 'void *') from smaller integer type 'target_mgreg_t' (aka 'int')
[-Wint-to-void-pointer-cast]
((MonoCallInst*)ins)->fptr = (gpointer)ins->inst_imm;
^
/s/mono/mono/mini/local-propagation.c:680:37: warning: cast to 'gpointer' (aka 'void *') from smaller integer type 'target_mgreg_t' (aka 'int')
[-Wint-to-void-pointer-cast]
((MonoCallInst*)ins)->fptr = (gpointer)ins->inst_imm;
^
/s/mono/mono/mini/mini-x86.c:5719:1: error: conflicting types for 'mono_arch_get_this_arg_from_call'
mono_arch_get_this_arg_from_call (mgreg_t *regs, guint8 *code)
^
/s/mono/mono/mini/mini.h:2406:10: note: previous declaration is here
gpointer mono_arch_get_this_arg_from_call       (host_mgreg_t *regs, guint8 *code);
^ …
```
=> Fix some host64 target32 compilation warnings and errors.

mcs/class/referencesource/System.Xml/System/Xml/XmlCharType.cs
Fix race condition in `XmlCharType.Instance` because:
```
if ( s_CharProperties == null ) {
InitInstance();
}
```
=> Fix race condition in XmlCharType.Instance

mcs/class/referencesource/System.Xml/System/Xml/XmlCharType.cs
Fix race condition in `XmlCharType.Instance` because:
```
if ( s_CharProperties == null ) {
InitInstance();
}
```
Backport of #11814.
/cc @marek-safar @ww898
=> [2018-10] Fix race condition in XmlCharType.Instance

mcs/class/referencesource/System.Xml/System/Xml/XmlCharType.cs
Fix race condition in `XmlCharType.Instance` because:
```
if ( s_CharProperties == null ) {
InitInstance();
}
```
Backport of #11814.
/cc @marek-safar @ww898
=> [2018-08] Fix race condition in XmlCharType.Instance

mono/metadata/marshal-internals.h, mono/metadata/marshal-windows.c, mono/metadata/marshal.c
Fix https://github.com/mono/mono/issues/11898
This regressed six months ago at https://github.com/mono/mono/pull/9503/files#r238093574.
There are two identical sounding functions:
mono_string_handle_to_utf8:
What we usually use. Sounds reasonable. Usually is reasonable.
Allocates with malloc.
mono_string_to_utf8str_handle:
What should be used here. Allocates with CoTaskMemAlloc.
So it can be freed with marshal_free => CoTaskMemFree.
i.e. The allocator and the freeer need to agree.
Backport of #11899.
/cc @marek-safar @jaykrell
=> [2018-10] Fix #11898

mono/metadata/marshal-internals.h, mono/metadata/marshal-windows.c, mono/metadata/marshal.c
Fix https://github.com/mono/mono/issues/11898
This regressed six months ago at https://github.com/mono/mono/pull/9503/files#r238093574.
There are two identical sounding functions:
mono_string_handle_to_utf8:
What we usually use. Sounds reasonable. Usually is reasonable.
Allocates with malloc.
mono_string_to_utf8str_handle:
What should be used here. Allocates with CoTaskMemAlloc.
So it can be freed with marshal_free => CoTaskMemFree.
i.e. The allocator and the freeer need to agree.
Backport of #11899.
/cc @marek-safar @jaykrell
=> [2018-08] Fix https://github.com/mono/mono/issues/11898

mono/mini/aot-compiler.c, mono/mini/exceptions-amd64.c, mono/mini/mini-amd64.c, mono/mini/mini-amd64.h, mono/mini/mini-arm64.c, mono/mini/mini-gc.c, mono/mini/mini-ppc.c, mono/mini/mini-sparc.h, mono/mini/tramp-ppc.c, mono/mini/tramp-riscv.c, mono/mini/unwind.c, mono/utils/mono-context.h
Mostly target_mgreg_t.
Note that this is all optional, in the sense that cross compilers
never run their runtime. So mgreg_t is always target_mgreg_t, or
they are the same.
But agreement is to ban mgreg_t.
=> More mgreg_t to host_mgreg_t or target_mgreg_t conversion.

mcs/class/Mono.Debugger.Soft/Makefile, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft.csproj, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/AssemblyMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/CustomAttributeDataMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/FieldInfoMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/ILInstruction.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/ILInterpreter.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/InterfaceMappingMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/MethodBodyMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/MethodMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/ModuleMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/PropertyInfoMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/TypeMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
Not all downstream users of the Mono.Debugger.Soft library are using the feature where mirrors provide direct access to the Cecil metadata if the `AssemblyMirror` has been fed a Cecil `AssemblyDefinition`.
This PR introduces a define to opt-in to use the Cecil metadata, otherwise falls back to exposing System.Reflection.Emit opcodes in the Instruction API.
=> [Mono.Debugger.Soft] Make exposing Cecil metadata an option

mono/metadata/threads.c
In particular, to not fail asserts related to MONO_ERROR_CLEANUP_CALLED_SENTINEL,
which are currently missing or incorrect.
See https://github.com/mono/mono/pull/11863
=> Fix and cleanup GetAbortExceptionState, esp. wrt broken MONO_ERROR_CLEANUP_CALLED_SENTINEL assert.

scripts/ci/run-jenkins.sh
-  Found latest V8 version: v7.3.16.  Works
Resolves: https://github.com/mono/mono/issues/11908
=> [ci] Re-Enable V8 tests on wasm

configure.ac, mono/tests/Makefile.am, scripts/ci/run-jenkins.sh, scripts/ci/run-test-testing_aot_full_interp_llvm.sh
That is, the AOT compiler uses the LLVM backend for BCL. AOT+LLVM is
used in the 'Release' configuration on Xamarin.iOS.
=> [bcl] add fullaotinterp_llvm preset

mono/mini/exceptions-s390x.c
New parameter addition was put in wrong spot in the parameter list. Also the offsets on the stack were incorrect as 32-bit values are placed in 64-bit aligned slots on s390x. Therefore, even though these are gbooleans the appear to be treated as gulongs.
=> Fix order of parameter processing. 

mono/metadata/icall.c, mono/metadata/threads.c
When a crash happens too early in initialization for the crash reporter to operate, exit gracefully
=> [crash] Early exit if callbacks not set

mono/mini/mini-llvm.c
mono/master 32beba680eda59a95894713388116cf904eaf453 with no local edits
With C++ accidentally enabled.
make -C sdks/builds build-ios-cross32 build-android-cross-arm build-android-cross-x86
```
/s/mono/mono/mini/mini-llvm.c:7729:18: warning: unused variable 'iter' [-Wunused-variable]
GHashTableIter iter;
^
/s/mono/mono/mini/mini-llvm.c:7730:15: warning: unused variable 'method' [-Wunused-variable]
MonoMethod *method;
^
/s/mono/mono/mini/mini-llvm.c:7731:11: warning: unused variable 'callers' [-Wunused-variable]
GSList *callers, *l, *l2;
^
/s/mono/mono/mini/mini-llvm.c:7731:21: warning: unused variable 'l' [-Wunused-variable]
GSList *callers, *l, *l2;
^
/s/mono/mono/mini/mini-llvm.c:7731:25: warning: unused variable 'l2' [-Wunused-variable]
GSList *callers, *l, *l2;
^ …
```
=> Fix warnings and a C++ error.

libgc/include/gc_pthread_redirects.h, mono/metadata/remoting.c, mono/metadata/w32file-unix.c, mono/mini/mini-posix.c, mono/sgen/sgen-memory-governor.c
This isn't correct for Win64 but that should be ok.
It is correct for all other platforms.
Ultimately  PRI64 and  casting to int64_t or uint64_t is the most portable and warning-free.
mingw warns for every use  of %ll for example, though the warning appears to be incorrect.
Or stop using sprintf. Portabilty problem, warning-farm, slow, overly general, not as reentrant as suspected, etc.
```
/s/mono/mono/sgen/sgen-memory-governor.c:309:5: warning: format specifies type 'ssize_t' (aka 'long') but the argument has type 'unsigned int' [-Wformat]
entry->promoted_size / 1024,
^~~~~~~~~~~~~~~~~~~~~~~~~~~
/s/mono/mono/sgen/sgen-memory-governor.c:310:5: warning: format specifies type 'ssize_t' (aka 'long') but the argument has type 'unsigned int' [-Wformat]
entry->major_size / 1024, …
```
=> Fix warnings.

mono/utils/mono-time.c
```
/s/mono/mono/utils/mono-time.c:23:34: warning: unused variable 's_TimebaseInfo' [-Wunused-variable]
static mach_timebase_info_data_t s_TimebaseInfo;
/s/mono/mono/utils/mono-time.c:112:1: warning: unused function 'get_boot_time' [-Wunused-function]
```
=> Fix warnings and race condition in time keeping.

mono/mini/mini-ppc.c
2b029b3df4a1816880e3f02bacd35cf9a0835e4e broke ppc JIT tracing by
moving it into mini and changing the arguments. Since the mini IR
emitter handles tracing now, rip out the tracing code from the JIT.
(Looks like SPARC will need a similar change, but someone needs to
love SPARC first.)
cc @lewurm (particularly over `mono_arch_allocate_vars` changes; I suspect the mini mid-end handles that now, and the comment about the stack allocation, but just want to be sure)
=> Fix PowerPC regression caused by tracing changes

mono/metadata/handle.c, mono/metadata/marshal.c, mono/metadata/method-builder.c, mono/metadata/sgen-mono.c, mono/metadata/w32file-unix.c, mono/metadata/w32handle.h, mono/metadata/w32process-unix-internals.h, mono/mini/branch-opts.c, mono/mini/exceptions-arm.c, mono/mini/helpers.c, mono/mini/interp/interp.c, mono/mini/interp/transform.c, mono/mini/mini-arm.c, mono/sgen/sgen-debug.c, mono/sgen/sgen-descriptor.c, mono/sgen/sgen-gc.c, mono/sgen/sgen-nursery-allocator.c, mono/sgen/sgen-pinning.c, mono/tests/libtest.c, mono/utils/mono-counters.c, mono/utils/mono-error.c, mono/utils/mono-os-mutex.h, mono/utils/mono-os-semaphore.h, mono/utils/mono-threads-android.c, mono/utils/mono-threads.h, mono/utils/os-event.h
```
/s/mono/mono/mini/interp/transform.c:1666:15: warning: unused variable 'vt' [-Wunused-variable]
MonoVTable *vt = mono_class_vtable_checked (domain, target_method->klass, error);
^
/s/mono/mono/utils/mono-counters.c:547:55: warning: format specifies type 'ssize_t' (aka 'long') but the argument has type 'gssize' (aka 'int') [-Wformat]
fprintf (outfile, ENTRY_FMT "%zd\n", counter->name, *(gssize*)buffer);
~~~                    ^~~~~~~~~~~~~~~~
%td
/s/mono/mono/sgen/sgen-debug.c:1066:72: warning: format specifies type 'ssize_t' (aka 'long') but the argument has type 'int' [-Wformat]
fprintf (heap_dump_file, "<occupied offset=\"%zd\" size=\"%zd\"/>\n", start - section_start, end - start);
~~~                      ^~~~~~~~~~~~~~~~~~~~~
%d
/s/mono/mono/sgen/sgen-debug.c:1066:95: warning: …
```
=> Fix a bunch of warnings.

mono/mini/interp/interp.c, mono/mini/method-to-ir.c
```
/s/mono/mono/mini/interp/interp.c: In function 'interp_entry_from_trampoline':
/s/mono/mono/mini/interp/interp.c:2422:3: warning: 'orig_domain' may be used uninitialized in this function [-Wmaybe-uninitialized]
mono_threads_detach_coop (orig_domain, &attach_cookie);
^
/s/mono/mono/mini/interp/interp.c: In function 'interp_exec_method_full':
/s/mono/mono/mini/interp/interp.c:2695:4: warning: 'locals' may be used uninitialized in this function [-Wmaybe-uninitialized]
memset (locals, 0, rtm->locals_size);
^
/s/mono/mono/mini/method-to-ir.c: In function 'mini_handle_enum_has_flag':
/s/mono/mono/mini/method-to-ir.c:3416:9: warning: 'load' may be used uninitialized in this function [-Wmaybe-uninitialized]
load = mono_decompose_opcode (cfg, load);
^
```
At least the first two seem to be …
=> Quash some "may be used uninitialized" warnings.

mono/metadata/threads.c, mono/sgen/sgen-gc.h, mono/utils/mono-log-common.c, mono/utils/mono-log-windows.c, mono/utils/mono-time.h
Expand them to their portable equivalents.
=> strftime(%F) and strftime(%T) are unnecessary unportable shorthands that warn.

mono/tests/libtest.c
https://gcc.gnu.org/bugzilla/show_activity.cgi?id=88352
Investigating my own PR breakage..I ended up building libtest with gcc and the runtime with msvc.
A runtime built with gcc would have behaved the same. Gcc has an ABI bug, that mono does not and probably should not implement, unless maybe gcc refuses to fix it.
Given:
libtest.c:
typedef struct {
double d;
} SingleDoubleStruct;
SingleDoubleStruct mono_test_marshal_return_single_double_struct (void);
Visual C++ and mono expect the return value in edx:eax.
Gcc returns it in ST0.
Changing struct to union fixes it.
Mono "actually" expects return value in local via pointer
in extra parameter, but it generates a wrapper to bridge
its custom (SysV?) ABI to the NT ABI.
Adjust the test to avoid the gcc bug.
The runtime is unchanged.
=> Adjust test (not runtime) to workaround Windows i386 GCC ABI bug.

mono/mini/mini-ops.h, mono/mini/mini-ppc.c
d5547b1929afa91944ba941d66a93767ca534a97 made an incorrect change to `mini-ppc.c` that wouldn't build; revert that file.
=> Fix regression with building PPC JIT

mono/sgen/sgen-gc.h
..\mono\metadata\sgen-mono.c(1443): warning C4390: ';': empty controlled statement found; is this the intent?
(Why is this not a function?)
=> Fix CHECK_CANARY_FOR_OBJECT.

mono/metadata/marshal.c, mono/metadata/marshal.h
- Reduce length computations of strings.
- Handle zero sized StringBuilder correctly (initialize the first
not just the second character).
- Check for overflow correctly in StringBuilder -- include offset.
- Fix prototype of mono_string_to_byvalstr (gpointer vs. char*).
- Fix prototype of mono_string_to_byvalwstr (gpionter vs. gunichar2*).
- Single point of exit in mono_string_builder_to_utf8.
=> marshal.c cleanup

mono/mini/mini-amd64.c
There are no 32bit host 64bit target configurations so this is cosmetic.
=> sizeof (gpointer) => sizeof (target_mgreg_t).

mono/metadata/icall-def.h
If this is incorrect, static or compile-time checks will eventually catch it.
=> [Coop] Mark System.ArgIterator icalls all NOHANDLES.

mcs/class/corlib/linux_build_corlib.dll.sources, mcs/class/corlib/macos_build_corlib.dll.sources, mcs/class/corlib/monotouch_corlib.dll.sources, mcs/class/corlib/unix_build_corlib.dll.sources
...of importing it at linux/macOS
this unbreaks the build on "unix" platforms like FreeBSD and AIX
(is this all needed files, and am I doing this right?)
=> for "build" config, import corlib common sources at unix instead

mono/metadata/icall-def.h, mono/metadata/locales.c, mono/metadata/locales.h
Unused since Feb 2018 d63e8b6f5ae04bdbf7b68f6f884d797df0d220ec.
=> Remove ves_icall_System_Globalization_CompareInfo_internal_index_char.

mono/metadata/mono-perfcounters.c, mono/metadata/w32process.c
These are the kinds of things a bare minimum of C++ -- destructors -- will make trivial to get correct with smaller/cleaner code.
A strict C convention would help too -- only ever a single point of function exit, at least for functions that "allocate any resources" (or more generally have "invariants to restore" -- like a function that increments some counter upon entry and decrements upon exit).
"Things you find if you read the code while converting to Coop."
=> Fix two leaks in error paths.

mono/mini/mini-posix.c
Looks like this broke when it got squashed down, or we overlooked it. We've got two calls where we expected one.
=> [runtime] Remove duplicate merp invoke line

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/metadata/threads.c, mono/mini/debugger-agent.c
The problem with this flaky issue was the timing of processing of the async tasks, as it was executed in background threads it was not possible to reach the end of execution because all the foreground threads exit earlier.
The solution creates a TaskScheduler that ensure that the thread that will execute the task will be a foreground thread and then the test always works.
Fixes https://github.com/mono/mono/issues/6997
=> [debugger] Fix test StepOutAsync

configure.ac, mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs, mcs/class/corlib/ReferenceSources/CompareInfo.cs, mono/metadata/icall-def.h, mono/metadata/locales.c, mono/metadata/locales.h, mono/metadata/object-internals.h
MonoSortKey native:
https://github.com/mono/mono/blob/f019810b12ba130b7fed1cd41bb2eaed04ececef/mono/metadata/object-internals.h#L700
SortKey managed:
https://github.com/mono/mono/blob/f019810b12ba130b7fed1cd41bb2eaed04ececef/mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs#L69
do not agree.
Memory is corrupted and crash if you set $MONO_DISABLE_MANAGED_COLLATION=yes documented here:
https://github.com/mono/mono/blob/f019810b12ba130b7fed1cd41bb2eaed04ececef/man/mono.1#L1161
Fix is to remove the native code and replace by trivial managed.
Found testing coop-conversion of System.Globalization. https://github.com/mono/mono/pull/12023
=> Fix MonoSortKey native/managed layout mismatch.

mcs/class/referencesource/System.Xml/System/Xml/Core/XmlReaderSettings.cs
Let's don't access Registry every time we use System.Xml for the first time
Fixes https://github.com/mono/mono/issues/11998
.NET Core doesn't have this option at all.
This legacy mode allows users to have old <4.5 behavior when XmlReader could send some web request for DTD urls, we even had a bug for it when `XmlDocument.Load` could crash if internet is turned off (see https://bugzilla.xamarin.com/show_bug.cgi?id=60621)
=> [System.XML] Get rid of Registry in XmlReader

configure.ac, mono/mini/mini-amd64.h, mono/mini/mini-x86.h, msvc/build-external-llvm.bat, msvc/build-external-llvm.vcxproj, msvc/build-init.vcxproj, msvc/mono.external.targets, msvc/mono.props, msvc/winsetup.bat
**Add support for LLVM asserts in internal LLVM build on Windows:**
Read and use of enable-llvm-asserts in autogen and include it in MSVC internal build LLVM.
**Only build LLVM using MSVC if not cross compiling:**
If not cross compiling, building runtime where host/target is Windows, only build and use LLVM as part of msvc build (only supported configuration), disabled on gcc build. This is needed so autogen.sh can be used to configure build using for example --enable-llvm, but only build on supported Windows configurations. NOTE, this will only be applied to none cross compiler builds since that LLVM build is currently x64, MSVC only.
Enforce 64-bit LLVM support when building using Visual Studio solution file.
=> Windows x64 LLVM assert support + MSVC only for none cross compiler build.

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/CustomAttributeDataMirror.cs
We were seeing random exceptions debugging an old protocol version, that would all happen after looking at Custom Attributes.
Turns out the client was always expecting the server to send a field id for named arguments in custom attributes. The server was fixed in https://github.com/mono/mono/commit/db0b932cd6c3c93976479ae3f6b5b2a885f681de without bumping the version, in between `2.11` and `2.12`
2.12 is then the only version in which can guarantee we can read named arguments for fields.
=> [Mono.Debugger.Soft] Fix reading custom attribute named arguments on old protocol versions

configure.ac, mcs/class/corlib/ReferenceSources/CompareInfo.cs, mono/metadata/icall-def.h, mono/metadata/locales.c, mono/metadata/locales.h
This is a subset of https://github.com/mono/mono/pull/12023, maybe easier to review
in smaller pieces.
Alternatives:
1. Move more to managed.
2. Remove the feature.
=> [Coop] Convert System.Globalization.CompareInfo.

mono/metadata/marshal.c
and like mono_string_to_byvalwstr does and like the code
makes room for.
=> Null terminate in mono_string_to_byvalstr as seems intended.

mcs/build/library.make, mcs/build/tests.make, mcs/class/corlib/win32_net_4_x_corlib_test.dll.sources, mcs/tools/gensources/gensources.cs, msvc/scripts/genproj.cs
The `gensources` tool now supports platform/specific `.sources` for nunit and xunit tests.
=> [gensources]: Add platform/project logic to tests.

mcs/class/corlib/Test/System.Reflection/ParameterInfoTest.cs, mcs/class/referencesource/mscorlib/system/attribute.cs
Fixes #12069
Backport of #12090.
=> [2018-08] Fix IndexOutOfRangeException in MethodInfo.ReturnParameter.IsDefined(type)

mono/mini/mini-posix.c, mono/mini/mini-runtime.c, mono/mini/mini.h, mono/mini/unwind.c, mono/utils/mono-logger-internals.h, mono/utils/mono-logger.c
Historically very common and hard to reproduce assertion, which, in some cases, could be fixed just from this logging. Log example :
```
Unset cfa_reg in method <0x40011220 - (null) trampoline>. Memory around ip (0x40011220):
0x40011210  41 89 07 4c 8b 3c 24 48 83 c4 08 c3 00 00 00 00  A..L.<$H........
0x40011220  48 83 c7 10 b8 00 12 01 40 ff e0 00 00 00 00 00  H.......@.......
0x40011230  00 00 00 00 e8 c7 ef fe ff 08 f8 34 e0 55 55 55  ...........4.UUU
0x40011240  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
* Assertion: should not be reached at unwind.c:664
```
Backport of #11888.
/cc @BrzVlad
=> [2018-08] [exceptions] Verbose logging for cfa_reg assertion

packaging/MacSDK/sqlite.py
Bump Mac bundle from SQLite 3.9.2 to 3.26.0
=> Bump to latest SQLite for Mac bundle

mcs/class/System.Net.Http/System.Net.Http/HttpRequestMessage.cs, sdks/wasm/tests/browser/HttpTestSuite.cs, sdks/wasm/tests/browser/http-spec.js
Relax HttpMessageRequest url scheme validation for wasm so that urls with a blob scheme make it to the host backend. Fixes #11681
note: the browser tests fail when running chrome 71 in headless mode, they work in chrome 70 and 72
=> Allow urls with a blob scheme to pass validation in WASM

mcs/class/corlib/Test/System/TypedReferenceTest.cs
The sdks/wasm run-all-corlib target currently aborts in the TypedReferenceTest fixture. Skip it in that case by adding it to the NotWasm category.
=> Skip TypedReferenceTest fixture for WASM as it causes a runtime abort

mcs/class/corlib/Test/System.Reflection/ParameterInfoTest.cs, mcs/class/referencesource/mscorlib/system/attribute.cs
Fixes https://github.com/mono/mono/issues/12069
Backport of #12090.
=> [2018-12] Fix IndexOutOfRangeException in MethodInfo.ReturnParameter.IsDefined(type)

mcs/class/corlib/Test/System.Reflection/ParameterInfoTest.cs, mcs/class/referencesource/mscorlib/system/attribute.cs
Fixes #12069
Backport of #12090.
=> [2018-10] Fix IndexOutOfRangeException in MethodInfo.ReturnParameter.IsDefined(type)

scripts/ci/run-jenkins.sh, sdks/builds/ios.mk, sdks/versions.mk
Forward port of https://github.com/mono/mono/pull/10139
Needed for `arm64_32` (https://github.com/mono/mono/pull/11691): We still need to build AOT compilers that are 32bit, which is only possible with Xcode9. However, `arm64_32` needs Xcode10.
=> [sdks] Add a XCODE32_DIR make variable and use it to compile the 32 bit cross compilers.

packaging/MacSDK/sqlite.py
Bump Mac bundle from SQLite 3.9.2 to 3.26.0
Backport of #12118.
=> [2018-10] Bump to latest SQLite for Mac bundle

packaging/MacSDK/sqlite.py
Bump Mac bundle from SQLite 3.9.2 to 3.26.0
Backport of #12118.
=> [2018-08] Bump to latest SQLite for Mac bundle

packaging/MacSDK/sqlite.py
Bump Mac bundle from SQLite 3.9.2 to 3.26.0
Backport of #12118.
=> [2018-12] Bump to latest SQLite for Mac bundle

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridView.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ListView.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/StatusBar.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/TabControl.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ToolBar.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStrip.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStripTextBox.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/TreeView.cs
I noticed that some controls do not dispose tooltips and timers. Depending on the underlying implementation these may use native resources. Therefore I'd suggest to dispose these with the parent control to not rely on the garbage collector to eventually release the resources.
Additionally, in the case of `ToolStrip.cs` `CloseToolTip` would first create the objects before turning them off.
=> Dispose tooltips

mcs/class/System.Windows.Forms/System.Windows.Forms.Layout/TableLayout.cs
Fixes issue #8922. The flow layout code specifies `int.MaxValue` as width in `GetPreferredSize` call, which the table layout didn't handle properly and tried to use all the available space.
Relevant WinForms open source code that implements the same behavior:
https://github.com/dotnet/winforms/blob/e5606060fa95bdb40af9ddeceb7bea81535de291/src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs#L183-L188
https://github.com/dotnet/winforms/blob/e5606060fa95bdb40af9ddeceb7bea81535de291/src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs#L700-L702
=> System.Windows.Forms: Fix incorrect layout for table layout nested in flow layout

mcs/class/System.Net.Http/CFNetworkHandler.cs
PS: This fix should be ported to 2018-08, 2018-10 and 2018-12.
=> [Network] Fix CVE 2018-8292 on Mac OS X.

mcs/class/System.Windows.Forms/System.Windows.Forms.Layout/TableLayout.cs
Fixes issue #8922. The flow layout code specifies `int.MaxValue` as width in `GetPreferredSize` call, which the table layout didn't handle properly and tried to use all the available space.
Relevant WinForms open source code that implements the same behavior:
https://github.com/dotnet/winforms/blob/e5606060fa95bdb40af9ddeceb7bea81535de291/src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs#L183-L188
https://github.com/dotnet/winforms/blob/e5606060fa95bdb40af9ddeceb7bea81535de291/src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs#L700-L702
Backport of #12161.
/cc @marek-safar @filipnavara
=> [2018-10] System.Windows.Forms: Fix incorrect layout for table layout nested in flow layout

mcs/class/System.Windows.Forms/System.Windows.Forms.Layout/TableLayout.cs
Fixes issue #8922. The flow layout code specifies `int.MaxValue` as width in `GetPreferredSize` call, which the table layout didn't handle properly and tried to use all the available space.
Relevant WinForms open source code that implements the same behavior:
https://github.com/dotnet/winforms/blob/e5606060fa95bdb40af9ddeceb7bea81535de291/src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs#L183-L188
https://github.com/dotnet/winforms/blob/e5606060fa95bdb40af9ddeceb7bea81535de291/src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs#L700-L702
Backport of #12161.
/cc @marek-safar @filipnavara
=> [2018-12] System.Windows.Forms: Fix incorrect layout for table layout nested in flow layout

mono/eglib/gerror.c, mono/metadata/boehm-gc.c, mono/metadata/cominterop.c, mono/metadata/cominterop.h, mono/metadata/gc-internals.h, mono/metadata/handle.h, mono/metadata/icall-decl.h, mono/metadata/icall-def.h, mono/metadata/icall-table.c, mono/metadata/icall-table.h, mono/metadata/icall.c, mono/metadata/marshal-ilgen.c, mono/metadata/marshal-internals.h, mono/metadata/marshal-windows.c, mono/metadata/marshal.c, mono/metadata/marshal.h, mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/remoting.c, mono/metadata/sgen-mono-ilgen.c, mono/mini/interp/interp.c, mono/mini/method-to-ir.c
[Coop] Mostly convert 30+ icalls used via register_icall.
And infrastructure to support that.
The infrastructure is not as ideal as it could be.
In future the C preprocessor wrappers should be marshal-ilgen wrappers,
so the handles are more efficiently created.
Some of the conversion is incomplete and just goes back to raw pointers,
but mostly it is good.
Some of the conversion is by replacing previously manual conversion
with more automatic conversion, but most of it is new.
Some is embedding API, not JIT icalls.
=> [Coop] Mostly convert 30+ JIT icalls (and embedding API).

mcs/class/Mono.Debugger.Soft/Test/dtest.cs
When going to https://jenkins.mono-project.com/job/test-mono-pull-request-arm64/8921/testReport/junit/(root)/DebuggerTests/StackTraceInNative/ for example, we have no idea why the underlying process has exited. To figure it out, we need to go to https://jenkins.mono-project.com/job/test-mono-pull-request-arm64/8921/parsed_console/log_content.html#WARNING1 and scroll back up to where the test was executed to find out the debuggee process crashed with an assertion.
This was fixed by redirecting the StandardOutput and StandardError of the debuggee process in the Mono.Debugger.Soft test suite.
Fixes #7741
=> [Debugger] Redirecting the StandardOutput and StandardError

mono/metadata/marshal-ilgen.c, mono/mini/aot-compiler.c, mono/mini/mini-amd64.c, mono/mini/mini-arm.c, mono/mini/mini-arm64.c, mono/mini/mini-runtime.c, mono/mini/mini-s390x.c, mono/mini/mini-x86.c, mono/mini/mini.c, mono/mini/mini.h
Always emit safepoints and blocking transitions on all targets except WASM.
Addresses #11765.
---
This is an alternative to #11833 which was over-engineered.  The rationale is that we should always emit the machinery at compile time and just ignore it at runtime if the host suspend policy says so.
=> [coop] Always emit safepoints and blocking transitions, except on WASM

sdks/wasm/tests/browser/.gitignore, sdks/wasm/tests/browser/karma.conf.js, sdks/wasm/tests/browser/package.json
- This will download the most recent version of headless to use.
- Add junit-reporter to output a tests output file to be used for jenkins CI in the future.
=> [wasm] Add puppeteer to the browser tests node packages.

mcs/class/System.Web/System.Web.Caching/Cache.cs, mcs/class/System.Web/System.Web.Caching/CacheItemLRU.cs
System.Web.Caching.CacheItemLRU.this[string].get modifies LRU list so it
must be called under write lock. Cache.GetKeyLastChange violates this
constraint by acquiring only a read lock.
Fixes #12218
=> Fix data race in System.Web.Caching by using appropriate lock level

mono/mini/jit-icalls.c, mono/mini/jit-icalls.h, mono/mini/mini-runtime.c
instead of each function twice.
Elsewhere there is single instancing based on function address
and registering the same function twice breaks things.
What breaks is that due to the single instancing, based on address, the second name is skipped, whatever happens to be second in hash order. Sometimes that is ok, sometimes not.
=> Register two separate functions for mono_fconv_u4 and mono_fconv_u8

mono/mini/mini-posix.c, mono/mini/mini-runtime.c, mono/mini/mini.h, mono/mini/unwind.c, mono/utils/mono-logger-internals.h, mono/utils/mono-logger.c
Historically very common and hard to reproduce assertion, which, in some cases, could be fixed just from this logging. Log example :
```
Unset cfa_reg in method <0x40011220 - (null) trampoline>. Memory around ip (0x40011220):
0x40011210  41 89 07 4c 8b 3c 24 48 83 c4 08 c3 00 00 00 00  A..L.<$H........
0x40011220  48 83 c7 10 b8 00 12 01 40 ff e0 00 00 00 00 00  H.......@.......
0x40011230  00 00 00 00 e8 c7 ef fe ff 08 f8 34 e0 55 55 55  ...........4.UUU
0x40011240  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
* Assertion: should not be reached at unwind.c:664
```
Backport of #11888.
/cc @BrzVlad
=> [2018-10] [exceptions] Verbose logging for cfa_reg assertion

mono/metadata/cominterop.c, mono/metadata/icall-def.h, mono/metadata/icall-table.h, mono/metadata/reflection-internals.h, mono/metadata/reflection.c, mono/metadata/remoting.c, mono/metadata/string-icalls.c
mostly into mono_type_from_handle.
However keep them separate for registration/patching sake, since
will error if register twice, else need to arrange to register once.
=> [Coop] Convert and consolidate {remoting,cominterop}type_from_handle.

sdks/wasm/packager.cs
Fixes issue: https://github.com/mono/mono/issues/11856
=> [wasm] Add support to find the wasm framework libraries.

mono/metadata/icall.c, mono/mini/aot-runtime.h, mono/mini/jit-icalls.c, mono/mini/jit-icalls.h, mono/mini/method-to-ir.c, mono/mini/mini-amd64.c, mono/mini/mini-amd64.h, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini.c, mono/mini/mini.h, mono/tests/Makefile.am, mono/tests/array-12193.cs
This fixes https://github.com/mono/mono/issues/12193.
This is alternative to https://github.com/mono/mono/pull/12200.
They are both pretty good approaches.
12200 uncovered a hash order dependency which should be fixed either way.
=> Change array construction with rank>4 to use not use varargs -- localalloc.

mcs/class/System.Net.Http/CFNetworkHandler.cs
PS: This fix should be ported to 2018-08, 2018-10 and 2018-12.
Backport of #12047.
=> [2018-08] [Network] Fix CVE 2018-8292 on Mac OS X.

mono/mini/ee.h, mono/mini/interp-stubs.c, mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c, mono/mini/mini-exceptions.c, mono/tests/Makefile.am, mono/tests/exception21.cs
During EH, we can have the same frame twice on the stack, the original one and when invoking clauses in the same frame from EH. When having a resume state, we need to check if we should catch it in the current frame, or the original.
=> [interp] Fix resuming into interp frame during EH

mcs/class/System.Net.Http/CFNetworkHandler.cs
PS: This fix should be ported to 2018-08, 2018-10 and 2018-12.
Backport of #12047.
=> [2018-10] [Network] Fix CVE 2018-8292 on Mac OS X.

mcs/class/System.Net.Http/CFNetworkHandler.cs
PS: This fix should be ported to 2018-08, 2018-10 and 2018-12.
Backport of #12047.
=> [2018-12] [Network] Fix CVE 2018-8292 on Mac OS X.

mono/mini/driver.c, mono/utils/mono-state.c, mono/utils/mono-threads-coop.c, mono/utils/mono-threads-coop.h
- mono_threads_suspend_policy_name
- mono_threads_suspend_policy_are_safepoints_enabled
- mono_threads_suspend_policy_is_multiphase_stw_enabled
- mono_threads_suspend_policy_is_blocking_transition_enabled
The normal accessors (mono_threads_are_safepoints_enabled, etc) just apply the
policy acessors to the current policy
=> [coop] Add high level suspend policy accessors

configure.ac
Apparently, on old versions of Autoconf, a AC_TRY_COMPILE block with an empty action-if-true block, like:
```
if test x$fpabi = xauto; then
AC_TRY_COMPILE([], [
#ifdef __riscv_float_abi_double
#error "double"
#endif
], [
], [
fpabi=double
])
fi
```
emits invalid shell code, like:
```
(exit $ac_status); } && {
test -z "$ac_c_werror_flag" ||
test ! -s conftest.err
} && test -s conftest.$ac_objext; then
else
```
`else` immediately after `then` is not valid.
This construct is fine on newer versions, where `then :` is used, which does not count as invalid.
Even though we're not building for CentOS 6 RISC-V, the invalid shell causes the configure script to fail entirely, e.g. https://jenkins.mono-project.com/view/Releases/job/ng-release-generate-rpm-packages/963/execution/node/142/log/
Add a …
=> Add explicit no-op to RISC-V FPU detection, to fix old Autoconf (RHEL 6)

sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets
- The "WasmLinkAssemblies" task could not be loaded from the assembly
=> [wasm] Fix build targets errors

mcs/class/corlib/Test/System.IO/DriveInfoTest.cs
All fixed drives are not guaranteed to be ready
Fixes https://github.com/mono/mono/issues/11960
Backport of #12296.
/cc @alexischr
=> [2018-12] [tests] Remove an invalid assertion on System.IO.DriveInfo

mcs/class/corlib/Test/System.IO/DriveInfoTest.cs
All fixed drives are not guaranteed to be ready
Fixes https://github.com/mono/mono/issues/11960
Backport of #12296.
/cc @alexischr
=> [2018-10] [tests] Remove an invalid assertion on System.IO.DriveInfo

llvm/build_llvm_config.sh, mono/mini/Makefile.am.in, sdks/builds/wasm.mk
(This has nothing to do with --enable-cxx.  This is about our LLVM .cpp files).
Explicitly set the linker for libmini.  The issue is that the automatic
linker selection (See
https://www.gnu.org/software/automake/manual/html_node/How-the-Linker-is-Chosen.html)
looks at all the _SOURCES for a target, even those that are only
conditionally added, even if the condition is false.  So because we sometimes
build mini-llvm-cpp.cpp we always get the c++ linker.  But that's not what we
want.
The goal is:
- if there's any C++ code included into mono (either the shared lib or a
program) that needs the C++ runtime library, ensure that we link using the C++
linker.  This was already true, we just need to make sure it stays true.
- if mono is built in such a way that it has no C++ code in it (that needs …
=> [mini] Use C++ linker iff building C++ that needs the C++ runtime

mono/utils/mono-threads-coop.c, mono/utils/mono-threads-coop.h
It was never documented and it is not as useful now with a matured hybrid
suspend.
If `MONO_ENABLE_BLOCKING_TRANSITION` is set, and mono is otherwise configured to use
preemptive suspend, the thread state machinery would perform RUNNING->BLOCKING
transitions (ie: `MONO_ENTER_GC_SAFE` and friends would be more than no-ops), but
still preemptively suspend every thread.  This was useful for testing the
thread transitions separately from the coop suspend details.
=> [coop] Drop support for MONO_ENABLE_BLOCKING_TRANSITION env var

scripts/ci/run-jenkins.sh, sdks/wasm/package.json
Re-enables the chakra tests now that the upstream jsvu issue was fixed.
Fixes https://github.com/mono/mono/issues/12331
=> [wasm][ci] Re-enable chakra tests

mcs/class/Mono.Debugger.Soft/Test/dtest.cs
Changing the test behavior as discussed with Ludovic, because we already have knowledge about the unreliability of the crash reporter and the test is not about it.
So if in 10 times at least one of them works for now it's good.
Fixes #11385
=> [Debugger] Crash test

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/metadata/seq-points-data.h, mono/mini/debugger-engine.c, mono/mini/interp/transform.c, mono/mini/method-to-ir.c, mono/mini/mini.h, mono/mini/seq-points.c
Backport of #12114
The problem was in this line:
ss_nested_with_two_args(ss_nested_arg (), ss_nested_arg ());
The first step_into works correctly entering in the ss_nested_arg method, but the second one doesn't work.
The problem was because this flag MONO_SEQ_POINT_FLAG_NONEMPTY_STACK was set, so the debugger don't consider that it was a possible break.
The solution of the issue was create another flag to identify nested calls and ignore the  MONO_SEQ_POINT_FLAG_NONEMPTY_STACK.
2 new tests were added to test other nested calls.
=> [2018-10] [debugger][backport] Fix test ShouldCorrectlyStepOverOnExitFromArgsAfterStepInMethodParameter (#12114)

mono/mini/mini-exceptions.c, mono/mini/mixed.cs, mono/tests/Makefile.am
We might need to adjust the ip in the same fashion when normally resuming to catch handler.
In the example from the testcase, we have these transitions : ... -> interp_frame -> jit -> eh1 -> interp_frame -> eh2. When eh1 unwinds to call the finally clause from interp_frame it also pops all other lmf entries until there. This means that eh2 thinks it was called directly from the interp_frame (as it would happen with the jit), but in this case there are still the jit frames in the middle. Eh2 doesn't know how to resume over the jit frames, it will just set the resume state to the interp_frame and eh1 will do the resuming over the jitted frames, after run_finally returns gracefully. If the exception were to be handled by frames parent to interp_frame and there are also pushed contexts on the …
=> [interp] Fix resuming into interp when finally throws exception

mono/utils/mono-state.c
According to @akoeplinger we are seeing a failure on CI:
```
mono-state.c:631:48: error: use of undeclared identifier 'LLVM_API_VERSION'
20:28:52         mono_state_writer_printf (writer, "\"%d\"\n", LLVM_API_VERSION);
```
I've removed that here. 
Note that this is the last item in the JSON list, so we have to preserve the lack of a trailing comma. That's why Github renders this diff like so.
=> [crash] Remove missing LLVM_API_SUPPORT symbol usage

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
Debugger crashes when there is a generic struct with a field that is an enumerator
Example: files.get_Current().Key
A unit test that reproduces this crash was added too.
Fixes #10735
=> [Debugger] Fix crash when there is a generic struct with a field that is an enumerator.

mcs/build/Makefile, mcs/build/common/.gitignore, mcs/build/common/sourcelink.json.in, mcs/build/library.make, msvc/scripts/genproj.cs
Source Link allows IDEs/debuggers to retrieve a source file from a remote location like GitHub when the local file isn't available.
Specification: https://github.com/dotnet/designs/blob/e55c517a1e7f8dc35b092397058029531209d610/accepted/diagnostics/source-link.md
For now we only embed info about mono, cecil, corefx and corert since that covers 99% of what you usually want to debug and doesn't need fancy logic that reads git submodules and figures out their URLs.
Should enable use cases like https://twitter.com/jlaban/status/1084248087802060801 (/cc @jeromelaban)
=> [bcl] Embed Source Link information

configure.ac, mono/utils/jemalloc/Makefile.am
In the process of diagnosing 
https://github.com/mono/mono/pull/12125
and
https://github.com/mono/mono/pull/12387
I needed jemalloc to be fixed because instruments was too heavyweight and I needed the memory assertions (--enable-fill).
This fixes the build with --enable-jemalloc.
=> [runtime] Fix jemalloc support

mcs/class/Mono.Debugger.Soft/Makefile, mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
Debugger failure when a method is called in watches and any field of the Class has the type of the field different of the value of the field because the assign was done in an unsafe way like this:
Now the datatypes check are only executed when it's not inside an invoke method.
_pinnable = Unsafe.As<Pinnable<T>>(array);
A unit test that reproduces the issue was created either.
Fixes #12374
=> [Debugger] Debugger failure when field content is assigned by an unsafe value

mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/12344
=> [2018-12] [runtime] Fix integer overflow when copying array

mono/mini/interp/interp.c
We throw exception directly from child frame if the transform phase fails.
=> [interp] Remove unreachable code

mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/12344
Backport of #12407.
/cc @BrzVlad
=> [2018-10] [runtime] Fix integer overflow when copying array

mono/mini/exceptions-amd64.c, mono/mini/exceptions-x86.c, mono/mini/mini-amd64.h, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini-windows.c, mono/mini/mini-x86.h, mono/utils/mono-signal-handler.h
Store handled status in local that is passed into
handler rather than a single thread local value
which can be overwritten in case of re-entrance.
I encountered this in following scenario:
```
try {
// cause null reference exception
} finally {
// cause a structure exception that mono does not handle, for example call OutputDebugString
}
```
The above caused a problem as:
1. Mono is in the middle of processing an exception it will handle, so previous thread local variable `mono_win_chained_exception_needs_run` is `FALSE`
2. Finally clauses are called during structured exception handling
3. Benign structured exception is triggered in finally clause (pinvoke `OutputDebugString` without debugger attached). This causes an exception mono doesn't want to handle but other handler will.
4. In …
=> Fix re-entrant structured exception handling

mcs/class/corlib/System.Threading/Thread.cs, mono/metadata/object-internals.h, mono/metadata/threads-types.h, mono/metadata/threads.c
Backport #12391 to `2018-10`
---
Reverts a29ad08d005671163e0c4b1f4d7c92a3d9e8df71 (#9914)
The basic problem we want to solve is the following:
1. All access to InternalThread:state must be protected by the
InternalThread:synch_cs mutex
2. We must destroy the mutex when we are done with the thread.
3. We don't know which happens later - detaching the machine thread or
finalizing its InternalThread managed object.
The solution is to replace InternalThread:synch_cs by InternalThread:longlived
which is a refcounted struct that holds the synch_cs.  The refcount starts out
at 2 when the thread is attached to the runtime and when we create the managed
InternalThread object that represents it.
Both detaching and finalizing the managed object will decrement the refounct,
and whichever one happens …
=> [2018-10] [threads] Use refcounts for coordinating finalization and detaching

mcs/class/corlib/System.Threading/Thread.cs, mono/metadata/object-internals.h, mono/metadata/threads-types.h, mono/metadata/threads.c
Reverts a29ad08d005671163e0c4b1f4d7c92a3d9e8df71 (#9914)
The basic problem we want to solve is the following:
1. All access to `InternalThread:state` must be protected by the
`InternalThread:synch_cs` mutex
2. We must destroy the mutex when we are done with the thread.
3. We don't know which happens later - detaching the machine thread or
finalizing its `InternalThread` managed object.
The solution is to replace `InternalThread:synch_cs` by `InternalThread:longlived`
which is a refcounted struct that holds the `synch_cs`.  The refcount starts out
at 2 when the thread is attached to the runtime and when we create the managed
`InternalThread` object that represents it.
Both detaching and finalizing the managed object will decrement the refounct,
and whichever one happens last will be …
=> [2018-12] [threads] Use refcounts for coordinating finalization and detaching

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
Debugger crashes when there is a generic struct with a field that is an enumerator
Example: files.get_Current().Key
A unit test that reproduces this crash was added too.
Fixes #10735
Backport https://github.com/mono/mono/pull/12368
=> [2018-08][debugger][backport] Fix crash when there is a generic struct with a field that is an enumerator

mono/mini/llvm-jit.h
This re-enables the Linux JIT as suggested in https://github.com/mono/mono/issues/12030
=> [mini] re-enable LLVM for Linux JIT

sdks/wasm/Makefile, sdks/wasm/framework/.gitignore, sdks/wasm/framework/src/WebAssembly.Bindings/LinkDescriptor/WebAssembly.Bindings.xml, sdks/wasm/framework/src/WebAssembly.Bindings/WebAssembly.Bindings.csproj, sdks/wasm/framework/src/WebAssembly.Net.Http/LinkDescriptor/WebAssembly.Net.Http.xml, sdks/wasm/framework/src/WebAssembly.Net.Http/WebAssembly.Net.Http.csproj, sdks/wasm/sdk/Mono.WebAssembly.Build/WasmLinkAssemblies.cs, sdks/wasm/sdk/WebAssembly.Net.Http.Framework/WebAssembly.Net.Http.csproj
- Add linker xml descriptor to WebAssembly.Bindings and WebAssembly.Net.Http
- The XML linker descriptor will keep the full assembly for these assemblies during link.
- Fix Link Assemblies command line.
- Miscellaneous fixes for how the assemblies are linked whether they are framework or facades.
- Add the Facades directory to the resolve paths.
=> [wasm] Build target fixes

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
Debugger crashes when there is a generic struct with a field that is an enumerator
Example: files.get_Current().Key
A unit test that reproduces this crash was added too.
Fixes #10735
Backport #12368
=> [2018-10][debugger][backport] Fix crash when there is a generic struct with a field that is an enumerator

configure.ac, mono/metadata/icall.c, mono/metadata/mono-config.c
Previously we were defining the build configuration dir on android. This directory exists on the host and not the target. 
It often appears in places like https://github.com/mono/mono/blob/master/mono/metadata/mono-config.c#L647 which causes us to probe files that will never exist.
=> [runtime] Don't define build config dir on android

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
Debugger crashes when there is a generic struct with a field that is an enumerator
Example: files.get_Current().Key
A unit test that reproduces this crash was added too.
Fixes #10735
Backport #12368
/cc @thaystg
=> [2018-12] [debugger][backport] Fix crash when there is a generic struct with a field that is an enumerator

mono/mini/mini-arm64.h
Backport of #12443.
/cc @lewurm
=> [2018-10] [arm64_32] use emulate OPs so it works with bitcode compiled code for armv7k

tools/offsets-tool/MonoAotOffsetsDumper.cs
The latest Android NDK releases no longer ship with per-platform C headers.
Instead they ship with a set of unified headers and require the presence of the
`__ANDROID_API__` macro in order to select the target platform.
The AOT offset dumper doesn't support this new layout and this commit changes
that by adding support for the unified headers (without removing support for the
older NDKs) thus fixing the following error when trying to dump the offsets with
newer NDK:
Processing triple: aarch64-v8a-linux-android
Error parsing '[...]/mono/mono/metadata/metadata-cross-helpers.c'
[...]/mono/mono/metadata/metadata-cross-helpers.c(5,10): fatal: 'stdio.h' file not found
Error parsing '[...]/mono/mono/mini/mini-cross-helpers.c'
[...]/mono/mono/mini/mini-cross-helpers.c(7,10): fatal: 'stdio.h' file …
=> [Android,AOT] Support dumping AOT offsets with Android NDK r17+

mcs/class/System.ComponentModel.Composition.4.5/src/ComponentModel/System/ComponentModel/Composition/ReflectionModel/ReflectionModelServices.cs
After .NET 4.5 .NET Framework has changed the System.ComponentModel.Composition ReflectionModelServices.IsExportFactoryImportDefinition to not throw.
Updating this to match the .NET Framework behavior.
Fixes #12461
=> Fixes https://github.com/mono/mono/issues/12461.

mcs/class/System.ComponentModel.Composition.4.5/src/ComponentModel/System/ComponentModel/Composition/ReflectionModel/ReflectionModelServices.cs
After .NET 4.5 .NET Framework has changed the System.ComponentModel.Composition ReflectionModelServices.IsExportFactoryImportDefinition to not throw.
Updating this to match the .NET Framework behavior.
Fixes #12461
Backport of #12462.
/cc @marek-safar @KirillOsenkov
=> [2018-10] Fixes https://github.com/mono/mono/issues/12461.

mcs/class/System.ComponentModel.Composition.4.5/src/ComponentModel/System/ComponentModel/Composition/ReflectionModel/ReflectionModelServices.cs
After .NET 4.5 .NET Framework has changed the System.ComponentModel.Composition ReflectionModelServices.IsExportFactoryImportDefinition to not throw.
Updating this to match the .NET Framework behavior.
Fixes #12461
Backport of #12462.
/cc @marek-safar @KirillOsenkov
=> [2018-12] Fixes https://github.com/mono/mono/issues/12461.

tools/offsets-tool/MonoAotOffsetsDumper.cs
Backport of: https://github.com/mono/mono/commit/eebe4b52857140ba9dea872c6249960273d222f2 from https://github.com/mono/mono/pull/12454
The latest Android NDK releases no longer ship with per-platform C headers.
Instead they ship with a set of unified headers and require the presence of the
`__ANDROID_API__` macro in order to select the target platform.
The AOT offset dumper doesn't support this new layout and this commit changes
that by adding support for the unified headers (without removing support for the
older NDKs) thus fixing the following error when trying to dump the offsets with
newer NDK:
Processing triple: aarch64-v8a-linux-android
Error parsing '[...]/mono/mono/metadata/metadata-cross-helpers.c'
[...]/mono/mono/metadata/metadata-cross-helpers.c(5,10): fatal: 'stdio.h' file not …
=> [2018-10 Android,AOT] Support dumping AOT offsets with Android NDK r17+ (#12454)

mcs/class/System/System.IO.Compression/DeflateStream.cs, support/zlib-helper.c
DeflateStream now correctly handles exceptions thrown by it's inner stream and
rethrows them after returning from native code.
Fixes #12205.
=> [System.IO.Compression]: Correctly handle exceptions in inner stream.  #12205.

sdks/wasm/binding_support.js, sdks/wasm/framework/src/WebAssembly.Bindings/LinkDescriptor/WebAssembly.Bindings.xml
Internally the javascript bridge support uses `System.Delegate` and `System.Delegate.DynamicInvoke` to support delegate callbacks.  The linker, when executed over the assemblies, does not know about this code coverage and will strip out `System.Delegate.DynamicInvoke`.
To fix this:
- Add reference to `System.Delegate.DynamicInvoke` to the `WebAssembly.Bindings` linker xml file so the linker knows not to strip the code.
- Add detailed error messages in case something else goes wrong so the crash is not so cryptic.
=> [wasm] Fix crash with delegates.

mcs/class/System.ComponentModel.Composition.4.5/src/ComponentModel/System/ComponentModel/Composition/ReflectionModel/ReflectionModelServices.cs
After .NET 4.5 .NET Framework has changed the System.ComponentModel.Composition ReflectionModelServices.IsExportFactoryImportDefinition to not throw.
Updating this to match the .NET Framework behavior.
Fixes #12461
Backport of #12462.
/cc @marek-safar @KirillOsenkov
=> [2018-08] Fixes https://github.com/mono/mono/issues/12461.

mono/mini/mini-arm64.h
Backport of #12443.
/cc @lewurm
=> [2018-12] [arm64_32] use emulate OPs so it works with bitcode compiled code for armv7k

mono/mini/aot-runtime.c
These attempts result in a lot of attempts to access this (nonexistant) path on android during load
=> [runtime] Don't probe aot cache on android

mono/metadata/assembly-internals.h, mono/metadata/assembly.c, mono/metadata/security-core-clr.c, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
Use the MONO_ASSEMBLY_CORLIB_NAME define instead of hardcoding "mscorlib" everywhere.  If building for netcore, the define is set to "System.Private.CoreLib" instead.
In some circumstances, a string comparison against `assembly->aname.name` is used to check if something is in corelib.  In cases like that, instead use `mono_is_corlib_image (assembly->image)` instead.  (This introduces a dependency on mono_defaults.corlib being correctly initialized, so it's inappropriate for code that runs very early during startup.  Which I checked as best I could.)
This should fix every use of literal "mscorlib" in the runtime.
This does _not_ fix every use of literal "mscorlib.dll" in the runtime, partly because some of those uses are in the Framework-specific codepaths in the loader and it doesn't …
=> Don't hardcode "mscorlib" use MONO_ASSEMLBY_CORLIB_NAME or mono_is_corlib_image

mono/mini/aot-runtime.c
These attempts result in a lot of attempts to access this (nonexistant) path on android during load
Backport of #12058.
=> [2018-12] [runtime] Don\u0027t probe aot cache on android

mono/mini/aot-runtime.c
These attempts result in a lot of attempts to access this (nonexistant) path on android during load
Backport of #12058.
=> [2018-08] [runtime] Don\u0027t probe aot cache on android

mono/mini/aot-runtime.c
These attempts result in a lot of attempts to access this (nonexistant) path on android during load
Backport of #12058.
=> [2018-10] [runtime] Don\u0027t probe aot cache on android

sdks/wasm/docs/getting-started/sample.md
There would be newer build instruction with msbuild sdks but so far fix current readme.
=> [wasm] fix insufficient csc arguments in sample README

mono/metadata/class-init.c
Uninitialized slot values are -1, not 0.
For example GetHashCode could be in slot 0.
=> [class-init] Allow ghc_slot or finalize_slot == 0

mono/utils/mono-dl-posix.c
On android, the dlopen call will take around 1ms per AOT module we try to load. By not using dlopen with the existence check, we rely on a much slower dlopen check that happens later. I think they support dlopen of non-resolved names. 
This might break a few things if we don't use the full path to dlopen. If it does, we should probably add existence checks at the caller, but this will be an optimization that works everywhere.  
@jonpryor @grendello
=> [runtime] Don't try (slow) dlopen on android if it doesn't exist

configure.ac, mono/metadata/class-init.c, mono/metadata/object.c
1. For `--with-core=only`, disable AppDomains, SRE.Save and Remoting.
2. System.Private.CoreLib System.Array type has some constant fields - don't assert in the runtime that there are 0 fields - when initializing the array type.
3. Don't treat `AppDomainUnloadedException` specially in exception handling.  (And in particular, don't try to load AppDomainUnloadedException - it's not in System.Private.CoreLib.dll, it's in netstandard.dll, so it won't work).
=> [netcore] Small runtime changes

mono/metadata/assembly.c, mono/metadata/domain.c, mono/mini/main-core.c
Set up an assembly loader preload hook using `TRUSTED_PLATFORM_ASSEMBLIES` from `coreclr_initialize`.
The [.NET Core hosting API](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#step-3---prepare-runtime-properties) passes some properties down to MonoVM to initialize it.  The trusted platform assemblies list includes the full path of every assembly that the application depends on.
So we set up a preload hook for the mono assembly loader to check the name of any requested assembly against the list.
---
Also load the `System.Private.CoreLib` using the preload hook.
**NOTE**: This breaks the AOT compiler under `--with-core=only` since the main `mono` binary doesn't know anything about preload hooks and so it is unable to find a corlib to use.
---
(Minor)
Also comment …
=> [netcore] Assembly loader preload hook

sdks/builds/ios.mk
I lost that change during upstreaming 🙁
=> [ios] enable llvm for watch64_32 runtime

sdks/builds/ios.mk
I lost that change during upstreaming 🙁 
Backport of #12497.
/cc @lewurm
=> [2018-12] [ios] enable llvm for watch64_32 runtime

sdks/builds/ios.mk
I lost that change during upstreaming 🙁 
Backport of #12497.
/cc @lewurm
=> [2018-10] [ios] enable llvm for watch64_32 runtime

mono/utils/mono-dl-posix.c
On android, the dlopen call will take around 1ms per AOT module we try to load. By not using dlopen with the existence check, we rely on a much slower dlopen check that happens later. I think they support dlopen of non-resolved names. 
This might break a few things if we don't use the full path to dlopen. If it does, we should probably add existence checks at the caller, but this will be an optimization that works everywhere.  
@jonpryor @grendello 
Backport of #12074.
=> [2018-10] [runtime] Don\u0027t try (slow) dlopen on android if it doesn\u0027t exist

mcs/class/System/Test/System.ComponentModel/DefaultValueAttributeTest.cs, mcs/class/referencesource/System/compmod/system/componentmodel/TypeDescriptor.cs
Backport of https://github.com/mono/mono/pull/12412 to 2018-12 branch.
Requires https://github.com/mono/corefx/pull/238
Fixes https://github.com/mono/mono/issues/12362
=> [2018-12] Add TypeConverter fallback to DefaultValueAttribute

mono/utils/mono-dl-posix.c
On android, the dlopen call will take around 1ms per AOT module we try to load. By not using dlopen with the existence check, we rely on a much slower dlopen check that happens later. I think they support dlopen of non-resolved names. 
This might break a few things if we don't use the full path to dlopen. If it does, we should probably add existence checks at the caller, but this will be an optimization that works everywhere.  
@jonpryor @grendello 
Backport of #12074.
=> [2018-12] [runtime] Don\u0027t try (slow) dlopen on android if it doesn\u0027t exist

configure.ac
Currently we print out that we are "assuming yes" for the condition but we don't actually follow the "yes" action here: https://github.com/mono/mono/blob/1291c08c1d07b97ed7087d15f4eca2538bd5c24f/configure.ac#L2678-L2679
=> [configure] Small fix in sigaltstack() checking on cross-compiler case

mcs/class/System/Mono/SystemDependencyProvider.cs
Fix race condition in `SystemDependencyProvider.Initialize()`.
Fixes #12538.
Backport of #12541.
/cc @baulig
=> [2018-10] [System]: Fix race condition in `SystemDependencyProvider.Initialize()`.  #12538.

mcs/class/System/Mono/SystemDependencyProvider.cs
Fix race condition in `SystemDependencyProvider.Initialize()`.
Fixes #12538.
Backport of #12541.
/cc @baulig
=> [2018-08] [System]: Fix race condition in `SystemDependencyProvider.Initialize()`.  #12538.

mcs/class/System/Mono/SystemDependencyProvider.cs
Fix race condition in `SystemDependencyProvider.Initialize()`.
Fixes #12538.
Backport of #12541.
/cc @baulig
=> [2018-12] [System]: Fix race condition in `SystemDependencyProvider.Initialize()`.  #12538.

mono/metadata/assembly.c
Partly revert a change in https://github.com/mono/mono/pull/12478
CoreCLR treats `Assembly.Load (new AssemblyName ("System.Private.CoreLib.dll"))`
the same as `Assembly.Load (new AssemblyName ("System.Private.CoreLib"))`  (and
.NET Framework behaves likewise with "mscorlib.dll").
=> [netcore] Make `Assembly.Load (new AssemblyName (corlib_name + ".dll"))` work again

mono/sgen/sgen-alloc.c, mono/sgen/sgen-gc.c, mono/sgen/sgen-memory-governor.c, mono/sgen/sgen-memory-governor.h
Concurrent gc (mark / sweep) allows the heap to grow further, which is not what we want if we already exceeded the limit.
=> [sgen] Don't trigger concurrent collections if we exceed soft heap limit

mono/mini/aot-runtime.c, mono/mini/driver.c, mono/mini/mini-runtime.c
Fixes reported startup time issues with probing filesystem for native AOT code files on Android.
Backport of #12053.
=> [2018-12] [runtime] Add opt-out for AOT file probing with MONO_AOT_MODE_NONE

mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs
The sync APIs `SslStream.AuthenticateAsClient()` and `AuthenticateAsServer()` should not throw `AggregateException`.
Fixes #9418.
Backport of #12553.
/cc @baulig
=> [2018-10] [SslStream]: Flatten exceptions in sync `SslStream` APIs.

mono/sgen/sgen-alloc.c, mono/sgen/sgen-gc.c, mono/sgen/sgen-memory-governor.c, mono/sgen/sgen-memory-governor.h
Concurrent gc (mark / sweep) allows the heap to grow further, which is not what we want if we already exceeded the limit.
Backport of #12536.
/cc @BrzVlad
=> [2018-12] [sgen] Don\u0027t trigger concurrent collections if we exceed soft heap limit

mono/sgen/sgen-alloc.c, mono/sgen/sgen-gc.c, mono/sgen/sgen-memory-governor.c, mono/sgen/sgen-memory-governor.h
Concurrent gc (mark / sweep) allows the heap to grow further, which is not what we want if we already exceeded the limit.
Backport of #12536.
/cc @BrzVlad
=> [2018-10] [sgen] Don\u0027t trigger concurrent collections if we exceed soft heap limit

mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs
The sync APIs `SslStream.AuthenticateAsClient()` and `AuthenticateAsServer()` should not throw `AggregateException`.
Fixes #9418.
=> [SslStream]: Flatten exceptions in sync `SslStream` APIs.

mcs/class/System/System.Net.NetworkInformation/UnixIPGlobalProperties.cs
The values of the enum for the TcpState are different in Unix systems
than in .NET, so a function was added to convert between the two.
Fixes #6477
=> [Fix] GetActiveTcpConnections now returns correct state in unix

mono/mini/mini-posix.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini-wasm.c, mono/mini/mini-windows.c
Contributes to https://github.com/mono/mono/issues/12404
=> [runtime] cleanup around native crash info

configure.ac, mono/eglib/gfile-unix.c, mono/eglib/gspawn.c, mono/metadata/assembly.c, mono/metadata/file-mmap-posix.c, mono/metadata/icall.c, mono/metadata/mono-security.c, mono/metadata/w32file-unix.c, mono/metadata/w32process-unix-default.c, mono/metadata/w32socket-unix.c, mono/metadata/w32socket.c, mono/mini/main.c, mono/utils/dlmalloc.c, mono/utils/mono-dl-posix.c, mono/utils/mono-log-posix.c, mono/utils/mono-proclib.c, mono/utils/mono-threads-posix.c
Some of these functions aren't available on POSIX-compliant platforms that are not linux or OSX. This some checks for these functions. 
It also makes it easier to use DISABLE_SOCKETS, by adding an enable-minimal option for it.
=> [runtime] Guard usage of unix functions that aren't posix

mono/eglib/gpath.c
=> [2018-08] [eglib]: Fix memory leak in `g_find_program_in_path()`.  #11615.

mono/eglib/gpath.c
=> [2018-10] [eglib]: Fix memory leak in `g_find_program_in_path()`.  #11615.

mcs/class/System/ReferenceSources/AutoWebProxyScriptEngine.cs
This fixes `NullReferenceException` that was thrown if:
- `HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ProxyEnable` was set to true (1)
- but `HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ProxyServer` was set to null
Fixes #10030
=> Fix handling invalid Windows proxy config

configure.ac, mono/mini/Makefile.am.in, mono/mini/llvm-jit.cpp, mono/utils/mono-dl.c, mono/utils/mono-dl.h
Essentialy bypass automake's automatic linker selection based on _SOURCES file
extensions.
The issue:
1. Right now we need to use the C linker unless we're linking with LLVM which
needs C++.
2. Later when we start using C++ in Mono we will still want the C linker,
because we will use a subset of C++ that doesn't depend on the C++ runtime
library (because we don't want to break embedders that don't expect us to
use C++).
So in either case which linker we use is a decision that we want to make
independent of what the file extensions look like.
So we set MONO_CXXLD in configure.  If LLVM is enabled, we use $CXX, otherwise
$CC.
Then in mono/mini/Makefile.am.in we set CCLD and CXXLD to MONO_CXXLD.  So
whatever automake decides we're going to use the linker that we want.
This partly reverts …
=> [cxx] Set CXXLD and CCLD in configure

mcs/class/Mono.Debugger.Soft/Makefile, mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
Backport of #12394 
Debugger failure when a method is called in watChes and any field of the Class has the type of the field different of the value of the field because the assign was done in an unsafe way like this:
Now the datatypes check are not executed only when each field of the class is been checked before the invoke method..
_pinnable = Unsafe.As<Pinnable<T>>(array);
A unit test that reproduces the issue was created either.
Fixes #12374
=> [2018-12][debugger][backport] Debugger failure when field content is assigned by an unsafe value 

mcs/class/System.Core/linux_build_System.Core.dll.sources, mcs/class/System.Core/macos_build_System.Core.dll.sources
I missed this in my compiler server PRs. Without it, the compiler server won't be able to open pipes. (It already works in every other profile).
=> Fix pipes not being enabled in all relevant versions of the build profile

mcs/class/System/System.Net/HttpWebRequest.cs
`HttpWebRequest.RunWithTimeoutWorker()` needs to observe the worker task's exception
on timeout to prevent it from being thrown via the `TaskScheduler.UnobservedTaskException`
event.  Fixes #10488.
Backport of #10595.
/cc @baulig
=> [2018-04] [System]: Make sure `HttpWebRequest` observes exceptions on timeout.  #10488.

mono/metadata/threads.c
At the moment of a safepoint, the runtime can be holding the loader lock. Fixes gsharing-valuetype-layout.exe timeouts.
Backport of #10793.
/cc @lambdageek @BrzVlad
=> [2018-08] [coop] Fix deadlock when unwinding

mono/metadata/mono-config.c
Fix leak if mono_set_config_dir is called multiple times by freeing the
previously stored value.
=> Fix leak if mono_set_config_dir is called multiple times.

mono/metadata/assembly.c
Fix leak if mono_assembly_setrootdir is called multiple times by freeing the
previously stored value.
=> Fix leak if mono_assembly_setrootdir is called multiple times.

mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
When using --break. We need to have a breakpoint set from debugger in mono_break.
=> [interp] Add support for break on method entry

mono/metadata/w32file-win32.c, mono/metadata/w32socket-win32.c, mono/utils/mono-os-wait-win32.c, mono/utils/mono-os-wait.h, mono/utils/mono-threads-windows.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
Windows support to abort blocking system calls has been limited since several of the API's currently used are not using overlapped IO and since system handles are exposed to clients, can't be changed to always work with overlapped IO, even if support could be added in the future, at least for sockets.
In order to add support to abort socket waits,  https://github.com/mono/mono/commit/53af53ae5923ccb205ea8e0ebebdbe0c0ee5de88, did an attempt to implement alertable socket support on Windows, but the implementation was racy and assume that only one thread works against the same socket handle, something that regressed a couple of scenarios, like the one described in https://github.com/mono/mono/issues/12480.
This PR adds optional support to break blocking socket calls using a different …
=> Windows support to abort blocking system calls.

mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mcs/class/corlib/System.Reflection.Emit/AssemblyBuilder.cs
Preserve the ModuleBuilder.RuntimeResolve () method using a PreserveDependency attribute.
Remove nonexistent methods.
=> [corlib] Fix the linker descriptors for the SRE classes.

mono/metadata/marshal.c
Fixes dynamic-method-churn.exe timeouts, which was hanging on arm because the finalizer thread was hanging from taking too long to clear these hashtable entries.
=> [marshal] Optimize clearing of entries for method

bcl.sln, mcs/class/Facades/System.Drawing.Common/Facades_System.Drawing.Common.csproj, mcs/class/Facades/System.Drawing.Common/Makefile, mcs/class/Facades/System.Drawing.Common/TypeForwarders.cs, mcs/class/Mono.CSharp/Mono.CSharp.csproj
I basically copied it from 
https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/ref/System.Drawing.Common.cs
and
https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Primitives/ref/System.Drawing.Primitives.cs
Replaced all `{ }` and `throw null` with `throw new PNSE()`
Addresses https://devdiv.visualstudio.com/DevDiv/_workitems/edit/767471
Backport of #12705.
=> [2018-10] Fill System.Drawing facade with API stubs

bcl.sln, mcs/class/Facades/System.Drawing.Common/Facades_System.Drawing.Common.csproj, mcs/class/Facades/System.Drawing.Common/Makefile, mcs/class/Facades/System.Drawing.Common/TypeForwarders.cs, mcs/class/Mono.CSharp/Mono.CSharp.csproj
I basically copied it from 
https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/ref/System.Drawing.Common.cs
and
https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Primitives/ref/System.Drawing.Primitives.cs
Replaced all `{ }` and `throw null` with `throw new PNSE()`
Addresses https://devdiv.visualstudio.com/DevDiv/_workitems/edit/767471
Backport of #12705.
=> [2018-12] Fill System.Drawing facade with API stubs

mono/mini/mini-arm.c
When moving parameters for tailcall, first copy the parameters using ARMREG_IP and after that get destination in ARMREG_IP, then it's not necessary the PUSH and POP to SP nor the saved_ip_offset.
Fixes #11489
=> [Tailcall] [arm] [jit] Fix moving tailcall parameters.

mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/11965
Backport of #12704.
=> [2018-10] [arm/ios] workaround for faulty vcmp.f64 insn

mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/11965
=> [arm/ios] workaround for faulty vcmp.f64 insn

bcl.sln, mcs/class/Mono.CSharp/Mono.CSharp.csproj
Commit list for mono/corert:
* mono/corert@1b7d4a1e4 [Number] make double 0.0 cmp more portable (#30)
* mono/corert@c4ae51646 Update ISOWeek.cs
* mono/corert@7e8bf2382 fix ISOWeek for mcs
Diff: https://github.com/mono/corert/compare/0e5f123f6b1792bf19fe21143a6d668b6ce8f483...1b7d4a1e4bd79305905338827cc41eb8303364f0
=> [2018-12] Bump corert

mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/11965
Backport of #12704.
/cc @lewurm
=> [2018-08] [arm/ios] workaround for faulty vcmp.f64 insn

.gitmodules
Commit list for mono/corert:
* mono/corert@e229c9448 [Number] make double 0.0 cmp more portable (#30)
Diff: https://github.com/mono/corert/compare/6c9c4d9cffe2031acb788718646fbc013632c9ea...e229c9448cb262ceb230dfab64a8237140c1dc2d
=> [2018-08] Bump corert

mcs/class/System/Microsoft.CSharp/CSharpCodeGenerator.cs
`CSharpCodeGenerator` runs a compiler while redirecting its standard error and
standard output streams for further reporting. However, in doing that it fails
to read the standard output data completely and also fails to properly wait for
the standard error output to complete. Depending on environment it may lead to
the process using `CSharpCodeGenerator` hanging while the process has already
exited but there still is data to be read from standard output and standard
error.
This commit changes the code to not redirect standard output at all, as it
appears to be unused, and switches to implementation of reading standard error
that makes sure all the data is read before the process is closed.
The hope is that it may fix some of the timeouts/hangs we see on the
Xamarin.Android build bots as a …
=> [bcl] Fix possible deadlock race in CSharpCodeGenerator

bcl.sln, configure.ac, mcs/class/Makefile, mcs/class/Mono.Simd/Mono.Simd.csproj, mono/mini/Makefile.am.in, msvc/mono-sgen-msvc.bat, msvc/mono-sgen-msvc.sh, msvc/mono.vcxproj, msvc/run-msbuild.bat, msvc/run-msbuild.sh, runtime/mono-wrapper.in, scripts/ci/run-jenkins.sh, scripts/ci/run-test-winaot.sh
Add support for building Windows x64 fullaot version of winaot profile that can be run on CI. Initial changes also add execution of mini regression tests on CI. More tests will be added going forward and when having full pass rate.
Add support for building Windows x64 fullaot+llvm version of winaot profile that can be run on CI. Initial changes also add execution of mini regression tests on CI. More tests will be added going forward and when having full pass rate.
In order to get deterministic build results and working build on CI, we need to setup a correct build environment for the MSVC builds. Since MSVC build is currently run from cygwin, there are environment problems, both general but also in our CI environment, since we add cygwin bin folder to system path
(needed by Jenkins …
=> Add support for Windows x64 winaot, winaot_llvm builds/tests on CI.

mcs/class/System/Microsoft.CSharp/CSharpCodeGenerator.cs
`CSharpCodeGenerator` runs a compiler while redirecting its standard error and
standard output streams for further reporting. However, in doing that it fails
to read the standard output data completely and also fails to properly wait for
the standard error output to complete. Depending on environment it may lead to
the process using `CSharpCodeGenerator` hanging while the process has already
exited but there still is data to be read from standard output and standard
error.
This commit changes the code to an implementation of reading standard error and output
that makes sure all the data is read before the process is closed.
The hope is that it may fix some of the timeouts/hangs we see on the
Xamarin.Android build bots as a portion of them hangs in test that use the
code generator. …
=> [2018-12] [bcl] Fix possible deadlock race in CSharpCodeGenerator

mcs/class/System/Microsoft.CSharp/CSharpCodeGenerator.cs
`CSharpCodeGenerator` runs a compiler while redirecting its standard error and
standard output streams for further reporting. However, in doing that it fails
to read the standard output data completely and also fails to properly wait for
the standard error output to complete. Depending on environment it may lead to
the process using `CSharpCodeGenerator` hanging while the process has already
exited but there still is data to be read from standard output and standard
error.
This commit changes the code to an implementation of reading standard error and output
that makes sure all the data is read before the process is closed.
The hope is that it may fix some of the timeouts/hangs we see on the
Xamarin.Android build bots as a portion of them hangs in test that use the
code generator. …
=> [2018-10] [bcl] Fix possible deadlock race in CSharpCodeGenerator

mono/mini/mini-arm.c
When moving parameters for tailcall, first copy the parameters using ARMREG_IP and after that get destination in ARMREG_IP, then it's not necessary the PUSH and POP to SP nor the saved_ip_offset.
Fixes #11489
Backport of #12701.
/cc @lewurm @thaystg
=> [2018-12] [Tailcall] [arm] [jit] Fix moving tailcall parameters.

mcs/class/corlib/System.Diagnostics/StackTrace.cs, mcs/class/corlib/Test/System.Diagnostics/StackFrameTest.cs
StackTrace.GetFrames can return additional frames recursively extracting them from captured traces.
It results in too many redundant frames for async methods. 
To limit a number of the additional frames I removed recursive calls and used frames from the first level of captured traces only.
For the sample from https://github.com/mono/mono/issues/12688 it becomes `25` instead of 56.
It kind of correlates with NetFX/NetCore number (`17`): in this case Mono gives two more frames for `Throw ` and `ValidateEnd` methods.
`Stack.FrameCount()` and `Stack.GetFrames().Length` still show different numbers.
=> [corlib] Avoid recursive extracting redundant frames from captured traces in StackTrace.GetFrames

mono/utils/mono-state.c
Backport of #12737.
/cc @luhenry @leculver
=> [2018-08] Add back missing stack frames to mono MERP reports

mono/utils/mono-state.c
Backport of #12737.
/cc @luhenry @leculver
=> [2018-10] Add back missing stack frames to mono MERP reports

mono/utils/mono-state.c
Backport of #12737.
/cc @luhenry @leculver
=> [2018-12] Add back missing stack frames to mono MERP reports

mono/utils/mono-state.c
=> Add back missing stack frames to mono MERP reports

mono/metadata/coree.c, mono/metadata/exception.c, mono/metadata/exception.h, mono/metadata/image-internals.h, mono/metadata/image.c, mono/metadata/image.h, mono/metadata/mono-security.c, mono/metadata/object.c, mono/metadata/w32socket.c
Addresses #12724 
Note this is against 2018-10.  Forward ports to 2018-12 and master after this one.
=> [2018-10][runtime] Switch to GC Unsafe in a few more external API functions

mcs/class/corlib/System.Diagnostics/StackTrace.cs, mcs/class/corlib/Test/System.Diagnostics/StackFrameTest.cs
Backport of https://github.com/mono/mono/pull/12729 to 2018-12 branch.
Related issue: https://github.com/mono/mono/issues/12688
=> [2018-12] [corlib] Avoid recursive extracting redundant frames from captured traces in StackTrace.GetFrames

mcs/class/corlib/System.Diagnostics/StackTrace.cs, mcs/class/corlib/Test/System.Diagnostics/StackFrameTest.cs
Backport of https://github.com/mono/mono/pull/12729 to 2018-10 branch.
Related issue: https://github.com/mono/mono/issues/12688
=> [2018-10] [corlib] Avoid recursive extracting redundant frames from captured traces in StackTrace.GetFrames

mcs/class/corlib/System.Diagnostics/StackTrace.cs, mcs/class/corlib/Test/System.Diagnostics/StackFrameTest.cs
Backport of https://github.com/mono/mono/pull/12729 to 2018-08 branch.
Related issue: https://github.com/mono/mono/issues/12688
=> [2018-08] [corlib] Avoid recursive extracting redundant frames from captured traces in StackTrace.GetFrames

bcl.sln, mcs/class/Mono.CSharp/Mono.CSharp.csproj
Commit list for mono/corert:
* mono/corert@1b7d4a1e4 [Number] make double 0.0 cmp more portable (#30)
* mono/corert@c4ae51646 Update ISOWeek.cs
* mono/corert@7e8bf2382 fix ISOWeek for mcs
* mono/corert@0e5f123f6 [corlib] Import System.IO.Stream/BufferedStream from CoreFX (#26)
Diff: https://github.com/mono/corert/compare/b6a822b7424dab39eee81f0c08160f996c9e9e27...1b7d4a1e4bd79305905338827cc41eb8303364f0
=> [2018-10] Bump corert

mcs/tools/xbuild/LoggerInfo.cs
LoadFile lost assembly load-context. If the logger assembly has any dependencies placed in same folder logger can't load it. Main.cs using LoadFrom to load assembly but assembly already loaded in the cache after GetLoggerTypeName.
It is a regression in previous version mono(I'm not sure about certain version) didn't use cache in this case. We have some customer reports from Linux distro without msbuild(like Arch). They have a problem after  mono upgrade.
=> Use LoadFrom instead LoadFile for load logger type.

mono/profiler/aot.c
Without this patch, Mono crashes while writing AOT profiling data at shutdown (when instructed to do so via `--profile=aot:output=out.aotprof`) if any of the sampled methods belong to a dynamic image, which doesn't have a GUID.
This happens with e.g. the `DynamicProxyGenAssembly2` image:
> DynamicProxyGenAssembly2 is a temporary assembly built by mocking systems that use CastleProxy like Moq or NSubsitute. It is generated when the mock is needed and disposed of after the tests are finished.
(cf. https://stackoverflow.com/a/17179923)
=> [profiler] Avoid native crash with GUID-less assemblies

mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/11965
Backport of #12704.
=> [2018-12] [arm/ios] workaround for faulty vcmp.f64 insn

mono/metadata/coree.c, mono/metadata/exception.c, mono/metadata/exception.h, mono/metadata/image-internals.h, mono/metadata/image.c, mono/metadata/image.h, mono/metadata/mono-security.c, mono/metadata/object.c, mono/metadata/w32socket.c
Addresses #12724 
Note this is against 2018-10.  Forward ports to 2018-12 and master after this one.
Backport of #12735.
=> [2018-12][runtime] Switch to GC Unsafe in a few more external API functions

mono/metadata/coree.c, mono/metadata/exception.c, mono/metadata/exception.h, mono/metadata/image-internals.h, mono/metadata/image.c, mono/metadata/image.h, mono/metadata/mono-security.c, mono/metadata/object.c, mono/metadata/w32socket.c
Addresses #12724 
---
Related to #12735, but targeting `master`
=> [runtime] Switch to GC Unsafe in a few more external API functions

mono/mini/debugger-agent.c, mono/mini/debugger-engine.c, mono/mini/debugger-engine.h, mono/mini/mini-wasm-debugger.c, sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs, sdks/wasm/library_mono.js
Add array inspection to the debugger for sized and unsized array, the example is below:
=> [wasm][debugger] Add array inspection to the debugger.

mono/utils/mono-state.c
Backport of #12737.
/cc @akoeplinger @leculver
=> [2018-06] Add back missing stack frames to mono MERP reports

mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs
Provide a Mono-specific version of CoreFx's `SslConnectionInfo` and use it to implement some "Connection Info" properties in `SslStream`: `CipherStrength`, `HashStrength` and `KeyExchangeStrength`.
Fixes #12552.
=> "Ice Blue": Adding some "Connection Info" properties to SslStream.

mcs/class/corlib/Test/System.Threading/CancellationTokenSourceTest.cs, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs
Fixes https://github.com/mono/mono/issues/12421
When we switched to CoreFX/CoreRT sources (mostly CoreRT) for System.Threading we had to keep old reference-source based `ExecutionContext`, `CancellationToken` and `CancellationTokenSource`.  In the bug above the redundant `SynchronizationContext.Post` was triggered here:
https://github.com/mono/corert/blob/1b7d4a1e4bd79305905338827cc41eb8303364f0/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs#L404
it was expected to be "myCustomSyncContext == myCustomSyncContext" but instead it was "myCustomSyncContext == empty SynchronizationContext instance".
That empty instance was allocated in `CreateCopy` which I am trying to delete in this PR.
That `.CreateCopy()` always creates `SynchronizationContext` instance (see …
=> [corlib] Do not clone SynchronizationContext in ExecutionContext.Capture

mcs/class/corlib/Test/System.Threading/CancellationTokenSourceTest.cs, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs
Fixes https://github.com/mono/mono/issues/12421
When we switched to CoreFX/CoreRT sources (mostly CoreRT) for System.Threading we had to keep old reference-source based `ExecutionContext`, `CancellationToken` and `CancellationTokenSource`.  In the bug above the redundant `SynchronizationContext.Post` was triggered here:
https://github.com/mono/corert/blob/1b7d4a1e4bd79305905338827cc41eb8303364f0/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs#L404
it was expected to be "myCustomSyncContext == myCustomSyncContext" but instead it was "myCustomSyncContext == empty SynchronizationContext instance".
That empty instance was allocated in `CreateCopy` which I am trying to delete in this PR.
That `.CreateCopy()` always creates `SynchronizationContext` instance (see …
=> [2019-02] [corlib] Do not clone SynchronizationContext in ExecutionContext.Capture

mcs/class/corlib/Test/System.Diagnostics/StackFrameTest.cs
=> [2019-02] [corlib] Fix GetFrames_AsyncCalls test not to block

mcs/class/corlib/Test/System.Threading/CancellationTokenSourceTest.cs, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs
Fixes https://github.com/mono/mono/issues/12421
When we switched to CoreFX/CoreRT sources (mostly CoreRT) for System.Threading we had to keep old reference-source based `ExecutionContext`, `CancellationToken` and `CancellationTokenSource`.  In the bug above the redundant `SynchronizationContext.Post` was triggered here:
https://github.com/mono/corert/blob/1b7d4a1e4bd79305905338827cc41eb8303364f0/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs#L404
it was expected to be "myCustomSyncContext == myCustomSyncContext" but instead it was "myCustomSyncContext == empty SynchronizationContext instance".
That empty instance was allocated in `CreateCopy` which I am trying to delete in this PR.
That `.CreateCopy()` always creates `SynchronizationContext` instance (see …
=> [2018-10] [corlib] Do not clone SynchronizationContext in ExecutionContext.Capture

mcs/class/corlib/Test/System.Threading/CancellationTokenSourceTest.cs, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs
Fixes https://github.com/mono/mono/issues/12421
When we switched to CoreFX/CoreRT sources (mostly CoreRT) for System.Threading we had to keep old reference-source based `ExecutionContext`, `CancellationToken` and `CancellationTokenSource`.  In the bug above the redundant `SynchronizationContext.Post` was triggered here:
https://github.com/mono/corert/blob/1b7d4a1e4bd79305905338827cc41eb8303364f0/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs#L404
it was expected to be "myCustomSyncContext == myCustomSyncContext" but instead it was "myCustomSyncContext == empty SynchronizationContext instance".
That empty instance was allocated in `CreateCopy` which I am trying to delete in this PR.
That `.CreateCopy()` always creates `SynchronizationContext` instance (see …
=> [2018-12] [corlib] Do not clone SynchronizationContext in ExecutionContext.Capture

mcs/class/corlib/Test/System.Diagnostics/StackFrameTest.cs
=> [2018-10] [corlib] Fix GetFrames_AsyncCalls test not to block

mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs
Provide a Mono-specific version of CoreFx's `SslConnectionInfo` and use it to implement some "Connection Info" properties in `SslStream`: `CipherStrength`, `HashStrength` and `KeyExchangeStrength`.
Fixes #12552.
Backport of #12687.
=> [2019-02] "Ice Blue": Adding some "Connection Info" properties to SslStream.

configure.ac, mono/native/Makefile.am
We were only doing the `-mmacosx-min-version` replacement magic on CFLAGS and LDFLAGS for mono-native-compat and -unified, but we need to do the same for CPPFLAGS/CXXFLAGS too.
Fixes an issue where the libraries were targeting the wrong minimum OSX version when built from xamarin-macios since they pass the minimum version in CPPFLAGS instead of CFLAGS for OSX.
=> [2018-10] Extend mono-native minimum version magic to CPPFLAGS/CXXFLAGS

mcs/class/corlib/Test/System.Diagnostics/StackFrameTest.cs
=> [2018-12] [corlib] Fix GetFrames_AsyncCalls test not to block

configure.ac, mono/native/Makefile.am
We were only doing the `-mmacosx-min-version` replacement magic on CFLAGS and LDFLAGS for mono-native-compat and -unified, but we need to do the same for CPPFLAGS/CXXFLAGS too.
Fixes an issue where the libraries were targeting the wrong minimum OSX version when built from xamarin-macios since they pass the minimum version in CPPFLAGS instead of CFLAGS for OSX.
Backport of #12801.
=> [2018-12] [2018-10] Extend mono-native minimum version magic to CPPFLAGS/CXXFLAGS

mcs/class/System.Core/System.Core.csproj, mcs/class/System.Core/common_System.Core.dll.sources, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/corlib/corlib_xtest.dll.sources, mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs, mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs, mcs/class/referencesource/mscorlib/system/threading/threadpool.cs
Bring some new APIs from corefx master for async-streams (C# 8.0):
- `IAsyncDisposable`
- `IAsyncEnumerable`
- `IAsyncEnumerator`
- `AsyncIteratorMethodBuilder`
- `AsyncIteratorStateMachineAttribute`
- `ConfiguredAsyncDisposable`
- `ConfiguredCancelableAsyncEnumerable`
- `ManualResetValueTaskSourceCore`
- `TaskExtensions` (replacing our reference source version).
Minor changes to existing code:
- Add `ExecutionContext.ContextCallback<TState>(ref TState state)` delegate.
- Add `ExecutionContext.RunInternal<TState>` method.
- Uncomment `AsyncMethodBuilderCore.Start<TStateMachine>`.
- Add new `ThreadPool.QueueUserWorkItem<T>(Action<T>,T,bool)` and `UnsafeQueueUserWorkItem<T>(Action<T>,T,bool)` overloads.
New xUnit tests from CoreFX:
- …
=> Add support for async-streams (C# 8.0).

configure.ac, mono/native/Makefile.am
We were only doing the `-mmacosx-min-version` replacement magic on CFLAGS and LDFLAGS for mono-native-compat and -unified, but we need to do the same for CPPFLAGS/CXXFLAGS too.
Fixes an issue where the libraries were targeting the wrong minimum OSX version when built from xamarin-macios since they pass the minimum version in CPPFLAGS instead of CFLAGS for OSX.
Backport of #12801.
=> [2019-02] [2018-10] Extend mono-native minimum version magic to CPPFLAGS/CXXFLAGS

mono/metadata/icall.c, sdks/builds/ios.mk
This fixes a regression introduced by https://github.com/mono/mono/commit/5187b0bdaaff56936d697b0753dad51e7498991d
The AOT compiler wasn't aware of the icalls since they are guarded by `ENABLE_MONOTOUCH`. Passing `--enable-monotouch` to configure of the AOT compiler enables that define, so it can properly resolve those icalls. However, to avoid `zlib` dependency for the cross compilers, we stub
them out.
Needs backport up to 2018-10.
Backport of #12834.
=> [2018-10] [ios] pass --enable-monotouch to cross compilers so icall defintions are visible to it

mono/mini/mini-wasm-debugger.c
An attribute with a content that was a string null was creating two items in result json and it was throwing an exception in client side because it is expected a name and a value and not a name and two values.
=> [wasm][debugger] Bug on attributes with value type string and content NULL

mono/metadata/icall.c, mono/metadata/loader-internals.h, mono/metadata/loader.c, mono/metadata/loader.h, mono/metadata/marshal.c, mono/mini/mini-runtime.c
Split up `mono_lookup_pinvoke_call` into several smaller static functions.  There is still more that should be done (the `for`-loop and `switch` for filename probing should also factor into smaller functions) but this is a first step.
There should be no functional change.
Also mark `mono_lookup_pinvoke_call` as external-only and switch the runtime to using `mono_lookup_pinvoke_call_internal`.  (This will make it easier to switch to a `MonoError` for errors, instead of returning a pair of strings).
=> [runtime] Refactor pinvoke probing

mono/metadata/sgen-stw.c
Due to current call order in sgen_client_stop_world to first process togglerefs and then take current threads stack could cause a problem where toogleref object references might be left in registers after running sgen_process_togglerefs and then those object reference would be put into current thread context, incorrectly pinning the object pointed to by a toggleref, preventing it from properly being handled by GC.
The problem was observed on Windows (in debug build) running sgen-toggleref.exe runtime test since
the compile of sgen_process_togglerefs used a register holding the current toogleref's object reference when walking the list of togglerefs. That register was then not re-used until the current threads stack was taken, causing incorrect pinning of the last toogleref object in the …
=> Fix issue where togglerefs might be incorrectly pinned by GC.

mono/tests/merp-crash-test.cs, mono/tests/merp-json-valid.cs
The 2018-10 lane seemed to be failing some tests because the merp-json-valid.exe test left behind the crash log file. I fixed that in this PR, but also move the tests into their separate folders so they can run at the same time safely.
=> [runtime] Use temp folders for merp tests

mono/metadata/icall.c, sdks/builds/ios.mk
This fixes a regression introduced by https://github.com/mono/mono/commit/5187b0bdaaff56936d697b0753dad51e7498991d
The AOT compiler wasn't aware of the icalls since they are guarded by `ENABLE_MONOTOUCH`. Passing `--enable-monotouch` to configure of the AOT compiler enables that define, so it can properly resolve those icalls. However, to avoid `zlib` dependency for the cross compilers, we stub
them out.
Needs backport up to 2018-10.
Backport of #12834.
=> [2018-12] [ios] pass --enable-monotouch to cross compilers so icall defintions are visible to it

mono/metadata/icall.c, sdks/builds/ios.mk
This fixes a regression introduced by https://github.com/mono/mono/commit/5187b0bdaaff56936d697b0753dad51e7498991d
The AOT compiler wasn't aware of the icalls since they are guarded by `ENABLE_MONOTOUCH`. Passing `--enable-monotouch` to configure of the AOT compiler enables that define, so it can properly resolve those icalls. However, to avoid `zlib` dependency for the cross compilers, we stub
them out.
Needs backport up to 2018-10.
Backport of #12834.
=> [2019-02] [ios] pass --enable-monotouch to cross compilers so icall defintions are visible to it

mono/metadata/icall.c, sdks/builds/ios.mk
This fixes a regression introduced by https://github.com/mono/mono/commit/5187b0bdaaff56936d697b0753dad51e7498991d
The AOT compiler wasn't aware of the icalls since they are guarded by `ENABLE_MONOTOUCH`. Passing `--enable-monotouch` to configure of the AOT compiler enables that define, so it can properly resolve those icalls. However, to avoid `zlib` dependency for the cross compilers, we stub
them out.
Needs backport up to 2018-10.
=> [ios] pass --enable-monotouch to cross compilers so icall defintions are visible to it

mono/mini/aot-runtime.c
/cc @spouliot. This fixes `--interpreter=-all` on Xamarin.iOS.
=> [aot] interp flag on AOT images only on mscorlib required

mono/tests/merp-crash-test.cs, mono/tests/merp-json-valid.cs
The 2018-10 lane seemed to be failing some tests because the merp-json-valid.exe test left behind the crash log file. I fixed that in this PR, but also move the tests into their separate folders so they can run at the same time safely. 
Backport of #12830.
=> [2019-02] [runtime] Use temp folders for merp tests

mono/mini/aot-runtime.c
/cc @spouliot. This fixes `--interpreter=-all` on Xamarin.iOS.
Backport of #12838.
/cc @lewurm
=> [2018-10] [aot] interp flag on AOT images only on mscorlib required

mcs/class/corlib/System.Reflection.Emit/CustomAttributeBuilder.cs, mcs/class/corlib/Test/System.Reflection.Emit/CustomAttributeBuilderTest.cs
Normally strings are encoded as length-then-utf8 in ECMA-335.  But a null
String is encoded as just the byte 0xFF.
When we make a CustomAttributeBuilder for a MarshalAsAttribute and attach it to
some parameter we first encode the CAB as a byte blob and then decode it in
CAB.get_umarshal into a UnmanagedMarshal attribute.  But the decoding didn't
account for the possibility of null strings.
Fixes https://github.com/mono/mono/issues/12747
=> [sre] Handle null values in MarshalAsAttribute CustomAttributeBuilder

mcs/class/corlib/System.Reflection.Emit/CustomAttributeBuilder.cs, mcs/class/corlib/Test/System.Reflection.Emit/CustomAttributeBuilderTest.cs
Normally strings are encoded as length-then-utf8 in ECMA-335.  But a null
String is encoded as just the byte 0xFF.
When we make a CustomAttributeBuilder for a MarshalAsAttribute and attach it to
some parameter we first encode the CAB as a byte blob and then decode it in
CAB.get_umarshal into a UnmanagedMarshal attribute.  But the decoding didn't
account for the possibility of null strings.
Fixes https://github.com/mono/mono/issues/12747
Backport of #12872.
=> [2019-02] [sre] Handle null values in MarshalAsAttribute CustomAttributeBuilder

mcs/class/corlib/System.Reflection.Emit/CustomAttributeBuilder.cs, mcs/class/corlib/Test/System.Reflection.Emit/CustomAttributeBuilderTest.cs
Normally strings are encoded as length-then-utf8 in ECMA-335.  But a null
String is encoded as just the byte 0xFF.
When we make a CustomAttributeBuilder for a MarshalAsAttribute and attach it to
some parameter we first encode the CAB as a byte blob and then decode it in
CAB.get_umarshal into a UnmanagedMarshal attribute.  But the decoding didn't
account for the possibility of null strings.
Fixes https://github.com/mono/mono/issues/12747
Backport of #12872.
=> [2018-10] [sre] Handle null values in MarshalAsAttribute CustomAttributeBuilder

mcs/class/corlib/System.Reflection.Emit/CustomAttributeBuilder.cs, mcs/class/corlib/Test/System.Reflection.Emit/CustomAttributeBuilderTest.cs
Normally strings are encoded as length-then-utf8 in ECMA-335.  But a null
String is encoded as just the byte 0xFF.
When we make a CustomAttributeBuilder for a MarshalAsAttribute and attach it to
some parameter we first encode the CAB as a byte blob and then decode it in
CAB.get_umarshal into a UnmanagedMarshal attribute.  But the decoding didn't
account for the possibility of null strings.
Fixes https://github.com/mono/mono/issues/12747
Backport of #12872.
=> [2018-12] [sre] Handle null values in MarshalAsAttribute CustomAttributeBuilder

mcs/class/corlib/Test/System/TypeTest.cs
TypeTest.MakeGenericType_BadUserType
TypeTest.MakeGenericType_NestedUserDefinedType
TypeTest.MakeGenericType_UserDefinedType
TypeTest.TestMakeGenericType_UserDefinedType_DotNet20SP1
These tests pass when run with the interpreter on xamarin-macios.
They were disabled on master with https://github.com/mono/mono/commit/dc9bc9e0e6462739872117afc59e46fbc780d981
Backport of #12868.
=> [2018-12] [corlib] Disable four tests in TypeTest

mono/mini/mini-arm64-gsharedvt.c
Backport of #12867.
/cc @lewurm
=> [2018-10] [arm64] encode offset within stack slot for r4 in gsharedvt descriptor

mono/mini/mini-arm64-gsharedvt.c
Backport of #12867.
/cc @lewurm
=> [2018-12] [arm64] encode offset within stack slot for r4 in gsharedvt descriptor

mono/mini/mini-arm64-gsharedvt.c
=> [arm64] encode offset within stack slot for r4 in gsharedvt descriptor

mono/mini/mini-arm64-gsharedvt.c
Backport of #12867.
/cc @lewurm
=> [2019-02] [arm64] encode offset within stack slot for r4 in gsharedvt descriptor

mono/mini/mini-generic-sharing.c, mono/tests/Makefile.am, mono/tests/async-generic-enum.cs
Also added an automated test to catch this scenario.
=> Fixing crash where a generic enum is passed into get_shared_type. 

mono/mini/mini-generic-sharing.c, mono/tests/Makefile.am, mono/tests/async-generic-enum.cs
Also added an automated test to catch this scenario.
Backport of #12622.
/cc @marek-safar @UnityAlex
=> [2018-12] Fixing crash where a generic enum is passed into get_shared_type. 

mono/mini/mini-generic-sharing.c, mono/tests/Makefile.am, mono/tests/async-generic-enum.cs
Also added an automated test to catch this scenario.
Backport of #12622.
/cc @marek-safar @UnityAlex
=> [2019-02] Fixing crash where a generic enum is passed into get_shared_type. 

mono/mini/mini-arm64-gsharedvt.c
Backport of #12867.
/cc @lewurm
=> [2018-08] [arm64] encode offset within stack slot for r4 in gsharedvt descriptor

mono/mini/aot-runtime.c
/cc @spouliot. This fixes `--interpreter=-all` on Xamarin.iOS.
Backport of #12838.
/cc @lewurm
=> [2018-12] [aot] interp flag on AOT images only on mscorlib required

mono/utils/mono-proclib.c
Since it's being used when the image is created, it actually doesn't need to be signal safe. This restores the previous behavior. 
Backport of #12588.
=> [2018-12] [runtime] Fix mono_pe_file_map logging

mono/utils/mono-proclib.c
Since it's being used when the image is created, it actually doesn't need to be signal safe. This restores the previous behavior. 
Backport of #12588.
=> [2018-10] [runtime] Fix mono_pe_file_map logging

mono/mini/interp/transform.c
=> [interp] Add method to seq_points table after we finish registering it

sdks/ios/appbuilder/appbuilder.cs
Fixes this app startup issue
```
dyld: Library not loaded: /Users/lewurm/work/mono-watch4-ios-sdk/sdks/out/ios-target64-release/lib/libmono-native-unified.0.dylib
Referenced from: /var/containers/Bundle/Application/9697C8F3-811C-4BF3-B1BC-1E6385673984/PublicStaging.app/test-Mono.Runtime.Tests
Reason: image not found
Process 2269 exited with status = 0 (0x00000000) Terminated due to signal 6
```
=> [ios] link mono-native correctly

mono/mini/mini-arm.c
=> [arm/bitcode] mark valuetype returns as such when dealing with pinvokes

mcs/class/corlib/Microsoft.Win32/UnixRegistryApi.cs
=> [Registry] Prevent crash due to background thread facing problems in the file system

mcs/class/corlib/Microsoft.Win32/UnixRegistryApi.cs
=> [2019-02] [Registry] Prevent crash due to background thread facing problems in the file system

mcs/class/corlib/Microsoft.Win32/UnixRegistryApi.cs
=> [2018-12] [Registry] Prevent crash due to background thread facing problems in the file system

mcs/class/corlib/Microsoft.Win32/UnixRegistryApi.cs
=> [2018-08] [Registry] Prevent crash due to background thread facing problems in the file system

mcs/class/corlib/Microsoft.Win32/UnixRegistryApi.cs
=> [2018-10] [Registry] Prevent crash due to background thread facing problems in the file system

mono/utils/mono-proclib.c
Since it's being used when the image is created, it actually doesn't need to be signal safe. This restores the previous behavior. 
Backport of #12588.
=> [2018-08] [runtime] Fix mono_pe_file_map logging

mcs/tools/cil-stringreplacer/Makefile
What was happening was that this was building with a Mono.Cecil from
the build profile, but was trying to load the system Mono.Cecil.
Those versions mismatch when building 2018-08 with a nightly mono that is 5.23.0.
Rather than messing with the MONO_PATH and risking shadowing something
important there, I chose to copy the Mono.Cecil files into this
"lib/build/tmp" directory that we are using for the emitted executable.
It is loaded by the system Mono as the correct Mono.Cecil to use, as assemblies in the same folder have precedence.
This fixes the build.
Backport of #12573.
=> [2018-08] [runtime] Fix building older runtimes with newer system Mono

mono/mini/arrays.cs, mono/mini/interp/interp.c, mono/mini/interp/transform.c
=> [interp] Fix ldelema

mono/mini/interp/transform.c
=> [2018-10] [interp] Add method to seq_points table after we finish registering it

mono/mini/mini-arm.c
=> [2018-10] [arm/bitcode] mark valuetype returns as such when dealing with pinvokes

mono/mini/mini-arm.c
=> [2019-02] [arm/bitcode] mark valuetype returns as such when dealing with pinvokes

mono/mini/interp/transform.c
=> [2019-02] [interp] Add method to seq_points table after we finish registering it

mono/mini/mini-arm.c
Backport of #12894.
/cc @lewurm
=> [2018-08-watchos] [arm/bitcode] mark valuetype returns as such when dealing with pinvokes

mono/mini/mini-arm.c
=> [2018-12] [arm/bitcode] mark valuetype returns as such when dealing with pinvokes

mono/mini/arrays.cs, mono/mini/interp/interp.c, mono/mini/interp/transform.c
=> [2018-08] [interp] Fix ldelema

mono/mini/arrays.cs, mono/mini/interp/interp.c, mono/mini/interp/transform.c
=> [2019-02] [interp] Fix ldelema

mono/mini/arrays.cs, mono/mini/interp/interp.c, mono/mini/interp/transform.c
=> [2018-12] [interp] Fix ldelema

mono/mini/arrays.cs, mono/mini/interp/interp.c, mono/mini/interp/transform.c
=> [2018-10] [interp] Fix ldelema

mono/mini/interp/transform.c
=> [2018-08] [interp] Add method to seq_points table after we finish registering it

mono/mini/interp/transform.c
=> [2018-12] [interp] Add method to seq_points table after we finish registering it

mono/mini/aot-runtime.c
/cc @spouliot. This fixes `--interpreter=-all` on Xamarin.iOS.
Backport of #12838.
/cc @lewurm
=> [2019-02] [aot] interp flag on AOT images only on mscorlib required

mono/tests/libtest.c
When using the previous test, some memory unsafety was
observed. It's rather unrecoverable memory unsafety, as
it corrupts heap memory used by the sequence points, registered MERP
paths, jit info internals, and output string.
The worst part of it is that it doesn't seem to be done in a way that triggers
lldb watchpoints on the memory addresses that are being corrupted. The physical
memory gets corrupted without going through the virtual address that we have.
Crashes seen here: https://github.com/mono/mono/pull/12387 reproduce
with less than 100 iterations of this malloc test run as the stress
test.
```
(MonoJitInfoTable) $2 = {
domain = 0x5050505050505050
num_chunks = 1347440720
num_valid = 1347440720
chunks = {}
}
```
with
```
(lldb) p/x 1347440720
(int) $0 = 0x50505050
```
And sometimes …
=> [crash] Use safer invalid-free test

mono/metadata/marshal.c
mono_string_utf16_to_builder_copy incorrectly uses MONO_HANDLE_SETRAW to update the chunkLength field with a string length. Since MONO_HANDLE_SETRAW assumes the argument is a MonoObject reference this could lead to a dereference and since the value is a string length, that dereference will lead to a crash.
The problem happens in mono_gc_wbarrier_set_arrayref_internal where vtable is retrieved from value. The crash happens randomly since it is depending on the object being moved out of the nursery + sgen_binary_protocol_wbarrier not being eliminated.
Fix is to use MONO_HANDLE_SETVAL since the value is not a reference so no need to trigger a write barrier.
=> Incorrect call to MONO_HANDLE_SETRAW causes random crash in sgen.

mono/mini/mini.c
Fixes Unity issue: https://issuetracker.unity3d.com/issues/allocating-too-many-variables-in-a-method-leads-to-a-crash
=> Grow StackSlotInfo array rather than asserting

mono/metadata/icall.c, mono/metadata/loader-internals.h, mono/metadata/loader.c, mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c, mono/metadata/marshal.h, mono/metadata/method-builder-ilgen.c, mono/metadata/method-builder-ilgen.h, mono/metadata/method-builder.h, mono/mini/interp/interp.c, mono/mini/mini-runtime.c
1. Use `MonoError` to signal pinvoke probing failures. This is a bit complicated because:
a. the old API uses another error mechanism
b. the marshalling code needs to emit IL that will raise an exception given a `MonoError`.
2. Refactor the pinvoke library path transformation code a bit.  It still needs work, but at least it's now hopefully a little clearer that it's just doing some name mangling every time through the loop.
3. There's a `ENABLE_NETCORE` leak that I didn't fix - see the comment in the code.  Ultimately, I think I'll need to make dllmap lookups return copies of results by default, or else copy them at the use site, and then free at the use site.
=> [runtime] Refactor pinvoke probing, part 2

mono/metadata/sgen-stw.c
Due to current call order in sgen_client_stop_world to first process togglerefs and then take current threads stack could cause a problem where toogleref object references might be left in registers after running sgen_process_togglerefs and then those object reference would be put into current thread context, incorrectly pinning the object pointed to by a toggleref, preventing it from properly being handled by GC.
The problem was observed on Windows (in debug build) running sgen-toggleref.exe runtime test since
the compile of sgen_process_togglerefs used a register holding the current toogleref's object reference when walking the list of togglerefs. That register was then not re-used until the current threads stack was taken, causing incorrect pinning of the last toogleref object in the …
=> [2019-02] Fix issue where togglerefs might be incorrectly pinned by GC.

configure.ac, mcs/class/System/corefx/Unix/Interop.cs, mcs/class/System/monodroid_System_xtest.dll.exclude.sources
…oid build
If this is not done, Android is not able to resolve mono symbols that are used in mono-native (e.g. `mono_add_internal_call_with_flags`), and will refuse to load the library with 'cannot locate symbol' errors
=> [2018-10] Xamarin.Android integration fixes

sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs, sdks/wasm/ProxyDriver/Startup.cs
Much of the tooling around DevTools expects
actions under /json to return useful data
this adds adds some simple logic to proxy those
so that you can point tooling directly at the
proxied port and get responses you expect
=> [Wasm] Proxy More of the DevTools protocol

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs, sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
Add missing callFrameId to the call stack and fill in any missing descriptions to make VSCode happy.
=> [Wasm] debug context

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs, sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
If we can locate the source locally use direct file: references because some of the Visual Studio tooling works much better in this case.
=> [Wasm] debug local source

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-engine.c
Reverting part of this commit https://github.com/mono/mono/pull/12114, removing this part the test ShouldCorrectlyStepOverOnExitFromArgsAfterStepInMethodParameter continues working and solve the regressions of 12881.
Inserted a new test that reproduces the regression.
Fixes #12881
=> [debugger] Reverting part of https://github.com/mono/mono/pull/12114 

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-engine.c
Reverting part of this commit https://github.com/mono/mono/pull/12114, removing this part the test ShouldCorrectlyStepOverOnExitFromArgsAfterStepInMethodParameter continues working and solve the regressions of 12881.
Inserted a new test that reproduces the regression.
Fixes #12881
Backport of #12950.
/cc @thaystg
=> [2018-12] [debugger] Reverting part of https://github.com/mono/mono/pull/12114 

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-engine.c
Reverting part of this commit #12114, removing this part the test ShouldCorrectlyStepOverOnExitFromArgsAfterStepInMethodParameter continues working and solve the regressions of 12881.
Inserted a new test that reproduces the regression.
Fixes #12881
Backport of #12950.
/cc @thaystg
=> [2018-10] [debugger] Reverting part of https://github.com/mono/mono/pull/12114

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-engine.c
Reverting part of this commit https://github.com/mono/mono/pull/12114, removing this part the test ShouldCorrectlyStepOverOnExitFromArgsAfterStepInMethodParameter continues working and solve the regressions of 12881.
Inserted a new test that reproduces the regression.
Fixes #12881
Backport of #12950.
/cc @thaystg
=> [2019-02] [debugger] Reverting part of https://github.com/mono/mono/pull/12114 

mono/metadata/class-init.c, mono/metadata/debug-helpers.c, mono/mini/mini-codegen.c
Include custom modifiers in the output of `mono_type_get_desc()` - useful when printing the vtable layout for debugging.
=> [debug-helpers] Include custom modifiers in mono_type_get_desc

configure.ac, mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mcs/class/corlib/Mono.Interop/ComInteropProxy.cs, mcs/class/corlib/System.Reflection/RuntimeParameterInfo.cs, mono/metadata/custom-attrs.c, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/reflection-internals.h, mono/metadata/reflection.c
=> [runtime] Avoid depending on the layout of the ParameterInfo class in the runtime, netcore has a version with a different layout.

mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs
It was missed in https://github.com/mono/mono/pull/11829 so we were still manually creating HttpListeners which are not hardened against "Address already in use".
Should fix/improve https://github.com/xamarin/maccore/issues/1407.
=> [System.Net.Http] Improve HttpClientTest to use the retry http listener

mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs
It was missed in https://github.com/mono/mono/pull/11829 so we were still manually creating HttpListeners which are not hardened against "Address already in use".
Should fix/improve https://github.com/xamarin/maccore/issues/1407.
Backport of #12994.
=> [2019-02] [System.Net.Http] Improve HttpClientTest to use the retry http listener

mono/metadata/sgen-stw.c
Due to current call order in sgen_client_stop_world to first process togglerefs and then take current threads stack could cause a problem where toogleref object references might be left in registers after running sgen_process_togglerefs and then those object reference would be put into current thread context, incorrectly pinning the object pointed to by a toggleref, preventing it from properly being handled by GC.
The problem was observed on Windows (in debug build) running sgen-toggleref.exe runtime test since
the compile of sgen_process_togglerefs used a register holding the current toogleref's object reference when walking the list of togglerefs. That register was then not re-used until the current threads stack was taken, causing incorrect pinning of the last toogleref object in the …
=> [2018-12] Fix issue where togglerefs might be incorrectly pinned by GC.

mono/metadata/sgen-stw.c
Due to current call order in sgen_client_stop_world to first process togglerefs and then take current threads stack could cause a problem where toogleref object references might be left in registers after running sgen_process_togglerefs and then those object reference would be put into current thread context, incorrectly pinning the object pointed to by a toggleref, preventing it from properly being handled by GC.
The problem was observed on Windows (in debug build) running sgen-toggleref.exe runtime test since
the compile of sgen_process_togglerefs used a register holding the current toogleref's object reference when walking the list of togglerefs. That register was then not re-used until the current threads stack was taken, causing incorrect pinning of the last toogleref object in the …
=> [2018-10] Fix issue where togglerefs might be incorrectly pinned by GC.

configure.ac, mcs/class/System/Test/System.Net/WebClientTest.cs, mcs/class/System/Test/System.Net/WebClientTestAsync.cs
We have APIs that use exception filter clauses, and we don't support that when
compiling to bitcode.
So mark any tests exercising such API accordingly, so that we can skip those
tests when running tests on targets that use bitcode (watchOS).
=> [tests] Add the BitcodeNotSupported category to tests exercising non-bitcode-compatible API.

mono/mini/mini-arm.c
consider
```csharp
struct S3
{
public ushort X;
public ushort Y;
public ushort Z;
}
```
this would be 3 * 2 = 6 bytes. Structs, however, are passed around as i32
arrays in LLVM IR between functions. Those, if such a struct is passed, are
split to `int32`s depending on the struct's size. The previous calulation was
wrongly reserving one such i32 slot instead of two for `S3` above.
Additionally increase slot size to i64 so that it aligns with a
slightly different ABI on arm64_32.
Fixes https://github.com/mono/mono/issues/8486
@rolfbjarne I've tested it on a arm64_32 device, please confirm that this fixes the issue on your armv7k device as well
Backport of #12992.
/cc @lewurm
=> [2018-10] [bitcode] round up value type size for slot calculation

mcs/class/Mono.Btls.Interface/Mono.Btls.Interface/BtlsProvider.cs, mcs/class/System/Mono.AppleTls/AppleTlsContext.cs, mcs/class/System/Mono.AppleTls/Trust.cs, mcs/class/System/Mono.Btls/MonoBtlsContext.cs, mcs/class/System/Mono.Btls/MonoBtlsProvider.cs, mcs/class/System/Mono.Net.Security/MobileTlsContext.cs, mcs/class/System/Mono/SystemCertificateProvider.cs
This makes us consistent with corefx; see also https://github.com/dotnet/corefx/pull/35306.
Using `X509Certificate` has become a problem because the `HttpClientHandler.ServerCertificateCustomValidationCallback` callback takes an `X509Certificate2` argument.
=> Pass X509Certificate2 to the certificate validator.

mono/mini/mini-posix.c
If someone jumps to a bogus address for some reason, the dump_memory_around_ip function will double-fault. On OSX, a double fault is often a hang. 
Moving this after the mission-critical reporting is helpful here.
=> [crash] Move dump_memory_around_ip after the native crash

mono/mini/mini-wasm-debugger.c
If getter is not implemented in a property we don't want to show this property, in Vs the behaviour is the same.
Fixes #12964
=> [wasm][debugger] Evaluate property without getter implemented

mono/tests/Makefile.am
The leading `.` in the script invocation causes the tests to fail on multiple platforms by causing the required argument to not be passed correctly resulting in bad output. Removal of the leading `.` ensures correct operation on all platforms.
=> Remove leading . from script invocation

mono/tests/Makefile.am
The leading `.` in the script invocation causes the tests to fail on multiple platforms by causing the required argument to not be passed correctly resulting in bad output. Removal of the leading `.` ensures correct operation on all platforms.
Backport of #13046.
/cc @akoeplinger @rootwyrm
=> [2019-02] Remove leading . from script invocation

mcs/class/Mono.Btls.Interface/Mono.Btls.Interface/BtlsProvider.cs, mcs/class/System/Mono.AppleTls/AppleTlsContext.cs, mcs/class/System/Mono.AppleTls/Trust.cs, mcs/class/System/Mono.Btls/MonoBtlsContext.cs, mcs/class/System/Mono.Btls/MonoBtlsProvider.cs, mcs/class/System/Mono.Net.Security/MobileTlsContext.cs, mcs/class/System/Mono/SystemCertificateProvider.cs
This makes us consistent with corefx; see also https://github.com/dotnet/corefx/pull/35306.
Using `X509Certificate` has become a problem because the `HttpClientHandler.ServerCertificateCustomValidationCallback` callback takes an `X509Certificate2` argument.
Backport of #12999.
/cc @baulig
=> [2019-02] Pass X509Certificate2 to the certificate validator.

mono/utils/mono-context.h
Later levels of glibc redefine struct ucontext to typedef struct ucontext_t. This PR will check the level of glibc and define MonoContext appropriately.
Backport of #12272.
/cc @akoeplinger @nealef
=> [2018-10] Cater for later glibc use of ucontext

mcs/class/System.Web/System.Web.Configuration_2.0/WebConfigurationHost.cs
```
class Program
{
{
//{
//}
// This works
{
var a = …
```
=> Fix InvalidCastException when building ASP MVC 5 project with RazorGenerator

mcs/class/System.Web/System.Web.Configuration_2.0/WebConfigurationHost.cs
```
class Program
{
{
//{
//}
// This works
{
var a = …
```
=> [2018-08] Fix InvalidCastException when building ASP MVC 5 project with RazorGenerator

mcs/class/System.Net.Http/StreamContent.Mono.cs, mcs/class/System.Net.Http/System.Net.Http.csproj, mcs/class/System.Net.Http/unix_net_4_x_System.Net.Http.dll.sources
This is a temporary workaround and not a final solution.  Please read my detailed comment in https://github.com/mono/mono/issues/12996#issuecomment-464142887 for details.
=> Add temporary workaround for internal StreamContent constructor.

mono/profiler/aot.c
The `mono_profiler_printf` already adds `\n` char, so we don't need to
add them in most cases.
Before the fix the output of aot profiler with verbose enabled looked
like:
02-19 10:50:02.877 22795 22815 I mono-prof: System.OutOfMemoryException:.ctor (string) 2
02-19 10:50:02.877 22795 22815 I mono-prof:
02-19 10:50:02.877 22795 22815 I mono-prof: System.SystemException:.ctor (string) 4
02-19 10:50:02.877 22795 22815 I mono-prof:
02-19 10:50:02.877 22795 22815 I mono-prof: System.Exception:.ctor (string) 6
02-19 10:50:02.877 22795 22815 I mono-prof:
02-19 10:50:02.877 22795 22815 I mono-prof: System.Exception:.cctor () 7
02-19 10:50:02.877 22795 22815 I mono-prof:
...
The `usage ()` output should now look similar to other profilers
usage output.
=> [profiler] Do not print that many new lines

mcs/build/library.make, mcs/build/tests.make, mcs/class/corlib/Mono.Globalization.Unicode/Makefile, mono/eglib/test/Makefile.am, scripts/ci/run-jenkins.sh, sdks/ios/Makefile, sdks/wasm/Makefile
Apple's `make` doesn't support the `--output-sync` option and Homebrew's `make` is installed as `gmake`.
Also fixed a few places in the repo where we directly invoked make instead of $(MAKE).
=> [ci] Prefer gmake over make for SDKs build

mcs/jay/Makefile
Jay should not be part of the package and cause issues on Windows 32-bit cygwin build since it's not using makefile generated by autotools. When make install is run it will build jay one more time, but picking up
cygwin default gcc compiler instead of the one used in configure step, mingw. That cause link errors since the object files are not rebuild, only relinked with different linker, causing errors.
=> Don't install jay as part of make install.

mono/metadata/assembly.c
Before 5e0d39a8a1268773656348a012a237164985dc5f, there used to be a handwritten binary search that traveersed `framework_assemblies` to determine if a given assembly was a framework assembly or not.  The binary search used `last = G_N_ELEMENTS (framework_assemblies) - 1` as the initial condition, but it used an inclusive `first <= last` as the loop count.
After we switched to a hashtable, we used the same final value initialize `assembly_remapping_table`.
We didn't notice because `mscorlib` used to be the last assembly in the table and `mscorlib` already has a ton of special handling in the loader.  But `netstandard` is not special.  So we added it to the table, but it still doesn't get special handling.
This should fix instances where code references netstandard 2.0.0.0, but we give it …
=> [loader] Fix off by 1 (netstandard is a framework facade)

mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/12988.
=> [llvm] Fix a 'incoming phi sreg1' llvm failure which happens with valuetypes+phi nodes.

mono/metadata/assembly.c
Before 5e0d39a8a1268773656348a012a237164985dc5f, there used to be a handwritten binary search that traveersed `framework_assemblies` to determine if a given assembly was a framework assembly or not.  The binary search used `last = G_N_ELEMENTS (framework_assemblies) - 1` as the initial condition, but it used an inclusive `first <= last` as the loop count.
After we switched to a hashtable, we used the same final value initialize `assembly_remapping_table`.
We didn't notice because `mscorlib` used to be the last assembly in the table and `mscorlib` already has a ton of special handling in the loader.  But `netstandard` is not special.  So we added it to the table, but it still doesn't get special handling.
This should fix instances where code references netstandard 2.0.0.0, but we give it …
=> [2019-02] [loader] Fix off by 1 (netstandard is a framework facade)

mono/mini/interp/transform.c, mono/mini/method-to-ir.c
Interface method calls on constrained types are resolved in get_method_constrained now (apparently since https://github.com/mono/mono/commit/3259e04ace67552fc8d63a8f1ddbb830e526f05f)
=> [runtime] Remove dead code

scripts/ci/run-test-winaot.sh
Not part (and should not be) part of the winaot profile and therefore not testable (even though they pass when manually AOT:ing the assembly).
=> Disable Mono.CSharp on Windows x64 full AOT test.

mcs/class/System.Web/System.Web.Configuration_2.0/WebConfigurationHost.cs
```
class Program
{
{
//{
//}
// This works
{
var a = …
```
=> [2019-02] Fix InvalidCastException when building ASP MVC 5 project with RazorGenerator

mcs/class/System.Web/System.Web.Configuration_2.0/WebConfigurationHost.cs
```
class Program
{
{
//{
//}
// This works
{
var a = …
```
=> [2018-12] Fix InvalidCastException when building ASP MVC 5 project with RazorGenerator

mcs/class/System.Web/System.Web.Configuration_2.0/WebConfigurationHost.cs
```
class Program
{
{
//{
//}
// This works
{
var a = …
```
=> [2018-10] Fix InvalidCastException when building ASP MVC 5 project with RazorGenerator

mono/mini/calls.c
Fixes https://github.com/mono/mono/issues/12998.
=> [llvmonly] Do null checks on interp transitions for virtual->non virtual calls.

mcs/class/corlib/System.IO/DriveInfo.cs, mcs/class/corlib/Test/System.IO/DriveInfoTest.cs
It's possible to pass any string as an argument to DriveInfo ctor (e.g.  `new DriveInfo(Path.GetTempPath())`). Mono throws ArgumentException if there is no exactly the same drive name in the list of available drives.
I tried to handle this case by extracting any valid drive name from the array of available drives sorted by path in descending order.
Fixes https://github.com/mono/mono/issues/12157
=> Try to extract valid drive name from DriveInfo ctor string argument

mono/mini/decompose.c, mono/mini/local-propagation.c, mono/tests/Makefile.am, mono/tests/gh-13056_mono_local_cprop_av.il, mono/tests/gh-13057_mono_local_emulate_ops_av.il
Fixes https://github.com/mono/mono/issues/13056 & https://github.com/mono/mono/issues/13057
=> [jit/cprop] insert dummy insn if first insn of basic block got replaced

packaging/MacSDK/fsharp.py, packaging/MacSDK/patches/fsharp-GetFileNameWithoutExtension-type-inference.patch
```
@/external/bockbuild/builds/fsharp-fsharp-6624925/src/scripts/fssrgen.fsx(334,28): error FS0041: A unique overload for method 'GetFileNameWithoutExtension' could not be determined based on type information prior to this program point.
A type annotation may be needed. Candidates: System.IO.Path.GetFileNameWithoutExtension(path: System.ReadOnlySpan<char>) : System.ReadOnlySpan<char>, System.IO.Path.GetFileNameWithoutExtension(path: string) : string
[@/external/bockbuild/builds/fsharp-fsharp-6624925/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj]
```
=> [fsharp] Fix a type inference error introduced by recent changes

mcs/class/System/Test/System.Net.Sockets/SocketTest.cs
- Previous test with 100 micro second timeout would fail on iOS device when running **all the socket tests** about 3 times out of 5.
- With a 1 millisecond timeout, it didn't fail the 10 times I tried locally, hopefully this is enough to fix the flakiness.
- Fixes #8360: [System.Net.Sockets] flakey failures of SocketTest.TestSelect1 on Darwin systems
(https://github.com/mono/mono/issues/8360)
- Also partial fix for maccore issue https://github.com/xamarin/maccore/issues/1069
=> [tests] Bump TestSelect1 socket timeout to 1ms

mono/mini/aot-compiler.c
When trying to use AOT profile in XA for assembly AOT compilation, the
methods from the profile were not compiled.
Context: https://github.com/xamarin/xamarin-android/issues/2504
The problem was, the profile data were not resolved, as there was no
assembly loaded in the domain.
With this fix, the compiled assembly is used to resolve the profile as
well.
=> [aot] Resolve profile against compiled assembly

mono/eglib/gfile-posix.c, mono/mini/driver.c
* If file is UTF8 encoded and include BOM mark, implementation failed to detect and remove BOM mark causing errors. Fix check for BOM mark and if found, remove it before passed to parsing. NOTE, current implementation only supports UTF8 (and ASCII) content in response file and won't detect or handle any other codepages.
* Since the content in --response file should mimic what should have been passed on command line, we should apply same parsing rules on Windows as done by the shell when running the arguments on the command line. Current implementation uses its own parsing that is not the same as used by the Windows shell, meaning that arguments can't be identical in response file compared to what's passed on command line. This commit fix parsing of the command line in the response file so …
=>  Fix multiple issues with response file option on Windows.

mono/utils/mono-mmap-windows.c
When I tried it, I got a different error.
The size of the mapping is the maximum file offset to map.
See https://docs.microsoft.com/en-us/windows/desktop/Memory/creating-a-file-mapping-object.
If in the debugger you simulate this fix, it gets further.
Here is a small program to exercise and see the behavior:
```
// include <windows.h>
// include <stdio.h>
// include <stdlib.h>
//
// int main()
// {
//  // Create a 128K file.
//
//  HANDLE file = CreateFile("1", GENERIC_READ | GENERIC_WRITE, 0, 0, CREATE_ALWAYS, 0, 0);
//  printf("createfile %p %d\n", file, GetLastError());
//
//  HANDLE map = CreateFileMapping(file, 0, PAGE_READWRITE, 0, 1 << 17, 0);
//  printf("createmap %p %d\n", map, GetLastError());
//
//  CloseHandle(map);
//  CloseHandle(file);
//  system("dir");
//
//  // Attempt …
```
=> [mkbundle] Fix mapping length

mono/mini/aot-runtime.c
Mixed mode depends on that.  Usually, compile_method of mini takes care
to request only existing methods from the AOT image, but in some cases,
e.g. from a trampoline, AOT runtime is quiered directly.
=> [aot] abort lookup early when a method isn't available in AOT image

mono/mini/aot-compiler.c
When trying to use AOT profile in XA for assembly AOT compilation, the
methods from the profile were not compiled.
Context: https://github.com/xamarin/xamarin-android/issues/2504
The problem was, the profile data were not resolved, as there was no
assembly loaded in the domain.
With this fix, the compiled assembly is used to resolve the profile as
well.
Backport of #13148.
/cc @luhenry @radekdoulik
=> [2019-02] [aot] Resolve profile against compiled assembly

mono/mini/aot-runtime.c
Mixed mode depends on that.  Usually, compile_method of mini takes care
to request only existing methods from the AOT image, but in some cases,
e.g. from a trampoline, AOT runtime is quiered directly.
Backport of #13138.
/cc @lewurm
=> [2018-12] [aot] abort lookup early when a method isn\u0027t available in AOT image

mono/mini/aot-compiler.c
When trying to use AOT profile in XA for assembly AOT compilation, the
methods from the profile were not compiled.
Context: https://github.com/xamarin/xamarin-android/issues/2504
The problem was, the profile data were not resolved, as there was no
assembly loaded in the domain.
With this fix, the compiled assembly is used to resolve the profile as
well.
Backport of #13148.
/cc @lewurm @radekdoulik
=> [2018-12] [aot] Resolve profile against compiled assembly

mcs/class/Mono.Security/Mono.Security.Cryptography/CryptoConvert.cs
* Add new internal `CryptoConvert.TryImportCapiPrivateKeyBlob()` method that's using `RSAManaged` directly to make it more linker-friendly.
* Use it in `AssemblyName.IsPublicKeyValid`.
=> [Mono.Security]: minor `CryptoConvert` changes to make it more linker-friendly.

mcs/class/I18N/CJK/GB18030Source.cs, mcs/class/I18N/CJK/Test/I18N.CJK.Test.cs
Fixes https://github.com/mono/mono/issues/13144
=> Consider unknown GB18030 characters as invalid to enforce use of replacement character instead of throwing SystemException.

mono/mini/aot-runtime.c
Mixed mode depends on that.  Usually, compile_method of mini takes care
to request only existing methods from the AOT image, but in some cases,
e.g. from a trampoline, AOT runtime is quiered directly.
Backport of #13138.
/cc @lewurm
=> [2019-02] [aot] abort lookup early when a method isn\u0027t available in AOT image

mono/mini/aot-runtime.c
Mixed mode depends on that.  Usually, compile_method of mini takes care
to request only existing methods from the AOT image, but in some cases,
e.g. from a trampoline, AOT runtime is quiered directly.
Backport of #13138.
/cc @lewurm
=> [2018-10] [aot] abort lookup early when a method isn\u0027t available in AOT image

mono/metadata/icall.c
This fixes 1 of 2 identified issues found in: https://github.com/mono/mono/issues/13133
We need a faster slow path and we need to use the fast path for 2d and 3d arrays. 
This makes us use the fast path on 2d and 3d arrays. Our check for bounds was wrong because we were checking if the array is null. When we have a rank above 1, we will always have at least some bounds struct pointed to by the relevant pointer because we place an array there. Instead, we check that all of the bounds are zero/NULL. 
There's an immediate speed gain on the benchmark.
Using the same number of iterations:
- Before:
- After:
=> [runtime] Use FastCopy on multidimensional arrays

mono/mini/aot-compiler.c
When trying to use AOT profile in XA for assembly AOT compilation, the
methods from the profile were not compiled.
Context: https://github.com/xamarin/xamarin-android/issues/2504
The problem was, the profile data were not resolved, as there was no
assembly loaded in the domain.
With this fix, the compiled assembly is used to resolve the profile as
well.
Backport of #13148.
/cc @radekdoulik
=> [2018-10] [aot] Resolve profile against compiled assembly

mono/eglib/gfile-posix.c, mono/mini/driver.c
* If file is UTF8 encoded and include BOM mark, implementation failed to detect and remove BOM mark causing errors. Fix check for BOM mark and if found, remove it before passed to parsing. NOTE, current implementation only supports UTF8 (and ASCII) content in response file and won't detect or handle any other codepages.
* Since the content in --response file should mimic what should have been passed on command line, we should apply same parsing rules on Windows as done by the shell when running the arguments on the command line. Current implementation uses its own parsing that is not the same as used by the Windows shell, meaning that arguments can't be identical in response file compared to what's passed on command line. This commit fix parsing of the command line in the response file so …
=> [2019-02]  Fix multiple issues with response file option on Windows.

mcs/class/Mono.Security/Mono.Security.Cryptography/CryptoConvert.cs
=> Revert "[Mono.Security]: minor `CryptoConvert` changes to make it more linker-friendly."

data/lldb/monobt.py
Broke due to b6775765ed2a15d8aa5580ad420bfb78bf9b4406
=> [lldb] fix helper for interpreter stacktraces

mcs/class/System/Test/System.Diagnostics/ProcessTest.cs, mcs/class/corlib/System.Runtime.InteropServices.RuntimeInformation/RuntimeInformation.cs, mcs/class/corlib/Test/System.Threading/InterlockedTest.cs, mono/metadata/icall-def.h, mono/metadata/icall.c
Uses reflection instead of an external harness variable as recommended to me on Gitter a few weeks ago.
Might also be slightly overzealous on the exchange tests as well.
----
This should let the System and corlib tests run all the way through on Jenkins too, so the babysitter won't have to intervene.
=> Mark some corlib/System tests that hang runtime on AIX as non-working

mono/mini/interp/interp.c, mono/mini/mixed.cs
Otherwise we smash the stack.
Contributes to https://github.com/xamarin/xamarin-macios/issues/5622
=> [interp] compute size of generic valuetype correctly

configure.ac, mono/metadata/threads.c, mono/utils/mono-threads-posix.c
Compile like this:
if you have Zircon installed, with the prebuilts on "../zircon", use this to compile:
```
CC="`pwd`/../zircon/prebuilt/downloads/clang/bin/clang-9 -nostdlib -O2 -g -fdebug-prefix-map=/cvs/fuchsia/zircon=. -finline -fno-common -ffunction-sections -fdata-sections -no-canonical-prefixes -march=x86-64 -mcx16 --target=x86_64-fuchsia -fPIC -D_ALL_SOURCE=1 -DENABLE_DRIVER_TRACING=1 -fasynchronous-unwind-tables -fno-omit-frame-pointer  -std=c11 -I`pwd`/../zircon/build-x64-clang/sysroot/include/ -I`pwd`/../zircon/system/public" LDFLAGS="-L`pwd`/../zircon/build-x64-clang/sysroot/lib/ -L`pwd`/../zircon/build-x64-clang/sysroot/debug" ./configure --host=x86_64-google-fuchsia
```
=> Initial support for Fuchsia

mono/tests/console-output.cs, mono/tests/console-output.exe.stderr.expected, mono/tests/console-output.exe.stdout.expected
Current output from console-output test is just Error and Out (indicating the different console output streams). When seen in log files the error output string can be misleading. Fix makes it clearer that the output is originating from a test and not an “error”.
=> Update output from console-output test.

mono/arch/ppc/ppc-codegen.h, mono/mini/cpu-ppc.md, mono/mini/cpu-ppc64.md, mono/mini/mini-ops.h, mono/mini/mini-ppc.c, mono/utils/mono-hwcap-ppc.c, mono/utils/mono-hwcap-vars.h
Optimizes a bunch of functions with expensive function call overhead into neat one or two instructions inlined. Optimizations are based on amd64 mini instruction emitting. Instructions used are still within the POWER5 optimizations applied.
`rcheck` in mini passes, and output seems sane from prodding code. Linux, PASE, and ppc32 are untested. Floating point I know can be.... delicate, but since amd64 tries to take the HW shortcuts, and IEEE floating point should be consistent, try this.
Functions affected:
* `System.Math`
*  `Min (int32, int32)`
*  `Min (uint32, uint32)`
*  `Min (int64, int64)` (don't enable long int arith functions on ppc32 though, based on implications in mini for ppc32)
*  `Min (uint64, uint64)`
*  `Sqrt (double)`
*  `Abs (double)`
*  `Round (double)`
*  `Truncate …
=> PPC JIT optimizations (System.Math instruction inlining)

mcs/class/Facades/subdirs.make
It was accidentally removed by 244c31c6be298c4d59059ce7901e548b99a77946.
=> [Facades] Add System.Drawing.Common back to monotouch etc profiles

sdks/ios/Makefile
PWD is the wrong directory when e.g. you're doing "make -C sdks/ios" from the repo root.
Fixes https://github.com/mono/mono/issues/13224
=> [sdks] Use abspath instead of PWD on iOS app build

mono/mini/interp/interp.c, mono/mini/mixed.cs
Otherwise we smash the stack.
Contributes to https://github.com/xamarin/xamarin-macios/issues/5622
Backport of #13216.
/cc @lewurm
=> [2018-12] [interp] compute size of generic valuetype correctly

mcs/class/Mono.Debugger.Soft/Test/dtest.cs
It was recently reenabled in https://github.com/mono/mono/pull/9091 but it fails/hangs frequently, e.g.:
- https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx/19575/testReport/junit/(root)/DebuggerTests/Attach/
- https://jenkins.mono-project.com/job/test-mono-pull-request-interpreter/15082/testReport/(root)/DebuggerTests/Attach/
/cc @luhenry @mfilippov
=> [Mono.Debugger.Soft] Disable Attach() test that fails or hangs

mcs/class/corlib/System.Runtime.Remoting/Identity.cs
Experimental partial fix for issue #13113. From looking at the code that uses this API, I don't think it's expected for it to throw in this scenario, and it's easy to end up with an instance that doesn't have a WR at all. The code using it seems to handle scenarios where the ClientProxy is null so I think this may be the correct way for the code to work.
=> If a ClientIdentity has no ClientProxy then return null from the accessor instead of throwing

mono/metadata/class.c, mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/object.c
This PR makes our array_set_value_impl slow path much faster. Benchmarks included. 
It fixes the second of two problems identified here: https://github.com/mono/mono/issues/13133
Before:
After:
=> [runtime] Optimize array_set_value_impl slow path

mono/mini/interp/interp.c, mono/mini/mixed.cs
Otherwise we smash the stack.
Contributes to https://github.com/xamarin/xamarin-macios/issues/5622
Backport of #13216.
/cc @lewurm
=> [2019-02] [interp] compute size of generic valuetype correctly

mcs/class/System.Net.Http/System.Net.Http/DelegatingHandler.cs, mcs/class/System.Net.Http/Test/System.Net.Http/DelegatingHandlerTest.cs
Mono uses DelegatingHandler class legacy implementation on Windows. The PR aligns its behavior with corefx implementation used on macOS/Unix.
Fixes https://github.com/mono/mono/issues/8142
=> Throw InvalidOperationException if inner handler is not assigned in DelegatingHandler

Makefile.am
Backport of #11509.
/cc @akoeplinger @directhex 
Fixes #13253
=> [2018-08] Clean up .o files from System.Native during `make dist`

configure.ac, mono/mini/basic-math.cs, mono/mini/mini-ppc.c
* fix a typo in the JIT optimization where signed longs were being compared unsigned, and add a mini rcheck test for it
* don't use `frin.` for rounding; the semantics are different enough from `Math.Round` where it might not be actually safe, some tests tripped out. Ceil/Floor/Trunc seem safe, however.
* link libbsd into Mono.Native (not the fd.o one) for flock; the runtime's dep chain on AIX loaded libbsd it seemed, but not on i
=> More PPC/AIX regression fixes

mcs/class/System.Windows.Forms/System.Windows.Forms/Form.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/MdiFormTest.cs
=> [SWF] Method OnClosed should pass FormClosedEventArgs type, instead of EventArgs

mono/metadata/loader.c
Context: https://github.com/xamarin/xamarin-android/issues/2780
On Android the executable for the application is going to be
`/system/bin/app_process{32,64}` depending on the application's architecture.
However, libraries for the different architectures live in different
subdirectories of `/system`: `lib` for 32-bit apps and `lib64` for 64-bit ones.
Thus appending `/lib` below will fail to load the DSO for a 64-bit app, even if
it exists there, because it will have a different architecture. The quickest fix
is to use `lib64` explicitly for 64-bit Android apps.
=> [2018-10] [Android] Fix runtime loading of DSOs for 64-bit processes

mcs/tools/linker/Makefile
The linker couldn't resolve Xamarin.iOS.dll which System.Net.Http references now.
=> [linker] Fix monotouch tests which need Xamarin.iOS.dll

mono/metadata/object-internals.h, mono/metadata/object.c, mono/mini/driver.c, mono/tests/Makefile.am, mono/tests/module-cctor-entrypoint.il
We need to ensure that any module cctor for the 'main' image
is run *before* we invoke the entry point
This is required in order for tools like Costura
(https://github.com/Fody/Costura) to work properly. These tools inject
a module initializer which sets up event handlers (e.g. AssemblyResolve),
which allows the main method to run properly
For more information about module constructors,
see https://blogs.msdn.microsoft.com/junfeng/2005/11/19/module-initializer-a-k-a-module-constructor/
=> Ensure that the module cctor is run before the entry point is executed

mono/metadata/mono-conc-hash.c, mono/utils/mono-conc-hashtable.c
The tombstone scrubbing fix applied in the past did not work in every case.
Since the key assignment to an element added via mono_conc_hashmap_insert() happens before the tombstone check, the tombstone count remains the same even if a tombstone was replaced. 
In this case the table size check can decide to rehash to the same table size because assuming free spots will become available from not copying over the tombstones. But if all tombstones have been replaced with new elements the fill rate of the hashmap will effectively stay the same, and in the long run rehashing with the same hashmapsize finally leads to a completely filled hashmap.
In the case of a completely filled hashmap looking up an element, not contained in the hashmap, will result in an endless loop because the termination …
=> [2018-10] Fix mono conc hashtable lookup endless loop

mono/metadata/mono-conc-hash.c, mono/utils/mono-conc-hashtable.c
The tombstone scrubbing fix applied in the past did not work in every case.
Since the key assignment to an element added via mono_conc_hashmap_insert() happens before the tombstone check, the tombstone count remains the same even if a tombstone was replaced. 
In this case the table size check can decide to rehash to the same table size because assuming free spots will become available from not copying over the tombstones. But if all tombstones have been replaced with new elements the fill rate of the hashmap will effectively stay the same, and in the long run rehashing with the same hashmapsize finally leads to a completely filled hashmap.
In the case of a completely filled hashmap looking up an element, not contained in the hashmap, will result in an endless loop because the termination …
=> Fix mono conc hashtable lookup endless loop

mono/metadata/mono-conc-hash.c, mono/utils/mono-conc-hashtable.c
The tombstone scrubbing fix applied in the past did not work in every case.
Since the key assignment to an element added via mono_conc_hashmap_insert() happens before the tombstone check, the tombstone count remains the same even if a tombstone was replaced. 
In this case the table size check can decide to rehash to the same table size because assuming free spots will become available from not copying over the tombstones. But if all tombstones have been replaced with new elements the fill rate of the hashmap will effectively stay the same, and in the long run rehashing with the same hashmapsize finally leads to a completely filled hashmap.
In the case of a completely filled hashmap looking up an element, not contained in the hashmap, will result in an endless loop because the termination …
=> [2019-02] Fix mono conc hashtable lookup endless loop

mcs/tools/linker/Makefile
The linker couldn't resolve Xamarin.iOS.dll which System.Net.Http references now.
Backport of #13287.
=> [2019-02] [linker] Fix monotouch tests which need Xamarin.iOS.dll

mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/13297.
=> [jit] Avoid an assert when gsharedvt enums are boxed.

mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/13297.
Backport of #13301.
/cc @vargaz
=> [2019-02] [jit] Avoid an assert when gsharedvt enums are boxed.

mono/metadata/object-internals.h, mono/metadata/object.c, mono/mini/driver.c, mono/tests/Makefile.am, mono/tests/module-cctor-entrypoint.il
Backport #13242 to `2018-10`
---
* Ensure that the module cctor is run before the entry point is executed
We need to ensure that any module cctor for the 'main' image
is run *before* we invoke the entry point
This is required in order for tools like Costura
(https://github.com/Fody/Costura) to work properly. These tools inject
a module initializer which sets up event handlers (e.g. AssemblyResolve),
which allows the main method to run properly
For more information about module constructors,
see https://blogs.msdn.microsoft.com/junfeng/2005/11/19/module-initializer-a-k-a-module-constructor/
* Fix module-cctor-entrypoint.il
=> [2018-10] Ensure that the module cctor is run before the entry point is executed

mono/metadata/object-internals.h, mono/metadata/object.c, mono/mini/driver.c, mono/tests/Makefile.am, mono/tests/module-cctor-entrypoint.il
Backport #13242 to `2019-02`
---
* Ensure that the module cctor is run before the entry point is executed
We need to ensure that any module cctor for the 'main' image
is run *before* we invoke the entry point
This is required in order for tools like Costura
(https://github.com/Fody/Costura) to work properly. These tools inject
a module initializer which sets up event handlers (e.g. AssemblyResolve),
which allows the main method to run properly
For more information about module constructors,
see https://blogs.msdn.microsoft.com/junfeng/2005/11/19/module-initializer-a-k-a-module-constructor/
* Fix module-cctor-entrypoint.il
=> [2019-02] Ensure that the module cctor is run before the entry point is executed

mono/metadata/object-internals.h, mono/metadata/object.c, mono/mini/driver.c, mono/tests/Makefile.am, mono/tests/module-cctor-entrypoint.il
Backport #13242 to `2018-12`
---
* Ensure that the module cctor is run before the entry point is executed
We need to ensure that any module cctor for the 'main' image
is run *before* we invoke the entry point
This is required in order for tools like Costura
(https://github.com/Fody/Costura) to work properly. These tools inject
a module initializer which sets up event handlers (e.g. AssemblyResolve),
which allows the main method to run properly
For more information about module constructors,
see https://blogs.msdn.microsoft.com/junfeng/2005/11/19/module-initializer-a-k-a-module-constructor/
* Fix module-cctor-entrypoint.il
=> [2018-12] Ensure that the module cctor is run before the entry point is executed

mono/metadata/threads.c
When we have 0 threads, most of the bookkeeping code goes a bit off the rails. Rather than hanging (OSX doesn't deliver double fault nowadays), this makes us exit cleanly. 
After: 
```
=================================================================
Telemetry Dumper:
=================================================================
No threads attached to runtime.
=================================================================
External Debugger Dump:
=================================================================
```
=> [crash] Detect when 0 attached threads, fix hang/double-fault.

mono/metadata/class.c, mono/metadata/icall.c
This change makes the underlying cause of #13113 discoverable - a type load error was occurring and instead of surfacing the error we were returning false from IsAssignableFrom, causing mysterious failures in other code.
=> Propagate type load errors out of IsAssignableFrom instead of erroneously returning false

mono/metadata/threads.c
When we have 0 threads, most of the bookkeeping code goes a bit off the rails. Rather than hanging (OSX doesn't deliver double fault nowadays), this makes us exit cleanly. 
After: 
```
=================================================================
Telemetry Dumper:
=================================================================
No threads attached to runtime.
=================================================================
External Debugger Dump:
=================================================================
```
Backport of #13262.
=> [2019-02] [crash] Detect when 0 attached threads, fix hang/double-fault.

mono/metadata/threads.c
When we have 0 threads, most of the bookkeeping code goes a bit off the rails. Rather than hanging (OSX doesn't deliver double fault nowadays), this makes us exit cleanly. 
After: 
```
=================================================================
Telemetry Dumper:
=================================================================
No threads attached to runtime.
=================================================================
External Debugger Dump:
=================================================================
```
Backport of #13262.
=> [2018-10] [crash] Detect when 0 attached threads, fix hang/double-fault.

configure.ac, mono/native/pal_config.h, tools/sgen/sgen-grep-binprot.c
When the configure checks were ported from configure.cmake in corefx a couple of mistakes happened:
- Using AC_TRY_COMPILE instead of AC_TRY_LINK:
CMake's check_c_source_compiles() function compiles *and* links while
AC_TRY_COMPILE only does the former. This hides potential linking issues
which should fail the configure check.
- Using CFLAGS="-Werror -W....":
This works in CMake but autoconf always appends the previously defined
CFLAGS and since we set e.g. `-Wno-undefined` some configure checks
would fail due to an unrelated warning being treated as an error.
We need to only promot specific warnings to errors instead.
While looking at this I also found that we were setting CFLAGS after we already AC_SUBST() it, we need to do this very close to the end of configure.ac. Moved some code …
=> [2018-10][configure.ac] Fix configure checks for Mono.Native

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
Avoid  a double lookup of the reply_packets dictionary.
=> [sdb] Avoid double lookup of reply packets

sdks/wasm/sdk/Mono.WebAssembly.Build/WasmLinkAssemblies.cs
Add the following exclude features when linking through the sdk.
- `--exclude-feature remoting --exclude-feature com --exclude-feature etw`
=> [wasm] Add exclude features option when linking through the sdk.

mcs/class/corlib/corlib.csproj, mcs/class/corlib/unix_build_corlib.dll.sources
We no longer need it since https://github.com/mono/mono/pull/13125 and having it included makes xamarin-macios still complain about the missing symbol.
Backport of #13363.
=> [2019-02] [corlib] Remove Interop.MountPoints.cs from .sources

mcs/class/corlib/corlib.csproj, mcs/class/corlib/unix_build_corlib.dll.sources
We no longer need it since https://github.com/mono/mono/pull/13125 and having it included makes xamarin-macios still complain about the missing symbol.
=> [corlib] Remove Interop.MountPoints.cs from .sources

mono/metadata/loader.c, winconfig.h
Several of the corefx interop sources uses the Unicode names of Win32 symbols. Our current probing implementation on Windows will test the given name last when nomangle is not provided (default). On Windows that will be a large number of probes due to old stdcall name mangling rules. Fix makes sure we first test the symbol against its charset and the given symbol, before trying the stdcall name mangling rules. Will reduce the probing a lot on Windows for corefx Win32 interop classes.
=> Better probing logic on Windows when Unicode Win32 symbols are used.

mono/utils/mono-os-mutex.h
When running multiple threads on a linux-rt kernel, with different priorities, the lack of priority-inheritance
makes the kernel make wrong scheduling choices.
This commit changes the system-wide mutex initializers.
This change protects our system against unexpected latencies in higher priority threads.
=> threads: set mutex PRIO_INHERIT in attribute

mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/ToolLocationHelper.cs
Relates to https://github.com/mono/mono/pull/12619
The methods added will be used by refsrc System.Web.Compliation.AssemblyResolver.  They really don't mean anything in a mono context, so that's why they return empty lists.
=> Add missing refsrc ToolLocationHelper methods 

sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs, sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs
Remove linq usage from WasmHttpMessageHandler
=> Remove linq usage from WasmHttpMessageHandler

mcs/class/System/ReferenceSources/DynamicRoleClaimProvider.cs, mcs/class/System/System.csproj, mcs/class/System/net_4_x_System.dll.sources, mcs/class/corlib/System/AppDomainSetup.cs
This relates to https://github.com/mono/mono/pull/12619
* DynamicRoleClaimProvider to help with legacy role management in web forms
* Added AppDomainManagerAssembly, AppDomainManagerType, and PartialTrustVisibleAssemblies
properties to AppDomainSetup. They don't do anything, but having  them there
helps lessen the amount of change in refsrc System.Web.
=> Add a few properties to AppDomainSetup 

mcs/class/corlib/corert/Decimal.DecCalc.cs, mcs/class/corlib/corert/Decimal.cs
Upstream must have rewritten, because the runtime checks were
replaced with the (not good for Mono) ifdefs.
Not throughly tested, but unbreaks build locally; waiting for CI
to come back with more results.
If it works, could someone get this upstream?
=> Fix System.Decimal regression from .NET Core on big endian

mono/utils/mono-error.h
Warning (at least on Windows) due to unamed struct:
C4201, nonstandard extension used : nameless struct/union
Since the header can be consumed by embedders this warning should be disabled.
=> Fix build warning in mono-error.h.

mono/utils/mono-os-mutex.h, mono/utils/mono-state.c
- sys/sysctl.h isn't available on Alpine and not needed by the code,
guard it using HAVE_SYS_SYSCTL_H like elsewhere (param.h/fcntl.h are already included further above). Added by https://github.com/mono/mono/pull/11855
- pthread_mutexattr_setprotocol doesn't support PTHREAD_PRIO_INHERIT,
check return value. Added by https://github.com/mono/mono/pull/13333
=> Fix build on Alpine Linux

mono/mini/debugger-agent.c
=> [debugger] Fixing two crashes while debugging an Android app.

configure.ac, mono/native/pal_config.h
Port of https://github.com/mono/mono/pull/13351 to master
When the configure checks were ported from configure.cmake in corefx
a couple of mistakes happened:
- Using AC_TRY_COMPILE instead of AC_TRY_LINK:
CMake's check_c_source_compiles() function compiles *and* links while
AC_TRY_COMPILE only does the former. This hides potential linking issues
which should fail the configure check.
- Using CFLAGS="-Werror -W....":
This works in CMake but autoconf always appends the previously defined
CFLAGS and since we set e.g. `-Wno-undefined` some configure checks
would fail due to an unrelated warning being treated as an error.
We need to only promot specific warnings to errors instead.
While looking at this I also found that we were setting CFLAGS after
we already AC_SUBST() it, we need to do this …
=> [configure.ac] Fix configure checks for Mono.Native

configure.ac, mono/native/pal_config.h
Port of #13351 / #13395 to 2019-02
=> [2019-02][configure.ac] Fix configure checks for Mono.Native

mono/mini/debugger-agent.c
=> [2018-10] [debugger] Fixing two crashes while debugging an Android app.

mono/mini/debugger-agent.c
=> [2019-02] [debugger] Fixing two crashes while debugging an Android app.

mono/mini/debugger-agent.c
=> [2018-12] [debugger] Fixing two crashes while debugging an Android app.

mono/metadata/threadpool-io.c
The format string was incorrect in this case, which leads to a crash
in Unity. Simply remove the unused `%s` format specifier here.
=> Fix a possible crash while printing a warning

mono/mini/intrinsics.c
This reverts commit c99fe4b4628817d9872172ff8e4b73b4f69bcf9e.
It doesn't work when LLVM is enabled for tvOS: https://github.com/xamarin/xamarin-macios/pull/5742#issuecomment-471007078, it causes multiple compilation errors like this:
Process exited with code 1, command:
/Applications/Xcode101.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -isysroot /Applications/Xcode101.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.1.sdk -Qunused-arguments -mtvos-version-min=12.1 -fembed-bitcode-marker -arch arm64 -c -o /private/var/folders/nh/n1y9qj2n40d7wpmx1mg9blg80000gn/T/mtouch.cache/arpl1vgs.js6/arm64/Xamarin.TVOS.dll-llvm.o -x assembler /private/var/folders/nh/n1y9qj2n40d7wpmx1mg9blg80000gn/T/mtouch.cache/arpl1vgs.js6/arm64/Xamarin.TVOS.dl …
=> [2019-02] Revert "[mini] Inline Selector.GetHandle for tvOS and watchOS assemblies as well. (#13246)"

mono/mini/intrinsics.c
This reverts commit c99fe4b4628817d9872172ff8e4b73b4f69bcf9e.
It doesn't work when LLVM is enabled for tvOS: https://github.com/xamarin/xamarin-macios/pull/5742#issuecomment-471007078, it causes multiple compilation errors like this:
Process exited with code 1, command:
/Applications/Xcode101.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -isysroot /Applications/Xcode101.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.1.sdk -Qunused-arguments -mtvos-version-min=12.1 -fembed-bitcode-marker -arch arm64 -c -o /private/var/folders/nh/n1y9qj2n40d7wpmx1mg9blg80000gn/T/mtouch.cache/arpl1vgs.js6/arm64/Xamarin.TVOS.dll-llvm.o -x assembler /private/var/folders/nh/n1y9qj2n40d7wpmx1mg9blg80000gn/T/mtouch.cache/arpl1vgs.js6/arm64/Xamarin.TVOS.dl …
=> Revert "[mini] Inline Selector.GetHandle for tvOS and watchOS assemblies as well. (#13246)"

mono/metadata/mono-config.c
On Windows MSVC build this cause:
warning C4459: declaration of 'mono_cfg_dir' hides global declaration
=> Fix build warning, local variable hides global.

mono/metadata/class-init.c
Writing to MonoClass:interface_id must be done with the loader lock held.
Fixes assertion:
```
* Assertion at class-init.c:1830, condition `i == 0 || interfaces_full [i]->interface_id >= interfaces_full [i - 1]->interface_id' not met
```
Backport of #13427.
=> [2019-02] [class-init] Take loader lock around mono_class_setup_interface_id_internal

mono/metadata/class-init.c
Writing to MonoClass:interface_id must be done with the loader lock held.
Fixes assertion:
```
* Assertion at class-init.c:1830, condition `i == 0 || interfaces_full [i]->interface_id >= interfaces_full [i - 1]->interface_id' not met
```
=> [class-init] Take loader lock around mono_class_setup_interface_id_internal

configure.ac
Regression in SIMD test on Windows x64 LLVM after https://github.com/mono/mono/commit/2eeaf888c1d0a681c8705bd609f76196d8fb82ed
=> Fix error in SIMD test on Windows x64 LLVM due to changed llc defaults.

mono/dis/get.c, mono/metadata/class.c, mono/metadata/debug-helpers.c, mono/metadata/icall.c, mono/metadata/marshal.c, mono/metadata/metadata-internals.h, mono/metadata/metadata.c, mono/metadata/reflection.c, mono/metadata/sre-encode.c, mono/metadata/sre.c, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/tests/Makefile.am, mono/tests/custom-modifiers-append.1.il, mono/tests/custom-modifiers-lib.il, mono/tests/custom-modifiers.2.cs
This all stems from ECMA 335, 7.1.1:
> The CLI itself shall treat required and optional modifiers in the same
> manner. Two signatures that differ only by the addition of a custom
> modifier (required or optional) shall not be considered to match. Custom
> modifiers have no other effect on the operation of the VES.
This rule means that when comparing signatures, we have to treat two types that
differ only in their custom modifiers as distinct. In particular, we have to do
this when comparing signatures in order to fill in the vtable for a class.  And
moreover, we have to concatenate custom modifiers when doing generic
instantiation.  If a method in a generic type has signature `T modopt(IsConst)
Method()` and we instantiate T with `int32 modopt(IsLong)`, we are expected to
produce the …
=> Custom modifier equivalence, duplication, appending and inflation

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/AssemblyMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs, mono/metadata/mono-debug.c, mono/mini/debugger-agent.c
This PR adds a new property to AssemblyMirror. This will allow us to optimize the treatment of assemblies with and without debug information in our debugger client.
=> [sdb] Add property AssemblyMirror.HasDebugInfo

mono/mini/intrinsics.c
This reverts commit c99fe4b4628817d9872172ff8e4b73b4f69bcf9e.
It doesn't work when LLVM is enabled for tvOS: https://github.com/xamarin/xamarin-macios/pull/5742#issuecomment-471007078, it causes multiple compilation errors like this:
Process exited with code 1, command:
/Applications/Xcode101.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -isysroot /Applications/Xcode101.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.1.sdk -Qunused-arguments -mtvos-version-min=12.1 -fembed-bitcode-marker -arch arm64 -c -o /private/var/folders/nh/n1y9qj2n40d7wpmx1mg9blg80000gn/T/mtouch.cache/arpl1vgs.js6/arm64/Xamarin.TVOS.dll-llvm.o -x assembler /private/var/folders/nh/n1y9qj2n40d7wpmx1mg9blg80000gn/T/mtouch.cache/arpl1vgs.js6/arm64/Xamarin.TVOS.dl …
=> [2018-10] Revert "[mini] Inline Selector.GetHandle for tvOS and watchOS assemblies as well. (#13246)"

configure.ac
Turns out that https://github.com/mono/mono/pull/13444 didn't solve the issue fully since mini regression tests are not using the AOT_BUILD_FLAGS variable set in configure script. The mini regression tests do however use the values in the INVARIANT_AOT_OPTION, so adding the llcopt into that will make sure the flag ends up in mini regression tests as well as other CI test suites.
=> Fix missing llc options for Windows x64 full AOT + LLVM mini regression tests.

netcore/sample/Makefile
It fixes "EntryPointNotFound" exceptions for a simple `System.Console.WriteLine(DateTime.Now);` because of https://github.com/dotnet/corefx/pull/35904/files
the newer sdk brings newer System.Native.
=> [netcore] bump netcore sdk version

mono/mini/calls.c, mono/mini/method-to-ir.c, mono/mini/mini.h
Fixes Xamarin.Tests.Misc.PublicSymbols test with 2019-02 integration: https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/9524/Test_20Report/
=> [mini] remove public symbol helper_sig_llvmonly_imt_trampoline

packaging/MacSDK/profile.py
Problem is that https://github.com/mono/bockbuild/blob/14535c270ea9f8d536efe6852700d8d1cb657c1f/packages/gtk%2B.py#L4 passes `gtk` for repository name to `GitHubPackage` which then uses this as package name. So when it's decided if `-g` should be added at https://github.com/mono/bockbuild/blob/5c2378112dc681cea0aa5c2447661fb13adbc46b/bockbuild/darwinprofile.py#L158-L159 it's false hence GTK assemblies don't get debug symbols.
=> Fix generating `.dSYM` for GTK assemblies

mono/eglib/eglib-remap.h
They fail a xamarin-macios public symbols check otherwise (monoeg_ is whitelisted).
=> [eglib] Remap g_utf16_len and g_utf16_len to monoeg_ prefix

configure.ac
Since Boehm is not supported on Windows x64 we should set sgen as default
GC instead of forcing the use of --disable-bohem.
=> Default to sgen on Windows x64.

scripts/Makefile.am
NUnit bundle is gone, these scripts are empty and useless
```
10:27:45  DEBUG: Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/mono-core-6.1.0.462-0.nightly.1.epel6.x86_64
10:27:45  DEBUG: BUILDSTDERR: error: Installed (but unpackaged) file(s) found:
10:27:45  DEBUG: BUILDSTDERR:    /usr/bin/nunit-console
10:27:45  DEBUG: BUILDSTDERR:    /usr/bin/nunit-console2
10:27:45  DEBUG: BUILDSTDERR:    /usr/bin/nunit-console4
10:27:45  DEBUG: RPM build errors:
10:27:45  DEBUG: BUILDSTDERR:     Installed (but unpackaged) file(s) found:
10:27:45  DEBUG: BUILDSTDERR:    /usr/bin/nunit-console
10:27:45  DEBUG: BUILDSTDERR:    /usr/bin/nunit-console2
10:27:45  DEBUG: BUILDSTDERR:    /usr/bin/nunit-console4
```
=> Don't produce nunit-console scripts in bin/

mcs/class/System.Windows.Forms/System.Windows.Forms/SplitContainer.cs
=> [SWF] Fix Stackoverflow SplitContainer`s SplitterDistance set in SplitterMoved

netcore/excludes-System.Runtime.Tests.rsp, netcore/gen-xunit-runner/Program.cs
As you can see here https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/Reflection/AssemblyFlagsAttributeTests.cs#L19
InlineData contains enums and an integer, without this change that integer will cause a compilation error (runner.cs).
Found and tested against the latest CoreFX repo 
```
RUN: 6261
FAILURES: 6
SKIPPED: 184
```
=> [netcore] Fix case when InlineData's type != ParameterType

netcore/Makefile
Don't download .NET Core sdk if it's already downloaded on `make prepare`
=> [netcore] Don't download .NET Core sdk if it's already downloaded 

msvc/scripts/tests/build-full-aot-regression-tests-asmonly-llvm.bat, msvc/scripts/tests/build-full-aot-regression-tests-asmonly.bat, msvc/scripts/tests/build-full-aot-regression-tests-dynamic-llvm.bat, msvc/scripts/tests/build-full-aot-regression-tests-dynamic.bat, msvc/scripts/tests/build-full-aot-regression-tests-static-llvm.bat, msvc/scripts/tests/build-full-aot-regression-tests-static.bat, msvc/scripts/tests/build-full-aot-regression-tests.bat, msvc/scripts/tests/run-full-aot-regression-tests.bat, msvc/scripts/tests/run-jit-regression.bat, msvc/scripts/tests/run-jit.bat
* Only do clean/rebuild when an assembly changed.
* Add wrappers for different full AOT build configurations.
* Make scripts callable from different working directory.
=> Windows full AOT build scripts update.

configure.ac, mono/metadata/threads.c, mono/mini/mini-runtime.c
=> [netcore] Disable runtime cleanup on netcore, coreclr does not cleanup either. Also disable aborting background threads, its no longer needed.

mono/metadata/object.c
Fixes part of https://github.com/mono/mono/issues/13374.
=> [runtime] Avoid putting non-virtual and non-static DIM methods into vtables, roslyn generates these for private property accessors.

mono/metadata/loader.c, mono/tests/Makefile.am, mono/tests/dim-sealed.il
```
interface I1
{
sealed void M1()
{
System.Console.WriteLine(“M1”);
}
}
interface I2 : I1
{
static void Test<T>(T x) where T : I2
{
x.M1();
}
}
class A : I2
{
{
I2.Test(new A());
}
}
```
When an interface implements a sealed method, this method is not virtual, so it will not be available at vtable. But in the IL the call is a virtual call, but in this case we don't need to search at vtable.
Fixes #13466
=> [dim] Interface with sealed method

mono/utils/mono-state.c
This is helpful by allowing the crash reporter to work even while unable to write to the working directory.
Backport of #13447.
=> [2019-02] [crash] Fallback to MAP_ANONYMOUS for allocator

mono/utils/mono-state.c
This is helpful by allowing the crash reporter to work even while unable to write to the working directory.
Backport of #13447.
=> [2018-10] [crash] Fallback to MAP_ANONYMOUS for allocator

mono/utils/mono-state.c
This is helpful by allowing the crash reporter to work even while unable to write to the working directory.
Backport of #13447.
=> [2018-08] [crash] Fallback to MAP_ANONYMOUS for allocator

mono/mini/aot-compiler.c
In https://github.com/mono/mono/pull/11172 we added passing `-march=arm` to `llc`, so that newer LLVM would generate code correctly for the target arch. Unfortunately this seems to break older LLVM, that is still used for 32bit code on Xamarin.iOS. For iOS we need to force it to armv7, otherwise it will try to substitute certain locking primitives with builtins that aren't available as hardware instructions on armv5.
Before this change:
```console
$ nm ./obj/iPhone/Release/mtouch-cache/armv7/mscorlib.dll-llvm.o | grep sync_
U ___sync_fetch_and_add_4
U ___sync_lock_test_and_set_4
U ___sync_synchronize
U ___sync_val_compare_and_swap_4
00079e1c T _mscorlib_System_Runtime_CompilerServices_AsyncMethodBuilderCore_ThrowAsync_System_Exception_System_Threading_SynchronizationContext
00057f80 T …
```
=> [aot] force v7 on arm when using LLVM on iOS

mono/mini/aot-compiler.c
In https://github.com/mono/mono/pull/11172 we added passing `-march=arm` to `llc`, so that newer LLVM would generate code correctly for the target arch. Unfortunately this seems to break older LLVM, that is still used for 32bit code on Xamarin.iOS. For iOS we need to force it to armv7, otherwise it will try to substitute certain locking primitives with builtins that aren't available as hardware instructions on armv5.
Before this change:
```console
$ nm ./obj/iPhone/Release/mtouch-cache/armv7/mscorlib.dll-llvm.o | grep sync_
U ___sync_fetch_and_add_4
U ___sync_lock_test_and_set_4
U ___sync_synchronize
U ___sync_val_compare_and_swap_4
00079e1c T _mscorlib_System_Runtime_CompilerServices_AsyncMethodBuilderCore_ThrowAsync_System_Exception_System_Threading_SynchronizationContext
00057f80 T …
```
=> [2019-02] [aot] force v7 on arm when using LLVM on iOS

netcore/gen-xunit-runner/Program.cs
I could not run tests because of it (I guess the typo was made when gen-xunit-runner was rewritten to use Roslyn instead of CodeDom).
=> [netcore] fix typo

netcore/gen-xunit-runner/Program.cs
Some literals have suffixes like:
float a = 0.1f;
long c = 0.1L;
etc
byte, sbyte, uint, short, ushort don't have them.
This PR fixes ~100 failing test because of incorrect codegen.
E.g. for https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/ByteTests.cs#L45 
we generate `255` which is int32 and can be successfully unboxed later in the test.
BTW, I don't know how to generate 'short' instead of 'System.Int16' using Roslyn API so I went with strings.
=> [netcore] gen-xunit-project generates incorrect literals for some types

mcs/ilasm/codegen/TypeDef.cs
When it is a sealed method in Interface it's not Static nor Virtual and shouldn't add virtual.
Fixes #13508
=> [ILAsm] Remove 'virtual' attribute that is being added to sealed default interface methods

mcs/class/System.Private.CoreLib/System/Buffer.cs
It fixes ~226 tests added in https://github.com/mono/mono/pull/13543
=> [netcore] Allow all primitive types to be passed to Buffer.BlockCopy

mono/utils/mono-state.c
The crash this fixes should have been fixed in https://github.com/mono/mono/pull/13503. When I tested it locally on Linux it was working. 
When I did a prolonged test by triggering a package build and testing with VS4M, it didn't work. Perhaps I failed to correctly inject the open() failure that VS4M encounters. 
This is a hotfix of a previous patch. 
Confirmed to be working. The VS4M MERP dialog box popped up with this JSON:
https://gist.github.com/alexanderkyte/89da7afb6019572ea4fe026ea715b05a
=> [2018-08][merp] Fix anon allocation, use MAP_PRIVATE

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
1. aot-compiler: don't leak `MonoCustomAttrInfo`
2. aot-runtime: don't leak sigs when decoding wrapper references.  All of these cases we decode a sig (which uses malloc), and then call some method that immediately calls `mini_get_underlying_signature` which dups the sig, so the one from the decode isn't needed anymore.
=> [aot] Fix a few memory leaks

mono/mini/ssa.c
Consider
```
BB4:  // successor BB5, BB9
[...]
br [B9]
BB5: // catch handler block for BB4
[...]
br BB9
BB9:
aotconst R90
gc_safe_point R90
[...]
```
Previously, our invariant code motion pass would move `aotconst R90` to the end of BB4. Unfortunately, BB4 contains instructions that can cause an exception and thus control flow is broken and continues to BB5. `aotconst R90` wouldn't be loaded correctly in this scenario.
When lowered to LLVM IR this is more obvious, and the verification pass of LLVM catches this.
Fixes https://github.com/mono/mono/issues/13460
=> [ssa] avoid code motion to try-blocks

msvc/scripts/genconsts.cs, msvc/winsetup.bat
When logic moved from winsetup.bat into an msbuild task that changed the console output of winsetup.bat causing problems for genconst to find MONO_VERSION and MONO_CORLIB_VERSION. There was also a potential problem where winsetup.bat couldn't find msbuild.exe if not included in PATH.
This fix makes sure winsetup.bat detect and setup a full msbuild environment before running msbuild.exe. It also change genconsts to look at the generated config.h for the correct values of MONO_VERSION and MONO_CORLIB_VERSION that will be used by the runtime builds.
Should fix https://github.com/mono/mono/issues/13533.
=> Adjust genconst to changes in winsetup.bat.

mono/mini/mini-llvm.c
This can be useful for debugging issues in the products.
=> [llvm] dump bitcode file even if verifier fails

mono/utils/mono-state.c
The crash this fixes should have been fixed in https://github.com/mono/mono/pull/13503. When I tested it locally on Linux it was working. 
When I did a prolonged test by triggering a package build and testing with VS4M, it didn't work. Perhaps I failed to correctly inject the open() failure that VS4M encounters. 
This is a hotfix of a previous patch. 
Confirmed to be working. The VS4M MERP dialog box popped up with this JSON:
https://gist.github.com/alexanderkyte/89da7afb6019572ea4fe026ea715b05a
Backport of #13538.
=> [runtime] Fix anon allocation, use MAP_PRIVATE

mono/utils/mono-state.c
The crash this fixes should have been fixed in https://github.com/mono/mono/pull/13503. When I tested it locally on Linux it was working. 
When I did a prolonged test by triggering a package build and testing with VS4M, it didn't work. Perhaps I failed to correctly inject the open() failure that VS4M encounters. 
This is a hotfix of a previous patch. 
Confirmed to be working. The VS4M MERP dialog box popped up with this JSON:
https://gist.github.com/alexanderkyte/89da7afb6019572ea4fe026ea715b05a
Backport of #13538.
=> [2019-02] [2018-08][merp] Fix anon allocation, use MAP_PRIVATE

mcs/class/System.Private.CoreLib/System.Threading/ThreadPool.cs, mcs/class/referencesource/mscorlib/system/threading/threadpool.cs, mono/metadata/domain.c
Now I am able to run xunit tests directly.
I mostly copied missing bits from old threadpool.
(In theory we need to use ThreadPool.Portable.cs, am I right?)
Managed to run 29808 xunit tests directly without the gen-xunit-proj in System.Runtime.Tests,
it crashes on `PointerFieldGetValue` which I guess should be skipped on mono (see https://github.com/mono/corefx/blob/master/src/System.Runtime/tests/System/Reflection/PointerTests.cs#L128)
I think we need to upstream all mono-runtime specific [Skip]s from mono/corefx to dotnet/corefx
=> [netcore] Implement missing bits in ThreadPool

mono/utils/mono-state.c
The crash this fixes should have been fixed in https://github.com/mono/mono/pull/13503. When I tested it locally on Linux it was working. 
When I did a prolonged test by triggering a package build and testing with VS4M, it didn't work. Perhaps I failed to correctly inject the open() failure that VS4M encounters. 
This is a hotfix of a previous patch. 
Confirmed to be working. The VS4M MERP dialog box popped up with this JSON:
https://gist.github.com/alexanderkyte/89da7afb6019572ea4fe026ea715b05a
Backport of #13538.
=> [2018-10][merp] Fix anon allocation, use MAP_PRIVATE

mono/mini/exceptions.cs, mono/mini/mini-arm.c
```
18 int_sbb R77 <- R54 R57
19 store_membase_reg [arm_fp + 0x24] <- R77
20 cond_exc_c OverflowException
```
this wasn't properly handled by the arch lowering pass.
Fixes https://github.com/mono/mono/issues/13284
=> [arm] respect potential spilling for overflow flag check

mono/mini/aot-compiler.c, mono/mini/mini-llvm.c, mono/mini/mini-llvm.h
- Enable MSVC objects on LLVM >= 6.00
- Always used PIC relocation-model on Windows x64 due to LLVM problem with
static triggering incorrect ADDR32 relocation entries in 64-bit objects.
- Add CodeView symbol format instead of DWARF for Windows x64.
- Fix LLVM outfile when doing static link to not end up in temp directory.
- Only add /DEFAULTLIB when using MSVC and not doing static compile. For static compile the needed libraries must be added when objects get's linked and since the needed libraries are c-runtime libraries, should be transparent for most applications consuming the object files.
=> Couple of fixes to LLVM AOT compiler on Windows x64.

mono/mini/ssa.c
Consider
```
BB4:  // successor BB5, BB9
[...]
br [B9]
BB5: // catch handler block for BB4
[...]
br BB9
BB9:
aotconst R90
gc_safe_point R90
[...]
```
Previously, our invariant code motion pass would move `aotconst R90` to the end of BB4. Unfortunately, BB4 contains instructions that can cause an exception and thus control flow is broken and continues to BB5. `aotconst R90` wouldn't be loaded correctly in this scenario.
When lowered to LLVM IR this is more obvious, and the verification pass of LLVM catches this.
Fixes https://github.com/mono/mono/issues/13460
Backport of #13555.
/cc @lewurm
=> [2019-02] [ssa] avoid code motion to try-blocks

mono/mini/calls.c, mono/tests/llvmonly-mixed/interponly.cs, mono/tests/llvmonly-mixed/tests.cs
Fixes https://github.com/mono/mono/issues/13463.
=> [llvmonly] Add gsharedvt in wrappers to calls which could go to the interpreter.

netcore/Makefile
Use actual `xunit.console.dll` console runner from the CoreFX repo to run tests.
`System.Collections.Tests` works fine, `System.Runtime.Tests` crashes after a while
Usage:
```
make run-xunit TEST_ASSEMBLY=path-to-tests.dll COREFX_ROOT=corefx-repo
```
Closing https://github.com/mono/mono/pull/13573
=> [netcore] Xunit console runner

mono/tests/test-runner.cs
Helix wasn't running our runtime tests as expected, because the test runner expected newline-separated tests to run, and we were generating space-separated.
Following "be liberal in what you accept" philosophy, and to prevent this issue in the future, just deal with "whitespace separated" rather than "this specific whitespace and no other"
=> Make test runner able to deal with whitespace patterns other than newline

mono/tests/test-runner.cs
Helix wasn't running our runtime tests as expected, because the test runner expected newline-separated tests to run, and we were generating space-separated.
Following "be liberal in what you accept" philosophy, and to prevent this issue in the future, just deal with "whitespace separated" rather than "this specific whitespace and no other"
Backport of #13587.
=> [2019-02] Make test runner able to deal with whitespace patterns other than newline

mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/13455.
=> [aot] Avoid an assert which can happen in normal usage.

mono/mini/debugger-agent.c
=> [2018-08] [debugger] Fixing two crashes while debugging an Android app.

mono/mini/aot-compiler.c
I missed something in the code review for #13581.  Need to cleanup MonoError if it's not ok.
=> [aot] cleanup MonoError in add_extra_method_with_depth

mono/mini/exceptions.cs, mono/mini/mini-arm.c
```
18 int_sbb R77 <- R54 R57
19 store_membase_reg [arm_fp + 0x24] <- R77
20 cond_exc_c OverflowException
```
this wasn't properly handled by the arch lowering pass.
Fixes https://github.com/mono/mono/issues/13284
Backport of #13564.
/cc @lewurm
=> [2019-02] [arm] respect potential spilling for overflow flag check

mono/metadata/marshal.h
This should fix the error seen when using the loaded-llvm configuration. 
```
root@breakfast:/# mono --aot=llvm /tmp/hello.exe 
Mono Ahead of Time compiler - compiling assembly /tmp/hello.exe
AOTID CA786163-28F4-6B55-13D1-2E3569054BE8
mono: symbol lookup error: /usr/lib/libmono-llvm.so: undefined symbol: mono_marshal_get_aot_init_wrapper_name
```
=> [runtime] Add MONO_LLVM_INTERNAL to *get_aot_init_wrapper* marshal funcs

sdks/wasm/Makefile
This update restores the ability to use the packager outside of the mono source tree.
=> [wasm] Include the corebindings.c in the package output

mono/metadata/cominterop.c
The function `cominterop_get_interface` in `mono/metadata/cominterop.c` had a number of changes made to it in 18b6846a3a2218525b7335a1f0515de93a1e44ca.
One of these seems to have missed a `return itf;` statement preceding `HANDLE_FUNCTION_RETURN_VAL`. Since `HANDLE_FUNCTION_RETURN_VAL` is meant to clean up the handle created in this function, this'd lead to a leaking handle.
This mainly hurt when running COM interface routines from finalizers, since the finalizer thread would end up owning a GC handle, and then hitting an assertion expecting the handle stack to be empty, but would be practically unnoticeable otherwise.
=> Fix handle leak in cominterop

mcs/class/System.Private.CoreLib/System.IO/Stream.cs, mcs/class/System.Private.CoreLib/System.Runtime.InteropServices/Marshal.cs
Needed for MSBuild.
Stream changes were copied from [CoreRT](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/IO/Stream.CoreRT.cs).
IsPinnable - perhaps it should be an icall/intrinsics for better perf?
[CoreCLR impl for IsPinnable (InternalCall)](https://github.com/dotnet/coreclr/blob/1f3f474a13bdde1c5fecdf8cd9ce525dbe5df000/src/vm/marshalnative.cpp#L257)
[CoreRT impl for IsPinnable](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs#L114) (and [MightBeBlittable](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Runtime/InteropServices/InteropExtensions.cs#L60))
=> [netcore] Marshal.IsPinnable

configure.ac, msvc/mono.winconfig.targets
Not just a guid or an uppercase guid.
=> [windows]Fix and cleanup configure.ac parsing for MONO_CORLIB_VERSION and AC_INIT.

mcs/class/corlib/Test/System.Threading/ManualResetEventSlimTests.cs
When running this test, ManualResetSlimTest on Windows on a machine with free cores during the test run, the SpinOnce's default value will be to low forcing the thread into frequent sleep(1) scenario, causing long execution times. This PR set count to 100 for the test (default 20) before SpinOnces will hit sleep(1. This will run the test much quicker on machines with idle cores.
=> Increase spin-count on test to not end up in frequent sleeps on multicore machines.

man/mono.1, mono/mini/driver.c, mono/utils/mono-mmap.c, mono/utils/mono-mmap.h
This is surfaced via a command line option, to not make this a strong API requirement on Xamarin.Mac requiring it.   See companion patch:
=> Do not use MAP_JIT by default

mcs/class/corlib/System/TimeZoneInfo.WinRT.cs
Needed by tests when hitting fallback solution in TimeZoneInfo.WinRT.cs. Fix also sort the TimeZones similar to how its done in .NET Framework/Core.
=> Add UTC timezone in WinRT GetSystemTimeZones fallback implementation.

man/mono.1, mono/mini/driver.c, mono/utils/mono-mmap.c, mono/utils/mono-mmap.h
This is surfaced via a command line option, to not make this a strong API requirement on Xamarin.Mac requiring it.   See companion patch:
Backport of #13446.
=> [2019-02] Do not use MAP_JIT by default

man/mono.1, mono/mini/driver.c, mono/utils/mono-mmap.c, mono/utils/mono-mmap.h
Reverts mono/mono#13446 as it breaks the build
=> Revert "Do not use MAP_JIT by default"

netcore/Makefile, netcore/excludes-System.Runtime.Tests.rsp
Now it correctly loads *.rsp files (list of tests to ignore).
Also, had to disable a few tests due to runtime crashes.
Renamed from `run-xunit` because there is already `run-%`.
1) **System.Collections.Tests**
```
make xtest-System.Collections.Tests COREFX_ROOT=/prj/corefx-egor
total="30406" failures="8" skipped="78"
```
2) **System.Runtime.Tests**
```
make xtest-System.Runtime.Tests COREFX_ROOT=/prj/corefx-egor
total="30706" failures="772" skipped="9"
```
_(most of the failures are RemoteTestExecutor related)_
3) **System.Reflection.Emit.Lightweight.Tests**
```
make xtest-System.Reflection.Emit.Lightweight.Tests COREFX_ROOT=/prj/corefx-egor
total="74" failures="22" skipped="0"
```
4) **System.Reflection.Emit.Tests**
```
make xtest-System.Reflection.Emit.Tests COREFX_ROOT=/prj/corefx-egor …
```
=> [netcore] Improve xunit console runner

sdks/wasm/packager.cs
when runtime.js is generated.
Reported by @jeromelaban on mono-community.
=> [wasm] [packager] Remove the unnecessary call to add_bindings()

mono/arch/amd64/amd64-codegen.h, mono/mini/cpu-amd64.md, mono/mini/mini-amd64.c, mono/mini/mini-ops.h
Consider
```
xor %r15, %r15       // %r15 = 0x0
dec %r15d            // %r15 = 0xffff_ffff
lea 0x1(%r15), %rdx  // %rdx = 0x1_0000_0000 but should be 0x0
```
instead `lea 0x1(%r15), %edx` should be generated.
Fixes #13452
Fixes #13597
=> [amd64] use 32bit variant of lea_membase for 32bit operations

mono/arch/amd64/amd64-codegen.h, mono/mini/cpu-amd64.md, mono/mini/mini-amd64.c, mono/mini/mini-ops.h
Consider
```
xor %r15, %r15       // %r15 = 0x0
dec %r15d            // %r15 = 0xffff_ffff
lea 0x1(%r15), %rdx  // %rdx = 0x1_0000_0000 but should be 0x0
```
instead `lea 0x1(%r15), %edx` should be generated.
Fixes #13452
Fixes #13597
Backport of #13642.
/cc @lewurm
=> [2018-10] [amd64] use 32bit variant of lea_membase for 32bit operations

mono/arch/amd64/amd64-codegen.h, mono/mini/cpu-amd64.md, mono/mini/mini-amd64.c, mono/mini/mini-ops.h
Consider
```
xor %r15, %r15       // %r15 = 0x0
dec %r15d            // %r15 = 0xffff_ffff
lea 0x1(%r15), %rdx  // %rdx = 0x1_0000_0000 but should be 0x0
```
instead `lea 0x1(%r15), %edx` should be generated.
Fixes #13452
Fixes #13597
Backport of #13642.
/cc @lewurm
=> [2019-02] [amd64] use 32bit variant of lea_membase for 32bit operations

mono/arch/amd64/amd64-codegen.h, mono/mini/cpu-amd64.md, mono/mini/mini-amd64.c, mono/mini/mini-ops.h
Consider
```
xor %r15, %r15       // %r15 = 0x0
dec %r15d            // %r15 = 0xffff_ffff
lea 0x1(%r15), %rdx  // %rdx = 0x1_0000_0000 but should be 0x0
```
instead `lea 0x1(%r15), %edx` should be generated.
Fixes #13452
Fixes #13597
Backport of #13642.
/cc @lewurm
=> [2018-08] [amd64] use 32bit variant of lea_membase for 32bit operations

mono/mini/generics.cs, mono/mini/mini-llvm.c, mono/mini/mini.h
=> [2019-02] [llvm] Fix the computation of size of gshared instances in emit_args_to_vtype ().

mono/mini/generics.cs, mono/mini/mini-llvm.c, mono/mini/mini.h
=> [llvm] Fix the computation of size of gshared instances in emit_args_to_vtype ().

mono/mini/intrinsics.c
Before the intrinsic implemented
```
ldarg.0
ldarg.1
sizeof !!T
mul
conv.i
add
ret
```
now it implements
```
ldarg.0
ldarg.1
sizeof !!T
conv.i
mul
add
ret
```
`conv.i` and `mul` have been swapped. Also see https://github.com/mono/mono/pull/13609
=> [intrinsics] sync implementation with IL code

mcs/class/System.Private.CoreLib/System/Array.cs, netcore/Makefile
```
make xtest-System.Runtime.Tests FIXTURE="-method System.Tests.ArrayTests.*"
```
Before:
```
Total: 2045, Errors: 0, Failed: 366, Skipped: 0, Time: 1.220s
```
After:
```
Total: 2045, Errors: 0, Failed: 223, Skipped: 0, Time: 1.188s
```
Most of the failures in ArrayTests are (un)expected `ArrayTypeMismatchException` (in Array.Copy?)
Also, it seems it's possible to move a bit more pieces from Array.CoreCLR.cs to the shared.
E.g. `Array.Clear` and this one (without the fast-path).
=> [netcore] Implement Array.Sort

mono/mini/generics.cs, mono/mini/mini-llvm.c, mono/mini/mini.h
Backport of #13659 to `2018-08`
/cc @vargaz
=> [2018-08] [llvm] Fix the computation of size of gshared instances in emit_args_to_vtype ().

mono/mini/generics.cs, mono/mini/mini-llvm.c, mono/mini/mini.h
Backport of #13659 to `2018-08`
/cc @vargaz 
Backport of #13675.
=> [2018-10] [llvm] Fix the computation of size of gshared instances in emit_args_to_vtype ().

configure.ac, mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mcs/class/corlib/System.Reflection.Emit/TypeBuilder.cs, mcs/class/corlib/System.Reflection.Emit/TypeBuilderInstantiation.cs, mcs/class/corlib/System/AppDomain.cs, mono/metadata/appdomain.c
* Instead of having one `AppDomain.DoTypeResolve(object)` that checks at runtime whether the argument is a `string` or a `TypeBuilder`, use two strongly-typed methods `DoTypeResolve(string)` and `DoTypeBuilderResolve(TypeBuilder)`.
* Add both to the `corlib/LinkerDescriptor/mscorlib.xml`.
* Adjust the code in `appdomain.c` accordingly.
* Bump corlib version.
This is part of a larger on-going project to improve the linker logic.
The rationale behind this is that the new `AppDomain.DoTypeResolve(string)` that is being called from `mono_domain_try_type_resolve_name()` should not reference `TypeBuilder`, to allow the linker to remove some of the `System.Reflection.Emit` types.
=> Split `AppDomain.DoTypeResolve(object)` into two stongly-typed methods.

.gitmodules, configure.ac, mcs/packages/csi-test.csx
This PR tests bumping our default roslyn to a recent version.
=> Bump roslyn binaries to 3.1.0 and add VBCSCompiler.exe to the set of paths auto-detected by configure.ac

mcs/class/corlib/Test/System.IO/FileTest.cs
When we switched to using the corefx System.IO.File implementation we also switched to an implementation that uses the `copyfile()` standard library call on macOS/iOS to copy files. This should preserve file metadata such as timestamps.
However there's a small edge case: when using an older version of the iOS Simulator < 11.0 the `copyfile()` call doesn't copy sub-second timestamps, presumably because older iOS ran on HFS which doesn't support that.
When we run this simulator on modern macOS which uses APFS and thus supports sub-second timestamps the origin file used for the test _does_ have sub-second timestamps and the test would fail.
We now skip the test in such environments.
PS: why did this not fail with the old Mono implementation? We used to always call utimes() on the destination …
=> [corlib] Skip FileTest.LastWriteTimeSubMsCopy on older iOS Simulators

mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/ComboBoxTest.cs
If combobox already was disposed and we setting Text field there will be NullReferenceException. On .net winforms there no excetions.
=> Fix NRE when combobox was disposed and Text set

netcore/Makefile, netcore/dl-test-assets.py
Use them in gen-xunit-runner. Note that COREFX_ROOT is still required since the test assemblies reference assemblies from
the corefx sdk dir.
=> [netcore] Download test assets from the dotnet-core blob feed.

mcs/class/corlib/Test/System.Runtime.InteropServices/MarshalTest.cs
Make sure the correct free method is called for strings allocated by StringToAllocatedMemoryUTF8 or StringToCoTaskMemUTF8, ZeroFreeCoTaskMemUTF8. Using incorrect free method will lead to heap corruption on platforms where CoTaskMem is backed by a different heap compared to HGlobal.
StringToAllocatedMemoryUTF8 has been renamed in corefx to StringToCoTaskMemUTF8, so switch to that method for allocation call.
=> Fix incorrect use of FreeHGlobal on Marshal UTF8 string test.

mono/metadata/w32process-unix.c
When you use `Process.Start()` with `UseShellExecute=true` (which is the default on Mono/.NET Framework, but false on .NET Core) then we'd still try to first start the file directly, before falling back to trying the "open" handlers like xdg-open to launch the file.
Presumably we do this so that on mobile you can still start a process without needing to explicitly set `UseShellExecute=false`.
However we don't need to try the fallback on iOS/Android since the "open" handlers won't work there anyway.
This recently showed up on the Xamarin.iOS Mono 2019-02 integration where we started running the `System.Diagnostics.ProcessTest` suite and the `Start1_FileName_NotFound()` would fail at `#C6` because the native error code wasn't 2 (file not found) but 13 (invalid data). This is because it …
=> [mono] Don't try "open" handlers on iOS/Android in ves_icall_System_Diagnostics_Process_ShellExecuteEx_internal

configure.ac, netcore/Makefile.am, netcore/runtime.nuspec
I changed the thing, so we can generate mono.nupkg runtime packages in the format consumed in core-setup. This isn't as immediately usable as the current makefile's "just squash Mono into a .zip", until some changes are made on the Core end (e.g. supporting `libmonosgen-2.0` in lieu of `libcoreclr`), but it's a starting point.
=> Runtime nupkg generation

mono/metadata/marshal.c, mono/metadata/marshal.h, mono/mini/aot-compiler.c, mono/mini/interp/transform.c, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c
Every caller was consistently forming the same name based on callinfo->name
and passing callinfo->func and callinfo->sig.
Pass callinfo instead and do the common work in mono_marshal_get_icall_wrapper.
This has the following side effects:
Do not form and free name when there is cache hit. This seems like a nice optimization.
Allow name to be null when there is cache hit. This is unintended. We could assert
if it is a problem.
=> Cleanup mono_marshal_get_icall_wrapper.

mcs/class/System.Private.CoreLib/System.Threading/EventWaitHandle.cs, mcs/class/corlib/System.Threading/RegisteredWaitHandle.cs
Fixes crash in System.Threading.ThreadPools.Tests and makes it run till the end:
```
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 3.0.0-preview4-27514-06)
Discovering: System.Threading.ThreadPool.Tests (method display = ClassAndMethod, method display options = None)
Discovered:  System.Threading.ThreadPool.Tests (found 18 test cases)
Starting:    System.Threading.ThreadPool.Tests (parallel test collections = on, max threads = 4)
System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest [FAIL]
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace:
at System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest()
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, …
```
=> [netcore] Implement missing functions in RegisteredWaitHandle and EventWaitHandle

mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLiteCommand.cs, mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLiteDataReader.cs, mcs/class/Mono.Data.Sqlite/Test/SqliteDataReaderTest.cs
Fixes https://github.com/mono/mono/issues/13547
=> [sqllite] Throw ArgumentException during empty text command initialization for reader

man/mono-profilers.1, mono/profiler/aot.c
It instructs the AOT profiler to write the data after NUM seconds
measured from runtime initialization.
Fixes: https://github.com/xamarin/xamarin-android/issues/2813
=> [profiler] Add duration=NUM parameter to AOT profiler

configure.ac
Closes https://github.com/mono/mono/issues/9267
This will likely require fixups in Linux packaging (which is the only place we consume tarballs instead of git)
=> Switch `make dist` format from BZip2 to XZ.

configure.ac
Closes https://github.com/mono/mono/issues/9267
This will likely require fixups in Linux packaging (which is the only place we consume tarballs instead of git)
Backport of #13700.
=> [2019-02] Switch `make dist` format from BZip2 to XZ.

llvm/SUBMODULES.json
Pick up https://github.com/mono/llvm/pull/19 to fix LLVM AOT crashes on
Windows.
/cc @lateralusX @jonathanpeppers
=> [2018-10][llvm] Bump LLVM submodule to 349752c464c5fc93b32e7d45825f2890c85c8b7d

mcs/class/System/Test/System.Net/DnsTest.cs
Sometimes Google DNS is/was returning "dns.google" for reverse query of 8.8.8.8 and 8.8.4.4 instead of the expected "google-public-dns-a.google.com" and "google-public-dns-b.google.com". Since "dns.google" resolves to both 8.8.8.8 and 8.8.4.4 in random order the round-trip tests for IP -> hostname -> IP were failing when they got the other IP. This changes the logic in the hostname -> IP check to check whether the expected IP is any one of the returned ones (ie. non necessarily the first one). 
/cc @akoeplinger @kg
=> Make the DnsTest more resilient to multi-IP DNS results

mcs/packages/Makefile
Roslyn picked up some new dependencies that I failed to add to a Makefile containing a list of its dependencies. This may fix some scenarios (not covered by CI) that result in csc and/or msbuild not working.
=> Add missing roslyn assemblies to mcs package makefile

mcs/class/System/System.Net.NetworkInformation/UnixNetworkInterfaceFactory.cs, mcs/class/System/System/Platform.cs
This adds OpenBSD to the platforms to use MacOsNetworkInterfaceAPI, fixes #8168, should apply similarly to DragonFly BSD. Tested with mono-5.14.0.177 from ports on OpenBSD with OpenRA and SMAPI for StardewValley that both do DNS lookup and exhibited NameResolutionFailure that is resolved with this diff.
=> Fix DNS Name Resolution Failure on OpenBSD (GitHub issue #8168)

mono/mini/mini-arm.c
Fixes the nightly C++ Jenkins jobs
https://jenkins.mono-project.com/job/test-mono-mainline-linux-cxx/
=> [arm] Don't use C++ keyword as a variable name

sdks/wasm/binding_support.js
Hi guys,
Yesterday I updated the WASM SDK and noticed an error while using Uint16Array: there's a misspeling in the binding_support.js file.
I've modified it on final mono.js one and works as expected.
Thanks for your work,
PS: We're using above here: https://github.com/MarcosCobena/WebGL.NET
—Marcos
=> Fixed casing

mcs/class/System.Private.CoreLib/System.Runtime.InteropServices/Marshal.cs, netcore/.gitignore
Fixes 19 failing tests in System.Runtime.Tests
before my fix this IsPinnable returned false for `sbyte[]` 
Inspired by https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs#L189
Also, do not add `netcore/System.Private.Corlib/shared` to gitignore, only `netcore/shared`
=> [netcore] Fix Marshal.IsPinnable

configure.ac, llvm/Makefile.am, mono/metadata/Makefile.am, mono/metadata/icall.c, mono/profiler/Makefile.am, scripts/ci/pipeline/sdks-archive.groovy, sdks/builds/android.mk, sdks/builds/llvm.mk, sdks/builds/mxe-Win32.cmake.in, sdks/builds/mxe-Win64.cmake.in, sdks/builds/mxe.mk, support/Makefile.am
It turns out that homebrew now has a package for the MinGW gcc-based windows
cross compiler which is awesome as it allows us to skip building MXE and use the
latest version of the GCC suite pre-packaged for Mac. This commit removes almost
all traces of MXE (except for `mxe.mk` itself, because I don't know if any bot
or external tool, whatever, use targets in it) and adds the following brew
packages to SDK bot provisioning as well as to the `provision-mxe` target of
Mono SDKs:
* mingw-w64
* xamarin/xamarin-android-windeps/mingw-zlib
The latter package builds a Windows version of zlib using MinGW and it comes
from Xamarin's own homebrew tap at https://github.com/xamarin/homebrew-xamarin-android-windeps/blob/f4cc90845ff1953800d8d71035566a12d9b7aa24/mingw-zlib.rb
A few things need to be …
=> [sdks,mac] Remove dependency on MXE in favor of MinGW

mono/unit-tests/Makefile.am, mono/unit-tests/test-path.c, mono/utils/mono-path.c
The main one is that strstr is too loose. The intent is prefix matching, not searching the entire string.
Add tests.
Make it case insensitive on Win32 and allow some denormal input.
Despite the prior intent and comments, the input is not normalized/absolute. Assuming so broke tests.
Note that case sensitivity is a function of file system, not
operating system, but a lot of code gets it wrong, so here does too.
The Win32 code paths could be tested on Unix and vice versa
w/o compromise. See https://github.com/mono/mono/pull/13707
That is removed here per PR feedback.
=> Fix a few deficiencies in mono_path_filename_in_basedir. Mainly strstr.

configure.ac, llvm/Makefile.am, mono/metadata/Makefile.am, mono/metadata/icall.c, mono/profiler/Makefile.am, scripts/ci/pipeline/sdks-archive.groovy, sdks/builds/android.mk, sdks/builds/llvm.mk, sdks/builds/mxe-Win32.cmake.in, sdks/builds/mxe-Win64.cmake.in, sdks/builds/mxe.mk, support/Makefile.am
It turns out that homebrew now has a package for the MinGW gcc-based windows
cross compiler which is awesome as it allows us to skip building MXE and use the
latest version of the GCC suite pre-packaged for Mac. This commit removes almost
all traces of MXE (except for `mxe.mk` itself, because I don't know if any bot
or external tool, whatever, use targets in it) and adds the following brew
packages to SDK bot provisioning as well as to the `provision-mxe` target of
Mono SDKs:
* mingw-w64
* xamarin/xamarin-android-windeps/mingw-zlib
The latter package builds a Windows version of zlib using MinGW and it comes
from Xamarin's own homebrew tap at https://github.com/xamarin/homebrew-xamarin-android-windeps/blob/f4cc90845ff1953800d8d71035566a12d9b7aa24/mingw-zlib.rb
A few things need to be …
=> [2019-02] [sdks,mac] Remove dependency on MXE in favor of MinGW

mcs/class/System.Private.CoreLib/System.Threading/Thread.cs
Fixes remaining failure in System.Threading.Thread.Tests.
=> [netcore] Fix TrySetApartmentStateUnchecked return value

netcore/excludes-System.IO.Tests.rsp, netcore/excludes-System.Text.Json.Tests.rsp, netcore/excludes-System.Threading.ThreadPool.Tests.rsp
Please review them carefully. Some of them may be worth fixing.
=> [netcore] Add exceptions for tests that depend on CoreCLR behavior

mcs/class/System/Microsoft.CSharp/CSharpCodeGenerator.cs
This showed up in the xamarin-macios 2019-02 integration.
When you used Xslt with a custom C# script in a Xamarin.Mac Full application we'd try to launch mcs via CodeDOM to compile the script.
This started failing in 2019-02 because System.Native (mono-native) wasn't found and we now need it for basic File IO, the reason is that XM sets MONO_CFG_DIR to point to the Contents/MonoBundle in the app bundle where it packages the global config file with dllmaps.
However the started Mono wasn't able to find mono-native since the config there uses a different name for the file.
To prevent that we now clear MONO_CFG_DIR so it uses the default value for the mono process we're starting (note that setting it to String.Empty doesn't work)
=> [System] Clear MONO_CFG_DIR before starting mcs in CodeDOM CSharpCodeGenerator

mcs/class/System.Private.CoreLib/System/Array.cs, mcs/class/System.Private.CoreLib/System/Buffer.cs, mono/metadata/exception.c, mono/metadata/icall.c, netcore/excludes-System.Runtime.Tests.rsp
Fixes 7 System.Tests.ArrayTests
ArrayTests still has a lot of failing tests for `ArrayTypeMismatchException` (tests expect it when we throw nothing and vice versa).
Mostly these two:
```
System.Tests.ArrayTests.ConstrainedCopy_UnreliableConversion_ThrowsArrayTypeMismatchException
System.Tests.ArrayTests.Copy_SourceAndDestinationNeverConvertible_ThrowsArrayTypeMismatchException
```
=> [netcore] Fix few Array tests

mcs/class/corlib/System/TimeZoneInfo.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
I'm not sure about the correctness of this workaround but it works on macOS for the repro from https://github.com/mono/mono/issues/9664#issuecomment-472260968
Transition bounds used by time zone info represent some local date-time but actually they are of Unspecified date-time kind. 
When we try to get transition offset we compare some current date-time converted to UTC with appropriate transition bounds.
The fix is to use UTC for both current date-time and transition bounds during comparing.
Fixes https://github.com/mono/mono/issues/9664
=> Fix transition offset logic

mcs/build/tests.make, mcs/class/Microsoft.Build.Tasks/Makefile, mcs/tools/nunit-lite/NUnitLite/Makefile, mcs/tools/nunit-lite/nunit-lite-console/Makefile, scripts/ci/run-test-default.sh, scripts/ci/run-test-helix.sh
In this case we relied on nunitlite to be compiled when the parent profile is compiled. That doesn't work however if we compile the child profile first (e.g. during a parallel make) since it'll
complain about missing nunitlite.dll.
We now compile nunitlite in the child profiles too even though we don't use it.
This is an alternative solution to what I tried in https://github.com/mono/mono/pull/5357 since I couldn't get it to work and this should be the easier fix.
It allows us to finally remove the `-i` (ignore errors) from the CI scripts and catch test assembly breakages in mobile profiles which we ignored before.
=> [bcl] Fix compiling nunitlite when PARENT_PROFILE is defined

mono/metadata/threadpool-worker-default.c, mono/utils/mono-complex.h, support/libm/complex.c
Also make cimag/creal macros for guaranteed inlining -- instead of passing structs by value.
And add spaces before parens to follow coding convention (which is designed
to ease low tech searches for entire words).
This was agreed to when the code was first ported to C++ but got dropped.
The compromise though was to put the defines relatively late to limit their impact.
=> Rename cabs/cimag/creal to mono_cabs/mono_cimag/mono_creal without macros.

mcs/class/corlib/ReferenceSources/RuntimeType.cs
Fixes remaining failures on System.Xml.XmlSerializer.Tests.
=> [netcore] Reenable some methods on RuntimeType

mcs/class/corlib/System/TimeZoneInfo.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
I'm not sure about the correctness of this workaround but it works on macOS for the repro from https://github.com/mono/mono/issues/9664#issuecomment-472260968
Transition bounds used by time zone info represent some local date-time but actually they are of Unspecified date-time kind. 
When we try to get transition offset we compare some current date-time converted to UTC with appropriate transition bounds.
The fix is to use UTC for both current date-time and transition bounds during comparing.
Fixes https://github.com/mono/mono/issues/9664
Backport of #13553.
=> [2018-10] Fix transition offset logic

mono/mini/generics.cs, mono/mini/mini-llvm.c, mono/mini/mini.h
Backport of #13659 to `2018-08`
/cc @vargaz 
Backport of #13675.
=> [2018-08-rc][llvm] Fix the computation of size of gshared instances in emit_args_to_vtype ().

mcs/class/System.Private.CoreLib/System/Array.cs
Fixes 192 tests:
`System.Runtime.Tests  Total: 31196, Errors: 0, Failed: 138, Skipped: 0, Time: 30.231s`
Many of the Array tests are still failing though.
/cc @EgorBo
=> [netcore] Improve element type checks in Array.Copy and Array.ConstrainedCopy

scripts/ci/run-jenkins.sh, scripts/ci/run-test-make-install.sh
Adds 5 quick checks, on prefix-tests tag:
* Build a basic file with mcs
* Build a basic file with Roslyn
* AOT an assembly
* LLVM AOT an assembly
* LLVM JIT an assembly
This uses loadedllvm, since that's what we ship on Linux.
This should let us spot regressions affecting installed prefixes sooner
=> Add tests to ensure `make install` prefix is functional

mono/mini/method-to-ir.c
We were setting the stack type by using another global local named ins.
This lead to missing methods in the aot image due to invalid IL. Fixes https://github.com/mono/mono/issues/13479.
=> [gsharedvt] Fix sizeof opcode

mcs/class/System.Private.CoreLib/System/Math.cs, mcs/class/System.Private.CoreLib/System/MathF.cs, mono/metadata/icall-decl.h, mono/metadata/icall-def.h, mono/metadata/sysmath.c
This PR fixes 169 tests in System.Runtime.Extensions.Tests (MathFTests)
.NET Core's JIT is able to replace `FusedMultiplyAdd` with FMA instructions (if CPU supports it)
I guess it should be implemented similar to https://github.com/mono/mono/pull/10039
(btw LLVM is able to insert FMA 🙂 see https://twitter.com/EgorBo/status/1063468884257316865)
=> [netcore] Implement missing Math and MathF methods

mcs/class/System.Private.CoreLib/System/Enum.cs, mono/metadata/class.c, mono/metadata/icall-def.h, mono/metadata/icall.c
Improve support for rare enum types (IntPtr, UIntPtr, Single, Double, Char, Boolean backing types) and make `Enum.HasFlag` working.
`System.Runtime.Tests  Total: 32076, Errors: 0, Failed: 122, Skipped: 0, Time: 29.682s`
Actual number of fixed tests is quite high because the discovery was broken. Remaining `Enum` related failures:
```
System.Tests.EnumTests.Parse<TestName_Single>(value: "vaLue2", ignoreCase: True, expected: Value1) [FAIL]
Assert.Equal() Failure
Expected: Value1
Actual:   Value2
Stack Trace:
/Users/vsts/agent/2.149.2/work/1/s/src/System.Runtime/tests/System/EnumTests.cs(133,0): at System.Tests.EnumTests.Parse[TestName_Single](String value, Boolean ignoreCase, TestName_Single expected)
/Users/filipnavara/Documents/mono/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs(3 …
```
=> [netcore] Improve support for rare enum types

scripts/ci/run-jenkins.sh
The debugger tests are being worked on and will be reactivate once the PR goes in https://github.com/mono/mono/pull/13622
=> [wasm] Disable debugger tests

mcs/class/PEAPI/Metadata.cs, mcs/ilasm/codegen/TypeManager.cs, mcs/ilasm/parser/ILParser.jay, mono/metadata/class-init.c, mono/metadata/class.c, mono/tests/Makefile.am, mono/tests/twopassvariance.il
This test https://github.com/dotnet/coreclr/blob/1649da12db73c8c07513c9168cb30ec70c310063/tests/src/Regressions/coreclr/20452/twopassvariance.il
On mono we were ordering the list of implemented interfaces and shouldn't do this as it's described on ECMA-335 Section II.12.2.1 and II.12.2.2.
The ordering was removed on ilasm and some changes were needed on metadata either because it's not ordered anymore.
There were two bugs, one on ilasm and other on class initialization on mono.
If we get the .exe generated by .net Framework it doesn't execute on mono without modifications because we ordered the implemented interfaces list by id. And doing that the order defined on source code is ignored.
If we get the .exe generated by Mono it doesn't execute on .net Framework because on IlAsm we order …
=> [DIM] Do not order implemented interfaces

scripts/ci/run-test-make-install.sh
=> Disable llvmjit in the packaging test ci lane so we can turn the lane back on

mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
This method returns a function pointer that can be called with a calli instruction. On interpreter we use a pointer to InterpMethod while on jit we use the native code address. Normally, GetFunctionPointer should return the InterpMethod pointer if called from interp or the native code address if called from jit. Since we don't have any information about the execution engine of the caller, we solve this by intrinsifying all these calls, that happen in the interpreter.
Passing such function pointers between jitted and interp code is probably still unreliable.
Fixes https://github.com/mono/mono/issues/13654
=> [interp] Fix GetFunctionPointer

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/mini/method-to-ir.c, mono/mini/mini-ppc.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini-s390x.c, mono/mini/mini-x86.c, mono/mini/patch-info.h, mono/mini/tramp-amd64.c, mono/mini/tramp-arm.c, mono/mini/tramp-arm64.c, mono/mini/tramp-mips.c, mono/mini/tramp-ppc.c, mono/mini/tramp-x86.c
The larger goal here is to stop hashing JIT icalls, by string and by code address, as suggested a few months ago. Both the inserts into hashtables and the lookups.
Note this is about JIT icalls.
Not icalls declared in C#.
Reducing the lookups is easy, but complete elimination takes more work,
and I believe is possible and desirable.
JIT icalls are used with:
`MONO_PATCH_INFO_JIT_ICALL` 
`MONO_PATCH_INFO_JIT_ICALL_ADDR` 
`MONO_PATCH_INFO_JIT_ICALL_ADDR_NOCALL` 
There is a fixed set of JIT icalls.
Their strings can be replaced with an enum,
or pointers to fixed data structures, or pointers/offsets
into a fixed data structure.
Except for:
`MONO_PATCH_INFO_JIT_ICALL_ADDR + sprintf ("trampoline_func_%d", tramp_type)`
`MONO_PATCH_INFO_JIT_ICALL_ADDR + sprintf …
=> Add MONO_PATCH_INFO_TRAMPOLINE_FUNC_ADDR and MONO_PATCH_INFO_SPECIFIC_TRAMPOLINE_LAZY_FETCH_ADDR.

mono/metadata/metadata.c
The aggregate modifiers container is owned by a `MonoImageSet`.  The aggregate modifiers may be shared by more than one `MonoType` that happen to need the same modifiers. (Similar to how generic instantiations are shared)
When the image set is cleaned up the aggregate modifier cleanup will free the types in the aggregate modifiers container (the call to `free_aggregate_modifiers` in `mono_metadata_clean_for_image`).
With this extra call to `free_aggregate_modifiers` in `mono_metadata_free_type` may cause the same memory to be freed twice.
Fixes https://github.com/mono/mono/issues/13775
=> [metadata] Don't free_aggregate_modifiers in mono_metadata_free_type

mono/mini/mini-llvm-cpp.cpp, mono/mini/mini-llvm-cpp.h, mono/mini/mini-llvm.c
From: https://llvm.org/docs/LangRef.html
```
Furthermore, the semantics of the noalias attribute on return values are stronger than the semantics of the attribute when used on function arguments. On function return values, the noalias attribute indicates that the function acts like a system memory allocation function, returning a pointer to allocated storage disjoint from the storage for any other object accessible to the caller.
```
Think this probably helps LLVM reorder the method calls, telling it that allocating won't return a pointer to something else on the stack.
=> [llvm] Give LLVM noalias info about alloc functions

netcore/Makefile.am
Keep the xunit parallelization setting at default value to allow `Xunit.CollectionBehavior(DisableTestParallelization = true)` override to work. Fixes all failures in System.Xml.RW.XmlWriterApi.Tests.
=> [netcore] Keep the xunit parallelization setting at default value

mono/mini/mini-llvm.c
Our LLVM IR is littered with bitcasts due to the GOT being currently an untyped array. 
This allows opt to remove those bitcasts, and to then see that we aren't crafting pointers from ints that may alias to other memory we're working with.
These conversions can pose trouble for LLVM's alias analysis, causing it to give up.
=> [llvm] Make GOT a typed struct

mono/utils/mono-dl.c
1. it doesn't touch the managed runtime
2. it may be called (arguably it ought to be called only) before the runtime is
initialized (and in particular before the current thread is attached).
=> [mono-dl] Don't do thread state transitions in mono_dl_fallback_register

mono/utils/mono-dl.c
1. it doesn't touch the managed runtime
2. it may be called (arguably it ought to be called only) before the runtime is
initialized (and in particular before the current thread is attached).
Backport of #13866.
=> [2018-10] [mono-dl] Don't do thread state transitions in mono_dl_fallback_register

mono/utils/mono-dl.c
1. it doesn't touch the managed runtime
2. it may be called (arguably it ought to be called only) before the runtime is
initialized (and in particular before the current thread is attached).
Backport of #13866.
=> [2019-04] [mono-dl] Don't do thread state transitions in mono_dl_fallback_register

mono/utils/mono-dl.c
1. it doesn't touch the managed runtime
2. it may be called (arguably it ought to be called only) before the runtime is
initialized (and in particular before the current thread is attached).
Backport of #13866.
=> [2019-02] [mono-dl] Don't do thread state transitions in mono_dl_fallback_register

man/mono.1, mono/mini/aot-compiler.c
Introduced by
https://github.com/mono/mono/commit/2eeaf888c1d0a681c8705bd609f76196d8fb82ed
=> [AOT] remove confusing llcopts flag

mcs/class/corlib/System.IO.IsolatedStorage/IsolatedStorageFile.cs
This was caused by changes in File.Move coming from https://github.com/mono/mono/pull/12000
=> [2019-02][corlib] Fix exception 'replacement' in IsolatedStorageFile.MoveFile()

sdks/wasm/Makefile, sdks/wasm/binding_support.js, sdks/wasm/framework/src/WebAssembly.Bindings/Core/TypedArray.cs, sdks/wasm/framework/src/WebAssembly.Bindings/Core/TypedArrayTypeCode.cs, sdks/wasm/framework/src/WebAssembly.Bindings/Interfaces.cs, sdks/wasm/tests/browser/BindingsTestSuite.cs, sdks/wasm/tests/browser/http-spec.js
Fixes issue https://github.com/mono/mono/issues/13787
- Add new BindingsTestSuite.cs program to the Tests that will test for these cases so regressions do not slip in.
- Add TypedArrayTypeCode enum
=> [wasm] Fix Uint8ClampedArray.From(byte[]) invalid cast

mcs/class/System.Private.CoreLib/System/Array.cs, mcs/class/System.Private.CoreLib/System/DefaultBinder.cs
Remaining errors:
```
/Users/filipnavara/Documents/mono/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs(391,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Tests.ArrayTests.Copy_SZArray(sourceArray: [0, 1, 2, 3, null, ...], sourceIndex: 2, destinationArray: [204, 204, 204, 204, 204, ...], destinationIndex: 5, length: 3, expected: [204, 204, 204, 204, 204, ...]) [FAIL]
System.InvalidCastException : Specified cast is not valid.
Stack Trace:
/Users/filipnavara/Documents/mono/mcs/class/System.Private.CoreLib/System/Array.cs(170,0): at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable) …
```
=> [netcore] More Array.Copy fixes

mono/metadata/marshal.c
Fix regression from https://github.com/mono/mono/pull/13807/files#diff-e881a4d9491559282e7ae2021f8ad3a4R54. 
CoreCLR code for reference: https://github.com/dotnet/coreclr/blob/2f4a7564beb6f8c1f4929504ee2221953d25fc39/src/vm/marshalnative.cpp#L276-L278
Fixes `System.Tests.StringTests.Ctor_CharPtr_DoesNotAccessInvalidPage` in `System.Runtime.Tests`.
/cc @EgorBo
=> [netcore] Fix Marshal.IsPinnable regression

mono/utils/mono-mmap.c
=> [Coverity] Ensure that we never return -1 from pagesize operation, helps eliminate many false positives

mono/mini/aot-runtime.c, mono/mini/mini.h
It does not matter perf-wise, but makes the code clearer.
i.e. if attempting to replace strings with enums.
=> Remove obsolete AOT relocations for code clarity, assuming no need to support old AOT images.

mono/mini/main-core.c
Propagate System.Globalization.Invariant from runtimeconfig.json to GlobalizationMode. It's temporary hack to make all Invariant.Tests pass. CoreCLR also uses special `CLRConfig` class and icall to access this property because it needs it very early, so this may end up quite ok way to accomplish the same.
=> [netcore] Propagate System.Globalization.Invariant from runtimeconfig.json

mono/metadata/assembly.c, mono/metadata/coree.c, mono/metadata/debug-mono-ppdb.c, mono/metadata/icall-windows.c, mono/metadata/image.c, mono/metadata/loader.c, mono/metadata/metadata-internals.h, mono/metadata/metadata-verify.c, mono/metadata/reflection.c, mono/metadata/w32process.c, mono/mini/debugger-agent.c, tools/pedump/pedump.c
Create a new data structure: MonoImageStorage.
It is an object that will have the responsibility for the raw data of a
MonoImage.  It has a string key and a refcount that is used to share a
MonoImageStorage between multiple MonoImage objects.
The reason we need this is because the current MonoAssembly/MonoImage design is
broken for multiple domains and (more evidently) it will be broken when we add
AssemblyLoadContext support.  The issue is that a MonoImage may be shared
between multiple domains (or ALCs), but it has a 'references' field which
points to a single other MonoAssembly.
This is a problem because the references of an image may be resolved
differently in different domains (or ALCs).
The eventual solution will be to stop sharing MonoImages based on path name (or
in the case of …
=> [image] Create MonoImageStorage to own the image raw data

mono/mini/mini-llvm.c
When we switched to `-place-safepoints` we lost this small but nice optimization introduced in #11554
e.g. C#:
```csharp
static unsafe void Test (byte* a)
{
a[0] = 42;
}
```
Before:
```llvm
; Function Attrs: norecurse nounwind uwtable
define hidden monocc void @P_Test_byte_(i64* nocapture %arg_a) #5 gc "mono" {
BB0:
%0 = bitcast i64* %arg_a to i8*
store i8 42, i8* %0, align 1
%1 = load i64*, i64** getelementptr inbounds (%MONO_GOT_p.exe, %MONO_GOT_p.exe* @mono_aot_p_llvm_got, i64 0, i32 7), align 8
%2 = load i64, i64* %1, align 4
%3 = icmp eq i64 %2, 0
br i1 %3, label %gc.safepoint_poll.exit, label %gc.safepoint_poll.poll.i
gc.safepoint_poll.poll.i:                         ; preds = %BB0
%4 = load void ()*, void ()** getelementptr inbounds (%MONO_GOT_p.exe, %MONO_GOT_p.exe* …
```
=> [llvm] do not emit safe points for simple methods

mono/metadata/assembly.c, mono/metadata/coree.c, mono/metadata/debug-mono-ppdb.c, mono/metadata/icall-windows.c, mono/metadata/image.c, mono/metadata/loader.c, mono/metadata/metadata-internals.h, mono/metadata/metadata-verify.c, mono/metadata/reflection.c, mono/metadata/w32process.c, mono/mini/debugger-agent.c, tools/pedump/pedump.c
Reverts mono/mono#13892. It had `do-not-merge` label and also breaks the mono-extensions build:
```
[2019-04-08T10:18:44.763Z] ./../../../mono-extensions/mono/metadata/enc-loader.c:10:13: error: no member named 'raw_data' in 'struct _MonoImage'
```
=> Revert "[image] Create MonoImageStorage to own the image raw data"

mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/13889.
=> [jit] Avoid adding a needless zext which confuses abcrem.

man/mono.1, mono/mini/aot-compiler.c
Introduced by
https://github.com/mono/mono/commit/2eeaf888c1d0a681c8705bd609f76196d8fb82ed
Backport of #13877.
/cc @lewurm
=> [2019-02] [AOT] remove confusing llcopts flag

man/mono.1, mono/mini/aot-compiler.c
Introduced by
https://github.com/mono/mono/commit/2eeaf888c1d0a681c8705bd609f76196d8fb82ed
Backport of #13877.
/cc @lewurm
=> [2019-04] [AOT] remove confusing llcopts flag

sdks/builds/wasm.mk
Updating to recent sdk 1.38.30.
There seems to be a problem with the 1.38.30 release right now for OSX.
Issue: https://github.com/WebAssembly/binaryen/issues/1975
=> [wasm] Update to emscripten 1.38.30 

mcs/class/System.Data/System.Data_xtest.dll.sources
It contained DllImports to some Windows APIs which causes issues on xamarin-macios which expects all pinvokes to exist.
Turns out we don't even need that file.
=> [System.Data] Remove unnecessary file from xunit tests

packaging/MacSDK/msbuild.py
There's a comment in this script that says to 'fix run-test-mac-sdk.sh' but i can't find anything to fix in that script. Is that comment dead?
=> Bump macsdk msbuild hash to msbuild that uses new roslyn, matching mono master

mono/mini/debugger-engine.c
In my batch of changes here: https://github.com/mono/mono/commit/c3fe80a0c43be780e35f3a4091d3dc1023b35a00#diff-dca5f20c7ac28a5a4487805c49836fdbL340
I changed
```
if (!seq_points)
/* Could be AOT code */
continue;
```
into
```
seq_points = (MonoSeqPointInfo *) ji->seq_points;
if (!seq_points) {
MonoMethod *jmethod = jinfo_get_method (ji);
if (jmethod->is_inflated) {
MonoJitInfo *seq_ji;
MonoMethod *declaring = mono_method_get_declaring_generic_method (jmethod);
mono_jit_search_all_backends_for_jit_info (domain, declaring, &seq_ji);
seq_points = (MonoSeqPointInfo *) seq_ji->seq_points;
}
}
```
which doesn't account for the case when it can't find the seq_points. When seq_points is NULL at the end of that block, we don't `continue;` as we did before. Instead we assert, and crash the runtime. …
=> [merp] Restore non-assertion behavior in debugger-engine.c

mono/mini/debugger-engine.c
In my batch of changes here: https://github.com/mono/mono/commit/c3fe80a0c43be780e35f3a4091d3dc1023b35a00#diff-dca5f20c7ac28a5a4487805c49836fdbL340
I changed
```
if (!seq_points)
/* Could be AOT code */
continue;
```
into
```
seq_points = (MonoSeqPointInfo *) ji->seq_points;
if (!seq_points) {
MonoMethod *jmethod = jinfo_get_method (ji);
if (jmethod->is_inflated) {
MonoJitInfo *seq_ji;
MonoMethod *declaring = mono_method_get_declaring_generic_method (jmethod);
mono_jit_search_all_backends_for_jit_info (domain, declaring, &seq_ji);
seq_points = (MonoSeqPointInfo *) seq_ji->seq_points;
}
}
```
which doesn't account for the case when it can't find the seq_points. When seq_points is NULL at the end of that block, we don't `continue;` as we did before. Instead we assert, and crash the runtime. …
=> [2018-10] [merp] Restore non-assertion behavior in debugger-engine.c

msvc/mono.winconfig.targets
Add support to pick up supported enable flags from configuration step. Currently only a limited number of flags are supported on Windows and when we add more support, it will be included in the list and picked up if set by configuration step.
NOTE, several parts of the diff are due to file used CRLF on a couple of lines, this PR adjust all lines to use LF.
=> Make sure additional supported enable defines ends up in config.h on Windows.

mcs/class/corlib/System.Reflection/RuntimePropertyInfo.cs, mono/metadata/icall.c, mono/metadata/marshal-ilgen.c
CoreCLR allows reflection on methods with ByRef return types under certain conditions. The PR implementing it is https://github.com/dotnet/coreclr/pull/17639.
Mono already implemented most of it in the marshalling code but artificially blocked it in `ves_icall_InternalInvoke`. I changed the condition for the exception to match the condition in `emit_invoke_call` (marshal-ilgen.c). It's similar to the condition in CoreCLR, but it may not handle byref-like types correctly. It would have to fixed on both places if it turns out to be the case.
The remaining issue is that null references returned in ByRef are not checked and converted to correct exception. It should result in `NullReferenceException` with special message that doesn't get wrapped in `TargetInvocationException`. I put a TODO …
=> [netcore] Allow reflection invocation of methods with ByRef return types

mono/mini/method-to-ir.c
Use TLS_KEY_LMF_ADDR on Windows as done on all other platforms. No need to go through the struct hosted at TLS_KEY_JIT_TLS since the same address is already set in TLS_KEY_LMF_ADDR.
=> Use TLS_KEY_LMF_ADDR on Windows when pusing lmf frame.

mono/mini/debugger-engine.c
In my batch of changes here: https://github.com/mono/mono/commit/c3fe80a0c43be780e35f3a4091d3dc1023b35a00#diff-dca5f20c7ac28a5a4487805c49836fdbL340
I changed
```
if (!seq_points)
/* Could be AOT code */
continue;
```
into
```
seq_points = (MonoSeqPointInfo *) ji->seq_points;
if (!seq_points) {
MonoMethod *jmethod = jinfo_get_method (ji);
if (jmethod->is_inflated) {
MonoJitInfo *seq_ji;
MonoMethod *declaring = mono_method_get_declaring_generic_method (jmethod);
mono_jit_search_all_backends_for_jit_info (domain, declaring, &seq_ji);
seq_points = (MonoSeqPointInfo *) seq_ji->seq_points;
}
}
```
which doesn't account for the case when it can't find the seq_points. When seq_points is NULL at the end of that block, we don't `continue;` as we did before. Instead we assert, and crash the runtime. …
=> [2019-02] [merp] Restore non-assertion behavior in debugger-engine.c

mono/mini/debugger-engine.c
In my batch of changes here: https://github.com/mono/mono/commit/c3fe80a0c43be780e35f3a4091d3dc1023b35a00#diff-dca5f20c7ac28a5a4487805c49836fdbL340
I changed
```
if (!seq_points)
/* Could be AOT code */
continue;
```
into
```
seq_points = (MonoSeqPointInfo *) ji->seq_points;
if (!seq_points) {
MonoMethod *jmethod = jinfo_get_method (ji);
if (jmethod->is_inflated) {
MonoJitInfo *seq_ji;
MonoMethod *declaring = mono_method_get_declaring_generic_method (jmethod);
mono_jit_search_all_backends_for_jit_info (domain, declaring, &seq_ji);
seq_points = (MonoSeqPointInfo *) seq_ji->seq_points;
}
}
```
which doesn't account for the case when it can't find the seq_points. When seq_points is NULL at the end of that block, we don't `continue;` as we did before. Instead we assert, and crash the runtime. …
=> [2019-04] [merp] Restore non-assertion behavior in debugger-engine.c

configure.ac, mcs/class/System.Private.CoreLib/.gitignore, mcs/class/System.Private.CoreLib/Makefile, mcs/class/System.Private.CoreLib/Makefile.am, netcore/Makefile.am, netcore/runtime.nuspec
I know everyone hated the move to Autotools, but there was method to my madness.
We can now build `--with-core=only` on Linux or Mac with the same makefile, and have a functional `make nupkg` rule which attempts to produce a .nupkg of the runtime in the format consumed by core-setup. We should at least have something we can throw at CI to get binaries produced, and talk to the Core team about consuming them.
=> [netcore] Runtime nupkg fixes

mono/mini/aot-compiler.c
Unbreaks jemalloc support as it hooks into `g_malloc ()` instead of replacing `malloc ()`.
```
%4  0x000055ee6af0d27b in sigabrt_signal_handler (_dummy=6, _info=0x7ffc7b0c4ff0, context=0x7ffc7b0c4ec0) at mini-posix.c:232
%5  <signal handler called>
%6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
%7  0x00007f4ae0d73801 in __GI_abort () at abort.c:79
%8  0x000055ee6b2ab6ed in rtree_child_leaf_tryread (elm=0x55ee6b75b028 <je_extents_rtree+704104>, dependent=true) at src/rtree.c:205
%9  0x000055ee6b2ab95f in je_rtree_leaf_elm_lookup_hard (tsdn=0x7f4ae1f05738, rtree=0x55ee6b6af1c0 <je_extents_rtree>, rtree_ctx=0x7f4ae1f05758, key=94482510772944, dependent=true, init_missing=false) at src/rtree.c:292
%10 0x000055ee6b242f70 in rtree_leaf_elm_lookup (tsdn=0x7f4ae1f05738, …
```
=> [aot] use g_malloc () instead of malloc ()

man/mono.1, mono/mini/driver.c, mono/utils/mono-mmap-wasm.c, mono/utils/mono-mmap-windows.c, mono/utils/mono-mmap.c, mono/utils/mono-mmap.h
Second version of this.  Previously #13446 which had to be reverted due to Windows and WASM breakage.
Add stub Win32 and WASM implementations of `mono_setmmapjit`
---
This is surfaced via a command line option, to not make this a strong API requirement on Xamarin.Mac requiring it. See companion patch:
=> Do not use MAP_JIT by default (take 2)

mono/metadata/metadata.c
The aggregate modifiers container is owned by a `MonoImageSet`.  The aggregate modifiers may be shared by more than one `MonoType` that happen to need the same modifiers. (Similar to how generic instantiations are shared)
When the image set is cleaned up the aggregate modifier cleanup will free the types in the aggregate modifiers container (the call to `free_aggregate_modifiers` in `mono_metadata_clean_for_image`).
With this extra call to `free_aggregate_modifiers` in `mono_metadata_free_type` may cause the same memory to be freed twice.
Fixes https://github.com/mono/mono/issues/13775
Backport of #13785.
=> [2019-04] [metadata] Don't free_aggregate_modifiers in mono_metadata_free_type

mcs/class/System.Data/Test/System.Data.SqlTypes/SqlStringTest.cs, mcs/class/System/Test/System.ComponentModel/DateTimeConverterTests.cs, mcs/class/corlib/System.Globalization/CultureInfo.cs, mcs/class/corlib/Test/System.Globalization/CalendarTest.cs, mcs/class/corlib/Test/System.Globalization/DateTimeFormatInfoTest.cs, mcs/class/corlib/Test/System.Globalization/EastAsianLunisolarCalendarTest.cs, mcs/class/corlib/Test/System/DateTimeOffsetTest.cs, mcs/class/corlib/Test/System/DateTimeTest.cs, mcs/class/corlib/Test/System/TimeSpanTest.cs, mcs/class/corlib/corlib_test.dll.sources, mcs/class/corlib/corlib_xtest.dll.sources, mcs/class/referencesource/mscorlib/system/globalization/calendardata.cs
Add `GlobalizationMode.Invariant` conditionals to some calendar code.
This allows the Japanese, Taiwan and Hebrew calendars to be disabled.
=> Add conditionals allowing some calenders to be disabled.

Makefile.am, scripts/update_submodules.sh
GitHub provides a way to download a .zip/.tar.gz of the repository content in their UI, however the archive doesn't contain git submodules.
The mono build then fails with confusing "missing file" errors.
Since GitHub doesn't let us disable the archive download we should at least add some logic to detect this broken case and bail out.
=> [configure] Add failsafe for missing submodules

mono/metadata/class-init.c, mono/metadata/class-internals.h, mono/metadata/class.c, mono/metadata/class.h, mono/metadata/verify.c, mono/mini/interp/transform.c, mono/mini/method-to-ir.c
Currently we have two nullable API's that will have value in the public embedding API (already requestsed by users), eliminating the needs to go from native->managed and back to get nullable information about a type.
mono_class_is_nullable
mono_class_get_nullable_param
This PR moves them from class-internals.h into class.h and mark them with MONO_API and when needed include GC UNSAFE/SAFE transition..
=> Make nullable embedding API's public.

mcs/class/System.Private.CoreLib/Makefile.am
```
make[5]: Entering directory `/mnt/jenkins/workspace/build-source-tarball-mono/mcs/class/System.Private.CoreLib'
make[5]: Leaving directory `/mnt/jenkins/workspace/build-source-tarball-mono/mcs/class/System.Private.CoreLib'
make[5]: *** No rule to make target `dist-recursive'.  Stop.
make[4]: *** [dist-recursive] Error 1
```
dist-recursive is missing because we don't use rules.make because it totally breaks the world when fed through autotools, in the case of this one specific assembly.
=> [netcore] Fix `make dist`

mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj
This mirrors https://github.com/dotnet/corert/pull/7277/commits/6fab74f83ca1f302bf0eb284ed8979fcfe0dc76c, it should unblock merge of #13963.
Now the CoreRT change passed the CI and I tested a dry merge of #13963 to Mono with older compiler.
=> [netcore] Disable nullability-related warnings

mcs/class/corlib/System/Console.iOS.cs
* Make NSLogWriter thread-safe.
* Simplify newline checking in NSLogWriter.
* Fix NSLogWriter.Write to take into account the index and count parameters.
Backport of #13799.
/cc @lewurm @rolfbjarne
=> [2019-02] [corlib] Fix a few NSLogWriter issues.

mono/metadata/object.c, mono/tests/exception.cs
Reset the stack_trace and trace_ips because the type initialization exception is reused.
Fixes #13714
=> Cleaning exceptions during static constructor loading

sdks/builds/wasm.mk
This reverts the update for PR: https://github.com/mono/mono/pull/13759
- 1.38.30 is still not available for mac.
- Works on Build CI.
=> [wasm] Revert Update to emscripten 1.38.30 

mono/metadata/icall-internals.h, mono/metadata/icall.c, mono/mini/mini-runtime.c, sdks/wasm/driver.c
icalls registered with mono_add_internal_call, mono_add_internal_call_with_flags or mono_add_internal_call_internal ended up in two different hash tables depending if they were "foreign" or not. This caused double lookups in mono_lookup_internal_call_full. There are also use cases where it could be interesting to keep additional flags related to the icall, that could be used by codegen for various optimization.
This PR merge the two hash tables into one and add a flag describing icall details. The flag could later be extended with additional behaviors going forward if needed.
=> Merge icall_hash and icall_hash_foreign into one.

man/mono-profilers.1, mono/profiler/aot.c
Backport of https://github.com/mono/mono/pull/13688 & https://github.com/mono/mono/pull/13060
[profiler] Add duration=NUM parameter to AOT profiler (#13688)
* [profiler] Add duration=NUM parameter to AOT profiler
It instructs the AOT profiler to write the data after NUM seconds
measured from runtime initialization.
* [profilers] Added aot:duration=NUM parameter description
[profiler] Do not print that many new lines (#13060)
The `mono_profiler_printf` already adds `\n` char, so we don't need to
add them in most cases.
Before the fix the output of aot profiler with verbose enabled looked
like:
02-19 10:50:02.877 22795 22815 I mono-prof: System.OutOfMemoryException:.ctor (string) 2
02-19 10:50:02.877 22795 22815 I mono-prof:
02-19 10:50:02.877 22795 22815 I mono-prof: …
=> [2018-10] [profiler] Add duration=NUM parameter to AOT profiler (#13688)

man/mono-profilers.1, mono/profiler/aot.c
Backport of https://github.com/mono/mono/pull/13688 & https://github.com/mono/mono/pull/13060
[profiler] Add duration=NUM parameter to AOT profiler (#13688)
* [profiler] Add duration=NUM parameter to AOT profiler
It instructs the AOT profiler to write the data after NUM seconds
measured from runtime initialization.
* [profilers] Added aot:duration=NUM parameter description
[profiler] Do not print that many new lines (#13060)
The `mono_profiler_printf` already adds `\n` char, so we don't need to
add them in most cases.
Before the fix the output of aot profiler with verbose enabled looked
like:
02-19 10:50:02.877 22795 22815 I mono-prof: System.OutOfMemoryException:.ctor (string) 2
02-19 10:50:02.877 22795 22815 I mono-prof:
02-19 10:50:02.877 22795 22815 I mono-prof: …
=> [2019-02] [profiler] Add duration=NUM parameter to AOT profiler (#13688)

sdks/wasm/README.md
fix link to WebAssembly packager.exe in README.MD
=> [wasm][doc] - fix link in README.MD

configure.ac
Mono currently uses `__builtin_popcount[ll]` functions. On older processor architectures the popcount operations are implemented using software fallback in libgcc library. On MinGW this happens to pull in dependency on two dynamic libraries (libgcc_s_seh-1.dll and transitively libwinpthread-1.dll). These two libraries are together ~130 Kb of code that is pulled in because of ~12 bytes of one function. Linking statically to libgcc reduces the overhead to 4Kb in debug build (page size aligned) and simplifies the deployment because the resulting binary has no external dependencies.
=> [windows] Link libgcc statically on Windows

mcs/class/System.Windows.Forms/System.Windows.Forms/TreeNode.cs
When ImageIndex in TreeNode set to -2 must not displayed any image
=> [WinForms] Fix displayed image in TreeNode when ImageIndex set to -1

mcs/tools/cil-strip/Mono.Cecil.Signatures/SignatureReader.cs
cil-strip crashed when processing this method: https://github.com/mono/corefx/blob/f54e64b341a7b114c3502e197b46670cacb28639/src/Microsoft.CSharp/tests/DefaultParameterTests.cs#L88
It uses `MarshalAs((UnmanagedType)2000)`, i.e. an undefined value for the native type. The old Cecil embedded in cil-strip tried to read more than one byte which blows up in this case.
Upstream Cecil just reads a single byte:
https://github.com/jbevain/cecil/blob/1b79b96d29f1e8e9ba832191b1b42ea9cb750d20/Mono.Cecil/AssemblyReader.cs#L3700-L3703
Fixes https://github.com/mono/mono/issues/13639
=> [cil-strip] Fix reading of undefined NativeType values in old Cecil

mcs/tools/xbuild/LoggerInfo.cs
LoadFile lost assembly load-context. If the logger assembly has any dependencies placed in same folder logger can't load it. Main.cs using LoadFrom to load assembly but assembly already loaded in the cache after GetLoggerTypeName.
It is a regression in previous version mono(I'm not sure about certain version) didn't use cache in this case. We have some customer reports from Linux distro without msbuild(like Arch). They have a problem after  mono upgrade.
Backport of #12372.
/cc @EgorBo @mfilippov
=> [2018-10] Use LoadFrom instead LoadFile for load logger type.

mcs/class/System.Windows.Forms/System.Windows.Forms/Form.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/MdiFormTest.cs
Fixes #13282
Backport of #13283.
=> [2019-02] [SWF] Method OnClosed should pass FormClosedEventArgs type, instead of EventArgs

mcs/class/System.Windows.Forms/System.Windows.Forms/SplitContainer.cs
Fixes #13434
Backport of #13451.
=> [2019-02] [SWF] Fix Stackoverflow SplitContainer`s SplitterDistance set in SplitterMoved

mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/ComboBoxTest.cs
If combobox already was disposed and we setting Text field there will be NullReferenceException. On .net winforms there no excetions.
Backport of #13665.
=> [2019-02] Fix NRE when combobox was disposed and Text set

mcs/tools/cil-strip/Mono.Cecil.Signatures/SignatureReader.cs
cil-strip crashed when processing this method: https://github.com/mono/corefx/blob/f54e64b341a7b114c3502e197b46670cacb28639/src/Microsoft.CSharp/tests/DefaultParameterTests.cs#L88
It uses `MarshalAs((UnmanagedType)2000)`, i.e. an undefined value for the native type. The old Cecil embedded in cil-strip tried to read more than one byte which blows up in this case.
Upstream Cecil just reads a single byte:
https://github.com/jbevain/cecil/blob/1b79b96d29f1e8e9ba832191b1b42ea9cb750d20/Mono.Cecil/AssemblyReader.cs#L3700-L3703
Fixes https://github.com/mono/mono/issues/13639
Backport of #13954.
/cc @marek-safar @akoeplinger
=> [2019-04] [cil-strip] Fix reading of undefined NativeType values in old Cecil

mono/mini/debugger-agent.c
And remove assert that probed the wrong value, Coverity 1307166
=> [debugger-agent]: Print error if the socket can not be created

mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/13297.
Backport of #13301.
/cc @akoeplinger @vargaz
=> [2018-10] [jit] Avoid an assert when gsharedvt enums are boxed.

mcs/class/System.Private.CoreLib/Makefile.am
`make dist` stopped erroring in #13961 but didn't actually work, because the relevant Makefile.am was not distributed, causing configure to fail (because the Makefile.am was cited as an input, unconditionally).
We can't rely on the dist-recusrive from library.make or build.make because this lib is in a weirdo format which doesn't comply with the requirements of those helpers, so craft a simple handwritten replacement for our special case
=> [netcore] hand-craft a dist-recursive rule for System.Private.CoreLib

mcs/class/referencesource/mscorlib/system/typedreference.cs
=> Remove #if-def for TypedReference.MakeTypedReference readonly restriction

man/mono.1, mono/mini/driver.c, mono/utils/mono-mmap-wasm.c, mono/utils/mono-mmap-windows.c, mono/utils/mono-mmap.c, mono/utils/mono-mmap.h
Second version of this.  Previously #13446 which had to be reverted due to Windows and WASM breakage.
Add stub Win32 and WASM implementations of `mono_setmmapjit`
---
This is surfaced via a command line option, to not make this a strong API requirement on Xamarin.Mac requiring it. See companion patch:
Backport of #13958.
=> [2019-04] Do not use MAP_JIT by default (take 2)

man/mono.1, mono/mini/driver.c, mono/utils/mono-mmap-wasm.c, mono/utils/mono-mmap-windows.c, mono/utils/mono-mmap.c, mono/utils/mono-mmap.h
Second version of this.  Previously #13446 which had to be reverted due to Windows and WASM breakage.
Add stub Win32 and WASM implementations of `mono_setmmapjit`
---
This is surfaced via a command line option, to not make this a strong API requirement on Xamarin.Mac requiring it. See companion patch:
Backport of #13958.
=> [2019-02] Do not use MAP_JIT by default (take 2)

configure.ac
There are many minor arguments here.
Where this matters most -- iOS -- the pool is already dynamic.
Other platforms could use a dynamic pool or JIT (despite FullAOT).
Using JIT would defeat the test coverage.
Mitigates https://github.com/mono/mono/issues/13888.
If this feels too tenative, go bigger.
=> Increase gsharedvt trampolines by 10% from 4000 to 4400.

mcs/class/referencesource/mscorlib/system/typedreference.cs
Fixes #13162
Backport of #13991.
=> [2019-02] Remove TypedReference.MakeTypedReference readonly restriction

mcs/class/referencesource/mscorlib/system/typedreference.cs
Fixes #13162 
Backport of #13991.
=> [2019-04] Remove #if-def for TypedReference.MakeTypedReference readonly restriction

sdks/builds/wasm.mk
osx binaries are now available.
```
touch .stamp-wasm-checkout-and-update-emsdk
cd /Users/Jimmy/websharp/projects/mono/sdks/builds/toolchains/emsdk && ./emsdk install sdk-1.38.30-64bit
Fetching all tags from Emscripten Github repository...
Done. 158 tagged releases available, latest is 1.38.30.
Fetching all tags from Binaryen Github repository...
Done. 85 tagged Binaryen releases available, latest is 1.38.30.
Fetching all precompiled tagged releases..
Downloading: /Users/Jimmy/websharp/projects/mono/sdks/builds/toolchains/emsdk/llvm-tags-32bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_32bit/index.txt
Downloading: /Users/Jimmy/websharp/projects/mono/sdks/builds/toolchains/emsdk/llvm-tags-64bit.txt from …
```
=> [wasm] Updating to recent sdk 1.38.30.

mono/mini/interp/interp.c, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c, mono/utils/mono-tls.c, mono/utils/mono-tls.h
It doesn't matter, but for code clarity.
Also strengthen the types of both of these, though rarely enough to avoid casts.
=> Remove constant parameter to mono_tls_get_tls_setter and mono_tls_get_tls_getter.

mono/mini/aot-compiler.c
It is checked just a few lines earlier.
=> Remove redundant check of llvm_acfg->aot_opts.direct_icalls.

mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj, mcs/class/System.Private.CoreLib/System.Reflection/AssemblyName.cs, mono/mini/method-to-ir.c
I think it's just a typo made in https://github.com/mono/mono/pull/13906
I tried to run System.Runtime.Tests on top of the fresh master and I got:
```
Method 'void Xunit.DiaSession:.cctor ()' which contains a StackCrawlMark local variable must be decorated with [System.Security.DynamicSecurityMethod].
```
so I suspect one of the `Type.GetType` was inlined despite the `[DynamicSecurityMethod]` attribute.
However after this fix I am getting:
```
System.InvalidOperationException: Could not find/load any of the following assemblies: xunit.execution.dotnet.dll
```
**UPD**: Applying @filipnavara's fix for the `InvalidOperationException` (missing null-check in CompurePublickKey).
cc: @filipnavara
=> [netcore] Do not inline if [DynamicSecurityMethod] exists

mcs/class/System.Windows.Forms/System.Windows.Forms/TreeNode.cs
When ImageIndex in TreeNode set to -2 must not displayed any image
Backport of #13933.
=> [2019-02] [WinForms] Fix displayed image in TreeNode when ImageIndex set to -1

mcs/class/System.Windows.Forms/System.Windows.Forms/TreeNode.cs
When ImageIndex in TreeNode set to -2 must not displayed any image
Backport of #13933.
=> [2019-04] [WinForms] Fix displayed image in TreeNode when ImageIndex set to -1

mcs/class/System.Private.CoreLib/System/Attribute.cs, mcs/class/corlib/System/MonoCustomAttrs.cs
This fixes 12 tests in System.Runtime.Tests.
Basically the fix replicates https://github.com/dotnet/coreclr/blob/edffbd9c545aa9c1f6cb7ae048efdf5db13d3991/src/System.Private.CoreLib/src/System/Attribute.CoreCLR.cs#L457-L458
=> [netcore] fix some CustomAttribute related tests

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
At the end of the AOT compilation, we dump a table containing all method
entrypoints using the toolchain linker to resolve the addresses. Previously
we used `bl` for that, however on larger assemblies the offset might
overflow the 24bit immediate (thus, the linker bailing out with
"Error: branch out of range"). Instead, using `ldr pc,=<label>` followed
by `.ltorg` emits the full 32bit address to a method. That takes 8 bytes
for each method instead of 4 bytes.
( I couldn't reopen https://github.com/mono/mono/pull/3486 anymore)
=> [aot] change method table generation so that it works for larger assemblies on ARM

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
At the end of the AOT compilation, we dump a table containing all method
entrypoints using the toolchain linker to resolve the addresses. Previously
we used `bl` for that, however on larger assemblies the offset might
overflow the 24bit immediate (thus, the linker bailing out with
"Error: branch out of range"). Instead, using `ldr pc,=<label>` followed
by `.ltorg` emits the full 32bit address to a method. That takes 8 bytes
for each method instead of 4 bytes.
( I couldn't reopen https://github.com/mono/mono/pull/3486 anymore)
Backport of #14043.
=> [2019-02] [aot] change method table generation so that it works for larger assemblies on ARM

mcs/tools/Makefile, mcs/tools/cil-strip/mono-cil-strip.csproj, sdks/wasm/Makefile, sdks/wasm/packager.cs
- Build, package and deliver `mono-cil-strip` in the mono `wasm_tools` to be used without relying on it being installed on the host system.
- Use the `mono-cil-strip` from the `wasm_tools` directory same as `monolinker.exe` and `wasm-tuner`.
=> [wasm] [packager] Run mono-cil-strip from wasm-tools

mcs/class/System.Private.CoreLib/System/Attribute.cs, mcs/class/corlib/System/MonoCustomAttrs.cs
This is fix for regressions from #14056 (System.ComponentModel.Composition.Tests) and #14050 (System.Runtime.Tests).
Essentially the issue is that `Attribute` methods (`GetCustomAttribute`, `GetCustomAttributes`, `IsDefined`) have to check if the `attributeType` is subclass of `Attribute` or `Attribute` itself. On the other hand other custom attribute methods should not check that because someone can ask for all custom attributes implementing some interface as the component model code does. All of these calls end up calling `MonoCustomAttrs` so the `attributeType` parameter checks have to be in `Attribute` class.
This highlights the need to get some CI working ASAP since we keep breaking it (myself included). I'm keeping this as draft until I run the full test suite on my machine to check …
=> [netcore] Fix couple of custom attribute tests

mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj, mcs/class/System.Private.CoreLib/System.Runtime.InteropServices/MarshalAsAttribute.cs, mcs/class/System.Private.CoreLib/System/Attribute.cs, mcs/class/corlib/System/MonoCustomAttrs.cs, mono/metadata/object-internals.h, netcore/Makefile.am
~@filipnavara noticed my previous [PR](https://github.com/mono/mono/pull/14056#issuecomment-483387022) broke `System.ComponentModel.Composition.Tests`.
Those were expecting to find custom attributes by an interface those attributes implement.~
This PR also fixes 7 test cases in `System.Tests.PseudoCustomAttributeTests.*`
Now results are:
```
System.Runtime.Tests  Total: 32363, Errors: 0, Failed: 38, Skipped: 0, Time: 28.718s
```
```
System.ComponentModel.Composition.Tests  Total: 1428, Errors: 0, Failed: 2, Skipped: 0, Time: 1.181s
```
`build-local-corefx-test-%` is a command to build corefx tests locally and put them to corefx/tests/extracted/$*.
=> [netcore] Fix System.Tests.PseudoCustomAttributeTests.* tests

mcs/class/System/monotouch_runtime_System.dll.exclude.sources, mcs/class/System/monotouch_tv_runtime_System.dll.exclude.sources
They were missing some exclude files that caused unnecessary p/invokes to be retained.
Fixes https://github.com/mono/mono/issues/13526
=> [2018-10] [System] Fix monotouch_runtime repl assemblies

mono/mini/exceptions-arm.c
This is a regression introduced by e46fa20466010a18b9b9a8130f6d8c62899780b3
Fixes https://github.com/mono/mono/issues/13672
Backport of #14078.
=> [2019-04] [arm] align stack pointer in throw trampoline

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
At the end of the AOT compilation, we dump a table containing all method
entrypoints using the toolchain linker to resolve the addresses. Previously
we used `bl` for that, however on larger assemblies the offset might
overflow the 24bit immediate (thus, the linker bailing out with
"Error: branch out of range"). Instead, using `ldr pc,=<label>` followed
by `.ltorg` emits the full 32bit address to a method. That takes 8 bytes
for each method instead of 4 bytes.
( I couldn't reopen https://github.com/mono/mono/pull/3486 anymore)
Backport of #14043.
=> [2019-04] [aot] change method table generation so that it works for larger assemblies on ARM

packaging/MacSDK/msbuild.py
.. to pick up update for the NuGetSdkResolver.
https://github.com/mono/msbuild/pull/92
=> Bump msbuild to track mono-2018-08

mono/mini/exceptions-arm.c
This is a regression introduced by e46fa20466010a18b9b9a8130f6d8c62899780b3
Fixes https://github.com/mono/mono/issues/13672
=> [arm] align stack pointer in throw trampoline

mono/mini/exceptions-arm.c
This is a regression introduced by e46fa20466010a18b9b9a8130f6d8c62899780b3
Fixes https://github.com/mono/mono/issues/13672
Backport of #14078.
/cc @lambdageek @lewurm
=> [2019-02] [arm] align stack pointer in throw trampoline

mono/mini/method-to-ir.c
We were setting the stack type by using another global local named ins.
This lead to missing methods in the aot image due to invalid IL. Fixes https://github.com/mono/mono/issues/13479.
Backport of #13817.
=> [2019-02] [gsharedvt] Fix sizeof opcode

mono/mini/calls.c, mono/mini/mini-arm.c, mono/mini/mini-arm64.c, mono/mini/mini-mips.c, mono/mini/mini-ppc.c, mono/mini/mini-s390x.c, mono/mini/mini.c, mono/mini/mini.h
of repeated code in many backends.
This notably does not apply to amd64, x86.
They have more logic intertwined around the patch when they emit the call.
=> Factor the function mono_call_add_patch_info out of a few lines

mcs/class/corlib/Test/System.IO/FileTest.cs
System.IO.Filesystem's MoveFile() and ReplaceFile() use link/unlink under some conditions to avoid a copy. This fixes two problems with that:
* MoveFile()'s fall-back does not recognize Android's error as non-critical, and bails out on the fall-back with an exception. From logs we know that 'strerror_r(android_error)' is 'Permission denied' so the missing error should be EACCES (we already check for EPERM)
* While MoveFile() was using a fall-back, ReplaceFile() wasn't.
Also improve a relevant test for more useful fault output.
=> [corefx] Use fallbacks when link() fails

mono/metadata/sre.c, mono/metadata/w32handle.c
Now all custom attribute related tests pass in System.Runtime.Tests.
Also this PR fixes broken acceptance tests for regular mono introduced in https://github.com/mono/mono/pull/13809
=> [netcore] Fix two System.Tests.PseudoCustomAttributeTests tests

mono/metadata/remoting.c
Alternative to https://github.com/mono/mono/pull/14076.
Alternatively move the registration to mono_remoting_init.
This should fix a problem I see in other work, and *seems* like an existing race condition.
In particular, you can emit a function pointer, and then:
```
case MONO_CEE_MONO_ICALL: {
g_assert (method->wrapper_type != MONO_WRAPPER_NONE);
gpointer func;
MonoJitICallInfo *info;
func = mono_method_get_wrapper_data (method, token);
info = mono_find_jit_icall_by_addr (func);
if (!info)
g_error ("Could not find icall address in wrapper %s", mono_method_full_name (method, 1));
g_assert (info);
```
though I don't know why with my changes this always hits, and previously never.
Anyway, it seems like this is the original intent.
Moving the initializer earlier would make it easier to …
=> mono_remoting_marshal_init in mono_marshal_get_proxy_cancast to register icalls.

mono/mini/aot-compiler.c, mono/mini/aot-compiler.h, mono/mini/method-to-ir.c
An icall declaration can now use the following attribute:
MonoDirectICallSymbolNameAttribute("MyNativeCFunction")
and if not already defined in icall-def.h and direct-icalls are used when AOT compile the assembly, a direct call will use symbol defined in attribute as the symbol for direct call. Using this attribute will also enable inlining for the specific icall wrapper generating inlined direct icalls to external defined native methods.
This feature is valuable when embedding the runtime and extend with icalls added using mono_add_internal_call. By applying the above attribute, it is possible to do AOT with direct-icalls and get static linked icalls without the need to extend and rebuild cross compiler in the process.
=> Add support for direct icalls using external functions not in icall-def.h.

README.md
This flag only applies to the Boehm GC, but it's not obvious until you dig down into the source code. I thought that an edit like this to the readme would help prevent future confusion for others, given that SGen the default.
=> Update documentation for --with-large-heap

configure.ac
There are many minor arguments here.
Where this matters most -- iOS -- the pool is already dynamic.
Other platforms could use a dynamic pool or JIT (despite FullAOT).
Using JIT would defeat the test coverage.
Mitigates https://github.com/mono/mono/issues/13888.
If this feels too tenative, go bigger.
Backport of #13988.
=> [2019-04] Increase gsharedvt trampolines by 10% from 4000 to 4400.

configure.ac
There are many minor arguments here.
Where this matters most -- iOS -- the pool is already dynamic.
Other platforms could use a dynamic pool or JIT (despite FullAOT).
Using JIT would defeat the test coverage.
Mitigates https://github.com/mono/mono/issues/13888.
If this feels too tenative, go bigger.
Backport of #13988.
=> [2019-02] Increase gsharedvt trampolines by 10% from 4000 to 4400.

mono/metadata/marshal.c
MS's C++ compiler emits code that uses this.
=> Respect call convention modopts in native wrappers.

mcs/class/corlib/Test/System.Reflection/MethodInfoTest.cs, mono/metadata/object.c
Trying to box a null value crashes inside mono_gc_wbarrier_value_copy_internal. As described by the customer using version 5.18.0.240 the crash doesn't happen.
As I could debug using this version doesn't crash only because is ignoring the SIGSEGV, when I attach to LLDB I can see the same crash in both versions.
I protected to only add data to res_handle if there is a valid value.
Fixes #13969
Backport of #14018.
=> [2019-02] Protecting boxing a null value

mcs/class/corlib/Test/System.Reflection/MethodInfoTest.cs, mono/metadata/object.c
Trying to box a null value crashes inside mono_gc_wbarrier_value_copy_internal. As described by the customer using version 5.18.0.240 the crash doesn't happen.
As I could debug using this version doesn't crash only because is ignoring the SIGSEGV, when I attach to LLDB I can see the same crash in both versions.
I protected to only add data to res_handle if there is a valid value.
Fixes #13969
Backport of #14018.
=> [2019-04] Protecting boxing a null value

mcs/class/corlib/Test/System.Reflection/MethodInfoTest.cs, mono/metadata/object.c
Trying to box a null value crashes inside mono_gc_wbarrier_value_copy_internal. As described by the customer using version 5.18.0.240 the crash doesn't happen.
As I could debug using this version doesn't crash only because is ignoring the SIGSEGV, when I attach to LLDB I can see the same crash in both versions.
I protected to only add data to res_handle if there is a valid value.
Fixes #13969
=> Protecting boxing a null value

mcs/class/corlib/monodroid_corlib_xtest.dll.exclude.sources
The test case CopyFileWithData_MemberData with input of size 1024 * 1024 * 10
causes the Xamarin.Android.Bcl_Tests to crash for some reason.  Temporarily
exclude this entire set of tests from running.
Also disable System.IO.Tests.FileInfo_CopyTo_str because it derives from the
above test class.
=> [monodroid] Exclude System.IO.Tests.File_Copy_str_str CoreFX testsuite

mono/metadata/assembly.c, mono/metadata/image.c
In `mono_image_open_a_lot`,  if `MonoImageOpenStatus *status` is null, don't write to it.
Also fixed up a few other places where we have assignments `*status = foo` by either:
* asserting that `status` is not null at the outset, or
* passing a local MonoImageOpenStatus if the argument is null, or
* adding a null check before the assignment.
Fixes #13941
=> [loader] Don't store through a null ptr

mono/mini/aot-compiler.c
We need to emit a real call here. On arm/android we would emit this now:
```asm
ldr pc, =label
.ltorg         # place address of `label` here.
```
which is a jump to `label`, not a call.
We need a different solution to make larger assemblies work, but for now
I revert it so the `2019-02` intergration is unblocked.
Partial revert of #14043
Backport of #14135.
/cc @lewurm
=> [2019-02] [aot] partial revert of #14043

mono/mini/mini-runtime.c
Ultimate goal is to significantly reduce or maybe completely
eliminate the hashing of JIT icalls.
It is not a small change.
This is a small digestable albeit tedious step toward that.
The "names" of opcode emulation icalls are needed for
token pasting and/or struct fields. They are needed without quotes.
This PR removes the quotes.
And then for now, just always restores them.
This is extracted from https://github.com/mono/mono/pull/14047
as a step toward making it easier to review.
=> Small step toward reduction/elimination of JIT icall hashing.

mcs/class/corlib/Test/System.Reflection/MethodInfoTest.cs, mono/metadata/object.c
When a static method is called the obj is not used, so it can be null and it doesn't need to be boxed.
Adding an assert in the method to prevent other crash in this method if a NULL is received.
Fixes #13969
Backport of #14018.
=> [2018-10] Protecting boxing a null value

packaging/MacSDK/patches/fsharp-msbuild-16-0.patch
Fixes:
```
23:55:47  can't find file to patch at input line 5
23:55:47  Perhaps you used the wrong -p or --strip option?
23:55:47  The text leading up to this was:
23:55:47  --------------------------
23:55:47  |diff --git a/mono/config.make.in b/mono/config.make.in
23:55:47  |index 3106ab99f..8af247ffd 100644
23:55:47  |--- a/mono/config.make.in
23:55:47  |+++ b/mono/config.make.in
23:55:47  --------------------------
23:55:47  File to patch: 
23:55:47  Skip this patch? [y] 
23:55:47  Skipping patch.
23:55:47  4 out of 4 hunks ignored
```
e.g. https://jenkins.mono-project.com/job/build-package-osx-mono/job/2019-02/173/console
=> Fix MSBuild/FSharp patch, which was missed in backport

sdks/wasm/Makefile, sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.csproj, sdks/wasm/sdk/Mono.WebAssembly.Build/WasmLinkAssemblies.cs, sdks/wasm/sdk/Mono.WebAssembly.Framework/Mono.WebAssembly.Framework.csproj, sdks/wasm/sdk/Mono.WebAssembly.Runtime.Framework/Mono.WebAssembly.Runtime.csproj, sdks/wasm/sdk/Mono.WebAssembly.Sdk/sdk/Sdk.props
The PR targets the sdk project build to make sure they run on windows and VS 2019
- Package the wasm bcl and wasm bcl Facades correctly.
- Move the build props and targets file to `netstandard2.0` build directory.
- Place `framework` .props file properly for build
- Place `runtime` .props file properly for build
- Modify the WasmLinkAssemblies Task to escape the windows path separator.  - There are problems executing `mononlinker.exe` on windows if the windows path separators are not escaped. 
**Note:**
* Tested on VS 2019 project on windows.
* VS Mac 2019 has problems executing these project types.  VS Mac 2017 did not have problems.
=> [wasm][sdk] Fixes to the sdk packages

mono/eglib/ghashtable.c, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/mini-runtime.c
e.g. whenever underlying representation is nul terminated string.
MONO_PATCH_INFO_LDSTR_LIT
MONO_PATCH_INFO_OBJC_SELECTOR_REF
almost the same as
MONO_PATCH_INFO_JIT_ICALL
MONO_PATCH_INFO_JIT_ICALL_ADDR
MONO_PATCH_INFO_JIT_ICALL_ADDR_NOCALL
MONO_PATCH_INFO_LDSTR_LIT no longer allocate
and copy the string from the AOT image into image_pool.
g_str_equal check pointer equality first.
While obviously correct, not obviously faster,
as it adds cost when strings are unequal.
Uninline g_str_equal, seems cleaner, but perhaps less efficient.
Combine the switch-exit and default: paths,
as only one case other than default exited the switch.
Lift out other common subexpressions.
=> Cleanup patch_info code a little.

mono/mini/aot-compiler.c
We need to emit a real call here. On arm/android we would emit this now:
```asm
ldr pc, =label
.ltorg         # place address of `label` here.
```
which is a jump to `label`, not a call.
We need a different solution to make larger assemblies work, but for now
I revert it so the `2019-02` intergration is unblocked.
Partial revert of #14043
=> [aot] partial revert of #14043

mono/mini/aot-compiler.c
We need to emit a real call here. On arm/android we would emit this now:
```asm
ldr pc, =label
.ltorg         # place address of `label` here.
```
which is a jump to `label`, not a call.
We need a different solution to make larger assemblies work, but for now
I revert it so the `2019-02` intergration is unblocked.
Partial revert of #14043
Backport of #14135.
/cc @lewurm
=> [2019-04] [aot] partial revert of #14043

acceptance-tests/roslyn.mk, scripts/ci/run-test-acceptance-tests.sh
We were inadvertently running the roslyn tests against the system mono in CI.
Instead we now install mono to a custom prefix, prepend that to PATH and run
the roslyn tests against the correct mono we just built.
=> [acceptance-tests] Run roslyn tests using in-tree mono instead of system mono

Makefile.am
Closes: https://github.com/mono/mono/issues/11501
Backport of #11509.
/cc @directhex
=> [2018-10] Clean up .o files from System.Native during `make dist`

mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
This method returns a function pointer that can be called with a calli instruction. On interpreter we use a pointer to InterpMethod while on jit we use the native code address. Normally, GetFunctionPointer should return the InterpMethod pointer if called from interp or the native code address if called from jit. Since we don't have any information about the execution engine of the caller, we solve this by intrinsifying all these calls, that happen in the interpreter.
Passing such function pointers between jitted and interp code is probably still unreliable.
Fixes https://github.com/mono/mono/issues/13654
=> [2019-02] [interp] Fix GetFunctionPointer

mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/13297.
Backport of #13301.
=> [2018-08] [jit] Avoid an assert when gsharedvt enums are boxed.

acceptance-tests/roslyn.mk, scripts/ci/run-test-acceptance-tests.sh
We were inadvertently running the roslyn tests against the system mono in CI.
Instead we now install mono to a custom prefix, prepend that to PATH and run
the roslyn tests against the correct mono we just built.
Backport of #14186.
=> [2019-04] [acceptance-tests] Run roslyn tests using in-tree mono instead of system mono

acceptance-tests/roslyn.mk, scripts/ci/run-test-acceptance-tests.sh
We were inadvertently running the roslyn tests against the system mono in CI.
Instead we now install mono to a custom prefix, prepend that to PATH and run
the roslyn tests against the correct mono we just built.
Backport of #14186.
=> [2019-02] [acceptance-tests] Run roslyn tests using in-tree mono instead of system mono

mcs/tools/linker/monolinker.csproj, mcs/tools/linker/monolinker.exe.sources, mono/mini/aot-compiler.c, mono/mini/aot-compiler.h, mono/mini/mini-llvm-cpp.cpp, mono/mini/mini-llvm-cpp.h, mono/mini/mini-llvm.c, sdks/wasm/packager.cs
This change allows LLVM to identify unnecessary null checks. We mark GOT accesses (including those made by LDSTR) and new object calls as nonnull.
Since LLVM won't propagate this, we propagate from definition to usage, across casts, and from usage to definition (conditionally).
This enables it to remove a significant portion of some benchmarks. 
In real-world code, we can expect to see this remove the unnecessary null checks made by private methods. 
Note that the constant strings are trivially non-null. This PR spots and propagates that. 
```
static void ThrowIfNull(string s)
{
if (s == null)
ThrowArgumentNullException();
}
static void ThrowArgumentNullException()
{
throw new ArgumentNullException();
}
static int Bench(string a, string b, string …
```
=> [llvm] Propagate nonnull attribute through LLVM IR

mono/mini/builtin-types.cs, mono/mini/interp/transform.c
Fixes https://github.com/xamarin/xamarin-macios/issues/5809
/cc @spouliot
=> [interp] fix op_explicit for cast from nfloat to nint and vice versa

mono/metadata/gc.c, mono/metadata/monitor.c, mono/metadata/threadpool.c, mono/metadata/threads.c, mono/metadata/w32file-win32-uwp.c, mono/metadata/w32file-win32.c, mono/metadata/w32handle.c, mono/metadata/w32socket-win32.c, mono/utils/mono-os-wait-win32-uwp.c, mono/utils/mono-os-wait-win32.c, mono/utils/mono-os-wait.h, mono/utils/mono-threads-coop.c, mono/utils/mono-threads-posix.c, mono/utils/mono-threads-wasm.c, mono/utils/mono-threads-windows.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h, mono/utils/win64.asm, msvc/mono.winconfig.targets, winconfig.h
Adding initial support for hybrid and cooperate suspend on Windows 32/64-bit platforms.
Fixes/adjustments needed in several areas:
Implementation/emulation of gcc's __builtin_unwind_init on MSVC needed by copy_stack_data function.
All wait methods have been extended with a cooperative alternative + handling interrupt under hybrid/cooperative suspend.
Methods that handles IO abort interruption on Windows (file, socket) have been updated to handle interrupt under hybrid/cooperative suspend.
Moved Windows implementations into w32handle.c instead of #ifdef on call site.
Reduced number of GC safe transition in a couple of Win32 file IO methods.
Added restore logic to Win32 last error when exiting GC safe mode. This is needed since we have code that depends on GetLastError that could be …
=> Add hybrid/cooperate suspend runtime support on Windows.

mono/metadata/marshal-ilgen.c, mono/mini/interp/interp.c, mono/mini/interp/transform.c
We already do it when we get back to the interpreter.
=> [interp] Don't check for exception in native wrappers

mcs/class/corlib/Test/System/TypeTest.cs
TypeTest.MakeGenericType_BadUserType
TypeTest.MakeGenericType_NestedUserDefinedType
TypeTest.MakeGenericType_UserDefinedType
TypeTest.TestMakeGenericType_UserDefinedType_DotNet20SP1
These tests pass when run with the interpreter on xamarin-macios.
They were disabled on master with https://github.com/mono/mono/commit/dc9bc9e0e6462739872117afc59e46fbc780d981
Backport of #12868.
/cc @lambdageek @akoeplinger
=> [2018-08] [corlib] Disable four tests in TypeTest

mono/mini/builtin-types.cs, mono/mini/interp/transform.c
Fixes https://github.com/xamarin/xamarin-macios/issues/5809
/cc @spouliot 
Backport of #14201.
/cc @lewurm
=> [2019-04] [interp] fix op_explicit for cast from nfloat to nint and vice versa
