mcs/class/System.Windows.Forms/System.Windows.Forms/ContainerControl.cs
mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs
mcs/class/System.Windows.Forms/System.Windows.Forms/Form.cs
mcs/class/System.Windows.Forms/Test/System.Windows.Forms/FormEventTest.cs

Fixes #13150
Backport of #13151

[WinForms] Related Forms closing issue

---

configure.ac
netcore/Makefile
netcore/runtime.nuspec
scripts/ci/pipeline-netcore-runtime.yml

`  Successfully created package 'D:\a\1\s\artifacts\runtime.win-x64.Microsoft.NETCore.Runtime.Mono.6.3.0.656.nupkg'.`

[netcore] Build/upload Windows runtime nupkg

---

scripts/ci/pipeline/sdks-archive.groovy

[sdks] Set PATH in Android Windows SDK pipeline job

---

mono/mini/mini-arm.c

Backport of https://github.com/mono/mono/pull/14444

[2019-02] [arm] one more attempt to fix slotsize issue on llvmonly (#14444)

---

packaging/MacSDK/msbuild.py
packaging/MacSDK/nuget.py

.. to pick up an update for the NuGetSdkResolver.

Bump msbuild to track mono-2019-02

---

mono/mini/intrinsics.c

Fixes https://github.com/mono/mono/issues/14551.

[jit] Fix signed/unsigned comparisons in JitHelpers.EnumCompareTo () intrinsic.

---

mcs/class/System.Private.CoreLib/System/RuntimeType.cs
mono/metadata/object.c
netcore/CoreFX.issues.rsp

This PR enables 87 tests in `System.Runtime.Tests`.

[netcore] Fix PointerTests

---

mcs/build/tests.make

So it gets included in the sdks archive

[tests] Add Xunit.NetCore.Extensions.dll to tests directory

---

mono/mini/mini-arm.c

Backport of https://github.com/mono/mono/pull/14444

[2019-04] [arm] one more attempt to fix slotsize issue on llvmonly (#14444)

---

mono/metadata/loader.c

Context: https://github.com/xamarin/xamarin-android/issues/2780
On Android the executable for the application is going to be
`/system/bin/app_process{32,64}` depending on the application's architecture.
However, libraries for the different architectures live in different
subdirectories of `/system`: `lib` for 32-bit apps and `lib64` for 64-bit ones.
Thus appending `/lib` below will fail to load the DSO for a 64-bit app, even if
it exists there, because it will have a different architecture. The quickest fix
is to use `lib64` explicitly for 64-bit Android apps.
Backport of #13281.
/cc @lambdageek @grendello

[Android] Fix runtime loading of DSOs for 64-bit processes

---

mono/metadata/threads.c

There's been a few instances of telemetry which seems to show the SIGTERM signal handler firing and starting a dump, and then dying at the end due to not having the place to output the created dump. 
```
INFO [2019-03-28 17:53:08Z]: Add-in loaded: MonoDevelop.VBBinding
INFO [2019-03-28 17:53:08Z]: [Inspector] Initializing
INFO [2019-03-28 17:53:08Z]: Add-in loaded: Xamarin.TestCloud.NUnit
Pkilling 0x70000eb4c000 from 0x7fffa3728380
Pkilling 0x70000d72e000 from 0x7fffa3728380
Pkilling 0x70000e949000 from 0x7fffa3728380
Pkilling 0x70000d52b000 from 0x7fffa3728380
Pkilling 0x70000d222000 from 0x7fffa3728380
Pkilling 0x70000e746000 from 0x7fffa3728380
Pkilling 0x70000e543000 from 0x7fffa3728380
Pkilling 0x70000e340000 from 0x7fffa3728380
Pkilling 0x70000e13d000 from 0x7fffa3728380
Pkilling …
```

[merp] Add assertions against initing dumper from signal handler

---

mono/metadata/Makefile.am
msvc/libmonoruntime-common.targets
msvc/libmonoruntime-common.targets.filters

They were added in https://github.com/mono/mono/pull/14427

Add missing new files to Makefile.am, fix tarball build

---

mcs/class/System/System.Security.Authentication/SslProtocols.cs
mcs/class/corlib/Test/System.Collections.ObjectModel/CollectionTest.cs

I myself am bumping for ODBC fixes. This includes a change to `SslProtocols` to include the `Tls13` entry required by the CoreFX changes. (It doesn't wire it up to anything, including BTLS.)

Bump CoreFX and make necessary changes

---

scripts/ci/run-jenkins.sh

- Chakra 1.11.9 release is now out which fixes https://github.com/microsoft/ChakraCore/issues/6037
Closes https://github.com/mono/mono/issues/13195

[wasm][ci] Enable ChakraCore tests

---

configure.ac
mcs/build/common/basic-profile-check.cs
mcs/build/rules.make
mcs/build/start-compiler-server.sh
msvc/scripts/genproj.cs

Infrastructure support / fixes for making compiler server the default

---

netcore/roslyn.make

Fixes https://github.com/mono/mono/issues/14689

[netcore] Bump roslyn

---

scripts/ci/pipeline/sdks-archive.groovy

Forward port of #14503 to `master` (includes also #14519 and #14516).
Part of #14333

[ci] Add Android Windows (Release) archive job to the pipeline

---

mono/metadata/mempool.c

per https://github.com/mono/mono/issues/14669

Cleanup mono_mempool_alloc0 code duplication from mono_mempool_alloc

---

sdks/wasm/docs/WASM-REQUESTS.md

[wasm] Add document with wasm feature requests.

---

THIRD-PARTY-NOTICES.TXT

Update TPN with Mono entry

---

.gitignore
mcs/class/Makefile
mcs/class/Mono.Profiler.Log/Makefile
mcs/class/Mono.Profiler.Log/Mono.Profiler.Aot/ProfileData.cs
mcs/class/Mono.Profiler.Log/Mono.Profiler.Aot/ProfileReader.cs
mcs/class/Mono.Profiler.Log/Mono.Profiler.Aot/Records.cs
mcs/class/Mono.Profiler.Log/Mono.Profiler.Log.csproj
mcs/class/Mono.Profiler.Log/Mono.Profiler.Log.dll.sources

[Mono.Profiler.Log] Add profiled data reader APIs

---

mono/sgen/sgen-array-list.c
mono/sgen/sgen-array-list.h

Update license to match directory

---

.gitignore
mcs/class/Makefile
mcs/class/Mono.Profiler.Log/Makefile
mcs/class/Mono.Profiler.Log/Mono.Profiler.Aot/ProfileData.cs
mcs/class/Mono.Profiler.Log/Mono.Profiler.Aot/ProfileReader.cs
mcs/class/Mono.Profiler.Log/Mono.Profiler.Aot/Records.cs
mcs/class/Mono.Profiler.Log/Mono.Profiler.Log.csproj
mcs/class/Mono.Profiler.Log/Mono.Profiler.Log.dll.sources

Extracted from #4305
Backport of #14664.

[2019-06] [Mono.Profiler.Log] Add profiled data reader APIs

---

sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets

[wasm][sdk] Clean the `managed` directory files on `/t:Clean` build target

---

mono/mini/interp/transform.c

[interp] Inline more methods

---

mcs/class/referencesource/mscorlib/system/globalization/calendardata.cs

See https://github.com/mono/corefx/pull/298 for a description of the
technique that we're using here to make it more linker friendly.

Make `CalendarData` more linker friendly.

---

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs

Trying to unrevert https://github.com/mono/mono/pull/7390.
Couldn't reproduce the same side effect as that caused before.
This PR fixes #7377

[Mono.Debugger.Soft] Properly close connections 

---

mono/utils/mono-threads-mach-helper.c

[mach] cast objc_msgSend{,Super} usages

---

mono/mini/mini-amd64.c

And it is reasonable to expect that to remain the case, as C compilers
do not generate code as would occur with the last parameter = TRUE.
They allocate the room for their maximum outgoing parameters at function entry,
and keep a constant stack, except for functions that call _alloca,
and this code risks but not necessarily breaks ABI compliance.
In particular, the rsp adjustment either needs unwind codes, or needs
to only occur in a function with a frame pointer other than RSP.
And the uwind codes for adding to RSP are very tricky to impossible.
Normally you only ever subtract from RSP. There is an unwind code for that.
But there isn't really for add.
You might be able to simulate it with chained unwind, making these
regions look kinda like end of function.
But this is all most unlikely. …

Cleanup amd64 emit_call / emit_call_body -- last parameter always FALSE. And let compiler decide inline.

---

mono/mini/aot-compiler.c

Fixes https://github.com/xamarin/xamarin-android/issues/3168.
Backport of #14992.
/cc @vargaz

[2019-02] [aot] Open AOT profile files using "rb" so it works on windows.

---

mono/mini/aot-compiler.c

Fixes https://github.com/xamarin/xamarin-android/issues/3168.

[aot] Open AOT profile files using "rb" so it works on windows.

---

mcs/class/referencesource/mscorlib/system/rttype.cs

This fixes set of warning currently appearing during build.

[netcore] Fix some warning related to nullability of reference types

---

mono/metadata/marshal.c
mono/mini/gshared.cs
mono/mini/mini-generic-sharing.c

Fixes https://github.com/mono/mono/issues/14972.

[runtime] Fix gshared support for BeginInvoke ()/EndInvoke () wrappers.

---

mcs/class/System.Private.CoreLib/System.Runtime.InteropServices/NativeLibrary.Unix.cs
netcore/CoreFX.issues.rsp
netcore/CoreFX.issues_linux.rsp
netcore/Makefile
scripts/ci/pipeline-netcore-runtime.yml

See https://github.com/mono/mono/pull/14849#issuecomment-501151916

[netcore] Enable CoreFX tests on CI for Linux

---

mono/metadata/image.c

The second assignment to the "problematic" image boolean out-parameter was in the wrong place. 
I've moved it down into register_image. 
I also enabled it here on Windows. As I recall, this is particularly relevant on Windows.

[metadata] Move problematic image out-param usage

---

mono/mini/ee.h
mono/mini/interp-stubs.c
mono/mini/interp/interp.c
mono/mini/mini-amd64.c
mono/mini/mini-arm.c
mono/mini/mini-arm64.c
mono/mini/mini-runtime.c
mono/mini/mini-runtime.h

This time without any order sensitivity.
Another alternative to https://github.com/mono/mono/pull/14648.

Readonly interp callbacks.

---

netcore/CoreFX.issues.rsp
netcore/CoreFX.issues_linux.rsp
netcore/Makefile
netcore/System.Private.CoreLib/System.Private.CoreLib.csproj
netcore/build.sh
netcore/sample/HelloWorld/HelloWorld.csproj
scripts/ci/pipeline-netcore-runtime.yml

[netcore] Fix CI build script

---

mono/metadata/icall-signatures.h
mono/mini/aot-compiler.c
mono/mini/interp/interp.c

[interp] Prefer interp_in wrappers over trampolines

---

mcs/class/Mono.Profiler.Log/Mono.Profiler.Aot/ProfileBase.cs
mcs/class/Mono.Profiler.Log/Mono.Profiler.Aot/ProfileReader.cs
mcs/class/Mono.Profiler.Log/Mono.Profiler.Aot/ProfileWriter.cs
mcs/class/Mono.Profiler.Log/Mono.Profiler.Log.csproj
mcs/class/Mono.Profiler.Log/Mono.Profiler.Log.dll.sources

It writes the profile data to given stream. It comes from
https://github.com/radekdoulik/aotprofile-tool

[Mono.Profiler.Aot] Add profile writer

---

mcs/tools/linker/Makefile
mcs/tools/linker/monolinker.csproj

[2019-06] Bump linker & cecil

---

mono/mini/alias-analysis.c

Alias analysis attempts to remove indirection when using OP_LDADDR (which fetches the address of a variable). For example :
ldaddr r1 <- r0
load_mem r2 <- r1
is equivalent to
mov r2 <- r0
The remembered r1 alias needs to be forgotten in case r1 is changed. We were handling this for direct assignment with MOV, but not for the more subtle case where an alias to r1 would be passed to a call, which could lead to changing r1.
https://github.com/mono/mono/issues/14872

[jit] Make alias analysis properly handle alias cloberring

---

sdks/wasm/tests/browser/IssuesTestSuite.cs
sdks/wasm/tests/browser/issues-spec.js

[wasm] Add an explicit test for https://github.com/dotnet/try/issues/290

---

sdks/wasm/Makefile

Add the driver conf targets to clean

[wasm] Add some missing directories to the clean target

---

mono/mini/alias-analysis.c

Alias analysis attempts to remove indirection when using OP_LDADDR (which fetches the address of a variable). For example :
ldaddr r1 <- r0
load_mem r2 <- r1
is equivalent to
mov r2 <- r0
The remembered r1 alias needs to be forgotten in case r1 is changed. We were handling this for direct assignment with MOV, but not for the more subtle case where an alias to r1 would be passed to a call, which could lead to changing r1.
https://github.com/mono/mono/issues/14872
Backport of #15255.
/cc @BrzVlad

[2019-06] [jit] Make alias analysis properly handle alias cloberring

---

mcs/class/corlib/System/Environment.cs
mono/metadata/icall-def-netcore.h
mono/metadata/icall-def.h
mono/metadata/icall.c
netcore/CoreFX.issues.rsp
netcore/System.Private.CoreLib/src/System/Environment.cs

Add basic implementation of Environment.FailFast

---

sdks/builds/Makefile

[sdks] Avoid building everything on make all.

---

mono/mini/aot-runtime.c

Fixes https://github.com/mono/mono/issues/15330.

[aot] Fix a deadlock in init_plt () by calling create_trampoline () outside the lock.

---

mono/profiler/Makefile.am
mono/profiler/aot.c
mono/profiler/helper.c
mono/profiler/helper.h
mono/profiler/log.c
msvc/mono-profiler-log.vcxproj
msvc/mono-profiler-log.vcxproj.filters

Extended the aot profiler so, that it can receive commands over the network.
Added new option `port=PORT`, which enables command server and specifies
the port the server should listen at.
We have 2 commands so far.
save ... save the profile data to socket and close it
quit ... quit the profiler. it also saves the profile to the file
in case the output option was specified.
It makes the aot profiling much easier to use on Android as we don't need to
save the profile to a file on the device. That means we don't need to set
`<application android:debuggable="true"/>` flag, which changes the Android
app behavior and thus influence the profile itself. It is also convenient way
for IDEs to retrieve the aot profiles.
Example use for Xamarin.Android. Save and receive the profile data:
adb shell …

[aot profiler] Listen for commands on given port

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

Pushing https://github.com/aspnet/AspNetCore/pull/10561 upstream, to fix
AzDO Bug #890301 (https://dev.azure.com/devdiv/DevDiv/_workitems/edit/890301/)

Remove a stale comment

---

sdks/wasm/library_mono.js

[debugger][wasm] Local vars

---

sdks/wasm/framework/src/WebAssembly.Bindings/WebAssembly.Bindings.csproj
sdks/wasm/framework/src/WebAssembly.Net.Http/WebAssembly.Net.Http.csproj
sdks/wasm/framework/src/WebAssembly.Net.WebSockets/WebAssembly.Net.WebSockets.csproj

Uses the Open key to sign the framework packages.
Closes https://github.com/mono/mono/issues/15275

[wasm][framework] Add signing of the framework assemblies

---

netcore/build.sh

It appears to have accidentally been changed in #15215, and the script no longer works correctly as a result, so revert

[netcore] Fix build.sh

---

sdks/wasm/README.md

[wasm] update the debugger instructions

---

mono/mini/interp/transform.c

calc_section mutex is meant to be a lower level mutex used only for synchronization on InterpMethod contents. Before this commit, we were taking the loader lock under calc_mutex which was leading to deadlocks.
Fixes random deadlocks on CI

[interp] Reduce computation under calc_section mutex

---

mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs

Disable HttpClientTest.CancelRequestViaProxy

---

mono/mini/mini-mips.c

Fixes https://github.com/mono/mono/issues/15441

Fix year+ old MIPS compile break.

---

configure.ac
mono/utils/mono-mmap.h
sdks/builds/android.mk

[2019-06] [sdks] dynamically link libmonosgen to mono-sgen for monodroid host builds

---

THIRD-PARTY-NOTICES.TXT

For https://github.com/mono/mono/blob/d58dfa185af1d48fb93efdef1d046762f214f0a7/libgc/include/gc_allocator.h

Add entry for Silicon Graphics and HP

---

mono/mini/mini-trampolines.c

Backport of #15239.
/cc @vargaz

[2019-06] [jit] Avoid calling mini_jit_info_table_find () in mini_add_method_trampoline () unless needed.

---

mono/metadata/custom-attrs-internals.h
mono/metadata/custom-attrs.c
mono/metadata/object-internals.h

[metadata] Fix resource leak, on error, we did not free the named arguments. Coverity 1443346

[metadata] Fix resource leak, on error, we did not free the named arguments.  Coverity 1443346

---

mono/mini/mini-wasm-debugger.c
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

Implementing evaluate of variable "this"
Fixes #15446

[debugger][wasm] Display content of "this"

---

netcore/CoreFX.issues.rsp
netcore/System.Private.CoreLib/src/System/TypeNameParser.cs

[netcore] Make System.Reflection.Tests.TypeTests.GetEnumUnderlyingType Pass

---

mcs/tools/linker/Makefile

[wasm] Add BlazingPizza.Client to size tests

---

sdks/wasm/.gitignore

- emsdk_env.sh
- builds/threads

[wasm] Update `.gitignore`

---

configure.ac
mono/metadata/Makefile.am
mono/metadata/debug-mono-ppdb.c
msvc/libmonoruntime.targets
msvc/monozlib.targets

Fixes https://github.com/mono/mono/issues/15503

Win32 zlib support.

---

netcore/CoreFX.issues.rsp
netcore/CoreFX.issues_linux.rsp
netcore/CoreFX.issues_windows.rsp
netcore/Makefile
scripts/ci/pipeline-netcore-runtime.yml

Add an rsp for Windows for 0 failures on CI

[netcore] CI work, add rsp for Windows

---

mono/utils/mono-error-internals.h
mono/utils/mono-threads.h

Context: Would make https://github.com/mono/mono/pull/15534 cheaper (and only MinGW is affected).

Inline GetLastError and SetLastError.

---

mono/utils/mono-tls.h

Should fix https://github.com/mono/mono/issues/15541
without the overhead of https://github.com/mono/mono/pull/15465.

mono_native_tls_get_value that does not change LastError.

---

mono/metadata/verify.c

Fixes https://github.com/mono/mono/issues/15551.

[runtime] Implement mono_verifier_class_is_valid_generic_instantiation () etc. even if the verifier is disabled.

---

mono/metadata/Makefile.am
mono/metadata/runtime.h

And distribute "normally" instead of "extra".

runtime.h remove extern "C"

---

mono/mini/Makefile.am.in

See https://github.com/mono/mono/pull/15599#issuecomment-509444313.
See https://github.com/mono/mono/pull/15567.
Alternative to https://github.com/mono/mono/pull/15599 and part of https://github.com/mono/mono/pull/15567.

Disable check-seq-points test.

---

mono/profiler/aot.c

[profiler] Fix printf bug -- char* vs. MonoString*

---

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/ThreadMirror.cs
mcs/class/Mono.Debugger.Soft/Test/dtest.cs
mono/mini/debugger-agent.c

PR of draft https://github.com/mono/mono/pull/14667
Fixes #13408

[debugger] Update client thread frames after SetIP.

---

mono/mini/interp/transform.c

Fixes https://github.com/mono/mono/issues/15596

[interp] Add JitHelper intrins for enum comparison

---

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/AppDomainMirror.cs
mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
mcs/class/Mono.Debugger.Soft/Test/dtest.cs
mono/mini/debugger-agent.c

[debugger] Add intrinsic for creating a byte array

---

mono/mini/mac-entitlements.xml
scripts/ci/run-jenkins.sh

(there is no matching PR lane for Catalina, at time of writing)

Add hardened runtime testing to Catalina lane

---

mcs/tools/linker/Makefile

[wasm][size-diff] fix typo in wasm targets

---

configure.ac
sdks/builds/wasm.mk

[wasm] disable gac in wasm runtime

---

mcs/class/Makefile
mcs/class/Mono.Cecil.Mdb/Mono.Cecil.Mdb.csproj

[bcl] Add Mono.Cecil.Mdb assembly to monodroid_tools profile

---

mcs/class/Makefile
mcs/class/Mono.Cecil.Mdb/Mono.Cecil.Mdb.csproj

Requested by the XA team.
Backport of #15710.

[2019-06] [bcl] Add Mono.Cecil.Mdb assembly to monodroid_tools profile

---

mono/metadata/jit-icall-reg.h
mono/metadata/marshal.c
mono/metadata/marshal.h
mono/mini/aot-runtime.h
mono/mini/interp/interp.c
mono/mini/method-to-ir.c

[netcore] Clear system last error before P/Invoke calls with SetLastError=true

---

sdks/builds/android.mk
sdks/builds/ios.mk

[ios][android] disable gac in ios and android sdk builds

---

configure.ac
mono/metadata/Makefile.am
support/Makefile.am

Extracted from https://github.com/mono/mono/pull/15480 for perhaps more readable history.

configure/makefile To support updating zlib to 1.2.11.

---

mono/eglib/gdate-unix.c

According to the manual, it is recommended to use clock_nanosleep instead of nanosleep when the sleep can be repeatedly interrupted by signals and resumed. The remaining sleep interval was greater than the original timespec.
Fixes random timeouts of finalizer-abort.exe

[glib] Use clock_nanosleep if available

---

mono/utils/mono-context.h
scripts/ci/pipeline/sdks-archive.groovy
sdks/builds/ios.mk
sdks/builds/runtime.mk
tools/offsets-tool-py/Makefile
tools/offsets-tool-py/offsets-tool.py

Backport of https://github.com/mono/mono/pull/15744

[2019-06][ios] Switch to python offset tool

---

scripts/ci/pipeline-netcore-runtime.yml

This is likely the first of several commits within the PR

Get ARM64 working on NetCore AzDO again

---

sdks/wasm/Makefile

[wasm] clean up the clean targets

---

eng/Versions.props
netcore/CoreFX.issues.rsp
netcore/Makefile
netcore/System.Private.CoreLib/System.Private.CoreLib.csproj

[netcore] Bump CoreFX version

---

mono/metadata/appdomain.c
mono/metadata/icall-def-netcore.h
netcore/CoreFX.issues.rsp
netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs

[netcore] Implement AssemblyLoadContext.InternalLoad

---

eng/Version.Details.xml
eng/Versions.props

The earlier PR didn't update this file which is used by arcade for tracking.

[netcore] Update Version.Details.xml

---

netcore/CoreFX.issues.rsp

[netcore] Remove exclusions for fixed tests

---

mono/metadata/sre.c

Added here https://github.com/mono/mono/commit/89d1455a80ef

[sre] Don't throw random exception when runtime shuts down

---

mono/mini/aot-compiler.c
mono/mini/mini-llvm.c

Tested by doing `make -C sdks/builds package-ios` after putting `ENABLE_CXX` in `Make.config` and disabling everything except the ios builds.

[cxx][llvm] Fix C++ build 

---

netcore/CoreFX.issues.rsp
netcore/Makefile

Remove exclusions fixed by #14967

[netcore] Update CoreFX.issues.rsp

---

README.md

add FreeBSD CI to README

---

mcs/class/System.ServiceModel/System.ServiceModel.Channels.Http/HttpReplyChannel.cs

This commit resolve https://github.com/mono/mono/issues/15740.

Commit methodos PUT, DELETE and OPTIONS.

---

mono/metadata/appdomain.c
mono/metadata/icall-def-netcore.h
mono/metadata/icall-def.h
netcore/CoreFX.issues.rsp
netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs

[netcore] Implement AssemblyLoadContext.GetLoadedAssemblies()

---

scripts/ci/pipeline-netcore-runtime.yml

Arcade would like us to start using yaml stages.

[netcore] Use yaml stages in azure pipelines definition

---

mono/mini/interp/interp.c
mono/mini/interp/mintops.def
mono/mini/interp/transform.c

Makes the opcode 2-3x time faster

[interp] Optimize ldelema

---

mcs/class/corlib/System.Runtime.InteropServices/Marshal.cs

ArgumentNullException when pointer is null for Marshal.Release

---

mono/metadata/cominterop.c
mono/metadata/custom-attrs.c
mono/metadata/dynamic-image.c
mono/metadata/handle.h
mono/metadata/object.c
mono/metadata/sre-save.c
mono/metadata/sre.c
mono/metadata/threadpool.c
mono/metadata/threads.c

[2019-06] HANDLE_FUNCTION_RETURN_VAL must not use handles in current frame.

---

mono/metadata/object-internals.h

Some needed. Harmless if extra.
Extracted from https://github.com/mono/mono/pull/15900.

[Coop] Add `TYPED_HANDLE_DECL`.

---

mono/metadata/sgen-client-mono.h

Remove unused macros

---

libgc/include/gc.h
libgc/os_dep.c
mono/metadata/mono-config.c

There is no functional changes in this PR.

Fix some compiler warnings for Win32/mingw64 build

---

mono/mini/interp/interp.c

Probably same on all 64bit architectures. half on 32bit.
before:
```
0000000000003ce0 <interp_exec_method_full>:
3ce0:	55                   	push   %rbp
3ce1:	48 89 e5             	mov    %rsp,%rbp
3ce4:	41 57                	push   %r15
3ce6:	41 56                	push   %r14
3ce8:	41 55                	push   %r13
3cea:	41 54                	push   %r12
3cec:	49 89 f4             	mov    %rsi,%r12
3cef:	53                   	push   %rbx
3cf0:	48 89 fb             	mov    %rdi,%rbx
3cf3:	48 81 ec 78 01 00 00 	sub    $0x178,%rsp
```
after:
```
0000000000003ce0 <interp_exec_method_full>:
3ce0:	55                   	push   %rbp
3ce1:	48 89 e5             	mov    %rsp,%rbp
3ce4:	41 57                	push   %r15
3ce6:	41 56                	push   %r14
3ce8:	41 55                	push   %r13 …
```

Save 64 bytes from most Linux/amd64 interpreter frames.

---

configure.ac

== is a bash extension
= is POSIX and equivalent

Use = as a test(1) operator.

---

mono/metadata/object-internals.h
mono/metadata/threads.c
mono/mini/mini-exceptions.c

Extracted from https://github.com/mono/mono/pull/15859.

Factor copy/pasted code into mono_gstring_append_thread_name.

---

mcs/class/corlib/corlib.csproj
mcs/class/corlib/unix_build_corlib.dll.sources

Fixes https://github.com/mono/mono/issues/14971
Upstream CoreFX PR:https://github.com/dotnet/corefx/pull/39306

[corlib] Allow copying/moving/replacing broken symlinks

---

mcs/class/System.Drawing/Test/System.Drawing/TestGraphics.cs

[System.Drawing] Fix comparison in MeasureString_Wrapping_Dots test

---

mcs/class/corlib/corlib.csproj
mcs/class/corlib/unix_build_corlib.dll.sources

This PR brings changes from https://github.com/mono/corefx/pull/313.
Fixes https://github.com/mono/mono/issues/15887.
Backport of #15932.
/cc @steveisok @MaximLipnin

[2019-06] Bump corefx

---

packaging/MacSDK/libgdiplus.py

```
directhex@breakfast:~/Projects/libgdiplus$ git diff aea1a492713b0ab101876e4ee72dde0f1cb3e3b4..93f43204a94ac75f468c58334ad07726958f4f26 | diffstat | tail -1
52 files changed, 2777 insertions(+), 972 deletions(-)
```

Bump libgdiplus to new release

---

mcs/class/System/System.IO.Compression/DeflateStream.cs

Fixes https://github.com/mono/mono/issues/15825
Backport of #15879.

[2019-06] Add finalizer to DeflateStream

---

mcs/class/System/System.IO.Compression/DeflateStream.cs

Fixes https://github.com/mono/mono/issues/15825
Backport of #15879.

[2019-02] Add finalizer to DeflateStream

---

mono/metadata/marshal.c

For static method delegates, we have a unique delegate_trampoline that is shared among all delegates. We always keep alive the first static method delegate passed to native, by creating a normal gchandle to it and storing it in delegate_hash_table. For instance methods, each delegate will create a separate wrapper and these wrappers are never shared (which was wrongly assumed in caa4a75). We shuldn't keep the delegate alive and this commit reverts the behavior for delegate with instance methods introduced in the mentioned commit.
Fixes #15751
Backport of #15935.

[2019-02] [marshal] Free delegates with target that are passed to native code.

---

sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets.buildschema.json

[wasm][sdk] Fix misspelling and trailing comma

---

mcs/class/System/System.IO.Compression/DeflateStream.cs

Backport of #16048.
/cc @akoeplinger @EgorBo

[2019-08] DeflateStream: check IsInvalid before disposing

---

sdks/wasm/docs/WASM-REQUESTS.md

[wasm] Update WASM-REQUESTS.md.

---

mcs/class/System/System.IO.Compression/DeflateStream.cs

Backport of #16048.
/cc @akoeplinger @EgorBo

[2019-06] DeflateStream: check IsInvalid before disposing

---

mcs/class/System/System.IO.Compression/DeflateStream.cs

Backport of #16048.
/cc @akoeplinger @EgorBo

[2019-02] DeflateStream: check IsInvalid before disposing

---

mono/mini/calls.c

Fixes #15835 
Backport of #16070.

[2019-06] [DIM][bitcode] Allow generating DIM bitcode

---

mono/mini/calls.c

Fixes #15835 
Backport of #16070.

[2019-08] [DIM][bitcode] Allow generating DIM bitcode

---

mono/mini/interp/interp.c

[interp] Fix DEBUG_INTERP build

---

configure.ac

[runtime] Fix an autoconf warning.

---

mono/utils/mono-state.c

Found solution from: 
https://github.com/eclipse/omr/issues/902#issuecomment-288559044

Fix compilation on OSX 10.9

---

mono/metadata/threads.c
mono/mini/exceptions-x86.c
mono/mini/mini-x86.c

[win32] Fix some compilation warnings

---

mono/mini/calls.c

[DIM][bitcode] Allow generating DIM bitcode

---

sdks/wasm/common/Versions.props
sdks/wasm/sdk/Mono.WebAssembly.Sdk/sdk/Versions.props
sdks/wasm/sdk/Templates/templates/DotNet/global.json
sdks/wasm/tests/browser/src/global.json

[wasm][sdk] Bump SDK Version 0.2.0

---

packaging/MacSDK/msbuild.py

Bump msbuild to 'cd5b32d' to disable compiler server

---

mono/metadata/appdomain.c
mono/mini/debugger-agent.c

Ran into some suspicious locks and attempted to relax them a bit. Not totally sure I got the lock-free code right - @jaykrell can you take a look?

Relax locking

---

packaging/MacSDK/msbuild.py

Only merge this if https://github.com/mono/msbuild/pull/124 ci passes

Pull in the unbroken msbuild

---

mcs/tools/corcompare/mono-api-info.cs
mcs/tools/linker/monolinker.csproj
mcs/tools/linker/monolinker.exe.sources
mcs/tools/mdoc/Makefile
mcs/tools/mdoc/mdoc.csproj

[2019-08] Bump linker

---

mono/metadata/w32process-win32.c

When given a null application name, CreateProcess already
searches the path and appends .exe in some cases. .NET's
Process class behaves in the same way (see
https://github.com/mono/mono/pull/16089#issuecomment-519984244).
The duplicated logic is unnecessary and broken in several ways.
Failures are ignored and the command line arguments are
executed. Relative paths are expected not to end in "exe".
Many corner cases work differently from .NET and CreateProcess.
This change makes it impossible for process_complete_path to fail,
so I removed the gboolean return and pulled out the output
parameter. Its caller wasn't handling the return value correctly
anyway.

[w32process-win32] Don't duplicate CreateProcess search logic.

---

mono/mini/interp/interp.c
mono/mini/mini-exceptions.c
mono/sgen/sgen-debug.c
mono/utils/strenc.c

[mono] Fix some compiler warnings

---

mono/metadata/appdomain.c
netcore/CoreFX.issues.rsp

[netcore] Pass MONO_ASMCTX_LOADFROM on LoadFrom calls

---

mono/mini/interp-stubs.c

Addresses Coverity CID 1452245

[interp] Fix stub_get_resume_state write to out parameter

---

mono/metadata/sre.c

The loop body uses coop handles, so wrap it in HANDLE_FUNCTION_ENTER/HANDLE_FUNCTION_RETURN
Addresses part of #16179

[sre] Outline typebuilder_setup_fields loop body

---

mono/mini/debugger-agent.c

I couldn't create a small test case that reproduces, I reproduced debugging (Xamarin.Mac) ios-sim-sharp.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/942093

[debugger] Debugger tries to execute a single step when the thread is already terminated

---

mono/mini/interp/interp.c

Now that we have that function, also change from `malloc` to `alloca`.
This is part of https://github.com/mono/mono/pull/16171 and ultimately over 100 bytes were saved.

[interp] Outline `mono_interp_calli_nat_dynamic_pinvoke` to reduce stack.

---

man/mono.1

[2019-08] (mono.1) Update the MONO_THREADS_SUSPEND description

---

man/mono.1

[2019-06] (mono.1) Update the MONO_THREADS_SUSPEND description

---

man/mono.1

[2019-02] (mono.1) Update the MONO_THREADS_SUSPEND description

---

configure.ac
netcore/Makefile
netcore/README.md
netcore/sample/HelloWorld/HelloWorld.csproj

Enable and document debug with sdb with netcore config

[netcore][debugger] Enable and document debug with sdb with netcore config

---

mono/mini/interp/interp.c

but without changing how exception handling macros access labels and locals.
This saves 16 bytes of stack on Linux/amd64/gcc and likely similar everywhere,
as it takes an address-taken local out of interp_exec_method_full (stackval tmp_sp).
See
https://github.com/mono/mono/pull/16171
https://github.com/mono/mono/pull/16171/commits/a6a8f0d5ffa875da9cda63444e401c37810a690f for a
full outlining.
Ultimately over 100 bytes are savable.
This is just one step toward that.

[interp] Split leave into pieces, partially outlined, to conserve stack,

---

mono/mini/interp/interp.c

From https://github.com/mono/mono/pull/16190.

[interp] Fix some, not all, of the error management.

---

mono/mini/interp/interp.c

I am not sure if this is needed or not.

[interp] [wasm] p vs. o on newobj

---

mono/mini/interp/interp.c

In this variation, the exception handling and resume are split between the main function and the helper function, and no address-taken occurs on ip/sp/vt_sp.
The order is a little tangled but convincing.
The helper function returns MonoException* or checks context->has_resume_state and then returns, and then the caller does the checks again.
Based on past analysis this will conserve stack, but that was not double checked here.
i.e. due to `&valuetype_this`, though it is conditional and the code could be split up into inline and outline.

[interp] Outline newobj and newobj_vt to conserve stack.

---

mono/mini/method-to-ir.c
mono/mini/mini-llvm-cpp.cpp
mono/mini/mini-llvm-cpp.h
mono/mini/mini-llvm.c

Llvm optimizations

---

mono/metadata/object.c

mono_compile_method
mono_runtime_set_main_args
mono_runtime_run_main
mono_runtime_exec_managed_code
mono_load_remote_field
mono_load_remote_field_new
mono_store_remote_field
mono_store_remote_field_new

Wrap more external-only functions in GC mode transitions.

---

mono/mini/interp/interp.c

Whittling away at https://github.com/mono/mono/pull/16190.

[interp] Fix more MonoError reuse (mono_object_isinst_checked).

---

mono/mini/mini-runtime.c

It is an actual function call at least on Windows.
Extracted from larger PR that reduced auto cast.

Cleanup alloca: call twice instead of once, and shrink allocation slightly.

---

mono/metadata/threadpool-worker-default.c

[runtime] Use a PRNG in the threadpool instead of the os random number generator.

---

mono/mini/interp/interp.c
mono/mini/interp/mintops.c
mono/mini/interp/mintops.h

combine lines for searchability
add const

[interp] remove last element from arrays and add const

---

mono/metadata/attach.c

Based on https://github.com/mono/mono/pull/15868.
Most cleanup and leak fixes moved and expanded to https://github.com/mono/mono/pull/15950

[Coop] Convert mono_attach_load_agent.

---

sdks/wasm/tests/browser/src/BrowserTestSuite/issues-spec.js
sdks/wasm/tests/browser/src/IssuesTestSuite/IssuesTestSuite.cs

- IL Linker not working correctly with IQueryable extensions

[wasm][tests] Add regression test for issue #12917

---

mono/mini/interp/interp.c

No immediate savings on Linux/amd64/gcc/clang.

[interp] Reduce register/stack pressure.

---

mono/mini/interp/interp-internals.h
mono/mini/interp/interp.c

[interp] Replace frame.args with frame.stack, the same except for type.

---

netcore/build.sh
scripts/ci/pipeline-netcore-runtime.yml

Fixes https://github.com/mono/mono/issues/16308

[netcore] Use Release configuration for CI builds

---

mono/mini/interp/interp.c

Part of https://github.com/mono/mono/issues/16172 though not necessarily any gain from this change, at this time.

[interp] Reduce register/stack pressure (field across mono_get_special_static_data).

---

scripts/ci/provisioning/freebsd.sh

Too much to list by many measures. This makes sure appropriate kernel modules, file systems, build packages, supplemental packages, and directories are installed or created as appropriate. This also addresses a known failure condition in System.Security-xunit due to a missing directory resulting in ownership problems.

Many updates to freebsd.sh

---

netcore/Makefile
netcore/xunit-summary.py
scripts/ci/pipeline-netcore-runtime.yml

There was some unnecessary duplication between the two that we can remove.

[netcore] Consolidate running tests between AzDO pipeline and Makefile

---

mono/metadata/appdomain.c
mono/metadata/assembly-load-context.c
mono/metadata/assembly.c

Fixes #16334
Future work threading ALCs through existing code should make an effort to update calls in this same fashion.

[netcore] Remove unnecessary calls to mono_domain_get

---

mono/mini/mini-llvm.c
mono/mini/simd-intrinsics-netcore.c

Fixes https://github.com/mono/mono/issues/16381.

[llvm] Fix an assert.

---

mono/utils/mono-dl-posix.c

The intention of calling `g_file_test (file, G_FILE_TEST_EXISTS)` where file is
the name of a shared library we want to open is to speed up probing for
non-existent libraries.
See https://github.com/mono/mono/pull/12074
The problem is that if file is just a simple "libdl.so" then `dlopen (file)`
doesn't just look for it in the current working directory, it will probe some
other paths too.  (For example on desktop linux you'd also look in all the
directories in LD_LIBRARY_PATH).  So the g_file_test() call is not a robust way
to avoid calling dlopen if the filename is relative.
But it actually broke more things: https://github.com/xamarin/xamarin-android/issues/3388
When probing for "libdl.so" on Android mono_lookup_pinvoke_call will first try
prepending some paths that it knows about and …

[android] mono_dl_open_file: use g_file_test only on absolute paths

---

mono/utils/mono-dl-posix.c

The intention of calling `g_file_test (file, G_FILE_TEST_EXISTS)` where file is
the name of a shared library we want to open is to speed up probing for
non-existent libraries.
See https://github.com/mono/mono/pull/12074
The problem is that if file is just a simple "libdl.so" then `dlopen (file)`
doesn't just look for it in the current working directory, it will probe some
other paths too.  (For example on desktop linux you'd also look in all the
directories in LD_LIBRARY_PATH).  So the g_file_test() call is not a robust way
to avoid calling dlopen if the filename is relative.
But it actually broke more things: https://github.com/xamarin/xamarin-android/issues/3388
When probing for "libdl.so" on Android mono_lookup_pinvoke_call will first try
prepending some paths that it knows about and …

[2019-08] [android] mono_dl_open_file: use g_file_test only on absolute paths

---

mono/mini/interp/interp.c

Seen to reduce frame from 0xB8 to 0xA8 on Linux/amd64/gcc against master.
Possibly similar elsewhere.
(Possibly 8 added to a rounded 8.)
Add const, add braces, they might help compiler and/or programmer.

[interp] Outline mono_interp_box_vt.

---

configure.ac
mcs/class/Mono.Management/Mono.Attach/VirtualMachine.cs
mono/metadata/attach.c

Extracted and slightly modified from https://github.com/mono/mono/pull/15868.

mono_attach_load_agent: Fix leaks, alloc, copy.

---

mono/utils/mono-codeman.c

- Chunks do not need flags, only codemanagers do.
- Sort by size to minimize padding for alignment.
- Booleans only need one bit.
- Chunk is not spelled chunck.
- Suggest foo accessors be named foo() and set_foo(), not get_foo() and set_foo().
i.e. the more common "get" is implied.
- Allow free(0) w/o initialization.

CodeManager cleanup.

---

mono/mini/interp/interp.c

This conserves stack on Linux/amd64/gcc.
Probably penalizes arm64 slightly (it has twice the number of registers), arm32 uncertain (same number of registers -- important number is how many nonvolatile registers).
Could ifdef it, i.e. `#define IMETHOD imethod` or `#define IMETHOD frame->imethod`.

[interp] Replace imethod with frame->imethod.

---

mono/mini/interp/interp.c

I missed this earlier cleaning stackval_to_data.

[interp] Minor cleanup of `stackval_from_data`.

---

mono/metadata/object.c

Extracted from earlier version of https://github.com/mono/mono/pull/16504.
Baby steps.

[Coop] mono_load_remote_field_checked single point of exit.

---

mono/metadata/cominterop.c
mono/metadata/marshal-ilgen.c
mono/tests/cominterop.cs
mono/tests/libtest.c

This is a case of CCW calling managed method with object[] argument.

[cominterop] Implement native-to-managed safearray marshalling.

---

mono/metadata/object.c

Keep the early exit optimizations.
This will likely want handles for the exceptions.
I think the single-point-of-exit changes are disruptive enough to PR separately.
Was willing to skip them but you seemed to want them in another PR.

[Coop] mono_runtime_class_init_full single point of exit mostly.

---

mono/metadata/cominterop.c
mono/metadata/object-internals.h
mono/tests/cominterop.cs
mono/tests/libtest.c

[cominterop] Respect ComDefaultInterfaceAttribute when constructing ccw.

---

mcs/class/corlib/System/AppDomain.cs

Mirrors change made with 068660732fbf10cae688182ef67f72cf80ebb632.

[corlib] Simplify file: protocol check in Assembly::Load().

---

mcs/class/corlib/ReferenceSources/CalendarData.cs
mcs/class/corlib/corlib.csproj
mcs/class/corlib/corlib.dll.sources

Workaround for https://github.com/mono/mono/issues/16623. Unblocks the CI, should be back-ported to other branches.
/cc @akoeplinger @jaykrell

[corlib] Add hack for Hebrew calendar data

---

mono/metadata/w32process-internals.h
mono/metadata/w32process-unix.c
mono/metadata/w32process.c

Fixes #14730
Not totally sure my Windows code is correct here, so it's a draft until I can look at CI results.
Backport of #16553.

[2019-08] Remove MAX_PATH usage in w32process

---

mono/metadata/w32process-internals.h
mono/metadata/w32process-unix.c
mono/metadata/w32process.c

Fixes #14730
Not totally sure my Windows code is correct here, so it's a draft until I can look at CI results.

Remove MAX_PATH usage in w32process

---

mono/mini/intrinsics.c

[netcore] Add intrinsic implementation for Unsafe.InitBlockUnaligned

---

mcs/class/corlib/ReferenceSources/CalendarData.cs
mcs/class/corlib/corlib.csproj
mcs/class/corlib/corlib.dll.sources

Workaround for https://github.com/mono/mono/issues/16623. Unblocks the CI, should be back-ported to other branches.
/cc @akoeplinger @jaykrell 
Backport of #16624.
/cc @directhex @filipnavara

[2019-06] [corlib] Add hack for Hebrew calendar data

---

mcs/class/corlib/ReferenceSources/CalendarData.cs
mcs/class/corlib/corlib.csproj
mcs/class/corlib/corlib.dll.sources

Workaround for https://github.com/mono/mono/issues/16623. Unblocks the CI, should be back-ported to other branches.
/cc @akoeplinger @jaykrell 
Backport of #16624.
/cc @directhex @filipnavara

[2019-08] [corlib] Add hack for Hebrew calendar data

---

mcs/class/corlib/ReferenceSources/CalendarData.cs
mcs/class/corlib/corlib.csproj
mcs/class/corlib/corlib.dll.sources

Workaround for https://github.com/mono/mono/issues/16623. Unblocks the CI, should be back-ported to other branches.
/cc @akoeplinger @jaykrell 
Backport of #16624.
/cc @steveisok @filipnavara

[2019-02] [corlib] Add hack for Hebrew calendar data

---

mono/metadata/boehm-gc.c
mono/metadata/handle-decl.h
mono/metadata/handle.h
mono/metadata/icall-decl.h
mono/metadata/icall-def-netcore.h
mono/metadata/icall-def.h
mono/metadata/icall-table.h
mono/metadata/icall.c
mono/metadata/null-gc.c
mono/metadata/object-internals.h
mono/sgen/sgen-gc.c

(Part taken from ves_icall_InternalExecute https://github.com/mono/mono/pull/16622.)

[Coop] ves_icall_InternalInvoke.

---

mono/metadata/icall-def-netcore.h
mono/metadata/icall-def.h
mono/metadata/icall-table.h
mono/metadata/object-internals.h
mono/metadata/reflection-internals.h
mono/metadata/sre.c

mono_reflection_get_custom_attrs_blob_checked
ModuleBuilder_WriteToFile,
ModuleBuilder_build_metadata
Remove some error_init.

[coop] CustomAttributeBuilder_GetBlob, etc.

---

Makefile.am
configure.ac
netcore/Makefile

I'm not entirely happy with the approach taken here with subdir-objects, but it does fix the core problem.
Fixes https://github.com/mono/mono/issues/16605

Fix distclean

---

eng/Version.Details.xml
eng/Versions.props
netcore/CoreFX.issues.rsp
netcore/Makefile

Should fix some of the flaky tests by picking up dotnet/corefx@a192823.

[netcore] Bump CoreFX, core-setup dependencies

---

mono/mini/interp/interp.c

[interp] Assign sp once is enough in leave.

---

sdks/wasm/build.sh

[wasm] update build.sh

---

sdks/wasm/Makefile

[wasm] Remove extraneous -s flag from EMCC_DEBUG_FLAGS

---

sdks/wasm/Makefile
sdks/wasm/README.md
sdks/wasm/packager.cs
sdks/wasm/runtime-tests.js
sdks/wasm/xunit-exclusions.rsp

[wasm] Fix several typos

---

configure.ac

[netcore] Disable more features.

---

scripts/ci/run-jenkins.sh
sdks/builds/wasm.mk
sdks/wasm/Makefile

Modify configuration flag `ENABLE_WASM_DYNAMIC_RUMTIME` to `ENABLE_WASM_DYNAMIC_RUNTIME`

[wasm] Dynamic Release RUNTIME configuration

---

packaging/MacSDK/msbuild.py

Start updating msbuild and toolset to x.4 builds

[msbuild][roslyn] Bump msbuild and roslyn to pull in new versions

---

mcs/tools/aprofutil/Program.cs

-p PORT allows easier retrieval of AOT profile from the application
running with aot profiler, using the socket connection on local PORT
-f instructs the tool to try setup adb port forwarding to/from Android
device or emulator
Example usage, retrieve the AOT profile from Android:
> mono aprofutil.exe -s -v -f -p 9998 -o my.aprof
Calling 'adb forward tcp:9998 tcp:9998'...
Reading from '127.0.0.1:9998'...
Read total 94903 bytes...
Summary:
Modules:          6
Types:          262
Methods:      1,162
Going to write the profile to 'my.aprof'

[aprofutil] Add -p and -f options

---

netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml
netcore/System.Private.CoreLib/src/System.Reflection.Emit/ILGenerator.cs
netcore/System.Private.CoreLib/src/System/Array.cs

[netcore] Change an ArrayList to a List<T>.

---

mono/mini/interp/interp.c

Strike a balance between https://github.com/mono/mono/pull/16835
and
https://github.com/mono/mono/pull/16834
The main 4 call opcodes should have no conditionality here.
The non-virtuals no extra branch.
The other opcodes all have one condition and branch into common code.
Everything could be smaller or faster but not both.
This is my favorite of the three.

[interp] Balance size and conditional branching in calls.

---

sdks/wasm/tests/browser/package.json

[wasm][tests] Bump Browser tests Karma version

---

sdks/wasm/common/Versions.props
sdks/wasm/sdk/Mono.WebAssembly.Sdk/sdk/Versions.props
sdks/wasm/sdk/Templates/templates/DotNet/global.json
sdks/wasm/sdk/global.json
sdks/wasm/tests/browser/src/Packages.props
sdks/wasm/tests/browser/src/global.json

[wasm] Bump sdk and bindings versions

---

configure.ac
mono/metadata/assembly.c
netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml
sdks/builds/wasm.mk
sdks/wasm/Makefile
sdks/wasm/netcore-corefx.diff
sdks/wasm/packager.cs
sdks/wasm/samples/hello/Program.cs
sdks/wasm/samples/hello/hello.csproj
sdks/wasm/src/driver.c
sdks/wasm/src/pinvoke-tables-default-netcore.h

[wasm] Initial netcore support.

---

mono/mini/interp/interp.c
mono/mini/interp/mintops.def
mono/mini/interp/transform.c

Get/Set for arrays with 2 dimensions is now 2-2.5x times faster. Arrays with more dimensions higher speedups. The implementation reuses MINT_LDELEMA which was also optimized for this purpose.

[interp] Optimize multidimensional array access

---

mono/mini/interp/interp.c

Partly revert https://github.com/mono/mono/commit/b18840e92cb5b1afef6c0e5df05cc026eb32efbf

[interp] Fix stack size regression

---

mcs/class/System/System.IO/FileSystemWatcher.cs
mcs/class/System/System.IO/FileSystemWatcher.platformnotsupported.cs
mcs/class/System/System.csproj
mcs/class/System/fsw.pns.sources
mcs/class/System/wasm_System.dll.exclude.sources
mcs/class/System/wasm_System.dll.sources
mcs/class/System/wasm_System_xtest.dll.exclude.sources

Fixes https://github.com/mono/mono/issues/16876

[wasm] Switch to PNSE version of FileSystemWatcher and exclude xunit tests

---

mcs/class/reference-assemblies/Makefile
mcs/mcs/ikvm.cs
mcs/tools/xbuild/Makefile
mcs/tools/xbuild/frameworks/net_4.8.xml

Brings in https://github.com/mono/reference-assemblies/pull/20

Add .NET 4.8 reference assemblies

---

netcore/Makefile

[netcore] Show line numbers when xunit tests fail

---

mono/mini/mini-llvm.c

Fixes https://github.com/mono/mono/issues/16943.

[llvm] Handle recursive calls as a direct call.

---

mono/metadata/metadata.c

Fix check for SafeHandle types

---

scripts/ci/run-jenkins.sh

Follow-up to https://github.com/mono/mono/pull/16936

[ci] Remove more XCODE32_DIR usages

---

scripts/mono-package-runtime

Because System.Windows.Forms.dll includes an assemblyref on
Mono.WebBrowser.dll, bundles need to be able to include it
in order for WinForms to work (even if they don't actually
use a browser component)
Compare:
```
$ mkbundle hellowin.exe -o hellowin --cross mono-6.0.0-ubuntu-18.04-x64 --i18n all
From: /home/directhex/.mono/targets/mono-6.0.0-ubuntu-18.04-x64
ERROR: Unable to load assembly `Mono.WebBrowser' referenced by `/home/directhex/.mono/targets/mono-6.0.0-ubuntu-18.04-x64/lib/mono/4.5/System.Windows.Forms.dll'
```
to
```
$ mkbundle hellowin.exe -o hellowin --cross mono-6.0.0-ubuntu-18.04-x64 --i18n all
From: /home/directhex/.mono/targets/mono-6.0.0-ubuntu-18.04-x64
Using runtime: /home/directhex/.mono/targets/mono-6.0.0-ubuntu-18.04-x64/bin/mono
Assembly: /tmp/hellowin.exe …
```

Include Mono.WebBrowser.dll in mkbundle bundles (Closes: #7454)

---

mono/utils/checked-build.c

@lambdageek does it still make sense?

[checked-build] update allowed thread states

---

mono/metadata/threads-types.h

Fix https://github.com/mono/mono/pull/16906/files#r327660329.

Fix comment about mono_thread_interruption_request_flag.

---

sdks/builds/runtime.mk
tools/offsets-tool-py/Makefile

So it doesn't mess with the Python installation of the user.

[offsets-tool] install clang python package into a virtualenv

---

mono/metadata/marshal-ilgen.c
mono/metadata/marshal.c

Revert "[2019-06][metadata] Fix leaks when handling a few attributes (#16675)"

---

mcs/class/Mono.Profiler.Log/Mono.Profiler.Log/LogEnums.cs
mono/metadata/mono-gc.h
mono/metadata/sgen-mono.c
mono/metadata/sgen-toggleref.c
mono/sgen/sgen-client.h

Fixes https://github.com/mono/mono/issues/16996

[sgen] Report roots from togglerefs

---

mono/mini/intrinsics.c
mono/mini/memory-access.c
mono/mini/method-to-ir.c

[mini] Expand clr-memory-model effect

---

sdks/wasm/xunit-runner.cs

Fixes https://github.com/mono/mono/issues/16879

[wasm][xunit tests] Fix issue "System.MissingMethodException: Default constructor not found for type"

---

mono/sgen/sgen-gc.c
mono/sgen/sgen-gc.h
mono/sgen/sgen-gchandles.c
mono/sgen/sgen-internal.c

https://github.com/mono/mono/issues/15885

[sgen] Add stats for allocated gchandles

---

packaging/MacSDK/msbuild.py

.. to pick up https://github.com/mono/msbuild/pull/142 and
https://github.com/mono/msbuild/pull/139 .

[msbuild] Bump to track xplat-master

---

sdks/wasm/xunit-runner.cs

Fixes https://github.com/mono/mono/issues/17040

[wasm][xunit tests] Other fix for "MissingMethodException: Default constructor not found" issue

---

mono/metadata/sgen-mono-ilgen.c
mono/metadata/sgen-mono.c
mono/metadata/sgen-mono.h

[sgen] Fix allocator spelling

---

mono/utils/mono-merp.c

[merp] Use macOS version not Darwin version in MERP reports

---

mono/metadata/cominterop.c
mono/metadata/icall.c
mono/metadata/marshal-ilgen.c
mono/metadata/marshal.c
mono/metadata/metadata-internals.h
mono/metadata/metadata.c
mono/metadata/metadata.h
mono/metadata/verify.c
mono/mini/debugger-agent.c
mono/mini/mini-generic-sharing.c

mono_type_get_type
mono_type_get_signature
mono_type_is_byref
mono_type_get_class
mono_type_get_array_type

Some external_only/internal split, and inlining.

---

mono/eglib/glib.h
mono/utils/mono-merp.c

Fixes #17004
Backport of #17130.
/cc @lambdageek @kdubau

[2019-08] [merp] Use macOS version not Darwin version in MERP reports

---

mcs/class/System.Runtime.Serialization/System.Runtime.Serialization.csproj
mcs/class/System.Runtime.Serialization/System.Runtime.Serialization.dll.sources
mcs/class/referencesource/System.Runtime.Serialization/System/Runtime/Serialization/PrimitiveDataContract.cs

[System.Runtime.Serialization] Make reflection calls linker friendly

---

.gitignore

https://github.com/mono/mono/pull/17013#issuecomment-536484069
/cc @MaximLipnin

[sdks] .gitignore python virtualenv

---

mcs/tools/aprofutil/Program.cs

[aprofutil] Add skip regexes to simplify expression of removal matching

---

mono/utils/mono-merp.c

[merp] exit_status is 0 if we ran the uploader successfully

---

mono/mini/intrinsics.c
netcore/System.Private.CoreLib/src/System/Array.cs

i.e. do the strcmp last.
Add GetRawArrayData.

Optimize and extend System.Array intrinsic identification.

---

mono/metadata/w32file-unix.c

Fixes #17151
This brings us in line with GetDiskFreeSpaceExW on Windows as well as .NET Core.
I checked with the Android folks and it seems like this won't fail their test - all they check is that the returned value isn't `long.MaxValue`.

[IO] Remove read-only logic in mono_w32_get_disk_free_space

---

mono/mini/method-to-ir.c
mono/tests/Makefile.am
mono/tests/localloc-noinit.il

Note that we will still touch the pages (mono_emit_stack_alloc).
Should fix https://github.com/mono/mono/issues/16867.

Do not always zero localalloc.

---

mono/eglib/glib.h
mono/metadata/w32process-internals.h
mono/metadata/w32process-unix.c
mono/metadata/w32process.c

Update to use Jay's helper functions introduced in #16562

Use eglib win32 helper functions without MAX_PATH limit

---

mono/metadata/w32file-unix.c

Fixes #17151
This brings us in line with GetDiskFreeSpaceExW on Windows as well as .NET Core.
I checked with the Android folks and it seems like this won't fail their test - all they check is that the returned value isn't `long.MaxValue`.
Backport of #17177.
/cc @akoeplinger @CoffeeFlux

[2019-10] [IO] Remove read-only logic in mono_w32_get_disk_free_space

---

mono/metadata/w32file-unix.c

Fixes #17151
This brings us in line with GetDiskFreeSpaceExW on Windows as well as .NET Core.
I checked with the Android folks and it seems like this won't fail their test - all they check is that the returned value isn't `long.MaxValue`.
Backport of #17177.
/cc @akoeplinger @CoffeeFlux

[2019-08] [IO] Remove read-only logic in mono_w32_get_disk_free_space

---

mono/mini/interp/transform.c

This increases the cprop time by about 30% (the reiteration part), but it is still very good relative to total transform time / jit time / execution time.
Before (corlib test suite)
Total transform time                : 3110.79 ms
Total cprop time                    : 105.97 ms
STLOC_NP count                      : 91809
MOVLOC count                        : 10032
Copy propagations                   : 8562
Killed instructions                 : 58904
Methods inlined                     : 96344
Inline failures                     : 198165
After (corlib test suite)
Total transform time                : 3160.24 ms
Total cprop time                    : 133.14 ms
STLOC_NP count                      : 99277
MOVLOC count                        : 12300
Copy propagations                   : 9138 …

[interp] Improve handling of stloc.np during cprop

---

configure.ac
mono/utils/mono-dl.c

Fixes #16521, or at least as close as we're going to get for now.

[netcore] Add libc name transition

---

man/mono.1

Fixes https://github.com/mono/mono/issues/15845

[man] Update MONO_IOMAP docs as it no longer works with corefx System.IO

---

netcore/System.Private.CoreLib/src/System/Exception.cs

Unblocks https://github.com/mono/mono/pull/17232. /cc @akoeplinger @marek-safar

[netcore] Port CoreCLR implementation of Exception.SetCurrentStackTrace

---

mono/utils/mono-dl.c

[netcore] Fix NULL dereference when running LLVM JIT

---

mcs/class/Facades/System.Drawing.Common/Facades_System.Drawing.Common.csproj
mcs/class/Facades/System.Drawing.Common/Makefile

Needed for https://github.com/xamarin/xamarin-android/issues/3726
Backport of #17238.

[2019-10] Add drawing type converters to mobile profiles

---

mcs/class/Facades/System.Drawing.Common/Facades_System.Drawing.Common.csproj
mcs/class/Facades/System.Drawing.Common/Makefile

Needed for https://github.com/xamarin/xamarin-android/issues/3726
Backport of #17238.

[2019-08] Add drawing type converters to mobile profiles

---

mcs/class/Facades/System.Drawing.Common/Facades_System.Drawing.Common.csproj
mcs/class/Facades/System.Drawing.Common/Makefile

Needed for https://github.com/xamarin/xamarin-android/issues/3726

Add drawing type converters to mobile profiles

---

mcs/class/System/Test/System.Net.WebSockets/ClientWebSocketTest.cs

See https://github.com/mono/corefx/pull/360

Bump corefx to get Azure testhost change

---

scripts/ci/pipeline/sdks-archive.groovy
scripts/ci/run-jenkins.sh

As requested by the xamarin-macios team.

[ci] Use Xcode11.1 for XI/XM Mono SDK builds

---

mono/mini/intrinsics.c

Found by https://github.com/mono/mono/issues/17335.

[jit] Fix is_reference checks for intrinsics with byref parameters.

---

scripts/ci/run-jenkins.sh
sdks/wasm/Makefile
sdks/wasm/tests/browser/karma.conf.js
sdks/wasm/tests/browser/package.json
sdks/wasm/tests/browser/src/BrowserTestSuite/core-bindings-spec.js

Execute tests using Safari browser on MacOSX CI lanes
This will only execute on a MacOSX CI lane.

[wasm][tests] WASM Safari browser tests

---

mono/metadata/marshal-ilgen.c
mono/tests/libtest.c
mono/tests/safehandle.2.cs
netcore/CoreFX.issues.rsp

Fix SafeHandle marshalling in ref/in/out parameters

---

mcs/class/referencesource/System/compmod/system/componentmodel/ReflectTypeDescriptionProvider.cs
mcs/tools/linker/Makefile
mcs/tools/linker/Tests/System/test-typeconverter.cs

[System] Add reflection dependency tracking

---

netcore/CoreFX.issues.rsp

[netcore] Remove GenericVectorTests from rsp

---

mcs/class/System/monotouch_watch_System_xtest.dll.exclude.sources

Removing execution of network tests from WatchOs.

Removing execution of network tests from WatchOs.

---

mono/mini/interp/interp.c

This conserves the less important stack, granted.

[interp][wasm] Remove more varargs to conserve stack.

---

configure.ac
docs/riscv.md
mono/mini/mini-riscv.h
mono/mini/mini.c
mono/utils/mono-context.c
mono/utils/mono-sigcontext.h

Also some updates to the toolchain setup documentation.

Some updates to make RISC-V buildable again.

---

mono/mini/mini-llvm.c

See the discussion in https://github.com/mono/mono/pull/16984#discussion_r326911650.
Fixes https://github.com/mono/mono/issues/16935.
Given:
```csharp
static bool testfunc(Vector<float> vec1, Vector<float> vec2) {
return vec1 == vec2;
}
```
Before:
```asm
0000000000000000 <loWorld_Program_testfunc__System_Numerics_Vector_1_single__System_Numerics_Vector_1_single__>:
<BB>:1
0:	c4 e1 f9 6e c6       	vmovq  %rsi,%xmm0
5:	c4 e1 f9 6e cf       	vmovq  %rdi,%xmm1
a:	c5 f1 6c c0          	vpunpcklqdq %xmm0,%xmm1,%xmm0
e:	c4 e1 f9 6e c9       	vmovq  %rcx,%xmm1
13:	c4 e1 f9 6e d2       	vmovq  %rdx,%xmm2
18:	c5 e9 6c c9          	vpunpcklqdq %xmm1,%xmm2,%xmm1
1c:	c5 f8 c2 c1 00       	vcmpeqps %xmm1,%xmm0,%xmm0
21:	c4 e3 79 04 c8 0e    	vpermilps …
```

Generate LLVM IR for OP_XEQUAL that is recognized by LLVM's vector pattern recognizers.

---

mcs/class/System.Net.Http/Test/System.Net.Http.Headers/HttpHeaderValueCollection.cs
mcs/class/System.Net.Http/Test/System.Net.Http.Headers/HttpHeadersTest.cs
mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs
mcs/class/System.Net.Http/Test/System.Net.Http/HttpRequestMessageTest.cs
mcs/class/System.Net.Http/Test/System.Net.Http/HttpResponseMessageTest.cs

Needs this ifdefs because of this https://github.com/mono/mono/pull/17260.

Changing behavior of some tests in WatchOs.

---

mono/mini/aot-runtime.c

Remove dead code left out in #17341

---

mcs/tools/mono-symbolicate/mono-symbolicate.csproj

Bump cecil.

---

mcs/class/System.Net.Http/Test/System.Net.Http.Headers/HttpHeaderValueCollection.cs
mcs/class/System.Net.Http/Test/System.Net.Http.Headers/HttpHeadersTest.cs
mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs
mcs/class/System.Net.Http/Test/System.Net.Http/HttpRequestMessageTest.cs
mcs/class/System.Net.Http/Test/System.Net.Http/HttpResponseMessageTest.cs

Changing __WATCHOS__ to MONOTOUCH_WATCH, __WATCHOS__ is not defined in this context.

Fix WatchOs tests

---

mcs/class/System.Data/corefx/Odbc/Res.cs

Fixes https://github.com/mono/mono/issues/17043

Get resource string

---

sdks/wasm/DebuggerTestSuite/DebuggerTestSuite.csproj
sdks/wasm/Makefile
sdks/wasm/Mono.WebAssembly.DebuggerProxy/Mono.WebAssembly.DebuggerProxy.csproj
sdks/wasm/ProxyDriver/Program.cs
sdks/wasm/ProxyDriver/ProxyDriver.csproj
sdks/wasm/ProxyDriver/Startup.cs
sdks/wasm/ProxyDriver/TestHarnessStartup.cs

[wasm] Bump DebugProxy to netstandard 2.1 / netcore 3

---

mono/mini/simd-intrinsics-netcore.c

[netcore] Disable debugging code in lookup_intrins

---

mono/mini/interp/interp.c

Remove the switch and have each instruction have its own code. Seems to improve speed on a benchmark that heavily uses ldelem by about 10-20%.

[interp] Optimize ldelem instructions

---

mono/mini/interp/transform.c
mono/mini/intrinsics.c
netcore/System.Private.CoreLib/shared/Internal/Runtime/CompilerServices/Unsafe.cs
netcore/System.Private.CoreLib/shared/System/Decimal.DecCalc.cs

Mirror changes from mono/coreclr 

---

mono/utils/mono-threads-state-machine.c
mono/utils/mono-threads.h

Problems reported on AIX.
Fixes https://github.com/mono/mono/issues/17501.

Fix endian problem due to int/MonoThreadStateMachine confusion.

---

mono/mini/mini-llvm.c

Fixes https://github.com/mono/mono/issues/17389.

[wasm] Avoid adding an extra arg to native-to-managed wrappers.

---

sdks/wasm/xunit-exclusions.rsp

Relates to https://github.com/mono/mono/issues/16858
/cc @steveisok

[wasm][xunit tests] Exclude some System.Data tests

---

sdks/wasm/common/Versions.props
sdks/wasm/sdk/Mono.WebAssembly.Sdk/sdk/Versions.props
sdks/wasm/sdk/Templates/templates/DotNet/global.json
sdks/wasm/sdk/global.json
sdks/wasm/tests/browser/src/global.json

[wasm][sdk] Bump SDK version to 0.2.2

---

data/lldb/monobt.py

And improved error message in case it breaks again.

[lldb] another fix for handling interp frames

---

mono/mini/exceptions-x86.c

Extracted from https://github.com/mono/mono/pull/17325.

[cxx][x86] int/ptr casts.

---

mono/metadata/icall-table.h
mono/metadata/icalls.h
mono/metadata/marshal.h
mono/metadata/monitor.h
mono/metadata/object-internals.h
mono/metadata/threads-types.h
mono/mini/trace.h
mono/utils/mono-threads-coop.h

[cxx] externC for some icalls, for wasm and ios.

---

mono/mini/interp/interp.c

By avoid switch. And optimize stelem_ref by avoiding call to slow method.

[interp] Optimize stelem

---

mono/mini/tramp-x86.c

From https://github.com/mono/mono/pull/17325.

[jit][x86][cxx] int/ptr casts in tramp-x86.c

---

mono/metadata/cominterop.c
mono/metadata/marshal-ilgen.c
mono/metadata/marshal.c
mono/metadata/marshal.h

Fixes https://github.com/mono/mono/issues/17367.

[runtime] Implement support for SuppressGCTransitionAttribute.

---

netcore/System.Private.CoreLib/System.Private.CoreLib.csproj
netcore/System.Private.CoreLib/shared/Interop/Windows/Kernel32/Interop.CompletionPort.cs
netcore/System.Private.CoreLib/shared/System.Private.CoreLib.Shared.projitems
netcore/System.Private.CoreLib/shared/System/Diagnostics/Tracing/ActivityTracker.cs
netcore/System.Private.CoreLib/shared/System/Diagnostics/Tracing/EventProvider.cs
netcore/System.Private.CoreLib/shared/System/IO/StreamReader.cs
netcore/System.Private.CoreLib/shared/System/Reflection/Assembly.cs
netcore/System.Private.CoreLib/shared/System/Runtime/CompilerServices/PreserveDependencyAttribute.cs
netcore/System.Private.CoreLib/shared/System/Runtime/InteropServices/CriticalHandle.cs
netcore/System.Private.CoreLib/shared/System/Runtime/Loader/AssemblyLoadContext.cs
netcore/System.Private.CoreLib/shared/System/Security/SecurityElement.cs
netcore/System.Private.CoreLib/src/System.Diagnostics/NativeRuntimeEventSource.cs

PR #17604 + temporary build fix (to be removed on next merge, see https://github.com/dotnet/corefx/pull/42202/files/e6235eb220d677b7ac4771e059ec7c2c4e904f21..3eb5f9e88fc3e293db02721206f5bfdfcb4503fb).

Mirror changes from mono/corefx,corert,coreclr

---

mono/metadata/icall-def.h
mono/metadata/mono-route.c
msvc/libmonoruntime-common.targets
sdks/wasm/packager.cs

[wasm] Fix build problems.

---

mono/metadata/threads-types.h
mono/metadata/threads.c

Remove some unused icalls.

---

mono/metadata/class-init.c
mono/tests/Makefile.am
mono/tests/interface-2.cs

* Precedence order:
-> Override interface method in class
-> Method in class
-> DIM
Backport #17583

[dim][regression][2019-10] Explicit interface override (#17583)

---

mono/metadata/class-init.c
mono/tests/Makefile.am
mono/tests/interface-2.cs

* Precedence order:
-> Override interface method in class
-> Method in class
-> DIM
Backport #17583

[dim][regression][2019-08] Explicit interface override (#17583)

---

configure.ac
mono/utils/mono-coop-mutex.h
mono/utils/mono-os-mutex.h
sdks/builds/wasm.mk

[runtime] Add a --enable-minimal=threads configure option to disable threading support. Use it on wasm.

---

mcs/build/tests.make
sdks/wasm/Makefile
sdks/wasm/packager.cs

[wasm] Fix xunit test ninja errors.

---

packaging/MacSDK/msbuild.py
packaging/MacSDK/nuget.py

Fixes https://github.com/mono/mono/issues/17637 as well

[2019-08] bump msbuild with more p2 packages

---

mono/metadata/domain.c
mono/metadata/object-internals.h
mono/metadata/object.c
netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml
netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs

[netcore] Cleanups.

---

mono/metadata/icall-decl.h
mono/metadata/icall-def-netcore.h
mono/metadata/icall.c
netcore/System.Private.CoreLib/src/System/Array.Mono.cs

Remove handles from ves_icall_System_Array_InternalCreate.

---

configure.ac
mono/metadata/monitor.c
netcore/CoreFX.issues.rsp

[netcore] Complete Monitor.LockContentionCount implementation

---

mcs/class/System.Windows.Forms/System.Windows.Forms/TabControl.cs

[WinForms] Fix TabPage position when enabling MultiLine

---

sdks/builds/wasm.mk

Includes updates for https://github.com/emscripten-core/emscripten/issues/9562 and side modules.

[Wasm] Update emscripten to 1.39.3

---

.gitmodules
configure.ac
mcs/class/corlib/corlib.csproj
mcs/class/corlib/unix_build_corlib.dll.sources
sdks/wasm/src/pinvoke-tables-default.h

Added HAVE_LCHFLAGS & HAVE_STAT_FLAGS to configure

Bump corefx to pick up #370

---

packaging/MacSDK/nuget.py

.. this wasn't available earlier.
Fixes https://github.com/mono/mono/issues/17637

Update nuget.exe to 5.3.1

---

mono/metadata/threadpool-io.h
mono/metadata/threadpool-worker-default.c
mono/metadata/threadpool-worker-wasm.c
mono/metadata/threadpool-worker.h
mono/utils/mono-complex.h

We use the managed threadpool there.

[metadata] Remove native threadpool from netcore build

---

mono/eglib/gmodule-aix.c
mono/eglib/gmodule-unix.c

Fixes crash in tests on AIX.
Matches b0d966bd7ab887f075f6ce3d1c9858af6b52f30f

[eglib] In AIX/generic POSIX, handle null addresses better

---

mono/mini/interp/transform.c

[interp] Resolve tokens also from wrappers during optimization

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

Handle expansion in more cases and trap failures instead of disconnecting from the debug session

[wasm][debugger] Fix issue in debugger variable inspection

---

mcs/tools/linker/Makefile

Fix bcl-size-diff for PROFILE=wasm

---

mcs/class/System.Windows.Forms/System.Windows.Forms/Theme.cs

In Mono 5 and earlier, the active GTK or KDE theme would be sourced for system colors, allowing dark themes to be obeyed:
This allowed WinForms apps to blend in and look more like native apps.
In Mono 6, this capability was lost (as noted in passing in #14325). WinForms apps now only look like this, regardless of the system color settings:
This looks somewhat jarring and worse than previous Mono releases, for users with a dark system theme.
During load of the system settings (in the static constructor of `X11DesktopColors`), `Theme.SetSystemColors` passes system color data to `System.Drawing.KnownColors.Update`, which populates them into `System.Drawing.KnownColors.ArgbValues`. In Mono 5 and earlier, this flowed through to the visible UI.
It seems that as of Mono 6, this table no longer …

Fix X11 theming

---

mcs/class/System.Windows.Forms/System.Windows.Forms/InputLanguage.cs

The method InstalledInputLanguages() always returned InvariantCulture. Now, installed input languages are detected properly on Windows.
Reproducer:
`Console.WriteLine(InputLanguage.CurrentInputLanguage.Culture.TwoLetterISOLanguageName.ToUpper());`
Related issue: #13552

[WinForms] Returns real installed input languages on Windows

---

mcs/class/System.Windows.Forms/System.Windows.Forms/TabControl.cs

Fix #12337: Refact selected indexes in TabControl.Remove

---

mono/metadata/class-init.c

This also fixes possible race conditions, because, one global to guard initialization instead of two.

Cleanup initialize_object_slots, remove unused GetHashCode (ghc) handling.

---

mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs

[WinForms] Fix #13777 DrawToBitmap() did not draw children controls

---

packaging/MacSDK/msbuild.py
packaging/MacSDK/nuget.py

[2019-08] bump msbuild+roslyn to track mono-2019-08

---

mono/metadata/monitor.c

The only difference in the copies, was that one had an infinite timeout
so implied TRUE result unless interrupted.
Where the other copy had a timeout and could return FALSE as a result.
They both used the same underlying, with timeout, so it wasn't really an optimization,
just duplicated code.
Also there is subtelty around having a return value or an out parameter.
That is carefully preserved.
Also, coop is fixed, by creating a frame only in a slow path.
Presumably creating a thread is quick and stateless enough such that this
is not too late.

Monitor: Eliminate near identical duplicated code.

---

mono/mini/intrinsics.c

```csharp
Buffer.MemoryCopy((void*) IntPtr.Zero, (void*) IntPtr.Zero, 0, 0);
```
Currently throws NRE but should not if length == 0.
Fixes a few corefx tests when LLVM is enabled.

[LLVM] Don't throw NRE when len == 0 in Buffer.Memmove

---

configure.ac

Community contribution from https://github.com/mono/mono/issues/18009 from @igorzigorz

[configure.ac] Build on FreeBSD/PowerPC64

---

mcs/class/System.Windows.Forms/System.Windows.Forms/RadioButton.cs

[WinForms] Fix #18020 Fix wrong behavior of RadioButton auto-check

---

configure.ac
mcs/class/corlib/corlib.csproj
mcs/class/corlib/unix_build_corlib.dll.sources
sdks/wasm/src/pinvoke-tables-default.h

Added HAVE_LCHFLAGS & HAVE_STAT_FLAGS to configure
Backport of https://github.com/mono/mono/pull/17758

Bump corefx to pick up https://github.com/mono/corefx/pull/370

---

mono/eglib/eglib-remap.h

Update glib-remap.h to include g_module_address

---

mono/eglib/eglib-remap.h

Backport of #18076.
/cc @SamMonoRT

[2019-12] Update glib-remap.h to include g_module_address

---

mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs
mcs/class/System.Windows.Forms/Test/System.Windows.Forms/ComboBoxTest.cs

 [WinForms] Fix #10643 No event should be triggered when calling ComboBox.Items.RemoteAt()

---

mono/mini/interp/interp.c

broke with c4136ebd94567bb29557c94e7480e24fe72ffdac
/cc @NattyNarwhal

[interp] fix build when DEBUG_INTERP is enabled

---

mono/metadata/appdomain.c
mono/metadata/reflection-internals.h
mono/metadata/reflection.c
mono/metadata/sre.c
netcore/CoreFX.issues.rsp
netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml
netcore/System.Private.CoreLib/src/Mono/MonoDomain.cs

In sre.c, avoid a crash due to the missing event but don't properly fix things up (since it's broken anyways). Otherwise, straightforward.

[netcore] Implement AppDomain.TypeResolve

---

mono/metadata/threadpool.c

Fix on-demand initialization race conditions [threadpool.c].

---

mono/metadata/reflection.c

Fix on-demand initialization race conditions [reflection.c].

---

mono/metadata/object.c

Fix on-demand initialization race conditions [object.c].

---

mono/metadata/custom-attrs.c

Fix on-demand initialization race conditions [custom-attrs.c]

---

mono/metadata/marshal-ilgen.c

Fix on-demand initialization race conditions [marshal-ilgen.c]

---

mono/metadata/appdomain.c
netcore/CoreFX.issues.rsp
netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml
netcore/System.Private.CoreLib/src/Mono/MonoDomain.cs

Pretty straightforward. Enables the relevant test.
The diff looks a little silly because I broke off the handles/event firing into a separate function.

[netcore] Implement AppDomain.AssemblyLoad

---

mono/metadata/marshal.c

Fix on-demand initialization race conditions [marshal.c].

---

sdks/wasm/tests/browser/src/BrowserTestSuite/http-spec-with-prom-lib.js
sdks/wasm/tests/browser/src/BrowserTestSuite/http-spec.js
sdks/wasm/tests/browser/src/WebSocketTestSuite/WebSocketTestSuite.cs

[wasm] Fix test case spelling

---

mcs/class/System.Windows.Forms/System.Windows.Forms/Form.cs

This PR is needed for https://github.com/mono/uia2atk/pull/8

[WinForms][UIA] Add new internal event to track form's owner change

---

mono/mini/iltests.il
mono/mini/interp/mintops.h
mono/mini/interp/transform.c

Fixes https://github.com/mono/mono/issues/18120

[interp] add guard that a local hasn't been modified for stlocfld fusion

---

mcs/class/System/Mono.Net.Security/MonoTlsStream.cs

See https://github.com/mono/mono/issues/15805#issuecomment-567131297

[System] Add additional hardening against race in MonoTlsStream

---

sdks/wasm/tests/browser/src/BrowserTestSuite/zip-spec.js
sdks/wasm/tests/browser/src/ZipTestSuite/ZipTestSuite.cs

[wasm] Make sure we're comparing the same date

---

mono/tests/Makefile.am
mono/tests/assembly-load-reference/Makefile.am
mono/tests/testing_gac/Makefile.am

Some test sources weren't included.
Fixes https://github.com/mono/mono/issues/18202
---
Verified that `configure && make && make -C mono/tests check` works as expected.

[tests] Add test files to tarball

---

mono/eglib/glib.h
mono/eglib/test/memory.c

Add cast to ((align) - 1) for Alignment macros

---

mono/eglib/glib.h
mono/eglib/test/memory.c
mono/mini/llvm-jit.cpp

Fix llvm jit assertion

---

mono/metadata/domain.c

Also when iterating over the runtimes, actually look at the current element,
not the first element.
Also mention the unsupported runtime version in the warning message when it is
passed to mono_init_internal.
Fixes https://github.com/mono/mono/issues/17916
Backport of #18260.

[2019-12] [domain] Don't add NULL runtime to runtimes list

---

mono/metadata/domain.c

Also when iterating over the runtimes, actually look at the current element,
not the first element.
Also mention the unsupported runtime version in the warning message when it is
passed to mono_init_internal.
Fixes https://github.com/mono/mono/issues/17916

[domain] Don't add NULL runtime to runtimes list

---

mcs/class/corlib/Test/System.IO/DirectoryInfoTest.cs

Pull in DirectoryInfo Invalidate After Create Fix

---

mono/eglib/test/memory.c

We should really have a linter catching things like lines 84-88 :(

[eglib] Fix whitespace in memory.c

---

mono/dis/main.c
mono/metadata/appdomain.c
mono/metadata/assembly-internals.h
mono/metadata/assembly.c
mono/metadata/assembly.h
mono/metadata/metadata-internals.h
mono/metadata/metadata.c
mono/metadata/reflection.c
mono/mini/driver.c
mono/mini/main-core.c
netcore/CoreFX.issues.rsp
tools/pedump/pedump.c

[loader] Add assembly name matching on netcore to fix DefaultContext test

---

sdks/wasm/DebuggerTestSuite/Support.cs
sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/ProxyDriver/Program.cs
sdks/wasm/ProxyDriver/TestHarnessStartup.cs

Await test test harness startup and start hoisting shared state above the tests

[wasm][debugger] await test server startup

---

mono/tests/Makefile.am
netcore/Makefile
scripts/submodules/versions.mk
sdks/builds/android.mk
sdks/wasm/Makefile

Split into two commits - the shebang stuff might be controversial if CentOS 6 or whatever lacks Python 3.

More "get rid of just-python invocation"

---

packaging/MacSDK/msbuild.py

- This enables parallel build support with msbuild!

[master] Bump msbuild to track xplat-master

---

mono/mini/genmdesc.py
mono/tests/gc-descriptors/gen-descriptor-tests.py
mono/tests/test_lldb.py
scripts/ci/babysitter
scripts/mono-heapviz
scripts/submodules/versions.py
sdks/wasm/print-table.py
tools/sgen/gcpausevis.py

Force Python 3.x from env in shebang lines

---

packaging/MacSDK/msbuild.py
packaging/MacSDK/nuget.py

- update nuget.exe to 5.5.0-preview1 to match

[2019-10] Bump msbuild to track mono-2019-10

---

mono/mini/mini-llvm.c

Should fix https://github.com/mono/mono/issues/18221.
Backport of #18296.

[2019-10] Use byte-aligned LLVM loads and stores for unaligned mini IR loads and stores.

---

mono/mini/generics.cs
mono/mini/method-to-ir.c
mono/mini/mini-generic-sharing.c

Fixes https://github.com/mono/mono/issues/18370.

[jit] Implement fast TLS access in gshared methods.

---

mono/mini/interp/interp.c
netcore/CoreFX.issues_interpreter.rsp

Fixes https://github.com/mono/mono/issues/18061

[interp] Throw overflow exception when converting NaN

---

sdks/wasm/Makefile
sdks/wasm/package.json
sdks/wasm/tests/browser/.npmrc
sdks/wasm/tests/browser/src/BrowserTestSuite/core-bindings-spec.html
sdks/wasm/tests/browser/src/BrowserTestSuite/http-spec-with-prom-lib.html
sdks/wasm/tests/browser/src/BrowserTestSuite/http-spec.html
sdks/wasm/tests/browser/src/BrowserTestSuite/issues-spec.html
sdks/wasm/tests/browser/src/BrowserTestSuite/zip-spec.html
sdks/wasm/tests/runtime/index.html

Add a node dependency and use that to run jsvu

[wasm] use updated node to run jsvu

---

mono/mini/driver.c
mono/mini/mini-runtime.c
mono/mini/mini-runtime.h

Implement parsing for optional method name to `--stats` command line argument.

[mini] Add optional method name to --stats

---

mcs/class/corlib/Test/System.Threading/ThreadTest.cs
mono/mini/intrinsics.c

Fixes https://github.com/mono/mono/issues/18418.

[jit] Fix an assertion in the Thread.VolatileRead () intrinsic.

---

mono/sgen/sgen-los.c
mono/sgen/sgen-memory-governor.c

Fixes https://github.com/mono/mono/issues/18343

[sgen] Fixes for max-heap-size option

---

mono/metadata/threads.c
mono/mini/driver.c
mono/mini/exceptions-amd64.c
mono/mini/exceptions-arm.c
mono/mini/exceptions-arm64.c
mono/mini/method-to-ir.c

Contributing: fixing some typos

---

mono/sgen/sgen-los.c
mono/sgen/sgen-memory-governor.c

Fixes https://github.com/mono/mono/issues/18343
Backport of #18446.
/cc @BrzVlad

[2019-12] [sgen] Fixes for max-heap-size option

---

mono/metadata/appdomain.c
mono/tests/Makefile.am
mono/tests/assembly-refonly-load-bytes-bindingredirect.cs
mono/tests/assembly-refonly-load-bytes-bindingredirect.exe.config

Match .NET Framework behavior.
Addresses #18388

[loader] ReflectionOnlyLoad(byte[]) should not apply binding redirects

---

mono/metadata/appdomain.c
mono/tests/Makefile.am
mono/tests/assembly-refonly-load-bytes-bindingredirect.cs
mono/tests/assembly-refonly-load-bytes-bindingredirect.exe.config

Match .NET Framework behavior.
Addresses #18388 
Backport of #18457.

[2019-12] [loader] ReflectionOnlyLoad(byte[]) should not apply binding redirects

---

mono/metadata/appdomain.c
mono/tests/Makefile.am
mono/tests/assembly-refonly-load-bytes-bindingredirect.cs
mono/tests/assembly-refonly-load-bytes-bindingredirect.exe.config

Match .NET Framework behavior.
Addresses #18388 
Backport of #18457.

[2019-10] [loader] ReflectionOnlyLoad(byte[]) should not apply binding redirects

---

tools/offsets-tool-py/Makefile

Backport of #18190.
/cc @lewurm @marek-safar

[2019-12] [wasm] Improve virtualenv installation script

---

packaging/MacSDK/xsp.py

See https://github.com/mono/xsp/pull/88

Bump xsp to fix issues with removed Mono.Security APIs

---

mono/mini/Makefile.am.in

[interp] Add missing files to tarball

---

mono/eglib/gpath.c
mono/sgen/sgen-protocol.c
mono/utils/mono-threads-windows.c

Compilation warnings fixes

---

mono/mini/interp/transform.c

[mini] Add a conditional to transform.c to enable stat dumping from the interpreter.

---

mono/mini/mini-llvm-cpp.cpp
mono/mini/mini-llvm-cpp.h
mono/mini/mini-llvm.c

Add disable_omit_fp support for LLVM

---

mono/CMakeLists.txt
mono/mini/CMakeLists.txt
mono/mini/gen-version-h.sh

!! This PR is a copy of dotnet/runtime#2108,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Initial CMAKE build system support.

---

configure.ac
docs/HtmlAgilityPack/HtmlAttributeCollection.cs
mcs/class/System.Web.Services/Documentation/en/System.Web.Services.Discovery/ContractReference.xml
mcs/class/System.Web.Services/Documentation/en/System.Web.Services.Discovery/DiscoveryDocument.xml
mcs/class/System.Web.Services/Documentation/en/System.Web.Services.Discovery/DiscoveryDocumentReference.xml
mcs/class/System.Web.Services/Documentation/en/System.Web.Services.Discovery/SchemaReference.xml
mcs/class/referencesource/System.Data.Entity/System/Data/Mapping/ViewGeneration/Validation/ForeignConstraint.cs
mcs/class/referencesource/System.Data.Entity/System/Data/Query/PlanCompiler/TransformationRules.cs
mcs/class/referencesource/System.Data/System/Data/Common/DBConnectionString.cs
mcs/class/referencesource/System.Data/System/Data/Odbc/odbcmetadatafactory.cs
mcs/class/referencesource/System.Data/System/Data/OleDb/OleDbMetaDataFactory.cs
mcs/class/referencesource/System.Data/System/Data/OleDb/oledbconnectionstring.cs
mcs/class/referencesource/System.Data/System/Data/SqlClient/sqlmetadatafactory.cs
mcs/class/referencesource/System.Web.DataVisualization/Common/ChartTypes/BoxPlotChart.cs
mcs/class/referencesource/System.Web.DataVisualization/Common/ChartTypes/ErrorBarChart.cs
mcs/class/referencesource/System/net/System/Net/WebRequestMethods.cs

Contributing: fix typos

---

sdks/wasm/packager.cs

Fixes the source filename for threads support.

[Wasm] Fix threading support file in packager

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

Remove unused variables

---

mono/utils/mono-counters.c

This makes `mono_counters_dump` actually work on Android. If either this added default behavior or the macro is too terrible I can explore other options, but I'm tired and this was fast. See #18580

[utils] Default to g_print in mono_counters_dump if the stream is NULL

---

mono/mini/interp/interp-internals.h
mono/mini/interp/interp.c
mono/mini/interp/transform.c

Alternative to https://github.com/mono/mono/pull/18475 which doesn't ignore mixed mode virtual call performance. It is 20% faster with this approach.
Fixes https://github.com/mono/mono/issues/14206

[interp] Fix virtual calls in mixed mode

---

mcs/build/tests.make
mcs/class/corlib/corlib_xtest.dll.sources

Follow-up to https://github.com/mono/mono/pull/18228 since two parts wasn't enough to fix the size issue on 32bits devices.
We now use three parts.
Fixes https://github.com/mono/mono/issues/18614

[corlib] Split corlib xunit tests even more for iOS

---

mono/utils/mono-mmap-wasm.c

!! This PR is a copy of dotnet/runtime#2386,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[wasm] Fix mono_vfree ().

---

mono/mini/aot-runtime.c

!! This PR is a copy of dotnet/runtime#2397,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>decode_patch_info () would not decode patches if their corresponding GOT entry
was already set, causing half initialized MonoJumpInfo entries to be returned
to callers. Set the type of the MonoJumpInfo entry to MONO_PATCH_INFO_NONE
in these cases, and have the callers handle it.

[aot] Fix some races if GOT entries are already set.

---

mono/mini/interp/transform.c

!! This PR is a copy of dotnet/runtime#31618,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>We were failing to dereference a managed pointer to the enum, due to incorrect checks, when doing a constrained call.
Fixes https://github.com/mono/mono/issues/18530

[interp] Fix enum constrained calls on netcore

---

sdks/builds/wasm.mk

[Wasm] Update to emscripten 1.39.7

---

mono/metadata/icall.c
mono/utils/mono-merp.c
mono/utils/mono-state.h

Addresses https://github.com/mono/mono/issues/18681
Backport of #18685.
/cc @alexischr

[2019-10] [merp] Add an exception type for managed exceptions

---

mono/metadata/icall.c
mono/utils/mono-merp.c
mono/utils/mono-state.h

Addresses https://github.com/mono/mono/issues/18681
Backport of #18685.
/cc @alexischr

[2019-12] [merp] Add an exception type for managed exceptions

---

mono/metadata/icall.c
mono/utils/mono-merp.c
mono/utils/mono-state.h

Addresses https://github.com/mono/mono/issues/18681
Backport of #18685.
/cc @alexischr

[2020-02] [merp] Add an exception type for managed exceptions

---

mono/metadata/icall.c
mono/utils/mono-merp.c
mono/utils/mono-state.h

Addresses https://github.com/mono/mono/issues/18681

[merp] Add an exception type for managed exceptions

---

packaging/MacSDK/packaging/resources/postinstall

[MacSDK] Get more verbose output from fc-cache operation

---

mono/tests/bug-10127.cs

This test is flaky. Maybe this helps. Otherwise I'll dig in later.

Add volatile for cross thread communication in test bug-10127.cs.

---

mcs/tools/linker/Makefile

Bump linker submodule
Backport of #18844.
/cc @akoeplinger @fanyang-mono

[2020-02] Bump linker submodule

---

mcs/tools/linker/Makefile

Bump linker submodule

---

mono/mini/mini-posix.c

Addresses https://github.com/mono/mono/issues/18796
Backport of #18798.
/cc @alexischr

[2019-10] [merp] Increase buffer size for state dump

---

mono/mini/interp/interp.c

https://github.com/mono/mono/pull/18825 was too large.
This starts by replacing imethod with cmethod which is a necessary
part of the consolidation of multiple non-recursive call sites to just one.

[interp] Step toward consolidating non-recursive call sites (cmethod).

---

mono/mini/debugger-state-machine.h

Less to build if you edit the file.

Remove unnecesssary include.

---

mono/mini/interp/interp.c

[interp] Consolidate non-recursive call sites.
Consolidate native_stack_addr as a result (resolving a FIXME).
Builds on:
https://github.com/mono/mono/pull/18857
https://github.com/mono/mono/pull/18858
https://github.com/mono/mono/pull/18869

[interp] Consolidate non-recursive call sites.

---

mono/utils/mono-os-mutex.h

Hopefully the uses are correct and consistent.

[win32] Make non-recursive mutexes SRWLOCK instead of CRITICAL_SECTION.

---

mono/metadata/domain.c

!! This PR is a copy of dotnet/runtime#32556,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes a crash with AOT because domain->setup is NULL here

[loader] Add check to mono_domain_ensure_entry_assembly for AOT

---

mono/mini/interp/interp.c

The real goal is to make it not recursive.
This is just a step along the way.
Note that the actual not-recursive change has *not* yet been developed,
so this *might* amount to nothing useful.

[interp] Inline newobj.

---

mono/metadata/loader.c

!! This PR is a copy of dotnet/runtime#32567,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[metadata] use descriptive constants for method table columns

---

mono/metadata/object-offsets.h
mono/mini/mini-s390x.c

Fix build on s390x after commit 79135c6
Fixes: #18930

add struct offset definitions to s390x

---

mono/mini/interp/interp.c
mono/mini/interp/transform.c

A few wierd here, esp. for string, but CI passes.
Acknowledged but skipped for now, a request to also refactor the opcode -- it doesn't seem like much throwaway work to go in either order, even if the code is dead (which I don't know).
Also amend recent nonrecursive PR to simulate stack +2 instead of +1.

[interp] Non-recursive newobj.

---

sdks/wasm/DebuggerTestSuite/Tests.cs

[wasm][tests] clean up a couple of the Contains assertions

---

mcs/class/corlib/LinkerDescriptor/mscorlib.xml

Backport of #18991.
/cc @fanyang-mono

[2020-02] Revert linker change of 5a65a97

---

mcs/class/corlib/LinkerDescriptor/mscorlib.xml

Revert linker change of 5a65a97

---

mono/metadata/debug-mono-ppdb.c
sdks/wasm/Mono.WebAssembly.DebuggerProxy/Mono.WebAssembly.DebuggerProxy.csproj

Update Mono.Cecil to make possible to use embedded ppdb on wasm

[wasm][debugger] Enable embedded ppdb on wasm

---

mono/mini/mini-posix.c

Addresses https://github.com/mono/mono/issues/18796

[merp] Increase buffer size for state dump

---

mono/mini/mini-posix.c

Addresses https://github.com/mono/mono/issues/18796
Backport of #18798.
/cc @alexischr

[2020-02] [merp] Increase buffer size for state dump

---

mono/mini/mini-posix.c

Addresses https://github.com/mono/mono/issues/18796
Backport of #18798.
/cc @alexischr

[2019-12] [merp] Increase buffer size for state dump

---

mono/mini/mini-exceptions.c

Before, this was only done for managed stacks.
Addresses https://github.com/mono/mono/issues/18941
Backport of #18943.

[2019-12] [merp] Produce hashes for unmanaged thread stacks also

---

mono/mini/mini-exceptions.c

Before, this was only done for managed stacks.
Addresses https://github.com/mono/mono/issues/18941
Backport of #18943.

[2020-02] [merp] Produce hashes for unmanaged thread stacks also

---

mono/mini/mini-exceptions.c

Before, this was only done for managed stacks.
Addresses https://github.com/mono/mono/issues/18941

[merp] Produce hashes for unmanaged thread stacks also

---

mono/mini/mini-wasm-debugger.c
sdks/wasm/DebuggerTestSuite/Support.cs
sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs
sdks/wasm/debugger-driver.html
sdks/wasm/debugger-test.cs

This fixes various issues in accessing locals on the stack.

[wasm][debugger] Improve accessing locals

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

[wasm][debugger] Use AsLocation when creating location

---

mono/mini/interp/interp-internals.h

for alignment. Size goes from 192 to 184.

[interp] Reorder InterpMethod to reduce padding

---

netcore/CoreFX.issues_interpreter.rsp

Attempt to enable more tests which don't seem to fail locally

[interp] Enable more interp tests

---

mono/eglib/gspawn.c

Change macro CLOSE_PIPE to function mono_close_pipe
Extracted from https://github.com/mono/mono/pull/19025.

Change macro CLOSE_PIPE to function mono_close_pipe.

---

mono/mini/mini-wasm-debugger.c
sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/debugger-driver.html
sdks/wasm/debugger-test.cs

[wasm][debugger] Fixes to get async method locals

---

mcs/class/Mono.Debugger.Soft/Test/dtest.cs
mono/metadata/Makefile.am
mono/metadata/debug-mono-ppdb.c

Backport https://github.com/mono/mono/pull/18895
Backport of #19049.
/cc @thaystg

[2019-12] [2020-02][debugger] Enable reading embedded ppdb

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs

[wasm][debugger] clean up scriptid parsing

---

mcs/class/Mono.Debugger.Soft/Test/dtest.cs
mono/metadata/Makefile.am
mono/metadata/debug-mono-ppdb.c

Backport https://github.com/mono/mono/pull/18895

[2020-02][debugger] Enable reading embedded ppdb

---

mono/metadata/appdomain.c

!! This PR is a copy of dotnet/runtime#32934,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[loader] Remove unnecessary newline in loader mono_trace call

---

mono/metadata/native-library.c

!! This PR is a copy of dotnet/runtime#32985,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Oops.

[loader] Free some leaked strings in NativeLibrary resolution

---

mono/metadata/icall.c
mono/mini/mini-posix.c
mono/utils/mono-state.c
mono/utils/mono-state.h

/cc @kdubau @lambdageek 
Addresses https://github.com/mono/mono/issues/18715

[merp] Create a signal ('source') breadcrumb for the crash dump process

---

mono/metadata/class-init.c
mono/tests/Makefile.am
mono/tests/dim-issue-18917.cs

The problem was a parent class overriding an interface that was already override by another interface.
Fix #18917

[dim] Class overriding interface method that was already override by another interface

---

mono/tests/merp-crash-test.cs

Contributes to https://github.com/mono/mono/issues/18078

[merp] Add a test for Mono.Runtime.ExceptionToState()

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

[wasm][debugger] Hash messages and sessions directly

---

sdks/wasm/src/driver.c

[wasm] remove m_strdup

---

mono/mini/aot-runtime.c

Fixes https://github.com/mono/mono/issues/18612; `aot_code_low_addr` and
`aot_code_high_addr` were set to a range that included only first-level
branch islands, so `find_aot_module` would fail early when passed a
genuine function address.
This change only affects monotouch for now.
Why not use relative offsets stored in a read-only section? One reason
is that llvm-as cannot handle a `.long` directive containing a
subtraction expression involving externally-defined symbols. The AOT
method address table and AOT LLVM-generated code are currently emitted
in separate object files, so the method address table would include
expressions with undefined symbols.
Related: https://xamarin.github.io/bugzilla-archives/70/707/bug.html

[arm][ios] Follow branch islands when determining method entry addresses.

---

winconfig.h

!! This PR is a copy of dotnet/runtime#33421,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>A temp fix for https://github.com/dotnet/runtime/issues/1933
to unblock @MaximLipnin 
Still has to be fixed, must be some missing #define etc (It's been broken for quite a while)

[mono] Disable SIMD support for Windows target

---

sdks/wasm/packager.cs
sdks/wasm/standalone-benchmarks/run-benchmark-wasm.sh

[wasm][packager] add option to pull from a different runtime directory

---

mono/mini/unwind.c

!! This PR is a copy of dotnet/runtime#33107,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Whenever there must be a loop that goes indefinitely, there are either return statements or break statements in the code.
However, in this codebase, there are "infinite loops" that appear as such until the next line is checked, which is an if statement saying to break if a condition is true.
This unneeded complexity can be resolved by inverting the condition and making that the while-loop …

No need to have a "while (TRUE)" statment if a for loop can work, or if there is a check right at the beginning.

---

mono/mini/method-to-ir.c

!! This PR is a copy of dotnet/runtime#32194,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This PR optimizes boxing for pattern matching idioms. Basically, it copies existing optimizations from CoreCLR to mono, see [impBoxPatternMatch](https://github.com/dotnet/runtime/blob/084dd1a5aae0fbe6ed4f9164ac4ee1c5f0b2398f/src/coreclr/src/jit/importer.cpp#L5856-L6032) (one of them was recently added by me for coreclr, see https://github.com/dotnet/runtime/pull/1817)
```csharp
public static int Case1<T>(T t)
{
if (t is int)
return 42;
return 0;
}
/*
IL_0000: ldarg.0
IL_0001: box !!T
IL_0006: isinst [System.Private.CoreLib]System.Int32
IL_000b: brfalse.s IL_0010
IL_000d: ldc.i4.s 42
IL_000f: ret
IL_0010: ldc.i4.0
IL_0011: …
```

[mono] Optimize boxing in Pattern Matching idioms

---

sdks/wasm/src/binding_support.js

store a converter object for each type string passed in
use that object to simplify the marshaling step. do one allocation
for arguments and exceptions.

[wasm][bindings] rework argument marshaling in call_method

---

sdks/wasm/DebuggerTestSuite/InspectorClient.cs
sdks/wasm/ProxyDriver/TestHarnessStartup.cs

Handle wss: and ws: debug proxy connection strings and be slightly more careful about
what we consider a match.

[wasm][tests] be slightly more careful looking for the connection string

---

mono/mini/mini-wasm-debugger.c
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
sdks/wasm/src/library_mono.js

Continue stepping over/into/out of managed code to native code, without this fix the behavior was resume when a SS leaves the managed code.

[wasm][debugger] Continue SS after leaving managed code

---

mono/metadata/threads.c
mono/utils/mono-state.c
mono/utils/mono-state.h

[merp] Add breadcrumb for StackHash

---

mono/metadata/threads.c
mono/utils/mono-state.c
mono/utils/mono-state.h

Backport of #19240.
/cc @alexischr

[2019-12] [merp] Add breadcrumb for StackHash

---

mono/mini/mini-amd64.c

A couple of more op codes embedded constant values in instruction stream. When using MONO_ARCH_CODE_EXEC_ONLY these needs to be moved into GOT slots.
Thanks @buggeststar for bring the issues to our attention.

Fix additional constants embedded in instruction stream on AMD64.

---

mono/mini/interp/mintops.def
mono/mini/interp/mintops.h
mono/mini/interp/transform.c

That are accessing the stack value at level -2.

[interp] Do cfold for a few more unary operators

---

mono/mini/interp/interp.c
mono/mini/interp/transform.c

Speeds up by 3.5x some span operations. We will likely get even more performance improvement there by adding special handling in interpreter for IntPtr.

[interp] Inline also constructors of valuetypes

---

mono/metadata/icall.c

!! This PR is a copy of dotnet/runtime#33723,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Fix warning building Mono using -Wint-conversion.

---

mono/mini/interp/transform.c

[interp] Optimize out intptr ctor

---

mono/tests/bug-10127.cs

This test is flaky, so let's simplify it a tiny bit.

Remove dead code from bug-10127.cs.

---

mono/utils/mono-threads-state-machine.c

Previously it would print a warning, only, because otherwise we would get a
second assert in the same place while the crash machinery would run from the
current thread from the abort in `mono_fatal_with_history`
The solution is to turn off the "no safepoints" bit since we know we're
definitely going to assert here.
Also record the current state in the checked mode state transition history to
make it a bit easier to diagnose where the problem surfaced.
Also fixed up a pair of other debugging/tracing messages so the message strings
accurately reflect the state.

[coop] Make MONO_ENTER_GC_UNSAFE fatal if no_safepoints is set

---

mono/metadata/assembly.c

!! This PR is a copy of dotnet/runtime#33941,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>The code here was right, the comment wrong. Also updated to mention that we now check APP_PATHS.

[loader] Fix mistake in netcore_load_reference comment

---

mono/utils/mono-threads-posix.c

!! This PR is a copy of dotnet/runtime#33966,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Try to address https://github.com/dotnet/runtime/issues/32377
(signal queue overflow) by sleeping and retrying a few times.
This is kind of a hack, but it woudl be good to see if it will address the issue

[mono] retry mono_threads_pthread_kill if result == EAGAIN on Linux

---

mono/metadata/icall.c

!! This PR is a copy of dotnet/runtime#33857,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Current implementation always returned true for Windows/Linux/Android. There are however use of this API in Task library to make sure recursive tasks won't hit stackoverflow. There are several tests in System.Threading.Tasks that currently hit this, at least on Windows, causing test failures.
Fix use stack limits already setup in register_thread and used by GC when doing conservative stack scan. …

Implement icall used by RuntimeHelpers.EnsureSufficientExecutionStack on netcore Mono.

---

mono/metadata/custom-attrs.c

!! This PR is a copy of dotnet/runtime#33937,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>https://github.com/dotnet/runtime/commit/9dec6ae2ea81d46884bf49d2df8b26cc1e28eb12#r37604565

[metadata] Fix leak in custom attribute lookup

---

mono/metadata/image.c

!! This PR is a copy of dotnet/runtime#34037,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[loader] Clear filename when debugging assembly unloading

---

mono/metadata/native-library.c

!! This PR is a copy of dotnet/runtime#33938,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Copy-paste error

[loader] Fix some log masks in native-library

---

sdks/wasm/framework/src/WebAssembly.Bindings/Core/TypedArray.cs

fixes https://github.com/mono/mono/issues/19288

[wasm][bindings] Remove typedarray length validation

---

sdks/wasm/Makefile

[wasm] Add make target to clean the framework directory

---

mono/mini/mono-private-unstable.h
mono/mini/monovm.h

!! This PR is a copy of dotnet/runtime#34047,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[meta] Make monovm_initialize public

---

mono/metadata/threads.c
mono/utils/mono-state.c
mono/utils/mono-state.h

Backport of #19240.
/cc @alexischr

[2020-02] [merp] Add breadcrumb for StackHash

---

sdks/wasm/Makefile

[wasm] Build aot-hello using --nobinding.

---

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/EventRequest.cs
mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs
mcs/class/Mono.Debugger.Soft/Test/dtest.cs
mono/mini/debugger-agent.c
mono/mini/debugger-engine.c
mono/mini/debugger-engine.h
mono/mini/mini-runtime.c
mono/mini/mini-wasm-debugger.c

[2020- 02][debugger] Implementing step through multithreaded code.

---

mono/mini/interp/transform.c
mono/mini/interp/transform.h

!! This PR is a copy of dotnet/runtime#34190,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Special cases around infinite recursiveness were not handled by the interpreter.

[interp] Fix issues around not yet supported System.Runtime.Intrinsics

---

mono/mini/mini-llvm.c

[llvm] Handle this arguments as inputs to phi nodes, i.e. for IL code doing starg.0.

---

sdks/wasm/packager.cs

[wasm] Fix threads support in the packager.

---

sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets

[wasm][sdk] fix output files

---

mono/mini/interp/transform.c

!! This PR is a copy of dotnet/runtime#34219,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[interp] Optimize Span<byte>.Fill

---

mono/metadata/monitor.c
mono/metadata/threads.c
mono/metadata/w32handle.c
mono/metadata/w32handle.h

[wasm] Throw an exception in some blocking operations in non-threaded mode.

---

sdks/wasm/README.md

Closes https://github.com/mono/mono/issues/19293

[wasm][docs] Document threading setup for webassembly build

---

mono/metadata/metadata.c

[runtime] Fix a problem with PR #19361.

---

configure.ac
mono/mini/driver.c
mono/mini/mini-runtime.c
mono/mini/mini-runtime.h
mono/mini/mini.c

Initial perf jitdump implementation

---

mono/mini/debugger-engine.c
mono/mini/debugger-engine.h

Adding static to ss_req_acquire and ss_req_count
Fixes #19389

[debugger] Adding static to ss_req_acquire and ss_req_count

---

mono/tests/.gitignore

!! This PR is a copy of dotnet/runtime#34281,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Should, for any reason, we need to remove /*.stderr or /*.aotlog from gitignore, there are two places to remove it from in the gitignore.
So I removed the duplicated entries.

Remove duplicated gitignore patterns

---

mono/metadata/threads.c

[wasm] Throw an exception when trying to start a thread instead of asserting.

---

mono/metadata/metadata.c

sets.
This fixes: https://issuetracker.unity3d.com/issues/editor-crash-when-entering-and-exiting-playmode-for-a-few-times-with-microsoft-maps-sdk
@joncham and I were working on this we hit the two asserts that I've removed. We were wondering if they were still needed?

Ensure generic parameter constraint type is included when building image

---

sdks/Make.config.sample
sdks/wasm/README.md
sdks/wasm/build.sh

Update build docs
closes https://github.com/mono/mono/issues/19409

[wasm][README] WASM Dynamic Runtime doc

---

mono/metadata/boehm-gc.c
mono/metadata/gc-internals.h
mono/metadata/icall-def-netcore.h
mono/metadata/null-gc.c
mono/metadata/object.c
mono/metadata/sgen-mono.c

!! This PR is a copy of dotnet/runtime#34398,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>https://github.com/dotnet/runtime/issues/33583

[sgen] Implement api for allocating pinned arrays

---

mono/mini/mini-wasm-debugger.c
sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/Makefile
sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
sdks/wasm/debugger-array-test.cs
sdks/wasm/debugger-driver.html
sdks/wasm/debugger-valuetypes-test.cs
sdks/wasm/src/library_mono.js

[wasm][debugger] Improve array visualization

---

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
mcs/class/Mono.Debugger.Soft/Test/dtest.cs
mono/mini/debugger-agent.c

As suggested by @jbevain we should bump the protocol to implement multi threaded single step.

[debugger] Bump protocol for  multi threaded single step implementation

---

mono/mini/aot-compiler.c
mono/mini/aot-runtime.c
mono/mini/aot-runtime.h
mono/mini/mini-llvm.c

[llvm] Replace the LLVM got array with a set of scalar variables whic…  …h are initialized by a callback called by the runtime.

---

mono/mini/llvm-jit.cpp

Share more code between LLVM 6 and LLVM 9.
Mangler::getNameWithPrefix takes a Twine, not a std::string, so use a
StringRef to avoid an unnecessary allocation.
InstructionCombiningPass grew a dependency on
ProfileSummaryInfoWrapperPass in
https://github.com/dotnet/llvm-project/commit/09e539fcaebb6362795d352cdcf4a818cf4d0d6a,
which depends on the enclosing FunctionPassManager having a valid
reference to a module. This commit adds a dummy module to satisfy this,
instead of recreating a new FunctionPassManager on every compilation.
(See also
http://lists.llvm.org/pipermail/llvm-dev/2019-March/130690.html.)

[llvm] Enable optimizations for LLVM 9 JIT.

---

mono/metadata/sgen-mono.c

!! This PR is a copy of dotnet/runtime#34629,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[sgen] Fix coverity issue

---

sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/Makefile
sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/EvaluateExpression.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
sdks/wasm/debugger-evaluate-test.cs

[wasm][debugger] Improving evaluate expression implementation (#19444)

---

mono/metadata/assembly-load-context.c

!! This PR is a copy of dotnet/runtime#34602,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[meta] Fix loader printf mistake and outdated info in Makefile

---

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs
mcs/class/Mono.Debugger.Soft/Test/dtest.cs
mono/mini/debugger-agent.c

Backporting this, and after this I will backport the bump protocol for this PR.
Backport #19248

[2020-02][debugger] Fix NOT_IMPLEMENTED while debugging.

---

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
mono/mini/debugger-agent.c

[2020-02][debugger] Bump protocol for this commit https://github.com/mono/mono/pull/19248

---

mcs/class/corlib/Mono/Runtime.cs

Should fix https://github.com/mono/mono/issues/19406

[merp] Synchronize (serialize) calls to MERP API

---

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
mcs/class/Mono.Debugger.Soft/Test/dtest.cs
mono/mini/debugger-agent.c

As suggested by @jbevain we should bump the protocol to implement this. (#19437)
Backport https://github.com/mono/mono/pull/19437/

[2020-02][debugger] Bump protocol for multi threaded single step implementation

---

sdks/wasm/package-update/download-packages.ps1
sdks/wasm/package-update/download-packages.sh

Add powershell and bash scripts for replacing default webassembly nuget packages from link or path.

[wasm] Add scripts for updating webassembly nuget packages

---

scripts/ci/pipeline/sdks-archive.groovy

Upload the zip in sdks/wasm

---

scripts/ci/run-jenkins.sh

Backport of #19508.
/cc @lewing

[3.2-wasm] [wasm][ci] Always build and package wasm

---

scripts/ci/pipeline/sdks-archive.groovy

[3.2-wasm][ci] Use path not name

---

sdks/wasm/package-update/download-packages.ps1
sdks/wasm/package-update/download-packages.sh

Add powershell and bash scripts for replacing default webassembly nuget packages from link or path. 
Backport of #19498.
/cc @lewing @tqiu8

[3.2-wasm] [wasm] Add scripts for updating webassembly nuget packages

---

sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/src/driver.c

[wasm] Disable interpreter optimizations when debugging.

---

sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/src/driver.c

[3.2-wasm] [wasm] Disable interpreter optimizations when debugging.

---

scripts/ci/run-jenkins.sh

[wasm][ci] Always build and package wasm

---

sdks/wasm/common/Versions.props
sdks/wasm/sdk/Mono.WebAssembly.Sdk/sdk/Versions.props
sdks/wasm/sdk/Templates/templates/DotNet/global.json
sdks/wasm/tests/browser/src/global.json

[wasm][sdk][nuget] Bump version.

---

sdks/wasm/package-update/README.md

Adding instructions for running update scripts. 
Backport of #19507.
/cc @lewing @tqiu8

[3.2-wasm] [wasm] Add readme to package update scripts

---

mono/mini/aot-runtime.c

!! This PR is a copy of dotnet/runtime#34880,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[wasm] Disable the AOT cache check on wasm as well.

---

mono/metadata/assembly.c

!! This PR is a copy of dotnet/runtime#34951,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Fix an uninitialized variable error introduced by https://github.com/dotnet/runtime/issues/34877

---

sdks/wasm/Makefile

[wasm] force set a locale when running debugger tests

---

sdks/wasm/ProxyDriver/TestHarnessStartup.cs

[wasm] Use browser style lang

---

sdks/wasm/ProxyDriver/TestHarnessStartup.cs

Backport of #19544.
/cc @lewing

[3.2-wasm] [wasm] Use browser style lang

---

sdks/wasm/Makefile

Backport of #19546.
/cc @lewing

[3.2-wasm] [wasm] force set a locale when running debugger tests

---

sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
sdks/wasm/debugger-driver.html
sdks/wasm/debugger-test.cs
sdks/wasm/src/library_mono.js

[wasm] Debugger test improvements.

---

mono/mini/mini-wasm-debugger.c

[wasm][debugger] Fix typo and silence output

---

configure.ac

!! This PR is a copy of dotnet/runtime#34965,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Make the -Wsometimes-uninitialized into an error.

---

sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

Add logic to support embedded sources and
add all the documents from multi-doc methods
Add logic to check source hashes against
pdb hash.

[wasm][debugger] Handle multi-doc methods and multiple results for breakpoints

---

mono/mini/aot-runtime.c

!! This PR is a copy of dotnet/runtime#34880,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
Backport of #19522.
/cc @lewing @monojenkins

[3.2-wasm] [wasm] Disable the AOT cache check on wasm as well.

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs

With embedded pdbs we have to try to load symbols even when the
pdb is missing then handle ArgumentException if there is no embedded
pdb.  This restores the intended error path and added an explanation
while still logging unexpected errors

[wasm][debugger] Add comment about embedded pdbs and fix old regression

---

mono/mini/mini-wasm-debugger.c

Backport of #19556.
/cc @lewing

[3.2-wasm] [wasm][debugger] Fix typo and silence output

---

sdks/wasm/Makefile
sdks/wasm/src/driver.c

[wasm] Update netcore support.

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

[3.2-wasm][wasm][debugger] Backport of 19449 3.2 wasm

---

mono/mini/mini-wasm-debugger.c
sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/Makefile
sdks/wasm/debugger-test.cs
sdks/wasm/src/library_mono.js

backport of #19537 
cc @radical

[3.2-wasm][wasm][debugger] Show pointer type+address

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs

With embedded pdbs we have to try to load symbols even when the
pdb is missing then handle ArgumentException if there is no embedded
pdb.  This restores the intended error path and added an explanation
while still logging unexpected errors
Backport of #19563.
/cc @lewing

[3.2-wasm] [wasm][debugger] Add comment about embedded pdbs and fix old regression

---

sdks/wasm/common/Versions.props
sdks/wasm/sdk/Mono.WebAssembly.Sdk/sdk/Versions.props
sdks/wasm/sdk/Templates/templates/DotNet/global.json
sdks/wasm/tests/browser/src/global.json

Backport of #19483.
/cc @lewing @kjpou1

[3.2-wasm] [wasm][sdk][nuget] Bump version.

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

Fixes https://github.com/mono/mono/issues/19549

[wasm][debugger] Add an option to clear navigator.webdriver on attach

---

mono/tests/Makefile.am

See https://github.com/mono/mono/issues/19603

[tests] Disable sgen-bridge.exe on Windows x64 FullAOT+LLVM

---

mcs/class/corlib/Makefile
mcs/class/corlib/ReferenceSources/CompareInfo.cs
mcs/class/corlib/corlib.csproj
mcs/class/corlib/wasm_corlib.dll.exclude.sources
sdks/wasm/packager.cs
sdks/wasm/src/linker-disable-collation.xml
sdks/wasm/xunit-exclusions.rsp

[wasm] Reenable the managed collation code, link it out by default, add a packager option to enable it.

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

Fixes https://github.com/mono/mono/issues/19549
Backport of #19584.
/cc @lewing

[3.2-wasm] [wasm][debugger] Add an option to clear navigator.webdriver on attach

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

[3.2-wasm] Wasm webdriver fix

---

mono/metadata/verify-internals.h

Fix a warning.

---

mcs/class/System/Mono.Net.Security/MonoTlsProviderFactory.cs
mcs/class/System/System.Net.Security/SslStream.cs
mcs/class/corlib/System.Diagnostics.Tracing/EventSource.cs
sdks/wasm/xunit-exclusions.rsp

https://github.com/mono/mono/issues/18735
cc @steveisok @lewing

[wasm] Add throwing PNSE to where currently disabled tests throw something different

---

mcs/class/System/Mono.Net.Security/MonoTlsProviderFactory.cs
mcs/class/System/System.Net.Security/SslStream.cs
mcs/class/corlib/System.Diagnostics.Tracing/EventSource.cs
sdks/wasm/xunit-exclusions.rsp

https://github.com/mono/mono/issues/18735
cc @steveisok @lewing 
Backport of #19538.
/cc @lewing @MaximLipnin

[3.2-wasm] [wasm] Add throwing PNSE to where currently disabled tests throw something different

---

mcs/class/corlib/Makefile
mcs/class/corlib/ReferenceSources/CompareInfo.cs
mcs/class/corlib/corlib.csproj
mcs/class/corlib/wasm_corlib.dll.exclude.sources
sdks/wasm/packager.cs
sdks/wasm/src/linker-disable-collation.xml
sdks/wasm/xunit-exclusions.rsp

[3.2-wasm] [wasm] Reenable the managed collation code, link it out by default, add a packager option to enable it.

---

mono/metadata/external-only.c
mono/metadata/object.h

!! This PR is a copy of dotnet/runtime#35197,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>I've adopted the v2 convention instead of attempting a more descriptive name, with the hope that it makes iteration easier in the future and simplifies opt-in obsoletion.
cc: @vargaz @garuma

[meta] Add GCHandle embedding API v2 with pointer-sized handles

---

mono/mini/mini-posix.c
mono/mini/mini-runtime.c
mono/utils/mono-time.c
mono/utils/mono-time.h

!! This PR is a copy of dotnet/runtime#34536,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>fixes dotnet/runtime#34074

Refactor get_time_stamp_ns

---

mono/metadata/exception.c

!! This PR is a copy of dotnet/runtime#35448,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Add some missing linker exclusions.

---

mono/mini/debugger-agent.c

Fixing this PR 
https://github.com/mono/mono/pull/19542

[debugger] Cleaning error before return Invalid_argument.

---

mono/profiler/Makefile.am
tools/sgen/Makefile.am

Disable a few executables if DISABLE_EXECUTABLES is defined.

---

mono/mini/mini-wasm-debugger.c

[wasm][debugger] Fix type argument

---

mono/mini/mini-wasm-debugger.c

fix numbers inspection in js
Backport of #19704.
/cc @lewing

[3.2-wasm] [wasm][debugger] Fix type argument

---

sdks/wasm/DebuggerTestSuite/Support.cs
sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/debugger-test2.cs

[wasm][debugger] Add tests for floating common types

---

sdks/wasm/DebuggerTestSuite/Support.cs
sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

Manual backport of #19688 to 3.2-wasm

[3.2-wasm][wasm][debugger] Backport of #19688

---

sdks/wasm/DebuggerTestSuite/Support.cs
sdks/wasm/DebuggerTestSuite/Tests.cs
sdks/wasm/debugger-test2.cs

Backport of #19712.
/cc @lewing

[3.2-wasm] [wasm][debugger] Add tests for floating common types

---

sdks/wasm/DebuggerTestSuite/Tests.cs

Add 2 tests for checking multiple inline breakpoints

[wasm][debugger][tests] Add tests for multiple breakpoints inline

---

sdks/wasm/DebuggerTestSuite/Tests.cs

Add 2 tests for checking multiple inline breakpoints
Backport of #19718.
/cc @lewing @tqiu8

[master] [wasm][debugger][tests] Add tests for multiple breakpoints inline

---

mono/mini/interp/interp.c
mono/mini/interp/mintops.def
mono/mini/interp/transform.c

!! This PR is a copy of dotnet/runtime#35952,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>param_count is always 1 and it doesn't need to be computed at runtime.

[interp] Remove unnecessary code

---

sdks/builds/wasm.mk

[wasm] Use the official emsdk repo. Use the same version of emsdk as emscripten.

---

mono/mini/interp/interp.c
mono/mini/mini-x86.c

[interp] Fix sdks build

---

sdks/builds/wasm.mk

[wasm] Bump emscripten to 1.39.15.

---

sdks/wasm/DebuggerTestSuite/DateTimeTests.cs
sdks/wasm/Makefile
sdks/wasm/debugger-datetime-test.cs

[wasm][debugger][tests] Add locale tests for datetime

---

sdks/wasm/DebuggerTestSuite/DateTimeTests.cs
sdks/wasm/Makefile
sdks/wasm/debugger-datetime-test.cs

Backport of #19734.
/cc @radical @tqiu8

[master] [wasm][debugger][tests] Add locale tests for datetime

---

mono/metadata/image.c
mono/metadata/marshal.c
mono/metadata/metadata-internals.h

[runtime] Move delegate_bound_static_invoke_cache to MonoWrapperCaches.

---

mono/tools/offsets-tool/offsets-tool.py

!! This PR is a copy of dotnet/runtime#36602,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Needed for the iOS Simulator for 32bit iOS devices.

Fixes for iOS x86 build

---

llvm/build.mk

Added hard limit to sub-make jobs. Fixes #19784

---

mono/mini/interp/interp.c
mono/mini/interp/mintops.def
mono/mini/interp/transform.c

[interp] Small cleanups

---

mono/metadata/marshal.c

!! This PR is a copy of dotnet/runtime#35686,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Simple here means of rank 1, and with a blittable value type as element type.
Contributes to https://github.com/dotnet/runtime/issues/35225

[mono] Implement AsAny marshalling for simple arrays

---

sdks/wasm/src/linker-preserves.xml

Fixes https://github.com/mono/mono/issues/19826.

[wasm] Preserve UnmanagedFunctionPointerAttribute.

---

mono/metadata/loader-internals.h
mono/metadata/native-library.c

!! This PR is a copy of dotnet/runtime#36835,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Add MONO_LOADER_LIBRARY_NAME define

---

mono/metadata/Makefile.am

Fixing make dist after implementation of static ICU Shim.

Fixing make dist after implementation of static ICU Shim.

---

sdks/wasm/packager.cs

[wasm] Avoid overwriting the pinvoke table if not changed.

---

sdks/wasm/Makefile
sdks/wasm/packager.cs

[wasm] Remove obsolete emscripten options.

---

sdks/wasm/docs/runtime-debugging.md

[wasm] Add more runtime debugging docs.

---

mono/mini/mini-generic-sharing.c

Fixes https://github.com/mono/mono/issues/19837.

[wasm] Fix the handling of i8/u8 in get_wrapper_shared_type_full ().

---

mono/mini/simd-intrinsics-netcore.c

!! This PR is a copy of dotnet/runtime#37036,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[runtime] Implement the many argument version of the Vector128.Create () intrinsic.

---

mono/metadata/sre-save.c

!! This PR is a copy of dotnet/runtime#36589,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Contributes to https://github.com/mono/mono/issues/14788

[mono] Implement AssemblyBuilder.GetSatelliteAssembly

---

mono/mini/interp/interp.c

!! This PR is a copy of dotnet/runtime#37160,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[interp] Remove assertions from release and add more to debug builds

---

mono/metadata/appdomain.c
mono/metadata/icall-eventpipe.c
mono/metadata/native-library.c
mono/metadata/object.c
mono/mini/monovm.c
msvc/libeventpipe.targets

!! This PR is a copy of dotnet/runtime#37153,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Fix Mono C++ build.

---

sdks/wasm/Makefile
sdks/wasm/packager.cs
sdks/wasm/samples/hello/hello.csproj

[wasm] Fix netcore support in the packager.

---

mono/mini/interp/interp.c

!! This PR is a copy of dotnet/runtime#37135,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/>
<br/>
For PInvokes, `ves_pinvoke_method` is called when we're interpreting the
pinvoke wrapper, after it already executed a transition from GC Unsafe to GC
Safe mode.  At that point, calling back into the runtime we have to temporarily
switch back to GC Unsafe mode.
Example stack trace where we don't:
```
0x10dbdd7d6 - /private/tmp/helix/working/B38709D8/p/libcoreclr.dylib : …
```

[interp] Switch to GC Unsafe mode before calling get_interp_to_native_trampoline

---

.github/CODEOWNERS

[github] remove me from codeowners

---

mono/mini/interp/interp.c

Regressed recently with the change in return value handling.

[interp] Fix tracing

---

sdks/wasm/print-table.py

[wasm] Fix the print-table.py script.

---

sdks/wasm/src/linker-subs.xml

[wasm] Link out the SR resource string code on netcore.

---

mcs/tools/wasm-tuner/tuner.cs
sdks/wasm/src/driver.c

[wasm] Fix icall linking with netcore.

---

mono/mini/aot-runtime.c

Fixes https://github.com/mono/mono/issues/19879.

[aot] Fix the binary search in the llvmonly unbox tramp table.

---

mono/utils/mono-context.h

Use new ucontext handling for glibc 2.26

---

configure.ac
mono/utils/mono-time.h

!! This PR is a copy of dotnet/runtime#37457,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes mono/mono#19733

Check the existence of clocked_t

---

sdks/wasm/framework/src/WebAssembly.Bindings/Runtime.cs
sdks/wasm/src/binding_support.js
sdks/wasm/tests/browser/src/BindingsTestSuite/BindingsTestSuite.cs
sdks/wasm/tests/browser/src/BindingsTestSuite/BindingsTestSuite.csproj
sdks/wasm/tests/browser/src/BrowserTestSuite/core-bindings-spec.js

Fixes https://github.com/mono/mono/issues/19943.

[wasm] Fix marshalling of pointer types.

---

mcs/class/corlib/Mono/Runtime.cs
mono/tests/merp-crash-test.cs

[merp] Add API methods for getting hashcode/reason of last crash

---

mono/mini/aot-runtime.c
mono/mini/driver.c

!! This PR is a copy of dotnet/runtime#37765,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[wasm] Disable aot support in release builds.

---

mono/tests/merp-crash-test.cs

Contributes to https://github.com/mono/mono/issues/18078
Backport of #18781.
/cc @alexischr

[2020-02] [merp] Add a test for Mono.Runtime.ExceptionToState()

---

mono/mini/mini-wasm.c

!! This PR is a copy of dotnet/runtime#37811,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[netcore] Implement timers for wasm.

---

scripts/ci/pipeline-netcore-runtime.yml

We have those over in dotnet/runtime now.

[netcore] Disable Interpreter CI runs

---

sdks/builds/wasm.mk

Bump emscripten to 1.39.18.

---

sdks/wasm/docs/getting-started/sample.md
sdks/wasm/sample.cs
sdks/wasm/sample.html

Fix readme and sample.html, the way that it was it wasn't working if you follow the instructions.

[wasm] Fix readme and sample.html.

---

sdks/wasm/Mono.WebAssembly.DebuggerProxy/EvaluateExpression.cs

Numbers are doubles not ints so support the full size.  I'll add tests before committing.

[wasm][debugger] evaluateOnCallFrame use double numbers

---

mono/mini/iltests.il
mono/mini/intrinsics.c
mono/mini/method-to-ir.c
mono/mini/mini.h

Fixes https://github.com/xamarin/xamarin-android/issues/4817.

[jit] Fix the Activator.CreateInstance () intrinsic for primitive types.

---

mono/mini/interp/interp.c
mono/mini/interp/mintops.def
mono/mini/interp/transform.c

Regressed recently with the addition of specialized ldfld.vt opcodes

[interp] Add unaligned version for ldfld.vt opcodes

---

mono/mini/mini-wasm.c

!! This PR is a copy of dotnet/runtime#38029,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Register a JS callback when a work item is queued, the callback will call into the runtime/bcl to execute the work item.

Add threadpool support for webassembly.

---

sdks/wasm/package-update/README.md
sdks/wasm/package-update/download-packages.ps1
sdks/wasm/package-update/download-packages.sh

Fixed scripts to handle copying files from local builds. Updated readme

Fix package update scripts for local builds

---

mono/mini/interp/interp.c
mono/mini/interp/mintops.def
mono/mini/interp/transform.c

!! This PR is a copy of dotnet/runtime#38561,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[interp] Small improvements around ByReference ctor

---

mono/metadata/Makefile.am

Adding qcalls-def.h to Makefile.am

---

mono/metadata/icall.c

!! This PR is a copy of dotnet/runtime#38646,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/36271

[mono] Implement getting the type modifiers for DynamicMethod parameters

---

mono/mini/interp/interp.c

!! This PR is a copy of dotnet/runtime#38813,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Their usage resulted in worse code on wasm.

[interp] Remove usage of some gotos

---

mono/metadata/native-library.c
mono/mini/interp/transform.c
mono/mini/mini-exceptions.c
mono/mini/mini-runtime.c
mono/sgen/sgen-gc.c

!! This PR is a copy of dotnet/runtime#38960,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>cc: @richlander, @terrajobst, @jkotas

Improve terminology used in code

---

configure.ac

!! This PR is a copy of dotnet/runtime#38977,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[wasm] Add beginnings of support for building with ICU.

---

configure.ac

!! This PR is a copy of dotnet/runtime#38818,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/33079

[mono] Disable config dir lookups on netcore

---

mono/metadata/icall-eventpipe.c

!! This PR is a copy of dotnet/runtime#39205,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Delegate callback can be held in native event pipe provider instance and called multiple times during provider lifetime (enable/disable sessions). Store a weak GC reference to delegate to correctly handle case where delegate gets moved by GC. It should not be collected since delegate should be held alive by managed event pipe class.

Keep weak gc handle for EventPipe delegate callback in provider.

---

configure.ac
mono/metadata/Makefile.am

!! This PR is a copy of dotnet/runtime#37971,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[netcore] ICU integration

---

mcs/tools/wasm-tuner/PInvokeTableGenerator.cs

Fixes https://github.com/mono/mono/issues/20123.

[wasm] Fix handling of enum types in the pinvoke generator.

---

configure.ac
mono/metadata/icall-eventpipe.c
mono/mini/mini-runtime.c

!! This PR is a copy of dotnet/runtime#38991,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Add a --enable-minimal=eventpipe configure option. Disable eventpipe on wasm.

---

mono/metadata/custom-attrs.c

!! This PR is a copy of dotnet/runtime#39774,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Hopefully helps with https://github.com/dotnet/runtime/issues/39473.

[runtime] Make sure newly created objects are pinned during a runtime invoke in create_cattr_typed/named_arg ().

---

mono/metadata/custom-attrs.c
mono/metadata/handle.h

!! This PR is a copy of dotnet/runtime#39856,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[runtime] Fix some more gc tracking problems in create_cattr_named/typed_arg.

---

mono/mini/intrinsics.c

!! This PR is a copy of dotnet/runtime#39965,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Part of https://github.com/dotnet/runtime/issues/38718.

[jit] Add a intrinsic for ThrowForUnsupportedVectorBaseType<T>.

---

mono/metadata/mono-config.c
mono/mini/debugger-agent.c

!! This PR is a copy of dotnet/runtime#39997,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This commit brings us back to zero warnings for the default build configuration.

[mono] Fix warnings on OSX netcore

---

mono/mini/debugger-agent-stubs.c
mono/mini/debugger-agent.c
mono/mini/debugger-agent.h
mono/mini/mini-exceptions.c
mono/mini/mini-runtime.c

This reverts commit 60643c36f5d4e349276e5dcce0e7fc3dc1d72f74.
To investigate error on android tests.

[debugger] Revert Removing unhandled_exception which was used for android

---

winconfig.h

!! This PR is a copy of dotnet/runtime#40005,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This was already disabled with autotools, but I forgot to update winconfig.h as well.

[mono] Disable cfgdir config on Windows netcore builds

---

mono/mini/interp/interp.c
mono/mini/interp/mintops.def
mono/mini/interp/transform.c

!! This PR is a copy of dotnet/runtime#39920,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>it's used under the hood in String, Span, Memory, etc.
It's also a public API now.

[mono][interp] Intrinsify MemoryMarshal.GetArrayDataReference

---

mono/metadata/object.c

!! This PR is a copy of dotnet/runtime#40071,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/39380.

[runtime] Handle null byref returns in runtime invokes.

---

mono/metadata/object-offsets.h
mono/mini/exceptions-amd64.c
mono/mini/exceptions-x86.c
mono/mini/mini-runtime.c
mono/mini/tasklets.c
mono/mini/tasklets.h

!! This PR is a copy of dotnet/runtime#40324,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Tasklets were an old mono-specific extension for continuations that is no longer relevant.

Mono: Ensure tasklets are removed in netcore build

---

mono/metadata/handle.h
mono/mini/mini-exceptions.c

!! This PR is a copy of dotnet/runtime#40384,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[wasm] Fix GC support in ves_icall_get_trace ().

---

mono/mini/interp/transform.c

!! This PR is a copy of dotnet/runtime#40017,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Common in generics, simple example:
```csharp
static int ToInt<T>(T t) => (int)(object)t;
```
`MONO_VERBOSE_METHOD=ToInt`:
```
Runtime method: Repro:ToInt<int> (int) 0x7ffee273b6d0
Locals size 8, VT stack size: 0
Calculated stack size: 1, stated size: 8
IR_0000: ldloc.i4   0
IR_0002: box        0,0
IR_0005: unbox      1
IR_0007: ldind.i4.check
IR_0008: ret
```
```
Runtime method: Repro:ToInt<int> …
```

[mono][interp] Optimize box+unbox to no-op

---

mono/mini/mini-wasm-debugger.c
sdks/wasm/src/library_mono.js

!! This PR is a copy of dotnet/runtime#40480,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Based on https://github.com/mono/mono/pull/20142

[wasm] [debugger] Support Exception Break on Debugger (handled and unhandled)

---

mono/mini/mini-wasm-debugger.c

!! This PR is a copy of dotnet/runtime#40548,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>- this allows IDEs to let users invoke property getters for ValueTypes

[wasm][debugger] Add support for invoking getters on ValueTypes

---

mono/metadata/reflection.c

!! This PR is a copy of dotnet/runtime#40326,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Resolves https://github.com/dotnet/runtime/issues/30714

Type.IsAssignableTo

---

mono/metadata/object.c

!! This PR is a copy of dotnet/runtime#40614,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[coop] Use handles for mono_runtime_try_invoke_array

---

mono/mini/interp/interp-internals.h
mono/mini/interp/interp.c

!! This PR is a copy of dotnet/runtime#40710,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[interp] Rework OBJREF and fix a GC issue

---

mono/metadata/native-library.c
mono/mini/CMakeLists.txt

!! This PR is a copy of dotnet/runtime#40811,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[runtime] Update cmake build.

---

mono/metadata/assembly.c

!! This PR is a copy of dotnet/runtime#40845,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>cc: @thaystg

[mono] Make bundle filename changes netcore-only

---

mono/metadata/appdomain.c
mono/metadata/assembly.c

!! This PR is a copy of dotnet/runtime#40819,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>See individual commits and description.

[mono] Loader improvements: bundle optimization and logging

---

mono/metadata/native-library.c

!! This PR is a copy of dotnet/runtime#41228,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Similar logging was added to the managed loading algorithm when it proved extremely useful for debugging a Blazor crash, so the equivalent is probably useful for the unmanaged library algorithm as well

[mono] Add more detailed logs for the PInvoke resolution process

---

mono/metadata/assembly-load-context.c
mono/metadata/assembly.c
mono/metadata/metadata-internals.h

!! This PR is a copy of dotnet/runtime#41342,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Needed for unloadability

[mono] Add mono_assembly_decref, return value on both decref and addref

---

sdks/wasm/BrowserDebugHost/Program.cs
sdks/wasm/BrowserDebugProxy/DevToolsHelper.cs
sdks/wasm/BrowserDebugProxy/DevToolsProxy.cs
sdks/wasm/BrowserDebugProxy/EvaluateExpression.cs
sdks/wasm/BrowserDebugProxy/MemberReferenceResolver.cs
sdks/wasm/BrowserDebugProxy/MonoProxy.cs
sdks/wasm/DebuggerTestSuite/EvaluateOnCallFrameTests.cs
sdks/wasm/DebuggerTestSuite/Support.cs
sdks/wasm/other.js
sdks/wasm/src/library_mono.js
sdks/wasm/tests/debugger/debugger-evaluate-test.cs
sdks/wasm/tests/debugger/debugger-valuetypes-test.cs

Merge dotnet/runtime to mono/mono.

[wasm][debugger] Merge dotnet/runtime to mono/mono

---

mono/metadata/filewatcher.c
mono/metadata/w32file.c
mono/metadata/w32process-unix-default.c
mono/mini/CMakeLists.txt
mono/utils/mono-dl-wasm.c
mono/utils/mono-threads-wasm.c

!! This PR is a copy of dotnet/runtime#41316,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Not enabled by default. Ninja is used for building if available, else we fall
back to make.

Add support for using cmake in the mono runtime build.

---

mono/mini/main.c

Issue18826 fix

---

mono/mini/mini-runtime.c

!! This PR is a copy of dotnet/runtime#41510,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/41470.

[runtime] Fix signature of mini_cleanup ().

---

mono/mini/interp/mintops.h
mono/mini/interp/transform.c

If we know the values of the arguments of a conditional branch, replace it with an unconditional branch. Once we have support for basic blocks, we can remove dead basic blocks and merge any adjacent ones.

[interp] Optimize out conditional branches

---

mono/mini/CMakeLists.txt
mono/tools/offsets-tool/offsets-tool.py

!! This PR is a copy of dotnet/runtime#41710,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Add ios support to the cmake build system.

---

mcs/class/corlib/System/TimeZoneInfo.Android.cs

**NOTE: please backport the fix to the 2020-02 branch, thanks!**
Context: https://source.android.com/devices/architecture/modular-system/runtime#time-zone-data-interactions
Context: https://source.android.com/devices/tech/config/timezone-rules#timezone-apex
Context: https://android.googlesource.com/platform/frameworks/base/+/a1ae02519d6fb5de636fc8728dec7cb9b14de356
Maybe helps with: https://github.com/xamarin/xamarin-android/issues/5080
Add support to read ICANN timezone data from two new locations found on
devices running Android 10+.  The data in the previously searched
location still exists but it's most likely out of date.
On Android 10+ tzdata updates will be derived via an APEX TimeData
package update, whose data directory this commit sets as the first
location to be searched.
This …

[Android] Enable access to up-to-date tzdata on Android 10+

---

mono/mini/CMakeLists.txt
mono/profiler/CMakeLists.txt

!! This PR is a copy of dotnet/runtime#41860,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Add x86/arm64/arm support to the cmake build. Fix issues.

---

mono/mini/mini-wasm-debugger.c

!! This PR is a copy of dotnet/runtime#41480,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>- surface inherited fields, and properties
- we try to support `Runtime.getProperties`'s two arguments:
- `ownProperties`, and `accessorsOnly`
- `ownProperties`: for JS, this means return only the object's own
members (not inherited ones)
- `accessorsOnly`: for JS, this means return all the getters
Actual implementation:
- In practice, VSCode, and Chrome debugger seem to only send
`{ …

[wasm][debugger] Add support for surfacing inherited members

---

mono/mini/mini-wasm-debugger.c

!! This PR is a copy of dotnet/runtime#41559,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Return the value, or null.
Fixes mono/mono#20310

[wasm][debugger] Add support for Nullable<T> 

---

mono/mini/mini-wasm-debugger.c

!! This PR is a copy of dotnet/runtime#41713,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Try to fail gracefully when we come across some variable/value that we can't describe (yet!)

[wasm][debugger] Small improvements to fail gracefully

---

mono/mini/main.c

Fixes #18826
Backport of #19580.
/cc @CoffeeFlux @HinTak

[2020-02] Issue18826 fix

---

mono/mini/CMakeLists.txt

!! This PR is a copy of dotnet/runtime#42095,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Remove some accidental duplicates from mini/CMakeLists.txt.

---

mono/metadata/boehm-gc.c
mono/metadata/mono-gc.h
mono/metadata/null-gc.c
mono/metadata/sgen-mono.c

It's sometimes useful to have a way for the runtime to stop the world.  Only works on SGen.

[gc] add stop-the-world api

---

llvm/build.mk

Fixes #19784
Backport of #19798.
/cc @lambdageek @andy-noisyduck

[2020-02] Added hard limit to sub-make jobs. Fixes #19784

---

mono/mini/debugger-agent.c
mono/mini/debugger-engine.c
mono/mini/debugger-engine.h
mono/mini/mini-wasm-debugger.c

!! This PR is a copy of dotnet/runtime#42227,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Moving some functions from debugger-agent to debugger-engine to be used from mini-wasm-debugger.

[wasm][debugger] Fix assert when calling set_set_notification_for_wait_completion_flag

---

configure.ac
mono/utils/mono-time.c

!! This PR is a copy of dotnet/runtime#42206,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes mono/mono wasm build
cc: @vargaz

[mono] Add proper check for clock_gettime

---

mono/mini/CMakeLists.txt
mono/mini/simd-intrinsics-netcore.c

!! This PR is a copy of dotnet/runtime#42182,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>* Fix indentation.
* Add linux support.
* Add tvos support.
* Use clang only options only with clang.
* Add check for iconv.

Ongoing cmake build work.

---

mono/metadata/debug-mono-ppdb.c
mono/metadata/debug-mono-ppdb.h
mono/mini/mini-wasm-debugger.c

!! This PR is a copy of dotnet/runtime#42255,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Support loading assemblies and symbols into debugger via callback

---

mono/mini/debugger-agent.c
mono/mini/debugger-engine.c
mono/mini/debugger-engine.h
mono/mini/mini-wasm-debugger.c

!! This PR is a copy of dotnet/runtime#42299,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Adding the test I realized that I need to move one more function.

[wasm] [debugger] Adding test for #42227 PR

---

mono/mini/mini-llvm.c

!! This PR is a copy of dotnet/runtime#42648,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>The `mask` parameter to `shufflevector` must be a vector of `i32`s; we
were mistakenly using a vector of `i8`s previously.
`extractelement` requires that supplied index is smaller than the source
vector's length. The underlying instructions only pay attention to the
lower bits of the index, so replicate this behavior manually with
masking at the LLVM IR level.
This change makes …

[mono] Fix LLVM IR emission for Ssse3.AlignRight and Sse2/Sse41.Extract

---

mono/metadata/CMakeLists.txt
mono/metadata/icall.c
mono/mini/CMakeLists.txt

!! This PR is a copy of dotnet/runtime#42647,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>* Fix some warnings.
* Avoid creating netcore/config.make.
* Fix CPU_COUNT test.
* Add missing source file.

Ongoing work on the cmake build.

---

mono/utils/Makefile.am

Fixes https://github.com/mono/mono/issues/20482

Add w32subset.h into monoutils_sources.

---

mono/mini/debugger-agent.c

If the runtime gets a single step or breakpoint signal while it is already
running native code for a P/Invoke, it will be in GC Safe mode.  Switch back to
GC Unsafe to run the debugger engine steps.
Addresses https://github.com/mono/mono/issues/20490

[debugger] Switch to GC Unsafe in signal handler callbacks

---

mono/mini/mini-llvm.c
mono/mini/mini-ops.h
mono/mini/simd-intrinsics-netcore.c

!! This PR is a copy of dotnet/runtime#43647,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[llvm] Fix some simd issues.

---

mono/mini/mini-runtime.c
mono/mini/mini.c

!! This PR is a copy of dotnet/runtime#43808,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Disable JIT counters if the JIT is disabled.

---

mono/tools/offsets-tool/offsets-tool.py

!! This PR is a copy of dotnet/runtime#41751,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Build Mono with LLVM AOT on arm64 Linux.
Run CoreCLR runtime tests on arm64 Linux with Mono + LLVM AOT.

CoreCLR runtime tests + Mono LLVM AOT on arm64 Linux

---

mono/metadata/image.c

!! This PR is a copy of dotnet/runtime#44022,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Disable the 'problematic assembly' code on .net core.

---

mono/mini/interp-stubs.c
mono/mini/interp/transform.c

!! This PR is a copy of dotnet/runtime#44024,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
Also fix mono/mono "Linux x64 Checked Private Types Build" breakage in interp

[checked-build] Fix interp build breakage

---

mono/mini/debugger-agent.c
mono/mini/debugger-engine.c
mono/mini/debugger-engine.h
mono/mini/mini-wasm-debugger.c

!! This PR is a copy of dotnet/runtime#43960,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Clean up debugger debug logging and wasm trace logging

---

mono/mini/interp/interp-internals.h
mono/mini/interp/interp.c
mono/mini/interp/transform.c

!! This PR is a copy of dotnet/runtime#44188,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Otherwise we can assert when attempting to use the error.

[interp] Reinitialize error in a few places

---

mono/mini/interp/transform.c

!! This PR is a copy of dotnet/runtime#44217,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Generate also better code.

[interp] Simplify GetRawData

---

mono/mini/mini-wasm-debugger.c
mono/mini/mini-wasm.h

!! This PR is a copy of dotnet/runtime#44305,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes dotnet/runtime#44210

[wasm][debugger] Implementing support to Debugger::Break.

---

mono/metadata/threads.c

!! This PR is a copy of dotnet/runtime#44124,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>It's not needed by the runtime and the tests should not penalize everyone

Remove all ThreadStartException ctors from descriptor

---

mono/mini/aot-compiler.c

!! This PR is a copy of dotnet/runtime#44783,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/44779.

Fix full-aot support for unmanaged function pointers.

---

mono/metadata/custom-attrs.c
mono/mini/aot-compiler.c
mono/mini/driver.c

!! This PR is a copy of dotnet/runtime#44809,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/44803.

Add AOT support for the EntryPoint property for UnmanagedCallersOnly.

---

mono/mini/method-to-ir.c

!! This PR is a copy of dotnet/runtime#45076,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/44269.

Add support for stack walks on wasm for the reflection methods which need them.

---

mono/mini/interp/interp.c

!! This PR is a copy of dotnet/runtime#45271,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/44270.

Fix stack size allocation during interpreter entry.

---

mono/metadata/mono-config.c
mono/utils/mono-sigcontext.h

!! This PR is a copy of dotnet/runtime#45434,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Also contains initial work to support arm/arm64 builds but those don't build yet.

netcore: Add Mono Windows x86 builds

---

mono/metadata/native-library-qcall.c
mono/metadata/native-library.c
mono/metadata/qcall-def.h

!! This PR is a copy of dotnet/runtime#44505,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

netcore: Static linking of native libs

---

mono/metadata/icall.c

!! This PR is a copy of dotnet/runtime#45761,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Find&Replace coreclr/src -> coreclr

---

mono/mini/aot-compiler.c
mono/mini/aot-runtime.c

!! This PR is a copy of dotnet/runtime#45616,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/45548.

Add support for MONO_TYPE_FNPTR to aot.

---

mono/metadata/native-library.c

!! This PR is a copy of dotnet/runtime#45713,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Superhost PR follow-up
Re: https://github.com/dotnet/runtime/pull/44505#discussion_r535708070
For the most part a search/replace change.

renaming `clrcompression` --> `System.IO.Compression.Native`

---

mono/metadata/marshal-ilgen.c
mono/tests/safehandle.2.cs

!! This PR is a copy of dotnet/runtime#45930,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>paramterless => parameterless
Polymorhic => Polymorphic

Fix a few spelling mistakes

---

configure.ac
mono/Makefile.am
mono/metadata/Makefile.am
mono/mini/Makefile.am.in

!! This PR is a copy of dotnet/runtime#46065,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Remove eventpipe from old Mono makefile build.

---

mono/metadata/class-init.c
mono/metadata/object.c
mono/mini/interp/transform.c
mono/tests/Makefile.am
mono/tests/struct-static.cs

Fixes https://github.com/mono/mono/issues/20650

[metadata] If a static field fails while computing size, fail the class

---

mono/eventpipe/Makefile

Remove empty EventPipe Makefile.

---

mono/metadata/appdomain.c
mono/metadata/class-internals.h
mono/metadata/domain-internals.h
mono/metadata/domain.c
mono/metadata/object-internals.h
mono/mini/mini-runtime.c

!! This PR is a copy of dotnet/runtime#46346,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Use a `System.Object` instance as a managed sentinel for the root domain

Remove Mono.MonoDomain managed class

---

mono/metadata/appdomain.c
mono/metadata/assembly-load-context.c
mono/metadata/class-internals.h
mono/metadata/domain.c
mono/metadata/icall.c
mono/metadata/native-library.c
mono/metadata/object-internals.h
mono/metadata/object.c

!! This PR is a copy of dotnet/runtime#46323,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Clean up managed dependencies for Mono's domain/loader context

---

mono/metadata/jit-info.c
mono/mini/aot-runtime.c

[wasm] Handle the case when emscripten interleaves methods from multiple AOT images.

---

mono/mini/Makefile.am.in

Fix building interp-whitebox test.

---

mono/metadata/class-init.c

!! This PR is a copy of dotnet/runtime#46533,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Fix array interface generation if both IList and IReadOnlyList are linked out.

---

mono/metadata/icall-def-netcore.h

!! This PR is a copy of dotnet/runtime#46443,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[mono] Fix DISABLE_REFLECTION_EMIT on netcore

---

mono/metadata/native-library.c
mono/metadata/native-library.h
mono/mini/monovm.c

!! This PR is a copy of dotnet/runtime#46442,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

[mono] Add support for PINVOKE_OVERRIDE

---

mono/metadata/domain.c
mono/metadata/object-internals.h
mono/metadata/object.c
mono/metadata/threads.c

!! This PR is a copy of dotnet/runtime#46691,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Remove System.Runtime.Remoting.Contexts.Context, its not used anymore on netcore.

---

mono/mini/mini-runtime.c

!! This PR is a copy of dotnet/runtime#46735,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Fix void returns in llvmonly runtime invokes.

---

mono/mini/aot-compiler.c

!! This PR is a copy of dotnet/runtime#46781,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/46746.

Fix the allocation of the acfg->cfgs array, it would have an incorrect size when using profiled AOT.

---

mono/metadata/native-library.c

!! This PR is a copy of dotnet/runtime#46917,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Follow up change missing in dotnet/runtime#46323
Fixes dotnet/runtime#46908

Don't assume presence of MonoResolveUnmanagedDllUsingEvent method

---

configure.ac
mono/utils/mono-merp.c

fix merp arm64

---

mono/mini/aot-compiler.c
mono/mini/aot-runtime.c
mono/mini/mini-llvm.c

[wasm] Emit some wrappers with linkonce linkage.

---

man/mkbundle.1
mcs/tools/mkbundle/mkbundle.cs

This PR adds support for the hybrid AOT mode in mkbundle

mkbundle: add support for hybrid aot

---

mono/mini/interp/transform.c

!! This PR is a copy of dotnet/runtime#47505,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>- use prepend instead of append
`g_list_append` has to repeatedly traverse the list using `g_list_last` to find the last element.
Instead use `g_list_prepend` to add the new bb to the front of the list and then reverse at the end (`g_list_reverse` is inplace and doesn't allocate)
- don't make the list at all unless it's needed.
it's only needed when generating sequence points.

[interp] basic_blocks list improvements

---

mono/mini/tramp-arm.c
mono/mini/tramp-ppc.c

!! This PR is a copy of dotnet/runtime#47576,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Same as https://github.com/dotnet/runtime/pull/47417

Fix a warning in mono/mini/tramp-arm.c and tramp-ppc.c

---

mono/metadata/icall-eventpipe.c

!! This PR is a copy of dotnet/runtime#47629,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>

Add support for EventPipe stackwalks and method formatting on Mono.

---

mono/metadata/metadata-internals.h
mono/metadata/metadata-update.c
mono/metadata/metadata.c

!! This PR is a copy of dotnet/runtime#47716,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Use it to take the slow path in metadata lookups when there's at least one delta applied.

[mbr] Add a global has_updates flag

---

mono/arch/arm64/arm64-codegen.h
mono/metadata/threads.c
mono/mini/aot-compiler.c
mono/mini/aot-runtime.c
mono/mini/debugger-agent.c
mono/mini/driver.c
mono/mini/exceptions-arm64.c
mono/mini/image-writer.c
mono/mini/interp/interp.c
mono/mini/mini-arm64.c
mono/mini/mini-arm64.h
mono/mini/mini-exceptions.c
mono/mini/mini-generic-sharing.c
mono/mini/mini-posix.c
mono/mini/mini-runtime.c
mono/mini/mini-runtime.h
mono/mini/mini-trampolines.c
mono/mini/mini.c
mono/mini/mini.h
mono/mini/tramp-arm64-gsharedvt.c
mono/mini/tramp-arm64.c
mono/utils/Makefile.am
mono/utils/ftnptr.h
mono/utils/mach-support-arm64.c
mono/utils/mono-context.c
mono/utils/mono-sigcontext.h
mono/utils/mono-state.c

- Fix the c++ build.
- Remove some unused prototypes.
- Initial arm64e support.

Initial arm64e support

---

.config/CredScanSuppressions.json

All of the flagged instances are harmless

Add CredScan suppression file

---

mcs/class/System.Drawing/System.Drawing.Imaging/Metafile.cs
mcs/class/System.Drawing/System.Drawing/Graphics.cs

Backport of https://github.com/mono/mono/pull/20827

[2020-02][System.Drawing] Work around libgdiplus Metafile dispose ordering

---

mono/metadata/w32process-unix.c

Fixes https://github.com/mono/mono/issues/17204
Fixes https://github.com/mono/mono/issues/19836

Fix early return in Process.Start

---

mono/metadata/w32process-unix.c

Fixes https://github.com/mono/mono/issues/17204
Fixes https://github.com/mono/mono/issues/19836
Backport of #20821.

[2020-02] Fix early return in Process.Start

---

NuGet.config

This pull request updates the usage of NuGet.org in cases where it is used in conjunction with other feeds.
Generally yes. If the target branch is no longer in use and will not need to be built in the future, please close this PR.
If packages are missing, please tag 'dotnet/dnceng' or 'mmitche' on this PR and note the missing packages.
If there are other unexpected failures, please contact 'dotnet/dnceng'.

[master] Fixup feeds

---

mcs/class/System/Test/System.Net.Sockets/UdpClientTest.cs
mcs/class/System/Test/System.Net/DnsTest.cs
scripts/ci/mono-ci-job-template.yml
scripts/ci/mono-ci.yml

Try adding an ARM64 lane, running on docker in a private pool

---

mcs/Makefile
mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/ModuleMirror.cs
mono/mini/debugger-agent.c

Add ApplyChanges command to Mono.Debugger.Soft
Related mono/debugger-libs PR https://github.com/mono/debugger-libs/pull/342
Related dotnet/runtime PR https://github.com/dotnet/runtime/pull/49043
Contributes to https://github.com/dotnet/runtime/issues/44806

[sdb] Add Module.ApplyChanges

---

.config/CredScanSuppressions.json
mcs/class/Mono.Security/Test/Mono.Security.Cryptography/CryptoConvertTest.cs

Another CredScan suppression

---

man/sqlsharp.1
mcs/class/System.Configuration/Test/System.Configuration/ConfigurationManagerTest.cs
mcs/class/System.Configuration/Test/test-config-file
mcs/class/System.Data.Linq/examples/DbLinq.Ora.Example/Program.cs
mcs/class/System.Data.Linq/examples/DbLinq.Pgsql.Example/PgAndrusClient.cs
mcs/class/System.Data.Linq/examples/DbLinq.Pgsql.Example/ProgramPg.cs
mcs/class/System.Data.OracleClient/Test/TestOracleClient.cs
mcs/class/System.Data.OracleClient/Test/refcursortest.cs
mcs/class/System.Data.OracleClient/Test/testblob.cs
mcs/class/System.Data.OracleClient/Test/testclob.cs
mcs/tools/sqlmetal/src/Build Northwind.bat
mcs/tools/sqlmetal/src/DbLinq/Test/Providers/ReadTest_AllTypes_MySql.cs
mcs/tools/sqlmetal/src/DbMetal/AllTypes to Cs.txt
mcs/tools/sqlmetal/src/DbMetal/DB to Cs.txt
mcs/tools/sqlmetal/src/DbMetal/DB to DBML.txt
mcs/tools/sqlmetal/tests/ConnectionStrings.xml
mcs/tools/sqlsharp/README

Update password - CredScan issues

---

data/net_1_1/machine.config
data/net_2_0/web.config
data/net_4_0/web.config
data/net_4_5/web.config
mcs/class/System.Data/Test/ProviderTests/System.Data.OleDb.jvm/OleDbCommand/OleDbCommand_Dispose.cs

Remove commented out lines of code which had a hardcoded password flagged by the CredScan tool (line 86)
Updated some config files to remove commented line of code containing a test password

CredScan issue - remove hardcoded password

---

mcs/class/System.XML/Documentation/en/System.Xml/XmlUrlResolver.xml

Replacing passwords with placeholders.
I don't think the webassembly failure is related.

[CREDSCAN] Replaced passwords with placeholder.

---

mcs/class/Mono.Http/samples/auth.xml
mcs/class/System.Data/Test/ProviderTests/System.Data.OleDb.jvm/OleDbCommand/OleDbCommand_ExecuteReader.cs
mcs/class/System.Data/Test/ProviderTests/app-net_1_1.config
mcs/class/System.Data/Test/ProviderTests/app-net_2_0.config

Replace passwords with PLACEHOLDER
Addresses the following credscan bugs:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1100566
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1100568
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1100600
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1100494

[CREDSCAN] Replaced password with placeholder

---

mcs/class/referencesource/System/net/System/Net/_FtpControlStream.cs

Replacing password with place holder for this credscan issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1100507/?triage=true

[CREDSCAN] Replace password with [PLACEHOLDER]

---

.config/CredScanSuppressions.json

Removing entries for which we already have the issue fixed via certain PRs last week and also for issues with exception details for files in this list

Update CredScanSuppressions.json file

---

mcs/class/System.Configuration/Test/appSettings.config

Added XML comment for credscan suppression.
Cred scan issue is here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1100673

[CredScan] Added suppression for cred scan

---

data/net_2_0/machine.jvm.config
mcs/class/System.Web/Documentation/en/System.Web.UI.WebControls/CreateUserWizard.xml

Adding suppressions to approved exceptions

Suppress CredScan checking

---

mcs/class/Mono.ServiceModel.IdentitySelectors/Test/resources/rupert.xml
mcs/class/System.Data/Test/ProviderTests/System.Data.OleDb.jvm/readme.txt

Add credscan supressions for the following issues with approved exceptions:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1101001
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1100465

[CredScan] Added credscan supressions

---

mcs/class/System.Data/Test/ProviderTests/System.Data.SqlClient/SqlConnectionTest.cs
mcs/class/System.Data/Test/System.Data.Common/DbConnectionStringBuilderTest.cs
mcs/class/System.IdentityModel/Test/System.IdentityModel.Tokens/BootstrapContextTest.cs
mcs/class/System.XML/Test/System.Xml.Serialization/XmlSerializerTests.cs
mcs/class/referencesource/System.Web/Configuration/ProcessModelSection.cs

Adding suppressions to approved exceptions

Suppress more CredScan checking

---

mcs/class/System.Web/Test/standalone/MD5PasswordAuth_Bug601727/Web.config

Add suppression for approved credscan exception.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1100607/

[Credscan] Added supression comment in Web.Config

---

mcs/class/corlib/Test/System/StringTest.cs
mcs/class/corlib/corefx/CompareInfo.cs

https://github.com/mono/mono/issues/20948

Fix the System.String.Replace throwing NotImplementedException

---

mcs/class/referencesource/System/net/System/Net/FtpWebRequest.cs

Suppress FTP anonymous credentials

---

mono/mini/cpu-arm.md
mono/mini/cpu-arm64.md
mono/mini/interp/transform.c
mono/mini/mini-arm.c
mono/mini/mini-arm64.c

Backport of the same fixes from dotnet/runtime

Fix r4_conv_to_i

---

mono/mini/cpu-arm.md
mono/mini/cpu-arm64.md
mono/mini/interp/transform.c
mono/mini/mini-arm.c
mono/mini/mini-arm64.c

https://github.com/mono/mono/pull/20985
Fixes #20775

[2020-02] Backport r4-conv-i fixes

---

mono/mini/exceptions-s390x.c
mono/mini/method-to-ir.c
mono/mini/mini-s390x.c
mono/mini/tramp-s390x.c
mono/mini/unwind.c

Recent fixes from dotnet/runtime for s390x
- Tailcall 
- Array construction
- Unwinding

Import s390x fixes from dotnet runtime

---

mono/mini/local-propagation.c

Signed-off-by: Zhenbo Li litimetal@gmail.com

Fix implicit conversion warning

---

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridView.cs

This pull request fixes the following issue. Let's go to edit mode of some cell from a `DataGridView` control. Then appeared text box will keep its locations if one scroll the grid.

[WinForms] DataGridView: Update editing control position on scroll

---

mono/mini/interp/transform.c

https://github.com/dotnet/runtime/pull/52632/

[debugger][interpreter] Generate seq_points even when doesn't have debug information

---

packaging/MacSDK/msbuild.py

PR for main - https://github.com/mono/mono/pull/21083

[2020-02][MSBuild] Update to vs16.10 branch

---

packaging/MacSDK/msbuild.py

[MSBuild] Update to vs16.10 branch

---

mono/mini/mini-generic-sharing.c

Fix memory leak during data registration

---

mono/mini/mini-generic-sharing.c

[2020-02] Fix memory leak during data registration (#21107)

---

mono/mini/cpu-s390x.md
mono/mini/mini-s390x.c

Missed this float32 instruction: OP_RMOVE

---

support/serial.c

Fix pseudo-ttys for kernel versions >= 5.13

---

mcs/class/referencesource/mscorlib/system/io/binaryreader.cs

The previous implementation created a temporary array and threw the
result away before copying back to the Span.
This commit brings a similar implementation to what is in dotnet/runtime
repo.

Fix BinaryReader Read to Span of byte and char

---

mono/mini/interp/transform.c

These structures are valuetypes, but their mint_type is a primitive. This means that a LDFLD applied on the type would have attempted to do a pointer dereference, because it saw that the current top of stack is not STACK_TYPE_VT. This was fixed in the past by passing the managed pointer to the valuetype rather than the valuetype itself, against the normal call convention, which lead to inconsistencies in the code.
This commit removes that hack and fixes the problem by ignoring LDFLD applied to nint/nfloat valuetypes in the first place.
Backport of https://github.com/mono/mono/pull/21382

[2020-02][interp] Remove hack for nint/nfloat

---

mono/mini/debugger-agent.c
mono/mini/mini-runtime.c

Backport https://github.com/dotnet/runtime/pull/71436

[debugger] Fix debugging on Mac and iOS

---

mono/mini/method-to-ir.c

Fixes https://github.com/dotnet/runtime/issues/72181

Backporting https://github.com/dotnet/runtime/pull/59861

---

scripts/ci/mono-ci-job-template.yml

The old ones are getting deprecated.

[ci] Update to new macOS and Ubuntu AzDO images

---

mono/metadata/assembly.c

* Backport https://github.com/dotnet/runtime/pull/76665

Fix incorrect version comparison in loader

---

configure.ac
mono/metadata/w32process-unix-osx.c
mono/utils/mono-threads-mach-helper.c

Fixes https://github.com/mono/mono/issues/21567

Fix build on macOS 13 / Xcode 14

---

mcs/class/WindowsBase/System.IO.Packaging/Package.cs

[WindowsBase] System.IO.Packaging.Package.Open truncate on FileMode.Create
