mono/mini/mini-arm.c
Revert 257efc6374cbffb95d83dc9257b432d6ae3d80f6
and provide something much closer to what it was based on.
There have been many variations of this.
My original slightly bigger fix that adds a small optimization:
https://github.com/mono/mono/pull/12070
My original bigger fix with even more optimization:
https://github.com/mono/mono/pull/12079 
The broken fix that was merged:
https://github.com/mono/mono/pull/12701
A current bigger fix:
https://github.com/mono/mono/pull/14178 
This PR is a revert of #12701 and then closely resembles #12070, but the small optimization is removed, and the semantically same thing is stated with an attempt at increased clarity and more const and slightly less change.
This should help or fix https://github.com/mono/mono/issues/14103.
The basic problem with …
=> Fix arm32 tailcall_reg/tailcall_membase.

mcs/class/System.Private.CoreLib/Makefile, netcore/Makefile
```
17:34:54 make[2]: Entering directory '/mnt/jenkins/workspace/build-source-tarball-mono/netcore'
17:34:54 
make[2]: *** No rule to make target 'distdir'.  Stop.
```
=> [netcore] Fix `make dist` following https://github.com/mono/mono/pull/14167

netcore/Makefile
`nuget pack runtime.nuspec -properties VERSION=6.3.0.208\;RID=linux-x64\;PLATFORM_AOT_SUFFIX=.so\;COREARCH=x64`
=> [netcore] Smarter version numbering of nupkg

sdks/wasm/Makefile
This change restores the ability to build wasm AOT apps outside the mono source tree.
=> [Wasm] Add missing pinvoke-tables-default.h from build artifacts

Makefile.am, configure.ac, mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj, mcs/class/System.Private.CoreLib/System.Reflection/CustomAttributeNamedArgument.cs, mcs/class/System.Private.CoreLib/System.Reflection/CustomAttributeTypedArgument.cs, mcs/class/System.Private.CoreLib/System.Reflection/MissingMetadataException.cs, mono/Makefile.am
This change:
* avoids updating submodules during autogen, if `--with-core=only`
* avoids updating submodules during make, if `--with-core=only`
* Bundles in 3 small files from corert with System.Private.CoreLib, to avoid the need for the corert submodule
This enables us to build on the internal project without needing to mirror or mangle submodules at all, which is proving difficult (and it should also speed builds up)
=> [netcore] Avoid needing any submodules to build `--with-core=only`

mono/mini/mini-arm.c
Revert 257efc6374cbffb95d83dc9257b432d6ae3d80f6
and provide something much closer to what it was based on.
There have been many variations of this.
My original slightly bigger fix that adds a small optimization:
https://github.com/mono/mono/pull/12070
My original bigger fix with even more optimization:
https://github.com/mono/mono/pull/12079 
The broken fix that was merged:
https://github.com/mono/mono/pull/12701
A current bigger fix:
https://github.com/mono/mono/pull/14178 
This PR is a revert of #12701 and then closely resembles #12070, but the small optimization is removed, and the semantically same thing is stated with an attempt at increased clarity and more const and slightly less change.
This should help or fix https://github.com/mono/mono/issues/14103.
The basic problem with …
=> [2019-02] Fix arm32 tailcall_reg/tailcall_membase.

mono/mini/mini-arm.c
Revert 257efc6374cbffb95d83dc9257b432d6ae3d80f6
and provide something much closer to what it was based on.
There have been many variations of this.
My original slightly bigger fix that adds a small optimization:
https://github.com/mono/mono/pull/12070
My original bigger fix with even more optimization:
https://github.com/mono/mono/pull/12079 
The broken fix that was merged:
https://github.com/mono/mono/pull/12701
A current bigger fix:
https://github.com/mono/mono/pull/14178 
This PR is a revert of #12701 and then closely resembles #12070, but the small optimization is removed, and the semantically same thing is stated with an attempt at increased clarity and more const and slightly less change.
This should help or fix https://github.com/mono/mono/issues/14103.
The basic problem with …
=> [2019-04] Fix arm32 tailcall_reg/tailcall_membase.

mono/mini/builtin-types.cs, mono/mini/interp/transform.c
Fixes https://github.com/xamarin/xamarin-macios/issues/5809
/cc @spouliot 
Backport of #14201.
/cc @lewurm
=> [2019-02] [interp] fix op_explicit for cast from nfloat to nint and vice versa

mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
This method returns a function pointer that can be called with a calli instruction. On interpreter we use a pointer to InterpMethod while on jit we use the native code address. Normally, GetFunctionPointer should return the InterpMethod pointer if called from interp or the native code address if called from jit. Since we don't have any information about the execution engine of the caller, we solve this by intrinsifying all these calls, that happen in the interpreter.
Passing such function pointers between jitted and interp code is probably still unreliable.
Fixes https://github.com/mono/mono/issues/13654
=> [2019-04] [interp] Fix GetFunctionPointer

sdks/wasm/binding_support.js, sdks/wasm/framework/src/WebAssembly.Bindings/Runtime.cs
Implement suggestion by Katelyn Gadd to use Symbol instead of a Map or WeakMap.
- Attach a special named Symbol for `wasm type` to the prototype property for the Core objects that we have bound.
- The Managed Type is stored in the Symbol property that will be passed to the managed side.
- Move the supported Core object identification into javascript.
- Runtime: the core object type is now passed into the Runtime from javascript binding support instead of being housed in managed code.
- Remove the use of tostring to identify the object type.
=> [wasm][bindings] Refactor WebAssembly.Core object instantiation.

mono/sgen/sgen-marksweep.c, mono/utils/monobitset.c
Don't use popcount intrinsic.
Alternative but not exactly contradictory to https://github.com/mono/mono/pull/14248.
Note that this is a single inlinable instruction on x86,
if you assume at least SSE4 from circa 2007, which I am avoiding here.
=> Remove libgcc_s_seh-1.dll dependency when targeting Win32 with gcc.

mcs/tools/wasm-tuner/tuner.cs, sdks/wasm/Makefile, sdks/wasm/driver.c, sdks/wasm/hello.cs, sdks/wasm/packager.cs
The --pinvoke-libs=x argument to packager.exe can be used to generate pinvoke linking tables.
'x' is a list of library names used in DllImport declarations, i.e. --pinvoke-libs=libtest is used
to link with [DllImport ("libtest")].
=> [wasm] Add support for pinvokes in user assemblies.

mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/14247.
=> [aot] Avoid passing -march=arm to llc when using thumb, it forces arm32 code generation.

mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/14247.
Backport of #14288.
/cc @vargaz
=> [2019-02] [aot] Avoid passing -march=arm to llc when using thumb, it forces arm32 code generation.

mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/14247.
Backport of #14288.
=> [2019-04] [aot] Avoid passing -march=arm to llc when using thumb, it forces arm32 code generation.

mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/14261
Fixes https://github.com/mono/mono/issues/14143
This was causing an issue when trying to inline
System.Numerics.Vectors.Vector`1<byte>:Equals into System.Span.IndexOf
from System.Memory.dll as provided by nuget. I believe that it is
comparing the result of a SIMD operation on two SIMD registers there with a
SIMD register full of zero bytes.
When we produce the Equals call (no inline), we spill the SIMD <4 x i32>
vector to the stack in the caller, and we then later load it
with the widened type used here <16 x i8>.
When we inline, we end up making the args into XMOV opcodes,
and then doing the "pcmpeqb" mini opcode with the return values
from those operations. This becomes a register to register no-op
copy, and the original <4 x i32> gets …
=> [llvm] Widen vector equality (OP_PCMPEQx)

mono/mini/exceptions-arm.c
The previous attempt ( https://github.com/mono/mono/pull/14078 ) only fixed it for ABIs where the stack pointer alignment is 8 bytes. ABIs, such as watchOS, require 16 byte alignment.
Fixes https://github.com/mono/mono/issues/14223
=> [arm] amend stack pointer properly in exception trampoline

mono/mini/exceptions-arm.c
The previous attempt ( https://github.com/mono/mono/pull/14078 ) only fixed it for ABIs where the stack pointer alignment is 8 bytes. ABIs, such as watchOS, require 16 byte alignment.
Fixes https://github.com/mono/mono/issues/14223
Backport of #14310.
/cc @lewurm
=> [2019-02] [arm] amend stack pointer properly in exception trampoline

sdks/wasm/library_mono.js
fix mono_wasm_set_runtime_options so that it can be used outside of the test app
=> [wasm] Define wasm_strdup when setting options

configure.ac
With this change, within libmonosgen.so, calls from
‘mono_x’ to ‘mono_y’ are made directly instead of going through ‘mono_y@plt’.
This is the same as the mono executable already and the same as Windows.
Mac/iOS might also already be this way?
This definitely changes Linux.
No other shared object, nor the executable can therefore replace ‘mono_y’. Does anyone do that?
It is then much more understood where locks are, making coop and crash reporting more correct and reliable.
=> ld -Bsymbolic so dynamic linker does not get between mono and itself.

mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs, mcs/class/corlib/System/MonoCustomAttrs.cs, mcs/class/corlib/Test/System.Reflection/FieldInfoTest.cs, mcs/class/corlib/Test/System.Resources/ResourceManagerTest.cs, mcs/class/corlib/corefx/RuntimeFeature.cs, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/referencesource/mscorlib/system/activator.cs, mcs/class/referencesource/mscorlib/system/rttype.cs
Move the `RuntimeFeature.IsDynamicCodeSupported` and `IsDynamicCodeCompiled` conditionals over here from the corefx module and add them in a few places where `TypeBuilder` is used.
=> Add a few `RuntimeFeature.IsDynamicCodeSupported` conditionals.

scripts/ci/pipeline-netcore-runtime.yml
This should make our builds available in the BAR/Maestro++
Relatedly, this also changes the job to a matrix one, because that was required for the Arcade template I'm using, so it should be easier to add non-x86-Linux to the build now.
=> [netcore] Publish to BAR too

mono/mini/exceptions-arm.c
The previous attempt ( https://github.com/mono/mono/pull/14078 ) only fixed it for ABIs where the stack pointer alignment is 8 bytes. ABIs, such as watchOS, require 16 byte alignment.
Fixes https://github.com/mono/mono/issues/14223
Backport of #14310.
/cc @lewurm
=> [2019-04] [arm] amend stack pointer properly in exception trampoline

sdks/wasm/packager.cs
Allow a --link-descriptor arg to supply a linker.xml configuration file
=> [wasm] Add --link-descriptor arg to packager

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridViewCheckBoxCell.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/DataGridViewCheckBoxCellTest.cs
If DataGridViewCheckBoxCell not in threeState mode EditingCellFormattedValue must return true or false, instead of value of CheckState type
=> [WinForms] fix EditingCellFormattedValue getter and setter for bool value

mono/mini/jit-icalls.c, mono/mini/jit-icalls.h, mono/mini/mini-runtime.c
removal of JIT icall hashing. Making it more consistent with other icalls.
Costing maybe one instruction in some slow paths.
=> Make mono_fmod extern "C and not static, to simplify later

mono/mini/debugger-agent.c
=> [debugger] Deadlock while debugging a process

mono/metadata/remoting.c
This will help remove/reduce JIT icall hashing, as the
name will also be a field name or token paste to an enum value.
=> Mechanize strings in remoting.c register_icall.

mono/metadata/cominterop.c
This reduces the current source code and will be useful in eliminating JIT icall hashing.
=> Mechanize strings in cominterop.c register_jit_icall.

mono/mini/mini-arm.c
We can't use `slotsize=8` on `armv7k` as it leads to stack corruption.
Note that `mtouch` already calls the AOT compiler with `--aot=mtriple=arm64_32-ios`, so no changes are required there.
Regression introduced by https://github.com/mono/mono/pull/12992
Fixes https://github.com/mono/mono/issues/13454
=> [arm] fix armv7k regression on struct passing

mono/sgen/sgen-gray.c
During GC we allocate a gray queue protected by a mutex, sgen_gray_object_queue_init. This mutex is never destroyed when clearing up the object containing it, sgen_gray_object_queue_dispose, so it will leak. Overtime this could cause OOM on some systems depending on how memory related to system primitives are handled and partitioned.
=> Mutex memory leak on sgen GC (nursery, major).

mono/mini/mini-arm.c
We can't use `slotsize=8` on `armv7k` as it leads to stack corruption.
Note that `mtouch` already calls the AOT compiler with `--aot=mtriple=arm64_32-ios`, so no changes are required there.
Regression introduced by https://github.com/mono/mono/pull/12992
Fixes https://github.com/mono/mono/issues/13454
Backport of #14362.
/cc @lewurm
=> [2019-04] [arm] fix armv7k regression on struct passing

mono/mini/mini-arm.c
We can't use `slotsize=8` on `armv7k` as it leads to stack corruption.
Note that `mtouch` already calls the AOT compiler with `--aot=mtriple=arm64_32-ios`, so no changes are required there.
Regression introduced by https://github.com/mono/mono/pull/12992
Fixes https://github.com/mono/mono/issues/13454
Backport of #14362.
/cc @lewurm
=> [2019-02] [arm] fix armv7k regression on struct passing

mcs/class/corlib/System/Console.iOS.cs
* Make NSLogWriter thread-safe.
* Simplify newline checking in NSLogWriter.
* Fix NSLogWriter.Write to take into account the index and count parameters.
Backport of #13799.
/cc @lewurm @rolfbjarne
=> [2019-04] [corlib] Fix a few NSLogWriter issues.

mono/mini/debugger-agent.c
The thread_stopped profiler event can be raised by the thread_info_key_dtor tls
key destructor when the thread is already doesn't have a domain set.  In that
case, don't call process_profiler_event since it cannot handle a thread with
null TLS values.
Addresses https://github.com/xamarin/xamarin-android/issues/2920
Backport of #13936.
/cc @lambdageek 
Backport of #13938.
/cc @marek-safar @monojenkins
=> [2019-04] [2019-02] [debugger-agent] Ignore thread_end event if thread is detached

mcs/class/corlib/System.IO.IsolatedStorage/IsolatedStorageFile.cs
This was caused by changes in File.Move coming from https://github.com/mono/mono/pull/12000
Backport of #13698.
=> [corlib] Fix exception 'replacement' in IsolatedStorageFile.MoveFile()

mcs/class/corlib/System.IO.IsolatedStorage/IsolatedStorageFile.cs
This was caused by changes in File.Move coming from https://github.com/mono/mono/pull/12000
Backport of #13698.
=> [2019-04] [corlib] Fix exception 'replacement' in IsolatedStorageFile.MoveFile()

mono/metadata/assembly.c, mono/metadata/image.c
In `mono_image_open_a_lot`,  if `MonoImageOpenStatus *status` is null, don't write to it.
Also fixed up a few other places where we have assignments `*status = foo` by either:
* asserting that `status` is not null at the outset, or
* passing a local MonoImageOpenStatus if the argument is null, or
* adding a null check before the assignment.
Fixes #13941 
Backport of #14110.
=> [2019-02] [loader] Don't store through a null ptr

mono/metadata/assembly.c, mono/metadata/image.c
In `mono_image_open_a_lot`,  if `MonoImageOpenStatus *status` is null, don't write to it.
Also fixed up a few other places where we have assignments `*status = foo` by either:
* asserting that `status` is not null at the outset, or
* passing a local MonoImageOpenStatus if the argument is null, or
* adding a null check before the assignment.
Fixes #13941 
Backport of #14110.
=> [2019-04] [loader] Don't store through a null ptr

mono/metadata/assembly.c
Closes: #14366
Fixes Mac package failures during IronRuby compilation
```
Mono: The request to load the assembly System.Numerics.Vectors v4.1.3.0 was remapped to v4.0.0.0
Mono: Assembly Loader probing location: '/tmp/monoprefix/lib/mono/gac/System.Numerics.Vectors/4.1.3.0__b03f5f7f11d50a3a/System.Numerics.Vectors.dll'.
Mono: Assembly Loader probing location: '/tmp/monoprefix/lib/mono/msbuild/Current/bin/Roslyn/System.Numerics.Vectors.dll'.
Mono: Assembly Loader probing location: '/tmp/monoprefix/lib/System.Numerics.Vectors.dll'.
Mono: Assembly Loader probing location: '/tmp/monoprefix/lib/mono/4.5//Facades/System.Numerics.Vectors.dll'.
Mono: Assembly Loader probing location: '/tmp/monoprefix/lib/mono/gac/System.Numerics.Vectors/4.1.3.0__b03f5f7f11d50a3a/System.Numerics.Vectors.exe'.
Mono: …
```
=> Remapping should affect GAC search paths considered by the loader

mono/utils/mono-error-internals.h, mono/utils/mono-error.c
The constructor for mono_error_set_argument lacks a `const char *msg_format` so clearly we shouldn't be applying formatting from an entirely unrelated parameter.
This was flagged by `-Werror=format-security`
=> Don't apply MONO_ATTR_FORMAT_PRINTF to mono_error_set_argument

mono/utils/mono-mmap.c
This is to address https://github.com/mono/mono/pull/13446#issuecomment-489749599
=> [runtime] Use MAP_JIT automatically when running under a hardened runtime on osx.

mono/mini/debugger-agent.c
Backport of #14368.
/cc @lewurm @thaystg
=> [2019-02] [debugger] Deadlock while debugging a process

mono/metadata/marshal.c
The less mechical parts:
- spell out monoeg_g_free
- register_dyn_icall not used, remove
- register_icall_no_wrapper only used once, spell it out instead
This is nice cosmetically on its own and will help remove JIT icall hashing.
=> Mechanize strings in marshal.c register_icall and cleanup a little.

mcs/class/System.Private.CoreLib/System.Collections.Generic/ArraySortHelper.cs, mcs/class/System.Private.CoreLib/System.Collections.Generic/Comparer.cs, mcs/class/System.Private.CoreLib/System.Collections.Generic/EqualityComparer.cs, mcs/class/System.Private.CoreLib/System/Array.cs, mono/metadata/icall.c, netcore/Makefile, netcore/excludes-System.Runtime.Tests.rsp
This PR enables >200 tests in System.Runtime.Tests.
1.
```csharp
public enum SByteEnum : sbyte
{
MinusTwo = -2,
Zero = 0,
Five = 5
}
SByteEnum[] arr = new SByteEnum[3];
arr.SetValue((sbyte) 1, 0);  // Expected: InvalidCast!
arr.CopyTo(new sbyte[3], 0); // Expected: success
```
Mono used to allow both (looks more logical).
2.
```csharp
Array sourceArray = new object[] { null };
Array destinationArray = new int?[] { 0 };
Array.Copy(sourceArray, 0, destinationArray, 0, 1);
```
Mono used to throw Exception here (that's why I added `Nullable.GetUnderlyingType`).
3.
In .NET Core it's allowed to copy array of `ushort` to `char` (`DefaultBinder.CanChangePrimitive` returns false for such conversion, but returns true for `char` to `ushort`).
4. if `#nullable enable` is defined in one of the …
=> [netcore] Set of workarounds for ArrayTests

mono/mini/debugger-agent.c
Backport of #14368.
/cc @lewurm @thaystg
=> [2019-04] [debugger] Deadlock while debugging a process

mono/metadata/appdomain.c, mono/metadata/custom-attrs.c, mono/metadata/exception.c, mono/metadata/marshal.c, mono/metadata/object.c, mono/metadata/reflection.c
Use mono_runtime_invoke_handle_void instead.
=> Usually do not create a handle in mono_runtime_invoke_handle.

mono/metadata/object.c
Fixes this crash on watchOS with llvmonly:
```
(lldb) bt 35
* thread %1, name = 'tid_303', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x4d55545c)
* frame %0: 0x01ab81de mscorlibtests`sgen_vtable_get_descriptor(vtable=0x4d555458) at sgen-client-mono.h:29:33
frame %1: 0x01a9e278 mscorlibtests`major_copy_or_mark_object_canonical at sgen-marksweep-drain-gray-stack.h:158:10
frame %2: 0x01a9debc mscorlibtests`major_copy_or_mark_object_canonical(ptr=0x182f260c, queue=0x01dd4894) at sgen-marksweep.c:1363
frame %3: 0x019d31f2 mscorlibtests`mono_handle_stack_scan(stack=0x17e200b0, func=(mscorlibtests`major_copy_or_mark_object_canonical + 1 at sgen-marksweep.c:1362), gc_data=0x01dd4894, precise=1, check=1) at handle.c:340:5
frame %4: 0x01a45680 …
```
=> [metadata] use handle stack in mono_runtime_object_init_handle

mono/utils/mono-mmap.c
This is to address https://github.com/mono/mono/pull/13446#issuecomment-489749599
Backport of #14395.
=> [2019-02] [runtime] Use MAP_JIT automatically when running under a hardened runtime on osx.

mono/mini/mini-exceptions.c
Fixes a race in llvmonly (watchOS):
```
Process 397 stopped
* thread %10, name = 'tid_8e2f', stop reason = EXC_BAD_ACCESS (code=1, address=0x28)
frame %0: 0x0177f690 mscorlibtests`mono_llvm_load_exception at mini-exceptions.c:3886:23
3883                 size_t upper = mono_array_length_internal (mono_ex->trace_ips);
3884
3885                 for (int i = 0; i < upper; i += TRACE_IP_ENTRY_SIZE) {
-> 3886                         gpointer curr_ip = mono_array_get_internal (mono_ex->trace_ips, gpointer, i);
3887                         for (int j = 0; j < TRACE_IP_ENTRY_SIZE; ++j) {
3888                                 gpointer p = mono_array_get_internal (mono_ex->trace_ips, gpointer, i + j);
3889                                 trace_ips = g_list_append (trace_ips, p);
Target 0: …
```
=> [2019-02] [llvmonly] make local copy of trace_ips pointer from exception object

mono/mini/mini-exceptions.c
Fixes a race in llvmonly (watchOS):
```
Process 397 stopped
* thread %10, name = 'tid_8e2f', stop reason = EXC_BAD_ACCESS (code=1, address=0x28)
frame %0: 0x0177f690 mscorlibtests`mono_llvm_load_exception at mini-exceptions.c:3886:23
3883                 size_t upper = mono_array_length_internal (mono_ex->trace_ips);
3884
3885                 for (int i = 0; i < upper; i += TRACE_IP_ENTRY_SIZE) {
-> 3886                         gpointer curr_ip = mono_array_get_internal (mono_ex->trace_ips, gpointer, i);
3887                         for (int j = 0; j < TRACE_IP_ENTRY_SIZE; ++j) {
3888                                 gpointer p = mono_array_get_internal (mono_ex->trace_ips, gpointer, i + j);
3889                                 trace_ips = g_list_append (trace_ips, p);
Target 0: …
```
=> [2019-04] [llvmonly] make local copy of trace_ips pointer from exception object

mono/metadata/threads-types.h, mono/metadata/threads.c, mono/metadata/w32mutex-unix.c
Take advantage of thread/internal_thread maturity/pinning.
There are arguments for and against this.
It is arguably better to use handles everywhere.
But it is dubious to require an allocation to release a lock.
Releasing a lock should be infallible.
And surviving low memory shouldn't be a lost cause, imho..
This diff could also be viewed as an opportunistic cycle/size optimization
and be placed under ifdef -- ifdef THREAD_ALWAYS_PINNED orsuch.
This is an alternative to https://github.com/mono/mono/pull/14397.
Contributes to https://github.com/mono/mono/issues/13006
=> Do not allocate handles in ReleaseMutex.

mono/metadata/appdomain.c, mono/metadata/custom-attrs.c, mono/metadata/exception.c, mono/metadata/marshal.c, mono/metadata/object.c, mono/metadata/reflection.c
Use mono_runtime_invoke_handle_void instead.
Backport of #14404.
/cc @lewurm @jaykrell
=> [2019-04] Usually do not create a handle in mono_runtime_invoke_handle.

mono/mini/debugger-agent.c
Backport of #14368.
/cc @lewurm @thaystg
=> [2018-10] [debugger] Deadlock while debugging a process

mono/mini/debugger-agent.c
Backport of #14368.
/cc @thaystg
=> [2018-08] [debugger] Deadlock while debugging a process

mono/metadata/appdomain.c, mono/metadata/custom-attrs.c, mono/metadata/exception.c, mono/metadata/marshal.c, mono/metadata/object.c, mono/metadata/reflection.c
Use mono_runtime_invoke_handle_void instead.
Backport of https://github.com/mono/mono/pull/14404
=> [2019-02] Usually do not create a handle in mono_runtime_invoke_handle.

mono/sgen/sgen-gray.c
During GC we allocate a gray queue protected by a mutex, sgen_gray_object_queue_init. This mutex is never destroyed when clearing up the object containing it, sgen_gray_object_queue_dispose, so it will leak. Overtime this could cause OOM on some systems depending on how memory related to system primitives are handled and partitioned.
Backport of #14375.
/cc @BrzVlad @lateralusX
=> [2019-02] Mutex memory leak on sgen GC (nursery, major).

mono/sgen/sgen-gray.c
During GC we allocate a gray queue protected by a mutex, sgen_gray_object_queue_init. This mutex is never destroyed when clearing up the object containing it, sgen_gray_object_queue_dispose, so it will leak. Overtime this could cause OOM on some systems depending on how memory related to system primitives are handled and partitioned.
Backport of #14375.
/cc @BrzVlad @lateralusX
=> [2019-04] Mutex memory leak on sgen GC (nursery, major).

mono/profiler/log.c, mono/utils/Makefile.am, mono/utils/mono-os-semaphore-win32.c, mono/utils/mono-os-semaphore.h, msvc/libmonoutils-win32.targets, msvc/libmonoutils-win32.targets.filters, msvc/mono-profiler-log.vcxproj, msvc/mono-profiler-log.vcxproj.filters, msvc/mono.sln
Several fixes to the log profiler in order to work on Windows.
* Add new dynamic library project to build log profiler on Windows MSVC.
* Fix dependecy between log profiler and Mono.
* Rewrite command pipe logic on Windows since it's not supported to select
on both sockets and pipes.
* Several additional socket fixes needed for log profiler to work on Windows.
NOTE, this makes sure we have a log profiler that can be started/stopped and at least generate some basic output. Still needs more testing on Windows since there might be other parts of the profiler not working as expected (since it has not been run for quite some time).
=> Add log profiler support to Mono MSVC build.

mcs/class/corlib/ReferenceSources/TextInfo.cs, mcs/class/corlib/Test/System.Globalization/CultureInfoTest.cs
Fixes https://github.com/mono/mono/issues/14102
Backport of #14105.
=> [2019-04] TextInfo.ChangeCase should not use CultureInfo.CurrentCulture

mono/metadata/class-internals.h, mono/metadata/cominterop.c, mono/metadata/icall-table.c, mono/metadata/icall.c, mono/metadata/jit-icall-reg.h, mono/metadata/marshal.c, mono/metadata/remoting.c, mono/mini/aot-runtime.c, mono/mini/mini-runtime.c, mono/mini/mini.c, mono/mini/mini.h
There is a little more to do (in a later PR).
Need to decide here, pointer or enum. Either work.
Very minor difference either way.
Make duplicate registration checking stricter.
=> Reduce malloc in JIT icall registration.

mono/mini/mini-arm64.h
Fixes a couple of mscorlib test failures, failing with
> Stack walks are not supported on this platform
=> [arm64] set MONO_ARCH_HAVE_UNWIND_BACKTRACE for watch4

mono/mini/mini-arm64.h
Fixes a couple of mscorlib test failures, failing with
> Stack walks are not supported on this platform
Backport of #14440.
/cc @lewurm
=> [2019-02] [arm64] set MONO_ARCH_HAVE_UNWIND_BACKTRACE for watch4

mono/metadata/object.c
Fixes this crash on watchOS with llvmonly:
https://gist.github.com/lewurm/921b77a238c6fd60757a5ee9f54279d1
The hint here was that the crash happened in `mono_handle_stack_scan ()` and inspecting the handle stack there. After enabling `MONO_HANDLE_TRACK_OWNER` and `MONO_HANDLE_TRACK_SP` in `handle.h`, I got this:
https://gist.github.com/lewurm/71f936a126879ef2b96d00399e6b2bd9
@lambdageek suggested this fix after showing this trace to him. As far as I understand we do _not_ know the root cause yet. The handle leak happens in this trace:
https://gist.github.com/lewurm/b76fbc391f22d897bfd532ac1b67e2aa
`mono_runtime_object_init_checked ()` already should take care of the handle stack 😕
Contributes to #13006
Backport of #14399.
=> [2019-04] [metadata] use handle stack in mono_runtime_object_init_handle

mcs/class/System.Private.CoreLib/Makefile, mono/metadata/icall.c
Better implementation for https://github.com/mono/mono/pull/14336.
Fixes `System.Reflection.Tests.TypeTests_HiddenTestingOrder.HideDetectionHappensAfterPrivateInBaseClassChecks` test
=> [netcore] Don't query non-public properties from base classes

mono/metadata/object.c
Fixes this crash on watchOS with llvmonly:
https://gist.github.com/lewurm/921b77a238c6fd60757a5ee9f54279d1
The hint here was that the crash happened in `mono_handle_stack_scan ()` and inspecting the handle stack there. After enabling `MONO_HANDLE_TRACK_OWNER` and `MONO_HANDLE_TRACK_SP` in `handle.h`, I got this:
https://gist.github.com/lewurm/71f936a126879ef2b96d00399e6b2bd9
@lambdageek suggested this fix after showing this trace to him. As far as I understand we do _not_ know the root cause yet. The handle leak happens in this trace:
https://gist.github.com/lewurm/b76fbc391f22d897bfd532ac1b67e2aa
`mono_runtime_object_init_checked ()` already should take care of the handle stack 😕
Contributes to #13006
Backport of #14399.
=> [2019-02] [metadata] use handle stack in mono_runtime_object_init_handle

mono/mini/mini-arm64.h
Fixes a couple of mscorlib test failures, failing with
> Stack walks are not supported on this platform
Backport of #14440.
/cc @lewurm
=> [2019-04] [arm64] set MONO_ARCH_HAVE_UNWIND_BACKTRACE for watch4

mcs/class/corlib/System.Reflection.Emit/AssemblyBuilder.cs, mcs/class/corlib/Test/System.Reflection.Emit/AssemblyBuilderTest.cs
Fixes #13028
Backport of #14406.
=> [2019-04] [corlib] Implement AssemblyBuilder.get_ReflectionOnly()

mcs/class/System/System.csproj, mcs/class/System/mono_fsw.sources, mcs/class/System/monotouch_System.dll.exclude.sources, mcs/class/System/monotouch_System.dll.sources, mcs/class/System/monotouch_runtime_System.dll.exclude.sources, mcs/class/System/monotouch_tv_runtime_System.dll.exclude.sources, mcs/class/System/net_4_x_System.dll.sources
This reverts commit 46fc5352f3dfe0027e684a0f61e71130fccd559f.
While iOS FileSystemWatcher works, we now find that it is used unofficially-available  symbols and cannot publish apps using those.
Fixes https://github.com/mono/mono/issues/14290
Backport of #14316.
Backport of #14447.
=> [2019-02] Revert "[System] Add FSEvent FileSystemWatcher to monotouch BCL profile"

mono/utils/mono-mmap.c
This is to address https://github.com/mono/mono/pull/13446#issuecomment-489749599
Backport of #14395.
=> [2019-04] [runtime] Use MAP_JIT automatically when running under a hardened runtime on osx.

mcs/class/System/System.csproj, mcs/class/System/mono_fsw.sources, mcs/class/System/monotouch_System.dll.exclude.sources, mcs/class/System/monotouch_System.dll.sources, mcs/class/System/monotouch_runtime_System.dll.exclude.sources, mcs/class/System/monotouch_tv_runtime_System.dll.exclude.sources, mcs/class/System/net_4_x_System.dll.sources
This reverts commit 46fc5352f3dfe0027e684a0f61e71130fccd559f.
While iOS FileSystemWatcher works, we now find that it is used unofficially-available  symbols and cannot publish apps using those.
Fixes https://github.com/mono/mono/issues/14290
Backport of #14316.
=> [2019-04] Revert "[System] Add FSEvent FileSystemWatcher to monotouch BCL profile"

mcs/class/corlib/ReferenceSources/TextInfo.cs, mcs/class/corlib/Test/System.Globalization/CultureInfoTest.cs
Fixes https://github.com/mono/mono/issues/14102
Backport of #14105.
=> [2019-02] TextInfo.ChangeCase should not use CultureInfo.CurrentCulture

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridViewCheckBoxCell.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/DataGridViewCheckBoxCellTest.cs
If DataGridViewCheckBoxCell not in threeState mode EditingCellFormattedValue must return true or false, instead of value of CheckState type
Backport of #13845.
=> [2019-04] [WinForms] fix EditingCellFormattedValue getter and setter for bool value

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridViewCheckBoxCell.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/DataGridViewCheckBoxCellTest.cs
If DataGridViewCheckBoxCell not in threeState mode EditingCellFormattedValue must return true or false, instead of value of CheckState type
Backport of #13845.
=> [2019-02] [WinForms] fix EditingCellFormattedValue getter and setter for bool value

configure.ac
Since commit d8af775, c++ compiler is required to compile.
This patch checks if the c++ compiler is available as soon as possible
and returns an error in case it is not found.
Fixes: https://github.com/mono/mono/issues/14195
Signed-off-by: Angelo Compagnucci <angelo@amarulasolutions.com>
=> configure: check for c++ availability

mono/utils/mono-state.c
Sometimes people expect crashes or don't care to have artifacts beyond what's put into stdout/stderr. This option is useful for these cases.
=> [merp] Add an env var to disable all mono_crash files

sdks/wasm/Makefile, sdks/wasm/bindings-test.cs, sdks/wasm/driver.c, sdks/wasm/framework/src/WebAssembly.Bindings/Runtime.cs
These changes update the `release-dynamic` configuration of the wasm runtime:
- Enhance the support for dynamically linked libraries, by including all available emscripten libraries. This makes the runtime a bit larger and enables support for C++ libraries.
- Add support for `IntPtr` in JavaScript bindings.
- Enable `addFunction` support to allow for wasm originating callbacks.
=> [Wasm] Expand support for dynamic linking

mono/mini/builtin-types.cs, mono/mini/interp/transform.c
Fixes https://github.com/mono/mono/issues/14246
=> [interp] disable inlining for built-in types

configure.ac, mono/metadata/sysmath.c, netcore/Makefile, netcore/excludes-System.Runtime.Extensions.Tests.rsp
This PR fixes 5 tests in `System.Runtime.Extensions.Tests` (MathTests)
It's basically a copy-paste from CoreCLR:
1) https://github.com/dotnet/coreclr/blob/bd7f8e7435b8cba0cca3a198f15fdc2e4764c2fc/src/pal/src/configure.cmake#L869-L892
2) https://github.com/dotnet/coreclr/blob/master/src/pal/src/cruntime/math.cpp#L876-L894
```
System.Runtime.Extensions.Tests  Total: 6466, Errors: 0, Failed: 11, Skipped: 2
```
=> [netcore] Fix Math.ILogB corner cases

mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c, mono/metadata/marshal.h
i.e. when CEE_MONO_JIT_ICALL_ADDR takes enum instead of func.
=> Work toward JIT icall hash removal.

mono/mini/mini-arm.c
Regression of https://github.com/mono/mono/pull/12992 & https://github.com/mono/mono/pull/14362
In the end, the actual fix boils down to:
```patch
--- a/mono/mini/mini-arm.c
+++ b/mono/mini/mini-arm.c
@@ -2374,7 +2374,7 @@ mono_arch_get_llvm_call_info (MonoCompile *cfg, MonoMethodSignature *sig)
lainfo->nslots = ALIGN_TO (ainfo->struct_size, 8) / 8;
lainfo->esize = 8;
} else {
-                               lainfo->nslots = ainfo->struct_size / sizeof (target_mgreg_t);
+                               lainfo->nslots = ALIGN_TO (ainfo->struct_size, sizeof (target_mgreg_t)) / sizeof (target_mgreg_t);
lainfo->esize = 4;
}
break;
```
Tested on `xamarin-macios/arm64_32-v3` branch:
* mscorlib
* mini
* dont link
* monotouch tests
* and a modified version of …
=> [arm] one more attempt to fix slotsize issue on llvmonly

mono/mini/mini-llvm.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini-trampolines.c, mono/mini/mini.c
Previously, some calls were not patched, so the trampolines were repeatedly called.
=> [llvm] Fix patching of calls from LLVM JITted code.

mono/mini/builtin-types.cs, mono/mini/interp/transform.c
Fixes https://github.com/mono/mono/issues/14246
Backport of #14501.
/cc @lewurm
=> [2019-04] [interp] disable inlining for built-in types

mono/mini/builtin-types.cs, mono/mini/interp/transform.c
Fixes https://github.com/mono/mono/issues/14246
Backport of #14501.
/cc @lewurm
=> [2019-02] [interp] disable inlining for built-in types

mono/mini/driver.c
When MONO_ENV_OPTIONS is null, we would leak the array and buffer
=> Fix leak in mono_parse_options

mono/mini/mini-posix.c
The issues fixed below were identified by https://github.com/mono/mono/issues/14416 .
The typo is a cosmetic fix.
The other change uses g_error and not g_assert_not_reached. g_error goes through the already-modified path that will work correctly during double faults during the crash dumper. Otherwise, the double fault results in a zero/successful status code.
The reproduction for this involves preventing mono from creating any more allocations, using `ulimit`.
=> [crash] Handle OOM/blocked allocation during crash dumper

mono/mini/mini-posix.c
Fixes https://github.com/mono/mono/issues/14469
This is necessary to make Mono crash reporting resilient in the face of forking failures.
=> [crash] Don't waitpid() if fork() fails

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/mini-amd64.c, mono/mini/mini-llvm.c, mono/mini/mini-ppc.c, mono/mini/mini-runtime.c, mono/mini/mini-s390x.c, mono/mini/mini-x86.c, mono/mini/patch-info.h
The most important point of the "temporary" aspect, esp. given
the complete conversion, is renaming MONO_PATCH_INFO_JIT_ICALL to MONO_PATCH_INFO_JIT_ICALL_ID.
Any accidental or merged MONO_PATCH_INFO_JIT_ICALL will fail to compile.
=> MONO_PATCH_INFO_JIT_ICALL cleanup

man/mono.1, mono/mini/driver.c
Useful for third parties consuming the version number of mono.
Fixes https://github.com/mono/mono/issues/14491
=> [driver] add --version=number

mono/mini/interp/transform.c
This detail got lost when the code was duplicated here: https://github.com/mono/mono/pull/13154/files#diff-f115ce23fba6528256a47e2b7e8b0a19R1611
Fixes `mono/tests/dim-constrainedcall.il` on the interpreter. This PR will enable it: https://github.com/mono/mono/pull/14166
/cc @thaystg @kg
=> [interp] add missing enum check on constrained callvirt

mono/metadata/custom-attrs.c
All the CustomAttribute initializer names (fields, property) except the last were leaked. Ensure all names are freed.
Fixes #14543
=> Plug leak of CustomAttribute initializer name

winconfig.h
Needed in order to setup CI lanes using --enable-cooperative-suspend.
=> Add ability to use cooperative suspend in configure step.

mono/metadata/loader.c
Backport #13281 to `2019-02`
---
Context: https://github.com/xamarin/xamarin-android/issues/2780
On Android the executable for the application is going to be
`/system/bin/app_process{32,64}` depending on the application's architecture.
However, libraries for the different architectures live in different
subdirectories of `/system`: `lib` for 32-bit apps and `lib64` for 64-bit ones.
Thus appending `/lib` below will fail to load the DSO for a 64-bit app, even if
it exists there, because it will have a different architecture. The quickest fix
is to use `lib64` explicitly for 64-bit Android apps.
=> [2019-02][Android] Fix runtime loading of DSOs for 64-bit processes

mono/metadata/loader.c
Context: https://github.com/xamarin/xamarin-android/issues/2780
On Android the executable for the application is going to be
`/system/bin/app_process{32,64}` depending on the application's architecture.
However, libraries for the different architectures live in different
subdirectories of `/system`: `lib` for 32-bit apps and `lib64` for 64-bit ones.
Thus appending `/lib` below will fail to load the DSO for a 64-bit app, even if
it exists there, because it will have a different architecture. The quickest fix
is to use `lib64` explicitly for 64-bit Android apps.
Backport of #13281.
/cc @lambdageek @grendello
=> [2019-04][Android] Fix runtime loading of DSOs for 64-bit processes

mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
```console
$ MONO_ENV_OPTIONS='--interp' make -C netcore xtest-System.Runtime.Tests
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET Core 3.0.0-preview5-27620-01)
Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
Discovered:  System.Runtime.Tests (found 5266 of 5402 test cases)
Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 16)
[...]
Finished:    System.Runtime.Tests
=== TEST EXECUTION SUMMARY ===
System.Runtime.Tests  Total: 32485, Errors: 0, Failed: 23, Skipped: 2, Time: 126.432s
```
See failures here: https://gist.github.com/lewurm/c8372b0c7ba6a78cf8b7b7b8c7090820
=> [netcore] add some intrinsics for interpreter

mono/mini/interp/transform.c
Needs some additional conversions which happen to be included by accident previously.
This fixes those warnings on amd64:
```
Test run:
image=/Users/lewurm/work/mono-dim-call/mono/mini/builtin-types.exe
BuiltinTests.test_0_nuint_fieldload: Store local stack type mismatch 0 1
BuiltinTests.test_0_much_casting: Store local stack type mismatch 0 1
Results: total tests: 84, all pass
Elapsed time: 0.026546 secs (0.026546, 0.000000)
```
and those warnings on armv7:
```
Test run: image=/mono/mono/mini/builtin-types.exe
BuiltinTests.test_0_nint_inc: 0011 arith type mismatch add.i4 0 1
BuiltinTests.test_0_nint_dec: 0011 arith type mismatch sub.i4 0 1
BuiltinTests.test_0_nint_implicit_decimal: 0034 arith type mismatch
add.i4 0 1
BuiltinTests.test_0_nuint_inc: 0011 arith type mismatch add.i4 0 1 …
```
=> [interp] set correct stack type on op_Implicit/op_Explicit intrinsics for native types

mcs/build/tests.make, runtime/Makefile.am
So it gets included in the sdks archive
=> [tests] Add xunit.execution.dotnet.dll to tests directory

mono/metadata/custom-attrs.c
All the CustomAttribute initializer names (fields, property) except the last were leaked. Ensure all names are freed.
Fixes #14543
Backport of #14544.
/cc @Therzok
=> [2019-02] Plug leak of CustomAttribute initializer name

mcs/class/System.Core/System.Core.csproj, mcs/class/System.Core/System.Linq.Expressions/LambdaExpression.NotSupported.cs, mcs/class/System.Core/System.Runtime.CompilerServices/RuntimeOps.NotSupported.cs, mcs/class/System.Core/monotouch_System.Core.dll.sources, mcs/class/System.Core/sre_pns.sources
Ensure the API surface for `System.Core.dll` is identical between the
`monotouch` and `monotouch_runtime` (used for REPL and the interpreter).
This ensure code compiled against one will be fine when building against
the other (e.g. avoiding linker errors).
Removed methods:
```csharp
public void CompileToMethod (System.Reflection.Emit.MethodBuilder method);
public void CompileToMethod (System.Reflection.Emit.MethodBuilder method, System.Runtime.CompilerServices.DebugInfoGenerator debugInfoGenerator);
```
Removed methods:
```csharp
[Obsolete ("do not use this method")]
public static IRuntimeVariables MergeRuntimeVariables (IRuntimeVariables first, IRuntimeVariables second, int[] indexes);
[Obsolete ("do not use this method")]
public static System.Linq.Expressions.Expression Quote …
```
=> [System.Core] Ensure monotouch[_runtime] API are identical

mono/metadata/class-internals.h, mono/metadata/debug-internals.h, mono/metadata/mono-debug.h, mono/mini/mini-llvm-cpp.h, mono/mini/mini-llvm.c, mono/mini/mini.h, mono/utils/mono-compiler.h
Remove unused function that would need MONO_LLVM_INTERNAL.
Found by linking with -z now (https://github.com/mono/mono/pull/14562), which we should do, separately.
=> [loaded LLVM] Add several missing MONO_LLVM_INTERNAL

mcs/class/Mono.Cairo/Mono.Cairo/Context.cs
@marek-safar Can you please help find a dev to shepherd this change through?  It has **not** been built or tested...unfortunately I'm not quite set up for full mono development.  It should also be code reviewed by someone in this space.
We are seeing instances where VS for Mac is crashing with a SIGSEGV when
calling into certain Cairo.Context functions.  Looking at the code, it's clear
that it's possible to have Context.handle == IntPtr.Zero after disposing the
object.
From research, it looks like passing a nullptr to raw cairo functions can
result in a SIGSEGV:
https://bugs.launchpad.net/ubuntu/+source/compiz/+bug/93807
This change adds check to see if Conext.handle == IntPtr.Zero in Context
painting, font, and path methods.  This will turn uncatchable SIGSEGVs
into …
=> Throw ObjectDisposedException instead of crashing when Cairo.Context handle == IntPtr.Zero

sdks/builds/mac.mk
It was using an unescaped makefile variable in the template, i.e. ended up empty which meant the build just took the host version as the min version.
Fixed the variable and also moved it to CFLAGS/CXXFLAGS instead of CPPFLAGS to be consistent with ios.mk
=> [sdks] Fix min OSX version of runtime files in Mac SDK

mcs/class/Mono.Cairo/Mono.Cairo/Context.cs
@marek-safar Can you please help find a dev to shepherd this change through?  It has **not** been built or tested...unfortunately I'm not quite set up for full mono development.  It should also be code reviewed by someone in this space.
We are seeing instances where VS for Mac is crashing with a SIGSEGV when
calling into certain Cairo.Context functions.  Looking at the code, it's clear
that it's possible to have Context.handle == IntPtr.Zero after disposing the
object.
From research, it looks like passing a nullptr to raw cairo functions can
result in a SIGSEGV:
https://bugs.launchpad.net/ubuntu/+source/compiz/+bug/93807
This change adds check to see if Conext.handle == IntPtr.Zero in Context
painting, font, and path methods.  This will turn uncatchable SIGSEGVs
into …
=> [2019-04] Throw ObjectDisposedException instead of crashing when Cairo.Context handle == IntPtr.Zero

mcs/class/System.Core/System.Core.csproj, mcs/class/System.Core/System.Linq.Expressions/LambdaExpression.NotSupported.cs, mcs/class/System.Core/System.Runtime.CompilerServices/RuntimeOps.NotSupported.cs, mcs/class/System.Core/monotouch_System.Core.dll.sources, mcs/class/System.Core/sre_pns.sources
Ensure the API surface for `System.Core.dll` is identical between the
`monotouch` and `monotouch_runtime` (used for REPL and the interpreter).
This ensure code compiled against one will be fine when building against
the other (e.g. avoiding linker errors).
Removed methods:
```csharp
public void CompileToMethod (System.Reflection.Emit.MethodBuilder method);
public void CompileToMethod (System.Reflection.Emit.MethodBuilder method, System.Runtime.CompilerServices.DebugInfoGenerator debugInfoGenerator);
```
Removed methods:
```csharp
[Obsolete ("do not use this method")]
public static IRuntimeVariables MergeRuntimeVariables (IRuntimeVariables first, IRuntimeVariables second, int[] indexes);
[Obsolete ("do not use this method")]
public static System.Linq.Expressions.Expression Quote …
```
=> [2019-04] [System.Core] Ensure monotouch[_runtime] API are identical

mcs/class/Mono.Cairo/Mono.Cairo/Context.cs
@marek-safar Can you please help find a dev to shepherd this change through?  It has **not** been built or tested...unfortunately I'm not quite set up for full mono development.  It should also be code reviewed by someone in this space.
We are seeing instances where VS for Mac is crashing with a SIGSEGV when
calling into certain Cairo.Context functions.  Looking at the code, it's clear
that it's possible to have Context.handle == IntPtr.Zero after disposing the
object.
From research, it looks like passing a nullptr to raw cairo functions can
result in a SIGSEGV:
https://bugs.launchpad.net/ubuntu/+source/compiz/+bug/93807
This change adds check to see if Conext.handle == IntPtr.Zero in Context
painting, font, and path methods.  This will turn uncatchable SIGSEGVs
into …
=> [2019-02] Throw ObjectDisposedException instead of crashing when Cairo.Context handle == IntPtr.Zero

packaging/MacSDK/nuget.py
Some of the packages/bockbuild caches have somehow ended up with a Nuget 5.0.0 binary, even after the 5.0.2 bump. We suspect that the wrong binary was temporarily published on the 5.0.2 URL
=> [MacSDK] Trigger redownload of Nuget 5.0.2

mono/utils/mono-state.c
Coverity said:
```
CID 1445100:  Resource leaks  (RESOURCE_LEAK)
Failing to save or free storage allocated by "monoeg_g_getenv("MONO_CRASH_NOFILE")" leaks it.
```
=> [merp] Don't leak g_getenv return value

mcs/class/System.Web/System.Web.Security/SqliteMembershipProvider.cs
Dear team Mono,
Please find below the fix of issue #14234 .  On the stage of the initialization of the SqliteMembershipProvider the existed code always produced an error "Failed to map path '/'" in case if the ASP.NET application is placed not at the root path. Detailed step by step description of the problem is provided in the issue description.
The bug was that was implemented the call of the function with wrong parameters list. So the fix was in changing the function call. The same function call is also used in SqlMembershipProvider.cs.
Thanks for your job.
Regards,
Alex
=>  Fixes #issue-14234

mono/mini/mini-trampolines.c
Variable is only used here: https://github.com/mono/mono/blob/82a993124888d470d1057eae9546e5be76524dad/mono/mini/mini-trampolines.c#L743
=> Fix build warning for orig_method

mono/mini/mini-llvm.c
Since they're identical right now, we can use the coreclr configuration
to make our IR more easily analyzed by tools built around LLVM.
```
class CoreCLRGC : public GCStrategy {
public:
CoreCLRGC() {
UseStatepoints = true;
// These options are all gc.root specific, we specify them so that the
// gc.root lowering code doesn't run.
InitRoots = false;
NeededSafePoints = 0;
UsesMetadata = false;
CustomRoots = false;
}
Optional<bool> isGCManagedPointer(const Type *Ty) const override {
// Method is only valid on pointer typed values.
const PointerType *PT = cast<PointerType>(Ty);
// We pick addrspace(1) as our GC managed heap.
return (1 == PT->getAddressSpace());
}
};
/// A GCStrategy for the Mono Runtime.
class MonoGC : public GCStrategy {
public:
MonoGC() {
UseStatepoints = true;
// These …
```
=> [llvm] Use CoreCLR GC interop configuration

configure.ac, mono/mini/aot-compiler.c
Without this, the Mono build won't actually succeed the first time on a fresh run. The wrong opt/llc are used. The builder has to stop and export the directory here to make it work. This invalidates our instructions we've always been giving about building with the one-liner of autogen and make.
This is sidestepped on linux in practice with a patch: 
https://github.com/mono/linux-packaging-mono/blob/centos/llvm_llc_opt_default_path.patch
But I'd like to fix the OSX build and remove the need for a patch in order to build Mono with LLVM out of the box.
=> [build] Provide in-tree llvm to mono correctly

mono/mini/intrinsics.c, mono/mini/mini.h
=> [jit] Also allow System.Runtime.CompilerServices.Unsafe intrinsics from the System.Runtime.CompilerServices assembly, not just corlib.

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/mini/mini-arm.c, mono/mini/mini-mips.c, mono/mini/mini-ppc.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini-s390x.c, mono/mini/patch-info.h
It is not used, and it had a larger than pointer field
where a pointer was required, at least for 32bit hosted cross builds.
By "unused", I'm assuming nobody does math on these enums to forms ones, that I don't see via textual search.
=> Remove MONO_PATCH_INFO_METHOD_REL.

mono/metadata/jit-icall-reg.h, mono/mini/mini-runtime.h
Alternative to https://github.com/mono/mono/pull/14641.
=> Widen MonoJumpInfo union to pointer-sized so mono_add_patch_info can just use target field blindly.

mcs/class/System/monotouch_runtime_System.dll.exclude.sources, mcs/class/System/monotouch_tv_runtime_System.dll.exclude.sources
They were missing some exclude files that caused unnecessary p/invokes to be retained.
Fixes https://github.com/mono/mono/issues/13526
Backport of #14077.
=> [master] [2018-10] [System] Fix monotouch_runtime repl assemblies

mcs/class/System/monotouch_runtime_System.dll.exclude.sources, mcs/class/System/monotouch_tv_runtime_System.dll.exclude.sources
They were missing some exclude files that caused unnecessary p/invokes to be retained.
Fixes https://github.com/mono/mono/issues/13526
Backport of #14077.
/cc @kg @akoeplinger
=> [2019-02] [System] Fix monotouch_runtime repl assemblies

mcs/class/System/monotouch_runtime_System.dll.exclude.sources, mcs/class/System/monotouch_tv_runtime_System.dll.exclude.sources
They were missing some exclude files that caused unnecessary p/invokes to be retained.
Fixes https://github.com/mono/mono/issues/13526
Backport of #14077.
/cc @kg @akoeplinger
=> [2019-04] [System] Fix monotouch_runtime repl assemblies

mono/mini/interp/interp.c, mono/mini/mini-amd64.c, mono/mini/tramp-amd64.c
First set of fixes to get the following tests working under interpreter on Windows x64:
* mono/mini richeck
* mono/mini mixedcheck
* mono/mini fullaotmixedcheck
* mono/tests winx64structs.exe
Fixes are primarily related to Windows x64 ABI support in interpreter. Fixes also makes sure our interpreter trampolines get unwind info making it possible to debug through the trampolines on Windows x64.
Several fixes related to value types was needed, also fixed support for return value types not fitting into registers, current implementation didn't return passed in value type address in return register as mandated by both System V and Win x64 ABI's.
Identified and fixed memory leak on every pinvoke from interpreter that needs stack. Since Windows x64 ABI always use 32 bytes of stack allocated by …
=> Fix interpreter mini regression test on Windows x64.

mono/eglib/glib.h, mono/metadata/monitor.c, mono/mini/method-to-ir.c, mono/utils/mono-rand.c
ifdef __cplusplus
define g_static_assert(x) static_assert (x, "")
else
define g_static_assert(x) g_assert (x)
endif
It is, granted, C++11, not C++98, and some C variations.
=> Introduce g_static_assert.

mono/mini/interp/interp.c
Interpreter frame was 1248 bytes in size under Windows MSVC. This was almost double the size of other platforms ~670 bytes. After investigating different constructs in interpreter switch statement in interp_exec_method_full, it turns out that local declared errors couldn't be reused over different case statements and added ~100 bytes each. Switching local declared errors to shared one, reduce the stack size down to ~670 bytes under Windows MSVC.
=> Reduce stack size used by interpreter frame on Windows MSVC.

scripts/ci/run-jenkins.sh, sdks/builds/ios.mk, sdks/builds/mac.mk, sdks/versions.mk
Otherwise the Xcode linker tries to guess the version from the path,
and since we use Xcode101.app it'd use sdk=101 as the version which is wrong.
By explicitly specifying e.g. `$(XCODE_DIR)/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk`
as the sysroot it correctly guesses sdk=12.1 instead.
See also https://github.com/xamarin/xamarin-macios/commit/834c0a9fd7062c0c25011721fd7d524b8a60b41e
=> [sdks] Explicitly set version of the mac/ios/watchos/tvos platform SDKs

configure.ac, llvm/build.mk, mono/mini/Makefile.am.in, sdks/builds/android.mk, sdks/builds/llvm.mk
We used to use the static MXE toolchain, but after switching to Homebrew we have to ask for static linking explicitly.
=> [sdks] Statically link LLVM and Android MXE cross builds

configure.ac, llvm/build.mk, mono/mini/Makefile.am.in, sdks/builds/android.mk, sdks/builds/llvm.mk
Backport of #14283 to `2019-02`
---
We used to use the static MXE toolchain, but after switching to Homebrew we have to ask for static linking explicitly.
=> [2019-02][sdks] Statically link LLVM and Android MXE cross builds

mono/mini/mini-generic-sharing.c
The passed arguments are already considered to be gpointer in interp_entry and the real value is obtained using stackval_from_data. For types that are passed by value in a register the wrappers will be identical and we can share them.
This commit reduces the size used by interp_in wrappers (in fullaot-interp) by half. These wrappers still take a fair amount of size, which comes mainly from signatures including value types, which aren't shared.
=> [interp] Share more wrappers for different interp in signatures

mono/mini/driver.c
It makes sense to pass --interp (--interp=-inline) while having another execution mode previously set up (like --full-aot-interp).
Cleanup code a little bit by killing mono_enable_interp which doesn't do much.
=> [interp] Make --interp= not override last set execution mode

mcs/class/corlib/System.Reflection.Emit/AssemblyBuilder.pns.cs, mcs/class/corlib/System.Reflection.Emit/ModuleBuilder.pns.cs
The original PR#14682 (manual backport from master) still had a few
differences specific to `2019-02`. This PR removes them
Added properties:
```csharp
public override string EscapedCodeBase { get; }
public override System.Security.Policy.Evidence Evidence { get; }
```
Added method:
```csharp
public override string ToString ();
```
Added interface:
```csharp
System.IEquatable<EventToken>
```
Added interface:
```csharp
System.IEquatable<FieldToken>
```
Added interface:
```csharp
System.IEquatable<MethodToken>
```
Added interface:
```csharp
System.IEquatable<ParameterToken>
```
Added interface:
```csharp
System.IEquatable<PropertyToken>
```
Added interface:
```csharp
System.IEquatable<SignatureToken>
```
Added interface:
```csharp
System.IEquatable<StringToken>
```
Added interface: …
=> [2019-02][mscorlib] Ensure monotouch[_runtime] API are identical

netcore/Makefile, netcore/metapackage.nuspec
Works in local testing.
```
directhex@breakfast:~/Projects/mono/artifacts$ nuget sources add -name moo -source .
Package source with Name: moo added successfully.
directhex@breakfast:~/Projects/mono/artifacts$ nuget install Microsoft.NETCore.Runtime.Mono
Feeds used:
https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
https://api.nuget.org/v3/index.json
/home/directhex/Projects/mono/.
Installing package 'Microsoft.NETCore.Runtime.Mono' to '/home/directhex/Projects/mono/artifacts'.
GET https://api.nuget.org/v3/registration3-gz-semver2/microsoft.netcore.runtime.mono/index.json
NotFound https://api.nuget.org/v3/registration3-gz-semver2/microsoft.netcore.runtime.mono/index.json 330ms
GET https://dotnetfeed.blob.core.windows.net/dotnet-core/registration/microsoft.netcore.runtime.mono …
```
=> [netcore] Add a metapackage for all supported runtimes

scripts/ci/pipeline-netcore-runtime.yml
`/Users/vsts/agent/2.150.3/work/1/s/eng/publishwitharcade.proj(40,5): error : Package already exists: Microsoft.NETCore.Runtime.Mono 6.3.0.789.`
=> [netcore] Fix duplicate publishing of metapackage

mcs/class/corlib/monodroid_corlib_xtest.dll.exclude.sources
The test case CopyFileWithData_MemberData with input of size 1024 * 1024 * 10
causes the Xamarin.Android.Bcl_Tests to crash for some reason.  Temporarily
exclude this entire set of tests from running.
Also disable System.IO.Tests.FileInfo_CopyTo_str because it derives from the
above test class.
Backport of #14133.
=> [master] [monodroid] Exclude System.IO.Tests.File_Copy_str_str CoreFX testsuite

mono/metadata/icall-def.h, mono/metadata/marshal-ilgen.c, mono/metadata/method-builder-ilgen.c, mono/mini/aot-compiler.c, mono/mini/tramp-amd64.c, mono/utils/mono-state.c
Warnings resolved, in no particular order:
```
mono-state.c:265:14: warning: incompatible pointer to integer conversion assigning to 'gint' (aka 'int') from 'void *' [-Wint-conversion]
mem->handle = NULL;
marshal.c:5550:1: warning: no previous prototype for function 'ves_icall_System_Runtime_InteropServices_Marshal_IsPinnableType' [-Wmissing-prototypes]
ves_icall_System_Runtime_InteropServices_Marshal_IsPinnableType (MonoReflectionTypeHandle type_h, MonoError *error)
method-builder-ilgen.c:549:33: warning: unused variable 'jit_icall_info' [-Wunused-variable]
MonoJitICallInfo const * const jit_icall_info = mono_find_jit_icall_info (jit_icall_id);
marshal-ilgen.c:6546:22: warning: unused variable 'func' [-Wunused-variable]
gconstpointer const func = callinfo->func;
aot-compiler.c:7199:82: …
```
=> Batch of runtime warning fixes on Darwin

mcs/class/System.Windows.Forms/System.Windows.Forms/ThemeWin32Classic.cs
If you use a ListViewGroup with a dark theme, the text is light on light:
It's using `SystemBrushes.ControlText`, which is not guaranteed to contrast with the background, which is `SystemColor.Window` and contrasts with `WindowText`.
On Windows these are drawn in a nice shade of blue:
So now mono will use `SystemBrushes.Highlight` to mimic that nice blue:
I think `Highlight` will contrast well with `Window`, and also look better in a dark theme.
(I was not able to get my locally compiled mono to obey a dark theme, but I'm 100% sure that's not caused by this change. If there are any known quirks related to that, I'd love some tips on how to fix it.)
=> Fix light on light ListViewGroup headers on dark theme

mono/metadata/marshal.c
When passing a delegate to native code, we pass the delegate_trampoline which can be used to invoke the delegate from native code and we store this mapping (delegate_trampoline->delegate) in a hashtable so we can get a delegate for the delegate_trampoline, when marshalling the opposite way. If we are trying to marshal a ftnptr (for managed code) to a delegate and we don't find this mapping we can crash. This could happen if the finalization for some other delegate that uses the same ftnptr removes this entry from the table. We solve this by never freeing these entries. The first delegate-ftnptr pair will always be alive. This is easier, faster and potentially uses less memory than tracking in the hashtable every pair. There should be a small and limited set of methods marshalled to …
=> [marshal] Fix race between delegate marshaling and finalization

mono/metadata/marshal.c
When passing a delegate to native code, we pass the delegate_trampoline which can be used to invoke the delegate from native code and we store this mapping (delegate_trampoline->delegate) in a hashtable so we can get a delegate for the delegate_trampoline, when marshalling the opposite way. If we are trying to marshal a ftnptr (for managed code) to a delegate and we don't find this mapping we can crash. This could happen if the finalization for some other delegate that uses the same ftnptr removes this entry from the table. We solve this by never freeing these entries. The first delegate-ftnptr pair will always be alive. This is easier, faster and potentially uses less memory than tracking in the hashtable every pair. There should be a small and limited set of methods marshalled to …
=> [2019-04] [marshal] Fix race between delegate marshaling and finalization

mono/metadata/marshal.c
When passing a delegate to native code, we pass the delegate_trampoline which can be used to invoke the delegate from native code and we store this mapping (delegate_trampoline->delegate) in a hashtable so we can get a delegate for the delegate_trampoline, when marshalling the opposite way. If we are trying to marshal a ftnptr (for managed code) to a delegate and we don't find this mapping we can crash. This could happen if the finalization for some other delegate that uses the same ftnptr removes this entry from the table. We solve this by never freeing these entries. The first delegate-ftnptr pair will always be alive. This is easier, faster and potentially uses less memory than tracking in the hashtable every pair. There should be a small and limited set of methods marshalled to …
=> [2019-02] [marshal] Fix race between delegate marshaling and finalization

mono/metadata/metadata.h
Used by the `MONO_CLASS_IS_INTERFACE` macro.
Fixes https://github.com/mono/mono/issues/14005
=> [metadata] Mark mono_type_is_generic_parameter as a MONO_API

mono/metadata/custom-attrs.c
All the CustomAttribute initializer names (fields, property) except the last were leaked. Ensure all names are freed.
Fixes #14543
Backport of #14544.
/cc @marek-safar @Therzok
=> [2019-04] Plug leak of CustomAttribute initializer name

mono/metadata/coree.c, mono/metadata/file-mmap-posix.c, mono/metadata/file-mmap-windows.c, mono/metadata/w32process-unix.c, mono/metadata/w32process-win32.c, mono/metadata/w32semaphore-unix.c, mono/metadata/w32semaphore-win32.c, mono/utils/mono-dl.c, mono/utils/mono-mmap.c
If this was not possible due to them being called during runtime initialization, a short comment was left noting the specific reason why.
Fixes https://github.com/mono/mono/issues/14377
This definitely needs a careful review, in particular the w32-process* files. Those, along with the other platform-specific ones, could potentially benefit from a more thorough audit, but it's rather difficult to tell what is and isn't being called during initialization. I've tried to be thorough on everything mentioned in the issue.
This includes a couple other random fixes I noticed on the way, which I can split off into a separate PR if preferable.
=> [coop] Add GC safe transitions around blocking OS API calls

mono/utils/mono-mmap.c
Fixes #14594
This should make the behavior consistent with Windows. The commit adding the emscripten-related length check didn't specify the exact exception, so I just put something that's as descriptive as possible.
=> Propagate error in mono_file_map_error on posix implementation

packaging/MacSDK/packaging/resources/postinstall
Backport of #14735.
/cc @alexischr
=> [2019-02] [MacSDK] Properly handle PATHs with spaces during package post-install

packaging/MacSDK/packaging/resources/postinstall
Backport of #14735.
/cc @alexischr
=> [2019-06] [MacSDK] Properly handle PATHs with spaces during package post-install

packaging/MacSDK/packaging/resources/postinstall
Backport of #14735.
/cc @alexischr
=> [2018-10] [MacSDK] Properly handle PATHs with spaces during package post-install

mono/mini/exceptions-arm64.c
=> [2018-08] [arm64] Correct exception filter stack frame size

mono/mini/exceptions-arm64.c
=> [2019-02] [arm64] Correct exception filter stack frame size

configure.ac
This bumps to release roslyn 3.1.0. Currently pointing to my branch and not roslyn-binaries (will merge to binaries repo once CI says it works)
=> Bump roslyn to release 3.1.0

mono/mini/exceptions-arm64.c
=> [2019-06] [arm64] Correct exception filter stack frame size

mono/mini/exceptions-arm64.c
=> [2018-10] [arm64] Correct exception filter stack frame size

mono/metadata/w32process-win32.c
https://github.com/mono/mono/commit/5d088cf0de7f3e50e3547dba361af4401e938dd4 exposed a problem with an uninitialized variable, only exposed on some build configurations, 32-bit Windows release builds.
=> Change in process_complete_path exposed uninitialized variable error.

configure.ac
https://github.com/mono/mono/pull/14607 broke LLVM build on Windows MSVC. This is just a quick fix falling back to old behavior on Windows MSVC. Since all LLVM tools will be available in the same folder as mono runtime binary there is no specific need to point out other build folders hosting LLVM tooling.
=> Fix LLVM build break on Windows MSVC.

packaging/MacSDK/msbuild.py, packaging/MacSDK/nuget.py
- this updates to upstream vs16.1 branch
- updates to nuget 5.1
=> [msbuild] Bump to track mono-2019-02 HEAD

configure.ac, mono/utils/mono-os-mutex.h
Android doesn't always declare that function.
Alternative to #14798
=> [runtime] Autoconf check for pthread_mutexattr_setprotocol

configure.ac, mono/utils/mono-os-mutex.h
Android doesn't always declare that function.
Alternative to #14798
Backport of #14799.
/cc @akoeplinger @lambdageek
=> [2019-06] [runtime] Autoconf check for pthread_mutexattr_setprotocol

mono/utils/mono-threads-windows.c, msvc/mono.vcxproj
On Windows default thread stack size has been 1MB for a long time (both 32/64-bit). When starting to use interpreter some of the tests include deep recursions that will hit stackoverflow on Windows(ackermann.exe as one example). This commit adjust the default reserved stack size to 8MB for debug builds and 1.5MB for release builds (same as coreclr), for main thread only. All other threads will still default to 1MB stack size (both debug/release).
=> Increase main thread stack size on Windows.

mcs/mcs/tuples.cs, mcs/tests/test-tuple-11.cs, mcs/tests/ver-il-net_4_x.xml
Before the code
(a, b) = (b, a);
was the equivalent of
a = b;
b = a;
now, it evaluates it to so something like
tmp1 = a;
tmp2 = b;
a = tmp2;
b = tmp1;
This change only applies to tuple literals because I don't think other tuples are able to overwrite themselves.
Fixes #11334
=> Align mcs's tuple deconstruction behavior with csc

mono/metadata/assembly.c
Closes: #14366
Fixes Mac package failures during IronRuby compilation
```
Mono: The request to load the assembly System.Numerics.Vectors v4.1.3.0 was remapped to v4.0.0.0
Mono: Assembly Loader probing location: '/tmp/monoprefix/lib/mono/gac/System.Numerics.Vectors/4.1.3.0__b03f5f7f11d50a3a/System.Numerics.Vectors.dll'.
Mono: Assembly Loader probing location: '/tmp/monoprefix/lib/mono/msbuild/Current/bin/Roslyn/System.Numerics.Vectors.dll'.
Mono: Assembly Loader probing location: '/tmp/monoprefix/lib/System.Numerics.Vectors.dll'.
Mono: Assembly Loader probing location: '/tmp/monoprefix/lib/mono/4.5//Facades/System.Numerics.Vectors.dll'.
Mono: Assembly Loader probing location: '/tmp/monoprefix/lib/mono/gac/System.Numerics.Vectors/4.1.3.0__b03f5f7f11d50a3a/System.Numerics.Vectors.exe'.
Mono: …
```
=> [2019-02] Remapping should affect GAC search paths considered by the loader

mono/mini/exceptions-arm64.c
=> [arm64] Correct exception filter stack frame size

mono/mini/basic.cs, mono/mini/objects.cs, mono/mini/ssa.c
=> [jit] Treat ternary operations as non-constant during constant evaluation and propagation

sdks/wasm/Makefile
By default, emscripten removes C++ exception support if not used explicitly in the main module.
This PR forces emscripten to keep C++ exception support so that side modules loaded via dynamic linking can function properly.
=> [Wasm] Enforce C++ exception support for the release-dynamic configuration

packaging/MacSDK/msbuild.py
Picks up changes in msbuild after:
[2019-02] Bump roslyn to 3.1.0, matching what mono uses
(https://github.com/mono/msbuild/pull/109)
=> Bump msbuild to track mono-2019-02

configure.ac, mono/utils/mono-md5.c, mono/utils/mono-threads-mach-helper.c
1) CC_MD5_Init, CC_MD5_Update and CC_MD5_Final are deprecated.
```c
mono-md5.c:45:2: error: 'CC_MD5_Init' is deprecated: first deprecated in macOS 10.15 - This function is
cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256
(or stronger). [-Werror,-Wdeprecated-declarations]
CC_MD5_Init (ctx);
^
```
2) 
```
mono-threads-mach-helper.c:95:17: error: too many arguments to function call, expected 0, have 2
objc_msgSend (value, release);
~~~~~~~~~~~~  ^~~~~~~~~~~~~~
```
XCode has a special switch `Enable Strict Checking of objc_msgSend Calls` which is now `true` by default? anyway it's fixed by `-DOBJC_OLD_DISPATCH_PROTOTYPES=1` flag
3) Fixes https://github.com/mono/mono/issues/14793
No idea how it worked on pre 10.15 without `-framework GSS` 🤔
=> Fix build on macOS 10.15 Catalina + xcode 11

configure.ac, mono/utils/mono-md5.c, mono/utils/mono-threads-mach-helper.c
1) CC_MD5_Init, CC_MD5_Update and CC_MD5_Final are deprecated.
```c
mono-md5.c:45:2: error: 'CC_MD5_Init' is deprecated: first deprecated in macOS 10.15 - This function is
cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256
(or stronger). [-Werror,-Wdeprecated-declarations]
CC_MD5_Init (ctx);
^
```
2) 
```
mono-threads-mach-helper.c:95:17: error: too many arguments to function call, expected 0, have 2
objc_msgSend (value, release);
~~~~~~~~~~~~  ^~~~~~~~~~~~~~
```
XCode has a special switch `Enable Strict Checking of objc_msgSend Calls` which is now `true` by default? anyway it's fixed by `-DOBJC_OLD_DISPATCH_PROTOTYPES=1` flag
3) Fixes https://github.com/mono/mono/issues/14793
No idea how it worked on pre 10.15 without `-framework GSS` 🤔 …
=> [2019-02] Fix build on macOS 10.15 Catalina + xcode 11

configure.ac, mono/utils/mono-md5.c, mono/utils/mono-threads-mach-helper.c
1) CC_MD5_Init, CC_MD5_Update and CC_MD5_Final are deprecated.
```c
mono-md5.c:45:2: error: 'CC_MD5_Init' is deprecated: first deprecated in macOS 10.15 - This function is
cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256
(or stronger). [-Werror,-Wdeprecated-declarations]
CC_MD5_Init (ctx);
^
```
2) 
```
mono-threads-mach-helper.c:95:17: error: too many arguments to function call, expected 0, have 2
objc_msgSend (value, release);
~~~~~~~~~~~~  ^~~~~~~~~~~~~~
```
XCode has a special switch `Enable Strict Checking of objc_msgSend Calls` which is now `true` by default? anyway it's fixed by `-DOBJC_OLD_DISPATCH_PROTOTYPES=1` flag
3) Fixes https://github.com/mono/mono/issues/14793
No idea how it worked on pre 10.15 without `-framework GSS` 🤔 …
=> [2019-06] Fix build on macOS 10.15 Catalina + xcode 11

mono/utils/mono-threads.c
[thread] Print function name when asserting MonoThreadInfo is non-NULL.
=> [thread] Print function name when asserting MonoThreadInfo is non-NULL

scripts/ci/pipeline/sdks-archive.groovy, sdks/builds/Makefile
It has way better compression performance.
Kept WebAssembly on .zip for now since external users took dependencies on it [1].
Fixes https://github.com/mono/mono/issues/14215
[1] https://github.com/nventive/Uno.Wasm.Bootstrap/blob/e2bf8946e162642ca1bdf4f003f8de4a94954f73/Readme.md#updating-the-mono-sdk-build
=> [sdks] Use 7z format for the android/ios/mac archives

scripts/ci/pipeline/sdks-archive.groovy, sdks/builds/Makefile
It has way better compression performance.
Kept WebAssembly on .zip for now since external users took dependencies on it [1].
Fixes https://github.com/mono/mono/issues/14215
[1] https://github.com/nventive/Uno.Wasm.Bootstrap/blob/e2bf8946e162642ca1bdf4f003f8de4a94954f73/Readme.md#updating-the-mono-sdk-build
Backport of #14837.
=> [2019-06] [sdks] Use 7z format for the android/ios/mac archives

mcs/class/System.Private.CoreLib/System/Environment.cs, mono/metadata/icall-decl.h, mono/metadata/icall-def-netcore.h, mono/metadata/icall.c, netcore/.gitignore, netcore/CoreFX.issues.rsp, netcore/Makefile, netcore/build.sh, netcore/corefx-restore.csproj, netcore/sample/AspNetCore/Startup.cs
Improve `netcore/build.sh` script:
1) Run `.autogen.sh` only once (creates `.configured` file as a sign - let me know if you don't like this file name)
2) Added `--rebuild` flag to run `.autogen.sh` despite the `.configured` file
3) Added `--skipnative` and `--skipmscorlib` for consistency with coreclr's build.sh
4) `xtestall` rule didn't run tests if it needed to download them first (so you had to run it twice)
Also, bump corefx and coreclr versions (to preview7) and ignore new failures in xtestall.
=> [netcore] Improve netcore/build.sh script

mono/metadata/image-internals.h, mono/metadata/image.c, mono/mini/driver.c
If we cause the AOT step to return a nonzero exit code, it makes failing to compile the "problematic" assemblies pretty disruptive. It means that suddenly the build systems need to filter all of these assemblies to use Mono.
If the "problematic" assembly can just be skipped, we should be able to just turn the AOT step into a "no-op".
This PR does that.
Fixes issue described here: https://github.com/mono/mono/issues/13941
=> [runtime] Gracefully skip AOTing problematic assemblies

mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/14243
=>  [llvm] emit call to mini_llvmonly_throw_nullref_exception without exceptions in mind

mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/14243
Backport of #14840.
/cc @lewurm
=> [2019-06]  [llvm] emit call to mini_llvmonly_throw_nullref_exception without exceptions in mind

mono/metadata/domain.c
Fixes #12141 
Switched to a list because in theory any number of tags can be present. Old behavior was to put them into an array of size 3 and zero the byte following them, which was causing the crash with more than two tags. There's no null check for the default runtime because that should never happen, and the list is reversed to preserve the order from the XML. Changing the signature of `get_runtimes_from_exe` should be fine because it's static and only called in the one place.
=> Switch supported runtimes storage from an array to a list

sdks/builds/ios.mk
Fixes https://github.com/mono/mono/issues/14841
Note that it breaks iOS 32bit on devices. The Apple Watch _might_ still works (only tested on `2019-02`).  It unblocks some build related issues on the Xamarin.iOS `2019-06` integration, and we have to do it anyway. I'll come back to it to fix device related issues.
=> [ios] switch cross32/crosswatch to be executed on x86_64 and use newer LLVM

sdks/builds/ios.mk
Fixes https://github.com/mono/mono/issues/14841
Note that it breaks iOS 32bit on devices. The Apple Watch _might_ still works (only tested on `2019-02`).  It unblocks some build related issues on the Xamarin.iOS `2019-06` integration, and we have to do it anyway. I'll come back to it to fix device related issues.
Backport of #14852.
=> [2019-06] [ios] switch cross32/crosswatch to be executed on x86_64 and use newer LLVM

netcore/CoreFX.issues.rsp
These tests were disabled because of #14555 which was fixed in a5a26a2f92d00ab174d794f077007faaab5d3843, but the tests were not reenabled as pointed out [here](https://github.com/mono/mono/issues/14555#issuecomment-499652206). That was an oversight and this corrects it.
=> Remove exclusions stemming from resolved type check bug

mcs/class/corlib/ReferenceSources/MethodBase.cs, mcs/class/corlib/Test/System/AppDomainTest.cs, mcs/class/corlib/corefx/MethodInfo.cs, mono/metadata/remoting.c
If we have a ref struct and a method that takes it as an argument:
```
[Serializable]
public ref struct R {
public int i;
}
public interface I {
public void M1 (R r, SomeClass o);
}
public class M : MarshalByRefObject, I {
public void M1 (R r, SomeClass o) { ... }
}
```
If we create an instance of M in another domain and try to call it:
```
I obj = (I)otherDomain.CreateInstanceAndUnwrap (typeof(M).Assembly.FullName,
nameof(M));
R r;
r.i = 42;
SomeClass o = ...;
obj.M1 (r, o);
```
Mono will need to create a wrapper that can invoke M.M1 in the other domain. The way the wrapper works in `mono_marshal_get_xappdomain_invoke` is by creating an array of all the arguments that need to be serialized (see `mono_get_xdomain_marshal_type`) and then serializing the whole array (by calling out to …
=> [2019-02] [runtime] Make cross-appdomain wrappers throw NIE for methods with ref struct args

mcs/class/corlib/ReferenceSources/MethodBase.cs, mcs/class/corlib/Test/System/AppDomainTest.cs, mcs/class/corlib/corefx/MethodInfo.cs, mono/metadata/remoting.c
If we have a ref struct and a method that takes it as an argument:
```
[Serializable]
public ref struct R {
public int i;
}
public interface I {
public void M1 (R r, SomeClass o);
}
public class M : MarshalByRefObject, I {
public void M1 (R r, SomeClass o) { ... }
}
```
If we create an instance of M in another domain and try to call it:
```
I obj = (I)otherDomain.CreateInstanceAndUnwrap (typeof(M).Assembly.FullName,
nameof(M));
R r;
r.i = 42;
SomeClass o = ...;
obj.M1 (r, o);
```
Mono will need to create a wrapper that can invoke M.M1 in the other domain. The way the wrapper works in `mono_marshal_get_xappdomain_invoke` is by creating an array of all the arguments that need to be serialized (see `mono_get_xdomain_marshal_type`) and then serializing the whole array (by calling out to …
=> [runtime] Make cross-appdomain wrappers throw NIE for methods with ref struct args

mcs/class/corlib/ReferenceSources/MethodBase.cs, mcs/class/corlib/Test/System/AppDomainTest.cs, mcs/class/corlib/corefx/MethodInfo.cs, mono/metadata/remoting.c
If we have a ref struct and a method that takes it as an argument:
```
[Serializable]
public ref struct R {
public int i;
}
public interface I {
public void M1 (R r, SomeClass o);
}
public class M : MarshalByRefObject, I {
public void M1 (R r, SomeClass o) { ... }
}
```
If we create an instance of M in another domain and try to call it:
```
I obj = (I)otherDomain.CreateInstanceAndUnwrap (typeof(M).Assembly.FullName,
nameof(M));
R r;
r.i = 42;
SomeClass o = ...;
obj.M1 (r, o);
```
Mono will need to create a wrapper that can invoke M.M1 in the other domain. The way the wrapper works in `mono_marshal_get_xappdomain_invoke` is by creating an array of all the arguments that need to be serialized (see `mono_get_xdomain_marshal_type`) and then serializing the whole array (by calling out to …
=> [2019-06] [runtime] Make cross-appdomain wrappers throw NIE for methods with ref struct args

mcs/class/System.Core/System.Security.Cryptography.X509Certificates/RSACertificateExtensions.cs, mcs/class/System/System.Net/HttpListener.Mono.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2Impl.cs, mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509CertificateImpl.cs, mcs/tools/security/Makefile, mcs/tools/security/httpcfg.cs
Since `RSACertificateExtensions` lives in `System.Core` and only `mscorlib` internals (but not `System` internals) are visible to it, we need to use a little trick here:
* System.Security.Cryptography.X509Certificates.X509CertificateImpl:
add new abstract methods CopyWithPrivateKey() and CreateCertificate().
* System.Security.Cryptography.X509Certificates.X509Certificate2Impl:
sealed implement them here.
The `httpcfg` tool, only checks whether the key is valid, so we don't really need to call `CopyWithPrivateKey()` (which requires us to take a dependency on `System.Core`).
Fixes https://github.com/mono/mono/issues/14152.
=> Implement RSACertificateExtensions.CopyWithPrivateKey().  #14152.

mono/mini/basic.cs, mono/mini/objects.cs, mono/mini/ssa.c
Fixes #13873
Backport of #14782.
/cc @marek-safar @imhameed
=> [2019-02] [jit] Treat ternary operations as non-constant during constant evaluation and propagation

mono/eglib/eglib-remap.h, mono/eglib/glib.h, mono/mini/mini-posix.c, mono/utils/mono-linked-list-set.h, mono/utils/mono-merp.c, mono/utils/mono-state.c
Previously, we would simply print the mapping to stdout. 
Since the pointers that are embedded into crash reports will point into these native modules, providing the mapping to module names helps someone debugging using the JSON to track down where a pointer came from.
Example report: https://gist.github.com/alexanderkyte/578b4e2f82a0e71a169c37d8bc18a305
Because of the fact that this is sending file paths from the end-user's machine, I have disabled it when we have crash privacy enabled.
=> [crash] Move /proc/self/maps crash collection to created JSON blob

packaging/MacSDK/msbuild.py
Picks up changes in msbuild after:
[mono] Update SDKs to track cli branch `release/2.1.8xx`
(https://github.com/mono/msbuild/pull/110)
=> Bump msbuild to track xplat-master

mcs/class/System.Core/System.Security.Cryptography.X509Certificates/RSACertificateExtensions.cs, mcs/class/System/System.Net/HttpListener.Mono.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2Impl.cs, mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509CertificateImpl.cs, mcs/tools/security/Makefile, mcs/tools/security/httpcfg.cs
_Manual backport of https://github.com/mono/mono/pull/14860._
* Implement RSACertificateExtensions.CopyWithPrivateKey().  #14152.
* RSACertificateExtensions.CopyWithPrivateKey(): implement.
Since `RSACertificateExtensions` lives in `System.Core` and only `mscorlib`
internals (but not `System` internals) are visible to it, we need to use a
little trick here:
* System.Security.Cryptography.X509Certificates.X509CertificateImpl:
add new abstract methods CopyWithPrivateKey() and CreateCertificate().
* System.Security.Cryptography.X509Certificates.X509Certificate2Impl:
sealed implement them here.
The `httpcfg` tool, only checks whether the key is valid, so we don't really
need to call `CopyWithPrivateKey()` (which requires us to take a dependency
on `System.Core`).
* Do the same thing in …
=> [2019-02] Implement RSACertificateExtensions.CopyWithPrivateKey().  #14152. (#14860).

sdks/wasm/driver.c
Fixed the real issue, where the malloc was not requesting the proper structure size.
~~This change avoids the inclusion of the emscripten `dlmalloc` library which seems to have stability issues (memory overwrite on allocation) using the release-dynamic configuration.~~
=> [Wasm] Fix memory override in mono_wasm_add_assembly

mcs/class/System.Core/System.Security.Cryptography.X509Certificates/RSACertificateExtensions.cs, mcs/class/System/System.Net/HttpListener.Mono.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2Impl.cs, mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509CertificateImpl.cs, mcs/tools/security/Makefile, mcs/tools/security/httpcfg.cs
Since `RSACertificateExtensions` lives in `System.Core` and only `mscorlib` internals (but not `System` internals) are visible to it, we need to use a little trick here:
* System.Security.Cryptography.X509Certificates.X509CertificateImpl:
add new abstract methods CopyWithPrivateKey() and CreateCertificate().
* System.Security.Cryptography.X509Certificates.X509Certificate2Impl:
sealed implement them here.
The `httpcfg` tool, only checks whether the key is valid, so we don't really need to call `CopyWithPrivateKey()` (which requires us to take a dependency on `System.Core`).
Fixes https://github.com/mono/mono/issues/14152.
Backport of #14860.
/cc @baulig
=> [2019-06] Implement RSACertificateExtensions.CopyWithPrivateKey().  #14152.

mono/metadata/class-internals.h, mono/metadata/icall.c, mono/metadata/jit-icall-reg.h, mono/mini/calls.c, mono/mini/decompose.c, mono/mini/method-to-ir.c, mono/mini/mini-amd64.c, mono/mini/mini-arm64.c, mono/mini/mini-codegen.c, mono/mini/mini-llvm.c, mono/mini/mini-runtime.c, mono/mini/mini-s390x.c, mono/mini/mini-sparc.c, mono/mini/mini-x86.c, mono/mini/mini.c, mono/mini/mini.h, mono/mini/tramp-wasm.c
Due to https://github.com/mono/mono/pull/11941#issuecomment-449157323.
-  Work toward removing JIT icall hashing by address.
Mostly remove it, assert it isn't needed/used.
- Actually remove JIT icall hashing by address.
=> Remove JIT icall hashing by address.

mono/mini/interp/interp.c, mono/mini/mini-runtime.h, mono/utils/win64.asm
INTERP_PUSH_LMF_WITH_CTX_BODY is not fully supported under Windows MSVC since that compiler doesn't support taking address from a label, needed by current implementation to correctly resume after unwinding exceptions happening in native frames as tested by install_eh_callback.exe.
This fix add support to restore to a known location and use a flag indicating if we have been resumed to the location or just passing by for the first time. If we resume it will transfer control to specified label. This will mimic the behavior of taking the address of a label and use that address as the resume point.
I also considered switching to setjmp/longjmp but that would have had a bigger impact on all platforms and needed changes into the resume context machinery as well.
While doing the implementation I …
=> Fix interpreter failure in install_eh_callback.exe under Windows x64 MSVC.

mono/mini/Makefile.am.in
Prevent the SDKs from making dangling symlinks when packaging the MXE
cross-compilers: should hav
mono.exe -> mono-sgen.exe
rather than
mono -> mono-sgen (dangling).
Backport of #14958.
=> [2019-06] [install] Include .exe extension when symlinking the mono binary

mono/mini/Makefile.am.in
Prevent the SDKs from making dangling symlinks when packaging the MXE
cross-compilers: should hav
mono.exe -> mono-sgen.exe
rather than
mono -> mono-sgen (dangling).
Backport of #14958.
=> [2019-02] [install] Include .exe extension when symlinking the mono binary

mono/mini/Makefile.am.in
Prevent the SDKs from making dangling symlinks when packaging the MXE
cross-compilers: should have
mono.exe -> mono-sgen.exe
rather than
mono -> mono-sgen (dangling)
=> [install] Include .exe extension when symlinking the mono binary

mono/mini/mini-llvm.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h
Previously we disabled too much runtime format when we disable direct calls. This fixes that.
By putting inlining behind a different flag than direct calls, you can tell if it's the direct call itself or the inlining it enables that leads to a specific bit of observed behavior.
=> [llvm] Fix disabling direct calls and inlining

mono/mini/mini-llvm.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h
Previously we disabled too much runtime format when we disable direct calls. This fixes that.
By putting inlining behind a different flag than direct calls, you can tell if it's the direct call itself or the inlining it enables that leads to a specific bit of observed behavior. 
Backport of #14880.
=> [2019-06] [llvm] Fix disabling direct calls and inlining

mcs/class/corlib/Test/System.Globalization/CalendarTest.cs, mcs/class/corlib/Test/System.Globalization/EastAsianLunisolarCalendarTest.cs, mcs/class/referencesource/mscorlib/system/globalization/japanesecalendar.cs, netcore/System.Private.CoreLib/shared/System/Globalization/JapaneseCalendar.Win32.cs, netcore/System.Private.CoreLib/shared/System/Globalization/JapaneseCalendar.cs
refs: <https://github.com/dotnet/coreclr/pull/23614>
mcs side of the hard coded tables seems referenced from Blazor (client-side), but it's not updated yet.
FYI: <https://qiita.com/jsakamoto/items/da68cee22bbca187f389> (an article which describes this problem, written in Japanese)
=> Fix Japan's new era fallback isn't reflected in Mono

mono/metadata/external-only.c
Fixes https://github.com/mono/mono/issues/14975
Backport of #14979.
=> [2019-02] [runtime] Switch to GC Unsafe for all GC external API functions

mono/mini/aot-compiler.c
Fixes https://github.com/xamarin/xamarin-android/issues/3168.
Backport of #14992.
=> [2019-06] [aot] Open AOT profile files using "rb" so it works on windows.

mcs/class/System.Net.Http/HttpClientHandler.cs, mcs/class/System.Net.Http/IMonoHttpClientHandler.cs, mcs/class/System.Net.Http/MonoWebRequestHandler.cs, mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs, mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.platformnotsupported.cs, mcs/class/System.Net.Http/System.Net.Http/HttpMessageInvoker.cs, mcs/class/System.Net.Http/corefx/SocketsHttpHandler.Mono.cs
* `HttpClientHandler`, `IMonoHttpClientHandler`: add new internal `MonoSetTimeout (TimeSpan)` function.
* `HttpClient.SendAsyncWorker()`: if `handler` is `HttpClientHandler`, call the new internal
`MonoSetTimeout()` function to pass down the timeout.
* `MonoWebRequestHandler.SendAsync()`: this is only used here to pass the timeout to the `HttpWebRequest`.
=> [System.Net.Http]: Add hack to the legacy HttpClient to pass down Timeout property. #12577.

mcs/class/corlib/System.Runtime.CompilerServices/Unsafe.il
Fixes https://github.com/mono/mono/issues/14871.
Backport of #14987.
=> [2019-02] [corlib] Add missing Unsafe.Unbox () method.

mono/metadata/external-only.c
Fixes https://github.com/mono/mono/issues/14975
=> [runtime] Switch to GC Unsafe for all GC external API functions

mono/metadata/debug-mono-ppdb.c
mono_image_open_metadata_only and its callees all dupe the filename string, so free the string after mono_image_open_metadata_only is done with it:
```
1 (128 bytes) ROOT LEAK: 0x7fb07f086c80 [128]  length: 105  "/Users/therzok/Work/md/md-addins/external-addins/MonoDevelop.MonoDroid/build/Xamarin.Installer.Common.pdb"
```
=> Plug leak of ppdb_filename

mono/mini/objects.cs, mono/mini/type-checking.c
Fixes a scenario on platforms with remoting disabled, where casting something to a special interface (like 
IEnumerable<>, IList<> ..) would fail to throw InvalidCastException.
Fixes https://github.com/mono/mono/issues/14729
=> [jit] Fix interface cast

configure.ac
Now that 2019-06 has branched, enable the compiler server by default
=> Enable the compiler server by default

mono/metadata/marshal.c, mono/mini/gshared.cs, mono/mini/mini-generic-sharing.c
Fixes https://github.com/mono/mono/issues/14972.
Backport of #14985.
=> [2019-06] [runtime] Fix gshared support for BeginInvoke ()/EndInvoke () wrappers.

mono/metadata/marshal.c, mono/mini/gshared.cs, mono/mini/mini-generic-sharing.c
Fixes https://github.com/mono/mono/issues/14972.
Backport of #14985.
=> [2019-02] [runtime] Fix gshared support for BeginInvoke ()/EndInvoke () wrappers.

mcs/class/corlib/System.Runtime.CompilerServices/Unsafe.il
Fixes https://github.com/mono/mono/issues/14871.
=> [corlib] Add missing Unsafe.Unbox () method.

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
Trying to unrevert https://github.com/mono/mono/pull/7390.
Couldn't reproduce the same side effect as that caused before.
This PR fixes #7377
Backport of #14773.
/cc @thaystg
=> [2019-06] [Mono.Debugger.Soft] Properly close connections 

mono/metadata/external-only.c
Fixes https://github.com/mono/mono/issues/14975
Backport of #14979.
=> [2019-06] [runtime] Switch to GC Unsafe for all GC external API functions

scripts/ci/pipeline-netcore-runtime.yml
Our run-step logic uses `bc` to calculate step times, so `bc` is
needed to avoid ugly things on the console like:
```
../scripts/ci/./run-step.sh: line 59: echo: write error: Broken pipe
```
=> Install `bc` as a Linux prerequisite

sdks/wasm/aot-profile/gen-profile.js, sdks/wasm/aot-profile/main.cs, sdks/wasm/framework/src/WebAssembly.Bindings/Runtime.cs, sdks/wasm/library_mono.js, sdks/wasm/packager.cs
Current steps:
- Call MONO.mono_wasm_init_aot_profiler (null) before calling MONO.mono_load_runtime_and_bcl ().
- Call WebAssembly.Runtime.StopProfile () from the c# code to stop profiling.
- The profile data will be in Module.aot_profile_data.
=> [wasm] Simplify AOT profiling initialization.

mcs/class/corlib/System.Runtime.CompilerServices/Unsafe.il
Fixes https://github.com/mono/mono/issues/14871.
Backport of #14987.
=> [2019-06] [corlib] Add missing Unsafe.Unbox () method.

mcs/class/System.Net.Http/HttpClientHandler.cs, mcs/class/System.Net.Http/IMonoHttpClientHandler.cs, mcs/class/System.Net.Http/MonoWebRequestHandler.cs, mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs, mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.platformnotsupported.cs, mcs/class/System.Net.Http/System.Net.Http/HttpMessageInvoker.cs, mcs/class/System.Net.Http/corefx/SocketsHttpHandler.Mono.cs
_manual backport of #14970._
[System.Net.Http]: Add hack to the legacy HttpClient to pass down Timeout property. #12577. (#14970)
* [System.Net.Http]: Add hack to the legacy HttpClient to pass down Timeout property. #12577.
* `HttpClientHandler`, `IMonoHttpClientHandler`: add new internal `MonoSetTimeout (TimeSpan)` function.
* `HttpClient.SendAsyncWorker()`: if `handler` is `HttpClientHandler`, call the new internal
`MonoSetTimeout()` function to pass down the timeout.
* `MonoWebRequestHandler.SendAsync()`: this is only used here to pass the timeout to the `HttpWebRequest`.
* Address feedback.
* Update HttpMessageInvoker.cs
* Make it build.
* Really make it build (forgot monotouch_watch).
(cherry picked from commit a44db72a1cf9a9d7d70270cefded64deb0c4b827)
=> [2019-02][System.Net.Http]: Add hack to the legacy HttpClient to pass down Timeout.  #14970

mono/mini/mini-exceptions.c
This makes it so that disabling crash privacy ensures we get the full native symbols printed regardless of allow and deny lists.
Before: https://gist.github.com/alexanderkyte/2b1f38a880c61ea15aa4c851e44af578
After: https://gist.github.com/alexanderkyte/ce80788a51761d91890d812874fa2da2
=> [crash] Print native module name when crash privacy disabled

sdks/wasm/driver.c
The following warning is generated when building master for interpreter as well as during `packager.exe` AOT build of driver.c
```
driver.c:346:31: warning: initializing 'const MonoBundledAssembly **' with an expression of type 'MonoBundledAssembly **' discards qualifiers in nested pointer types [-Wincompatible-pointer-types-discards-qualifiers]
const MonoBundledAssembly **bundle_array = g_new0 (MonoBundledAssembly*, assembly_count + 1);
^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The warning was introduced by PR: https://github.com/mono/mono/pull/14890
=> [wasm] Fix generated warning in driver.c

mono/metadata/mono-security.c, mono/metadata/w32file-unix.c, mono/metadata/w32process-unix.c, mono/utils/Makefile.am, mono/utils/mono-proclib.c, mono/utils/strenc-internals.h, mono/utils/strenc.c, msvc/libmonoutils-common.targets, msvc/libmonoutils-common.targets.filters
The error propagation made sense in most places the function was called, and so they were updated accordingly. Notably, however, this removes the `g_assert` previous present in the function that was being hit as part of https://github.com/mono/mono/issues/14730. I've re-added it higher in the call stack along with a print of more diagnostic information to figure out exactly what's going on. It preserves existing behavior, so this is not going to cause additional new failures, and a later PR addressing the underlying cause of the bug will remove it.
Hopefully this time I've added the new file to the build system properly...
=> Propagate error in mono_unicode_to_external

scripts/ci/pipeline-netcore-runtime.yml
.NET SDK is installed via a step, instead of via apt, because packages.microsoft.com doesn't support ARM(64)
The other dependencies are installed on the (non-cloud) host system.
=> [netcore] Add native ARM64 build to `--with-core=only` matrix

mono/mini/method-to-ir.c, mono/tests/Makefile.am, mono/tests/bug-gh-9706.il
`mono_emit_jit_icall` adds the instruction it generates to the current
basic block, and the redundant use of `MONO_ADD_INS` on an instruction
that has already been added to a BB will create a cycle in the `prev`
link chain.
Fixes #9706.
=> Don't create a cycle when translating IL `break` to IR.

mono/mini/mini-wasm-debugger.c, sdks/wasm/library_mono.js
Fix the signededness of numeric types and use double
for the display of everthing since we are stuck with that
on the js side.
need to add tests
=> [wasm] fix most cases of numeric debugger display for wasm

mono/mini/basic.cs, mono/mini/objects.cs, mono/mini/ssa.c
Fixes #13873
Backport of #14782.
/cc @marek-safar @imhameed
=> [2019-06] [jit] Treat ternary operations as non-constant during constant evaluation and propagation

mono/metadata/mono-security.c, mono/metadata/w32file-unix.c, mono/metadata/w32process-unix.c, mono/utils/Makefile.am, mono/utils/mono-proclib.c, mono/utils/strenc-internals.h, mono/utils/strenc.c, msvc/libmonoutils-common.targets, msvc/libmonoutils-common.targets.filters
The error propagation made sense in most places the function was called, and so they were updated accordingly. Notably, however, this removes the `g_assert` previous present in the function that was being hit as part of https://github.com/mono/mono/issues/14730. I've re-added it higher in the call stack along with a print of more diagnostic information to figure out exactly what's going on. It preserves existing behavior, so this is not going to cause additional new failures, and a later PR addressing the underlying cause of the bug will remove it.
Hopefully this time I've added the new file to the build system properly...
Backport of #14879.
=> [2019-06] Propagate error in mono_unicode_to_external

mcs/class/corlib/Test/System.Globalization/CalendarTest.cs, mcs/class/corlib/Test/System.Globalization/EastAsianLunisolarCalendarTest.cs, mcs/class/referencesource/mscorlib/system/globalization/japanesecalendar.cs, netcore/System.Private.CoreLib/shared/System/Globalization/JapaneseCalendar.Win32.cs, netcore/System.Private.CoreLib/shared/System/Globalization/JapaneseCalendar.cs
refs: <https://github.com/dotnet/coreclr/pull/23614>
mcs side of the hard coded tables seems referenced from Blazor (client-side), but it's not updated yet.
FYI: <https://qiita.com/jsakamoto/items/da68cee22bbca187f389> (an article which describes this problem, written in Japanese)
Backport of #14896.
/cc @marek-safar @acid-chicken
=> [2019-06] Fix Japan's new era fallback isn't reflected in Mono

mcs/class/System.Net.Http/HttpClientHandler.cs, mcs/class/System.Net.Http/IMonoHttpClientHandler.cs, mcs/class/System.Net.Http/MonoWebRequestHandler.cs, mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs, mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.platformnotsupported.cs, mcs/class/System.Net.Http/System.Net.Http/HttpMessageInvoker.cs, mcs/class/System.Net.Http/corefx/SocketsHttpHandler.Mono.cs
* `HttpClientHandler`, `IMonoHttpClientHandler`: add new internal `MonoSetTimeout (TimeSpan)` function.
* `HttpClient.SendAsyncWorker()`: if `handler` is `HttpClientHandler`, call the new internal
`MonoSetTimeout()` function to pass down the timeout.
* `MonoWebRequestHandler.SendAsync()`: this is only used here to pass the timeout to the `HttpWebRequest`.
Backport of #14970.
=> [2019-06] [System.Net.Http]: Add hack to the legacy HttpClient to pass down Timeout property. #12577.

mono/metadata/assembly.c
We can hit the following deadlock when loading assemblies (using reflection) together with bundling:
One thread calls mono_assembly_open_from_bundle, that will take assemblies lock and then try to load assembly. If this race with a different load of the same assemblies, one will lose, and that method will call mono_image_close that in turn will call unload hook (mono_class_unregister_image_generic_subclasses) that will take loader lock.
If we at the same time have a different thread that calls mono_class_create_from_typedef , it will take loader lock and then it might end up calling mono_assembly_load_reference that will take assemblies lock, but since that thread takes the locks in different order compare to first thread, they could deadlock.
Looking into the use of assemblies lock in …
=> Deadlock in loader when using bundling.

netcore/System.Private.CoreLib/System.Private.CoreLib.csproj, netcore/build.sh
Overwrite `Configuration` and `Platform` only when external variables are defined.
=> [netcore] Fix csproj

mono/mini/aot-runtime.h, mono/mini/jit.h, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h
And mark them all `MONO_RT_EXTERNAL_ONLY`.
`mono_set_use_llvm` is new - Xamarin.Android previously assigned to `mono_use_llvm` directly.
Fixes #15099
=> [mini] Move some MONO_API functions to public header

mono/utils/mono-lazy-init.h
There are two things here.
One is a no-brainer. Fast and required.
Changing `status` to `*lazy_init`.
Without that, initialization claims failure in a race, when there was actually success.
One is a little controversial.
A slow down (added barrier in fast path).
Could be done in a more complex barrier-free way.
Isn't always a problem.
Details and other recommendations within.
This is a superset of https://github.com/mono/mono/pull/15020.
The small no-brainer part fixes:
https://github.com/mono/mono/issues/14486
Thanks to @MaximLipnin for the trivial repro.
Backport of #15126.
/cc @marek-safar @jaykrell
=> [2019-06] Fix bug and race in mono_lazy_initialize.

mono/utils/mono-lazy-init.h
There are two things here.
One is a no-brainer. Fast and required.
Changing `status` to `*lazy_init`.
Without that, initialization claims failure in a race, when there was actually success.
One is a little controversial.
A slow down (added barrier in fast path).
Could be done in a more complex barrier-free way.
Isn't always a problem.
Details and other recommendations within.
This is a superset of https://github.com/mono/mono/pull/15020.
The small no-brainer part fixes:
https://github.com/mono/mono/issues/14486
Thanks to @MaximLipnin for the trivial repro.
Backport of #15126.
/cc @marek-safar @jaykrell
=> [2019-02] Fix bug and race in mono_lazy_initialize.

mono/mini/aot-runtime.h, mono/mini/jit.h, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h
And mark them all `MONO_RT_EXTERNAL_ONLY`.
`mono_set_use_llvm` is new - Xamarin.Android previously assigned to `mono_use_llvm` directly.
Fixes #15099
Backport of #15105.
=> [2019-06] [mini] Move some MONO_API functions to public header

mono/mini/debugger-agent.c
The thread_stopped profiler event can be raised by the thread_info_key_dtor tls
key destructor when the thread is already doesn't have a domain set.  In that
case, don't call process_profiler_event since it cannot handle a thread with
null TLS values.
Addresses https://github.com/xamarin/xamarin-android/issues/2920
Backport of #13936.
=> [master][debugger-agent] Ignore thread_end event if thread is detached

mono/mini/debugger-agent.c
The thread_stopped profiler event can be raised by the thread_info_key_dtor tls
key destructor when the thread is already doesn't have a domain set.  In that
case, don't call process_profiler_event since it cannot handle a thread with
null TLS values.
Addresses https://github.com/xamarin/xamarin-android/issues/2920
Backport of #13936.
=> [2019-06][debugger-agent] Ignore thread_end event if thread is detached

.gitignore
I failed to do this when we first added it.
=> Add the compiler server log to the gitignore

mono/metadata/jit-icall-reg.h, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/mini/method-to-ir.c, mono/mini/mini-ppc.c, mono/mini/mini-runtime.c, mono/mini/mini-s390x.c, mono/mini/mini-x86.c, mono/mini/mini.h, mono/mini/patch-info.h, mono/mini/tramp-amd64.c, mono/mini/tramp-arm.c, mono/mini/tramp-arm64.c, mono/mini/tramp-ppc.c, mono/mini/tramp-x86.c
Fewer patch types is preferred to simplify and reduce the code.
Originally JIT icalls were string based, so there are a few separate ones that are enum/integer-based.
JIT icalls are now enum-based and can replace a few others. This isn’t the only one.
=> Replace MONO_PATCH_INFO_TRAMPOLINE_FUNC_ADDR with MONO_PATCH_INFO_JIT_ICALL_ADDR.

mono/utils/mono-lazy-init.h
There are two things here.
One is a no-brainer. Fast and required.
Changing `status` to `*lazy_init`.
Without that, initialization claims failure in a race, when there was actually success.
One is a little controversial.
A slow down (added barrier in fast path).
Could be done in a more complex barrier-free way.
Isn't always a problem.
Details and other recommendations within.
This is a superset of https://github.com/mono/mono/pull/15020.
The small no-brainer part fixes:
https://github.com/mono/mono/issues/14486
Thanks to @MaximLipnin for the trivial repro.
=> Fix race conditions in mono_lazy_initialize.

mono/mini/mini-arm.c
Fixes Debug mode for iOS 32bit.
Contributes to https://github.com/mono/mono/issues/15058 & https://github.com/mono/mono/issues/9621
Diff before (left old cross32, right new cross32 running on amd64 host _before_ this fix):
/cc @mandel-macaque 
Backport of #15205.
/cc @lewurm
=> [2019-06] [arm] use target_mgreg_t instead of plain pointer type in sdb breakpoint

netcore/System.Private.CoreLib/src/System/RuntimeType.cs, netcore/build.sh
I suspect some regions were deleted accidentally during https://github.com/mono/mono/pull/15149 so now we have > 3k of failing tests in `System.Runtime.Tests`.
I've tried to merge `rttype.cs` with `RuntimeType.cs` myself using IDE  (because I don't think I could just find what is missing in these huge files).
What I did:
1) Removed all irrelevant #if-defs (IDE rendered them in gray color), only left one `#if FULL_AOT_RUNTIME` and `_DEBUG` symbols.
2) merged rttype.cs with netcore/RuntimeType.cs
3) removed unused members
Let's see what the CI thinks
=> [netcore] Fix RuntimeType.cs

mono/metadata/custom-attrs.c, mono/metadata/exception.c, mono/metadata/image.c, mono/metadata/marshal.c, mono/metadata/object.c, mono/metadata/reflection-cache.h, mono/metadata/sgen-dynarray.h, mono/metadata/sgen-mono.c, mono/metadata/sre-save.c, mono/metadata/sre.c, mono/metadata/threadpool.c, mono/metadata/threads.c, mono/metadata/w32file-unix.c, mono/metadata/w32handle.c, mono/mini/debugger-engine.c, mono/mini/interp/interp.c, mono/mini/interp/mintops.c, mono/mini/intrinsics.c, mono/mini/mini-amd64-gsharedvt.c, mono/mini/tramp-arm64-gsharedvt.c, mono/utils/mono-mmap.c, mono/utils/os-event-unix.c
intrinsics.c: In function 'mini_emit_inst_for_method':
intrinsics.c:1580:11: warning: 'result' may be used uninitialized in this function [-Wmaybe-uninitialized]
*dest = result;
~~~~~~^~~~~~~~
debugger-engine.c: In function 'set_bp_in_method':
debugger-engine.c:354:11: warning: variable 'code' set but not used [-Wunused-but-set-variable]
gpointer code;
^~~~
tramp-arm64-gsharedvt.c: In function 'mono_arch_get_gsharedvt_trampoline':
tramp-arm64-gsharedvt.c:217:54: warning: variable 'callee_stack_area_offset' set but not used [-Wunused-but-set-variable]
int caller_reg_area_offset, callee_reg_area_offset, callee_stack_area_offset;
^~~~~~~~~~~~~~~~~~~~~~~~
mini-arm64-gsharedvt.c: In function 'mono_arch_get_gsharedvt_call_info':
mini-arm64-gsharedvt.c:142:29: warning: variable 'gsig' set but …
=> Fix compiler warnings.

mono/mini/mini-arm.c
Fixes Debug mode for iOS 32bit.
Contributes to https://github.com/mono/mono/issues/15058 & https://github.com/mono/mono/issues/9621
Diff before (left old cross32, right new cross32 running on amd64 host _before_ this fix):
=> [arm] use target_mgreg_t instead of plain pointer type in sdb breakpoint

mono/eglib/gshell.c
Fixes #14724 
This may need to be reverted if customers are relying on the existing behavior, but we can cross that bridge when we come to it.
The larger issue of incompatibility with .NET Core should probably be a separate issue that I'll open once I hear back from the Core folks, but I think I can mark the original issue closed once the single quote bug specifically is resolved.
=> [eglib] Don't escape chars in argv parsing enclosed in single quotes

mono/metadata/external-only.c, mono/profiler/log.c, mono/utils/mono-threads-coop.h, mono/utils/mono-threads.h
Revert one part of #14979  - `mono_gchandle_free` can be called by Xamarin.Mac form [`xamarin_dispose_helper`](https://github.com/xamarin/xamarin-macios/blob/7f4a1db36fa0544020b73deefbac0ed0b1d5f0c8/runtime/shared.m#L244) which can run on a thread that's not attached to the runtime.
This is fine for SGen since the gchandle code is lockfree.
SGen also calls back into Mono, which fires a profiler event.  The profiler has its own mechanism for tracking threads, but in `buffer_lock()` we need to make sure that we don't do the Mono thread state transitions if the thread is attached to the profiler but not to Mono.
Follow-up PR for https://github.com/mono/mono/issues/14975
Backport of #15214.
=> [2019-06] [runtime] Don't do GC Unsafe transition in mono_gchandle_free

mono/mini/mini-amd64.c, mono/mini/mini-arm64.c
See https://github.com/mono/mono/pull/15205#issuecomment-502925368
Theoretically fixes cross compilation on a 32bit host to a 64bit target.
=> [mini] fix OP_SEQ_POINT of other backends regarding target pointer size

mono/metadata/external-only.c, mono/profiler/log.c, mono/utils/mono-threads-coop.h, mono/utils/mono-threads.h
Revert one part of #14979  - `mono_gchandle_free` can be called by Xamarin.Mac form [`xamarin_dispose_helper`](https://github.com/xamarin/xamarin-macios/blob/7f4a1db36fa0544020b73deefbac0ed0b1d5f0c8/runtime/shared.m#L244) which can run on a thread that's not attached to the runtime.
This is fine for SGen since the gchandle code is lockfree.
SGen also calls back into Mono, which fires a profiler event.  The profiler has its own mechanism for tracking threads, but in `buffer_lock()` we need to make sure that we don't do the Mono thread state transitions if the thread is attached to the profiler but not to Mono.
Follow-up PR for https://github.com/mono/mono/issues/14975
Backport of #15214.
=> [2019-02] [runtime] Don't do GC Unsafe transition in mono_gchandle_free

mono/mini/mini-arm.c
As suggested by Jay in https://github.com/mono/mono/issues/15058#issuecomment-501995400
I haven't seen fixing it any specific issue, but we should still backport it to `2019-06` in order to avoid hard-to-debug regressions.
=> [arm] fix some more host/target pointer size issues

packaging/MacSDK/packaging/resources/postinstall
We have several issues (e.g. https://github.com/mono/mono/issues/14181) where the installer occasionally fails in the postinstall script for unknown causes, on some hosts.
This seems to be sometimes the culpable section and this patch should help trace the issue or alleviate the common symptoms of it (see https://github.com/mono/mono/issues/14181)
=> Improve robustness of post-install script

mcs/class/System/Test/System.IO/FileSystemWatcherTest.cs, mono/metadata/filewatcher.c
Fixes https://github.com/mono/mono/issues/12535
=> [filewatcher] Fall back to default if a new instance cannot be created

packaging/MacSDK/packaging/resources/postinstall
We have several issues (e.g. https://github.com/mono/mono/issues/14181) where the installer occasionally fails in the postinstall script for unknown causes, on some hosts.
This seems to be sometimes the culpable section and this patch should help trace the issue or alleviate the common symptoms of it (see https://github.com/mono/mono/issues/14181)
Backport of #15213.
/cc @alexischr
=> [2019-02] Improve robustness of post-install script

packaging/MacSDK/packaging/resources/postinstall
We have several issues (e.g. https://github.com/mono/mono/issues/14181) where the installer occasionally fails in the postinstall script for unknown causes, on some hosts.
This seems to be sometimes the culpable section and this patch should help trace the issue or alleviate the common symptoms of it (see https://github.com/mono/mono/issues/14181)
Backport of #15213.
/cc @alexischr
=> [2019-06] Improve robustness of post-install script

mcs/tests/test-ref-07.cs, mcs/tests/ver-il-net_4_x.xml, mono/metadata/icall.c, netcore/CoreFX.issues.rsp
Update the checks for ByRef return type in reflection invocation to also check for IsByRefLike types. This was missed as part of #13901 and noted in the description.
Fixes #14959, #14960, #14961, #14963
=> [netcore] Update the checks for ByRef return type in reflection invocation

mono/mini/mini-arm.c
As suggested by Jay in https://github.com/mono/mono/issues/15058#issuecomment-501995400
I haven't seen fixing it any specific issue, but we should still backport it to `2019-06` in order to avoid hard-to-debug regressions.
Backport of #15223.
/cc @lewurm
=> [2019-06] [arm] fix some more host/target pointer size issues

scripts/ci/run-test-interpreter.sh
On Windows (partly due to slow shell execution) this test take longer to
complete than current given timeout.
https://jenkins.mono-project.com/job/z3/
=> Increase timeout for interpreter fullaotmixed regression.

mono/metadata/external-only.c, mono/profiler/log.c, mono/utils/mono-threads-coop.h, mono/utils/mono-threads.h
Revert one part of #14979  - `mono_gchandle_free` can be called by Xamarin.Mac form [`xamarin_dispose_helper`](https://github.com/xamarin/xamarin-macios/blob/7f4a1db36fa0544020b73deefbac0ed0b1d5f0c8/runtime/shared.m#L244) which can run on a thread that's not attached to the runtime.
This is fine for SGen since the gchandle code is lockfree.
SGen also calls back into Mono, which fires a profiler event.  The profiler has its own mechanism for tracking threads, but in `buffer_lock()` we need to make sure that we don't do the Mono thread state transitions if the thread is attached to the profiler but not to Mono.
Follow-up PR for https://github.com/mono/mono/issues/14975
=> [runtime] Don't do GC Unsafe transition in mono_gchandle_free

scripts/ci/run-test-interpreter.sh
Fix makes sure we don't run full test suite on PR builds or when targeting arm architectures. Current implementation will always run full test suite on PR builds for Windows and Linux. Full test suites will be run on master CI builds for none arm architectures.
=> Interpreter PR builds run too many test suites.

netcore/Directory.Build.props, netcore/corefx-restore.csproj, netcore/roslyn-restore.csproj
I couldn't build netcore from master and it turned out it ignored list of feeds in nuget.config. 
@ViktorHofer helped to figure out why.
=> [netcore] Fix missing nuget feeds

mono/metadata/threadpool-io.c
It should not matter in this case, but it is the usual practise,
and not strictly valid otherwise.
=> Write to the same union member that is later read.

mono/metadata/sre.c
It is called in a loop by ves_icall_TypeBuilder_create_runtime_class.
See https://github.com/mono/mono/issues/15247.
=> [Coop] Establish handle frame in reflection_setup_internal_class.

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/mini-exceptions.c
When the try catch found is in a MONO_WRAPPER_RUNTIME_INVOKE method (in this case in "runtime_invoke_void_object" method) the exception should be treated as an UNHANDLED by the debugger.
Fixes #15203
=> [debugger] Debugger doesn't break on unhandled exceptions 

scripts/ci/git-reset-hard.sh, scripts/ci/pipeline/sdks-archive.groovy
Work around a weird bug in Homebrew git 2.22.0
=> [2019-02][ci] Use a shell script to reset HEAD for submodules

mono/metadata/assembly.c
Allow through requests for newer versions unchanged.
=> [loader] remap only System.Threading.Tasks.Dataflow older than 4.0.0.0

configure.ac, mono/utils/mono-threads-coop.c
By default when called through macros like MONO_ENTER_GC_UNSAFE code will always dump current registers into stack space on hybrid/coop. The registers will be scanned but only when hitting a GC and when running in GC unsafe, that will only happen when we block in the enter or hit a safe point at a later point in time. There are currently a couple of frequent scenarios where we go into GC safe when thread won't be suspended and in that case the copy of the registers will only reflect the state when
entering GC unsafe.
Commits add option to enable/disable copy_stack_data support in configure step:
--enable-copy-stack-data, --disable-copy-stack-data.
copy_stack_data is enabled by default on all platforms except desktop platforms macos, linux and windows (both 32/64-bit), since these …
=> Make copy_stack_data support configurable.

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/mini-exceptions.c
When the try catch found is in a MONO_WRAPPER_RUNTIME_INVOKE method (in this case in "runtime_invoke_void_object" method) the exception should be treated as an UNHANDLED by the debugger.
Fixes #15203
Backport of #15234.
=> [2019-06] [debugger] Debugger doesn't break on unhandled exceptions 

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/mini-exceptions.c
When the try catch found is in a MONO_WRAPPER_RUNTIME_INVOKE method (in this case in "runtime_invoke_void_object" method) the exception should be treated as an UNHANDLED by the debugger.
Fixes #15203
Backport of #15234.
=> [2019-02] [debugger] Debugger doesn't break on unhandled exceptions 

sdks/wasm/binding_support.js
- Fixes `this.mono_string_get_utf8 is not a function`.
Closes https://github.com/mono/mono/issues/15273
Possibly this issue as well https://github.com/mono/mono/issues/14582 as it looks like the same error.
=> [wasm][bindings] Make sure that bindings are initialized in `mono_wasm_new`.

netcore/Makefile
Fixes `build-test-corefx` command (cc @MaximLipnin)
Also don't know why but in order to use the runtime we download on windows I have to chmod it.
=> [netcore] fix windows build and build-test-corefx command 

scripts/ci/pipeline/sdks-archive.groovy
Homebrew Git 2.22.0 misparses the submodule command and passes arguments like --hard and -xdff to git-submodule instead of to git-reset or git-clean.  Passing the entire command as a single argument seems to help.
---
Previous attempt in #15284 had two shortcomings:
1. it didn't work on Windows
2. I didn't fix up `git submodule foreach --recursive git clean -xdff`
This new approach with double quoting should address both of those things.
---
[Git mailing list bug report](https://public-inbox.org/git/pull.263.git.gitgitgadget@gmail.com/)
=> [2019-02][ci] One more workaround for Git 2.22.0

scripts/ci/pipeline/sdks-archive.groovy
Homebrew Git 2.22.0 misparses the submodule command and passes arguments like --hard and -xdff to git-submodule instead of to git-reset or git-clean.  Passing the entire command as a single argument seems to help.
Git mailing list bug report: https://public-inbox.org/git/pull.263.git.gitgitgadget@gmail.com/
=> [2019-06][ci] One more workaround for Git 2.22.0

scripts/ci/pipeline/sdks-archive.groovy
Homebrew Git 2.22.0 misparses the submodule command and passes arguments like --hard and -xdff to git-submodule instead of to git-reset or git-clean.  Passing the entire command as a single argument seems to help.
Git mailing list bug report: https://public-inbox.org/git/pull.263.git.gitgitgadget@gmail.com/
Backport of #15325.
=> [ci] One more workaround for Git 2.22.0

mono/metadata/Makefile.am, mono/metadata/profiler-legacy.h, mono/metadata/profiler.c, msvc/libmonoruntime-common.targets, msvc/libmonoruntime-common.targets.filters
Add a header with the legacy Mono profiler API and mark every function in it with `MONO_DEPRECATED`.
New code should use the API from mono/metadata/profiler.h.
---
No functional change. All these symbols were already exported by mono/metadata/profiler.c.  Now we just have a proper header for them.
=> [api] Add a mono/metadata/profiler-legacy.h header

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
Remove three unused functions:
mono_aot_init_gshared_method_this
mono_aot_init_gshared_method_mrgctx
mono_aot_init_gshared_method_vtable
Update comments that refer to them, to refer to the renames.
mini_llvm_init instead of mono_aot_init.
See 80bc006 and 04d65f2.
=> Remove three unused functions.

mono/mini/mini-amd64.c, mono/mini/mini-arm.c, mono/mini/mini-arm64.c
On arm and arm64
>   0xf7e5d384 in __libc_do_syscall () from /lib/arm-linux-gnueabihf/libpthread.so.0
>   0xf7e5c126 in waitpid () from /lib/arm-linux-gnueabihf/libpthread.so.0
>   0x0068f3ac in dump_native_stacktrace (mctx=mctx@entry=0xef3fdee8, signal=0x8399ac "SIGSEGV") at mini-posix.c:1079
>   0x0068f4c2 in mono_dump_native_crash_info (signal=signal@entry=0x8399ac "SIGSEGV", > mctx=mctx@entry=0xef3fdee8, info=info@entry=0xef3fdfe0) at mini-posix.c:1125
>   0x0066ba90 in mono_handle_native_crash (signal=0x8399ac "SIGSEGV", mctx=0xef3fdee8, mctx@entry=0xef3fdef0, info=0xef3fdfe0, info@entry=0xef100f28) at mini-exceptions.c:3328
>   0x00643734 in mono_sigsegv_signal_handler_debug (_dummy=-274701152, _info=0x66952e <get_generic_info_from_stack_frame+158>, context=0xb, …
=> [exceptions] Fix crashes when getting generic info during EH

mono/mini/trace.c
Greetings; this is just a simple debugging fix, partially to improve a +wrapper trace I encountered, and partly to ensure I'm acquainted to the Mono patch submission process.
=> [mini] Support tracing pointer return values.

mono/mini/mini-amd64.c, mono/mini/mini-arm.c, mono/mini/mini-arm64.c
On arm and arm64
>   0xf7e5d384 in __libc_do_syscall () from /lib/arm-linux-gnueabihf/libpthread.so.0
>   0xf7e5c126 in waitpid () from /lib/arm-linux-gnueabihf/libpthread.so.0
>   0x0068f3ac in dump_native_stacktrace (mctx=mctx@entry=0xef3fdee8, signal=0x8399ac "SIGSEGV") at mini-posix.c:1079
>   0x0068f4c2 in mono_dump_native_crash_info (signal=signal@entry=0x8399ac "SIGSEGV", > mctx=mctx@entry=0xef3fdee8, info=info@entry=0xef3fdfe0) at mini-posix.c:1125
>   0x0066ba90 in mono_handle_native_crash (signal=0x8399ac "SIGSEGV", mctx=0xef3fdee8, mctx@entry=0xef3fdef0, info=0xef3fdfe0, info@entry=0xef100f28) at mini-exceptions.c:3328
>   0x00643734 in mono_sigsegv_signal_handler_debug (_dummy=-274701152, _info=0x66952e <get_generic_info_from_stack_frame+158>, context=0xb, …
=> [2019-06] [exceptions] Fix crashes when getting generic info during EH

mono/mini/aot-runtime.c
Fixes https://github.com/mono/mono/issues/15330.
Backport of #15332.
/cc @vargaz
=> [2019-06] [aot] Fix a deadlock in init_plt () by calling create_trampoline () outside the lock.

mono/mini/aot-compiler.c
We recently switched the AOT compiler for iOS armv7 from 32bit host to 64bit host. At the same time we _also_ switched from LLVM 3.6 to the newer LLVM 6.0 fork we support.
In a Xamarin.iOS Release build for iOS armv7 exception handling would crash. Specifically the problem was that the exception object wasn't properly injected into the handler block. The way it works is, that the exception handler machinery passes the pointer to the exception object via `r0`.
With the newer LLVM the generated code of the exception handling block
looks like this:
```
LBB1_15:                                @ %EH_CLAUSE0_BB3
Ltmp8:
ldr	r0, [sp, #24]
str	r0, [sp, #4]
ldr	r0, [sp, #28]
ldr	r0, [sp, #12]
ldr	r0, [r0]
cmp	r0, #0
beq	LBB1_17
```
thus overwriting `r0`, so that the pointer to the exception object …
=> [arm] set exception handling model to dwarf for iOS

mono/mini/aot-compiler.c
We recently switched the AOT compiler for iOS armv7 from 32bit host to 64bit host. At the same time we _also_ switched from LLVM 3.6 to the newer LLVM 6.0 fork we support.
In a Xamarin.iOS Release build for iOS armv7 exception handling would crash. Specifically the problem was that the exception object wasn't properly injected into the handler block. The way it works is, that the exception handler machinery passes the pointer to the exception object via `r0`.
With the newer LLVM the generated code of the exception handling block
looks like this:
```
LBB1_15:                                @ %EH_CLAUSE0_BB3
Ltmp8:
ldr	r0, [sp, #24]
str	r0, [sp, #4]
ldr	r0, [sp, #28]
ldr	r0, [sp, #12]
ldr	r0, [r0]
cmp	r0, #0
beq	LBB1_17
```
thus overwriting `r0`, so that the pointer to the exception object …
=> [2019-06] [arm] set exception handling model to dwarf for iOS

mcs/class/corlib/System.Threading/RegisteredWaitHandle.cs, netcore/System.Private.CoreLib/src/System.Threading/RegisteredWaitHandle.cs
We have seen sporadic failures in thread pool tests on CI related to test case:
```
System.Threading.ThreadPools.Tests.ThreadPoolTests.QueueRegisterPositiveAndFlowTest [FAIL]
Assert.Equal() Failure
Expected: 0
Actual:   1
Stack Trace:
at System.Threading.ThreadPools.Tests.ThreadPoolTests.QueueRegisterPositiveAndFlowTest () [0x00143] in D:\j\workspace\z3\label\w64\external\corefx\src\System.Threading.ThreadPool\tests\ThreadPoolTests.cs:337
at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo …
```
=> Fix race related to final event signaling in RegisteredWaitHandle.

mono/mini/mini-wasm-debugger.c, sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs, sdks/wasm/library_mono.js
- Improving performance calling only once mono_wasm_get_var_info.
- Adding support to debug local vars in async methods. They are special in the way that local variables can be lifted to generated class fields.
Fixes #14608
=> [wasm][debugger] Adding support to debug local vars in async methods

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridViewColumn.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/DataGridViewColumnTest.cs
This PR fix crash of `DataGridView` in case of assigning a custom Column Header.
=> [System.Windows.Forms] Fix crash of DataGridView in case of assigning a custom Column Header.

mcs/class/test-helpers/Configuration.Certificates.cs
Fixes #15379.
Backport of #15383.
/cc @baulig
=> [2019-06] [test-helpers]: Don't use named Mutexes on mobile.

mono/mini/cpu-amd64.md
We hit the following assert when doing full AOT of some assemblies:
wrong maximal instruction length of instruction localloc (expected 96, got 99)
Assertion: should not be reached at mono\mono\mini\mini-amd64.c:6801
Turns out that that size could be hit when a couple of things happens as part of lowering OP_LOCALLOC and OP_LOCALLOC_IMM:
sreg1 is not RAX, RCX or RDI
dreg is not RAX, RCX or RDI
cfg->param_area is bigger than 127
Fix is to increase max size of the instruction, from 96 -> 120 (same as x86).
=> Increase max size of localloc and localloc_imm on amd64.

mono/utils/mono-threads-api.h, mono/utils/mono-threads-coop.c, mono/utils/mono-threads-windows.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h, winconfig.h
When running in hybrid suspend and having threads in blocking mode, GC Safe mode, threads will still be preemptive suspended. This is done to make sure compatibility is kept with embedders since current embedding API is not coop aware. If, however the external attached threads promise to follow the coop
rules for a thread in Safe mode, it could still be possible to have them running, making sure they won't be preempted when running STW. Unlocking this possibility could have large performance wins if embedding threads runs a lot of unrelated native code on threads attached to runtime (game engines as an example).
This commit adds support for a new pair of API's where an external thread can mark itself as cooperative suspend aware. Doing that guarantees the runtime that it will follow all …
=> Add cooperative suspend aware threads for hybrid suspend.

mcs/class/System.Core/monotouch_System.Core_xtest.dll.exclude.sources, mcs/class/System/monotouch_watch_System_xtest.dll.exclude.sources
[System.Core] Exclude AnonymousPipe tests on monotouch/xammac profiles
[System] Exclude WebClient and WebSocket tests on monotouch_watch …
Fixes #15329
Fixes #15265
=> Exclude a few tests on monotouch_watch/xammac

mcs/class/System.Core/monotouch_System.Core_xtest.dll.exclude.sources, mcs/class/System/monotouch_watch_System_xtest.dll.exclude.sources
[System.Core] Exclude AnonymousPipe tests on monotouch/xammac profiles
[System] Exclude WebClient and WebSocket tests on monotouch_watch …
Fixes #15329
Fixes #15265
Backport of #15397.
=> [2019-06] Exclude a few tests on monotouch_watch/xammac

mono/profiler/Makefile.am
This should fix broken `OS X x64 iOS SDK` build.
=> [profiler] Add helper.c to static sources where needed

configure.ac, mcs/build/common/basic-profile-check.cs, mcs/class/Makefile, netcore/Makefile
Tarball build was broken by https://github.com/mono/mono/commit/9010d2f290d28dc97ac276e0c0d32a2932b7550f
=> Fix tarball build and refresh monolite due to memory model change

mono/mini/aot-runtime.h, mono/mini/debug-mini.c
=> [aot] Save the number of locals into the aot debug info so the method header doesn't have to be decoded when its loaded.

mono/mini/objects.cs, mono/mini/type-checking.c
Fixes a scenario on platforms with remoting disabled, where casting something to a special interface (like 
IEnumerable<>, IList<> ..) would fail to throw InvalidCastException.
Fixes https://github.com/mono/mono/issues/14729
Backport of #14978.
=> [2019-06] [jit] Fix interface cast

netcore/Makefile, netcore/xunit-summary.py
```
make xunit-summary
```
it prints some compact xunit report - a similar python script is used by coreclr (or corefx):
```
=========================================================================================================
Common.Tests.dll                                              Total:1144    Failed:0       Time:9.2 sec
CoreFx.Private.TestUtilities.Tests.dll                        Total:87      Failed:0       Time:0.2 sec
Invariant.Tests.dll                                           Total:296     Failed:0       Time:0.4 sec
Microsoft.Bcl.AsyncInterfaces.Tests.dll                       Total:10      Failed:0       Time:0.2 sec
Microsoft.CSharp.Tests.dll                                    Total:4796    Failed:0       Time:2.6 sec
Microsoft.VisualBasic.Core.Tests.dll …
```
=> [netcore] Add xunit summary script

mcs/class/test-helpers/Configuration.Certificates.cs
=> [test-helpers]: Don't use named Mutexes on mobile.

mcs/class/System.Private.CoreLib/System.Threading/RegisteredWaitHandle.cs, mcs/class/corlib/System.Threading/RegisteredWaitHandle.cs
We have seen sporadic failures in thread pool tests on CI related to test case:
```
System.Threading.ThreadPools.Tests.ThreadPoolTests.QueueRegisterPositiveAndFlowTest [FAIL]
Assert.Equal() Failure
Expected: 0
Actual:   1
Stack Trace:
at System.Threading.ThreadPools.Tests.ThreadPoolTests.QueueRegisterPositiveAndFlowTest () [0x00143] in D:\j\workspace\z3\label\w64\external\corefx\src\System.Threading.ThreadPool\tests\ThreadPoolTests.cs:337
at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo …
```
=> [2019-06] Fix race related to final event signaling in RegisteredWaitHandle.

mcs/class/corlib/System.Runtime.Remoting.Messaging/CADMessages.cs, mono/sgen/sgen-debug.c
CADMessages are passed directly between appdomains. When using contained data, we need to make sure we don't create any cross domain references.
When domains are unloaded, all threads executing code in that appdomain are aborted and the entire heap is traversed and objects in that appdomain are cleared. If any objects in other domains are directly referencing objects in the unloaded domain, they will reference junk. If any, cross domain refs should only be allowed when the referenced object is in the root domain which is never unloaded.
=> [sgen] Fix crashes in sgen due to xdomain refs

mono/metadata/jit-icall-reg.h, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/mini/interp/transform.c, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c, mono/mini/patch-info.h, mono/utils/mono-tls.c, mono/utils/mono-tls.h
The goal being fewer patch types for slight simplicity and efficiency.
There are still plenty of patch types to reason over however.
It was structured like this before, presumably, either because:
1. MONO_PATCH_INFO_JIT_ICALL_ADDR_NOCALL was string-based instead of enum-based or
2. NOCALL variant did not exist.
3. Perhaps the "enum overlay" is considered inelegant but I think it is ok. It was only possible before by parsing integers out of the strings, which other icalls did do (but no longer). Now that it is free of string parsing, I think it is ok.
=> Change MONO_PATCH_INFO_GET_TLS_TRAMP to MONO_PATCH_INFO_JIT_ICALL_ADDR_NOCALL.

mono/metadata/icall-decl.h, mono/metadata/icall.c, support/nl.c, support/nl.h
Fixes #14848 
In managed, these functions are used as `static external IntPtr`. This means that previously on arm64 the top bits of the return value were garbage. A comparison with 64-bit -1 like in LinuxNetworkChange.EnsureSocket would never be true, which was causing us to hit other assertions in the runtime.
This will require a change in xamarin-android as well.
=> CreateNLSocket and CloseNLSocket should return gpointer

mcs/class/corlib/System.Runtime.Remoting.Messaging/CADMessages.cs, mono/sgen/sgen-debug.c
CADMessages are passed directly between appdomains. When using contained data, we need to make sure we don't create any cross domain references.
When domains are unloaded, all threads executing code in that appdomain are aborted and the entire heap is traversed and objects in that appdomain are cleared. If any objects in other domains are directly referencing objects in the unloaded domain, they will reference junk. If any, cross domain refs should only be allowed when the referenced object is in the root domain which is never unloaded.
Backport of #15390.
/cc @lambdageek @BrzVlad
=> [2019-06] [sgen] Fix crashes in sgen due to xdomain refs

netcore/CoreFX.issues.rsp
Went through the majority of corefx tests that were being skipped in CoreFX.issues.rsp.
For each failure, a github issue was logged and if possible, a more expanded
failure reason was specified.
Part of the https://github.com/mono/mono/issues/14787 epic work.
=> [netcore] Review and document netcore test failures that are skipped

mcs/class/corlib/System/TimeZoneInfo.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
When a datetime appears in range of [end_of_DST_period - Daylight_delta; end_of_DST_period] it's not DST and should return base offset.
Fixes #9664.
Backport of #15401.
=> [2019-02] Fix time zone transition out of DST

mcs/class/corlib/System/TimeZoneInfo.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
When a datetime appears in range of [end_of_DST_period - Daylight_delta; end_of_DST_period] it's not DST and should return base offset.
Fixes #9664.
Backport of #15401.
=> [2019-06] Fix time zone transition out of DST

mono/utils/mono-threads-windows.c
According to documentation of mono_threads_suspend_begin_async_suspend:
"If begin suspend fails the thread must be left uninterrupted and resumed."
Current implementation on Windows didn't resume thread in case GetThreadContext fails, leaving a thread in suspended state on failure.
Fix is to resume thread if GetThreadContext fails.
PR also fix the use of THREAD_SUSPEND_DEBUG macro in the same file, since current implementation had both compile error and warnings (not used before).
=> Fix suspend thread failure behavior on Windows.

mono/metadata/jit-icall-reg.h, mono/mini/interp/transform.c, mono/mini/jit-icalls.c, mono/mini/jit-icalls.h, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c, mono/tests/Makefile.am, mono/tests/dim-abstractcall.il
Emitting bad image exception when a non virtual call is calling an abstract method.
Fixes #13925
=> [dim] Emit error when calling abstract methods

mono/mini/mini-mips.c
Fixes https://github.com/mono/mono/issues/15441
Backport of #15459.
/cc @akoeplinger @jaykrell
=> [2019-06] Fix year+ old MIPS compile break.

packaging/MacSDK/packaging/resources/postinstall
We have several issues (e.g. https://github.com/mono/mono/issues/14181) where the installer occasionally fails in the postinstall script for unknown causes, on some hosts.
This seems to be sometimes the culpable section and this patch should help trace the issue or alleviate the common symptoms of it (see https://github.com/mono/mono/issues/14181)
Backport of #15213.
/cc @alexischr
=> [2018-10] Improve robustness of post-install script

sdks/wasm/sdk/Mono.WebAssembly.Sdk/Directory.Build.targets, sdks/wasm/sdk/Mono.WebAssembly.Sdk/sdk/Versions.props, sdks/wasm/sdk/global.json
The version is incorrectly generated.
- The package reference of `ClientWebSocketPackageVersion` is generated with an appended `1` causing an error being generated when restoring.
=> [wasm][sdk] Fix generation of version.

mcs/class/corlib/System/TimeZoneInfo.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
When a datetime appears in range of [end_of_DST_period - Daylight_delta; end_of_DST_period] it's not DST and should return base offset.
Fixes #9664.
=> Fix time zone transition out of DST

scripts/ci/pipeline/sdks-archive.groovy
Ought to cause fewer failures during archive job.
=> Use /mnt/scratch for Android SDK, to match https://github.com/xamarin/xamarin-android/pull/3125

scripts/ci/pipeline/sdks-archive.groovy
Ought to cause fewer failures during archive job.
Backport of #15453.
=> [2019-06] Use /mnt/scratch for Android SDK, to match https://github.com/xamarin/xamarin-android/pull/3125

scripts/ci/pipeline/sdks-archive.groovy
This fixes https://github.com/mono/mono/pull/15453
The issue is the env var names differ vs. Xamarin.Android
this value comes from sdks/paths.mk
=> Correct env vars used for Android directory override

scripts/ci/pipeline/sdks-archive.groovy
This fixes https://github.com/mono/mono/pull/15453
The issue is the env var names differ vs. Xamarin.Android
this value comes from sdks/paths.mk
Backport of #15469.
/cc @directhex
=> [2019-06] Correct env vars used for Android directory override

mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c, mono/tests/libtest.c, mono/tests/pinvoke2.cs
Fixes #15366 and #15306.
- Fixes NULL termination of `StringBuilder` to UTF-16 marshalling. Additionally an extra NULL is added as defense-in-depth protection for incorrect handling in native calls. This extra NULL adds protection when trying to marshal the NULL-terminated string back and the native function doesn't null-terminate at the size of the buffer.
- Fixes marshalling back from UTF-16/UTF-8 buffers into chunked `StringBuilder`.
- Fixes missing `mono_marshal_free` call causing a memory leak when marshalling `StringBuilder` to UTF-16 and back.
- Skips marshalling back to `StringBuilder` when the parameter doesn't have `[Out]` attribute.
Unit tests are still TBD. Not sure where to put them and how to structure them. Any help would be appreciated. /cc @vargaz @EgorBo
=> Fix marshalling bugs for StringBuilder parameters

mono/mini/exceptions-x86.c
32-bit build is broken when using C++ compiler:
https://jenkins.mono-project.com/view/All/job/test-mono-mainline-linux-cxx/label=debian-9-i386/
https://jenkins.mono-project.com/view/All/job/test-mono-mainline-cxx/
https://jenkins.mono-project.com/view/All/job/e/
=> Fix 32-bit build error when using C++ compiler.

sdks/wasm/ProxyDriver/TestHarnessStartup.cs
We want to avoid throwing inside ErrorDataReceived on unexpected
input because tends to hang the process in a bad state.  Instead
we return null from extract_conn_url and let the normal cleanup
process happen.
=> [wasm] make extract_conn_url return null on unexpected data

mono/metadata/icall-decl.h, mono/metadata/icall.c, support/nl.c, support/nl.h
Fixes #14848 
In managed, these functions are used as `static external IntPtr`. This means that previously on arm64 the top bits of the return value were garbage. A comparison with 64-bit -1 like in LinuxNetworkChange.EnsureSocket would never be true, which was causing us to hit other assertions in the runtime.
This will require a change in xamarin-android as well.
Backport of #15408.
=> [2019-06] CreateNLSocket and CloseNLSocket should return gpointer

mono/metadata/assembly.c
Allow through requests for newer versions unchanged.
Backport of #15266.
/cc @lewing @lambdageek
=> [2019-06] [loader] remap only System.Threading.Tasks.Dataflow older than 4.0.0.0

mono/metadata/jit-icall-reg.h, mono/mini/interp/transform.c, mono/mini/jit-icalls.c, mono/mini/jit-icalls.h, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c, mono/tests/Makefile.am, mono/tests/dim-abstractcall.il
Manual backport of https://github.com/mono/mono/pull/15433 to 2019-06.
=> [2019-06][dim] Emit error when calling abstract methods

mono/metadata/debug-mono-ppdb.c, mono/mini/Makefile.am.in
https://github.com/mono/mono/pull/4484 broke Windows mingw build due to new dependency, zlib1.dll not available in PATH on build bots. Disabling for now until we know how this should be handled (and also fixed for MSVC build runtime).
=> Disable zlib on mingw Windows build to avoid dependency on zlib1.dll.

mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs
This test was checking a broken Mono-specific behavior, which has been removed after we switched to the new corefx-based handler.  It also didn't make much sense to use a `Transfer-Encoding` header with a GET request.
=> [System.Net.Http]: Delete broken `Send_Transfer_Encoding_Custom()` test.

mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs
This test was checking a broken Mono-specific behavior, which has been removed after we switched to the new corefx-based handler.  It also didn't make much sense to use a `Transfer-Encoding` header with a GET request.
Backport of #15470.
/cc @akoeplinger @baulig
=> [2019-06] [System.Net.Http]: Delete broken `Send_Transfer_Encoding_Custom()` test.

netcore/CoreFX.issues.rsp, netcore/System.Private.CoreLib/src/System.Reflection.Emit/DynamicMethod.cs
Fixes https://github.com/mono/mono/issues/15324
Removed check on the return type being by ref.
=> [netcore] Remove IsByRef check on Reflection.Emit.DynamicMethod

mono/utils/mono-codeman.h
Seems a bit obscure to be public.
The header is not public --  could still dlsym + cast.
=> Make codeman not public.

mono/mini/aot-runtime.c, mono/mini/mini-runtime.c, mono/mini/mini.h
Also print the stats on shutdown when configured with `--with-core=only`
=> [stats] distinguish between mini and LLVM AOT method

mono/mini/Makefile.am.in, mono/mini/mini-windows-dllmain.c, mono/mini/mini-windows-tls-callback.c, mono/mini/mini-windows.c, mono/mini/mini-windows.h, msvc/libmini-win32.targets, msvc/libmini-win32.targets.filters
Mono runtime depends on DllMain to be called by OS in order to correctly detach threads from the runtime. If this doesn't happen, threads from native thread pools (not owned by runtime) and attached
using native->managed callback, won't detach resulting in attached threads no longer running. Since threads are still attached to runtime, next GC will try to suspend the thread and that will fail and that in turn will put the state machine in an incorrect state, bringing down the runtime at next GC (when the thread state is revisited).
This problem is currently handled by DllMain, but since DllMain only exist in DLL's, statically link Mono runtime will get us into the above scenario.
This commit add support to hook up a TLS callback using the same mechanism used by MSVC linker and c-runtime …
=> Add support for TLS callbacks on Windows.

packaging/MacSDK/msbuild.py, packaging/MacSDK/nuget.py
Picks up update to nuget 5.2.0-rtm.6067
https://github.com/mono/msbuild/pull/115
=> [2019-06] Bump msbuild to track mono-2019-06

configure.ac
i.e. so it can be used in C instead of make.
i.e. so it can actually work.
Alternatively since it is not working, could remove it.
The lone use is here:
```
C:\s\mono2\mono\utils\mono-dl.c(271):#if MONO_DL_NEED_USCORE
```
=> AC_DEFINE instead of AC_SUBST MONO_DL_NEED_USCORE.

mono/utils/mono-threads-mach.c, mono/utils/mono-threads-posix.c, mono/utils/mono-threads-state-machine.c, mono/utils/mono-threads-windows.c, mono/utils/mono-threads.h
When a preemptive suspend fails, state machine will get into an invalid state and the thread is in an unknown state (running/self-suspended). In case of failure in mono_threads_suspend_begin_async_suspend, a new method should be called, mono_threads_transition_abort_async_suspend making sure state machine reflects correct thread state as well as reporting correct result to initial caller of mono_threads_suspend_begin_async_suspend.
=> Abort async suspend request on failure doing preemptive suspend.

mono/utils/mono-tls.h
The Windows SDKs are inconsistent (and clearly documented as so), and the JIT assumes TLS.
=> Make sure TLS (thread local storage) is always TLS and not FLS (fiber local storage).

sdks/wasm/sdk/Mono.WebAssembly.Runtime.Framework/Mono.WebAssembly.Runtime.csproj
- Fix the directory paths after threads commit
- Add threads build directories to the Runtime package.
=> [wasm][sdk] Fix the Mono.WebAssembly.Runtime package directory paths

sdks/wasm/Makefile
as we debug some 3.0.0-preview7 related build problems allow environment overrides of
the command used to build the projects
=> [wasm] allow overriding the build command invocation

sdks/wasm/Makefile, sdks/wasm/tests/runtime/package.json
- Add a `package.json` to the tests/runtime directory.
- Installs the required packages to run
- Modify make target `run-threads-sample` to use npm to install and run the test.
- There are two targets in the package.json file one for `test` and another 'start`
=> [wasm] Make the runtime threading sample easier to setup and execute.

sdks/builds/android.mk
Untested, but we need to do it anyway soon. This will help us to understand the situation on Xamarin.Android while finishing the work for Xamarin.iOS.
=> [android] switch cross compilers host from 32bit to 64bit

mono/utils/mono-tls.c
Making them static for C is not worth the ifdef.
=> Make thread locals just always extern. Not worth ifdef.

mono/mini/mini-runtime.c, mono/utils/mono-codeman.c, mono/utils/mono-codeman.h
The callbacks cannot be made directly, because codeman is used by metadata, and linked to monodis, but mini is not linked to monodis. The pointers provide a "weak" linkage. That is preserved.
=> Readonly codemanager callbacks.

configure.ac, m4/ax_append_flag.m4, m4/ax_append_link_flags.m4, m4/ax_check_link_flag.m4, m4/ax_require_defined.m4
Advantages:
Dynamic linker gets out of the way of random function calls,
in terms of timing, in terms of locking, and in term of success,
and possibly in terms of security (readonly function pointers).
If you successfully load, then you can make function calls with impunity,
without regard as to if they are in the same .so as the caller, well,
assuming they are to a leaf like libc, or to something itself built with -z now.
The "success" is significant, as otherwise loaded LLVM has unresolved symbols lurking, depending on which code paths you send it down.
Disadvantage: Slower startup.
Mixed:
Platform consistency, since this is how Windows behaves usually (unless you say link /delayload)
This will combine well with an upcoming revision of https://github.com/mono/mono/pull/14524.
Difficult …
=> Link with -z now or -bind_at_load.

netcore/Makefile, scripts/ci/pipeline-netcore-runtime.yml
The Versions.props is auto-updated by Arcade so we automatically get new versions.
Also simplify CI build invocation a little bit.
=> [netcore] Read NETCORETESTS_VERSION and NETCOREAPP_VERSION from eng/Versions.props

sdks/builds/Makefile
Default for `ulimit -n ` seems to be 256, that isn't enough for the Android SDK build.
=> [sdks] sanity check for maximum number of open file descriptors

sdks/builds/android.mk
This way we are able to dynamically load libmonosgen and also use host
mono binary.
The library dependencies look like this after the change:
```
otool -L /Users/rodo/git/mono/sdks/out/android-host-Darwin-release/bin/mono
/Users/rodo/git/mono/sdks/out/android-host-Darwin-release/bin/mono:
@loader_path/libmonosgen-2.0.dylib (compatibility version 2.0.0, current version 2.0.0)
...
otool -L /Users/rodo/git/mono/sdks/out/android-host-Darwin-release/lib/libmonosgen-2.0.dylib
/Users/rodo/git/mono/sdks/out/android-host-Darwin-release/lib/libmonosgen-2.0.dylib:
@loader_path/libmonosgen-2.0.dylib (compatibility version 2.0.0, current version 2.0.0)
...
```
=> [sdks] Use @loader_path for mono and libmonosgen

sdks/builds/android.mk
This way we are able to dynamically load libmonosgen and also use host
mono binary.
The library dependencies look like this after the change:
```
otool -L /Users/rodo/git/mono/sdks/out/android-host-Darwin-release/bin/mono
/Users/rodo/git/mono/sdks/out/android-host-Darwin-release/bin/mono:
@loader_path/libmonosgen-2.0.dylib (compatibility version 2.0.0, current version 2.0.0)
...
otool -L /Users/rodo/git/mono/sdks/out/android-host-Darwin-release/lib/libmonosgen-2.0.dylib
/Users/rodo/git/mono/sdks/out/android-host-Darwin-release/lib/libmonosgen-2.0.dylib:
@loader_path/libmonosgen-2.0.dylib (compatibility version 2.0.0, current version 2.0.0)
...
```
Backport of #15580.
/cc @akoeplinger @radekdoulik
=> [2019-06] [sdks] Use @loader_path for mono and libmonosgen

sdks/builds/android.mk
Untested, but we need to do it anyway soon. This will help us to understand the situation on Xamarin.Android while finishing the work for Xamarin.iOS.
Backport of #15553.
/cc @lewurm
=> [2019-06] [android] switch cross compilers host from 32bit to 64bit

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridViewColumn.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/DataGridViewColumnTest.cs
This PR fix crash of `DataGridView` in case of assigning a custom Column Header.
Backport of #15135 
=> [2019-06] [System.Windows.Forms] Fix crash of DataGridView in case of assigning a custom Column Header.

mono/metadata/Makefile.am
Automake sees through the conditionals, right?
=> Remove extra explicit dist.

mono/metadata/icall.c, support/zlib-helper.c
- Cleanup allocation -- leave integer overflow checks to `calloc`.
- Assume "recent" zlib (10 years old is recent from this point of view).
=> Cleanup zlib-helper.c.

netcore/dl-test-assets.py
Not sure if this will cause issues with the bots, but Python 2 is unsupported in a few months so this is going to have to happen sooner or later.
=> Convert dl-test-assets.py to Python 3

netcore/CoreFX.issues.rsp, netcore/CoreFX.issues_windows.rsp, netcore/System.Private.CoreLib/src/System/Array.cs
Fixes https://github.com/mono/mono/issues/14857
```csharp
Array src = new object[] { (object)1 };
Array dst = new DateTimeKind[] { DateTimeKind.Local };
src.CopyTo(dst, 0); // should throw InvalidCastException
```
=> [netcore] Throw ICE for Array.Copy(object[], enum[])

mcs/ilasm/codegen/GenericArguments.cs, mcs/ilasm/codegen/PrimitiveTypeRef.cs
Was crashing when was executing the boring.il test from coreclr, the problem was that using [System.Runtime]System.String the type was not understood as the primitive type string.
Using ilasm from coreclr and running on mono it works, because of that I decided to fix on ilasm and not on runtime.
Fixes #13923
=> [ilasm] [System.Runtime]System.String wasn't generating string primitive type

mcs/ilasm/codegen/GenericArguments.cs, mcs/ilasm/codegen/PrimitiveTypeRef.cs
Was crashing when was executing the boring.il test from coreclr, the problem was that using [System.Runtime]System.String the type was not understood as the primitive type string.
Using ilasm from coreclr and running on mono it works, because of that I decided to fix on ilasm and not on runtime.
Fixes #13923
Backport of #15552.
/cc @thaystg
=> [2019-06] [ilasm] [System.Runtime]System.String wasn't generating string primitive type

mcs/class/corlib/Mono/Runtime.cs
The regression is the accidental removal of RegisterReportingForNativeLib from the managed side, introduced by b919ac4#diff-939ea9baecd2e8b24260bcb33f531274
=> [merp] Fix API regression

mcs/build/tests.make
Starting another Mono process for the remote executor doesn't work on any of them.
Helps with https://github.com/mono/mono/issues/15328
=> Make RemoteExecutor a no-op on all mobile profiles

mcs/class/System/System.Net/BufferedReadStream.cs, mcs/class/System/System.Net/WebConnectionStream.cs, mcs/class/System/System.Net/WebRequestStream.cs, mcs/class/System/System.Net/WebResponseStream.cs, mcs/class/System/Test/System.Net/HttpWebRequestTest.cs
[System]: Allow reading fully buffered `HttpWebResponse` body after close.
If we have already read the entire response body, then we should allow the
user to read it even after the request has been aborted.
* `WebConnectionStream.Read ()`: Move `Operation.ThrowIfClosedOrDisposed ()`
call down after argument checks and call a new protected abstract method
called `TryReadFromBufferedContent ()` prior to it.
* `WebResponseStream.TryReadFromBufferedContent ()`: Implement it here.
If the entire response body has been buffered, then `bufferedEntireContent`
is true and `innerStream is BufferedReadStream` and we can call the new
`BufferedReadStream.TryReadFromBuffer ()`.
* `WebResponseStream.ReadAllAsync ()`: Set `bufferedEntireContent = true`
after reading the entire response body.
* …
=> [System]: Allow reading fully buffered `HttpWebResponse` body after close.  #10645.

mono/mini/aot-compiler.c
Instead of
```
push    {r4, r5, r6, r7, r10, r11, lr}
```
LLVM will generate
```
push    {r4, r5, r6, r7, lr}
add     r7, sp, #12
push    {r9, r10}
```
Seems like this https://github.com/mono/llvm/commit/a04e9e4a0af16f15ace258e81448b7eeca5ff599 assumes that `-disable-fp-elim` is passed for iOS targets. I wondered why this wouldn't break things for them, but when you run `clang` from Xcode with `-v`, you will discover that its driver passes `-mdisable-fp-elim`.
Together with https://github.com/mono/llvm/pull/48 this fixes crashes with FullAOT+LLVM on iOS 32bit.
Fixes https://github.com/mono/mono/issues/15058
Backport of #15617.
/cc @lewurm
=> [2019-06] [llvm] avoid FP elimination on iOS/armv7

mono/eglib/eglib-remap.h, mono/eglib/glib.h, mono/eglib/gstr.c, mono/eglib/test/string.c, mono/mini/cfgdump.c
See https://github.com/mistydemeo/tigerbrew/issues/605.
See https://www.gnu.org/software/gnulib/manual/html_node/strnlen.html.
Note that the patch referred to using max and strlen isn't quite right.
strnlen is not supposed to scan past the specified number of bytes.
=> g_strnlen for portability.

mono/utils/networking-posix.c
But next let's consider -Wunused-function.
=> Fix warning: unused function get_address_from_sockaddr

mcs/class/System/System.Net/BufferedReadStream.cs, mcs/class/System/System.Net/WebConnectionStream.cs, mcs/class/System/System.Net/WebRequestStream.cs, mcs/class/System/System.Net/WebResponseStream.cs, mcs/class/System/Test/System.Net/HttpWebRequestTest.cs
[System]: Allow reading fully buffered `HttpWebResponse` body after close.
If we have already read the entire response body, then we should allow the
user to read it even after the request has been aborted.
* `WebConnectionStream.Read ()`: Move `Operation.ThrowIfClosedOrDisposed ()`
call down after argument checks and call a new protected abstract method
called `TryReadFromBufferedContent ()` prior to it.
* `WebResponseStream.TryReadFromBufferedContent ()`: Implement it here.
If the entire response body has been buffered, then `bufferedEntireContent`
is true and `innerStream is BufferedReadStream` and we can call the new
`BufferedReadStream.TryReadFromBuffer ()`.
* `WebResponseStream.ReadAllAsync ()`: Set `bufferedEntireContent = true`
after reading the entire response body.
* …
=> [2019-06] [System]: Allow reading fully buffered `HttpWebResponse` body after close.  #10645.

mono/eglib/gstr.c
Prefer strlen + memcpy over strcat.
=> Remove quadratic behavior from g_strconcat.

mono/metadata/icall.c, mono/metadata/reflection-internals.h, mono/metadata/reflection.c, mono/mini/debugger-agent.c, netcore/CoreFX.issues.rsp
Fixes #15075
The `else if` block didn't appear to be hit regardless when running the netcore tests, but I don't know for sure whether it's dead code in classic Mono so I've just ifdef'd it.
=> [netcore] Don't default to mscorlib in Assembly.GetType

mcs/class/System/Assembly/AssemblyInfo.cs
Add TypeForwards for:
* System.IO.Enumeration.FileSystemName
* System.Security.Cryptography.CryptographicOperations
Since these were removed in NS 2.1
=> Add TypeForwards for FileSystemName & CryptographicOperations

mcs/class/System/Assembly/AssemblyInfo.cs
Add TypeForwards for:
* System.IO.Enumeration.FileSystemName
* System.Security.Cryptography.CryptographicOperations
Since these were removed in NS 2.1
Backport of #15652.
/cc @akoeplinger @steveisok
=> [2019-06] Add TypeForwards for FileSystemName & CryptographicOperations

configure.ac, mono/utils/mono-threads-windows.c, winconfig.h
And fix mingw warning unused function __readfsdword.
Prepare for, but don't actually, bumping minimum from Windows 7 to Windows 8. If there is a UWP-specific build, it will use the Windows 8 version.
=> Cleanup mono_threads_platform_get_stack_bounds.

configure.ac, winconfig.h
They are never checked and all relevant systems have all of them.
=> Remove configure cruft -- Interlocked and GetProcessId.

configure.ac, mono/metadata/w32socket.c, mono/mini/mini-exceptions.c, mono/utils/mono-threads-aix.c, mono/utils/networking-posix.c
Minor changes/patches I had sitting around for a few weeks, mostly preparing for things to be done in the future. Basically:
1. Set up the infrastructure for sigaltstack. Turns out it had similar limitations to macOS. This is useful in the future, but don't enable it just yet. There's a few deadlocks in the crash reporter with it on that I'd want to look at before turning it on by default..
2. Set up stuff for i getifaddrs equivalent. This will be useful for NetworkInface when it gets converted to CoreFX. Unfortunately for me, none of the codepaths using this are actually compiled in out of the box, because SIOCGIFADDR is hoisted above getiffaddrs in `networking-posix`, which may not be preferred, and the other usage is only for macOS/FreeBSD (though I haven't determined if a similar …
=> Misc AIX/PASE tweaks

mono/metadata/metadata.c, mono/tests/Makefile.am, mono/tests/calli_native.il, mono/tests/libtest.c
According to ECMA-335 § II.15.3, calling conventions other than "default" and
"vararg" describe unmanaged methods. Accordingly they should be treated as
pinvokes so that that their calling conventions are respected.
=> [metadata] Respect unmanaged calling conventions in function signatures.

tools/offsets-tool/MonoAotOffsetsDumper.cs
**NOTE: please backport to 2019-06, it is required to allow Xamarin.Android to switch to that branc**
Context: https://github.com/xamarin/xamarin-android/pull/3155
Android NDK r20 contains a header file (`ioctl.h`) with this code:
int ioctl(int __fd, int __request, ...);
#if !defined(BIONIC_IOCTL_NO_SIGNEDNESS_OVERLOAD)
/* enable_if(1) just exists to break overloading ties. */
int ioctl(int __fd, unsigned __request, ...) __overloadable __enable_if(1, "") __RENAME(ioctl);
#endif
The `_RENAME` macro is defined as `__asm__(x)` and serves the purpose of
replacing an existing symbol with the new one, decorated with the keyword.
Unfortunately, Mono's `offsets-tool` doesn't parse the header properly as
`CppSharp` doesn't understand `__asm__`:
Processing triple: armv7-none-linux-androideabi
Error …
=> [2019-06] Fix offsets tool for Android NDK r20

mono/metadata/class.c, netcore/CoreFX.issues.rsp
Mono used to return `true` for these three cases (see System.Reflection.Tests.TypeTests.IsAssignableFrom tests):
```csharp
using System.Reflection;
using Xunit;
namespace ConsoleApp
{
public static class Program
{
static void Main(string[] args)
{
Assert.False(typeof(TI_Interface1[]).GetTypeInfo().IsAssignableFrom(
typeof(TI_StructWithInterface[]).GetTypeInfo()));
Assert.False(typeof(int?[]).GetTypeInfo().IsAssignableFrom(
typeof(int[]).GetTypeInfo()));
Assert.False(typeof(int[]).GetTypeInfo().IsAssignableFrom(
typeof(int?[]).GetTypeInfo()));
}
}
public interface TI_Interface1 { }
public struct TI_StructWithInterface : TI_Interface1 { }
}
```
Fixes https://github.com/mono/mono/issues/10848
Fixes https://github.com/mono/mono/issues/15080
Unrelated …
=> [netcore] Fix IsAssignableFrom

mcs/class/corlib/System/TimeZoneInfo.MonoTouch.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs, sdks/ios/runtime/runtime.m
Fixes https://github.com/mono/mono/issues/14839
The local timezone name was not known and defaulted to "Local". 
This change adds an sdk function that returns the local name and sets TimeZoneInfo.Local accordingly.
=> [ios] Ensure Local TimeZone Id is Set For TimeZoneInfo.Local 

tools/offsets-tool/MonoAotOffsetsDumper.cs
**NOTE: please backport to 2019-06, it is required to allow Xamarin.Android to switch to that branc**
Context: https://github.com/xamarin/xamarin-android/pull/3155
Android NDK r20 contains a header file (`ioctl.h`) with this code:
int ioctl(int __fd, int __request, ...);
#if !defined(BIONIC_IOCTL_NO_SIGNEDNESS_OVERLOAD)
/* enable_if(1) just exists to break overloading ties. */
int ioctl(int __fd, unsigned __request, ...) __overloadable __enable_if(1, "") __RENAME(ioctl);
#endif
The `_RENAME` macro is defined as `__asm__(x)` and serves the purpose of
replacing an existing symbol with the new one, decorated with the keyword.
Unfortunately, Mono's `offsets-tool` doesn't parse the header properly as
`CppSharp` doesn't understand `__asm__`:
Processing triple: armv7-none-linux-androideabi
Error …
=> Fix offsets tool for Android NDK r20

sdks/ios/runtime/runtime.m
In runtime.m added nil check in xamarin_timezone_get_local_name. Returns Local as the Id in the case of nil.
=> [ios] Nil Check to Ensure Local TimeZone Id is Set For TimeZoneInfo.Local

configure.ac, mono/metadata/assembly.c
netcore doesn't have a GAC.  Some other embedded Mono configurations could benefit from this, too.
=> Add configure flag to disable GAC support; disable GAC in netcore

mcs/class/corlib/System/TimeZoneInfo.MonoTouch.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs, sdks/ios/runtime/runtime.m
Fixes https://github.com/mono/mono/issues/14839
The local timezone name was not known and defaulted to "Local". 
This change adds an sdk function that returns the local name and sets TimeZoneInfo.Local accordingly.
Backport of #15667.
/cc @akoeplinger @steveisok
=> [2019-06] [ios] Ensure Local TimeZone Id is Set For TimeZoneInfo.Local 

sdks/ios/runtime/runtime.m
In runtime.m added nil check in xamarin_timezone_get_local_name. Returns Local as the Id in the case of nil.
Backport of #15682.
/cc @steveisok
=> [2019-06] [ios] Nil Check to Ensure Local TimeZone Id is Set For TimeZoneInfo.Local

mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c, mono/tests/libtest.c, mono/tests/pinvoke2.cs
Fixes #15366 and #15306.
- Fixes NULL termination of `StringBuilder` to UTF-16 marshalling. Additionally an extra NULL is added as defense-in-depth protection for incorrect handling in native calls. This extra NULL adds protection when trying to marshal the NULL-terminated string back and the native function doesn't null-terminate at the size of the buffer.
- Fixes marshalling back from UTF-16/UTF-8 buffers into chunked `StringBuilder`.
- Fixes missing `mono_marshal_free` call causing a memory leak when marshalling `StringBuilder` to UTF-16 and back.
- Skips marshalling back to `StringBuilder` when the parameter doesn't have `[Out]` attribute.
Unit tests are still TBD. Not sure where to put them and how to structure them. Any help would be appreciated. /cc @vargaz @EgorBo 
Backport of …
=> [2019-06] Fix marshalling bugs for StringBuilder parameters

mono/mini/debugger-agent.c
The example that reproduces the bug does this:
var thread = vm.GetThreads()[0];
greetingValue = program.InvokeMethod(thread, greeting, new Value[0]) as StringMirror;
But sometimes the Thread[0] was the MainThread of the program and it works, and other times was the GC Finalizer, but when it tries to run something on GC Finalizer thread, the thread is not suspended and throws an exception.
In the fix I removed the Finalizer thread of the list that is returned when CMD_VM_ALL_THREADS is called if the thread is not executing a managed code.
Fixes #13311
=> [debugger] Don't list finalizer gc thread if it's not executing managed code

mono/mini/debugger-agent.c
The example that reproduces the bug does this:
var thread = vm.GetThreads()[0];
greetingValue = program.InvokeMethod(thread, greeting, new Value[0]) as StringMirror;
But sometimes the Thread[0] was the MainThread of the program and it works, and other times was the GC Finalizer, but when it tries to run something on GC Finalizer thread, the thread is not suspended and throws an exception.
In the fix I removed the Finalizer thread of the list that is returned when CMD_VM_ALL_THREADS is called if the thread is not executing a managed code.
Fixes #13311
Backport of #15618.
=> [2019-06] [debugger] Don't list finalizer gc thread if it's not executing managed code

mono/metadata/assembly.c
=> [netcore] Ignore public key when matching assemblies

mono/mini/main-core.c
Mono historically was quite lax in how it resolved assembly references - it
would pick the first assembly with a matching simple name.  The "strict"
mode (available in framework Mono with `--assembly-loader=strict`) follows the
spec behavior: the version and public key token of the candidate assembly must
match what is requested.
=> [netcore] Use the strict loader

mono/mini/mini-runtime.c
Fix use of freed memory.
Move the free later, on the assumption that the free itself doesn't use memory now freed before it.
valgrind:
==29462== Invalid read of size 8
==29462==    at 0x139078: mono_get_lmf (mini-runtime.c:748)
==29462==    by 0x1917E7: mono_thread_state_init (mini-exceptions.c:3626)
==29462==    by 0x63DA1B: mono_threads_enter_gc_safe_region_unbalanced_with_info (mono-threads-coop.c:333)
==29462==    by 0x63D8F6: mono_threads_enter_gc_safe_region_with_info (mono-threads-coop.c:293)
==29462==    by 0x638E8B: mono_thread_info_suspend_lock_with_info (mono-threads.c:1415)
==29462==    by 0x638F34: mono_thread_info_suspend_lock (mono-threads.c:1431)
==29462==    by 0x566FB7: acquire_gc_locks (sgen-stw.c:87)
==29462==    by 0x567036: sgen_client_stop_world (sgen-stw.c:111) …
=> Fix use after free.

mono/utils/mono-error-internals.h
Fixes https://github.com/mono/mono/issues/15692.
=> [runtime] Fix the error message for exceptions created from MonoError.

mono/mini/mac-entitlements.plist
This avoids the issue from https://github.com/mono/mono/issues/13445 when hardened runtime is enabled.
=> Add com.apple.security.cs.allow-unsigned-executable-memory exception to hardened runtime entitlements

mono/utils/mono-proclib.c
I didn't think this through with the initial attempt. Since this is UTF-16 the string comes in pairs of two-bytes, with one of them often being null when converted up from ASCII. This should print the string properly.
=> Print two bytes at a time in mono_pe_file_map conversion error

mono/mini/mac-entitlements.plist
This avoids the issue from https://github.com/mono/mono/issues/13445 when hardened runtime is enabled.
Backport of #15721.
=> [2019-06] Add com.apple.security.cs.allow-unsigned-executable-memory exception to hardened runtime entitlements

mono/metadata/icall.c
=> Fix leaks in mono_lookup_internal_call_full_with_flags, for lack of destructors.

packaging/MacSDK/msbuild.py
Bump msbuild to stop disabling compiler server in msbuild
=> [2019-06][msbuild] Bump msbuild to msbuild:mono-2019-06 to stop disabling compiler server

netcore/CoreFX.issues.rsp
`System.Reflection.Tests.CustomAttributeTests.CustomAttributeNamedArguments_Field` test from https://github.com/mono/mono/issues/15339 passes locally with latest master on macOS.
`System.Reflection.Tests.CustomAttributeTests.TestDllImportPseudoCustomAttribute` and 
`System.Reflection.Tests.CustomAttributeTests.TestMarshalAsPseudoCustomAttribute` fail with the same exception (see https://github.com/mono/mono/issues/15340).
=> [netcore] Clean up rsp-file

mono/mini/interp/interp.c
The truncated store to the top of the stack in`MINT_INTRINS_UNSAFE_BYTE_OFFSET` could cause the upper bytes of the address used as the first argument to `ByteOffset` to linger, yielding inaccurate (and usually excessively large) offsets on systems where `sizeof(void *) > sizeof(guint32)`; this made
`System.Text.Unicode.Utf8Utility.GetPointerToFirstInvalidByte` return nonsense results.
The truncation in `MINT_INTRINS_UNSAFE_ADD_BYTE_OFFSET` hasn't, as far as I know, caused any test failures. But `AddByteOffset` takes an `IntPtr` as its second argument, not an `int`.
Fixes #14847.
=> [interp] Use correctly-sized writes and reads in Unsafe.AddByteOffset and Unsafe.ByteOffset

mono/mini/method-to-ir.c, mono/tests/Makefile.am
This supersedes #14166 - enable `dim-constrainedcall.exe` and also make a fix so it works with FullAOT. 
---
This is to handle the following example.  The issue is that in `Check()` we have
a constrained call where the called method is ``IAdder`1<!!U>::PlusPlus()`` which
is a default interface method, and we need to determine at runtime whether to
box the this argument.
```csharp
using System;
public interface IAdder<T> {
int Add (int x);
int PlusPlus () {
return Add (1);
}
}
interface IGen3<T> { }
struct Adder<T> : IAdder<IGen3<T>> {
int _field;
public int Add (int x) {
_field = x + _field;
return _field;
}
}
public class P {
public static int Check<T, U>(T t) where T : IAdder<U> {
return t.PlusPlus () + t.PlusPlus ();
}
public static void Main () {
var x = new Adder<object> ();
int y = …
```
=> [2019-06] [mini] Runtime check if boxing is needed for DIM constrained calls

mono/mini/method-to-ir.c, mono/tests/Makefile.am
This supersedes #14166 - enable `dim-constrainedcall.exe` and also make a fix so it works with FullAOT. 
---
This is to handle the following example.  The issue is that in `Check()` we have
a constrained call where the called method is ``IAdder`1<!!U>::PlusPlus()`` which
is a default interface method, and we need to determine at runtime whether to
box the this argument.
```csharp
using System;
public interface IAdder<T> {
int Add (int x);
int PlusPlus () {
return Add (1);
}
}
interface IGen3<T> { }
struct Adder<T> : IAdder<IGen3<T>> {
int _field;
public int Add (int x) {
_field = x + _field;
return _field;
}
}
public class P {
public static int Check<T, U>(T t) where T : IAdder<U> {
return t.PlusPlus () + t.PlusPlus ();
}
public static void Main () {
var x = new Adder<object> ();
int y = …
```
=> [mini] Runtime check if boxing is needed for DIM constrained calls

mono/utils/mono-proclib.c
I didn't think this through with the initial attempt. Since this is UTF-16 the string comes in pairs of two-bytes, with one of them often being null when converted up from ASCII. This should print the string properly.
Backport of #15523.
=> [2019-06] Print two bytes at a time in mono_pe_file_map conversion error

mono/dis/main.c, mono/metadata/appdomain.c, mono/metadata/assembly-internals.h, mono/metadata/assembly.c, mono/metadata/assembly.h, mono/metadata/domain-internals.h, mono/metadata/metadata-internals.h, mono/metadata/reflection.c, mono/mini/debugger-agent.c, tools/pedump/pedump.c
Replace runtime callers of `mono_domain_loaded_full` by `mono_domain_loaded_internal` - pass a `MonoAssemblyLoadContext` to the callers.  Update the search hook to take an ALC argument (for now it's not used for anything, but it will be needed to check if an assembly is already loaded in the correct ALC).
Add a temporary `mono_domain_ambient_alc` function which just returns the default ALC, but is meant to mark a place where we should be getting an ALC from the callers.
=> [loader] Pass ALC to mono_domain_loaded_internal, and then to domain search hook

sdks/builds/android.mk, sdks/builds/ios.mk, sdks/builds/mac.mk
It takes all THIRD-PARTY-NOTICES.TXT and LICENSE files from the repo.
/cc @marek-safar @grendello
=> [sdks] Add third party notices to sdks archives

sdks/builds/android.mk, sdks/builds/ios.mk, sdks/builds/mac.mk
It takes all THIRD-PARTY-NOTICES.TXT and LICENSE files from the repo.
/cc @marek-safar @grendello 
Backport of #15741.
=> [2019-06] [sdks] Add third party notices to sdks archives

mono/metadata/assembly.c
Fixes crash in System.Reflection.Tests netcore testsuite in
System.Reflection.Tests.AssemblyNetCoreAppTests.AssemblyGetForwardedTypesLoadFailure
=> [netcore] Pass ALC in second loader request in load_reference_by_aname_default_asmctx

mono/utils/mono-context.h, sdks/builds/ios.mk, sdks/builds/runtime.mk, sdks/builds/wasm.mk, tools/offsets-tool-py/Makefile, tools/offsets-tool-py/offsets-tool.py
The C# version doesn't work on 64bit. It would require to update its dependencies, but Zoltan already added a Python version for WebAssembly which works fine.
Some notes:
* changed the semantics of `--xcode-path` in order to match the output of `xcode-select -p`
* switched to python3/pip3
* removed hack for arm64_32, it works properly now because the Python version uses stock `clang`
* removed some leftover usages of `XCODE32_DIR`.
Manually verified by comparing output with the C# version.
This will unblock the iOS team when building on Catalina/Xcode11, as they can't consume SDK archives there. See https://github.com/xamarin/xamarin-macios/pull/6603#issuecomment-512803082
=> [ios] switch to python offset tool

sdks/wasm/framework/src/WebAssembly.Bindings/Core/Array.cs, sdks/wasm/tests/browser/src/BindingsTestSuite/BindingsTestSuite.cs, sdks/wasm/tests/browser/src/BrowserTestSuite/core-bindings-spec.js
if the WebAssembly.Core.Array is empty instead of throwing error.
- Add test to the BindingsTestSuite.
Fixes https://github.com/mono/mono/issues/15731
=> [wasm][bindings] WebAssembly.Core.Array.Pop should return null 

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/TypeMirror.cs
Fixing two issues in TypeMirror.CSharpName computation (not sure if this property is actively used):
- there is a typo on S**B**yte primitive, preventing System.SByte -> sbyte.
- array rank display is wrong. For example System.Byte[,,,] has GetArrayRank() == 4, so the previous computation gave byte[,,,,] instead of byte[,,,]
=> [sdb] Fix TypeMirror.CSharpName computation

mono/metadata/icall-def-netcore.h, mono/metadata/threads.c, mono/utils/mono-threads-aix.c, mono/utils/mono-threads-android.c, mono/utils/mono-threads-freebsd.c, mono/utils/mono-threads-haiku.c, mono/utils/mono-threads-linux.c, mono/utils/mono-threads-mach.c, mono/utils/mono-threads-netbsd.c, mono/utils/mono-threads-openbsd.c, mono/utils/mono-threads-wasm.c, mono/utils/mono-threads-windows.c, mono/utils/mono-threads.h, netcore/System.Private.CoreLib/src/System.Threading/Thread.cs
Fixes #15728
Not sure what to do for wasm and Haiku, so I've put a fairly boring attempt down for now (that's almost certainly wrong in Haiku's case). Most of the platform-specific behavior is exactly copied from CoreCLR.
Not sure if there are any tests I need to re-enable now that this is added, but I don't think so.
=> [netcore] Implement Thread.CurrentOSThreadId

netcore/CoreFX.issues.rsp, netcore/System.Private.CoreLib/src/System.Reflection/RuntimeFieldInfo.cs
`Expression.Bind` should throw `ArgumentException` if called with `FieldInfo` for a global field. The exception is thrown from validation of the (null) `DeclaringType` (see https://github.com/dotnet/corefx/pull/15318).
Mono returns `"<Module>"` in this case and doesn't throw so the test fails. 
Fixes #14917 .
=> [netcore] Make System.Linq.Expressions.Tests.BindTests.GlobalField Pass

sdks/wasm/README.md, sdks/wasm/common/Signing.props, sdks/wasm/framework/src/Directory.Build.props, sdks/wasm/framework/src/WebAssembly.Bindings/WebAssembly.Bindings.csproj, sdks/wasm/framework/src/WebAssembly.Net.Http/WebAssembly.Net.Http.csproj, sdks/wasm/framework/src/WebAssembly.Net.WebSockets/WebAssembly.Net.WebSockets.csproj, sdks/wasm/sdk/Directory.Build.props, sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.csproj, sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets, sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets.buildschema.json, sdks/wasm/sdk/Mono.WebAssembly.Framework/Mono.WebAssembly.Framework.csproj, sdks/wasm/sdk/Mono.WebAssembly.Runtime.Framework/Mono.WebAssembly.Runtime.csproj, sdks/wasm/sdk/Mono.WebAssembly.Sdk/Mono.WebAssembly.Sdk.csproj, sdks/wasm/sdk/WebAssembly.Bindings.Framework/WebAssembly.Bindings.csproj, sdks/wasm/sdk/WebAssembly.Net.WebSockets/WebAssembly.Net.WebSockets.csproj
- Add the `Signing.props` to the `Directory.Build.props`
- Modify framework build to use the 'Signing.props' file
- To enable the build with threads set `<EnableMonoWasmThreads>true</EnableMonoWasmThreads>`
- default is false.
Closes: https://github.com/mono/mono/issues/15757
Closes: https://github.com/mono/mono/issues/15734
Closes: https://github.com/mono/mono/issues/15481
=> [wasm][sdk] Fix issues with SDK packaging

netcore/CoreFX.issues.rsp
Was fixed by https://github.com/mono/mono/pull/15752
=> [netcore] Re-enable AssemblyGetForwardedTypesLoadFailure

mcs/class/corlib/Test/System/TypeTest.cs, mono/metadata/class.c
Fixes #15647
I don't actually like this patch, as it's another special-case in an already patchwork function, but it fixes the immediate issue. At some point, mono_class_is_assignable_from_checked should probably just be refactored, but doing that without breaking anything is a rather daunting task.
=>  Special-case arrays of interfaces/generic parameters in IsAssignableFrom

mono/mini/interp/interp.c, mono/mini/interp/transform.c
If the ctor was inlined, the newobj instruction receives a max ushort as the data item for the index, so it doesn't execute the ctor in this case. Also, when inlining, we need to push on the stack the allocated object, once as argument for the ctor and the second needs to remain on the stack as the result of the IL newobj instruction.
=> [interp] Enable inlining of object constructors

mcs/class/corlib/System/TimeZoneInfo.cs
As an addition to https://github.com/mono/mono/pull/15401 it should resolve XA-related issue.
Fixes #9664
=> Fix ambiguous time at the end of DST period on Windows

m4/ax_append_flag.m4, m4/rh6-compat.m4
This was broken in e7f9dbe73c3344c96a13892a6c4c45f8e5c35aa3, because
AS_VAR_APPEND does not exist until v2.63b (?!)
=> Fix build on Autoconf 2.63

mono/metadata/assembly.c, mono/metadata/reflection.c, netcore/CoreFX.issues.rsp
Fixes #15077
Fixes #11269
Possibly fixes other things?
I've broken this into separate commits to make clearer what's going on.
The first issue present is that the assembly info was parsed case-insensitively, so setting a lowercase 'p' in PublicKeyToken would result in it not being parsed. When fixing this, the test then consistently failed whether or not the first letter was capitalized.
The second issue, somewhat hidden by the first, is that the public key token is copied directly from the input string and then compared case-sensitively in the assembly lookup. I've added two commits to deal with this, one lowercasing the PKT on parse and one making the later comparison case-insensitive. Either of them individually solves the issue, but I think it's worth doing both for good measure. …
=> [netcore] Make assembly name parsing and comparison case-insensitive

mcs/class/corlib/System/TimeZoneInfo.cs
As an addition to https://github.com/mono/mono/pull/15401 it should resolve XA-related issue.
Fixes #9664 
Backport of #15548.
/cc @akoeplinger @MaximLipnin
=> [2019-06] Fix ambiguous time at the end of DST period on Windows

mcs/class/corlib/Test/System/TypeTest.cs, mcs/class/corlib/corert/Type.cs
Fixes a stack overflow when running Staxel under wine-mono.
=> [corlib] Foward System.Type.GetTypeFromProgID() to the correct function.

mono/metadata/assembly-internals.h
assembly.c `exact_sn_match` uses bitwise-or on MonoAssemblyNameEqFlags
Tested witih:
```console
$ ./autogen.sh --with-core=only --enable-cxx
$ make
```
=> [cxx][netcore] Fix C++ build

mono/utils/mono-error-internals.h
Fixes https://github.com/mono/mono/issues/15692.
Backport of #15705.
/cc @vargaz
=> [2019-06] [runtime] Fix the error message for exceptions created from MonoError.

netcore/CoreFX.issues.rsp, netcore/CoreFX.issues_linux_arm64.rsp, netcore/Makefile, netcore/System.Private.CoreLib/src/System/Delegate.cs
Fixes https://github.com/mono/mono/issues/15008
Test case:
```csharp
using System;
public enum Enum1 : long
{
A,
B,
C
}
public enum Enum2 : long
{
A,
B,
C
}
public sealed class Program
{
public Enum1 Test => Enum1.A;
static void Main(string[] args)
{
var del1 = typeof(Program).GetProperty("Test").GetGetMethod().CreateDelegate(typeof(Func<Program, Enum1>));
// the Test property is of Enum1 type but we can use Enum2 too
var del2 = typeof(Program).GetProperty("Test").GetGetMethod().CreateDelegate(typeof(Func<Program, Enum2>));
}
}
```
Also, ignore `System.Transactions.Tests` - extremely slow on our CI (slow hardware?) and even timeouts sometimes
=> [netcore] Allow different enums as return type in CreateDelegate

mcs/class/corlib/System.Reflection.Emit/DynamicMethod.cs, mono/metadata/sre.c, netcore/CoreFX.issues.rsp, netcore/System.Private.CoreLib/src/System.Reflection.Emit/DynamicMethod.cs
Before, reflection_create_dynamic_method could end up being called by two threads simultaneously. At the end of the method the ilgen field of the MonoReflectionDynamicMethod object is cleared, to enable its collection since it is no longer needed. The problem with this is that it can confuse the other thread compiling the dynamic method, making it see that there is no body.
We could either bother making this clearing work with multiple threads (and I'm not 100% convinced that the rest of the code is thread safe), disable the clearing of ilgen (which would make us use more memory) or go with the simple approach of locking on this DynamicMethod so only one thread is compiling it at one time.
Fixes mainly _Invalid IL, method body is empty_ crashes like …
=> [sre] Make creation of dynamic method synchronized

scripts/ci/pipeline-netcore-runtime.yml
I talked to @ViktorHofer and corefx doesn't run tests on the internal builds, let's do the same.
=> [netcore] Run tests only on public builds

mono/utils/mono-codeman.c, mono/utils/mono-codeman.h
The uses are all void* or casted.
=> Remove unneeded auto cast with codeman.

mcs/class/System.Private.CoreLib/System.Reflection.Emit/DynamicMethod.cs, mcs/class/corlib/System.Reflection.Emit/DynamicMethod.cs, mono/metadata/sre.c
Before, reflection_create_dynamic_method could end up being called by two threads simultaneously. At the end of the method the ilgen field of the MonoReflectionDynamicMethod object is cleared, to enable its collection since it is no longer needed. The problem with this is that it can confuse the other thread compiling the dynamic method, making it see that there is no body.
We could either bother making this clearing work with multiple threads (and I'm not 100% convinced that the rest of the code is thread safe), disable the clearing of ilgen (which would make us use more memory) or go with the simple approach of locking on this DynamicMethod so only one thread is compiling it at one time.
Backport of https://github.com/mono/mono/pull/15803
=> [2019-06][sre] Make creation of dynamic method synchronized

mono/tests/merp-crash-test.cs
If any of the stress tests fail, return a non-zero exit code from the
supervising process.
Fixes #15781
=> [tests] Return non-zero exit code if from MERP crash test on failure

mono/metadata/class-init.c, mono/metadata/class.c, mono/metadata/metadata.c, mono/tests/Makefile.am, mono/tests/recursive-generics.3.cs
Don't try to layout the field to find out if it's blittable.
Fixes certain recursive examples.
```csharp
using System;
namespace TestRecursiveType
{
class Program
{
static void Main(string[] args)
{
SubClass subC = new SubClass();
Console.WriteLine(subC.GetTest());
}
}
public struct ValueTest<U>
{
// When U is instantiated with T, from BaseClass, we know it'll be a
// reference field, so we know the instantiation ValueTest<T> won't
// be blittable.
public readonly U value;
}
public abstract class BaseClass<T> where T : BaseClass<T>
{
public ValueTest<T> valueTest = default(ValueTest<T>);
}
public class SubClass : BaseClass<SubClass>
{
private String test = "test";
public string GetTest()
{
return test;
}
}
}
```
Fixes https://github.com/mono/mono/issues/15760
---
=> [metadata] Fields whose types are gparams with a reference type constraint aren't blittlable.

sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs
- 2.1.801 seems to have a problem with:
```
using (var uint8Buffer = Uint8Array.From(await request.Content.ReadAsByteArrayAsync ()))
```
=> [wasm][cli] Fix http framework module that errors using SDK 2.1.801

mcs/class/Mono.Posix/Documentation/en/Mono.Unix.Native/Syscall.xml, mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs, mcs/class/Mono.Posix/Mono.Unix/UnixFileSystemInfo.cs, mcs/class/Mono.Posix/Mono.Unix/UnixStream.cs, mcs/class/Mono.Posix/Mono.Unix/UnixSymbolicLinkInfo.cs
Fixes https://github.com/mono/mono/issues/10748
The calls for chown, lchown, fchown, and fchownat (from `Mono.Unix.Native.Syscall`) are all declared with unsigned integers for the `owner` and `group` parameters. This is incorrect.
Directly from the manpage
`man 2 chown`
<pre><code>
...
int chown(const char *pathname, uid_t owner, gid_t group);
int fchown(int fd, uid_t owner, gid_t group);
int lchown(const char *pathname, uid_t owner, gid_t group);
...
int fchownat(int dirfd, const char *pathname,
uid_t owner, gid_t group, int flags);
...
...
<b>If the owner or group is specified as -1</b>, then that ID is not changed.
...
</pre></code>
Emphasis added on the documentation explaining how the parameters can take the value -1, clearly not an unsigned integer. The `uid_t` struct is not an …
=> Parameters for chown should be signed integers not unsigned

sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs
- 2.1.801 seems to have a problem with:
```
using (var uint8Buffer = Uint8Array.From(await request.Content.ReadAsByteArrayAsync ()))
```
Backport of #15844.
/cc @lewing @kjpou1
=> [2019-06] [wasm][cli] Fix http framework module that errors using SDK 2.1.801

configure.ac, netcore/Makefile, netcore/runtime.nuspec, scripts/ci/pipeline-netcore-runtime.yml
When https://github.com/mono/mono/commit/9010d2f290d28dc97ac276e0c0d32a2932b7550f was merged we stopped including mcs/build/config.make.
However, that file set the VERSION variable which wasn't migrated to the new netcore/config.make so the nuget package missed the version.
Additionally, System.Private.CoreLib sources were moved into the netcore folder and we now seemingly need to pass `-p:IsPackable=true` for dotnet pack to build the nuget package.
=> [netcore] Fix building of nupkg

packaging/MacSDK/msbuild.py
.. which updates to SDKs from dotnet `3.0.1xx`
(https://github.com/mono/msbuild/pull/117)
=> Bump msbuild to track mono-2019-06

packaging/MacSDK/nuget.py
This is a bit delayed as the 5.2.0 `nuget.exe` wasn't available earlier.
=> Update nuget.exe to 5.2.0, matching msbuild

mono/metadata/handle.c, mono/metadata/handle.h, mono/metadata/icall-decl.h, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/w32file.c, mono/utils/mono-threads-state-machine.c
And inline `mono_array_handle_length`.
And remove `inline` in .c files a little -- it only belongs in .h.
=> [Coop] Convert System.Buffer.

mono/metadata/threads-types.h, mono/metadata/threads.c
Unused since https://github.com/mono/mono/commit/b5c0c831da328b8ab7b7283a38fa56baaa7ae380.
And not likely to come back.
=> Remove mono_thread_get_name.

packaging/MacSDK/msbuild.py, packaging/MacSDK/nuget.py
.. to pick changes from mono/msbuild#119
```
[mono] Update to track upstream master and update SDKs
.. to track dotnet/toolset's release/3.0.1xx branch.
```
And update nuget.exe to 5.2.0, to match msbuild
=> Update msbuild to xplat-master

mono/metadata/marshal.c
Remove the raw pointer that static analysis will flag.
Extracted from https://github.com/mono/mono/pull/15900.
=> [Coop] Convert mono_string_from_byvalwstr_impl.

mono/metadata/marshal.c
Static analysis prefers not even these short lived raw pointers.
Extracted from https://github.com/mono/mono/pull/15900.
=> [Coop] Convert ves_icall_string_new_wrapper_impl.

sdks/builds/android.mk, sdks/builds/ios.mk, sdks/builds/llvm.mk, sdks/builds/runtime.mk, sdks/builds/wasm.mk
Also switches the MXE cross compilers for Android and WebAssembly to 64bit host.
=> [sdks] remove 32bit llvm

sdks/builds/android.mk, sdks/builds/ios.mk, sdks/builds/llvm.mk, sdks/builds/runtime.mk, sdks/builds/wasm.mk
Also switches the MXE cross compilers for Android and WebAssembly to 64bit host.
Backport of #15896.
/cc @lewurm
=> [2019-06] [sdks] remove 32bit llvm

mono/metadata/icall-table.c, mono/mini/main.c
Albeit a little slower due to indirection.
Also fix the chance of overflow in the comparison of pointers.
Subtraction is not safe.
=> Fix race condition and use less memory in mono_lookup_icall_symbol.

mono/metadata/cominterop.c, mono/tests/cominterop.cs, mono/tests/libtest.c
Fixes a bug running Rak24u with wine-mono: <https://bugs.winehq.org/show_bug.cgi?id=47561>
=> [cominterop] Handle NULL pointers when marshalling native-to-managed return values.

mono/metadata/cominterop.c, mono/metadata/cominterop.h, mono/metadata/marshal.c, mono/metadata/metadata.c, mono/tests/cominterop.cs
This fixes Game Maker Studio 2 Desktop under Wine.
=> [cominterop] Always marshal a class as a COM interface if it has the InterfaceType attribute set.

configure.ac
We test dlopen with no library and in libdl later, without the use of this setting.
Got the hint since I'm building for a configuration which had it set wrong.
=> Remove unused libdl setting

mono/metadata/object-offsets.h, mono/mini/decompose.c, mono/utils/mono-error-internals.h, tools/offsets-tool-py/offsets-tool.py
Previously, we would emit a call to memset since the struct is large (> 100 bytes). Only the error code
field needs to be initialized.
=> [jit] Optimize the initialize of MonoError locals.

mono/metadata/appdomain.c, mono/metadata/attach.c, mono/metadata/gc.c, mono/metadata/threadpool-io.c, mono/metadata/threadpool.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/mini/aot-compiler.c, mono/mini/debugger-agent.c, mono/mini/mini-posix.c, mono/profiler/aot.c, mono/profiler/log.c
Extracted from https://github.com/mono/mono/pull/15859.
=> mono_thread_set_name_internal change boolean parameters to enum flags.

configure.ac, mcs/class/corlib/System.Threading/Thread.cs, mono/metadata/object-internals.h, netcore/System.Private.CoreLib/src/System.Threading/Thread.cs
- Remove unused.
- Add missing that just happened to work.
- Synchronize size between netcore and regular. `#if` considered bad.
Extracted from https://github.com/mono/mono/pull/15859.
=> Cleanup and resynchronize Thread/InternalThread fields.

mono/metadata/jit-info.c, mono/metadata/mono-conc-hash.c, mono/utils/mono-threads.c
If the thread info TLS key dtor runs `unregister_thread` from a foreign thread and we have work in the hazard pointer queue, we need to first switch to GC Unsafe mode because some of the free methods passed to `mono_thread_hazardous_try_free` need to be coop-aware.
Also, added checked mode assertions that `conc_table_free` and `jit_info_table_free` are called from GC Unsafe mode.
Fixes https://github.com/mono/mono/issues/15878
=> [threads] Enter GC Unsafe before pumping HP queue in unregister_thread

mono/tests/pinvoke3.cs
On some operating systems, this test can take forever because the worker starves the other threads by holding the gc_lock. Bump sleeping so it doesn't rely on OS scheduling that much and guarantees other threads can progress in reasonable amount of time.
=> [tests] Bump sleep for pinvoke3 test

eng/Version.Details.xml, eng/Versions.props
This should bring down the Microsoft.Net.Compilers package,
which contains the Roslyn binaries needed for mono packaging.
=> Add Roslyn maestro dependency

mono/metadata/jit-info.c, mono/metadata/mono-conc-hash.c, mono/utils/mono-threads.c
If the thread info TLS key dtor runs `unregister_thread` from a foreign thread and we have work in the hazard pointer queue, we need to first switch to GC Unsafe mode because some of the free methods passed to `mono_thread_hazardous_try_free` need to be coop-aware.
Also, added checked mode assertions that `conc_table_free` and `jit_info_table_free` are called from GC Unsafe mode.
Fixes https://github.com/mono/mono/issues/15878
Backport of #15890.
=> [2019-06] [threads] Enter GC Unsafe before pumping HP queue in unregister_thread

mcs/class/System/System.Net.Sockets/Socket.cs, mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs, mcs/class/System/Test/System.Net.Sockets/SocketTest.cs, mcs/class/referencesource/System/net/System/Net/Sockets/_MultipleConnectAsync.cs
We need to clearly distinguish between synchronous and asynchronous completions and avoid any ambiguities and race conditions when it comes to error handling.
On synchronous completion, we must not invoke the async completion delegate.
In `System.Net.Sockets/Socket.cs`, the internal `BeginSConnect()` and `BeginMConnect()` now return a `bool` indicating whether or not an async operation is pending.
If any error happens prior to starting the async operation, then we shall call `SocketAsyncResult.Complete(..., true)` and return `false`.  And since this is a synchronous completion, it's `AsyncCallback` will not be invoked.
In `referencesource/System/net/System/Net/Sockets/_MultipleConnectAsync.cs`, I compared the entire file against the CoreFX version and then copied the `AttemptConnection()` …
=> Fix `Socket.ConnectAsync(SocketAsyncEventArgs)` behavior.

mcs/class/System/System.Net.Sockets/Socket.cs, mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs, mcs/class/System/Test/System.Net.Sockets/SocketTest.cs, mcs/class/referencesource/System/net/System/Net/Sockets/_MultipleConnectAsync.cs
We need to clearly distinguish between synchronous and asynchronous completions and avoid any ambiguities and race conditions when it comes to error handling.
On synchronous completion, we must not invoke the async completion delegate.
In `System.Net.Sockets/Socket.cs`, the internal `BeginSConnect()` and `BeginMConnect()` now return a `bool` indicating whether or not an async operation is pending.
If any error happens prior to starting the async operation, then we shall call `SocketAsyncResult.Complete(..., true)` and return `false`.  And since this is a synchronous completion, it's `AsyncCallback` will not be invoked.
In `referencesource/System/net/System/Net/Sockets/_MultipleConnectAsync.cs`, I compared the entire file against the CoreFX version and then copied the `AttemptConnection()` …
=> [2019-06] Fix `Socket.ConnectAsync(SocketAsyncEventArgs)` behavior.

mcs/class/System/System.Net.Sockets/Socket.cs, mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs, mcs/class/System/Test/System.Net.Sockets/SocketTest.cs, mcs/class/referencesource/System/net/System/Net/Sockets/_MultipleConnectAsync.cs
We need to clearly distinguish between synchronous and asynchronous completions and avoid any ambiguities and race conditions when it comes to error handling.
On synchronous completion, we must not invoke the async completion delegate.
In `System.Net.Sockets/Socket.cs`, the internal `BeginSConnect()` and `BeginMConnect()` now return a `bool` indicating whether or not an async operation is pending.
If any error happens prior to starting the async operation, then we shall call `SocketAsyncResult.Complete(..., true)` and return `false`.  And since this is a synchronous completion, it's `AsyncCallback` will not be invoked.
In `referencesource/System/net/System/Net/Sockets/_MultipleConnectAsync.cs`, I compared the entire file against the CoreFX version and then copied the `AttemptConnection()` …
=> [2019-02] Fix `Socket.ConnectAsync(SocketAsyncEventArgs)` behavior.

mono/mini/iltests.il, mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/15794
=> [mini] Ignore conv.r.un if top of stack is already float

mono/metadata/marshal.c
For static method delegates, we have a unique delegate_trampoline that is shared among all delegates. We always keep alive the first static method delegate passed to native, by creating a normal gchandle to it and storing it in delegate_hash_table. For instance methods, each delegate will create a separate wrapper and these wrappers are never shared (which was wrongly assumed in caa4a75). We shuldn't keep the delegate alive and this commit reverts the behavior for delegate with instance methods introduced in the mentioned commit.
Fixes #15751
=> [marshal] Free delegates with target that are passed to native code.

mono/metadata/marshal.c
For static method delegates, we have a unique delegate_trampoline that is shared among all delegates. We always keep alive the first static method delegate passed to native, by creating a normal gchandle to it and storing it in delegate_hash_table. For instance methods, each delegate will create a separate wrapper and these wrappers are never shared (which was wrongly assumed in caa4a75). We shuldn't keep the delegate alive and this commit reverts the behavior for delegate with instance methods introduced in the mentioned commit.
Fixes #15751
Backport of #15935.
/cc @BrzVlad
=> [2019-06] [marshal] Free delegates with target that are passed to native code.

mcs/tools/mdoc/Makefile
Non-Linux systems largely do not support `--binary`. Since the patch appears to be text anyway, it's probably safe to remove for all platforms.
With `patch -p0` , mdoc test now provides accurate pass/fail on FreeBSD.
=> Fix patch step in mdoc tests for FreeBSD and others

sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets, sdks/wasm/sdk/Mono.WebAssembly.Build/WasmLinkAssemblies.cs
- Provide extra definitions to the linker to ensure the type, methods and/or fields are not eliminated from your application.
* Use a <LinkDescription> item as follows:
```
<ItemGroup>
<LinkDescription Include="customlinker.xml" />
</ItemGroup>
```
These will then be added to the `WasmLinkAssemblies` task step.
Example xml:
```
<linker>
<assembly fullname="mscorlib">
<type fullname="System.Environment">
<field name="mono_corlib_version" />
<method name="get_StackTrace" />
</type>
</assembly>
<assembly fullname="My.Own.Assembly">
<type fullname="Foo" preserve="fields">
<method name=".ctor" />
</type>
<type fullname="Bar">
<method signature="System.Void .ctor(System.String)" />
<field signature="System.String _blah" />
</type>
<namespace fullname="My.Own.Namespace" />
<type …
```
=> [wasm][sdk] Support for Custom Linker Configuration

mono/mini/interp/transform.c
These are very common, at least in debug builds. Optimize them away so it doesn't distort performance numbers.
=> [interp] Remove unconditional branches to next instruction

netcore/Makefile, netcore/System.Private.CoreLib/System.Private.CoreLib.csproj
Now it's possible to open `System.Private.CoreLib.csproj` in an IDE and build (use Roslyn version from `eng/Versions.props`).
=> [netcore] Make System.Private.CoreLib.csproj IDE friendly

mono/metadata/assembly-internals.h, mono/metadata/assembly-load-context.c, mono/metadata/assembly.c, mono/metadata/domain.c, mono/metadata/icall-def-netcore.h, mono/metadata/loader-internals.h, netcore/CoreFX.issues.rsp, netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml, netcore/System.Private.CoreLib/src/System.Reflection/RuntimeAssembly.cs, netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs
1. Implement the ALC referenced assembly resolving logic from https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-3.0#usage-in-the-runtime
2. Implement `AssemblyLoadContext GetLoadContext (Assembly assembly)`
---
The managed code is from https://github.com/dotnet/coreclr/blob/8ba2e15201361402acd0ae9710bd37d50785cdfa/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.CoreCLR.cs#L253-L281
And from https://github.com/dotnet/coreclr/blob/8ba2e15201361402acd0ae9710bd37d50785cdfa/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.CoreCLR.cs#L84-L187
=> [netcore] Implement referenced assembly resolving and ALC.GetLoadContext

netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs
As suggested [in a comment on 15946](https://github.com/mono/mono/pull/15946#discussion_r310227893), fix inadvertantly copy-pasted comment and make sure to use Mono terminology.
=> [netcore] Fix comments in ALC to use Mono terminology

mono/eglib/gdate-unix.c, mono/mini/mini-posix.c, mono/utils/mono-threads.c
PASE exports this AIX syscall so autoconf detects it, but using it
will trigger SIGILL (for unimplemented syscall), which emits a LIC
log entry type of 4700-000F.
=> Don't use clock_nanosleep on PASE

mono/metadata/profiler.c, mono/mini/debugger-agent.c, mono/mini/mini-llvm.c
Audit usage of `mono_debug_get_seq_points` to either avoid passing unused variables that are not freed or properly free usage of returned variables.
=> Fix usage of mono_debug_get_seq_points to avoid leaks

sdks/wasm/framework/src/WebAssembly.Bindings/JSObject.cs, sdks/wasm/framework/src/WebAssembly.Bindings/LinkDescriptor/WebAssembly.Bindings.xml, sdks/wasm/framework/src/WebAssembly.Net.Http/LinkDescriptor/WebAssembly.Net.Http.xml
- Remove the fully preserved assembly references from `WebAssembly.Bindings` and `WebAssembly.Net.Http`
Close https://github.com/mono/mono/issues/15365
=> [wasm][framework] Rework framework linker descriptions

mono/metadata/icall-table.h
Preferable would be native only, i.e. for interpreter and for when
it is actually unused, but ok for now.
Between removing the managed and the native, managed is preserved
in case there uses of MonoError in C# other than icall wrappers.
Keep them safe.
But again ideally move it to native and remove the managed type,
pending debugging WebAssembly failure doing so.
=> Remove error_init from native icall wrappers since managed does it.

mcs/class/corlib/Test/System/TimeZoneTest.cs
TimeZone.CurrentTimeZone.DaylightName returns an empty value on Android
when the system timezone is set to GMT:
D02
Expected: True
But was: False
Stack trace
at MonoTests.System.TimeZoneTest.GMT (System.TimeZone t1) [0x00039] in <e7d9f181b8344f4db486bd1abf716986>:0 
at MonoTests.System.TimeZoneTest.TestCtors () [0x000f5] in <e7d9f181b8344f4db486bd1abf716986>:0 
at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <9d875ba36f50420f9caa8cacffb879b4>:0
=> [corlib] Ignore TimeZoneTest.TestCtors on Android GMT

mono/metadata/appdomain.c, mono/metadata/appdomain.h, mono/metadata/assembly-load-context.c, mono/metadata/assembly.c, mono/metadata/domain-internals.h, mono/metadata/domain.c, mono/metadata/loader-internals.h, mono/metadata/sre.c, mono/metadata/w32process.c, mono/mini/driver.c
Notably, this PR does not touch the debugger or some of the other places that currently read domain_assemblies. Those will have to be made ALC-aware at a later date.
I'm not entirely convinced the way assemblies are freed in ALCs is correct, both due to locking and interaction with the GC, but this is an initial attempt at it. It shouldn't matter for now, but that will become relevant with collectability.
=> [netcore] Enable ALC loaded_assemblies

sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets, sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets.buildschema.json, sdks/wasm/sdk/Templates/templates/DotNet/WasmTemplate.1.csproj
Allow the selection of the WebAssembly runtime version Debug | Release
- Decouple the reliance on `_DebugSymbolsProduced` to decide which runtime version to publish.
- Add support for <MonoWasmRuntime>Debug | Release</MonoWasmRuntime>
- Add validation target of the property to Mono.WebAssembly.Build.targets.
Update templates
- Add PropertyGroups for Debug and Release to set the DebugSymbols and DebugType by default.
Close https://github.com/mono/mono/issues/16013
Close https://github.com/mono/mono/issues/16011
=> [wasm][sdk] Decoupling the WebAssembly runtime debug and release versions.

mono/mini/intrinsics.c
Fixes https://github.com/mono/mono/issues/15992.
=> [jit] Avoid asserting on Unsafe.As<T> in gsharedvt methods.

mcs/class/System/System.Net.Sockets/Socket.cs, mcs/class/System/System.Net.Sockets/SocketAsyncEventArgs.cs, mcs/class/referencesource/System/net/System/Net/Sockets/Socket.cs
Cleaning up the `SocketAsyncEventArgs` class and preparing it for it's eventual
adaption from CoreFX.
There are a few instance fields and property accessors with `internal` visibility,
which the CoreFX version does not have.  Replaced these with accessor methods.
The `PolicyRestricted` property and it's related `SocketAsyncEventArgs (bool)`
constructor is not used anywhere and the CoreFX version has a constructor with the
same signature, but different semantics.
In the CoreFX version, `Complete ()` does not call `DoComplete (this)` - renamed it
into `Complete_internal ()` to avoid any ambiguities and help the transitioning.
=> `SocketAsyncEventArgs` cleanups and preparations for the real thing.

mono/dis/main.c, mono/metadata/appdomain.c, mono/metadata/assembly-internals.h, mono/metadata/assembly.c, mono/metadata/assembly.h, mono/metadata/loader-internals.h, mono/metadata/mono-debug.c, mono/metadata/sre.c, mono/mini/aot-runtime.c, tools/pedump/pedump.c
The meat of this PR is what the title suggests, and with this commit all the basic ALC functionality should be working properly. Probably worth checking if this makes any new tests pass.
Additionally, this PR includes a second commit that switches over the search hook to use loaded_assemblies from the ALCs. This may break some existing tests due to remaining unimplemented ALC behavior, notably the native loading mechanism needed for Openssl in some of the cryptography tests. My inclination is to include the commit regardless and just disable the failing tests so that any future ALC work can watch for regressions in the loader, but I would appreciate input from @steveisok on how important those tests are. I've not disabled anything yet in order to see exactly what new failures are …
=> [netcore] Make the load hook ALC-aware

mcs/class/corlib/Test/System/TimeZoneTest.cs
TimeZone.CurrentTimeZone.DaylightName returns an empty value on Android
when the system timezone is set to GMT:
D02
Expected: True
But was: False
Stack trace
at MonoTests.System.TimeZoneTest.GMT (System.TimeZone t1) [0x00039] in <e7d9f181b8344f4db486bd1abf716986>:0 
at MonoTests.System.TimeZoneTest.TestCtors () [0x000f5] in <e7d9f181b8344f4db486bd1abf716986>:0 
at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <9d875ba36f50420f9caa8cacffb879b4>:0 
Backport of #15987. …
=> [2019-06] [corlib] Ignore TimeZoneTest.TestCtors on Android GMT

mono/metadata/assembly-load-context.c
Fixes https://github.com/mono/mono/issues/16046.
=> [netcore] Avoid calling load hooks during AOT.

netcore/CoreFX.issues.rsp
Fixes #15074 
Fixes #15170
Fixes #15172 
Some additional failures appear to be relatively low-hanging fruit, but this should get us up to date with the current status of ALCs in Mono.
=> [netcore] Update test exclusions to reflect ALC work

mono/metadata/assembly.c, netcore/CoreFX.issues.rsp
=> [netcore] Set flag for processor arch when parsing assembly names

mono/metadata/w32error.h, mono/metadata/w32socket-unix.c
Translate to WSAELOOP and WSAENAMETOOLONG, respectively.
See https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2
Backport of #16039.
=> [2019-06] [w32socket] Translate ELOOP and ENAMETOOLONG

mono/metadata/w32error.h, mono/metadata/w32socket-unix.c
Translate to WSAELOOP and WSAENAMETOOLONG, respectively.
See https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2
Backport of #16039.
/cc @akoeplinger @lambdageek
=> [2019-08] [w32socket] Translate ELOOP and ENAMETOOLONG

mono/mini/trace.c
Return value changes are especially visible for bools, where currently 4 bytes integers are printed.
=> [trace] Improve enter/leave output formatting

mono/metadata/w32error.h, mono/metadata/w32socket-unix.c
Translate to WSAELOOP and WSAENAMETOOLONG, respectively.
See https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2
=> [w32socket] Translate ELOOP and ENAMETOOLONG

mono/utils/mono-merp.c
if there are multiple threads calling (unlikely).
This zeroing was made moot by 470354fa817716739615ff0c6cfefca42ec8b385 January 2019.
=> There is no need to zero static data, and it is racy.

netcore/CoreFX.issues.rsp
This was fixed a while back by @EgorBo but never removed from the exclusions.
=> [netcore] Re-enable IsAssignableFrom test

mcs/class/corlib/ReferenceSources/Buffer.cs
Correct what appears to be a typo in System.MemoryCopy with "long, long" size arguments: use Memcpy instead of memcpy1 in the same way it is done in System.Buffer.MemoryCopy (void*, void*, ulong, ulong).
Consequently, copy is not done byte per byte for the last int.MaxValue bytes when MemoryCopy is called with long argument (most common case I guess). This should provide noticeable performance increase.
=> Use Memcpy instead of memcpy1 in System.Buffer.MemoryCopy (..., long, long)

mono/mini/llvm-jit.cpp
LLVM built with LLVM_ENABLE_ASSERTIONS=On will crash if errors are not
explicitly consumed.
=> [llvm] Explicitly check for errors when calling LegacyIRCompileLayer::addModule.

mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c, mono/mini/ee.h, mono/mini/interp-stubs.c, mono/mini/interp/interp.c
This recovers the relevant bits of the "resume state" from the interpreter and uses that to recalculate the `il_offset` for the top frame.
Fixes https://github.com/mono/mono/issues/15687.
=> [sdb][interp] Use the interpreter's resume state to compute the IL offset in compute_frame_info.

mcs/class/referencesource/mscorlib/system/rttype.cs
https://github.com/mono/mono/issues/16010
The current behavior for GetConstructorCandidates when the name is null, "",
or "*" is to return the set of constructors for the type. For "", .NET Core and
.NET Framework return 0 elements.  This PR adds a check for "" to match that
behavior.
=> Fixed RuntimeType.GetConstructorCandidates("") to return 0 elements.

man/Makefile.am, mcs/tools/aprofutil/Makefile, mcs/tools/aprofutil/aprofutil.csproj, mcs/tools/aprofutil/aprofutil.exe.sources, packaging/MacSDK/packaging/resources/whitelist.txt, scripts/.gitignore, scripts/Makefile.am
It needed a few tweaks to be usable when Mono is installed to the prefix.
=> [aprofutil] Install the tool correctly

mcs/class/referencesource/mscorlib/system/rttype.cs
https://github.com/mono/mono/issues/16010
The current behavior for GetConstructorCandidates when the name is null, "",
or "*" is to return the set of constructors for the type. For "", .NET Core and
.NET Framework return 0 elements.  This PR adds a check for "" to match that
behavior.
Backport of #16054.
/cc @marek-safar @steveisok
=> [2019-08] Fixed RuntimeType.GetConstructorCandidates("") to return 0 elements.

mono/metadata/mono-perfcounters.c
There are silent linker failures on the netcore win32 builds.  [Example](https://dev.azure.com/dnceng/public/_build/results?buildId=299471&view=logs&jobId=4e8f8277-b720-51b0-a345-2b36834044de&taskId=e9ed07b3-5ac5-5b9a-00a5-b77b9c91ad53&lineStart=2381&lineEnd=2381&colStart=11&colEnd=120).
Fix it by providing a definition of `mono_perfcounter_foreach` for the `DISABLE_PERFCOUNTERS` case.
Fixes netcore build on win32
=> [perfcounter] Define mono_perfcounter_foreach even if perfcounters are disabled.

configure.ac, mcs/packages/Makefile, mono/tests/remoting1.cs, packaging/MacSDK/msbuild.py, scripts/ci/run-test-mac-sdk.sh
Prompted by https://github.com/mono/msbuild/pull/123 :
```
This includes:
Update to upstream vs16.3 branch
SDK update to track dotnet release/3.0.100-preview8
Roslyn updated to 3.3.0-beta2-19381-14
```
=> [msbuild] Bump to track mono-2019-06 and update roslyn

mono/tests/remoting1.cs
We need to copy it to a local variable first.
This was exposed by a new Roslyn optimization for String.Concat (see https://github.com/dotnet/roslyn/issues/37830).
=> [tests] Fix accessing field of MarshalByRefObject in remoting1.cs

mono/metadata/assembly.c
As-is, error handling (among other things) will be totally broken.
@monojenkins backport 2019-08
=> [netcore] Don't return REFERENCE_MISSING in netcore_load_reference

configure.ac, mono/metadata/icall.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/utils/mono-state.c, runtime/bin/mono-hang-watchdog.in, tools/Makefile.am, tools/mono-hang-watchdog/Makefile.am, tools/mono-hang-watchdog/mono-hang-watchdog.c
Fixes https://github.com/mono/mono/issues/15646
macOS does not like signals being sent from the forked supervisor process, possibly towards anywhere but definitely when sent to the parent process. The following message is currently spewed after the supervisor process attempting to send a SIGSEGV to a hanged Mono process:
"The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec()."
We follow that direction and introduce a new binary that, when available, is used to abort the parent process for us.
=> [merp] Use a separate program as the hang supervisor.

mono/mini/intrinsics.c, netcore/CoreFX.issues.rsp, netcore/System.Private.CoreLib/src/System.Reflection.Emit/DynamicMethod.cs, netcore/build.sh
We don't support SRI.X86 yet but at least we should be able to eliminate the `IsSupported` branches, e.g.:
```csharp
static float TestSRI(float x)
{
if (Sse2.IsSupported)
{
// we don't support SIMD yet so I expect this 'if' and 'sqrt' to be eliminated
return MathF.Sqrt(x);
}
return x * x * x;
}
```
Current codegen (llvm):
```asm
_Program_TestSRI_single:
pushq	%rax
movss	%xmm0, 4(%rsp)
movq	1850(%rip), %rax
cmpq	$0, (%rax)
je	6 <_Program_TestSRI_single+0x1a>
callq	*1942(%rip)
callq	225 <plt_System_Runtime_Intrinsics_X86_Sse2_get_IsSupported>
testb	%al, %al
je	12 <_Program_TestSRI_single+0x2f>
movss	4(%rsp), %xmm0
sqrtss	%xmm0, %xmm0
popq	%rax
retq
movss	4(%rsp), %xmm1
movaps	%xmm1, %xmm0
mulss	%xmm0, %xmm0
mulss	%xmm1, %xmm0
popq	%rax
retq
```
After my change:
```asm …
```
=> [netcore] Make System.Runtime.Intrinsics.X86.*.IsSupported intrinsic

mcs/class/referencesource/mscorlib/system/rttype.cs
Fixes https://github.com/mono/mono/issues/16010
The current behavior for GetConstructorCandidates when the name is null, "",
or "*" is to return the set of constructors for the type. For "", .NET Core and
.NET Framework return 0 elements.  This PR adds a check for "" to match that
behavior.
Backport of #16054.
/cc @marek-safar @steveisok
=> [2019-06] Fixed RuntimeType.GetConstructorCandidates("") to return 0 elements.

eng/Version.Details.xml, eng/Versions.props
Manual update until the arcade fix rolls out that reenables the update bot for our repo.
=> Update dependencies from corefx

mono/dis/main.c, mono/metadata/appdomain.c, mono/metadata/assembly-internals.h, mono/metadata/assembly.c, mono/metadata/assembly.h, mono/metadata/attach.c, mono/metadata/coree.c, mono/metadata/domain.c, mono/metadata/icall.c, mono/metadata/mono-security.c, mono/metadata/w32socket.c, mono/mini/aot-runtime.c, mono/mini/driver.c, mono/mini/main-core.c, tools/pedump/pedump.c
Pushing this into the preparation function is the easiest way to assert all callers are either setting it or don't need to, as currently it was a mix of the two. Conveniently, this also gets rid of a bunch of ambient_alc calls.
I've opted to have non-netcore paths still calling `mono_domain_default_alc` even if it always returns NULL, so that if we do end up wanting to port back ALC behavior in some form the process will be expedited.
=> [netcore] Make mono_assembly_request_prepare take an ALC

mono/mini/interp/transform.c
We were not tracking max_stack_height for a few opcodes.
=> [interp] Fix overflow of execution stack

mono/mini/method-to-ir.c
It turns out my previous change broke inlining for netcore.
I am not sure how to properly fix the case (don't inline throw helpers)
cc @vargaz 
I suspect it might affect some StackTrace related tests, let's check CI.
=> [netcore] Fix inlining

mcs/class/System.Drawing.Design/System.Drawing.Design/ColorEditor.cs
Backport of #16141 
/cc @marek-safar, @filipnavara
=> [2019-08] [System.Drawing.Design] Allow `context` be a null in the `ColorEditor.EditValue`

mcs/class/System.Drawing/System.Drawing.csproj, mcs/class/System.Drawing/win32_net_4_x_System.Drawing.dll.exclude.sources, mcs/class/System.Drawing/win32_net_4_x_System.Drawing.dll.sources
The issue was made visible with .NET Core WinForms. Some controls draw text with DrawTextEx to intermediate Graphics based on Bitmap, that later it's moved back to main Graphics with DrawImage. This results in a lost of transparency component along the way, making antialiased glyph bitmaps draw and B/W. Corruption is visible with gray antialiasing, but is more severe in subpixel modes.
I verified that same happens with gdiplus on Windows, code from CoreFX works correctly.
=> [System.Drawing] Use CoreFX implementation of BufferedGraphics on Windows

mono/mini/debugger-agent.c
Cleanup MonoError on error paths.  Also change `return FALSE` to `return 0`.
Addresses Coverity CID 1452205
=> [debugger] Cleanup MonoError in isFixedSizeArray

mcs/class/System.Windows.Forms/System.Windows.Forms/XplatUIX11.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=14976
Credit goes to datnhanlz for noting that removing XChangeProperty(DisplayHandle, hwnd.whole_window, _XEMBED_INFO, _XEMBED_INFO, 32, PropertyMode.Replace, atoms, 2); would also fix the bug. 
Note that the type of Atom is actually unsigned long (see usr/include/X11/X.h), however the code used a C# int for the atoms. As such the code worked without a problem on 32 bit linux, but broke on 64 bit linux.
I switched to using IntPtr instead to make the code also work on 64-bit.
---
I compiled mono from 6.0.0.319.tar.xz release, and my test application didn't show an icon in the system tray. After applying these changes it shows in the system tray now.
https://bugzilla.xamarin.com/show_bug.cgi?id=8935 also mentions a similar issue with KeePass. …
=> [WinForms] Fix NotifyIcon not showing in systray on 64bit linux

configure.ac, mcs/packages/Makefile, packaging/MacSDK/msbuild.py, scripts/ci/run-test-mac-sdk.sh
Prompted by mono/msbuild#126:
This includes:
- merge mono-2019-06
- SDK update to track dotnet release/3.0.100-preview8
- Roslyn updated to 3.3.0-beta2-19381-14
=> [msbuild] Bump to track xplat-master and update Roslyn

configure.ac, mcs/packages/Makefile, packaging/MacSDK/msbuild.py, scripts/ci/run-test-mac-sdk.sh
- upstream doesn't have a vs16.4 branch yet, so let's track xplat-master for now
Prompted by mono/msbuild#126:
This includes:
- merge mono-2019-06
- SDK update to track dotnet release/3.0.100-preview8
- Roslyn updated to 3.3.0-beta2-19381-14
=> [2019-08][msbuild] Bump to track xplat-master and update Roslyn

sdks/builds/ios.mk
This will allow the interpreter to use System.Reflection.Emit.
Note: There is a small size increase (about 50kb) for an application
built in release mode with the LLVM backend (even if the interpreter
is now used).
=> [sdk] Enable the SRE runtime code inside iOS builds

mcs/class/System.Windows.Forms/System.Windows.Forms/XplatUIX11.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=14976
Credit goes to datnhanlz for noting that removing XChangeProperty(DisplayHandle, hwnd.whole_window, _XEMBED_INFO, _XEMBED_INFO, 32, PropertyMode.Replace, atoms, 2); would also fix the bug. 
Note that the type of Atom is actually unsigned long (see usr/include/X11/X.h), however the code used a C# int for the atoms. As such the code worked without a problem on 32 bit linux, but broke on 64 bit linux.
I switched to using IntPtr instead to make the code also work on 64-bit.
---
I compiled mono from 6.0.0.319.tar.xz release, and my test application didn't show an icon in the system tray. After applying these changes it shows in the system tray now.
https://bugzilla.xamarin.com/show_bug.cgi?id=8935 also mentions a similar issue with KeePass. …
=> [2019-08] [WinForms] Fix NotifyIcon not showing in systray on 64bit linux

sdks/builds/ios.mk
This will allow the interpreter to use System.Reflection.Emit.
Note: There is a small size increase (about 50kb) for an application
built in release mode with the LLVM backend (even if the interpreter
is now used).
Backport of https://github.com/mono/mono/pull/16151
=> [2019-06][sdk] Enable the SRE runtime code inside iOS builds

sdks/builds/ios.mk
This will allow the interpreter to use System.Reflection.Emit.
Note: There is a small size increase (about 50kb) for an application
built in release mode with the LLVM backend (even if the interpreter
is now used).
Backport of https://github.com/mono/mono/pull/16151
=> [2019-08][sdk] Enable the SRE runtime code inside iOS builds

mono/metadata/marshal.c, netcore/CoreFX.issues.rsp
Fixes https://github.com/mono/mono/issues/15092 (see my comment there)
Fixes https://github.com/mono/mono/issues/15091
Fixes https://github.com/mono/mono/issues/15090
btw, do I need to wrap minor changes with `#if ENABLE_NETCORE`? such as different strings in exceptions.
=> [netcore] decimal should have alignment=8

mono/mini/interp/interp.c
The locally unknown function, despite being small/fast,
forces saving values in stack and nonvolatile registers around calling it.
Both nonvolatile registers and stack are at a premium here, whereas usually stack is cheap.
The macro is just a read from offset 0 and checking for zero.
The entire runtime should be repaired in this way.
=> [interp] Replace `mono_error_ok` with `is_ok`.

netcore/System.Private.CoreLib/System.Private.CoreLib.csproj
- The eng/Versions.props was already imported by the arcade targets causing a double-import warning:
> warning MSB4011: "/Users/alexander/dev/mono/eng/Versions.props" cannot be imported again. It was already imported at "/Users/alexander/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19379.1/tools/DefaultVersions.props (17,3)". This is most likely a build authoring error. This subsequent import will be ignored.
- Remove BaseAddress and TRACE from the project file, this was done upstream at https://github.com/dotnet/coreclr/commit/bc430cdd2010bf7790854a60380d00c506c346a6
- Remove unecessary DebugSymbols/DebugType settings, we already set them in the global PropertyGroup
=> [netcore] Cleanup System.Private.CoreLib.csproj

mono/mini/driver.c, mono/mini/mini-runtime.c, mono/utils/mono-threads-coop.c, mono/utils/mono-threads-coop.h, mono/utils/mono-threads.c
On some benchmarks we saw `mono_threads_suspend_policy()` using a lot of CPU time.
Rather than doing an init-on-first-use, initialize the policy once upfront when the JIT it starting up and make the getter method static inline.
=> [runtime] Initialize thread suspend policy at startup, inline getter

mono/mini/interp/interp.c
This is not intuitive but I definitely saw it.
=> [interp] Outline `set_resume_state` to conserve stack in main interpreter loop.

mono/mini/interp/interp.c
Ultimately over 100 bytes are savable.
=> [interp] Outline `get_virtual_method_fast` to save 16 bytes of stack.

mono/dis/main.c, mono/eglib/glib.h, mono/eglib/gptrarray.c, mono/metadata/icall-table.c, mono/metadata/mono-ptr-array.h, mono/metadata/object.c, mono/metadata/sgen-bridge.c, mono/metadata/sre-save.c, mono/metadata/w32handle.c, mono/mini/aot-compiler.c, mono/mini/dwarfwriter.c, mono/profiler/mprof-report.c, mono/unit-tests/test-sgen-qsort.c, mono/utils/mono-os-wait-win32.c
Fixes https://github.com/mono/mono/issues/15994
Some is redundant for some qsort implementations.
=> Skip degenerate qsort: num < 2, size == 0, base == 0

mono/mini/interp/interp.c
*Theoretically* *could* help reduce frame size but it has not been seen to.
Frame has been gradually reduced over 100 bytes to 0xD8 bytes but this change is *not* clearly important for that, and *might* be contradicted by other changes that take address of vt_sp.
=> [interp] Remove address-taking of vt_sp.

mono/metadata/sre.c
The loop body uses coop handles, so wrap it in HANDLE_FUNCTION_ENTER/HANDLE_FUNCTION_RETURN
Addresses part of #16179
Backport of #16184.
=> [2019-08] [sre] Outline typebuilder_setup_fields loop body

mono/metadata/sre.c
The loop body uses coop handles, so wrap it in HANDLE_FUNCTION_ENTER/HANDLE_FUNCTION_RETURN
Addresses part of #16179
Backport of #16184.
=> [2019-06] [sre] Outline typebuilder_setup_fields loop body

mono/utils/hazard-pointer.c
(Later non-recursive Windows mutexes should be SRWLOCK and only statically initialized.)
=> Make small_id_mutex not recursive.

mono/mini/interp/interp.c
Extracted from https://github.com/mono/mono/pull/16171.
Ultimately over 100 bytes can be saved.
This change on its own probably saves 16 bytes, but over 100 bytes are savable.
Also fixes the error reuse problem nearby but not overall (https://github.com/mono/mono/pull/16190).
Outlining is partial to avoid "trouble" around:
vt_sp update
ip update
exception handling
But those are more elegantly shown in other PR.
=> [interp] Reduce frame size by partially outlining load remote field.

netcore/CoreFX.issues.rsp
See https://github.com/mono/mono/pull/16191/files#r313441821
(Here is the custom throw helper which is inlined: https://github.com/dotnet/corefx/blob/de38804d52f6b65f0f290b81383f01e6943a6d8f/src/System.Diagnostics.StackTrace/tests/StackTraceTests.cs#L326 but should not)
=> [netcore] Ignore failing StackTraces tests

mono/dis/main.c, mono/metadata/appdomain.c, mono/metadata/assembly-internals.h, mono/metadata/assembly.c, mono/metadata/attach.c, mono/metadata/coree.c, mono/metadata/domain.c, mono/metadata/mono-security.c, mono/metadata/w32socket.c, mono/mini/aot-runtime.c, mono/mini/driver.c, mono/mini/main-core.c, tools/pedump/pedump.c
This is #13857 with conflicts resolved. Also fixed up a couple of references to `mono_assembly_request_prepare` that were under ifdefs.
---
Addresses the family of issues similar to Coverity #1443346.
This came up as part of the Coverity review, and Coverity notices that this is
writting beyond the end of the structure. While this is correct, this requires
that the idiom be properly followed - that is, that the structure being passed
is of the given size.
Replaced instead with a method that eliminates the room for error with methods
that will initialize the whole structure, and the actual size computation is
done inside the method with the proper type sizes.
While I used methods, I feel that this should use macros.
Update: This both prevents Coverity from reporting a potential overflow, …
=> [metadata] Create strongly typed versions of mono_assembly_request_prepare

mcs/class/System/Mono.Btls/X509CertificateImplBtls.cs
The `X509CertificateImplBtls.PrivateKey` property setter was previously ignoring all values and always used `null`.  This should help with #16189.
=> X509CertificateImplBtls.PrivateKey should allow to actually set the key.

mono/mini/aot-compiler.c, mono/mini/driver.c, mono/mini/intrinsics.c, mono/mini/method-to-ir.c, mono/mini/mini.c, mono/mini/mini.h, mono/mini/type-checking.c
Immeasurably less efficient ('mov' vs. 'lea`) but looks maybe nice and more like other code.
Alternatively, the error doesn't really belong here, plumb the stack?
=> Remove ampersand from cfg->error per old agreement.

mono/metadata/cominterop.c
This typo was introduced with 29a95bafd87830c430432546af4bf7076ba5542f.
=> [cominterop] Fix copy-paste error in ComVisibleAttribute testing helper.

mono/mini/interp/interp.c
Presumably this is not a useful semantic change,
to skip those functions, given NULL.
(We will probably want to outline all of this also, later).
=> [interp] Short-circuit MINT_STELEM_REF on NULL.

configure.ac, mcs/class/corlib/System.Threading/Thread.cs, mono/metadata/object-internals.h, mono/metadata/threadpool.c, mono/metadata/threads-types.h, mono/metadata/threads.c, netcore/System.Private.CoreLib/src/System.Threading/Thread.cs
Maintain a counter and only set if the counter has changed.
This cannot be fully thread safe, so is not.
Any thread can set any other thread name at any time.
You could be atomic to do better, and loop to do even better,
but the thread name could still be changed again right after the loop exists.
The previous code was also not reliable in this way, since again the name
could be changed right away.
https://github.com/mono/mono/issues/16248
=> Reduce redundant setting of thread name.

mono/mini/mini-exceptions.c
=> [exceptions] Don't debug hang on ThreadAbortException

mono/metadata/cominterop.c
This typo was introduced with 29a95bafd87830c430432546af4bf7076ba5542f.
Backport of #16254.
/cc @marek-safar @nsivov
=> [2019-08] [cominterop] Fix copy-paste error in ComVisibleAttribute testing helper.

mono/dis/Makefile.am
Linker order matters when using .a files, so zlib.a MUST come after
sgen.a if sgen.a was compiled with support for compressed ppdb
=> Fix failing OSX Android lane

mono/dis/Makefile.am
Linker order matters when using .a files, so zlib.a MUST come after
sgen.a if sgen.a was compiled with support for compressed ppdb
Backport of #16274.
/cc @directhex
=> [2019-08] Fix failing OSX Android lane

scripts/ci/pipeline-netcore-runtime.yml
Currently "Run CoreFX tests" step is always green
=> [netcore] Mark "Run Tests" step as failed if there are failures

configure.ac, mcs/class/corlib/System.Threading/Thread.cs, mono/metadata/appdomain.c, mono/metadata/attach.c, mono/metadata/gc.c, mono/metadata/object-internals.h, mono/metadata/threadpool-io.c, mono/metadata/threadpool.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/mini/aot-compiler.c, mono/mini/debugger-agent.c, mono/mini/mini-posix.c, mono/profiler/aot.c, mono/profiler/log.c, netcore/System.Private.CoreLib/src/System.Threading/Thread.cs
Windows can still have its Unicode thread names, since we have UTF16 initially, just don't retain it.
This does penalize ves_icall_System_Threading_Thread_GetName_internal (non-netcore only),
which has to convert back to UTF16 each time.
But seems like a net win overall.
There is also a little prep work here for constant thread names and some temporary measures as multiple changes head toward the same code.
Rename `mono_thread_set_name_internal` to `mono_thread_set_name`.
Close possible race conditions.
Extracted from https://github.com/mono/mono/pull/15859.
=> Retain thread names as UTF8 instead of UTF16.

mono/mini/mini-arm64.h
Should resolve:
```
Xamarin.MTouch.Architectures_WatchOS(Dev,"arm64_32+llvm","ARM64_32"): Expected execution to succeed, but exit code was 1, and there were 3 error(s): build
error MT5210: Native linking failed, undefined symbol: _mono_fconv_u8_2. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
error MT5210: Native linking failed, undefined symbol: _mono_rconv_u8. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
error MT5202: Native linking failed. Please review the build log.
Xamarin.MTouch.Architectures_WatchOS(Dev,"armv7k+llvm,arm64_32+llvm","ARMv7k,ARM64_32"): Expected execution to succeed, but exit code was 1, and there were 3 error(s): build
error …
```
=> Add missing FCONV_TO_U8 on ILP32 (WatchOS 5)

mono/mini/mini-arm64.h
Should resolve:
```
Xamarin.MTouch.Architectures_WatchOS(Dev,"arm64_32+llvm","ARM64_32"): Expected execution to succeed, but exit code was 1, and there were 3 error(s): build
error MT5210: Native linking failed, undefined symbol: _mono_fconv_u8_2. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
error MT5210: Native linking failed, undefined symbol: _mono_rconv_u8. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
error MT5202: Native linking failed. Please review the build log.
Xamarin.MTouch.Architectures_WatchOS(Dev,"armv7k+llvm,arm64_32+llvm","ARMv7k,ARM64_32"): Expected execution to succeed, but exit code was 1, and there were 3 error(s): build
error …
```
=> [2019-08] Add missing FCONV_TO_U8 on ILP32 (WatchOS 5)

mono/metadata/handle.h, mono/metadata/marshal-ilgen.c
Removing calls to mono_string_new_checked.
Extracted from https://github.com/mono/mono/pull/15900.
=> [Coop] Convert emit_invoke_call.

mono/mini/mini-llvm.c
Contributes to https://github.com/mono/mono/issues/16251
So for
```csharp
public static byte GetElement(byte* array) 
{
return array[0];
}
```
the LLVM IR diff (before and after my change) is: https://www.diffchecker.com/sXN2IeJg
(note the argument type and removed bitcast)
=> Align C# pointers with LLVM pointers for primitive types

mcs/class/System/Test/System.Security.Cryptography.X509Certificates/X509Certificate2Test.cs
1002a4de2b0d added Authenticode cert support on non-WatchOS. The tests,
however, were not non-WatchOS-only. Fix this, so Watch doesn't try to
run Authenticode tests.
=> Exclude Authenticode tests on Watch

mcs/class/System/Test/System.Security.Cryptography.X509Certificates/X509Certificate2Test.cs
1002a4de2b0d added Authenticode cert support on non-WatchOS. The tests,
however, were not non-WatchOS-only. Fix this, so Watch doesn't try to
run Authenticode tests.
Backport of #16278.
/cc @directhex
=> [2019-08] Exclude Authenticode tests on Watch

mono/mini/interp/interp.c
Alternative to https://github.com/mono/mono/pull/16197.
If you are going outline, you sometimes might as well take it all with you
instead of bouncing back and forth for a partial inlining.
=> [interp] Outline enum_hasflag to save stack.

netcore/Makefile
The already existing `patch-local-dotnet` rule patches local .NET Core to be able to do experiments. This rule precompiles all BCL libs using LLVM.
This PR is a modified version of https://github.com/mono/mono/pull/15487
=> [netcore] Add patch-local-dotnet-aot-llvm rule

mono/mini/interp/interp.c
From https://github.com/mono/mono/pull/16190.
=> [interp] Fix more MonoError reuse (mono_object_new_checked).

mono/mini/interp/interp.c
This saves 16 stack bytes for clang, doesn't help gcc, it probably figured it out itself.
=> [interp] Localize c, i32, o to conserve stack as suggested.

mono/metadata/appdomain.c, mono/metadata/assembly-load-context.c, mono/metadata/assembly.c, mono/metadata/class-internals.h, mono/metadata/domain-internals.h, mono/metadata/object-internals.h, netcore/CoreFX.issues.rsp, netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs
Draft for now, as things are ~~probably~~definitely broken.
Addresses parts of #16246.
FIxes #15081.
Remaining todos:
=> [netcore] Enable netcore resolution logic for mono_assembly_byname_lookup

mono/mini/llvm-jit.cpp
Tested on some samples and `EB.setMCPU(sys::getHostCPUName());` (see https://llvm.org/doxygen/namespacellvm_1_1sys.html#a2e8cdc0e591685c9156af3d0d4fdae06) indeed allowed LLVM to use all of my CPU instructions (FMA, BMI2, AVX2)
e.g.
```csharp
public static float MultiplyAdd(float x, float y, float z) => x * y + z;
```
```
gram_MultiplyAdd:
vfmadd213ss	%xmm2, %xmm1, %xmm0
retq
```
uses modern FMA instruction (if fast math mode is enabled like this:
```c
TargetOptions targetOptions; 
targetOptions.AllowFPOpFusion = FPOpFusion::Fast; 
EB.setTargetOptions( targetOptions ); 
```
(will made a command line parameter to enable it in a separate PR)
=> Auto-detect current cpu in LLVM JIT

mono/mini/interp/transform.c
This opcode is pushing a function pointer from the delegate, so it needs to have stack reserved.
=> [interp] Make sure we allocate stack for MINT_LD_DELEGATE_INVOKE_IMPL

mono/metadata/object-offsets.h, mono/mini/decompose.c, mono/unit-tests/test-mono-callspec.c, mono/utils/mono-error-internals.h, mono/utils/mono-error.c, mono/utils/mono-error.h, tools/offsets-tool-py/offsets-tool.py
This is compatible enough?
We don't hand off MonoError externally, that anyone can/should use the size of?
As long as embedders give us a large enough one, and we retain the size for any that they embed in their own data structures?
=> Reduce size of internal MonoErrors by 3 pointers, while trying to be compatible with old size.

configure.ac, mcs/class/corlib/System.Threading/Thread.cs, mono/metadata/appdomain.c, mono/metadata/attach.c, mono/metadata/gc.c, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/metadata/object-internals.h, mono/metadata/threadpool-io.c, mono/metadata/threadpool.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/mini/aot-compiler.c, mono/mini/debugger-agent.c, mono/mini/mini-posix.c, mono/profiler/aot.c, mono/profiler/log.c, netcore/System.Private.CoreLib/src/System.Threading/Thread.cs
Several improvements to thread name including coop conversion.
- Convert setting thread name to be coop-compatible.
- For constant thread names, just retain the constant, not a copy.
This includes producing and using constant unicode thread names on Windows.
- Make setting a thread name often non-fatal, except where mandated by public API.
- From earlier PR: mono_free (mono-publib.c) would no longer be referenced and therefore
no longer exported. That broke profilers and maybe other externals.
Choices:
1 Use it instead of g_free randomly sometimes.
2 Call it randomly sometimes.
3 include it in external-only.c or object.c
4 Mark it external only (breaks profiler).
5 Use a .def file or Unix equivalent.
5 is best, 2 is done here, the advantages/disadvantages
among most choices are subtle. 3 …
=> thread name: coop, constant, ignore-error, etc.

mono/mini/interp/interp.c
=> [interp] Outline ves_array_element_address to save 16 bytes of stack on Linux/amd64/clang.

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c
Partial undo of f8fd60b5c088753a4a0ccb79483ebae73489e7a2.
Let the compiler do register allocation of locals. It does well enough with that.
Keep address-taken structs to a minimum. It does poorly with that.
=> [interp] Put finally data back in locals instead of frame to save 16 bytes of stack.

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c
=> [interp] Remove InterpFrame.locals, replace with reasonably efficient frame_locals macro.

mono/eglib/gfile-win32.c
The strcmp is wrong, and it doesn't test anything meaningful
anyway.
This flag is unused since #16156 was merged.
=> eglib: Remove broken executable test on Windows.

scripts/ci/provisioning/freebsd.sh, scripts/ci/run-jenkins.sh
We'll download it from GitHub instead of storing it in Jenkins admin config.
Trial run with FreeBSD for moving all the other provisioning scripts to the repo too.
/cc @rootwyrm
=> [ci] Add CI VM provisioning script for FreeBSD to the repo

mono/metadata/locales.c
Otherwise we see warnings like these:
```
ves_icall_System_Globalization_CultureInfo_internal_get_cultures_raw USED 680 handles
```
=> [coop] Add a handle frame in construct_culture

netcore/CoreFX.issues.rsp
Apparently these started passing at some point. Not sure exactly when, but probably with #16256.
=> [netcore] Update ALC test exclusions

mono/mini/interp/interp.c
For purposes of stack savings, only MINT_NEWOBJ_VT_FAST w/o the "ST"
needed to be outlined, and inlining also the ST form increased
its stack use, w/o savings elsewhere.
That is, the recursive cases should generally not be outlined.
We were outlining two. We still outline one.
This is partially undoing my recent change, where I outlined both of these, but only one was justified.
=> [interp] Reinline MINT_NEWOBJ_VTST_FAST.

mono/mini/interp/interp.c
Part of https://github.com/mono/mono/issues/16172 though not necessarily any gain from this change, at this time.
We might want to expose ifdef and inline mono_thread_internal_current also or instead.
=> [interp] Relieve register/stack pressure around mono_thread_internal_current.

mono/mini/interp/interp.c
Part of https://github.com/mono/mono/issues/16172 though not necessarily any gain from this change, at this time.
=> [interp] Reduce register/stack pressure esp. around vtable init.

mcs/class/System/Mono.Net.Security/MonoTlsStream.cs
Backport of #16233.
/cc @akoeplinger @baulig
=> [2019-08] Add missing `Dispose()` call on error in `MonoTlsStream.CreateStream()`.

mono/mini/interp/interp.c
Without being entirely scientific about it, this case seems
to be one that uses more than typical locals and therefore
be on a sort of critical path to reduce frame size.
I have a change that reduces frame to 0x78 bytes (albeit
not yet working) and to achieve that, in this case I refetched
the locals after function calls.
This achieves similar but perhaps more elegantly.
If we rest at larger frame size then this case might not be on the critical path.
https://github.com/mono/mono/issues/16172.
=> [interp] Outline box_nullable.

support/minizip/ioapi.c
it doesn't have f*64 funcs, it seems
=> fix minizip compile on Haiku

mono/profiler/Makefile.am, mono/profiler/aot.c, mono/profiler/coverage.c, mono/profiler/log.c, mono/profiler/vtune.c
This appears to not break the profilers:
```
directhex@breakfast:/tmp$ nm -g /tmp/ponyponyponypony/lib/libmono-profiler-log.so | grep close_socket_fd
directhex@breakfast:/tmp$
directhex@breakfast:/tmp$ /tmp/ponyponyponypony/bin/mono --profile=log:report bottle.exe
99 bottles of beer on the wall, 99 bottles of beer.
Take one down and pass it around, 99 bottles of beer on the wall.
[..]
No more bottles of beer on the wall, no more bottles of beer.
Go to the store and buy some more, 99 bottles of beer on the wall.
Mono log profiler data
Profiler version: 3.0
Data version: 17
Arguments: log:report
Architecture: x86-64
Operating system: linux
Mean timer overhead: 86 nanoseconds
Program startup: Mon Aug 19 14:18:30 2019
Program ID: 17715
Server listening on: 41539
JIT summary
Compiled methods: …
```
=> Pass -fvisibility=hidden to profiler modules.

scripts/ci/provisioning/freebsd.sh
Jenkins builds are failing due to missing gettext; also realized that graphics unit tests will fail without some additional packages that will not be pulled in automatically.
Added:
`gettext-runtime gettext-tools cairo libdrm mesa-dri mesa-libs`
=> Fix Jenkins build failure due to missing dependencies

mcs/class/System/Mono.Net.Security/MonoTlsStream.cs
Backport of #16233.
/cc @akoeplinger @baulig
=> [2019-06] Add missing `Dispose()` call on error in `MonoTlsStream.CreateStream()`.

mono/metadata/w32error.h, mono/metadata/w32socket-unix.c
These aren't a perfect match, but better than falling into the `default` case
where Mono asserts and crashes.
---
Also add `WSA_INVALID_PARAMETER` and `WSA_INVALID_HANDLE` defines
=> [w32socket] Translate some errno codes to WSA_ errors imprecisely.

mono/profiler/aot.c, mono/profiler/helper.c, mono/profiler/helper.h, mono/profiler/log.c
Unfortunately https://github.com/mono/mono/pull/16335 didn't fix the new symbols showing up in the log profiler module.
The reason is that we actually pass `--disable-visibility-hidden` for iOS builds in https://github.com/mono/mono/blob/0b6d95e8ce7c882e2db9e89fa0dec850c687f65e/sdks/builds/ios.mk#L98
Rename the helper functions instead to have a common prefix so they can be ignored in xamarin-macios tests.
=> [profiler] Rename helper functions to have common prefix

mono/profiler/aot.c, mono/profiler/helper.c, mono/profiler/helper.h, mono/profiler/log.c
Unfortunately https://github.com/mono/mono/pull/16335 didn't fix the new symbols showing up in the log profiler module.
The reason is that we actually pass `--disable-visibility-hidden` for iOS builds in https://github.com/mono/mono/blob/0b6d95e8ce7c882e2db9e89fa0dec850c687f65e/sdks/builds/ios.mk#L98
Rename the helper functions instead to have a common prefix so they can be ignored in xamarin-macios tests.
Backport of #16367.
=> [2019-08] [profiler] Rename helper functions to have common prefix

sdks/wasm/library_mono.js
- Tests if we are running in ENVIRONMENT_IS_WORKER
- run message pump if we are.
- This also fixes GC not running.
close https://github.com/mono/mono/issues/16319
=> [wasm] Make sure message pump is working when executing via webworker.

netcore/Makefile
For some reason it defaults to `Debug' otherwise.
=> [netcore] use Release configuration for default System.Private.CoreLib build

mono/mini/aot-runtime.c
Fixes https://github.com/mono/mono/issues/16380.
=> [aot] Simplify a check to avoid calling into the assembly loading code while loading the aot image for corlib.

mono/mini/intrinsics.c
```csharp
static IntPtr test_Zero() => IntPtr.Zero;
```
Before:
```asm
_P_test_Zero:
1640:	push	rax
1641:	cmp	byte ptr [rip + 3265], 0
1648:	je	12 <_P_test_Zero+0x16>
164a:	mov	rax, qword ptr [rip + 3239]
1651:	mov	rax, qword ptr [rax]
1654:	pop	rcx
1655:	ret
1656:	mov	edi, 1
165b:	call	-1264 <_mono_aot_HelloWorldinit_method>
1660:	jmp	-24 <_P_test_Zero+0xa>
```
After:
```asm
_P_test_Zero:
1670:	xor	eax, eax
1672:	ret
```
All other IntPtr members generate perfect codegen if inlined (in CoreCLR all members are marked with `[Intrinsic]`) so I don't know what to do - should I intrinsify them anyway or can just make the inliner always inline them? (emulate AggressiveInlining attribute)
=> Make IntPtr.Zero intrinsic

mono/mini/interp/interp.c
This should conserve stack. I didn't verify it.
child_frame being address-taken, compiler would struggle to remove it.
So we have the same value in two places.
https://github.com/mono/mono/issues/16172
=> [interp] Replace endsp with child_frame.retval.

mcs/class/corlib/System/AppDomainSetup.cs, mcs/class/corlib/Test/System/AppDomainSetupTest.cs
WiX 3 installer toolkit uses file:/// prefix when setting ApplicationBase for newly created domain.
Currently this leads to invalid path exception:
file:///C:\... -> /C:\... -> full path expansion with current workdir on different drive -> Y:\C:\...
Later it fails check for multiple ':' -> NotSupportedException ("The given path's format is not supported.").
This patch uses logic already present in AppDomain::Load().
=> [corlib] Improve file:// url handling in AppDomainSetup.

mono/mini/intrinsics.c
Currently, if the process is 32-bit, roslyn tries to determine how much
memory is available.  To do that, it tries to pinvoke into GlobalMemoryStatusEx,
which is not supported on mono.
Without it, the compiler server bombs on https://github.com/dotnet/roslyn/blob/0e63260c5afb3fb5b74c357dd250e500172bcd63/src/Compilers/Server/VBCSCompiler/NamedPipeClientConnection.cs#L55-L59
=> Add Compiler Server Workaround for 32-bit Linux

mono/utils/mono-dl-posix.c
The intention of calling `g_file_test (file, G_FILE_TEST_EXISTS)` where file is
the name of a shared library we want to open is to speed up probing for
non-existent libraries.
See https://github.com/mono/mono/pull/12074
The problem is that if file is just a simple "libdl.so" then `dlopen (file)`
doesn't just look for it in the current working directory, it will probe some
other paths too.  (For example on desktop linux you'd also look in all the
directories in LD_LIBRARY_PATH).  So the g_file_test() call is not a robust way
to avoid calling dlopen if the filename is relative.
But it actually broke more things: https://github.com/xamarin/xamarin-android/issues/3388
When probing for "libdl.so" on Android mono_lookup_pinvoke_call will first try
prepending some paths that it knows about and …
=> [2019-06] [android] mono_dl_open_file: use g_file_test only on absolute paths

mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs
Using the CoreCLR version of this line fixed the problem and my investigations
also revealed why.
The `SafePipeHandle` contains a reference to both the Socket as well as the
`SafeSocketHandle`, taking ownership of them.  If there are no additional
references to either of them, so that both are collected in the same GC pass,
their finalizer may be invoked in any order.
If the Socket gets finalized first, it's `SafeSocketHandle` will have a `_mstate`
of 8 (two references) at the beginning of `DangerousReleaseInternal()` - which
will set it to 6 (one reference plus disposed flag).
Then when the `SafePipeHandle` gets collected, it will call `DangerousRelease ()`
on it's `SafeSocketHandle`.  As mentioned above, it's `_mstate` will be 6.
Now we own the handle, so we'll decrease it's reference …
=> Fix issue in `SafeHandle.DangerousReleaseInternal()` that caused #16034.

mono/metadata/threads.c
netbsd and linux both require that if SCHED_OTHER is used, a fixed value is used for sched_param ([0 for linux](http://man7.org/linux/man-pages/man7/sched.7.html), -1 for netbsd)
the netbsd case can also be detected by the [POSIX-defined failure](https://pubs.opengroup.org/onlinepubs/007908799/xsh/sched_get_priority_min.html) return value for sched_get_priority_min, a return value of -1.
=> If either sched_get_priority_{min,max} failed, don't try to set a priority

mono/mini/mini-llvm.c, mono/mini/mini.c
1) ~~`MONO_VERBOSE_METHOD=*` will dump everything~~
2) Wrap `mono_llvm_dump_value` and `mono_disassemble_code` with some separators to be able to parse these pieces in external tools (e.g. diff tools)
Example:
```csharp
static int Test(int a, int b) => a + b;
```
`MONO_VERBOSE_METHOD=Test`
```
...
*** LLVM IR for P:Test ***
; Function Attrs: noinline uwtable
define monocc i32 @"P:Test (int,int)"(i32 %arg_a, i32 %arg_b) #0 {
BB0:
br label %BB3
BB3:                                              ; preds = %BB0
br label %BB2
BB2:                                              ; preds = %BB3
%t19 = add i32 %arg_a, %arg_b
br label %BB4
BB4:                                              ; preds = %BB2
br label %BB1
BB1:                                              ; preds = %BB4
ret i32 %t19
}
*** …
```
=> Improve MONO_VERBOSE_METHOD

mono/mini/intrinsics.c
Currently, if the process is 32-bit, roslyn tries to determine how much
memory is available. To do that, it tries to pinvoke into GlobalMemoryStatusEx,
which is not supported on mono.
Without it, the compiler server bombs on https://github.com/dotnet/roslyn/blob/0e63260c5afb3fb5b74c357dd250e500172bcd63/src/Compilers/Server/VBCSCompiler/NamedPipeClientConnection.cs#L55-L5
Backport of https://github.com/mono/mono/pull/16405
=> [2019-06] Add Compiler Server Workaround for 32-bit Linux

mono/mini/intrinsics.c
Currently, if the process is 32-bit, roslyn tries to determine how much
memory is available. To do that, it tries to pinvoke into GlobalMemoryStatusEx,
which is not supported on mono.
Without it, the compiler server bombs on https://github.com/dotnet/roslyn/blob/0e63260c5afb3fb5b74c357dd250e500172bcd63/src/Compilers/Server/VBCSCompiler/NamedPipeClientConnection.cs#L55-L59
Backport of https://github.com/mono/mono/pull/16405
=> [2019-08] Add Compiler Server Workaround for 32-bit Linux

mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs
Using the CoreCLR version of this line fixed the problem and my investigations
also revealed why.
The `SafePipeHandle` contains a reference to both the Socket as well as the
`SafeSocketHandle`, taking ownership of them.  If there are no additional
references to either of them, so that both are collected in the same GC pass,
their finalizer may be invoked in any order.
If the Socket gets finalized first, it's `SafeSocketHandle` will have a `_mstate`
of 8 (two references) at the beginning of `DangerousReleaseInternal()` - which
will set it to 6 (one reference plus disposed flag).
Then when the `SafePipeHandle` gets collected, it will call `DangerousRelease ()`
on it's `SafeSocketHandle`.  As mentioned above, it's `_mstate` will be 6.
Now we own the handle, so we'll decrease it's reference …
=> [2019-08] Fix issue in `SafeHandle.DangerousReleaseInternal()` that caused #16034.

mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs
Using the CoreCLR version of this line fixed the problem and my investigations
also revealed why.
The `SafePipeHandle` contains a reference to both the Socket as well as the
`SafeSocketHandle`, taking ownership of them.  If there are no additional
references to either of them, so that both are collected in the same GC pass,
their finalizer may be invoked in any order.
If the Socket gets finalized first, it's `SafeSocketHandle` will have a `_mstate`
of 8 (two references) at the beginning of `DangerousReleaseInternal()` - which
will set it to 6 (one reference plus disposed flag).
Then when the `SafePipeHandle` gets collected, it will call `DangerousRelease ()`
on it's `SafeSocketHandle`.  As mentioned above, it's `_mstate` will be 6.
Now we own the handle, so we'll decrease it's reference …
=> [2019-06] Fix issue in `SafeHandle.DangerousReleaseInternal()` that caused #16034.

mono/metadata/appdomain.c, mono/metadata/assembly.c
Should probably rebase this instead of squashing - the changes are largely isolated but I didn't want to make two pull requests.
The latter commit fixes the main remaining issue with the System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext test. Sadly, the test still can't be re-enabled because it fails the very first assert, which checks that a target assembly has never been loaded before, but should be otherwise functional.
Hopefully the order shuffling on the search hooks will not cause issues with legacy Mono, but we'll see.
=> [netcore] Loader cleanup and LoadInDefaultContext test fixes

mono/metadata/icall.c, mono/metadata/image.c, mono/metadata/metadata-internals.h, netcore/CoreFX.issues.rsp
Fixes #15192 
The core of the issue here is that [this code](https://github.com/mono/mono/blob/7c3dfbcbdf46d057ae4f145a8ddfc8e193d90ef5/mono/metadata/image.c#L1833) sets the name field on assemblies to the pointer when loaded from a stream, and get_location simply returns that field. The [relevant docs](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.location?view=netframework-4.8#System_Reflection_Assembly_Location) seem unambiguous that an empty string should be returned instead, even in framework.
If this ends up failing some legacy mono tests, I can either change the test or make this behavior netcore-only.
=> Return an empty string for assemblies loaded from stream

configure.ac, packaging/MacSDK/msbuild.py
.. to get changes from https://github.com/mono/msbuild/pull/130
which tracks dotnet `release/3.0.100-preview9`.
Also, bump Roslyn to 3.3.1-beta3-19421-04 .
=> [msbuild] Bump to track mono-2019-06

scripts/csc.in, scripts/csi.in, scripts/vbc.in
Should help with random CSC crashes on ARM (we've been using it in the Mono build for a while).
=> Pass --clr-memory-model in csc/vbc wrapper script

packaging/MacSDK/msbuild.py
Turns shared compiler back on now that https://github.com/mono/mono/issues/16034 is fixed
=> [2019-06][msbuild] bump msbuild to pick up latest p9 versions and enable shared compilation again

mono/mini/interp/interp.c
Without being entirely scientific about it, this case seems
to be one that uses more than typical locals and therefore
be on a sort of critical path to reduce frame size.
I have a change that reduces frame to 0x78 bytes (albeit
not yet working) and to achieve that, in this case I refetched
the locals after function calls.
This achieves similar but perhaps more elegantly.
If we rest at larger frame size then this case might not be on the critical path.
https://github.com/mono/mono/issues/16172.
=> [interp] Outline STRMFLD_VT.

mono/mini/mini-runtime.h
To fix Linux x64 - prefix sanity checks.
=> Add MONO_LLVM_INTERNAL to mono_jit_compile_method.

mono/metadata/assembly.c, netcore/CoreFX.issues.rsp
=> Detect additional invalid assembly names when parsing

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
Remove support for "big assemblies" for AOT on Android running on ARM 32bit. This will remove relocations in `.text` which are not allowed in the upcoming Android Q release anymore.
_If_ a customer should run into this problem, the suggested workarounds are:
* Switch to ARM64, or
* Do not use AOT compilation.
Fixes https://github.com/mono/mono/issues/16369
=> [android] remove text relocations in AOT/arm32

mono/mini/interp/interp.c
No functional change, except for debugging, look up a frame
for the prior value.
=> [interp] Cleanup stackval_to_data and stackval_to_data_addr.

mono/metadata/locales.c
Otherwise we see warnings like these:
```
ves_icall_System_Globalization_CultureInfo_internal_get_cultures_raw USED 680 handles
```
Backport of #16299.
/cc @akoeplinger @lambdageek
=> [2019-08] [coop] Add a handle frame in construct_culture

mono/mini/mini-llvm.c
```csharp
static int Test(int a, int b, int c) => a * b + a * c;
```
`MONO_VERBOSE_METHOD="Test"` now prints both unoptimized and optimized IR:
```llvm
*** Unoptimized LLVM IR for P:Test ***
; Function Attrs: noinline uwtable
define monocc i32 @"P:Test (int,int,int)"(i32 %arg_a, i32 %arg_b, i32 %arg_c) #0 {
BB0:
br label %BB3
BB3:                                              ; preds = %BB0
br label %BB2
BB2:                                              ; preds = %BB3
%t22 = mul i32 %arg_a, %arg_b
%t25 = mul i32 %arg_a, %arg_c
%t27 = add i32 %t22, %t25
br label %BB1
BB1:                                              ; preds = %BB2
ret i32 %t27
}
***
*** Optimized LLVM IR for P:Test ***
; Function Attrs: noinline uwtable
define monocc i32 @"P:Test …
```
=> LLVM JIT: dump IR after optimizations 

mono/utils/mono-mmap.c
As of XCode 11 beta6 the MacOSX SDK defines the MAP_32BIT symbol:
```diff
--- /Applications/Xcode11-beta5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/sys/mman.h    2019-07-25 17:43:49.000000000 -0400
+++ /Applications/Xcode11-beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/sys/mman.h    2019-08-06 21:03:07.000000000 -0400
@@ -1,5 +1,5 @@
/*
- * Copyright (c) 2000-2002 Apple Computer, Inc. All rights reserved.
+ * Copyright (c) 2000-2019 Apple Computer, Inc. All rights reserved.
*
* @APPLE_OSREFERENCE_LICENSE_HEADER_START@
*
@@ -145,6 +145,10 @@
#define MAP_RESILIENT_CODESIGN  0x2000 /* no code-signing failures */
#define MAP_RESILIENT_MEDIA     0x4000 /* no backing-store failures */
+#if …
```
=> [utils] Don't use MAP_32BIT on Apple platforms, fixes crash with XCode 11 beta6

scripts/csc.in, scripts/csi.in, scripts/vbc.in
Should help with random CSC crashes on ARM (we've been using it in the Mono build for a while).
Backport of #16439.
=> [2019-08] Pass --clr-memory-model in csc/vbc wrapper script

mono/mini/method-to-ir.c, mono/mini/tramp-amd64.c, mono/mini/tramp-x86.c
https://github.com/mono/mono/pull/16408 temporary fixed a tramp issue on x86 (also exist on amd64). This commit fixes the underlying issue and re-enable the use of noreturn outside of netcore.
The problem hit by the use of OP_NOT_REACHED on x86/amd64 is due to a specific case when the address to patch happens to fall at the start of a different managed method. Since the use of OP_NOT_REACHED can end a method with the call instruction on x86/amd64 in combination with how patch location (using the return address from stack) is resolved, the implementation in
mono_arch_patch_callsite didn't take this case into account, reading incorrect patch data, triggering assert on x86. So, based on timing we could end up with the following code:
025715B3 call 02570D98
025715B8 push ebp
since the patch …
=> Fix special case tramp assert in x86/amd64 when using OP_NOT_REACHED.

mono/utils/mono-mmap.c
As of XCode 11 beta6 the MacOSX SDK defines the MAP_32BIT symbol.
This causes the `mono_valloc()` function to try to use the `MAP_32BIT` flag for `mmap()`.
However as mentioned in the comment for the symbol in mman.h it seems to require a special entitlement which isn't available/documented anywhere yet.
This in turn causes the mmap call to fail presumably because we're missing that entitlement.
Instead we now skip setting this flag on Apple platforms to make `mmap()` behave like it did before.
Backport of https://github.com/mono/mono/pull/16441
=> [2019-08] [utils] Don't use MAP_32BIT on Apple platforms, fixes crash with XCode 11 beta6

mono/utils/mono-mmap.c
As of XCode 11 beta6 the MacOSX SDK defines the MAP_32BIT symbol.
This causes the `mono_valloc()` function to try to use the `MAP_32BIT` flag for `mmap()`.
However as mentioned in the comment for the symbol in mman.h it seems to require a special entitlement which isn't available/documented anywhere yet.
This in turn causes the mmap call to fail presumably because we're missing that entitlement.
Instead we now skip setting this flag on Apple platforms to make `mmap()` behave like it did before.
Backport of https://github.com/mono/mono/pull/16441
Backport of #16480.
=> [2019-06] [utils] Don't use MAP_32BIT on Apple platforms, fixes crash with XCode 11 beta6

mono/metadata/boehm-gc.c, mono/metadata/external-only.c, mono/metadata/null-gc.c, mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/object.h, mono/metadata/sgen-mono.c, mono/mini/ee.h, mono/mini/interp-stubs.c, mono/mini/interp/interp.c, mono/sgen/sgen-cardtable.c, mono/sgen/sgen-gc.c, mono/sgen/sgen-gc.h
But do not change the signatures of external functions.
=> Add missing const, particularly on functions "like" memcpy.

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
Remove support for "big assemblies" for AOT on Android running on ARM 32bit. This will remove relocations in `.text` which are not allowed in the upcoming Android Q release anymore.
_If_ a customer should run into this problem, the suggested workarounds are:
* Switch to ARM64, or
* Do not use AOT compilation.
Fixes https://github.com/mono/mono/issues/16369
Backport of #16432.
/cc @lewurm
=> [2019-08] [android] remove text relocations in AOT/arm32

mono/metadata/w32error.h, mono/metadata/w32socket-unix.c
These aren't a perfect match, but better than falling into the `default` case
where Mono asserts and crashes.
---
Also add `WSA_INVALID_PARAMETER` and `WSA_INVALID_HANDLE` defines
Backport of #16331.
=> [2019-08] [w32socket] Translate some errno codes to WSA_ errors imprecisely.

mono/metadata/w32error.h, mono/metadata/w32socket-unix.c
These aren't a perfect match, but better than falling into the `default` case
where Mono asserts and crashes.
---
Also add `WSA_INVALID_PARAMETER` and `WSA_INVALID_HANDLE` defines
Backport of #16331.
=> [2019-06] [w32socket] Translate some errno codes to WSA_ errors imprecisely.

mono/dis/dump.c
Alternatively use 'u' for one of them.
=> Combine adjacent identical cases.

mono/metadata/sgen-mono.c, mono/metadata/sgen-stw.c, mono/sgen/sgen-gc.c
Several SGEN_LOG entries logged usec based on result returend from TV_ELAPSED. On SGEN's implementation of TV_ELAPSED, the result is not scaled to usec but returned as 100ns ticks. This was not handled correctly by SGEN_LOG, but other measures, like profile counters and SGEN binary protocol handles it correctly.
Fix will adjust the SGEN_LOG calls currently presenting usec to correctly scale the result. Fix also adds additional logging measuring total amount of time spend scanning thread data as well as stopping/restarting world.
=> Fix multiple SGEN_LOG to correctly scale elapsed time in usec.

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c
While working on stack reduction, I believe I found that
the compiler could not tell how THROW_EX and/or NULL_CHECK terminate.
That is, essentially, the success paths preserve volatile registers.
They do not have to be spilled/filled.
This tweak should make it clearer to the compiler, optimized common paths, and not slow down uncommon paths.
This also cleans it up a little and reduces macro expansion, and then possibly should allow for reinlining what is now used only once.
Also add some const so it can be casted away less.
Believed to save 32 bytes of stack with Linux/amd64/clang, nothing for gcc.
And a nice cleanup.
=> [interp] Error handling refactor (optimize non-exception path) (helps clang save stack).

mono/mini/interp/interp.c
Seems to have been added by mistake in https://github.com/mono/mono/pull/16317, which was meant just to remove the locals variable from InterpFrame.
=> [interp] Remove unnecessary recomputation

netcore/System.Private.CoreLib/src/System/TypedReference.cs
This brings us in line with CoreCLR behavior.
=> [netcore] Change exception thrown for SetTypedReference

eng/Versions.props, netcore/System.Private.CoreLib/System.Private.CoreLib.csproj
… to mimic CoreCLR and make BenchmarkDotNet happy.
BenchmarkDotNet recently updated the algorithms for .NET version detection (https://github.com/dotnet/BenchmarkDotNet/pull/1230) which made it incompatible with the version presented by Mono.
This updates the value of [ProductName](https://github.com/dotnet/coreclr/blob/1f428dbc5554191dadd27511cd5cd181e4a60efb/Directory.Build.targets#L7) and [Version](https://github.com/dotnet/coreclr/blob/c9007e73286456434ba12744e778e87a89fc1d90/eng/Versions.props#L5) to match what CoreCLR is currently reporting and makes the [BDN detection code](https://github.com/dotnet/BenchmarkDotNet/blob/b6d0e0f1d80ed60aa157149a0dfb704a2da4ca41/src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs#L73-L81) happy.
=> [netcore] Update version information in System.Private.CoreLib

mono/mini/mini-arm.c, mono/mini/mini-mips.c, mono/mini/mini-ppc.c
- It _presumably_ means nothing on 32bit ARM and 32bit MIPS (was there mono/mips64?).
- Leaving only PowerPC32 and PowerPC64 (in this vicinity).
- It presumably means nothing on PowerPC32.
- Leaving PowerPC64 as the only user in this vicinity -- is it needed?
- Notice this is varyingly absent on x86, arm64, amd64, s390x. (ok, there is no x86, S390x AOT).
Subject of another PR maybe.
Perhaps this was to enable the debugger to be 32bit against a 64bit target
on a biarch system, so it could do a cross-process manipulation of these pages, i.e. with a truncated address?
That makes some sense on Windows at least.
32bit debugger cannot debug 64bit target as of Vista, but that is using the Win32
"hard" debugger API. Mono could do otherwise.
There remains amd64 mono-codeman.c define ARCH_MAP_FLAGS …
=> Cleanup MONO_MMAP_32BIT.

mono/mini/interp/interp.c
Paired with https://github.com/mono/mono/pull/16456, saves 16 bytes on Linux/amd64/clang.
No change with gcc.
=> [interp] Asserts pessimize clang. Removing saves 16 bytes on Linux/amd64/clang.

mono/mini/interp/interp.c
Must be paired with additional savings, to get 16 bytes saved on Linux/amd64/clang.
Such as https://github.com/mono/mono/pull/16530.
No change with gcc.
=> [interp] Outline box.

mono/mini/Makefile.am.in, mono/mini/jit-icalls.c, mono/mini/jit-icalls.h, mono/mini/mini-amd64.h, mono/mini/mini-arm.c, mono/mini/mini-arm.h, mono/mini/mini-arm64.h, scripts/ci/run-test-testing_aot_full.sh
[arm64] use opcode emulation for fconv/rconv
LLVM eagerly optimizes constants such as NaN in a way that does not align with .NET behaviour. In the future we can change it so that we only do opcode emulation when LLVM is used.
Fixes https://github.com/mono/mono/issues/16411
---------------------------------------------------------------
[ci] add make -C mono/mini llvmaotcheck to FullAOT LLVM lanes
---------------------------------------------------------------
[arm] use opcode emulation for fconv/rconv  (needed to fix `llvmaotcheck`)
---------------------------------------------------------------
[arm] account only 4 bytes on stack for single precision arguments  (needed to fix `llvmaotcheck`)
Fixes `test_0_arm64_small_stack_args` in gshared.cs when
* `test_0_arm64_small_stack_args` is …
=> [2019-08] [arm/arm64] fix fconv/rconv issues with LLVM

mcs/class/corlib/Test/System/TimeZoneInfoTest.cs, mcs/class/corlib/Test/System/TimeZoneTest.cs
This fixes #16415 
All timezones indicated as deprecated have been updated to the current IANA specification.
=> Remove/Update deprecated TZs for #16415

mono/mini/interp/interp.c
[interp] Fix remaining MonoError reuse.
This finishes off:
https://github.com/mono/mono/commit/38aebeae38704df53ef8f2991ff63e293a3ac4de
which is *ok*, but leaves alone the other approach, not my preference:
https://github.com/mono/mono/commit/4d9e6ae20e536394c9ff65c61238045db294c08e
https://github.com/mono/mono/commit/b654aa1ca858666539a677e96d00f594fd81c630
https://github.com/mono/mono/commit/fd4956fbf277ec56a13137e01b48efb98a5556f5
Several other options are possible, if insisted upon.
We could use reuse `MonoError` more, or less, and/or wrap every `mono_foo` + ignore error with `mono_interp_foo`.
Ignoring the matter of quantity of `MonoError`, the real-ish problem I was originally fixing before we went and argued how many `MonoError`s to instantiate is that originating an error, then …
=> [interp] Fix remaining MonoError reuse.

mono/metadata/icall-def-netcore.h, mono/metadata/monitor.c, mono/metadata/monitor.h, netcore/System.Private.CoreLib/src/System.Threading/Monitor.cs
Contributes to https://github.com/mono/mono/issues/14828.
The PR just wires up the Monitor.LockContentionCount API to an icall. The actual implementation is not done yet.
I wanted to reuse the existing `thread_contentions` performance counter but all performance counters unconditionally disabled on netcore builds. Also, the counter is 32-bit only while the managed API returns 64-bit values.
The CoreCLR implementation uses a neat trick to reduce the cost of counting. It stores a per-thread contention counter (eg. in `MonoInternalThread` field) and a global overflow counter. Up to 2^32 contentions could be recorded in the per-thread field with simple volatile incrementation. Once an overflow happens a slow path is taken that updates a global overflow counter. The `LockContentionCount` API …
=> [netcore] Add Monitor.LockContentionCount icall

mcs/class/System/System.IO.Compression/DeflateStream.cs
Resolves https://github.com/mono/mono/issues/16122
Since we put in the corefx version of GZipStream, it is expected that
our version of DeflateStream actually implements Write+ReadAsyncMemory.
This change does that by just calling the plain WriteAsync & ReadAsync
methods until we decide (or not) to pull in the corefx DeflateStream.
Backport of #16523.
/cc @steveisok
=> [2019-02] Implement Read and WriteAsyncMemory in Mono DeflateStream

mcs/class/System/System.IO.Compression/DeflateStream.cs
Resolves https://github.com/mono/mono/issues/16122
Since we put in the corefx version of GZipStream, it is expected that
our version of DeflateStream actually implements Write+ReadAsyncMemory.
This change does that by just calling the plain WriteAsync & ReadAsync
methods until we decide (or not) to pull in the corefx DeflateStream.
Backport of #16523.
/cc @steveisok
=> [2019-06] Implement Read and WriteAsyncMemory in Mono DeflateStream

mcs/class/System/System.IO.Compression/DeflateStream.cs
Resolves https://github.com/mono/mono/issues/16122
Since we put in the corefx version of GZipStream, it is expected that
our version of DeflateStream actually implements Write+ReadAsyncMemory.
This change does that by just calling the plain WriteAsync & ReadAsync
methods until we decide (or not) to pull in the corefx DeflateStream.
Backport of #16523.
/cc @steveisok
=> [2019-08] Implement Read and WriteAsyncMemory in Mono DeflateStream

mono/metadata/assembly-load-context.c, mono/metadata/icall-def-netcore.h, netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs
Some quick tests in a sample program indicate it throws the right errors and the call to mono_dl_open succeeds when given a valid dylib. Hopefully this works fine on platforms other than OSX.
=> [netcore] Implement AssemblyLoadContext.LoadUnmanagedDllFromPath

packaging/MacSDK/profile.py
See https://github.com/mono/bockbuild/pull/116
=> Build pkg-config as 64bit only, libtiff as universal and remove gtk-quartz-engine.py

mono/mini/exceptions-amd64.c, mono/mini/exceptions-x86.c, mono/mini/mini-amd64.c, mono/mini/mini-x86.c, mono/mini/tramp-amd64-gsharedvt.c, mono/mini/tramp-amd64.c, mono/mini/tramp-x86-gsharedvt.c, mono/mini/tramp-x86.c
- named `int` everywhere
- `assert` everywhere
- assert `<=` everywhere instead of `<`
- `const` almost everywhere
Names not consistent, following existing code (`size`, `buf_len`, `kMaxCode`.)
Only touching x86/amd64, granted.
Could be better -- make them two pass and avoid the presizing.
=> Cleanup trampoline size checks.
