mono/mono

configure.ac, mono/profiler/Makefile.am, mono/profiler/mono-profiler-vtune.c
Add support for tracking emitted code when profiling with vtune.
=> Vtune integration

mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs
Check if handle is closed before release for Dispose(true).
=> Small fix for SafeHandle Disposing

mcs/class/Managed.Windows.Forms/System.Windows.Forms/TextBoxTextRenderer.cs
See https://bugzilla.xamarin.com/show_bug.cgi?id=26258 for details.
=> Fix occasional rendering problem in TextBoxes

mcs/class/Managed.Windows.Forms/System.Windows.Forms/Line.cs
Many fonts, including the default DejaVu Sans, use kerning between
certain character pairs.  This resulted in garbled or even invisible
display during typing of strings with a lot of kerning going on.  An
attempt is made to retain the current speed-optimized implementation
while using accurate, slower string width measurements when needed.
See https://bugzilla.xamarin.com/show_bug.cgi?id=26478 for details.
=> Fix TextBox display to handle kerning fonts

mono/metadata/Makefile.am, mono/metadata/sgen-protocol-def.h, mono/metadata/sgen-protocol.c, mono/metadata/sgen-protocol.h, tools/sgen/sgen-grep-binprot.c
You just have to edit mono/metadata/sgen-protocol-def.h to generate a new binary protocol entry type
=> [runtime] Generate binary protocol functions and structure with macro

mcs/class/Managed.Windows.Forms/System.Windows.Forms/ToolStripSplitStackLayout.cs
This addresses https://bugzilla.xamarin.com/show_bug.cgi?id=26523.
=> Fix the default behavior of ToolStripLayoutStyle.Table

mono/metadata/threadpool-internals.h, msvc/libmonoruntime.vcxproj
It was broken by c731686feb3a5d2681d9bf19b2e5c8c2ad35825c
/cc @kumpera
=> Fix Windows build

tools/sgen/sgen-grep-binprot.c
`fread()` spent a great deal of time locking, and we called `malloc()` once for each entry. Replacing `fread()` with `read()` plus manual buffering, as well as replacing `malloc()` with a static buffer, improves throughput by an order of magnitude.
This also adds an `--input` option for reading from a stream other than standard input.
=> Make sgen-grep-binprot faster.

mcs/class/System.Configuration/System.Configuration/ConfigurationPropertyOptions.cs, mcs/class/System.DirectoryServices/System.DirectoryServices/DirectoryEntry.cs, mcs/class/corlib/System.Security.Claims/ClaimsPrincipal.cs, mcs/class/corlib/System.Threading/HostExecutionContext.cs
They are required for the upcoming System.Web port.
=> [bcl] Added a few stubs for missing APIs

mono/tests/test-runner.cs
This makes it easy to plug failures from the runtime tests into a visualisation, such as Jenkins' jUnit display system.
=> Add NUnit XML emission to the managed runtime test runner.

mcs/class/Microsoft.Build.Tasks/Microsoft.Build.Tasks/Copy.cs, mcs/class/Microsoft.Build.Tasks/Test/Microsoft.Build.Tasks/CopyTest.cs
This is required for dotnet/corefx.
=> [Microsoft.Build.Tasks] Implement retries in Copy task and add a stub.

mono/utils/Makefile.am
Exactly what it says on the tin.
=> [utils] Fix warning in Makefile.am.

mono/mini/Makefile.am.in, mono/mini/test_op_il_seq_point.sh, mono/mini/test_op_il_seq_point_headerfooter.sh
This generates an XML representation of the check-seq-points target, as separate tests, which can be easily tracked by anything which parses NUnit output (e.g. Jenkins or other CI systems). For example, we are currently regressed on this on ARM.
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-results name="regression-tests.dummy" total="24" failures="0" not-run="0" date="2015-02-18" time="12:22:54">
<environment nunit-version="2.4.8.0" clr-version="4.0.30319.17020" os-version="Unix 3.13.0-45-generic" platform="Unix" cwd="/home/directhex/Projects/mono/mono/mini" machine-name="marceline" user="directhex" user-domain="marceline" />
<culture-info current-culture="en_GB" current-uiculture="en_GB" />
<test-suite name="op_il_seq_point-tests.dummy" success="True" time="0" …
=> Emit NUnit representation of check-seq-points target.

mcs/class/System/System.IO.Compression/GZipStream.cs
=> Revert "revises GZipStream ctor parameter names"

mcs/class/Microsoft.Build.Engine/Microsoft.Build.BuildEngine/PredefinedPropertyFunctions.cs, mcs/class/Microsoft.Build.Engine/Microsoft.Build.Engine_test.dll.sources, mcs/class/Microsoft.Build.Engine/Test/Microsoft.Build.BuildEngine/PredefinedPropertyFunctionsTest.cs
It is a pretty naive implementation, but should be good enough for now.
=> [Microsoft.Build.Engine] Implement MakeRelative() predefined property function

mono/metadata/sgen-gc.c, mono/metadata/sgen-stw.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
It better hides thread state management in preparation of further changes and
improves system suspend in comparison to GC suspend.
=> This is a small cleanup of the threading API.

mcs/class/System.Runtime.Caching/Test/System.Runtime.Caching/MemoryCacheTest.cs
After MemoryCache was imported from referencesources, some tests started
failing occasionally. Cross-testing on MS.NET showed that you need to
access the cached item to make MemoryCache.GetCount() reliably return the
correct number after an item was expired from the cache.
Also removed `__MonoTimerPeriod` and `__MonoEmulateOneCPU` configuration variables,
they were used in Mono code before and don't make sense with the new code.
=> [System.Runtime.Caching] Make some MemoryCache tests more reliable

mcs/class/Microsoft.Build.Engine/Microsoft.Build.BuildEngine/ConsoleLogger.cs
This occasionally made the BasicManualParallelBuilds test fail on Jenkins.
The inner exception was:
```
System.IndexOutOfRangeException: Array index is out of range.
at System.Collections.Generic.Dictionary`2[System.Object,Microsoft.Build.Logging.ConsoleLogger+BuildRecord].Insert (System.Object key, Microsoft.Build.Logging.BuildRecord value, Boolean add) [0x000e2] in /home/alexander/dev/mono/external/referencesource/mscorlib/system/collections/generic/dictionary.cs:343 
at System.Collections.Generic.Dictionary`2[System.Object,Microsoft.Build.Logging.ConsoleLogger+BuildRecord].Add (System.Object key, Microsoft.Build.Logging.BuildRecord value) [0x00000] in /home/alexander/dev/mono/external/referencesource/mscorlib/system/collections/generic/dictionary.cs:185 
at …
```
=> [Microsoft.Build.Enginge] Fix race in ConsoleLogger

mcs/class/System.XML/System.Xml.Serialization/XmlTypeMapMemberElement.cs, mcs/class/System.XML/Test/System.Xml.Serialization/XmlSerializerTests.cs
These commits add a new failing test case to demonstrate the serialization bug and the code that eliminates it.
=> Fix for Bug 18558

mono/mini/mini-x86.c
=> [x86] Handle stack pop done by native stdcalls.

mcs/class/corlib/System.Reflection/FieldInfo.cs, mcs/class/corlib/System.Reflection/MethodBase.cs, mcs/class/corlib/System.Reflection/MonoField.cs, mcs/class/corlib/System.Reflection/MonoMethod.cs, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/security-core-clr.c, mono/metadata/security-core-clr.h
=> Implement CoreCLR security properties on reflection info types.

configure.ac, mcs/.gitignore, mono/mini/jit.h, mono/mini/mini-runtime.c, mono/profiler/proflog.c
See f091327 for an explanation.
=> [profiler] Redesign buffer flushing and method reporting.

mono/utils/mono-uri.c
There are identical sub-expressions
=> Fix duplicate sub-expressions

mcs/class/System.Windows.Forms/System.Windows.Forms/FileDialog.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ThemeWin32Classic.cs
This fixes https://bugzilla.xamarin.com/show_bug.cgi?id=28025.
=> Show thumbnail images in SWF.(Open,Save)FileDialog

mcs/class/System.XML/Test/System.Xml.Serialization/XmlSerializerTests.cs
Addresses error in test from PR 1672.
=> Corrects error in XmlSerializerTests.

mcs/class/corlib/System/TimeZoneInfo.cs
**Fixes:** [24086](https://bugzilla.xamarin.com/show_bug.cgi?id=24086)
**Fixes:** [28687](https://bugzilla.xamarin.com/show_bug.cgi?id=28687)
=> TimeZoneInfo bug fixing.

samples/profiler/sample.c
Just adds how to build the sample and deploy the sample in mac as well as linux
These two lines would have saved me a few days of work
=> add compilation instructions

scripts/mono-find-provides.in, scripts/mono-find-requires.in
Otherwise, RPMs don't have any dependency information
=> [RPM] Fix MONO_PATH in RPM dependency generators

mcs/class/System.Data/.gitignore
This is according to: https://github.com/mono/mono/blob/master/mcs/class/System.Data/Makefile#L21
=> [git] Ignore System.Data built sources

mono/utils/mono-mutex.h
Like the pthread_cond_wait functions, this needs to release the mutex while waiting on the condition. Otherwise, nothing can set the condition during the wait call.
This commit is licensed as MIT/X11.
=> Release the mutex in mono_cond_[timed]wait on Windows.

mono/metadata/mempool-internals.h, mono/utils/hazard-pointer.c, mono/utils/lock-free-alloc.c, mono/utils/lock-free-array-queue.c, mono/utils/lock-free-queue.c, mono/utils/mono-codeman.c, mono/utils/mono-counters.c, mono/utils/mono-dl.c, mono/utils/mono-linked-list-set.c, mono/utils/mono-linked-list-set.h, mono/utils/mono-logger.c, mono/utils/mono-mmap.c, mono/utils/mono-mutex.c, mono/utils/mono-networkinterfaces.c, mono/utils/mono-path.c, mono/utils/mono-proclib.c, mono/utils/mono-property-hash.c, mono/utils/mono-threads-mach.c, mono/utils/mono-threads-posix.c, mono/utils/mono-threads-state-machine.c, mono/utils/mono-threads.c, mono/utils/mono-tls.h, mono/utils/monobitset.c, mono/utils/strtod.h
So after our brief conversation about C++ yesterday I started looking into what kind of compile issues we'll get if we try to compile the codebase in C++ mode.
These are just the first round of things the compiler complains about and they're mostly related to implicit conversions that are legal in C but disallowed in C++. 
I won't continue down this path until we get some discussion about if we're really serious about adopting some C++ features. We should also figure out if it makes sense to compile the whole codebase in C++ or just leave most of what we already have in C and start progressively adding classes and generics to it.
What do you guys think?
=> C++ compliance fixes

mcs/class/System.Windows.Forms/System.Windows.Forms/FileDialog.cs
This fixes https://bugzilla.xamarin.com/show_bug.cgi?id=29724.
=> Fix memory leak in SWF.FileDialog due to thumbnail images

mono/metadata/threadpool-ms.c
The cleanup code would wait for all worker threads to finish, but that could lead to some workload that would block. By disabling the cleanup code, we do not wait on anything to happen, we count on the OS to clean everything up.
=> [threadpool-ms] Disable cleanup

mcs/class/System.Windows.Forms/System.Windows.Forms/FileDialog.cs
The fix for Xamarin 29724 submitted a day or two ago wasn't quite right.
=> Fix bug in new SWF.MWFFileView.Dispose method (Xamarin 29724)

mono/sgen/sgen-debug.c, mono/utils/hazard-pointer.c, mono/utils/lock-free-alloc.c, mono/utils/lock-free-array-queue.c
Mainly just updating to the new directory structure.
=> [sgen] Fix non-Mono SGen clients.

mono/sgen/sgen-nursery-allocator.c
The types of these counters were changed in 5f33085d, so the atomic updates (should have) stopped working. We can just mutate them non-atomically.
=> [sgen] Fix warnings with heavy stats.

mono/profiler/proflog.c
For the helper and writer thread to actually work, we need Mono's threading subsystem to be initialized (so we can use TLS and hazard pointers). We now wait with starting these threads until Mono gives us the go-ahead.
This means that a bit more data will be buffered up in the thread-local log buffers during startup, but it shouldn't really matter in practice.
**Please don't merge yet.**
=> [profiler] Initialize threads in runtime initialization callback

mono/profiler/proflog.c
getline(3) is not available on Android API < 21, so we use our own custom functions
=> [Profiler] Replace getline(3)

mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs
What happens here is the following:
When using chunked encoding, the ChunkStream sometimes mixes async and sync requests
on the underlying stream.  The async calls work great - just the sync ones create
problems.
In this particular bug, the server returns two ApplicationData records - one big one
and then a smaller one.  The chunk parser requests a sync read of 1024 bytes which
then result in a series of sync reads on the underlying network stream.  The first
two or three network reads don't return enough data to fill the huge ApplicationData
record - the last one then returns so much data that it fills both the remainder of
the first record and the entire second one.
If the caller issued a second sync read, then the implementation would catch this -
but the async code path does not.
=> [TLS]: Fix #23792.

mono/metadata/profiler.c, mono/profiler/decode.c, mono/profiler/proflog.c
Just an assortment of random improvements.
=> Profiler improvements

mono/io-layer/processes.c
This way there is no need to mount /proc
to use nunit. /proc filesystem is by default not used
on the FreeBSD system.
=> Use sysctl and <link.h> interface for FreeBSD

mono/io-layer/processes.c
Use normal sysctl(3) interface (just like
Mac OS X), the OpenBSD way does not seem to work.
Followup to https://github.com/mono/mono/pull/1863
=> FreeBSD: sysctl() to get process information

mcs/class/System.ServiceModel/Test/System.ServiceModel/ServiceHostBaseTest.cs, mcs/class/System/Test/System.Net/HttpWebRequestTest.cs
Follow up to https://github.com/mono/mono/pull/1871
=> [WIP] Fix tests breaking due to network ports

configure.ac, mono/mini/aot-compiler.c, mono/mini/graph.c, mono/mini/helpers.c
It's not available in the iOS WatchOS simulator.
=> Add a conditional for the system function.

mcs/class/Mono.CompilerServices.SymbolWriter/MonoSymbolTable.cs
Discovered by coverity in NRefactory.
=> [mcs] Fix order of parameters for LineNumberEntry

mono/metadata/metadata.c
Fixes:
https://bugzilla.xamarin.com/show_bug.cgi?id=29679
=> [msbuild][crash] Enums are classes that can be assigned to value types

mono/metadata/threads.c
We had a use-after-free bug in context freeing that creating
and freeing AppDomains in parallel exposed.
We called g_hash_table_remove in a callback to g_hash_table_foreach, which
resulted in freeing the Slot struct that the g_hash_table_foreach was
holding a local reference to.
When it tried to get the chained 'next' element in the table, if
other threads caused enough memory pressure to reuse that memory
between freeing and getting the 'next' pointer, then we try to
dereference a garbage value and get a SIGSEGV.
=> [runtime] Fixed use-after-free in context freeing

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
https://bugzilla.xamarin.com/show_bug.cgi?id=19687
=> Fix TransparentProxy ObjectMirror value queries via debugger

mono/metadata/debug-helpers.c, mono/mini/aot-runtime.c, mono/tests/find_aot_method_in_amodule_stress/Makefile, mono/tests/find_aot_method_in_amodule_stress/Template.py
A number of optimizations to reduce the work and allocation done, and a benchmark.
I see a decrease in the average running time of this method from 300-500ms to about 17ms, as measured by OSX's Instruments.
=> [runtime] Speed up find_aot_method_in_module

mono/metadata/class.c
The changes fix stack overflows caused while traversing images with
cyclic references.
Fixes [#31396](https://bugzilla.xamarin.com/show_bug.cgi?id=31396)
=> [runtime] mono_class_from_name cyclic ref handling

mcs/class/System.Web/System.Web.dll.sources, mcs/class/System.Web/System.Web/HttpApplication.cs
HttpApplication: https://msdn.microsoft.com/en-us/library/system.web.httpapplication(v=vs.110).aspx
=> [System.web] Reference source imports + HttpApplication fix

runtime/Makefile.am
=> [mono-config] update path to libMonoPosixHelper in runtime/ as well

mcs/class/System/Test/System.Net/HttpListenerTest.cs
There was a race so that sometimes ipEndPoint wasn't yet assigned when the method returned, 
which resulted in the test failing like this:
```
MESSAGE:  reuse1
Expected: <127.0.0.1:54370>
But was: null
```
To fix this the race, we now wait until ipEndPoint is assigned before returning.
The test was actually disabled on Android because of this (see 7cb4cc9c0e61d921c75ab654641a154d12cc8085), we can reenable it again as it should now work fine.
=> [System] Fix race condition in HttpListenerTest.ConnectionReuse test

mcs/class/System/System.Net/ServicePoint.cs
See https://bugzilla.xamarin.com/show_bug.cgi?id=32685
=> Fix NRE in CheckAvailableForRecycling. Fixes #32685

mono/mini/cpu-ppc.md, mono/mini/mini-ppc.c
Per @directhex's observations and testing here: https://github.com/mono/mono/pull/1925#issuecomment-127190268
=> Fix atomic_add_i4 on PPC

mcs/class/System/System.Diagnostics/Process.cs, mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs, mcs/class/corlib/System.Runtime.Remoting.Messaging/AsyncResult.cs, mcs/class/corlib/System.Runtime.Remoting.Messaging/MonoMethodMessage.cs, mcs/class/corlib/System/Environment.cs, mcs/class/corlib/System/MonoAsyncCall.cs, mono/metadata/appdomain.c, mono/metadata/icall-def.h, mono/metadata/marshal.c, mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/threadpool-ms.c
Depends on https://github.com/mono/mono/pull/1911
=> [runtime] Move AsyncResult.Invoke to managed

mono/arch/s390x/s390x-codegen.h, mono/mini/mini-posix.c, mono/mini/mini-s390x.c, mono/utils/mono-hwcap-s390x.h
Conversion of to/from unsigned integer values was incorrect resulting in bad values being returned.
=> Fix and simplify float conversions - for 3.12.0

mono/io-layer/processes.c
GetModuleFileNameEx now returns a full path instead of the process name.
Fixes [#32579](https://bugzilla.xamarin.com/show_bug.cgi?id=32579)
=> [runtime] GetModuleFileNameEx

mono/mini/exceptions-ppc.c, mono/mini/mini-ppc.h, mono/utils/mono-context.h
This patch adds a basic mono_arch_setup_async_callback function and a full MonoContext.
=> [ppc] Add MonoContext and asynch callback support

mono/mini/mini-amd64.c, mono/mini/mini-runtime.c, mono/mini/mini.h, mono/mini/test_op_il_seq_point.sh
=> Revert "[runtime] Fix test_op_il_seq_point in amd64."

mcs/class/System/System.Net/WebHeaderCollection.cs
as mentioned by FastCode in IRC
=> fixing typo appropiate in WebHeaderCollection.cs

mono/mini/mini-ppc.c, mono/mini/mini-ppc.h, mono/tests/Makefile.am, mono/tests/libtest.c, mono/tests/pinvoke_ppcc.cs, mono/tests/pinvoke_ppcd.cs, mono/tests/pinvoke_ppcf.cs, mono/tests/pinvoke_ppci.cs, mono/tests/pinvoke_ppcs.cs
Note that there are some additional commits to add the ABI changes for returning-structures-from-functions.
=> [ppc] Changes for power for ELF ABI v2 structure parameters

mcs/tools/resgen/monoresgen.cs
- Add support for #if, #ifdef, #if !SYMBOL, #else
and #endif directives
- Add /DEFINE: (/DEFINE:) option:
/D:SYMBOL1 /D:SYMBOL2 or /DEFINE:SYMBOL1,SYMBOL2
This is needed to compile mscorlib resources
from CoreCLR
=> [resgen] Implement conditional resources (#if/#ifdef)

mcs/class/corlib/System/TimeZoneInfo.cs
See https://bugzilla.xamarin.com/show_bug.cgi?id=30360
=> [ppc] Fix exception when reading from timezone file.

mono/sgen/sgen-gchandles.c
Haven’t been able to test with XS yet, but this should work.
=> Fix assertion in mono_gchandle_get_target.

mono/metadata/object.c, mono/metadata/threadpool-ms.c
The timeout before exiting a worker thread is random to limit the worst case scenario where, if the timeout is set to N seconds, the user would launch a lot of work item simultaneously, at an interval of N + 1 seconds. In this case, we would have to kill all the threads at once, and starts them all over again 1 second later. The randomization makes the creation and destruction more linear in time, and avoid burst.
=> [threadpool-ms] Exit worker thread after 5 to 60 seconds

mono/metadata/marshal.c
`mono_threads_prepare_blocking`, `mono_threads_finish_blocking`,
`mono_threads_reset_blocking_start`, `mono_threads_reset_blocking_end` all
take a stack pointer argument.  Update the native and managed wrappers
to pass it to them.
=> [coop] update native call marshalling to pass thread state transition functions a stack ptr arg.

mono/mini/mini-llvm-cpp.cpp, mono/mini/mini-ppc.h
Just the basic things to activate the llvm backend for power.
=> [ppc] Activate llvm for power

mono/metadata/marshal.c
Missed a pair of
`mono_threads_reset_blocking_start`/`mono_threads_reset_blocking_end`
calls in 991e3ef3e47f0ccf9981a791f7da680b4ee9c4c6
=> [coop] One more pair of coop gc marshal fixes.

mono/mini/debugger-agent.c
The problem happens because thread_interrupt runs in the debugger thread (suspend initiator).
thread_interrupt then calls mono_thread_state_init_from_monoctx which collects the state of the current thread
which is definitely not what we wanted.
There used to be some compensation code after calling mono_thread_state_init_from_monoctx to actually init the state properly.
This is why it worked, at all.
Thew problem is that the debugger thread now might not attach at all under some circumstances, which would trigger
mono_thread_state_init_from_monoctx to return FALSE and trip into the assert.
The fix is to simply not use mono_thread_state_init_from_monoctx at all, just copy the state from data. This fix has the
bonus of getting the domain correctly.
=> [sdb] Fix state initialization of suspended threads to work when the debugger thread is not attached. Fixes #34750

mono/metadata/assembly.c, mono/metadata/class-internals.h, mono/metadata/image.c, mono/metadata/mempool.c, mono/metadata/mempool.h, mono/metadata/metadata-internals.h, mono/metadata/metadata.c, mono/mini/aot-runtime.c
This is the first commit of pull request #2163 (see comments and description there), plus changes for the comments on that pull request, moved out into its own PR.
=> Mempool reference-auditing feature in checked builds (prep work only)

mono/metadata/gc.c, mono/metadata/marshal.c, mono/metadata/mono-hash.c, mono/metadata/sgen-stw.c, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/branch-opts.c, mono/mini/mini-amd64.c, mono/mini/mini-arm.c, mono/mini/mini-runtime.c, mono/mini/mini-s390x.c, mono/mini/mini-x86.c, mono/mini/mini.c, mono/mini/mini.h, mono/utils/mono-threads-coop.c, mono/utils/mono-threads-coop.h, mono/utils/mono-threads-mach-abort-syscall.c, mono/utils/mono-threads-mach.c, mono/utils/mono-threads-posix-abort-syscall.c, mono/utils/mono-threads-posix-signals.c, mono/utils/mono-threads-posix.c, mono/utils/mono-threads-windows-abort-syscall.c, mono/utils/mono-threads-windows.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
To enable cooperative suspend, simply set the MONO_ENABLE_COOP
environment variable.
=> [threads] Use runtime flag to enable cooperative suspend

mcs/class/System.DirectoryServices/System.DirectoryServices-net_4_5.csproj, mcs/class/System.DirectoryServices/System.DirectoryServices-net_4_x.csproj, mcs/class/System.DirectoryServices/System.DirectoryServices.ActiveDirectory/ActiveDirectoryObjectNotFoundException.cs, mcs/class/System.DirectoryServices/System.DirectoryServices.dll.sources
largely copied from ActiveDirectoryOperationException
=> Add stub implementation of ActiveDirectoryObjectNotFoundException

mono/profiler/proflog.c
=> [profiler] Disable the hack to attempt to get code start/size info. (4.2.0)

mcs/class/Microsoft.Build.Engine/Microsoft.Build.BuildEngine/Engine.cs, mcs/tools/xbuild/data/12.0/Microsoft.Common.targets, mcs/tools/xbuild/data/14.0/Microsoft.Common.targets, mcs/tools/xbuild/data/2.0/Microsoft.Common.targets, mcs/tools/xbuild/data/3.5/Microsoft.Common.targets, mcs/tools/xbuild/data/4.0/Microsoft.Common.targets
=> Revert 8862921b8611220f5d744f5b7f5d7e064a9769b6

mcs/class/System.Drawing/System.Drawing/ColorTranslator.cs, mcs/class/System.Drawing/Test/System.Drawing/ColorTranslator.cs
=> ColorTranslator.FromHtml 3-digit codes support (#35664)

mcs/class/corlib/Test/System.Reflection/MonoGenericClassTest.cs, mono/metadata/class.c
Backport #2207 to https://github.com/mono/mono/tree/mono-4.3.1-branch
=> [reflection] Fix for 35375 (4.3.1)

mono/metadata/Makefile.am, mono/utils/Makefile.am, msvc/libmonoruntime.vcxproj, msvc/libmonoutils.vcxproj
Previous patch missed some build files.
=> Minor: Style cleanup on internal headers (continued)

mcs/tools/linker/Mono.Linker.Steps/BlacklistStep.cs, mcs/tools/linker/Mono.Linker.Steps/ResolveFromXmlStep.cs
With this mtouch will show:
error MT2001: Could not link assemblies. Reason: Failed to process XML description: /work/maccore/master/maccore/tests/link sdk/extra-linker-defs.xml
Failed to process XML description: /work/maccore/master/maccore/tests/link sdk/extra-linker-defs.xml
Failed to resolve assembly: 'MonoTouch, Culture=neutral, PublicKeyToken=null'
instead of:
error MT2002: Failed to resolve assembly: 'MonoTouch, Culture=neutral, PublicKeyToken=null'
which is a lot less helpful
=> [linker] Provide better error message when an error occurs while processing xml descriptions

mcs/class/monodoc/Monodoc.Ecma/EcmaDesc.cs, mcs/class/monodoc/Test/Monodoc.Ecma/EcmaUrlTests.cs
In particular:
- Issues with cref formatting for subtypes.
- Added support for Explicitly implemented members.
- Added support for generic member parameters.
A number of unit tests were added to verify this functionality.
=> [monodoc] Fixed several issues with `.ToEcmaCref` method.

mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/TargetDotNetFrameworkVersion.cs, mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/ToolLocationHelper.cs, mcs/tools/xbuild/Makefile, mcs/tools/xbuild/frameworks/net_4.6.1.xml, mcs/tools/xbuild/frameworks/net_4.6.xml
Commented the entries in ToolLocationHelper, they could be misunderstood since the 4.0/4.5/4.6 entries are all the same.
=> [xbuild] Add net_4.6.xml/net_4.6.1.xml and wire through xbuild

mcs/class/System/System.Net.NetworkInformation/NetworkInterface.cs
This change fixes bug https://bugzilla.xamarin.com/show_bug.cgi?id=2033
=> [NetworkInterface] IPv4Mask property implementation for Linux

mcs/class/Microsoft.Build.Tasks/Microsoft.Build.Tasks-net_4_5.csproj, mcs/class/Microsoft.Build.Tasks/Microsoft.Build.Tasks-net_4_x.csproj, mcs/class/Microsoft.Build.Tasks/Microsoft.Build.Tasks-xbuild_12.csproj, mcs/class/Microsoft.Build.Tasks/Microsoft.Build.Tasks.dll.sources, mcs/class/Microsoft.Build.Tasks/Microsoft.Build.Tasks/XmlPeek.cs
XmlPeek was missing from Mono. Adding it based on the
open source msbuild implementation with a few minor
changes because of missing support classes.
=> [msbuild] Added XmlPeek

mcs/docs/Makefile
=> [docs] fix case in Makefile

mcs/class/System/Documentation/en/ns-System.Security.Cryptography.xml
Closes https://github.com/xamarin/documentation/issues/944
=> Changed link from GUID to URL

mono/utils/networking-posix.c
Merged to master in https://github.com/mono/mono/pull/2154.
=> Port fix for Bug 30018 to C6SR1

mono/metadata/threadpool-ms.c
=> Revert "[threadpool-ms] Exit worker thread after 5 to 60 seconds"

mcs/class/corlib/System/Delegate.cs, mcs/class/corlib/System/MulticastDelegate.cs, mono/tests/Makefile.am, mono/tests/delegate13.cs
.NET returns the method for the last delegate of the multicast delegate.
=> [delegate] Fix multicast Method property implementation

mcs/class/System.Web/System.Web.Util/UrlUtils.cs
This is a fix for the
https://bugzilla.xamarin.com/show_bug.cgi?id=36724
also patch for portage was created - https://github.com/gentoo/dotnet/pull/147
=> fix for https://bugzilla.xamarin.com/show_bug.cgi?id=36724

mono/mini/driver.c
We just reverted a patch that prevented the FileSystemWatcher from
opening too many file descriptors (200).  That was a band-aid at one
of the spots that opened too many file, as we would exhaust the number
of files, and later abort when some other operation needed files.
The problem is that OSX defaults to 256 file descriptors, and .NET
applications are file descriptor hungry, in fact, many applications
increase their file handled limit before starting.
This patch on OSX will attempt to increase the number of handles
available to 1024 if the number of handles avaialble is less than
that.
The commit that removed the limit was:
2af882232ce4961fdbe1ba0ae36246456bb1fbfb
And it was closed to fix:
#28693
=> [mono/driver] On OSX, increase the number of file handles available.

mcs/class/System.ServiceModel/Test/System.ServiceModel.Dispatcher/Bug32886Test.cs, mcs/class/System.ServiceModel/Test/System.ServiceModel.Dispatcher/Bug652331Test.cs, mcs/class/System.ServiceModel/Test/System.ServiceModel.Dispatcher/Bug652331_2Test.cs
=> [tests] Fix more System.ServiceModel flakiness

mcs/tools/xbuild/data/12.0/Microsoft.Common.targets, mcs/tools/xbuild/data/14.0/Microsoft.Common.targets, scripts/xbuild.in
@marek-safar since this turned out to be a bit more involved, would you mind taking a look?
=> Bump xbuild script to 14.0 and a few other fixes

mcs/class/System.ServiceModel/System.ServiceModel/NetTcpBinding.cs, mcs/class/System.ServiceModel/Test/System.ServiceModel/NetTcpBindingTest.cs
=> Add test and merge #1879

mono/mini/mini-ppc.c, mono/mini/mini-ppc.h
I am adding some support for how the v2 elf ABI handles function return values and in preparation I added some new macros and support functions.
=> [powerpc] New macros and utility functions for v2 elf ABI function calls

mcs/class/System.ServiceModel/System.ServiceModel/ServiceHost.cs, mcs/class/System.ServiceModel/Test/System.ServiceModel/ServiceHostTest.cs
Fixes [#37035](https://bugzilla.xamarin.com/show_bug.cgi?id=37035)
=> [WCF] ServiceHost should look for inherited ServiceBehaviorAttribute

mcs/class/System/Test/System.Net.Sockets/SocketTest.cs
We were sometimes seeing the following failure on Jenkins on OSX:
```
Test Case Failures:
1) MonoTests.System.Net.Sockets.SocketTest.AcceptBlockingStatus : System.Net.Sockets.SocketException : Operation on non-blocking socket would block
at System.Net.Sockets.Socket.Accept () [0x00033] in /Users/builder/jenkins/workspace/test-mono-mainline/label/osx-i386/mcs/class/System/System.Net.Sockets/Socket.cs:896
at MonoTests.System.Net.Sockets.SocketTest.BlockingConnect (Boolean block) [0x0003e] in /Users/builder/jenkins/workspace/test-mono-mainline/label/osx-i386/mcs/class/System/Test/System.Net.Sockets/SocketTest.cs:129
at MonoTests.System.Net.Sockets.SocketTest.AcceptBlockingStatus () [0x0001e] in /Users/builder/jenkins/workspace/test-mono-mainline/label/osx-i386/mcs/class/System/Test/System.Net …
```
=> [System] Fix flaky AcceptBlockingStatus test that sometimes failed on OSX

data/gdb-pre7.0/mono-gdb.py, data/gdb/mono-gdb.py
Fix the format statements in GDB's mono mode plugin.
The %s-style that is currently used is meant for the old and deprecated [% format operator](https://docs.python.org/2/library/stdtypes.html#string-formatting), not for the current [format](https://docs.python.org/3/library/string.html#formatspec) method that only accepts curly braces as replacement field designators.
For instance, without the patch, the current name is printed as "%s:%s"(sic). After applying the patch, it should be properly shown as something like "System.Object:wbarrier_noconc".
=> Fix the format statements in mono-gdb.

mcs/tools/mdoc/Makefile, mcs/tools/mdoc/Mono.Documentation/mdoc.cs, mcs/tools/mdoc/Mono.Documentation/monodocer.cs, mcs/tools/mdoc/Test/DocTest-DropNS-classic.cs, mcs/tools/mdoc/Test/DocTest-DropNS-unified.cs, mcs/tools/mdoc/Test/en.expected-dropns-classic-v1/MyFramework.MyNamespace/MyClass.xml, mcs/tools/mdoc/Test/en.expected-dropns-classic-withsecondary/MyFramework.MyNamespace/MyClass.xml, mcs/tools/mdoc/Test/en.expected-dropns-classic-withsecondary/MyFramework.MyOtherNamespace/MyOtherClass.xml, mcs/tools/mdoc/Test/en.expected-dropns-delete/MyFramework.MyNamespace/MyClass.xml, mcs/tools/mdoc/Test/en.expected-dropns-delete/MyFramework.MyNamespace/TypeOnlyInClassic.xml, mcs/tools/mdoc/Test/en.expected-dropns-multi-withexisting/MyFramework.MyNamespace/MyClass.xml, mcs/tools/mdoc/Test/en.expected-dropns-multi-withexisting/MyFramework.MyNamespace/OnlyInMulti.xml, mcs/tools/mdoc/Test/en.expected-dropns-multi-withexisting/index.xml, mcs/tools/mdoc/Test/en.expected-dropns-multi-withexisting/ns-MyFramework.MyNamespace.xml, mcs/tools/mdoc/Test/en.expected-dropns-multi/MyFramework.MyNamespace/MyClass.xml
This brings in the latest mdoc commits into `mono-4.3.1-branch`
=> [mdoc] sync mono-4.3.1-branch with mdoc commits

mcs/class/corlib/ReferenceSources/CLRConfig.cs, mono/metadata/appdomain.c, mono/metadata/domain-internals.h, mono/metadata/icall-def.h, mono/metadata/object.c
Improves the situation wrt: https://bugzilla.xamarin.com/show_bug.cgi?id=36560
=> [TPL] Add support for the <ThrowUnobservedTaskExceptions /> config element.

mcs/class/corlib/Test/System.Threading/ThreadPoolTest.cs, mono/metadata/threadpool-ms.c
=> [4.2.0][threadpool] Fix get min and available threads icalls

mcs/class/corlib/System.Globalization/CultureInfo.cs, mcs/class/corlib/Test/System.Globalization/CultureInfoTest.cs
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=37848
=> [corlib] Throw correct exception for GetCultureInfo(0)

mono/metadata/handle.c
Remove the `chunk_last` field.  This changes MonoHandleArena from a queue of chunks to a stack of chunks.  More importantly, the MonoHandleArena has an initial chunk that is allocated on the stack together with the arena.  Previously that chunk was at the front of the list of chunks, but now it is at the end.
=> [handle] Remove chunk_last field from MonoHandleArena

mono/metadata/reflection.c
=> [runtime] Use MonoError for check_array_for_usertypes

mono/metadata/reflection.c
=> [runtime] Use MonoError for RESOLVE_TYPE

mcs/class/Mono.Posix/Test/Mono.Unix.Native/SocketTest.cs
See https://github.com/mono/mono/pull/2514 for context.
Unlike Linux, OSX does not allow multiple SCM_RIGHTS control messages in
sendmsg().
The SocketTest.ControlMsg() test is split into two tests, one which sends
only a single control message (containing two FDs), and another one which
sends two control messages (each containing one FD). The second test is not
executed on OSX.
I'm not sure whether the OSX behaviour is correct, as POSIX doesn't say much about how SCM_RIGHTS works. Anyway, the old test case is something which is rather unlikely to appear in a real program (normally you would use one control message containing multiple FDs), but I'd like to keep it on Linux because it also tests having multiple control messages at all, so I've split the test into two tests, where one isn't …
=> [Mono.Posix] Fix the SocketTest.ControlMsg() test on OSX

mono/dis/dump.c, mono/dis/get.c, mono/metadata/attach.c, mono/metadata/coree.c, mono/metadata/debug-helpers.c, mono/metadata/loader.c, mono/metadata/marshal.c, mono/metadata/metadata-verify.c, mono/metadata/reflection.c, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/debugger-agent.c, mono/mini/driver.c, mono/mini/dwarfwriter.c, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c, mono/mini/mini-trampolines.c
This removes usage of mono_get_method(_full).
Reflection and the JIT remain problematic, but this removes one of the big offender.
=> [mono-error] Another round of loader-error

mcs/build/library.make, mcs/build/profiles/mobile_static.make, mcs/build/rules.make, mcs/build/tests.make, mcs/class/Facades/Makefile, mcs/class/I18N/Makefile, mcs/class/Makefile, mcs/tools/nunit-lite/Makefile, mcs/tools/nunit-lite/nunit-lite-console/Makefile
All but the last commit are parts of other PRs. This repository will be rebased. This PR is made as-is in order to get code review.
I've made the build system optionally run in a 2-pass system where the first pass produces .dll and .exe files, and the second pass produces aot'ed versions of those files.
=> [aot/bcl] Compile the BCL with AOT

mono/metadata/object-internals.h, mono/metadata/object.c, mono/mini/aot-runtime.c, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c, mono/mini/mini-trampolines.c, mono/mini/mini.c, mono/mini/mini.h, mono/utils/mono-error.c
Convert more parts of the JIT to use MonoError.
=> Jit errors2

configure.ac, mono/metadata/loader.c, mono/metadata/loader.h, mono/utils/mono-publib.h
=> [api] Add API kill switch.

mcs/class/System.IO.Compression/ZipArchive.cs
Fix for https://bugzilla.xamarin.com/show_bug.cgi?id=38335
=> Fix stream leak when failing to open a zip file

mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/reflection-internals.h, mono/metadata/reflection.c, mono/metadata/reflection.h
=> [reflection] Use MonoError for mono_module_get_object

mono/metadata/appdomain.c, mono/metadata/icall.c, mono/metadata/reflection-internals.h, mono/metadata/reflection.c, mono/metadata/reflection.h, mono/mini/debugger-agent.c, mono/mini/jit-icalls.c
=> Use MonoError in mono_assembly_get_object

mono/io-layer/io.c
Quick fix for https://bugzilla.xamarin.com/show_bug.cgi?id=37834
IOLayer is_file_writable/System.IO.File.GetAttributes on posix systems looks only at the unix file permissions and does not consider special OS flags. This leads to an easily end-user-triggered bug on OS X if a mono app (the bug was observed in Xamarin Studio) uses GetAttribute on a file which has been "Locked" using the checkbox in Finder Get Info. This patch recognizes the "uchg" flag for non-writability which Finder uses.
=> Recognize OS X file "locked" state (fixes #37834)

mono/metadata/appdomain.c, mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/reflection-internals.h, mono/metadata/reflection.c, mono/metadata/reflection.h, mono/mini/debugger-agent.c, mono/mini/mini-runtime.c
=> [reflection] Grab bag of MonoError commits

mono/metadata/threadpool-ms.c
Because the ThreadPool heuristic is optimized for short lived work item, it has more difficulty when executing long lived work item. That case can lead to a starvation of the worker threads: they are all doing work, while there is outstanding request, and these requests are not satisfied because we reached the max number of working thread.
To fix that issue, we have the monitor thread, whose sole job is to unstuck this kind of starvation cases. Unfortunately, it only works when all the worker threads are in the ThreadState.WaitSleepJoin state, which excludes the case of calling an IO operation in a Task. That includes the case of FileStream.BeginRead/Write/... which implementation can be simplified as follows: FileStream.BeginRead(...) -> Task.Run(() => FileStream.Read(...)).
The way we …
=> [threadpool] Improve the monitor thread heuristic

mcs/class/System.Windows.Forms/System.Windows.Forms/XplatUIWin32.cs, mcs/class/System.Windows.Forms/System.Windows.Forms_test.dll.sources, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/FormThreadTest.cs
=> [System.Windows.Forms] Recreate FosterWindow when required in XplatUIWin32

mono/metadata/threads.c
Depends on https://github.com/mono/mono/pull/2554
=> [threads] Split abort/suspend into self and async cases

mcs/class/corlib/Makefile, mcs/class/corlib/Test/System/StringTest.cs
#2612 
This bug is interfering with testing of the 4.3.2 branch.
=> Backport PR#2612 to 4.3.2

mcs/class/System.Configuration/System.Configuration/Configuration.cs, mcs/class/System.Configuration/Test/System.Configuration/ConfigurationManagerTest.cs, mcs/class/System/System.Configuration/CustomizableFileSettingsProvider.cs, mcs/class/System/Test/System.Configuration/ApplicationSettingsBaseTest.cs
Bring https://github.com/mono/mono/pull/2400 into mono 4.3.2.
=> [System] Fix extra head in config bug.

mcs/class/System.ServiceModel/System.ServiceModel.Dispatcher/XmlMessagesFormatter.cs, mcs/class/System.ServiceModel/Test/System.ServiceModel/ClientBaseTest.cs
Gets https://github.com/mono/mono/pull/2323 into mono 4.3.2
=> [System.ServiceModel] Fixes missing xsi xsd attributes

mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/ProcessWrapper.cs
The previous implementation of ProcessWrapper would launch its own threads to read on the process stdout and stderr. We can more simply use OutputDataReceived and ErrorDataReceived which will do the same under the hood. We use as well the Exited event to track the end of the Process.
=> [Microsoft.Build] Fix Microsoft.Build.Execution.BuildManagerTest.BasicManualParallelBuilds

mono/mini/driver.c, mono/tests/threadpool.cs
* Fix error in DISABLE_HW_TRAPS implementation
* Rename class in mono/tests/threadpool.cs to allow embedding
=> Minor platform-support fixes

mono/metadata/locales.c, mono/metadata/locales.h
=> [runtime] Remove ves_icall_System_String_InternalReplace_Str_Comp

mcs/tools/xbuild/Makefile
It needs for build WebProjects with xbuild.
=> Add generation WepApplication.targets for v12.0 and v14.0 xbuild.

mono/utils/mono-threads.c
This overflow would happen of the machine was up for more than 29 days, leading to an overflow in the value returned by mono_100ms_ticks.
The simplest solution is simply to resort to mono_100ns_ticks which would only overflow after more than 29247 years. So even the platform implement this value as the time since 0000-00-00 00:00:00, we still have more than 27000 years if front of us. It's also highly unlikely that we would overflow the `end' value when adding `ms', as that would mean we are in the last 29 days of that 29247 years.
=> [threads] Fix mono_thread_info_sleep overflow

mcs/class/corlib/System/TimeZoneInfo.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
=> Don't trim TimeZone names ending in parenthesys

mcs/class/Mono.Options/Mono.Options/Options.cs
The `TypeDescriptor` types aren't available on PCL, but in this case I switch it out for a more basic, but cross-platform conversion using `IConvertible` through `Convert.ChangeType`.
This change should not affect the net40 running at all.
=> [Mono.Options] Changed the code a bit so that it works with PCL

mono/metadata/jit-info.c, mono/metadata/sgen-mono.c, mono/metadata/sgen-os-mach.c, mono/metadata/sgen-os-posix.c, mono/metadata/sgen-os-win32.c, mono/metadata/sgen-stw.c, mono/mini/mini-posix.c, mono/sgen/sgen-alloc.c, mono/sgen/sgen-debug.c, mono/unit-tests/test-mono-linked-list-set.c, mono/utils/hazard-pointer.c, mono/utils/hazard-pointer.h, mono/utils/lock-free-alloc.c, mono/utils/lock-free-queue.c, mono/utils/mono-conc-hashtable.c, mono/utils/mono-linked-list-set.c, mono/utils/mono-linked-list-set.h, mono/utils/mono-threads.c, mono/utils/mono-threads.h
See aa0d58f2e87e317996dae86ec7ec447cc39ef520 for an explanation.
=> Fix a crash in the MONO_LLS_FOREACH_SAFE macro

mono/mini/mini-runtime.c
=> [jit] remove 'jit_' prefix in two phases in stats output

mcs/class/PEAPI/Metadata.cs, mcs/ilasm/codegen/MethodDef.cs, mono/metadata/class.c, mono/metadata/object-internals.h, mono/metadata/threads.c, mono/mini/method-to-ir.c, mono/mini/mini-amd64.c, mono/mini/mini-arm.c, mono/mini/mini-ia64.c, mono/mini/mini-mips.c, mono/mini/mini-s390x.c, mono/mini/mini-sparc.c, mono/mini/mini-x86.c, mono/mini/mini.c
This addresses compiling b28158/test.il and executing exchangetneg.
=> First batch of bug fixes found in the CoreClr test suite.

mono/metadata/threads.c
A suspended thread, in non-coop case, can be holding runtime locks. When the suspender tries to unwind the stack for this thread, it might require taking of runtime locks (ex. in aot case we might search for the jit info in the aot image and then register it, which requires the domain lock). Mark the suspender thread as running in async context while it unwinds other threads.
=> [runtime] Fix deadlock while unwinding the stack of suspended thread

mono/mini/aot-runtime.c
The last source was on the AOT compiler in load_image.
I hooked enough MonoError to bubble the issue to a reasonably higher layer.
@vargaz please review.
=> This removed the last source of loader error from the runtime

mono/metadata/reflection.c
Depends on #2745
Bubble MonoError up to `mono_reflection_create_runtime_class`.  Use `mono_error_set_pending_exception` instead of `mono_error_raise_exception` And try to release resources on the way out.
=> [System.Reflection.Emit] MonoError in mono_reflection_create_runtime_class

mcs/tools/corcompare/Makefile, scripts/.gitignore, scripts/Makefile.am
We install its counterpart mono-api-info already
=> Install mono-api-html

mcs/class/System/System.Net.Sockets/SafeSocketHandle.cs
We are quite frequently seeing an error on the ARM workers on Jenkins:
```
Test Case Failures:
1) MonoTests.System.Net.Sockets.SocketTest.SendAsyncFile : System.Exception : Could not abort registered blocking threads before closing socket.
at System.Net.Sockets.SafeSocketHandle.ReleaseHandle () [0x000be] in /media/ssd/jenkins/workspace/test-mono-mainline/label/debian-armhf/mcs/class/System/System.Net.Sockets/SafeSocketHandle.cs:77
at System.Runtime.InteropServices.SafeHandle.DangerousReleaseInternal (Boolean dispose) <0x42cb0050 + 0x0020b> in <filename unknown>:0
at System.Runtime.InteropServices.SafeHandle.InternalDispose () <0x446ba758 + 0x00023> in <filename unknown>:0
at System.Runtime.InteropServices.SafeHandle.Dispose (Boolean disposing) [0x00000] in …
```
=> [System] Use Monitor.Wait/Pulse in SafeSocketHandle instead of Thread.Sleep

mono/utils/mono-signal-handler.h
Krait cpus don't ignore thumb ITT state in ARM mode (it's unspecified CPU behavior).
The linux kernel then didn't bother resetting that state when landing an ARM signal handler.
The end result was that Krait cpus would skip the first few instructions of the signal handler
and things would explode in the most amazing possible ways.
Patch by Mark Probst <mark.probst@gmail.com>.
=> [android] Fix Krait CPU bug on Android.

mcs/class/corlib/System.Runtime.InteropServices/GCHandle.cs
1) Free() throws on MS.NET when the handle was already freed, copied and adapted the referencesource implementation.
2) Explicit conversion from IntPtr to GCHandle throws InvalidOperationException when value is IntPtr.Zero on MS.NET, not ArgumentException.
This fixes two failing CoreCLR test cases.
=> [corlib] Two small fixes for GCHandle

configure.ac
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=34314.
=> Fixed runtime dependency on libgdiplus with developer soname

mcs/class/Mono.Options/Mono.Options/Options.cs, mcs/class/Mono.Options/Test/Mono.Options/OptionSetTest.cs
- Support for String to Enum
- Support for Number to Enum
- Support for Flags to Enum
- Added a UnitTest
=> [Mono.Options] Added support for Enums in the PCL version

mcs/class/System/System.Net/EndPointListener.cs
Affects all HttpListener usages.
A connect flood will break the async loop and take down the entire HttpListener instance (will stop accepting connections).
To reproduce. Take a HttpListener run say 2 wrk test instances against it (1000 connections each works here). After the run the HttpListener has broken its async loop and will no longer accept any connections after. The reason for this is that it was not previously handling the case that AcceptAsync can return synchronously. In this case event will not be called with args.
Patch handles this case and the above issue is not reproducible with.
=> handles AwaitAsync finishing synchronously

mono/metadata/class-internals.h, mono/metadata/loader.c, mono/metadata/metadata.c, mono/metadata/mono-basic-block.c, mono/metadata/mono-basic-block.h, mono/metadata/verify.c, mono/mini/aot-runtime.c, mono/mini/method-to-ir.c, mono/mini/unwind.c
=> Cherry-pick alexanderkyte PRs #2781 #2783 #2785 #2786

.gitmodules, mono/mini/mini-arm-tls.S, mono/mini/mini-arm64-gsharedvt.c, mono/mini/mini-exceptions-native-unwinder.c, mono/mini/tramp-arm64-gsharedvt.c
These changes are required so it builds again after the recent OSSing of various parts.
=> Fix monodroid build

mono/metadata/appdomain.c, mono/metadata/attach.c, mono/metadata/gc.c, mono/metadata/sgen-mono.c, mono/metadata/threadpool-ms.c, mono/metadata/threads.c, mono/mini/aot-compiler.c, mono/mini/debugger-agent.c, mono/mini/driver.c, mono/mini/mini-posix.c, mono/mini/mini-runtime.c, mono/profiler/decode.c, mono/profiler/proflog.c, mono/utils/mono-threads-posix.c, mono/utils/mono-threads.h
=> Bunch of improvements surrounding thread names and reporting of such to the profiler

mono/profiler/proflog.c
We would previously constantly try to dequeue from the writer queue which would
result in extremely high CPU usage, making many apps (e.g. Xamarin Studio)
nearly unusable.
=> [profiler] Use a semaphore to signal the writer thread.

man/mono.1, mono/mini/Makefile.am.in, mono/mini/cfgdump.c, mono/mini/cfgdump.h, mono/mini/mini-codegen.c, mono/mini/mini.c, mono/mini/mini.h, msvc/libmono.vcxproj
related doc PR: https://github.com/mono/website/pull/189
=> [jit] mini IR dumping feature for IGV

mono/utils/lock-free-queue.c
Found using gcc -fsanitize=bounds
=> Remove an undefined behavior

mono/metadata/method-builder.c, mono/metadata/reflection.c, mono/mini/tramp-arm64.c
I saw these while working on fixing up maccore after the recent mono-extension changes.
=> A few small fixes for maccore

mcs/class/System/System.IO/KeventWatcher.cs
Instead of opening a file for the sole purpose of calling
F_GETPATH on the resulting descriptor, we can just use the
native realpath() function; as a side benefit, this also works
on *BSD where F_GETPATH isn't supported.
=> use native realpath() function

mono/metadata/class.c, mono/tests/Makefile.am, mono/tests/bug-29585.cs
=> Fix #29585.

mono/mini/genmdesc.c
https://github.com/mono/mono/pull/2855
=> Backport PR-2855 memory leak fix to 4.4 branch

configure.ac
Stop hardcoding libc and linbintl versions.
Add support for libsqlite and libsqlite3.
=> Improve NetBSD target handling in ./configure

mono/metadata/marshal.c
The marshal code was using CEE_STIND_I for a lot of ref stores. This would not
generate a WB and is a heap corruption vector.
=> [marshal] Ensure marshal code emit the right indirect store when dealing with ref types.

mono/metadata/marshal.c, mono/mini/mini-codegen.c
=> Random mini stuff

mono/metadata/sgen-bridge.c, mono/tests/Makefile.am, mono/tests/sgen-bridge-gchandle.cs
The bridge code was triggering handles to be considered deallocated thus leading
them to be overwritten.
=> [sgen] Add regression test for the interaction between the bridge and handles.

mono/mini/aot-compiler.c
When running basic make check in mono/mini there are some hidden errors in the check-seq-points test. Current test compares output between JIT and AOT compile assemblies but doesn't pay attention to the result of the as and ld calls building the AOT:ed modules.
It turns out that the linkage of the AOT compiled module on win32 x86 actually fails due to naming of symbols included in .def or .globl assembler expressions. The fix makes sure that local function symbols or global symbol definitions follows the cdecl win32 x86 convention and are prefixed with _.
The fix tries to resolve this using two different strategies. Since there are many code paths in the AOT compiler emitting local/global symbols + referencing the emitted symbols, it doesn't look like there is one place to fix this …
=> Windows 32-bit x86 AOT assembler didn't compile due to incorrect symbol mangling.

mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLiteConvert.cs
Fixes that dates written from System.Data.Sqlite could not be read on Mono!
=> Bugfix DateTime in Sqlite: https://bugzilla.xamarin.com/show_bug.cgi?id=40603

mono/mini/method-to-ir.c
The following test would trigger a SIGSEGV during a GC collection:
```
object _Lock;
C5.HashedLinkedList<byte[]> _Set;
List<byte[]> _Candidates;
void Run ()
{
_Lock = new object ();
_Set = new C5.HashedLinkedList<byte[]>(new Core.CommonUtils.ByteArrayComparer());
BuildList ();
for (var i = 0; i < 10; ++i) {
Task.Run (() => WorkOnSet ());
}
}
void BuildList() {
_Candidates = new List<byte[]>();
Random r = new Random();
for(var i = 0; i < 20; ++i) {
var key = new byte[16];
r.NextBytes(key);
_Candidates.Add(key);
}
}
void WorkOnSet() {
Random r = new Random();
for (;;) {
byte[] src = _Candidates [r.Next (_Candidates.Count)];
byte[] key = new byte[src.Length];
for (int i = 0; i < src.Length; ++i)
key [i] = src [i];
lock(_Lock) {
if(r.Next (2) != 0)
_Set.Add(key);
else
_Set.Remove(key);
}
}
} …
```
=> [mini] Add missing gsharedvt write barrier

mcs/class/System/System.Diagnostics/Process.cs, mcs/class/System/Test/System.Diagnostics/ProcessTest.cs, mono/io-layer/handles.c, mono/io-layer/io.c, mono/io-layer/processes.c, mono/tests/Makefile.am, mono/tests/process-leak.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=40643
=> [Process] Fix Process.Start handle leak

mcs/class/corlib/Test/System.IO/FileInfoTest.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
Fixes [#40642](https://bugzilla.xamarin.com/show_bug.cgi?id=40624).
=> Fix two corlib test issues on mobile

mono/mini/mini-runtime.c
Previously we had separate codepaths in mono_jit_thread_attach for coop
and non-coop modes.
Now there's a common codepath for attaching the thread, and separate
code paths for performing coop state machine transitions and computing
the return value cookie.
Fixes Mono.Debugger.Soft tests under coop.
=> [runtime] Unify codepath in mono_jit_thread_attach

mono/metadata/threads.c
If there's a pending exception and an AbortRequested, the pending
excpetion should be thrown.
This fixes threadpool-exceptions5.cs in coop mode.
There are two situations where this could happen.
1. Like threadpool-exception5.cs we have a threadpool worker thread
request an abort and then its async callback runs and throws an
exception.  In this case apparently the async callback's exception
should be allowed to unwind and hit the unhandled exception handler.
2. A thread catches ThreadAbortException and then throws some other
excpetion from the catch clause.  In this case we unwind that other
exception, and when it's caught we rethrow the abort.
=> [runtime] Pending exception takes precedence over Thread.Abort ()

mcs/class/corlib/System.Threading/Monitor.cs, mcs/class/corlib/Test/System.Threading/MonitorTest.cs, mcs/class/corlib/corlib.dll.sources, mcs/class/referencesource/mscorlib/system/threading/monitor.cs, mono/metadata/icall-def.h, mono/metadata/marshal.c, mono/metadata/monitor.c, mono/metadata/monitor.h, mono/mini/method-to-ir.c
=> [corlib] Import System.Threading.Monitor

mcs/class/Microsoft.Web.Infrastructure/Microsoft.Web.Infrastructure-net_4_x.csproj, mcs/class/System.Design/Makefile, mcs/class/System.Design/System.Design-net_4_x.csproj, mcs/class/System.Web.Http.WebHost/System.Web.Http.WebHost-net_4_x.csproj, mcs/class/System.Web.Mvc3/System.Web.Mvc3-net_4_x.csproj, mcs/class/System.Web.Services/Makefile, mcs/class/System.Web.Services/System.Web.Services-net_4_x.csproj, mcs/class/System.Web.WebPages.Deployment/System.Web.WebPages.Deployment-net_4_x.csproj, mcs/class/System.Web.WebPages/System.Web.WebPages-net_4_x.csproj, mcs/class/System.Web/System.Web-net_4_x.csproj, msvc/scripts/genproj.cs, msvc/scripts/net_4_x.sln, msvc/scripts/order.xml
The rest is auto-generated noise, you can ignore.
=> [WIP] Important change: more comprehensive Makefile to support csproj-local on System.Design

mono/metadata/appdomain.c, mono/metadata/icall.c, mono/metadata/marshal.c, mono/metadata/marshal.h, mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/object.h, mono/metadata/remoting.c, mono/metadata/threadpool-ms.c, mono/mini/debugger-agent.c, mono/mini/jit-icalls.c, mono/mini/jit-icalls.h, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c, mono/mini/mini.c
As well as several other functions in `object.c`
=> [runtime] MonoError for mono_message_init

mono/metadata/monitor.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/metadata/threads.h, mono/mini/debugger-agent.c
Reverts mono/mono#3025
@akoeplinger mentioned it regressed BCL tests.
=> Revert "[coop] Remove mono_raise_exception from threads.c"

mcs/class/Microsoft.Build.Engine/Microsoft.Build.BuildEngine/Project.cs, mcs/class/Microsoft.Build.Tasks/Microsoft.Build.Tasks/ResolveAssemblyReference.cs, mcs/tools/xbuild/data/14.0/Microsoft.Common.targets, mcs/tools/xbuild/data/14.0/Microsoft.Common.tasks
=> [4.4] Various xbuild 14.0 fixes 

mono/metadata/gc.c
Ship them off to unhandled exception handling instead.
=> [runtime] Don't raise MonoErrors in mono_gc_run-finalize

mcs/class/WindowsBase/Makefile, mcs/class/WindowsBase/Test/System.IO.Packaging/PackageTest.cs, mcs/class/WindowsBase/ZipSharp/ZipFileInfo.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=41157
=> [WindowsBase] Fixed System.IO.Packaging creating Zip archive with wrong date time entries

tools/offsets-tool/Makefile
This is a backport of PR #3058.
This PR depends on #3064 to be merged first.
=> [offsets-tool] Use git protocol instead of ssh to allow anonymous access.

mcs/class/System.IO.Compression.FileSystem/Test/System.IO.Compression.FileSystem/ZipTest.cs, mcs/class/System.IO.Compression.FileSystem/ZipFileExtensions.cs, mcs/class/System.IO.Compression/SharpCompress/Archive/Zip/ZipWritableArchiveEntry.cs, mcs/class/System.IO.Compression/Test/System.IO.Compression/ZipTest.cs
=> [System.IO.Compression/.Filesystem] Fixed handling of date/time for Zip entries

mono/mini/aot-compiler.c
I had a look in vtunes for
```
$ mono/mini/mono-sgen --stats -O=all --aot=threads=1,asmonly ~/work/benchmarker/tests/fsharp/lib/bootstrap/4.0/FSharp.Compiler.dll
```
and that method showed up as hot.
With this change I get an improvement from ~27.4s down to ~24.3s on my
machine.
@vargaz: what do you think?
=> [aot] use hashtable for caching typespec of classes

mcs/class/System/Test/System.Net.Sockets/SocketTest.cs
SendAsyncFile uses StartSocketServer to start a server and at the same
time begins to accept a client socket. The issue is that when
the accept callback is called SendAsyncFile already closed the socket.
Fixed race condition by moving StartSocketServer and ReceiveCallback
logic into SendAsyncFile, and by using a new MRE to ensure that the
client receives all the data before the server is closed.
Fixes [#41264](https://bugzilla.xamarin.com/show_bug.cgi?id=41264)
=> [System] Fixes socket async exception.

mcs/class/System/System.Net/EndPointListener.cs
This fixes a regression introduced in 123aaa5db07fe464d12ea178ecc3f27990cc1a72. We would sometimes see an ObjectDisposedException when calling AcceptAsync () because that patch removed the try-catch around it.
=> [bcl] Avoid ObjectDisposedException in EndPointListener.

mcs/class/System/mobile_System.dll.sources
=> [System] Add back IWebProxyScript to the mobile profile.

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
Backport https://github.com/mono/mono/pull/3040 to 4.5.1
=> Debugger step recursive 4.5.1

mono/metadata/handle.c, mono/metadata/handle.h, mono/metadata/object-internals.h, mono/metadata/sgen-mono.c, mono/sgen/sgen-gc.c, mono/unit-tests/test-mono-handle.c, mono/utils/mono-error-internals.h, mono/utils/mono-threads.h
This is the local handles API I think we should be using. It addresses
issues from the current implementation and actually make it work.
=> Local handles initial drop

mcs/build/rules.make, mono/mini/aot-compiler.c
We need to increase this value on mobile_static in order to run the test suite.
=> [runtime][mobile_static] Add flag for rgctx_fetch_trampolines and use it

mcs/class/System/Test/System.Timers/TimerTest.cs
We were seeing intermittent failures on devices like:
```
[FAIL] TimerTest.EnabledInElapsed :   #1 loss of events
Expected: True
But was:  False
at MonoTests.System.Timers.TimerTest.EnabledInElapsed () <0x33b168 + 0x0014f> in <filename unknown>:0
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object , BindingFlags , System.Reflection.Binder , System.Object[] , System.Globalization.CultureInfo ) <0x66d400 + 0x000b7> in <filename unknown>:0
```
Since OS scheduling and GCs can influence the exact timing of the timer intervals sleeping for 200ms is likely just to short.
Instead of bumping the timeout, I decided to rewrite the test to not rely on …
=> [System] Make TimerTest.EnabledInElapsed more reliable

mcs/class/System/System.Net.Sockets/Socket.cs, mcs/class/System/Test/System.Net.Sockets/SocketAsyncTest.cs, mcs/class/corlib/System/Environment.cs, mono/metadata/appdomain.c, mono/metadata/socket-io.c, mono/metadata/socket-io.h
Fixes 3 of the 4 socket failures that we're currently seeing on Android.
=> Fix a few socket test failures on Android

mono/metadata/sgen-mono.c
We were not exiting the critical section on this code path. This was leading to hangs at stw since the native code would take locks when compiling the code.
=> [sgen] Exit the critical section also on the slowpath of managed allocators

mcs/class/System/Test/System.Net/HttpListenerRequestTest.cs
We're seeing the following exception on devices in CI:
```
[FAIL] HttpListenerRequestTest.HttpRequestIsLocal : System.Net.Sockets.SocketException : Could not resolve host 'XQA-AppleTV-1'
at System.Net.Dns.Error_11001 (System.String hostName) [0x00000] in /Users/builder/data/lanes/1381/d8287824/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/System/System.Net/Dns.cs:292
at System.Net.Dns.GetHostByName (System.String hostName) [0x00024] in /Users/builder/data/lanes/1381/d8287824/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/System/System.Net/Dns.cs:419
at System.Net.Dns.GetHostEntry (System.String hostNameOrAddress) [0x00061] in …
```
=> [System] Fix HttpListenerRequestTest.HttpRequestIsLocal intermittently failing

mono/metadata/monitor.c
Just return that you couldn't enter the monitor and let the slow path handle it.
Fixes [#41705](https://bugzilla.xamarin.com/show_bug.cgi?id=41705)
=> [runtime] Don't raise ArgumentNullException in mono_monitor_enter_fast

mcs/build/profiles/mobile_static.make
=> [mobile_static] Skip PKITS tests on mobile_static due to missing

mono/utils/mono-time.c
Should fix https://bugzilla.xamarin.com/show_bug.cgi?id=41786
/cc @rolfbjarne
=> [utils] Work around CLOCK_MONOTONIC being defined on macOS 10.12 SDK despite targeting earlier releases

mcs/tools/security/mozroots.cs
MXR is not coming back (see https://bugzilla.mozilla.org/show_bug.cgi?id=1279952 and SuaveIO/mono-script-buildpack#9 (comment)) and this broke everyone who still relied on mozroots. Fix by using the version from the hg repository instead.
Starting from Mono 3.12 we've been shipping cert-sync to import CA certificates from the local computer trust store to Mono's trust store, we strongly encourage everyone to move to that instead. Added a deprecation warning to mozroots to further strengthen this message.
Note that when fetching the CA list over the new https URL we need to skip cert validation errors, as the common use case for mozroots is when no certs are present on the system (bootstrapping). This enables MITM but we don't really have any other options. Another reason why cert-sync is …
=> [tools] Fix mozroots URL for Mozilla's certdata.txt and add deprecation warning

man/mono.1, mono/sgen/sgen-gc.h, mono/utils/Makefile.am, mono/utils/mono-log-common.c, mono/utils/mono-log-posix.c, mono/utils/mono-log-windows.c, mono/utils/mono-logger.c, mono/utils/mono-logger.h, mono/utils/mono-threads.c, msvc/libmonoutils.vcxproj
=> Enhanced logging - attempt 2.5

mcs/class/System/Mono.Net.Security/MonoSslStreamImpl.cs
=> [4.4] Fix recursive property call in MonoSslStreamImpl

mono/sgen/sgen-marksweep.c
=> [sgen] Use sgen_qsort instead of qsort

mcs/tools/security/mozroots.cs
Backport of https://github.com/mono/mono/pull/3188 for C7SR1
=> [4.4] [tools] Fix mozroots URL for Mozilla's certdata.txt and add deprecation warning

mono/profiler/Makefile.am
**Please do not merge yet, even if green.**
=> Revert changes to profiler library linking

mono/mini/debugger-agent.c
=> Restore debugger step-over NULL check 4.5.1

mcs/class/System/Test/System.Timers/TimerTest.cs
Backport of #3122 to the 4.4 branch.
=> [4.4][System] Make TimerTest.EnabledInElapsed more reliable

mcs/class/System/System.Net.Sockets/Socket.cs, mcs/class/System/Test/System.Net.Sockets/SocketTest.cs
=> [C7][System] Fixes ConnectAsync UnhandledEx

mcs/class/System.IO.Compression/SharpCompress/Archive/AbstractWritableArchive.cs, mcs/class/System.IO.Compression/SharpCompress/Archive/Zip/ZipArchiveEntry.cs, mcs/class/System.IO.Compression/SharpCompress/IO/ReadOnlySubStream.cs, mcs/class/System.IO.Compression/Test/System.IO.Compression/ZipTest.cs, mcs/class/System.IO.Compression/ZipArchive.cs, mcs/class/System.IO.Compression/ZipArchiveEntry.cs
=> [C7] [System.IO.Compression] Backporting of Zip fixes

man/mono.1, mcs/tools/mono-symbolicate/Makefile, mono/mini/aot-compiler.c, mono/mini/mini-runtime.c, mono/mini/mini.c, mono/mini/mini.h, mono/mini/test_op_il_seq_point.sh
=> [C8][runtime] Enable compact seq point by default

mcs/class/System.Web.Services/System.Web.Services.Protocols/Methods.cs, mcs/class/System.Web.Services/Test/System.Web.Services.Protocols/SoapHttpClientProtocolTest.cs
=> [C7][System.Web.Services] Fixes bad XmlMapping.Key

mcs/class/corlib/System/TimeZoneInfo.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
Fixes [#41349](https://bugzilla.xamarin.com/show_bug.cgi?id=41349)
=> [corlib] Implements TZI.IsDST(DateTimeOffset)

mcs/class/Microsoft.Build.Tasks/Microsoft.Build.Tasks/GetReferenceAssemblyPaths.cs, mcs/class/Microsoft.Build.Utilities/Mono.XBuild.Utilities/ReservedNameUtils.cs
Fix several xbuild bugs that prevented older PCL targets working correctly
=> [xbuild] Fix PCL build

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/metadata/threadpool-ms-io-epoll.c, mono/metadata/threadpool-ms-io-kqueue.c, mono/metadata/threadpool-ms-io-poll.c
Fixes [Bugzilla #42625](https://bugzilla.xamarin.com/show_bug.cgi?id=42625)
=> [threadpool-ms] Switch to GC Safe mode in event_wait backends

mcs/tools/mono-symbolicate/Makefile, mcs/tools/mono-symbolicate/Test/symbolicate.expected
Make all file locations in symbolicate.expected relative to mono
repository base directory.
=> [mono-symbolicate] Fixes symbolicate.expected

mono/io-layer/wait.c
Wait math must always subtract ticks and get deltas. That way we avoid overflows.
=> [wapi] Fix timed wait code to not overflow. Fixes #42688

mcs/class/System/System.Net/ResponseStream.cs
Fixes issues where ResponseStream.Close would throw an exception when
peer had already closed the connection and ResponseStream.Close would
still try to communicating to peer that it was closing.
The issue was brought to our attention by failures on:
- MonoTests.System.Net.WebRequestTest.TestReceiveCancelation
- MonoTests.System.Net.HttpWebRequestTest.TestLargeDataReading
=> [System] Fix RequestCanceled ex on ResponseStream.Close

mono/mini/aot-compiler.c
In order for our exception handling to work on linux, we need the
unwind-dw2-fde-dip implementation in libgcc to work with our
.o file. This requires that `--eh-frame-hdr` be passed by the linker.
By using clang++ as the linker, we will get this and other flags
necessary for correct interop with c++ libraries.
=> [mobile_static] Use clang++ for the linker

mcs/class/System/System.Net/ResponseStream.cs
Fixes issues where ResponseStream.Close would throw an exception when
peer had already closed the connection and ResponseStream.Close would
still try to communicating to peer that it was closing.
The issue was brought to our attention by failures on:
- MonoTests.System.Net.WebRequestTest.TestReceiveCancelation
- MonoTests.System.Net.HttpWebRequestTest.TestLargeDataReading
Master PR #3305
=> [C8][System] Fix RequestCanceled ex on ResponseStream.Close

mcs/class/Mono.Tasklets/Test/Mono.Tasklets/ContinuationsTest.cs, mono/mini/mini-runtime.c, mono/mini/tasklets.c, scripts/ci/run-test-default.sh
Follow up to pull request https://github.com/mono/mono/pull/3258
=> Added Mono.Tasklets test

mcs/class/Mono.Debugger.Soft/Makefile, mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs
Check that we can suspend I/O blocked threadpool workers in coop GC mode.
=> [debugger-agent] Regression test for #42625

mono/metadata/gc.c
=> [gc] Replace domain finalizer request cond+mutex by a semaphore

mono/metadata/object.c
This fixes a number of tests in System.Transactions for bitcode / co-op.
=> [runtime] Propagate async MonoError to AsyncResult

mono/metadata/threads.c
Fixes the weird Jenkins logs for the coop job.
=> [coop] Don't call unhandled exn hook for ThreadAbortException

libgc/os_dep.c, mono/io-layer/processes.h, mono/mini/exceptions-arm.c
See commit messages for details.
Closes #3212.
=> Fix Alpine build

mono/metadata/sgen-mono.c
Windows uses a guard page before the committed stack memory pages to detect when the stack needs to be grown. If we suspend a thread just after a function prolog has decremented the stack pointer to point into the guard page but before the thread has been able to read or write to that page, starting the stack scan at the thread's ESP/RSP will raise a STATUS_GUARD_PAGE_VIOLATION and the process will crash.
This patch uses VirtualQuery() to determine whether the thread's stack_start value points into the guard page. If it does the stack scan will instead be started at the following, non-guard page.
The sgen-weakref-stress.exe test triggered this bug in about 1 out of 100 runs.
=> Prevent SGen from scanning the guard page used by Windows to dynamically grow the stack

mono/metadata/gc.c
The crash would come from a use-after-free of stack memory: in coop_cond_timedwait_alertable, we would allocate the struct we pass to the mono_thread_info_install_interrupt function on the stack. But there is no guarantee as to when break_coop_alertable_wait is run. The fix is to allocate the data passed to mono_thread_info_install_interrupt on the heap, and free it in the callback, or if it hasn't been interrupted.
cc @vargaz
=> [gc] Fix crash when doing WaitForPendingFinalizers

mono/metadata/sre-encode.c
Followup for 6be008c409153a82e80394b98c93564e2cdb2309 to fix the s390x build.
=> [sre] Fix s390x build

mono/metadata/icall-def.h, mono/metadata/object-internals.h, mono/metadata/sre.c
There is no System.Refleciton.Emit.AssemblyBuilder::InternalAddModule method
=> [runtime] ves_icall_AssemblyBuilder_InternalAddModule is dead code

libgc/include/gc.h, mono/metadata/boehm-gc.c, mono/metadata/gc-internals.h, mono/metadata/gc.c, mono/metadata/jit-info.c, mono/metadata/mono-gc.h, mono/metadata/profiler-private.h, mono/metadata/profiler.c, mono/metadata/profiler.h, mono/metadata/sgen-mono.c, mono/metadata/sgen-stw.c, mono/profiler/decode.c, mono/profiler/proflog.c, mono/profiler/proflog.h, mono/profiler/utils.c, mono/unit-tests/test-mono-linked-list-set.c, mono/utils/hazard-pointer.c, mono/utils/hazard-pointer.h, mono/utils/lock-free-alloc.c, mono/utils/lock-free-queue.c, mono/utils/mono-conc-hashtable.c, mono/utils/mono-linked-list-set.c, mono/utils/mono-linked-list-set.h, mono/utils/mono-threads.c, mono/utils/mono-threads.h
Decided to combine my other PRs into one to avoid merge conflicts.
=> Even more profiler fixes/improvements

mcs/class/corlib/ReferenceSources/AppContextSwitches.cs, mcs/class/corlib/System.Globalization/CultureInfo.cs, mcs/class/corlib/System.Threading/Thread.cs, mcs/class/corlib/Test/System.Globalization/CultureInfoTest.cs, mcs/class/referencesource/mscorlib/system/threading/thread.cs
This is a breaking change behaviour introduced in .net 4.6.
More info at https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.currentculture(v=vs.110).aspx
=> [corlib] Flow CultureInfo from parent thread. Fixes #43193

mono/mini/aot-compiler.c
fixes regression introduced by 7d238ddd5edeeb42cec5e07b6d6527d16332f921
cc @alexanderkyte
=> [aot] fix linker invocation

mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/mini/mini-exceptions.c, mono/tests/Makefile.am, mono/tests/abort-cctor.cs
This fixes one of the sources of instability on jenkins.
=> [runtime] Don't abort .cctors. Fixes #43320

man/mprof-report.1
Also reformat some sections a bit.
=> [man] Update mprof-report.1 to cover new profiler options.

eglib/src/gmisc-win32.c
Relying on the HOMEDRIVE/HOMEPATH environment variables is fragile as those variables don't always have to be set. One such scenario is when running on a Jenkins slave. When not set g_get_home_dir() in eglib would return NULL which led to a crash in ves_icall_System_Environment_InternalGetHome().
This patch changes g_get_home_dir() to first try to call SHGetKnownFolderPath() to get the current user's profile directory (i.e. home dir). If that fails it falls back to the USERPROFILE environment variable. If that isn't available the function will fallback to the original behavior and try with HOMEDRIVE/HOMEPATH.
=> Prefer SHGetKnownFolderPath() in g_get_home_dir() over HOMEDRIVE/HOMEPATH environment variables

mono/metadata/threadpool-ms.c
Previous logic only ensured that domain->threadpool_jobs was 0.
There was a race condition as follows:
* worker jobs are queued into ThreadPoolDomain outstanding_request's
* domain unload starts
* domain->threadpool_jobs is 0 so unload proceeds
* queued jobs are processed from the ThreadPoolDomain outstanding_request's
* the domain can be set/entered by worker threads since
mono_domain_set only fails for domains with state of MONO_APPDOMAIN_UNLOADED,
while our domain is in the MONO_APPDOMAIN_UNLOADING state
* jobs are now being unexpectedly run in domain that is being shutdown
=> Avoid race condition between domain unload and threadpool.

mcs/class/corlib/System.Threading/Thread.cs, mono/metadata/appdomain.c, mono/metadata/attach.c, mono/metadata/object-internals.h, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/mini/aot-compiler.c, mono/mini/debugger-agent.c, mono/utils/mono-threads-posix.c, mono/utils/mono-threads-windows.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
=> [threads] Import mono_thread_info_set_priority

mono/mini/aot-compiler.c, mono/mini/driver.c
=> [hybrid-aot] Add runtime support

mcs/class/corlib/System/TimeZoneInfo.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
When passed a time within this period .NET's IsDaylightSavingTime() returns true while GetUtcOffset() returns the BaseUtcOffset without the DST delta added. This patch changes the behaviour in Mono to do what .NET does.
=> Replicate .NET's TimeZoneInfo.IsDaylightSavingTime() and GetUtcOffset() behaviour when passed times within the lost period at DST start

mcs/class/System/Test/System.Net/DnsTest.cs
Previously the tests were written so that some failures might occur on the
threadpool in methods that did not catch exceptions. In that case the process
would terminate due to an unhandled exception. So rewrite the tests to catch
exceptions in any code that doesn't run on the main thread, and forward those
exceptions to the main thread.
Also wait for async operations to complete on the main thread, and remove
asserts that are not supposed to be hit.
=> [System] Rewrite Dns tests so that failures don't cause the process to crash.

mcs/class/System.Data/Test/System.Data/DataTableReadWriteXmlTest.cs, mcs/class/System.Data/Test/System.Data/DataTableTest.cs, mcs/class/System.Data/Test/System.Xml/XmlDataDocumentTest.cs
To make them run successfully on Windows.
=> Fixes line ending issues in System.Data tests

mono/dis/main.c
monodis with coop enabled segfaulted in mono_thread_info_attach
=> [monodis] Don't segfault using cooperative GC.

mono/utils/mono-threads.c
This is important as platform unregister is where we signal the thread handle, and that should be done as late as possible, but still before we switch the thread state to DETACHED and remove it from the thread list.
The fact that we do under the suspend lock shouldn't be an issue as we shouldn't call in any other code than w32handle code.
=> [mono-threads] Move platform unregister after detach

mcs/class/System/ReferenceSources/Logging.cs, mcs/class/System/ReferenceSources/Socket.cs, mcs/class/System/System.Net.NetworkInformation/Ping.cs, mcs/class/System/System.Net.Sockets/Socket.cs, mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs, mcs/class/System/System.dll.sources, mcs/class/System/mobile_System.dll.sources, mcs/class/referencesource/System/net/System/Net/Sockets/Socket.cs, mono/metadata/socket-io.c
=> [referencesource] Import parts of System.Net.Sockets.Socket

mono/metadata/threads.c, mono/tests/Makefile.am, mono/tests/thread-native-exit.cs
=> [threads] Assert that every thread is detached when exiting

mcs/class/corlib/Mono/Runtime.cs
- Extends https://github.com/mono/mono/pull/3624
=> Add Mono.Runtime to XM 4.5 profile

mono/metadata/domain.c, mono/metadata/gc.c, mono/metadata/profiler.c
A couple that were missing in #3688.
=> Profiler fixes for Cycle 9 (#2)

mcs/class/System/Mono.Btls/MonoBtlsContext.cs, mcs/class/System/Mono.Btls/MonoBtlsKey.cs, mcs/class/System/Mono.Btls/MonoBtlsPkcs12.cs, mcs/class/System/Mono.Btls/MonoBtlsProvider.cs, mcs/class/System/Mono.Btls/MonoBtlsUtils.cs, mcs/class/System/Mono.Btls/MonoBtlsX509Name.cs, mcs/class/System/Mono.Btls/X509CertificateImplBtls.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X500DistinguishedName.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2Impl.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2ImplMono.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509Helper2.cs, mono/btls/btls-x509-name.c, mono/btls/btls-x509-name.h, scripts/ci/run-test-default.sh
Fully implement X509CertificateImplBtls and use .NET semantics in Import().
=> [BTLS]: Certificate cleanups and fixes.

mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs, mono/io-layer/processes.c
=> [System] Fix Process::Dispose resource leak due to RS import.

mcs/class/corlib/System.Globalization/CultureInfo.cs, mcs/class/corlib/System.Security.Cryptography/CryptoConfig.fullaot.cs, mcs/class/corlib/System.Security.Cryptography/RNGCryptoServiceProvider.cs, mcs/class/corlib/System/AppDomain.cs, mcs/class/referencesource/mscorlib/system/globalization/compareinfo.cs, mcs/class/referencesource/mscorlib/system/runtime/interopservices/runtimeenvironment.cs, mcs/class/referencesource/mscorlib/system/security/cryptography/rc2cryptoserviceprovider.cs, mcs/class/referencesource/mscorlib/system/security/cryptography/rfc2898derivebytes.cs, mcs/tools/commoncryptogenerator/CommonCryptorGenerator.cs, mcs/tools/commoncryptogenerator/generator.cs
See https://github.com/dotnet/standard/issues/47.
=> [bcl] Expose a few more APIs on mobile to match with netstandard

mono/btls/btls-x509.c
In mono_btls_x509_get_serial_number(), first call i2c_ASN1_INTEGER()
which takes care of padding and computing the 2s complement for negative
numbers, then reverse the buffer.
=> [BTLS]: Correctly handle certificates with negative serial numbers.

mcs/class/corlib/Test/System.Runtime.CompilerServices/RuntimeHelpersTest.cs, mono/metadata/appdomain.c, mono/metadata/attach.c, mono/metadata/icall.c, mono/metadata/threads.c, mono/mini/aot-compiler.c, mono/mini/debugger-agent.c, mono/utils/mono-threads-posix.c, mono/utils/mono-threads-windows.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
@ludovic-henry @vargaz please review
=> [mono] Fixes hardcoded stack limit in EnsureSufficientExecutionStack check

mcs/class/referencesource/System/services/monitoring/system/diagnosticts/AsyncStreamReader.cs
This round ensures stream and decoder are protected from dispose and that we properly
bail out to the EOS case.
=> [System] Another round of hardening around disposal of Process while doing async reads.

mcs/class/System.Windows.Forms/System.Windows.Forms/ListView.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/ListViewTest.cs
Fixes two issues when adding/removing items in a winforms ListView. See the commit messages for more information.
=> [MWF] Fix two issues in ListView

mono/metadata/class-internals.h, mono/metadata/verify.h, mono/mini/method-to-ir.c, mono/mini/mini.h
Some strong types that make it nicer to see variables in the debugger, plus
some inline API docs.
=> [mono] Add some strong types for a few variables, document some methods

man/mkbundle.1, mcs/tools/mkbundle/Makefile, mcs/tools/mkbundle/mkbundle.cs, mono/metadata/assembly.c, mono/metadata/assembly.h
Make mkbundle use SDKs instead of a single runtime for cross compilation
=> Mkbundle zips

mono/mini/mini-darwin.c, mono/mini/tramp-amd64.c, mono/utils/mach-support-amd64.c, mono/utils/mach-support-x86.c, mono/utils/mach-support.h, mono/utils/mono-context.c, mono/utils/mono-context.h, mono/utils/mono-sigcontext.h, mono/utils/mono-threads-mach.c
Testing the Mac parts of #3364 in isolation.
=> [wip] [runtime] Fix scanning of SIMD registers on Mac.

mcs/class/corlib/System.Runtime.InteropServices/Marshal.cs
https://github.com/dotnet/standard/issues/94
=> [corlib] Add Marshal.CleanupUnusedObjectsInCurrentContext() stub

tools/offsets-tool/Makefile, tools/offsets-tool/MonoAotOffsetsDumper.cs
This is a pre-requisite to getting the tool to run on Linux host, as requested by Android team.
=> Updated offsets tool to latest CppSharp.

mono/mini/mini-arm64.c
otherwise we still have the theoretical chance of a race. this code isn't really perf-critical, so it should be fine.
worth a try in order to fix https://bugzilla.xamarin.com/show_bug.cgi?id=45609
cc @kumpera
=> [arm64] always assume a cache line size of 4

mono/mini/mini-arm64.c
backport of https://github.com/mono/mono/pull/3928
=> [C9][arm64] always assume a cache line size of 4

scripts/ci/run-jenkins.sh
=> [ci] Reduce make parallelism on ppc64

mono/tests/Makefile.am, scripts/ci/run-test-default.sh
Until someone can investigate those we want to have a clean CI.
=> [ppc64] Disable a few runtime/bcl tests that currently fail

mono/metadata/w32process-unix.c
This reverts commit d6928839015effec6358d7bc9c7b1b547645140a.
=> Revert "[process] Allocate a handle even for non-child processes"

configure.ac
=> Revert "[runtime] Default mobile_static AOT type to FullAOT"

mono/metadata/sgen-mono.c, mono/mini/method-to-ir.c, mono/sgen/sgen-gc.h
Do not merge as it contains a commit that turns on canaries always (for running the test suite)
Missing a way to export this option to AOT images.
=> [sgen][DO NOT MERGE] nursery canaries + managed allocators

mono/metadata/w32process-unix.c, mono/mini/mini-llvm.c
Usage of g_slist_count and g_slist_nth are actually O(n) operations by themselves. Nesting them can prove to be CPU intensive.
=> [Perf] Replace some exhaustive O(n^3) or O(n^2) iterations with O(n)

mono/metadata/object-internals.h, mono/metadata/threads.c, mono/mini/mini-exceptions.c, mono/mini/mini.h, mono/tests/thread6.cs
Reading commit messages recommended.
=> Prevent ThreadAbort from prematurely ending function calls in catch block

mono/metadata/appdomain.c, mono/metadata/domain-internals.h, mono/metadata/object.c, mono/metadata/object.h, msvc/mono.def, msvc/monosgen.def
=> Revert "Only allocate 1 empty string instance per AppDomain "

mcs/class/corlib/Microsoft.Win32/Win32RegistryApi.cs
I used reference source as inspiration for the changes.
=> Fix a bug in registry API implementation where had wrong assumptions about possible registry size.

mcs/class/System.Runtime.InteropServices.RuntimeInformation/System.Runtime.InteropServices.RuntimeInformation-net_4_x.csproj, msvc/scripts/order.xml, net_4_x.sln
=> [msvc] Update csproj files

mcs/class/System/System.Net.Sockets/Socket.cs
=> Socket.AddSockets throw exception with meaningful name

mono/metadata/w32process-win32.c
Commit 07630fe8c5b73c5ed47038a8e63b098fbbea05ff broke the build on Windows.
=> Fix build failure in w32process-win32.c

configure.ac, mono/metadata/Makefile.am, mono/metadata/assembly.c, mono/metadata/assembly.h, mono/metadata/mono-config-dirs.c, mono/metadata/mono-config-dirs.h, mono/metadata/mono-config.c
=> [4.8] Handle relocatable libMonoPosixHelper.so when --libdir= isn't lib/

mono/mini/mini-llvm.c
An OBJC_IMAGE_INFO section must be emitted when we emit the native equivalent
of @selector for Selector.GetHandle, otherwise the Objective-C runtime will
not process the selectors in this image at runtime (and we may end up with
duplicate selectors in memory).
The AOT compiler already does this here: https://github.com/mono/mono/blob/2eda626316fd8f70cd98947af2f89b7ca9b0ebe5/mono/mini/aot-compiler.c#L9657-L9661
=> [llvm] Fix intrinsic Selector.GetHandle support.

configure.ac, mcs/build/profiles/basic.make
=> [configure] fix out-of-tree-build with roslyn

mcs/class/Facades/System.ValueTuple/AssemblyInfo.cs, mcs/class/Facades/System.ValueTuple/Makefile, mcs/class/Facades/System.ValueTuple/System.ValueTuple.dll.sources, mcs/class/Facades/System.ValueTuple/TypeForwarders.cs, mcs/class/Facades/subdirs.make
=> [Facades] Add System.ValueTuple facade

mono/mini/unwind.c
on arm32 it goes down from 5120 bytes to 676 bytes in terms of frame size.
/cc @vargaz
=> [unwind] reduce frame size of mono_unwind_frame ()

mono/mini/mini-exceptions.c
helps with analyzing crash reports
=> [exceptions] print process map when crashing on Android/Linux

mcs/class/System.IO.Compression/Test/System.IO.Compression/ZipTest.cs, mcs/class/System.IO.Compression/ZipArchive.cs
My attempt to fix: https://bugzilla.xamarin.com/show_bug.cgi?id=48516
=> Fix bug 48516

mono/mini/mini-exceptions.c
=> fix behaviour of crash handler

mcs/class/PEAPI/Metadata.cs, mcs/ilasm/parser/ILParser.jay, mcs/ilasm/scanner/ILTables.cs
I encountered an IL file with this, and it raised a syntax error. I figured it should be supported, but I’m not sure if this is complete or correct.
=> [ilasm] Support 'nooptimization' attribute.

mcs/class/System/System.Net.NetworkInformation/IPInterfaceProperties.cs
This change implements retrieving a list of DNS server addresses from Android
instead of attempting to parse `/etc/resolv.conf` which doesn't exist on
Android.
The list is retrieved by calling native function in Xamarin.Android that gets
the data from the system.
Part 2 of fix for https://bugzilla.xamarin.com/show_bug.cgi?id=48016
Xamarin.Android counterpart of the fix: https://github.com/xamarin/xamarin-android/commit/ab375abc69adc370a379232468879c3cafe0fe2a
=> [BCL,Android] Get DNS server addresses from Android

configure.ac, mono/mini/.gitignore, mono/mini/Makefile.am.in, mono/mini/driver.c, mono/mini/interpreter/embed.h, mono/mini/interpreter/hacks.h, mono/mini/interpreter/interp.c, mono/mini/interpreter/interp.h, mono/mini/interpreter/mintops.c, mono/mini/interpreter/mintops.def, mono/mini/interpreter/mintops.h, mono/mini/interpreter/transform.c, mono/mini/mini-runtime.c, mono/mini/mini.h, mono/mini/tramp-amd64.c, scripts/ci/run-jenkins.sh, scripts/ci/run-test-interpreter.sh
only executes a couple regression tests so far
=> reviving interpreter

mcs/class/corlib/System.Runtime.CompilerServices/ConditionalWeakTable.cs
Fixes leak from #47388 and improves ephemeron processing performance.
=> [corlib] Avoid unbounded resizes of ephemeron arrays

mono/mini/branch-opts.c
This PR is meant to fix the prev_bb quick lookup from mono_merge_basic_blocks(). For some reason it always tried the first predecessor instead of iterating through all of them.
=> [jit] Fix the prev_bb quick lookup in mono_merge_basic_blocks().

mono/metadata/image.c, tools/nuget-hash-extractor/Makefile, tools/nuget-hash-extractor/download.sh, tools/nuget-hash-extractor/nuget-hash-extractor.cs
This allows us to prioritize system libs over current-dir libs.
=> [runtime] Deny loading bad images.

mcs/tools/pdb2mdb/Driver.cs
Before when trying to convert an assembly that had a portable PDB instead of a native PDB alongside it we'd just crash in the Microsoft.Cci pdb reader.
We now check whether the symbol file is a portable PDB and exit gracefully with an error message and exit code 2 from the app.
Users which access the Converter class (like e.g. Xamarin Android [1]) directly can now catch the PortablePdbNotSupportedException to do custom logic.
[1] https://github.com/xamarin/xamarin-android/blob/15f7547fa673e02256a75910c60c5e13eb158d2b/src/Xamarin.Android.Build.Tasks/Tasks/ConvertDebuggingFiles.cs#L28
=> [pdb2mdb] Detect portable PDB and fail gracefully instead of crashing

mono/metadata/image.c
This fixed my recent breakage on windows.
=> Fix the windows build.

mono/metadata/threads.c, mono/utils/mono-threads-posix.c
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=51545
=> [threads] Fix crash on unknown policy

mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/tests/abort-cctor.cs
The timer test runs for thousands of times without the TAE failure.
=> [runtime] Latest attempt at the cctor abort race. All tests passing locally.

configure.ac
It crashes during build with roslyn on Jenkins.
=> Default powerpc to build with mcs

acceptance-tests/coreclr.mk
We can look into them when we have time, but for now let's just ensure no new failures sneak in.
=> [acceptance-tests] Baseline failing coreclr tests for now

mono/metadata/icall.c, mono/metadata/threads.c, mono/utils/mono-threads.c, mono/utils/os-event-unix.c, mono/utils/os-event-win32.c, mono/utils/os-event.h
=> Revert "[threads] Make OSEvent alertable to fix bug #51653"

mcs/class/corlib/Test/System.Threading/ThreadTest.cs, mono/metadata/appdomain.c, mono/metadata/attach.c, mono/metadata/gc.c, mono/metadata/threadpool-worker-default.c, mono/metadata/threadpool.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/mini/aot-compiler.c, mono/mini/debugger-agent.c
Fixes bug https://bugzilla.xamarin.com/show_bug.cgi?id=47221
=> [threads] Allow resetting the name of a threadpool thread

mcs/class/System/System.Diagnostics/Process.cs, mcs/class/System/Test/System.Diagnostics/ProcessTest.cs, mono/metadata/w32process-unix-osx.c
Fixes bug https://bugzilla.xamarin.com/show_bug.cgi?id=51561
=> [process] Improve error message for inaccessible process

man/mono.1, mono/mini/mini-exceptions.c, mono/mini/mini-runtime.c, mono/mini/mini.h
/cc @BrzVlad @vargaz @ludovic-henry
=> [exceptions] introduce suspend-on-native-crash

mono/utils/mono-threads-posix.c
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=51545
=> [4.8][threads] Fix crash on unknown policy

mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs
It might be possible that the callback modifies the current SocketAsyncResult via the Init method. We observe it with AcceptAsync with a ReceiveAsync in the callback.
=> [socket] Fix race on SocketAsyncResult

mcs/class/System/Test/System.Net.Sockets/SocketTest.cs, mono/metadata/w32error.h, mono/metadata/w32socket-unix.c
Fixes bug https://bugzilla.xamarin.com/show_bug.cgi?id=52549
=> [socket] Add EPROTOTYPE error case

mono/metadata/sgen-os-mach.c, mono/mini/mini-darwin.c, mono/utils/mach-support-amd64.c, mono/utils/mach-support-arm.c, mono/utils/mach-support-unknown.c, mono/utils/mach-support-x86.c, mono/utils/mach-support.h, mono/utils/mono-context.c, mono/utils/mono-context.h, mono/utils/mono-sigcontext.h, mono/utils/mono-threads-mach.c
PR’d to see what the buildbots say.
=> Backport Mac 64 SIMD fixes to 4.2

mono/sgen/sgen-workers.c
If we don't take the finished_lock when starting workers, the workers that we started could have already finished the work and switch to non-parallel context before we are even able to signal all of them.
=> [sgen] Lock around worker start, not only finishing

configure.ac, mono/mini/alias-analysis.c, mono/mini/liveness.c, mono/mini/method-to-ir.c, mono/mini/mini-arm64.c
This improves configure to work better with Android.
The AA bug affects KW_THREAD targets.
The LMF codegen issue is the only one that is important.
cc @BrzVlad @vargaz
=> Fix a few issues on Android

mcs/class/System/Test/System.Net/FtpWebRequestTest.cs
Even though I couldn't repro the bug I thought it'd still be a good idea to at least add some basic coverage with non-Latin chars.
=> [System] Add regression test for Bugzilla 10899

mono/metadata/assembly.c
In multiple occasions we had bugs due to framework_assemblies not being correctly sorted.
Instead of just fixing the ordering again, I'm moving it a hashtable so future generations won't have to fix this for System.SpaceTravel.dll.
=> [runtime] Fix assembly remapping by using a hashtable. Fixes #52846 and #52743

mono/metadata/object.c
The following can happen:
* Thread T1 starts initialization of C1
* Thread T2 starts initialization of C2
* T2 starts initialization of C1, it gets blocked on T1.
* T1 finishes initializing C1.
* T1 starts initialization of C3.
* T1 starts initialization of C2. It sees that T2 is
still blocked on T1, but its not actually blocked, since
C1 is finished. Still, we record that T1 is blocked.
* T3 starts initialization of C2, it gets into an infinite
loop in the while loop, since the blocked_thread_hash
now indicates that T1 and T2 are blocked on each other.
The solution is to not mark a thread as blocked, if its waiting
for a thread which is waiting on a finished lock. Fixes hangs
when running csc.
=> [runtime] Fix an infinite loop in the runtime class init code.

mono/metadata/loader.c
It's possible for two threads to modify the same MonoMethodPInvoke.addr
in mono_lookup_pinvoke_call, with one thread setting it to NULL inside the
loop, and the other thread having completed the loop and expecting it to
be non-NULL.
Use an intermediate variable to prevent addr becoming non-NULL.
=> [metadata] Fix a possible crash when looking up a p/invoke function.

mcs/tools/security/cert-sync.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=53015
=> [cert-sync] Don't import into BTLS store if BTLS is not available

mono/utils/mono-threads-posix-signals.c
Android on 32bits arm shipped broken headers that made sigset_t be 32 bits instead of 64.
This means that it's not possible to use signals whose value are >= 32. The default implementation
uses RT signals when available (and they are on Android). But RT signals don't work as expected
as their value is >= 32.
This fix hardcodes some safe signals on Android and add asserts about their values to avoid regressions.
See 5005c6f3fbc1da584c6a550281689cc23f59fe6d for more details.
=> [runtime] Make sure we use lower numbered signals on Android.

mcs/class/referencesource/System.Data/System/Data/Common/AdapterUtil.cs
A small fix for AdapterUtil.cs 😢
Fixed my integration tests and Bug-52795 Infinite loop on MySqlDataReader.ReadAsync()
=> Wrong value for s_falseTask

docs/sources/mono-api-internal.html, docs/sources/mono-api-jitinternal.html, docs/sources/mono-api-metadata.html, mono/metadata/metadata.h
Most of these were already “internal”.
=> Remove dead APIs

configure.ac, scripts/ci/run-jenkins.sh
=> [configure] rename "--with-interpreter=yes" to "--enable-interpreter"

mcs/tools/mdb2ppdb/Makefile
@vargaz Marek told me he doesn't want it installed so let's not install it by default 😄
=> [tools] Don't install mdb2ppdb by default

mono/mini/mini-amd64.h
It lacks _In_reads_ and _Inout_.
=> [amd64] Fix mingw-w64 build.

.gitmodules, mcs/build/library.make, mcs/build/tests.make, mcs/class/System.Numerics/Makefile, mcs/class/System.Numerics/System.Numerics_xtest.dll.sources, mcs/class/Xunit.NetCore.Extensions/Makefile, mcs/class/Xunit.NetCore.Extensions/Microsoft.Xunit.Performance/BenchmarkAttribute.cs, mcs/class/Xunit.NetCore.Extensions/Microsoft.Xunit.Performance/BenchmarkDiscover.cs, mcs/class/Xunit.NetCore.Extensions/Xunit.NetCore.Extensions.dll.sources
It's should fail due to runtime bugs
=> [System.Numerics] xunit tests

mono/metadata/debug-helpers.c, mono/metadata/metadata-internals.h, mono/mini/aot-compiler.c
Split off to make other PR smaller. 
Got the merge confirmation already.
=> [runtime] Finish the AOT mangler

mcs/class/System/System.Net/ListenerPrefix.cs
Fix Bug #40969
https://bugzilla.xamarin.com/show_bug.cgi?id=40969
=> Fix Bug #40969

mono/metadata/class.c
This would have helped with debugging an issue we saw on Android.
=> Improve "Could not resolve type with token" exception message

mono/mini/interp/interp.c, mono/mini/tramp-amd64.c, mono/tests/Makefile.am
=> [interp] enable more tests for CI and some small fixes

mcs/class/System/Test/System.Diagnostics/ProcessTest.cs
This fixes bug https://bugzilla.xamarin.com/show_bug.cgi?id=53881
=> [2017-02][process] Disable tests that do not work on mobile

mcs/class/System.Web/System.Web.Hosting/HostingEnvironment.cs, mcs/class/System.Web/System.Web.dll.sources
This allows the Azure Functions Host to run unmodified.
=> [System.Web] Implement HostingEnvironment.QueueBackgroundWorkItem

mono/metadata/class.c, mono/mini/method-to-ir.c, mono/mini/mini-generic-sharing.c
…ere the default method is used.
=> [runtime] Default Interface Method support

mono/mini/TestHelpers.cs, mono/sgen/sgen-gc.c, mono/tests/Makefile.am, mono/tests/sgen-oom-bridge-major-fragmentation.cs, mono/tests/sgen-oom-cementing-stress.cs, mono/tests/sgen-oom-new-threads-dont-join-stw-2.cs, mono/utils/atomic.h, mono/utils/mono-mmap-internals.h, mono/utils/mono-mmap-windows.c, mono/utils/mono-mmap.c, mono/utils/mono-mmap.h
Not included as part of default testing yet as it has 100% failure rate.
=> [sgen] OOM testing

mcs/build/rules.make, mcs/class/reference-assemblies/Makefile, mcs/mcs/ikvm.cs, mcs/tools/xbuild/frameworks/net_4.5.1.xml, mcs/tools/xbuild/frameworks/net_4.5.2.xml, mcs/tools/xbuild/frameworks/net_4.6.1.xml, mcs/tools/xbuild/frameworks/net_4.6.2.xml, mcs/tools/xbuild/frameworks/net_4.6.xml
=> [2017-02] Backport new reference assemblies

mcs/class/System/Test/System.Diagnostics/ProcessTest.cs, mcs/class/System/Test/System.Net/DnsTest.cs, mono/metadata/w32file-unix.c, mono/metadata/w32process-unix-default.c, mono/metadata/w32process-unix-osx.c, mono/metadata/w32process-unix.c, mono/utils/mono-os-mutex.h
=> Fix Android compilation and some tests

mcs/build/gensources.sh
This has bitten us a bunch of times now so let's make sure it doesn't happen again.
=> [bcl] Add check for newline to gensources.sh

configure.ac, mono/mini/aot-compiler.c
=> LLVM Orbis support

mono/metadata/marshal.c
The code was bailing straight to native which is significantly slower. This is the result of roslyn compiling corlib on my machine:
Before:
real	0m5.757s
user	0m22.059s
sys	0m1.736s
After:
real	0m5.816s
user	0m23.623s
sys	0m1.693s
=> [runtime] Fix get_virtual_stelemref_wrapper STELEMREF_CLASS case to actually do the base class check.

mcs/class/System/System.Net/WebConnection.cs, mcs/class/System/System.Net/WebConnectionStream.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=54526
=> [WebConnection] Fix race condition between Close and BeginWrite

mcs/class/System/System.Net/WebConnection.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=54526
=> [2017-02][WebConnection] Fix race condition between Close and BeginWrite

mono/mini/debugger-agent.c
This "backport" of https://github.com/mono/mono/pull/4688
=> Bug 55148 - Debugger checks type which is possibly never used

mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLiteConnection.cs
Most likely a bug. Otherwise while loop should be replaced with if statement.
=> Place break inside if block

mcs/class/System/System.Net/WebConnection.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=54526
=> [2017-04][WebConnection] Fix race condition between Close and BeginWrite

mcs/class/corlib/System.Reflection.Emit/ModuleBuilder.cs, mcs/class/corlib/System.Reflection.Emit/TypeBuilder.cs, mcs/class/corlib/Test/System.Reflection.Emit/TypeBuilderTest.cs, mono/metadata/object-internals.h, mono/metadata/sre.c
- rebase of 2017-02 PR onto master
=> [runtime] Fix circular types in SRE

mcs/class/referencesource/System/net/System/Net/webproxy.cs
Should not throw PlatformNotSupportedException
=> Minor orbis fix in System.Net

mono/metadata/boehm-gc.c, mono/metadata/gc-internals.h, mono/metadata/marshal.c, mono/metadata/null-gc.c, mono/metadata/sgen-mono.c, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c, mono/sgen/sgen-cardtable.c, mono/sgen/sgen-gc.c, mono/sgen/sgen-gc.h
Improve array stores a bit and do a big rework of the VT WB.
=> [JIT] Last two optimizations to Roslyn.

mono/metadata/mono-security.c, mono/metadata/w32socket.c
* Some platforms don't support these features, so guard them.
* For platforms that do support them, no changes should occur.
=> Add #ifdef checks for code that might not exist

mcs/class/System.Net.Http/CFContentStream.cs
Some network errors in iOS are exposed as Stream errors, specially those
related with the lost of the connection. This patch ensures that if such
an issue happens an exception is raised in the async read task.
Fixes bug https://bugzilla.xamarin.com/show_bug.cgi?id=53792
=> Ensure that when an async read is performed on a response content the errors are correctly dealt with.

mcs/tools/mkbundle/mkbundle.cs
monodroid used to build its own version of mkbundle since it
requires slightly different code than the desktop. This
logic was protected in a #if block. Now that monodroid is
trying to make use of the shipped mkbundle rather than use
its own we need to turn this logic on at runtime.
A new parameter has been added
--bundled-header
When this option is passed, the code which skips including
mono/metadata/mono-config.h
will be skipped in favour of defining the required structures
and entry points directly.
=> [mkbundle] Add support for generating monodroid compatible mkbundle code at runtime

mono/mini/mini-runtime.c
Hello,
This fixes two memory leaks in mono_tramp_info_register().
- One issue is related to the fact that the `tramp_infos` list was perpetually growing with addition of every trampoline, even though it isn't used anywhere after `mini_init()`. This is solved by only adding trampolines to the list that are created before the root domain has been fully initialised.
- Another leaky behaviour has to do with MonoTrampInfo not being freed upon domain destruction. This is solved by allocating that structure in the domain's memory pool if the domain has already been initialised.
=> [jit] Fix memory leak in trampoline info registration.

mcs/class/System/Mono.Net.Security/MonoTlsProviderFactory.cs
(cherry picked from commit 9667aa6485bfc59ba257e9fb73f5e2cfbc9a2e50)
=> [System]: Fix default TLS provider. (#4797)

mcs/tools/xbuild/Makefile
(cherry picked from commit 8077ff5da774bb771c896d6fdb40740f649975af)
=> [2017-02][xbuild] Add web targets for 15.0 (#4868)

mono/metadata/handle.c, mono/metadata/handle.h, mono/metadata/marshal.c
When `MONO_HANDLE_TRACK_SP` is defined, each handle records the native C stack pointer
at the time of its nearest enclosing `HANDLE_FUNCTION_ENTER`.  If a subsequent
handle is allocated with a lower stack pointer (in memory; ie higher in the
call tree) then a `HANDLE_FUNCTION_RETURN` is missing and we're leaking handles.
=> [coop handles] Add mechanism to track handle leaks

mono/mini/mini-posix.c
With this, `cd mono/profiler && make check` passes on WSL.
=> [profiler] Fall back to CLOCK_MONOTONIC if CLOCK_PROCESS_CPUTIME_ID results in EINVAL.

mcs/tools/mkbundle/mkbundle.cs
Helps user self service by providing a more detailed error message and diagnostics.
https://bugzilla.xamarin.com/show_bug.cgi?id=51650
=> Improve error messages to help users diagnose problems when using custom mode

mcs/class/corlib/System/TimeZoneInfo.cs
=> Bug #56499: unreadable /etc/localtime should not cause an exception

mono/mini/mini-arm.c
The thread coprocessor registers appear only in v7 specification.
=> [arm] Don't use fast tls on v5 arm

mono/mini/tramp-arm.c
didn't test on linux/armv7, so let's see what CI says before merging
=> [interp] iOS ABI fixes for icall trampoline on armv7

mono/mini/interp/interp.c, mono/mini/unaligned.cs
please have a look @kumpera, I'm not sure about that change in the test
=> [interp] fixes around unaligned.

mono/metadata/handle.c, mono/metadata/handle.h, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/w32event-unix.c, mono/metadata/w32event-win32.c, mono/metadata/w32event.h, mono/metadata/w32handle-namespace.c, mono/metadata/w32handle-namespace.h, mono/metadata/w32mutex-unix.c, mono/metadata/w32mutex-win32.c, mono/metadata/w32mutex.h, mono/metadata/w32socket.c, mono/metadata/w32socket.h
Mostly focusing on the win32 threading primitives
=> [coop handles] Another batch of icalls

mcs/class/corlib/Test/System.Threading/WaitHandleTest.cs, mono/metadata/w32event-unix.c, mono/metadata/w32handle.c, mono/metadata/w32handle.h, mono/metadata/w32mutex-unix.c, mono/metadata/w32semaphore-unix.c
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=57069
=> [w32handle] Fix deadlock on SignalAndWait

mcs/class/System.Drawing/System.Drawing/Image.cs
This is thought to be fixing https://bugzilla.novell.com/show_bug.cgi?id=406307.
v4: state that my changes are licensed under MIT X11 license
=> implement Image.SetPropertyItem() method v4

mono/mini/interp/interp.c
debugging `tests/finalizer-exception.exe` on linux/amd64
=> [interp] reduce stack pressure

mcs/class/Mono.Security/Mono.Security_test.dll.sources, mcs/class/Mono.Security/Test/Mono.Security.Interface/TestProvider.cs, mcs/class/System/Mono.Net.Security/MonoTlsProviderFactory.cs
Cherry-picking PR #4987 from master.
* [Mono.Security]: Add test for MonoTlsProviderFactory.GetProvider ().
* [System]: Fix possible initialization issue in MonoTlsProviderFactory.
(cherry picked from commit 83f74c4123f77387bf44280c7d2da3b7cb6df958)
=> [System]: Fix possible initialization issue in MonoTlsProviderFactory. (#4987)

mcs/class/System/Mono.AppleTls/AppleCertificateHelper.cs, mcs/class/System/Mono.AppleTls/ImportExport.cs
Cherry-picking PR #4983 from master.
(cherry picked from commit fff41905e9c1636e14c6a71238ace8d52ac4c27f)
=> [System]: Actually disable the keychain code and SecItemImport() on XI (#4983)

mono/tests/Makefile.am, mono/tests/bug-45841-fpstack-exceptions.il
=> [tests] Re-enable bug-45841-fpstack-exceptions.exe

configure.ac, man/mono.1, mono/metadata/marshal.c, mono/metadata/method-builder.c, mono/metadata/method-builder.h, mono/metadata/object-offsets.h, mono/metadata/sgen-mono.c, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/driver.c, mono/mini/interp/interp.c, mono/mini/jit.h, mono/mini/method-to-ir.c, mono/mini/mini-cross-helpers.c, mono/mini/mini-runtime.c, mono/mini/tramp-arm.c, mono/mini/tramp-arm64.c, tools/offsets-tool/MonoAotOffsetsDumper.cs
@vargaz @kumpera @luhenry do you guys have some input on naming? how do you like `defined(HAVE_ONLINE_VES)` as a substitute for `!defined(DISABLE_JIT) || defined(ENABLE_INTERPRETER)`?
=> [interp] add MONO_AOT_MODE_INTERP

configure.ac, man/mono.1, mono/metadata/marshal.c, mono/metadata/method-builder.c, mono/metadata/method-builder.h, mono/metadata/object-offsets.h, mono/metadata/sgen-mono.c, mono/mini/driver.c, mono/mini/jit.h, mono/mini/method-to-ir.c, mono/mini/mini-cross-helpers.c, mono/mini/mini-runtime.c, mono/mini/tramp-arm.c, mono/mini/tramp-arm64.c, mono/mini/tramp-ppc.c, mono/mini/tramp-x86.c, tools/offsets-tool/MonoAotOffsetsDumper.cs, winconfig.h
backport of https://github.com/mono/mono/pull/4958
=> [2017-06][interp] add MONO_AOT_MODE_INTERP

mcs/class/Mono.Security/Mono.Security.Interface/IMonoSslStream.cs, mcs/class/System/Mono.AppleTls/AppleTlsContext.cs, mcs/class/System/Mono.AppleTls/AppleTlsStream.cs, mcs/class/System/Mono.Btls/MonoBtlsContext.cs, mcs/class/System/Mono.Btls/MonoBtlsObject.cs, mcs/class/System/Mono.Btls/MonoBtlsSsl.cs, mcs/class/System/Mono.Btls/MonoBtlsStream.cs, mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs, mcs/class/System/Mono.Net.Security/LegacySslStream.cs, mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs, mcs/class/System/Mono.Net.Security/MobileTlsContext.cs, mcs/class/System/ReferenceSources/SR2.cs, mcs/class/System/System.Net.Security/SslStream.cs, mcs/class/System/System.Net.Security/SslStream.platformnotsupported.cs, mcs/class/System/common.sources, mcs/class/System/net_4_x_System.dll.sources, mono/btls/btls-bio.c, mono/btls/btls-ssl.c, mono/btls/btls-ssl.h
Cherry-picking PR #4969 from master.
* [System]: Correctly implement close and shutdown in SslStream.
* Cleanup.
* Cosmetic.
* More ReferenceSources/SR2.cs into common.sources to make it build.
(cherry picked from commit 21d5c9c346113d47455d96e545410733bfccf1fb)
=> [System]: Correctly implement close and shutdown in SslStream. (#4969)

mono/mini/aot-compiler.c
=> [aot] fix compiliation for targets that do not set MONO_ARCH_HAVE_FULL_AOT_TRAMPOLINES

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachineManager.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs
And added new `new String('a', 3);` unit test after `return;`
=> Fixed Mono.Debugger.Soft unit tests

mono/metadata/profiler-private.h, mono/metadata/profiler.c, mono/metadata/profiler.h, mono/mini/mini-exceptions.c, mono/profiler/log.c, mono/profiler/log.h, mono/profiler/mprof-report.c
This addresses some inconsistencies in the format that I found while implementing the profiler library, and adds some extra data that the Xamarin Profiler team needs.
=> [profiler] A few small format changes

mcs/class/corlib/Test/System.Security.Cryptography.X509Certificates/X509CapiTest.cs, mcs/class/corlib/Test/System.Security.Cryptography.X509Certificates/X509CertificateTest.cs
backport of https://github.com/mono/mono/pull/5066
=> [2017-06][bcl tests] do not attempt to delete non-existing files

acceptance-tests/profiler-stress/runner.cs, mono/mini/mini-posix.c, mono/profiler/log-args.c, mono/profiler/log.c, mono/utils/mono-threads-posix.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
This is a revival of some of my old PRs. This should make the profiler stress test lane green again.
=> [profiler] A bunch of profiler bug/stability fixes.

mono/profiler/log.c
The lock no longer supports recursion as of 10ba222234b0ff23bfbe29c6f2dfd7673ec2ca7f. Not that it ever really did, since the old implementation was buggy.
=> [profiler] Fix a deadlock due to recursive use of the buffer lock.

packaging/MacSDK/msbuild.py
cherry-pick 67f753a893184932c75b63f2d7cca0cd6323c081
=> [packaging/msbuild] Bump to get new changes on xplat-master (#5127)

packaging/MacSDK/msbuild.py
cherry-pick 7f5c2b61fcf67cc47aa8b010b34da8039276afb6
=> [packaging/msbuild] Bump to get new changes on xplat-master

mono/sgen/sgen-memory-governor.c
The mutex is used by sgen worker threads that are not attached to the mono
runtime - they cannot use a coop mutex.
=> [sgen] Use an OS mutex for memory governor log entries

mcs/class/corlib/Test/System.IO/DriveInfoTest.cs, mcs/class/corlib/Test/System.IO/FileTest.cs, mcs/class/corlib/corlib_test.dll.sources, mcs/class/test-helpers/NunitHelpers.cs, mono/metadata/w32file-unix.c
=> Add apfs to list of fixed drive types and add test for deleting non-existing file

mcs/class/Mono.Security/Mono.Security.Interface/IMonoSslStream.cs, mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs, mcs/class/System/Mono.Net.Security/MonoTlsStream.cs
* Add missing IMonoSslStream.WriteAsync().
* MonoTlsStream: put implementation inside #SECURITY_DEP, not the entire class.
* cosmetic debug-only 1-line change.
=> [System]: minor cleanups.

mono/mini/mini-runtime.c
=> [profiler] Report main thread name after attaching.

mcs/class/System/ReferenceSources/Win32Exception.cs, mono/metadata/w32error.h, mono/metadata/w32socket-unix.c
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=58100
=> [w32error] Add ENXIO error case

tools/offsets-tool/MonoAotOffsetsDumper.cs
backport for https://github.com/mono/mono/pull/5237
=> [2017-06][offset-tool] fix assignment for GeniOS

mono/mini/interp/interp.c
makes the recently introduced regression test `test_2_fault` work in the interpreter.
=> [interp] reuse finally_ips infrastructue for fault clauses

configure.ac, mono/mini/Makefile.am.in, mono/mini/builtin-types.cs, mono/mini/driver.c, mono/mini/mini-native-types.c
not sure about the `arch_pointer_size` stuff in `Makefile.am.in`.  is there a way to get my hands on `SIZEOF_VOID_P` in the Makefile?
=> [jit] test builtin types

tools/nuget-hash-extractor/nuget-hash-extractor.cs
.. denied assemblies usable by a msbuild task for filtering them.
=> [msbuild] Add option to nuget-hash-extractor to generate a list of the

samples/profiler/sample.c
- Fix the Linux build instructions
- Remove eglib dependencies, as they complicate the build of an
extenral module
- Make the call counter 64 bits
- Adjustments to accommodate the new profiling API
=> [profiler] fixes to profiler sample

mcs/class/corlib/System.Reflection.Emit/ConstructorBuilder.cs, mcs/class/corlib/System.Reflection.Emit/CustomAttributeBuilder.cs, mcs/class/corlib/System.Reflection.Emit/FieldBuilder.cs, mcs/class/corlib/System.Reflection.Emit/MethodBuilder.cs, mcs/class/corlib/System.Reflection.Emit/ModuleBuilder.cs, mcs/class/corlib/Test/System.Reflection.Emit/ConstructorBuilderTest.cs, mcs/class/corlib/corlib_xtest.dll.sources
- Fix some argument checking in SRE
- Enable more of the CoreFX SRE xUnit tests
=> [sre] Fix some argument checks, enable xtests

mcs/class/System/ReferenceSources/Win32Exception.cs, mono/metadata/w32error-unix.c, mono/metadata/w32error.h
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=58738
=> [w32error] Add ENODEV -> ERROR_DEV_NOT_EXIST error translation

mono/mini/method-to-ir.c, mono/tests/Makefile.am, mono/tests/delegate14.cs
=> Add null check for target to optimized delegate constructor code path

packaging/MacSDK/libgdiplus.py
=> Bump libgdiplus

mcs/class/System/Mono.AppleTls/AppleTlsContext.cs
(cherry picked from commit c74f44126efe14f933ddc77dc0778f5142be0ec2)
=> [System]: Fix major AppleTls memory leak.  Bug #56814. (#5370)

README.md, configure.ac, mono/metadata/mono-config.c, mono/metadata/object-offsets.h, mono/sgen/sgen-archdep.h, mono/utils/Makefile.am, mono/utils/atomic.c, mono/utils/mono-context.h, mono/utils/mono-dl-wasm.c, mono/utils/mono-hwcap-wasm.c, mono/utils/mono-membar.h, mono/utils/mono-mmap.c, mono/utils/mono-threads-posix.c, mono/utils/mono-threads-wasm.c, mono/utils/mono-threads.h
This has the initial set of commits used by my hackweek port.
This includes configure.ac changes and the initial utils port.
=> WebAssembly port

mcs/class/System/ReferenceSources/Win32Exception.cs, mono/metadata/w32error-unix.c, mono/metadata/w32error.h
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=58738
=> [2017-06][w32error] Add ENODEV -> ERROR_DEV_NOT_EXIST error translation (#5385)

mcs/class/System/ReferenceSources/Win32Exception.cs, mono/metadata/w32error-unix.c, mono/metadata/w32error.h
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=58738
=> [2017-08][w32error] Add ENODEV -> ERROR_DEV_NOT_EXIST error translation (#5385)

scripts/ci/run-test-default.sh
Should be fixed now that https://github.com/mono/mono/pull/5477 was merged.
=> [ci] Reenable xunit tests on Windows

mono/metadata/class.c
`class.c` contains some racy counters that appear quite often in my ongoing data race analysis. I would therefore like to propose a few changes / fixes:
- use `Unlocked* ()` for `class_gparam_count`, `classes_size` and `inflated_methods_size` (all occurrences seem to be too perf critical and/or unimportant to use `Interlocked* ()`)
- I am unable to find `class_ext_size` and `class_ext_count` anywhere in Mono and would therefore delete them (dead code)
- fix a typo: "the the" -> "let the"
About the conversion from `guint32` to `gint32`:
- `gint32` supports the general tendency of using signed types with `Interlocked* ()` operations
- nothing will break or change since these values get registered as `MONO_COUNTER_INT` anyways which will be printed with `%d` at some point
=> [TSan] Unlock class.c

packaging/MacSDK/fsharp.py, packaging/MacSDK/patches/fsharp-metadata-table-size-fix.patch
...from https://github.com/Microsoft/visualfsharp/pull/3553
=> Add portable pdb metadata table size fix 

mono/metadata/loader.c
`loader.c` contains four statistics counters and all of them are invovled in data races. This PR focuses on dealing with them:
- All of them can be `gint32` as they are registered as `MONO_COUNTER_INT` anyways.
- Since there is already a lot of locking involved in `loader.c` (including an approved usage of `Interlocked* ()` with with `mono_stats`), I think that `Interlocked* ()` can be used here instead of `Unlocked* ()`. If this assumption is wrong, I would kindly ask to correct me by commenting the affected rows and I will change it to `Unlocked* ()`.
=> [TSan] Interlocking loader.c

mono/mini/mini-amd64.c
=> [amd64] fix tailcall insn size

mcs/class/Mono.Profiler.Log/Mono.Profiler.Log/LogProcessor.cs
Make sure all events have all fields initialized. This was missing setting
Buffer and Timestamp properties when creating the different LogEvent* subclasses.
=> [Mono.Profiler.Log] Initialize LogEvent's properties

mono/metadata/metadata.c
- using `gint32` instead of `int` should not be an issue
- `img_set_count` is interlocked by `image_sets_lock ()` - `UnlockedIncrement ()` is just used for completeness / documentation
- `++img_set_cache_(hit|miss)` is called quite often and is connected to caching: it seems to me as if interlocking these counters would be a bad idea (at least for cache hits)
=> [TSan] Mark racy counters in metadata.c

man/mcs.1, mcs/mcs/settings.cs
=> Toggle the turbo button

mcs/class/System.Xaml/System.Xaml/XamlBackgroundReader.cs
The ManualResetEvent wouldn't be signaled when an exception happens in the reader loop so we'd deadlock in Read().
I'm still investigating where the exception comes from but this should at least help unblocking CI.
https://bugzilla.xamarin.com/show_bug.cgi?id=46683
=> [System.Xaml] Fix deadlock on exception in XamlBackgroundReader

packaging/MacSDK/fsharp.py, packaging/MacSDK/patches/fsharp-install-netsdk-targets.patch
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=57771
=> Install Microsoft.FSharp.NetSdk.props and targets

packaging/MacSDK/msbuild.py
https://github.com/mono/msbuild/commit/f296e67b6004dd39c3f43b177bcf45dfbe931341
=> [msbuild] Bump to get workaround for bxc #55697 .

mcs/class/WindowsBase/System.Windows.Converters/Int32RectValueSerializer.cs, mcs/class/WindowsBase/System.Windows.Converters/PointValueSerializer.cs, mcs/class/WindowsBase/System.Windows.Converters/RectValueSerializer.cs, mcs/class/WindowsBase/System.Windows.Converters/VectorValueSerializer.cs, mcs/class/WindowsBase/System.Windows.Media/Matrix.cs, mcs/class/WindowsBase/System.Windows/Int32Rect.cs, mcs/class/WindowsBase/System.Windows/NumericListTokenizer.cs, mcs/class/WindowsBase/System.Windows/Point.cs, mcs/class/WindowsBase/System.Windows/Rect.cs, mcs/class/WindowsBase/System.Windows/Size.cs, mcs/class/WindowsBase/System.Windows/Vector.cs, mcs/class/WindowsBase/Test/System.Windows/Int32RectConverterTest.cs, mcs/class/WindowsBase/Test/System.Windows/Int32RectTest.cs, mcs/class/WindowsBase/Test/System.Windows/Int32RectValueSerializerTest.cs, mcs/class/WindowsBase/Test/System.Windows/PointConverterTest.cs, mcs/class/WindowsBase/Test/System.Windows/PointTest.cs, mcs/class/WindowsBase/Test/System.Windows/PointValueSerializerTest.cs, mcs/class/WindowsBase/Test/System.Windows/RectConverterTest.cs, mcs/class/WindowsBase/Test/System.Windows/RectTest.cs, mcs/class/WindowsBase/Test/System.Windows/RectValueSerializerTest.cs, mcs/class/WindowsBase/Test/System.Windows/VectorConverterTest.cs, mcs/class/WindowsBase/Test/System.Windows/VectorValueSerializerTest.cs, mcs/class/WindowsBase/WindowsBase.dll.sources, mcs/class/WindowsBase/WindowsBase_test.dll.sources
Multi-culture implementation ValueSerializers, Parse and ToString for types from WindowsBase.
=> Multi-culture implementation ValueSerializers, Parse and ToString for types from WindowsBase.

mono/metadata/w32error-unix.c
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=58738
=> [w32error] Add ENXIO -> ERROR_DEV_NOT_EXIST error translation

mono/mini/mini.h
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=33081
=> [runtime] Fix shared-only build.

mcs/class/System/System.Net/HttpListenerRequest.cs, mcs/class/System/Test/System.Net/HttpListenerRequestTest.cs
Rebased https://github.com/mono/mono/pull/582 against master.
=> [System] HttpListenerRequest: ignore bad cookies and keep request alive

mono/metadata/w32file-win32.c, mono/metadata/w32file.c
ERROR_SHARING_VIOLATION can only happen on win32, so pushing the code to deal with this error to w32file-win32.c file.
=> [w32file] Push win32 specific error to win32 specific implementation

mono/mini/exceptions-amd64.c
Full AOT on Windows x64 is currently broken due to the following commit:
https://github.com/mono/mono/pull/5472
The problem is that this commit is not full AOT compliant, so currently it is not possible to run any full AOT compiled code. Needs to be fixed using a trampoline in AOT image (similar to other exception handling methods). The emitted code also needs to work in the full AOT use case, so smaller adjustments are needed there as well.
Temporary disable stack overflow implementation on Windows x64 full AOT until we have a proper fix for:
https://bugzilla.xamarin.com/show_bug.cgi?id=59913
=> [Windows] Temporary disable none-working stack overflow implementation on Windows x64 full AOT.

mono/mini/mini-runtime.c
(from #5425, in order to get work upstream)
=> [interp] remove InterpMethod entry in hash table on free_method callback

mcs/packages/.gitignore, mcs/packages/Makefile, mcs/packages/csi-test.csx, scripts/ci/run-test-default.sh
=> [2017-10][bcl] Fix csi to work on Mono

data/lldb/monobt.py, mono/mini/interp/interp.c, mono/mini/interp/mintops.c, mono/mini/interp/transform.c, mono/mini/tramp-amd64.c
get partial work of https://github.com/mono/mono/pull/5425 upstream
=> [interp] misc fixes

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
* fixes crash in gtest-065.cs and gtest-072.cs
* fixes test-async-11.exe
* fixes gtest-112.cs
* propagate error, we do not assert at least on test-269.exe
* fixes test-301.cs and test-305.cs
* fixes gtest-etree-01.exe
see commit messages for details.
(from #5425, in order to get work upstream)
=> [interp] several fixes for the execution system

mcs/class/corlib/ReferenceSources/Type.cs, mcs/class/corlib/System/TypeSpec.cs, mcs/class/corlib/Test/System/TypeTest.cs, mono/metadata/icall.c, mono/metadata/reflection-internals.h, mono/metadata/reflection.c, mono/metadata/reflection.h, mono/mini/debugger-agent.c
Cherrypick #5751 to `2017-10`
Fixes [#59664](https://bugzilla.xamarin.com/show_bug.cgi?id=59664)
=> [2017-10][reflection] Throw TLE for Type.GetType("", ...) (Fixes #59664)

mcs/class/Mono.Debugger.Soft/Test/dtest.cs
The behaviour in the test is the same as VSfM.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=5438
=> [debugger] Fix LineNumbers test

mono/metadata/w32socket.c, mono/utils/mono-context.c, mono/utils/mono-sigcontext.h
WSL issues opened for these workarounds:
* a6c061d1d11824ca483fcd2dfe05d63d58b9f9ed: https://github.com/Microsoft/BashOnWindows/issues/2205
* 959eb46e17ac6544a2a6dc623392457446ee8aed: https://github.com/Microsoft/BashOnWindows/issues/2555
This PR supersedes #5003.
=> [runtime] Some WSL fixes.

mcs/class/System.Windows.Forms/System.Windows.Forms/MonthCalendar.cs
In MonthCalendar added validation on acceptable date interval when update SelectionRange property. 
Fixed loss of focus when the user presses the arrow buttons and shift.
=> [System.Windows.Forms]  In MonthCalendar added validation on acceptable date interval. Fixes #60115

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c, mono/mini/interp/transform.c, mono/mini/mini-generic-sharing.c
get partial work of #5425 upstream
=> [interp] stop leaking MonoMethodHeader

mono/mini/Makefile.am.in, mono/mini/aot-tests.cs, mono/mini/driver.c, mono/mini/interp/transform.c
plus some fixes to make `aot-tests.cs` work in the interpreter
=> [mini regressions] enable aot-tests.cs & gshared.cs on more configurations

mono/eglib/gmisc-unix.c
backport of https://github.com/mono/mono/pull/5809
=> [2017-10] [eglib] check if result is set

mcs/tools/linker/monolinker-net_4_x.csproj, mcs/tools/linker/monolinker.exe.sources
backport of https://github.com/mono/mono/pull/5797
=> [2017-08] bump linker

eglib/src/gmisc-unix.c
backport of https://github.com/mono/mono/pull/5809
=> [2017-08] [eglib] check if result is set

mcs/class/System/Test/System.Net.Sockets/SocketTest.cs, mcs/class/System/Test/System.Net/WebClientTest.cs, mcs/class/System/Test/System.Net/WebClientTestAsync.cs
backport of https://github.com/mono/mono/pull/5819
=> [2017-08] [System.Net] Tweak tests for watchOS

mcs/class/System/Test/System.Net.Sockets/SocketTest.cs, mcs/class/System/Test/System.Net/HttpListenerRequestTest.cs, mcs/class/System/Test/System.Net/WebClientTest.cs, mcs/class/System/Test/System.Net/WebClientTestAsync.cs
backport of https://github.com/mono/mono/pull/5819
=> [2017-10] [System.Net] Tweak tests for watchOS

mono/mini/interp/transform.c
interp changes in https://github.com/mono/mono/pull/5791 broke `test-550.cs`
=> [interp] another cee_ldobj fix

.gitignore
".idea" - folder generated by jetBrains Rider IDE (it's possible to open, compile and debug net_4_x.sln solution in it)
=> Update root gitignore

mono/mini/interp/interp.c, mono/mini/interp/transform.c, mono/mini/mini-runtime.c, mono/tests/Makefile.am, mono/tests/delegate15.cs
It requires creating a vtable for the class, which is not supported.
Fixes #59153
=> [mini] Don't attempt to compile method of open generic class

mono/metadata/object-internals.h, mono/metadata/object.c, mono/mini/interp/interp.c, mono/mini/interp/interp.h, mono/mini/mini-runtime.c, mono/tests/Makefile.am
=> [interp] Interp fixes

mono/mini/tramp-s390x.c
Add code to check for thread interruption and handle any exception.
=> Match amd64/arm64 in the way of handling exceptions within trampolines

mcs/class/corlib/Test/System.IO/FileTest.cs, mcs/class/corlib/Test/System.IO/StreamReaderTest.cs, mcs/class/corlib/Test/System.IO/StreamWriterTest.cs
In the original tests there was a confusion between GetTempDir and GetTempFileName, GetTempDir always return the tmp dir.
=> [Tests] Small improvement to make sure that the tmp directories are unique.

mcs/tools/xbuild/Makefile
=> [msbuild] Fix build - create the directories before installing ..

mcs/class/System/System.Diagnostics/Process.cs
(cherry picked from commit 03ea90cf1f9a823abf7f0fb23edbcfee6b640f82)
=> [2017-10] [bcl] Optimize Process.GetCurrentProcess ().MainModule. (#5843)

mcs/class/System/System.IO.Compression/DeflateStream.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=56727
=> [System] Fix DeflateStream crash with high concurrency on Read/Write/Close

mono/metadata/locales.c
fixes https://bugzilla.xamarin.com/show_bug.cgi?id=59916
=> [metadata] make get_darwin_locale thread-safe

mcs/class/System/System.IO.Compression/DeflateStream.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=56727
=> [System] Fix DeflateStream crash with high concurrency on Read/Write/Close (#5994)

mono/metadata/loader.c
Follow-up to #6037 
Fixes interpreter failure in gtest-253.cs due to 3259e04ace67552fc8d63a8f1ddbb830e526f05f
If we're constraining an inflated generic method, `mono_method_get_vtable_index` will return a generic method definition.  So we need to re-inflate it with the original method instantiation.
=> [loader] inflate constrained result if constraining an inflated generic method

mono/metadata/loader.c, mono/tests/Makefile.am, mono/tests/iface-contravariant1.cs
Cherrypick #6037 for `2017-10`
=> [loader] Rework get_method_constrained (Fixes #60545)

mcs/class/System.Core/Test/System.Security.Cryptography/AesManagedTest.cs
Fixes https://github.com/xamarin/maccore/issues/588
=> [tests] Adjust ifdefs to get the expected behavior for Xamarin.Mac/Modern tests.

mono/metadata/profiler.c
Add back some more legacy profiler APIs: 
```
mono_profiler_install_allocation
mono_profiler_install_enter_leave
mono_profiler_install_exception
```
=> Legacy Profiler APIs

scripts/ci/pipeline/osx-package.groovy, scripts/ci/pipeline/win-package.groovy
=> [ci] Switch .pkg PR build to pipeline script as well

mcs/class/corlib/System.Reflection.Emit/CustomAttributeBuilder.cs, mcs/class/corlib/System.Reflection.Emit/ModuleBuilder.cs, mcs/class/corlib/Test/System.Reflection.Emit/ModuleBuilderTest.cs, mono/metadata/reflection.c
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=59343
=> [runtime] Implement a few ModuleBuilder getters

packaging/MacSDK/msbuild.py
In preparation for the next branching.
=> Bump msbuild to xplat-master branch

mcs/class/System.IdentityModel/System.IdentityModel.Tokens/InMemorySymmetricSecurityKey.cs, mcs/class/System.IdentityModel/Test/System.IdentityModel.Tokens/InMemorySymmetricSecurityKeyTest.cs
Commit based on https://bugzilla.xamarin.com/show_bug.cgi?id=35661
All credit goes to af4178a2
=> un-commented HmacSha256Signature bug 35661

mono/mini/memory-access.c
fixes (for the runtime part): https://bugzilla.xamarin.com/show_bug.cgi?id=60865
now at least the runtime doesn't crash anymore:
``` 
Starting:    net_4_x_System.Runtime.CompilerServices.Unsafe_xunit-test
System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_ByRef_Double [FAIL]
Assert.Equal() Failure
Expected: 3.42
Actual:   -1.78354552337557E+259
Stack Trace:
at System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_ByRef_Double () [0x0002e] in /Users/bernhardu/work/mono/external/corefx/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs:701
at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags …
```
=> [mini] don't do regular store if it's already handled by the unaligned case

acceptance-tests/profiler-stress/runner.cs
It's proven to be too flaky everywhere, with random timeouts and OOMEs.
=> [acceptance-tests] Disable the msbiology test completely.

mono/metadata/icall.c, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/interp/interp.c
backport of https://github.com/mono/mono/pull/6112
=> [2017-10][interp] fixes for interp AOT mode

mcs/tools/Makefile
We would like to include linker analyzer in the Xamarin.Android
installation (https://github.com/xamarin/xamarin-android/issues/1093)
=> [monodroid] Build linker-analyzer tool for monodroid

mono/metadata/threads.c, mono/tests/Makefile.am, mono/tests/threads-leak.cs
Fixes https://github.com/mono/mono/issues/6169
=> [threads] Fix leak of gchandle to MonoInternalThread

mono/metadata/object.c
I notice this stuff working on larger changes but should either leave it alone or separate it.
=> Remove a few braces that are contrary to our prescribed style.

mono/metadata/Makefile.am
This list is almost sorted -- so repair the sorting and add comment.
=> This list is almost sorted -- so repair the sorting and add comment.

mono/metadata/w32process-unix.c
This resolves quite a serious issue for Unix users of Mono that prevents Mono applications from tracking the exit status of any child process, e.g. `fork()`.
`waitpid(-1,...)` reaps all zombie child processes of the calling process (see `man waitpid`). After a child process is reaped, it can no longer be queried. Because this reaping step is invoked via the `SIGCHLD` signal, all zombie children of the calling process are reaped every time any child process terminates, regardless of whether that child process was tracked by Mono.
The impact of this bug is that apps using Mono that spawn their own child processes (outside of Mono's `w32process` API) cannot query the exit state of its children. For example, a call to `waitpid(my_child_pid,...)` will return `ECHILD` for "no such child" …
=> Only call `waitpid` for processes that Mono tracks

configure.ac
backport of https://github.com/mono/mono/pull/6276
=> [2017-12] [runtime] Fixes issue when compiling with -no_weak_imports

mono/mini/interp/transform.c, mono/tests/Makefile.am
=> [interp] Check for class failure when emitting constructor

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c, mono/tests/Makefile.am
Finally blocks are protected.
We need to throw abort once we exit all cctors.
=> [interp] Fix abort protected blocks

mono/mini/method-to-ir.c
This fix is a generalization of commit 0c6932a985175a5cf0cbc59ffd3af4abf3db248e. The previous commit was restricted to LDLOC and LDLOCS. We now avoid loading a struct for all variants of LDLOC and LDARG. Testing on a simple armv7-a Vector3 class provides a reduction in instructions for an addition operator of about 30% (~64 -> 40 instructions)
=> Generalize optimization avoiding struct loads for loading a field

mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/sre.c
Fix an error ignore, and then remove the support for it, and unused similar.
=> Fix an error ignore, and then remove the support for it, and unused similar.

mono/metadata/object.c, mono/unit-tests/Makefile.am, mono/unit-tests/test-mono-string.c
Also added some unit tests for `mono_string_new_checked`
=> Don't leak glib error in mono_string_new_checked

packaging/Windows/defs/managed-components, packaging/Windows/defs/mono, packaging/Windows/defs/mono64
We don't want to package these, found a few that needed to be removed/fixed.
=> [packaging] Add check for cygwin paths on Windows

mono/mini/interp/interp.c, mono/tests/Makefile.am
=> [interp] Add missing param support for floating types in interp_entry

man/mono.1, mono/metadata/debug-helpers.c, mono/mini/mini.c
document some internal APIs, update man page with more explanations.
Feature request: https://github.com/mono/mono/issues/6399
=> Add capability to list more than one method to be verbose

mcs/class/System/System.Diagnostics/Process.cs, mono/metadata/w32process-unix.c, mono/metadata/w32process-win32.c, mono/metadata/w32process.h
Fixes https://github.com/mono/mono/issues/6383
=> [w32process] Ensure process_handle is a legal value

mcs/class/System/System.Net/WebConnection.cs
Backport of https://github.com/mono/mono/pull/6346 for potential inclusion into future service releases for the Xamarin 15.5 Release.
=> [d15-5-2017-06] [System]: Ensure WebConnection calls nstream.EndWrite()

mono/metadata/object.c
Previously, we tried to keep the intern status of a string consistent across domains. Meaning
that if you interned "FOO" in domain 0, it would return true for String.IsInterned in domain 1.
This behavior exists in the CLR because the string table is shared between domain as string are
what they call agile objects - those that can exit in multiple domains at the same time.
Mono appdomain isolation doesn't work that way and there's not visible advantage of keeping that property.
The reason for this change is to potentially reduce the amount of interned strings and, more importantly,
reduce the amount of domain lookups, which are quite expensive and unsafe.
This should speed up interning queries.
=> [runtime] Don't auto intern a string just because another domain has done the same.

mono/eglib/glib.h
Subset of https://github.com/mono/mono/pull/6235
=> [eglib] Add g_assertf

mcs/class/referencesource/mscorlib/system/exception.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=60030
OOM was changed for consistency with .NET
=> [corlib] Some system exceptions have empty Message. Fixes bug-60030

mcs/class/System/System.Diagnostics/Process.cs, mono/metadata/w32process-unix.c, mono/metadata/w32process-win32.c, mono/metadata/w32process.h
* [w32process] Ensure process_handle is a legal value
Fixes https://github.com/mono/mono/issues/6383
* [w32process] Remove dead code
=> [w32process] Ensure process_handle is a legal value (#6449)

mcs/class/corlib/System.Runtime.InteropServices.RuntimeInformation/RuntimeInformation.cs, mcs/class/corlib/System/Environment.cs
Alternatve patch to: https://github.com/mono/mono/pull/6533
=> Use Environment.Platform to access the platform, rather than probing the file system

mono/mini/mini-runtime.c
Fixes partially https://bugzilla.xamarin.com/show_bug.cgi?id=48707
=> [mini] Fix seq point info leak

mono/metadata/class-internals.h, mono/metadata/metadata-internals.h, mono/metadata/metadata.c, mono/metadata/profiler.c, mono/profiler/coverage.c
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60225
=> [profiler] Write out all uncovered classes/methods in a loaded image.

mcs/jay/closure.c, mcs/jay/defs.h, mcs/jay/error.c, mcs/jay/lalr.c, mcs/jay/lr0.c, mcs/jay/main.c, mcs/jay/mkpar.c, mcs/jay/output.c, mcs/jay/reader.c, mcs/jay/symtab.c, mcs/jay/verbose.c, mcs/jay/warshall.c
Also smaller part fix C-vs.-C++-isms.
=> Convert K&R warning farm to ANSI and add static/const.

packaging/MacSDK/msbuild.py
=> Bump msbuild to pick up the IsOSX performance fix

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
Backport of http://github.com/mono/mono/pull/6562
=> [runtime] Apply cctor filters to callees of cctors (#6562)

mcs/class/System.Data/System.Data.SqlClient/SqlBulkCopy.platformnotsupported.cs, mcs/class/System.Data/System.Data.SqlClient/SqlCommand.platformnotsupported.cs, mcs/class/System.Data/System.Data.SqlClient/SqlCommandBuilder.platformnotsupported.cs, mcs/class/System.Data/System.Data.SqlClient/SqlConnection.platformnotsupported.cs, mcs/class/System.Data/System.Data.SqlClient/SqlDataAdapter.platformnotsupported.cs, mcs/class/System.Data/System.Data.SqlClient/SqlException.platformnotsupported.cs, mcs/class/System.Data/System.Data.SqlClient/SqlParameter.platformnotsupported.cs, mcs/class/System.Data/System.Data.SqlClient/SqlParameterCollection.platformnotsupported.cs, mcs/class/System.Data/System.Data.SqlClient/SqlTransaction.platformnotsupported.cs, mcs/class/System.Data/Test/System.Data.SqlClient/SqlDataAdapterTest.cs, mcs/class/System.Data/monotouch_watch_System.Data.dll.exclude.sources, mcs/class/System.Data/monotouch_watch_System.Data.dll.sources
Backport of https://github.com/mono/mono/pull/6600
=> Fix watchos tests for system.data (#6600)

packaging/MacSDK/mono-basic.py
=> [2017-12] [packaging] Bump mono-basic to bring latest fixes

mcs/mcs/expression.cs, mcs/tests/test-readonly-03.cs, mcs/tests/ver-il-net_4_x.xml
=> [2017-12] [mcs] readonly struct this can be reassigned within ctor

mcs/errors/cs1983.cs, mcs/mcs/async.cs, mcs/mcs/attribute.cs, mcs/mcs/class.cs, mcs/mcs/generic.cs, mcs/mcs/import.cs, mcs/mcs/method.cs, mcs/mcs/statement.cs, mcs/mcs/typemanager.cs, mcs/mcs/typespec.cs, mcs/tests/test-async-94.cs, mcs/tests/ver-il-net_4_x.xml
=> [2017-12] [mcs] Implements C# 7.0 Generalized async return types

mcs/mcs/ecore.cs, mcs/tests/test-ref-10.cs, mcs/tests/ver-il-net_4_x.xml
=> [2017-12] [mcs] Allow calling by-ref types virtual methods which can be devirtualized

mcs/errors/cs8346.cs, mcs/mcs/assign.cs, mcs/mcs/expression.cs, mcs/mcs/typemanager.cs, mcs/tests/test-948.cs, mcs/tests/ver-il-net_4_x.xml
=> [2017-12] [mcs] Implements 7.2 stackalloc to Span assignment conversion.

mcs/mcs/import.cs
=> [2017-12] [mcs] Add a detection for ByRefLikeMarker

mcs/class/System.Drawing/System.Drawing/FontFamily.cs, mcs/class/System.Drawing/System.Drawing/gdipFunctions.cs
Fixes https://github.com/mono/mono/issues/6705
=> [System.Drawing] Fix leak in FontFamily

scripts/ci/run-test-interpreter.sh
image got upgraded for interpreter lanes too
=> [ci] update ARM label for ignored interpreter tests

sdks/wasm/Makefile
=> [wasm] Fix nunit dep description.

mcs/class/System/Test/System.Net/WebClientTest.cs
=> [System] Disable few tests which blocks when run on main loop

mcs/class/System/Test/System.Net/WebClientTest.cs
=> [2017-12] [System] Disable few tests which blocks when run on main loop

configure.ac
=> [build] Bump corlib counter for mcs changes

mcs/packages/Makefile, packaging/MacSDK/packaging/resources/whitelist.txt, scripts/.gitignore, scripts/Makefile.am, scripts/vbc.in
Backport of https://github.com/mono/mono/pull/6127
=> [2017-12][packaging] Add install of Visual Basic compiler

.vscode/c_cpp_properties.json
This greatly ease development of the runtime with VSCode since we can enjoy code completion with IntelliSense.
=> [RFC] [ide] Add setup file for VSCode

mcs/class/System.Data/corefx/SqlConnectionStringBuilder.cs
Fixes https://github.com/mono/mono/issues/6767
I updated the reference to external/corefx with my PR (https://github.com/mono/corefx/pull/18) but it looks like there were a few more commits
=> [System.Data] Add missing API (fixes 6767)

scripts/ci/pipeline/osx-package.groovy, scripts/ci/pipeline/win-package.groovy
Use the trigger `@monojenkins build pkg and msi`.
=> [ci] Add Windows .msi PR build

sdks/builds/download-llvm.sh, sdks/builds/ios.mk
Revert part of https://github.com/mono/mono/commit/605cadfb09d6c79723763b8afd09480a5941eabf
=> [sdks] Bring back download of llvm for iOS

mono/metadata/w32socket-win32.c
Backport of #6453.
/cc @lewurm
=> [2017-12] Fix mono_w32socket_send (and maybe others)

mcs/class/System.Data/corefx/SqlConnectionStringBuilder.cs
Backport of #6795.
/cc @EgorBo
=> [2018-02] [System.Data] Add missing API (fixes 6767)

mcs/class/System.Data/corefx.unix.sources, mcs/class/System.Data/corefx/Interop.NetSecurityNative.cs
Backport of #6824.
/cc @luhenry
=> [2018-02] [System.Data] Add stubs for Interop.NetSecurityNative

mcs/class/System.Data/corefx.unix.sources, mcs/class/System.Data/corefx/Interop.NetSecurityNative.cs
Backport of #6824.
/cc @luhenry
=> [2017-12] [System.Data] Add stubs for Interop.NetSecurityNative

mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
https://github.com/xamarin/maccore/issues/628
=> [timezone] ignore LocalId test on XAMMAC_4_5 too

mono/tests/Makefile.am
https://github.com/mono/mono/issues/6834
=> Disable a couple of flaky tests (monitor-*abort)

mono/metadata/w32socket-win32.c
Backport of #6453.
/cc @lewurm
=> [2017-10] Fix mono_w32socket_send (and maybe others)

mcs/class/Makefile, mcs/class/Mono.CompilerServices.SymbolWriter/Makefile, mcs/class/Mono.Security/Mono.Security.Interface/IMonoSslStream.cs, mcs/class/System.Configuration/Makefile, mcs/class/System.Design/Makefile, mcs/class/System.Security/Makefile, mcs/class/System.ServiceModel.Activation/Makefile, mcs/class/System.ServiceModel.Activation/System.ServiceModel.Activation.dll.sources, mcs/class/System.ServiceModel.Activation/System.ServiceModel/ServiceHostingEnvironment.cs, mcs/class/System.ServiceModel.Internals/Makefile, mcs/class/System.ServiceModel/Assembly/AssemblyInfo.cs, mcs/class/System.ServiceModel/Makefile, mcs/class/System.ServiceModel/System.ServiceModel.Channels.Http/HttpListenerManagerTable.cs, mcs/class/System.ServiceModel/System.ServiceModel.Channels/SvcHttpHandlerFactory.cs, mcs/class/System.ServiceModel/System.ServiceModel.Configuration/ConfigUtil.cs, mcs/class/System.ServiceModel/System.ServiceModel.dll.sources, mcs/class/System.Web.Services/Makefile, mcs/class/System.Web/Makefile, mcs/class/System.Web/System.Web.Configuration_2.0/SystemWebSectionGroup.cs, mcs/class/System.XML/Makefile, mcs/class/System/Makefile
=> [build] Narrow recursive dependencies

mcs/class/System/System.Net/WebConnection.cs, mcs/class/System/System.Net/WebResponseStream.cs
Backport of #6898.
/cc @lewurm
=> [master] [System]: Set NetworkStream.ReadTimeout in WebConnection.InitConnection().

scripts/ci/run-test-default.sh
See https://github.com/mono/mono/issues/6908
=> [System.Drawing] Disable tests except on ARM64

mcs/class/System.Data/corefx/SqlConnectionStringBuilder.cs
=> [System.Data] Add missing api

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c, mono/mini/interp/transform.c
=> [interp] Fix vararg on arm

mono/mini/interp/transform.c, mono/tests/Makefile.am
=> [interp] Add class failure checks

mcs/class/System/System.Net/WebConnection.cs
Fix a regression introduced in the new web stack - when connecting
to a DNS host name that resolves to multiple IP addresses, we need
to probe them all.
On iOS, "localhost" will resolve to both "::1" and "127.0.0.1".
=> [System]: WebConnection.Connect() needs to probe all IP addresses.

mcs/class/System/System.Net/WebConnection.cs
Backport of #6931.
/cc @baulig
=> [2018-02] [System]: WebConnection.Connect() needs to probe all IP addresses.

mono/mini/aot-tests.cs
Backport of #6890.
/cc @lewurm
=> [2018-02] [interp] disable test_42_arm64_dyncall_vtypebyval

configure.ac, mono/metadata/Makefile.am, mono/metadata/class-internals.h, mono/metadata/icall-table.c, mono/metadata/icall-table.h, mono/metadata/icall.c, msvc/libmonoruntime-common.targets, msvc/libmonoruntime-common.targets.filters
Backport of #6905.
/cc @lewurm
=> [2018-02] [runtime] Make icall tables loadable.

mcs/tools/linker-analyzer/Makefile, mcs/tools/linker-analyzer/illinkanalyzer-net_4_x.csproj
=> Bump linker and update linker-analyzer references

mcs/tools/mkbundle/mkbundle.cs
Fixes https://github.com/mono/mono/issues/6187
=> [runtime] Revert mkbundle defaulting behavior made in ca8b8bd346

mono/metadata/reflection.c, mono/metadata/sre.c
=> [2018-02] [sre] Unlock loader lock on error paths

mcs/tools/mkbundle/mkbundle.cs
=> [2017-12] [runtime] Revert mkbundle defaulting behavior made in ca8b8bd346

mcs/tools/mkbundle/mkbundle.cs
=> [2018-02] [runtime] Revert mkbundle defaulting behavior made in ca8b8bd346

mcs/class/Makefile
=> [build] Fixes monolite build

packaging/MacSDK/fsharp.py
Next update to F# to include regression fix https://github.com/Microsoft/visualfsharp/pull/4348
=> Update F# to 4.1.33

packaging/MacSDK/fsharp.py
=> [2017-12] Update F# to 4.1.33

mcs/class/corlib/System.IO/LogcatTextWriter.cs
Backport of #6954.
/cc @luhenry
=> [master] [corlib] Pass null-terminated string for logging

mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mcs/class/corlib/System/Nullable.cs, mono/mini/interp/transform.c, mono/mini/method-to-ir.c, mono/mini/objects.cs
=> [runtime] Unboxing of nullable enums should throw for boxed ints.

man/mkbundle.1, mcs/tools/mkbundle/mkbundle.cs
For the simple/cross compiler scenario, fixes one of the missing issues for #6230
=> [mkbundle] Automatically bundle config files and machine.config files

mcs/class/Mono.Runtime.Tests/Mono.Runtime.Tests_test.dll.sources, mono/mini/bench.cs, mono/mini/builtin-types.cs
This reverts commit e2874db5227649ad9b005a5c1d30742bb896a670.
Revert this as it breaks the SDK tests.
=> Revert "[jit] Make some JIT regression test files compile in the mobile profile (#7059)"

mono/mini/method-to-ir.c
=> [2017-12] Generalize optimization avoiding struct loads for loading a field

mono/metadata/object.c
i.e. merge 20e69fa1996e32bba66cea4a723b3da0ee913243 and d7626e8217f3d2b8dbcabfa8281475fe8b2eb851.
Remove some redundant error_init calls.
=> Centralize handle-based post-object creation code.

mcs/class/Mono.Debugger.Soft/Test/dtest.cs
Backport of #7032.
/cc @vargaz
=> [2018-02] [debugger] disable StepOutAsync test because it\u0027s flaky

sdks/builds/Makefile, sdks/builds/mxe.mk
Backport of #7108.
/cc @luhenry
=> [master] [sdks] Fix for XA integration

mcs/class/corlib/corlib.dll.sources
=> [corlib] order sources content

sdks/wasm/Makefile
=> More Wasm ci fixes

sdks/builds/Makefile, sdks/builds/mxe.mk
Backport of #7108.
/cc @luhenry
=> [2018-02] [sdks] Fix for XA integration

mono/mini/gshared.cs, mono/mini/method-to-ir.c
Hopefully fixes https://github.com/mono/mono/issues/7016.
=> [jit] Handle more cases for gsharedvt constrained calls.

mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mcs/class/corlib/Test/System.Runtime.CompilerServices/RuntimeFeatureTest.cs
=> [2017-12] [corlib] Fix RuntimeFeatureTest.NoNewFeaturesAdded on mobile

mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mcs/class/corlib/Test/System.Runtime.CompilerServices/RuntimeFeatureTest.cs
=> [2018-02] [corlib] Fix RuntimeFeatureTest.NoNewFeaturesAdded on mobile

mcs/build/tests.make, mcs/class/System/common_networking.sources, mcs/class/test-helpers/Configuration.Http.cs, mcs/class/test-helpers/PlatformDetection.cs
This is the Mono part for corefx commit
https://github.com/mono/corefx/commit/a46b8d9a2c960d0cb882831ef4e6a665e5d9b8e2.
=> Add Mono-specific System.Net.Test.Common.Configuration.Http.

mcs/build/tests.make, mcs/class/System/System_xtest.dll.sources
Fixes 5fabb059cfc1e92c486844cf76d5cf3b3c4d1a4f
=> [build] Don't add specific support file to all xunit test builds

mono/Makefile.am, mono/metadata/Makefile.am
Backport of #7141.
/cc @lewurm
=> [2018-02] [icall table] add ldflags for bitcode

mcs/class/referencesource/mscorlib/system/missingmemberexception.cs
=> [corlib] Make MissingMember exceptions working again after #6123

mcs/tools/mono-api-html/ApiChange.cs, mcs/tools/mono-api-html/ApiDiff.cs, mcs/tools/mono-api-html/ClassComparer.cs, mcs/tools/mono-api-html/ConstructorComparer.cs, mcs/tools/mono-api-html/EventComparer.cs, mcs/tools/mono-api-html/FieldComparer.cs, mcs/tools/mono-api-html/MemberComparer.cs, mcs/tools/mono-api-html/NamespaceComparer.cs, mcs/tools/mono-api-html/PropertyComparer.cs
=> [2018-02] [mono-api-html] Expand \u0022ignore\u0022 functionality (#7154)

mcs/class/System.XML/ReferenceSources/BinaryCompatibility.cs, mcs/class/System.XML/System.Xml.dll.sources
Fixes https://github.com/xamarin/xamarin-android/issues/1309
=> [System.Xml] Remove reflection calls for value has to be set

mcs/class/System.XML/ReferenceSources/BinaryCompatibility.cs, mcs/class/System.XML/System.Xml.dll.sources
=> [2017-12] [System.Xml] Remove reflection calls for value has to be set

mcs/class/System.XML/ReferenceSources/BinaryCompatibility.cs, mcs/class/System.XML/System.Xml.dll.sources
=> [2018-02] [System.Xml] Remove reflection calls for value has to be set

mono/mini/Makefile.am.in, mono/mini/mini.c
=> [2017-12] [jit] Disable partial sharing during JITting, its only been tested in full aot mode, and doesn\u0027t seem to work with JITted methods.

mono/mini/Makefile.am.in, mono/mini/mini.c
=> [2018-02] [jit] Disable partial sharing during JITting, its only been tested in full aot mode, and doesn\u0027t seem to work with JITted methods.

mono/mini/aot-compiler.c
=> [2018-02] [aot] Emit the same instances in hybrid aot mode as in full aot mode.

mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/7086.
=> [aot] Emit the same instances in hybrid aot mode as in full aot mode.

mcs/class/System.Web/System.Web/HttpRequest.cs, mcs/class/System.Web/Test/System.Web/HttpRequestTest.cs
=> Fix unknown-length requests being treated as if they are fully preloaded.

mono/mini/aot-compiler.c
Backport of #7165.
/cc @lewurm
=> [2018-02] [interp] add another signature for interp_in wrappers

mono/mini/aot-compiler.c
=> [interp] add another signature for interp_in wrappers

mcs/class/Mono.Security/Makefile, mcs/class/System.Core/System.Security.Cryptography.X509Certificates/RSACertificateExtensions.cs, mcs/class/System.Security/Makefile, mcs/class/System.Security/System.Security.dll.sources, mcs/class/System/Makefile, mcs/class/System/System.Security.Cryptography.X509Certificates/PublicKey.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2.cs
=> [build] Remove multi stage build from Mono.Security

mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/ToolTask.cs
Backport of #7202.
/cc @lewurm
=> [2017-12] [xbuild] add property that is available in msbuild

mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/ToolTask.cs
Backport of #7202.
/cc @lewurm
=> [master] [xbuild] add property that is available in msbuild

mono/mini/aot-compiler.c
=> [2017-12] [aot] Emit the same instances in hybrid aot mode as in full aot mode.

mono/Makefile.am, mono/metadata/Makefile.am
=> [icall table] add ldflags for bitcode

mcs/class/System.Web/System.Web/HttpRequest.cs
=> Properly handle non-quoted multipart content dispositions

mono/mini/TestHelpers.cs, mono/tests/Makefile.am, mono/tests/weak-fields.cs
=> [tests] Fix weak-fields on interp

mono/sgen/sgen-workers.c
=> [sgen] Check if we are exceeding the worker count limit

mcs/class/System.Net.Http/System.Net.Http.Headers/HttpHeaders.cs
=> [System.Net.Http] Better exception message for invalid header value

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/PointerValue.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/TypeMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs, mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
I was not sure about:
1. Protocol versioning process
2. CommandSet enum value
=> Add PointerValue.Value to dereference and access pointer value.

mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs
=> [System.Windows.Forms] Fix typo in implementation of Disposing property.

sdks/builds/.gitignore, sdks/builds/Makefile, sdks/builds/android.mk, sdks/builds/llvm.mk, sdks/builds/mxe.mk
=> [sdks] Merge mxe-Win32 and mxe-Win64 targets since we are building both in XA anyway

man/mono.1
=> Remove mention of MONO_THEME from man page.

mcs/class/corlib/Mono.Globalization.Unicode/SimpleCollator.cs, mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs, mcs/class/corlib/ReferenceSources/CompareInfo.cs, mcs/class/corlib/ReferenceSources/String.cs, mcs/class/corlib/System.Globalization/CultureInfo.cs, mcs/class/corlib/corefx/CompareInfo.cs, mcs/class/corlib/corefx/GlobalizationMode.cs, mcs/class/corlib/corlib.dll.sources, mcs/class/corlib/corlib_xtest.dll.sources, mcs/class/test-helpers/PlatformDetection.cs
=> [corlib] CompareInfo from CoreFX

sdks/builds/.gitignore, sdks/builds/Makefile, sdks/builds/android.mk, sdks/builds/llvm.mk, sdks/builds/mxe.mk
Backport of #7239.
/cc @luhenry
=> [2017-12] [sdks] Merge mxe-Win32 and mxe-Win64 targets since we are building both in XA anyway

sdks/builds/Makefile, sdks/builds/ios.mk, sdks/paths.mk
=> Ios sdk changes

mono/sgen/sgen-workers.c
Backport of #7180.
/cc @luhenry
=> [2017-12] [sgen] Check if we are exceeding the worker count limit

mono/sgen/sgen-workers.c
Backport of #7180.
/cc @luhenry
=> [2018-02] [sgen] Check if we are exceeding the worker count limit

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/EnumMirror.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs
Backport of #7303.
/cc @vargaz
=> [2018-02] [sdb] Fix VirtualMachine.CreateEnumMirror () so it works with types from non-root domains.

configure.ac, mcs/class/corlib/System/TermInfoReader.cs
Backport of #6960.
/cc @lewurm
=> [2018-02] [TermInfo] support new file format terminfo2 introduced with ncurses6.1

mono/mini/aot-tests.cs
Backport of #6890.
/cc @lewurm
=> [2017-12] [interp] disable test_42_arm64_dyncall_vtypebyval

mcs/tests/known-issues-interp-net_4_x, mono/tests/Makefile.am
https://github.com/mono/mono/issues/6861
=> [interp] Enable more tests

mcs/class/System.Design/System.Web.UI.Design/HtmlControlDesigner.cs, mcs/class/System.Net.Http.WinHttpHandler/System.Net.Http/WinHttpHandler.cs, mcs/class/System/System.IO/FileSystemWatcher_mobile.cs
=> [2018-02] Don't throw NotImplementedException in Dispose()

mono/metadata/appdomain.c
The original version of this code overwrote the same string over and over
again.  Because of the order of operations, when looking for siblings of
Test.dll, we would probe for Test.dll.mdb, then Test.pdb, then Test.pdb.config
(note the last one - should be Test.dll.config).
New version of the code uses fresh strings for each sibling.
Fixes https://github.com/mono/mono/issues/7262
=> [appdomain] Fix path clobbering when trying to shadow copy siblings

mono/metadata/appdomain.c
=> [2018-02] [appdomain] Fix path clobbering when trying to shadow copy siblings

configure.ac
=> [2018-02] Problem building on Arch linux #7200

packaging/MacSDK/msbuild.py
=> [msbuild] Bump to track msbuild's mono-2018-02 branch

mcs/class/System.Design/System.Web.UI.Design/HtmlControlDesigner.cs, mcs/class/System.Net.Http.WinHttpHandler/System.Net.Http/WinHttpHandler.cs, mcs/class/System/System.IO/FileSystemWatcher_mobile.cs
=> [2017-12] Don't throw NotImplementedException in Dispose()

mcs/class/System.Windows.Forms/System.Windows.Forms/TextControl.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/TextBoxTest.cs
=> [System.Windows.Forms] Fix inconsistent state of Document object

mono/utils/mono-publib.h
=> [2017-12] Fix for gcc 4.4; nominal support for older.

mono/utils/mono-publib.h
=> [2018-02] Fix for gcc 4.4; nominal support for older.

mono/mini/method-to-ir.c
Backport of #6226.
/cc @luhenry
=> [2017-10] Generalize optimization avoiding struct loads for loading a field

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
=> [2018-02] [Mono.Debugger.Soft] Properly close connections

mono/profiler/aot.c
Part of preparation for MonoClass refactoring #6925
=> [profiler] Use accessor functions for MonoClass fields

mono/metadata/w32handle.c
Fixes https://github.com/mono/mono/issues/7460
=> [w32handle] Lower minimum memory usage

mcs/class/System/System.CodeDom.Compiler/CompilerCollection.cs
=> [System] Remove compiler config sections for types which cannot be instantiated

mcs/class/System/System.CodeDom.Compiler/CompilerCollection.cs
=> [2018-02] [System] Remove compiler config sections for types which cannot be instantiated

mcs/class/corlib/Test/System/TypeTest.cs, mono/metadata/class-internals.h, mono/metadata/class.c, mono/metadata/domain.c
=> [2018-02] [metadata] An array is not an IEnumerator`1

sdks/builds/.gitignore, sdks/builds/Makefile, sdks/builds/android.mk, sdks/builds/ios.mk, sdks/builds/runtime.mk
=> [2018-02][sdks] Unify targets to build runtimes

sdks/builds/.gitignore, sdks/builds/Makefile, sdks/builds/android.mk, sdks/builds/ios.mk, sdks/builds/runtime.mk
=> [2017-12][sdks] Unify targets to build runtimes

mcs/class/System/System.Net/WebOperation.cs, mcs/class/System/System.Net/WebRequestStream.cs
Fixes https://github.com/mono/mono/issues/7094.
=> [System]: WebRequestStream now throws correct exception on cancellation.

mcs/tools/mkbundle/mkbundle.cs
=> [master] [mkbundle] Fix generated file when passing --bundled-header

mcs/tools/mkbundle/mkbundle.cs
Backport of #6730.
/cc @luhenry
=> [2018-02] [mkbundle] Fix generated file when passing --bundled-header

mono/mini/interp/interp.c, mono/mini/interp/transform.c
=> [interp] Pinvoke fixes

mono/mini/interp/transform.c
=> [interp] Fix stack usage after throw

mcs/class/System/System.Net/WebOperation.cs, mcs/class/System/System.Net/WebRequestStream.cs
=> [2018-02] [System]: WebRequestStream now throws correct exception on cancellation.

mono/metadata/icall.c, mono/tests/valuetype-equals.cs
=> Implement native ValueType Equals and GetHashCode support for pointer fields

mcs/class/System.Windows.Forms/System.Windows.Forms/ErrorProvider.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/RichTextBox.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/TextBox.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/TextBoxBase.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/TextControl.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ThemeVisualStyles.cs
=> [System.Windows.Forms] Fix lifetime of Graphics objects in TextBox controls

mcs/class/referencesource/mscorlib/system/diagnostics/assert.cs, mcs/class/referencesource/mscorlib/system/exception.cs, mcs/class/referencesource/mscorlib/system/gc.cs, mcs/class/referencesource/mscorlib/system/missingmemberexception.cs, mcs/class/referencesource/mscorlib/system/timespan.cs
=> [2018-02] [bcl] Comment/stub out some unused icalls to prevent problems with AOT.

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/mini/mini-exceptions.c, mono/utils/Makefile.am, mono/utils/mono-merp.c, mono/utils/mono-merp.h
=> [runtime] Add MS telemetry reporter for unmanaged exceptions

mono/mini/mini-generic-sharing.c
Fixes test_0_marshal_struct_delegate
=> [interp] Fix return of value type from interp to native

mono/metadata/object-offsets.h, mono/mini/aot-runtime-wasm.c, mono/mini/exceptions-wasm.c, mono/mini/mini-exceptions.c, mono/mini/mini-runtime.c, mono/mini/mini-wasm.c, mono/mini/mini-wasm.h, sdks/wasm/Makefile, sdks/wasm/driver.c, sdks/wasm/library_mono.js, sdks/wasm/sample.cs, sdks/wasm/sample.html, sdks/wasm/test.js
This supports setting, resolving and hitting breakpoints.
This support reporting stack frames and their params & locals.
=> [WASM] Initial code drop for debugger

mcs/class/Facades/System.Net.Http.Rtc/AssemblyInfo.cs, mcs/class/Facades/System.Net.Http.Rtc/Makefile, mcs/class/Facades/System.Net.Http.Rtc/System.Net.Http.Rtc.dll.sources, mcs/class/Facades/System.Net.Http.Rtc/TypeForwarders.cs, mcs/class/Facades/System.Resources.Reader/AssemblyInfo.cs, mcs/class/Facades/System.Resources.Reader/Makefile, mcs/class/Facades/System.Resources.Reader/System.Resources.Reader.dll.sources, mcs/class/Facades/System.Resources.Reader/TypeForwarders.cs, mcs/class/Facades/System.Resources.Writer/AssemblyInfo.cs, mcs/class/Facades/System.Resources.Writer/Makefile, mcs/class/Facades/System.Resources.Writer/System.Resources.Writer.dll.sources, mcs/class/Facades/System.Resources.Writer/TypeForwarders.cs, mcs/class/Facades/subdirs.make
Some of them we had on mobile only, others were missing completely.
Fixes https://github.com/mono/mono/issues/7536
=> [Facades] Add missing Facades that exist in .NET 4.7.1

mono/metadata/debug-mono-ppdb.c
Fixes https://github.com/mono/mono/issues/6812.
=> [ppdb] Set the column number in mono_ppdb_lookup_location ().

mcs/class/Facades/System.Net.Http.Rtc/AssemblyInfo.cs, mcs/class/Facades/System.Net.Http.Rtc/Makefile, mcs/class/Facades/System.Net.Http.Rtc/System.Net.Http.Rtc.dll.sources, mcs/class/Facades/System.Net.Http.Rtc/TypeForwarders.cs, mcs/class/Facades/System.Resources.Reader/AssemblyInfo.cs, mcs/class/Facades/System.Resources.Reader/Makefile, mcs/class/Facades/System.Resources.Reader/System.Resources.Reader.dll.sources, mcs/class/Facades/System.Resources.Reader/TypeForwarders.cs, mcs/class/Facades/System.Resources.Writer/AssemblyInfo.cs, mcs/class/Facades/System.Resources.Writer/Makefile, mcs/class/Facades/System.Resources.Writer/System.Resources.Writer.dll.sources, mcs/class/Facades/System.Resources.Writer/TypeForwarders.cs, mcs/class/Facades/subdirs.make
=> [2018-02] [Facades] Add missing Facades that exist in .NET 4.7.1

.github/ISSUE_TEMPLATE.md
Correcting typos for ISSUE_TEMPLATE.md
=> Correcting typos for ISSUE_TEMPLATE.md

mcs/class/System.Windows.Forms/Test/System.Windows.Forms/FormTest.cs
=> [System.Windows.Forms] Make Form scaling tests platform independent.

mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/MenuAPI.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/MonthCalendar.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/TextBox.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStripDropDown.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ToolTip.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/ControlTest.cs
Updates code for top-level windows to match the behavior of .NET Framework more closely. The relevant unit tests were run on Windows 10 with .NET Framework 4.7.1.
=> [System.Windows.Forms] Update code for top-level windows

mcs/class/System.Windows.Forms/Makefile, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/PrintPreviewControlTest.cs
=> [System.Windows.Forms] Fix custom test targets in makefile.

mcs/class/System.XML/mobile_System.Xml.dll.sources
d4816ef1abcfc5b3dea41a87fe5a7a4c4a3781ed
More fixes for #7302
=> [System.Xml] Update source file location from commit

mcs/class/System.XML/mobile_System.Xml.dll.sources
=> [2018-02] [System.Xml] Update source file location from commit

mcs/class/System.XML/mobile_System.Xml.dll.sources
=> [2017-12] [System.Xml] Update source file location from commit

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/mini/mini-exceptions.c, mono/utils/Makefile.am, mono/utils/mono-merp.c, mono/utils/mono-merp.h
Backport of #7451.
/cc @luhenry
https://github.com/mono/mono/issues/7072
=> [2018-02] [runtime] Add MS telemetry reporter for unmanaged exceptions

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/mini/mini-exceptions.c, mono/utils/Makefile.am, mono/utils/mono-merp.c, mono/utils/mono-merp.h
Backport of #7451.
/cc @luhenry
https://github.com/mono/mono/issues/7072
=> [2017-12] [runtime] Add MS telemetry reporter for unmanaged exceptions

mcs/class/Facades/subdirs.make
=> [2018-02] [Facades] Make System.Net.Http.Rtc.dll a net_4_x only facade

mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLite3.cs
=> [Mono.Data.Sqlite] Throw better exception for missing mobile support

mono/metadata/icall.c, mono/mini/mini-exceptions.c, mono/utils/mono-merp.c, mono/utils/mono-merp.h
Backport of #7604.
/cc @lewurm
=> [2018-02] [merp] only target macOS, HOST_DARWIN includes iOS etc. as well

mono/metadata/icall.c, mono/mini/mini-exceptions.c, mono/utils/mono-merp.c, mono/utils/mono-merp.h
Backport of #7604.
/cc @lewurm
=> [2017-12] [merp] only target macOS, HOST_DARWIN includes iOS etc. as well

mono/profiler/log.c
=> [profiler] Increment ref count of an image's method while we're keeping around pointers to it.

mono/mini/mini-runtime.c, mono/tests/Makefile.am
Backport of #7529.
/cc @vargaz
=> [2018-02] [tests] Disable delegate-15.exe in the full-aot profile.

mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs, mcs/class/System/System.Net/ServicePointScheduler.cs, mcs/class/System/System.Net/WebCompletionSource.cs, mcs/class/System/System.Net/WebOperation.cs, mcs/class/System/System.Net/WebRequestStream.cs, mcs/class/System/System.Net/WebResponseStream.cs
=> [System]: Introduce `WebCompletionSource<T>` and use it in `WebOperation`.

mcs/class/Makefile
=> [build] Fixes mcs only dist build

mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs, mcs/class/System/System.Net/ServicePointScheduler.cs, mcs/class/System/System.Net/WebCompletionSource.cs, mcs/class/System/System.Net/WebOperation.cs, mcs/class/System/System.Net/WebRequestStream.cs, mcs/class/System/System.Net/WebResponseStream.cs
=> [2018-02] [System]: Introduce `WebCompletionSource\u003cT\u003e` and use it in `WebOperation`.

mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/ControlTest.cs
=> [System.Windows.Forms] Fix bounds manipulation in Control.DrawToBitmap

mcs/errors/cs1013-1.cs, mcs/errors/cs1021-4.cs, mcs/mcs/cs-tokenizer.cs, mcs/tests/test-binaryliteral.cs, mcs/tools/mkbundle/mkbundle.cs
Had some time between meetings.
Includes the relevant Roslyn tests.
Contributes to https://github.com/mono/mono/issues/6854
=> Implement C#7 binary literals

Makefile.am, sdks/builds/android.mk, sdks/builds/ios.mk, sdks/builds/runtime.mk, support/Makefile.am
Backport of #7652.
/cc @vargaz
=> [2017-12] [sdks] Fix concurrent building of MonoAotOffsetsDumper.exe + Simplify building of support library

configure.ac
This should've happened once we pushed the first 5.10 release to stable but let's do it now at least :)
=> [2017-12] Bump version to 5.10.1

mono/utils/mach-support-arm64.c
=> [arm64] Add a known TLS offset.

mcs/packages/Makefile, scripts/Makefile.am, scripts/csc-dim.in
=> Add csc-dim as a prototype of default interface implementation

Makefile.am, sdks/builds/android.mk, sdks/builds/ios.mk, sdks/builds/runtime.mk, support/Makefile.am
=> [2018-02] [sdks] Fix concurrent building of MonoAotOffsetsDumper.exe + Simplify building of support library

mcs/packages/Makefile, scripts/Makefile.am, scripts/csc-dim.in
=> [2018-02] Add csc-dim as a prototype of default interface implementation

mono/metadata/sgen-mono.c, mono/tests/Makefile.am
Fixes https://github.com/mono/mono/issues/7199
=> [sgen] Finish thread pool work before shutting down threads

man/mono.1
=> Update man page, MONO_DISABLE_AIO is now MONO_ENABLE_AIO.

mono/tests/Makefile.am, mono/tests/tailcall-interface-conservestack.il, mono/tests/tailcall-interface-justrun.il, mono/tests/tailcall-interface.cs
These all fail on Mono. All but one succeeds on desktop.
=> [Tailcall] Add interface tailcall tests, and generics thereof.

configure.ac, mono/utils/mono-time.c
=> Backport new boottime

mono/metadata/assembly.c
=> [2018-02] [loader] Don't load framework Facade assemblies that are older than expected.

mono/mini/mini-arm.c, mono/tests/libtest.c, mono/tests/pinvoke11.cs
fixes https://github.com/mono/mono/issues/7449
/cc @joncham
=> [arm] fix stack alignment for structs

configure.ac
=> Bumps roslyn to 2.7.0

mcs/mcs/statement.cs, mcs/tests/test-928.cs, mcs/tests/ver-il-net_4_x.xml
=> [mcs] Fixes codegen for null fixed string statement

mcs/mcs/tuples.cs, mcs/tests/test-tuple-10.cs, mcs/tests/ver-il-net_4_x.xml
=> [mcs] Adds cloning for TupleLiteralElement expressions

mcs/build/common/basic-profile-check.cs, mcs/build/profiles/basic.make, mcs/class/System.Web.DynamicData/Test/System.Web.DynamicData/MetaColumnTest.cs, mcs/class/System/common.sources, mcs/class/corlib/ReferenceSources/Buffer.cs, mcs/class/corlib/ReferenceSources/String.cs, mcs/class/corlib/System.Runtime.InteropServices/Marshal.cs, mcs/class/corlib/Test/System/StringTest.cs, mcs/class/corlib/corefx/CompareInfo.cs, mcs/class/corlib/corefx/MemoryExtensions.cs, mcs/class/corlib/corlib.dll.sources, mcs/class/corlib/corlib_xtest.dll.sources, mcs/class/referencesource/mscorlib/system/globalization/textinfo.cs, mcs/class/referencesource/mscorlib/system/stringcomparer.cs, mcs/errors/cs0419.cs, mcs/tools/cil-stringreplacer/Makefile
=> [corlib] CoreFX String

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
This reverts commit e7ba41d14c7e1dc6e860e6e9c5a3db05686d2c5a.
=> Revert "Swap Close/Dispose calls so that the receiver_thread_main loop will be properly interrupted (#7390)"

mcs/class/System/System.Net/HttpWebRequest.cs, mcs/class/System/System.Net/ServicePointScheduler.cs, mcs/class/System/System.Net/WebCompletionSource.cs, mcs/class/System/System.Net/WebOperation.cs, mcs/class/System/System.Net/WebResponseStream.cs
=> [2018-02] [System]: Fix a race condition that was exposed by #7358 (see #7668).

sdks/builds/android.mk
Backport of #7768.
/cc @luhenry
=> [2018-02] [sdks] Fix Android build

sdks/builds/android.mk
Backport of #7768.
/cc @luhenry
=> [2017-12] [sdks] Fix Android build

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
Backport of #7745.
/cc @luhenry
=> [2018-02] Revert "Swap Close/Dispose calls so that the receiver_thread_main loop will be properly interrupted (#7390)"

sdks/builds/Makefile
Backport of #7775.
/cc @luhenry
=> [2017-12] [sdks] Fix Android build on Linux

sdks/builds/Makefile
Backport of #7775.
/cc @luhenry
=> [2018-02] [sdks] Fix Android build on Linux

mono/mini/aot-compiler.c, mono/mini/interp/interp.c, mono/mini/interp/transform.c, mono/mini/mini-exceptions.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini-trampolines.c
The assemblies need to be AOTed using:
--aot=full,interp
and run using:
--full-aot --interp
=> [interp] Improve mixed mode execution support, using full-aot+interp as the configuration.

mcs/class/corlib/System/Console.cs, mcs/tools/mkbundle/mkbundle.cs
This documentation has not been updated, despite the fact that the capabilities were implemented in the TermInfo driver.
=> Remove incorrect docs

mono/mini/builtin-types.cs, mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
update definition to be in sync with XI
=> [interp] support increment and decrement of nint/nuint

mcs/class/System/System_xtest.dll.sources
=> Bump corefx to bring a fix for #7696

mcs/class/System.Windows.Forms/System.Windows.Forms/FileDialog.cs
=> [System.Windows.Forms] Fallback to listing drives in My Computer using System.IO.DriveInfo.

CODEOWNERS
=> CodeOwners update

mono/mini/exceptions-s390x.c, mono/mini/exceptions-sparc.c, mono/mini/exceptions-x86.c, mono/mini/mini-arm.c, mono/mini/mini-arm64.c, mono/mini/mini-llvm.c, mono/mini/mini-mips.c, mono/mini/mini-ppc.c, mono/mini/mini-s390x.c, mono/mini/mini-sparc.c, mono/mini/mini-wasm.c, mono/mini/mini-x86.c
Best effort to replace direct MonoClass field access by getters.
=> [mini] Use MonoClass getters on non-AMD64 platforms

sdks/builds/android.mk, sdks/builds/runtime.mk
Backport of #7817.
/cc @luhenry
=> [2018-02] [sdks] Fix Android build for toolchain

sdks/builds/android.mk, sdks/builds/runtime.mk
Backport of #7817.
/cc @luhenry
=> [2017-12] [sdks] Fix Android build for toolchain

mono/metadata/w32handle.c
Fixes https://github.com/mono/mono/issues/7460
=> [w32handle] Lower minimum memory usage (2nd attempt)

mono/mini/method-to-ir.c
=> [mini] Use MonoClass getters in method-to-ir.c

mono/metadata/sre-save.c, mono/mini/interp/transform.c, mono/mini/mini-runtime.c, mono/mini/mini.c, tools/monograph/monograph.c, tools/pedump/pedump.c
Merge when the "Linux x64 Checked Build" lane gets past the `make` step.
Misc cleanup commits to mop-up the MonoClass getters task #6925
=> MonoClass getters mop-up PR

sdks/builds/Makefile
Backport of #7801.
/cc @vargaz
=> [2017-12] [sdks] Fix the ios sdk build.

sdks/builds/Makefile
=> [sdks] Fix the ios sdk build. (#7801)

mono/mini/aot-compiler.c, mono/mini/interp/interp.c
Backport of #7780.
/cc @lewurm
=> [2018-02] [interp] improve error message and add another interp_in signature

mono/mini/builtin-types.cs, mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
Backport of #7778.
/cc @lewurm
=> [2018-02] [interp] support increment and decrement of nint/nuint

mono/metadata/icall-def.h, sdks/builds/ios.mk
backport of https://github.com/mono/mono/pull/7779
=> [2018-02] [icall] remove DISABLE_PROCESS_HANDLING

mono/metadata/threads.c, mono/utils/mono-threads.c
Fixes https://github.com/mono/mono/issues/7786
=> [threads] Remove suspicious mono_gchandle_free

mono/metadata/threads.c, mono/utils/mono-threads.c
Backport of #7812.
/cc @luhenry
Fixes https://github.com/mono/mono/issues/7786
=> [2018-02] [threads] Remove suspicious mono_gchandle_free

mono/metadata/threads.c, mono/utils/mono-threads.c
Backport of #7812.
/cc @luhenry
Fixes https://github.com/mono/mono/issues/7786
=> [2017-12] [threads] Remove suspicious mono_gchandle_free

scripts/ci/run-test-default.sh
=> [ci] Bundle nunit xml results in a .tar file

mcs/class/Makefile
=> [build] Update monolite package to support cil-stringreplacer

mono/metadata/boehm-gc.c, mono/metadata/marshal-ilgen.c, msvc/monograph.vcxproj, tools/monograph/Makefile.am, tools/monograph/monograph.c
- Fixup recent ilgen change
- Fix linking error in *monograph* due to static linking an extra copy of metadata.
- Fix runtime crash in `monograph`, too, while I'm at it.
=> [runtime] One more MonoClass getter fixup

mcs/build/profiles/basic.make, mcs/tools/cil-stringreplacer/Makefile
=> [build] Fixes bootstrap invocation of cil-stringreplacer

packaging/MacSDK/msbuild.py
=> [msbuild] Bump to pick up updates

mcs/class/corlib/Test/System.Collections.Concurrent/ConcurrentDictionaryTests.cs
=> [corlib] Restores ConcurrentDictionary serialization support.

mono/mini/iltests.il, mono/mini/method-to-ir.c
=> [jit] Add signature checking for CALLI.

mono/mini/iltests.il, mono/mini/method-to-ir.c
Backport of #7832.
/cc @vargaz
=> [2018-02] [jit] Add signature checking for CALLI.

mono/mini/iltests.il, mono/mini/method-to-ir.c
Backport of #7832.
/cc @vargaz
=> [2017-12] [jit] Add signature checking for CALLI.

sdks/builds/llvm.mk
Backport of #7897.
/cc @luhenry
=> [2018-02] [sdks] Fix usage of MXE for XA

sdks/builds/llvm.mk
Backport of #7897.
/cc @luhenry
=> [2017-12] [sdks] Fix usage of MXE for XA

sdks/builds/android.mk, sdks/builds/llvm.mk
Backport of #7910.
/cc @luhenry
=> [2017-12] [sdks] Fix LLVM build on Linux for XA + Fix MXE usage on non-Darwin platforms

sdks/builds/android.mk, sdks/builds/llvm.mk
Backport of #7910.
/cc @luhenry
=> [2018-02] [sdks] Fix LLVM build on Linux for XA + Fix MXE usage on non-Darwin platforms

sdks/builds/llvm.mk
Backport of #7917.
/cc @luhenry
=> [2017-12] [sdks] Fix LLVM build for XA

sdks/builds/llvm.mk
Backport of #7917.
/cc @luhenry
=> [2018-02] [sdks] Fix LLVM build for XA

mono/metadata/class-internals.h
Backport of #7906.
/cc @lewurm
=> [2018-02] [perfcounters] fix alignment issue on 32bit

mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mcs/class/corlib/Makefile, mcs/class/corlib/System.Security.Cryptography/CryptoConfig.Mobile.cs, mcs/class/corlib/System.Security.Cryptography/CryptoConfig.cs, mcs/class/corlib/Test/System.Security.Cryptography/CryptoConfigTest.cs, mcs/class/corlib/Test/System.Security.Cryptography/SignatureDescriptionTest.cs, mcs/class/corlib/corlib.dll.sources
=> [2018-02]  [corlib] Enable machine.config dependant version of CryptoConfig for net_4_x profile only

packaging/MacSDK/msbuild.py
=> Bump msbuild to track xplat-master

msvc/scripts/genproj.cs
=> When using fallback profile selection don't build the projects that were missing a profile

mcs/class/System.Drawing/Makefile, mcs/class/System.Drawing/System.Drawing_xtest.dll.sources, mcs/class/test-helpers/PlatformDetection.cs, scripts/ci/run-test-default.sh
So @filipnavara can play with it :)
=> [System.Drawing] Enable corefx xunit tests

mcs/class/System.Drawing/System.Drawing_xtest.dll.sources
=> [System.Drawing] Include CoreFX GraphicsPath and Region tests.

mcs/class/corlib/System.Runtime.InteropServices.RuntimeInformation/RuntimeInformation.cs, mono/metadata/sgen-mono.c, mono/mini/aot-runtime-wasm.c, mono/utils/mono-time.c, sdks/wasm/main.cs
This PR replaces #7877 and #7874.
I'm doing it this way to flush most of the fixes as #7874 has a contentious change
that spilled over into #7887, which remains unfinished.
=> [wasm] Multiple fixes for the WASM target extracted for other PRs.

mono/utils/mono-sigcontext.h
Backport of #7936.
/cc @lewurm
=> [2018-02] [ppc] use ucontext_t

mono/utils/mono-sigcontext.h
Backport of #7936.
/cc @lewurm
=> [2017-12] [ppc] use ucontext_t

mcs/class/Facades/System.Memory/AssemblyInfo.cs, mcs/class/Facades/System.Memory/Makefile, mcs/class/Facades/System.Memory/System.Memory.dll.sources, mcs/class/Facades/System.Memory/TypeForwarders.cs, mcs/class/Facades/subdirs.make
Contains only the types we have right now.
Fixes https://github.com/mono/mono/issues/7610
=> [Facades] Add System.Memory facade to mobile profiles

mcs/class/System.ServiceModel/System.ServiceModel.Description/ContractDescriptionGenerator.cs, mcs/class/System.ServiceModel/Test/System.ServiceModel.Description/ContractDescriptionTest.cs
Fixes https://github.com/mono/mono/issues/7305
=> Fix stack overflow on ServiceHost initialisation

mcs/class/System/Test/System.Net.Sockets/SocketTest.cs
Backport of #7533.
/cc @luhenry
=> [2017-12] [System] Disable SocketTest.AcceptBlockingStatus

mcs/class/Facades/System.Memory/AssemblyInfo.cs, mcs/class/Facades/System.Memory/Makefile, mcs/class/Facades/System.Memory/System.Memory.dll.sources, mcs/class/Facades/System.Memory/TypeForwarders.cs, mcs/class/Facades/subdirs.make
=> [2018-04] [Facades] Add System.Memory facade to mobile profiles

mcs/class/Facades/System.Memory/AssemblyInfo.cs, mcs/class/Facades/System.Memory/Makefile, mcs/class/Facades/System.Memory/System.Memory.dll.sources, mcs/class/Facades/System.Memory/TypeForwarders.cs, mcs/class/Facades/subdirs.make
=> [2018-02] [Facades] Add System.Memory facade to mobile profiles

msvc/scripts/Mono.CSharp.pre, msvc/scripts/genproj.cs
We weren't emitting the postbuild script.
=> [genproj] Add Mono.CSharp.pre and fix genproj postbuild bug

mcs/class/Facades/System.Memory/AssemblyInfo.cs, mcs/class/Facades/System.Memory/Makefile, mcs/class/Facades/System.Memory/System.Memory.dll.sources, mcs/class/Facades/System.Memory/TypeForwarders.cs, mcs/class/Facades/subdirs.make
=> [2017-12] [Facades] Add System.Memory facade to mobile profiles

mcs/class/System/Test/System.Net.Sockets/SocketTest.cs
Backport of #7533.
/cc @luhenry
=> [2018-02] [System] Disable SocketTest.AcceptBlockingStatus

sdks/builds/mxe.mk
Backport of #8006.
/cc @luhenry
=> [2017-12] [sdks] Fix MXE_PREFIX for XA

sdks/builds/mxe.mk
Backport of #8006.
/cc @luhenry
=> [2018-02] [sdks] Fix MXE_PREFIX for XA

sdks/builds/mxe.mk
Backport of #8006.
/cc @luhenry
=> [2018-04] [sdks] Fix MXE_PREFIX for XA

mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
Backport of #8021.
/cc @lewurm
=> [2018-02] [interp] do not bake object reference into code stream

sdks/builds/android.mk, sdks/builds/unzip-android-archive.sh
Backport of #8015.
/cc @luhenry
=> [2018-04] [SDKS] Fix Android SDK build on Linux

sdks/builds/android.mk, sdks/builds/unzip-android-archive.sh
Backport of #8015.
/cc @luhenry
=> [2018-02] [SDKS] Fix Android SDK build on Linux

sdks/builds/android.mk, sdks/builds/unzip-android-archive.sh
Backport of #8015.
/cc @luhenry
=> [2017-12] [SDKS] Fix Android SDK build on Linux

mcs/errors/cs8326.cs, mcs/errors/cs8327.cs, mcs/mcs/cs-parser.jay, mcs/mcs/cs-tokenizer.cs, mcs/mcs/expression.cs, mcs/tests/test-ref-11.cs, mcs/tests/ver-il-net_4_x.xml
=> [mcs] Implements C# 7.2 conditional ref expression

mcs/class/System/System.Net/HttpWebRequest.cs, mcs/class/System/System.Net/ServicePointScheduler.cs, mcs/class/System/System.Net/WebRequestStream.cs, mcs/class/System/System.Net/WebResponseStream.cs
=> [2018-02] [System]: Fix memory leak in the web stack (partial fix of #7356).

mono/btls/Makefile.am
Backport of #8038.
/cc @luhenry
=> [2017-12] [SDKS] fix Linux (and possibly other OSes) build for Android

mcs/class/System/System.Net/HttpWebRequest.cs, mcs/class/System/System.Net/ServicePointScheduler.cs, mcs/class/System/System.Net/WebRequestStream.cs, mcs/class/System/System.Net/WebResponseStream.cs
=> [2018-04] [System]: Fix memory leak in the web stack (partial fix of #7356).

mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
Backport of #8021.
/cc @lewurm
=> [2018-04] [interp] do not bake object reference into code stream

configure.ac
Backport of #7999.
/cc @vargaz
=> [2018-02] [runtime] Fix --disable-btls.

configure.ac
Backport of #7999.
/cc @vargaz
=> [2018-04] [runtime] Fix --disable-btls.

mono/utils/mono-threads-coop.c, mono/utils/mono-threads-state-machine.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
These are the last two uses of `SelfSuspendWait` and `AsyncSuspendWait`
=> [coop] We never return SelfSuspendWait and AsyncSuspendWait

mono/mini/interp/interp.c
Backport of #8003.
/cc @lewurm
=> [2018-02] [interp] workaround undefined behaviour in r8 to u1 cast

mono/mini/interp/interp.c
Backport of #8003.
/cc @lewurm
=> [2018-04] [interp] workaround undefined behaviour in r8 to u1 cast

mono/btls/Makefile.am
Backport of #8038.
/cc @luhenry
=> [2018-02] [SDKS] fix Linux (and possibly other OSes) build for Android

mono/btls/Makefile.am
Backport of #8038.
/cc @luhenry
=> [2018-04] [SDKS] fix Linux (and possibly other OSes) build for Android

mono/mini/cpu-s390x.md, mono/mini/mini-s390x.c, mono/mini/mini-s390x.h
* Compete float32 support
* Fix float register saving/restoring
* Add tailcall_membase support
* Enhance conditions under which tailcalls are valid
=> [s390x] Float32
