mono/mini/intrinsics.c, mono/mini/llvm-jit.cpp, mono/mini/mini-llvm.c, mono/mini/mini-ops.h, netcore/CoreFX.issues.rsp
Before this PR `Pow`, `Min` and `Max` worked only for `float`
```csharp
static float Test1(float x) => MathF.Pow(x, 2);
static double Test2(double x) => Math.Pow(x, 2);
// Min and Max require `--ffast-math` mode for optimal codegen
static float Test3(float x, float y) => MathF.Min(x, y);
static double Test4(double x, double y) => Math.Min(x, y);
static float Test5(float x, float y) => Math.Max(x, y);
static double Test6(double x, double y) => Math.Max(x, y);
```
Asm:
```asm
0000000000000000	vmulss	%xmm0, %xmm0, %xmm0
0000000000000004 …
```
=> Make Math.Pow, Min and Max for doubles intrinsics

configure.ac
Instead `./autogen.sh --with-llvm=<path>` should be used if a build from `external/llvm` is not preferred.
The old behavior was confusing when a `llvm-config` is on `$PATH`, which can be the case when you have LLVM packages installed on a Linux distribution. It picked that up when `./autogen.sh --enable-llvm` was used.
/cc @brianrob
=> [configure] remove autodection of llvm-config in $PATH

mcs/class/System.Windows.Forms/System.Windows.Forms/TreeNodeCollection.cs
The UIA event doesn't emited by means of insertion a new `TreeNode` to a `TreeNodeCollection` of the respective `TreeNode`.
=> [WinForms] Fix UIA event on node insertions into a `TreeView` object

mcs/class/Mono.Posix/Mono.Posix_test.dll.sources, mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs, mcs/class/Mono.Posix/Test/Mono.Unix.Native/OFDLockTest.cs, support/map.c, support/map.h
Add F_OFD_GETLK, F_OFD_SETLK and F_OFD_SETLKW to FcntlCommand. These
commmands are similar to F_GETLK, F_SETLK and F_SETLKW but operate on a
per-open-file-description lock instead of a per-process lock and avoid the
problem that the locks are released when close(dup(fd)) is called. See
https://lwn.net/Articles/586904/ for more information.
This commit also reruns create-native-map but keeps manual changes from
ed892ccf27849c082ce6ca46fa8b96d86ca7c329,
b522eab5ff5466debaacf9e971e26cfc464ebba5 and
22b6b9581418260397b701c17b16c3eb55136de7.
In [create-native-map.diff.txt](https://github.com/mono/mono/files/3557077/create-native-map.diff.txt) you can see the difference between the commited `map.[ch]` and the one `create-native-map.exe` wants to create:
- Manually inserted changes for NetBSD …
=> [Mono.Posix] Add FcntlCommand.F_OFD_{GETLK,SETLK,SETLKW}

mono/mini/mini-generic-sharing.c
This reverts commit ee90fc601e762dc31eeb90fc61b6305246ad5275 (also see https://github.com/mono/mono/pull/4878 ).
The device was released November 2014.  I think it's fair to assume it isn't widely used anymore.
=> Revert "[android] add hardware specific workaround for Nexus9 in armv7 mode"

mono/mini/mini.c
Fixes https://github.com/mono/mono/issues/14080
Consider the following example:
```csharp
static void CommonCallTarget () { }
static void TailA () {
tailcall CommonCallTarget ();
}
static void TailB () {
tailcall CommonCallTarget ();
}
```
Since `TailA` and `TailB` are tailcalling into `CommonCallTarget`, the resolution at patch-time is a bit tricky, that is, since it's a jump-like instruction the patching machinery won't know where it was called from. That's why we maintain a global hashtable `jump_target_hash` where each jump-site is signed up to be patched. At patch-time we know the target method (in the example `CommonCallTarget`), but since we don't know where we are coming from, we will just apply all patches for that target.
This works since ages, so why did it crash on arm64 …
=> [mini] publish global patches after JitInfo has been added

mono/arch/x86/x86-codegen.h, mono/mini/mini-amd64.c, mono/mini/mini-x86.c, mono/mini/mini-x86.h
amd64_patch has two incorrect looking probably unused cases.
g_assert(0) and fix them.
call and jmp indirect (one case)
move reg RIP relative
x86_patch is large-ish inline macro.
Presumably for sharing with amd64, not inlining.
Restructure as an inline function, called once.
Try to make the code a little clearer also, with same functionality and efficiency
(modulo the optimized perf of "if i == 4" vs. "if i")
i.e. speak of instruction_size and offset_size, not pos and boolean size.
Add to x86_patch the ability to patch jmp/call indirect,
as amd64_patch has, but which was incorrect.
This would seem useful for a later change (using "thunks"
to patch nearby data instead of patching aligned instructions,
indirect call/jmp vs. direct).
amd64_patch largely delegates to x86_patch.
One case …
=> Cleanup x86_patch and amd64_patch.

mono/eglib/Makefile.am, mono/eglib/test/.gitignore, mono/eglib/test/Makefile.am, scripts/ci/run-test-default.sh, scripts/ci/run-test-helix.sh
Update mono/eglib SUBDIRS to build tests after eglib is built.
Add a check-local automake rule.
Add CI steps to run the eglib tests.
=> [runtime] Make eglib tests run on CI

mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
This PR fixes some invalid il_offsets associated with instructions, making sure that every IL instruction has a corresponding IR instruction (which is mainly useful when resolving branches)
=> [interp] Fixes for il_offsets associated with instructions

mono/metadata/handle.c, mono/metadata/handle.h
w/o HANDLE_FUNCTION_ENTER or SETUP_ICALL_FUNCTION.
This is based on my read of https://github.com/mono/mono/pull/16487.
=> [coop] Allow SETUP_ICALL_FRAME (i.e. a loop) to reference calling function.

mono/mini/debugger-agent.c, mono/mini/debugger-engine.c
Fixing single step inside Exception on Android...
The method is null because on ss_create_init_args the IL is -1 when calling method Mono_UnhandledException_internal what I think it's expected, because of that I ignore the single step on android if there is no method. (debugger-engine.c)
After that the sequence point cannot be found because it's calling a method of class DynamicMethodNameCounter what I think it's expected, because of that I remove the assert on android. (debugger-agent.c)
Fixes #14772
Backport of #16596.
=> [2019-08] [debugger][android] Fixing single step inside Exception on Android

mono/mini/aot-compiler.c
=> [aot] Avoid crashing with --aot=llvm is used in a runtime without llvm support.

mono/mini/intrinsics.c, mono/mini/llvm-jit.cpp, mono/mini/mini-llvm.c, mono/mini/mini-ops.h
[Buffer.MemoryCopy](https://github.com/dotnet/coreclr/blob/d951f5f0ee8862f954c69a4fd9e05184bad15d25/src/System.Private.CoreLib/shared/System/Buffer.cs#L93-L100) calls [Memmove](https://github.com/dotnet/coreclr/blob/d951f5f0ee8862f954c69a4fd9e05184bad15d25/src/System.Private.CoreLib/shared/System/Buffer.cs#L144) which is manually unrolled and calls [__Memmove](https://github.com/dotnet/coreclr/blob/d951f5f0ee8862f954c69a4fd9e05184bad15d25/src/System.Private.CoreLib/shared/System/Buffer.cs#L307-L308) (InternalCall) if array is bigger than [MemmoveNativeThreshold](https://github.com/dotnet/coreclr/blob/52651008a5fb72eb678467cd2eb42aac4e5334e8/src/System.Private.CoreLib/shared/System/Buffer.Unix.cs#L24). I am not sure should we replace the whole `Memmove` with `llvm.memmove.p0i8.p0i8.i64` …
=> LLVM: Make Buffer.Memmove intrinsic

mono/metadata/icall.c
Prevents `ves_icall_System_Reflection_RuntimeAssembly_GetTopLevelForwardedTypes_raw USED 1265 handles` from appearing when running `make run-tests-corefx-System.Runtime.Tests`.
=> [netcore] Add handle frame to loop body in GetTopLevelForwardedTypes

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c, mono/mini/interp/transform.c
=> [interp] Remove varargs from InterpFrame and pass it on stack instead

netcore/Makefile, netcore/NuGet.config, netcore/init-tools.sh
Remove ASP.NET sample (we currently have to download apsnet runtime everytime)
instead we can do:
```
dotnet new webapp
```
and do `make patch-app APP_PATH=/path/to/myasp` (works for any kind of apps/templates)
=> [netcore] Makefile clean up

global.json, mono/mini/mini-llvm-cpp.cpp, mono/mini/mini-llvm-cpp.h, mono/mini/mini-llvm.c, netcore/Makefile
It turns out it's not enough to set global fast math parameters, it's also required to mark some instructions as "fast" (see https://llvm.org/docs/LangRef.html#fast-math-flags) like, for instance, clang does, see https://godbolt.org/z/U8TFST
E.g. all optimizations inside [SimplifyLibCalls](https://llvm.org/doxygen/SimplifyLibCalls_8cpp_source.html) pass (it's a subpass of InstCombine) need it.
Example:
```csharp
static float Test(float x)
{
return MathF.Pow(x, 0.5f);
}
```
Before (Unoptimized):
```llvm
define monocc float @"HelloWorld.Program:Test (single)"(float %arg_x) #0 {
BB0:
br label %BB3
BB3:                                              ; preds = %BB0
br label %BB2
BB2:                                              ; preds = %BB3
%t21 = call float @llvm.pow.f32(float %arg_x, float …
```
=> Improve Fast-Math mode for LLVM

mono/metadata/cominterop.c, mono/metadata/jit-icall-reg.h
This is important for mscoree-style embedding. When native host creates domains and loads to newly created domain, it's important to have it set correctly before hitting managed code. This happens with WiX installer tool, that creates domain with temporary dir path as a base, and loads assembly to it, which otherwise will fail file look up.
=> [cominterop] Maintain object domain around ccw wrapper calls.

netcore/CoreFX.issues.rsp, netcore/System.Private.CoreLib/resources/SR.cs, netcore/System.Private.CoreLib/src/System.Threading/Overlapped.cs, netcore/System.Private.CoreLib/src/System.Threading/ThreadPoolBoundHandle.cs
Changes:
1) Made it Nullability friendly
2) 
```
Interop.MemFree  -> Marshal.FreeHGlobal
Interop.MemAlloc -> Marshal.AllocHGlobal
```
Fixes https://github.com/mono/mono/issues/15308
Fixes https://github.com/mono/mono/issues/15310
Also, copy `ThreadPoolBoundHandle.PlatformNotSupported.cs`
=> [netcore] Use CoreRT's Overlapped

mono/mini/debugger-agent.c, mono/mini/debugger-engine.c
Fixing single step inside Exception on Android...
The method is null because on ss_create_init_args the IL is -1 when calling method Mono_UnhandledException_internal what I think it's expected, because of that I ignore the single step on android if there is no method. (debugger-engine.c)
After that the sequence point cannot be found because it's calling a method of class DynamicMethodNameCounter what I think it's expected, because of that I remove the assert on android. (debugger-agent.c)
Fixes #14772
=> [debugger][android] Fixing single step inside Exception on Android

mcs/class/System/Mono.Btls/X509CertificateImplBtls.cs
The `X509CertificateImplBtls.PrivateKey` property setter was previously ignoring all values and always used `null`.  This should help with #16189.
Backport of #16212.
/cc @steveisok @baulig
=> [2019-08] X509CertificateImplBtls.PrivateKey should allow to actually set the key.

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mono/metadata/icall-decl.h, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/object-internals.h, mono/mini/mini-exceptions.c, mono/mini/mini-runtime.c, mono/utils/mono-state.c
This is so that complex consumers such as Visual Studio for Mac can forego attempting to enumerate all loaded libraries, register them one at a time and potentially have to keep the whitelist updated.
=> [merp] Add API method that whitelists all native libraries

mono/eglib/eglib-remap.h, mono/eglib/glib.h, mono/eglib/gstr.c, mono/eglib/test/string-util.c
1. When comparing strings, check pointer equality.
Faster when they match, slower when they do not.
2. Provide string lowercasing into a provided buffer, which can equal
the input, to avoid extra malloc/free.
3. Provide string compare case insensitive that accepts an exact length,
not a length that will be dominated by a nul.
On Windows this just calls _memicmp.
Arguably it should accept two lengths.
Caller could compare those, but such inlining at caller gets annoying.
Will revisit that as needed.
4. define G_STRING_CONSTANT_AND_LENGTH(x) (x), G_N_ELEMENTS (x) - 1
e.g. strncmp (foo, G_STRING_CONSTANT_AND_LENGTH ("version"))
=> Cleanup and augment string handling based on https://github.com/mono/mono/pull/15522.

mono/mini/intrinsics.c
Fixes `System.Text.Tests.StringBuilderTests.Append_CharPointer_Null_ThrowsNullReferenceException` test for LLVM.
```csharp
var builder = new StringBuilder();
builder.Append(null, 2);
```
will end up in `Buffer.Memmove` and throw NRE in `*dst = xx` or `*src = xx` for regular mono and coreclr but not for `@llvm.memmove` intrinsic added [recently](https://github.com/mono/mono/pull/16610) (it crashes instead)
=> LLVM: Throw NRE if src or dst in Buffer.Memmove are nulls

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
Remove support for "big assemblies" for AOT on Android running on ARM 32bit. This will remove relocations in `.text` which are not allowed in the upcoming Android Q release anymore.
_If_ a customer should run into this problem, the suggested workarounds are:
* Switch to ARM64, or
* Do not use AOT compilation.
Fixes https://github.com/mono/mono/issues/16369
Backport of #16432.
/cc @lewurm
=> [2019-06] [android] remove text relocations in AOT/arm32

mono/mini/interp/interp.c
It might actually cause stack pressure (but on its own, this PR does not save stack).
=> [interp] Remove unused parameter to ves_pinvoke_method.

sdks/wasm/.gitignore, sdks/wasm/Makefile, sdks/wasm/build.sh
This build script contains a copy of build commands from existing wasm CI.
`cd sdks/wasm && ./build.sh`
=> [wasm] Add build.sh

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c
Move it to ThreadContext where it makes more sense, together with the rest of the resume state, saving stack space in the process.
=> [interp] Kill InterpFrame.ex

mono/mini/debugger-agent.c, mono/mini/mini.c
It was not initialising seq_points on MonoCompile on Android, so when was compiling dynamic methods, seq_points wasn't created and we got the assert when try to single step.
Fixes #14772
=> [debugger][android] Initialise seq_points on MonoCompile

mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c, mono/mini/debugger-agent.c
Callers of mono_reflection_create_custom_attr_data_args_noalloc were leaking some of the returned information. Accessed attributes are FixedBufferAttribute and UnmanagedFunctionPointerAttribute.
=> [metadata] Fix leaks when handling a few attributes

mono/mini/abcremoval.c, mono/mini/abcremoval.h, mono/mini/method-to-ir.c
"Nullness" is tracked via a separate field that is stored adjacent to
variable/array value ranges; values may be "maybe-null" or "not-null";
the intersection of maybe-null and not-null yields not-null, the union of
maybe-null and not-null yields maybe-null. The existing graph traversal logic
is reused as much as possible, which makes the implementation of this
null value approximation slightly more complicated than it would be
otherwise.
Fixes https://github.com/mono/mono/issues/16310, which was caused by
the use of non-empty array length ranges as a way to encode non-null
values.
This also allows null check elision for zero-sized arrays.
=> [jit][llvm] Track variable nullness separately from array length ranges/index ranges in abcrem.

mono/mini/debugger-agent.c, mono/mini/mini.c
It was not initialising seq_points on MonoCompile on Android, so when was compiling dynamic methods, seq_points wasn't created and we got the assert when try to single step.
Fixes #14772 
Backport of #16691.
=> [2019-08] [debugger][android] Initialise seq_points on MonoCompile

mcs/class/System.Xaml/System.Xaml/XamlXmlReader.cs, mcs/class/System.Xaml/Test/System.Xaml/XamlXmlReaderTest.cs
This makes it possible to parse escaped values https://docs.microsoft.com/en-us/dotnet/framework/xaml-services/escape-sequence-markup-extension
=> Fix Xaml reader to parse escaped values correctly

mono/mini/memory-access.c
The overall `memcpy`/`memset` situation could use a better overhaul when compiling with LLVM since we can convert directly to intrinsics and the optimizer could make better choices and automatic vectorization for us.
This tweaks single heuristic that is affecting codegen for `System.Buffer.Memmove` (and by proxy `Buffer.BlockCopy` and some string operations). The `Memmove` code uses an `HAS_CUSTOM_BLOCKS` optimization that tries to copy memory block by 16-byte or 16-dword chunks. This hit the previous limit for inlining and resulted in a call being emitted instead of the intended inline code.
Furthermore, `Buffer.Memmove` got compiled to something that uses `string.memcpy`. `string.memcpy` is implemented as wrapper around `Buffer.Memcpy`, and `Buffer.Memcpy` calls `Buffer.Memmove`. The …
=> [netcore] Tweak inlining heuristic for memcpy

mono/mini/interp/mintops.h, mono/mini/interp/transform.c
Before this commit, the only information associated with a local was just the offset at which it resides and instructions had this offset embedded from the start. This makes it awkward to have data structures indexed on the local, or have additional information per local, which we might care at some point (for example if it is multi basic block local, if the address of the local was taken etc). In addition to this, if we will want to remove some instructions that make some locals dead, it means that we will have to compact the whole locals space and update all the offsets referenced by all instructions. We solve all these problems by resolving (and allocating) the local offset at the latest time, while emitting the instruction in the compacted byte stream. At this point dead locals will …
=> [interp] Defer local offset allocation to compacted emit phase

mono/mini/interp/interp.c
or to gint16*. Or is there a reason for this style?
Maybe could change type but still want to cast for the deref?
=> [interp] Embrace that ip is const guint16* and remove casts to that type.

mono/mini/mini.c
Fixes https://github.com/mono/mono/issues/14080
Consider the following example:
```csharp
static void CommonCallTarget () { }
static void TailA () {
tailcall CommonCallTarget ();
}
static void TailB () {
tailcall CommonCallTarget ();
}
```
Since `TailA` and `TailB` are tailcalling into `CommonCallTarget`, the resolution at patch-time is a bit tricky, that is, since it's a jump-like instruction the patching machinery won't know where it was called from. That's why we maintain a global hashtable `jump_target_hash` where each jump-site is signed up to be patched. At patch-time we know the target method (in the example `CommonCallTarget`), but since we don't know where we are coming from, we will just apply all patches for that target.
This works since ages, so why did it crash on arm64 …
=> [2019-08] [mini] publish global patches after JitInfo has been added

mono/metadata/cominterop.c, mono/tests/cominterop.cs, mono/tests/libtest.c
Array argument marshalling logic depends on valid marshal spec, by default object[] arrays are mapped to SAFEARRAY(VARIANT) in ccw. This change implements such fallback; it was tested with _MethodInfo.Invoke() where method parameters are passed as a SAFEARRAY from ccw side, being object[] on receiving end.
=> [cominterop] Default to SAFEARRAY(VARIANT) as CCW argument for object[].

mono/metadata/class-init.c, mono/mini/mini-llvm.c
These are not currently supported, but marking them as simd helps llvm eliminate dead variables with these types, since
XZERO is easier to eliminate than VZERO.
=> [llvm] Mark Vector128/Vector256 types as SIMD.

mono/metadata/class-init.c
Vtable [i] can be null so this should be check before use it.
Fixes #16712
Backport of #16733.
/cc @thaystg
=> [2019-06] [dim][regression] Null pointer exception

mono/metadata/class-init.c
Vtable [i] can be null so this should be check before use it.
Fixes #16712
Backport of #16733.
/cc @thaystg
=> [2019-08] [dim][regression] Null pointer exception

mono/mini/interp/interp.c
Manual inlining shows no additional stack use any longer.
=> [interp] Let compiler decide clear_resume_state inlining.

mono/metadata/class-init.c
Vtable [i] can be null so this should be check before use it.
Fixes #16712
=> [dim][regression] Null pointer exception

scripts/ci/run-jenkins.sh, sdks/builds/wasm.mk, sdks/wasm/Makefile, sdks/wasm/README.md
Restores the release-dynamic configuration for mono-wasm, which was removed when changing the emscripten backend to LLVM.
Fixes #16633
=> [Wasm] Restore release-dynamic configuration

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
Another revert of a revert! 🎉 
After some discussions with @grendello and @radekdoulik, we came up with this solution. It's a better attempt to fix https://github.com/mono/mono/issues/16369 as it (1) works within the restrictions of Android 10 and (2) still works for armv7 AOT. 
`.text` relocations aren't allowed in Android 10 (and this change shouldn't hurt on Linux).
AOT compilation:
```console
$ MONO_PATH=/Users/lewurm/Downloads/xamarin.android-oss-v10.0.99.136_Darwin-x86_64_pr_766265b9-Debug/bin/Debug/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/ \
MONO_ENV_OPTIONS="" \
./sdks/out/android-cross-arm-release/bin/armv7-linux-android-mono-sgen \
--aot=keep-temps,outfile=here.dll.so,asmwriter,mtriple=armv7-linux-gnueabi,tool-prefix=/Users/lewurm/android-toolchain/ndk/toolchains/ar …
```
=> [aot] move method_addresses to data.rel.so section to avoid text relocations

mcs/class/corlib/System/TermInfoDriver.cs
It can be outdated due to writes to `stdout`.
Fixes https://github.com/mono/mono/issues/16701
=> [TermInfoDriver] update top/left value on Console.{CursorTop,CursorLeft} access

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
Another revert of a revert! 🎉 
After some discussions with @grendello and @radekdoulik, we came up with this solution. It's a better attempt to fix https://github.com/mono/mono/issues/16369 as it (1) works within the restrictions of Android 10 and (2) still works for armv7 AOT. 
`.text` relocations aren't allowed in Android 10 (and this change shouldn't hurt on Linux).
AOT compilation:
```console
$ MONO_PATH=/Users/lewurm/Downloads/xamarin.android-oss-v10.0.99.136_Darwin-x86_64_pr_766265b9-Debug/bin/Debug/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/ \
MONO_ENV_OPTIONS="" \
./sdks/out/android-cross-arm-release/bin/armv7-linux-android-mono-sgen \
--aot=keep-temps,outfile=here.dll.so,asmwriter,mtriple=armv7-linux-gnueabi,tool-prefix=/Users/lewurm/android-toolchain/ndk/toolchains/ar …
```
=> [2019-08] [aot] move method_addresses to data.rel.so section to avoid text relocations

packaging/MacSDK/msbuild.py
Start updating msbuild and toolset to x.4 builds
Backport of #16744.
/cc @lewing
=> [2019-08] [msbuild][roslyn] Bump msbuild and roslyn to pull in new versions

mcs/class/System/System.csproj, mcs/class/System/System_xtest.dll.sources, mcs/class/System/common.sources
Fixes #16486 - This was only partially fixed until now
This is a continuation of https://github.com/mono/mono/pull/16539
Should we port all sources to corefx?
Backport of #16755.
/cc @Therzok
=> [2019-08] Add RenamedEvent* to FSW sources from CoreFX

mono/mini/interp/interp.c
Eventually this could contribute to stack savings. On its own, nothing.
The compiler apparently likes to create temporaries, like ip and ip - 1.
Which then have to survive functions calls, on the stack, if nonvolatile registers are exhausted.
This combats that and in a larger PR helped.
=> [interp] Reduce register pressure in endfinally.

mcs/class/System/System.csproj, mcs/class/System/System_xtest.dll.sources, mcs/class/System/common.sources
Fixes #16486 - This was only partially fixed until now
This is a continuation of https://github.com/mono/mono/pull/16539
Should we port all sources to corefx?
Backport of #16755.
/cc @Therzok
=> [2019-06] Add RenamedEvent* to FSW sources from CoreFX

scripts/ci/run-jenkins.sh
- replaced set of `run-*-mini` targets with more common `run-all-mini` one;
- removed redundant `run-v8-corlib` (there is `run-all-corlib`)
=> [wasm] update run-jenkins.sh

mono/mini/mini-llvm.c, mono/mini/mini.c, netcore/CoreFX.issues.rsp, netcore/CoreFX.issues_windows.rsp, netcore/System.Private.CoreLib/System.Private.CoreLib.csproj, netcore/System.Private.CoreLib/src/System.Reflection.Emit/DynamicMethod.cs, netcore/System.Private.CoreLib/src/System.Runtime.InteropServices/SafeHandle.cs
1) Fixes 55 tests in `DynamicMethodToString.ToStringTest`
Also, minor changes:
2) Print full method names in `*** ASM/LLVM for %s`, e.g. Was: `Main`, Now: `Main (String[])`
3) Add `[StructLayout (LayoutKind.Sequential)]` to SafeHandle (just like in regular mono)
4) Ignore `ShimsHaveOnlyTypeForwards ` test on Windows (crashes runtime - SIMD support on Windows?)
=> [netcore] Fix DynamicMethodToString.ToStringTest tests

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c, mono/mini/interp/transform.c
Stats on corlib test suite which runs a great amount of code :
```
Interp statistics
Total transform time                : 3855.60 ms
Total cprop time                    : 113.34 ms
STLOC_NP count                      : 85043
MOVLOC count                        : 11498
Copy propagations                   : 7409
Killed instructions                 : 55472
Methods inlined                     : 96785
Inline failures                     : 198312
```
In this current state, it provides a perf improvement of 0-5%. Speedups up to 1.3x were observed on benchmarks though.
A good amount of code refactoring and stack/local value generalization should take place in order to add constant propagation/folding. Keep it simple for now.
=> [interp] Propagate locals and kill dead ones afterwards

mono/mini/alias-analysis.c
Fixes inefficient code generation for `(IntPtr)42` (#16805). Alternative to #16807.
=> Improve alias analysis for pointer sized variables

mono/mini/aot-compiler.c
Should fix: https://github.com/xamarin/xamarin-android/issues/3619
As it results in double quoting, which vanishes the effect and breaks
AOT for XA on Windows.
The actual error:
[aot-compiler stdout] Stripping the binary: ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Stable\MSBuild\Xamarin\Android\ndk\arm-linux-androideabi-"strip" --strip-symbol=\$a --strip-symbol=\$d obj\Release\90\aot\armeabi-v7a\libaot-Xamarin.Android.Arch.Core.Common.dll.so.tmp
[aot-compiler stderr] '""C:\Program' is not recognized as an internal or external command,
[aot-compiler stderr] operable program or batch file.
[aot-compiler stderr] AOT of image C:\Users\peter\source\repos\App9\App9\App9.Android\obj\Release\90\android\assets\Xamarin.Android.Support.CoordinaterLayout.dll failed.
=> [aot] Do not put quotes around wrapped path

mono/mini/aot-compiler.c
Should fix: https://github.com/xamarin/xamarin-android/issues/3619
As it results in double quoting, which vanishes the effect and breaks
AOT for XA on Windows.
The actual error:
[aot-compiler stdout] Stripping the binary: ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Stable\MSBuild\Xamarin\Android\ndk\arm-linux-androideabi-"strip" --strip-symbol=\$a --strip-symbol=\$d obj\Release\90\aot\armeabi-v7a\libaot-Xamarin.Android.Arch.Core.Common.dll.so.tmp
[aot-compiler stderr] '""C:\Program' is not recognized as an internal or external command,
[aot-compiler stderr] operable program or batch file.
[aot-compiler stderr] AOT of image C:\Users\peter\source\repos\App9\App9\App9.Android\obj\Release\90\android\assets\Xamarin.Android.Support.CoordinaterLayout.dll failed.
Backport of #16792.
/cc …
=> [2019-08] [aot] Do not put quotes around wrapped path

mono/mini/trace.c
This is a legacy of before the profiler was used for the trace
output; it would apparently get the raw stack pointer and try to
dereference things by recalculating the offset as needed (no for
little, yes for big). However, because the profiler returns the
actual fixed-up pointer, this recalculation isn't needed on BE,
but instead grabs garbage a bit ahead on the stack.
To fix, use what was the little endian case unconditionally.
Example before:
`[1: 20.70598 14] ENTER: System.Globalization.CultureInfo:.ctor (int,bool,bool)(this:700000000408fb0[System.Globalization.CultureInfo platform.exe], 271824864, -32, -32, )`
Example after:
`[1: 1.93377 14] ENTER: System.Globalization.CultureInfo:.ctor (int,bool,bool)(this:700000000408fb0[System.Globalization.CultureInfo platform.exe], 127, 0, 1)`
=> [BE] Fix small sized argument output with tracing enabled

mono/mini/mini-llvm-cpp.cpp, mono/mini/mini-llvm-cpp.h, mono/mini/mini-llvm.c
Since each function has it's own module (in JIT mode) it makes sense to dump the whole module for `MONO_VERBOSE_METHOD` instead of just LLVM::Function.
It adds metadata, attributes and global variables (so it will be possible to copy-paste it to godbolt)
Example
```csharp
static int Test(int x)
{
return x / 10;
}
```
Diff for Unoptimized IR: https://www.diffchecker.com/NrF413Ts 
Diff for Optimized IR: https://www.diffchecker.com/jbEkeFFS
So now we can see global variables and metadata for each function (and can easily paste them to godbolt.org)
NOTE: optimized IR for this case contains "dead" variables (`dump_module` allowed us to see such), we probably need some Module-wide optimizations to strip dead code such as `-globaldce`
NOTE2: why do we emit exceptions in the first place for this …
=> LLVM: Dump Module instead of Function in JIT mode

mono/metadata/threads.c
=> [2019-08] [threads] do not convert NULL thread name

mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c
Callers of mono_reflection_create_custom_attr_data_args_noalloc were leaking some of the returned information. Accessed attributes are FixedBufferAttribute and UnmanagedFunctionPointerAttribute.
Backport of https://github.com/mono/mono/pull/16675
=> [2019-06][metadata] Fix leaks when handling a few attributes (#16675)

mono/mini/debugger-agent.c
With the single point of exit, this means the main ErrorCode isn't being written to and uninitialized memory is returned.
=> [debugger] Remove extraneous ErrorCode declaration

mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c, mono/mini/debugger-agent.c
Callers of mono_reflection_create_custom_attr_data_args_noalloc were leaking some of the returned information. Accessed attributes are FixedBufferAttribute and UnmanagedFunctionPointerAttribute.
Backport of #16675.
/cc @BrzVlad
=> [2019-08] [metadata] Fix leaks when handling a few attributes

mono/mini/interp/interp.c
- Factor out reptition into already existing macros.
- Remove the default for computed goto which is dead.
Computed goto has no notion of default. It is just
an unchecked array access.
Extracted from https://github.com/mono/mono/pull/16721.
=> [interp] Cleanup dispatch macros.

mono/metadata/cominterop.c, mono/tests/cominterop.cs, mono/tests/libtest.c
Treat [In, Out], [In] and unspecified as input arguments. Important change from
current behavior is to allow parameter without directional attributes.
Use case example is _MethodInfo.Invoke() method called from native client.
=> [cominterop] Default to [in] parameter direction when not specified explicitly

configure.ac, mono/arch/arm64/arm64-codegen.h, mono/mini/aot-compiler.c, mono/mini/image-writer.c, mono/mini/tramp-arm64.c, mono/utils/mono-machine.h
Main objective for reviewers: This PR shouldn't change anything for `arm64`.
Context: "Debug Mode" on the Apple Watch allows execution of regular machine code and thus is pretty similar to FullAOT on iPhone, i.e. it doesn't require bitcode, but _still_ doesn't allow `signal(3)` so cooperative suspend is required.
Apple Watch Series 4 and onward use an ARM64 chip, but with a different ABI, also known as `arm64_32`. This PR changes the AOT compiler and related trampolines so that the AOT compiler can generate all necessary code to run the interpreter on this target.
Changes:
--------------------------------------
[arm64_32] set register size to 8 in cross compiler too 
-----------------------------------------
[machine] update `target_mgreg_t` definition
`SIZEOF_REGISTER` is usually the …
=> [arm64_32] make "Debug Mode" work on Watch series 4 with --interpreter

mono/metadata/debug-mono-ppdb.c, mono/metadata/metadata-internals.h
Will need to put out a new Ubuntu nightly after this is merged, and then they can re-add us to CI.
=> Temporarily disable embedded ppdb data decompression

mono/mini/interp/interp.c
i.e. a = a op b is *not* double evaluating a.
=> [interp] Use +=, *= etc. Seems to generate identical code though.

sdks/builds/ios-Mono.framework-tvos.Info.plist, sdks/builds/ios-Mono.framework-watchos.Info.plist
This is the equivalent of
https://github.com/xamarin/xamarin-macios/commit/a9abc07cb357f9f012e3da66c70fa09d96bf02f7,
just for the Mono.frameworks in the mono archive.
Fixes https://github.com/xamarin/xamarin-macios/issues/7005.
=> Rename bundle identifier for the various Mono.frameworks we create for Xamarin.iOS. Fixes xamarin/xamarin-macios#7005.

sdks/builds/ios-Mono.framework-tvos.Info.plist, sdks/builds/ios-Mono.framework-watchos.Info.plist
This is the equivalent of
https://github.com/xamarin/xamarin-macios/commit/a9abc07cb357f9f012e3da66c70fa09d96bf02f7,
just for the Mono.frameworks in the mono archive.
Fixes https://github.com/xamarin/xamarin-macios/issues/7005.
Backport of #16896.
/cc @akoeplinger @rolfbjarne
=> [2019-08] Rename bundle identifier for the various Mono.frameworks we create for Xamarin.iOS. Fixes xamarin/xamarin-macios#7005.

sdks/builds/ios-Mono.framework-tvos.Info.plist, sdks/builds/ios-Mono.framework-watchos.Info.plist
This is the equivalent of
https://github.com/xamarin/xamarin-macios/commit/a9abc07cb357f9f012e3da66c70fa09d96bf02f7,
just for the Mono.frameworks in the mono archive.
Fixes https://github.com/xamarin/xamarin-macios/issues/7005.
Backport of #16896.
/cc @akoeplinger @rolfbjarne
=> [master] Rename bundle identifier for the various Mono.frameworks we create for Xamarin.iOS. Fixes xamarin/xamarin-macios#7005.

mono/metadata/assembly-load-context.c, mono/metadata/icall.c, mono/metadata/image.c, mono/metadata/marshal.c, mono/metadata/mono-route.c, mono/metadata/object.c, mono/metadata/threadpool-io.c, mono/metadata/threads.c, mono/metadata/w32socket.c, mono/sgen/sgen-debug.c
This fixes the compiler warnings when building netcore-only on macOS.
Mostly warnings about functions without prototypes for icalls that don't exist on netcore so wrapped them in `ENABLE_NETCORE` ifdef.
=> [netcore] Fix compiler warnings

configure.ac, mono/arch/arm64/arm64-codegen.h, mono/mini/aot-compiler.c, mono/mini/image-writer.c, mono/mini/tramp-arm64.c, mono/utils/mono-machine.h
Main objective for reviewers: This PR shouldn't change anything for `arm64`.
Context: "Debug Mode" on the Apple Watch allows execution of regular machine code and thus is pretty similar to FullAOT on iPhone, i.e. it doesn't require bitcode, but _still_ doesn't allow `signal(3)` so cooperative suspend is required.
Apple Watch Series 4 and onward use an ARM64 chip, but with a different ABI, also known as `arm64_32`. This PR changes the AOT compiler and related trampolines so that the AOT compiler can generate all necessary code to run the interpreter on this target.
Changes:
--------------------------------------
[arm64_32] set register size to 8 in cross compiler too 
-----------------------------------------
[machine] update `target_mgreg_t` definition
`SIZEOF_REGISTER` is usually the …
=> [2019-08] [arm64_32] make "Debug Mode" work on Watch series 4 with --interpreter

mcs/class/System.Windows.Forms/System.Windows.Forms/InternalWindowManager.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ThemeWin32Classic.cs
ControlBox property didn`t hide Close button and icon when set to false
=> [WinForms] fix ControlBox appearance

mono/utils/mono-threads-api.h
Perhaps they are never needed then.
=> All existing safepoints appear to be mooted by pinned coop handles.

mono/metadata/debug-mono-ppdb.c, mono/metadata/metadata-internals.h
Will need to put out a new Ubuntu nightly after this is merged, and then they can re-add us to CI.
Backport of #16868.
/cc @marek-safar @CoffeeFlux
=> [2019-08] Temporarily disable embedded ppdb data decompression

mono/mini/mini-generic-sharing.c
Whenever we are publishing changes to the rgctx arrays, we are racing with rgctx_lazy_fetch_trampoline, so we need to make sure any pointers we set there must have their contents initialized.
=> [mini] Add missing membars when initializing rgctx entries

mono/arch/s390x/s390x-codegen.h, mono/metadata/mono-endian.h, mono/mini/exceptions-s390x.c, mono/mini/mini-s390x.c, mono/mini/tramp-s390x.c, mono/utils/mono-context.h, mono/utils/mono-sigcontext.h
- Use __builtin_bswapxx for s390x rather than inline assembler
- s390x ABI specifies that %f8-%f15 are protected between calls so avoid using or save/restore as required
- Save the "protected" FP registers in the context structure
- Additional SIMD prep for s390x
=> s390x ABI fixes 

mono/mini/mini-generic-sharing.c
Whenever we are publishing changes to the rgctx arrays, we are racing with rgctx_lazy_fetch_trampoline, so we need to make sure any pointers we set there must have their contents initialized.
Backport of #16904.
=> [2019-08] [mini] Add missing membars when initializing rgctx entries

packaging/MacSDK/msbuild.py
Pull in ~~https://github.com/mono/msbuild/pull/136~~ https://github.com/mono/msbuild/pull/141 and get 
```
MicrosoftNetCompilersVersion: 3.3.1-beta4-19462-11
MicrosoftNETSdkPackageVersion: 3.0.100-rc2.19467.3
MicrosoftNETSdkRazorPackageVersion: 3.0.0
MicrosoftNETSdkWebPackageVersion: 3.0.100-rc2.19465.1
NuGetBuildTasksPackageVersion: 5.3.0-rtm.6251
MicrosoftDotNetMSBuildSdkResolverPackageVersion: 3.0.100-rc2.19465.3
MicrosoftNETCoreAppPackageVersion: 3.0.0
ILLinkTasksPackageVersion: 0.1.6-prerelease.19380.1
```
=> [2019-06] Bump msbuild and sdk versions to 3.0.1xx latest

mono/metadata/class.c, netcore/CoreFX.issues.rsp
Fixes #15153 
This changes `mono_class_from_name_case_checked` to call into `mono_class_from_name_checked_aux`, which I made case-aware. The old code was broken in a couple different ways and almost never hit, as the only way to do so from C# was via reflection.
This is neither terribly pretty nor fast, but hopefully it sees little use outside of the test suite.
=> Make case-insensitive class lookup work correctly with exported types

configure.ac
hybrid suspend won't get disabled when using --enable-cooperative-suspend triggering configure error:
Hybrid suspend and Cooperative suspend cannot be both enabled.
Fix explicit set hybrid suspend default behavior to no if cooperative suspend has been configured.
=> Explicit disable hybrid suspend when cooperative suspend is enabled.

mcs/class/corlib/System.Runtime.InteropServices/Marshal.cs, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/metadata/marshal.c, mono/metadata/marshal.h, netcore/System.Private.CoreLib/src/System.Runtime.InteropServices/Marshal.cs
It is used by `SafeHandle` to restore last error from `Release`. This is especially important when doing P/Invoke marshalling where the error of the P/Invoked API would get overwritten if it was holding last reference for the particular `SafeHandle`.
=> [bcl/netcore] Implement Marshal.SetLastWin32Error

tools/offsets-tool-py/Makefile
Because the system location isn't world writeable on Catalina.
=> [2019-06] [offsets-tool] Install clang into the user-specific python directory.

mcs/class/corlib/System.Security.Policy/ApplicationTrustEnumerator.cs
`ApplicationTrustEnumerator ` used to call itself. The following snippet crashed with SO:
```csharp
using System.Security.Policy;
public class Program {
public static void Main (string[] args)
{
ApplicationTrustCollection col = ApplicationSecurityManager.UserApplicationTrusts;
col.GetEnumerator ();
}
}
```
=> Fix StackOverflow in ApplicationTrustEnumerator

mcs/class/System/System.IO/FileSystemWatcher.cs, mcs/class/System/Test/System.IO/FileSystemWatcherTest.cs
The FileSystemWatcher `watcher` field is the backend IFileWatcher that's
supposed to be used for the actual operations.
Each backend has a `bool GetInstance (out watcher)` method that returns a
singleton object, so each new instance of FileSystemWatcher gets the same
IFileWatcher instance.  (They will get different `watcher_handle` instances
which are used by some backends to uniquely identify this FileSystemWatcher).
However when the first FileSystemWatcher instance is `Dispose`d, it will set
`watcher = null` which will prevent the remaining instances from calling
watcher?.StopDispatching (watcher_handle);
watcher?.Dispose (watcher_handle);
which means that the backend won't properly cleanup resources for any other FSW
instances that have other `watcher_handle` values.
Addresses …
=> [2019-08] [System] Make FileSystemWatcher backend non-static

sdks/builds/.gitignore, sdks/builds/mac.mk, sdks/versions.mk
Xamarin.Mac doesn't need nor use it anymore.
This also removes the last part of the mono archive that required Xcode 9.4.
=> [2019-08] [sdks] Remove the mac32 build.

mono/metadata/threads-types.h, mono/metadata/threads.c, mono/mini/interp/interp.c, mono/mini/interp/transform.c, mono/mini/mini-runtime.c
Note that the name mono_thread_interruption_request without trailing flag
was already taken.
=> Inline mono_thread_interruption_request_flag.

sdks/builds/.gitignore, sdks/builds/mac.mk, sdks/versions.mk
Xamarin.Mac doesn't need nor use it anymore.
This also removes the last part of the mono archive that required Xcode 9.4.
Backport of #16936.
/cc @rolfbjarne
=> [master] [sdks] Remove the mac32 build.

mcs/class/System/System.IO.Compression/DeflateStream.cs
No idea why these were left unimplemented (probably were not used at that point).
Fixes https://github.com/mono/mono/issues/16950
=> Implement WriteCore and ReadCore in DeflateStream

mcs/class/System/System.IO.Compression/DeflateStream.cs
No idea why these were left unimplemented (probably were not used at that point).
Fixes https://github.com/mono/mono/issues/16950
Backport of #16951.
=> [2019-08] Implement WriteCore and ReadCore in DeflateStream

tools/offsets-tool-py/Makefile
Because the system location isn't world writeable on Catalina.
Backport of #16933.
/cc @lewurm @rolfbjarne
=> [master] [offsets-tool] Install clang into the user-specific python directory.

tools/offsets-tool-py/Makefile
Because the system location isn't world writeable on Catalina.
Backport of #16933.
/cc @lewurm @rolfbjarne
=> [2019-08] [offsets-tool] Install clang into the user-specific python directory.

configure.ac, mono/metadata/icall.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/utils/mono-state.c, runtime/bin/mono-hang-watchdog.in, tools/Makefile.am, tools/mono-hang-watchdog/Makefile.am, tools/mono-hang-watchdog/mono-hang-watchdog.c
Fixes https://github.com/mono/mono/issues/15646
macOS does not like signals being sent from the forked supervisor process, possibly towards anywhere but definitely when sent to the parent process. The following message is currently spewed after the supervisor process attempting to send a SIGSEGV to a hanged Mono process:
"The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec()."
We follow that direction and introduce a new binary that, when available, is used to abort the parent process for us.
Backport of #15715.
/cc @alexischr
=> [2019-08] [merp] Use a separate program as the hang supervisor.

mcs/class/System/System.IO/FileSystemWatcher.cs, mcs/class/System/Test/System.IO/FileSystemWatcherTest.cs
The FileSystemWatcher `watcher` field is the backend IFileWatcher that's
supposed to be used for the actual operations.
Each backend has a `bool GetInstance (out watcher)` method that returns a
singleton object, so each new instance of FileSystemWatcher gets the same
IFileWatcher instance.  (They will get different `watcher_handle` instances
which are used by some backends to uniquely identify this FileSystemWatcher).
However when the first FileSystemWatcher instance is `Dispose`d, it will set
`watcher = null` which will prevent the remaining instances from calling
watcher?.StopDispatching (watcher_handle);
watcher?.Dispose (watcher_handle);
which means that the backend won't properly cleanup resources for any other FSW
instances that have other `watcher_handle` values.
Addresses …
=> [System] Make FileSystemWatcher backend non-static

mono/mini/aot-compiler.c
This keeps the dynamic loader a little out of the way, I.e. for intra .so calls, on some systems, e.g. Linux. On other systems it does nothing e.g. Apple and Windows -- they do this always. So this makes Linux more efficient, more like Apple and Windows.
=> Use ld -Bsymbolic when linking AOT.

mono/mini/interp/interp.c
Usually the interpreter operates in GC Unsafe state. There is an exception however, and that is when it executes a `managed-to-native` wrapper in cooperative (or hybrid) suspend.
The wrapper does essentially:
1. enter GC Safe state via `mono_threads_enter_gc_safe_region_unbalanced`
2. call native function
3. exit GC state via `mono_threads_exit_gc_safe_region_unbalanced`
Usually upon return of a native function call, the interpreter would check for thread interruption and, if applicable, throw an exception.  That, however, would mess with the GC state as the interpreter operates in GC Safe state at this moment.
Note that ignoring thread interruption at that point shouldn't be a problem, because after 3. the `managed-to-native` wrapper will check for thread interruption anyway.
Contributes …
=> [interp] avoid exception checkpoint when in thread is in GC Safe state 

mono/mini/mini-arm64.c
Note that in the output below `a`, `b`, etc. are NSObjects, so they are really passed as pointer.
Before:
```
* thread #1, name = 'tid_303', queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
frame #0: 0x04f301d4 aWatchOSExtension`::xamarin_localized_string_format_9(format="hello%@%@%@%@%@%@%@%@%@", a=0, b=1, c=2, d=3, e=4, f=5, g=6, h=7, i=0x00000000) at nsstring-localization.m:81:9
78   void *
79   xamarin_localized_string_format_9 (NSString *format, id a, id b, id c, id d, id e, id f, id g, id h, id i)
80   {
-> 81           return [NSString localizedStringWithFormat: format, a, b, c, d, e, f, g, h, i];
82   }
83
84   }
(lldb) mbt 4
* thread #1
* frame #0: 0x04f301d4 aWatchOSExtension`::xamarin_localized_string_format_9(format="hello%@%@%@%@%@%@%@%@%@", a=0, b=1, c=2, d=3, …
```
=> [arm64_32] fix pointer size in CallInfo

mono/metadata/jit-icall-reg.h, mono/mini/exceptions-amd64.c, mono/mini/mini-arm.c, mono/mini/mini-ppc.c, mono/mini/mini-runtime.c, mono/mini/mini-s390x.c, mono/utils/mono-tls.c, mono/utils/mono-tls.h
The same functions are referenced by JIT and runtime.
The JIT uses cannot be inlined. The runtime can.
Since I could not get anything else to build and the change is simple and mechanical, now two sets of functions are provided, inline and extern. Extern just calls inline.
This PR appears to change all the uses, but it is only the JIT uses. The runtime ones just work and keep the old names.
We should also consider building desktop with LTO/LTCG, which would do all this automatically, smarter, more generally. A quick experiment shows it grows the runtime size, which is why I say desktop.
=> Inline TLS access.

mono/metadata/w32process-unix.c
If you compile the runtime in debug mode (e.g. `./build.sh -c Debug`), `make run-sample` will crash with "symbols were not found".
/cc @filipnavara
=> [netcore] Add more stubs to w32process-unix.c to fix debug builds

mono/mini/debugger-engine.c, mono/mini/mini-exceptions.c
Doing the same fix from Android to IOS, I removed the ifdef, I don't think that this will happen when not using IOS nor Android, but I prefer to let the if there to avoid the exception.
On mini-exceptions.c check if there is no ji we can continue and generate the exception without checking wrapper_type.
Fixes #16824
=> [debugger] Crash when debugging iOS application that throws

mono/mini/mini-arm64.c
Note that in the output below `a`, `b`, etc. are NSObjects, so they are really passed as pointer.
Before:
```
* thread #1, name = 'tid_303', queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
frame #0: 0x04f301d4 aWatchOSExtension`::xamarin_localized_string_format_9(format="hello%@%@%@%@%@%@%@%@%@", a=0, b=1, c=2, d=3, e=4, f=5, g=6, h=7, i=0x00000000) at nsstring-localization.m:81:9
78   void *
79   xamarin_localized_string_format_9 (NSString *format, id a, id b, id c, id d, id e, id f, id g, id h, id i)
80   {
-> 81           return [NSString localizedStringWithFormat: format, a, b, c, d, e, f, g, h, i];
82   }
83
84   }
(lldb) mbt 4
* thread #1
* frame #0: 0x04f301d4 aWatchOSExtension`::xamarin_localized_string_format_9(format="hello%@%@%@%@%@%@%@%@%@", a=0, b=1, c=2, d=3, …
```
=> [2019-08] [arm64_32] fix pointer size in CallInfo

mcs/class/System/System.IO.Compression/DeflateStream.cs
No idea why these were left unimplemented (probably were not used at that point).
Fixes https://github.com/mono/mono/issues/16950
Backport of #16951.
=> [2019-06] Implement WriteCore and ReadCore in DeflateStream

mcs/class/corlib/Test/System.Threading/CancellationTokenSourceTest.cs, mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs
Restores previous ExecutionContext Capture behavior where we were copying a new SynchronizationContext as opposed to a reference to the existing one.
The old behavior caused SynchronizationContextAwaitTaskContinuations to not post to a SynchronizationContext.
Fixes #16759
Reverts a fix for #12421
=> Restore Previous ExecutionContext Capture Behavior

mono/mini/interp/interp.c
Backport of https://github.com/mono/mono/pull/16955
=> [2019-08] [interp] avoid exception checkpoint when in thread is in GC Safe state

mono/mini/mini-exceptions.c
Partially fixes https://github.com/mono/mono/issues/16689
=> [merp] Use function names even in 'private crashes' mode

configure.ac
The AC_CHECK_MEMBER check was done incorrectly, the include files need to be separated by newlines otherwise we would get a false negative result.
config.log contained this:
```
conftest.c:279:23: warning: extra tokens at end of #include directive [-Wextra-tokens]
#include <sys/types.h>, #include <sys/stat.h>
^
//
```
This means that when doing File.GetCreationTime() we'd fall back to returning the last modified time.
It regressed when we switched System.IO.File to the CoreFX implementation i.e. System.Native in https://github.com/mono/mono/commit/8f5cef936491e8b20888bbf18d426482c890637c.
Fixes https://github.com/mono/mono/issues/16974
=> Correctly check for HAVE_STAT_BIRTHTIME in configure.ac checks for System.Native

mcs/class/corlib/Test/System.Threading/CancellationTokenSourceTest.cs, mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs
Restores previous ExecutionContext Capture behavior where we were copying a new SynchronizationContext as opposed to a reference to the existing one.
The old behavior caused SynchronizationContextAwaitTaskContinuations to not post to a SynchronizationContext.
Fixes #16759
Reverts a fix for #12421
Backport of #16945.
/cc @steveisok
=> [2019-08] Restore Previous ExecutionContext Capture Behavior

configure.ac
The AC_CHECK_MEMBER check was done incorrectly, the include files need to be separated by newlines otherwise we would get a false negative result.
config.log contained this:
```
conftest.c:279:23: warning: extra tokens at end of #include directive [-Wextra-tokens]
#include <sys/types.h>, #include <sys/stat.h>
^
//
```
This means that when doing File.GetCreationTime() we'd fall back to returning the last modified time.
It regressed when we switched System.IO.File to the CoreFX implementation i.e. System.Native in https://github.com/mono/mono/commit/8f5cef936491e8b20888bbf18d426482c890637c.
Fixes https://github.com/mono/mono/issues/16974
Backport of #16999.
/cc @marek-safar @akoeplinger
=> [2019-08] Correctly check for HAVE_STAT_BIRTHTIME in configure.ac checks for System.Native

mono/mini/mini-exceptions.c
Partially fixes https://github.com/mono/mono/issues/16689
Backport of #16897.
/cc @alexischr
=> [2019-08] [merp] Use function names even in 'private crashes' mode

mono/utils/mono-threads.c
Fixes
```
* thread #12, name = 'tid_a507', stop reason = EXC_BREAKPOINT (code=1, subcode=0x1be66144)
* frame #0: 0x1be66144 libsystem_c.dylib`__abort + 184
frame #1: 0x1be6608c libsystem_c.dylib`abort + 152
frame #2: 0x003e1fa0 monotouchtest`log_callback(log_domain=0x00000000, log_level="error", message="* Assertion at ../../../../../mono/utils/hazard-pointer.c:158, condition `mono_bitset_test_fast (small_id_table, id)' not met\n", fatal=4, user_data=0x00000000) at runtime.m:1251:3
frame #3: 0x003abf44 monotouchtest`monoeg_g_logv_nofree(log_domain=0x00000000, log_level=G_LOG_LEVEL_ERROR, format=<unavailable>, args=<unavailable>) at goutput.c:149:2 [opt]
frame #4: 0x003abfb4 monotouchtest`monoeg_assertion_message(format=<unavailable>) at goutput.c:184:22 [opt]
frame #5: 0x003904dc …
```
=> [threads] clear small_id_key TLS when unregistering a thread

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/ExceptionEventRequest.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs, mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c, mono/mini/debugger-engine.h
Creating a new version of MOD_KIND_EXCEPTION_ONLY to support VsWin features, discussed with Joaquin Jares.
Because we don't have this functionality of get every other exception that is not specified, VsWin was getting every exception and filtering later. But this causes a slowness during the debugger because we stop all thread on each exception that we get, even if they are caught and we don't want to stop.
This fix a bug of slowness on Android Debugger.
Backport of #16825.
/cc @thaystg
=> [2019-08] [debugger] New way to filter exceptions to support VSWin features

runtime/Makefile.am
Resolves:
```
07:04:21  configure.ac:6082: error: required file 'runtime/bin/mono-hang-watchdog.in' not found
```
=> Add mono-hang-watchdog.in to tarball

mono/mini/debugger-engine.c, mono/mini/mini-exceptions.c
Doing the same fix from Android to IOS, I removed the ifdef, I don't think that this will happen when not using IOS nor Android, but I prefer to let the if there to avoid the exception.
On mini-exceptions.c check if there is no ji we can continue and generate the exception without checking wrapper_type.
Fixes #16824
Backport of #16958.
=> [2019-08] [debugger] Crash when debugging iOS application that throws

mono/mini/intrinsics.c, mono/mini/mini-llvm.c, mono/mini/mini-ops.h
My previous Math-related PRs didn't touch `MathF.Round`, because `llvm.round.f32` generated slightly different (from CoreCLR) codegen.
```csharp
static float Test(float x) => MathF.Round(x);
```
CoreCLR emits:
```asm
vzeroupper
vroundss xmm0, xmm0, xmm0, 0x4
ret
```
Mono-LLVM emits (before this PR):
```asm
push   rax
movabs rax,0xd2de20
call   QWORD PTR [rax]
pop    rax
ret 
```
Mono-LLVM emits (with this PR):
```asm
vroundss xmm0,xmm0,xmm0,0x4
ret 
```
```
CoreCLR:                             5.14 us
Mono-LLVM:                          16.52 us
Mono-LLVM-llvm.round.f32:           14.35 us
Mono-LLVM-llvm.x86.sse41.round.ss:   5.14 us
```
=> LLVM: Intrinsify MathF.Round

mono/utils/mono-threads.c
Fixes
```
* thread #12, name = 'tid_a507', stop reason = EXC_BREAKPOINT (code=1, subcode=0x1be66144)
* frame #0: 0x1be66144 libsystem_c.dylib`__abort + 184
frame #1: 0x1be6608c libsystem_c.dylib`abort + 152
frame #2: 0x003e1fa0 monotouchtest`log_callback(log_domain=0x00000000, log_level="error", message="* Assertion at ../../../../../mono/utils/hazard-pointer.c:158, condition `mono_bitset_test_fast (small_id_table, id)' not met\n", fatal=4, user_data=0x00000000) at runtime.m:1251:3
frame #3: 0x003abf44 monotouchtest`monoeg_g_logv_nofree(log_domain=0x00000000, log_level=G_LOG_LEVEL_ERROR, format=<unavailable>, args=<unavailable>) at goutput.c:149:2 [opt]
frame #4: 0x003abfb4 monotouchtest`monoeg_assertion_message(format=<unavailable>) at goutput.c:184:22 [opt]
frame #5: 0x003904dc …
```
=> [2019-08] [threads] clear small_id_key TLS when unregistering a thread

scripts/ci/run-jenkins.sh, sdks/wasm/Makefile, sdks/wasm/xunit-exclusions.rsp
Add the other corefx xunit test assemblies to the build and adjust jenkins to run them on CI.
=> Enable additional wasm corefx xunit tests

sdks/builds/.gitignore, sdks/builds/mac.mk, sdks/versions.mk
Xamarin.Mac doesn't need nor use it anymore.
This also removes the last part of the mono archive that required Xcode 9.4.
Backport of #16936.
/cc @rolfbjarne
=> [2019-06] [sdks] Remove the mac32 build.

mcs/class/corlib/System/TimeZoneInfo.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
There is an issue with jumping into DST for some time zones when the incorrect date-time offset is returned for date-time in UTC (which comes from DateTime.Now). The fix is to just check if the incoming date-time is in UTC
Also I added set of tests for some time zones but they verify jumping into DST in general.
Fixes #16395
Backport of https://github.com/mono/mono/pull/16430
=> [2019-08] Fix time zone issue when jumping into DST

netcore/CoreFX.issues_linux.rsp, netcore/Makefile, netcore/System.Private.CoreLib/System.Private.CoreLib.csproj, netcore/sample/HelloWorld/HelloWorld.csproj
Currently netcore-build doesn't need submodules (except LLVM) so a task somewhere in arcade/microsoft.build.tasks.git always complain if those are not cloned, something like this:
```
make bcl
```
Outputs:
```
/home/egor/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-19367-01/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Could not find file '/mnt/c/prj/mono/mono-b/external/api-doc-tools/.git'. The source code won't be available via Source Link. [/mnt/c/prj/mono/mono-b/netcore/sample/HelloWorld/HelloWorld.csproj]
/home/egor/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-19367-01/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Could not find file '/mnt/c/prj/mono/mono-b/external/api-snapshot/.git'. The source code won't be available via Source Link. …
```
=> [netcore] Disable annoying SourceLink warrnings

mono/metadata/object.c, mono/mini/driver.c, mono/mini/jit.h, mono/unit-tests/test-mono-callspec.c, mono/unit-tests/test-mono-string.c, mono/utils/mono-threads-api.h
When embedded mono is executing a C++ code, it didn't start to execute a C# code, we don't need to suspend the thread to run GC.
So my idea is set the flag  MONO_THREAD_INFO_FLAGS_NO_GC when initializes mono embedded and only remove the flag MONO_THREAD_INFO_FLAGS_NO_GC when a mono_runtime_invoke_array or a mono_runtime_invoke is called. 
Fixes #16192
Fixes #14725
=> [threading] embedded mono hangs

mono/mini/debugger-agent.c
When we detach from the debugger, we reset the state by starting a new debugger thread (why don't we just use the existing thread?). As per commit https://github.com/mono/mono/commit/540ef385faa230bc226c7a83bfabd0730520911e we should shut down the debugger thread when the connection drops. However, since that commit was acting as a Dispose command was sent instead, it would end up relentlessly spawning and closing new debugger threads up until the runtime is shut down. This commit makes sure we don't respawn once the connection hangs.
=> [debugger] Properly close debugger thread when connection hangs

mono/mini/interp/interp.c
Follow-up for https://github.com/mono/mono/pull/16955
/cc @BrzVlad
=> [interp] always require GC Unsafe mode in exception checkpoint

sdks/versions.mk
Because that's the min iOS version in all current versions of Xamarin.iOS.
=> [sdks] Bump min iOS version to 7.0.

sdks/versions.mk
Because that's the min iOS version in all current versions of Xamarin.iOS.
Backport of #17070.
/cc @akoeplinger @rolfbjarne
=> [master] [sdks] Bump min iOS version to 7.0.

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
Mono.Debugger.Soft tests have been annoyingly flaky on CI lately due to random VMDisconnectedException. This fixes them.
=> [Mono.Debugger.Soft] Fix VirtualMachine detaching

mono/mini/mini-exceptions.c
Fixes https://github.com/mono/mono/issues/16803
=> [crashing] Remove Mono signal handlers when starting to handle a crash

mcs/class/corlib/System/TimeZoneInfo.cs, mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
There is an issue with jumping into DST for some time zones when the incorrect date-time offset is returned for date-time in UTC (which comes from DateTime.Now). The fix is to just check if the incoming date-time is in UTC
Also I added set of tests for some time zones but they verify jumping into DST in general.
Fixes https://github.com/mono/mono/issues/16395
Backport of https://github.com/mono/mono/pull/16430
=> [2019-06] Fix time zone issue when jumping into DST

samples/embed/test-invoke.c, samples/embed/teste.c
Add loading the default Mono configuration file in the examples of Mono Embedded.
Also include header in existing usage of `mono_config_parse`.
This fixes problems under Raspbian, when extending the sample with your own code. 
The `teste.c` is still not compiling, because the `mono_set_allocator_vtable` function is not up to date. But I was not able to find the documentation for this function.
=> Add loading the default Mono configuration file.

mono/metadata/domain.c
In 6d2c77fb3373971b4c615a70fe43f3622e3c91d8 we changed the representation of
the runtimes that we will probe from a NULL-terminated array to a linked list.
Unfortunately we made a typo, and in the case where the caller of
`mono_init_internal` provided a runtime_version, we still picked
`DEFAULT_RUNTIME_VERSION` instead of the given `runtime_version`.
This is an issue for embedders like XA that use the "mobile" runtime - all
their BCL assemblies are compiled with the "mobile" version number (2.0.5.0) but
Mono running with the default runtime configuration will remap to 4.0.0.0.  As
a result, when there are references to 2.0.5.0 assemblies, the load requests
will be remapped to 4.0.0.0 which will never see the already loaded 2.0.5.0
assemblies, and we will fall back on the embedder's …
=> [2019-08] [runtime] Respect runtime_version in mono_init_internal

mono/metadata/jit-icall-reg.h, mono/mini/exceptions-amd64.c, mono/mini/mini-arm.c, mono/mini/mini-ppc.c, mono/mini/mini-runtime.c, mono/mini/mini-s390x.c, mono/utils/mono-tls.c, mono/utils/mono-tls.h
Reverts mono/mono#16882
This broke the Mono Android SDKs build in master though for some reason it doesn't show up in the PR build:
```
[2019-09-26T03:19:55.366Z] Undefined symbols for architecture x86_64:
[2019-09-26T03:19:55.366Z]   "_mono_tls_key_jit_tls", referenced from:
[2019-09-26T03:19:55.366Z]       _mono_tls_get_jit_tls in libmain_a-main-sgen.o
[2019-09-26T03:19:55.366Z]   "_mono_tls_key_lmf_addr", referenced from:
[2019-09-26T03:19:55.366Z]       _mono_tls_get_lmf_addr in libmain_a-main-sgen.o
[2019-09-26T03:19:55.366Z] ld: symbol(s) not found for architecture x86_64
[2019-09-26T03:19:55.366Z] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[2019-09-26T03:19:55.366Z] gmake[6]: *** [Makefile:1634: mono-sgen] Error 1
[2019-09-26T03:19:55.366Z] …
```
=> Revert "Inline TLS access."

mono/metadata/domain.c
In 6d2c77fb3373971b4c615a70fe43f3622e3c91d8 we changed the representation of
the runtimes that we will probe from a NULL-terminated array to a linked list.
Unfortunately we made a typo, and in the case where the caller of
`mono_init_internal` provided a runtime_version, we still picked
`DEFAULT_RUNTIME_VERSION` instead of the given `runtime_version`.
This is an issue for embedders like XA that use the "mobile" runtime - all
their BCL assemblies are compiled with the "mobile" version number (2.0.5.0) but
Mono running with the default runtime configuration will remap to 4.0.0.0.  As
a result, when there are references to 2.0.5.0 assemblies, the load requests
will be remapped to 4.0.0.0 which will never see the already loaded 2.0.5.0
assemblies, and we will fall back on the embedder's …
=> [runtime] Respect runtime_version in mono_init_internal

mono/mini/mini-exceptions.c
Fixes https://github.com/mono/mono/issues/16803
Backport of #17002.
=> [2019-08] [crashing] Remove Mono signal handlers when starting to handle a crash

packaging/MacSDKRelease/mono-extensions.py
It needed an update because https://github.com/mono/mono/commit/5b108b5726ec196f4b61d30f406919ce70211754 touched code the patch modified.
=> Fix mono-extensions build

mcs/class/corlib/System.IO/Path.cs
A valid path might be something like \\\\.\\pipe\\pipename (i.e. \\\\.\\ is a valid root). If we blindly strip directories named `.` then we end up confusing our path cleaning algorithm. So permit a directory component of `.` in UNC path roots.
Closes: https://github.com/mono/mono/issues/16460
```
UNC pipe name (input is \\.\pipe\pipename): \\.\pipe\pipename
UNC network name (input is \\servername\sharename\dirname): \\servername\sharename\dirname
UNC DOS name (input is \\?\C:\Users\.\joshield): \\?\C:\Users\joshield
```
=> Special case in GetFullPath for UNC roots of \\.\

mcs/class/System/wasm_System_xtest.dll.exclude.sources
`System/RemoteExecutorTests.cs` tests are excluded in the mobile test profiles. It makes sense to do the same for wasm.
Fixes https://github.com/mono/mono/issues/17038.
=> [wasm][xunit test] Exclude RemoteExecutorTests in bcl profile

sdks/wasm/xunit-exclusions.rsp
Excluded:
- System.Net.Tests.WebClientTest.DefaultCtor_PropertiesReturnExpectedValues
- System.Net.Tests.WebClientTest.Proxy_Roundtrips
- System.Net.Sockets.Tests.NetworkStreamTest.Ctor_NotConnected_ThrowsIOException
due to PNSE-implemenatation of  [ClientWebSocket.Proxy](https://github.com/mono/mono/blob/master/sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs#L570-L573) and [Socket ctor](https://github.com/mono/mono/blob/master/mcs/class/referencesource/System/net/System/Net/Sockets/Socket.cs#L148-L151)
Fixes https://github.com/mono/mono/issues/17039.
=> [wasm][xunit tests] Exclude some tests due to PNSE-implemented members.

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mono/metadata/icall-decl.h, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/threads-types.h, mono/mini/mini-exceptions.c, mono/mini/mini-runtime.c, mono/utils/mono-state.c
Support native call data from all native modules. Backport of  https://github.com/mono/mono/pull/16899/ and https://github.com/mono/mono/pull/15622
=> [2019-08] [merp] Add API method that whitelists all native libraries

man/mono.1, mcs/build/rules.make, mcs/build/start-compiler-server.sh, mono/mini/Makefile.am.in, mono/mini/intrinsics.c, mono/mini/memory-access.c, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/tests/Makefile.am, scripts/csc.in, scripts/csi.in, scripts/vbc.in
Otherwise we can have potential crashes in the bcl on arm targets, since a lot of code that assumes this memory model is now shared with mono.
Keep the old clr-memory-model option alive for now, to avoid potential build problems, if building older mono with newer mono.
Fixes https://github.com/mono/mono/issues/16770
=> [mini] Use clr memory model by default

mono/mini/mini-exceptions.c
Fixes https://github.com/mono/mono/issues/16803
Backport of https://github.com/mono/mono/pull/17002
=> [2019-06][crashing] Remove Mono signal handlers when starting to handle a crash

Makefile.am
```
configure.ac:6695: error: required file 'netcore/corerun/Makefile.in' not found
Makefile.am:24: error: required directory ./netcore/corerun does not exist
```
=> Fix missing corerun/ directory in `make dist` tarballs

configure.ac, llvm/build_llvm_msbuild.bat, mcs/jay/Makefile, mono/dis/Makefile.am, mono/eglib/Makefile.am, mono/metadata/Makefile.am, mono/mini/Makefile.am.in, mono/mini/main.c, mono/native/Makefile.am, mono/sgen/Makefile.am, mono/tests/Makefile.am, mono/tests/fullaot-mixed/Makefile.am, mono/tests/testing_gac/Makefile.am, mono/utils/Makefile.am, msvc/Makefile.am, msvc/build-external-btls.bat, msvc/build-external-llvm.bat, msvc/libmono-dynamic.vcxproj, msvc/libmono-static.vcxproj, msvc/mono.sln, msvc/monow.vcxproj, msvc/monow.vcxproj.filters, msvc/run-msbuild.bat, scripts/ci/run-test-default.sh, support/Makefile.am, tools/mono-hang-watchdog/Makefile.am, tools/pedump/Makefile.am, tools/sgen/Makefile.am
Add a new option to only build MSVC version of mono runtime and native tools, --enable-msvc-only. In the past, --enable-msvc build both mingw as well as MSVC runtime, this commit adds an option to only build MSVC version of runtime and native tools using make file system.
Commit updates all native make file making sure mingw/gcc builds are not done if --enable-msvc-only has been used. It also makes sure we build and use MSVC based tools as part of build and tests.
Result will be a build without any mingw/gcc artifacts, but where all existing make files still works with the MSVC build artifacts. NOTE, this PR is just a first step, optional disabling the gcc/mingw build on Windows. It does not look into the install targets or other automake features, except making sure everything builds and …
=> Optional only build MSVC runtime using make file system on Windows.

netcore/System.Private.CoreLib/src/System/GC.cs
I experimentally determined that implementing GC.AllocateUninitializedArray() is unlikely to save any time. To do this I constructed a program that allocates 100k arrays of the maximum size for which we do explicit zeroing, and modified the VM to skip zeroing. This resulted in no measurable speed up.
This change is a result of this issue: https://github.com/mono/mono/issues/15235
=> Add a comment explaining why GC.AllocateUninitializedArray is not an icall

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/mini/mini-llvm.c
After https://github.com/mono/mono/commit/9ff3b0d65ee4, in an aot image we can emit addresses either as bl offset (which uses 4 bytes) or as ldr pc, =<label>; <addr> (which uses 8 bytes). Before this commit we were dereferencing an instruction pointer, in get_call_table_entry, assuming 8 bytes per entry. This could overflow and crash if we used in fact only 4 bytes per entry. Fix this by including the entry size in the aot image.
Fixes random crashes on arm CI on full-aotmixed suite.
=> [arm] Fix fetching of method addresses

packaging/MacSDK/msbuild.py
.. which is tracking dotnet branch `release/3.1.1xx`.
=> [2019-08] Bump msbuild to track xplat-master

mcs/tools/mkbundle/bundle-mono-api.inc, mcs/tools/mkbundle/template_common.inc
This change fixes conflicting definitions of mono_aot_register_module.
This caused our mkbundle use case to fail on mono 6.4.
Also removed a seemingly unneeded definition in template_common.inc.
Fixes #17139
=> mkbundle: fix 17139 mono aot register module fix definitions

configure.ac, mono/utils/mono-threads-coop.c, netcore/CoreFX.issues.rsp
This reverts https://github.com/mono/mono/commit/ad90ebd3abf06a33174ebf0979950025e7381f50 that seems to be a little to aggressive in its optimization.
It also enables a flaky test in CoreFx test suite that seems to hit the case where optimization of native code in mono_threads_enter_gc_safe_region_unbalanced_with_info, lost a reference to a managed SafeHandle only kept in a register. That reference needs to be spilled as part of doing copy_stack_data, making sure it is still visible to GC.
=> Always do copy_stack_data on entering GC safe/unsafe.

mcs/class/corlib/Test/System.Reflection.Emit/CustomAttributeBuilderTest.cs, mono/metadata/loader.c, mono/metadata/sre.c
Fixes #16570
We were treating the union as though it was a different type than it really is, and so we got junk data for the pointers and attempting to access them caused a crash.
Also fixed a typo seen along the way.
=> [reflection] Only duplicate MonoMarshalSpec strings for custom types

sdks/wasm/xunit-exclusions.rsp
`CoreXml.Test.XLinq.LoadSaveAsyncTests.RoundtripSyncAsyncMatches_Stream` tests passes on latest master.
CI logs:
```
...
WASM: CoreXml.Test.XLinq.LoadSaveAsyncTests.RoundtripSyncAsyncMatches_Stream
...
WASM: TESTS = 686, RUN = 994, SKIP = 63, FAIL = 0
make: Leaving directory '/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm'
*** end(149): xunit-System.Xml.Linq: [42mPassed[0m
...
```
Fixes https://github.com/mono/mono/issues/16878
/cc @steveisok
=> [wasm] Enable CoreXml.Test.XLinq.LoadSaveAsyncTests.RoundtripSyncAsyncMatches_Stream test

mcs/class/corlib/Test/System.Reflection.Emit/CustomAttributeBuilderTest.cs, mono/metadata/loader.c, mono/metadata/sre.c
Fixes #16570
We were treating the union as though it was a different type than it really is, and so we got junk data for the pointers and attempting to access them caused a crash.
Also fixed a typo seen along the way.
Backport of #17175.
=> [2019-08] [reflection] Only duplicate MonoMarshalSpec strings for custom types

mono/utils/mono-merp.c
Not 1 (TRUE)
Backport of #17185.
=> [2019-08] [merp] exit_status is 0 if we ran the uploader successfully

configure.ac, mono/utils/mono-threads-coop.c
This reverts ad90ebd that seems to be a little to aggressive in its optimization. It also enables a flaky test in CoreFx test suite that seems to hit the case where optimization of native code in mono_threads_enter_gc_safe_region_unbalanced_with_info, lost a reference to a managed SafeHandle only kept in a register. That reference needs to be spilled as part of doing copy_stack_data, making sure it is still visible to GC.
Backport of #17150.
=> [2019-08] Always do copy_stack_data on entering GC safe/unsafe mode.

mono/utils/mono-merp.c
Not 1 (TRUE)
Backport of #17185.
=> [2019-06] [merp] exit_status is 0 if we ran the uploader successfully

mono/metadata/threads.c
Followup work for https://github.com/mono/mono/pull/17090
In order to get managed method info for unmanaged stacktraces, we call
`mini_jit_info_table_find_ext` which calls `decode_exception_debug_info` which may
allocate if it's not in async context.
Do the switch in `mono_threads_summarize_execute` so that non-supervising threads
all switch when they run the `sigterm_signal_handler`.  `mono_threads_summarize`
already does it for the supervisor thread.
Fixes https://github.com/mono/mono/issues/17180
=> [merp] Put thread into async context before running summarizer

mono/metadata/threads.c
Followup work for https://github.com/mono/mono/pull/17090
In order to get managed method info for unmanaged stacktraces, we call
`mini_jit_info_table_find_ext` which calls `decode_exception_debug_info` which may
allocate if it's not in async context.
Do the switch in `mono_threads_summarize_execute` so that non-supervising threads
all switch when they run the `sigterm_signal_handler`.  `mono_threads_summarize`
already does it for the supervisor thread.
Fixes https://github.com/mono/mono/issues/17180
Backport of #17194.
=> [2019-08] [merp] Put thread into async context before running summarizer

mcs/class/corlib/System.Security.Permissions/SiteIdentityPermission.cs, mcs/class/corlib/Test/System.Security.Permissions/SiteIdentityPermissionTest.cs
We were throwing an IndexOutOfRangeException with a string like 'www.mono-project.com*' when an ArgumentException was expected.
Fixes https://github.com/mono/mono/issues/17017
=> Re-ordered the wildcard IsValid check in SiteIdentityPermissions

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/mini-exceptions.c
If there is a perform_wait_callback in the stack there will be another catch generated by the method called in the owner thread, so we don't need to throw as unhandled exception, we can continue and find the next catch.
Fixes #17083
=> [debugger][exception] Debugger breaks on handled exceptions

packaging/MacSDK/msbuild.py
.. to track https://github.com/mono/msbuild/pull/143 .
`Update SDKs to track vs16.4 and `.NET Core 3.1 Dev``
=> Bump msbuild to track mono-2019-08

data/lldb/monobt.py
Instead of:
```
(lldb) mbt 20
* thread #11
* frame #0: 0x1bf28f28 libsystem_kernel.dylib`__pthread_kill + 8
frame #1: 0x1bf9caac libsystem_pthread.dylib`pthread_kill + 300
frame #2: 0x1be66080 libsystem_c.dylib`abort + 140
frame #3: 0x024bdfa0 monotouchtest`log_callback(log_domain=0x00000000, log_level="error", message="../../../../../mono/metadata/object.c:1905: Expected GC Unsafe mode but was in STATE_BLOCKING state", fatal=4, user_data=0x00000000) at runtime.m:1251:3
frame #4: 0x02487f44 monotouchtest`monoeg_g_logv_nofree(log_domain=0x00000000, log_level=G_LOG_LEVEL_ERROR, format=<unavailable>, args=<unavailable>) at goutput.c:149:2 [opt]
frame #5: 0x02487ee0 monotouchtest`monoeg_g_logv(log_domain=<unavailable>, log_level=<unavailable>, format=<unavailable>, args=<unavailable>) at …
```
=> [lldb] use mono_method_full_name helper

mcs/tools/mono-service/mono-service.cs
There is a bug in mono-service.cs file.
`setup.ApplicationBase = Environment.CurrentDirectory;`;
General `Environment.CurrentDirectory` does returns `Directory.GetCurrentDirectory()`.
And retuened value 'current path' without last character `/` but `AppDomain.CurrentDomain.BaseDirectory`;
It have a problem in my service application.
In my service application code,
```cs
using System;
using System.IO;
namespace BaseDirTest
{
internal class Program
{
public static void Main(string[] args)
{
var baseDir = AppDomain.CurrentDomain.BaseDirectory;
Console.WriteLine($"baseDir={baseDir}");
Console.WriteLine($"Path.GetDirectoryName(baseDir)={Path.GetDirectoryName(baseDir)}");
}
}
}
```
When I launch `mono app.exe`,
```bash
baseDir=/workspace/test/mono-owin-test/ConsoleApplication1/BaseDirTest/bin/De …
```
=> Fixed a bug in mono-service.cs

autogen.sh, configure.ac
Previous attempt to do this as part of configure.ac didn't cover all cases since the auto generated parts of configure script already setup some values before we had the chance to set --host-alias. In order to fix this, the check for --host is moved to autogen.sh, making sure we pass --host to configure step, if missing.
NOTE, this will only apply to cygwin build that, by default, wants a different host/target toolchain compared to what config.guess delivers. By default, we will use --host=x86_64-w64-mingw32 when running autogen.sh without passing --host parameter on cygwin. NOTE, there is already a error on cygwin for this case in configure.ac, so it is currently not possible without passing --host to configure.
=> Set default value for --host in autogen.sh on cygwin when missing.

mono/metadata/class-internals.h, mono/metadata/class.c, mono/metadata/icall.c, netcore/System.Private.CoreLib/src/System/TypeNameParser.cs
Resolves parser issues discussed in https://github.com/mono/mono/pull/16425#issuecomment-529661033, along with some minor cleanup. 
The commit making TypeNameParser consistent can be removed if the line damage isn't worth it, but the file is currently a mess, so I'm of the opinion that it is.
This is maybe worth rebasing for the history, perhaps with the last two commits squashed?
=> Clean up assembly name parsers' handling of special chars

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/mini-exceptions.c
If there is a perform_wait_callback in the stack there will be another catch generated by the method called in the owner thread, so we don't need to throw as unhandled exception, we can continue and find the next catch.
Fixes #17083
Backport of #17106.
/cc @thaystg
=> [2019-08] [debugger][exception] Debugger breaks on handled exceptions

mono/utils/mono-merp.c, mono/utils/mono-state.c, mono/utils/mono-state.h
Simplify by moving all marker file creation to `mono_summarize_timeline_phase_log` 
/cc @lambdageek @kdubau
=> [merp] Print missing status marker file for stage 1 (setup)

netcore/CoreFX.issues.rsp, netcore/CoreFX.issues_linux.rsp
The tests are kinda bogus since they create a SafeWaitHandle from `new IntPtr(1)` which causes a crash during finalization when releasing that handle.
See https://github.com/mono/mono/issues/17224
=> [netcore] Disable some SafeWaitHandle tests everywhere, not just Linux

configure.ac, packaging/MacSDK/msbuild.py
- Bumps msbuild to track `mono-2019-08` branch
- Bumps roslyn to `3.4.0-beta2-19477-01 `
=> [2019-08] Bump msbuild+roslyn

mono/metadata/object.c
It breaks Xamarin.Android.
Backport of #17233.
=> [2019-10] Revert mono_runtime_set_main_args in 44ff0597b835d0af62f526169dba3b365c9c3411.

mono/metadata/object.c
=> Revert mono_runtime_set_main_args in 44ff0597b835d0af62f526169dba3b365c9c3411.

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/mini-exceptions.c
If there is a perform_wait_callback in the stack there will be another catch generated by the method called in the owner thread, so we don't need to throw as unhandled exception, we can continue and find the next catch.
Fixes #17083
Backport of #17106.
=> [2019-06] [debugger][exception] Debugger breaks on handled exceptions

mcs/class/Facades/System.Drawing.Common/Facades_System.Drawing.Common.csproj, mcs/class/Facades/System.Drawing.Common/Makefile
Needed for https://github.com/xamarin/xamarin-android/issues/3726
Backport of #17238.
=> [2019-06] Add drawing type converters to mobile profiles

mono/mini/memory-access.c
When doing memory copy dest is the destination address and src is the source address. If we are copying a single reference, we need to emit a write barrier and pass to the write barrier the value, not the pointer where the value is stored. Otherwise nursery checks will fail and we won't mark the card table.
=> [sgen] Fix invalid value passed to write barrier

mono/mini/memory-access.c
When doing memory copy dest is the destination address and src is the source address. If we are copying a single reference, we need to emit a write barrier and pass to the write barrier the value, not the pointer where the value is stored. Otherwise nursery checks will fail and we won't mark the card table.
Backport of #17236.
=> [2019-10] [sgen] Fix invalid value passed to write barrier

mono/mini/memory-access.c
When doing memory copy dest is the destination address and src is the source address. If we are copying a single reference, we need to emit a write barrier and pass to the write barrier the value, not the pointer where the value is stored. Otherwise nursery checks will fail and we won't mark the card table.
Backport of #17236.
=> [2019-08] [sgen] Fix invalid value passed to write barrier

mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/metadata/sgen-mono-ilgen.c, mono/metadata/string-icalls.c, mono/mini/method-to-ir.c, netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml
The check that was supposed to take managed allocation code path for strings was broken since e58097e957af9939c94ee46ecd78e38b16a1f989. It went unnoticed for over 4 years.
=> [mini] Fix check for FastAllocateString that used old name

mono/mini/method-to-ir.c
before:
```
fmove R11 <- R9
ff  11 9
1  nop
```
after:
```
fmove R11 <- R9
ff  11 9
0  loadr8_membase R11 <- [%ebp + 0x8]
1  nop
```
=> [mini] print inserted instruction in verbose logging

mcs/class/Mono.Posix/Mono.Posix_test.dll.sources, mcs/class/Mono.Posix/Mono.Unix.Native/NativeConvert.generated.cs, mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs, mcs/class/Mono.Posix/Test/Mono.Unix.Native/MemfdTest.cs, support/map.c, support/map.h
Add the linux syscall memfd_create() and add support for file sealing with
fcntl().
=> [Mono.Posix] Add support for memfd_create() and file sealing

mcs/class/System.Web/System.Web.Security/FormsAuthenticationTicket.cs
Now IsExpired property compares two dates (actual datetime and expiration datetime) with same kind (UTC) due to converting both dates to UTC. Fixes #17161
=> Now IsExpired property for FormsAuthenticationTicket compares two dates with same kind (UTC)

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/mini/mini-llvm.c
After https://github.com/mono/mono/commit/9ff3b0d65ee4, in an aot image we can emit addresses either as bl offset (which uses 4 bytes) or as ldr pc, =<label>; <addr> (which uses 8 bytes). Before this commit we were dereferencing an instruction pointer, in get_call_table_entry, assuming 8 bytes per entry. This could overflow and crash if we used in fact only 4 bytes per entry. Fix this by including the entry size in the aot image.
Fixes random crashes on arm CI on full-aotmixed suite.
Backport of https://github.com/mono/mono/pull/17099
=> [2019-08][arm] Fix fetching of method addresses

mono/eglib/glib.h, mono/eglib/goutput.c
g_assertf unchanged.
I have a strong suspicion, this will save approximately 432 - sizeof (InterpFrame) bytes of stack
per function call in the WebAssembly interpreter.
It will not significantly benefit or hurt any other system.
Systems with disabled asserts will receive a small size improvement.
WebAssembly has no provision for varargs.
Emscripten emulates it.
It appears the emulation allocates room in the frame per outgoing varargs call.
No stack packing.
So each g_assert takes space.
Alternative would be to discourage or disable or remove asserts.
=> Remove varargs from g_assert and g_assert_not_reachable (save 200+ bytes per frame in wasm interp).

mcs/class/Mono.Debugger.Soft/Test/dtest.cs
Running these tests makes the application crash, probably at shutdown. Even if the tests are reported as passing, check if disabling them fixes the suite timeout on android osx sdks.
```
Unloading domain TEST RUNNER[0x9cdb3c00], assembly foo[0xa4cab530], ref_count=1
Unloading assembly foo [0xa4cab530].
Unloading image foo [0x89865c00].
Unloading image foo [0x875ef000].
* Assertion at /Users/vbrezae/Xamarin/repos/mono2/mono/metadata/image.c:2470, condition `!image->reflection_info_unregister_classes || mono_runtime_is_shutting_down ()' not met
```
=> [tests] Disable tests that crash on android sdks

mono/mini/gshared.cs, mono/mini/jit-icalls.c
For generic constrained virtual calls using reference type's, the virtual call will be dispatched using instance vtable. When the same virtual call is taking place in a gsharedvt method, mono_gsharedvt_constrained_call gets called that will assist making the call, the problem is that it will
use the constrained class for reference types meaning that it will not call the most derived implementation of the method. This difference in the behavior compared to none gsharedvt versions of methods, gives inconsistent results.
One way this will reproduce is by using Dictionary<Type, EmptyStruct>. For methods that will take both Type (reference type) and EmptyStruct (value type) like Add, calling that through IDictionary (hiding details from compiler) will use the gsharedvt version of the method. …
=> Incorrect constrained virtual call in method using gsharedvt for reference type.

mono/eglib/glib.h
Currently we can get output like this:
```
gstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' failedgstr.c:992: assertion 'src != NULL' …
```
=> [eglib] Add newline for failure check prints

mono/utils/mono-merp.c, mono/utils/mono-state.c, mono/utils/mono-state.h
Simplify by moving all marker file creation to `mono_summarize_timeline_phase_log` 
/cc @lambdageek @kdubau 
Backport of #17213.
/cc @alexischr
=> [2019-08] [merp] Print missing status marker file for stage 1 (setup)

mono/utils/mono-merp.c, mono/utils/mono-state.c, mono/utils/mono-state.h
Simplify by moving all marker file creation to `mono_summarize_timeline_phase_log` 
/cc @lambdageek @kdubau 
Backport of #17213.
/cc @alexischr
=> [2019-10] [merp] Print missing status marker file for stage 1 (setup)

mcs/class/Mono.Debugger.Soft/Test/dtest.cs, sdks/android/app/src/main/c/runtime-bootstrap.c
mini_jit_cleanup will cause mono_runtime_try_shutdown to be called before
mono_runtime_quit which will set the shutting down flags in the runtime.
Fixes #17256
=> [sdks] Android runner: properly shutdown runtime for Mono.Debugger.Soft test app

sdks/android/app/src/main/c/runtime-bootstrap.c
mini_jit_cleanup will cause mono_runtime_try_shutdown to be called before
mono_runtime_quit which will set the shutting down flags in the runtime.
Fixes #17256
Backport of #17261.
=> [2019-10] [sdks] Android runner: properly shutdown runtime for Mono.Debugger.Soft test app

mono/metadata/icall.c, mono/metadata/threads.c, mono/mini/mini-posix.c
install_state_summarizer installs a SIGTERM handler. Unfortunately sigterm_signal_handler assumes that it will only be called when a crash is already in progress (it assumes it won't be the supervisor, and so it doesn't setup the memory for capturing a crash report among other things).
Addresses #17271
=> [2019-06][merp] Don't install SIGTERM handler in EnableMicrosoftTelemetry

sdks/wasm/src/library_mono.js
This adds the ability to continue loading the application even though the .pdb files are not found.
When uploading an app built with mono-wasm the `.pdb` may not get committed so they will not exist when trying to load them.
- Add new boolean variable to MONO library support to control skipping these files on errors.
- `mono_wasm_ignore_pdb_load_errors` default is true
- Modify the assembly file fetching routine `mono_load_runtime_and_bcl` within our MONO module.
- Allows skipping the .pdb files if the `mono_wasm_ignore_pdb_load_errors` flag is true.
Tested this against Windows browsers and it still works:
Current test url:  https://kjpou1.github.io/WasmTestPDB/
=> [wasm] Continue loading app even when `.pdb` files are not found

mono/mini/mini-amd64.c, mono/mini/mini-x86.c, netcore/CoreFX.issues.rsp
The [fsin](https://www.felixcloutier.com/x86/fsin) and [fcos](https://www.felixcloutier.com/x86/fcos) instructions work only within the −2^63 to +2^63 range. Even within this range they are document to be accurate only for values between -3π/4 and +3π/4. Just kill the whole optimization completely and use the C runtime `cos`/`sin` instead.
Fixes #15106
Fixes #15107
Fixes #15108
Fixes #15109
Fixes #15110
/cc @MaximLipnin
=> [mini] Remove broken sin/cos optimization for x86/x64

mono/metadata/icall.c, mono/mini/mini-posix.c
install_state_summarizer installs a SIGTERM handler. Unfortunately sigterm_signal_handler assumes that it will only be called when a crash is already in progress (it assumes it won't be the supervisor, and so it doesn't setup the memory for capturing a crash report among other things).
Addresses #17271
Backport of #17296.
=> [2019-08][merp] Don't install SIGTERM handler in EnableMicrosoftTelemetry

mono/metadata/icall.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/mini/debugger-agent.c, netcore/CoreFX.issues.rsp
CoreCLR doesn't suspend threads on exit (https://github.com/dotnet/corefx/pull/41450#issuecomment-536755093, https://github.com/dotnet/coreclr/pull/1813).
Fixes #17317 
Fixes #15006
Fixes #15010
Fixes #15181
Unblocks #17232
=> [netcore] Avoid suspending threads in Environment.Exit, it can hang process

mono/metadata/icall.c, mono/mini/mini-posix.c
install_state_summarizer installs a SIGTERM handler. Unfortunately sigterm_signal_handler assumes that it will only be called when a crash is already in progress (it assumes it won't be the supervisor, and so it doesn't setup the memory for capturing a crash report among other things).
Addresses #17271
Backport of #17296.
=> [2019-10][merp] Don't install SIGTERM handler in EnableMicrosoftTelemetry

mono/metadata/w32file-unix.c
Fixes #17151
This brings us in line with GetDiskFreeSpaceExW on Windows as well as .NET Core.
I checked with the Android folks and it seems like this won't fail their test - all they check is that the returned value isn't `long.MaxValue`.
Backport of #17177.
/cc @marek-safar @CoffeeFlux
=> [2019-06] [IO] Remove read-only logic in mono_w32_get_disk_free_space

scripts/ci/pipeline/sdks-archive.groovy, scripts/ci/run-jenkins.sh
As requested by the xamarin-macios team.
=> [2019-08][ci] Use Xcode11.1 and 11.2beta2 for XI/XM Mono SDK builds

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/utils/mono-merp.c, mono/utils/mono-merp.h
Backport of #17131  to `2019-08`
---
* Update parameters in MERP WerReportMetadata xml
To enable backend analysis, we need to update our parameters to match our back end event type, which is MonoAppCrash.
It doesn't make sense to me that the previous implementation constructed the XML here in Mono, but depended on the user (VSMac in this case) to add the "correct" event type.  The parameters in the XML, must match exactly what is expected for the given EventType, and so we should ensure they are always in-sync by defining them here.  Thus, I removed the usage of `eventType` in `mono_merp_enable` and hard coded the expected eventType.
* [merp] Don't pass eventType from managed
The eventType must me MONO_MERP_EVENT_TYPE_STR ("MonoAppCrash") - the backend
determines the format of the other …
=> [2019-08] Update MERP event type to MonoAppCrash

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/utils/mono-merp.c, mono/utils/mono-merp.h
Backport of #17131 to `2019-10`
---
* Update parameters in MERP WerReportMetadata xml
To enable backend analysis, we need to update our parameters to match our back end event type, which is MonoAppCrash.
It doesn't make sense to me that the previous implementation constructed the XML here in Mono, but depended on the user (VSMac in this case) to add the "correct" event type.  The parameters in the XML, must match exactly what is expected for the given EventType, and so we should ensure they are always in-sync by defining them here.  Thus, I removed the usage of `eventType` in `mono_merp_enable` and hard coded the expected eventType.
* [merp] Don't pass eventType from managed
The eventType must me MONO_MERP_EVENT_TYPE_STR ("MonoAppCrash") - the backend
determines the format of the other …
=> [2019-10] Update MERP event type to MonoAppCrash

netcore/build.sh, scripts/ci/pipeline-netcore-runtime.yml
This should add some basic output into our builds on VSTS, following https://github.com/dotnet/arcade/blob/master/Documentation/Projects/DevOps/CI/Telemetry-Guidance.md, which will feed into the .NET Core builds dashboard to better show where our builds are failing.
=> Initial telemetry for netcore builds

mcs/class/corlib/System/CStreamWriter.cs, mcs/class/corlib/System/TermInfoDriver.cs
In https://github.com/mono/mono/commit/fd424c5dd07b2dbbd4aafbf9165a42166d789438 we switched over to the `TextWriter.cs`/`StreamWriter.cs` implementation of corefx. One subtle difference is that an override for `WriteLine(string)` in `StreamWriter` was introduced:
https://github.com/mono/corefx/blob/8e3b279377d1f01d2d089f24548e33855bf6502e/src/Common/src/CoreLib/System/IO/StreamWriter.cs#L526-L531
Previously the definition in `TextWriter` was used, which would call the base case `Write(char[],int,int)`.  The new override however won't call the base implementation at all, but directly uses the `Span`-variant.
This is a problem for our `CStreamWriter` implementation, since `WriteLine(string)` won't end up in the special handling for `Write(char[],int,int)`, which accounts for terminal cursor …
=> [bcl] add WriteLine(string) override to CStreamWriter needed due to corefx import

mcs/class/corlib/System/CStreamWriter.cs, mcs/class/corlib/System/TermInfoDriver.cs
In https://github.com/mono/mono/commit/fd424c5dd07b2dbbd4aafbf9165a42166d789438 we switched over to the `TextWriter.cs`/`StreamWriter.cs` implementation of corefx. One subtle difference is that an override for `WriteLine(string)` in `StreamWriter` was introduced:
https://github.com/mono/corefx/blob/8e3b279377d1f01d2d089f24548e33855bf6502e/src/Common/src/CoreLib/System/IO/StreamWriter.cs#L526-L531
Previously the definition in `TextWriter` was used, which would call the base case `Write(char[],int,int)`.  The new override however won't call the base implementation at all, but directly uses the `Span`-variant.
This is a problem for our `CStreamWriter` implementation, since `WriteLine(string)` won't end up in the special handling for `Write(char[],int,int)`, which accounts for terminal cursor …
=> [2019-10] [bcl] add WriteLine(string) override to CStreamWriter needed due to corefx import

configure.ac, mono/metadata/loader-internals.h, mono/metadata/loader.c, mono/metadata/metadata-internals.h, mono/metadata/mono-config.c, mono/metadata/native-library.c, msvc/build-init.vcxproj
Previously, we were adding and parsing the DllMap entries but not using them, which seems silly. This puts all DllMap functionality behind a single define and enables it for non-netcore.
=> [loader] Add an explicit define DISABLE_DLLMAP to control dllmap usage

sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs
Set default `StreamingEnabled` property of the WasmHttpMessageHandler to be `false`.
Due to the way that the javascript `Fetch` API works asynchronously the non asynchronous methods of the wrapped stream can not be used.  
There are some API's such as the `CsvHelper` that do not implement an async API.
Setting the default implementation to false solves this issue as the read content is wrapped in a memory stream and is able to be used in those circumstances.
fixes https://github.com/mono/mono/issues/17343
=> [wasm][http] WasmHttpMessageHandler StreamingEnabled default to false

mcs/tests/known-issues-interp-net_4_x, mono/mini/interp/mintops.h, mono/mini/interp/transform.c
StackValue can contain now also the value of an integer. We track these values on the stack and in locals. Constant values take precedence over local propagation, meaning that if a local contains the value of another local, which in turn stores a constant, then we mark the original local as storing a constant. We try to replace local usage (LDLOC) with constant usage (LDC) so we can kill more locals.
=> [interp] Add constant propagation of integers

mono/metadata/appdomain.c, mono/metadata/assembly.c, mono/metadata/assembly.h, mono/metadata/external-only.c, mono/metadata/icall.c, mono/mini/mini-wasm-debugger.c
Maybe just remove the GC mode change and remove the internal form.
We don't really equate malloc/free with GC/locks/hangs, though arguably we should. Arguably this change is right.
=> Replace mono_assembly_name_free use with mono_assembly_name_free_internal.

netcore/build.sh, scripts/ci/pipeline-netcore-runtime.yml, scripts/ci/run-jenkins.sh
Follow-up to https://github.com/mono/mono/pull/17331.
We were running nuget pack and tests explicitly in the Azure Pipelines
config so we weren't capturing failure telemetry.
=> [ci] Improve netcore build telemetry by running nupkg and tests through build.sh

netcore/corerun/Makefile.am
=> [netcore] Fix build for Windows with cygwin

configure.ac, mcs/class/corlib/System.Threading/Interlocked.cs, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, netcore/System.Private.CoreLib/src/System.Threading/Interlocked.cs
`Exchange<T>` is supposed to be picked up as an intrinsic.  But if it isn't (until #17338 is merged),
since `T` has a class constraint, call the `Exchange (ref object, ref object, ref object)` overload instead.
This works around a limitation in the JIT:
https://github.com/mono/mono/blob/82a07273c22b996b08fa88ee2e6632d782ac2242/mono/mini/mini-trampolines.c#L704-L713
if we're in the common call trampoline, and the caller is generic method and the callee is a generic method, if we're using generic sharing for the caller, but there's no generic jit info for the callee, we will not patch the call site.
In this case we had `Exchange<T>` calling `Exchange_T<T>`
where the callee is an icall (and evidently didn't have generic jit info).
So every time we called `Exchange<T>`, we would go through …
=> [bcl][jit] implement Interlocked.Exchange<T> in terms of object

mcs/class/System/monotouch_watch_System_xtest.dll.exclude.sources
Removing execution of network tests from WatchOs.
Backport of #17358.
/cc @thaystg
=> [2019-10] Removing execution of network tests from WatchOs.

sdks/wasm/xunit-exclusions.rsp
Fixes https://github.com/mono/mono/issues/17053
/cc @steveisok
=> [wasm][xunit tests] Disable System.IO.Compression.Tests.BrotliEncoderTests

mcs/class/corlib/System.Threading/Interlocked.cs
In https://github.com/mono/mono/pull/17341 we change the caller of `CompareExchange_T<T>(ref T, ...)` to call `CompareExchange (ref object, ...)`, but didn't delete the declaration.
It's already deleted in unmanaged and in the netcore version of this file.
=> [bcl] Remove CompareExchange_T

mono/metadata/marshal-ilgen.c, mono/tests/libtest.c, mono/tests/safehandle.2.cs
* Fix SafeHandle marshalling in ref/in/out parameters
* Fix test_0_safehandle_ref test. The test was expecting incorrect behavior, verified on .NET Core 3 and .NET Framework 4.8.
* Add more tests for SafeHandle marshalling
=> [2019-10] Fix SafeHandle marshalling in ref/in/out parameters

mono/metadata/marshal-ilgen.c, mono/tests/libtest.c, mono/tests/safehandle.2.cs
* Fix SafeHandle marshalling in ref/in/out parameters
* Fix test_0_safehandle_ref test. The test was expecting incorrect behavior, verified on .NET Core 3 and .NET Framework 4.8.
* Add more tests for SafeHandle marshalling
=> [2019-08] Fix SafeHandle marshalling in ref/in/out parameters

mcs/class/referencesource/mscorlib/system/runtime/compilerservices/YieldAwaitable.cs
Make it consistent with .NET Standard/Core which makes future API Compat runs report one less difference.
=> [corlib] Mark YieldAwaitable struct readonly

mcs/class/referencesource/mscorlib/system/runtime/compilerservices/YieldAwaitable.cs
Make it consistent with .NET Standard/Core which makes future API Compat runs report one less difference.
Backport of #17386.
=> [2019-10] [corlib] Mark YieldAwaitable struct readonly

mono/metadata/profiler.c, mono/profiler/coverage.c
If we have coverage profiling enabled for a method (mono_profiler_coverage_instrumentation_enabled, with coverage_filter callback), then we should be able to allocate a coverage info structure (mono_profiler_coverage_alloc). After https://github.com/mono/mono/commit/52429673dc617fd437518757c04c7448211075e9, coverage_filter was reporting wrapper methods as ok to profile, while mono_profiler_coverage_alloc was refusing to allocate the necessary structure, leading to crashes.
=> [profiler] Fix coverage profiler on macos

.gitignore
This will ignore the __pycache__ files generated after the tools offset build.
=> [sdks] add .gitignore python __pycache__

mcs/class/corlib/System.Threading/Interlocked.cs, netcore/System.Private.CoreLib/src/System.Threading/Interlocked.cs
and Interlocked.CompareExchange<T>
This is to mimic the old behavior in unmanaged when the intrinsic cannot be
used.
The issue was detected via the coreclr acceptance test:
https://github.com/mono/coreclr/blob/mono/tests/src/baseservices/threading/interlocked/exchange/exchangetneg.il
=> [bcl] Add null reference checks to Interlocked.Exchange<T>

sdks/wasm/src/library_mono.js
closes https://github.com/mono/mono/issues/17454
=> [wasm] Export `mono_load_runtime_and_bcl` so that it is available on the Module.

sdks/wasm/src/library_mono.js
- Tests if we are running in ENVIRONMENT_IS_NODE
- run message pump if we are.
- This also fixes GC not running.
- Clean up some messages.
reported in issue: https://github.com/mono/mono/issues/17398
=> [wasm] Make sure message pump is working when executing via NODEJS

mcs/class/System.Net.Http/Test/System.Net.Http.Headers/HttpHeaderValueCollection.cs, mcs/class/System.Net.Http/Test/System.Net.Http.Headers/HttpHeadersTest.cs, mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs, mcs/class/System.Net.Http/Test/System.Net.Http/HttpRequestMessageTest.cs, mcs/class/System.Net.Http/Test/System.Net.Http/HttpResponseMessageTest.cs
Fixes the conditional from mono/mono#17423, we don't define __WATCHOS__ in the Mono BCL builds. We use MONOTOUCH_WATCH instead.
=> [tests] Replace __WATCHOS__ with MONOTOUCH_WATCH

sdks/wasm/src/binding_support.js
- The checking for the existence of the object is incorrect: Missing parens around undefined.
- Modify error description returned back to managed code.
- Fix capitalization in global object check error.
closes https://github.com/mono/mono/issues/17449
=> [wasm][binding] Fix host object existence check.

mono/mini/interp/interp.c
From https://github.com/mono/mono/pull/17325.
=> [cxx][debug-interp] Cast once from void* to non-void*.

sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs
Modify the check for streaming to also check that the browser `Response` object exists.
fixes https://github.com/mono/mono/issues/17448
=> [wasm][http] WasmHttpMessageHandler: Fix streaming check Unhandled Exception.

mcs/class/System/System.Net.Sockets/Socket.cs, mcs/class/System/Test/System.Net.Sockets/SocketTest.cs
The following commit, 068e8fe changed the way we do DNS resolve in BeginConnect using host name. Instead of doing a blocking DNS resolve, it switched to an async DNS resolve, followed by an async connect. The returned IAsyncResult was just representing the completion of the DNS resolve task and not the underlying connect. It
also turns out that part of doing EndConnect, we did some validation of the used IAsyncResult making sure it was an instance of SocketAsyncResult, meaning that if EndConnect was called on the returned IAsyncResult from BeginConnect, EndConnect would throw and exception.
NOTE, this only happens if you use pattern like this:
var result = sock.BeginConnect (hostName, port, null, null);
result.AsyncWaitHandle.WaitOne (2000);
sock.EndConnect (result);
It did not happened …
=> [2019-08]   BeginConnect complete to early when not using callback.

mono/metadata/profiler.c, mono/profiler/coverage.c
If we have coverage profiling enabled for a method (mono_profiler_coverage_instrumentation_enabled, with coverage_filter callback), then we should be able to allocate a coverage info structure (mono_profiler_coverage_alloc). After https://github.com/mono/mono/commit/52429673dc617fd437518757c04c7448211075e9, coverage_filter was reporting wrapper methods as ok to profile, while mono_profiler_coverage_alloc was refusing to allocate the necessary structure, leading to crashes.
Backport of #17396.
/cc @BrzVlad
=> [2019-10] [profiler] Fix coverage profiler on macos

mono/metadata/icall-internals.h
From https://github.com/mono/mono/pull/17325.
https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx-products-sdks-android/17137/parsed_console/log_content.html
In file included from /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/metadata/icall.c:42:
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/metadata/icall-internals.h:89:10: fatal error: 'type_traits' file not found.
=> [cxx] No type_traits on Android.

mono/mini/interp/transform.c
LDC is faster and also allows for constant propagation. Cleanup code a little bit.
=> [interp] Replace loading of static readonly fields with LDC

sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
Check the length of the vars array not the ids string when looping over variables.  Fixes a crash in the inspection logic.
=> [debugger][wasm] Check the length of the vars array. Fixes #17473

mono/metadata/profiler.c, mono/profiler/coverage.c
If we have coverage profiling enabled for a method (mono_profiler_coverage_instrumentation_enabled, with coverage_filter callback), then we should be able to allocate a coverage info structure (mono_profiler_coverage_alloc). After https://github.com/mono/mono/commit/52429673dc617fd437518757c04c7448211075e9, coverage_filter was reporting wrapper methods as ok to profile, while mono_profiler_coverage_alloc was refusing to allocate the necessary structure, leading to crashes.
Backport of #17396.
/cc @BrzVlad
=> [2019-08] [profiler] Fix coverage profiler on macos

mono/mini/exceptions-amd64.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h
=> [2019-10] [jit] Avoid running mono_handle_native_crash () on the altstack, it can't produce a backtrace. AMD64 only for now.

mono/utils/checked-build.c, mono/utils/mono-threads-coop.c, mono/utils/mono-threads-state-machine.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
Because we have extra bits (like suspend count and the no_checkpoints bit) on
the thread state, we have to mask it to get the actual thread state enum value.  This was broken in the checked build code, previoiusly, and in general it was easy to get wrong.  Instead let's use bitfields.
But we still need access to the whole state as a 32-bit int so that we can do atomic cas
=> [coop] Use bitfields for coop state machine state representation

mcs/class/corlib/Test/System/AttributeTest.cs, mono/metadata/class.c
The issue is in how we pass along the generic instantiation.  So there are two parts here:
* we start with a method on a GTD which has to decompose into the GTD and it's instantiation with its own generic parameters, 
* and then we go up to its parent and grandparent inflating and decomposing the resulting instantiation. 
In the test, the instantiations keep passing the last parameter as the number of parameters shrinks so that the gparam index from the original type is now out of bounds for the parent and grandparent.
If we mess up, we'll get a `BadImageFormatException` from the runtime
Fixes #17278
=> [reflection] mono_method_get_base_method on a GTD should use canonical ginst

configure.ac, mcs/class/corlib/System.Threading/Interlocked.cs, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, netcore/System.Private.CoreLib/src/System.Threading/Interlocked.cs
Backport of #17341 to `2019-10`
---
`Exchange<T>` is supposed to be picked up as an intrinsic.  But if it isn't (until #17338 is merged),
since `T` has a class constraint, call the `Exchange (ref object, ref object, ref object)` overload instead.
This works around a limitation in the JIT:
https://github.com/mono/mono/blob/82a07273c22b996b08fa88ee2e6632d782ac2242/mono/mini/mini-trampolines.c#L704-L713
if we're in the common call trampoline, and the caller is generic method and the callee is a generic method, if we're using generic sharing for the caller, but there's no generic jit info for the callee, we will not patch the call site.
In this case we had `Exchange<T>` calling `Exchange_T<T>`
where the callee is an icall (and evidently didn't have generic jit info).
So every time we called …
=> [2019-10][bcl][jit] implement Interlocked.Exchange<T> in terms of object

mono/mini/interp/transform.c
When replacing a stloc with a pop, we should retry the pass, since it is very likely that we will be able to kill the instruction that pushed that value on the stack. We kill 10% more instructions with this change.
Before
```
Total transform time                : 3266.23 ms
Total cprop time                    : 156.43 ms
STLOC_NP count                      : 100869
MOVLOC count                        : 11303
Copy propagations                   : 18164
Added pop count                     : 25306
Constant folds                      : 62183
Killed instructions                 : 266680
Emitted instructions                : 4867277
```
After
```
Total transform time                : 2959.10 ms
Total cprop time                    : 159.01 ms
STLOC_NP count                      : 100941
MOVLOC …
```
=> [interp] Retry cprop pass if killing stloc

sdks/wasm/src/binding_support.js
- Add `mono_bind_assembly_entry_point`
- Add `mono_call_assembly_entry_point`
- Module.mono_call_assembly_entry_point("WasmHttpStreamSync", []);
Example:
```
Module.mono_call_assembly_entry_point("WasmHttpStreamSync", []);
```
```
var main = Module.mono_bind_assembly_entry_point("WasmHttpStreamSync", []);
main();
```
=> [wasm][binding] Add bindings for calling the entry point of an '.exe'

mono/mini/exceptions-amd64.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h
=> [2019-08] [jit] Avoid running mono_handle_native_crash () on the altstack, it can't produce a backtrace. AMD64 only for now.

mono/metadata/sgen-mono.c, mono/sgen/sgen-array-list.h, mono/sgen/sgen-debug.c, mono/sgen/sgen-gc.c, mono/sgen/sgen-gc.h, mono/sgen/sgen-los.c
Running parallel scan in minor GC doesn't scale out well over multiple cores when the LOS list is getting big. One of the reasons why this happens is the way each job travers the LOS list. Currently, all jobs scan the complete LOS list, skipping jobs not matching their individual job index.
Problem with this is that each thread needs to touch every element in the list, and by default, we  create number of cores * 4 jobs scanning LOS objects. That means we will touch every element 32 times on an 8 core machine, moving a lot of memory between cache levels, increasing the total scan time for the complete LOS scan job.
This is especially problematic on hardware with slower memory bus and smaller caches, but with many cores. On such hardware the accumulated scan time can be bigger when …
=> [sgen] Optimize LOS for better locality and parallelization.

packaging/MacSDK/msbuild.py
VS Mac would like a package without this update so we're reverting temporarily
=> [2019-08] rollback msbuild/roslyn updates for a preview

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/exceptions-amd64.c, mono/mini/exceptions-arm.c, mono/mini/exceptions-arm64.c, mono/mini/exceptions-mips.c, mono/mini/exceptions-ppc.c, mono/mini/exceptions-s390x.c, mono/mini/exceptions-sparc.c, mono/mini/exceptions-x86.c, mono/mini/mini-exceptions.c
Removing all fixes to fix #15203 and #17083, and trying a new approach to fix this #17084, together.
The thing is when we are executing on hybrid suspend the caller is executed inside try catch in the runtime_invoke_ method that is generated. And this try catch should be ignored for the debugger exception, otherwise it's the last try catch in main thread, but should always be considered to generate the stack trace.
Fixes #17084
=> [debugger] Changing how debugger handles exception when hybrid suspend is enabled

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/exceptions-amd64.c, mono/mini/exceptions-arm.c, mono/mini/exceptions-arm64.c, mono/mini/exceptions-mips.c, mono/mini/exceptions-ppc.c, mono/mini/exceptions-s390x.c, mono/mini/exceptions-sparc.c, mono/mini/exceptions-x86.c, mono/mini/mini-exceptions.c
Removing all fixes to fix #15203 and #17083, and trying a new approach to fix this #17084, together.
The thing is when we are executing on hybrid suspend the caller is executed inside try catch in the runtime_invoke_ method that is generated. And this try catch should be ignored for the debugger exception, otherwise it's the last try catch in main thread, but should always be considered to generate the stack trace.
Fixes #17084
Backport of #17478.
/cc @thaystg
=> [2019-10] [debugger] Changing how debugger handles exception when hybrid suspend is enabled

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/exceptions-amd64.c, mono/mini/exceptions-arm.c, mono/mini/exceptions-arm64.c, mono/mini/exceptions-mips.c, mono/mini/exceptions-ppc.c, mono/mini/exceptions-s390x.c, mono/mini/exceptions-sparc.c, mono/mini/exceptions-x86.c, mono/mini/mini-exceptions.c
Removing all fixes to fix #15203 and #17083, and trying a new approach to fix this #17084, together.
The thing is when we are executing on hybrid suspend the caller is executed inside try catch in the runtime_invoke_ method that is generated. And this try catch should be ignored for the debugger exception, otherwise it's the last try catch in main thread, but should always be considered to generate the stack trace.
Fixes #17084
Backport of #17478.
/cc @thaystg
=> [2019-08] [debugger] Changing how debugger handles exception when hybrid suspend is enabled

mcs/class/corlib/Test/System/AttributeTest.cs, mono/metadata/class.c
The issue is in how we pass along the generic instantiation.  So there are two parts here:
* we start with a method on a GTD which has to decompose into the GTD and it's instantiation with its own generic parameters, 
* and then we go up to its parent and grandparent inflating and decomposing the resulting instantiation. 
In the test, the instantiations keep passing the last parameter as the number of parameters shrinks so that the gparam index from the original type is now out of bounds for the parent and grandparent.
If we mess up, we'll get a `BadImageFormatException` from the runtime
Fixes #17278
Backport of #17475.
=> [2019-10] [reflection] mono_method_get_base_method on a GTD should use canonical ginst

configure.ac, mono/eglib/gfile-unix.c, mono/eglib/test/Makefile.am, mono/eglib/test/file.c, mono/eglib/test/path.c, mono/eglib/test/test-eglib.exp
* Work around access(2) syscall bug on PASE
On PASE, X_OK will always returns true. This is contrary to
how AIX behaves (though corresponds to documentation!). This
is probably because it's an upcall to the ILE version of
access, and that seemingly always returns true.
* Always export the dummy function in the test suite
The AIX linker didn't export this properly, without using the
giant sledgehammer of -bexpall. Write an export file and use
it. This required some build system changes to expose an
AIX-only automake conditional.
* Use a file that exists on PASE for tests
PASE doesn't use Unix-style DNS resolution, so /etc/hosts is
missing. Use /etc/magic, since that seems to be present.
* Don't use /bin on AIX/PASE for tests
This is a symlink to /usr/bin, and it seems chdir/getcwd
follows …
=> fix eglib on AIX/PASE

packaging/MacSDK/msbuild.py
This reverts commit 1b2e536b2238aa6bd86722996bcd1cf0f76cd6f3.
now that packages have been built.
=> Revert "[2019-08] rollback msbuild/roslyn updates for a preview"

configure.ac, mono/metadata/metadata-verify.c, mono/metadata/threads.c, mono/metadata/w32process-unix.c, mono/metadata/w32socket-unix.c, mono/mini/driver.c, mono/mini/exceptions-amd64.c, mono/mini/mini-amd64.h, mono/mini/mini-exceptions.c, mono/mini/mini-runtime.c, mono/mini/mini-x86.h, mono/mini/mini.h, mono/utils/mono-context.h, mono/utils/mono-mmap-wasm.c, mono/utils/mono-mmap.c, mono/utils/mono-sigcontext.h, tools/mono-hang-watchdog/mono-hang-watchdog.c
Include signal.h unconditionally.
Some of the includes already were unconditional, including both on Win32 and Unix.
It is part of ANSI C 89, albeit in a reduced form compared to typical Unix (no sigaction).
Its contents has no bearing on whether it was included or not, just its existance.
Keep the configuration for now, in case of lingering ifdefs, though it should really be removed too.
Remove the configuration of related MSG_NOSIGNAL which is more obscure and there was only this one use.
=> Include signal.h unconditionally.

mcs/class/corlib/corefx/SR.missing.cs
Includes upstream corefx changes that makes NTLM auth work for more scenarios.
Backport of https://github.com/mono/mono/pull/17530
=> [2019-10] Bump to mono/corefx@fb41040

mcs/class/corlib/corefx/SR.missing.cs
Includes upstream corefx changes that makes NTLM auth work for more scenarios.
Backport of https://github.com/mono/mono/pull/17530
=> [2019-08] Bump to mono/corefx@fb41040

mcs/class/Mono.Security/Mono.Security.Interface/CertificateValidationHelper.cs, mcs/class/Mono.Security/Mono.Security.Interface/IMonoSslStream.cs, mcs/class/Mono.Security/Mono.Security.Interface/MonoTlsProvider.cs, mcs/class/System/Mono.AppleTls/AppleCertificateHelper.cs, mcs/class/System/Mono.AppleTls/AppleTlsProvider.cs, mcs/class/System/Mono.AppleTls/AppleTlsStream.cs, mcs/class/System/Mono.Btls/MonoBtlsProvider.cs, mcs/class/System/Mono.Btls/MonoBtlsStream.cs, mcs/class/System/Mono.Btls/X509PalImpl.Btls.cs, mcs/class/System/Mono.Net.Security/ChainValidationHelper.cs, mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs, mcs/class/System/Mono.Net.Security/MobileTlsContext.cs, mcs/class/System/Mono.Net.Security/MobileTlsProvider.cs, mcs/class/System/Mono.Net.Security/MonoTlsProviderFactory.cs, mcs/class/System/Mono.Net.Security/MonoTlsStream.cs, mcs/class/System/Mono.Net.Security/NoReflectionHelper.cs, mcs/class/System/System.Net.Mail/SmtpClient.cs, mcs/class/System/System.Net.Security/SslStream.cs, mcs/class/System/System.Net/HttpWebRequest.cs, mcs/class/System/System.csproj, mcs/class/System/common_networking.sources
After the removal of the Legacy TLS Provider, we can make some cleanups and improvements to the `SslStream` class.  Since both the remaining providers use the internal `MobileAuthenticatedStream` and support Task-async code, we can get rid of some of the Begin/End async logic and the the underlying
`Stream` class handle it instead.
This also fixes a nasty issue with some of those task objects leaking unobserved exceptions.  The problem was that `SslStream.Dispose()` needs to clear out all resources, but in doing so also nulls out the `Impl` handle to the `MobileAuthenticatedStream` - so a subsequent `End*()` call will not reach it's corresponding `TaskToApm.End()` method.
There are also some cleanups in the internal APIs that were only ever used internally and not intended for public …
=> [2019-10] Cleaning up SslStream, MobileAuthenticatedStream and TaskToApm.

mcs/class/referencesource/System/compmod/system/diagnostics/TraceInternal.cs
```
Error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
```
- WASM does not have access to the command line arguments through the browser so the length is 0 causing index out of range error.
- The zero index of the command line arguments is what decides the `AppName` so under WASM the AppName will be blanks.
fixes https://github.com/mono/mono/issues/17490
=> [wasm][bcl] Fix `System.Diagnostics.Trace.TraceError` crash.

mono/metadata/coree.c, mono/metadata/external-only.c, mono/metadata/object.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/metadata/threads.h, mono/mini/driver.c
runtime should use `mono_thread_manage_internal`
=> [runtime] Make mono_thread_manage external only

mono/mini/Makefile.am.in
This is presently catastrophic, because of `MonoJitICallId` varying between C and C++, and therefore the layout of `MonoCallInst`.
Related to:
https://github.com/mono/mono/pull/17557
https://github.com/mono/mono/pull/17445#issuecomment-546175352
=> [cxx] Compile mini-llvm.c as C++ if configure -enable-cxx.

sdks/wasm/framework/src/WebAssembly.Bindings/Runtime.cs, sdks/wasm/src/corebindings.c
and returns a `WebAssembly.Core.Function`
- The code passed to `CompileFunction` is not a function definition. Instead it must create and return a function instance.
```
var hello = Runtime.CompileFunction("return () => console.log(\"hello\")");
hello.Call();  // outputs hello
```
- Solves the problem of accessing `Node.js` functionality as defining a JavaScript function executes in the global space and does not get `Node.js` access.
When run through `Node.js` has access to 'require'
```
var requireFS = Runtime.CompileFunction("return () => require('fs')");
var fs = (JSObject)requireFS.Call();
var data = fs.Invoke("readFileSync", "./publish/RunClass.txt", "utf8");
```
- Returning a function instance allows the function to initialize and maintain encapsulated state.
- When run through …
=> [wasm][binding] Add `CompileFunction` to Runtime

mcs/class/System.Windows.Forms/System.Windows.Forms/ListViewGroup.cs
ListViewGroup doesn't (always) have a serialized member "ListViewItemCount".
This patch accounts for that and also adds support for the "ItemsCount"
property that upstream [1] seems to use.
Also items should be initialized regardless of the count, otherwise we get a NPE.
[1] https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs#L144
=> Fixes #17190: SerializationException on ListViewItemCount

sdks/wasm/packager.cs
This option allows the developer to specify files and directories to embed inside [Emscripten's virtual file system](https://emscripten.org/docs/porting/files/packaging_files.html). The enables the use of System.IO functions like `File.Open` in a wasm application. Without explicitly preloading these files, all IO operations result in a FileNotFoundException since the virtual file system does not match the system's directory structure.
Disclaimer: For reasons unrelated to this PR, I was unable to successfully run the packager tool when built from source, so technically this code is untested. However, it is confirmed to compile, and when I manually added the `--preload-file=` option to the `build.ninja` file, it worked as expected. So in theory this should work, but someone who knows how to …
=> [wasm] Add --preload-file packager option

mono/metadata/appdomain.c, mono/metadata/appdomain.h, mono/metadata/coree.c, mono/metadata/domain-internals.h, mono/metadata/icall.c, mono/metadata/runtime.c, mono/mini/debugger-agent.c, mono/mini/driver.c
When embedders call `mono_runtime_quit` or `mono_jit_cleanup`, we need to do unbalanced transitions to GC Unsafe, because after `mini_cleanup` runs we don't have GC thread states anymore and `MONO_EXIT_GC_UNSAFE` will assert.
=> [runtime] Unbalanced GC Unsafe transitions before shutdown

mono/metadata/coree.c, mono/metadata/icall.c, mono/mini/exceptions-amd64.c, mono/mini/exceptions-ppc.c, mono/mini/exceptions-x86.c, mono/mini/mini-posix.c, mono/mini/mini-runtime.c, mono/utils/mono-state.c, mono/utils/mono-state.h, msvc/libmonoutils-common.targets, msvc/libmonoutils-common.targets.filters
[merp] Introduce a new 'dump mode' that allows different signal behavior when dumping
The primary reason for this is gaining the ability to interpret SIGTERM properly as a crashing signal when outside of 'dump mode', and as a utility signal during the 'thread summarizer' dumping process.
=> [merp] Introduce a new 'dump mode' that allows different signal behavior when dumping

mono/metadata/coree.c, mono/metadata/icall.c, mono/mini/exceptions-amd64.c, mono/mini/exceptions-ppc.c, mono/mini/exceptions-x86.c, mono/mini/mini-posix.c, mono/mini/mini-runtime.c, mono/utils/mono-state.c, mono/utils/mono-state.h, msvc/libmonoutils-common.targets, msvc/libmonoutils-common.targets.filters
[merp] Introduce a new 'dump mode' that allows different signal behavior when dumping
The primary reason for this is gaining the ability to interpret SIGTERM properly as a crashing signal when outside of 'dump mode', and as a utility signal during the 'thread summarizer' dumping process.
Backport of #17537.
/cc @alexischr
=> [2019-10] [merp] Introduce a new 'dump mode' that allows different signal behavior when dumping

mono/metadata/coree.c, mono/metadata/icall.c, mono/mini/exceptions-amd64.c, mono/mini/exceptions-ppc.c, mono/mini/exceptions-x86.c, mono/mini/mini-posix.c, mono/mini/mini-runtime.c, mono/utils/mono-state.c, mono/utils/mono-state.h, msvc/libmonoutils-common.targets, msvc/libmonoutils-common.targets.filters
[merp] Introduce a new 'dump mode' that allows different signal behavior when dumping
The primary reason for this is gaining the ability to interpret SIGTERM properly as a crashing signal when outside of 'dump mode', and as a utility signal during the 'thread summarizer' dumping process.
Backport of #17537.
/cc @alexischr
=> [2019-08] [merp] Introduce a new 'dump mode' that allows different signal behavior when dumping

mono/metadata/appdomain.c, mono/metadata/object-internals.h, mono/metadata/object.h, mono/mini/aot-compiler.c, mono/mini/mini-runtime.c, mono/utils/mono-forward-internal.h
- [netcore] Fix offsets generation when cross compiling
The offsets-tool.py uses some magic to map `typename` to `<underscore>typename` for looking up runtime types.
This caused issues on netcore because we aliased it to a different name.
To fix this let's keep the `_MonoInternalThread` name instead and just fix the one location where `_MonoThread` is used.
- [netcore] Don't load types in aot-compiler.c that don't exist in corefx
Fixes #16026
=> [netcore] Fix offsets generation when cross compiling and don't load non-existing types for AOT

mono/sgen/sgen-gc.c, mono/sgen/sgen-workers.c, mono/sgen/sgen-workers.h
When running parallel minor GC we currently get incorrect timing on several loggings and counters due to work being put on thread pool and accumulated. This commit fix so that the logging is accurate when running with and without parallelization. In parallel mode a new logging is also added to show the accumulated split between major and los remset scan jobs.
The counters time_minor_scan_remsets and time_minor_scan_roots are only updated when not running parallel GC since they are not correct when running parallel GC.
=> Additional and adjusted logging for parallel minor GC.

mono/metadata/icall.c
Partly revert https://github.com/mono/mono/pull/17296 backports.
Follow-up work for backports of https://github.com/mono/mono/pull/17537 backports.
=> [2019-08][merp] Install sigterm handler in EnableMicrosoftTelemetry

mono/metadata/icall.c
Partly revert https://github.com/mono/mono/pull/17296 backports.
Follow-up work for backports of https://github.com/mono/mono/pull/17537 backports.
Backport of #17581.
=> [2019-10][merp] Install sigterm handler in EnableMicrosoftTelemetry

mono/metadata/appdomain.c, mono/metadata/appdomain.h, mono/metadata/coree.c, mono/metadata/domain-internals.h, mono/metadata/external-only.c, mono/metadata/icall.c, mono/metadata/object.c, mono/metadata/runtime.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/metadata/threads.h, mono/mini/debugger-agent.c, mono/mini/driver.c
Backport of #17554 and #17566 to `2019-10`
* make `mono_thread_manage` external only
* Do unbalanced GC Unsafe transitions in `mono_jit_cleanup`
* make `mono_runtime_quit` external only
* Do unbalances GC Unsafe transitions in `mono_runtime_quit`
=> [2019-10] Embedding API GC Unsafe transition fixes

mcs/class/Mono.Options/Mono.Options/Options.cs, mcs/class/Mono.Options/Test/Mono.Options/OptionSetTest.cs
Currently Mono.Options/Options.cs will wrap command and option help descriptions so they fit within 80-character lines. However, the logic in StringCoda to find the end of the line only accounts for UNIX-style line endings - `\n`. 
StringCoda is the class responsible for creating wrapped lines. If a command or option description contains UNIX style newlines, then the line is wrapped before the `\n`, and the next line continues after the `\n`, so `Foo\nBar` remains `Foo\nBar`. However, if a command or option description contains Windows-style newlines `\r\n`, then the line is wrapped after the _`\r`_ character, which makes the console output add an extra line because `Foo\r\nBar` becomes `Foo\r\r\nBar`. 
1. Report a line end for `"\r\n"` in `StringCoda.GetLineEnd()`
1. Calculate the …
=> Support platform-independent newlines in line wrapping in Mono.Options.cs

mono/eglib/gmodule-unix.c
Should fix the warnings/assertions in g_strlcpy ().
=> [eglib] Handle dli.dli_sname being NULL in g_module_address ().

mono/metadata/icall-internals.h, mono/metadata/icall.c, mono/mini/mini-runtime.c
=> [wasm] Print a useful error message instead of a signature mismatch error on missing icalls.

mcs/class/System.Windows.Forms/System.Windows.Forms.Theming/Default/TabControlPainter.cs
The default behavior on .NET Framework is _HotkeyPrefix.None_ when creating a _TabControl_ element (ampersands not escaped). 
If an user wants to override this behavior, he has to declare a _DrawItemEventHandler_ (with _DrawMode = OwnerDrawFixed_).
=> Fix #16206: Change HotkeyPrefix default value in TabControlPainter.cs

mcs/class/referencesource/mscorlib/system/threading/threadpool.cs
On top of https://github.com/mono/corefx/pull/369 this improves the execution time of `System.Core-xunit` on Linux/ARM64 by 2x, so from:
```console
$ make -C mcs/class/System.Core run-xunit-test
[...]
=== TEST EXECUTION SUMMARY ===
net_4_x_System.Core_xunit-test  Total: 48774, Errors: 0, Failed: 0, Skipped: 6, Time: 131.143s
```
to
```console
$ make -C mcs/class/System.Core run-xunit-test
[...]
=== TEST EXECUTION SUMMARY ===
net_4_x_System.Core_xunit-test  Total: 48774, Errors: 0, Failed: 0, Skipped: 6, Time: 74.636s
```
This is only relevant for non-netcore. The CoreCLR folks just recently fixed something similar (thanks to Marek sharing this link): https://github.com/dotnet/coreclr/pull/27543
=> [threadpool] cache processor count

mono/mini/mini-llvm.c
Backport of #17648.
/cc @thaystg @vargaz
=> [2019-10] [llvm] Fix a case where we treated the dreg of a store_membase instruction as a dreg, its actually the base reg.

mono/mini/interp/transform.c
Doing this we avoid using slow ldrmfld/strmfld in the common case of loading fields from instance methods, when we execute on the real object.
=> [interp] Handle remoting field access same as jit

configure.ac, mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mcs/class/corlib/Mono/RuntimeStructs.cs, mono/metadata/icall-table.h, mono/metadata/marshal-ilgen.c, mono/metadata/object-offsets.h, mono/mini/decompose.c, netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml, tools/offsets-tool-py/offsets-tool.py
Move MonoError from managed wrappers (ilgen) to native wrappers (C preprocessor).
Alternative to https://github.com/mono/mono/pull/15869.
Which says: Previously, we would emit a call to memset
since the struct is large (> 100 bytes). Only the error code
field needs to be initialized.
Which that PR and this PR both fix, in different ways.
In the past:
- This did not work due to a possible dependency on precise GC,
interacting with what gets zeroed or not here.
That is why I put it on the managed side.
We'll see if that reproduces.
(https://github.com/mono/mono/pull/11294/files#diff-efe0070415f3f0c0f24ed0221aa1962aR339
external/coreclr/tests/src/CoreMangLib/cti/system/weakreference/weakreferenceisaliveb.exe.)
- Some indication that embedding API should expose MonoError
and not …
=> Move MonoError from managed wrappers to native wrappers.

mcs/class/corlib/System/TimeZoneInfo.MonoTouch.cs, sdks/ios/runtime/runtime.m
We enabled new clang flags in the xamarin-macios project which threw a few warnings with the following methods (we are loosing precision from unsigned long to int). 
SDK changes can be found here: https://github.com/xamarin/xamarin-macios/pull/7353
Following the comment in our sources, we are pushing the same changes to mono.
=> [iOS] Match changes done in xamarin-macios in the SDK runtime.

mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/17665
=> [jit] Call mono_class_setup_fields () before accessing field->offset. Fixes https://github.com/mono/mono/issues/17665.

mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/17665
Backport of #17667.
/cc @vargaz
=> [2019-10] [jit] Call mono_class_setup_fields () before accessing field->offset. Fixes https://github.com/mono/mono/issues/17665.

configure.ac, netcore/Makefile, netcore/System.Private.CoreLib/System.Private.CoreLib.csproj
It's using the Silverlight key: https://github.com/dotnet/coreclr/blob/34fe045a27e150bde7ee54e0d5f0df635922519d/src/System.Private.CoreLib/System.Private.CoreLib.csproj#L112
Also disable shared compilation for System.Private.CoreLib, there's a dotnet process hanging around which seems to lock the build when called from the SDKs Makefiles.
=> [netcore] Fix strong name key for System.Private.CoreLib and out of tree build

netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs
- Pre-filter the constructors on argument types
- Cache when no default constructor is found (common for struct)
Benchmark was extracted from [here](https://github.com/dotnet/performance/blob/694c6bbe4e5b57e215a8ef689193cf8db0600ffb/src/benchmarks/micro/coreclr/System.Reflection/Activator.cs#L18-L22):
Before
|                      Method |     Mean |   Error |  StdDev |
|---------------------------- |---------:|--------:|--------:|
| CreateInstanceGenericStruct | 633.0 ns | 3.83 ns | 2.99 ns |
|  CreateInstanceGenericClass | 336.2 ns | 0.95 ns | 0.84 ns |
After
|                      Method |     Mean |   Error |  StdDev |
|---------------------------- |---------:|--------:|--------:|
| CreateInstanceGenericStruct | 274.8 ns | 0.62 ns | 0.55 ns |
|  CreateInstanceGenericClass | 335.9 ns | …
=> [netcore] Improve default constructor lookup, 

configure.ac, msvc/build-init.vcxproj, msvc/mono.winconfig.targets, netcore/build.cmd, netcore/build.ps1, netcore/build.targets, netcore/run-tests-corefx.ps1, winconfig.h
Support for Windows Mono NetCore build/test without any need for cygwin/wsl/automake, just MSBuild and MSVC. Windows build uses the same technologies used by coreclr/aracade builds msbuild + powershell.
Windows only Mono NetCore build, makes a port of existing build.sh and Makefile, implementing a build.ps1 and build.targets. So far full build support + execution of corefx test suite is implemented. Other make file rules can be added when needed.
MSVC build runtime seems to hits a couple of additional test failures in corefx test suite that needs to be investigated further.
Building NetCore Mono on Windows can now be done without cygwin or wsl. Build depends on regular VS install (or build tools), if xunit summary is requested, python needs to be installed.
=> Mono NetCore Windows only build/test.

mono/mini/interp/interp.c
Discovered by Coverity:
```
>>>     CID 1455205:    (CONSTANT_EXPRESSION_RESULT)
>>>     The expression "flag && 2" is suspicious because it performs a
Boolean operation on a constant other than 0 or 1.
```
=> [interp] use mask instead of bool expression

mono/metadata/class-accessors.c, mono/metadata/class-internals.h, mono/metadata/class.c, mono/metadata/verify.c, mono/mini/intrinsics.c
Follow up to #17666, fixes https://github.com/mono/mono/issues/16615#issuecomment-527533992
Before:
|                      Method |     Mean |   Error |  StdDev |
|---------------------------- |---------:|--------:|--------:|
| CreateInstanceGenericStruct | 274.8 ns | 0.62 ns | 0.55 ns |
|  CreateInstanceGenericClass | 335.9 ns | 0.61 ns | 0.51 ns |
After:
|                      Method |       Mean |     Error |    StdDev |
|---------------------------- |-----------:|----------:|----------:|
| CreateInstanceGenericStruct |   2.505 ns | 0.0859 ns | 0.1411 ns |
|  CreateInstanceGenericClass | 317.281 ns | 6.3202 ns | 8.8601 ns |
=> Intrinsify Activator.CreateInstance<T> for value types with no ctor

mono/mini/interp/transform.c
We didn't do this because it had some issues when GetType was invoked through reflection. This issue would also be present with jit but, because jit doesn't use direct wrappers, the GetType call can't be intrinsified in that scenario. See https://github.com/mono/mono/pull/5350 for the context of the issue.
=> [interp] Use GetType instrinsic also on net4x

mono/metadata/class-internals.h, mono/metadata/icall-def-netcore.h, mono/metadata/icall.c, mono/metadata/object.c, mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c, mono/mini/intrinsics.c, netcore/System.Private.CoreLib/src/System/Array.Mono.cs, netcore/System.Private.CoreLib/src/System/Buffer.Mono.cs
Make `IsPrimitiveArray` (GetElementCorElementType) intrinsic (as it was requested here https://github.com/mono/mono/pull/16692#discussion_r321495346).
Also, these methods will be needed for other unmanaged-to-managed transitions.
Also, tried to make it managed in CoreCLR: https://github.com/dotnet/coreclr/pull/27302 🙂
=> [netcore] Intrinsify Buffer.IsPrimitiveTypeArray

mono/metadata/runtime.c
Problem was spotted with mono tracing hitting ProcessExit handler,
and crashing on first argument.
=> [mono] Fix ProcessExit handler argument.

mono/sgen/sgen-gc.c, mono/sgen/sgen-gc.h, mono/utils/atomic.c, mono/utils/atomic.h
Current implementation incorrectly accumulate time for scan jobs for the follow metrics when running parallel minor GC:
time_minor_scan_major_blocks,
time_minor_scan_los,
time_major_scan_mod_union_blocks,
time_major_scan_mod_union_los
Commit fix so updates are atomic making sure values are correct in cases where parallel minor GC is used.
=> Fix correct accumulated time for parallelized jobs in SGEN.

mono/metadata/native-library.c
See #17693 
This probably won't fix the issue, but it should propagate the correct error and prevent any name-mangling in the case of failure.
=> [loader] Skip the full pinvoke resolution process for __Internal

packaging/MacSDK/msbuild.py
Pull in dotnet/toolset versions
```
Microsoft.NET.Sdk: 3.1.100-preview3.19553.1 (from 3.1.100-preview2.19528.2)
Microsoft.NET.Sdk.Razor: 3.1.0-preview3.19553.1 (from 3.1.0-preview2.19528.1)
Microsoft.NET.Sdk.Web: 3.1.100-preview3.19554.3 (from 3.1.100-preview2.19529.1)
Microsoft.DotNet.Cli.Runtime: 3.1.100-preview3.19554.3 (from 3.1.100-preview2.19529.1)
```
=> Bump msbuild packages to 1e1d0f2caad3731357cca18b298536e514f5519b

msvc/build-external-btls.bat, msvc/build-external-llvm.bat
Reduce the scope of git submodule update --init to only LLVM and/or BTLS repositories when building external MSVC dependencies.
=> Explicit update/init only LLVM BTLS repro on external MSVC build.

netcore/build.ps1
Running Start-Process, Wait-Process on msbuild.exe have showed a couple of hangs in the build script. This is most likely due to msbuild.exe spawned child processes (like compile servers) running longer than spawned msbuild.exe process. Since there is no specific requirements when spawning the process from build.ps1, switch to regular process exec and LastExitCode.
=> Switch away from Start-Process, Wait-Process in build.ps1.

mono/mini/seq-points.c
Fixes https://github.com/mono/mono/issues/17737.
=> [runtime] Fix locking in mono_get_seq_points ().

mono/mini/seq-points.c
Fixes https://github.com/mono/mono/issues/17737.
Backport of #17738.
/cc @vargaz
=> [2019-10] [runtime] Fix locking in mono_get_seq_points ().

mono/profiler/Makefile.am, mono/profiler/log.c, mono/profiler/proftest-pinvokes.c, mono/profiler/ptestrunner.pl, mono/profiler/test-pinvokes.cs, mono/utils/mono-threads-api.h, mono/utils/mono-threads-coop.h
When we call back to managed from a pinvoke, we're in GC Safe mode and the profiler instrumentation is inserted in the wrapper before it does the transition to GC Unsafe.  So we need an extra transition before the profiler calls its locking functions.
Fixes #17687
=> [profiler] Fix log profiling of native to managed wrappers

scripts/ci/run-jenkins.sh, sdks/ios/Makefile, sdks/ios/harness/harness.cs, sdks/ios/runtime/ViewController.m, sdks/ios/runtime/runtime.h, sdks/ios/runtime/runtime.m, sdks/ios/test-runner/runner.cs
- Allows the on-device runner to work with the xunit framework in preparation for netcore.
- Added a simple UI to show the test run progress
- Report the test result XML back to the host so we can process it on Jenkins/AzDO
=> [sdks] Add xunit to iOS test runner and add results reporting

sdks/wasm/packager.cs
This PR makes emcc to work for the non-AOT scenario. I've added some comments to https://github.com/mono/mono/pull/17555 about why this is needed.
=> [Wasm] Enabled --preload-files without AOT

mono/metadata/assembly.h, mono/metadata/custom-attrs.c, mono/metadata/icall.c, mono/metadata/marshal-ilgen.c, mono/metadata/metadata-verify.c, mono/metadata/reflection-internals.h, mono/metadata/reflection.c, mono/metadata/sre.c, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/debugger-agent.c, mono/mini/mini-wasm-debugger.c
Draft because I still have ambient calls and I'm not convinced all the sites where I get the ALC from the image are correct. I'm also not sure how this should work with the marshaling code.
=> [netcore] Propagate ALCs through reflection functions

mono/profiler/Makefile.am, mono/profiler/log.c, mono/profiler/proftest-pinvokes.c, mono/profiler/ptestrunner.pl, mono/profiler/test-pinvokes.cs, mono/utils/mono-threads-api.h, mono/utils/mono-threads-coop.h
When we call back to managed from a pinvoke, we're in GC Safe mode and the profiler instrumentation is inserted in the wrapper before it does the transition to GC Unsafe.  So we need an extra transition before the profiler calls its locking functions.
Fixes #17687 
Backport of #17740.
=> [2019-10] [profiler] Fix log profiling of native to managed wrappers

mono/utils/mono-merp.c
This basically guarantees that the following waitpid invocation will fail. Fixes merp stating that its process has failed when it hasn't.
Contributes to #17726
=> [merp] Remove extraneous waitpid invocation

netcore/Makefile
This is implemented in a lazy way for convenience when manually testing until the tests are wired up to xunit. Does not write to the log.
=> [netcore] Run individual CoreCLR test suites

mono/mini/intrinsics.c, netcore/System.Private.CoreLib/src/System/Reflection/CustomAttribute.cs, netcore/System.Private.CoreLib/src/System/Reflection/Emit/TypeBuilder.Mono.cs, netcore/System.Private.CoreLib/src/System/Reflection/RuntimePropertyInfo.cs, netcore/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeFeature.Mono.cs, netcore/System.Private.CoreLib/src/System/Type.Mono.cs
It tried to use dynamic codegen which is not available in FullAOT.
We can use the `RuntimeFeature.IsDynamicCodeSupported` to check for this, added a JIT intrinsic which returns false in FullAOT.
Used a linker friendly way to check for TypeBuilder by adding an `internal virtual IsTypeBuilder` method in the `Type` class which returns false, and overwrote it in `TypeBuilder`.
=> [netcore] Fix RuntimePropertyInfo.GetValue() in FullAOT scenarios

mono/utils/mono-merp.c
This basically guarantees that the following waitpid invocation will fail. Fixes merp stating that its process has failed when it hasn't.
Contributes to #17726 
Backport of #17723.
=> [2019-10] [merp] Remove extraneous waitpid invocation

Makefile.am
Many of the tests from the llvm-project monorepo cause problems to `make dist`
=> Delete some LLVM test cases from `make dist`

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridView.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ScrollBar.cs
=>  [WinForms] Fix #12249 scroll orientation was not defined in ScrollEventArgs

man/mono.1, mono/mini/aot-compiler.c, mono/mini/llvm-jit.cpp, mono/mini/mini-llvm.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini.c, mono/mini/mini.h, mono/tests/thread-suspend-suspended.cs, scripts/ci/run-test-make-install.sh
When the LLVM backend is used for a method, explicit null checks will
unconditionally be used at the mini IR level. We had previously used
implicit null checks at the mini IR level combined with llvm-volatile
loads and stores to avoid mis-optimization of the generated code.
During AOT compilation, LLVM's `ImplicitNullChecks` pass is enabled.
This conservatively elides these explicit null checks. This pass only
modifies branches tagged with `make.implicit` metadata.
Null check branches are now tagged with `make.implicit` metadata, with
three exceptions:
1. For platforms with backends that do not support zero page fault
handling, null check branches are not tagged with `make.implicit`.
2. This commit also adds a `MONO_DEBUG` option:
`llvm-disable-implicit-null-checks`. When it is enabled, …
=> [llvm] Use explicit null checks with LLVM.

packaging/MacSDK/xamarin-gtk-theme.py
This adds some accessibility fixes from https://github.com/mono/xamarin-gtk-theme/pull/35
Backport of #17785.
/cc @sevoku
=> [2019-08] [MacSDK] Bump xamarin-gtk-theme.py to latest revision from private bockbuild

packaging/MacSDK/xamarin-gtk-theme.py
This adds some accessibility fixes from https://github.com/mono/xamarin-gtk-theme/pull/35
Backport of #17785.
/cc @sevoku
=> [2019-10] [MacSDK] Bump xamarin-gtk-theme.py to latest revision from private bockbuild

packaging/MacSDK/xamarin-gtk-theme.py
This adds some accessibility fixes from https://github.com/mono/xamarin-gtk-theme/pull/35
=> [MacSDK] Bump xamarin-gtk-theme.py to latest revision from private bockbuild

mono/utils/mono-merp.c
This basically guarantees that the following waitpid invocation will fail. Fixes merp stating that its process has failed when it hasn't.
Contributes to #17726 
Backport of #17723.
=> [2019-08] [merp] Remove extraneous waitpid invocation

sdks/wasm/Makefile, sdks/wasm/docs/packager.md, sdks/wasm/hello-io.cs, sdks/wasm/hello-io.html, sdks/wasm/packager.cs
I'm looking for forcing Emscripten to enable the filesystem even if emcc didn't detect such during compilation. This enables scenarios where users can preload files through Emscripten's file_packager.py tool, without needing to rebuild mono.wasm & co. by them-selves.
=> [Wasm] Forced filesystem creation

mono/mini/decompose.c
All other call sites for mono_type_size() are already passing non-null pointer there.
Spotted after I got a crash when running some application I'm testing.
=> [mini] Fix NULL pointer crash in mono_decompose_vtype_opts().

mcs/class/System/Mono.Net.Security/MonoTlsStream.cs
Fixes https://github.com/mono/mono/issues/15805 at least in terms of what may be making it crash.
Adds a null check around the sslStream before trying to dispose.
=> Add null check around sslStream when trying to dispose in MonoTlsStream

mono/mini/debugger-agent.c
`remove_gc_finalizing` wasn't initialized so its value is undefined.
The `count_thread_check_gc_finalizer()` function only sets it in some cases so we could end up with the variable having an undefined (and probably not 0) value.
This resulted in the returned thread count from the debuggee being wrong because we'd decrement `count` even though we shouldn't.
Fixes regression from https://github.com/mono/mono/pull/15618
Thanks to @lewurm for helping me with this!
=> [debugger-agent] Fix CMD_VM_ALL_THREADS returning wrong value due to uninitialized variable

mono/mini/debugger-agent.c
`remove_gc_finalizing` wasn't initialized so its value is undefined.
The `count_thread_check_gc_finalizer()` function only sets it in some cases so we could end up with the variable having an undefined (and probably not 0) value.
This resulted in the returned thread count from the debuggee being wrong because we'd decrement `count` even though we shouldn't.
Fixes regression from https://github.com/mono/mono/pull/15618
Thanks to @lewurm for helping me with this!
Backport of #17847.
=> [2019-10] [debugger-agent] Fix CMD_VM_ALL_THREADS returning wrong value due to uninitialized variable

mono/mini/interp/interp.c
`mono_class_array_element_size` gives us the size of the provided MonoClass if it would be an array element. But here we want the element size of a given array's MonoClass. That's what `mono_array_element_size` is returning.
This leads to all kind of weird crashes otherwise, specifically here:
https://github.com/mono/mono/blob/2c20649539ac16e069a65f2a750c793eb341e50f/netcore/System.Private.CoreLib/src/System/Array.Mono.cs#L64
Which is then used later to compute the size to memset in order to clear the content of an array. If it's larger than it should be, then this will cause memory corruption. For example this would crash eventually:
```csharp
using System;
using System.Collections.Generic;
namespace HelloWorld {
class Program {
static void Main(string[] args) {
for (int j = 0; j < …
```
=> [interp] fix array_element_size intrinsic

mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.wasm.cs
Add more descriptive `PlatformNotSupportedException` message to `HttpClientHandler.wasm.cs`.
Motive:
The handler is now being used in Blazor and what was not handled before now throws `PlatformNotSupportedException` but there is no description.  Developers using third party libraries need a way to report these errors.
=> [wasm][bcl][http] Add more descriptive message to the `PlatformNotSupportedException`

netcore/CoreFX.issues_linux.rsp, netcore/Makefile, scripts/ci/pipeline-netcore-runtime.yml
Also, with LLVM.
Only System.Runtime.Tests for now, also, interpreter crashes if we use `parallel` test execution mode (https://github.com/mono/mono/issues/17863).
=> [netcore] Run tests with Interpreter 

mono/mini/intrinsics.c
It was unintentionally shifting the address to left instead of right. It should be shift right to get rid of zeroes from the alignment.
=> Fix InternalGetHashCode for boehm/null GC

mcs/class/System/Mono.Net.Security/MonoTlsStream.cs
Fixes https://github.com/mono/mono/issues/15805 at least in terms of what may be making it crash.
Adds a null check around the sslStream before trying to dispose.
Backport of #17270.
/cc @baulig @steveisok
=> [2019-10] Add null check around sslStream when trying to dispose in MonoTlsStream

mono/metadata/Makefile.am, mono/metadata/empty.c, mono/metadata/support.c
It's used for the zlib compression helpers used by System.IO.Compression in the old Mono BCL.
On corefx this is handled differently so we don't need it there.
To avoid automake complaining about missing files we include the .c files directly instead of in the Makefile.
=> [netcore] Disable libmonoruntime-support.la build on netcore

mono/metadata/domain.c, mono/metadata/gc.c, mono/metadata/icall-def.h, mono/metadata/sgen-mono.c
This makes at least the netcore-mono build in dotnet/runtime warning-free.
=> Fix warnings in runtime build

configure.ac, mono/arch/ppc/ppc-codegen.h, mono/eglib/giconv.c, mono/metadata/sre-encode.c, mono/metadata/threads.c, mono/metadata/w32file-unix.c, mono/metadata/w32process-unix-default.c, mono/metadata/w32process-unix.c, mono/mini/exceptions-ppc.c, mono/mini/mini-ppc.c, mono/mini/mini-runtime.c, mono/mini/tramp-ppc.c, mono/utils/mono-context.c, mono/utils/mono-threads-aix.c
Many AIX/PPC/BE specific codepaths didn't do casting properly,
since C++ is much stricter than C about pointer typing.
Also specify the C99 format macros early as possible, since
inttypes may get included before eglib gets a chance to set the
macros.
Also explicitly use -pthread, since not using it is the cause of
many libstdc++ crashes on AIX.
=> Allow runtime to be built with C++ on AIX

sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs, sdks/wasm/src/binding_support.js, sdks/wasm/tests/browser/karma.conf.js, sdks/wasm/tests/browser/src/BrowserTestSuite/http-spec-with-prom-lib.html, sdks/wasm/tests/browser/src/BrowserTestSuite/http-spec-with-prom-lib.js, sdks/wasm/tests/browser/src/Packages.props
**WasmHttpMessageHandler:**
Add a more descriptive error in case of fetch response not returning back what it should.  In this case a managed Task.
**binding_support.js**
Add a more reliable way of identifying a Promise to be marshaled.  This is left as generic as possible so we do not have to check for specific library implementations.
**Tests**
Add specific promise library tests that test specifically for Bluebird promise library functionality as reported in issue.
fix https://github.com/mono/mono/issues/17895
close https://github.com/mono/mono/issues/17874
=> [wasm][bindings] Marshal Promise correctly when using Promise Library

sdks/wasm/src/binding_support.js, sdks/wasm/tests/browser/src/BindingsTestSuite/BindingsTestSuite.cs, sdks/wasm/tests/browser/src/BrowserTestSuite/core-bindings-spec.js, sdks/wasm/tests/browser/src/BrowserTestSuite/issues-spec.js
Method calls should throw an error if args list count does not match signature.
- Add parameter and signature validation to bindings.
- throws `Parameter count mismatch.` if the signature and argument counts are not consistent. 
- Add tests for `Parameter count mismatch.`
fixes https://github.com/mono/mono/issues/17843
=> [wasm] [bindings] Method invoke signature argument validation.

mcs/class/corlib/Test/System/BufferTest.cs
Test ignored byte order when considering integer comparison. This
tests different cases for each endian, and explains why the byte
order is different.
=> Fix flawed BufferTest on big-endian

mono/mini/debugger-agent.c, mono/utils/networking-posix.c, mono/utils/networking.h
Mono SDB's debugger agent takes a `host:port` parameter to specify the host and
port to connect to for the debugger connection. `host` is passed, via
`mono_get_address_info`, to the `getaddrinfo(3)` standard library call which
does the job of translating the name to the IP address. However, there's no
special treatment for situations when `host` is already an IP address. In this
case `getaddrinfo` takes a lot of time to perform at least two DNS lookups (if
there's just a single DNS server configured) which will time out as the IP
address in `host` will not be resolved by any of the servers.
`getaddrinfo` takes a "hints" parameter where caller can specify some
information about the `host:port` pair to make the lookup faster/easier.
However, Mono doesn't specify the address family in the …
=> Make debugger agent startup faster

msvc/run-msbuild.bat
After https://github.com/mono/mono/pull/16832 was merged the run-msbuild.bat script has an additional required parameter for specifying the GC.
However the script only passed the MONO_TARGET_GC property to msbuild if the script had no additional parameters which doesn't make sense.
Always pass the parameter, this should fix the boehm build on Windows i386.
=> Fix boehm on Windows i386 builds

mcs/class/corlib/Test/System.IO/BinaryWriterTest.cs, mcs/class/referencesource/mscorlib/system/io/binaryreader.cs
The ints passed into the int array ctor needed to be endian swapped.
Interestingly, the BinaryWriter implementation currently being used
(not refsrc AFAIK) does this on write just fine.
Fixes ReadDecimal test on AIX, and adds another test to ensure that
Write(decimal) can be read back by ReadDecimal in case.
=> Fix BinaryReader on BE

configure.ac
=> [configure.ac] Don't run compiler server check in netcore mode

mono/btls/Makefile.am, msvc/Makefile.am
These can be easily replaced so we don't need to mirror over the mkinstalldirs file to the new repo
=> Remove mkinstalldirs invocation from two places

mono/mini/debugger-agent.c, mono/utils/networking-posix.c, mono/utils/networking.h
Mono SDB's debugger agent takes a `host:port` parameter to specify the host and
port to connect to for the debugger connection. `host` is passed, via
`mono_get_address_info`, to the `getaddrinfo(3)` standard library call which
does the job of translating the name to the IP address. However, there's no
special treatment for situations when `host` is already an IP address. In this
case `getaddrinfo` takes a lot of time to perform at least two DNS lookups (if
there's just a single DNS server configured) which will time out as the IP
address in `host` will not be resolved by any of the servers.
`getaddrinfo` takes a "hints" parameter where caller can specify some
information about the `host:port` pair to make the lookup faster/easier.
However, Mono doesn't specify the address family in the …
=> [2019-10] Make debugger agent startup faster

configure.ac, mono/metadata/marshal.c, mono/mini/gshared.cs, mono/mini/mini-amd64-gsharedvt.c, mono/mini/mini-runtime.c
Backport of #17832.
/cc @vargaz
=> [2019-10] [runtime] Treat calling a non-virtual method through an open delegate the same as the normal case instead of the OPEN_VIRTUAL case.

mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/exceptions-amd64.c
This test is failing in the interpreter (ONLY on Debian9/amd64. Not Ubuntu/amd64. Not macOS/amd64):
https://github.com/mono/mono/blob/0fed03ed63ed4ea742c4511d8edc3bc1c6f4044f/mcs/class/Mono.Debugger.Soft/Test/dtest.cs#L2484-L2499
Where the debuggee is just some unsafe code that tries to read from unmapped memory, thus causing a segfault.
So the test expects the runtime to send a CRASH event via the managed debugger interface. This happens very late in the crash handling machinery:
https://github.com/mono/mono/blob/0fed03ed63ed4ea742c4511d8edc3bc1c6f4044f/mono/mini/mini-posix.c#L1105
However, the runtime would never reach that, because it silently crashes when calling `backtrace`:
https://github.com/mono/mono/blob/0fed03ed63ed4ea742c4511d8edc3bc1c6f4044f/mono/mini/mini-posix.c#L939
At the …
=> [amd64] do not stack allocate on the application stack for the transtion from alstack handling

mono/mini/aot-compiler.c
E.g. when passing `-march=arm -mtriple=armv7s-ios`, `-march` will win and thus ignore `armv7s`.
Fixes https://github.com/mono/mono/issues/17931
* Caused by 5e318afd2e1d5f9ef0fd692abbceadcf615389a5
* Related with 4cd506823079bc15c9ee72da4f94a653f237a5e5
* Almost fixed by e431093f73360b5726e5256fd0de3108ec21b38a
Hopefully we are done with it.
=> [arm] if mtriple is provided, do not set -march

mcs/class/System.Windows.Forms/System.Windows.Forms/ScrollableControl.cs
=> [WinForms] Fix Recalculate in ScrollableControl

mono/mini/aot-compiler.c
E.g. when passing `-march=arm -mtriple=armv7s-ios`, `-march` will win and thus ignore `armv7s`.
Fixes https://github.com/mono/mono/issues/17931
* Caused by 5e318afd2e1d5f9ef0fd692abbceadcf615389a5
* Related with 4cd506823079bc15c9ee72da4f94a653f237a5e5
* Almost fixed by e431093f73360b5726e5256fd0de3108ec21b38a
Hopefully we are done with it.
Backport of #17937.
/cc @lewurm
=> [2019-10] [arm] if mtriple is provided, do not set -march

mono/metadata/threadpool-worker-default.c
The corresponding code in CoreCLR:
https://github.com/dotnet/runtime/blob/bf88f146412d1e2d41779422337184a802f186c9/src/coreclr/src/vm/win32threadpool.cpp#L2156-L2164
The issue is that counter._.max_working is only ever changed by:
1. the monitor_thread when it detects starvation (increment by 1).
2. the hill climbing algorithm (increment or decrement).
Creating a periodic load of creating many workers at once followed by a minute
or more of quiescence increases the variable worker.counters._.max_working in
monitor_thread(). Once that counter matches worker.limit_worker_max,
monitor_thread() keeps looping without unparking or creating a thread, even
though the actual number of threads/workers is small. If the existing threads
are all waiting on work that needs a new thread, then a deadlock …
=> [2019-10] [threadpool] Decrement max_working when worker times out

mono/metadata/threadpool-worker-default.c
The corresponding code in CoreCLR:
https://github.com/dotnet/runtime/blob/bf88f146412d1e2d41779422337184a802f186c9/src/coreclr/src/vm/win32threadpool.cpp#L2156-L2164
The issue is that counter._.max_working is only ever changed by:
1. the monitor_thread when it detects starvation (increment by 1).
2. the hill climbing algorithm (increment or decrement).
Creating a periodic load of creating many workers at once followed by a minute
or more of quiescence increases the variable worker.counters._.max_working in
monitor_thread(). Once that counter matches worker.limit_worker_max,
monitor_thread() keeps looping without unparking or creating a thread, even
though the actual number of threads/workers is small. If the existing threads
are all waiting on work that needs a new thread, then a deadlock …
=> [threadpool] Decrement max_working when worker times out

mcs/class/Mono.Security/Mono.Security/ASN1.cs
If `byte[] data` has additional data at the end `Decode` will try to parse it and will generate incorrect tags or throw an exception. This fix makes `Decode` to use only `nLength` bytes from `byte[] data`.
=> [Mono.Security] Do not decode data beyond detected length in ASN1 parser

mono/metadata/jit-icall-reg.h, mono/mini/aot-runtime.c, mono/mini/mini-runtime.h
Between mini-codegen.c and mini-llvm.c, one of them might not be getting
the -enable-cxx flag, which could be another problem, but
this is still probably better for now.
Alternative to https://github.com/mono/mono/pull/17445.
I'll dig a bit more, but this is ok and makes some sense.
=> [cxx] MonoJitICallId same between C and C++.

mono/eglib/eglib-remap.h, mono/eglib/glib.h, mono/eglib/gstr.c, mono/metadata/loader-internals.h, mono/metadata/metadata-internals.h, mono/metadata/native-library.c, mono/mini/main.c, mono/utils/mono-dl.h
A bunch of this was added to `main.c` with #3571 and doesn't really belong. This moves it into the runtime proper, with the rest of the bundling/loader code, and stops exporting the symbols this used.
Fixes #17728
=> [mini] Move bundled native library loading into the runtime

netcore/Makefile, netcore/tools/jitdiff/jitdiff.cs, netcore/tools/jitdiff/jitdiff.csproj
A tool to detect size improvements/regressions for JIT changes. It compiles the whole BCL (including mscorlib) using LLVM AOT and dumps asm with `objdump -d` to a specific folder. Then a special tool `jitdiff` can compare two folders for diffs.
A typical workflow may look like this:
```
make dump-asm-bcl DUMPASM_OUT=dumps/before-my-jit-fix
```
Now make a change (e.g. add an optimization to the jit). I decided to change this [-O2](https://github.com/mono/mono/blob/master/mono/mini/aot-compiler.c#L9811) to -Os to test.
```
make runtime -j12
make dump-asm-bcl DUMPASM_OUT=dumps/after-my-jit-fix
make jitdiff BEFORE=dumps/before-my-jit-fix AFTER=dumps/after-my-jit-fix
```
The last command will output a detailed report (per library and per method), e.g. for my case:
```
Total diff for …
```
=> [netcore] JIT diff tools

sdks/wasm/src/driver.c, sdks/wasm/tests/browser/src/BindingsTestSuite/BindingsTestSuite.cs, sdks/wasm/tests/browser/src/BrowserTestSuite/core-bindings-spec.js
- Add regression tests for string null, string.IsNullOrEmpty and null string array.
fix https://github.com/mono/mono/issues/17947
=> [wasm][binding] Marshal null string correctly.

mono/mini/decompose.c, mono/mini/mini-llvm-cpp.cpp, mono/mini/mini-llvm-cpp.h, mono/mini/mini-llvm.c, mono/mini/mini.h
Let's see what CI thinks and will generate a jit-diff later. But basically it should help LLVM a bit, e.g.
```csharp
public static bool Test(int[] array)
{
return array.Length >= 0; // always true, Length is always positive.
}
```
LLVM IR diff: https://www.diffchecker.com/aPIBx94I (before and after the change)
Another example:
```csharp
public static int Test(int[] array)
{
// some peephole optimizations work only for unsigned types
// and the `range` basically tells LLVM that Array.Length, Span.Length, String.Length are unsigned
return array.Length / 10;
}
```
LLVM IR diff (see asm): https://www.diffchecker.com/wCILljua
Closes https://github.com/mono/mono/issues/16948
=> [llvm] use `range` metadata

mono/mini/decompose.c, mono/mini/mini-llvm-cpp.cpp, mono/mini/mini-llvm-cpp.h, mono/mini/mini-llvm.c, mono/mini/mini.h
=> Revert "[llvm] use `range` metadata"

sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs
There is a race condition on Safari as a result of using TaskCompletionSource that causes a stack exceeded error being thrown during Blazor startup.
Safari throws the following error:
```
[Error] Unhandled Promise Rejection: RangeError: Maximum call stack size exceeded.
step (blazor.webassembly.js:2530)
fulfilled (blazor.webassembly.js:2500)
promiseReactionJob
```
- Modify `WebAssemblyHttpMessageHandler.cs` to create the TaskCompletionSource to run continuations asynchronously.
- `TaskCompletionSource<HttpResponseMessage>(TaskCreationOptions.RunContinuationsAsynchronously);`
The following link discusses the potential stack/race problem that can occur when using TaskCompletionSource:  https://devblogs.microsoft.com/premier-developer/the-danger-of-taskcompletionsourcet-class/
=> [wasm][http] Fix race condition as a result of using TaskCompletionSource: RangeError: Maximum call stack size on Safari

netcore/Makefile, netcore/tools/jitdiff/jitdiff.cs
use `objdump` arguments to reduce verbosity (no raw bytes, etc) and make the dasm more diff-friendly.
On Linux all functions have a random prefix (address) - replace it with `0xD1FFAB1E` constant). On macOS it's fine by default.
Also, allow to generate diffs for a single assembly via `dump-asm-lib` rule.
=> [netcore] Improve Jitdiff tool

packaging/MacSDK/msbuild.py, packaging/MacSDK/nuget.py
Also, bump nuget.exe to 5.3.1 . We need to bump to 5.4.0, but that isn't available yet.
=> [2019-10] Bump msbuild to track mono-2019-10

mono/mini/iltests.il, mono/mini/interp/transform.c
Usually the stack depth is determined via basic block predecessors, but  that only works for forward branches.
Fixes https://github.com/mono/mono/issues/17924
=> [interp] track valuetype stack for CEE_RET too

mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.wasm.cs
As pointed out by https://github.com/mono/mono/commit/202cb6a6483019185db7e1f75929d7db0d319173#r36087022
Introduced in https://github.com/mono/mono/pull/17864
Should there also be a more descriptive message for [`Properties`](https://github.com/mono/mono/commit/202cb6a6483019185db7e1f75929d7db0d319173#diff-5bf439c4c9f249ccbf47381e492ef72bR135)?
=> [wasm][bcl][http] Fix descriptive message for the `PlatformNotSupportedException`

mcs/class/System/Test/System.Net.Sockets/SocketTest.cs
Hangs runtime; prevents CI from completing run. (Another test can
also hang the runtime, but is hard to reproduce and inconsistent
about that.)
This should be fixed eventually, but...
=> Disable ConnectFailAsync test on AIX

mono/mini/iltests.il, mono/mini/interp/transform.c
Backport of #17968
Fixes https://github.com/mono/mono/issues/17924
=> [2019-10] [interp] track valuetype stack for CEE_RET too

mono/metadata/class-init.c, mono/tests/Makefile.am, mono/tests/dim-generic.cs
Fix behavior when there is an override of a method in a generic interface.
Fixes #17869
=> [DIM] Fix behavior when there is an override of a method in a generic interface. 

configure.ac, mono/metadata/marshal.c, mono/mini/gshared.cs, mono/mini/mini-amd64-gsharedvt.c, mono/mini/mini-runtime.c
Backport of #17832.
/cc @vargaz
=> [2019-08] [runtime] Treat calling a non-virtual method through an open delegate the same as the normal case instead of the OPEN_VIRTUAL case.

mono/mini/aot-compiler.c
E.g. when passing `-march=arm -mtriple=armv7s-ios`, `-march` will win and thus ignore `armv7s`.
Fixes https://github.com/mono/mono/issues/17931
* Caused by 5e318afd2e1d5f9ef0fd692abbceadcf615389a5
* Related with 4cd506823079bc15c9ee72da4f94a653f237a5e5
* Almost fixed by e431093f73360b5726e5256fd0de3108ec21b38a
Hopefully we are done with it.
Backport of #17937.
/cc @lewurm
=> [2019-08] [arm] if mtriple is provided, do not set -march

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridViewLinkCell.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridViewLinkColumn.cs
=>  [WinForms] the Text property was not set for every cell in the column when UseColumnTextForLinkValue is true

mono/sgen/sgen-alloc.c
Allocation of thread objects uses the mono_object_new_mature API. These objects are allocated before the thread is finished attaching to the runtime. This means that a collection can happen on an unattached thread as well as all its callbacks, which is a counter-intuitive behavior.
On android this is problematic because at the end of the SGen collection we need to call the java collection, which needs to have the thread attached. This could probably be fixed instead from the Xamarin.Android side, but this approach seems simpler and saner.
Fixes https://github.com/mono/mono/issues/17878
=> [sgen] Don't trigger collections during allocation of thread objects

mono/metadata/profiler-private.h, mono/metadata/profiler.c, mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/17774
=> [profiler] disable inlining when coverage profiler is used and fix allocation sizes

mcs/class/corlib/System.Security.Principal/SecurityIdentifier.cs, mcs/class/corlib/Test/System.Security.AccessControl/RawSecurityDescriptorTest.cs
Fix security identifier parsing error with the following SDDL:
```
O:S-1-5-21-1356517589-3987021482-2501375073-1001G:S-1-5-21-1356517589-3987021482-2501375073-513D:(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-21-1356517589-3987021482-2501375073-1001)
```
=> Fix raw security descriptor parsing

mono/sgen/sgen-alloc.c
Allocation of thread objects uses the mono_object_new_mature API. These objects are allocated before the thread is finished attaching to the runtime. This means that a collection can happen on an unattached thread as well as all its callbacks, which is a counter-intuitive behavior.
On android this is problematic because at the end of the SGen collection we need to call the java collection, which needs to have the thread attached. This could probably be fixed instead from the Xamarin.Android side, but this approach seems simpler and saner.
Fixes https://github.com/mono/mono/issues/17878
Backport of #17970.
/cc @lambdageek @BrzVlad
=> [2019-10] [sgen] Don't trigger collections during allocation of thread objects

mono/sgen/sgen-alloc.c
Allocation of thread objects uses the mono_object_new_mature API. These objects are allocated before the thread is finished attaching to the runtime. This means that a collection can happen on an unattached thread as well as all its callbacks, which is a counter-intuitive behavior.
On android this is problematic because at the end of the SGen collection we need to call the java collection, which needs to have the thread attached. This could probably be fixed instead from the Xamarin.Android side, but this approach seems simpler and saner.
Fixes https://github.com/mono/mono/issues/17878
Backport of #17970.
/cc @lambdageek @BrzVlad
=> [2019-12] [sgen] Don't trigger collections during allocation of thread objects

mcs/class/corlib/System/AppDomain.cs
The intent is to be helpful for when .NET 5 comes along.
=> Added Obsolete to AppDomain.CreateDomain for monodroid. 

mono/mini/iltests.il, mono/mini/interp/transform.c
Backport of #17968
Fixes https://github.com/mono/mono/issues/17924
=> [2019-08] [interp] track valuetype stack for CEE_RET too

mono/metadata/profiler-private.h, mono/metadata/profiler.c, mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/17774
Backport of #17986.
=> [2019-12] [profiler] disable inlining when coverage profiler is used and fix allocation sizes

mono/metadata/profiler-private.h, mono/metadata/profiler.c, mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/17774
Backport of #17986.
=> [2019-10] [profiler] disable inlining when coverage profiler is used and fix allocation sizes

packaging/MacSDK/msbuild.py
.. to get changes from https://github.com/mono/msbuild/pull/159 .
=> Bump msbuild to track mono-2019-10

sdks/builds/wasm.mk
Fixes for i64 returning functions with dynamic runtime configuration.
See https://github.com/emscripten-core/emscripten/issues/9850
=> [Wasm] Update to emscripten 1.39.4

configure.ac, mono/metadata/mono-config.c, sdks/builds/android.mk
In Xamarin.Android, on startup we see logging like this for every .NET
assembly:
12-03 14:27:42.104 26842 26842 D Mono    : Prepared to set up assembly 'FormsViewGroup' (/storage/emulated/0/Android/data/Xamarin.Forms_Performance_Integration/files/.__override__/FormsViewGroup.dll)
12-03 14:27:42.104 26842 26842 D Mono    : Assembly FormsViewGroup[0xebcee9c0] added to domain RootDomain, ref_count=1
12-03 14:27:42.104 26842 26842 D Mono    : Assembly Loader loaded assembly from location: '/storage/emulated/0/Android/data/Xamarin.Forms_Performance_Integration/files/.__override__/FormsViewGroup.dll'.
12-03 14:27:42.104 26842 26842 D Mono    : Config attempting to parse: '/storage/emulated/0/Android/data/Xamarin.Forms_Performance_Integration/files/.__override__/FormsViewGroup.dll.config'.
12-03 …
=> [android] don't probe directories for .config files

mono/metadata/class-init.c, mono/tests/Makefile.am, mono/tests/dim-generic.cs
Fix behavior when there is an override of a method in a generic interface.
Fixes #17869
Backport of #17963.
/cc @akoeplinger @thaystg
=> [2019-12] [DIM] Fix behavior when there is an override of a method in a generic interface. 

mono/metadata/class-init.c, mono/tests/Makefile.am, mono/tests/dim-generic.cs
Fix behavior when there is an override of a method in a generic interface.
Fixes #17869
Backport of #17963.
=> [2019-10] [DIM] Fix behavior when there is an override of a method in a generic interface. 

autogen.sh
Otherwise we'll run into issues because in configure.ac we update submodules _after_ we try to call external/bdwgc/configure (which won't be there if autogen.sh didn't run).
This would manifest itself as `*** No rule to make target 'all'.` in external/bdwgc when you build as there's no Makefile.
=> Update submodules before running external/bdwgc/autogen.sh

mono/eglib/glib.h, mono/mini/exceptions-amd64.c
16byte stack pointer alignment is only required in certain places by the ABI, so the assumption that it holds all the time is wrong (though, it passed CI 😅). We have to setup the frame properly, i.e. we have to ensure the stack pointer is properly aligned. That's what we have done previously too.
Regression of https://github.com/mono/mono/pull/17922
Fixes https://github.com/mono/mono/issues/18006
=> [amd64] align application stack pointer in signal handler

configure.ac, packaging/MacSDK/msbuild.py
.. to get changes from https://github.com/mono/msbuild/pull/163 .
And bump roslyn to 3.4.0-beta4-19569-03 to match msbuild.
=> [2019-12] Bump msbuild to track mono-2019-10

mono/mini/mini-llvm.c
`OP_XEQUAL` instead of `1` (true) used to return 255 (which is technically also `true` but not exactly => we had a lot of `Actual: True, Expected: True` failures in corefx tests).
Fixes https://github.com/mono/mono/issues/18037
=> Fix OP_XEQUAL return value (normalize to 0/1 boolean)

mono/metadata/icall-decl.h
There was no clash so ok either way but this is more like intended.
=> Fix ifndef include guard in icall-decl.h.

mcs/class/Mono.Messaging.RabbitMQ/Mono.Messaging.RabbitMQ/RabbitMQMessagingProvider.cs, mcs/class/System.Runtime.Remoting/Test/ActivationTests.cs, mcs/class/System.Runtime.Remoting/Test/GenericTest.cs, mcs/class/System.Runtime.Remoting/Test/HttpBugTests.cs, mcs/class/System.Runtime.Remoting/Test/RemotingServicesTest.cs, mcs/class/System.Runtime.Remoting/Test/TcpCalls.cs, sdks/ios/harness/harness.cs
This allows us to workaround issues we currently have in the macOS bot network where DNS lookup of the hostname fails. We instead bind to 127.0.0.1.
All changes are in test code except for Mono.Messaging.RabbitMQ which used the local IP to generate a transaction ID. This doesn't seem necessary so replaced it with a GUID.
=> Remove DNS lookups of the local hostname in tests

mono/mini/mini-llvm.c, netcore/CoreFX.issues_linux.rsp
Use actual `-x` instead of `0-x` for NEG
Fixes https://github.com/mono/mono/issues/18052
=> LLVM: use fneg instead of fsub for `-x`

mono/metadata/icall-decl.h, mono/metadata/icall-def.h, mono/metadata/w32socket.c
Ongoing removal of handles() icalls.
This is small, to pause and remove `mono_class_get_field_from_name_full` from w32socket.c.
=> Remove handles/MonoError from two socket icalls.

mono/mini/aot-compiler.c
Currently we always use `opt -O2` even if user overwrites `llvmopts`, e.g.
```
--aot=llvm,llvmopts="-Os"
```
will end up as `opt -O2 ... -Os` and it turns out `opt` will use both! (we expected it to pick the last -Ox)
E.g.:  https://godbolt.org/z/X8w-_T  (`opt -O2 -O0` != `opt -O0`)
It works as expected for clang CLI.
=> Don't pass -O2 to opt if llvmopts is overriden

mono/metadata/icall.c
https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/19408/parsed_console/log_content.html
```
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/metadata/icall.c:882:1: error: jump to label 'exit' [-fpermissive]
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/metadata/icall.c:882:1: error: jump to label 'exit' [-fpermissive]
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/metadata/icall.c:882:1: error: jump to label 'exit' [-fpermissive]
```
=> [cxx][netcore] Fix goto around init.

mono/utils/mono-md5.c
https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/19408/parsed_console/log_content.html
```
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/utils/mono-md5.c:259:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
register guint32 a, b, c, d;
^~~~~~~~~
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/utils/mono-md5.c:259:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
register guint32 a, b, c, d;
^~~~~~~~~
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/utils/mono-md5.c:259:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
register guint32 a, b, c, d;
^~~~~~~~~ …
```
=> [cxx] Remove use of register keyword.

mono/mini/exceptions-ppc.c
Also update assert which doesn't make sense since we have moved over to MonoContext
Some context: e7011c780f676914f559f14f25e76c192bb2b0b2
Fixes: https://github.com/mono/mono/issues/18064
=> [ppc32] delete leftover code from pre-monoctx area

mono/mini/decompose.c
Backport of #18041.
/cc @vargaz
=> [2019-12] [llvm] Avoid decomposing OP_STOREV_MEMBASE early for types which contains no references.

mono/metadata/appdomain.c, mono/metadata/assembly-load-context.c, mono/metadata/boehm-gc.c, mono/metadata/class-init.c, mono/metadata/class-internals.h
accessed from multiple threads without locks.
This is based on earlier PR https://github.com/mono/mono/pull/17849..
Read-side barriers are removed.
More analysis is needed to determine if they are needed (which pointer
read vs. written).
Write-side barriers are store-release or store-store barrier instead of full barrier (which separately will get compiler barriers).
Note all candidates are converted to new form yet (go slowly).
=> Add some missing barriers when dealing with global caches

mono/metadata/threadpool-worker-default.c
https://jenkins.mono-project.com/job/build-source-tarball-mono-pullrequest/854/console
=> fix warning: threadpool-worker-default.c: function 'worker_try_create': 'now' may be used uninitialized

sdks/wasm/xunit-exclusions.rsp
Relates to https://github.com/mono/mono/issues/16858
- we have the whole `System.IO.Pipes.Tests` namespace excluded so there is no need to exclude particular classes;
- `CoreXml.Test.XLinq.FunctionalTests.EventsTests.EventsReplaceNodes.XElementReplaceNodes` passes locally
/cc @steveisok
=> [wasm] Clean up rsp-file

mono/metadata/boehm-gc.c
https://jenkins.mono-project.com/job/test-mono-pull-request-i386/32263/consoleText
```
boehm-gc.c: In function 'void mono_gc_base_init()':
boehm-gc.c:202:42: error: invalid conversion from
'void (*)(size_t) {aka void (*)(unsigned int)}' to
GC_on_heap_resize_proc {aka void (*)(long unsigned int)}' [-fpermissive]
GC_set_on_heap_resize (on_gc_heap_resize);
^
In file included from ../../mono/utils/gc_wrapper.h:44:0,
from ../../mono/metadata/gc-internals.h:16,
from boehm-gc.c:16:
../../external/bdwgc/include/gc.h:132:21: note:
initializing argument 1 of 'void GC_set_on_heap_resize(GC_on_heap_resize_proc)'
GC_API void GC_CALL GC_set_on_heap_resize(GC_on_heap_resize_proc);
```
=> [cxx] Fix mono-boehm to compile as C++.

mono/mini/mini-trampolines.c, mono/tests/Makefile.am, mono/tests/delegate17.cs, mono/tests/delegate18.cs
If we need to jit the Invoke method of a delegate, we get `tramp_info` with a
NULL method.
Background: normally when we create a delegate around a virtual method,
`handle_delegate_ctor` will just create a virtual invoke trampoline with
`mono_arch_get_delegate_virtual_invoke_impl` which doesn't get here.  But if
we're asked to compile the delegate's `Invoke` method, then `compile_special ()`
will create a `tramp_info` with a null method, and return a delegate trampoline.
That's the case here - we had
```
var del = SomeDelegate(obj.VirtualMethod);
var invoke_method = del.GetType().GetMethod ("Invoke");
invoke_method.Invoke (del, args);
```
or
```
var del = SomeDelegate(obj.VirtualMethod);
var another_del = OtherDelegate (del.Invoke);
another_del (args);
```
in both cases, we end up in …
=> [mini] Fix delegate trampoline virtual call via delgate Invoke

mono/mini/debugger-agent.c
When the debugger tries to suspend all the VM threads, it can happen with cooperative-suspend that it tries to suspend a thread that has previously been attached, but then did a "light" detach (that only unsets the domain). With the domain set to `NULL`, looking up a JitInfo for a given `ip` will result into a crash, but it isn't even necessarily needed for the purpose of suspending a thread.
More details: Consider the following:
```
(lldb) c
error: Process is running.  Use 'process interrupt' to pause execution.
Process 12832 stopped
* thread #9, name = 'tid_a31f', queue = 'NSOperationQueue 0x8069b670 (QOS: UTILITY)', stop reason = breakpoint 1.1
frame #0: 0x00222870 WatchWCSessionAppWatchOSExtension`debugger_interrupt_critical(info=0x81365400, user_data=0xb04dc718) at …
```
=> [debugger] skip suspend for unattached threads

configure.ac, mcs/packages/Makefile, packaging/MacSDK/msbuild.py
- bumps roslyn to `3.5.0-beta1-19606-04`
=> Bump msbuild+roslyn to track mono-2019-10

configure.ac, mcs/packages/Makefile, packaging/MacSDK/msbuild.py
- bumps roslyn to `3.5.0-beta1-19606-04`
=> [2019-10] Bump msbuild+roslyn to track mono-2019-10

mono/mini/mini-trampolines.c, mono/tests/Makefile.am, mono/tests/delegate17.cs, mono/tests/delegate18.cs
If we need to jit the Invoke method of a delegate, we get `tramp_info` with a
NULL method.
Background: normally when we create a delegate around a virtual method,
`handle_delegate_ctor` will just create a virtual invoke trampoline with
`mono_arch_get_delegate_virtual_invoke_impl` which doesn't get here.  But if
we're asked to compile the delegate's `Invoke` method, then `compile_special ()`
will create a `tramp_info` with a null method, and return a delegate trampoline.
That's the case here - we had
```
var del = SomeDelegate(obj.VirtualMethod);
var invoke_method = del.GetType().GetMethod ("Invoke");
invoke_method.Invoke (del, args);
```
or
```
var del = SomeDelegate(obj.VirtualMethod);
var another_del = OtherDelegate (del.Invoke);
another_del (args);
```
in both cases, we end up in …
=> [2019-12] [mini] Fix delegate trampoline virtual call via delgate Invoke

sdks/wasm/xunit-exclusions.rsp
`System.Numerics.Tests.BigIntegerConstructorTest.RunCtorByteArrayTests` passes locally. Let's see CI verdict.
/cc @steveisok
=> [wasm] Re-enable System.Numerics.Tests.BigIntegerConstructorTest.RunCtorByteArrayTests test

mono/mini/debugger-agent.c
When the debugger tries to suspend all the VM threads, it can happen with cooperative-suspend that it tries to suspend a thread that has previously been attached, but then did a "light" detach (that only unsets the domain). With the domain set to `NULL`, looking up a JitInfo for a given `ip` will result into a crash, but it isn't even necessarily needed for the purpose of suspending a thread.
More details: Consider the following:
```
(lldb) c
error: Process is running.  Use 'process interrupt' to pause execution.
Process 12832 stopped
* thread #9, name = 'tid_a31f', queue = 'NSOperationQueue 0x8069b670 (QOS: UTILITY)', stop reason = breakpoint 1.1
frame #0: 0x00222870 WatchWCSessionAppWatchOSExtension`debugger_interrupt_critical(info=0x81365400, user_data=0xb04dc718) at …
```
=> [2019-12] [debugger] skip suspend for unattached threads

mono/mini/debugger-agent.c
When the debugger tries to suspend all the VM threads, it can happen with cooperative-suspend that it tries to suspend a thread that has previously been attached, but then did a "light" detach (that only unsets the domain). With the domain set to `NULL`, looking up a JitInfo for a given `ip` will result into a crash, but it isn't even necessarily needed for the purpose of suspending a thread.
More details: Consider the following:
```
(lldb) c
error: Process is running.  Use 'process interrupt' to pause execution.
Process 12832 stopped
* thread #9, name = 'tid_a31f', queue = 'NSOperationQueue 0x8069b670 (QOS: UTILITY)', stop reason = breakpoint 1.1
frame #0: 0x00222870 WatchWCSessionAppWatchOSExtension`debugger_interrupt_critical(info=0x81365400, user_data=0xb04dc718) at …
```
=> [2019-10] [debugger] skip suspend for unattached threads

mono/mini/interp/transform.c
This can lead to problems on big endian.
```
result.i = (int) 1;
--> 0x0000_0001_XXXX_XXXX;
result.l = (long) 1;
--> 0x0000_0000_0000_0001;
```
On little endian it's always `0x0000_0000_0000_0001`, so it doesn't matter.
=> [interp] relop result is always int

mono/mini/mini-trampolines.c, mono/tests/Makefile.am, mono/tests/delegate17.cs, mono/tests/delegate18.cs
If we need to jit the Invoke method of a delegate, we get `tramp_info` with a
NULL method.
Background: normally when we create a delegate around a virtual method,
`handle_delegate_ctor` will just create a virtual invoke trampoline with
`mono_arch_get_delegate_virtual_invoke_impl` which doesn't get here.  But if
we're asked to compile the delegate's `Invoke` method, then `compile_special ()`
will create a `tramp_info` with a null method, and return a delegate trampoline.
That's the case here - we had
```
var del = SomeDelegate(obj.VirtualMethod);
var invoke_method = del.GetType().GetMethod ("Invoke");
invoke_method.Invoke (del, args);
```
or
```
var del = SomeDelegate(obj.VirtualMethod);
var another_del = OtherDelegate (del.Invoke);
another_del (args);
```
in both cases, we end up in …
=> [2019-10] [mini] Fix delegate trampoline virtual call via delgate Invoke

sdks/wasm/Mono.WebAssembly.DebuggerProxy/WsProxy.cs
This prevents the debugger proxy from crashing when the client disconnects.
This allows the client to stop the debug session and reconnect at a later time.
=> [wasm][debugger] Prevent crash on disconnect of client

mcs/class/corlib/ReferenceSources/BCLDebug.cs, mcs/class/referencesource/mscorlib/system/resources/resourcereader.cs
After https://github.com/mono/mono/pull/18040 we now have InternalsVisibleTo for the Mono.Android assembly.
This exposed the internal LogLevel enum in BCLDebug which causes an issue when consumed in XA:
```
Java.Lang/Object.cs(119,18): error CS0104: 'LogLevel' is an ambiguous reference between 'Android.Runtime.LogLevel' and 'System.LogLevel'
```
To fix this we rename the internal enum in corlib since it's not really used.
/cc @BrzVlad @jonathanpeppers 
Backport of #18124.
=> [2019-12] [corlib] Rename internal LogLevel enum to avoid conflict with Android LogLevel

sdks/wasm/xunit-exclusions.rsp
It brings https://github.com/mono/corefx/pull/378.
As for unrelated FSW stuff I guess there is another bump for it so it'll come anyway.
Relates to https://github.com/mono/mono/issues/16858
=> [wasm] Re-enabling a test that was fixed by the corefx bump

mcs/class/corlib/ReferenceSources/BCLDebug.cs, mcs/class/referencesource/mscorlib/system/resources/resourcereader.cs
After https://github.com/mono/mono/pull/18040 we now have InternalsVisibleTo for the Mono.Android assembly.
This exposed the internal LogLevel enum in BCLDebug which causes an issue when consumed in XA:
```
Java.Lang/Object.cs(119,18): error CS0104: 'LogLevel' is an ambiguous reference between 'Android.Runtime.LogLevel' and 'System.LogLevel'
```
To fix this we rename the internal enum in corlib since it's not really used.
/cc @BrzVlad @jonathanpeppers
=> [corlib] Rename internal LogLevel enum to avoid conflict with Android LogLevel

mono/utils/mono-dl-posix.c, mono/utils/mono-dl-wasm.c
On Linux, neither flag being specified will result in a default of RTLD_LOCAL. Unfortunately, on MacOS it's the opposite - the default is RTLD_GLOBAL. This means currently there is no way to set RTLD_LOCAL on Macs, so despite the potential for this to break someone it directly contradicts our documentation and needs to be changed.
=> [utils] Correctly convert MONO_DL_LOCAL to RTLD_LOCAL

configure.ac, mcs/class/System/System.Net.Sockets/Socket.cs, mono/metadata/icall-def.h, mono/metadata/w32socket.c
Also partial undo recent and append _icall to end.
This is verbose, but maybe worthwhile to aid search.
This is extracted from https://github.com/mono/mono/pull/17978.
=> Make Socket.Socket_icall static, as most icalls are, removing the first, unused parameter.

netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml, netcore/System.Private.CoreLib/src/Mono/MonoDomain.cs
This is no longer called in netcore builds as of a while ago, so get rid of it and the corresponding linker exclusion.
=> [netcore] Remove MonoDomain.DoAssemblyResolve

netcore/CoreFX.issues.rsp
The relevant API (GC.GetGCMemoryInfo) has existed for a while now.
=> [netcore] Enable AppDomainTests.MonitoringIsEnabled

sdks/wasm/tests/browser/src/Directory.Build.props
There are problems on the CI when using the linker building the Browser Tests.
https://github.com/mono/mono/commit/3142396c3c6a62f389420113129783bb156de399
PR https://github.com/mono/mono/pull/18128
=> [wasm][ci] Deactivate linker on browser tests

netcore/CoreFX.issues.rsp
I don't remember why this wasn't enabled originally, but it seems to be passing now. I probably accidentally fixed it back when I made changes to our assembly name parsing.
=> [netcore] Enable AppDomainTests.AssemblyResolveInvalidAssemblyName

mono/mini/debugger-agent.c
When the debugger tries to suspend all the VM threads, it can happen with cooperative-suspend that it tries to suspend a thread that has previously been attached, but then did a "light" detach (that only unsets the domain). With the domain set to `NULL`, looking up a JitInfo for a given `ip` will result into a crash, but it isn't even necessarily needed for the purpose of suspending a thread.
More details: Consider the following:
```
(lldb) c
error: Process is running.  Use 'process interrupt' to pause execution.
Process 12832 stopped
* thread #9, name = 'tid_a31f', queue = 'NSOperationQueue 0x8069b670 (QOS: UTILITY)', stop reason = breakpoint 1.1
frame #0: 0x00222870 WatchWCSessionAppWatchOSExtension`debugger_interrupt_critical(info=0x81365400, user_data=0xb04dc718) at …
```
=> [2019-08] [debugger] skip suspend for unattached threads

sdks/wasm/xunit-exclusions.rsp
on MacOS:
`make -C sdks/wasm run-System-xunit`:
before: WASM: TESTS = 5385, RUN = 1193, SKIP = 4268, FAIL = 0
after:    WASM: TESTS = 5385, RUN = 5313, SKIP = 153, FAIL = 0
Relates #16858
/cc @steveisok
=> [wasm] Disable particular failing System.Net.Security.Tests tests rather than the whole namespace

mono/metadata/sre.c
=> Fix on-demand initialization race conditions [sre.c].

mono/mini/aot-compiler.c, mono/mini/debugger-agent.c, mono/mini/method-to-ir.c, mono/mini/mini-generic-sharing.c
=> Fix on-demand initialization race conditions [mini].

mono/metadata/native-library.c
=> Fix on-demand initialization race conditions [native-library.c].

mono/metadata/remoting.c
=> Fix on-demand initialization race conditions [remoting.c].

mono/metadata/sgen-toggleref.c
=> Fix on-demand initialization race conditions [sgen].

mcs/class/System.ServiceModel/ReferenceSources/SR.cs, mcs/class/System.ServiceModel/System.ServiceModel.Channels/MessageFault.cs, mcs/class/System.ServiceModel/System.ServiceModel.csproj, mcs/class/System.ServiceModel/System.ServiceModel.dll.sources, mcs/class/System.ServiceModel/Test/Resources/soap-fault-number.xml, mcs/class/System.ServiceModel/Test/System.ServiceModel.Channels/MessageFaultTest.cs, mcs/class/System.ServiceModel/mobile_System.ServiceModel.dll.sources, mcs/class/referencesource/System.ServiceModel/System/ServiceModel/XmlUtil.cs, mcs/class/referencesource/System.Xml/System/Xml/XmlCharType.cs
The mono implementation was reading the faultcode content as an XmlQualifiedName, which applied the rule where you could not start a name with a number. This caused interoperability problems with the .net framework because their parsing just looks for <namespace>:<name>, where name can be any string.
Example:
`<faultcode>s:1</faultcode>`
On mono, a soap response that contains a fault code name of 1 will throw an error.  If you run the same code on the .net framework, it will not.
Fixes https://github.com/mono/mono/issues/12995
=> Relax faultcode parsing for Soap11 message errors.

mono/metadata/cominterop.c
=> Fix on-demand initialize race conditions [cominterop.c]

sdks/wasm/Mono.WebAssembly.DebuggerProxy/Mono.WebAssembly.DebuggerProxy.csproj, sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
When the proxy runs into an error parsing properties request it will crash and end the debugging session unexpectedly.  Instead log the error to stdout right now and send back a failed message.
The locals window in VSC returns empty.  This may be what is happening as reported by Blazor but not sure if it is the exact error they reported.
Also, updates `Mono.Cecil` and `Newtonsoft` to current versions.
=> [wasm][debug-proxy] Fix crash and send back failed message.

mono/metadata/threads.c
=> Fix on-demand initialization race conditions [threads.c].

mono/metadata/cominterop.c, mono/tests/cominterop.cs, mono/tests/libtest.c
If the COM object for a managed object is passed to a thread that hasn't interacted with Mono before, we need to attach before doing GC thread state transitions.
---
Also added tests that invoke managed methods via a COM interface from an unattached thread.  This works (because the COM vtable entry is a native-to-managed wrapper which does a thread attach) but I don't think we had a test case before.
---
Addresses #18137
=> [cominterop] Attach to runtime from IUnknown and IDispatch methods

mono/utils/mono-memory-model.h
A compiler barrier generates no code.
It "only" inhibits certain compiler optimizations, which I do not consider
particularly worrisome, as most code is "fully" optimized, and
compiler barriers are relatively rare.
It could be a concern in code paths that greatly benefit
from compiler optimizations and for which barriers greatly
inhibits the compiler.
I would further suggest, though it is not here, that any compiler
half barrier (read, write) be a compiler full barrier instead,
as they sound pretty cheap, so simplify.
Similar cannot be said about CPU barriers.
They do not always generate code, but when they do, it can cost.
This is follow-up from https://github.com/mono/mono/pull/17849#issuecomment-556273801
https://github.com/mono/mono/pull/17849#issuecomment-557661604.
=> Add full compiler barriers to any fence that lacked a compiler barrier.

mcs/class/System.ServiceModel/ReferenceSources/SR.cs, mcs/class/System.ServiceModel/System.ServiceModel.Channels/MessageFault.cs, mcs/class/System.ServiceModel/System.ServiceModel.csproj, mcs/class/System.ServiceModel/System.ServiceModel.dll.sources, mcs/class/System.ServiceModel/Test/Resources/soap-fault-number.xml, mcs/class/System.ServiceModel/Test/System.ServiceModel.Channels/MessageFaultTest.cs, mcs/class/System.ServiceModel/mobile_System.ServiceModel.dll.sources, mcs/class/referencesource/System.ServiceModel/System/ServiceModel/XmlUtil.cs, mcs/class/referencesource/System.Xml/System/Xml/XmlCharType.cs
The mono implementation was reading the faultcode content as an XmlQualifiedName, which applied the rule where you could not start a name with a number. This caused interoperability problems with the .net framework because their parsing just looks for <namespace>:<name>, where name can be any string.
Example:
`<faultcode>s:1</faultcode>`
On mono, a soap response that contains a fault code name of 1 will throw an error.  If you run the same code on the .net framework, it will not.
Fixes https://github.com/mono/mono/issues/12995
Backport of #18154.
/cc @steveisok
=> [2019-12] Relax faultcode parsing for Soap11 message errors.

sdks/wasm/xunit-exclusions.rsp
This PR re-enables `System.MemoryTests` and `System.SpanTests` xunit tests.
Some of SpanTests still fail (due to the CompareInfo issue?):
```
System.SpanTests.ReadOnlySpanTests.Compare
System.SpanTests.ReadOnlySpanTests.IndexOf_AllSubstrings
System.SpanTests.ReadOnlySpanTests.IndexOf_EquivalentDiacritics_EnglishUSCulture
System.SpanTests.ReadOnlySpanTests.IndexOf_EquivalentDiacritics_InvariantCulture
```
Run on MacOS:
before: `WASM: TESTS = 64145, RUN = 72923, SKIP = 17030, FAIL = 0`
after: `WASM: TESTS = 64145, RUN = 74948, SKIP = 15033, FAIL = 0`
Relates to #16858
/cc @steveisok
=> [wasm][xunit] Re-enable System.MemoryTests and System.SpanTests tests

scripts/ci/run-jenkins.sh, sdks/wasm/Makefile, sdks/wasm/packager.cs, sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets
- Add dynamic runtime browser tests in CI
- Change `release-dynamic` to `dynamic-release` to align with other runtimes
- Add `-dynamic-runtime` flag for packager.exe
- Add debug configuration for dynamic runtime
- Fix invalid `MAIN_MODULE=2` flag, which forces the emscripten linker to pass even on exported functions
=> [Wasm] Enable dynamic runtime tests

sdks/wasm/xunit-exclusions.rsp
Two methods are still being excluded due to crash:
```
System.Tests.MathFTests.Round_Digits
System.Tests.MathFTests.Truncate
```
before: `WASM: TESTS = 64145, RUN = 74948, SKIP = 15033, FAIL = 0`
after:  `WASM: TESTS = 64145, RUN = 75850, SKIP = 14125, FAIL = 0`
Relates to #16858
/cc @steveisok
=> [wasm][xunit tests] Re-enable System.Tests.MathFTests

mono/metadata/cominterop.c, mono/tests/cominterop.cs, mono/tests/libtest.c
If the COM object for a managed object is passed to a thread that hasn't interacted with Mono before, we need to attach before doing GC thread state transitions.
---
Also added tests that invoke managed methods via a COM interface from an unattached thread.  This works (because the COM vtable entry is a native-to-managed wrapper which does a thread attach) but I don't think we had a test case before.
---
Addresses #18137
Backport of #18175.
=> [2019-12] [cominterop] Attach to runtime from IUnknown and IDispatch methods

mcs/class/corlib/Test/System/TypeTest.cs, mono/metadata/class-init.c
Fixes #7095
Judging by https://github.com/mono/mono/blob/4cefdcb7ce2d939ee78fb45d1b4913eb3bc064fd/mono/metadata/metadata.c#L3515 the cached_class is sometimes intentionally a GTD, which can get passed all the way down to `setup_generic_array_ifaces` and causes a crash.
=> [metadata] Check for GTDs in setup_generic_array_ifaces

sdks/wasm/xunit-exclusions.rsp
Three failures exist:
```
System.Buffers.Text.Tests.ParserTests.TestParserDecimal
System.Buffers.Text.Tests.ParserTests.TestParserDouble
System.Buffers.Text.Tests.ParserTests.TestParserSingle
```
before: `WASM: TESTS = 64145, RUN = 75850, SKIP = 14125, FAIL = 0`
after:  `WASM: TESTS = 64145, RUN = 92584, SKIP = 14094, FAIL = 0`
Relates to #16858
/cc @steveisok
=> [wasm][xunit tests] Re-enable System.Buffers.Text.Tests.ParserTests

mono/mini/mini-arm64.c
This assert fails when the trampoline code size worst case is realized.
Observed on a Android device with HWASan [1] enabled, where heap
addresses have a non-zero tag in the most significant byte, and thus
require 4 instructions to materialize in emit_imm64.
[1] https://source.android.com/devices/tech/debug/hwasan
=> Relax assert in mono_arch_build_imt_trampoline.

mono/metadata/cominterop.c, mono/tests/cominterop.cs, mono/tests/libtest.c
If the COM object for a managed object is passed to a thread that hasn't interacted with Mono before, we need to attach before doing GC thread state transitions.
---
Also added tests that invoke managed methods via a COM interface from an unattached thread.  This works (because the COM vtable entry is a native-to-managed wrapper which does a thread attach) but I don't think we had a test case before.
---
Addresses #18137
Backport of #18175.
=> [2019-10] [cominterop] Attach to runtime from IUnknown and IDispatch methods

mcs/class/corlib/Test/System/TypeTest.cs, mono/metadata/class-init.c
Fixes #7095
Judging by https://github.com/mono/mono/blob/4cefdcb7ce2d939ee78fb45d1b4913eb3bc064fd/mono/metadata/metadata.c#L3515 the cached_class is sometimes intentionally a GTD, which can get passed all the way down to `setup_generic_array_ifaces` and causes a crash.
Backport of #18101.
=> [2019-12] [metadata] Check for GTDs in setup_generic_array_ifaces

mono/mini/cfold.c
This fixes an error in constant propagation when propagating a constant through a sign extension operation. The result type was set to ICONST, which doesn't always work since the result should be 64 bits. The fix was to change it to I8CONST.
The github issue with a simple repro is here: https://github.com/mono/mono/issues/17928
=> Fix bug in constant propagation through sign extension

sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
=> [wasm][debugger] fix exception when we can't locate debug assembly

sdks/wasm/xunit-exclusions.rsp
This is a follow up PR to https://github.com/mono/mono/pull/18208
/cc @steveisok
=> [wasm][xunit tests] Re-enable System.Tests.MathFTests.Round_Digits and System.Tests.MathFTests.Truncate

sdks/wasm/src/library_mono.js
the clear_all_bp function was never getting wrapped, this fixes that and cleans up some of the other signatures to match the emscripten docs
=> [wasm][debugger] Fix clear all bp

global.json
Should unbreak the publishing build of netcore-mono.
=> [netcore] Update dotnet sdk version in global.json

netcore/CoreFX.issues.rsp
These seem to have been fixed inadvertently at some point. Who knows, but they pass now, at least on my machine!
Fixes #15116 
Fixes #15117
=> [netcore] Re-enable some BinaryFormatter tests

mono/metadata/assembly.c, mono/mini/main-core.c
`mono_trace` adds a newline automatically, and we had a few random entries that were doubling up for no reason. This makes the logs easier to skim.
=> [loader] Remove unnecessary newlines in tracing

scripts/ci/run-jenkins.sh, sdks/wasm/DebuggerTestSuite/Support.cs, sdks/wasm/Makefile, sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs, sdks/wasm/Mono.WebAssembly.DebuggerProxy/WsClient.cs, sdks/wasm/ProxyDriver/TestHarnessStartup.cs, sdks/wasm/build.sh, sdks/wasm/packager.cs
This fixes the debugger test harness and enables it in CI.  Then fixes packager to correctly locate the pdbs for assembly references.
=> [wasm][debugger] Fix debugger test harness and enable it in CI

mono/metadata/domain.c
Also when iterating over the runtimes, actually look at the current element,
not the first element.
Also mention the unsupported runtime version in the warning message when it is
passed to mono_init_internal.
Fixes https://github.com/mono/mono/issues/17916
Backport of #18260.
=> [2019-10] [domain] Don't add NULL runtime to runtimes list

mono/mini/mini-llvm.c
Should fix https://github.com/mono/mono/issues/18221.
=> Use byte-aligned LLVM loads and stores for unaligned mini IR loads and stores.

mcs/class/System/System.Net.Sockets/Socket.cs
Socket.BeginMConnect() should not attempt connections on unsupported address families.
Fixes #16513.
=> Socket.BeginMConnect() should not attempt connections on unsupported address families.

mcs/class/System/System.Net.Sockets/Socket.cs
Socket.BeginMConnect() should not attempt connections on unsupported address families.
Fixes #16513.
Backport of #18302.
/cc @steveisok @baulig
=> [2019-12] Socket.BeginMConnect() should not attempt connections on unsupported address families.

mcs/class/System/System.Net.Sockets/Socket.cs
Socket.BeginMConnect() should not attempt connections on unsupported address families.
Fixes #16513.
Backport of #18302.
/cc @steveisok @baulig
=> [2019-10] Socket.BeginMConnect() should not attempt connections on unsupported address families.

mcs/class/corlib/System/TermInfoDriver.cs
This flag was causing issues when accessing console properties on concurrent threads during TermInfoDriver initialisation.
Fixes #18317
=> Set inited flag _after_ TermInfoDriver initialisation completes

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c, mono/mini/mini-exceptions.c
The behaviour expected of filter exceptions is:
-> throw in a async task with a try catch in the caller -> don't stop
-> throw in a new thread with a try catch in the caller -> stop
-> throw in the main thread without any try catch -> stop
Including a new test to test the fix of #17601.
Fixing #16588, create a while 1 to stops the program execution when an exception is thrown and no try catch is found and MONO_DEBUG=suspend-on-unhandled.
Fixes #17601
Fixes #16588
=> [debugger] Fix exception handler in a new thread and fix MONO_DEBUG=suspend-on-unhandled

mcs/class/corlib/System/MonoCustomAttrs.cs, netcore/CoreFX.issues.rsp, netcore/System.Private.CoreLib/src/System/Attribute.Mono.cs, netcore/System.Private.CoreLib/src/System/Reflection/CustomAttribute.cs
There's no reason to use object[] internally, and it leads to accidental object[]-typed array creation, which then can't be downcast to Attribute[].
The most important part of the fix was applied to the legacy BCL as well, though not the full set of changes.
Fixes #15173
Fixes #15171
=> [reflection] Convert internal GetCustomAttributes calls to Attribute[]

sdks/wasm/packager.cs
Improves Windows compatibility by using `Path.Combine` instead of explicit path separator.
=> [Wasm] Use Path.Combine in Packager

mono/mini/mini-llvm-cpp.cpp, mono/mini/mini-llvm-cpp.h, mono/mini/mini-llvm.c
Notify LLVM that all allocations we do are 8-byte aligned (managed wrappers) via `align 8` attributes. 
E.g.:
```csharp
static int[] Test()
{
return new int[100];
}
```
LLVM IR Diff: https://www.diffchecker.com/sz2kHGv5
So LLVM doesn't need to emit redundant "is aligned" checks in some places, etc.
Assembly diff for `System.Private.CoreLib.dll` (LLVM-AOT) using `make jitdiff`:
```
Total diff for System.Private.CoreLib.dll.so.dasm: -1111 bytes
Total diff for all files: -1111 bytes
=====================
= Per-method diffs (may take a while):
=====================
Diff for  <string_Ctor_char__>::  -1 lines (-2.0%)
Diff for  <string_Ctor_char___int_int>::  -1 lines (-2.0%)
Diff for  <string_Ctor_char__int_int>::  -1 lines (-2.0%)
Diff for  <string_Concat_string_string_string>::  -2 lines …
```
=> [llvm] Add !align 8 to all managed allocators (calls)

mono/mini/mini-llvm.c
Should fix https://github.com/mono/mono/issues/18221.
Backport of #18296.
/cc @lambdageek @imhameed
=> [2019-12] Use byte-aligned LLVM loads and stores for unaligned mini IR loads and stores.

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c, mono/mini/mini-exceptions.c
The behaviour expected of filter exceptions is:
-> throw in a async task with a try catch in the caller -> don't stop
-> throw in a new thread with a try catch in the caller -> stop
-> throw in the main thread without any try catch -> stop
Including a new test to test the fix of #17601.
Fixing #16588, create a while 1 to stops the program execution when an exception is thrown and no try catch is found and MONO_DEBUG=suspend-on-unhandled.
Fixes #17601
Fixes #16588
Backport of #18309.
/cc @thaystg
=> [2019-12] [debugger] Fix exception handler in a new thread and fix MONO_DEBUG=suspend-on-unhandled

mcs/class/PEAPI/Metadata.cs, mono/dis/dump.c, mono/metadata/assembly.c, mono/metadata/metadata-internals.h, mono/metadata/metadata.c, mono/tests/Makefile.am, mono/tests/null-blob-main.cs, mono/tests/null-blob-null-blob-assm.il, mono/tests/null-blob-ref.il, mono/tests/null-blob-tgt.cs
Sometimes, ILasm apparently can produce images with a size 0 Blob heap.  In cases where we're loading assembly references from such an image, the hash (which is optional) can be at index = 0 and the Blob heap size is also 0.
Also: add the hash value to the output of `monodis --assemblyref`
Also: patch PEAPI (used by mono's `ilasm`) to emit a size 0 Blob heap if no blobs are added.  Previously it would unconditionally emit the index 0 entry (a single zero byte - required by ECMA 335 II.24.2.) Now it will only emit the index 0 entry only if the MetaDataStream.Add methods are called.
Related to #10332
=> [metadata] Size 0 Blob heap is ok when resolving assembly refs

mcs/class/corlib/Test/System.IO/DirectoryInfoTest.cs
Bump to mono/corefx@b7e7440
Backport of https://github.com/mono/mono/pull/18310
=> [2019-12] Pull in DirectoryInfo Invalidate After Create Fix

mcs/class/corlib/System/TermInfoDriver.cs
This flag was causing issues when accessing console properties on concurrent threads during TermInfoDriver initialisation.
Fixes #18317
Backport of #18318.
/cc @steveisok @nagytech
=> [2019-12] Set inited flag _after_ TermInfoDriver initialisation completes

mcs/class/PEAPI/Metadata.cs, mono/dis/dump.c, mono/metadata/assembly.c, mono/metadata/metadata-internals.h, mono/metadata/metadata.c, mono/tests/Makefile.am, mono/tests/null-blob-main.cs, mono/tests/null-blob-null-blob-assm.il, mono/tests/null-blob-ref.il, mono/tests/null-blob-tgt.cs
Sometimes, ILasm apparently can produce images with a size 0 Blob heap.  In cases where we're loading assembly references from such an image, the hash (which is optional) can be at index = 0 and the Blob heap size is also 0.
Also: add the hash value to the output of `monodis --assemblyref`
Also: patch PEAPI (used by mono's `ilasm`) to emit a size 0 Blob heap if no blobs are added.  Previously it would unconditionally emit the index 0 entry (a single zero byte - required by ECMA 335 II.24.2.) Now it will only emit the index 0 entry only if the MetaDataStream.Add methods are called.
Related to #10332 
Backport of #18313.
=> [2019-12] [metadata] Size 0 Blob heap is ok when resolving assembly refs

mcs/class/PEAPI/Metadata.cs, mono/dis/dump.c, mono/metadata/assembly.c, mono/metadata/metadata-internals.h, mono/metadata/metadata.c, mono/tests/Makefile.am, mono/tests/null-blob-main.cs, mono/tests/null-blob-null-blob-assm.il, mono/tests/null-blob-ref.il, mono/tests/null-blob-tgt.cs
Sometimes, ILasm apparently can produce images with a size 0 Blob heap.  In cases where we're loading assembly references from such an image, the hash (which is optional) can be at index = 0 and the Blob heap size is also 0.
Also: add the hash value to the output of `monodis --assemblyref`
Also: patch PEAPI (used by mono's `ilasm`) to emit a size 0 Blob heap if no blobs are added.  Previously it would unconditionally emit the index 0 entry (a single zero byte - required by ECMA 335 II.24.2.) Now it will only emit the index 0 entry only if the MetaDataStream.Add methods are called.
Related to #10332 
Backport of #18313.
=> [2019-10] [metadata] Size 0 Blob heap is ok when resolving assembly refs

mono/mini/Makefile.am.in, mono/mini/gshared.cs, mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/18276.
=> [jit] Avoid passing a vtable argument to DIM methods when making calls out of gsharedvt methods.

mono/metadata/icall-def-netcore.h, mono/metadata/icall.c, mono/metadata/monitor.c, mono/mini/interp/transform.c, netcore/System.Private.CoreLib/src/System/Array.Mono.cs, netcore/System.Private.CoreLib/src/System/Diagnostics/Debugger.cs, netcore/System.Private.CoreLib/src/System/Object.Mono.cs, netcore/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeFeature.Mono.cs, netcore/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.Mono.cs, netcore/System.Private.CoreLib/src/System/String.Mono.cs, netcore/System.Private.CoreLib/src/System/Threading/Interlocked.cs, netcore/System.Private.CoreLib/src/System/Threading/Monitor.cs, netcore/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs, netcore/System.Private.CoreLib/src/System/Type.Mono.cs
1. Removed icalls where intrinsic version for the method exists
2. Add [Intrinsic] attribute to methods which have runtime intrinsic
to make them easier to track and to tell linker not to analyze them
3. Use recursive syntax for any intrinsic which can be called via
reflection to correctly apply the intrinsic when invoked.
```C#
public static bool IsSupported { get => IsSupported; }
```
When one calls X86.IsSupported, the call gets replaced by an
intrinsics. When one calls it with an Invoke, the body of IsSupported
gets replaced by intrinsics. It's just a hack to get Invoke support for free.
=> [System.Private.CoreLib] Cleanup intrinsic tracking

mono/metadata/sgen-bridge-internals.h, mono/metadata/sgen-bridge.c, mono/metadata/sgen-tarjan-bridge.c
Between C# and java (on android) there are objects that live on both worlds. This means that there exists a C# object with a corresponding java object. The relationship between them is strong, meaning if C# object is alive then java object must stay alive, and vice-versa. We keep java bridge objects always alive through a GCHandle (on the java gc). When doing a C# collection we select all bridge objects that appear to be dead on the C# side. These objects are candidates for collection, assuming the java side has nothing against it. Before triggering a collection on the java side (following the mono gc) we switch all the strong gchandles to the java objects to be weak (for these objects that are candidate to be collected) and we recreate the reference graph from the C# side to the java …
=> [sgen] Fix xref computation with tarjan bridge

scripts/ci/provisioning/freebsd.sh
The base image appears to have perl5.26 which conflicts with perl5-5.30, resulting in the /usr/local/bin/perl binary not being placed by perl5-5.30, which results in failed builds. The `perl5.26` appears to be part of the base image and has no packages actually dependent on it.
=> Fix for perl5.26 / perl5-5.30 conflict

mono/mini/Makefile.am.in, mono/mini/gshared.cs, mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/18276.
Backport of #18334.
=> [2019-12] [jit] Avoid passing a vtable argument to DIM methods when making calls out of gsharedvt methods.

mono/mini/Makefile.am.in, mono/mini/gshared.cs, mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/18276.
Backport of #18334.
=> [2019-10] [jit] Avoid passing a vtable argument to DIM methods when making calls out of gsharedvt methods.

mono/metadata/class-internals.h, mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/18364.
=> [runtime] Initialize field info before accessing it in ves_icall_System_RuntimeFieldHandle_SetValueDirect ().

mono/metadata/object.c
This was prompted by https://github.com/mono/mono/issues/18339, which seems to be failing to locate a native library and then hitting this assertion. We should propagate the error instead, so that if others run into something similar they can see what's actually going wrong instead of just getting a runtime crash.
=> [metadata] Propagate error in mono_runtime_try_invoke_array

mcs/class/corlib/ReferenceSources/RuntimeType.cs, netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs
Fixes #18180 
Updated test to follow in dotnet/runtime
=> [reflection] Fix check for Type.FullName to match CoreCLR

mono/utils/mono-threads-posix.c
`limits.h` doesn't always define `PAGESIZE` properly (e.g. iOS), so it would fall back to `0x1000` (4096) but it's really `0x4000` (16384) on iOS. We already have a helper in the runtime to determine the pagesize, so let's use that instead.
Fixes https://github.com/mono/mono/issues/18273
=> [memory barrier] use pagesize determined by helper

netcore/CoreFX.issues.rsp
https://github.com/mono/mono/issues/14903
=> [netcore][xunit tests] Re-enable System.Diagnostics.Tests.ProcessTests.ProcessStart_UseShellExecute_ExecuteOrder

mcs/class/corlib/ReferenceSources/RuntimeType.cs, netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs
Fixes #18180 
Updated test to follow in dotnet/runtime
Backport of #18385.
=> [2019-12] [reflection] Fix check for Type.FullName to match CoreCLR

mono/utils/mono-threads-posix.c
`limits.h` doesn't always define `PAGESIZE` properly (e.g. iOS), so it would fall back to `0x1000` (4096) but it's really `0x4000` (16384) on iOS. We already have a helper in the runtime to determine the pagesize, so let's use that instead.
Fixes https://github.com/mono/mono/issues/18273
Backport of #18383.
/cc @lewurm
=> [2019-12] [memory barrier] use pagesize determined by helper

mono/mini/interp/interp.c
Native methods can be run in gc safe mode, meaning we can be in gc safe mode while setting/getting the arguments for a native transition. Call context computation requires us to be in unsafe mode.
Fixes https://github.com/mono/mono/issues/16969
=> [interp] Add gc unsafe transition during pinvokes

sdks/wasm/packager.cs
Reverts mono/mono#18401
This only works with:
https://github.com/mono/linker/pull/910
=> Revert "[wasm] Pass --used-attrs-only true to the linker."

mono/mini/interp/interp.c, mono/tests/libtest.c, mono/tests/pinvoke2.cs
If we are in pinvoke wrapper, we need to use the marshalled native size, not the managed size.
=> [interp] Fix struct copying during pinvoke transitions

mcs/class/System.Windows.Forms/System.Windows.Forms/X11Keyboard.cs
Two small fixes to X11 keyboard handling here:
- For Xutf8LookupString, use the actual buffer size rather than the starting buffer size. Using the previous fixed size made the buffer overflow handing code immediately after the change pointless.
- For XLookupString, handle similar to Xutf8LookupString, getting a byte array. The old was sometimes causing problems where input on the numeric keypad didn't enter text. I believe using a StringBuilder similar to how it was _should_ work, but for some reason I could not get it to work reliably. So I changed it to this, which seems to work well for me. The only question I have is whether it should be Encoding.ASCII like I used, Encoding.Default, or another specific encoding.
=> [Winforms] X11Keyboard LookupString fixes

.gitattributes
Looks like https://github.com/mono/mono/commit/c9dc20f59ebe7fbed2a439d69c2d03a2d4500577 broke Windows build for some scenarios using .bat files. Fix makes sure we convert .bat and .cmd files to use crlf in wd.
=> Make sure .bat and .cmd files have crlf in wd.

mcs/class/System.Windows.Forms/System.Windows.Forms/X11Structs.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/XplatUIX11.cs
Fixes https://xamarin.github.io/bugzilla-archives/20/20233/bug.html Previously, on Linux, setting Control.Region just set the clipping for painting, but didn't influence the visibility of other controls behind the one it was set on. This implements this correctly via X11 Shape extension.
=> [Winforms] Implement correct Control.Region / ClipRegion support on X11

mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs
- Make the state of Control.CanSelect depend on whether the control is visible and enabled.
- When setting Control.Visible to false, if this control is focused, move the focus to the next control.
=> [Winforms] Don't have non-active controls focused

mcs/class/System.Windows.Forms/System.Windows.Forms/X11Keyboard.cs
- Ignore key events with vkey == 0. They won't match a real key code so don't try. Besides, trying can cause segfaults on ChromeOS Linux mode.
- Check special-case keys (numpad) before looping to get them. No point leaving them for afterwards...
=> [Winforms] Improve X11 keyboard handling.

mcs/class/System.Windows.Forms/System.Windows.Forms.Theming/Default/LabelPainter.cs
Previously, if the Label wasn't quite high enough nothing would be drawn as the line didn't quite fit. It should draw the line anyway, clipped if necessary.
=> [Winforms] Always draw at least one line of a Label.

mcs/class/System.Windows.Forms/System.Windows.Forms/GroupBox.cs
GroupBox's GetPreferredSize() is not great. I've simply copied the code from Panel, and used that. It uses LayoutEngine.GetPreferredSize(), which does things a lot better than the code this used.
=> [Winforms] Calculate GroupBox preferred size the same way as Panel

mono/metadata/icall.c, mono/mini/simd-intrinsics-netcore.c, netcore/build.sh
1. Update `build.sh` to use `--enable-checked-build=private_types` which forces the use of getter methods to access `MonoClass` fields.
2. Fix up some places that were accessing MonoClass directly.
3. Get rid of a spurious comma operator usage from an earlier refactoring:
```c
z = a, b, c;
```
is the same as
```c
z = a; b; c;
```
which is the same as just `z = a;` if `b` and `c` have no side-effects.
=> [netcore] Require use of MonoClass getters in Debug builds

mono/mini/mini.h, mono/utils/dlmalloc.c, mono/utils/dlmalloc.h
This is https://github.com/mono/mono/pull/17325 but with configure.ac change removed.
Each of the commits can also be separated and have been.
=> [cxx] Fixes for all lanes to build as C++ but w/o configure.ac change.

mono/metadata/boehm-gc.c, mono/metadata/gc-internals.h, mono/metadata/null-gc.c, mono/metadata/sgen-mono.c, mono/metadata/threads.c
Use under Boehm to detach without threads lock as Boehm will take it's own lock internally.
Note in `on_gc_notification` we take threads lock after Boehm already has it's own lock. For consistency and to prevent deadlocks always take lock ordering of Boehm then threads lock.
=> Add mono_gc_thread_detach callback for Boehm

mono/mini/mini.h
The explanations/fixes were:
Compile consistently as C++:
https://github.com/mono/mono/commit/893486638cae8efc46323d6c2209fc99febcd05d
Make inconsistent compilation safe since it was fragile:
https://github.com/mono/mono/commit/b2817e6404d573e837e1d8c7e047135974a3b311
=> Remove comment about unexplained C++/LLVM problem.

mono/mini/jit-icalls.h
There are pluses and minuses here:
plus Minimize externC.
plus Maximize typesafe linkage (not clear for these).
minus Minimize configuration-sensitivity.
minus Maximize commonality across all configurations, so that
success in one configuration maximally but not 100% implies
success in others (which is why to avoid `#if` in general,
to contribute toward compilation success).
plus Use higher level macros to explain reason.
Even if ICALL_EXTERN_C was always externC (presently not),
using it instead of plain G_EXTERN_C offers a builtin comment.
=> [cxx] Make the externC of JIT icalls configuration-dependent instead of always.

mono/mini/tramp-arm.c
See `bl` documentation (make sure you look at the thumb2 one):
Fixes https://github.com/mono/mono/issues/18247
=> [arm] account for signed bit when calculating offset to PLT entry

mono/mini/tramp-arm.c
See `bl` documentation (make sure you look at the thumb2 one):
Fixes https://github.com/mono/mono/issues/18247
Backport of #18454.
/cc @lewurm
=> [2019-10] [arm] account for signed bit when calculating offset to PLT entry

mono/mini/tramp-arm.c
See `bl` documentation (make sure you look at the thumb2 one):
Fixes https://github.com/mono/mono/issues/18247
Backport of #18454.
/cc @lewurm
=> [2019-12] [arm] account for signed bit when calculating offset to PLT entry

Makefile.am, configure.ac
Automake doesn't have a built-in `noinst_SUBDIRS`, because Automake doesn't add "much-needed features" which have only been asked for for 15 years.
So override `make install` with a custom rule to filter out entries.
Yes, I tested it.
```
--- makeinstall.files	2019-11-25 11:52:50.560157892 -0500
+++ makeinstall-with-patch.files	2019-11-25 11:32:12.487098228 -0500
@@ -107,25 +107,6 @@
./etc/mono/browscap.ini
./etc/mono/config
./etc/mono/mconfig/config.xml
-./include/gc/cord.h
-./include/gc/cord_pos.h
-./include/gc/ec.h
-./include/gc/gc_allocator.h
-./include/gc/gc_backptr.h
-./include/gc/gc_config_macros.h
-./include/gc/gc_disclaim.h
-./include/gc/gc_gcj.h
-./include/gc/gc.h
-./include/gc/gc_inline.h
-./include/gc/gc_mark.h
-./include/gc/gc_pthread_redirects.h
-./include/gc/gc_tiny_fl.h …
```
=> [2019-12] Don't run `make install` in boehm submodule

mono/mini/mini-runtime.c, mono/mini/mini-runtime.h
Add an enum for dumping stats at points in time. Print header before dumping stats in `mini_cleanup`.
=> [mini] Print header for stats.

mono/mini/debugger-agent.c
On android sometimes there is no valid_info but the ctx is valid and the debug can continue.
Fixes #18106
=> [debugger] Invalid callstack after repeated breakpoint in Android.OS.AsyncTask

packaging/MacSDK/xsp.py
See https://github.com/mono/xsp/pull/88
Backport of #18478.
=> [2019-10] Bump xsp to fix issues with removed Mono.Security APIs

packaging/MacSDK/xsp.py
See https://github.com/mono/xsp/pull/88
Backport of #18478.
=> [2019-12] Bump xsp to fix issues with removed Mono.Security APIs

mono/mini/debugger-agent.c
This reverts commit 61894d4a0745783372f3214f3bf4345d620fbc21.
@lambdageek and I decided to fix in a different way.
=> Revert "On android sometimes there is no valid_info but the ctx is valid and the debug can continue. (#18463)"

configure.ac, mcs/class/corlib/System.Threading/Thread.cs, mono/metadata/icall-decl.h, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/metadata/threads.c, netcore/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs
This function (and its call to `mono_handle_new`) was showing up in the
flamegraph for some async-heavy benchmarks
=> [runtime] NOHANDLES for ves_icall_System_Threading_Thread_GetCurrentThread

netcore/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs
Follow-up for https://github.com/mono/mono/pull/18480
We might want to replace calls to this with an intrinsic
=> [netcore] Mark InitializeCurrentThread NoInlining

mono/profiler/mprof-report.c
Fixes this warning:
```
CC       mprof-report.o
mprof-report.c:408:62: warning: format specifies type 'char *' but the argument has type 'guint64' (aka 'unsigned long long') [-Wformat]
snprintf (format, sizeof (format), "%s : %%" PRIu64 "\n", (guint64)key_format);
~~                    ^~~~~~~~~~~~~~~~~~~
%llu
/Applications/Xcode112.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:57:62: note: expanded from macro
'snprintf'
__builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
^~~~~~~~~~~
```
mistake in refactoring commit https://github.com/mono/mono/commit/07402062541fa9555bef99dbaac84cfb587926cd#diff-c825627ea9ddb3fa753fa3617eaec7c8R408
=> [prof] remove wrong cast for format string

mcs/class/Mono.Profiler.Log/Test/ProfilerTests.cs
It is not clear if it will fail again or not, but it is not reproducible.
https://github.com/mono/mono/issues/8709
=> [tests] Re-enable profiler test that used to fail

mono/mini/mini-runtime.c, mono/mini/mini-runtime.h
Make print_jit_stats global to enable JIT and interpreter-triggered stat dumps.
=> [mini] Global JIT Stats Printing

mono/metadata/class-init.c, mono/mini/gshared.cs
Fixes #18455
Backport of #18496.
/cc @BrzVlad @vargaz
=> [2019-12] [jit] Compute the instance size/alignment correctly for gshared types whose constraint is a generic valuetype.

mono/mini/driver.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini.c, mono/mini/mini.h
parsing fully qualified method name using a`MonoMethodDesc` struct
=> [mini] parse fully qualified method name using mono_method_desc_new

configure.ac
This causes an additional dependency of mono on libintl which we didn't have before.
Reported by a user on gitter, it's problematic on macOS since it makes the mono binary depend on the libintl we ship in the Mono .pkg.
It was introduced in Mono 6.6 by https://github.com/mono/mono/commit/18e0ebfe89be0a175d2f904b9bb1ec6816daa318
=> configure.ac: remove AC_SEARCH_LIBS for libintl

mono/mini/interp/interp.c
`jit_tls->interp_context` gets initialized lazily, that is, upon the first interpreter execution on a specific thread (e.g. via interp_runtime_invoke). However, with mixed mode the execution can purely happen in AOT code upon the first interaction with the managed debugger.
Stack trace:
```
thread #1, name = 'tid_407', queue = 'com.apple.main-thread'
frame #0: 0x0000000190aedc94 libsystem_kernel.dylib`__psynch_cvwait + 8
frame #1: 0x0000000190a0f094 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 672
frame #2: 0x000000010431318c reloadcontext.iOS`mono_os_cond_wait(cond=0x0000000104b9ba78, mutex=0x0000000104b9ba30) at mono-os-mutex.h:219:8
frame #3: 0x0000000104312a68 reloadcontext.iOS`mono_coop_cond_wait(cond=0x0000000104b9ba78, mutex=0x0000000104b9ba30) at …
```
=> [2019-12] [interp] context can be uninitialized for get_resume_state callback

mono/mini/interp/interp.c
`jit_tls->interp_context` gets initialized lazily, that is, upon the first interpreter execution on a specific thread (e.g. via interp_runtime_invoke). However, with mixed mode the execution can purely happen in AOT code upon the first interaction with the managed debugger.
Stack trace:
```
thread #1, name = 'tid_407', queue = 'com.apple.main-thread'
frame #0: 0x0000000190aedc94 libsystem_kernel.dylib`__psynch_cvwait + 8
frame #1: 0x0000000190a0f094 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 672
frame #2: 0x000000010431318c reloadcontext.iOS`mono_os_cond_wait(cond=0x0000000104b9ba78, mutex=0x0000000104b9ba30) at mono-os-mutex.h:219:8
frame #3: 0x0000000104312a68 reloadcontext.iOS`mono_coop_cond_wait(cond=0x0000000104b9ba78, mutex=0x0000000104b9ba30) at …
```
=> [interp] context can be uninitialized for get_resume_state callback

mono/metadata/class-init.c, mono/mini/gshared.cs
=> [jit] Compute the instance size/alignment correctly for gshared types whose constraint is a generic valuetype.

mono/mini/debugger-agent.c
If a thread was suspended and doesn't have any managed stack, it was considered as terminated, but it wasn't really terminated because it can execute managed code again, and stop in a breakpoint so if the execution arrives in debugger_agent_breakpoint_from_context we reset the flag terminated to FALSE.
Fixes #18106
=> [debugger] Native thread not executing managed code considered as terminated 

mono/mini/debugger-agent.c
If a thread was suspended and doesn't have any managed stack, it was considered as terminated, but it wasn't really terminated because it can execute managed code again, and stop in a breakpoint so if the execution arrives in debugger_agent_breakpoint_from_context we reset the flag terminated to FALSE.
Fixes #18106 
Backport of #18501.
/cc @thaystg
=> [2019-12] [debugger] Native thread not executing managed code considered as terminated 

packaging/MacSDK/packaging/resources/preinstall
- roslyn's shared compiler server hashes it's pipename on the path to
the assembly.
- On macOS, this looks like `/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Roslyn/VBCSCompiler.exe`
- When installing a new mono, with that same `x.y.z` version, this
process will effectively be out of sync with the new updated
mono/msbuild/roslyn
- This manifests as:
```
Using shared compilation with compiler from directory: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Roslyn
/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Roslyn/Microsoft.CSharp.Core.targets(59,5): error : Roslyn compiler server reports different hash version than build task. [/Users/builder/azdo/_work/3/s/xamarin-android/build-tools/xaprepar …
```
=> [bockbuild] preinstall: kill any running VBCSCompiler processes

mono/metadata/icall-decl.h, mono/metadata/icall-def-netcore.h, mono/metadata/icall-def.h, mono/metadata/w32semaphore-unix.c, mono/metadata/w32semaphore-win32.c
Actually, there were no handles.
This reduces MonoError.
=> Remove "handles" from System.Threading.Semaphore.

mcs/errors/cs1013-3.cs, mcs/errors/cs1013-4.cs, mcs/errors/cs1013-5.cs, mcs/errors/cs1013-6.cs, mcs/errors/cs1013-7.cs, mcs/errors/cs1013-8.cs, mcs/mcs/cs-tokenizer.cs, mcs/tests/test-950.cs, mcs/tests/ver-il-net_4_x.xml
Fixes #18467 and #16648 with regards to [digit separators](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.0/digit-separators.md)
=> [mcs] Fix support for digit separators

mono/mini/interp/interp.c
`jit_tls->interp_context` gets initialized lazily, that is, upon the first interpreter execution on a specific thread (e.g. via interp_runtime_invoke). However, with mixed mode the execution can purely happen in AOT code upon the first interaction with the managed debugger.
Stack trace:
```
thread #1, name = 'tid_407', queue = 'com.apple.main-thread'
frame #0: 0x0000000190aedc94 libsystem_kernel.dylib`__psynch_cvwait + 8
frame #1: 0x0000000190a0f094 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 672
frame #2: 0x000000010431318c reloadcontext.iOS`mono_os_cond_wait(cond=0x0000000104b9ba78, mutex=0x0000000104b9ba30) at mono-os-mutex.h:219:8
frame #3: 0x0000000104312a68 reloadcontext.iOS`mono_coop_cond_wait(cond=0x0000000104b9ba78, mutex=0x0000000104b9ba30) at …
```
=> [2019-10] [interp] context can be uninitialized for get_resume_state callback

mono/mini/debugger-agent.c
If a thread was suspended and doesn't have any managed stack, it was considered as terminated, but it wasn't really terminated because it can execute managed code again, and stop in a breakpoint so if the execution arrives in debugger_agent_breakpoint_from_context we reset the flag terminated to FALSE.
Fixes #18106 
Backport of #18501.
/cc @thaystg
=> [2019-10] [debugger] Native thread not executing managed code considered as terminated 

scripts/ci/provisioning/freebsd.sh
compile-runtime-tests is looking for python3, but $(env python3) will return error (no `/usr/local/bin/python3`); if this is the case, create a symlink from 3.6 or 3.7 to /usr/local/bin/python3 so it works. We already have this listed in `SHEBANG_FILES` for the port.
Also stop installing python27 (port is deprecated and will expire by end of year.)
=> [community-ci] Fix for failing compile-runtime-tests

mono/metadata/domain.c
!! This PR is a copy of dotnet/runtime#2142,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
=> [runtime] Avoid loading ThreadAbortException class on netcore.

scripts/ci/run-jenkins.sh, sdks/Make.config.sample, sdks/builds/wasm.mk, sdks/wasm/Makefile, sdks/wasm/src/driver.c
Add a DOTNET_REPO_DIR variable to Make.config which should point to the dotnet/runtime repo. Compile
the netcore runtime and corelib from this repo.
=> [wasm] Fix netcore build.

mono/metadata/class-init.c, mono/mini/memory-access.c
=> [2019-12] [jit] Compute has_references correctly for gshared types whose constraint is a generic valuetype.

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/PointerValue.cs, mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
Creating a fork process to access address that came from IDE using PointerValue. The IDE can send an invalid address and it was crashing mono.
Fixes #18191
=> [debugger] Access invalid memory address using PointerValue Command.

mono/mini/mini-posix.c
!! This PR is a copy of dotnet/runtime#2206,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
Related to root cause of https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1056907
=> [runtime] Disable lldb backtrace display on osx, it hangs on attaching in lldb.

mono/mini/mini-posix.c
Related to root cause of https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1056907
Backport of #18590.
=> [2019-12] [runtime] Disable lldb backtrace display on osx, it hangs on attaching in lldb.

mono/metadata/marshal.c, mono/tests/libtest.c, mono/tests/pinvoke2.cs
This is used by the SplashScreen class of WindowsBase in .NET Core to pass a NULL pointer.
=> Allow passing IntPtr values with UnmanagedType.AsAny.

mcs/class/System.Windows.Forms/System.Windows.Forms/XplatUIX11.cs
The real change here is, in `XplatUIX11.SetWindowPos()`, simply moving the `SendMessage` call to the end instead of earlier. The problem with it earlier is that any change in bounds from any of the bounds-related events (OnLocationChanged / OnMove, OnSizeChanged / OnResize, OnLayout, OnClientSizeChanged) will be overridden. When `SendMessage` is called, `UpdateBounds` is run, and that raises those events as relevant. After those events finish, `SetWindowPos` continues with setting the size of the window to the value originally specified – which is now potentially wrong. So send the message later on.
There is also no point that I can see in writing the values to `hwnd` twice, because as far as I can see the only one that can be changed is `hwnd.ClientRect` (set by `PerformNCCalc`).
=> [Winforms] X11 Fix bounds change from within bounds-related events

mcs/class/System.Windows.Forms/System.Windows.Forms/XplatUIX11.cs
Whenever mono opens an X11 window, the application opens a tcp socket for controlling the (non-tcp)-connection to X11. This is bad practice, as a tcp socket is not needed.
This pull request cleans the logic, by replacing the tcp socket with a fifo. That way this loopback connection is not visible from outside the .NET application, and all logic surrounding it should remain unchanged.
=> Fix open port for X11 applications

mcs/class/Mono.Posix/Mono.Unix/UnixEncoding.cs, mcs/class/Mono.Posix/Test/Mono.Unix/UnixEncodingTest.cs
Current versions of the mono return a null pointer as address of the first
element for empty arrays, i.e.
fixed (byte* ptr = new byte[0]) Console.WriteLine (ptr == null);
will print "true". This causes a problem in the UnixEncoding class where it
triggers a check for null pointers. Fix this by allowing null pointers when
the number of elements is zero.
=> Fix UnixEncoding.GetBytes() for empty strings

mcs/class/System.Windows.Forms/System.Windows.Forms/TextBoxBase.cs
If one click on a `ComboBox` the caret does not appear. This is so because `document.PositionCaret` call hides the caret.
=> [WinForms] Display caret while click on ComboBox

configure.ac
This causes an additional dependency of mono on libintl which we didn't have before.
Reported by a user on gitter, it's problematic on macOS since it makes the mono binary depend on the libintl we ship in the Mono .pkg.
It was introduced in Mono 6.6 by https://github.com/mono/mono/commit/18e0ebfe89be0a175d2f904b9bb1ec6816daa318
Backport of #18531.
=> [2019-12] configure.ac: remove AC_SEARCH_LIBS for libintl

configure.ac
This causes an additional dependency of mono on libintl which we didn't have before.
Reported by a user on gitter, it's problematic on macOS since it makes the mono binary depend on the libintl we ship in the Mono .pkg.
It was introduced in Mono 6.6 by https://github.com/mono/mono/commit/18e0ebfe89be0a175d2f904b9bb1ec6816daa318
Backport of #18531.
=> [2019-10] configure.ac: remove AC_SEARCH_LIBS for libintl

mono/eglib/glib.h, mono/eglib/goutput.c, mono/eglib/gstr.c
Done to unblock the externs, ensuring it works properly on Android. More work should probably be done, see #18580.
=> [eglib] Use the stdout handler with g_printf

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
BreakpointRequest commands can come out of order and before the runtime is ready (RuntimeReady).  A null check for the DebugStore was added to guard against this since these requests seem to be for JS  breakpoints.  These seem to be able to be safely ignored.
Fixes https://github.com/mono/mono/issues/18584
=> [wasm][debugger] Handle When BreakpointRequest Commands Come Out of Order 

mcs/class/System.Windows.Forms/System.Windows.Forms/ListBox.cs
When the user types a letter or digit, KeySearch looks for and selects an item starting with that character. If SelectionMode is None, this is incorrect.
=> [Winforms] Don't select ListBox item if SelectionMode == None

mcs/class/System.Windows.Forms/System.Windows.Forms/Form.cs
- In SelectActiveControl(), use SendControlFocus() rather than Select() because the former simply gives it focus, the latter will set ActiveControl which is at best unnecessary, and I think can cause problems (I'm sure I've had some, but can't recall the details).
- In CreateHandle(), ensure the ClientSize is correct if it is set. If not, update it to make it right. Suspend layout while changing it so that child controls with anchors other than Top Left are not moved. This is important because forms are normally sized with ClientSize, and on X11 when they are initially created they are sized based on estimated borders (border sizes from Theme, caption height from XplatUIX11). Once they're created, the actual client size can be calculated, and from there the correct form size.
- When …
=> [Winforms] Form fixes

mcs/class/corlib/ReferenceSources/Buffer.cs, mcs/class/corlib/Test/System/BufferTest.cs
Use `memmove` in `Buffer.MemoryCopy` instead of `memcpy`.
Fixes: https://github.com/mono/mono/issues/18516
.NET Core also uses memmove there: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Buffer.cs#L127-L147
Mono-netcore works as expected.
=> Use memmove in Buffer.MemoryCopy

mono/mini/mini-posix.c
Only prevent `gdb` or `lldb` from being invoked.
MERP is controlled by separate mechanisms --- configure flags for crash
reporting and an explicit opt-in icall.
The existing code collects crashed process data in-process, but it writes the
data out (using mono_merp_invoke) in the forked child process.  This is a bit
surprising, but in the interest of not disturbing the code too much, this PR
doesn't change that.  We should revisit `dump_native_stacktrace` again in the
future and rationalize these decisions.
Addresses https://github.com/mono/mono/issues/18565
=> [merp] MONO_DEBUG=no-gdb-stacktrace shouldn't disable MERP

mcs/build/tests.make, mcs/class/corlib/corlib_xtest.dll.sources
Follow-up to https://github.com/mono/mono/pull/18228 since two parts wasn't enough to fix the size issue on 32bits devices.
We now use three parts.
Fixes https://github.com/mono/mono/issues/18614
Backport of #18619.
=> [2019-12] [corlib] Split corlib xunit tests even more for iOS

sdks/wasm/README.md, sdks/wasm/docs/getting-started/sample.md
Use -j with all example make invocations, mention Ninja dependency, mention raising ulimit, recommend py3 for running the server (when using py2, the port isn't properly released).
If the omission of -j was intentional I'll revert that part, but to the best of my knowledge there's no reason for that and people unfamiliar with make on multi-core machines will suffer extremely slow builds.
=> [wasm] README updates

mono/mini/debugger-agent.c, mono/mini/debugger-engine.c, mono/mini/debugger-engine.h, mono/mini/mini-wasm-debugger.c, sdks/wasm/Makefile
When stepping out of a c# breakpoint into the runtime (or JS... Not sure if that's accurate),
multiple single step requests can be created when the breakpoint is hit again.  In order to handle this scenario for wasm, we just cancel the existing one.
NOTE: The debugger args addition seemed a better way to handle this than outright canceling in debugger-engine. If there are implications in doing this, I can take it out.
Fixes https://github.com/mono/mono/issues/18558
=> [wasm][debugger] Cancel Existing Single Step Request When Creating New

mono/mini/mini-wasm-debugger.c, sdks/builds/wasm.mk
=> [mono] Prevent direct MonoClass field access

mono/mini/driver.c, mono/mini/mini-exceptions.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h
!! This PR is a copy of dotnet/runtime#2321,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This is not really a MONO_DEBUG option, but easier to implement it this way.
=> [jit] Add a 'top-runtime-invoke-unhandled' option to treat exceptions which reach the top invoke frame as unhandled when embedding.

mono/mini/method-to-ir.c
When calling a generic class we need to make sure it has been initilized. This is done by calling generic_class_init. Since the need to check if the method has been executed happens frequently, but will only run once, it should be put out of line, assisting branch predictor, preventing misspredictions (in all places but the first).
Currently this is not the case, since we will generate code like this:
```
0000000000000484: cmp         byte ptr [rcx+2Dh],0
0000000000000488: jne         000000000000048F
000000000000048A: call        p_3_plt_EmptyGame__jit_icall_mono_generic_class_init_llvm
000000000000048F: mov         rax,qword ptr [mono_aot_EmptyGame_llvm_got+0C8h]
```
Where we will always (except for first call) take the forward branch.
Instead we should mark the call to the method as …
=> Move generic_class_init out of line to assist branch prediction.

mono/mini/alias-analysis.c, mono/mini/decompose.c, mono/mini/memory-access.c, mono/mini/mini.h
The existing heuristic doesn't work with llvm.
=> [jit] Avoid generating wbarriers for vtype stores to the stack.

mono/mini/mini-posix.c
Only prevent `gdb` or `lldb` from being invoked.
MERP is controlled by separate mechanisms --- configure flags for crash
reporting and an explicit opt-in icall.
The existing code collects crashed process data in-process, but it writes the
data out (using mono_merp_invoke) in the forked child process.  This is a bit
surprising, but in the interest of not disturbing the code too much, this PR
doesn't change that.  We should revisit `dump_native_stacktrace` again in the
future and rationalize these decisions.
Addresses https://github.com/mono/mono/issues/18565
Backport of #18567.
=> [2019-12] [merp] MONO_DEBUG=no-gdb-stacktrace shouldn't disable MERP

sdks/wasm/Makefile
This PR renames other instances of `.stamp-build-debug-sample` to debug_sample/dotnet.js as done in #18644
=> [wasm] Clean up .stamp-build-debug-sample

mono/mini/branch-opts.c, mono/mini/iltests.il
=> Abort cmov optimization, when one of the out blocks is try block

mono/mini/llvm-jit.cpp
See https://github.com/mono/mono/issues/16243. This will allow elision of redundant bounds checks. This pass is already used during AOT (as part of opt -O2).
Here's `FirstOrDefault` (from #16243) with this change:
```
0000000000000000 <gram_FirstOrDefault__int___>:
<BB>:1
0:	31 c0                	xor    %eax,%eax
2:	48 85 ff             	test   %rdi,%rdi
5:	74 09                	je     10 <gram_FirstOrDefault__int___+0x10>
7:	83 7f 18 01          	cmpl   $0x1,0x18(%rdi)
b:	7e 03                	jle    10 <gram_FirstOrDefault__int___+0x10>
d:	8b 47 24             	mov    0x24(%rdi),%eax
10:	c3                   	retq   
***
```
=> [llvm] Enable jump threading with LLVM JIT.

configure.ac
The original fix back at #18554 did not work quite right, which was missed for lack of CI.
Reworked this check to instead test for `-mminimal-toc` on all powerpc hosts, and to only do the ELF version check on FreeBSD.
Fixes #18554 #18578 current CI build failures on AIX
=> Fix ppc64 build by fixing -mminimal-toc more correctly.

netcore/CoreFX.issues_interpreter.rsp
Fixed by https://github.com/mono/mono/commit/9ea350ed3c963c77f0f4f77ec590cc3c84773424
Fixes https://github.com/mono/mono/issues/18063
=> [tests] Reenable enum equals test on interpreter

man/mono.1, mono/mini/driver.c, mono/mini/interp/transform.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini.c
This work extends the `--stats` command to take in an optional method name. When a matching method is compiled or transformed, the stats will be printed out at that point in addition to after program execution. This is useful for products looking to measure startup time and activity, as well as for ourselves to track any loader performance regressions.
Once this lands, we should see about running it on a cadence, ideally on both desktop and Android. Additionally, more work needs to be done to the counters to expose them in a way more friendly to consumption on Android/wasm (including a callback). We should also update the website to document this additional behavior.
=> [mini] Add method-triggered printing for runtime stats

mono/mini/mini-generic-sharing.c
!! This PR is a copy of dotnet/runtime#31670,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/mono/mono/issues/18676.
=> [aot] Avoid inflating gparams with byreflike types during generic sharing.

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c
!! This PR is a copy of dotnet/runtime#31684,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/mono/mono/issues/18675.
=> [runtime] Fix the --enable-minimal=aot build.

mono/mini/interp/interp.c
When the interpreter does recurse, use a different function
for each call site, so you can tell from a WebAssembly stack
which case it is. i.e. with function names but no line numbers.
With this, we can see that call_varargs contributes to the problem
here: https://github.com/mono/mono/issues/18646
Also, do not inline the interpreter, it probably/hopefully never was.
=> [interp][wasm]Use per-call recursive functions in interpreter to aid debugging.

mono/mini/mini-posix.c
!! This PR is a copy of dotnet/runtime#2206,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
Related to root cause of https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1056907
Backport of #18590.
/cc @alexischr @monojenkins
=> [2019-10] [runtime] Disable lldb backtrace display on osx, it hangs on attaching in lldb.

mono/mini/interp/interp.c
[interp] Remove goto for code_type unknown | interp | compiled.
The goto kinda implies a loop, but it is really just handling one case
before the other, but the source misorders the checks, perhaps for perf,
which maybe, can be done equivalently with G_UNLIKELY, and also remove
some possible extra memory reads.
=> [interp] Remove goto for code_type unknown | interp | compiled.

mono/mini/mini-generic-sharing.c
!! This PR is a copy of dotnet/runtime#31670,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/mono/mono/issues/18676.
Backport of #18680.
=> [2019-12] [aot] Avoid inflating gparams with byreflike types during generic sharing.

sdks/wasm/Makefile
Add --profiling-funcs to release wasm build.
This is a weaker for of -g2 or -g3 or -g4 or --profiling.
It sounds like the weakest form that preserves names.
Documentation is around here: https://emscripten.org/docs/tools_reference/emcc.html#emcc-g1
Now when reproducing for example https://github.com/mono/mono/issues/18646, you get:
```
e.stack
<?>.wasm-function[generate_code]@[wasm code]
<?>.wasm-function[interp_inline_method]@[wasm code]
<?>.wasm-function[interp_transform_call]@[wasm code]
<?>.wasm-function[generate_code]@[wasm code]
<?>.wasm-function[interp_inline_method]@[wasm code]
<?>.wasm-function[interp_transform_call]@[wasm code]
<?>.wasm-function[generate_code]@[wasm code]
<?>.wasm-function[interp_inline_method]@[wasm code]
<?>.wasm-function[generate_code]@[wasm code] …
```
=> [wasm] Put function names in call stacks.

scripts/ci/util.sh
Use of `access_token` is now deprecated, switching to HTTP header
```
Please use the Authorization HTTP header instead, as using the `access_token`
query parameter is deprecated.
```
=> Update deprecated query parameter to header

mono/metadata/icall.c, mono/metadata/metadata.c
Calling a method compiled using full AOT from interpreter can lead to stack corruption if signature include a ValueTuple without fields on compilers where MONO_ZERO_LEN_ARRAY is not 0 (msvc, clang). This is due to doing memset on memory allocated using MONO_SIZEOF_GENERIC_INST but
then memset using sizeof (MonoGenericInst). Fix makes sure we allocate and memset the same size of memory since otherwise it will lead to an overwrite of allocated memory when type_argc is 0.
The repro is a little tricky since the called method needs to be in a full AOT assembly and then called from an interpreted assembly:
If this is included in a full AOT:ed assembly.
```
public class StackOverwrite
{
static public ValueTuple trashStack()
{
return ValueTuple.Create(); …
```
=> [interp] Stack corruption running full AOT interpreter using ValueTuple.

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c
[interp] Remove recursion from call_vararg.
This contributes to https://github.com/mono/mono/issues/18646 but is not enough to fix it. The interpreter still recurses a lot.
=> [interp] Make call_vararg non-recursive.

configure.ac, mono/metadata/icall.c, mono/mini/exceptions-amd64.c, mono/mini/exceptions-ppc.c, mono/mini/exceptions-x86.c, mono/mini/mini-posix.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini-windows.c, mono/utils/Makefile.am, mono/utils/mono-merp.c, mono/utils/mono-signal-handler.c, mono/utils/mono-signal-handler.h, msvc/libmonoutils-common.targets, msvc/libmonoutils-common.targets.filters
The default handlers for SIGTRAP, SIGSYS on macOS and Linux crash the process, so we now have Mono report this.
This change also changes the presentation of the signal name on the stacktrace report dumped on error (from e.g. "SIGSEGV" to "segv").
=> [runtime] Report crash when receiving crashing signals

sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs
By not checking and throwing if the state is already disposed.
See comments https://github.com/mono/mono/issues/18628#issuecomment-580570718 https://github.com/mono/mono/issues/18628#issuecomment-580625819
Since @lewing [mentioned another way to fix it](https://github.com/mono/mono/issues/18628#issuecomment-580555408) feel free to close this PR in favor of the proper fix.
Fixes #18628 
---
How I tested it:
- Create blazor wasm app and restore dependencies
- Build `mono/sdks/wasm/framework/src/WebAssembly.Framework.sln`
- Copy DLLs from `mono/sdks/wasm/framework/netstandard2.0` into `C:\Users\[user]\.nuget\packages\microsoft.aspnetcore.blazor.mono\[version]\tools\mono\framework`
- Rebuild blazor wasm app
=> [wasm] Close WebSocket on Dispose (#18628)

sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs, sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs, sdks/wasm/ProxyDriver/Program.cs, sdks/wasm/ProxyDriver/Startup.cs, sdks/wasm/src/library_mono.js
Extract commands as an actual object and use it to reduce duplicated code.
Reduce silence more logging by default and start reducing Newtonsoft.Json usage
=> [wasm][debugger] Process arguments in the command where they are used

sdks/builds/ios.mk, tools/offsets-tool-py/Makefile
Apple removed -t switch from dsymutil in favor of -num-threads and replaced pip clang with the newer version so it can be used with the new version of clang included in the new Xcode
=> [2019-08] Add fixes needed by new version of Xcode 

msvc/libmono.bat
Current script, libmono.bat, copied all metadata headers into include folder. This folder is used up by some other distribution as include folder. Fix makes sure we copy the same number of header files as we do in our make files scripts.
=> Reduce number of mono header files copied into SDK include folder (MSVC build).

mcs/class/corlib/System/Environment.cs
Fixes #18652 
```
Mitchells-iMac:mono mdhwang$ ls -al ~/.config/user-dirs.dirs
----------  1 mdhwang  staff  0 Feb  3 11:52 /Users/mdhwang/.config/user-dirs.dirs
Mitchells-iMac:mono mdhwang$ mcs Hello.cs && mono Hello.exe
GetFolderPath: /Users/mdhwang/Templates
```
=> [corlib] Silence undocumented exceptions in ReadXdgUserDir

mono/mini/driver.c, mono/mini/mini-runtime.h
!! This PR is a copy of dotnet/runtime#31683,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>What this means is:
1. --debug is no longer needed since the default is TRUE
2. --debug=ignore is a new switch to go back to the old mono default
Fixes https://github.com/dotnet/runtime/issues/31662
=> [mono] Enable debugging for netcore configurations by default.

sdks/builds/ios.mk
Apple removed `-t` switch from dsymutil in favor of `-num-threads`
=> [iOS] Replace removed dsymutil `-t` switch with `-num-threads`

sdks/builds/ios.mk
Apple removed `-t` switch from dsymutil in favor of `-num-threads`
Backport of #18741.
/cc @lambdageek @dalexsoto
=> [2019-10] [iOS] Replace removed dsymutil `-t` switch with `-num-threads`

sdks/builds/ios.mk
Apple removed `-t` switch from dsymutil in favor of `-num-threads`
Backport of #18741.
/cc @lambdageek @dalexsoto
=> [2019-12] [iOS] Replace removed dsymutil `-t` switch with `-num-threads`

sdks/builds/ios.mk
Apple removed `-t` switch from dsymutil in favor of `-num-threads`
Backport of #18741.
/cc @lambdageek @dalexsoto
=> [2020-02] [iOS] Replace removed dsymutil `-t` switch with `-num-threads`

packaging/MacSDK/packaging/resources/postinstall
This is helpful for issues such as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/596552 OC, where the user is asked to both provide these logs for debugging, and also reinstall the SDK to resolve the issue
=> [MacSDK] Keep logged post-install script output from previous installs

mono/metadata/domain-internals.h, mono/metadata/domain.c, mono/metadata/object.c
!! This PR is a copy of dotnet/runtime#31814,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When locating AppContext.BaseDirectory on netcore, if APP_CONTEXT_BASE_DIRECTORY is not set we call into the runtime for a fallback location, which checks domain->entry_assembly. On legacy this is fine because we set that property in `prepare_thread_to_exec_main`, but on netcore the new managed assembly loading algorithm will call into managed and check the property before that function is run, which will result in AppContext.BaseDirectory returning an empty string. The solution is to set entry_assembly a bit earlier in initialization. This is the appropriate location because it's what embedding API users will call to run …
=> [loader] Set domain->entry_assembly earlier in startup

configure.ac, tools/offsets-tool-py/offsets-tool.py
Some notes on usage:
```console
$ sudo apt install g{++,cc}-gnu-linux-gnueabihf python3-pip
$ ./autogen.sh --disable-boehm --target=arm-linux-gnueabihf \
--with-cross-offsets=arm-linux-gnueabihf-cross-offsets.h \
--with-core=only \
CFLAGS="-O0 -ggdb3 -fno-omit-frame-pointer" \
CXXFLAGS="-O0 -ggdb3 -fno-omit-frame-pointer"
$ make -C tools/offsets-tool-py/
$ python3 tools/offsets-tool-py/offsets-tool.py \
--targetdir=/home/lewurm/work/mono \
--abi=arm-linux-gnueabihf \
--monodir=/home/lewurm/work/mono \
--outfile=arm-linux-gnueabihf-cross-offsets.h \
--libclang=/usr/lib/x86_64-linux-gnu/libclang-7.so.1 \
--sysroot=/usr/arm-linux-gnueabihf \
--netcore
```
=> [cross] support arm-linux-gnueabihf cross compiling with netcore

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c
When a requested frame size doesn't fit in an already allocated stack fragment, we instead allocate another, larger fragment.
When doing this we missed to free the existing stack fragment, and in combination with a second problem (`current->next` not being cleared when unused) it can accumulate to a lot of unused stack fragments and in worst-case to OOM, as it happened on Linux corlib xunit tests.
Thanks to Jay for tracking it down.
=> [interp] reclaim stack fragments when not used.

mono/mini/driver.c, mono/mini/mini-runtime.h
See if this fixes the weird bug-10127.exe test failure that only occurs on Windows C++ builds.
=> [mini] Wrap check for debug info enabled in ENABLE_NETCORE in all places

mono/utils/checked-build.c
!! This PR is a copy of dotnet/runtime#32138,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>At least on my machine, this is the only warning we have when building netcore in the default configuration.
=> [utils] Add unused attribute to fix warning in checked-build.c

mcs/class/System.Net.Http/HttpClientHandler.SocketsHandler.Android.cs, mcs/class/System.Net.Http/System.Net.Http.csproj, mcs/class/System.Net.Http/System.Net.Http/HttpClient.android.cs, mcs/class/System.Net.Http/UnitTests/HttpClientHandlerTests.Android.cs, mcs/class/System.Net.Http/UnitTests/monodroid_System.Net.Http.UnitTests_xtest.dll.sources, mcs/class/System.Net.Http/monodroid_System.Net.Http.dll.exclude.sources, mcs/class/System.Net.Http/monodroid_System.Net.Http.dll.sources
Currently Android has two HttpHandler options: **Managed** (which is based on modern fully managed `SocketHttpHandler` from corefx) and **Android**. Unfortunately it turned out in order to support NTLM/Kerberos authentication, `SocketHttpHandler` needs some native pieces (GSS) we don't have for Android (basically we need to port [krb5](https://github.com/krb5/krb5) lib to Android NDK) - other platforms including iOS are fine.
However, our old legacy `MonoWebRequestHandler` (we still have it in System.Net.Http) used to fully support NTLM. So the idea is to bring it back and allow users to select it via VS
There are two scenarios we must support:
**1)**
```csharp
var httpClient = new HttpClient();
```
**2)** 
```csharp
var httpHandler = new HttpHandler { Credentials = ... };
var httpClient …
```
=> [2019-10] Allow users to switch to MonoWebRequestHandler on Android via UI

mcs/class/System.Net.Http/HttpClientHandler.SocketsHandler.Android.cs, mcs/class/System.Net.Http/System.Net.Http.csproj, mcs/class/System.Net.Http/System.Net.Http/HttpClient.android.cs, mcs/class/System.Net.Http/UnitTests/HttpClientHandlerTests.Android.cs, mcs/class/System.Net.Http/UnitTests/monodroid_System.Net.Http.UnitTests_xtest.dll.sources, mcs/class/System.Net.Http/monodroid_System.Net.Http.dll.exclude.sources, mcs/class/System.Net.Http/monodroid_System.Net.Http.dll.sources
Currently Android has two HttpHandler options: **Managed** (which is based on modern fully managed `SocketHttpHandler` from corefx) and **Android**. Unfortunately it turned out in order to support NTLM/Kerberos authentication, `SocketHttpHandler` needs some native pieces (GSS) we don't have for Android (basically we need to port [krb5](https://github.com/krb5/krb5) lib to Android NDK) - other platforms including iOS are fine.
However, our old legacy `MonoWebRequestHandler` (we still have it in System.Net.Http) used to fully support NTLM. So the idea is to bring it back and allow users to select it via VS
There are two scenarios we must support:
**1)**
```csharp
var httpClient = new HttpClient();
```
**2)** 
```csharp
var httpHandler = new HttpHandler { Credentials = ... };
var httpClient …
```
=> [2019-12] Allow users to switch to MonoWebRequestHandler on Android via UI

mcs/class/System.Net.Http/HttpClientHandler.SocketsHandler.Android.cs, mcs/class/System.Net.Http/System.Net.Http.csproj, mcs/class/System.Net.Http/System.Net.Http/HttpClient.android.cs, mcs/class/System.Net.Http/UnitTests/HttpClientHandlerTests.Android.cs, mcs/class/System.Net.Http/UnitTests/monodroid_System.Net.Http.UnitTests_xtest.dll.sources, mcs/class/System.Net.Http/monodroid_System.Net.Http.dll.exclude.sources, mcs/class/System.Net.Http/monodroid_System.Net.Http.dll.sources
Currently Android has two HttpHandler options: **Managed** (which is based on modern fully managed `SocketHttpHandler` from corefx) and **Android**. Unfortunately it turned out in order to support NTLM/Kerberos authentication, `SocketHttpHandler` needs some native pieces (GSS) we don't have for Android (basically we need to port [krb5](https://github.com/krb5/krb5) lib to Android NDK) - other platforms including iOS are fine.
However, our old legacy `MonoWebRequestHandler` (we still have it in System.Net.Http) used to fully support NTLM. So the idea is to bring it back and allow users to select it via VS
There are two scenarios we must support:
**1)**
```csharp
var httpClient = new HttpClient();
```
**2)** 
```csharp
var httpHandler = new HttpHandler { Credentials = ... };
var httpClient …
```
=> [2020-02] Allow users to switch to MonoWebRequestHandler on Android via UI

mcs/class/System.Net.Http/HttpClientHandler.SocketsHandler.Android.cs, mcs/class/System.Net.Http/System.Net.Http.csproj, mcs/class/System.Net.Http/System.Net.Http/HttpClient.android.cs, mcs/class/System.Net.Http/UnitTests/HttpClientHandlerTests.Android.cs, mcs/class/System.Net.Http/UnitTests/monodroid_System.Net.Http.UnitTests_xtest.dll.sources, mcs/class/System.Net.Http/monodroid_System.Net.Http.dll.exclude.sources, mcs/class/System.Net.Http/monodroid_System.Net.Http.dll.sources
Currently Android has two HttpHandler options: **Managed** (which is based on modern fully managed `SocketHttpHandler` from corefx) and **Android**. Unfortunately it turned out in order to support NTLM/Kerberos authentication, `SocketHttpHandler` needs some native pieces (GSS) we don't have for Android (basically we need to port [krb5](https://github.com/krb5/krb5) lib to Android NDK) - other platforms including iOS are fine.
However, our old legacy `MonoWebRequestHandler` (we still have it in System.Net.Http) used to fully support NTLM. So the idea is to bring it back and allow users to select it via VS
There are two scenarios we must support:
**1)**
```csharp
var httpClient = new HttpClient();
```
**2)** 
```csharp
var httpHandler = new HttpHandler { Credentials = ... };
var httpClient …
```
=> Allow users to switch to MonoWebRequestHandler on Android via UI

sdks/wasm/Makefile, sdks/wasm/docs/WASM-REQUESTS.md
Chakra is no longer getting updated and we don't use XS.
=> [wasm] Remove chakra and xs from the jsvu update list.

scripts/mono-package-runtime
This mostly resolves the worst parts of https://github.com/mono/mono/issues/16991 (but does not deal with the issues in mkbundle itself when it comes to tracking native dependencies automatically).
Using a temporary directory rather than "more correct" use of a temporary file w/ rename, because `zipnote` on macOS is broken and cannot do renames.
=> Fix native mkbundle

mono/metadata/icall-decl.h, mono/metadata/icall-def-netcore.h, mono/metadata/threads.c, mono/utils/Makefile.am, mono/utils/lifo-semaphore.c, mono/utils/lifo-semaphore.h, msvc/libmonoutils-common.targets, msvc/libmonoutils-common.targets.filters
!! This PR is a copy of dotnet/runtime#2098,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This change is motivated on two main fronts. The first is maintainability - the current managed implementation is difficult to understand and I worry diagnosing any potential issues would be a massive time sink. The second is performance - the current implementation appears to suffer from significant lock contention when running the TechEmpower plaintext benchmark. My hope is that the simpler, cleaner native implementation here will avoid both problems, but I don't want to merge it until we have benchmarking data. However, even if the numbers are similar, I still think it's worth merging just from a maintainability …
=> [threading] Switch to a native implementation of LowLevelLifoSemaphore

sdks/wasm/packager.cs
Reverts mono/mono#18775
Revert this as it causes build failures when code references nonexistent pinvokes.
=> Revert "[wasm] Pass direct-pinvoke to the AOT compiler."

configure.ac, mono/mini/Makefile.am.in, mono/profiler/Makefile.am
!! This PR is a copy of dotnet/runtime#32181,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Traditionally, Mono is build with native compilers (i.e. "build for this architecture" running in an ARM or ARM64 chroot on an ARM64 server), but to align with CoreCLR, let's go the cross-compile way.
This enables cross-compiler support, by passing a whole bunch of extra info to `./configure`, some of which is set in the common YAML (like the `--sysroot` value)
=> Enable Mono ARM & ARM64 Linux builds

mono/mini/interp/interp.c, mono/mini/interp/transform.c
Make newobj_fast not recursive.
This contributes significantly to https://github.com/mono/mono/issues/18646,
and against master might even fix it.
Much recursion remains in the interpreter/transform.
This also cleans up redundant code, i.e. method_entry,
and places EXCEPTION_CHECKPOINT more correctly,
i.e. when transform occurs but does not return an exception.
EXCEPTION_CHECKPOINT fix is necessary so that non-recursive newobj_fast does not break one test.
One more item, could be separate PR:
Making call_vararg added the following to all calls:
storing is_void in a larger scoped local
save is_void
restore is_void
check is_void, along with preexisting check of retval == null
Because retval must be set even for void call_varargs, because the arglist is found from it.
This removes the check …
=> [interp][wasm] Make newobj_fast not recursive, cleanup, fix EXCEPTION_CHECKPOINT.

mcs/class/System.Drawing/System.Drawing/Graphics.cs, mcs/class/System.Drawing/Test/System.Drawing/TestGraphics.cs
The gdiplus.dll on Windows will fail when attempting to delete a
Graphics object that has an unreleased HDC. This allows Dispose
to succeed in that case.
This more closely resembles the behavior of corefx.
=> [System.Drawing] Release the Graphics HDC on Dispose.

mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
Fixes tests from System.Linq.Expressions suite
=> [interp] Add missing conversion opcodes from r4

mono/mini/interp/transform.c
Storing uninitialized locals in a managed object shouldn't crash the runtime, so they should be zeroed. This doesn't seem to regress performance on wasm since the initlocals flag is always set, currently. We should be able to remove it most of the time, once we add some multi basic block support to the cprop phase. This will enable us to further reduce call overhead.
Fixes https://github.com/mono/mono/issues/18527
=> [interp] Always init locals

configure.ac, mono/tests/Makefile.am
It hangs: https://github.com/mono/mono/issues/18827
=> [tests] Disable bug-10127.exe runtime test on Windows x64 C++

mono/mini/CMakeLists.txt, mono/mini/Makefile.am.in, mono/mini/main-core.c, mono/mini/monovm.c, mono/mini/monovm.h, msvc/libmini-common.targets, msvc/libmini-common.targets.filters
!! This PR is a copy of dotnet/runtime#32136,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Made minor fixes to the preload hook in the process.
The runtime will still crash if you don't specify the TPA paths and include corlib in that list, but it will at least hit an assert that makes clear it can't find corlib instead of attempting to dereference a null pointer in the preload hook.
The monovm header functions are exported for testing purposes, but the file is intentionally not made public as of now.
=> [mini] Move netcore hosting functionality into separate file

mono/metadata/debug-mono-ppdb.c
We are investigating to turn on PPDB everywhere, but for now, WASM is already working using it.
=> [debugger] Enabling embedded PPDB on Wasm.

sdks/android/Makefile, sdks/android/app/src/main/c/runtime-bootstrap.c, sdks/builds/android.mk, sdks/builds/runtime.mk
The Xamarin.Android team prefers that we ship two different `libmonosgen-2.0.so` for each target, e.g. for arm64 we will have with this PR:
* `./sdks/out/android-arm64-v8a-release/lib/libmonosgen-2.0.so`
* `./sdks/out/android-interpreter-arm64-v8a-release/lib/libmonosgen-2.0.so`
As the names indicate one has the interpreter enabled.
This is contrary to what we do for Xamarin.iOS. There, `--enable-minimal=interpreter` has the side-effect that the build will produce a `libmono-ee-interp.dylib` that can be linked next to `libmonosgen-2.0.dylib`. We _could_ do the same for Android, but that would require us to
* Add `--disable-visibility-hidden` to the Android Mono runtime builds. There are concerns however that this will slow down `dlopen (libmonosgen-2.0.so)` on the Xamarin.Android side.
* …
=> [sdks] add anroid-interpreter-{arm64-v8a,armeabi-v7a,x86,x86_64} targets

mcs/class/System.Net.Http/HttpClientHandler.SocketsHandler.Android.cs, mcs/class/System.Net.Http/MonoWebRequestHandler.cs, mcs/class/System.Net.Http/System.Net.Http/HttpClient.android.cs
Create it using reflection so it will be always linked out. However if it's set via `XA_HTTP_CLIENT_HANDLER_TYPE` linker will preserve it in a special substep: https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/PreserveHttpAndroidClientHandler.cs#L72-L80
I had to make its ctor **public** because Linker instantiate it via `Activator.CreateInstance(string)` ([here](https://github.com/xamarin/xamarin-android/blob/60363ef45cd6994a322adac1b73d4271b0658c1e/src/Mono.Android/Android.Runtime/AndroidEnvironment.cs#L369)). But the whole type remains internal so it's not a real API change.
Fixes issue from https://github.com/mono/mono/pull/18818#issuecomment-585611647
=> Make MonoWebRequestHandler linker friendly

mono/tests/coreclr-security.cs
!! This PR is a copy of dotnet/runtime#32273,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes MSDN blogs links throughout our docs and source code comments that were broken during the great MSDN migration of 2019.
Note: I am changing the contents of the _davbr Blog Archives_ folder by fixing the broken links. If we need to keep these files exactly as they were when they were copied from the blog, I can revert.
=> Fix broken MSDN blogs links

mono/metadata/jit-icall-reg.h, mono/mini/aot-runtime.h, mono/mini/llvmonly-runtime.c, mono/mini/llvmonly-runtime.h, mono/mini/mini-llvm.c, mono/mini/mini-runtime.c
Emit a stub for methods which failed llvm compilation. Currently the stub will
throw a MissingMethodException, later it can fall back to the interpreter etc.
This is required for cross-assembly direct calls, since the caller doesn't
know that the callee has failed llvm compilation leading to missing
symbols during linking.
=> [llvmonly] Emit stubs for methods which failed compilation.

mono/mini/interp/interp.c
When executing a filter we create a new interp frame, that is a duplicate of the original frame that contains the filter. Once the execution of the filter is finished, we were copying the stack contents back to the base frame. The problem with this is that when the filter is run, the stack is not completely unwinded, meaning that later we can still run a finally block in a frame called by the base frame. This finally block can access the stack arguments, which would reside on the stack of base frame. This means that we must not override the stack of the base frame, only the locals.
Fixes some tests from System.Linq.Expressions suite.
=> [interp] Fix filter clauses

mono/metadata/domain-internals.h, mono/mini/llvm-jit.cpp, mono/mini/llvm-jit.h, mono/mini/mini-llvm-loaded.c, mono/mini/mini-llvm.c, mono/mini/mini-llvm.h, mono/mini/mini-runtime.c
We currently reuse LLVM's command line parsing system to configure and
enable passes. When using the default code generator pass configuration,
the `ImplicitNullChecks` and `X86CallFrameOptimization` passes can only
be enabled or disabled via the command line argument parser: the
`cl::opt`s controlling these (and many other) passes are private to
their translation units, and `TargetPassConfig`/`X86PassConfig` read
from these `cl::opt`s with no other means to override these values.
Unfortunately, some LLVM command line options have restrictions on the
number of times they may be set, and running the LLVM command line
argument parser more than once can fail, because the 'number of
occurrences' counter is stored in each global `cl::opt`. This causes
several tests to fail--one such test is …
=> [llvm] Fix LLVM JIT when used with multiple AppDomains.

msvc/mono.props
!! This PR is a copy of dotnet/runtime#32130,  please do not edit or review it in this repo !!<br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes
```
fatal error C1083: Cannot open include file: '../../support/libm/complex.c': No such file or directory
```
when `mono-netcore.sln` is opened in vs2019
=> [mono] Fix msvc mono build

mono/mini/interp/interp.c
https://github.com/mono/mono/pull/18825 was deemed too large and requested to be split up.
This is one of the required pieces.
To consolidate the multiple nonrecursive call sites requires they share the same retval variable. Go ahead and share them all.
=> [interp] Step toward consolidating nonrecursive call sites (retval).

mono/mini/interp/interp.c
[interp] Use method_entry at interp entry instead of duplicating the code.
`tracing` was a mix of:
- sometimes ifdef out, sometimes not; make it always ifdefed
- sometimes `int`, sometimes `gint`, sometimes `gboolean`; make it always `int`
Much of this PR will end up deleted when the multiple nonrecursive calls are
consolidated, but two will remain -- entry and call: label.
https://github.com/mono/mono/pull/18825 is where this is going but it was deemed
too large and requested to be split up. This is part of it.
=> [interp] Use method_entry at interp entry instead of duplicating the code.

mono/metadata/sre.c, mono/mini/linear-scan.c, mono/mini/method-to-ir.c, mono/mini/mini-runtime.h, mono/mini/mini.c, mono/mini/type-checking.c, mono/utils/dtrace.h
mini\mini.c(1253,59): warning C4390:  ';': empty controlled statement found; is this the intent?
mini\mini.c(3100,43): warning C4390:  ';': empty controlled statement found; is this the intent?
mini\mini.c(3273,49): warning C4390:  ';': empty controlled statement found; is this the intent?
mini\mini.c(3281,49): warning C4390:  ';': empty controlled statement found; is this the intent?
mini\mini.c(3480,51): warning C4390:  ';': empty controlled statement found; is this the intent?
mini\mini.c(3490,49): warning C4390:  ';': empty controlled statement found; is this the intent?
mini\mini.c(3626,48): warning C4390:  ';': empty controlled statement found; is this the intent?
mini\mini.c(3664,48): warning C4390:  ';': empty controlled statement found; is this the intent?
mini\mini.c(3722,48): …
=> Fix/quash some warnings.

winconfig.h
#undef never needs an ifdef guard, it works unconditionally without warning.
=> Remove unnecessary ifdef before undef.

mono/metadata/abi-details.h, mono/metadata/object-internals.h, mono/metadata/object-offsets.h
I think the fallback was added because "let's get it back to work quickly", back in the dark times without CI: https://github.com/mono/mono/commit/b655fb35c61fd3422003de01eed8e634d46b4186
=> [abi-details] add explaining comment for macro magic

mono/metadata/metadata-cross-helpers.c, mono/mini/mini-cross-helpers.c
It's essentially dead code in any of our configurations.
`MONO_ALIGN_gint8` is define here:
https://github.com/mono/mono/blob/ab2321c1dc1bf0293dadd7e52436b2bd87f2b7c3/mono/metadata/abi-details.h#L26-L35
And the correct value is set here:
https://github.com/mono/mono/blob/ab2321c1dc1bf0293dadd7e52436b2bd87f2b7c3/mono/metadata/abi.c#L71-L75
=> [cross] check against correct alignment value

mono/mini/llvm-jit.cpp, mono/tests/Makefile.am, mono/tests/bug-gh-17285.cs
Fixes https://github.com/mono/mono/issues/17285.
For calls that require parameters passed in stack memory,
X86CallFrameOptimization can sometimes replace a sequence of movs to
prologue-reserved stack memory with a sequence of pushes and a compensating sub
rsp after the call. LLVM accumulates an OpAdjustCfaOffset MCCFIInstruction for
each push and and records the ephemeral parameter space consumed by the call
using an OpGnuArgsSize MCCFIInstruction (i.e. DW_CFA_GNU_args_size).
MonoException doesn't support encoding OpGnuArgsSize MCCFIInstructions, and
attempting to encode this instruction can cause unpredictable behavior, due to
our use of llvm_unreachable with assertions disabled [1]. Moreover, even if
MonoException happens to emit valid call frame instructions despite the UB
induced by …
=> [llvm] Disable X86 call frame size optimization.

sdks/android/Makefile, sdks/android/app/src/main/c/runtime-bootstrap.c, sdks/builds/android.mk, sdks/builds/runtime.mk
The Xamarin.Android team prefers that we ship two different `libmonosgen-2.0.so` for each target, e.g. for arm64 we will have with this PR:
* `./sdks/out/android-arm64-v8a-release/lib/libmonosgen-2.0.so`
* `./sdks/out/android-interpreter-arm64-v8a-release/lib/libmonosgen-2.0.so`
As the names indicate one has the interpreter enabled.
This is contrary to what we do for Xamarin.iOS. There, `--enable-minimal=interpreter` has the side-effect that the build will produce a `libmono-ee-interp.dylib` that can be linked next to `libmonosgen-2.0.dylib`. We _could_ do the same for Android, but that would require us to
* Add `--disable-visibility-hidden` to the Android Mono runtime builds. There are concerns however that this will slow down `dlopen (libmonosgen-2.0.so)` on the Xamarin.Android side.
* …
=> [2020-02] [sdks] add anroid-interpreter-{arm64-v8a,armeabi-v7a,x86,x86_64} targets

mcs/tools/wasm-tuner/tuner.cs, sdks/wasm/packager.cs
The linker can completely link away some assemblies, but the rest of the ninja
build still requires them. Previously they were generated by running csc, but
thats too slow, so generate them using Cecil from wasm-tuner.
=> [wasm] Implement generation of empty assemblies in wasm-tuner.

mono/mini/mini-native-types.c
This wastes about 24 static const bytes which I think is ok.
6 bytes per struct plus 2 padding, and there are 3 of them, total, ever, passed by pointer.
I was looking into https://github.com/mono/mono/issues/18827
and wanting to rule out #if __cplusplus.
=> Remove #if __cplusplus from MagicTypeInfo.

mcs/class/System.Net.Http/System.Net.Http_test.dll.sources, mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientHandlerTests.Android.cs, mcs/class/System.Net.Http/UnitTests/monodroid_System.Net.Http.UnitTests_xtest.dll.sources
The xunit tests we have for this lib use "fake" `HttpClientHandler` (and the test expects the real one), see https://github.com/mono/corefx/blob/master/src/System.Net.Http/tests/UnitTests/Fakes/HttpClientHandler.cs
Backport of #18883.
/cc @EgorBo
=> [2019-10] Move TestEnvVarSwitchForInnerHttpHandler to nunit (from xunit)
