- mcs/class/System.Net.Http/System.Net.Http_test.dll.sources
- mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientHandlerTests.Android.cs
- mcs/class/System.Net.Http/UnitTests/monodroid_System.Net.Http.UnitTests_xtest.dll.sources
The xunit tests we have for this lib use "fake" `HttpClientHandler` (and the test expects the real one), see https://github.com/mono/corefx/blob/master/src/System.Net.Http/tests/UnitTests/Fakes/HttpClientHandler.cs
Backport of #18883.
/cc @EgorBo
> [2019-12] Move TestEnvVarSwitchForInnerHttpHandler to nunit (from xunit)

- mcs/class/System.Net.Http/System.Net.Http_test.dll.sources
- mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientHandlerTests.Android.cs
- mcs/class/System.Net.Http/UnitTests/monodroid_System.Net.Http.UnitTests_xtest.dll.sources
The xunit tests we have for this lib use "fake" `HttpClientHandler` (and the test expects the real one), see https://github.com/mono/corefx/blob/master/src/System.Net.Http/tests/UnitTests/Fakes/HttpClientHandler.cs
Backport of #18883.
/cc @EgorBo
> [2020-02] Move TestEnvVarSwitchForInnerHttpHandler to nunit (from xunit)

- mcs/class/System.Net.Http/HttpClientHandler.SocketsHandler.Android.cs
- mcs/class/System.Net.Http/MonoWebRequestHandler.cs
- mcs/class/System.Net.Http/System.Net.Http/HttpClient.android.cs
Create it using reflection so it will be always linked out. However if it's set via `XA_HTTP_CLIENT_HANDLER_TYPE` linker will preserve it in a special substep: https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/PreserveHttpAndroidClientHandler.cs#L72-L80
I had to make its ctor **public** because Linker instantiate it via `Activator.CreateInstance(string)` ([here](https://github.com/xamarin/xamarin-android/blob/60363ef45cd6994a322adac1b73d4271b0658c1e/src/Mono.Android/Android.Runtime/AndroidEnvironment.cs#L369)). But the whole type remains internal so it's not a real API change.
Fixes issue from https://github.com/mono/mono/pull/18818#issuecomment-585611647
Backport of #18832.
/cc @EgorBo
> [2020-02] Make MonoWebRequestHandler linker friendly

- mcs/class/System.Net.Http/HttpClientHandler.SocketsHandler.Android.cs
- mcs/class/System.Net.Http/MonoWebRequestHandler.cs
- mcs/class/System.Net.Http/System.Net.Http/HttpClient.android.cs
Create it using reflection so it will be always linked out. However if it's set via `XA_HTTP_CLIENT_HANDLER_TYPE` linker will preserve it in a special substep: https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/PreserveHttpAndroidClientHandler.cs#L72-L80
I had to make its ctor **public** because Linker instantiate it via `Activator.CreateInstance(string)` ([here](https://github.com/xamarin/xamarin-android/blob/60363ef45cd6994a322adac1b73d4271b0658c1e/src/Mono.Android/Android.Runtime/AndroidEnvironment.cs#L369)). But the whole type remains internal so it's not a real API change.
Fixes issue from https://github.com/mono/mono/pull/18818#issuecomment-585611647
Backport of #18832.
/cc @EgorBo
> [2019-10] Make MonoWebRequestHandler linker friendly

- mcs/class/System.Net.Http/HttpClientHandler.SocketsHandler.Android.cs
- mcs/class/System.Net.Http/MonoWebRequestHandler.cs
- mcs/class/System.Net.Http/System.Net.Http/HttpClient.android.cs
Create it using reflection so it will be always linked out. However if it's set via `XA_HTTP_CLIENT_HANDLER_TYPE` linker will preserve it in a special substep: https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/PreserveHttpAndroidClientHandler.cs#L72-L80
I had to make its ctor **public** because Linker instantiate it via `Activator.CreateInstance(string)` ([here](https://github.com/xamarin/xamarin-android/blob/60363ef45cd6994a322adac1b73d4271b0658c1e/src/Mono.Android/Android.Runtime/AndroidEnvironment.cs#L369)). But the whole type remains internal so it's not a real API change.
Fixes issue from https://github.com/mono/mono/pull/18818#issuecomment-585611647
Backport of #18832.
/cc @EgorBo
> [2019-12] Make MonoWebRequestHandler linker friendly

- netcore/CoreFX.issues_interpreter.rsp
See https://github.com/mono/mono/issues/18695, it's most likely fixed in dotnet/runtime already but we can't easily get updated binaries into mono/mono.
> [netcore] Disable flaky BasicTest_AccessInstanceProperties_NoExceptions_Linux test on interpreter

- mono/mini/ee.h
- mono/mini/interp-stubs.c
- mono/mini/interp/interp.c
- mono/mini/mini-exceptions.c
- netcore/CoreFX.issues_interpreter.rsp
when throwing non exception objects.
Enable the entire System.Linq.Expressions suite with interpreter
> [interp] Unwrap RuntimeWrappedException if needed

- mono/metadata/icall.c
- mono/tests/merp-crash-test.cs
- mono/utils/mono-state.c
- mono/utils/mono-state.h
If the process calls `System.Environment.FailFast (message, exception)` we should capture the message in the crash report log.
> [merp] Capture Environment.FailFast message in crash report

- mono/mini/mini-posix.c
See https://github.com/mono/mono/pull/18243#issuecomment-586013427
> [mono] Remove SIGTRAP handler, as it interferes with debugging

- mono/mini/interp/interp.c
- mono/mini/interp/transform.c
[interp] Make newobj_vtst_fast and newobj_vt_fast not recursive.
This is builds upon https://github.com/mono/mono/pull/18875 which was newobj_vt_fast-only.
That was preceded by https://github.com/mono/mono/pull/18870 which did not handle the stack/GC perhaps as well.
Some notes:
- This is a little gnarly in its stack manipulation in transform.c and interp.c. Please review carefully.
- This is *not* known to contribute to WebAssembly/Blazor failures (which are suspected fixed via earlier fixes already). Leaving it alone is an option. Not my favorate, but I understand.
- There are expected to be improvements on the Apple side as well, further strengthening the previous point. Still not my preference, but again I understand.
> [interp] Make newobj_vt[st]_fast non-recursive.

- mono/metadata/opcodes.h
- mono/mini/mini-native-types.c
- mono/mini/mini-runtime.h
- mono/utils/mono-logger-internals.h
- mono/utils/mono-publib.h
Make MONO_API_DATA clearer, its old form -- MONO_API extern.
extern "C" { } should be added around it not within it, for clarity.
I've always found extern "C" without braces unclear, esp. for data.
i.e.
```
extern "C" {
1   extern void function(); // redundant but clear
// same as void function();
2   extern int data; // not redundant, and clear
}
```
vs.
```
3   extern "C" void function(); // I guess clear.
4   extern "C" int data; // unclear -- is it extern or extern "C" or both?
```
This PR in particular turns 4 into 2.
2 is clearly a declaration, not a definition.
4 is unclear as to if it is a declaration or definition.
I was looking into https://github.com/mono/mono/issues/18827.
This does not actually change anything but makes things clearer.
This is similar/related in spirit to …
> Make MONO_API_DATA clearer.

- mono/utils/mono-tls-inline.h
The code is fine, and we should put it back at some point,
but I want things to be clearer regarding https://github.com/mono/mono/issues/18827.
i.e. That this does not cause it.
I don't know what does cause it, granted.
Maybe a preexisting race condition/deadlock, I don't know.
Repro is run a loop like:
```
type \s\1.cmd
for /l %%a in (1 1 999) do echo %%a && C:\s\mono2\msvc\build\sgen\x64\bin\Release\mono-sgen.exe \s\mono2\mono\tests\bug-10127.exe
```
> Remove some #if __cplusplus wrt inlining.

- scripts/ci/pipeline-netcore-runtime.yml
They were moved over to dotnet/runtime: https://github.com/dotnet/runtime/pull/32303
> [netcore] Disable ARM64 CI runs

- mcs/class/System.Net.Http/System.Net.Http_test.dll.sources
- mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientHandlerTests.Android.cs
- mcs/class/System.Net.Http/UnitTests/monodroid_System.Net.Http.UnitTests_xtest.dll.sources
The xunit tests we have for this lib use "fake" `HttpClientHandler` (and the test expects the real one), see https://github.com/mono/corefx/blob/master/src/System.Net.Http/tests/UnitTests/Fakes/HttpClientHandler.cs
> Move TestEnvVarSwitchForInnerHttpHandler to nunit (from xunit)

- mcs/class/System.XML/System.Xml.Serialization/XmlSerializer.cs
- mcs/class/System.XML/Test/System.Xml.Serialization/XmlSerializerTests.cs
Fixes #16741 with regards to using Encoding.UTF8 over Encoding.Default as recommended in the [Encoding.Default](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=netframework-4.8) remarks to mitigate lossy data.
**Testing**:
Reproducing error
- Creating Visual Studio Xamarin.Mac App using code provided in #16741 
- Ran code 
```
Test with default encoder:
<?xml version="1.0" encoding="us-ascii"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Name>L?ther</Name>
<Description>D?scription</Description>
</Information>
Test by overriding default encoder with UTF8:
<?xml version="1.0" encoding="utf-8"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" …
```
> [2019-12] [bcl] Default XmlSerializer stream serialize to UTF8 Encoding

- mcs/class/System.XML/System.Xml.Serialization/XmlSerializer.cs
- mcs/class/System.XML/Test/System.Xml.Serialization/XmlSerializerTests.cs
Fixes #16741 with regards to using Encoding.UTF8 over Encoding.Default as recommended in the [Encoding.Default](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=netframework-4.8) remarks to mitigate lossy data.
**Testing**:
Reproducing error
- Creating Visual Studio Xamarin.Mac App using code provided in #16741 
- Ran code 
```
Test with default encoder:
<?xml version="1.0" encoding="us-ascii"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Name>L?ther</Name>
<Description>D?scription</Description>
</Information>
Test by overriding default encoder with UTF8:
<?xml version="1.0" encoding="utf-8"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" …
```
> [2020-02] [bcl] Default XmlSerializer stream serialize to UTF8 Encoding

- mono/metadata/appdomain.c
- mono/metadata/assembly-internals.h
- mono/metadata/assembly.c
- mono/metadata/native-library.c
- mono/mini/monovm.c
!! This PR is a copy of dotnet/runtime#32263,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This includes some other minor cleanup to the netcore hosting functions.
Setting `assemblies_path` with `APP_PATHS` despite it also being set by `MONO_PATH` doesn't scare me too much because:
1) Anyone using `MONO_PATH` is probably not going through the hosting API and is using `mono-sgen` directly
2) The default host doesn't set `APP_PATHS` (and we've worked fine without it being set at all up …
> [loader] Parse in more netcore hosting properties

- mcs/class/System.XML/System.Xml.Serialization/XmlSerializer.cs
- mcs/class/System.XML/Test/System.Xml.Serialization/XmlSerializerTests.cs
Fixes #16741 with regards to using Encoding.UTF8 over Encoding.Default as recommended in the [Encoding.Default](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=netframework-4.8) remarks to mitigate lossy data.
**Testing**:
Reproducing error
- Creating Visual Studio Xamarin.Mac App using code provided in #16741 
- Ran code 
```
Test with default encoder:
<?xml version="1.0" encoding="us-ascii"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Name>L?ther</Name>
<Description>D?scription</Description>
</Information>
Test by overriding default encoder with UTF8:
<?xml version="1.0" encoding="utf-8"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" …
```
> [bcl] Default XmlSerializer stream serialize to UTF8 Encoding

- mono/metadata/icall.c
- mono/tests/merp-crash-test.cs
- mono/utils/mono-state.c
- mono/utils/mono-state.h
Backport #18863 to `2020-02`
---
If the process calls `System.Environment.FailFast (message, exception)` we should capture the message in the crash report log.
Backport of #18920.
> [2019-12] [merp] Capture Environment.FailFast message in crash report

- configure.ac
- mono/tests/Makefile.am
It hangs: https://github.com/mono/mono/issues/18827
Backport of #18828.
> [2020-02] [tests] Disable bug-10127.exe runtime test on Windows x64 C++

- mono/metadata/icall.c
- mono/tests/merp-crash-test.cs
- mono/utils/mono-state.c
- mono/utils/mono-state.h
Backport #18863 to `2020-02`
---
If the process calls `System.Environment.FailFast (message, exception)` we should capture the message in the crash report log.
> [2020-02][merp] Capture Environment.FailFast message in crash report

- mono/mini/interp/transform.c
- netcore/CoreFX.issues_interpreter.rsp
We never track the value of locals who have their address taken in a method, since their value can change without the pass detecting it, leading to propagation of incorrect values. We failed to check for this when doing a stloc.np optimization.
Fixes System.Reflection.Metadata.Tests.ImmutableByteArrayInteropTest.DangerousCreateFromUnderlyingArray
Enable more interp tests, which don't seem to fail on my machine.
> [interp] Fix incorrect propagation of indirect local

- man/mono.1
- mono/metadata/sgen-mono.c
- mono/sgen/sgen-gc.c
The managed allocator included in a full aot image does not support canaries, leading to inconsistent object layout.
Fixes https://github.com/mono/mono/issues/18925
> [sgen] Disable managed allocator when using nursery-canaries

- man/mono.1
- mono/metadata/sgen-mono.c
- mono/sgen/sgen-gc.c
The managed allocator included in a full aot image does not support canaries, leading to inconsistent object layout.
Fixes https://github.com/mono/mono/issues/18925
Backport of #18932.
/cc @BrzVlad
> [2020-02] [sgen] Disable managed allocator when using nursery-canaries

- man/mono.1
- mono/metadata/sgen-mono.c
- mono/sgen/sgen-gc.c
The managed allocator included in a full aot image does not support canaries, leading to inconsistent object layout.
Fixes https://github.com/mono/mono/issues/18925
Backport of #18932.
/cc @BrzVlad
> [2019-12] [sgen] Disable managed allocator when using nursery-canaries

- mono/mini/interp/interp.c
Implied extra stack use is probably ok now, and this wasn't generally the most problematic stack in the first place, albeit still somewhat worth optimizing.
Might want to leave this alone for now, at least not without testing against current iOS/Blazor.
There is much other mitigating change, but these *might* matter.
> [interp] Allow inlining.

- mono/dis/get.c
Code like this:
```csharp
using System;
class Program
{
static byte[] bla = new byte[] {1,2,3,4,5};
{
}
}
```
Compiles to a private field declaration for the array with a compiler generated
name, that name should be quoted if it starts with a digit.  For example:
```
IL_0007:  ldtoken field valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=5' '<PrivateImplementationDetails>'::'74F81FE167D99B4CB41D6D0CCDA82278CAEE9F3E2F25D5E5A3936FF3DCEC60D0'
```
Fixes https://github.com/mono/mono/issues/18750
> [monodis] Escape names that start with a digit

- mono/metadata/sgen-mono.c
!! This PR is a copy of dotnet/runtime#32640,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This fixes https://github.com/mono/mono/issues/17140; intermittent incorrect results from GetTotalBytesAllocated for current thread. uint64_t and a pointer difference are not the same type/width on all architectures, so incorrect results can happen with out the parenthesis.
> Added some parenthesis and a cast to control order of operations.

- sdks/wasm/DebuggerTestSuite/Support.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
Register a DebugStore and ExecutionContext per session and force some commands
to block on source loading so that scripts are loaded before attempting to use
them. This should populate the sources in vscode-js-debug properly.
> [wasm][debugger] Store more per session state and force some event ordering

- mono/metadata/metadata-internals.h
- mono/metadata/metadata.c
- mono/metadata/metadata.h
- mono/mini/mini-amd64-gsharedvt.c
Also `mark mono_signature_get_params` external only.
Runtime should use `mono_signature_get_return_type_internal`
and `mono_signature_get_params_internal`
> [metadata] Mark mono_signature_get_return_type external only

- mono/metadata/sgen-mono.c
!! This PR is a copy of dotnet/runtime#32640,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This fixes https://github.com/mono/mono/issues/17140; intermittent incorrect results from GetTotalBytesAllocated for current thread. uint64_t and a pointer difference are not the same type/width on all architectures, so incorrect results can happen with out the parenthesis. 
Backport of #18972.
> [2020-02] Added some parenthesis and a cast to control order of operations.

- mono/mini/interp/interp.c
- mono/mini/interp/transform.c
This is an alternative to https://github.com/mono/mono/pull/18974.
Mainly that it does not introduce new opcode to remove branch from newobj/newobj_string.
Both eliminate a bit of dead code in newobj (if turns out to be alive, can also be new opcodes).
> [interp] Remove some unused paths in newobj and cleanup a little.

- mono/eglib/glib.h
- mono/mini/ee.h
- mono/mini/interp-stubs.c
- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/mini-exceptions.c
This is like https://github.com/mono/mono/pull/19002 but next_free is initialized upon allocation instead of `pop_frame` which is a slight optimization.
> [interp] Use alloca for InterpFrame.

- mono/metadata/sgen-mono.c
!! This PR is a copy of dotnet/runtime#32640,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This fixes https://github.com/mono/mono/issues/17140; intermittent incorrect results from GetTotalBytesAllocated for current thread. uint64_t and a pointer difference are not the same type/width on all architectures, so incorrect results can happen with out the parenthesis. 
Backport of #18972.
> [2019-12] Added some parenthesis and a cast to control order of operations.

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
.. breakpoints. Chrome tries set the breakpoints from previous sessions
when the debugger starts up. And we set that in mono, if the runtime is
ready.
But in `MonoProxy.RuntimeReady`, we mark the runtime ready *before*
clearing the breakpoints. So, we end up setting the breakpoints, as
asked by chrome debugger, but then subsequently clearing them!
This manifests as previously set breakpoints in managed code not getting
hit, but if we reset the breakpoint manually then it gets hit.
> [wasm][debugger] Don't mark the runtime ready before clearing the

- mono/metadata/sysmath.c
!! This PR is a copy of dotnet/runtime#32740,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When compiling, Visual Studio gives two compiler warnings in the sysmath.c file about FPILOGB0/-2147483648 being converted into an unsigned integer.
The standard library math.h states that FPILOGB0 be INT_MIN, so I replaced -2147483648 with the INT_MIN macro so the behavior is much more clear as well as stifling the compiler warnings.
Changes tested manually and automatically.
> Fix compilation warning for converting negative integer constant to unsigned.

- mono/eglib/gfile-win32.c
- mono/eglib/test/driver.c
- mono/eglib/test/spawn.c
- mono/metadata/custom-attrs.c
- mono/metadata/gc.c
- mono/metadata/icall.c
- mono/metadata/mono-debug.c
- mono/metadata/object.c
- mono/metadata/sgen-mono.c
- mono/metadata/sgen-stw.c
- mono/metadata/threads.c
- mono/mini/debugger-agent.c
- mono/mini/interp/interp.c
- mono/mini/mini-codegen.c
- mono/mini/mini-exceptions.c
- mono/mini/trace.c
- mono/profiler/log.c
- mono/sgen/sgen-debug.c
- mono/sgen/sgen-internal.c
- mono/sgen/sgen-thread-pool.c
- mono/tests/libtest.c
- mono/utils/hazard-pointer.c
- mono/utils/lock-free-queue.c
- mono/utils/mono-threads.c
- msvc/msvc-disabled-warnings.h
Whittle away at warnings:
Return address of local (deliberate).
Pointer cast to different size (need to go back and fix them all).
Function parameter and declaration badly mismatch (pid_t vs. void*). (need to come back and fix it).
Unused locals.
Top level volatile is ignored.
Negative shift undefined.
Call to undeclared function (getpid).
Some are fixed, some are disabled temporarily.
> Fix/quash more warnings.

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
This change broke windows path processing
> [wasm][debugger] revert DotNetUrl changes

- mcs/class/System.Windows.Forms/System.Windows.Forms/ListViewItem.cs
- mcs/class/System.Windows.Forms/Test/System.Windows.Forms/ListViewItemTest.cs
> Ensure ListView ItemCheck event can update the checked state (#18926)

- mono/eglib/test/spawn.c
Extracted from https://github.com/mono/mono/pull/19025.
> Fix warnings: GPid vs. pid_t function signature mixup in glib test code.

- mono/utils/lifo-semaphore.c
- mono/utils/lifo-semaphore.h
!! This PR is a copy of dotnet/runtime#32328,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When compiling for Mono, Apple's compiler gives a warning saying to put braces around the 0 as it is a subobject. To silence the compiler, I put braces around the 0. Simply fix.
> Braces around subobject of initialization warning fix

- mono/mini/monovm.c
!! This PR is a copy of dotnet/runtime#32789,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Current hook compares TPA list file names using case sensitive compare. On Windows, the TPA list, when passed from CoreRun.exe makes all file paths lower case, meaning that our checks fails to find assemblies in TPA list.
Since CoreRun.exe is used for both CoreCLR and Mono, removing the tolower on file paths added to the TPA list in CoreRun.exe could be an option, but that might introduce …
> Fix Mono netcore preload hook to work with Windows CoreRun.exe.

- mono/mini/mini-wasm-debugger.c
- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/debugger-driver.html
- sdks/wasm/debugger-test.cs
- no details of the valuetype are accessible
Fixes #18232
> [wasm][debugger] Show the typename for valuetypes

- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
Originally we had a simple way to detect that breakpoints were
meant for the runtime but that is no longer true.  Now if we
can't locate a breakpoint we need to pass the request on to the
target so it can make an attempt.
> [wasm][debugger] Always pass failed breakpoint requests to target

- mono/mini/aot-runtime.c
- mono/mini/aot-runtime.h
- mono/mini/mini-trampolines.c
Fixes https://github.com/mono/mono/issues/19009.
https://github.com/mono/mono/pull/18505 made PLT initialization occur at
image load time. When initializing the PLT for mscorlib,
`mono_defaults.corlib` is not yet initialized.
This change works around this by using `mscorlib_aot_module`--which is
initialized relatively early--instead of `mono_defaults.corlib`. PLT
initialization is also moved slightly later: it now happens after
`use_page_trampolines` has been initialized. The `USE_PAGE_TRAMPOLINES`
macro has also been changed to dereference `mscorlib_aot_module`.
This commit also removes an unused parameter from
`mono_aot_create_specific_trampoline`.
> [aot] Avoid `mono_defaults` when creating trampolines.

- mcs/class/System.Windows.Forms/System.Windows.Forms/PropertyGrid.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/PropertyGridView.cs
Assume, one have colorized `PropertyGrid propertyGrid` control:
```
propertyGrid.CategoryForeColor = Color.Red;
propertyGrid.LineColor = Color.Blue;
```
Before changes proposed by the current PR we get the following image:
After:
(item labeled "_Child 2_" is selected by user)
> [WinForms] Colorize PropertyGrid's Categories properly

- msvc/mono.external.targets
If LLVM build is done using different build configuration, Mono build will fail to static link LLVM libraries due to incompatibility between release and debug C++ runtime library, generating a lot of linker errors like this:
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in mini-llvm-cpp.obj
error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in mini-llvm-cpp.obj
This is normally not a problem when doing local builds of LLVM but when using an external provided build, like netcore Mono build, this problem is more likely to occur.
This fix adds an additional check to make sure build configuration reported by llvm-config.exe --build-mode matches current Mono build …
> Detect build config mismatch for MSVC Windows LLVM build.

- mono/mini/aot-runtime.c
- mono/mini/aot-runtime.h
- mono/mini/mini-trampolines.c
Fixes https://github.com/mono/mono/issues/19009.
https://github.com/mono/mono/pull/18505 made PLT initialization occur at
image load time. When initializing the PLT for mscorlib,
`mono_defaults.corlib` is not yet initialized.
This change works around this by using `mscorlib_aot_module`--which is
initialized relatively early--instead of `mono_defaults.corlib`. PLT
initialization is also moved slightly later: it now happens after
`use_page_trampolines` has been initialized. The `USE_PAGE_TRAMPOLINES`
macro has also been changed to dereference `mscorlib_aot_module`.
This commit also removes an unused parameter from
`mono_aot_create_specific_trampoline`.
Backport of #19055.
/cc @lewurm @imhameed
> [2020-02] [aot] Avoid `mono_defaults` when creating trampolines.

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/runtime-tests.js
- sdks/wasm/src/library_mono.js
Using a `debugger` breakpoint in MONO.mono_wasm_runtime_ready has
unfortunate side effects, this changes the logic to use console.trace
and checks the stackTrace when the event arrives.
> [wasm][debugger] use console.debug to signal runtime init

- configure.ac
- mono/metadata/icall.c
- mono/mini/exceptions-amd64.c
- mono/mini/exceptions-ppc.c
- mono/mini/exceptions-x86.c
- mono/mini/mini-posix.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
- mono/mini/mini-windows.c
- mono/utils/Makefile.am
- mono/utils/mono-merp.c
- mono/utils/mono-signal-handler.c
- mono/utils/mono-signal-handler.h
- msvc/libmonoutils-common.targets
- msvc/libmonoutils-common.targets.filters
The default handlers for SIGTRAP, SIGSYS on macOS and Linux crash the process, so we now have Mono report this.
This patch also changes how the name of the signal is acquired for passing on to the crash reporting functions, allowing code reuse on crashing signals.
Backport of https://github.com/mono/mono/pull/18243 and #18851
> [2019-12][runtime] Improve handling crashing signals

- mcs/class/System/System.Net.NetworkInformation/NetworkInterface.platformnotsupported.cs
- mcs/class/System/System.csproj
- mcs/class/System/wasm_System.dll.exclude.sources
- mcs/class/System/wasm_System.dll.sources
- mcs/class/referencesource/System/net/System/Net/NetworkInformation/NetworkInterface.cs
PNSE coverage of wasm bcl has shown that only three public members of `System.Net.NetworkInformation.NetworkInterface` class throw `PlatformNotSupportedException`.
Now all public members throw PNSE on WASM.
Relates to https://github.com/mono/mono/issues/18735
> [wasm] Use PNSE version of System.Net.NetworkInformation.NetworkInterface

- mono/eglib/Makefile.am
- mono/eglib/glib.h
- mono/eglib/gmodule-aix.c
- mono/eglib/gspawn.c
- mono/eglib/test/spawn.c
- mono/mini/debugger-agent.c
- msvc/eglib-common.targets
- msvc/eglib-common.targets.filters
- msvc/eglib-posix.targets
- msvc/eglib-posix.targets.filters
Subject to configuration, spawn has three widely divergent behaviors:
1. succeed but do nothing
2. print and exit
3. do what it sounds like
Rather than mislead the callers, provide only option 3 and let the caller decide what to do otherwise.
> Remove non-functional spawn code.

- mono/metadata/icall.c
- mono/tests/merp-crash-test.cs
- mono/utils/mono-state.c
- mono/utils/mono-state.h
If the process calls `System.Environment.FailFast (message, exception)` we should capture the message in the crash report log.
Backport of #18920 (which is a handwritten backport of #18863)
> [2019-10] [merp] Capture Environment.FailFast message in crash report

- configure.ac
- mono/metadata/icall.c
- mono/mini/exceptions-amd64.c
- mono/mini/exceptions-ppc.c
- mono/mini/exceptions-x86.c
- mono/mini/mini-posix.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
- mono/mini/mini-windows.c
- mono/utils/Makefile.am
- mono/utils/mono-merp.c
- mono/utils/mono-signal-handler.c
- mono/utils/mono-signal-handler.h
- msvc/libmonoutils-common.targets
- msvc/libmonoutils-common.targets.filters
The default handlers for SIGTRAP, SIGSYS on macOS and Linux crash the process, so we now have Mono report this.
This patch also changes how the name of the signal is acquired for passing on to the crash reporting functions, allowing code reuse on crashing signals.
Backport of https://github.com/mono/mono/pull/18243 and #18851
> [2020-02][runtime] Improve handling crashing signals

- mono/metadata/domain-internals.h
- mono/metadata/domain.c
!! This PR is a copy of dotnet/runtime#32502,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>I don't think you can create a root domain without reaching the thread info attach call, so this should be safe to change outright.
Fixes dotnet/runtime#32177 
We should complete https://github.com/mono/mono/issues/18915 and then convert over other locks as needed, but this fixes the immediate CI hang.
> [threading] Switch domain assemblies lock from OS to Coop

- packaging/MacSDK/msbuild.py
Roslyn updated to `3.5.0-beta4-20128-01`.
> [2020-02] Bump msbuild to track xplat-master

- packaging/MacSDK/msbuild.py
Roslyn updated to `3.5.0-beta4-20128-01`.
> [2019-12] Bump msbuild to track mono-2019-12

- mono/metadata/custom-attrs.c
!! This PR is a copy of dotnet/runtime#32974,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Xamarin.Forms calls this _constantly_ during startup, to the point where the malloc calls were actually showing up in the profile. This should help with that, and gives us some ms back during startup.
There are also a bunch of calls that return empty arrays, which in theory could be created in managed for a perf boost. However, it seems the Xamarin.Android team has mostly gotten rid of those calls …
> Use GArray instead of GList when getting custom attributes from an image

- msvc/genmdesc.vcxproj
- msvc/monodis.vcxproj
- msvc/pedump.vcxproj
Changes done in object-offsets.h by #18713 adding offsets for TARGET_AMD64 exposed
a build configuration error in the Mono Tool MSVC debug build due to incorrectly setting both X86 and AMD64 defines causing compile errors when including object-offset.h. Release configuration didn't have this configuration error, meaning that CI builds wouldn't trigger build error.
Fix makes sure all MSVC build configurations for Mono Tools (genmdesc, monodis, pedump) matches the build configuration for other binaries and that debug build configuration is inline with release build configuration.
> Fix Mono Tool MSVC Debug build.

- mcs/class/System.ComponentModel.DataAnnotations/ReferenceSources/SR.cs
- mcs/class/System.ComponentModel.DataAnnotations/System.ComponentModel.DataAnnotations.csproj
- mcs/class/System.ComponentModel.DataAnnotations/System.ComponentModel.DataAnnotations.dll.sources
- mcs/class/System.ComponentModel.DataAnnotations/System.ComponentModel.DataAnnotations_test.dll.sources
- mcs/class/System.ComponentModel.DataAnnotations/Test/System.ComponentModel.DataAnnotations/MaxMinLengthAttributeTest.cs
- mcs/class/System.ComponentModel.DataAnnotations/corefx/CountPropertyHelper.cs
- mcs/class/referencesource/System.ComponentModel.DataAnnotations/DataAnnotations/MaxLengthAttribute.cs
- mcs/class/referencesource/System.ComponentModel.DataAnnotations/DataAnnotations/MinLengthAttribute.cs
It should now validate against ICollection or any other type that has a Count property for that matter.
We're still relying on the reference source implementation because corefx strips some types out.
Fixes https://github.com/mono/mono/issues/19022
> Changed Max and MinLengthAttribute validation

- mono/mini/mini-runtime.c
- mono/utils/mono-threads-coop.c
- mono/utils/mono-threads-coop.h
This contributes to https://github.com/mono/mono/issues/18916 (to make coop locking not bother with state transitions if the runtime isn't ready yet) and also to some upcoming additions to checked mode checks to verify that os locks don't cross a safepoint.
> [threads] Add a global "runtime startup is finished" flag

- mono/metadata/domain-internals.h
- mono/metadata/image.c
- mono/mini/driver.c
In a current shipping Visual C++, 19.21.27702.2,
there is a bug involving const member data in structs, where for example:
static const struct a { // const on this line in either case
const int b; // const on this line
} c = {1};
will have a static initializer, run usually reliably before main, but:
static const struct a { // const on this line in either case
int b; // no const on this line
} c = {1};
will not.
The semantic difference is minuscule, so much so, that the first form
is relatively rare, and the bug shipped.
Just always use the second form.
The difference is that if you have a non-const a, b is still const, I guess.
If you have a const a, then no difference.
You can find these easily:
cd ...
for %a in (*.exe *.dll) do link /dump /disasm %a > %a.txt
findstr /c:"dynamic …
> [cxx] Remove static initializers.

- mono/metadata/appdomain.c
- mono/metadata/assembly.c
- mono/metadata/loader-internals.h
- mono/metadata/metadata-internals.h
!! This PR is a copy of dotnet/runtime#32622,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Unsure of whether the `add_assembly_to_domain` changes are safe to make, but I *think* so. We'll see if it causes issues on legacy CI, and maybe I'll revert it anyway if I decide I'm not comfortable changing that.
I can't reproduce the crash prompting this at all locally, though I've asked Viktor for ideas on how to do so.
My guess for what causes the crash is that we add the assembly to the …
> [loader] Clean up locking around adding assemblies to domain/ALC

- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
This  set consists of a few logical changes
* Try to follow CDP ordering constraints by not responding Debugger.enable until we've fired scriptParsed events for any already loaded assemblies.
* Send Debugger.scriptParsed asynchronously as we load assemblies instead of waiting for them all to load first and fix some of the sequence point processing to speed up debugger initialization time.
* Rework breakpoint request handling by always passing the request to the browser then storing both the request and the resultant id for use in when any new scripts are loaded.
* Passing any previous breakpoint requests to the new execution context on page reload.
> [wasm][debugger] Rework breakpointRequest handling across sessions

- mono/mini/llvm-jit.cpp
- mono/mini/llvm-jit.h
- mono/mini/mini-llvm.c
Should fix https://github.com/mono/mono/issues/19115. This bug was
introduced in https://github.com/mono/mono/pull/18824, which
conditionally initalized an LLVM JIT-related TLS slot while preserving
unconditonal stores to that same slot.
The value stored in this TLS slot should only be used during JIT
compilation, so set/reset it in `mono_llvm_compile_method` instead of
during IR construction in `mono_llvm_emit_method`. No non-JIT code
should depend on the existence of this TLS variable, so
remove `mono_llvm_jit_set_tls_cfg`.
> [llvm] Don't set the LLVM JIT TLS variable in AOT.

- mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
As analysed by @jstedfast and me the only way to get this exception with this callstack below is 2 threads call GetThreads at same time, so while one of them is filling the items in the array, the other one is already trying to use the array with null items.
```
System.NullReferenceException: Object reference not set to an instance of an object
at Mono.Debugging.Soft.SoftDebuggerSession.GetId (Mono.Debugger.Soft.ThreadMirror thread) [0x00000] in /Users/runner/runners/2.164.6/work/1/s/monodevelop/main/external/debugger-libs/Mono.Debugging.Soft/SoftDebuggerSession.cs:3227
at Mono.Debugging.Soft.SoftDebuggerSession.OnGetThreads (System.Int64 processId) [0x0002c] in /Users/runner/runners/2.164.6/work/1/s/monodevelop/main/external/debugger-libs/Mono.Debugging.Soft/SoftDebuggerSession.cs:879
at …
```
> [debugger] NRE when 2 threads try to call GetThreads at same time

- mono/mini/mini-llvm-cpp.cpp
!! This PR is a copy of dotnet/runtime#32742,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>numOperands is an unsigned integer. In addition, getArgOperand has unsigned int arguments. As a result, I have no idea why i is an int, but to fix compiler warnings, I made it an unsigned int.
> changed signedness of iterator to fix warnings.

- mcs/class/corlib/System.IO/FileStream.cs
- mcs/class/corlib/System/Console.cs
We already suppress the finalization of the CStreamReader and CStreamWriter, but during shutdown, the underlying FileStream may be finalized which invalidates its access field which can lead to a crash.
Addresses https://github.com/mono/mono/issues/19005
> [corlib] Suppress finalization of underlying console FileStreams

- mono/metadata/appdomain.c
During unload_thread_main, **mono_gc_collect** is called 3 times.
First: https://github.com/mono/mono/blob/280e9d2423549d86686716f0818bcdbac9702ea1/mono/metadata/gc.c#L455
Second: https://github.com/mono/mono/blob/b4c506c3045516349d03ce8f3fe9fa5b79a7271c/mono/metadata/appdomain.c#L3305
Third: https://github.com/mono/mono/blob/b4c506c3045516349d03ce8f3fe9fa5b79a7271c/mono/metadata/appdomain.c#L3324
This PR #ifdefs the Second GC Collect for Boehm as it does not use remsets, and removes the third one completely. 
The comment for the second gc_collect existence mentions that:
> We need to make sure that we don't have any remsets pointing into static data...(cont)
> However, Unity uses Boehm so it can be defined out.
There seems to be no good reason for the third GC collect, as it is already …
> Remove redundant mono_gc_collect during domain unload

- mono/metadata/icall.c
- mono/mini/mini-posix.c
- mono/utils/mono-state.c
- mono/utils/mono-state.h
/cc @kdubau @lambdageek 
Addresses https://github.com/mono/mono/issues/18715
Backport of #19072.
/cc @alexischr
> [2020-02] [merp] Create a signal ('source') breadcrumb for the crash dump process

- sdks/wasm/src/binding_support.js
- sdks/wasm/src/corebindings.c
- sdks/wasm/src/dotnet_support.js
- sdks/wasm/src/driver.c
- sdks/wasm/src/library_mono.js
Previously when converting strings from mono objects to js we used a utf8 intermediate buffer, this change builds the js string from the mono string without an intermediate.
> [wasm] Convert MonoString to string without utf8 intermediate

- mono/mini/interp/whitebox.c
!! This PR is a copy of dotnet/runtime#33045,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>In C, the if statement checks if the value is 0 or not 0. !!, or forcing to 1 or 0, is unnecessary here.
> No need to force to bool, when C does that automatically in the if statement.

- mono/mini/aot-runtime.c
Fixes https://github.com/mono/mono/issues/18612; `aot_code_low_addr` and
`aot_code_high_addr` were set to a range that included only first-level
branch islands, so `find_aot_module` would fail early when passed a
genuine function address.
This change only affects monotouch for now.
Why not use relative offsets stored in a read-only section? One reason
is that llvm-as cannot handle a `.long` directive containing a
subtraction expression involving externally-defined symbols. The AOT
method address table and AOT LLVM-generated code are currently emitted
in separate object files, so the method address table would include
expressions with undefined symbols.
Related: https://xamarin.github.io/bugzilla-archives/70/707/bug.html
Backport of #19126.
> [2020-02][arm][ios] Follow branch islands when determining method entry addresses.

- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
- mono/mini/aot-runtime.h
- mono/mini/mini-llvm.c
- mono/mini/mini-trampolines.c
- mono/mini/tramp-amd64.c
Current implementation embedded critical runtime information directly into PLT slot. It also depends on finding call site in generic trampoline reading call target from instruction stream in order to locate PLT slot in use and then read GOT offset as well as PLT info offset from PLT slot instruction stream.
This is problematic on platforms where code is execute only. Fix changes how the metadata needed in order to correctly patch PLT is discovered. Instead of depending on reading instruction stream, it is loaded into RAX (free to be used when calling through PLT on AMD64) in PLT slot before jmp takes place that moves control over to generic trampoline.
The PLT slot is the only place where we have access to both GOT index (used in jmp), PLT info offset (currently embedded after jmp …
> Convert PLT table and call site to execute only on AMD64.

- mono/metadata/appdomain.c
- mono/metadata/exception.c
- mono/metadata/icall.c
- mono/metadata/metadata.c
- mono/mini/aot-runtime.c
!! This PR is a copy of dotnet/runtime#33117,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes dotnet/runtime#31649 
Fixes dotnet/runtime#31650 
**Testing**:
Reproduced Error via
`<Runtime Repo Root>/build.sh /p:RuntimeFlavor=mono`
Removing `[ActiveIssue("https://github.com/dotnet/runtime/issues/31650", TestRuntimes.Mono)]` in AssemblyTests.cs
Running `dotnet msbuild /t:RebuildAndTest /p:XunitMethodName=System.Reflection.Tests.AssemblyTests.LoadFile_NoSuchPath_ThrowsFileNotFoundExcepti …
> Include filename in Invalid image error messages

- sdks/wasm/standalone-benchmarks/run-benchmark-all.sh
- sdks/wasm/standalone-benchmarks/run-benchmark-mono-aot.sh
- sdks/wasm/standalone-benchmarks/run-benchmark-mono-interpreter.sh
- sdks/wasm/standalone-benchmarks/run-benchmark-mono.sh
- sdks/wasm/standalone-benchmarks/run-benchmark-wasm-aot.sh
- sdks/wasm/standalone-benchmarks/run-benchmark-wasm.sh
This just handles systems (mac) without realpath installed and with a version of bash
that doesn't support &>>.  It also trims path information from the benchmark name
> [wasm][standalone-benchmarks] Support mac (old bash, no realpath)

- mono/mini/mini-runtime.c
/s/mono2/mono/mini/mini-runtime.c:2284:15: warning: unused variable 'ji'
[-Wunused-variable]
MonoJitInfo *ji;
> [wasm] Fix warnings about unused variables.

- mono/metadata/class.c
- mono/mini/driver.c
This is subtle and not actually misleading,
because it tends to be space tab or space tab, not wrong
number of tabs or significant wrong number of spaces.
/s/mono2/mono/metadata/class.c:4010:6: warning: misleading indentation;
statement is not part of the previous 'if' [-Wmisleading-indentation]
if (mono_class_implement_interface_slo...
/s/mono2/mono/metadata/class.c:4039:3: warning: misleading indentation;
statement is not part of the previous 'if' [-Wmisleading-indentation]
if (m_class_is_delegate (target) && mono_class_has_variant_gener...
/s/mono2/mono/mini/driver.c:1780:4: warning: misleading indentation; statement
is not part of the previous 'if' [-Wmisleading-indentation]
if (strncmp (argv [i], "--debugger-agent=", 17) == 0) {
> Fix warnings about misleading indentation.

- mono/mini/mini-generic-sharing.c
/s/mono2/mono/mini/mini-generic-sharing.c:1415:9: warning: unused variable
'param_names' [-Wunused-variable]
char **param_names;
> [mini] Fix warning about unused variables.

- tools/sgen/sgen-grep-binprot.c
Kind of a silly warning.
mono/sgen/sgen-protocol-def.h:102:1: warning: adding 'unsigned long' to
a string does not append to the string [-Wstring-plus-int]
BEGIN_PROTOCOL_ENTRY_HEAVY2 (binary_protocol_block_alloc, TYPE_POINTER, addr, TYPE_SIZE, size)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tools/sgen/sgen-grep-binprot.c:394:2: note: expanded from macro
'BEGIN_PROTOCOL_ENTRY_HEAVY2'
BEGIN_PROTOCOL_ENTRY2 (method,t1,f1,t2,f2)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tools/sgen/sgen-grep-binprot.c:291:26:
note: BEGIN_PROTOCOL_ENTRY3 (binary_protocol_world_stopping,
TYPE_INT, generation, TYPE_LONGLONG, timestamp, TYPE_POINTER, thread)exp
mono/sgen/sgen-protocol-def.h:102:1: note: use array indexing to
silence this warning
> [tools/sgen] Fix warnings about adding integers to string pointers.

- mono/mini/interp/transform.c
/s/mono2/mono/mini/interp/transform.c:3166:25: note: place parentheses around
the '&&' expression to silence this warning
if (mt >= MINT_TYPE_I1 && mt <= MINT_TYPE_I4
~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
> [interp][32bit] Fix warning about precedence/parentheses.

- mono/mini/aot-runtime.c
- mono/mini/tramp-arm64.c
Followup to https://github.com/mono/mono/pull/19126 and
https://github.com/mono/mono/pull/19169.
Bring arm64 `mono_arch_get_call_target` in line with other platforms by
returning NULL on failure instead of asserting. Bits 30-26 in an arm64
unconditional branch are exactly 0b00101, so 0x1f (0b11111) is used as a
mask to determine if the branch uses an immediate target--0x7 (0b111)
would incorrectly match against branches using register targets. The
extracted immediate is now sign extended in a branch-free way.
Avoid following blx entries in the method address table; ld64 can emit 4
different instruction sequences for islands involving thumb, and I'd
rather not implement support for them all now because 32-bit iOS is old
and large unlinked assemblies seem rare.
> [arm] Fix branch island disassembly for arm64 and thumb.

- mono/metadata/icall.c
- mono/mini/mini-posix.c
- mono/utils/mono-state.c
- mono/utils/mono-state.h
/cc @kdubau @lambdageek 
Addresses https://github.com/mono/mono/issues/18715
Backport of #19072.
/cc @alexischr
> [2019-12] [merp] Create a signal ('source') breadcrumb for the crash dump process

- mono/mini/aot-runtime.c
- mono/mini/tramp-arm64.c
Followup to https://github.com/mono/mono/pull/19126 and
https://github.com/mono/mono/pull/19169.
Bring arm64 `mono_arch_get_call_target` in line with other platforms by
returning NULL on failure instead of asserting. Bits 30-26 in an arm64
unconditional branch are exactly 0b00101, so 0x1f (0b11111) is used as a
mask to determine if the branch uses an immediate target--0x7 (0b111)
would incorrectly match against branches using register targets. The
extracted immediate is now sign extended in a branch-free way.
Avoid following blx entries in the method address table; ld64 can emit 4
different instruction sequences for islands involving thumb, and I'd
rather not implement support for them all now because 32-bit iOS is old
and large unlinked assemblies seem rare.
Backport of #19188.
/cc …
> [2020-02] [arm] Fix branch island disassembly for arm64 and thumb.

- mcs/build/config-default.make
- mono/metadata/verify.c
- runtime/Makefile.am
See https://github.com/mono/mono/issues/18572#issuecomment-595924767.
Fixes https://github.com/mono/mono/issues/18572.
> Avoid passing /features:peverify-compat to csc, it generates very inefficient code in some cases.

- mcs/build/config-default.make
- mono/metadata/verify.c
- runtime/Makefile.am
See https://github.com/mono/mono/issues/18572#issuecomment-595924767.
Fixes https://github.com/mono/mono/issues/18572.
Backport of #19144.
/cc @vargaz
> [2020-02] Avoid passing /features:peverify-compat to csc, it generates very inefficient code in some cases.

- mono/utils/mono-state.c
Closes https://github.com/mono/mono/issues/19136
> [merp] Remove unnecessary call to msync in mono_state_free_mem

- mono/utils/mono-state.c
Closes https://github.com/mono/mono/issues/19136
Backport of #19167.
> [2020-02] [merp] Remove unnecessary call to msync in mono_state_free_mem

- sdks/builds/Makefile
SDK builds done under WSL was done like Cygwin in order to be a Cygwin replacement going forward. This has caused issues when building sdk's under WSL when Linux is the assumed build host.
Adding an additional define where WSL build host can be overridden to Windows, but default will now be Linux. This can in future be used from configure scripts, setting it in sdks/Make.config when needed, but will be an opt in feature to override Linux as default build host for WSL.
Mainly fixing issue building WASM SDK under WSL defaulting to Windows as build host.
> Disable Windows as default build host for WSL sdk builds.

- mono/metadata/icall-decl.h
- mono/metadata/icall.c
> [metadata] Disable three icalls on netcore monodroid

- mcs/class/corlib/corert/RuntimeAugments.cs
- mono/tests/Makefile.am
- mono/tests/threadpool-exceptions8.cs
In `task.GetAwaiter().OnCompleted(action)` if `action` throws, the `TaskContinuation.RunOrScheduleAction` method will catch the exception and then call `RuntimeAugments.ReportUnhandledException`.  We must not simply throw the exception again - in that case we will lose all the frames leading up to the `catch` in `RunOrScheduleAction`.  Instead use `ExceptionDispatchInfo` to capture the original throw.
Addresses https://github.com/mono/mono/issues/19166
> [corlib] Capture the ExceptionDispatchInfo when rethrowing from TaskContinuation

- sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs
- sdks/wasm/tests/browser/src/BrowserTestSuite/http-spec.js
- sdks/wasm/tests/browser/src/WebSocketTestSuite/WebSocketTestSuite.cs
works around https://github.com/mono/mono/issues/19100
Also removes some string buffering and switches to "arraybuffer" by default
Probably easiest to read as separate commits
> [wasm][websocket] Buffer writes when endOfMessage == false

- sdks/wasm/src/binding_support.js
Instead of hard coding a switch of available types we do a one type lookup for each type by name and store that result.
> [wasm][bindings] clean up symbol resolution

- mcs/class/corlib/corert/RuntimeAugments.cs
- mono/tests/Makefile.am
- mono/tests/threadpool-exceptions8.cs
In `task.GetAwaiter().OnCompleted(action)` if `action` throws, the `TaskContinuation.RunOrScheduleAction` method will catch the exception and then call `RuntimeAugments.ReportUnhandledException`.  We must not simply throw the exception again - in that case we will lose all the frames leading up to the `catch` in `RunOrScheduleAction`.  Instead use `ExceptionDispatchInfo` to capture the original throw.
Addresses https://github.com/mono/mono/issues/19166
Backport of #19168.
> [2019-10] [corlib] Capture the ExceptionDispatchInfo when rethrowing from TaskContinuation

- mono/mini/debugger-agent.c
If there is a crash and the debugger is attached, we call mini_get_dbg_callbacks ()->send_crash().
That call ends up in mono_debugger_agent_send_crash which does all kinds of questionable stuff like trying to take the loader lock. Eventually it ends up calling socket_transport_send which tries to do a transition to GC Safe mode.
I inserted a MONO_ENTER_GC_UNSAFE in mono_debugger_agent_send_crash function and this fixes the assert.
Fixes #18794
> [debugger] [coop] assertion when `socket_transport_send` called from the crash reporter

- mcs/class/corlib/corert/RuntimeAugments.cs
- mono/tests/Makefile.am
- mono/tests/threadpool-exceptions8.cs
In `task.GetAwaiter().OnCompleted(action)` if `action` throws, the `TaskContinuation.RunOrScheduleAction` method will catch the exception and then call `RuntimeAugments.ReportUnhandledException`.  We must not simply throw the exception again - in that case we will lose all the frames leading up to the `catch` in `RunOrScheduleAction`.  Instead use `ExceptionDispatchInfo` to capture the original throw.
Addresses https://github.com/mono/mono/issues/19166
Backport of #19168.
> [2019-12] [corlib] Capture the ExceptionDispatchInfo when rethrowing from TaskContinuation

- mcs/class/corlib/corert/RuntimeAugments.cs
- mono/tests/Makefile.am
- mono/tests/threadpool-exceptions8.cs
In `task.GetAwaiter().OnCompleted(action)` if `action` throws, the `TaskContinuation.RunOrScheduleAction` method will catch the exception and then call `RuntimeAugments.ReportUnhandledException`.  We must not simply throw the exception again - in that case we will lose all the frames leading up to the `catch` in `RunOrScheduleAction`.  Instead use `ExceptionDispatchInfo` to capture the original throw.
Addresses https://github.com/mono/mono/issues/19166
Backport of #19168.
> [2020-02] [corlib] Capture the ExceptionDispatchInfo when rethrowing from TaskContinuation

- mono/metadata/threads.c
!! This PR is a copy of dotnet/runtime#32968,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>If the runtime is shutting down, instead of creating a new thread, or throwing
an exception on the current thread, just shut down the current thread.
This takes advantage of `mono_threads_set_shutting_down`'s behavior that if you
call it after shutdown is already started, it will suspend, detach and exit
from the current thread.
Fixes https://github.com/dotnet/runtime/issues/31842
> [threads] If shutting_down, don't create new thread, kill current thread

- mono/metadata/appdomain.c
- mono/metadata/assembly-load-context.c
- mono/metadata/assembly.c
- mono/metadata/domain.c
- mono/metadata/image.c
- mono/metadata/loaded-images.c
- mono/metadata/mono-config.c
- mono/metadata/native-library.c
- mono/metadata/sgen-bridge.c
- mono/metadata/sgen-mono.c
- mono/metadata/sgen-new-bridge.c
- mono/metadata/sgen-old-bridge.c
- mono/metadata/sgen-tarjan-bridge.c
- mono/metadata/threadpool-worker-default.c
- mono/mini/aot-runtime.c
- mono/mini/monovm.c
- mono/sgen/sgen-memory-governor.c
Fixes #18795
**Testing:**
Created HelloWorld script
Set environment variable `export MONO_LOG_LEVEL=info`
Compiled and executed script before and after these changes were applied
```
mdhwang:~/Desktop$ ls -al csc_*txt mono_*txt
-rw-r--r--@ 1 mdhwang  staff   4270 Mar  3 10:12 csc_after.txt
-rw-r--r--@ 1 mdhwang  staff  56698 Mar  3 10:14 csc_before.txt
-rw-r--r--@ 1 mdhwang  staff    176 Mar  3 10:12 mono_after.txt
-rw-r--r--@ 1 mdhwang  staff   3617 Mar  3 10:14 mono_before.txt
```
There is a noticeable difference in log output sizes, and the logs created after the changes were applied mainly contain `Loading reference 0 of _ asmctx _` as desired in the issue.
> [Loader] Change mono_trace level from info to debug

- mono/mini/mini-amd64.c
- mono/mini/mini.c
- mono/mini/mini.h
#19219 didn't convert the JIT flags into options on cfg meaning that code currently checked JIT_FLAG_CODE_EXEC_ONLY never executed. Fix handles the new JIT flag in same way as other JIT flags, converted into bit field on cfg.
With this fix, the following C# method:
```
static double Test()
{
return 1.0f;
}
```
will now generate the following assembly on amd64, when using MONO_ARCH_CODE_EXEC_ONLY:
```
sub rsp,8
mov r11,qword ptr [180003318h]
movsd xmm0,mmword ptr [r11]
add rsp,8
ret
```
> Fix usage of JIT_FLAG_CODE_EXEC_ONLY flag.

- sdks/wasm/Makefile
browser tests were failing locally with node command not being found if the other tests were not run before.  This makes sure that the  NPM command can be found by installing it if not there.
This also separates out the npm version that is being installed.
> [wasm] cleanup npm/node install.

- mono/mini/mini-runtime.c
- mono/mini/mini.c
!! This PR is a copy of dotnet/runtime#33717,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fix makes sure runtime checks also report that SIMD has been disabled. Returning FALSE from is_simd_supported will turn of MONO_OPT_SIMD and disable all SSE/AVX cpu features will prevent code checking cpu capabilities to emit SIMD instructions.
> Mono DISABLE_SIMD still emits OP codes depending on SIMD support.

- mono/mini/exceptions-amd64.c
!! This PR is a copy of dotnet/runtime#33726,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Running System.Runtime.Serialization.Xml test suite triggers calls to mono_code_manager_reserve with 0 size code block. On Windows, allocating code regions from code manager will also add callback for code region into unwinder function table, but since region could be 0 length, it will be causing a crash in RtlInstallFunctionTableCallback OS call.
Fix hardens code to not try to register callbacks …
> Ignore register unwinder callback for empty patch_info data table on Windows Mono Runtime.

- mono/mini/intrinsics.c
!! This PR is a copy of dotnet/runtime#33761,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes StackOverflow in https://github.com/dotnet/runtime/pull/33749#issuecomment-601271356
Intrinsify all `get_IsSupported` under `System.Runtime.Intrinsics*` to just `false` (except the sets we support, see mono_emit_simd_intrinsics).
> [mono] return false for AdvSimd.IsSupported and friends

- mono/metadata/object.c
!! This PR is a copy of dotnet/runtime#33754,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>All these functions are MONO_RT_EXTERNAL_ONLY and they all allocate managed
objects.
Fixes a coop state machine assertion if an embedder calls the function and it needs to take the GC
lock to do a collection.
> [runtime] Enter GC Unsafe mode in some string allocation functions

- mono/metadata/object.c
!! This PR is a copy of dotnet/runtime#33754,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>All these functions are MONO_RT_EXTERNAL_ONLY and they all allocate managed
objects.
Fixes a coop state machine assertion if an embedder calls the function and it needs to take the GC
lock to do a collection.
Backport of #19261.
> [2020-02] [runtime] Enter GC Unsafe mode in some string allocation functions

- configure.ac
- mono/metadata/Makefile.am
Resolves #18528 in for both detection and compiling. This should backport cleanly to next release.
Tested on 12.1-RELEASE with libinotify; configure detects features correctly, compiles successfully, resolves some observed issues during run.
```
#define HAVE_SYS_INOTIFY_H 1
#define HAVE_LIBINOTIFY 1
#define HAVE_INOTIFY_INIT 1
#define HAVE_INOTIFY_ADD_WATCH 1
#define HAVE_INOTIFY_RM_WATCH 1
#define HAVE_INOTIFY 1
```
> [FreeBSD] Fix for libinotify support and compile

- mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
- mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
- mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs
- mcs/class/Mono.Debugger.Soft/Test/dtest.cs
- mono/metadata/reflection.c
- mono/mini/debugger-agent.c
- Changed mono_reflection_parse_type_checked to accept names that includes < and >
- Changed the behavior on debugger-agent, if we can't parse the new behavior is to return invalid_argument and not assert and stop debugging
- Changed the mono_domain_set_fast before return from assembly_commands.
Fixes #19146
> [debugger] Fix NOT_IMPLEMENTED while debugging.

- mono/mini/driver.c
Removes the copyright year.
```
$ mono --version
Mono JIT compiler version 6.6.0.166 (2019-08/d9001b5ae70 Wed Feb 12 19:20:16 EST 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
TLS:           
SIGSEGV:       altstack
Notification:  kqueue
Architecture:  amd64
Disabled:      none
Misc:          softdebug 
Interpreter:   yes
LLVM:          yes(610)
Suspend:       hybrid
GC:            sgen (concurrent by default)
```
> Updating the Copyright line display when running 'mono --version'

- mono/metadata/Makefile.am
- mono/metadata/mono-private-unstable.h
- mono/mini/Makefile.am.in
- mono/mini/mono-private-unstable.h
- mono/utils/Makefile.am
- mono/utils/mono-private-unstable.h
- msvc/libmono.bat
- msvc/libmonoruntime-common.targets
- msvc/libmonoruntime-common.targets.filters
- msvc/libmonoutils-common.targets
- msvc/libmonoutils-common.targets.filters
!! This PR is a copy of dotnet/runtime#33869,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>We have functions that are de-facto part of the Mono embedding API that are
used by Xamarin.iOS or Xamarin.Android that are not in a state where we want to
commit to supporting them forever in their current form.
Nonetheless, we would like to make sure that the symbols for these functions
are visible even if we otherwise compile the runtime with
`-fvisisibility=hidden`, and we would like to …
> [mono] Add headers for unstable APIs

- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
unbox tramp method addresses are emitted as a table of calls and read at runtime by get_call_table_entry. This is problematic on platforms that doesn't allow data to be read from instruction stream.
Fix follow same pattern as method address table emitted as function pointers into table in data segment when using MONO_ARCH_CODE_EXEC_ONLY.
> Move unbox tramp method address table to data segment, MONO_ARCH_CODE_EXEC_ONLY.

- msvc/mono.props
!! This PR is a copy of dotnet/runtime#33853,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>CoreCLR static link vcruntime140.dll, but dynamic link rest of C-runtime using ucrt.lib in release build. Commit align Mono runtime to follow same pattern, removing dependency on vcruntime140.dll.
> Remove Mono runtime vcruntime140.dll release build dependency.

- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.h
- mono/mini/interp/transform.c
- mono/mini/interp/transform.h
If loaded/stored field is the only field of the valuetype. This is meant to mainly optimize IntPtr accesses, which contains a single void* field and is heavily used in Unsafe intrinsics.
> [interp] Replace ldloca + ldfld/stfld pairs with ldloc/stloc

- mono/metadata/gc.c
- mono/metadata/mono-gc.h
- mono/mini/aot-runtime.c
- mono/mini/aot-runtime.h
- mono/mini/jit.h
- mono/mini/mono-private-unstable.h
- mono/utils/mono-logger.c
!! This PR is a copy of dotnet/runtime#33736,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>See https://github.com/dotnet/runtime/pull/33633 and https://github.com/xamarin/xamarin-macios/blob/master/runtime/exports.t4
* `mono_install_load_aot_data_hook` was already a `MONO_API`, but it was not in a public header.
It is added to `mono/jit/mono-private-unstable.h`
* `mono_gc_init_finalizer_thread` was [used by Xamarin.iOS](https://github.com/xamarin/xamarin-macios/blob/63ab48e679716264b33af …
> [mono] Make some API functions public and private

- mono/metadata/jit-icall-reg.h
- mono/mini/llvmonly-runtime.c
- mono/mini/llvmonly-runtime.h
- mono/mini/mini-llvm.c
- mono/mini/mini-runtime.c
> [llvmonly] Throw an ExecutionEngine exception with a helpful message when we try to execute a method which failed AOT compilation.

- mono/mini/mini-generic-sharing.c
- mono/tests/Makefile.am
- mono/tests/rgctx-thread-static.cs
Initialize the klass containing the field to be accessed, rather than the class of the method from where we are accessing.
> [mini] Initialize correct class for tls fields

- sdks/wasm/sdk/Mono.WebAssembly.Build/Mono.WebAssembly.Build.targets
- sdks/wasm/sdk/Mono.WebAssembly.Build/WasmLinkAssemblies.cs
- Facilitate testing of in tree build during the browser tests.
> [wasm][sdk] Add functionality to override the bindings framework location

- mono/metadata/native-library.c
!! This PR is a copy of dotnet/runtime#33940,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes dotnet/runtime#33246
> [metadata] Skip symbol name mangling on non-Windows for netcore

- mcs/class/Mono.Posix/Mono.Unix/UnixEndPoint.cs
On windows, remote end point client will not return file name, but socket address size still isn't `0x02`.
So check empty file name after bytes readed.
> Refine UnixEndPoint to support Windows Unix socket

- mono/mini/debugger-agent.c
- mono/mini/debugger-engine.c
There was a race where a domain was being unloaded while debugger would access it. A domain was only removed from the 'appdomains_list' as a very last step. The domain was already invalid to access at this point (locks freed for example).
Worse, images would be unloaded if only referenced by that domain. All places the debugger iterates domains hold the loader lock. The loader lock is acquired by the domain unloading process, so as long as a domain is not unloading when we access it inside of the loader lock we are safe.
> Do not access unloading domains in debugger

- mono/metadata/icall.c
- mono/mini/mini-exceptions.c
- mono/utils/mono-threads-windows.c
- mono/utils/mono-threads.h
!! This PR is a copy of dotnet/runtime#34005,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When hitting stackoverflow on Windows, the amount of stack available to exception handler is too small. Windows doesn't support alt stack as other platforms, but there is a way to guarantee a certain amount of available stack during stack overflow exceptions using
SetThreadStackGuarantee.
Fix add support on Windows platforms including SetThreadStackGuarantee API to reserve space needed to handle …
> Add stack guarantee on Mono Windows to handle stack overflow.

- mono/mini/mini-llvm.c
> [llvm] Disable running the llvm verifier by default, it was enabled by mistake, and it takes a long time.

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs
When the sessionId is null, don't send "null" but omit the field;  Canary does not permit "sessionId: null".
> [wasm][debugger]: Correctly handle null sessionId.

- mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
- mcs/class/Mono.Debugger.Soft/Test/dtest.cs
- mono/mini/debugger-agent.c
Fix suspend_policy that will be send to debugger-libs, because on debugger-libs we want to resume the VM only when it's suspended, but we were sending the wrong suspend_policy in the case of EVENT_KIND_VM_START and mono is started with suspend=y.
With this fix we can do this PR again: https://github.com/mono/debugger-libs/pull/264/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999375/
Related https://github.com/mono/debugger-libs/pull/302
> [debugger] Fix suspend_policy that will be send to debugger-libs

- mono/metadata/assembly-load-context.c
- mono/metadata/domain-internals.h
- mono/metadata/domain.c
- mono/metadata/icall-def-netcore.h
- mono/metadata/loader-internals.h
!! This PR is a copy of dotnet/runtime#34038,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This should enable creation of a collectible ALC from managed, though it will not actually unload properly when Unload is called. This should be enough to unblock Xamarin porting work.
If you think the `mono_alc_cleanup` work is just noise I can remove that, but I thought it helpful to check in to make future diffs clearer as I split it up with the LoaderAllocator work.
> [loader] Initial work to support ALC collectability

- mcs/class/corlib/System.IO/FileStream.cs
- mcs/class/corlib/System/Console.cs
We already suppress the finalization of the CStreamReader and CStreamWriter, but during shutdown, the underlying FileStream may be finalized which invalidates its access field which can lead to a crash.
Addresses https://github.com/mono/mono/issues/19005
Backport of #19137.
> [2020-02] [corlib] Suppress finalization of underlying console FileStreams

- mono/mini/mini-generic-sharing.c
- mono/tests/Makefile.am
- mono/tests/rgctx-thread-static.cs
Initialize the klass containing the field to be accessed, rather than the class of the method from where we are accessing.
> [2020-02][jit] Initialize correct class for tls fields (#19300)

- mono/mini/debugger-agent.c
- mono/mini/debugger-engine.c
There was a race where a domain was being unloaded while debugger would access it. A domain was only removed from the 'appdomains_list' as a very last step. The domain was already invalid to access at this point (locks freed for example).
Worse, images would be unloaded if only referenced by that domain. All places the debugger iterates domains hold the loader lock. The loader lock is acquired by the domain unloading process, so as long as a domain is not unloading when we access it inside of the loader lock we are safe.
Backport of #19299.
/cc @thaystg @UnityAlex
> [2020-02] Do not access unloading domains in debugger

- mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
- mcs/class/Mono.Debugger.Soft/Test/dtest.cs
- mono/mini/debugger-agent.c
Fix suspend_policy that will be send to debugger-libs, because on debugger-libs we want to resume the VM only when it's suspended, but we were sending the wrong suspend_policy in the case of EVENT_KIND_VM_START and mono is started with suspend=y.
With this fix we can do this PR again: mono/debugger-libs#264
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999375/
Related mono/debugger-libs#302
Backport https://github.com/mono/mono/pull/19317
> [2020-02] [debugger] Fix suspend_policy that will be send to debugger-libs

- mono/metadata/class-init.c
- mono/tests/Makefile.am
- mono/tests/dim-issue-18917.cs
The problem was a parent class overriding an interface that was already override by another interface.
Fix #18917
Backport of #18962.
> [2020-02] [dim] Class overriding interface method that was already override by another interface

- sdks/wasm/sdk/Mono.WebAssembly.Build/WasmLinkAssemblies.cs
- Causes build error if sdk path is not being overridden.
> [wasm][sdk] Remove Required attribute from Bindings Directory.

- mono/mini/mini-llvm.c
Backport of #19319.
/cc @vargaz
> [2020-02] [llvm] Disable running the llvm verifier by default, it was enabled by mistake, and it takes a long time.

- mono/metadata/custom-attrs.c
There are also a bunch of calls that return empty arrays, which in theory could be created in managed for a perf boost. However, it seems the Xamarin.Android team has mostly gotten rid of those calls and that optimization would complicate the code and require changes to our managed CustomAttribute implemented for both legacy and netcore, so I've opted to not check it in for now. If the empty calls continue to show up down the line, I can dig the code back up from my local branch and PR it separately.
If this is producing huge arrays and malloc continues to show up in the profile, consider https://github.com/dotnet/runtime/issues/32972. Even without that, this is a substantial improvement.
Backport of #19083.
/cc @CoffeeFlux @monojenkins
> [2020-02] Use GArray instead of GList when getting custom attributes from an image

- mono/metadata/image.c
- mono/metadata/metadata-internals.h
- mono/metadata/metadata.c
- mono/mini/mini-generic-sharing.c
Fixes https://github.com/mono/mono/issues/18127.
> [runtime] Allocate the memory for gshared gparams from image sets.

- mono/mini/method-to-ir.c
- mono/mini/mini-llvm.c
- mono/mini/mini.h
In normal llvm mode, these variables are marked as indirect and stored to a stack slot so the EH code can access them.
> [llvmonly] Avoid marking the rgctx/vtable variable indirect, its not needed.

- sdks/wasm/src/library_mono.js
Avoids the following error message when running with threading enabled:
```
Failed to execute 'decode' on 'TextDecoder': The provided ArrayBufferView value must not be shared.
```
> [Wasm] Fix string_decoder when running with threading enabled

- mcs/class/referencesource/mscorlib/system/resources/resourcemanager.cs
Fixes https://github.com/mono/mono/issues/19314.
> [wasm] Add a try-catch around GetCallingAssembly () calls in ResourceManager, it can fail on wasm aot.

- scripts/ci/run-jenkins.sh
This PR depends on https://github.com/mono/mono/pull/19355 to pass.
Without the above PR there are exceptions on TextDecoder
closes: https://github.com/mono/mono/issues/19356
> [wasm][tests] Reactivate the browser threads tests.

- mono/mini/debugger-engine.c
- mono/mini/debugger-engine.h
Adding static to ss_req_acquire and ss_req_count
Fixes #19389
Backport of #19390.
/cc @thaystg
> [2020-02] [debugger] Adding static to ss_req_acquire and ss_req_count

- mono/mini/llvm-jit.cpp
!! This PR is a copy of dotnet/runtime#34350,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>`EB.selectTarget ();` used to return `NULL` on arm64 (and hit an assert later)
Turns out it needs MArch on arm (e.g. `"aarch64"`) set. No idea why it doesn't use host arch by default on arm (but works on x86).
> [mono] Fix LLVM JIT on Arm64

- mono/mini/llvm-jit.cpp
!! This PR is a copy of dotnet/runtime#34368,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Turns out `llvm::Triple(llvm::sys::getDefaultTargetTriple()).getArchName()` doesn't work as expected on all targets so the only option is to set arch via defines.
NOTE: it accepts "x86-64", not "x86_64
> [mono] Fix setMArch, getArchName() doesn't work as expected

- sdks/ios/app/runtime.m
Starting with https://github.com/mono/mono/pull/16907 , the runtime ends in GC-Safe state (mode) after mono_jit_init_version() is called. mono_gc_init_finalizer_thread() expects the GC to not already be in safe mode.
> [ios][sdks] Fix finalizer thread init in coop-mode

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
Don't try to process commands for sessions without an execution context.
> [wasm][debugger] don't try to process commands for sessions without context

- mono/dis/main.c
- mono/metadata/appdomain.c
- mono/metadata/assembly-internals.h
- mono/metadata/assembly.c
- mono/metadata/mono-debug.c
- mono/mini/aot-runtime.c
- mono/mini/monovm.c
- tools/pedump/pedump.c
!! This PR is a copy of dotnet/runtime#34284,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/34273
While this specific issue only affects the preload hook, I've added the append option to all the installation functions since this seems like a generally useful capability, both for internal use and embedders.
@BrzVlad tested locally and confirmed this patch solves the problem.
> [loader] Add append option to loader hook installation functions

- mono/metadata/class-internals.h
- mono/metadata/class.h
!! This PR is a copy of dotnet/runtime#34436,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This is needed by Xamarin.Android to be able to round-trip with names fetched via reflection, as the only public API for this (`mono_type_get_name`) uses the IL format instead.
Fixes https://github.com/mono/mono/issues/19377
> [meta] Add mono_type_get_name_full to public API

- mono/metadata/class-internals.h
- mono/metadata/class.h
!! This PR is a copy of dotnet/runtime#34436,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This is needed by Xamarin.Android to be able to round-trip with names fetched via reflection, as the only public API for this (`mono_type_get_name`) uses the IL format instead.
Fixes https://github.com/mono/mono/issues/19377
Backport of #19414.
/cc @CoffeeFlux @monojenkins
> [2020-02] [meta] Add mono_type_get_name_full to public API

- sdks/wasm/src/library_mono.js
Since 3 days ago, Mono WebAssembly no longer works on Firefox. The error is `ReferenceError: SharedArrayBuffer is not defined`.
This PR adds a trivial fix.
cc @lewing - we're aiming for code complete for Blazor WebAssembly preview 4 tomorrow (Friday) so would be great if this was merged soon :)
> Fix Mono WebAssembly regression on Firefox

- mono/eglib/glib.h
- mono/mini/exceptions-amd64.c
16byte stack pointer alignment is only required in certain places by the ABI, so the assumption that it holds all the time is wrong (though, it passed CI 😅). We have to setup the frame properly, i.e. we have to ensure the stack pointer is properly aligned. That's what we have done previously too.
Regression of https://github.com/mono/mono/pull/17922
Fixes https://github.com/mono/mono/issues/18006
Backport of #18021.
/cc @lewurm
> [2019-12] [amd64] align application stack pointer in signal handler

- sdks/wasm/Makefile
> [wasm] Avoid including config.make into wasm/Makefile, its generated by one of the builds triggered by this Makefile.

- mcs/class/System.Windows.Forms/System.Windows.Forms/PropertyGrid.cs
for custom tabs.
when the mouse is on the native tab buttons, tooltips appear, and when on the custom tab buttons, then no
> [WinForms] Show ToolTips for PropertyTab`s buttons

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
Instead of surfacing the error to the browser log it return an empty result.  This means
hovering will only show a value if we found one.
> [wasm][debugger] Don't surface evaluation errors to the browser

- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/debugger-test.cs
Some frames were skipped in MonoProxy but we don't skip the frame_id, doing this the call_stack has a different position than it's in the real stack on mono side.
- changed the frame_id, so we will follow the frame_id from callstack even if we don't add all of them into the CallStack list in MonoProxy.
- added a test.
Fixes #19379
> [wasm][debugger] Fix wrong frame_id in call stack on MonoProxy

- mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs
Otherwise some stuff doesn't always get drawn.
Fixes https://github.com/mono/libgdiplus/issues/640, and probably other similar things.
> [WinForms] When double buffering, flush the buffered graphics

- scripts/ci/provisioning/freebsd.sh
pkg has been updated to 1.12+ which has an incompatible metadata format. Fix this by force bootstrapping pkg when necessary. Also perform some general cleanup and go back to the python3 metaport as 2020Q1 uses a sufficiently current Python for the metaport.
Should fix Jenkins CI.
> Fix for 2020Q1 FreeBSD pkg upstream, some cleanup.

- sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs
Should throw HttpRequestException instead of internal WebAssembly.JSException.
closes: https://github.com/mono/mono/issues/18780
> [wasm][http] Throw HttpRequestException not WebAssembly.JSException

- scripts/ci/provisioning/freebsd.sh
Fixes pkg bootstrap failing due to kernel mismatch in 2020Q1 quarterly branch.
> Fix for missing IGNORE_OSVERSION

- mcs/class/corlib/Test/System/TypeTest.cs
- mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/17735.
> [runtime] Fix Type.GetTypeCode () for generic enums.

- mcs/class/corlib/Test/System/TypeTest.cs
- mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/17735.
Backport of #19470.
> [3.2-wasm] [runtime] Fix Type.GetTypeCode () for generic enums.

- mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStripTextBox.cs
When set non-Empty Size to ToolStripTextBox it will appear with zero width, but must use width from size.
Windows example
Linux mono example
> [WinForms] Fix ToolStripTextBox Width

- mcs/class/System.Windows.Forms/System.Windows.Forms/PropertyGrid.cs
When Category Name match with Item name this GridItem will disappear
> [Winforms] PropertyGrid fix disappearing of items

- mcs/class/System.Windows.Forms/System.Windows.Forms/GridEntry.cs
When using implemeted ICustomTypeDescriptor with overrided SetValue(object component, object value) and there value reference will be changed even if new object`s fields will be equals then in line
current_changed = Object.Equals (properties[i].GetValue (propertyOwners[i]), value);
will not detected change cause of references of object in operands are not equal.
In usual ways references will be equal. So we compare old value ref with new value ref earlier.
In .net winforms do same. And also original winforms did not check CanConvertFrom whith type of editable object. So we do not need block with
converter.CanConvertFrom ((ITypeDescriptorContext)this, valueType))
> [Winforms] fix #18606 PropertyGrid edit with CustomTypeDescriptor

- mcs/class/System.Windows.Forms/System.Windows.Forms/Line.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/RichTextBox.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/TextControl.cs
1. Fix the line height calculated by `Line.RecalculatePasswordLine()`. Would have been roughly double what it should have been – line spacing includes the height of the line.
2. In RichTextBox, when parsing RTF, insert a character for the Quote special character tags rather than just printing a message on the console.
3. In TextControl `Document.Draw()`, fix the criteria for decrementing `end`. Could probably be improved further, but the previous had a problem because it could check with a point well off the bottom of the second to last line instead of its bottom. This probably arose because I had originally used `Line.Height` for just the height of the text in the line, and later decided that it should be the entire height including all spacing. The earlier behaviour would have been …
> [WinForms] Three small RichTextBox / TextControl fixes

- mcs/class/System.Windows.Forms/System.Windows.Forms/LinkLabel.cs
MeasureCharacterRanges handles the alignment correctly by itself.
This may have been to handle poor behaviour in libgdiplus, particularly when Pango text layout was not default.
This doesn't actually affect the alignment of the LinkLabel text, it affects where it clips the text when drawing, and where it thinks the links are. So what happens when non-TopLeft alignment is used is that text is only partially visible, and where the links interact with the mouse (and where their focus boxes are drawn) is offset.
> [WinForms] Fix LinkLabel drawing

- mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs
- mcs/class/System/System.Net.Security/SslStream.cs
Add BeginRead/BeginWrite/EndRead/EndWrite overloads back to SslStream and underlying implementation. Unlike the default implementation in Stream it allows parallel read along with parallel write using the standard TaskToApm pattern (https://github.com/dotnet/runtime/issues/33447). This reverts part of https://github.com/mono/mono/pull/17393 which could lead to deadlocks as reported in https://github.com/mono/mono/issues/18865.
Fixes #18865.
> Add BeginRead/BeginWrite/EndRead/EndWrite overloads back to SslStream

- mono/metadata/metadata.c
Fixes abort when PTR-FNPTR field signature is encountered.
I do not have a deep understanding of how the code in this area works,
but I have called the function that appears most consistent with how
other signatures are being handled.
Fixes #12098
Fixes #17113
Fixes #19433
> [metadata] Handle MONO_TYPE_FNPTR case in collect_type_images

- mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs
- mcs/class/System/System.Net.Security/SslStream.cs
Add BeginRead/BeginWrite/EndRead/EndWrite overloads back to SslStream and underlying implementation. Unlike the default implementation in Stream it allows parallel read along with parallel write using the standard TaskToApm pattern (https://github.com/dotnet/runtime/issues/33447). This reverts part of https://github.com/mono/mono/pull/17393 which could lead to deadlocks as reported in https://github.com/mono/mono/issues/18865.
Fixes #18865.
Backport of #19442.
/cc @steveisok @filipnavara
> [2020-02] Add BeginRead/BeginWrite/EndRead/EndWrite overloads back to SslStream

- mono/mini/mini-wasm-debugger.c
- mono/mini/mini-wasm.h
- sdks/wasm/src/driver.c
enable_debugging was already an int, with this change log_level
will remain at 1 by default but passing -1 will disable the log
spew
> [wasm][debugger] Wasm debug log level

- mono/metadata/icall-decl.h
- mono/metadata/icall.c
- sdks/wasm/src/driver.c
- Correctly marshal Intl.DateTimeFormat().resolvedOptions().timeZone information
/cc @pranavkm 
Thanks for the report and testing Pranav
> [wasm][bcl][zoneinfo] Fix local zone info marshaling

- mono/metadata/icall-decl.h
- mono/metadata/icall.c
- sdks/wasm/src/driver.c
- Correctly marshal Intl.DateTimeFormat().resolvedOptions().timeZone information
/cc @pranavkm 
Thanks for the report and testing Pranav
Backport of #19493.
/cc @lewing @kjpou1
> [3.2-wasm] [wasm][bcl][zoneinfo] Fix local zone info marshaling

- mono/mini/mini-wasm-debugger.c
- mono/mini/mini-wasm.h
- sdks/wasm/src/driver.c
enable_debugging was already an int, with this change log_level
will remain at 1 by default but passing -1 will disable the log
spew
Backport of #19479.
/cc @lewing
> [3.2-wasm] [wasm][debugger] Wasm debug log level

- mcs/class/corlib/Test/System.IO/DirectoryTest.cs
- mcs/class/corlib/Test/System.IO/PathTest.cs
- mono/metadata/w32file.c
- sdks/wasm/tests/browser/src/BrowserTestSuite/issues-spec.js
- sdks/wasm/tests/browser/src/IssuesTestSuite/IssuesTestSuite.cs
- Modify IO file to assign backslash to alternate directory separator by default
- Add tests for issue https://github.com/mono/mono/issues/18933
closes: https://github.com/mono/mono/issues/18933
> [wasm][bcl] Handle correctly backslash in file name

- mcs/class/corlib/Test/System.IO/DirectoryTest.cs
- mcs/class/corlib/Test/System.IO/PathTest.cs
- mono/metadata/w32file.c
- sdks/wasm/tests/browser/src/BrowserTestSuite/issues-spec.js
- sdks/wasm/tests/browser/src/IssuesTestSuite/IssuesTestSuite.cs
- Modify IO file to assign backslash to alternate directory separator by default
- Add tests for issue https://github.com/mono/mono/issues/18933
closes: https://github.com/mono/mono/issues/18933
Backport of #19488.
/cc @lewing @kjpou1
> [3.2-wasm] [wasm][bcl] Handle correctly backslash in file name

- sdks/wasm/Makefile
> [wasm] Remove .stamp-build-debugger-test-app, the app can always be built.

- sdks/wasm/Makefile
> [3.2-wasm] [wasm] Remove .stamp-build-debugger-test-app, the app can always be built.

- sdks/wasm/ProxyDriver/TestHarnessStartup.cs
Force a language on the test harness, fixes the test failures on https://github.com/mono/mono/pull/19490
> [wasm][debugger] explicitly pass --lang=en_US for debugger tests

- sdks/wasm/ProxyDriver/TestHarnessStartup.cs
Force a language on the test harness, fixes the test failures on https://github.com/mono/mono/pull/19490
Backport of #19529.
/cc @lewing
> [3.2-wasm] [wasm][debugger] explicitly pass --lang=en_US for debugger tests

- mono/mini/mini-wasm-debugger.c
- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/debugger-test.cs
- sdks/wasm/src/library_mono.js
- As object properties, we return a `Target` which has the signature of
the delegate target.
Fixes #19382
> [wasm][debugger] Show signature for delegate, or target, if available

- mono/metadata/assembly.c
!! This PR is a copy of dotnet/runtime#34877,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
> [runtime] Try to load assemblies from bundles on netcore before trying other methods, the ALC might not be initialized yet.

- mono/mini/mini-windows.c
- mono/utils/mono-context.c
- mono/utils/mono-threads-windows.c
- mono/utils/win64.asm
Hard to repro and very infrequent crash. Have been analyzing a couple of crash dumps from retail devices getting different crashes related to vtable "corruption" on Windows x64. After some deeper analysis it turns out the object instance has been forwarded by GC (object vtable pointers lowest bit set to 1), but object still holds tagged vtable. This will then cause misaligned reads, getting back random values and pointers from vtable on next object access.
After some further analyzing it turns out that LLVM codegen and some specific generic vt arrays lowering can cause optimized mem copies using XMM registers. I have also identified scenarios where vt copies gets lowered into a c-runtime memcpy that in turn uses XMM registers as an optimization. Since Windows x64 currently don't include …
> Fix infrequent/random crashes on Windows x64 due to use of GC forwarded objects.

- mono/metadata/class-init.c
- mono/mini/iltests.il
- mono/mini/method-to-ir.c
According to ECMA, VES should add the following methods to arrays:
* A constructor that takes a sequence of int32 arguments, one for each dimension of the array, that specify the number of elements in each dimension beginning with the first dimension. A lower bound of zero is assumed.
* A constructor that takes twice as many int32 arguments as there are dimensions of the array. These arguments occur in pairs—one pair per dimension—with the first argument of each pair specifying the lower bound for that dimension, and the second argument specifying the total number of elements in that dimension.
* Get.
* Set.
* Address.
In Mono's case we only added the `ctor (int32, int32)` for rank 1 arrays if they were "jagged" array. Array with rank 1-4 executed an optimized code path always using the …
> Fix missing array ctor(int32,int32) test failures.

- mono/mini/debugger-agent.c
Remove the assert because we don't need to stop the debug if we cannot create the object when calling the constructor using invoke_method, if it's a DebuggerTypeProxy, we are not able to show the value of the DebuggerTypeProxy, but we still can show the Raw View, if it's not the case of DebuggerTypeProxy, we just cannot evaluate this expression, but we can continue the debug session.
Fix #19492
> [debugger] Remove assert when the DebuggerTypeProxy cannot be instantiated

- mcs/class/corlib/System.Runtime.InteropServices.RuntimeInformation/RuntimeInformation.cs
Following the guidance in https://github.com/dotnet/runtime/issues/33328
Change OSPlatform to BROWSER for wasm runtimeArchitecture.
> Change OSPlatform for wasm to "BROWSER" rather than "WEBASSEMBLY"

- mono/metadata/jit-icall-reg.h
- mono/mini/decompose.c
- mono/mini/jit-icalls.c
- mono/mini/jit-icalls.h
- mono/mini/method-to-ir.c
- mono/mini/mini-runtime.c
!! This PR is a copy of dotnet/runtime#34949,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>These opcodes have the same effect as their non-_un_ counterpart, since floats are always signed. This means that applying a fconv.ovf.i8.un to a negative float, will result in a negative integer, despite the unsigned suffix (tested against coreclr).
Fixes https://github.com/dotnet/runtime/issues/34084
> [jit] Add support for fconv.ovf.*.un opcodes

- mcs/class/corlib/System.Runtime.InteropServices.RuntimeInformation/RuntimeInformation.cs
Following the guidance in https://github.com/dotnet/runtime/issues/33328
Change OSPlatform to BROWSER for wasm runtimeArchitecture.
Backport of #19482.
/cc @marek-safar @lewing
> [3.2-wasm] Change OSPlatform for wasm to "BROWSER" rather than "WEBASSEMBLY"

- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/debugger-driver.html
- sdks/wasm/debugger-test.cs
- sdks/wasm/src/library_mono.js
* Disable the Loaded: messages, they are not very useful.
* Add a Dotnet-test.setBreakpointByMethod protocol extensions to the proxy to set breakpoints in specific methods during testing.
* Add a new sample debugger test using the setBreakpointByMethod API.
* Remove some unrelated changes.
* Restore logging.
* Disable a log message which is printed when a pdb file is missing.
> [3.2-wasm][wasm] Debugger test improvements. (#19499)

- mono/eglib/gfile-posix.c
- mono/metadata/icall.c
- mono/metadata/w32file-unix.c
- mono/metadata/w32handle.c
- mono/metadata/w32process-unix.c
- mono/metadata/w32socket.c
- mono/mini/branch-opts.c
- mono/mini/cfold.c
- mono/mini/method-to-ir.c
- mono/mini/mini-wasm-debugger.c
- mono/sgen/sgen-nursery-allocator.c
- mono/unit-tests/test-mono-callspec.c
!! This PR is a copy of dotnet/runtime#35053,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Based on a recent PoliCheck tool run on the code base, there were some words in the code which weren't compliant. List of Mono bugs here : 
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2Fweb%2Fqr.aspx%3Fpguid%3D0bdbc590-a062-4c3f-b0f6-9383f67865ee%26qid%3Da5547394-def7-4a3d-ae81-fe8480583539&data=04%7C01%7Csampatel%40microsoft.com%7C0f0f005f4bf4422e7d5f0 …
> Minor changes - Update specific words in mono code base to be PoliCheck/TSA compliant

- mono/metadata/assembly-load-context.c
- mono/metadata/assembly.c
- mono/metadata/loader-internals.h
- mono/metadata/mono-private-unstable.h
- mono/metadata/object-internals.h
!! This PR is a copy of dotnet/runtime#34601,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>After talking with @lambdageek , we decided we wanted the public API for ALCs to just use gchandles instead of a native struct and to handle conversion within the runtime.
This PR takes that approach, exposing the managed ALC fields to the runtime for cheap conversion and adding `mono_assembly_load_full_alc` and preload hook V3 to the unstable headers.
I considered trying to do something fancier …
> [meta] Mono ALC embedding primer

- mono/mini/iltests.il
- mono/mini/interp/interp.c
- mono/mini/method-to-ir.c
mono_array_full_new_checked and mono_array_full_new (which is marked as
a MONO_API function) both take two pointers to buffers containing
lengths and lower bounds. mono_array_new_n_icall can split the incoming
parameter list in two before forwarding the results to
mono_array_full_new_checked, so mono_array_full_new_checked was
receiving two buffers containing interleaved lower bounds and lengths.
ECMA-335 states that array constructors that specify both lower bounds
and lengths interleave these values. Deinterleave these in method_to_ir.
Add some tests to iltests.il that verify that multidimensional arrays
with custom lower bounds work.
Fixes https://github.com/dotnet/runtime/issues/34377
Fixes https://github.com/dotnet/runtime/issues/34378
Fixes …
> [mono] Fix multidimensional array construction when using programmer-specified lower bounds.

- LICENSE
It should be MIT, not MIT X11.
Fixes https://github.com/mono/mono/issues/18133
> Fix name of MIT license in LICENSE file

- mono/metadata/metadata-verify.c
- mono/metadata/verify-internals.h
- mono/metadata/verify.c
Helps fix issue: https://issuetracker.unity3d.com/issues/unity-crashes-when-opening-the-project
We were hitting a crash were a corrupted dll would get loaded and then hit an assert later on when something tried to use it. The verifier suite would correctly identify the dll as corrupt but it was impossible to turn on just the PE verification. I've added a new PE only mode above "off" to allow for just the PE verifier to be used instead of the larger verification suite.
> Add ability to turn on just the portable executable verifier.

- mono/mini/mini-wasm-debugger.c
- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Makefile
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/debugger-array-test.cs
- sdks/wasm/debugger-driver.html
- sdks/wasm/debugger-test.cs
- sdks/wasm/other.js
- sdks/wasm/sample.cs
- sdks/wasm/src/library_mono.js
- This was prompted by vscode/vs requiring this for array expansion.
- It runs a given js function string, on a given object id.
- We handle the case for dotnet object ids.
Implementation:
- We build a proxy object that reflects the details of the real dotnet object/array
- And run the js function on that proxy object
- Then if `returnByValue` was requested, the result is returned as-is
- Else we cache that object, with a new special object id (`dotnet:cfo_res:..`),
and return that id in the response.
- Subsequently, we would get `Runtime.getProperties` request on this new object id
- And a `Runtime.releaseObject` request, to free that function result.
- All this is handled currently
Tests:
- A few tests were added which invoke `callFunctionOn`, on JS objects, and checks the result
- And …
> [wasm][debugger] Support array expansion in VS via callFunctionOn

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
The important part of this change is to make sure we *always* respond to the evaluate call otherwise they will get stuck in limbo.  The second part is to generally pass anything we don't understand on to the browser and let let it respond (this tends to produce error messages in the format the browser expects)
The impetus for the pr is to make the watch window and hovering Visual Studio and Visual Studio Code not show confusing errors when the watch variables are out of scope
> [wasm][debugger] Fix command response handling

- mono/mini/mini-wasm-debugger.c
- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Makefile
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/debugger-array-test.cs
- sdks/wasm/debugger-driver.html
- sdks/wasm/debugger-test.cs
- sdks/wasm/other.js
- sdks/wasm/sample.cs
- sdks/wasm/src/library_mono.js
- This was prompted by vscode/vs requiring this for array expansion.
- It runs a given js function string, on a given object id.
- We handle the case for dotnet object ids.
Implementation:
- We build a proxy object that reflects the details of the real dotnet object/array
- And run the js function on that proxy object
- Then if `returnByValue` was requested, the result is returned as-is
- Else we cache that object, with a new special object id (`dotnet:cfo_res:..`),
and return that id in the response.
- Subsequently, we would get `Runtime.getProperties` request on this new object id
- And a `Runtime.releaseObject` request, to free that function result.
- All this is handled currently
Tests:
- A few tests were added which invoke `callFunctionOn`, on JS objects, and checks the result
- And …
> [3.2-wasm] [wasm][debugger] Support array expansion in VS via callFunctionOn

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
The important part of this change is to make sure we *always* respond to the evaluate call otherwise they will get stuck in limbo.  The second part is to generally pass anything we don't understand on to the browser and let let it respond (this tends to produce error messages in the format the browser expects)
The impetus for the pr is to make the watch window and hovering Visual Studio and Visual Studio Code not show confusing errors when the watch variables are out of scope
Backport of #19590.
/cc @lewing
> [3.2-wasm] [wasm][debugger] Fix command response handling

- mono/mini/mini-wasm-debugger.c
- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/debugger-array-test.cs
- sdks/wasm/debugger-evaluate-test.cs
- sdks/wasm/src/library_mono.js
- This also fixes the same thing for `evaluateOnCallFrame`
- And, showing type arguments in generic method names
> [wasm][debugger] Fix enumerating for `this` on valuetypes 

- mono/mini/mini-amd64.c
!! This PR is a copy of dotnet/runtime#34814,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>On all platforms, OP_TAILCALL copies the arguments (that are passed on the stack) from the param area in the current frame, to the param area in the caller frame, meaning that it expects the arguments to be passed normally on the stack. However, on amd64, mono_arch_emit_call was storing these arguments directly in the param area of the caller (EMIT_NEW_ARGSTORE), instead of the param area of the …
> [amd64] Fix tailcall with arguments passed on stack

- sdks/wasm/packager.cs
- sdks/wasm/src/linker-preserves.xml
Fixes https://github.com/mono/mono/issues/19594.
> [wasm] Preserve MonoPInvokeCallback using a linker xml descriptor.

- mono/mini/mini-wasm-debugger.c
- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/debugger-array-test.cs
- sdks/wasm/debugger-evaluate-test.cs
- sdks/wasm/src/library_mono.js
- This also fixes the same thing for `evaluateOnCallFrame`
- And, showing type arguments in generic method names
Backport of #19626.
/cc @lewing @radical
> [3.2-wasm] [wasm][debugger] Fix enumerating for `this` on valuetypes 

- mcs/class/corlib/Test/System/StringTest.cs
- mcs/class/corlib/corefx/CompareInfo.cs
Backport of https://github.com/mono/mono/issues/18978 without the test.  Fixes the Replace call but removes the test for the moment.
> [3.2-wasm] Backport wasm index fix

- mcs/class/System.Runtime.Serialization/ReferenceSources/JsonFormatWriterGenerator_static.cs
Fixes #19466 
It was discovered that the `specified cast is not valid` was being thrown because of an attempt to cast an object of type `ResourceType` as `XmlDictionaryString`. However, `ResourceType` is of type `Enum`, so instead a check for type `XmlDictionaryString` is performed before resorting to getting the object's name via `ToString()`.
To test code changes, I needed to side install msbuild into my mono install via
`make -j` in `<msbuild_repo>`
`<msbuild_repo>/install-mono-prefix.sh <local-mono-install>`
And then in the Wasm project directory 
`<local-mono-install>/bin/msbuild Wasm.csproj`
```
$ dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview3.20168.3
$ dotnet new blazorwasm -o Wasm
$ cd Wasm
$ msbuild Wasm.csproj
```
``` …
```
> [System.Runtime.Serialization] Work around `specified cast is not valid`

- mcs/class/System.Windows.Forms/System.Windows.Forms/ListView.cs
When ListView.VirtualMode = true GetItemAt should not access items collection directly to
get bounds of ListViewItem. Otherwise, method OnRetrieveVirtualItem will be called.
Which costs a lot of time.
> [WinForms] Fix ListView GetItemAt high load

- mono/metadata/assembly-load-context.c
- mono/metadata/mono-private-unstable.h
!! This PR is a copy of dotnet/runtime#35191,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Also formatting fixes to the unstable header.
We can just return the stored GCHandle for the default ALC because it's both strong and should never change.
cc: @garuma
> [meta] Add embedding API function to get the default ALC

- mono/mini/mini-wasm-debugger.c
- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/debugger-evaluate-test.cs
- sdks/wasm/src/library_mono.js
.. including generic, and async methods. This fixes `hover` for valuetype locals.
> [wasm][debugger] Fix `evaluateOnCallFrame` for valuetype locals

- mcs/class/System.Runtime.Serialization/ReferenceSources/DataContractSerializerExtensions.cs
Prevents NullReferenceException in SurrogateProviderAdapter which occurred when SurrogateProviderAdapter is constructed with a null ISerializationSurrogateProvider instance, which results in NullReferenceException in GetDataContractType, GetDeserializedObject and GetObjectToSerialize.
> Prevent NullReferenceException in SurrogateProviderAdapter

- mcs/class/System.Runtime.Serialization/ReferenceSources/JsonFormatWriterGenerator_static.cs
Fixes #19466 
It was discovered that the `specified cast is not valid` was being thrown because of an attempt to cast an object of type `ResourceType` as `XmlDictionaryString`. However, `ResourceType` is of type `Enum`, so instead a check for type `XmlDictionaryString` is performed before resorting to getting the object's name via `ToString()`.
To test code changes, I needed to side install msbuild into my mono install via
`make -j` in `<msbuild_repo>`
`<msbuild_repo>/install-mono-prefix.sh <local-mono-install>`
And then in the Wasm project directory 
`<local-mono-install>/bin/msbuild Wasm.csproj`
```
$ dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview3.20168.3
$ dotnet new blazorwasm -o Wasm
$ cd Wasm
$ msbuild Wasm.csproj
```
``` …
```
> [2020-02] [System.Runtime.Serialization] Work around `specified cast is not valid`

- mcs/class/System.Runtime.Serialization/ReferenceSources/JsonFormatWriterGenerator_static.cs
Fixes #19466 
It was discovered that the `specified cast is not valid` was being thrown because of an attempt to cast an object of type `ResourceType` as `XmlDictionaryString`. However, `ResourceType` is of type `Enum`, so instead a check for type `XmlDictionaryString` is performed before resorting to getting the object's name via `ToString()`.
To test code changes, I needed to side install msbuild into my mono install via
`make -j` in `<msbuild_repo>`
`<msbuild_repo>/install-mono-prefix.sh <local-mono-install>`
And then in the Wasm project directory 
`<local-mono-install>/bin/msbuild Wasm.csproj`
```
$ dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview3.20168.3
$ dotnet new blazorwasm -o Wasm
$ cd Wasm
$ msbuild Wasm.csproj
```
``` …
```
> [2019-12] [System.Runtime.Serialization] Work around `specified cast is not valid`

- mono/mini/debugger-agent.c
When a new thread is attached to the VM, the debugger will add it to the
`thread_to_tls` hash table. When that thread detaches, it will be
removed. Once the thread is attached, if a client is debugging, the
client can use the `CMD_THREAD_GET_FRAME_INFO` command to ask for
details about that thread.
This is a possibility that the thread detaches before the
`CMD_THREAD_GET_FRAME_INFO` command is processed, so the thread may not
exist the the `thread_to_tls` hash table any more.
This is a race condition, but is a valid state, so instead of asserting,
the debugger agent should indicate to the client that the thread no
longer exists, using `ERR_UNLOADED`.
> Prevent a possible assert in the debugger when a thread detaches

- mono/mini/method-to-ir.c
`mini_method_get ()` doesn't guarantee that `method->signature` is set.
Fixes a problem in https://github.com/mono/mono/pull/19624
/cc @lewing
> [jit] use helper to obtain method signature

- mono/mini/interp/transform.c
!! This PR is a copy of dotnet/runtime#35524,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Consider the following IL code pattern:
```
stloc.np 0
dup
stloc 1
```
When `stloc 1` instruction is processed, we know we have local 0 on the top of the stack so we can replace `dup/stloc` with `movloc 0 -> 1`. However, we need to make sure that the refcount for local 0 is increased so we don't prematurely kill instructions that store into this local (the `stloc.np` from above). This is needed …
> [interp] Fix tracking of local refcount when adding movloc opcode 

- mono/mini/debugger-agent.c
Remove the assert because we don't need to stop the debug if we cannot create the object when calling the constructor using invoke_method, if it's a DebuggerTypeProxy, we are not able to show the value of the DebuggerTypeProxy, but we still can show the Raw View, if it's not the case of DebuggerTypeProxy, we just cannot evaluate this expression, but we can continue the debug session.
Fix #19492 
Backport of #19542.
/cc @thaystg
> [2020-02] [debugger] Remove assert when the DebuggerTypeProxy cannot be instantiated

- mcs/class/System/System.Net/HttpConnection.cs
- mcs/class/System/System.Net/HttpListenerRequest.cs
Fixed #10435 
HttpListener already closes the Response object, closes the HTTP Client connection, and then sets the value of Response.StatusCode again. If so, an ObjectDisposedException is thrown.
```
Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
at System.Net.HttpListenerResponse.set_ContentLength64 (System.Int64 value) [0x00013] in <b4473693dd3c4d45883c574a53529fbe>:0
at MonoConsoleApp1.Program.Main (System.String[] args) [0x000f8] in <a66f6d7d417445dc9f89c691941ca70b>:0
at MonoConsoleApp1.Program.<Main> (System.String[] args) [0x0000c] in <a66f6d7d417445dc9f89c691941ca70b>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: …
```
> Fix if already send error to http client, do not callback.

- mono/mini/mini-wasm-debugger.c
- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/debugger-evaluate-test.cs
- sdks/wasm/src/library_mono.js
.. including generic, and async methods. This fixes `hover` for valuetype locals.
Backport of #19638.
/cc @lewing @radical
> [3.2-wasm] [wasm][debugger] Fix `evaluateOnCallFrame` for valuetype locals

- mcs/class/System/System.Net/HttpConnection.cs
- mcs/class/System/System.Net/HttpListenerRequest.cs
Fixed #10435 
HttpListener already closes the Response object, closes the HTTP Client connection, and then sets the value of Response.StatusCode again. If so, an ObjectDisposedException is thrown.
```
Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
at System.Net.HttpListenerResponse.set_ContentLength64 (System.Int64 value) [0x00013] in <b4473693dd3c4d45883c574a53529fbe>:0
at MonoConsoleApp1.Program.Main (System.String[] args) [0x000f8] in <a66f6d7d417445dc9f89c691941ca70b>:0
at MonoConsoleApp1.Program.<Main> (System.String[] args) [0x0000c] in <a66f6d7d417445dc9f89c691941ca70b>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: …
```
> [2020-02] Fix if already send error to http client, do not callback.

- packaging/MacSDK/msbuild.py
- Updates roslyn to `3.6.0-4.20224.5` to match msbuild
- This bump includes `NuGet.Build.Tasks` update to `5.6.0-rtm.6591`
> [2020-02] Bump msbuild to track mono-2019-12

- mono/mini/interp/interp.c
!! This PR is a copy of dotnet/runtime#35778,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Wasm has control flow limitations which don't go well with gotos. Move label outside of main loop because it translates to very poor wasm code. Other gotos don't seem to negatively impact instruction dispatch code, so leave them alone, for now ..
> [interp] Move label outside of main loop

- mono/metadata/mono-private-unstable.h
!! This PR is a copy of dotnet/runtime#35515,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>We can't have GLib types in public headers. Oops.
There is potentially still an issue with `mono_alc_get_default_gchandle` not being exported, but that can wait for later.
cc: @garuma
> [runtime] Mono ALC embedding: use public types, correct hook signature

- mono/arch/s390x/s390x-codegen.h
- mono/metadata/debug-mono-ppdb.c
- mono/mini/cpu-s390x.md
- mono/mini/debugger-agent.c
- mono/mini/exceptions-s390x.c
- mono/mini/mini-s390x.c
- mono/mini/mini-s390x.h
- mono/mini/tramp-s390x.c
- mono/mini/unwind.c
- mono/utils/mono-hwcap-s390x.c
- mono/utils/mono-hwcap-vars.h
* Add soft debugger support to s390x
- Implement the sdb trampoline
- Big-endian fixes for ppdb debugger:
- Fix utf16 strings
- Fix decoding of ImageDebugDirectory structures
- New implementation of OP_SEQ_POINT
- Enable successful unwind by defining markpoints
- Implement mono_arch_setup_resume_sighandler_ctx
- Implement unwind ops in epilog
* Fix delegate-invoke processing
- Handle up to 10 parameters
- Use sigparam information to correctly "slide" parameters
* Fix floating point negative zero for s390x
- Add a new instruction for use in OP_RxCONST -0
- Check for -0 in constant
* Minor indentation fixes
* Fix atomic add implementation
* Check for additional hardware facilities
> Add soft debugger support to s390x

- mono/mini/interp/interp.c
!! This PR is a copy of dotnet/runtime#35778,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Wasm has control flow limitations which don't go well with gotos. Move label outside of main loop because it translates to very poor wasm code. Other gotos don't seem to negatively impact instruction dispatch code, so leave them alone, for now ..
Backport of #19696.
/cc @lewing @monojenkins
> [3.2-wasm] [interp] Move label outside of main loop

- sdks/wasm/DebuggerTestSuite/Support.cs
- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- For column=0 requests only set and return the best match
- Merge js/html locations into the response so that they don't appear to be unbound
- Handle the possibility of multiple documents source files matching the regex but only use the best match from each
> [wasm][debugger] Rework setBreakpointByUrl location handling

- mono/mini/mini-arm.c
In get_call_info, IS_HARD_FLOAT is checked to switch between using the FP registers and the GP registers. This was not done in arg_get_storage, which was always using the hard float registers. This would mean parameters to the native trampoline wouldn't get copied correctly, and return values would be incorrect as well.
I can't find a way to add this to tests, since no softfp test systems seem to be built. I'm working on testing the use cases I can think of on my softfp system just to be sure.
Any assignments to type RegTypeHFA were locked behind a IS_HARD_FLOAT check as well, so I think its safe to modify that case too.
Fixes #14591
> [interpreter] Fix incorrect arg storage for arm softfp interpreter

- sdks/wasm/DebuggerTestSuite/Tests.cs
When we moved debugger tests out into more classes, this created more test collections and by default xunit runs them in parallel. This is likely causing more flaky test failures in the linux wasm lane.
cc @radical
> Disable per-collection parallelism in debugger tests

- mono/metadata/threads.c
- mono/utils/mono-threads-posix.c
!! This PR is a copy of dotnet/runtime#35907,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>1) Use `HostArch` for AppBuilder tasks 
2) Remove `tkill` for Android 32bit since it's not available in recent Android NDKs anymore.
> [mono] Fix 32bit Android build

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/src/library_mono.js
in the case when we aren't attaching we can get the list of loaded files directly from the console.debug event rather than waiting for the browser to respond to the get_loaded_files request.
> [wasm][debugger] Get loaded files without having a round trip

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
We were sending resolved events for setBreakpointByUrl request not just when they were 
the result of a scriptParsed event.  This fixes that and hopefully fixes breakpoint binding in VS.
In slight chance that the bp is what triggered the store load we also delay adding the request
to the context until after the load is finished so that it won't be included in any resolution events while loading.
> [wasm][debugger] Only send resolved events on load

- mono/mini/aot-runtime-wasm.c
- mono/mini/interp/interp.c
Fixes https://github.com/mono/mono/issues/19684.
> [interp] Fix memory overwrite during pinvoke r4 parameter passing.

- mono/metadata/object-offsets.h
- mono/mini/exceptions-x86.c
- mono/mini/interp/interp-internals.h
- mono/mini/interp/transform.c
- mono/mini/mini-x86.c
- mono/mini/mini-x86.h
- mono/mini/tramp-x86.c
- mono/tests/Makefile.am
This mainly consists of a trampoline that is used when calling from interp into native code, as well as the call convention logic that initializes the CallContext structure (which is passed to the trampoline). On other platforms we also have a single trampoline used when entering interpreter code. That trampoline works in a similar way and its purpose is to avoid compilation of all possible interp entry signatures, which is problematic on full aot scenarios. Given the interp x86 support is currently provided for android, we can avoid using that trampoline for now and use the per signature jit compiled interp_in_wrappers instead.
The few disabled interp tests are the same as on amd64.
We only support pinvoke into cdecl functions.
> [interp] Add x86 support

- mono/utils/mono-sigcontext.h
PT_NIP and friends are in this kernel header, but glibc includes it
somewhere in the chain implicitly. musl doesn't. Fix that.
> Fix musl PowerPC build

- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
We were sending resolved events for setBreakpointByUrl request not just when they were 
the result of a scriptParsed event.  This fixes that and hopefully fixes breakpoint binding in VS.
In slight chance that the bp is what triggered the store load we also delay adding the request
to the context until after the load is finished so that it won't be included in any resolution events while loading.
Backport of #19736.
/cc @lewing
> [3.2-wasm] [wasm][debugger] Only send resolved events on load

- mono/mini/dwarfwriter.c
- mono/mini/image-writer.c
- mono/mini/image-writer.h
When outputting DWARF code to start a compilation unit in .debug_info, the standard expect a 4-byte offset from the .debug_abbrev code. Mono has always output an offset of 0.
However, this doesn't work in every cases. When we have linux+fullaot, we link two object files (one from Mono, one from LLVM). Both have their .debug_abbrev section. If we use 0 as an offset, it seems possible that the linker will keep thinking that our offset is 0, no matter the circumstances. Since the offset is always 0, it can be using the wrong abbreviation table (i.e. the one from the LLVM assembly instead of the one from the Mono assembly). The consequence of this is that the linked file is not valid DWARF (dwarfdump and objdump will complain about invalid offsets). At best, some tools will be able to work …
> Emit DWARF debug_abbrev offset for compile units as a label instead of 0

- mono/mini/llvm-intrinsics.h
- mono/mini/llvm-jit.cpp
- mono/mini/mini-llvm-cpp.cpp
- mono/mini/mini-llvm-cpp.h
- mono/mini/mini-llvm.c
!! This PR is a copy of dotnet/runtime#36369,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>The llvm.x86.sse41.pmuldq intrinsic is no longer available as of
https://github.com/dotnet/llvm-project/commit/254ed028a4bd4fa81d0049d90e6ab23d704dd366.
This also adds a convenience wrapper for creating constant LLVM IR
vectors, up to 16 elements long, of arbitrary integral type.
Finally, fix a latent bug in init_function_pass_manager;
llvm::StringRef::size returns a value of type size_t, but the …
> Improve Sse41.Multiply compatibility with LLVM 9.

- scripts/ci/run-jenkins.sh
- sdks/wasm/DebuggerTestSuite/DateTimeTests.cs
- sdks/wasm/DebuggerTestSuite/Support.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
.. location info from the proxy, and then use `setBreakpointByUrl` to
set the breakpoint. And support `lineOffset` from the start of the method.
> [wasm][debugger][tests] Rework SetBreakpointInMethod, to get the

- mono/mini/aot-runtime.c
- mono/mini/simd-intrinsics-netcore.c
- mono/utils/mono-state.c
!! This PR is a copy of dotnet/runtime#36435,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
```
/Users/alexander/dev/runtime/src/mono/mono/mini/aot-runtime.c:5647:13: warning: unused variable 'image' [-Wunused-variable]
```
```
/Users/alexander/dev/runtime/src/mono/mono/mini/simd-intrinsics-netcore.c:11:1: warning: no previous prototype for function 'mono_simd_intrinsics_init' [-Wmissing-prototypes]
```
```
/Users/alexander/dev/runtime/src/mono/mono/utils/mono-state.c:1230:1: warning: …
```
> Fix mono runtime build warnings when building iOS config

- mono/mini/debugger-agent.c
Removing some asserts and returning err_invalid_argument with an error message when it's possible.
Fixes https://github.com/mono/mono/issues/19651
> [debugger] Removing some asserts

- sdks/wasm/DebuggerTestSuite/Tests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsHelper.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/debugger-valuetypes-test.cs
- sdks/wasm/src/library_mono.js
- This fixes:
1. Check valuetype properties
2. Debugger.resume, over some code that updates that valuetype
3. That valuetype's properties show older values
> [wasm][debugger] Clear valuetypes cache on Debugger.resume

- mono/utils/mono-threads-posix.c
- mono/utils/mono-threads.c
- mono/utils/mono-threads.h
!! This PR is a copy of dotnet/runtime#36116,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/35908
Depends on https://github.com/dotnet/runtime/pull/34064 (which has the test case)
This adds a new function `mono_native_thread_main_thread_known` which returns `TRUE` when the `MonoNativeThreadId` (`pthread_t` on Linux) of the main thread is known.  On Linux the main thread is the one where `gettid () == getpid ()`.  There are two complications: …
> [Mono] Don't set thread name of main thread on Linux

- mono/mini/mini-generic-sharing.c
We share interp_in wrappers for different types of signatures if the corresponding params are equivalent. This was added in https://github.com/mono/mono/commit/5cbe93884798684efbb81abd79e0e2a170544b75. This was reusing some sharing mechanism used by gsharedvt. Those wrappers are shared with regard to managed->managed transitions so it takes additional freedoms, converting all valuetypes to ValueTuples instances. These can end up being marshalled differently from the initial struct so we can't use this valuetype sharing infrastructure in the interp_in_wrappers which can operate on native structs.
Fixes test_0_marshal_struct_delegate from pinvoke3.cs
> [interp] Don't share interp_in signatures for different valuetypes

- mcs/class/corlib/corert/RuntimeThread.cs
The only call site of RuntimeThread.InitializeThreadPoolThread() is in
ThreadPoolCallbackWrapper, and it needs to return a valid RuntimeThread
reference to prevent a NullReferenceException later on. So return
`new RuntimeThread (null)` instead of a null reference.
This fixes a wine-mono crash I have encountered in "ZUSI 3 - Aerosoft
Edition" (in ZusiDisplay), and it might fix mono bug #17994.
> [corlib] Improve RuntimeThread stub

- scripts/ci/run-jenkins.sh
- sdks/wasm/DebuggerTestSuite/DebuggerTestSuite.csproj
- sdks/wasm/DebuggerTestSuite/Support.cs
- sdks/wasm/DebuggerTestSuite/appsettings.json
- sdks/wasm/ProxyDriver/Program.cs
.. via the envvar `WASM_TESTS_ChromePath`.
This can also be set in an `appsettings.json` file next to the test
binaries, like:
```
{ "ChromePath": "</path/to/chrome/binary>" }
```
Also, prefer stable Chrome over Canary.
> [wasm][debugger][tests] Allow overriding which browser to use

- mcs/class/corlib/Makefile
As-is, a tarball created in Roslyn mode is missing the file charinfo.nlp, which mcs needs to build the classlib.
> Always include Unicode charinfo, so tar made in csc mode works in mcs mode

- mono/mini/aot-compiler.c
- mono/mini/interp/interp.c
- mono/mini/interp/interp.h
- mono/mini/mini-generic-sharing.c
Fixes https://github.com/mono/mono/issues/19801.
> [interp] Fix interp entry for methods with lots of arguments in llvmonly+interp mode.

- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
Before this change, pop-ing a vt from the stack was done in 2 opcodes, a MINT_POP (decrementing the stack) and the weird MINT_VTRESULT (decrementing the vtstack). However, optimizations could have removed both the initial loading of the value type on the stack as well as the MINT_POP, leaving MINT_VTRESULT underflowing the vtstack. Fix this and cleanup the code by pop-ing a value type from the stack in a single instruction.
> [interp] Add separate opcode for pop vt

- mono/metadata/native-library.c
!! This PR is a copy of dotnet/runtime#36788,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>The linker was removing the icu shim functions even exporting them. The unique solution that we found until now is to force the linking using the -u flag.
This is a temporary fix until we don't implement QCalls.
Fixes https://github.com/dotnet/runtime/issues/36685
> Fixing tests on android that uses Icu Shim Globalization

- mono/metadata/debug-mono-ppdb.c
Unity has a pdb with zero sequence points somehow. If a user added a reference to the library and then attempted to set a managed breakpoint mono would hit an assert and crash when it would attempt to decode this pdb.
Call stack would look like:
```
>	mono-2.0-boehm.dll!mono_ppdb_get_seq_points(_MonoDebugMethodInfo * minfo, char * * source_file, _GPtrArray * * source_file_list, int * * source_files, MonoSymSeqPoint * * seq_points, int * n_seq_points) Line 508	C
mono-2.0-boehm.dll!mono_debug_get_seq_points(_MonoDebugMethodInfo * minfo, char * * source_file, _GPtrArray * * source_file_list, int * * source_files, MonoSymSeqPoint * * seq_points, int * n_seq_points) Line 1093	C
mono-2.0-boehm.dll!get_source_files_for_type(_MonoClass * klass) Line 6920	C …
```
> Adding check to bypass decoding pdbs that have no sequence points.

- mono/metadata/class-internals.h
- mono/metadata/icall.c
- mono/metadata/marshal.c
- mono/metadata/object-internals.h
- mono/metadata/object.c
- mono/mini/aot-runtime.c
- mono/mini/interp/interp.c
- mono/mini/jit-icalls.c
- mono/mini/mini-arm64.c
- mono/mini/mini-runtime.c
- mono/mini/mini-wasm.c
- mono/mini/mini.h
Fixes https://github.com/dotnet/runtime/issues/34379.
> [jit] Return the compiled method and an unbox trampoline from ldvirtftn when calling ldvirtftn on a valuetype method.

- mcs/class/corlib/Makefile
As-is, a tarball created in Roslyn mode is missing the file charinfo.nlp, which mcs needs to build the classlib.
Backport of #19807.
> [2020-02] Always include Unicode charinfo, so tar made in csc mode works in mcs mode

- configure.ac
HAVE_STRUCT_SOCKADDR_IN6 needs to be defined to enable IPv6 features in
mono/metadata/w32socket.c.
Fixes TcpListener issues in wine-mono.
----
I've noticed ZusiDisplay fails under wine-mono while trying to use TcpListener, because of an exception that says something along the lines of "operation completed successfully" (I don't have the details right now, but I could reproduce again if you need more info).
It turned out that this was because the IPv6-related code in mono/metadata/w32socket.c is compiled conditionally. However, HAVE_STRUCT_SOCKADDR_IN6 was not defined during configure, even though my mingw cross-compile setup has that struct available. This PR adds a check for that struct's existence in the "Checks for Windows compilation" section of configure.ac.
I've only tested that …
> configure.ac: check for sockaddr_in6 on Win32

- mono/metadata/reflection.c
`Xamarin.Android` native runtime calls `mono_reflection_type_from_name`
and passes `NULL` as the `image` parameter.  The parameter is then
propagated all the way to `_mono_reflection_get_type_from_info` where,
in case the assembly isn't loaded yet, it is used to obtain base
directory of the assembly.  However, since the `image` parameter is
`NULL` in our case, attempt to dereference it causes a segfault:
libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4c0 in tid 11029 (ompanyname.app3), pid 11029 (ompanyname.app3)
crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
/system/bin/tombstoned: received crash request for pid 11029
crash_dump64: performing dump of process 11029 (target tid = 11029)
DEBUG   : *** *** *** *** *** *** *** *** *** *** …
> [reflection] Check whether a pointer is valid before dereferencing

- mono/metadata/reflection.c
`Xamarin.Android` native runtime calls `mono_reflection_type_from_name`
and passes `NULL` as the `image` parameter.  The parameter is then
propagated all the way to `_mono_reflection_get_type_from_info` where,
in case the assembly isn't loaded yet, it is used to obtain base
directory of the assembly.  However, since the `image` parameter is
`NULL` in our case, attempt to dereference it causes a segfault:
libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4c0 in tid 11029 (ompanyname.app3), pid 11029 (ompanyname.app3)
crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
/system/bin/tombstoned: received crash request for pid 11029
crash_dump64: performing dump of process 11029 (target tid = 11029)
DEBUG   : *** *** *** *** *** *** *** *** *** *** …
> [2020-02] [reflection] Check whether a pointer is valid before dereferencing

- mono/mini/dwarfwriter.c
- mono/mini/image-writer.c
- mono/mini/image-writer.h
When outputting DWARF code to start a compilation unit in .debug_info, the standard expect a 4-byte offset from the .debug_abbrev code. Mono has always output an offset of 0.
However, this doesn't work in every cases. When we have linux+fullaot, we link two object files (one from Mono, one from LLVM). Both have their .debug_abbrev section. If we use 0 as an offset, it seems possible that the linker will keep thinking that our offset is 0, no matter the circumstances. Since the offset is always 0, it can be using the wrong abbreviation table (i.e. the one from the LLVM assembly instead of the one from the Mono assembly). The consequence of this is that the linked file is not valid DWARF (dwarfdump and objdump will complain about invalid offsets). At best, some tools will be able to work …
> [2020-02] Emit DWARF debug_abbrev offset for compile units as a label instead of 0

- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
!! This PR is a copy of dotnet/runtime#37004,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When returning from a method we used to save the return value into frame->retval. We would then have separate opcodes for normal and void call and, depending on the type of call, we would access the retval and push it on the stack. In case of valuetype returns, the value is not returned in the proper space so we have an additional MINT_VTRESULT that copies the return around in the caller frame. In …
> [interp] Remove return value indirection

- mono/mini/monovm.c
!! This PR is a copy of dotnet/runtime#37037,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This adds AppLocalIcu switch support on Mono. I also refactored GlobalizationMode to share the sources in between Mono and CoreCLR to avoid duplicating all the AppLocal and UseNls switches logic.
cc: @jkotas @thaystg @akoeplinger @tarekgh @ericstj
> Add ICU App-Local support on Mono

- sdks/wasm/packager.cs
Fix the packager not emitting debug symbols when ninja is enabled (e.g. when statically linking a bitcode file, still using the interpreter).
> [wasm] Fix packager not emitting debug symbols when ninja is enabled

- mono/metadata/assembly.c
- mono/metadata/custom-attrs.c
- mono/metadata/icall.c
- mono/metadata/metadata-internals.h
- mono/metadata/metadata.c
!! This PR is a copy of dotnet/runtime#36346,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Some info from https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder.getreferencedassemblies?view=netcore-3.1:
> This method does not return a complete list of referenced assemblies. For example, if you apply a custom attribute to the AssemblyBuilder, the assembly in which the attribute was defined is included in the list returned by this method. However, if you use a …
> [mono] Implement AssemblyBuilder.GetReferencedAssemblies

- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
clause_args can be set only from EH. This means that clause_args can be set only in the first executed frame, so there is no need to save it in the interp state. Also make sure we never check for it in the main_loop block, for normal calls and returns. Added exec_frame to the clause_args so we can detect whether a frame is the first frame invoked from EH. We can no longer use clause_args for this purpose because we no longer save it in the interp state.
Makes calls 6% faster
> [interp] Remove saving of clause_args from interp state

- mono/metadata/class-init.c
- mono/metadata/custom-attrs-internals.h
- mono/metadata/custom-attrs.c
!! This PR is a copy of dotnet/runtime#37172,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Our normal custom attribute lookup method may trigger loading.  This is undesirable during class initialization, for example.  For this reason, we have `mono_class_metadata_foreach_custom_attr` that scans a class for custom attributes without triggering loading.
This PR adds `mono_method_metadata_foreach_custom_attr` that does the same thing - looks for custom attributes on methods without causing …
> [mono][metadata] Add a method custom attribute scanning function

- mono/metadata/loader-internals.h
!! This PR is a copy of dotnet/runtime#37251,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>`libruntime-android.so` was just a random name I used for our test runner but since we need some name for `dlopen` (we can't use dlopen(NULL)) and to be shared between the test runner and Xamarin.Android let's switch to the XA name.
We could add an API for mono embedding to set desired name but 'm not sure if it's worth an effort now.
> [mono] Rename libruntime-android.so to libmonodroid.so

- mono/mini/mini-runtime.c
We must always have a call to mono_chain_signal() after mono_handle_native_crash(), in case signal chaining and crash chaining are both enabled.
> [runtime] Fix a case where crash chaining was broken

- mono/metadata/appdomain.c
- mono/metadata/metadata-internals.h
- mono/mini/aot-runtime.c
If its loaded later, its loading could trigger the execution of managed code i.e. loader callbacks on netcore.
> [runtime] Add a MONO_ASMCTX_INTERNAL assembly context.

- sdks/wasm/aot-profile/runtime.js
> [wasm] Make aot-profile/runtime.js work with different executables.

- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
* Move the JIT call related fields to a separate JitCallInfo structure.
* Compute calling convention information and store it into JitCallInfo
to avoid most type processing at call time.
> [interp] Optimize do_jit_call ().

- mono/mini/intrinsics.c
- mono/mini/memory-access.c
- mono/mini/method-to-ir.c
The intrinsic expansions for Unsafe.ReadUnaligned and
Unsafe.WriteUnaligned now use mini_emit_memory_load and
mini_emit_memory_store.
stind is now implemented in terms of mini_emit_memory_store; when used
during compilation of the the sgen nursery check wrapper,
mini_emit_memory_store will no longer longer emit a release fence when
storing a reference under the CLR memory model.
mini_emit_memory_load and mini_emit_memory_store also no longer
decompose unaligned loads/stores to explicit byte-wise memcpy move
sequences when targeting LLVM; the LLVM IR backend already converts
MONO_INST_UNALIGNED-flagged OP_LOAD*/OP_STORE* operations to LLVM memory
movement operations with alignment 1.
Should fix https://github.com/mono/mono/issues/19142.
> Start unifying unaligned memory access codepaths.

- mono/metadata/assembly-internals.h
- mono/metadata/assembly.c
- mono/metadata/class-internals.h
- mono/metadata/domain.c
- mono/metadata/icall.c
- mono/metadata/object-internals.h
- mono/metadata/object.c
- mono/metadata/runtime.c
- mono/mini/mini-exceptions.c
!! This PR is a copy of dotnet/runtime#36658,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/mono/mono/issues/16246
Contributes to https://github.com/mono/mono/issues/14788
The commits here should be reasonably chunked up, but a summary of what this accomplishes:
* Wires up OnResourceResolve
* Fixes our corlib satellite assembly check in netcore_load_reference (we were previously comparing System.Private.Corelib to System.Private.Corelib.resources, which does not …
> [runtime] Add remaining runtime events and fix some existing ones on netcore

- mono/mini/llvm-jit.cpp
!! This PR is a copy of dotnet/runtime#37458,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Partially fixes https://github.com/dotnet/runtime/issues/37449
```csharp
static ReadOnlySpan<byte> Arr
{
[MethodImpl(MethodImplOptions.AggressiveInlining)]
get => new byte[] {1, 2, 3, 4};
}
public static byte GetByte(int i) => Arr[0];
```
```asm
0000000000000000 <gram_GetByte__int_>:
<BB>:1
0:   48 83 ec 28             sub    $0x28,%rsp
4:   c5 f8 57 c0 …
```
> [mono] Append -sroa and -instcombine to LLVM-JIT pass manager

- configure.ac
- mono/utils/mono-os-mutex.h
Fixes #7167
The PR 3e8108ea6576b07de2a64528be18674683879189 introduced a deadlock on Alpine, making it impossible to even build mono. This PR reverts the setting of PTHREAD_PRIO_INHERIT when on Alpine.
Since GCC on Alpine doesn't provide a builtin macro to detect Alpine, I also added a #define in configure.ac.
> Fix deadlock on Alpine

- mcs/class/corlib/LinkerDescriptor/mscorlib.xml
- mono/metadata/monitor.c
- mono/metadata/threads.c
- mono/utils/mono-error-internals.h
> [wasm] Throw PlatformNotSupportedException instead of NotSupportedException when starting threads/waiting on monitors.

- mono/utils/mono-time.h
!! This PR is a copy of dotnet/runtime#37653,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Looks like it was accidentally removed in https://github.com/dotnet/runtime/pull/37457
> [mono] Add back sys/types.h include for clockid_t

- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
We had frame->ip used by EH and debugger and frame->state.ip used to save the ip of the next instruction to be executed when we return from the call. Since both represent more or less the same thing, unify them and avoid duplicate storing inside InterpFrame for each call. Because we use this ip with exception handling, we need to subtract 1 (similar to the jit) so the ip ends up being in the call instruction and not the next.
> [interp] Don't save ip twice in InterpFrame

- mono/metadata/icall-decl.h
- mono/metadata/icall-def-netcore.h
- mono/metadata/icall.c
!! This PR is a copy of dotnet/runtime#37920,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>The mono version has an extra type argument since it uses copy functions which are type specific.
Also add an elementCount > 0 check to avoid icall overhead if possible.
> Move the Buffer.Memmove<T> implementation into the runtime specific files since it requires a runtime specific BulkMoveWithWriteBarrier icall.

- mono/tests/libtest.c
- mono/tests/merp-crash-test.cs
Backport of https://github.com/mono/mono/pull/18532
> [2020-02] [merp] Add  tests for crashing via POSIX signal

- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/interp/transform.c
The order before was execution stack, vtstack, locals. The order now is locals, vtstack, execution stack. The reason for this is that in the future we would like to access arguments as locals, so the args pushed by the caller will end up being locals in the new frame. Additionally, this enables us to further compact the stack use in the future since a new frame will be allocated immediately following the current stack top. This also can also make calls up to 10% faster.
> [interp] Switch locals and execution stack order

- mcs/class/corlib/Mono/Runtime.cs
- mono/tests/merp-crash-test.cs
cc @kdubau
Backport of #19901.
/cc @alexischr
> [2020-02] [merp] Add API methods for getting hashcode/reason of last crash

- mono/mini/method-to-ir.c
!! This PR is a copy of dotnet/runtime#37544,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Mono's inliner is quite conservative (see https://github.com/dotnet/runtime/issues/34286) so we have to workaround some limitations, e.g.
```csharp
static ReadOnlySpan<byte> Arr => new byte[] {1, 2, 3, 4};
// access example:
byte GetByte(int i) => Arr[i];
```
```asm
0000000000000000 <gram_GetByte__int_>:
<BB>:1
0:   48 83 ec 18             sub    $0x18,%rsp
4:   c5 f8 57 c0             vxorps …
```
> [mono] Don't contribute to inline_const if ctor has AggressiveInlining

- mono/mini/debugger-agent.c
If there is a crash and the debugger is attached, we call mini_get_dbg_callbacks ()->send_crash().
That call ends up in mono_debugger_agent_send_crash which does all kinds of questionable stuff like trying to take the loader lock. Eventually it ends up calling socket_transport_send which tries to do a transition to GC Safe mode.
I inserted a MONO_ENTER_GC_UNSAFE in mono_debugger_agent_send_crash function and this fixes the assert.
Fixes #18794
Backport of #19191.
/cc @alexischr @thaystg
> [2020-02] [debugger] [coop] assertion when `socket_transport_send` called from the crash reporter

- mono/mini/interp/interp.c
Do overflow checks the same way we do it in the jit.
> [interp] Fix some warnings that show up on wasm

- configure.ac
- mono/metadata/threads.c
- mono/mini/mini-amd64.h
- mono/utils/Makefile.am
- mono/utils/mono-threads-sunos.c
!! This PR is a copy of dotnet/runtime#37560,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Summary:
* wire `$(Compiler)` in `mono.proj`, that comes from `eng/build.sh`.
* add configurations for illumos cross-compilation.
* set `-Werror=strict-prototypes` for `madvise` and `posix_madvise` introspection, which is used during the compilation.
* implement `mono-threads-sunos.c`.
* add some solaris-specific thread priority levels.
With this set of changes, `dotnet hwapp.dll` works with mono …
> Enable mono cross-build on SunOS-like OS

- sdks/wasm/packager.cs
Fixes https://github.com/mono/mono/issues/20002.
> [wasm] Use wasm-opt --strip-dwarf instead of wasm-strip which is missing from recent emscripten versions.

- mono/mini/dwarfwriter.c
- mono/mini/image-writer.c
- mono/mini/image-writer.h
Reverts mono/mono#19794
It breaks on iOS: https://github.com/mono/mono/issues/8806#issuecomment-648286417
> Revert "[2020-02] Emit DWARF debug_abbrev offset for compile units as a label instead of 0"

- mono/mini/mini-wasm.c
!! This PR is a copy of dotnet/runtime#38256,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>.
> [wasm] Make some libc stubs return an error instead of asserting.

- mcs/tools/wasm-tuner/InterpToNativeGenerator.cs
- mono/mini/wasm_m2n_invoke.g.h
Fixes tests in dotnet/runtime that currently fail with `WASM-ERR: CANNOT HANDLE COOKIE VL`.
> [wasm] Missing signatures for Microsoft.Extensions.EventSource

- configure.ac
- packaging/MacSDK/msbuild.py
Also, bumps roslyn to `3.7.0-1.20262.2`
> [master] Bump msbuild to track xplat-master

- mono/mini/exceptions-amd64.c
- mono/mini/exceptions-ppc.c
- mono/mini/exceptions-x86.c
- mono/mini/mini-exceptions.c
- mono/mini/mini-posix.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
- mono/mini/mini-windows.c
- mono/mini/mini.h
With this change, `mono_post_native_crash_handler` chains the crashing signal directly, instead of that having to happen after `mono_handle_native_crash` returns (which created a fragile repetitive code pattern). Finally, this way `mono_post_native_crash_handler` can also re-raise the signal right after chaining it. Since we remove our crashing signal handlers in `mono_handle_native_crash`, this should allow the OS to handle the signal as the final action.
TODO:
Fixes https://github.com/mono/mono/issues/19860
> [crashing] Improve crash chaining code

- mcs/mcs/settings.cs
The `mcs` help text says that it will use the value `4.5` by default for the option `-sdk:`, but it actually uses `4.x`. Fix the help text.
> [mcs] Fix help text for default value of -sdk: option

- mono/mini/jit-icalls.c
- mono/mini/mini-generic-sharing.c
This is needed in llvmonly mode, since that mode doesn't use the
fastpath lazy rgctx fetch trampolines.
> [jit] Add a fastpath to fill_runtime_generic_context ().

- sdks/wasm/Makefile
> [wasm] Remove obsolete --llvm-lto 1 argument, lto is already enabled when -s WASM_OBJECT_FILES=0 is used.

- mono/mini/exceptions-amd64.c
- mono/mini/exceptions-ppc.c
- mono/mini/exceptions-x86.c
- mono/mini/mini-exceptions.c
- mono/mini/mini-posix.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
- mono/mini/mini-windows.c
- mono/mini/mini.h
With this change, `mono_post_native_crash_handler` chains the crashing signal directly, instead of that having to happen after `mono_handle_native_crash` returns (which created a fragile repetitive code pattern). Finally, this way `mono_post_native_crash_handler` can also re-raise the signal right after chaining it. Since we remove our crashing signal handlers in `mono_handle_native_crash`, this should allow the OS to handle the signal as the final action.
Fixes https://github.com/mono/mono/issues/19860
> [2020-02] [crashing] Improve crash chaining

- mono/metadata/Makefile.am
- mono/metadata/class-accessors.c
- mono/metadata/class-init-internals.h
- mono/metadata/class-init.c
- mono/metadata/class-internals.h
- mono/metadata/class-setup-vtable.c
- mono/metadata/class.c
- mono/metadata/icall.c
- mono/metadata/metadata-internals.h
- mono/metadata/metadata.c
- mono/mini/interp/interp-internals.h
- msvc/libmonoruntime-common.targets
- msvc/libmonoruntime-common.targets.filters
!! This PR is a copy of dotnet/runtime#37516,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Covariant return implementation for Mono.
---
There are also a couple of general Mono fixes in here, too:
1. Interpreter support for `MONO_TYPE_FNPTR`  in `mint_type()`
2. a "signature assignment" mode for `mono_class_is_assignable_from` that doesn't treat `IntPtr[]` and `long[]` (or `int[]`) as interchangeable
3. support for unmanaged pointer comparisons in `mono_class_is_assignable_from`
4. …
> [metadata] Implement PreserveBaseOverridesAttribute and covariant returns support

- mono/mini/mini-exceptions.c
Entry to crash reporting is now more properly handled by mono_dump_start()
> [crashing] Remove redundant gatekeeping code

- sdks/wasm/DebuggerTestSuite/Support.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/DevToolsProxy.cs
- sdks/wasm/ProxyDriver/Startup.cs
- sdks/wasm/ProxyDriver/TestHarnessStartup.cs
Blazor's wrapper around the debug proxy no correctly propagates log settings to the proxy so users can configure the log verbosity they want.
> Re-enable verbose and trace logging in debug proxy

- mono/mini/interp/interp.c
- mono/mini/mini-trampolines.c
- mono/tests/delegate17.cs
!! This PR is a copy of dotnet/runtime#38449,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When we call a delegate that was bound to a specific function, don't do a virtual call.
Fixes mono/mono#19964
> [mini] Do a non-virtual call for bound delegates

- mono/metadata/cominterop.c
- mono/metadata/object-internals.h
- mono/tests/Makefile.am
- mono/tests/ccw-class-iface.cs
- mono/tests/libtest.c
This helps the Windows 10 v1903 SDK installer run under wine-mono. It uses _AppDomain::CreateInstance to retrieve an ObjectHandle, and then tries to call _ObjectHandle::Unwrap() using the auto-dual interface. With these patches that call succeeds and it gets further, though it does not completely run (likely due to insufficiency in wine-mono's wpfgfx).
This patch set does not implement accessor methods for public fields, mostly because the necessary bits are missing in MonoMethodBuilder, and plumbing them seems decidedly nontrivial.
> [cominterop] Support ClassInterfaceType and auto-dual class interfaces

- mono/metadata/exception.c
- mono/metadata/object-internals.h
This is an enhanced version of `mono_exception_get_managed_backtrace()` that takes an optional `const char *prefix` argument (to indent the stack-trace) and returns FALSE with a NULL backtrace on error.
> Add mono_exception_try_get_managed_backtrace().

- configure.ac
- mono/mini/exceptions-s390x.c
* Fix exception-s390x so mono_handle_native_crash() is called according to the changes made in #19973 
* Make roslyn the default compiler for s390x
> Fix #20022 - changing the signature of mono_handle_native_crash() for s390x

- mono/mini/dwarfwriter.c
https://github.com/mono/mono/pull/19794 broke on iOS. Analyzing the result showed that, while the assembly was generated as expected, the linked result was different. Analyzing the LLVM code (which triggered the original fix) seems to imply that, on Apple platforms, they will not generate a label for it, only doing the 0-offset as we were doing before. Therefore, match the LLVM behavior by bringing back our previous logic when targetting Mach, otherwise use the new way of doing things.
Fixes #8806 (again)
> Bring back previous debug_abbrev offset behavior on Apple platforms

- mono/mini/mini-exceptions.c
Entry to crash reporting is now more properly handled by mono_dump_start()
Backport of #20015.
/cc @alexischr
> [2020-02] [crashing] Remove redundant gatekeeping code

- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
!! This PR is a copy of dotnet/runtime#38569,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This greatly impacts Array.Clear performance, which is commonly used in blazor rendering.
> [interp] Intrinsify ClearWithReferences

- mono/metadata/icall-eventpipe.c
- mono/mini/mini-runtime.c
- msvc/libeventpipe.targets
- msvc/libeventpipe.targets.filters
!! This PR is a copy of dotnet/runtime#37756,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Continuation of https://github.com/dotnet/runtime/pull/34600, adding BufferManager into the library including unit tests, merging source files and additional library restructuring.
- Port EventPipeBuffer.
- Port EventPipeBufferList.
- Port EventPipeManager.
- Merge internals source files. Changed GETTER_SETTER to only mandate use of inlined functions when calling betweeen source files for …
> WIP: Port EventPipeBuffer, EventPipeBufferList, EventPipeBufferManager to Mono.

- mono/mini/interp/interp.c
- mono/mini/mini-trampolines.c
- mono/tests/delegate17.cs
!! This PR is a copy of dotnet/runtime#38449,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When we call a delegate that was bound to a specific function, don't do a virtual call.
Fixes mono/mono#19964
Backport of #20030.
> [2020-02] [mini] Do a non-virtual call for bound delegates

- mono/mini/mini-wasm.c
!! This PR is a copy of dotnet/runtime#38690,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This can by used by the xharness xunit runner to make sure async tasks are executed.
We also need to tweak how `ThreadPoolTaskScheduler` handles `TaskCreationOptions.LongRunning` since the usual mode of starting a new thread doesn't work, instead we treat it like the option wasn't set and queue the task on the threadpool.
> WASM: Add an internal method to pump the threadpool

- mcs/class/System.IO.Compression/System.IO.Compression.csproj
- mcs/class/System.IO.Compression/wasm_System.IO.Compression.dll.exclude.sources
- mcs/class/System.IO.Compression/wasm_System.IO.Compression.dll.sources
Throw PNS when using BrotliStream on WASM.
Unfortunately, we do not yet ship the native parts that would be required to use BrotliStream and there is a size penalty involved.
This does not fix https://github.com/mono/mono/issues/19952, but provides a better error message.
> [wasm][System.IO.Compression]: Disable BrotliStream on wasm.

- sdks/wasm/.gitignore
The top-level .gitignore has `[Dd]ebug*/` - which matches `sdk/wasm/DebuggerTestSuite/*`; to override, we need to add `!DebuggerTestSuite` to sdk/wasm/.gitignore
> Fix sdk/wasm/.gitignore to not-ignore the DebuggerTestSuite directory.

- mono/metadata/debug-internals.h
- mono/metadata/debug-mono-ppdb.c
- mono/metadata/image.c
- mono/metadata/image.h
- sdks/wasm/src/driver.c
- sdks/wasm/src/library_mono.js
Identify if an assembly has debug information and only download it to debug proxy if it has, this will speed up a lot the debugger initialisation.
> [wasm][debugger] Don't download unnecessary assemblies to DebugProxy

- mono/Makefile.am
- mono/eventpipe/Makefile
make dist fails as mono/eventpipe/Makefile never makes it into the tarball.
> Add eventpipe to dist files

- mono/metadata/debug-internals.h
- mono/metadata/image.c
- sdks/wasm/DebuggerTestSuite/Tests.cs
Considering DebugDirectoryEntryType = Reproducible as an assembly that has debug information.
Fixes #20075
> [wasm][debugger] DebugDirectoryEntryType = Reproducible means that has debug information

- mono/metadata/class-init.c
- mono/metadata/class-internals.h
- mono/metadata/class-setup-vtable.c
- mono/metadata/class.c
- mono/metadata/loader.c
- mono/mini/mini.c
!! This PR is a copy of dotnet/runtime#38735,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>The `MonoMethod:slot` width was accidentally changed in https://github.com/dotnet/runtime/commit/8465be73eb40a9c409dc8974b9d6b235a1b5158f
To compensate, we move 3 bits out to image properties
* `verification_success` - rarely used nowadays, protected by the image lock (like all image properties)
* `is_reabstracted`, `is_covariant_override_impl` - infrequently used features of newer C# language …
> [metadata] Move rarely used bits out of MonoMethod and give 1 bit back to MonoMethod:slot

- mono/metadata/icall-eventpipe.c
!! This PR is a copy of dotnet/runtime#38927,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
> Fix case where EventPipeInternal::Enable is called with NULL output file.

- mono/arch/riscv/riscv-codegen-test.c
- mono/arch/riscv/riscv-codegen.h
- mono/metadata/profiler-events.h
- mono/metadata/profiler-legacy.h
- mono/metadata/profiler-private.h
- mono/metadata/profiler.c
- mono/metadata/profiler.h
- mono/mini/cpu-riscv32.md
- mono/mini/cpu-riscv64.md
- mono/mini/ee.h
- mono/mini/exceptions-riscv.c
- mono/mini/mini-profiler.c
- mono/mini/mini-riscv.c
- mono/mini/mini-riscv.h
- mono/mini/tramp-riscv.c
- mono/tests/pinvoke-utf8.cs
- mono/utils/mono-hwcap-riscv.c
!! This PR is a copy of dotnet/runtime#38953,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>After https://github.com/dotnet/runtime/pull/38793 tweaked the license header on ~30K files, this cleans up after it, handling another ~1300, and adding license headers where they were missing in .cs files under libraries.  It also adds a default license header to the .editorconfig.
cc: @jkotas
> Fix remaining license headers

- mono/metadata/icall-eventpipe.c
!! This PR is a copy of dotnet/runtime#38989,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Due to issues on some platforms related to mono_delegate_to_ftnptr_impl, switch to use mono_runtime_delegate_invoke without need for delegate wrapper generation currently not supported on all platforms.
> Use mono_runtime_delegate_invoke in EventPipeInternal::CreateProvider.

- mono/metadata/appdomain.c
!! This PR is a copy of dotnet/runtime#37768,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>If strstr does not return 0, found is true, so instead of using !!, let's use != 0.
> Change double NOT operation to comparison to 0

- mono/metadata/class-internals.h
- mono/metadata/jit-icall-reg.h
- mono/metadata/marshal.c
- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
- mono/mini/aot-runtime.h
- mono/mini/interp/transform.c
- mono/mini/jit-icalls.c
- mono/mini/jit-icalls.h
- mono/mini/method-to-ir.c
- mono/mini/mini-runtime.c
!! This PR is a copy of dotnet/runtime#38728,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When we see a method tagged with `UnmanagedCallersOnlyAttribute` in an `ldtn` instruction, load a pointer to a native-to-managed wrapper instead of a pointer to the managed method.
See https://github.com/dotnet/csharplang/blob/master/proposals/functionpointers.md#systemruntimeinteropservicesunmanagedcallersonlyattribute
> [netcore][mono] Add support for UnmanagedCallersOnlyAttribute

- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/mini-runtime.c
!! This PR is a copy of dotnet/runtime#39045,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This tracks how many interpreter opcodes were executed as part of each method and reports them during runtime shutdown. Example output : 
```
Total executed opcodes 305590200
11% Opcounts 34261110, calls 81900, Method System.Text.Json.JsonWriterHelper:ToUtf8 (System.ReadOnlySpan`1<byte>,System.Span`1<byte>,int&,int&), imethod ptr 0x55f2d503d870
22% Opcounts 33980080, calls 849502, Method …
```
> [interp] Add debug option which reports the hottest methods

- sdks/wasm/DebuggerTestSuite/CallFunctionOnTests.cs
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
`silent` argument for `Runtime.callFunctionOn` should not cause errors to be
suppressed. According to the protocol docs:
`In silent mode exceptions thrown during evaluation are not reported and do not pause execution. Overrides setPauseOnException state.`
- so, the result returned should have the error, if any.
- Added corresponding JS test, so that we know we are matching the
correct behavior.
> [wasm][debugger] Fix `callFunctionOn`+`silent` arg behavior

- mono/metadata/class-init.c
- mono/metadata/class.c
!! This PR is a copy of dotnet/runtime#36604,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>In https://github.com/dotnet/winforms/pull/3197 we were investigating what happens when you try to create an an array from SAFEARRAY with more than 32 dimensions.
Found out that this throws `TypeLoadException`.
Thought I'd come along and write some tests to validate this constraint in dotnet/runtime.
Note: in In https://github.com/dotnet/winforms/pull/3197 we wanted to `stackalloc` an `int` array …
> Add some edge case tests for Array.CreateInstance

- configure.ac
- mono/mini/Makefile.am.in
- mono/mini/mini-llvm-cpp.cpp
!! This PR is a copy of dotnet/runtime#38547,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
- coreclr/build-test.sh now has a new subcommand: 'mono_aot', which builds a
new target, named 'MonoAotCompileTests', added to
coreclr/tests/src/runtest.proj. This target compiles the runtime tests using
Mono LLVM AOT in a simple configuration where the host platform is identical to
the target platform. Parallel compilation happens via a hack: actual
compilation happens in …
> Run CoreCLR runtime tests using Mono with LLVM AOT.

- mono/mini/interp/interp.c
!! This PR is a copy of dotnet/runtime#39260,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>The previous method of returning interp_no_native_to_managed doesn't work:
* The runtime expects different function pointers for different methods, returning
the same pointer leads to all kinds of weird errors.
* On wasm, the native caller expects the function to have the right signature, so
calling interp_no_native_managed () will leads a to signature mismatch error which is
hard to debug.
> [wasm] Fail right away in interp_create_method_pointer () when trying to create a function pointer to a native-to-managed wrapper.

- mono/mini/wasm_m2n_invoke.g.h
!! This PR is a copy of dotnet/runtime#39271,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>It was missing a few signatures in wasm_m2n_invoke.g.h that caused it to fail with `WASM-ERR: CANNOT HANDLE INTERP ICALL SIG IIILIIII`
> WASM: Fix System.Diagnostics.Tracing

- mono/mini/interp/interp.c
The previous code would convert exceptions into errors which would
be rethrown later, clearing the resume state.
Hopefully fixes https://github.com/dotnet/runtime/issues/38337.
> [wasm] Fix the propagation of exceptions through runtime invokes.

- mcs/tools/wasm-tuner/PInvokeTableGenerator.cs
Fixes https://github.com/mono/mono/issues/20120.
> [wasm] Fix handling of void types in the pinvoke generator.

- mono/mini/llvm-jit.cpp
!! This PR is a copy of dotnet/runtime#38659,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>I noticed that the following code leaves bound checks when compiled using LLVM-JIT:
```csharp
static void Test(Span<int> span)
{
for (int i = 0; i < span.Length; i++)
x[i] = 0;
}
```
```asm
Test:
0000000000000000	pushq	%rax
0000000000000001	testl	%esi, %esi
0000000000000003	jle	0x3f
0000000000000005	xorl	%eax, %eax
0000000000000007	movl	%esi, %ecx
0000000000000009	cmpq	%rcx, %rax
000000000000000c …
```
> [mono] fix bound checks for Spans in LLVM-jit mode (add extra SROA pass)

- mcs/tools/wasm-tuner/InterpToNativeGenerator.cs
- mono/mini/wasm_m2n_invoke.g.h
This change adds the set of signatures required for SkiaSharp to work untouched using the signatures already provided for the existing platform.
> [Wasm] Additional signatures for SkiaSharp interop + More

- mono/metadata/class-init.c
!! This PR is a copy of dotnet/runtime#39517,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>MonoClass-es created for ftnptr types have an implicit pointer field so their size is not
the same as the computed size.
> [mono] Fix an assert which happens when marshalling ftnptr types.

- mono/mini/method-to-ir.c
- mono/mini/mini-runtime.c
I've been noticing some C compiler warnings during build of dotnet/runtime.
```
C:\Users\gotos\source\repos\runtime\src\mono\mono\mini\mini-runtime.c(1920,1): warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss [C:\Users\gotos\source\repos\runtime\src\mono\msvc\libmono-dynamic.vcxproj]
C:\Users\gotos\source\repos\runtime\src\mono\mono\mini\method-to-ir.c(5337,1): warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss [C:\Users\gotos\source\repos\runtime\src\mono\msvc\libmono-dynamic.vcxproj]
```
Apparently there are some smart quotes and a zero-width space (Why?!) in some of Mono's …
> Remove some non-unicode characters from source code

- configure.ac
- mono/eglib/glib.h
- mono/eglib/goutput.c
- mono/metadata/sgen-toggleref.c
- mono/sgen/sgen-client.h
- mono/sgen/sgen-conf.h
- mono/sgen/sgen-gc.c
- mono/sgen/sgen-gc.h
- mono/sgen/sgen-gchandles.c
- mono/sgen/sgen-marksweep.c
- mono/sgen/sgen-pinning-stats.c
- mono/sgen/sgen-pinning.h
- mono/sgen/sgen-protocol.c
- mono/sgen/sgen-protocol.h
- mono/sgen/sgen-thread-pool.c
- mono/sgen/sgen-workers.c
- mono/sgen/sgen-workers.h
!! This PR is a copy of dotnet/runtime#39549,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This disables several debugging features in sgen, helps the compiler remove some unused code related to concurrent collector and disables more assertion messages, but also some other logs. We might have to reenable some of them if this is problematic.
Saves about 60k on wasm
> [wasm] Trim down size of dotnet.wasm

- mono/metadata/class.c
- mono/mini/debugger-agent.c
!! This PR is a copy of dotnet/runtime#39479,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>* Changed debugger-agent to allow for the Debugger Attributes to not exist.
* Removed the Debugger Attributes entries from the Descriptors.xml file.
Fix mono/linker#1355
> Allow Debugger attributes to be trimmed in Mono

- mono/metadata/marshal.c
!! This PR is a copy of dotnet/runtime#39700,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/39100.
> [runtime] Initialize the class if needed in type_is_blittable ().

- mono/mini/dwarfwriter.c
- mono/mini/image-writer.c
- mono/mini/image-writer.h
Reverts the revert from https://github.com/mono/mono/pull/20013 to reinclude https://github.com/mono/mono/pull/19794 along with the fix from https://github.com/mono/mono/pull/20031
> [2020-02] Reapply "Emit DWARF debug_abbrev offset for compile units as a label instead of 0"

- mono/mini/mini-generic-sharing.c
Backport of #20157.
/cc @vargaz
> [2020-02] [aot] Avoid a crash in generic sharing for invalid generic instances. Fixes https://github.com/mono/mono/issues/20138.

- .gitmodules
Bumps bockbuild to get the changes from https://github.com/mono/bockbuild/pull/162
BigSur's CoreGraphics seems to need a copy of the data to stick around longer than the surface,
so we provide it a copy of the data instead.
> Fix Cairo issue on macOS Big Sur

- mono/mini/debugger-agent-stubs.c
- mono/mini/debugger-agent.c
- mono/mini/debugger-agent.h
- mono/mini/mini-exceptions.c
- mono/mini/mini-runtime.c
Trying to remove the usage of unhandled_exception function to make debugger handle with an exception when running on android.
We should ignore the try catch that is in an WRAPPER_SUBTYPE_ICALL_WRAPPER, then we can walk through all the callstack and find any try catch in managed code if it exists.
Relates to https://github.com/xamarin/xamarin-android/pull/4927
> [debugger] Removing unhandled_exception which was used for android.

- mono/metadata/Makefile.am
!! This PR is a copy of dotnet/runtime#39970,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>After adding the ICU shim code to the runtime we hit an issue when e.g. compiling for "desktop" mono in a working directory that already had Browser wasm artifacts in it.
This is due to automake putting the intermediate compilation artifacts at the same location where a file was referenced from.
This means that e.g. when using `../../../libraries/Native/Unix/System.Globalization.Native/pal_icushim. …
> [mono] Fix building multiple os/arch combinations in the same working directory

- mono/mini/driver.c
- mono/mini/jit.h
- mono/mini/mini-runtime.h
- sdks/wasm/src/driver.c
interp-llvmonly caused mono_llvm_only to be set, causing bad behavior like
stack walks not working.
> [wasm] Use interp-only instead of interp-llvmonly as the default execution mode.

- mono/metadata/custom-attrs.c
- mono/metadata/native-library.c
!! This PR is a copy of dotnet/runtime#38975,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>So far we have been ignoring the flags contained in the attribute.
Attribute can be applied to a pinvoke method or an assembly. See https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.defaultdllimportsearchpathsattribute.-ctor?view=netcore-3.1#System_Runtime_InteropServices_DefaultDllImportSearchPathsAttribute__ctor_System_Runtime_InteropServices_DllImportSearchPath_
> [mono] Use DefaultDllSearchPaths attribute for PInvokes

- mono/mini/mini-wasm.c
!! This PR is a copy of dotnet/runtime#40000,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>EDIT: Simple test case to trigger an error:
```csharp
ThreadPool.QueueUserWorkItem((_) => {
throw new Exception("test");
});
var t = typeof(System.Threading.ThreadPool);
var m = t.GetMethod("PumpThreadPool", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
m.Invoke(null, null);
```
> Update threadpool callback error messages to fix #38803

- tools/locale-builder/Makefile.am
As part of https://github.com/mono/mono/pull/19912 we moved the locale files to the mono/culture/ subdirectory.
> Make install-culture-table write to mono/culture/

- mcs/class/System.Windows.Forms/System.Windows.Forms/Line.cs
Also adds a minor improvement to line wrapping, by not updating the wrap position when it can only move it earlier.
This means when processing end-of-wrapped-line whitespace that it doesn't get adjusted every time. This also fixes it so it doesn't update the previous wrap position to the same thing, but that shouldn't be used in this situation anyway as it is only for wrapping after dashes.
The real problem that this fixes is that wrapping a line at a point such that there was whitespace including a tab after the wrap position could cause an infinite loop. Without the fix, with `wrap_pos > 0` (normal), it only split the line after reaching non-whitespace. In most situations that was OK as we normally wrap after whitespace. However a tab is whitespace we wrap before. Once `pos` was equal …
> [WinForms] Fix Line problem with wrapping and tabs

- mcs/class/System/Mono.Btls/MonoBtlsBio.cs
- mcs/class/System/Mono.Btls/MonoBtlsSsl.cs
- mcs/class/System/Mono.Btls/MonoBtlsSslCtx.cs
- mcs/class/System/Mono.Btls/MonoBtlsX509LookupMono.cs
Fixes crashes when BTLS is compiled for Windows x86 with Clang.
> [System] Mark BTLS callbacks as cdecl.

- mcs/jay/skeleton.cs
Incorrect loop indexing. The loop index is incremented twice per iteration.
Fixes #14241
> jay.exe (ILASM): Incorrect loop indexing, fixes #14241

- mono/metadata/icall-decl.h
- mono/metadata/icall-def-netcore.h
- mono/metadata/icall.c
!! This PR is a copy of dotnet/runtime#40079,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>They are no longer needed after https://github.com/dotnet/runtime/pull/38996 since we return values in managed code now.
> [wasm] Remove unused icalls for Environment properties

- configure.ac
- mono/mini/mini-s390x.h
- mono/utils/mono-context.h
- mono/utils/mono-hwcap-s390x.c
- mono/utils/mono-tls.c
- mono/utils/valgrind.h
This patch set will enable a clean build of mono for s390x using clang. The register specifications require the use of a prefix ('r' - general registers 'f' - floating point 'a' - access) rather than just a number. This has been fixed in the most recent level of clang. The current compilers (gcc and clang) are also better at optimizing string operations so the compiler option ```-D__USE_STRING_INLINES``` is also no longer required.
> Fix __asm__ specifications for Clang

- configure.ac
!! This PR is a copy of dotnet/runtime#40263,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>We need to set these defines so we don't use obsolete ICU functions and cause warnings, just like we do in the CMakeLists.txt version..
> Fix ICU_CFLAGS in mono configure.ac

- mono/mini/interp/transform.c
!! This PR is a copy of dotnet/runtime#40266,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes dotnet/runtime#38897 , by allowing transforming internal calls when method is dynamic.
> Check if a method is dynamic when transforming internal calls

- mono/mini/debugger-agent.c
!! This PR is a copy of dotnet/runtime#40325,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>```
CC       libmono_dbg_la-debugger-agent.lo
/Users/runner/work/1/s/src/mono/mono/mini/debugger-agent.c:1088:9: warning: unused variable 'argv' [-Wunused-variable]
char *argv [ ] = {
```
> Fix warning in debugger-agent.c

- mono/metadata/reflection.c
!! This PR is a copy of dotnet/runtime#40405,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>`mono_type_get_object_checked` will return the `MonoReflectionType`
referred to by `MonoDomain::typeof_void` if present. If a byref
`System.Void` is stored in this field, then
`get_ContainsGenericParameters` applied to `System.Void` will loop
indefinitely, because our implementation of
`get_ContainsGenericParameters` expects `GetElementType` to yield a
`MonoReflectionType` with one layer of "type …
> [mono] Don't save byref `System.Void` into `MonoDomain::typeof_void`.

- mono/metadata/appdomain.h
- mono/metadata/assembly.c
- mono/metadata/domain-internals.h
!! This PR is a copy of dotnet/runtime#39446,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Calling monovm_initialize matches how other mono platforms init themselves.
> [Wasm] Ensure monovm_initialize is called and the entry assembly is set

- mono/metadata/icall.c
!! This PR is a copy of dotnet/runtime#40472,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>CoreCLR gained support for creating`TypedReference *` and `TypedReference &` via `MakePointerType` and `MakeByRefType` in https://github.com/dotnet/coreclr/pull/25817.
Reenable byref System.Void-related reflection tests.
Fixes https://github.com/dotnet/runtime/issues/31713.
Fixes https://github.com/dotnet/runtime/issues/37489.
> [mono] Allow creating `TypedReference *` and `TypedReference &` via reflection.

- mono/mini/mini-generic-sharing.c
The attributes need to be ignored as with the other types, otherwise gsharedvt wrappers for signatures with
parameters like double f = default will not be found.
Fixes https://github.com/mono/mono/issues/20195.
> [aot] Fix the handling of r4/r8 parameter types with attributes during generic sharing.

- mono/mini/aot-runtime.c
This will decrease the size of the dedup assembly which can get
large with lots of instances.
Hopefully fixes https://github.com/mono/mono/issues/20224.
> [aot] Avoid dedup-ing non-public instances.

- configure.ac
!! This PR is a copy of dotnet/runtime#40686,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>`$enable_monodroid` and `$enable_monotouch` are set to no by default, not an empty string.
Accidentally enabled globally here: https://github.com/dotnet/runtime/commit/a54d391d9daebf7b53e7f1efc1690c1c35177570#diff-294e5f7514d4059e724506770913e1d7R1386
Fixes https://github.com/dotnet/runtime/issues/40147
> [mono] Fix configure to actually disable dllmap on non-mobile platforms

- mono/mini/aot-compiler.c
The c# compiler generates these for anonymous types.
Fixes https://github.com/xamarin/xamarin-macios/issues/9289.
Fixes https://github.com/mono/mono/issues/20237
> [aot] Fix an assert which is hit for generic instances with a lot of arguments.

- mono/mini/mini-wasm-debugger.c
!! This PR is a copy of dotnet/runtime#40728,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Changing some console.log to console.debug to not pollute the console.
Changing printf to DEBUG_PRINTF to follow the debug level chosen by user.
Remove unnecessary console.log.
Fix dotnet/runtime#40721
> [wasm] Remove unnecessary console messages.

- mono/mini/aot-compiler.c
The c# compiler generates these for anonymous types.
Fixes https://github.com/xamarin/xamarin-macios/issues/9289.
Backport of #20238.
/cc @vargaz
> [2020-02] [aot] Fix an assert which is hit for generic instances with a lot of arguments.

- mono/tests/Makefile.am
- mono/utils/mono-threads-windows.c
!! This PR is a copy of dotnet/runtime#40286,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Replace them with the current URL after the redirect.
Similar to @stephentoub's PR: https://github.com/dotnet/runtime/pull/2063.
This is a mechanical find/replace, I did not check whether the references are still accurate or issues are already fixed.
> Cleanup old corefx/coreclr GitHub issue links

- mono/metadata/appdomain.c
- mono/metadata/assembly.c
- mono/metadata/debug-mono-ppdb.c
- mono/metadata/image.c
- mono/metadata/metadata-internals.h
- mono/tests/metadata-verifier/gen-md-tests.c
!! This PR is a copy of dotnet/runtime#40818,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This change means we will handle bundles consistently across platforms and ensures that the MonoImageStorage is keyed by the in-memory location rather than the assembly name, which seems less error-prone.
> [mono] Improve MonoImage filename handling for bundled images

- sdks/wasm/packager.cs
Fixes #19785. This adds a convenient way to provide additional flags to emcc via the packager tool.
Example usage: `mono packager.exe <other flags> --extra-emcc-flags="-s USE_SDL=2 -s MIN_WEBGL_VERSION=2" <assembly>`
> [wasm] Add extra-emcc-flags parameter to packager

- mono/metadata/icall-decl.h
- mono/metadata/icall-def-netcore.h
- mono/mini/mini-llvm.c
- mono/mini/mini-ops.h
- mono/mini/simd-intrinsics-netcore.c
- mono/mini/simd-methods-netcore.h
- mono/utils/mono-hwcap-x86.c
!! This PR is a copy of dotnet/runtime#40861,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Implement `BitScanForward` and `BitScanReverse` as intrinsics.
Implement `__cpuidex` as a netcore-only icall. Rename `cpuid` (in
mono-hwcap-x86.c) to `mono_cpuidex`, give it extern linkage, and add
support for extended CPUID.
Related: https://github.com/dotnet/runtime/pull/40167
> [mono] Add `X86Base` support.

- mono/metadata/icall-eventpipe.c
!! This PR is a copy of dotnet/runtime#39178,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Make sure EventPipe specific classes won't get trimmed by ILLinker when building S.P.C, same as done for CoreCLR. Since linker rule is now shared between both CoreCLR/Mono S.P.C, moved rules into ILLink.Descriptors.Shared.xml.
Added missing case into Mono's EventPipeInternal::EnvetActivityIdControl implementations.
Enabled eventactivityidcontrol test on Mono runtime.
> Fix EventActivityIdControl test on MonoVM.

- mono/mini/interp/interp.c
- mono/mini/interp/transform.c
- mono/mini/intrinsics.c
- mono/mini/method-to-ir.c
- mono/mini/mini-arm64.c
- mono/mini/mini.h
- mono/mini/simd-intrinsics-netcore.c
- mono/mini/simd-intrinsics.c
!! This PR is a copy of dotnet/runtime#35008,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fix https://github.com/mono/mono/pull/19494 adds missing array ctor needed by several tests currently failing as described by https://github.com/dotnet/runtime/issues/34068.
This PR re-eanbles the tests currently listed in https://github.com/dotnet/runtime/issues/34068.
> Enable tests previously failing due to missing array ctor.

- mono/mini/aot-runtime.c
Fixes https://github.com/mono/mono/issues/20256.
> [aot] Fix the lookup of jit info for WASM. On wasm, methods have no size, so only the method address can be looked up, jinfo->code_size is set to 1.

- mono/mini/method-to-ir.c
- mono/mini/mini-llvm.c
!! This PR is a copy of dotnet/runtime#40990,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Mono currently just ignores `MethodImplOptions.NoOptimization` flag, this PR adds support for it.
```csharp
static int Add(int a, int b) => a + b;
[MethodImpl(MethodImplOptions.NoOptimization)]
static int Test(int a, int b) => Add(a, b) * Add(a, b); // NoOpt means - don't inline Add here, don't do opts
static void Main(string[] args)
{
Test(1, 2);
}
```
Codegen for Test:
```asm
0000000000000000 …
```
> [mono] Add MethodImplOptions.NoOptimization support

- mono/metadata/native-library.c
- mono/utils/mono-dl-posix.c
- mono/utils/mono-dl-wasm.c
- mono/utils/mono-dl-windows.c
- mono/utils/mono-dl.c
- mono/utils/mono-dl.h
!! This PR is a copy of dotnet/runtime#41229,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This mostly completes support for the attribute. Our algorithm differs a bit from CoreCLR right now, so we don't support the legacy behavior flag since it makes less since in the context of our algorithm, but this should be good enough for most cases.
> [mono] Thread DllImportSearchPath flags down to LoadLibraryEx

- mono/metadata/sgen-client-mono.h
- mono/metadata/sgen-mono.c
- mono/sgen/sgen-gc.c
!! This PR is a copy of dotnet/runtime#40985,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When this experiment is enabled, the GC doesn't scan stack or registers. This mode is meant to disable scanning of native frames. This implementation only makes sense in full interpreter mode, where the interp stack is scanned separately from the thread stack. Longer term we could use this mode to scan only the managed stack, also in jit mode.
The point of this mode is to be able to stress test …
> [coop] Add configuration option to disable stack scan

- mono/metadata/icall-eventpipe.c
- mono/mini/mini-runtime.c
!! This PR is a copy of dotnet/runtime#41152,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Port changes done in the following CoreCLR PR's affecting corresponding Mono runtime EventPipe library sources:
https://github.com/dotnet/runtime/pull/36720
https://github.com/dotnet/runtime/pull/37002
https://github.com/dotnet/runtime/pull/38967
https://github.com/dotnet/runtime/pull/40191
https://github.com/dotnet/runtime/pull/40332
https://github.com/dotnet/runtime/pull/40499
EventPipe native …
> Port EventPipe CoreCLR changes to Mono.

- mcs/class/corlib/Test/System.Reflection.Emit/EnumBuilderTest.cs
- mono/metadata/sre.c
Previously, only non-enum types containing fields with incomplete enum
types were forbidden.
(Original: https://github.com/mono/mono/pull/19456)
> [runtime] Catch attempts to create enum types with an underlying type that is itself an incomplete enum type.

- configure.ac
- mono/metadata/w32socket-internals.h
- mono/metadata/w32socket-unix.c
- mono/mini/helpers.c
- mono/mini/simd-intrinsics-netcore.c
- mono/utils/mono-hwcap-vars.h
- mono/utils/mono-hwcap-x86.c
!! This PR is a copy of dotnet/runtime#41233,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This PR:
* Enables `-Wc++-compat` on all platforms: we support building the runtime as C++, so this helps catch errors before they're found in CI and will help keep the netcore build C++-compatible
* Sets `-Werror` on netcore CI for OSX
It also fixes various warnings currently present in the build.
`-Werror` should probably be extended to cover all CI platforms eventually. Adding a new platform is …
> [mono] Pass -Wc++-compat on all platforms, -Werror on OSX, fix errors

- mono/metadata/assembly-load-context.c
- mono/metadata/domain-internals.h
- mono/metadata/domain.c
- mono/metadata/loader-internals.h
!! This PR is a copy of dotnet/runtime#41344,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>We previously had a weird split between the domain and loader headers/files. This makes fewer things public, moves the useful ALC functions to loader-internals.h with the implementation in assembly-load-context.c, and cleans up the flow for some unloading behavior.
> [mono] ALC function restructuring for unloadability

- mono/metadata/icall-decl.h
- mono/metadata/icall-def-netcore.h
- mono/metadata/icall.c
!! This PR is a copy of dotnet/runtime#41440,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>In order to avoid the static Thread initialization (System.Thread.CurrentThread inits a static field) see https://github.com/dotnet/runtime/pull/41360
Benchmark:
```csharp
[Benchmark]
public int CurrentThreadId() => Environment.CurrentManagedThreadId;
```
Mono JIT (benchmarked on a slow machine):
```
|          Method |     Mean |     Error |    StdDev |
|---------------- …
```
> [mono] Convert Environment.CurrentManagedThreadId to an icall

- mono/metadata/icall-decl.h
- mono/metadata/icall-def-netcore.h
- mono/metadata/icall.c
Reverts mono/mono#20313, not needed.
> Revert "[mono] Convert Environment.CurrentManagedThreadId to an icall"

- mono/mini/mini-darwin.c
Work around LLDB's unconditionally-installed and inflexible Mach
exception handler by installing a no-op task-wide Mach exception
handler.
See also:
- https://github.com/openjdk/jdk/blob/50cc54c730bb0f130991648d1547d42483edddc1/src/hotspot/os/bsd/os_bsd.cpp#L2810-L2817
- https://github.com/mono/mono/issues/10180#issuecomment-683119507
> [mono] Squelch Mach exception handlers

- mcs/tools/resgen/monoresgen.cs
* Only set basepath to the source directory if useSourcePath is set.
* Fixes a regression from mono 4 that happened when changing the code
to not use reflection.
> [resgen] Honour absence of -usesourcepath

- mcs/class/I18N/CJK/GB18030Encoding.cs
GetByteCount will not return the right number of bytes needed, so GetBytes in Encoder.Convert will crash for some input
> Fixes potential crash for Encoder.Convert

- mono/mini/mini-codegen.c
While unlikely in practice, architectures with more than 32 registers would be affected by this as `sizeof(regmask_t) == 8` && `sizeof(int) == 4`.
Run into this while debugging something unrelated.
> mono: result of regmask should be stored in regmask_t, not int

- support/serial.c
To make pseudo-ttys are usable.
Fixes #20218
> Ignore EINVAL errors on ioctl TIOCMGET/TIOCMSET

- mono/mini/mini-wasm-debugger.c
!! This PR is a copy of dotnet/runtime#41468,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Recent debugger test runs were showing lot of
`CWL: Failed to lookup sequence point` messages.
These are being shown for cases like:
`CWL: list_frames: Failed to lookup sequence point. method: runtime_invoke_direct_void, native_offset: 56`
This is a warning, and doesn't need to be emitted by default.
> [wasm][debugger] Disable an extraneous debug message

- mono/metadata/image.c
- mono/metadata/mono-private-unstable.h
!! This PR is a copy of dotnet/runtime#41334,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Xamarin-Android will need this for the net6 migration, so might as well add it before I forget about it. They currently use `mono_image_open_from_data_with_name`. cc: @grendello
> [mono] Add mono_image_open_from_data_alc to unstable embedding API

- mcs/class/System.Windows.Forms/System.Windows.Forms/GridEntry.cs
In Line 552 value and properties[i].GetValue (propertyOwners[i]) will not be same cause custom Converter
can change object reference on its side, so there will be enough check at line 523
> [Winforms] Real fix for #18606 PropertyGrid didn`t edit value with CustomTypeDescriptor (#19452)

- mcs/class/corlib/System/TimeZoneInfo.Android.cs
**NOTE: please backport the fix to the 2020-02 branch, thanks!**
Context: https://source.android.com/devices/architecture/modular-system/runtime#time-zone-data-interactions
Context: https://source.android.com/devices/tech/config/timezone-rules#timezone-apex
Context: https://android.googlesource.com/platform/frameworks/base/+/a1ae02519d6fb5de636fc8728dec7cb9b14de356
Maybe helps with: https://github.com/xamarin/xamarin-android/issues/5080
Add support to read ICANN timezone data from two new locations found on
devices running Android 10+.  The data in the previously searched
location still exists but it's most likely out of date.
On Android 10+ tzdata updates will be derived via an APEX TimeData
package update, whose data directory this commit sets as the first
location to be searched.
This …
> [2020-02] [Android] Enable access to up-to-date tzdata on Android 10+

- mono/mini/mini-wasm-debugger.c
!! This PR is a copy of dotnet/runtime#41562,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Eg. `object o = "foobar"`
This will show the string `"foobar"`, instead of an object, in the
debugger.
> [wasm][debugger] Show actual data for boxed values

- mono/mini/interp/transform.c
- mono/mini/interp/transform.h
- mono/mini/interp/whitebox.c
- mono/mini/mini-codegen.c
- scripts/ci/run-test-interpreter.sh
This PR makes basic blocks a fundamental part of the code generation machinery. Before this change, there wasn't really any notion of basic blocks, there was a single list of instructions. With this change, we emit instructions inside basic blocks which are linked together. These basic blocks are iterated one at a time when doing optimization passes or emitting the final code. Currently, the origin of all basic blocks is IL code (they originate from branch targets and exception clauses) and we might never support creation of additional bblocks (since we could just create more complex instructions, which would also result in faster code). The bblocks will be emitted in the final code in the same order as they appear in IL code. This order is maintained through `next_bb` link.
Since the …
> [interp] Add basic block support

- mono/metadata/assembly.c
- mono/metadata/domain-internals.h
- mono/metadata/domain.c
- mono/metadata/image-internals.h
- mono/metadata/image.c
- mono/metadata/loaded-images.c
- mono/metadata/loader-internals.h
- mono/metadata/mono-private-unstable.h
!! This PR is a copy of dotnet/runtime#41358,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This adds a satellite assemblies bundle for WASM and also adds a hook into the driver to be able to register satellite assemblies into the bundle before the runtime is initialized. This allows us to load a satellite assembly by name from the bundle for bundled runtimes.
Fixes: https://github.com/dotnet/runtime/issues/39379
cc: @steveisok @marek-safar @lewing
> [WASM] Add satellite assemblies bundle and hook to register them

- mono/mini/exceptions-s390x.c
commit 2a4e66af4dc628a84a42ff443bc2c09a4bcc7dec broke build on s390x after
changing the signature of `mono_handle_native_crash()`. We need to update
exceptions-s390x.c as well.
Fixes: https://github.com/mono/mono/issues/20356
> [crashing] update s390x handling

- mcs/class/reference-assemblies/Makefile
.msi creation has been broken for a while, throwing a LGHT0001 file access error during packing of the final installer
Whilst WiX helpfully does not tell you the cause of LGHT0001 errors, I tracked it down to two files - UNIX-style symlinks, created by Cygwin, by `ln` calls in mcs/class/reference-assemblies/Makefile. WiX fails on these.
Cygwin can be forced to use Windows NT symlinks instead, through an environment variable - this PR forces that environment variable on Windows builds for those calls to `ln`
> Fix building of Mono .msi Windows packages

- mcs/class/reference-assemblies/Makefile
.msi creation has been broken for a while, throwing a LGHT0001 file access error during packing of the final installer
Whilst WiX helpfully does not tell you the cause of LGHT0001 errors, I tracked it down to two files - UNIX-style symlinks, created by Cygwin, by `ln` calls in mcs/class/reference-assemblies/Makefile. WiX fails on these.
Cygwin can be forced to use Windows NT symlinks instead, through an environment variable - this PR forces that environment variable on Windows builds for those calls to `ln`
Backport of #20372.
/cc @directhex
> [2020-02] Fix building of Mono .msi Windows packages

- mono/metadata/image.c
- mono/metadata/metadata-internals.h
- mono/utils/mono-logger-internals.h
- mono/utils/mono-logger.c
The presence of the heap indicates that it's a minimal delta image (where the heaps are meant to be appended to the previous heaps), as opposed to a full delta image (where the heap in the delta image contains the previous and the
new data)
---
Also add `MONO_TRACE_METADATA_UPDATE` (set `MONO_LOG_MASK` to `metadata-update`) for tracing
> [metadata] Add #JTD heap MonoImage:minimal_delta bit

- mono/mini/mini-posix.c
- mono/utils/mono-counters.c
- mono/utils/mono-time.c
!! This PR is a copy of dotnet/runtime#41994,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>I recommend reviewing each commit individually with the corresponding commit message. If desired I can split this into two PRs.
The end result is that this adds a new timer to the startup stats that works by getting the time early in Mono startup and then comparing with that at the time of stat dumps, as opposed to reading in process information. This means it should be easy to get working on all …
> [mono] Enable startup stats timer on wasm

- mono/mini/mini-wasm-debugger.c
!! This PR is a copy of dotnet/runtime#42059,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Eg. `object o = new object(); object o1 = o;`
- Avoid infinitely looping for `o1`
> [wasm][debugger] Avoid infinite loop when we have a boxed `new object`

- mono/metadata/object.c
`mono_runtime_invoke_array` is marked as `MONO_API MONO_RT_EXTERNAL_ONLY`, but it does not transition to GC Unsafe in contrast to similar methods like `mono_runtime_invoke`. This led to crashes when calling it from unmanaged code.
The original PR that added the transitions in the other methods is https://github.com/mono/mono/pull/8613, maybe there was a particular reason for not updating  `mono_runtime_invoke_array` also?
> Transition to GC Unsafe in mono_runtime_invoke_array

- mono/mini/exceptions-amd64.c
- mono/mini/exceptions-ppc.c
- mono/mini/exceptions-x86.c
- mono/mini/mini-exceptions.c
- mono/mini/mini-posix.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
- mono/mini/mini-windows.c
- mono/mini/mini.h
This commit https://github.com/mono/mono/commit/7a0425e81ffe0e77a4ba22ff45e691934ecc49a1 is causing the following xamarin-android issue: https://github.com/mono/mono/issues/20275
This pull request reverts it.
Backport of #20332.
/cc @naricc
> [2020-02] [merp] Revert 7a0425e which is causing xamarin-android failures

- mono/utils/mono-mmap.c
Fixes package building.  We use Xcode 8.3.3 for the 32-bit x86 build, and it is too old for `__builtin_available`
> [utils] Don't use __builtin_available on x86 and amd64 macos

- mono/.editorconfig
!! This PR is a copy of dotnet/runtime#42286,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>The main motivation is to override the [.editorconfig in the repo root](https://github.com/dotnet/runtime/blob/master/.editorconfig) to ensure that Mono C files follow the [Mono coding guidelines](https://www.mono-project.com/community/contributing/coding-guidelines/)
> Add a minimal .editorconfig for Mono C files

- mono/metadata/image.c
- mono/metadata/metadata.c
Some  cherrypicked changes from a work in progress
* Try to set MonoImage guid from modules table for metadata_only images
If the image has a modules table, and a guid heap, set MonoImage:guid when loading the image, even if it is metadata_only.  In minimal delta images this is true.
* Minimal delta files have 4 byte indices, always
* Don't populate MonoImage:module_name for minimal deltas
* Always store precise string heap size in MonoImage:heap_strings
In minimal delta images, the String heap is appended to the heap of the base image.  But in the physical base image, the String heap is zero-padded to a size that's a multiple of 4 bytes.
Compute the precise String heap size at base image load time.
> [metadata] Assorted enhancements for some CIL image formats

- mono/mini/interp/transform.c
This allows us to optimize out checks like `typeof(T1) == typeof(T2)`, which is very common in bcl.
> [interp] Track MINT_MONO_LDPTR as constants

- mono/metadata/assembly-internals.h
- mono/metadata/assembly.c
!! This PR is a copy of dotnet/runtime#42425,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/42207
The new test is based on the sample from that issue.
The naive fix (moving all bundle loading to after we check the default ALC) highlights that the satellite assembly tests were passing for the wrong reasons. The full fix here handles satellite loads correctly, putting them in the same ALC as the parent assembly. One non-satellite test that was …
> [mono] Add test for wasm loader regression, fix loading from bundle

- mono/metadata/marshal-ilgen.c
- mono/tests/libtest.c
- mono/tests/pinvoke2.cs
Fixes https://github.com/mono/mono/issues/20367.
> [runtime] Throw a MarshalDirectiveException when returning an array from a pinvoke method.

- mono/mini/debugger-engine.c
!! This PR is a copy of dotnet/runtime#42639,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>We don't have ctx available on wasm, but we don't need it to calculate the frames, the ifdef on debugger-engine.h fix the dotnet/runtime#42424.
> [wasm][debugger] Fixing step over in an async method

- mono/metadata/sgen-mono.c
!! This PR is a copy of dotnet/runtime#42388,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>TotalBytesAllocated was sometimes not monotonically increasing on Mono. The reason was that when a thread was detached, we were not counting bytes allocated in its thread local allocation buffer. So, under the right circumstances the bytes would be counted while the thread is attached, but then get lost when the thread detached.
Fixes: https://github.com/dotnet/runtime/issues/2280
> [Mono] [GC] Fix TotalBytesAllocated and reenable test

- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
Stop managing a finally_ips list at runtime. It is cumbersome, redundant and has a performance penalty (since we malloc/free for every single finally block invocation).
For every EH clause we were allocating a local slot (exvar_offsets). This was used to store thrown exception for catch blocks, but wasted for finally blocks. Following this commit, we reuse that slot to store the endfinally return ip. When we execute the endfinally instruction we check this local slot and branch to that ip. If it is null, then we know we were called from EH and should bail out of interpreter execution loop. In normal execution, this return ip is set by MINT_CALL_HANDLER. For every leave IL instruction we explicitly generate a MINT_CALL_HANDLER for every finally block.
> [interp] Refactor finally block invocation

- mono/metadata/marshal.c
- mono/metadata/marshal.h
- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
- mono/mini/aot-tests.cs
The testcase only fails when AOTed using --aot=soft-debug.
Fixes https://github.com/mono/mono/issues/20421.
> [aot] Add support for references to GENERIC_ARRAY_HELPER wrappers.

- mono/mini/mini-trampolines.c
managed->native wrapper does the following under coop:
enter gc safe
native call
exit gc safe
since enter/exit gc safe are icalls they will be called through PLT on AOT builds. First call through a PLT slot will resolve the function using mono_aot_plt_trampoline and it currently assumes GC safe mode, so when hit as part of resolving exit gc safe, it is called under GC safe mode.
This has not showed up to be an issue under coop AOT, but asserts when running under checked build.
Fix will make sure thread is in GC unsafe mode making sure assumption of GC unsafe mode holds.
> Fix mono_aot_plt_trampoline GC unsafe assumption.

- mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/20417.
> [aot] Prepend the assembly name to the names of gsharedvt wrappers to avoid duplicate symbol errors during static linking.

- mono/mini/interp/transform.c
https://github.com/dotnet/runtime/issues/42628.
> [interp] Throw an InvalidProgramException instead of asserting when trying to transform a method with too many locals.

- mono/mini/tramp-s390x.c
s390x uses 'method' as parameter name in mono_arch_get_unbox_trampoline()
in mono/mini/tramp-s390x.c, rename to 'm' to be in sync with other arches.
Fixes: https://github.com/mono/mono/issues/20437
> [runtime] sync parameter name in tramp-s390x.c

- mono/metadata/class-abi-details.h
- mono/metadata/class-internals.h
In normal builds, the getters are `static inline` functions, so the profiler doesn't reference the symbols - it just accesses the fields by offset.
In checked builds with `--enable-checked-build=private_types`, the getters are not inlined, so the profiler shared libraries need the symbols to be visible.
> [metadata] Use MONO_PROFILER_API on MonoClass getters in checked builds

- mono/metadata/class.c
!! This PR is a copy of dotnet/runtime#42920,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/42917
> [metadata] Getting the element size of array of fnptr types is ok

- mono/metadata/sysmath.c
- mono/mini/intrinsics.c
- mono/utils/mono-math.h
!! This PR is a copy of dotnet/runtime#42951,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/mono/mono/issues/20449
We have a logic to fold various Math* operators to constants and it's incorrect for `Math.Round(double)` which is "round to even".
Btw, we don't need this folding for LLVM since all math functions are LLVM-intrinsics so the folding is done there.
> [mono] Fix constant folding for Math.Round

- mono/metadata/Makefile.am
- mono/metadata/appdomain.c
- mono/metadata/environment-internals.h
- mono/metadata/environment.c
- mono/metadata/icall-decl.h
- mono/metadata/icall-eventpipe.c
- mono/metadata/object-internals.h
- mono/metadata/object.c
- mono/mini/driver.c
- mono/mini/mini-runtime.c
- mono/mini/simd-intrinsics-netcore.c
- msvc/libeventpipe.targets
- msvc/libeventpipe.targets.filters
- msvc/libmonoruntime-common.targets
- msvc/libmonoruntime-common.targets.filters
!! This PR is a copy of dotnet/runtime#41872,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>WIP.
PR handling port of Diagnostic Server C++ library from CoreCLR into a C library that can be shared between Mono as well as CoreCLR runtime. Port follows same guidelines setup for event pipe port dotnet/runtime#34600. Diagnostic server library is currently hosted as part of event pipe library but hosting its own runtime shim as well as source files (so could be split into separate library if …
> [WIP] Initial work porting native diagnostic server library to C library potentially shared between runtimes.

- mono/metadata/object.c
!! This PR is a copy of dotnet/runtime#43009,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This PR fixes this issue. dotnet/runtime#40738. 
Whereas the fix is simple, we need to throw `mono_error_set_not_supported` instead of `mono_error_set_execution_engine`.
> Changed mono exception type from execution engine to not supported.

- mono/metadata/appdomain.c
- mono/metadata/cominterop.c
- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/metadata/threads.h
- mono/mini/interp/interp.c
- mono/mini/mini-runtime.c
- mono/profiler/aot.c
- mono/profiler/log.c
- mono/tests/.gitignore
- mono/tests/Makefile.am
- mono/tests/libtest.c
- mono/tests/pinvoke-detach-1.cs
Addresses https://github.com/mono/mono/issues/20290 and https://github.com/mono/mono/issues/20283
If a foreign thread (that was created outside the runtime) calls
`mono_thread_detach`, leave it in a preemptively-suspendable state, since we can't expect it to coop suspend.
Conversely in `mono_thread_attach` (external only), ensure that we always leave
the thread in GC Unsafe (aka RUNNING) state, for cases like
while (cond) {
t = mono_thread_attach (domain);
<...>
mono_thread_detach (t);
}
---
To make this work, we also make `mono_thread_detach` and `mono_thread_attach` external only.  The runtime should use `mono_thread_internal_detach` and `mono_thread_internal_attach`.
> [threads] Switch foreign threads to GC Safe in mono_thread_detach

- mono/metadata/icall-eventpipe.c
Followup to 4dd414b6ca6 to pick up icall-eventpipe.c changes from dotnet/runtime that were not in the
mono/mono repo
> [threads] Followup to 4dd414b6ca6

- mcs/class/corlib/Test/System/ArrayTest.cs
Bump `external/corert`
The ArraySortHelper catches all exceptions in the comparer.
If the sorting thread is aborted while it is running the comparer, the
ArraySortHelper will catch the TAE and propagate an InvalidOperationException
instead.
As a workaround, catch and rethrow TAEs separately.
Add regression test
Related to mono/mono#15418
> [corlib] ThreadAbortException protection for ArraySortHelper

- mcs/class/corlib/Test/System/ArrayTest.cs
Bump `external/corert`
The ArraySortHelper catches all exceptions in the comparer.
If the sorting thread is aborted while it is running the comparer, the
ArraySortHelper will catch the TAE and propagate an InvalidOperationException
instead.
As a workaround, catch and rethrow TAEs separately.
Add regression test
Related to mono/mono#15418
---
Backport of https://github.com/mono/mono/pull/20467
> [2020-02][corlib] ThreadAbortException protection for ArraySortHelper

- mono/metadata/custom-attrs.c
- mono/metadata/metadata.h
- mono/tests/Makefile.am
- mono/tests/block_guard_restore_alignment_on_exit.cs
!! This PR is a copy of dotnet/runtime#43073,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>* `occurence`, `occurance` -> `occurrence`
* `accross` -> `across`
* `adddress`, `addresss` -> `address`
* `alignement`, `aligment` -> `alignment`
* Remove `c` from triple c.
* Remove `s` from triple s.
* In palsuite, `Successs` (with triple s) was in commented out
`Trace()` message, removed all commented out `Trace()` calls
from such files.
* Fix invalid markdown in `unix-test-instructions.md`. …
> Fix various typos

- mono/sgen/sgen-cardtable.c
- mono/sgen/sgen-gc.c
- mono/sgen/sgen-gc.h
- mono/sgen/sgen-los.c
- mono/sgen/sgen-marksweep.c
Currently, when using overlapped card table, each minor GC will do a copy/clear of all marked cards into a temporary card table used during minor scan. In order to find marked cards, major heap blocks + LOS is scanned. This is currently done serial and could take significant time of total minor GC depending on platform/hardware.
On hardware with multiple cores it is possible to parallelize the copy/clear of card table, decreasing the minor GC pause times. As an example, a major heap of ~3 GB and a LOS of 600 MB, went from 5 ms minor GC down to 3 ms where most objects didn't have any references (just byte arrays). Increasing the number of objects with references will benefit event more. Before switching
over LOS to a SgenArrayList, similar scenario took 8 ms and was reduced to 3 ms, and …
> Parallelize card table copy/clear in minor GC.

- mono/profiler/mprof-report.c
Version 16 of log profiler data format added mvid to image load event and mprof-report was never aligned to handle that since it assumed all events for TYPE_IMAGE included mvid.
Fix makes sure to correctly read pass mvid only for event actually including the field.
> Fix parse error in mprof-report image load event.

- man/chktrust.1
- mcs/tools/security/chktrust.cs
This PR fixes a few minor spelling and grammatical mistakes pertaining to the `chktrust` program. A few instances of "an" were changed to "a" and the redundant phrase "PE executable" (Portable Executable executable) was changed to "PE binary".
> Minor spelling and grammar fixes.

- mono/mini/driver.c
- mono/mini/mini-runtime.c
Adding --profile argument to mono_jit_parse_options. Can be used when
embedding and not using parsing in driver.c.
Add env variable MONO_PROFILE adding another possibility to pass profiler
arguments to runtime.
> Simplify enabling profiler support for embedders.

- mono/metadata/profiler.c
- mono/profiler/helper.c
- mono/profiler/log-args.c
- mono/profiler/log.c
* Disable popen/pclose.
* Disable reporting using |mprof-report on Windows due to limited piping support.
* Switch to inet_pton instead of deprecated inet_addr.
* Fix Windows socket server since FD is handle and can be bigger than FD_SETSIZE.
> Additional fixes to Windows log profiler.

- mono/mini/aot-compiler.c
HAVE_SYSTEM is not defined on all HOST_WIN32 where building the AOT compiler makes sense (like cygwin). Make sure this works on all HOST_WIN32 independent of HAVE_SYSTEM.
> Fix aot compiler execute_system on all HOST_WIN32.

- mono/mini/mini-wasm-debugger.c
- mono/mini/mini-wasm.h
!! This PR is a copy of dotnet/runtime#42532,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Debugger.IsAttached is now working on wasm. And can be used to detect if debugger is attached.
Fix dotnet/runtime#42411
> [debugger][wasm] Implement Debugger.IsAttached on wasm

- mono/metadata/metadata-internals.h
!! This PR is a copy of dotnet/runtime#43536,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>We also no longer appear to need the NETCORE or DISABLE_REMOTING defines in msbuild, so remove them
> [mono] Ensure MonoAssemblyName is in sync between managed and native

- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/tests/libtest.c
- mono/tests/pinvoke-detach-1.cs
If a thread is started from native code, and it interacts with the runtime (by calling a thunk that invokes a managed method),
the runtime will attach the thread - it will create a `MonoInternalThread` and
add it to the list of threads hash (in threads.c).
If the thread returns from the managed call, it will still be recorded by the runtime, but as long as it is not running managed code anymore, it will prevent shutdown.  The problem is when we try to suspend the thread in order to abort it, `mono_thread_state_init_from_handle` will see a NULL domain (because `mono_threads_detach_coop_internal` will restore it to NULL when a managed method returns back to native code).  (On systems using POSIX signals to suspend, the same check is in `mono_thread_state_init_from_sigctx`).  As a result, …
> [threads] At shutdown, don't wait for native threads that aren't calling Mono 

- mono/mini/debugger-agent.c
If the runtime gets a single step or breakpoint signal while it is already
running native code for a P/Invoke, it will be in GC Safe mode.  Switch back to
GC Unsafe to run the debugger engine steps.
Addresses https://github.com/mono/mono/issues/20490
Backport of #20492.
> [2020-02] [debugger] Switch to GC Unsafe in signal handler callbacks

- mono/metadata/appdomain.c
!! This PR is a copy of dotnet/runtime#43592,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>We don't actually pin the byte array, so it must be copied or it can be overwritten once we run a GC on the LOH.
Fixes https://github.com/dotnet/runtime/issues/43402
Tested manually that it fixes the issue using the associated repro. This isn't really something that lends itself to a test, so that's the best I can do.
> [mono] Copy image data with AssemblyLoadContext.LoadFromStream

- mono/metadata/threads.c
!! This PR is a copy of dotnet/runtime#38225,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>- Enables using the portable thread pool with coreclr as opt-in. Change is off by default for now, and can be enabled with COMPlus_ThreadPool_UsePortableThreadPool=1. Once it's had bake time and seen to be stable, at a reasonable time in the future the config flag would ideally be removed and the relevant parts of native implementation deleted.
- The IO thread pool is not being migrated in this …
> Migrate coreclr's worker thread pool to be able to use the portable thread pool in opt-in fashion

- mono/metadata/threads.c
Without proper alignment, this may lead to reference types
being stored at non-pointer aligned offsets. Among other
issues this may lead to the GC not scanning those pointers
properly.
For example, a type such as
```
struct Point
{
public int X;
public int Y;
}
```
will have size 8 and alignment 4 on x64 platforms.
If we reuse the special slot allocated for the `Point` type to store
a reference pointer, it may not be pointer aligned.
Backport of #20501.
/cc @lambdageek @joncham
> [2020-02] Ensure special static slots respect alignment.

- mono/mini/jit-icalls.c
!! This PR is a copy of dotnet/runtime#43729,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/35674.
> [jit] Fix gsharedvt constrained calls to Object.GetType () under netcore.

- mono/mini/CMakeLists.txt
- mono/profiler/CMakeLists.txt
!! This PR is a copy of dotnet/runtime#43715,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>CLion creates a directory named ".idea" as a sibling to the top-level
CMakeLists.txt that describes the project; with src/mono, git clean -dXf
will delete src/mono/.idea because ".idea/" is an ignored pattern in
.gitignore.
One workaround is to create an out-of-tree CMakeLists.txt that contains
nothing but add_directory(relative/path/to/src/mono), but this changes
the value of CMAKE_SOURCE_DIR to …
> [mono] Use CMAKE_CURRENT_SOURCE_DIR instead of CMAKE_SOURCE_DIR

- msvc/setup-vs-msvcbuild-env.bat
Building full AOT using CI scripts won't work when VS2019 IDE is present (not falling back to VS2019 build tools).
This happens due to a typo in setup-vs-msvcbuild-env.bat. Since CI doesn't install VS IDE, but using buildtools (where clan bin
path is added to PATH) problem only shows up on local development environment using VS2019 IDE.
> Clang bin path not added to PATH for VS2019 builds.

- mono/metadata/w32socket-unix.c
When the destination IP on the packet doesn't match any WireGuard peer (such as
if the peer is disconnected while the app is running), the sender may get an ENOKEY errno.
This is mentioned in Section 3 "Send/Receive" of
https://www.wireguard.com/papers/wireguard.pdf
Fixes https://github.com/mono/mono/issues/20503
> [w32socket] Turn WireGuard ENOKEY errno to WASANETUNREACH

- mono/metadata/remoting.c
- mono/mini/ee.h
- mono/mini/interp-stubs.c
- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
- mono/mini/interp/transform.h
- mono/mini/mini-amd64.c
- mono/mini/mini-arm.c
- mono/mini/mini-arm64.c
- mono/mini/mini-profiler.c
- mono/mini/mini.h
Before this change, an InterpFrame contained 3 regions of data : args + locals, valuetype stack, execution stack. Each entry on the execution stack was a stackval structure. The space for valuetypes, was allocated separately, since they have various sizes. When pushing a valuetype on the stack, we allocated first the space for it on the vtstack and then pushed the address of the region on the execution stack. This change merges the execution stack with the valuetype stack, meaning we push now variable sized data on the execution stack. In order to keep track of the current stack location, whenever we push a type on stack, during transform phase, we also keep track of the offset where this value will reside on stack, as well as the size it occupies. All callsites need to be informed how …
> [interp] Unify execution and valuetype stacks 

- mono/metadata/native-library-qcall.c
- mono/metadata/native-library.c
!! This PR is a copy of dotnet/runtime#43798,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This is needed because they are stored in a separate table, so they cannot be linked out the same
way as pinvokes/icalls.
> Disable qcalls on wasm. Treat them as normal pinvokes.

- mcs/class/I18N/CJK/GB18030Encoding.cs
GetByteCount will not return the right number of bytes needed, so GetBytes in Encoder.Convert will crash for some input
Backport of #20271.
/cc @akoeplinger @jeffgoku
> [2020-02] Fixes potential crash for Encoder.Convert

- mono/metadata/appdomain.c
- mono/metadata/handle.c
- mono/metadata/handle.h
!! This PR is a copy of dotnet/runtime#43830,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Copying of the assembly and symbols happens later, in `mono_alc_load_raw_bytes`, and the pinning is no longer necessary so long as we have the handle.
Followup from https://github.com/dotnet/runtime/pull/43592#discussion_r508002405, cc: @lambdageek
> [mono] Fix LoadAssemblyRaw to not pin or copy

- mono/mini/interp/transform.c
!! This PR is a copy of dotnet/runtime#43946,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>To help those who maintain Mono for BE.
Also, it allows interpreter to fold branches since now IsLittleEndian is converted into `LDC.I4.1` always on LE.
Example:
```csharp
static void Validate()
{
if (!BitConverter.IsLittleEndian)
throw new PlatformNotSupportedException();
}
```
Current output for `MONO_VERBOSE_METHOD=Validate` on both LE/BE:
```
IR_0000: ldsfld.u1  0
IR_0003: brtrue.i4.s IR_000b …
```
> [interp] return false for IsLittleEndian on BE

- mono/mini/jit-icalls.c
!! This PR is a copy of dotnet/runtime#44047,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/44000.
> Fix gsharedvt constrained calls to Object.GetHashCode () which was broken by #43729.

- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
!! This PR is a copy of dotnet/runtime#43893,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>For microbenchmark System.Threading.Tests.Perf_Interlocked.Exchange_long, before and after this change: 141.6ns -> 11.0ns
For microbenchmark System.Threading.Tests.Perf_Volatile.Read_double, before and after this change: 183.9ns -> 158.5ns
For microbenchmark System.Threading.Tests.Perf_Volatile.Write_double, before and after this change: 151.0ns -> 18.04ns
Fixes dotnet/runtime#41449
> [Interp] Create an intrinsic for Interlocked.Exchange for int64

- mono/mini/exceptions-riscv.c
- mono/mini/mini-riscv.c
I don't believe this fixes any existing issue in the tracker, but I'm trying to build mono with dotnet-core on riscv from git and ran into this problem when compiling.  There may end up being other changes but I won't know until my VM is done actually building mono.  The changes right now are incredibly minor, just updating some function signatures to match the current rest of the system.
> Minor update to function signatures for RISCV64 architecture

- mono/mini/interp/interp.c
!! This PR is a copy of dotnet/runtime#44129,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>For valuetypes, a stackval used to contain a pointer to the valuetype data, while currently the valuetype data is stored directly in the stackval.
> [interp] Fix pinvoke passing of valuetype on wasm

- mono/mini/mini-llvm.c
!! This PR is a copy of dotnet/runtime#44092,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
> Fix an assert which is hit when compiling Microsoft.CodeAnalysis.dll with llvmonly.

- mono/mini/interp/transform.c
- mono/mini/intrinsics.c
!! This PR is a copy of dotnet/runtime#44081,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>1. move `GetRawData` to an extension method in RuntimeHelpers and fixup the intrinsics
2. replace `Object.CloneInternal` by `MarshalAsAttribute.CloneInternal` at its one use site
3. re-enable System.Reflection.Tests.TypeInfoTests.FindMembers and fix mono/mono#15029
> [netcore] remove 2 extra members from System.Object

- mono/utils/mach-support-amd64.c
- sdks/builds/.gitignore
- sdks/builds/ios.mk
Xcode 12.2 removed 32 bits support for watchOS simulators, this PR helps to fix https://github.com/xamarin/xamarin-macios/issues/9949, we have tested the new binaries and they are working as expected
> [2020-02][watchOS] Add simwatch64 support

- mono/utils/mach-support-amd64.c
- sdks/builds/.gitignore
- sdks/builds/ios.mk
Xcode 12.2 removed 32 bits support for watchOS simulators, this PR helps to fix https://github.com/xamarin/xamarin-macios/issues/9949, we have tested the new binaries and they are working as expected
> [master][watchOS] Add simwatch64 support

- mono/mini/mini-wasm.c
!! This PR is a copy of dotnet/runtime#44046,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Update browser tests to use https://github.com/dotnet/xharness/pull/345 and be able to run promise related tests. Depends on https://github.com/dotnet/runtime/pull/44045
The build will fail until the xharness change makes it in.
> Use the new async Run method from xharness and implement a test

- mono/mini/mini-arm64.c
Partial backport of #20100.
Should fix https://github.com/mono/mono/issues/20533.
Also see:
https://github.com/dotnet/runtime/pull/35008#issuecomment-657402155
> Add support for OP_FCONV_TO_I to mini-arm64.c.

- mono/sgen/sgen-gc.h
Attempt to fix https://jenkins.mono-project.com/job/test-mono-mainline-staticanalysis/
> [sgen] Add Ward annotations to sgen_get_total_allocated_bytes

- mono/utils/mono-log-darwin.c
- sdks/builds/.gitignore
- sdks/builds/Makefile
- sdks/builds/maccat.mk
- sdks/paths.mk
- sdks/versions.mk
This patch introduces new Mac Catalyst support for mono!
**Background** Mac Catalyst allows a developer to use the traditionally iOS APIs - like UIKit - on macOS. It retains the same ABI as macOS x86_64, however, is compiled with a new `-target` flag that is required in all static and dynamic libraries.
This patch is my first port of mono so I appreciate any code reviews. :-)
I started with a clean build target so as not to break current iOS and Mac support. There is the potential to merge this with the existing iOS support, but I think this method of a specific `maccat.mk` file is a cleaner separation.
I discussed this publicly on the Merge Conflict podcast: https://www.mergeconflict.fm/225
I also show off the work on my Twitch stream: https://twitch.tv/FrankKrueger
This is the build …
> Build makefile to support Mac Catalyst

- mono/metadata/object-offsets.h
- mono/mini/exceptions-wasm.c
- mono/mini/method-to-ir.c
- mono/mini/mini-exceptions.c
- mono/mini/mini-llvm.c
- mono/mini/mini-runtime.h
- mono/mini/mini-wasm.c
- mono/mini/mini-wasm.h
For methods which need to show up during stack walks, push/pop an LMF
frame and have mono_arch_unwind_frame () handle it.
This is needed to be able to support methods which do stack walks like
Type.GetType () or Assembly.Load () in the future.
> [runtime] Add some support for stack walks for AOT code on wasm.

- mono/mini/method-to-ir.c
!! This PR is a copy of dotnet/runtime#44345,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>profiler enter code (such as mono_trace_enter_method) must not be called before a thread attaches to the runtime - otherwise calls like `mono_domain_get()` will return NULL unexpectedly and then crash.
When detaching, we should call the profiler leave code before the detach, and suppress it on return.
Simple repro (that relies on pal_signal.c SignalHandlerLoop - which is a background thread from …
> [mono][jit] Emit profiler enter after jit attach; leave before detach

- mono/utils/mono-log-darwin.c
- scripts/ci/pipeline/sdks-archive.groovy
- scripts/ci/run-jenkins.sh
- sdks/builds/.gitignore
- sdks/builds/Makefile
- sdks/builds/maccat.mk
- sdks/paths.mk
- sdks/versions.mk
This patch introduces new Mac Catalyst support for mono!
**Background** Mac Catalyst allows a developer to use the traditionally iOS APIs - like UIKit - on macOS. It retains the same ABI as macOS x86_64, however, is compiled with a new `-target` flag that is required in all static and dynamic libraries.
This patch is my first port of mono so I appreciate any code reviews. :-)
I started with a clean build target so as not to break current iOS and Mac support. There is the potential to merge this with the existing iOS support, but I think this method of a specific `maccat.mk` file is a cleaner separation.
I discussed this publicly on the Merge Conflict podcast: https://www.mergeconflict.fm/225
I also show off the work on my Twitch stream: https://twitch.tv/FrankKrueger
This is the build …
> [2020-02] Build makefile to support Mac Catalyst

- mono/mini/aot-compiler.c
- mono/mini/mini-llvm.c
!! This PR is a copy of dotnet/runtime#44235,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
> Use corlib instead of System.Private.CoreLib as a name prefix in AOT symbol names.

- sdks/builds/ios.mk
- sdks/builds/mac.mk
- sdks/versions.mk
The new Xcode introduced functions like preadv/pwritev in the SDK that get erraneously detected by autoconf even though we can't use them.
Disable these functions and also add a check for Xcode version to workaround https://github.com/mono/mono/issues/19393.
> Fix iOS sdks build on Xcode 12

- sdks/builds/ios.mk
- sdks/builds/mac.mk
- sdks/versions.mk
The new Xcode introduced functions like preadv/pwritev in the SDK that get erraneously detected by autoconf even though we can't use them.
Disable these functions and also add a check for Xcode version to workaround https://github.com/mono/mono/issues/19393.
Backport of #20573.
> [2020-02] Fix iOS sdks build on Xcode 12

- mono/mini/aot-compiler.c
- mono/mini/mini-wasm.c
!! This PR is a copy of dotnet/runtime#44468,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Allows creating AOT images for WASM with the AOT compiler and consuming them in the runtime.
> Enable WASM AOT option in build and update MonoAOTCompiler

- mono/metadata/icall-eventpipe.c
- msvc/libeventpipe.targets
- msvc/libeventpipe.targets.filters
!! This PR is a copy of dotnet/runtime#44527,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Adjustments done to better align with implementation of CoreCLR shim using CoreCLR artifacts and C++ code (CoreCLR implementation done in separate PR).
Disconnect runtime specific shim info from shared sources, all included shim files handled through defines.
Exception safety and improved error handling, adding error checking and error returns into shim container functions.
Walkthrough of …
> Adjust Mono EventPipe/DiagnosticServer C library to better support CoreCLR shim.

- mono/metadata/icall.c
!! This PR is a copy of dotnet/runtime#44843,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Based on a comment at https://github.com/dotnet/runtime/pull/32520#discussion_r451336436 that we should improve unit test coverage for `RuntimeHelpers.GetUninitializedObject` before making any changes to the runtime logic. This helps demonstrate that these unit tests pass both before + after any changes to the implementation.
> Improve unit test coverage for GetUninitializedObject

- mono/arch/s390x/s390x-codegen.h
- mono/mini/exceptions-s390x.c
- mono/mini/mini-s390x.c
- mono/mini/mini-s390x.h
- mono/mini/tramp-s390x.c
Fix unwinding for s390x. Removes the `-mbackchain` flag that had been used in the past when unwinding stack frames but has not been required for sometime. This should also improve performance.
> Fix s390x unwinding and remove need for backchain pointer

- mono/metadata/appdomain.c
- mono/metadata/icall-eventpipe.c
- mono/mini/mini-runtime.c
- msvc/libeventpipe.targets
- msvc/libeventpipe.targets.filters
- msvc/libmini.vcxproj
- msvc/libmono-dynamic.vcxproj
- msvc/libmonoruntime.vcxproj
- msvc/mono.props
!! This PR is a copy of dotnet/runtime#44791,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Move C version of EventPipe library into a folder that can be shared by both CoreClr and Mono:
src/common/src/eventpipe
naming follows pattern already in used by coreclr subfolder, src/coreclr/src/...
All runtime specific EventPipe files (shim implementation, build files etc) will be kept under each runtime (mono/mono/eventpipe for example). Example on how shared EventPipe sources will be consumed …
> Move EventPipe C library into shared location.

- mono/mini/llvm-jit.cpp
!! This PR is a copy of dotnet/runtime#44908,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>`assert()` will expand to a no-op if NDEBUG is defined, which can
cause an assertion-enabled LLVM to trap if an `llvm::Expected<T>` is
destroyed before having had `operator bool` applied to it.
> [mono] Unconditionally check llvm::Expected<T> for success

- mono/metadata/icall.c
!! This PR is a copy of dotnet/runtime#44898,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/44852.
> Run class cctor in RuntimeHelpers.GetUninitializedObject(type).

- mono/metadata/fdhandle.c
- mono/metadata/icall.c
- mono/sgen/sgen-descriptor.c
!! This PR is a copy of dotnet/runtime#44747,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Some warnings snuck in after we lost this in the CMake transition. Contributes to https://github.com/dotnet/runtime/issues/41357
> [mono] Fix warnings on OSX and wasm, re-enable -Werror on CI with CMake

- mono/utils/mono-mmap.c
Backport of #20622.
/cc @vargaz
> [2020-02] [runtime] Avoid checking for hardened runtime on ios, its not needed, and it causes alerts because of PROT_WRITE|PROT_EXEC.

- mono/metadata/class-init.c
- mono/metadata/domain.c
- mono/metadata/icall.c
!! This PR is a copy of dotnet/runtime#45125,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Don't implement the `IList<T>` and `IReadOnlyList<T>` for array types if those interfaces are linked out.
Also check for individual methods from the generic interfaces - if the methods aren't used and are linked out, drop them from the array initialization.
Also drop option for pre-.NET 2.0 behavior (in netcore and in mono net 4.x mode)
Related to dotnet/runtime#44859
> [Mono] Arrays shouldn't implement linked out generic classes

- mono/metadata/class-internals.h
- mono/metadata/icall-internals.h
- mono/metadata/icall.c
- mono/mini/mini-runtime.c
Add support to register an external icall getting minimal runtime overhead when called. An icall that can be used without a wrapper needs to follow specific rules in order to correctly collaborate with runtime. All functions are currently internal only and only accessible by runtime or embedders using static linking and fully acknowledge that this is not an optimization available as a public API.
> Add support for external icalls not using a wrapper.

- mono/mini/mini-windows.c
- mono/utils/mono-context.c
- mono/utils/mono-context.h
- mono/utils/mono-threads-windows.c
- mono/utils/win64.asm
Controlled using MONO_HAVE_SIMD_REG_AVX define, disabled by default.
> Enable YMM context support on Windows.

- mono/mini/mini-amd64.h
Fixes https://github.com/mono/mono/issues/20632.
> Use explicit arithmetic checks in the amd64 watchOS simulator.

- mono/mini/mini-amd64.h
Fixes https://github.com/mono/mono/issues/20632.
Backport of #20639.
/cc @imhameed
> [2020-02] Use explicit arithmetic checks in the amd64 watchOS simulator.

- mono/mini/debugger-agent.c
- mono/mini/debugger-engine.c
- mono/mini/debugger-engine.h
- mono/mini/mini-wasm-debugger.c
Runtime workaround fix for incorrect VM resume when suspend policy none is in use. Real fix is in debugger-libs, mono/debugger-libs#264 but until that lands in VS installer (and tooling has been upgraded to VS2019) this workaround will prevent the error to be propagated back to client and VM will make sure the correct suspend state is maintained.
Fix also makes sure logging done within debugger engine/agent is not directly send to stdout/stderr on platforms where there is no console (or alternative console).
This is done to prevent scenarios where stdout/stderr has been redirected to for example the debug client, but logging into the same streams as part of debugger agent implementation will trigger new messages to redirect, flooding the message queue and suspending/resuming the VM for …
> Fix debugger late attach, suspend=n.

- mono/metadata/reflection.c
The lookup assumes that the method came from metadata, which is not the case
for wrappers.
Fixes #20600
> [reflection] Don't get parameter default values for wrapper methods

- mcs/class/corlib/ReferenceSources/RuntimeType.cs
- mono/metadata/cominterop.c
- mono/metadata/cominterop.h
- mono/metadata/icall-def.h
- mono/metadata/icall.c
- mono/metadata/metadata-internals.h
- mono/metadata/metadata.c
- mono/tests/ccw-class-iface.cs
- mono/tests/libtest.c
- mono/utils/mono-digest.h
- mono/utils/mono-md5.c
I'm opening this although it's still WIP, for discussion, as I'm not sure what else I should be adding. Tests probably, of course, but also I was wondering if it should be plugged to RuntimeType.GUID / Marshal.GenerateGuidForType. I'm not entirely sure if that's desired as I've seen clues in the reference source that the GUID generation has issues.
I've left class GUID generation aside, as it doesn't seem so useful for COM interop, and the algorithm uses some Assembly properties to seed the GUID, and retrieving that is currently beyond my understanding of the code.
Also I'm a bit lost regarding which RuntimeType.GUID it should be added to: there's at least two places that looked appropriate : in `mono/netcore/System.Private.CoreLib/src/RuntimeType.Mono.cs` and in …
> [metadata] Generate type-3 GUIDs for interfaces.

- mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/20606.
> [aot] Quote the -Wl,install_name argument to clang.

- mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/20606.
Backport of #20659.
> [2020-02] [aot] Quote the -Wl,install_name argument to clang.

- mono/mini/interp/interp-intrins.c
!! This PR is a copy of dotnet/runtime#45928,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/45889. There was an edge case where the characters ``'`'`` and `'@'` would inadvertently compare as equal under _OrdinalIgnoreCase_. This PR also introduces a unit test to run through all combinations of ASCII chars to look for other edge cases, and it looks like this was the only edge case.
My AMD-based dev box is reporting a tiny perf improvement: …
> Fix bad case-insensitive ASCII equality check

- mono/metadata/Makefile.am
- mono/metadata/marshal-internals.h
- mono/metadata/marshal-noilgen.c
- mono/metadata/marshal.c
!! This PR is a copy of dotnet/runtime#46046,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>I need to be able to use a subset of these to replace the equivalent ilgen version, and previously they were spread out throughout `marshal.c`, meaning it created a really messy diff modifying tons of defines.
We've already created the (somewhat awkward) split with `marshal-ilgen.c`, so I don't see any downside to moving this stuff all out and under a single define. 
also took the opportunity to …
> [mono] Move noilgen marshaling functions to a separate file

- mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/AssemblyMirror.cs
- mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs
- mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs
- mcs/class/Mono.Debugger.Soft/Test/dtest.cs
- mono/mini/debugger-agent.c
This reuses the existing pattern in Mono.Debugger.Soft to retrieve custom attributes.
The only questionable thing is moving the `buffer_add_cattrs` function instead of adding a forward declaration.
> [sdb] Add ability to retrieve custom attributes on assemblies

- mono/tests/ccw-class-iface.cs
The commit d5f338c088defdf81f4374f4e6fbff75c9b1e554 broke the ccw-class-iface test on Windows under .NET Framework. A couple of the tests expect Guid.Empty, but Mono only produces Guid.Empty because GUID generation isn't yet implemented for those classes.
This patch adds the values produced by .NET Framework as accepted values, while still accepting Guid.Empty for now.
> [tests] Accept GUIDs from .NET Framework in ccw-class-iface test.

- mono/mini/Makefile.am.in
Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
This date call works with different variants of the date command.
Also use UTC to be independent of timezone.
This helps a bit towards deterministic mono builds = issue #20172
This PR was done while working on reproducible builds for openSUSE.
> Allow to override build date with SOURCE_DATE_EPOCH

- mono/metadata/class-accessors.c
- mono/metadata/class-init.c
- mono/metadata/class-internals.h
!! This PR is a copy of dotnet/runtime#46366,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>The array fill type `MonoClass` is used to populate the vtable of sgen nursery free space.
Previously we used a static `MonoClass` that was zero-initialized. To make it easier to spot pointers to freed nursery memory, initialize the `class_kind` to a new constant `MONO_CLASS_GC_FILLER`.
Check for the new value explicitly in `class-accessors.c`
> [sgen] Use new MonoClassKind MONO_CLASS_GC_FILLER in mono_class_create_array_fill_type

- mono/metadata/appdomain.c
- mono/metadata/assembly-internals.h
- mono/metadata/assembly.c
- mono/metadata/class-internals.h
- mono/metadata/domain-internals.h
- mono/metadata/domain.c
- mono/metadata/object-internals.h
- mono/mini/driver.c
!! This PR is a copy of dotnet/runtime#46472,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
There's one unrelated functional change here: we don't call `mono_assembly_apply_binding` anymore - binding redirects aren't a thing in .NET 5+  /cc @CoffeeFlux
> Remove managed Mono.MonoDomainSetup class and MonoAppDomainSetup struct

- mono/mini/mini-llvm.c
warning: <unknown>:0:0: 94.12% (64 / 68)
> [llvm] Change branch weights for GC safe points to 1000:1, 64:4 seems to cause a warning from clang:

- mono/metadata/marshal-ilgen.c
- mono/tests/cominterop.cs
- mono/tests/libtest.c
Found while working on WPF clipboard code in Wine Mono. The test case causes a NullReferenceException in Mono but works in .NET Framework.
> [marshal-ilgen] Fix NULL check for blittable out lparray.

- mono/metadata/threads.c
Without proper alignment, this may lead to reference types
being stored at non-pointer aligned offsets. Among other
issues this may lead to the GC not scanning those pointers
properly.
For example, a type such as
```
struct Point
{
public int X;
public int Y;
}
```
will have size 8 and alignment 4 on x64 platforms.
If we reuse the special slot allocated for the `Point` type to store
a reference pointer, it may not be pointer aligned.
> Ensure special static slots respect alignment.

- mono/metadata/cominterop.c
- mono/metadata/image.c
- mono/metadata/marshal-ilgen.c
- mono/metadata/marshal-noilgen.c
- mono/metadata/marshal.c
- mono/metadata/marshal.h
- mono/metadata/metadata-internals.h
- mono/metadata/metadata.c
- mono/metadata/metadata.h
- mono/mini/method-to-ir.c
!! This PR is a copy of dotnet/runtime#46491,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>- Add `mono_marshal_get_native_func_wrapper_indirect` 
This will be used to add a wrapper around `calli <sig>` indirect calls where `sig` has an unmanaged calling convention.
We need to do a GC transition before calling an unmanaged function from managed. So this wrapper does it.
This is reusing much of the code implemented for `mono_marshal_get_native_func_wrapper_aot` which is used for …
> [Mono][jit] Emit GC transitions for "calli unmanaged" instructions

- mono/arch/amd64/amd64-codegen.h
!! This PR is a copy of dotnet/runtime#46573,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>After upgrade to later msvc version on CI boots, see https://github.com/dotnet/runtime/issues/45524 for details, Window x64 Release builds started to crash on libraries tests.
After investigation it turns out that new msvc compiler handles an expression different compared to how it was handled in previous version.
After upgrade of msvc, the expression:
int _amd64_width_temp = ((guint64)(imm) == …
> Fix Mono Windows x64 crash blocking CI Windows x64 Release job.

- mono/metadata/marshal-ilgen.c
- mono/metadata/marshal-internals.h
- mono/metadata/marshal-noilgen.c
!! This PR is a copy of dotnet/runtime#46444,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This flag is not set by default on any platforms, but long-term it should be useful on wasm with the pinvoke generator work being done by the interop team.
This flag reduces around 13k in dotnet.wasm as of today (12/29/2020). However, that is a fairly low-end measurement because this PR only focused on the pinvoke marshaling rather than the full functionality. The structure of our marshaling …
> [mono] Add DISABLE_BLITTABLE for non-blittable marshaling

- mono/mini/mini.h
- mono/mini/simd-intrinsics-netcore.c
- mono/mini/simd-intrinsics.c
!! This PR is a copy of dotnet/runtime#46812,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Mono Windows x64 SIMD support was not fully implemented on netcore causing issues reported in https://github.com/dotnet/runtime/issues/1933. PR integrate logic from Mono Windows x64 SIMD implementation into Mono netcore SIMD implementation needed to correctly handle Windows x64 value type ABI together with SIMD intrinsics.
PR also re-enables SIMD optimization on Windows x64.
> Fix Mono Windows x64 SIMD support.

- mono/metadata/assembly.c
- mono/metadata/class.c
- mono/metadata/metadata-internals.h
- mono/metadata/reflection.c
- mono/tests/Makefile.am
- mono/tests/assemblyresolve_event7.cs
My previous unsuccessful pull request   https://github.com/mono/mono/pull/19804
I have improved the logic so that the code is more systematic
> Try to fix #19803

- mono/metadata/threads.c
!! This PR is a copy of dotnet/runtime#46896,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Revert https://github.com/dotnet/runtime/pull/46390 which reverted the Mono parts of https://github.com/dotnet/runtime/pull/46244.
Fixes https://github.com/dotnet/runtime/issues/46389
The issue was that the code in dotnet/runtime#46244 throws in `Thread` constructors before calling `Initialize`.  Which will then cause a finalizer to run on a partially-initialized thread object, which means that …
> Mono: use shared StartHelper object

- mono/metadata/marshal.c
- mono/metadata/metadata-internals.h
- mono/metadata/metadata.c
- mono/mini/method-to-ir.c
!! This PR is a copy of dotnet/runtime#47006,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>* Parse modopt encoded calling conventions
Add `suppress_gc_transition` bit to `MonoMethodSignature` to add support for the `SuppressGCTransition` unmanaged calling convention modifier.
* Don't emit a wrapper on `calli` if `suppress_gc_transition` is set 
This adds support for `delegate* unmanaged[Cdecl, SuppressGCTransition] <TRet, TArgs...>` function pointers. (And other base calling conventions …
> Mono: support CallConvSuppressGCTransition

- mono/sgen/sgen-gc.c
- mono/sgen/sgen-thread-pool.c
- mono/sgen/sgen-thread-pool.h
- mono/sgen/sgen-workers.c
- mono/sgen/sgen-workers.h
When running parallel minor GC the scan of major and LOS is split up in several jobs based on number of available cores * 4 * 2. On an 8 core machine that will generate 32 major heap and 32 LOS scanning jobs. Current implementation queued each individual job into the thread pool but since the threads where not allowed to work on the items at this point, doing it
this way creates a lot of signalled threads + contention over shared mutex for each queued job.
Commit optimize this pattern adding the ability to add a batch of allocated jobs into the thread pool at the same time, signalling all threads when all, jobs have been added to the queue reducing the number of mutex acquire/release and waking all thread pool threads from 65 (including scan wbroots) down to 1.
This is an upstream of a …
> [SGen] Optimize thread pool enqueue to handle job batches more efficiently.

- mono/eglib/garray.c
!! This PR is a copy of dotnet/runtime#47089,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>dotnet/runtime#32972
This tries to fix this referenced issue.
It changes to the multiplicative growth, renames a makefile to allow compilation, and removes it from the .gitignore.
I am a newcomer to open source so please tell me if I have not submitted something right, thank you!
> Fix to issue dotnet/runtime#32972: Grow GArray multiplicatively

- mono/metadata/jit-icall-reg.h
- mono/mini/aot-runtime.h
- mono/mini/llvmonly-runtime.c
- mono/mini/llvmonly-runtime.h
- mono/mini/method-to-ir.c
- mono/mini/mini-llvm.c
- mono/mini/mini-runtime.c
!! This PR is a copy of dotnet/runtime#47144,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/dotnet/runtime/issues/46613.
> Pop LMF frames in exception handlers on wasm, since the normal pop LMF code might not get executed in case of an exception.

- mono/mini/memory-access.c
!! This PR is a copy of dotnet/runtime#46817,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Part of the fix for https://github.com/dotnet/runtime/issues/46766.
> [jit] Emit a null check for stelem instructions.

- mono/mini/mini-llvm-cpp.cpp
- mono/mini/mini-llvm-cpp.h
- mono/mini/mini-llvm.c
- mono/mini/mini.h
- mono/mini/simd-intrinsics-netcore.c
!! This PR is a copy of dotnet/runtime#47028,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>This change:
- Unpacks SIMD parameters passed via multiple GPRs (`LLVMArgVtypeAsIArgs`) into
local LLVM SSA vector-typed values on function entry. The calling convention we
use on arm and arm64 has "large" value types passed in multiple GPRs when
possible, and the way this is currently encoded in the LLVM IR we emit is by
using parameters with the LLVM type `[Size x {i32 or i64}]`, where the …
> Add basic Vector128 support for arm64.

- mono/mini/aot-compiler.c
!! This PR is a copy of dotnet/runtime#47033,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>
> [aot] Avoid creating runtime invoke wrappers for methods which return a byreflike type, the return value cannot be boxed.

- configure.ac
It causes a build warning on some newer compilers:
```
cc1plus: warning: command line option '-Wc++-compat' is valid for C/ObjC but not for C++
```
> Remove -Wc++-compat option when building Mono as C++

- mcs/tools/mkbundle/template.c
- mcs/tools/mkbundle/template_common.inc
The mono api struct is never initialized causing a segfault in the first method that uses it: install_dll_config_files.
The init funtion init_default_mono_api_struct is also incorrectly included in the #ifdef USE_COMPRESSED_ASSEMBLY, making it available only when using compressed assemblies
> mkbundle: fix initialization segfault in custom mode

- mono/mini/llvm-jit.cpp
- mono/mini/unwind.c
!! This PR is a copy of dotnet/runtime#47391,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Adds a case for `DW_CFA_offset_extended` to `mono_print_unwind_info`,
which avoids a crash when running the runtime with high verbosity.
Initializes the LLVM JIT with LLVM-detected host CPU features.
Unconditionally enables all detected features, instead of using only the
subset supported in `mono_llvm_get_cpu_features`.
> [mono] LLVM on arm64 bugfixes.

- mono/eglib/eglib-remap.h
- mono/eglib/giconv.c
- mono/eglib/glib.h
- mono/eglib/gmodule-win32.c
- mono/metadata/domain-internals.h
- mono/metadata/icall-eventpipe.c
- mono/metadata/jit-info.c
!! This PR is a copy of dotnet/runtime#47339,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Add support into Mono VM emitting rundown events into EventPipe stream. All rundown events emitted by CoreClr during EventPipe rundown phase are now also emitted by Mono, making sure enough meta information is available for tooling to correctly resolve callstacks (not yet emitted) included in EventPipe events emitted by Mono VM.
Re-eanble couple of runtime tests disabled on Mono due to lack of …
> Add Mono EventPipe rundown support.

- mono/metadata/jit-icall-reg.h
- mono/mini/llvmonly-runtime.c
- mono/mini/llvmonly-runtime.h
- mono/mini/method-to-ir.c
- mono/mini/mini-llvm.c
- mono/mini/mini-runtime.c
- mono/mini/mini.h
Instead of failing to compile methods with filter clauses, make them
enter the interpreter.
> [llvmonly] Fall back to the interpreter for methods with filter clauses.

- mono/mini/Makefile.am.in
debugger-protocol.h was missing from the tarball
> Fix rpm build

- mono/mini/debugger-protocol.c
During my last PR about icordebug I included this error, fixing it.
> [debugger] Fix comparison between pointer and zero 

- mono/mini/debugger-protocol.c
- mono/mini/debugger-protocol.h
This error was introduced in my last PR about icordebug implementation. Fixing it as @lambdageek told me that it was reported on coverity scan.
> [mono][debugger] Fixing len as unsigned int and comparing < 0

- man/mono.1
- mono/mini/aot-compiler.c
Context: https://github.com/android/ndk/wiki/Changelog-r22#announcements
Context: https://github.com/xamarin/xamarin-android/pull/5475
This commit fixes a problem where the AOT compiler hard-codes the native
linker executable name to a platform-specific value but such an
executable does not exist in the toolchain being used, thus making the
AOT compiler fail to link the final binary.
The specific use case here is the new Android NDK r22 which not only
deprecates GNU binutils, but also removes architecture-prefixed `ld`
binary (e.g. `aarch64-linux-android-ld` no longer exists). Instead, the
NDK provides a non-prefixed `ld` binary and two prefixed ones:
`$arch-ld.gold` and `$arch-ld.bfd`. However, since the AOT compiler
hardcodes `ld` as the linker name on Linux systems, the AOT compilation …
> [AOT] Make native linker name configurable

- mono/metadata/threads.c
!! This PR is a copy of dotnet/runtime#47816,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>The previous logic would not call `mono_gc_thread_detach` for a number of scenarios. One example:
```
start_wrapper
- mono_thread_info_attach - thread is now live in mono threads layer
- start_wrapper_internal
-- mono_thread_attach_internal - mono attached to vm thread layer. GC handle is set via mono_thread_info_set_internal_thread_gchandle
-- mono_thread_detach_internal - detached from vm thread …
```
> Ensure mono_gc_thread_detach is always called

- mcs/class/System.Data.OracleClient/Test/System.Data.OracleClient.jvm/readme.txt
This password was picked up by credscan. It gives the default password of a database, but I can't find any script that actually uses that default password. It seems like we may as well just remove it.
> Remove incorrect password

- mono/mini/trace.c
On a CEE_MONO_ICALL set to **mono_threads_detach_coop** (from native to managed), the profile code is always emitted without a return value, since it's not at a ret. This means it's never set, even if there actually is a return type (other than TYPE_VOID). When tracing, it's assumed that valid result types other than TYPE_VOID can be dereferenced, even though in this case no result has been set. This causes a null dereference fault.
> Don't assume result is non-NULL if its type is not TYPE_VOID when tracing.

- scripts/ci/mono-ci-job-template.yml
- scripts/ci/mono-ci.yml
The magic at https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/5867980d00afd4d11385810129bc62f8135b6c2e/src/ubuntu/18.04/mono/arm32v7/Dockerfile#L40 should allow us to run ARMv7 jobs on an ARM64 build pool.
> Add an ARMv7 lane, which runs on our AARCH64 pool

- mcs/class/System.ServiceModel/System.ServiceModel.Channels.Http/HttpReplyChannel.cs
- Add PATCH verb to be processed in WCF request.
- Validate if ContentType is present. WCF was simply not responding if ContentType is not reported.
Fixes #20611
> WCF process PATCH verb

- configure.ac
- mono/arch/arm64/Makefile.am
- mono/arch/arm64/arm64-codegen.h
- mono/arch/arm64/codegen-test.c
- mono/eglib/eglib-remap.h
- mono/mini/aot-compiler.c
- mono/mini/exceptions-arm64.c
- mono/mini/helpers.c
- mono/mini/llvm-jit.cpp
- mono/mini/mini-arm64.c
- mono/mini/mini-arm64.h
- mono/mini/mini-llvm.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
- mono/mini/mini.c
- mono/mini/mini.h
- mono/mini/trace.c
- mono/mini/tramp-arm64-gsharedvt.c
- mono/mini/tramp-arm64.c
- mono/tests/Makefile.am
- mono/tools/offsets-tool/offsets-tool.py
- mono/utils/mono-codeman.c
- mono/utils/mono-codeman.h
- mono/utils/mono-dl.h
- mono/utils/mono-merp.c
- mono/utils/mono-mmap.c
- sdks/builds/.gitignore
- sdks/builds/mac.mk
- support/sys-uio.c
Adds Apple silicon support from https://github.com/mono/mono/pull/20597 to 2020-02, tested against xamarin/xamarin-macios#10115 and it works!
> [2020-02] Backport Apple silicon support

- mono/utils/dtrace.h
offsets-tool can run before mono-dtrace.h is generated which leads to a compiler error about the file missing.
This happened with the mac arm64 sdks build where we didn't disable dtrace like we do for iOS.
It was racy since it depends on whether we already built the target mono before we're building the cross compiler mono.
> Don't include mono-dtrace.h when generating offsets

- mcs/class/System/Mono.Btls/MonoBtlsContext.cs
When using SslStream.AuthenticateAsServer, the incoming certificate will be an X509Certificate(2). It will never have the "intermediate" certificates attached. The chain of intermediate certificates needs to be rebuilt on the fly.
I believe this could fix #20505, but bug complaints about missing intermediate certificates in server authentication date back to BugZilla times.
> Allow sending intermediate certificates with SslStream.AuthenticateAsServer.

- mono/metadata/marshal-ilgen.c
- mono/metadata/metadata.c
- mono/tests/cominterop.cs
- mono/tests/libtest.c
Manual backport of #20917 to `2020-02` (6.12).  but also **new** BSTR fixes
---
Partial revert of #8732
If a managed struct is declared as
public struct StructWithVariant
{
[MarshalAs (UnmanagedType.Struct)]
public object data;
};
Then the `data` field should be marshalled as a VARIANT.
The fix checks that the field's type is `object` and uses VARIANT for marshaling, otherwise it continues as in #8732 and uses MONO_MARSHAL_CONV_OBJECT_STRUCT.
---
Also added support for marshaling BSTR in structs in reverse P/Invokes.  Morally it's a piece of https://github.com/mono/mono/pull/19701 but just for the `BSTR_STR` case
> [2020-02][marshal] Fix VARIANT and BSTR marshaling in structs

- mono/metadata/metadata.c
- mono/tests/cominterop.cs
- mono/tests/libtest.c
Partial revert of #8732
If a managed struct is declared as
public struct StructWithVariant
{
[MarshalAs (UnmanagedType.Struct)]
public object data;
};
Then the `data` field should be marshalled as a VARIANT.
The fix checks that the field's type is `object` and uses VARIANT for marshaling, otherwise it continues as in #8732 and uses MONO_MARSHAL_CONV_OBJECT_STRUCT.
---
Also added tests for BSTR marshaling inside structs.  This actually works on mono master thanks to https://github.com/mono/mono/pull/19701 but there was no test covering this case.
> [marshal] Fix VARIANT marshaling in structs

- mcs/class/Mono.Debugger.Soft/Test/dtest.cs
- mono/mini/mini-runtime.c
It was causing a side effect on Unity, I will study it again while implement multithread on icordebug.
Reverting part of this PR https://github.com/mono/mono/pull/19103
> [debugger] Removing call to jit_done to help debug multithread

- mcs/class/corlib/Test/System/StringTest.cs
- mcs/class/corlib/corefx/CompareInfo.cs
Backport of https://github.com/mono/mono/pull/20960 to the `2020-02` branch
Issue: https://github.com/mono/mono/issues/20948
> [2020-02] Fix the System.String.Replace throwing NotImplementedException

- configure.ac
- packaging/MacSDK/msbuild.py
- packaging/MacSDK/nuget.py
Bump to MSBuild vs16.9, Roslyn 3.9.0 and NuGet 5.9.0
> Bump msbuild, roslyn and nuget

- configure.ac
- packaging/MacSDK/msbuild.py
- packaging/MacSDK/nuget.py
Bump to MSBuild vs16.9, Roslyn 3.9.0 and NuGet 5.9.0
Backport of https://github.com/mono/mono/pull/20979
> [2020-02] Bump msbuild, roslyn and nuget

- mono/utils/jemalloc/Makefile.am
- mono/utils/jemalloc/SUBMODULES.json
This updates the build to consume upstream jemalloc releases starting with 5.2.1 (Aug 2019) while preserving the public and private prefixing. This passed testing locally without issue, but definitely could use a once over by a more familiar set of eyes. I tested with both `--with-jemalloc` and `--use-jemalloc-always` successfully on Ubuntu, Alpine, and FreeBSD.
> Update to consume jemalloc upstream releases

- mcs/class/corlib/Test/System.Reflection/FieldInfoTest.cs
- mono/metadata/object.c
Fixes #20872
See that bug for a sort-of longwinded explanation and test case, alternatively there is a shorter reproduction here: https://gist.github.com/spaarmann/0d74ba8dee2c60ea3b21a9dd0741fbcb.
Setting a pointer via reflection incorrectly added an extra layer of indirection, and getting a pointer via reflection incorrectly dereferenced the value once.
As a result, setting and then getting only via reflection worked correctly, but doing either step by directly accessing the field and the other via reflection was broken.
This was actually mentioned [here](https://github.com/mono/mono/pull/14557#issuecomment-494682176) by @filipnavara when this code was last touched, but that seems to have never been acted on :)
Also adjusts `FieldInfoTest` to test this, for both static and instance …
> Fix setting or getting pointer fields with reflection

- mono/metadata/threadpool-io.c
This is needed to fix https://github.com/godotengine/godot/issues/21895.
Taken from Unity's Mono fork: https://github.com/Unity-Technologies/mono/commit/37dc7aae643fa1d86f183044379352eac074d96e
> Fix console warning spam in threadpool-io.c

- mono/metadata/w32process-unix.c
- mono/utils/mono-proclib.c
- mono/utils/mono-proclib.h
During our upgrade of the mono runtime we ran into a situation where `mono_pe_file_map` was being called as part of opening an image now on android. This function did not currently adhere to the filemap wrapper functions so the difference in data types being used by Unity caused crashes.
> Correcting proclib function that did not adhere to filemap wrappers

- mono/mini/mini-arm64-gsharedvt.c
Transitioning from ArgVtypeByRefOnStack to ArgVtypeByRef requires no marshalling. The reference ends up being saved on stack the same way and the stack slot just needs to be copied (in mono_arm_start_gsharedvt_call).
Backport of https://github.com/dotnet/runtime/pull/50772
> [arm64] Fix wrong marshalling in gsharedvt transition

- mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStripMenuItem.cs
> [WinForms] Fix #19755: Make ToolStripMenuItem constructor handle shortcut parameter

- mcs/class/System.Windows.Forms/System.Windows.Forms/Timer.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/XplatUICarbon.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/XplatUIX11.cs
If you change the system time back a minute, then the timer will work only after a minute, even if you set its timeout to 500 milliseconds.
This fix uses a system-independent timing with Stopwatch.GetTimestamp ()
> [WinForms] Fixed dependence of the countdown in the System.Windows.Forms.Timer on the system time.

- mcs/class/System.Windows.Forms/System.Windows.Forms/GridEntry.cs
The OnPropertyValueChanged event should tell the event handler about the old value of the property being changed using the OldValue field of the PropertyValueChanghedEventArgs class, but actually reports the new one by reading it from the changed Value. Therefore, we save the old value before the change that occurs in SetValueCore.
> [WinForms] Fix OnPropertyValueChanged behavior

- mcs/class/System.Windows.Forms/System.Windows.Forms/X11Structs.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/XplatUIX11.cs
The _Application Menu Button_ at the _Gnome Shell_ displays wrong application name -- it contains just a word _Unknown_. 
It seems this issue stems from the function `shell_app_get_name` in the https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/gnome-3-38/src/shell-app.c#L256. Hence one need to set `WM_CLASS` to fix app name.
> [WinForms] Form: Set `WM_CLASS` while change `Text`

- mcs/class/System.Windows.Forms/System.Windows.Forms/GridEntry.cs
Type Convertor isn't invoked for `GridEntry` value at the present time. Current PR is aimed to fix this.
> [WinForms] GridEnty: Invoke type converter to display entry value properly

- mcs/class/System.Windows.Forms/System.Windows.Forms/ButtonBase.cs
When the OnClick event occurs on a Button mouse click, MouseEventArgs should be passed to it instead of the usual EventArgs. Then in the event handler you can see which key is pressed and the coordinates of the mouse cursor. Now the behavior is the same as in .net
> [WinForms] Pass MouseEvetArgs to OnClick event

- mcs/class/System.Windows.Forms/System.Windows.Forms/ListView.cs
- mcs/class/System.Windows.Forms/Test/System.Windows.Forms/ListViewTest.cs
When the ListView has VirtualMode=true, calling the Clear method for Items should not throw an exception. This is how .NET behaves
> [WinForms] Do not throw InvalidOperationException when ListView in VirtualMode calls Items.Clear

- mono/mini/mini-arm64-gsharedvt.c
Transitioning from ArgVtypeByRefOnStack to ArgVtypeByRef requires no marshalling. The reference ends up being saved on stack the same way and the stack slot just needs to be copied (in mono_arm_start_gsharedvt_call).
> [2020-02][arm64] Fix wrong marshalling in gsharedvt transition

- mono/metadata/w32file-unix.c
Backport of #21041 to 2020-02
---
Related to https://github.com/mono/mono/issues/21040 and
https://github.com/dotnet/runtime/issues/48663
On MacOS Big Sur open() is much more likely to throw EINTR - and moreover if the thread receives a signal while doing an open() even if the signal handler is marked with SA_RESTART, the open call appears not to restart and to fail anyway.
So wrap all the calls to open() in retry loops.
> [2020-02][MonoIO] Wrap calls to open() in EINTR handling

- mono/metadata/marshal.c
If the method or type containing the icall instruction has a
generic parameter, the resulting signature is "inflated" even if
the generic parameter is not used in the signature. This breaks
some methods in SlimDX, and probably other C++/CLI code.
> Remove !sig->is_inflated assert from icall wrapper generator.

- mono/metadata/native-library.c
!! This PR is a copy of dotnet/runtime#52307,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Fixes https://github.com/mono/mono/issues/21034
The leaked memory was the duplicated strings after the first assembly-specific lookup. If that lookup failed, they were overwritten with the global lookup and never freed.
> [mono] Fix leak in assembly-specific dllmap lookups

- mono/mini/method-to-ir.c
Fix for null-pointer bug found with Clang's undefined-behavior-sanitizer using `-fsanitize=null`
https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
> Fix for null pointer bug found by UBSAN

- mono/metadata/icall.c
Addressing 4 issues for GetInterfaceMap and default interface methods
Only methods marked as virtual on on interface should be added to the
interface map. (no static or instance)
If the found target method is ambiguous (a diamond) the target is
null.
If the found target method's class in an interface, then the target
class is the interface class, else it is the class of the RuntimeType
(aka this)
If the found target method is abstract (reabstraction) then the
target is null.
https://github.com/dotnet/runtime/blob/6072e4d/src/tests/reflection/DefaultInterfaceMethods/GetInterfaceMapConsumer.cs
dotnet/runtime PR: https://github.com/dotnet/runtime/pull/52566
> Fixing the GetInterfaceMap tests for mono in the runtime repo.

- mcs/tools/wasm-tuner/InterpToNativeGenerator.cs
- mono/mini/wasm_m2n_invoke.g.h
@vargaz it turned out that IIIIL was not all I needed. I also need LIIIL for preadv|pwritev and IILL for posix_fallocate
> [mono][wasm] add new signatures for pread|pwrite, preadv|pwritev, posix_fallocate

- mcs/class/System/System.Net.NetworkInformation/Ping.cs
Avoid Windows socket error code WSAEMSGSIZE when receiving the ping
reply for larger sent payloads.
> Increase the buffer size for ping reply

- mono/utils/mono-sigcontext.h
There are three changes required to build mono on OpenBSD/arm64.
- The first one is to provide the UCONTEXT macros, which for OpenBSD simply map to sigcontext.
- Furthermore as stated in issue #21005, https://github.com/mono/boringssl/compare/mono...bluerise:obsd is necessary for boringssl so that it can be built.
- And last, bdwgc needs to be patches as well: https://github.com/Unity-Technologies/bdwgc/pull/62
> Add support for OpenBSD/arm64

- mcs/class/Mono.Debugger.Soft/Makefile
- mcs/class/Mono.Debugger.Soft/Test/dtest-app-opt.cs
- mcs/class/Mono.Debugger.Soft/Test/dtest.cs
- mono/mini/debugger-engine.c
- mono/mini/mini-amd64.c
- mono/mini/mini-exceptions.c
- mono/mini/mini.h
Assertion at C:\build\output\Unity-Technologies\mono\mono\mini\debugger-engine.c:1657, condition `is_ok (error)' not met, function:set_set_notification_for_wait_completion_flag, Could not execute the method because the containing type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[T_REF]', is not fully instantiated. assembly:<unknown assembly> type:<unknown type> member:(null)
> [debugger] Fix assertion when trying to debug an async method in a valuetype

- mcs/class/System.Windows.Forms/System.Windows.Forms/Application.cs
Fix regression introduced in #20953
If we do not use this typecasting, then NRE will occur in line 910 for MenuStrip with submenu embedded in the form.
> [WinForms] MenuStrip: Close toplevel menu if some click somewhere outside of it

- mcs/class/System.Windows.Forms/System.Windows.Forms/PrintPreviewControl.cs
- mcs/class/System.Windows.Forms/Test/System.Windows.Forms/PrintPreviewControlTest.cs
If a reference to PrintDocument is passed to PrintPreviewControl, and then this control is displayed on the form,
then original PrintController of the PrintDocument will be replaced by previewController and if you call print for PrintController,
then the print page will not be sent to printer.
> [WinForms] Fix changing reference to PrintController in preview in PrintPreviewControl

- mono/metadata/class-inlines.h
- mono/metadata/icall.c
If the interface method is reabstracted, and either the found implementation
method is abstract, or the found implementation method is from another
DIM (meaning neither klass nor any of its ancestor classes implemented the
method), then say the target method is null. Otherwise return the found
implementation method, even if it is abstract.
Corresponding dotnet/runtime PR is https://github.com/dotnet/runtime/pull/53972
Fixes https://github.com/dotnet/runtime/issues/53933
> Don't return null target methods in GetInterfaceMap for abstract classes, or classes using DIMs

- mono/mini/mini-posix.c
> Fix for heap_use_after_free flagged by sanitizer

- mono/mini/unwind.c
Hi this is an alternative approach for problem described in #21108
According to your comment there we implemented similar optimization by using hashtable, while it has bit more memory overhead than original code, it still performs equally fast on same system. However apparently potentially hashtable approach will perform better on larger projects. So please decide which solution is better from your point of view.
> optimize adding unwind info entries by hashtable

- mono/metadata/image.c
!! This PR is a copy of dotnet/runtime#55201,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>* The mono_refcount_inc call in mono_image_storage_trypublish or
mono_image_storage_tryaddref may abort when racing against a
mono_image_storage_dtor that already decremented the refcount.
This race triggered in some cases when building aspnetcore using a Mono-based dotnet host SDK.   The problem is that `mono_image_storage_close` runs outside the `mono_images_storage_lock` (and this may be …
> [mono] Fix race during mono_image_storage_open

- mono/metadata/sgen-bridge.c
- mono/metadata/sgen-bridge.h
- mono/metadata/sgen-client-mono.h
- mono/metadata/sgen-mono.c
!! This PR is a copy of dotnet/runtime#55681,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Mark it as an external only API.  In the runtime, use `mono_gc_wait_for_bridge_processing_internal`
> [sgen] Transition to GC Unsafe in mono_gc_wait_for_bridge_processing

- mono/mini/abcremoval.c
!! This PR is a copy of dotnet/runtime#56508,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Detected by valgrind.
> [mono] Fix an uninitialized memory access in the ABCREM pass.

- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
Manual backport of #21185  to `2020-02`
---
Add a new mono_pmip_u that doesn't do the transition.
The intent is that Mono developers in the debugger can call still call
mono_pmip_u if the thread state machine is in a broken state.
Fixes #21184
> [2020-02][mini] Add GC Unsafe transitions in mono_pmip

- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
Add a new mono_pmip_u that doesn't do the transition.
The intent is that Mono developers in the debugger can call still call
mono_pmip_u if the thread state machine is in a broken state.
Fixes #21184
> [mini] Add GC Unsafe transitions in mono_pmip

- mcs/class/Mono.Profiler.Log/Mono.Profiler.Aot/ProfileWriter.cs
In some cases, it seems like Mono.Profiler.Aot `ProfileWriter` can produce custom profiles that are unable to be read by `ProfileReader` (or `aot-compiler.c`). There are a few reports [here](https://github.com/xamarin/xamarin-android/issues/4602#issuecomment-618201419).
I investigated and found a cause may be the writing of incorrect string length markers in situations where `String.Length` is less than the encoded byte length. In that kind of case, the reader falls out of sync with the record structure and quickly fails. [Here is an example dependency](https://www.fuget.org/packages/AuroraControls.Core/1.2020.520.2/lib/netstandard2.0/Aurora.dll) with members that can produce the issue (I guess the odd characters are caused by obfuscation).
I don't think the change requires a profile …
> [Mono.Profiler.Aot] Write true string wire length

- mono/mini/method-to-ir.c
When a callvirt instruction is encountered on a static method, there is
a hard abort/crash. This commit avoids the problem.
> Adding null check to avoid abort when invalid IL is encountered

- mono/metadata/image.c
- mono/metadata/metadata.c
Backport some fixes done in the past year to metadata loading that are surfacing as crashes in VSMac:
Related:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1344181/
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1367602/
❗There are a few other changes (covariant returns and suppressgctransition) that I have not backported as they conflict.
I think the main problem was https://github.com/mono/mono/commit/58f650c2f54d96bdc9da74d07d0a2fc0cd8cbd34, which I'm not sure whether it's safe to backport.
cc @slluis @lambdageek @kdubau
> 2020 02 backport metadata fixes

- mono/btls/btls-error.c
This return statement is dead code and can’t be reached. Remove it.
> Remove dead code in blts-error

- mono/metadata/metadata-verify.c
Update the SectionAlignment and FileAlignment validate to match the
ms docs...
https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#optional-header-windows-specific-fields-image-only
"SectionAlignment
The alignment (in bytes) of sections when they are loaded into memory
It must be greater than or equal to FileAlignment. The default is the
page size for the architecture."
"FileAlignment
The alignment factor (in bytes) that is used to align the raw data of
sections in the image file. The value should be a power of 2 between 512
and 64 K, inclusive. The default is 512. If the SectionAlignment is less
than the architecture's page size, then FileAlignment must match
SectionAlignment."
For the import table use a case insensitive compare for the mscoree.dll
file name.
> Update portable executable and import table validation

- mcs/class/Mono.Options/Documentation/en/Mono.Options/ArgumentSource.xml
- mcs/class/Mono.Options/Documentation/en/Mono.Options/CommandSet.xml
- mcs/class/Mono.Options/Documentation/en/Mono.Options/OptionException.xml
- mcs/class/Mono.Options/Documentation/en/Mono.Options/OptionSet.xml
- mcs/class/Mono.Options/Documentation/en/Mono.Options/OptionValueCollection.xml
- mcs/class/Mono.Options/Documentation/en/Mono.Options/OptionValueType.xml
- mcs/class/Mono.Options/Documentation/en/Mono.Options/ResponseFileSource.xml
- mcs/class/Mono.Options/Mono.Options/Options.cs
- mcs/class/Mono.Options/Mono.Options_test.dll.sources
- mcs/class/Mono.Options/Test/Mono.Options/CaseSensitivityTests.cs
Added constructors to OptionSet to allow for Case Insensitive command line arguments. Will be Case Sensitive by default, and can pass StringComparer.OrdinalIgnoreCase to use Case Insensitive which is passed to the base KeyedCollection<string, Option>. Added related unit tests in CaseSensitivityTests.cs.
> Allow Case Insensitive OptionSet

- support/serial.c
Cherrypick #20219 and #21204 to `2020-02`
Pseudo-TTYs are usable if `ioctl` `TIOCMGET` returns `EINVAL` or `ENOTTY`
Thanks @csanchezdll !
> [2020-02][linux] Some pseudo-tty fixes

- mono/mini/mini-trampolines.c
!! This PR is a copy of dotnet/runtime#58521,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Don't unbox a valuetype `this` if the generic method is a DIM
Fixes https://github.com/dotnet/runtime/issues/58394
Fixes #21206
> [mini] Don't add unbox tramopline on generic DIM calls

- mono/metadata/native-library.c
- mono/utils/mono-dl-windows.c
Fixes #21122 
We have existing code for this, but as the test case shows, it doesn't work. It's not really clear how it's supposed to work, since all it does is skip the "#" in the entry point name. GetProcAddress does not interpret numeric strings as ordinals, but it will interpret a pointer address from 1 to 65535 as an ordinal.
> Fix ordinal imports on Windows.

- packaging/MacSDK/fsharp.py
.NET 6 RC 2 adds an MSBuild check to see that the VisualStudioVersion
property is below 17.0 and reports a not supported warning if this is
the case. Updating the VisualStudioVersion to 17.0 used in Visual
Studio for Mac 17.0 to fix this warning breaks F# SDK projects and
classic F# projects since Mono's MSBuild tries to load F# targets
files from a directory which does not exist:
xbuild/Microsoft/VisualStudio/v17.0/FSharp
Adding a v17.0 directory to Mono allows Visual Studio for Mac 17.0
to define VisualStudioVersion to be 17.0 and restore and build F#
projects.
> [MacSDK] Add F# targets to VisualStudio/v17.0 directory

- mono/mini/mini-s390x.c
!! This PR is a copy of dotnet/runtime#61009,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>* Remove incorrect conversion in the cfg->r4fp case
* Fixes System.Threading.Tests.InterlockedTests.InterlockedExchange_Float
CC @nealef @akoeplinger @steveisok
> [mono][s390x] Fix OP_MOVE_F_TO_I4 codegen bug

- mono/mini/mini-native-types.c
Ref: https://github.com/xamarin/xamarin-macios/pull/13092
> Allow nfloat to be in the ObjCRuntime namespace, and make it work for Xamarin.MacCatalyst.dll as well.

- mono/metadata/debug-helpers.c
- mono/mini/mini.c
!! This PR is a copy of dotnet/runtime#61520,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>Implement method name wildcard matching for method descriptions
Globbing doesn't work because we don't have g_pattern_match_simple in eglib.
But a plain '*' wildcard does work.  
Also `'className:*'` works.  (`*:methodName` already worked)
> [mini] Allow MONO_VERBOSE_METHOD='*:*'

- data/config.in
New MacOS Monterey is not correctly resolving dylib locations when dllmap configuration is not specifying full paths, this makes VS4Mac use libcairo-2.dll from a dependency of a installed library in Hombrew.
A workaround was set full path to libcairo-2 and this fixed the problem.
> Adds full path to libcairo for correct assembly directory resolution in monterey

- mono/metadata/cominterop.c
- mono/tests/cominterop.cs
The CCW methods for IUnknown (and in principle IDispatch - except they all have trivial bodies) are native C code in the runtime that may allocate coop handles.  Add a coop handle frame around the entire call in order to make sure they're cleaned up and don't retain a reference.
This helps fix managed object leaks with code like:
```csharp
var o  = new SomeClass();
var pUnk = Marshal.GetIUnknownForObject(o);
int c = Marshal.Release(pUnk);
o = null;
```
Which retains a reference to the `SomeClass` instance that won't be collected until the thread dies, despite cleaning up the IUnknown refcount. The underling ccw addref/release methods leak coop handles on the thread.
This is not an issue when the CCW calls some managed method because there are no coop handles there until some icall (at …
> [cominterop] Add coop handle enter/return on native CCW methods 

- tools/pedump/pedump.c
Fixes #21372 by changing index in dump_blob from int to guint32
> Fixes #21372 index overflow in pedump.c:dump_blob

- mono/sgen/sgen-cardtable.c
- mono/sgen/sgen-marksweep.c
Fixes #21369
Related to https://github.com/xamarin/xamarin-android/issues/6546
job_major_mod_union_preclean can race with the tarjan bridge
implementation that changes the vtable pointer by settings the three
lower bits. this results in invalid loading of the vtable
(shifted by 7 bytes)  which in turn give a wrong desc to the scan
functions
> transform sgen_get_descriptor to parallel safe version in job_major_mod_union_preclean

- mono/mini/interp/transform.c
These structures are valuetypes, but their mint_type is a primitive. This means that a LDFLD applied on the type would have attempted to do a pointer dereference, because it saw that the current top of stack is not STACK_TYPE_VT. This was fixed in the past by passing the managed pointer to the valuetype rather than the valuetype itself, against the normal call convention, which lead to inconsistencies in the code.
This commit removes that hack and fixes the problem by ignoring LDFLD applied to nint/nfloat valuetypes in the first place.
Backport of https://github.com/dotnet/runtime/pull/61612
https://github.com/dotnet/runtime/issues/61153
> [interp] Remove hack for nint/nfloat

- mono/metadata/object.c
The mono_field_static_get_value method uses a handle, but did not set up
enter/exit macros properly, so this handle was leaked.
Some code in Unity calls this embedding API method pretty often, which
can lead to the mark stack overflowing in the GC code.
> Add missing handle function enter/return macros

- configure.ac
- mono/metadata/icall.c
- mono/metadata/threadpool-worker-default.c
- mono/metadata/threadpool.c
- mono/sgen/sgen-marksweep.c
- mono/utils/Makefile.am
- mono/utils/memfuncs.c
- mono/utils/memfuncs.h
- mono/utils/mono-cgroup.c
- mono/utils/mono-proclib-windows.c
- mono/utils/mono-proclib.c
- mono/utils/mono-proclib.h
Add capability to interrogate cgroup limitations when determining CP and memory limits
This code has been adapted from coreCLR. It has been modified from C++ but uses the same naming conventions in the event of a unified mechanism that can be shared between both runtimes being developed. The code has been tested on Ubuntu 20.04 and CentOS 7 with cgroupv1 and cgroupv2. 
This code is required in the event of running mono in a container as the current limitations being discovered by mono are purely for the machine and not in a container which may have lower quotas.
* mono/utils/Makefile.am
- Add new file to build
* mono/utils/memfuncs.c
- Call `getRestrictedPhysicalMemoryLimit()` or `getPhyscalMemoryAvail()`
* mono/utils/memfuncs.h
- Add prototypes for the new APIs
* mono/utils/mono-cgroup.c …
> Determine any memory/CPU limitations from sysfs cgroup 

- mono/mini/image-writer.c
Xamarin.Android is trying to (partially) switch to LLVM-based toolchain
and it appears that the llvm-mc assembler doesn't accept .hword as a
valid directive for x86 targets. Since it's an alias for .short,
which works fine, the change should be safe across all the architectures
supported by AOT.
> [AOT] Use .short directive instead of .hword

- mono/metadata/icall.c
!! This PR is a copy of dotnet/runtime#64214,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When the field is byref but the value being passes in is not, throw an
ArgumentException. Without this change the call to
mono_object_handle_pin_unbox will assert and kill the process.
This can occur when de-serializing an object and the field types have
changed.
> Avoid an assert in ves_icall_RuntimeFieldInfo_SetValueInternal

- mono/metadata/class-setup-vtable.c
!! This PR is a copy of dotnet/runtime#64102,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>When processing the overrides from interface default methods we should
check if the interface class is a generic type definition first and
inflate with the interface class context.
Test case included.
Fixes dotnet/runtime#61244
> vtable setup fix for generic default interface methods in mono runtime

- mono/metadata/class-init.c
Backport of #21421 to `2020-02`
When processing the overrides from interface default methods we should
check if the interface class is a generic type definition first and
inflate with the interface class context.
Related to dotnet/runtime#61244
> [2020-02] vtable setup fix for generic default interface methods in mono runtime

- mono/metadata/object.c
- mono/mini/mini-exceptions.c
!! This PR is a copy of dotnet/runtime#60770,  please do not edit or review it in this repo !!<br/>Do not automatically approve this PR:<br/><br/>* Consider how the changes affect configurations in this repo,<br/>* Check effects on files that are not mirrored,<br/>* Identify test cases that may be needed in this repo.<br/><br/>!! Merge the PR only after the original PR is merged !!<br/><hr/><br/>- Fix StackTrace when called from a DIM.
- Fix the other test case that was added for @bholmes, and this case when the method `TestMethod5` was being called it was executing `TestMethod10`, and this was fixed skipping static interface methods when was calculating vtable offsets.
The fix was completely done by @vargaz, I just opened the PR.
Thanks @vargaz .
Fix …
> [mono] Fix StackTrace from a dim and Vtable offsets for static interface method

- mcs/tools/mono-api-html/MarkdownFormatter.cs
One of the changes in macios revealed a bug in which @new can be null
resulting in a NRE like the one that follows:
```
System.NullReferenceException: Object reference not set to an instance of an object
2022-01-26T09:23:11.9538790Z   at Mono.ApiTools.MarkdownFormatter.DiffModification (System.Text.StringBuilder output, System.String old, System.String new, System.Boolean breaking) [0x00013] in /Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/mcs/tools/mono-api-html/MarkdownFormatter.cs:181
2022-01-26T09:23:11.9543530Z   at Mono.ApiTools.ApiChange.AppendModified (System.String old, System.String new, System.Boolean breaking) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/mcs/tools/mono-api-html/ApiChange.cs:49
2022-01-26T09:23:11.9547700Z …
```
> [Tools] Fix mono-api-html MarkdownFormatter.cs to avoid a NRE

- mono/eglib/Makefile.am
- mono/eglib/eglib-remap.h
- mono/eglib/gclock-nanosleep.c
- mono/eglib/gdate-unix.c
- mono/eglib/glib.h
- mono/mini/mini-posix.c
- mono/utils/mono-threads.c
Fixes https://github.com/xamarin/xamarin-android/issues/6600
Backported from https://github.com/dotnet/runtime/pull/64679 and https://github.com/dotnet/runtime/pull/65373
> [Android] Workaround for invalid return value from clock_nanosleep

- mono/eglib/Makefile.am
- mono/eglib/eglib-remap.h
- mono/eglib/gclock-nanosleep.c
- mono/eglib/gdate-unix.c
- mono/eglib/glib.h
- mono/mini/mini-posix.c
- mono/utils/mono-threads.c
Fixes https://github.com/xamarin/xamarin-android/issues/6600
Backported from https://github.com/dotnet/runtime/pull/64679 and https://github.com/dotnet/runtime/pull/65373
Backported to 2020-02 from #21433
> [2020-02][Android] Workaround for invalid return value from clock_nanosleep

- mono/metadata/cominterop.c
Free the method builder after compiling the wrapper.
This is already fixed on mono/mono `main` as part of the refactoring in
https://github.com/mono/mono/pull/19768 (And that change was also propagated to
dotnet/runtime)
> [2020-02][cominterop] Fix CCW memory leak

- mono/mini/aot-compiler.c
- mono/mini/mini-llvm.c
According to Apple's headers, it's not used anymore, and ignored.
However, with Xcode 13.3, it seems Apple has re-used this value for something
else, and it's causing warnings in the linker:
> ld: warning: '[...]/arm64/Xamarin.iOS.dll.o' was built with class_ro_t pointer signing enabled, but previous .o files were not
Fixes https://github.com/mono/mono/issues/21450.
Ref: https://opensource.apple.com/source/objc4/objc4-818.2/runtime/objc-abi.h.auto.html
> [AOT] Don't set the 'CorrectedSynthesize' flag in the objc_imageinfo section.

- mono/mini/mini-exceptions.c
Fixes dotnet#67354.
pick of dotnet PR https://github.com/dotnet/runtime/pull/69292 from @vargaz
> [mono] Fix a crash during stack trace construction if a this object is null

- mono/metadata/domain.c
- mono/metadata/threads.c
When a domain is unloaded, it is possible that an InternalThread
has a reference to an app context from the unloaded domain.
> Set app context to null on thread detach

- .gitmodules
- mono/metadata/threadpool-worker-default.c
Backport threadpool worker timeout fix to 5.16 (2018-06). The fix has been recreated manually as cherrypicking would not work.
> Backport 4caf2b3dccee96d3d3bf1b95972761e32e62117c to 5.16

- mono/mini/mini-generic-sharing.c
Backport https://github.com/mono/mono/pull/19859 and https://github.com/mono/mono/pull/20217
Reported by user https://github.com/dotnet/runtime/issues/68849
> Backport fixes for sharing wrappers when type attributes are involved

- mono/utils/memfuncs.c
- mono/utils/mono-cgroup.c
- mono/utils/mono-hwcap-s390x.c
- mono/utils/mono-proclib.c
- mono/utils/mono-proclib.h
Update memory usage calculation in line with comments made in  [coreCLR cgroup PR](https://github.com/dotnet/runtime/pull/64128).
The other significant change is the use of `sysconf(_SC_PHYS_PAGES)`. In the earlier version of this code I had used `sysconf(_SC_AVPHYS_PAGES)`.  The latter is often significantly smaller (by an order of magnitude) to the former meaning that the value returned may be quite low. However, I am unsure whether mono already takes this into account. For example, running in with no-cgroup restrictions on a 16G virtual machine would report a `_SC_AVPHYS_PAGES` value of 79138 pages resulting in a memory value of 324149248 bytes (309MB) being returned. When setting cgroup constraints:
```
systemd-run -q --scope -p CPUQuota=400% -p MemoryLimit=13G
```
We'd also return …
> CGroup fix to match coreCLR PR 64128

- mono/mini/debugger-agent.c
In this particular case, one of the method arguments has a type that
can not be resolved and the signature code returns null.
This is a cherry-pick from the the Unity Mono repo...
https://github.com/Unity-Technologies/mono/pull/1658
> Avoid a crash when the debugger code fails to lookup the signature

- docs/produce-lists
- mcs/Makefile
- mcs/class/I18N/CJK/gb2312-build.sh
- sdks/android/gradlew
Grep now prints warning messages when using `egrep` and `fgrep`
Replacing with the standard `grep -E` and `grep -F`
Signed-off-by: Nicolas signed-log FORMICHELLA <stigpro@outlook.fr>
> egrep/fgrep are deprecated and obsolete, replacing with `grep -E/-F`

- scripts/ci/mono-ci-job-template.yml
As a part of https://github.com/dotnet/arcade/issues/10123, we are moving all docker containers to the new tagging schema
> Update docker tags to the new schema

- mono/mini/mini-s390x.c
Port dotnet runtime fix for `OP_CHECK_THIS` operation.
> Fix OP_CHECK_THIS - matches PR#76916 for dotnet runtime

- mono/utils/memfuncs.c
The value was supposed to be 20MB but was incorrectly entered as 200MB.
> Fix default value to be 20MB

- mono/metadata/assembly.c
- mono/metadata/image.c
1. Set status on success
Manual backport of https://github.com/dotnet/runtime/pull/80949 to mono/mono
Emebedders that call `mono_assembly_load_from_full` may observe a non-NULL return value and an uninitialized 
MonoImageOpenStatus, which may lead to incorrect diagnostics in code like:
```
MonoImageOpenStatus status;
MonoAssembly *assembly = mono_assembly_load_from_full (image, name, status, refonly);
if (!assembly || status != MONO_IMAGE_OK) {
fprintf(stderr, "Failure due to: %s\n", mono_image_strerror (status));
abort();
}
```
Which will print `Failure due to: Internal error`
2.  Make mono_image_load_time_date_stamp a no-op on Android
Avoid an mmap that will fail since Android uses a custom loader and the assemblies aren't on disk
> [mono][loader] Set status on success; avoid mmap on Android

- mono/mini/mini-arm.c
When the return struct is large the store instruction offset is too large. When this happens, put the large offset in a register.
backport of https://github.com/dotnet/runtime/pull/77854
> Fix mono arm assert with large return structs

- mono/eglib/ghashtable.c
- mono/metadata/metadata.c
Backport of https://github.com/dotnet/runtime/pull/83273 to mono/mono `main`
The C standard does not specify whether `char` is signed or unsigned, it is implementation defined.
Apparently Android aarch64 makes a different choice than other platforms (at least macOS arm64 and Windows x64 give different results).
Mono uses `mono_metadata_str_hash` in the AOT compiler and AOT runtime to optimize class name lookup.  As a result, classes whose names include UTF-8 continuation bytes (with the high bit = 1) will hash differently in the AOT compiler and on the device.
Contributes to https://github.com/dotnet/runtime/issues/82187 
Contributes to https://github.com/dotnet/runtime/issues/78638
> [mono] Use `unsigned char` when computing UTF8 string hashes

- mono/mini/mini-exceptions.c
- mono/utils/valgrind.h
Fix a couple of errors that show up when compiling Mono for aarch64 using clang on Linux.
> fix aarch64+clang compilation errors

- mono/metadata/debug-mono-ppdb.c
- mono/metadata/debug-mono-ppdb.h
- mono/mini/debugger-agent.c
Changes:
- Support symbol server on mobile devices: port from https://github.com/dotnet/runtime/pull/82555
- Show loaded symbols on VS module window: port from https://github.com/dotnet/runtime/pull/82587
- Added compatibility with CMD_GET_ENC_CAPABILITIES message: even if C# Hot Reload is not supported in Xamarin Forms, the debug client can send this message if the version is at least 2.61, which it is since the latest changes. See code for reference: https://github.com/mono/debugger-libs/blob/main/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs#L799-L800. For that reason and for compatibility, we should support that message and return "Baseline", the same as the client code does with a lower version.
The main motivation of these ports is to support symbol server in Xamarin …
> [debugger] Ports from dotnet/runtime to maintain compatibility

- mono/mini/mini-generic-sharing.c
Was looking to debug some code and noticed this little typo.
Can't sign the CLA right now since the website https://cla.dotnetfoundation.org/ seems to be down.
Let me know what I should do, else I leave this here.
*Backs away slowly*
:sparkles::unicorn:
> Fixed compile errors in mini/mini-generic-sharing.c when DEBUG is defined

- mcs/class/System.Windows.Forms/System.Windows.Forms/GridEntry.cs
This PR allows the `IServiceProvider` implementation for property grid items to resolve `GetService` requests using the control `Site`, if specified. This is consistent with the original behavior on .NET Framework and is fundamental to enable advanced extensibility scenarios where custom editors require services from the application hosting the property grid.
Fixes #21660
> Improve compatibility of property grid custom editors

- mcs/class/corlib/System/TimeZoneInfo.cs
Contributes towards fixing https://github.com/xamarin/xamarin-android/issues/8175
Contributes towards fixing https://github.com/xamarin/xamarin-android/issues/8028
In Android 14 (API Level 34), the tzdata file needs to be read using the V2 header information as the V1 header information doesn't carry enough to fill out timezones properly. Moreover, time values in the V2 section are stored as `long`s rather than `int`s used in V1 section. This PR looks to enable the TimeZoneInfo class to read V2 header information and parse the associated data.
The V1 information will give counts of 
Number of Greenwich Mean Time transition time flags: 0
Number of Standard Time transition time flags: 0
Number of leap seconds: 0
Number of transition times: 0
Number of local time types: 1
Number of …
> [libs] Update TimeZoneInfo to read new version of tzdata

- mcs/class/corlib/System/TimeZoneInfo.cs
When https://github.com/mono/mono/pull/21682 was introduced, Version 2 header data was preferred over version 1 header data. As a result, a tzdata file like `/usr/share/zoneinfo/Etc/UTC` which contains the bytes
```
54, 5A, 69, 66, 32, 00, 00, 00, 00, 00, 00, 00,
00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01,
00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00,
00, 00, 00, 01, 00, 00, 00, 04, 00, 00, 00, 00,
00, 00, 55, 54, 43, 00, 00, 00, 54, 5A, 69, 66,
32, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00,
00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 01,
00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 01,
00, 00, 00, 04, F8, 00, 00, 00, 00, 00, 00, 00,
00, 00, 00, 00, 00, 00, 00, 55, 54, 43, 00, 00,
00, 0A, 55, 54, 43, 30, 0A
```
will point to transition time byte data `F8 00 00 00 00 00 00 00` ([more …
> [libs][TimeZoneInfo] Bound transition time conversion

- mcs/class/Mono.Security/Mono.Security/PKCS7.cs
This is an obvious and annoying typo. There's nothing more to say.
> Fix typo in OIDs corresponding to SHA256, SHA384, and SHA512

- mono/arch/loongarch64/loongarch64-codegen.h
- mono/mini/mini-loongarch64.c
- mono/mini/mini-loongarch64.h
Add a new archecture LoongArch64, this is the first patch about the `codegen.h` and `mini-loongarch64.h`.
This PR is part of #21381
> [LoongArch64] Part-1: Add `codegen.h` and `mini-loongarch64.h`.

- mono/mini/cpu-loongarch64.md
- mono/mini/genmdesc.py
- mono/mini/mini-ops.h
Add a new architecture LoongArch64
This is the seconde patch,the first patch see [#21389](https://github.com/mono/mono/pull/21389), this patch is related to instruction selection. Add the LoongArch64 special instruction in mini-ops. h, add architecture support in genmdesc. py, and add the instruction description file cpu-longarch64.md，other modules will be submitted gradually.
> [LoongArch64] Part-2:add instruction selection module for LoongArch64

- mono/mini/mini-loongarch64-gsharedvt.c
- mono/mini/mini-loongarch64-gsharedvt.h
- mono/mini/tramp-loongarch64-gsharedvt.c
- mono/mini/tramp-loongarch64.c
Add a new architecture LoongArch64
This is the third patch, the patch is related to method trampolines. Add tramp-loongarch64.c、tramp-loongarch64-gsharedvt.c、mini-loongarch64-gsharedvt.h、mini-loongarch64-gsharedvt.c.
This PR is part of https://github.com/mono/mono/issues/21381
>  [LoongArch64] Part-3:add method trampolines module for LoongArch64.
