mono/mono

- mcs/errors/cs1013-2.cs
- mcs/errors/cs1061-18.cs
- mcs/errors/cs1644-61.cs
- mcs/mcs/cs-tokenizer.cs
- mcs/tests/test-950.cs
- mcs/tests/ver-il-net_4_x.xml
> [mcs] Implements C# 7 digits separators

- sdks/builds/llvm.mk
Backport of #8107.
/cc @luhenry
> [2017-12] [sdks] Fix arguments passed to llvm on Linux

- sdks/builds/llvm.mk
Backport of #8107.
/cc @luhenry
> [2018-02] [sdks] Fix arguments passed to llvm on Linux

- mono/metadata/w32file-unix.c
> [2018-04] [w32file] Fix memory leak

- mcs/errors/cs0273-2.cs
- mcs/errors/cs1527-2.cs
- mcs/errors/cs1527-3.cs
- mcs/errors/cs1527.cs
- mcs/errors/cs1644-62.cs
- mcs/mcs/cs-parser.jay
- mcs/mcs/modifiers.cs
- mcs/tests/test-960.cs
- mcs/tests/ver-il-net_4_x.xml
> [mcs] Adds private protected modifier to the parser only

- mcs/errors/cs0273-2.cs
- mcs/errors/cs1527-2.cs
- mcs/errors/cs1527-3.cs
- mcs/errors/cs1527.cs
- mcs/errors/cs1644-62.cs
- mcs/mcs/cs-parser.jay
- mcs/mcs/modifiers.cs
- mcs/tests/test-960.cs
- mcs/tests/ver-il-net_4_x.xml
> [2018-04] [mcs] Adds private protected modifier to the parser only

- mcs/errors/cs0273-2.cs
- mcs/errors/cs1527-2.cs
- mcs/errors/cs1527-3.cs
- mcs/errors/cs1527.cs
- mcs/errors/cs1644-62.cs
- mcs/mcs/cs-parser.jay
- mcs/mcs/modifiers.cs
- mcs/tests/test-960.cs
- mcs/tests/ver-il-net_4_x.xml
> [2018-02] [mcs] Adds private protected modifier to the parser only

- mono/mini/interp/transform.c
- mono/tests/Makefile.am
- mono/tests/delegate-prop.cs
Regression introduced in 77b4cd11d1d7c7b79c426ddc5a343b373a3b2cc3. We
need to distinguish this case.
Fixes #7944
> [interp] fix regression for virtual delegates

- mono/mini/aot-compiler.c
- mono/mini/mini.c
> [mono] Update documentation pages links

- mcs/errors/cs1013-1.cs
- mcs/errors/cs1021-4.cs
- mcs/mcs/cs-tokenizer.cs
- mcs/tests/test-binaryliteral.cs
- mcs/tools/mkbundle/mkbundle.cs
> [2018-02] Implement C#7 binary literals

- mono/metadata/w32file-unix.c
> [2018-02] [w32file] Fix memory leak

- configure.ac
- mcs/build/tests.make
> [build] Exclude platform specific xunit tests

- mcs/class/corlib/System.Security.Cryptography/CryptoConfig.Mobile.cs
- mcs/class/corlib/System.Security.Cryptography/CryptoConfig.common.cs
- mcs/class/corlib/System.Security.Cryptography/CryptoConfig.cs
- mcs/class/corlib/Test/System.Security.Cryptography/CryptoConfigTest.cs
> [corlib] Implements CryptoConfig::AddAlgorithm on all profiles

- mcs/class/corlib/System.Security.Cryptography/CryptoConfig.Mobile.cs
- mcs/class/corlib/System.Security.Cryptography/CryptoConfig.common.cs
- mcs/class/corlib/System.Security.Cryptography/CryptoConfig.cs
- mcs/class/corlib/Test/System.Security.Cryptography/CryptoConfigTest.cs
> [2018-04] [corlib] Implements CryptoConfig::AddAlgorithm on all profiles

- mcs/class/corlib/System.Security.Cryptography/CryptoConfig.Mobile.cs
- mcs/class/corlib/System.Security.Cryptography/CryptoConfig.common.cs
- mcs/class/corlib/System.Security.Cryptography/CryptoConfig.cs
- mcs/class/corlib/Test/System.Security.Cryptography/CryptoConfigTest.cs
> [2018-02] [corlib] Implements CryptoConfig::AddAlgorithm on all profiles

- mcs/class/corlib/LinkerDescriptor/mscorlib.xml
Removes some duplication of preservation's
Consolidations some preservation's under a single <type> element
> Clean up mscorlib link xml

- mono/mini/generics.cs
- mono/mini/interp/transform.c
Fixes https://github.com/mono/mono/issues/8143
> [interp] support r4 (single) in stelem instruction

- mcs/errors/cs1763-2.cs
- mcs/errors/cs1763.cs
- mcs/mcs/expression.cs
- mcs/mcs/parameter.cs
- mcs/tests/test-default-01.cs
- mcs/tests/ver-il-net_4_x.xml
> [mcs] Fixes parameter check for interface types used with default parameters

- mcs/errors/cs1763-2.cs
- mcs/errors/cs1763.cs
- mcs/mcs/expression.cs
- mcs/mcs/parameter.cs
- mcs/tests/test-default-01.cs
- mcs/tests/ver-il-net_4_x.xml
> [2018-04] [mcs] Fixes parameter check for interface types used with default parameters

- mcs/errors/cs1763-2.cs
- mcs/errors/cs1763.cs
- mcs/mcs/expression.cs
- mcs/mcs/parameter.cs
- mcs/tests/test-default-01.cs
- mcs/tests/ver-il-net_4_x.xml
> [2018-02] [mcs] Fixes parameter check for interface types used with default parameters

- mono/profiler/log.c
Fixes https://github.com/mono/mono/issues/6173
> [profiler] Fix heapshot frequency calculation

- mono/mini/generics.cs
- mono/mini/interp/transform.c
Backport of #8145.
/cc @alexischr
> [2018-04] [interp] support r4 (single) in stelem instruction

- mono/mini/debugger-agent.c
- mono/mini/driver.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
Fixes https://github.com/mono/mono/issues/8177
> [wasm] Fix the disable sdb check.

- mcs/class/System/Test/System.Net/HttpWebRequestTest.cs
- mcs/class/System/Test/System.Net/HttpWebResponseTest.cs
- mcs/class/System/Test/System.Net/WebClientTest.cs
Backport of #8202.
/cc @lewurm
> [2018-04] [system.net] disable some tests to unblock XI integration

- sdks/wasm/README.md
* Fixed heading levels (there should be only one H1 per page).
* Fixed links.
* Removed unnecessary indentation from code.
> Improved wasm sdk README formatting

- mcs/class/System/Test/System.Net/HttpWebRequestTest.cs
- mcs/class/System/Test/System.Net/HttpWebResponseTest.cs
- mcs/class/System/Test/System.Net/WebClientTest.cs
Backport of #8202.
/cc @lewurm
> [2018-02] [system.net] disable some tests to unblock XI integration

- mcs/class/corlib/Test/System.Threading/ThreadTest.cs
- mono/mini/interp/interp.c
- mono/mini/interp/transform.c
- mono/mini/mini-exceptions.c
Fixes https://github.com/mono/mono/issues/7402
> [interp] Exit from finally abort protected block when EH

- mono/metadata/w32handle.c
> [2018-02] [w32handle] Lower minimum memory usage (2nd attempt)

- sdks/builds/android.mk
- sdks/builds/unzip-android-archive.sh
Backport of #8242.
/cc @luhenry
> [2018-02] [sdks] Fix typo + Fix verbosity of unzip-android-archive.sh

- sdks/builds/android.mk
- sdks/builds/unzip-android-archive.sh
Backport of #8242.
/cc @luhenry
> [2018-04] [sdks] Fix typo + Fix verbosity of unzip-android-archive.sh

- sdks/builds/android.mk
- sdks/builds/unzip-android-archive.sh
Backport of #8242.
/cc @luhenry
> [2017-12] [sdks] Fix typo + Fix verbosity of unzip-android-archive.sh

- mcs/class/corlib/Test/System.IO/FileTest.cs
- mono/metadata/w32file-unix.c
> [2018-02] Fix timestamp for file copy

- mcs/class/corlib/Test/System.IO/FileTest.cs
- mono/metadata/w32file-unix.c
> [2018-04] Fix timestamp for file copy

- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/mini/mini-runtime.c
Backport of #7423.
/cc @lewurm
> [2018-02] Harden JIT job control against cctors deadlocking.

- mono/metadata/object.h
- mono/metadata/threads.c
Backport of #7759.
/cc @luhenry
> [2018-04] [runtime] Add public API to set the pending exception.

- mcs/errors/cs1013-2.cs
- mcs/errors/cs1061-18.cs
- mcs/errors/cs1644-61.cs
- mcs/mcs/cs-tokenizer.cs
- mcs/tests/test-950.cs
- mcs/tests/ver-il-net_4_x.xml
> [2018-02] [mcs] Implements C# 7 digits separators

- mono/metadata/object.h
- mono/metadata/threads.c
Backport of #7759.
/cc @luhenry
> [2018-02] [runtime] Add public API to set the pending exception.

- mcs/class/Mono.Security/Mono.Security/StrongName.cs
Fixes https://github.com/mono/mono/issues/8218
> Teach sn.exe about PE32+, and while there ROM images and MS-DOS-less images.

- mono/metadata/w32file-unix.c
Backport of #8293.
/cc @lewurm
> [2018-04] [w32file-unix] fix mistake in 8430155946c31f0f3f5f04017eebd79ac15e566d

- mono/metadata/w32file-unix.c
Backport of #8293.
/cc @lewurm
> [2018-02] [w32file-unix] fix mistake in 8430155946c31f0f3f5f04017eebd79ac15e566d

- mcs/class/corlib/Test/System.IO/FileTest.cs
https://github.com/mono/mono/pull/8293#pullrequestreview-113037270
let's see if that causes any issues
> [corlib] add sanity check to filetest for last access modification time

- mcs/class/System/Test/System.Threading/WaitHandleTests.cs
This follows https://github.com/mono/mono/commit/64ec2dd3eb1309b84819b34c4279d946acacd082.
https://github.com/mono/mono/issues/8349
> [corlib] Disable failing test on XA

- mcs/class/System/Test/System.Threading/WaitHandleTests.cs
Backport of #8351.
/cc @luhenry
> [2018-02] [corlib] Disable failing test on XA

- mcs/class/System/Test/System.Threading/WaitHandleTests.cs
Backport of #8351.
/cc @luhenry
> [2018-04] [corlib] Disable failing test on XA

- mono/mini/interp/interp.c
Backport of #8334.
/cc @lewurm
> [2018-02] Remove unused signal.h include in interp.c

- mono/mini/interp/interp.c
Backport of #8334.
/cc @lewurm
> [2018-04] Remove unused signal.h include in interp.c

- packaging/MacSDK/fsharp.py
- packaging/MacSDK/patches/fsharp-path-overloads.patch
Upstream patch is at https://github.com/fsharp/fsharp/pull/844
> [packaging] Apply F# patch that fixes #8310

- mono/metadata/icall.c
- mono/metadata/object-internals.h
- mono/mini/mini-posix.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
Fixes https://github.com/mono/mono/issues/8236
> [runtime] Add a signal handler for sigterm

- scripts/ci/run-jenkins.sh
https://github.com/mono/mono/issues/7333
> [ci] Add `jit_llvm` configuration

- mono/metadata/icall.c
- mono/metadata/object-internals.h
- mono/mini/mini-posix.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
> [2018-04] [runtime] Add a signal handler for sigterm

- mono/metadata/icall.c
- mono/metadata/object-internals.h
- mono/mini/mini-posix.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
> [2018-02] [runtime] Add a signal handler for sigterm

- mcs/class/System/Test/System.ComponentModel/TypeDescriptorTests.cs
See https://github.com/mono/mono/issues/8407
> [System] Temporarily disable failing TypeDescriptorTests on FullAOT

- packaging/MacSDK/fsharp.py
- packaging/MacSDK/patches/fsharp-path-overloads.patch
> [2018-04] [packaging] Apply F# patch that fixes #8310

- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
- mcs/class/corlib/net_4_x_corlib.dll.sources
> [corlib] Clean up .sources files

- mono/mini/mini-arm.c
Backport of #8413.
/cc @vargaz
> [2018-04] [arm] Fix a regression introduced by:

- mono/mini/mini-arm.c
Backport of #8413.
/cc @vargaz
> [2018-02] [arm] Fix a regression introduced by:

- acceptance-tests/SUBMODULES.json
Fixes https://github.com/mono/mono/issues/8422
> [acceptance-tests] Bump coreclr to fix #8422

- mono/mini/mini-arm.c
Backport of #8413.
/cc @vargaz
> [2017-12] [arm] Fix a regression introduced by:

- configure.ac
- mono/utils/mono-time.c
https://bugzilla.xamarin.com/show_bug.cgi?id=58413
> Backport new mono_msec_boottime() to 2017-12

- mono/metadata/sgen-mono-ilgen.c
- mono/metadata/sgen-mono.c
ilgen changes messed up the defines.
> [sgen] unbreak build when SGEN_HEAVY_BINARY_PROTOCOL is set

- packaging/MacSDK/msbuild.py
- scripts/ci/run-test-mac-sdk.sh
.. which is now on the netcore2.x based build. Update build and test
scripts accordingly.
> [msbuild] Bump to latest xplat-master

- mono/tests/Makefile.am
> Fix typo causing `make destdir` to fail

- sdks/builds/runtime.mk
- sdks/builds/wrap-configure.sh
Backport of #8306.
/cc @luhenry
> [2018-04] [sdks] Wrap configure to provide better output.

- packaging/MacSDK/msbuild.py
- scripts/ci/run-test-mac-sdk.sh
> [msbuild] Zip test results and log files for surfacing in jenkins

- tools/nuget-hash-extractor/Makefile
- tools/nuget-hash-extractor/nuget-hash-extractor.cs
> nuget-hash-extract: Improvements to make it more deterministic

- man/mono.1
> [Man page] Deambiguate TLS

- mono/metadata/marshal-ilgen.c
Fixes corefx generic list tests with interp.
> [runtime] Fix runtime invoke with generic enums

- man/mono.1
- mono/mini/driver.c
Implements the feature request here:
https://github.com/mono/mono/issues/8518
> [mono] Add support for response files, using --response=FILE

- mcs/tools/security/certmgr.cs
> [tools]: Use the official 'SslStream' APIs in certmgr.

- mcs/class/Mono.Cairo/Mono.Cairo.dll.sources
- mcs/class/Mono.Cairo/Mono.Cairo/Device.cs
- mcs/class/Mono.Cairo/Mono.Cairo/EGLDevice.cs
- mcs/class/Mono.Cairo/Mono.Cairo/GLSurface.cs
- mcs/class/Mono.Cairo/Mono.Cairo/GLXDevice.cs
- mcs/class/Mono.Cairo/Mono.Cairo/NativeMethods.cs
- mcs/class/Mono.Cairo/Mono.Cairo/Surface.cs
- mcs/class/Mono.Cairo/Mono.Cairo/WGLDevice.cs
Add Device class.
Add GLSurface class, created for texture.
Add Surface types
> [Mono.Cairo] Add OpenGL texture Surface support 

- mcs/build/rules.make
- runtime/Makefile.am
- scripts/ci/run-test-default.sh
Similar to how we do it for nunit.
> [bcl] Add xunit to STD_TARGETS and precompile tests

- mono/metadata/appdomain-icalls.h
- mono/metadata/appdomain.c
- mono/metadata/icall-def.h
> [Coop] Convert System.CLRConfig

- mono/metadata/icall-def.h
- mono/metadata/icall.c
> [Coop] Convert Mono.Runtime

- mono/metadata/icall-def.h
- mono/metadata/icall.c
> [Coop] Convert Mono.RuntimeClassHandle

- mono/metadata/icall-def.h
- mono/metadata/icall.c
> [Coop] Convert Mono.RuntimeMarshal

- mono/metadata/icall-def.h
- mono/metadata/icall.c
- mono/mini/debugger-agent-stubs.c
- mono/mini/debugger-agent.c
- mono/mini/debugger-agent.h
Could use fixed, but this seems straightforward enough.
> [Coop] Convert System.Diagnostics.Debugger.

- .vscode/c_cpp_properties.json
The C/C++ extension was updated yesterday and bumped the version in that file.
@monojenkins skip
> [vscode] Update c_cpp_properties.json

- configure.ac
- mcs/class/System/System.Diagnostics/DefaultTraceListener.cs
- mono/metadata/icall-def.h
- mono/metadata/icall-internals.h
- mono/metadata/icall-windows.c
- mono/metadata/icall.c
Pretty trival.
Bumping version by 2 due to another outstanding PR.
> [Coop] Convert System.Diagnostics.DefaultTraceListener.

- packaging/MacSDK/msbuild.py
- scripts/ci/run-test-mac-sdk.sh
> Bump msbuild to track mono-2018-02

- packaging/MacSDK/msbuild.py
Backport of #8682.
/cc @radical
> [2018-04] Bump msbuild to track mono-2018-02

- mono/mini/interp/transform.c
> [interp] Add null checks for ldind

- mono/mini/method-to-ir.c
> Some method-to-ir cleanup.

- packaging/MacSDK/mono-basic.py
> [packaging] Bump basic to fix build with master and add deprecation message

- mcs/class/corlib/Test/System.Threading/ThreadPrincipalTests.cs
Fixes https://github.com/mono/mono/issues/8723
/cc @kg @EgorBo
> [corlib tests] improve ThreadPrincipalTests regarding SynchronizationContext

- mcs/class/corlib/Test/System.Threading/ThreadPrincipalTests.cs
> [2018-04] [corlib tests] improve ThreadPrincipalTests regarding SynchronizationContext

- mono/mini/method-to-ir.c
> No _Static_assert in old compiler.

- mono/mini/Makefile.am.in
- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
- mono/mini/aot-runtime.h
- mono/mini/aot-tests.cs
Fixes https://github.com/mono/mono/issues/8701.
> [aot] Fix encoding/decoding of types with custom modifiers.

- mono/mini/Makefile.am.in
- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
- mono/mini/aot-runtime.h
- mono/mini/aot-tests.cs
Backport of #8772.
/cc @vargaz
> [2018-02] [aot] Fix encoding/decoding of types with custom modifiers. (#8729)

- mcs/class/corlib/orbis_corlib_test.dll.exclude.sources
- mcs/class/corlib/orbis_corlib_test.dll.sources
> [2018-04] Added corlib .sources files for the ORBIS profile

- sdks/wasm/Makefile
> [wasm] Unify csc settings with the rest of Mono tree

- mcs/class/corlib/System.IO/LogcatTextWriter.cs
- mono/eglib/goutput.c
> [2018-04] [android] Fix truncating of messages longer than 4096 characters

- mcs/class/corlib/System.IO/LogcatTextWriter.cs
- mono/eglib/goutput.c
> [2018-02] [android] Fix truncating of messages longer than 4096 characters

- mono/mini/debugger-agent.c
Backport of #6456.
/cc @lewurm
> [2018-04] [debugger] Add locking around tls->eframes usage/freeing

- mcs/mcs/expression.cs
> [mcs] Don't report internal error when Span type is not available

- packaging/MacSDK/nuget.py
Do not merge as it is technically still a release candidate
> [MacSDK] Update Nuget to 4.7.0

- packaging/MacSDK/nuget.py
Backport of #7412.
/cc @alexischr
> [2018-04] [MacSDK] Update Nuget to 4.7.0

- packaging/MacSDK/nuget.py
Backport of #7412.
/cc @alexischr
> [2018-02] [MacSDK] Update Nuget to 4.7.0

- mcs/errors/cs1525-43.cs
- mcs/errors/cs1611.cs
- mcs/mcs/cs-parser.jay
- mcs/mcs/cs-tokenizer.cs
- mcs/mcs/parameter.cs
- mcs/tests/test-961.cs
- mcs/tests/ver-il-net_4_x.xml
> [mcs] Adds parser support for C# 7.2 readonly references

- mcs/class/System/System.Net.Sockets/Socket.cs
> [2018-02] [System] BeginConnect fails on ipv6 if Socket is ipv4

- mono/btls/btls-ssl-ctx.c
Rather than reaching into the library internals and potentially violating its invariants, assemble a cipher string and call the supported public API. (There's no need to touch the version-specific cipher lists because mono/btls never configures them.) The existing code also had a bug; it incorrectly assumed `OPENSSL_malloc` returned a zero-initialized buffer for `in_group_flags`. (Though Mono doesn't set `SSL_OP_CIPHER_SERVER_PREFERENCE`, so I suspect this was a no-op.)
Additionally, this should hopefully ease updating to a less outdated version of BoringSSL in the future.
Note I've changed the return value of this function from returning the number of ciphers to merely returning 0/1 for whether the operation succeeded. The only caller of this function, `MonoBtlsSslCtx.SetCiphers`, only …
> [btls] rewrite mono_btls_ssl_ctx_set_ciphers

- mcs/tools/linker/monolinker.exe.sources
> Bump linker to resolve XA issues

- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/mini/mini-exceptions.c
- mono/mini/mini-posix.c
- mono/utils/mono-merp.c
- mono/utils/mono-merp.h
An example of the emitted files can be found here
https://gist.github.com/alexanderkyte/47307c95f77ef6e6a2d5efc73cb76dec
It's verbose.
> [runtime] Change merp to emit files for MERP upload mode

- mcs/tools/linker/monolinker.csproj
- mcs/tools/linker/monolinker.exe.sources
> [master] Bump linker to resolve XA issues

- mcs/class/referencesource/mscorlib/system/io/stream.cs
> [corlib] Optimizes Stream:CopyTo

- mono/mini/Makefile.am.in
- mono/mini/debugger-agent.c
- mono/mini/debugger-engine.c
- mono/mini/debugger-engine.h
- msvc/libmini-common.targets
- msvc/libmini-common.targets.filters
- sdks/builds/wasm.mk
This PR adds the new files, moves the enums / structs and a small bit of code to validate the change.
> [wasm] [sdb] Initial PR towards making some of sdb's code shareable.

- mono/profiler/log.c
- mono/utils/mono-threads.c
- mono/utils/mono-threads.h
Fixes https://github.com/mono/mono/issues/7683
> Sanitize TLS handling in the profiler.

- configure.ac
> Bump Roslyn to 2.8.2

- mono/profiler/log.c
- mono/utils/mono-threads.c
- mono/utils/mono-threads.h
> [2018-04] Sanitize TLS handling in the profiler.

- configure.ac
- mcs/class/System.Security/System.Security.Cryptography.Xml/SignedXml.cs
> Bump corefx

- mcs/class/Facades/subdirs.make
> [Facades] Removes System.Memory

- sdks/versions.mk
> [sdks] Fixes llvm branch name

- .github/ISSUE_TEMPLATE.md
> Update issues template

- mcs/packages/Makefile
Fixes https://github.com/mono/mono/issues/8897 .
> [roslyn][msbuild] Copy the new Microsoft.Managed.Core.targets file in roslyn.

- mcs/tools/Makefile
> [2018-04] [build] Includes tools used by XI/XA build CI in build profile

- acceptance-tests/SUBMODULES.json
> [acceptance-tests] Bump roslyn tests to match bundled version

- mono/mini/aot-runtime.c
> [runtime] Fix the --enable-minimal=aot build.

- mono/mini/interp/interp.c
- mono/mini/mini-generic-sharing.c
- mono/tests/Makefile.am
Backport of #6868.
/cc @lewurm
> [2018-02] [interp] Fix native to interp transition

- mcs/class/System.Windows.Forms/System.Windows.Forms/PropertyGrid.cs
> [2018-04] [System.Windows.Forms] fix PropertyGrid

- mcs/class/System/System.IO/CoreFXFileSystemWatcherProxy.cs
- mcs/class/System/System.IO/FileSystemWatcher.cs
Backport of https://github.com/mono/mono/pull/8719.
> [2018-04] [System.IO] Finish initializing all FileSystemWatchers, not just the first one

- mcs/tools/mono-api-html/ApiChange.cs
- mcs/tools/mono-api-html/ApiDiff.cs
- mcs/tools/mono-api-html/ClassComparer.cs
- mcs/tools/mono-api-html/Comparer.cs
- mcs/tools/mono-api-html/ConstructorComparer.cs
- mcs/tools/mono-api-html/FieldComparer.cs
- mcs/tools/mono-api-html/Formatter.cs
- mcs/tools/mono-api-html/Helpers.cs
- mcs/tools/mono-api-html/HtmlFormatter.cs
- mcs/tools/mono-api-html/MarkdownFormatter.cs
- mcs/tools/mono-api-html/MemberComparer.cs
- mcs/tools/mono-api-html/NamespaceComparer.cs
- mcs/tools/mono-api-html/mono-api-html.csproj
- mcs/tools/mono-api-html/mono-api-html.exe.sources
Backport of #8057.
/cc @alexischr
> [2018-04] [mono-api-html] Update tool to optionally output markdown

- mcs/tools/mono-api-html/MarkdownFormatter.cs
Backport of #8285.
/cc @alexischr
> [2018-04] [mono-api-html] Fix markdown diff which was reversed

- mcs/class/System.ServiceModel/System.ServiceModel.Dispatcher/ChannelDispatcher.cs
This partially reverts commit 1628f04de5c1026b23ec350486b1b3c45708b771 .
Runtime tested and fixes #8970 and allows long-term
operation of RapidSCADA.
> [wcf] Fix memory leak processing requests

- mcs/class/Makefile
> [build] Adds System.IO.Compression csc dependency to bootstrap package

- mcs/class/System.ServiceProcess/System.ServiceProcess_test.dll.sources
Mitigates https://github.com/mono/mono/issues/9002.
> Remove ServiceControllerTest.cs.

- packaging/MacSDK/msbuild.py
> Bump msbuild to track mono-2018-04

- mono/profiler/Makefile.am
Not clear if this is correct, but let build progress.
> [bitcode] Fix building -with-runtime-preset=bitcode.

- configure.ac
- mono/mini/llvm-jit.cpp
Backport of #8092.
/cc @vargaz
> [2018-04] [arm64] Fix llvm jit support.

- mono/mini/aot-compiler.c
- mono/mini/basic.cs
- mono/mini/exceptions.cs
- mono/mini/interp/interp.c
- mono/mini/mini-generic-sharing.c
- mono/mini/mini-trampolines.c
> Mixed testing

- mono/metadata/icall.c
- mono/metadata/monitor.c
- mono/metadata/monitor.h
These  functions are the same except for if vs. while, so can be one function with a boolean parameter. (and unused func in debugging)
>  Refactor ves_icall_System_Threading_Monitor_Monitor_pulse and pulse_all.

- mono/mini/cfold.c
- mono/mini/decompose.c
- mono/mini/intrinsics.c
- mono/mini/ir-emit.h
- mono/mini/local-propagation.c
- mono/mini/method-to-ir.c
- mono/mini/mini-ops.h
- mono/mini/mini.h
> [jit] Add Span<T> intrinsics.

- mono/metadata/assembly.c
- mono/metadata/image-internals.h
- mono/metadata/image.c
> [2018-06] Revert "[loader] LoadFrom of problematic images should reprobe"

- mono/metadata/profiler.c
> [2018-04] [profiler] Don't raise events until the profiler transitions to the ready state.

- mcs/class/System.Runtime.Serialization/System.Runtime.Serialization.csproj
- mono/metadata/profiler.c
> [2018-06] [profiler] Don't raise events until the profiler transitions to the ready state.

- mono/metadata/assembly.c
- mono/metadata/image-internals.h
- mono/metadata/image.c
This reverts commit efe1fdeb9dedeb2f3aba2efe63a977f3521d04b0.
Fix #9044 for `2018-04`
> [2018-04] Revert "[loader] LoadFrom of problematic images should reprobe"

- sdks/builds/android.mk
- sdks/builds/unzip-android-archive.sh
Backport of #9125.
/cc @luhenry
> [2018-02] [SDKS,Android] Install cmake when provisioning Android SDK

- sdks/builds/android.mk
- sdks/builds/unzip-android-archive.sh
Backport of #9125.
/cc @luhenry
> [2018-04] [SDKS,Android] Install cmake when provisioning Android SDK

- sdks/builds/android.mk
- sdks/builds/unzip-android-archive.sh
Backport of #9125.
/cc @luhenry
> [2018-06] [SDKS,Android] Install cmake when provisioning Android SDK

- sdks/builds/determine-linux-flavor.sh
- sdks/builds/mxe.mk
Backport of #9150.
/cc @luhenry
> [2018-02] [Linux,XA build] Fix building of Windows cross-compilers on Ubuntu Linux

- sdks/builds/determine-linux-flavor.sh
- sdks/builds/mxe.mk
Backport of #9150.
/cc @luhenry
> [2018-04] [Linux,XA build] Fix building of Windows cross-compilers on Ubuntu Linux

- sdks/builds/determine-linux-flavor.sh
- sdks/builds/mxe.mk
Backport of #9150.
/cc @luhenry
> [2018-06] [Linux,XA build] Fix building of Windows cross-compilers on Ubuntu Linux

- mono/metadata/appdomain.c
- mono/metadata/custom-attrs.c
- mono/metadata/icall.c
- mono/metadata/object-internals.h
- mono/metadata/object.c
- mono/metadata/w32file.c
https://github.com/mono/mono/issues/9153
> Fix some handle type violations.

- mcs/class/System/System.Net.Sockets/SocketAsyncEventArgs.cs
> [2018-06] [System]: Fix another `SocketAsyncEventArgs` issue for #8871.

- mono/mini/mini-runtime.c
- mono/utils/mono-internal-hash.c
- mono/utils/mono-internal-hash.h
> [code hashtable] change remove function so that it does not fail on removing a non-existing element

- mcs/mcs/expression.cs
- mcs/tests/test-decl-expr-05.cs
- mcs/tests/ver-il-net_4_x.xml
> [mcs] Extend emit preparation to binary expressions

- mono/metadata/object.c
ldstr_section can be taken during jit compilation.
Fixes random hangs in corlib suite.
> [coop] Use coop mutex

- mcs/class/Mono.Security/Mono.Security.X509/PKCS12.cs
- mcs/class/Mono.Security/Mono.Security.X509/X509Certificate.cs
> Detect the private key type from the supplied OID instead of guessing from the content.

- README.md
attempt at "the build is broken" development. it's marked (cs) like the others.
> Add AIX CI badge

- packaging/MacSDK/msbuild.py
> Bump msbuild to track xplat-master (for 2018-06)

- sdks/ios/harness/harness.cs
> [sdks] Delete ios simulators created by old versions of xcode if needed.

- mcs/class/System/System.Net/HttpWebRequest.cs
- mcs/class/System/System.Net/ServicePointScheduler.cs
- mcs/class/System/System.Net/WebResponseStream.cs
AKA The NuGet Lover's Pull Request.
> [System]: Fix bug in `WebResponseStream.GetResponse()` that will make some people happy.

- mcs/class/System/System.Net/HttpWebRequest.cs
- mcs/class/System/System.Net/ServicePointScheduler.cs
- mcs/class/System/System.Net/WebResponseStream.cs
Backport of #9228.
/cc @baulig
> [2018-06] [System]: Fix bug in `WebResponseStream.GetResponse()` that will make some people happy.

- mono/metadata/threads-types.h
- mono/mini/mini-exceptions.c
- mono/utils/mono-merp.c
- mono/utils/mono-state.c
> [runtime] Package merp params in 3 ways needed

- mono/metadata/w32socket.c
Thread A calls `Accept()`. Thread B wants to abort Thread A:
- Thread A installs the interrupt callback `abort_syscall`
- Thread B begins an async abort of Thread A, and ends up in `async_abort_internal`
- It will call `mono_thread_info_safe_suspend_and_run` and after that succeeds, it will get back the interrupt token that Thread A installed, and then Thread B will call `abort_syscall` on Thread A.
- but before it does that, Thread A first ends up in `suspend_sync` which will end up trying to suspend the thread and since `interrupt_kernel` is `TRUE`, it will even break syscalls.
- So by the time Thread B returns to `async_abort_internal` and calls the callback,  Thread A has already started being aborted, so we would just abort it for a second time for no reason.
> [w32socket] Remove useless interrupt callback

- mono/metadata/threads-types.h
- mono/mini/mini-exceptions.c
- mono/utils/mono-merp.c
- mono/utils/mono-state.c
> [2018-02] [runtime] Package merp params in 3 ways needed

- mono/metadata/threads-types.h
- mono/mini/mini-exceptions.c
- mono/utils/mono-merp.c
- mono/utils/mono-state.c
> [2018-04] [runtime] Package merp params in 3 ways needed

- mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs
- mcs/class/System/System.Net/HttpWebRequest.cs
- mcs/class/System/System.Net/WebResponseStream.cs
> [2018-06] [System]: `HttpWebRequest` now throws `WebExceptionStatus.RequestCanceled` on abort.  #9031.

- mono/metadata/custom-attrs.c
i.e. single point of exit/cleanup.
> Cleanup resource management and error paths ahead of coop conversion.

- mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs
> [2018-06] [System] Fix exception when process exit code is -1 on Windows

- mono/metadata/threads-types.h
- mono/mini/mini-exceptions.c
- mono/utils/mono-merp.c
- mono/utils/mono-state.c
Backport of #9062.
/cc @luhenry
> [2018-06] [runtime] Package merp params in 3 ways needed

- mono/metadata/threads.c
> [2018-06] [runtime] Make mono-state dumper abandon stuck threads

- mcs/class/corlib/LinkerDescriptor/mscorlib.xml
- mcs/class/corlib/System.Runtime.CompilerServices/PreserveDependencyAttribute.cs
- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
- mcs/tools/linker/Makefile
- mcs/tools/linker/Tests/mscorlib/test-string-01.cs
- mcs/tools/linker/Tests/mscorlib/test-string-02.cs
- mcs/tools/linker/Tests/mscorlib/test-string-03.cs
> [mscorlib] Conditional string ctors dependency

- mcs/errors/cs0280.cs
- mcs/errors/cs1611-2.cs
- mcs/errors/cs1644-63.cs
- mcs/errors/cs8385-2.cs
- mcs/errors/cs8385.cs
- mcs/mcs/report.cs
- mcs/mcs/settings.cs
- mcs/mcs/statement.cs
- mcs/tests/test-fixed-01.cs
- mcs/tests/ver-il-net_4_x.xml
> [mcs] Implements C# 7.3 extensible fixed statement

- mono/mini/debugger-agent.c
- mono/mini/debugger-engine.c
- mono/mini/mini-wasm-debugger.c
- sdks/builds/bcl.mk
- sdks/wasm/Makefile
- sdks/wasm/README.md
- sdks/wasm/debug.html
- sdks/wasm/packager.cs
- sdks/wasm/runtime.g.js
- sdks/wasm/sample.cs
- sdks/wasm/sample.html
The major change is adding a primitive packaging tool that handles copying BCL files & runtime.
> [wasm] Unbreak the wasm debugging and massively simplify writing wasm apps using our SDK.

- mono/utils/mono-merp.c
Backport of #9274.
/cc @luhenry
> [2018-02] Make requested MERP file format changes

- mono/utils/mono-merp.c
Backport of #9274.
/cc @luhenry
> [2018-04] Make requested MERP file format changes

- mono/utils/mono-merp.c
Backport of #9274.
/cc @luhenry
> [2018-06] Make requested MERP file format changes

- mcs/build/tests.make
- mcs/class/test-helpers/RemoteExecutorTestBase.Mobile.cs
The proper implementation will be written later
/cc @grendello
> [build] Skips RemoteExecutor bases tests on monodroid

- mcs/build/tests.make
- mcs/class/test-helpers/RemoteExecutorTestBase.Mobile.cs
The proper implementation will be written later
> [build] Skips RemoteExecuted bases tests on monodroid

- mono/mini/mini.c
Backport of #9321.
/cc @lewurm
> [2018-02] [mini] add workaround for AMD Ryzen Threadripper issue

- mono/mini/aot-runtime.c
Backport of #8952.
/cc @lewurm
> [2018-04] [runtime] Fix the --enable-minimal=aot build.

- mono/metadata/marshal.c
Fixes https://github.com/mono/mono/issues/9407
> [marshal] Use a MonoCoopMutex for marshal_mutex

- mono/metadata/w32file-unix.c
> [2018-06] Add another Darwin file system

- mono/metadata/w32file-unix.c
> [2018-04] Add another Darwin file system

- mono/metadata/image.c
- mono/metadata/marshal.c
- mono/metadata/metadata-internals.h
Backport of #9385.
/cc @lewurm
> [2018-06] [mini] respect additional flags when caching runtime invoke wrappers

- mono/mini/Makefile.am.in
- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
- mono/mini/aot-runtime.h
- mono/mini/interp/transform.c
- mono/mini/mini-llvm.c
- mono/mini/mini-trampolines.c
> [interp] fullaotmixedcheck fixes

- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
- mono/mini/aot-runtime.h
- mono/mini/interp/transform.c
- mono/mini/mini-llvm.c
- mono/mini/mini-runtime.c
backport of https://github.com/mono/mono/pull/9295
> [2018-06] [mini] make interp work with AOT image generated with aot=interp

- mono/mini/debugger-agent.c
> [2018-02] [debugger] Add locking around tls-\u003eframes usage/freeing

- mono/mini/interp/transform.c
- mono/mini/objects.cs
Backport of #9348.
/cc @lewurm
> [2018-06] [interp] fix scope issue regarding `klass` var

- mono/mini/aot-compiler.c
- mono/mini/mini-runtime.c
- scripts/ci/run-jenkins.sh
- sdks/ios/Makefile
- sdks/ios/README.md
- sdks/ios/appbuilder/appbuilder.cs
- sdks/ios/runtime/runtime.m
depends on https://github.com/mono/mono/pull/9295
should be backported to `2018-06`
> [ios sdk] add interp-only support

- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/win32_net_4_x_corlib.dll.sources
Testing build... currently all PRs with bumped corefx fail to build, this should fix it.
> Bump corefx.

- mono/metadata/Makefile.am
- scripts/ci/run-jenkins.sh
backport of https://github.com/mono/mono/pull/9480
> [2018-06] [sdks] fix build for watchOS and tvOS

- mcs/mcs/expression.cs
- mcs/tests/test-ref-12.cs
- mcs/tests/ver-il-net_4_x.xml
> [mcs] Implements awaited expression check for indirections

- mono/metadata/handle.h
- mono/metadata/marshal.c
> [coop] Fix MONO_HANDLE_TRACK_OWNER build

- mono/mini/interp/transform.c
- scripts/ci/run-jenkins.sh
- sdks/ios/Makefile
- sdks/ios/appbuilder/appbuilder.cs
AOT compile mscorlib, everything else runs in the interpreter
> [sdks] add interp-mixed to iOS SDK

- mcs/mcs/expression.cs
- mcs/tests/test-ref-12.cs
- mcs/tests/ver-il-net_4_x.xml
> [2018-06] [mcs] Implements awaited expression check for indirections

- mono/mini/cfold.c
- mono/mini/decompose.c
- mono/mini/intrinsics.c
- mono/mini/ir-emit.h
- mono/mini/local-propagation.c
- mono/mini/method-to-ir.c
- mono/mini/mini-ops.h
- mono/mini/mini.h
> [2018-06] [jit] Add Span\u003cT\u003e intrinsics.

- mono/utils/mono-rand-windows.c
> Remove Vista support now that Unity has.

- mono/cil/.gitignore
- mono/cil/Makefile.am
- mono/cil/cil-opcodes.xml
- mono/cil/make-opcodes-def.pl
- mono/cil/opcode.def
Backport of #9111.
/cc @jaykrell
> [2018-06] Opcodes.def is no longer generated and there are reports of breaks.

- mono/mini/interp/transform.c
- scripts/ci/run-jenkins.sh
- sdks/ios/Makefile
- sdks/ios/appbuilder/appbuilder.cs
Backport of #9493.
/cc @lewurm
> [2018-06] [sdks] add interp-mixed to iOS SDK

- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
> [corlib] Include all span helpers optimizations

- mcs/errors/cs1644-64.cs
- mcs/errors/cs1644-65.cs
- mcs/errors/cs1644-66.cs
- mcs/mcs/cs-parser.jay
> [mcs] Constrain expression bodied accessors to C# 7

- mcs/build/common/basic-profile-check.cs
> [build] Bump mcs bootstrap version

- mcs/class/System/System.csproj
- mcs/class/System/corefx.unix.sources
- mcs/class/System/corefx/Unix/Interop.Read.cs
- mcs/class/System/corefx/Unix/Interop.cs
- mcs/class/System/unix_net_4_x_System.dll.sources
- mono/metadata/Makefile.am
- mono/metadata/filewatcher.c
- mono/metadata/filewatcher.h
- mono/metadata/icall-def.h
- mono/metadata/marshal.c
- mono/metadata/marshal.h
- mono/metadata/pal-icalls.c
- mono/metadata/pal-icalls.h
- mono/metadata/pal_config.h
- mono/utils/mono-compiler.h
- mono/utils/mono-threads.h
Progresses #6966
System.Native icalls now live in `metadata/pal-icalls.c|h`
> CoreFX FileSystemWatcher (Linux)

- configure.ac
- mcs/class/corlib/System/Delegate.cs
- mcs/class/corlib/Test/System/DelegateTest.cs
- mono/metadata/object-internals.h
- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
> [interp] Delegate fixes

- mono/metadata/cominterop.c
- mono/metadata/icall-def.h
- mono/metadata/marshal.h
- mono/metadata/object-internals.h
- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/utils/mono-threads.h
i.e. to see in debugger and for static type checking
> [Coop] Convert 3 more functions and strengthen some types to be not just gpointer.

- mono/mini/mini-posix.c
- mono/utils/mono-merp.c
backport of https://github.com/mono/mono/pull/9607
> [2018-02] [runtime] Make sigterm dumper send file to merp

- mono/mini/mini-posix.c
- mono/utils/mono-merp.c
> [2018-04] [runtime] Make sigterm dumper send file to merp

- mono/mini/mini-posix.c
- mono/utils/mono-merp.c
> [2018-06] [runtime] Make sigterm dumper send file to merp

- mono/metadata/icall.c
> [2018-02] Fix LogcatTextWriter writing garbage and/or crashing

- mono/metadata/icall.c
Backport of #9606.
/cc @lewurm
> [2018-04] Fix LogcatTextWriter writing garbage and/or crashing

- mono/metadata/icall.c
Backport of #9606.
/cc @lewurm
> [2018-06] Fix LogcatTextWriter writing garbage and/or crashing

- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
- mono/mini/mini-exceptions.c
Fixing some random failures of threadpool-exceptions7.exe
> [interp] Move some wrapper generation from interp to transform

- mcs/class/System/Test/System.ComponentModel/TypeDescriptorTests.cs
> [System] Update mobile tests to reflect missing DesignerAttribute

- mcs/class/System/Test/System.ComponentModel/TypeDescriptorTests.cs
> [2018-06] [System] Update mobile tests to reflect missing DesignerAttribute

- mono/tests/split-tailcall-interface-conservestack.cpp
- mono/tests/tailcall/split-fsharp.cpp
These programs work if you just compile them with g++ and most of the automake/autoconf/libtool
flags, but not if you use all of automake/autoconf/libtool switches. Something to do with library search paths perhaps?
> Workaround broken AIX toolset (libtool).

- mcs/class/corlib/System/TermInfoReader.cs
Backport of #9520.
/cc @lewurm
> [2018-06] [TermInfo] fix reading integer value for new file format

- configure.ac
Fixes https://github.com/mono/mono/issues/9421.
> [runtime] Run update_submodules.sh earlier.

- mcs/class/corlib/System/TermInfoReader.cs
Backport of #9520.
/cc @lewurm
> [2018-04] [TermInfo] fix reading integer value for new file format

- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
- mono/mini/mini-exceptions.c
Backport of #9601.
/cc @lewurm
> [2018-06] [interp] Move some wrapper generation from interp to transform

- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
Backport of #9644.
/cc @lewurm
> [2018-06] [interp] add Span\u003cT\u003e intrinsics for get_Item and get_Length

- mono/metadata/appdomain-icalls.h
- mono/metadata/appdomain.c
(just started with Centrinel report but had to take a break right away)
> [Coop] Remove ves_icall_System_AppDomain_GetIDFromDomain.

- configure.ac
- mono/metadata/w32file-unix.c
Backport of #9642.
/cc @lewurm
> [2018-06] [MacOS] On Mac, use the copyfile API to copy files

- mcs/class/System.Core/System.Core_xtest.dll.sources
- mcs/class/corlib/corlib_xtest.dll.sources
> [build] Update xunit to 2.4 version

- mono/eglib/glib.h
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
> [interp] Overflow fixes

- mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLite3.cs
- mcs/class/System/Mono.AppleTls/MonoCertificatePal.cs
See https://github.com/dotnet/corefx/pull/31457
> Fix comparison of IntPtr with null in Mono

- packaging/MacSDK/fsharp.py
- packaging/MacSDK/patches/fsharp-debug-pinvoke-fix.patch
Backport of #9792.
/cc @nosami
> [2018-06] Apply F# portable pdb debug fix for pinvokes \u0026 bump

- packaging/MacSDK/fsharp.py
- packaging/MacSDK/patches/fsharp-debug-pinvoke-fix.patch
Backport of #9792.
/cc @nosami
> [2018-04] Apply F# portable pdb debug fix for pinvokes \u0026 bump

- mono/mini/interp/interp.c
Backport of #9838.
/cc @lewurm
> [2018-06] [interp] Fix span exception throwing

- scripts/ci/run-test-interpreter.sh
> [interp] Run tests for entire bcl

- mcs/build/tests.make
> [build] Switch to netstandard based xunit

- mono/sgen/sgen-conf.h
- sdks/builds/ios.mk
> [runtime] Cross32 changes.

- mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/9869.
> [llvm] Fix OP_ABSF.

- mcs/build/tests.make
> [build] Updates script after xunit runner utility rename

- mcs/tools/linker/Makefile
> [linker] Pass more profile flags to calculate size

- mono/metadata/class.c
> [2018-08] Add missing return from the function.

- mcs/class/corlib/LinkerDescriptor/mscorlib.xml
- mcs/class/corlib/Makefile
Cleans up static descriptors for no longer available types
> [corlib] Update linker descriptors

- sdks/builds/download-llvm36.sh
> [2018-06][sdks] Install the llvm36 versions of opt/llc as well.

- mcs/build/common/basic-profile-check.cs
> [2018-06][build] Bump bootstrap mcs version

- configure.ac
- mono/dis/main.c
- mono/metadata/appdomain.c
- mono/metadata/assembly-internals.h
- mono/metadata/assembly.c
- mono/metadata/attach.c
- mono/metadata/coree.c
- mono/metadata/domain.c
- mono/metadata/icall.c
- mono/metadata/mono-security.c
- mono/metadata/reflection-internals.h
- mono/metadata/w32socket.c
- mono/mini/driver.c
- mono/tests/Makefile.am
- mono/tests/assembly-load-reference/Makefile.am
- mono/tests/assembly-load-reference/README
- mono/tests/assembly-load-reference/mainanddep/LoadFileMain.cs
- mono/tests/assembly-load-reference/mainanddep/LoadFromMain.cs
- mono/tests/assembly-load-reference/samedir/LoadFileMain.cs
- mono/tests/assembly-load-reference/samedir/LoadFromMain.cs
- mono/tests/assembly-load-reference/separatedir/LoadFileMain.cs
- mono/tests/assembly-load-reference/separatedir/LoadFromMain.cs
- mono/tests/assembly-load-reference/src/Dep.cs
- mono/tests/assembly-load-reference/src/Mid.cs
- mono/utils/mono-path.c
- mono/utils/mono-path.h
- tools/pedump/pedump.c
> [2018-08] [loader] Determine assembly load context from path

- mono/mini/method-to-ir.c
> [llvmonly] Fix a regression caused by 55950a060838c3d044dc23c9a9a2a99102977146.

- mono/metadata/custom-attrs.c
- mono/metadata/loader.c
- mono/metadata/object.c
- mono/metadata/reflection.c
- mono/metadata/remoting.c
- mono/metadata/sgen-mono-ilgen.c
- mono/metadata/sre-encode.c
- mono/metadata/sre-save.c
- mono/metadata/sre.c
- mono/metadata/w32socket.c
The result would be undefined/uninitialized -- presumably that is what we get in C,
not as safe as it seems.
> [cxx] C++ does not allow goto around initialization.

- mono/metadata/threads.c
- mono/utils/mono-error.c
> [2018-08] [coop] Thread.JoinInternal should not call mono_error_set_pending_exception

- mono/metadata/threads.c
- mono/utils/mono-error.c
> [2018-06] [coop] Thread.JoinInternal should not call mono_error_set_pending_exception

- mono/eglib/glib.h
- mono/utils/lock-free-alloc.c
- mono/utils/mono-error.c
- mono/utils/mono-flight-recorder.c
- mono/utils/mono-logger.c
- mono/utils/mono-threads-coop.c
- mono/utils/mono-threads.c
- mono/utils/mono-utility-thread.c
Some fixes are separated or pending my own review, for a separate PR, but this is the vast majority.
> [cxx] Mostly port utils.

- mono/metadata/w32file-unix.c
Backport of #10001.
/cc @luhenry
> [2018-06] [w32file] Fix typo

- mono/metadata/w32file-unix.c
Backport of #10001.
/cc @luhenry
> [2018-08] [w32file] Fix typo

- configure.ac
Fixes the build on AIX and FreeBSD, and some stuff for Haiku. (More Haiku stuff is blocking on upstream CoreFX merging the Haiku PAL patchset.)
> Misc autotools fixes

- mono/metadata/w32file-unix.c
Backport of #10008.
/cc @luhenry
> [2018-06] [w32file] Fix usage of copyfile

- mono/tests/Makefile.am
> [2018-08] [ci] Disable sgen-new-threads-collect.exe until #9959 is addressed

- mcs/class/corlib/System.Runtime.CompilerServices/PreserveDependencyAttribute.cs
- mcs/class/corlib/System.Security.Cryptography/CryptoConfig.Mobile.cs
- mcs/tools/linker/Makefile
- mcs/tools/linker/monolinker.csproj
- mcs/tools/linker/monolinker.exe.sources
> Bump linker to fix reflection deps

- mono/mini/mini-ppc.c
Backport of #9108.
/cc @directhex
> [2018-06] [ppc] Lower OP_LMUL_IMM.

- mono/eglib/gdir-win32.c
- mono/eglib/glib.h
Notice gdir-win32.c doesn't include config.h.
> [cxx] Make gunichar2==wchar_t on Windows.

- mcs/class/corlib/Test/System.Reflection/ParameterInfoTest.cs
Backport of #10103.
/cc @vargaz
> [2018-06] [bcl] Disable a test which fails with linking.

- mcs/class/corlib/Test/System.Reflection/ParameterInfoTest.cs
> [2018-08] [bcl] Disable a test which fails with linking.

- mono/mini/ee.h
- mono/mini/interp-stubs.c
- mono/mini/interp/interp.c
- mono/mini/interp/transform.c
- mono/mini/mini-runtime.c
- mono/mini/mini-trampolines.c
- scripts/ci/run-test-interpreter.sh
> [interp] Fix missing InvalidProgramException

- mcs/class/corlib/ReferenceSources/RuntimeType.cs
- mcs/class/corlib/System/RuntimeTypeHandle.cs
- mcs/class/corlib/Test/System/TypeTest.cs
- mcs/class/referencesource/mscorlib/system/rttype.cs
- mono/metadata/class-internals.h
- mono/metadata/class.c
- mono/metadata/icall-def.h
- mono/metadata/icall.c
On my machine the benchmark in #10000 takes `889` ms.   Using this native version, I get `222`ms.  So approximately a 4x speedup.
> [reflection] Implement RuntimeType.IsSubclassOf in native

- mcs/class/corlib/ReferenceSources/RuntimeType.cs
- mcs/class/corlib/System/RuntimeTypeHandle.cs
- mcs/class/corlib/Test/System/TypeTest.cs
- mcs/class/referencesource/mscorlib/system/rttype.cs
- mono/metadata/class-internals.h
- mono/metadata/class.c
- mono/metadata/icall-def.h
- mono/metadata/icall.c
Backport of #10012 
----
Fixes a performance regression https://github.com/mono/mono/issues/10000
> [2018-06][reflection] Implement RuntimeType.IsSubclassOf in native

- sdks/builds/llvm.mk
Fix for https://github.com/xamarin/xamarin-android/pull/1836
> [2018-06] [sdks] Fix llvm build with MXE

- mcs/class/corlib/ReferenceSources/RuntimeType.cs
- mcs/class/corlib/System/RuntimeTypeHandle.cs
- mcs/class/corlib/Test/System/TypeTest.cs
- mcs/class/referencesource/mscorlib/system/rttype.cs
- mono/metadata/class-internals.h
- mono/metadata/class.c
- mono/metadata/icall-def.h
- mono/metadata/icall.c
> [2018-08] [reflection] Implement RuntimeType.IsSubclassOf in native

- mcs/class/corlib/Makefile
- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
- mcs/class/corlib/corlib_xtest.dll.sources
Part of https://github.com/mono/mono/issues/9660.
> [System.Reflection] CoreFX import for ManifestResourceInfo and ResourceLocation types

- sdks/builds/ios.mk
> [2018-08] [sdks] Fix typo in ios template

- mcs/class/corlib/Test/System.Reflection/AssemblyTest.cs
- mcs/tools/compiler-tester/compiler-tester.cs
- mono/metadata/appdomain.c
- mono/tests/Makefile.am
- mono/tests/test-multi-netmodule-4-exe.cs
Fixes https://github.com/mono/mono/issues/9943
> [reflection] Assembly.LoadFile should throw ArgumentException for relative paths

- mcs/class/corlib/Test/System.Reflection/AssemblyTest.cs
- mcs/tools/compiler-tester/compiler-tester.cs
- mono/metadata/appdomain.c
- mono/tests/Makefile.am
- mono/tests/test-multi-netmodule-4-exe.cs
> [2018-08] [reflection] Assembly.LoadFile should throw ArgumentException for relative paths

- mcs/class/corlib/Test/System.Reflection/AssemblyTest.cs
- mcs/tools/compiler-tester/compiler-tester.cs
- mono/metadata/appdomain.c
- mono/tests/Makefile.am
- mono/tests/test-multi-netmodule-4-exe.cs
> [2018-06] [reflection] Assembly.LoadFile should throw ArgumentException for relative paths

- mono/mini/tramp-arm64.c
Fixes https://github.com/mono/mono/issues/9566
> [arm64] Unwind info for generic trampoline

- mcs/class/corlib/System.Globalization/CultureInfo.cs
>  Revert "[runtime] Cache culture locale name in managed"

- mcs/class/System/System.Diagnostics/Process.cs
> [2018-08] Fix process leak in process enumeration.

- mcs/class/System/System.Diagnostics/Process.cs
> [2018-06] Fix process leak in process enumeration.

- configure.ac
- mono/metadata/object-internals.h
- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/mini/mini-exceptions.c
- mono/mini/mini-posix.c
- mono/mini/mini-runtime.h
- mono/utils/mono-state.c
- mono/utils/mono-state.h
- sdks/builds/runtime.mk
- winconfig.h
> [2018-08] Enable mono-state-based telemetry for crashing on CI

- mono/metadata/class.c
- mono/tests/Makefile.am
- mono/tests/generic-unmanaged-constraint.cs
> [2018-08] Properly inflate pointer types in inflate_generic_type. 

- mono/metadata/w32file-unix.c
These are the ones all 0x80000000 or higher.
And remove an excess const.
For consistenty/ease, we could cast them all.
Or change the type to unsigned long (and cast back at use to preserve meaning).
> [cxx] Don't use overflowing constants, to avoid warning/error in some configurations.

- mcs/class/corlib/corert/Type.cs
- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
> [System.Reflection] CoreFX import fot Pointer type

- mono/utils/mono-threads-mach.c
- mono/utils/mono-threads-windows.c
- mono/utils/mono-threads.c
> [2018-08] [coop] Check async suspend status in ReqSuspendInitSuspendBlocking case

- mono/metadata/sgen-stw.c
- mono/tests/Makefile.am
- mono/utils/mono-threads-state-machine.c
- mono/utils/mono-threads.c
- mono/utils/mono-threads.h
Backport of #10140.
/cc @luhenry
> [2018-08] [hybrid-suspend] Two phase STW

- mcs/class/System/Mono.Btls/MonoBtlsProvider.cs
- mcs/class/System/Mono.Btls/MonoBtlsX509StoreCtx.cs
- mcs/class/System/Mono.Btls/X509ChainImplBtls.cs
- mcs/class/System/System.Security.Cryptography.X509Certificates/X509ChainImpl.cs
- mcs/class/System/System.Security.Cryptography.X509Certificates/X509ChainImplMono.cs
> [2018-08] An implementation of the ChainStatus property for Btls

- mcs/class/System/Mono.Btls/MonoBtlsProvider.cs
- mcs/class/System/Mono.Btls/MonoBtlsX509StoreCtx.cs
- mcs/class/System/Mono.Btls/X509ChainImplBtls.cs
- mcs/class/System/System.Security.Cryptography.X509Certificates/X509ChainImpl.cs
- mcs/class/System/System.Security.Cryptography.X509Certificates/X509ChainImplMono.cs
> [2018-06] An implementation of the ChainStatus property for Btls

- mono/mini/Makefile.am.in
> [2018-08] [mini] Don't regen Makefile.am if llvm/llvm_config.mk changes

- mono/eglib/gstr.c
- mono/eglib/test/string-util.c
Backport of #10255.
/cc @luhenry
> [2018-04] [eglib] Fix URI to file name conversion

- llvm/build.mk
Backport of #10263.
/cc @BrzVlad
> [2018-08] [llvm] Use curl as fallback for wget

- llvm/build.mk
> [llvm] Use curl as fallback for wget

- mono/mini/mini-amd64.c
- mono/mini/mini-amd64.h
- mono/mini/mini-arm.c
- mono/mini/mini-arm.h
- mono/mini/mini-arm64.c
- mono/mini/mini-arm64.h
- mono/mini/mini-mips.c
- mono/mini/mini-ppc.c
- mono/mini/mini-s390x.c
- mono/mini/mini-x86.c
- mono/mini/mini.h
…; strengthen CallInst.call_info from gpointer to CallInfo*.
> Strengthen mono_arch_get_seq_point_info() & CallInst.call_info from void*.

- mcs/class/System.Windows.Forms/Makefile
- mcs/class/System.Windows.Forms/System.Windows.Forms.Layout/DefaultLayout.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/TextBoxBase.cs
- mcs/class/System.Windows.Forms/samples/issue10235.cs
> System.Windows.Forms: Fix regressions in layout code and TextBox Font handling

- mcs/class/System.Windows.Forms/Makefile
- mcs/class/System.Windows.Forms/System.Windows.Forms.Layout/DefaultLayout.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/TextBoxBase.cs
- mcs/class/System.Windows.Forms/samples/issue10235.cs
Backport of #10238.
/cc @filipnavara
> [2018-08] System.Windows.Forms: Fix regressions in layout code and TextBox Font handling

- mcs/class/System.Windows.Forms/Makefile
- mcs/class/System.Windows.Forms/System.Windows.Forms.Layout/DefaultLayout.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/TextBoxBase.cs
- mcs/class/System.Windows.Forms/samples/issue10235.cs
Backport of #10238.
/cc @filipnavara
> [2018-06] System.Windows.Forms: Fix regressions in layout code and TextBox Font handling

- mcs/tools/mkbundle/mkbundle.cs
- mcs/tools/mkbundle/template_common.inc
This fixes the additional warnings mentioned in #10170
> Mkbundle warnings

- configure.ac
- mcs/class/corlib/Mono/Runtime.cs
- mono/metadata/icall-def.h
- mono/metadata/icall.c
- mono/metadata/object-internals.h
- mono/metadata/threads.c
- mono/mini/mini-exceptions.c
- mono/mini/mini-posix.c
- mono/utils/mono-merp.c
- mono/utils/mono-merp.h
- mono/utils/mono-state.c
- mono/utils/mono-state.h
> [2018-04] Add pipeline to convert managed exception into telemetry format

- mono/mini/method-to-ir.c
> Revert "[jit] Disable tail calls from gsharedvt code for now."

- mono/mini/mini-exceptions.c
Backport of https://github.com/mono/mono/pull/10316
> [2018-06] [mini] fix memory dumping on devices 

- packaging/MacSDK/mono.py
- tools/offsets-tool/MonoAotOffsetsDumper.cs
After another grep with different search terms I found a few more matches.
Follow up to #10286 
Fixes #9581
> Follow up to bump target requirement to OSX 10.9 Mavericks

- configure.ac
- llvm/Makefile.am
- llvm/build_llvm_config.sh
Backport of #10321.
/cc @lateralusX
> [2018-08] Fix Windows LLVM mono cross compiler build.

- mono/mini/mini-posix.c
Backport of #10316.
/cc @lewurm
> [2018-08] [mini] fix memory dumping on devices

- mono/mini/builtin-types.cs
- mono/mini/interp/transform.c
needs backport to `2018-06` and `2018-08`
> [interp] white list nfloat::IsNaN ()

- README.md
I changed all the link for going to the https version as there is no redirect in some of them (.net foundation and monoproject)
> Changed http: to https:

- mono/metadata/loader.c
- mono/mini/arch-stubs.c
- mono/mini/debugger-agent.c
- mono/mini/exceptions-amd64.c
- mono/mini/exceptions-arm.c
- mono/mini/exceptions-arm64.c
- mono/mini/interp/interp.c
- mono/mini/mini-exceptions.c
- mono/mini/mini-runtime.h
- mono/mini/mini-wasm.c
- mono/mini/mini.h
- mono/utils/mono-compiler.h
- mono/utils/mono-stack-unwinding.h
Backport of https://github.com/mono/mono/pull/10224
> [2018-06] [interp] fix ftnptr_eh_callback

- mono/metadata/loader.c
- mono/mini/arch-stubs.c
- mono/mini/debugger-agent.c
- mono/mini/debugger-engine.c
- mono/mini/exceptions-amd64.c
- mono/mini/exceptions-arm.c
- mono/mini/exceptions-arm64.c
- mono/mini/interp/interp.c
- mono/mini/mini-exceptions.c
- mono/mini/mini-runtime.h
- mono/mini/mini-wasm-debugger.c
- mono/mini/mini.h
- mono/utils/mono-compiler.h
- mono/utils/mono-stack-unwinding.h
Backport of #10224.
/cc @lewurm
> [2018-08] [interp] fix ftnptr_eh_callback

- acceptance-tests/SUBMODULES.json
Includes https://github.com/mono/coreclr/pull/1
> Bump CoreCLR to fix two math acceptance tests

- mcs/class/System/Mono.Btls/MonoBtlsProvider.cs
Backport of #10396.
/cc @baulig
> [2018-08] [System]: Fix `MonoBtlsProvider.CheckValidationResult ()` logic.

- mono/eglib/ghashtable.c
- mono/eglib/glib.h
- mono/eglib/gmem.c
- mono/metadata/cominterop.c
- mono/metadata/icall.c
- mono/metadata/marshal.c
- mono/metadata/object.c
- mono/metadata/sgen-mono.c
(split from a more significant PR)
> Minor cleanup.

- mono/mini/lldb.c
- mono/mini/mini-amd64.c
- mono/mini/mini-arm.c
- mono/mini/mini-arm64.c
- mono/mini/xdebug.c
- mono/utils/memfuncs.h
- mono/utils/mono-compiler.h
How to discover these systematically, i.e. the debugger one?
The others are obvious link errors.
> [cxx]  Some required extern "C" and some minor cleanup.

- mono/unit-tests/Makefile.am
Reported by NattyNarwhal.
https://gitter.im/mono/mono?at=5b8802eb1d3a5711b6bd6c8f
> Fix test dependencies build problem.

- mono/metadata/object-internals.h
- mono/metadata/object.c
- mono/metadata/sgen-client-mono.h
Backport of #10355.
/cc @BrzVlad
> [2018-08] [sgen] Fix string size inconsistency between alloc/scan

- mono/utils/mono-threads.c
> [2018-08] [coop] Fixup dump_threads () legend to match thread state enum values

- mono/metadata/object-internals.h
- mono/metadata/object.c
- mono/metadata/sgen-client-mono.h
Backport of #10355.
/cc @BrzVlad
> [2018-06] [sgen] Fix string size inconsistency between alloc/scan

- mono/mini/builtin-types.cs
- mono/mini/interp/transform.c
Backport of #10357.
/cc @lewurm
> [2018-06] [interp] white list nfloat::IsNaN ()

- mono/arch/amd64/amd64-codegen.h
- mono/mini/cpu-amd64.md
- mono/mini/intrinsics.c
- mono/mini/mini-amd64.c
- mono/mini/mini-llvm.c
- mono/mini/mini-ops.h
> [jit] Add intrinsics for Math.Round/Floor/Cecil () on SSE41.

- mcs/class/corlib/ReferenceSources/String.cs
- mcs/class/corlib/Test/System.Reflection/MethodInfoTest.cs
> [2018-06] [corlib] Bring back String.Concat with __arglist

- mcs/class/corlib/ReferenceSources/String.cs
- mcs/class/corlib/Test/System.Reflection/MethodInfoTest.cs
> [2018-08] [corlib] Bring back String.Concat with __arglist

- mcs/class/corlib/ReferenceSources/String.cs
- mcs/class/corlib/Test/System.Reflection/MethodInfoTest.cs
> [2018-04] [corlib] Bring back String.Concat with __arglist

- mcs/class/System/Mono.Btls/MonoBtlsProvider.cs
Backport of #10396.
/cc @baulig
> [2018-06] [System]: Fix `MonoBtlsProvider.CheckValidationResult ()` logic.

- mono/eglib/gfile-unix.c
- mono/metadata/icall-table.c
- mono/metadata/icall.c
- mono/metadata/image.c
- mono/metadata/marshal-windows.c
- mono/metadata/marshal.c
- mono/metadata/mempool.h
- mono/metadata/method-builder-ilgen.h
- mono/metadata/object-internals.h
- mono/metadata/object.c
- mono/metadata/profiler.c
- mono/metadata/reflection-cache.h
- mono/metadata/sgen-client-mono.h
- mono/metadata/sgen-mono.c
- mono/metadata/sre-encode.c
- mono/metadata/sre.c
- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/metadata/w32file-unix-glob.c
- mono/metadata/w32file.c
- mono/metadata/w32handle.h
- mono/metadata/w32process-win32.c
- mono/metadata/w32process.c
- mono/metadata/w32process.h
- mono/metadata/w32socket-win32.c
- mono/metadata/w32socket.c
- mono/metadata/w32socket.h
Mostly casts, some type change.
This should finish the metadata directory.
> [cxx] [metadata] Convert to be valid C and C++.

- mcs/class/System/Test/System.IO.Compression/DeflateStreamTest.cs
- support/zlib-helper.c
> Fix DeflateStream handling of zero-length reads from underlying stream.

- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/mini/interp/interp.c
- mono/tests/Makefile.am
> [interp] Don't abort in critical wrappers

- mono/metadata/icall.c
- sdks/wasm/packager.cs
> [wasm] Misc fixes/improvements

- mono/mini/builtin-types.cs
- mono/mini/interp/transform.c
Backport of #10357.
/cc @lewurm
> [2018-08] [interp] white list nfloat::IsNaN ()

- mcs/class/System/System.IO.Compression/DeflateStream.cs
> Ensure the finalization in DeflateStream is performed in the correct order.

- mcs/class/System/System.IO.Compression/DeflateStream.cs
Backport of #10330.
/cc @Therzok
> [2018-04] Ensure the finalization in DeflateStream is performed in the correct order.

- mcs/class/corlib/System.Reflection.Emit/FieldOnTypeBuilderInst.cs
- mcs/class/corlib/System.Reflection/FieldInfo.cs
- mcs/class/corlib/Test/System.Reflection/FieldInfoTest.cs
- mcs/class/referencesource/mscorlib/system/runtime/serialization/serializationfieldinfo.cs
Fixes https://github.com/mono/mono/issues/10495
> [System.Reflection] Make GetFieldOffset method virtual to fix issue with custom FieldInfo type.

- packaging/MacSDK/msbuild.py
> Bump msbuild 2018-06 branch to track xplat-master

- tools/offsets-tool/MonoAotOffsetsDumper.cs
> [MonoAotOffsetsDumper] Remove --monodroid argument

- mono/mini/aot-tests.cs
- mono/mini/mini-arm64.c
> [2018-08] [arm64] Add dyncall support for ArgVtypeByRefOnStack arguments.

- mono/mini/aot-tests.cs
- mono/mini/mini-arm64.c
> [2018-06] [arm64] Add dyncall support for ArgVtypeByRefOnStack arguments.

- mono/mini/aot-tests.cs
- mono/mini/mini-arm64.c
https://github.com/mono/mono/issues/10483
> [arm64] Add dyncall support for ArgVtypeByRefOnStack arguments.

- mcs/build/library.make
- mcs/build/rules.make
> [build] Clean up no longer needed rules and conversions

- mono/mini/interp/interp.c
Fixup for bad merge of #10545 and #10561
> [interp] Add declaration for set_context

- mcs/class/corlib/System.Reflection/MonoMethod.cs
- mcs/class/corlib/Test/System.Reflection/CustomAttributeDataTest.cs
Fixes https://github.com/mono/mono/issues/10544
> [System.Reflection] Fix the issue with constructing DllImportAttribute data

- mcs/mcs/expression.cs
- mcs/tests/test-anon-123.cs
- mcs/tests/ver-il-net_4_x.xml
> [mcs] Adds cloning for default literals

- mcs/class/Facades/subdirs.make
> [2018-06][Facades] Removes duplicate entry

- mcs/class/Facades/subdirs.make
> [2018-08][Facades] Removes duplicate entry

- mono/metadata/marshal-ilgen.c
- mono/mini/ee.h
- mono/mini/interp-stubs.c
- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
- mono/mini/jit-icalls.c
- mono/mini/mini-runtime.c
- mono/mini/mini-trampolines.c
- scripts/ci/run-test-interpreter.sh
Backport of https://github.com/mono/mono/pull/10579
> [2018-08] [interp] move thread attach to interpreter entry

- sdks/builds/.gitignore
resolves https://github.com/mono/mono/issues/10664
> [wasm] Add wasm-cross to .gitignore.

- mono/mini/driver.c
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
- mono/mini/mini.c
Fixes https://github.com/mono/mono/issues/10260
> [interp] add safepoints and enable hybrid suspend as default

- mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs
Backport of #10650.
/cc @vargaz
> [2018-08] [sdb] Avoid calling into the debuggee from VirtualMachine.GetObject () while holding the objects_lock.

- mcs/class/System/Test/System.Net/HttpWebRequestTest.cs
> [System] Improves test failures reporting from TP threads

- mono/mini/interp/transform.c
As we do with jit. Improves speed of typeof operator by 10-15 times.
> [interp] Optimize ldtoken + GetTypeFromHandle pair

- mcs/class/Makefile
> [build] Another make dist fix

- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/metadata/w32mutex-unix.c
See https://jenkins.mono-project.com/job/test-mono-mainline-staticanalysis/Centrinel_20Report/
> [Coop] Convert w32mutex-unix.c.

- mono/mini/driver.c
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
- mono/mini/mini.c
Backport of #10652.
/cc @lewurm
> [2018-08] [interp] add safepoints and enable hybrid suspend as default

- sdks/README.md
resolves https://github.com/mono/mono/issues/10682
> [wasm] Add ninja build to the skds wasm build dependencies documentation.

- mcs/class/corlib/System.Runtime.CompilerServices/ConditionalWeakTable.cs
- mcs/class/corlib/Test/System.Runtime.CompilerServices/ConditionalWeakTableTest.cs
> [2018-06] Implement IEnumerable for ConditionalWeakTable

- mcs/class/corlib/System.Runtime.CompilerServices/ConditionalWeakTable.cs
- mcs/class/corlib/Test/System.Runtime.CompilerServices/ConditionalWeakTableTest.cs
> [2018-08] Implement IEnumerable for ConditionalWeakTable

- mcs/tools/mono-api-html/Helpers.cs
> [2018-08] [mono-api-html] Fix rendering of nuint.

- tools/offsets-tool/MonoAotOffsetsDumper.cs
Backport of #10690.
/cc @luhenry
> [2018-08] [offset-tool] Error out when parsing fails.

- tools/offsets-tool/MonoAotOffsetsDumper.cs
Backport of #10690.
/cc @luhenry
> [2018-06] [offset-tool] Error out when parsing fails.

- tools/offsets-tool/MonoAotOffsetsDumper.cs
Backport of #10690.
/cc @luhenry
> [2018-04] [offset-tool] Error out when parsing fails.

- mcs/tools/mono-api-html/FieldComparer.cs
Backport of #10663.
/cc @luhenry
> [2018-06] [mono-api-html] Render something for fields with marshalling info.

- mcs/tools/mono-api-html/FieldComparer.cs
Backport of #10663.
/cc @luhenry
> [2018-08] [mono-api-html] Render something for fields with marshalling info.

- mono/metadata/dynamic-image.c
- mono/metadata/sre-internals.h
- mono/metadata/sre.c
See https://jenkins.mono-project.com/job/test-mono-mainline-staticanalysis/Centrinel_20Report/.
Perhaps some unnecessary change here, the out parameter vs. boolean. If so I can reduce it.
> [Coop] Convert dynamic-image.c.

- mono/metadata/assembly.c
See https://jenkins.mono-project.com/job/test-mono-mainline-staticanalysis/Centrinel_20Report/.
> [Coop] Convert assembly.c.

- mcs/mcs/settings.cs
> [mcs] Adds sourcelink option (as unsupported)

- mono/eglib/glib.h
- mono/eglib/gstr.c
- mono/eglib/test/string-util.c
- mono/metadata/appdomain.c
- mono/metadata/w32file-unix.c
- mono/mini/aot-compiler.c
- mono/utils/mono-io-portability.c
- mono/utils/mono-path.c
Noticed some duplication of exit paths doing coop conversion for example.
>  Some cleanup in appdomain.c.

- mono/mini/mini-exceptions.c
Backport of #10723.
/cc @luhenry
> [2018-08] [crash] Fix summarize_frame assertion

- mono/mini/mini-exceptions.c
Backport of #10723.
/cc @luhenry
> [2018-04] [crash] Fix summarize_frame assertion

- sdks/builds/runtime.mk
Backport of #10711.
/cc @luhenry
> [2018-06] [SDKS] Build host runtime with correct bitness

- sdks/builds/runtime.mk
Backport of #10711.
/cc @luhenry
> [2018-04] [SDKS] Build host runtime with correct bitness

- sdks/builds/runtime.mk
Backport of #10711.
/cc @luhenry
> [2018-08] [SDKS] Build host runtime with correct bitness

- mcs/class/corlib/Test/System.Runtime.Remoting/RemotingServicesTest.cs
> [corlib] Increases test timeout

- scripts/ci/run-jenkins.sh
- sdks/builds/ios.mk
> [sdks] Add a 64 bit arm32 cross compiler build.

- configure.ac
- mono/dis/declsec.c
- mono/dis/dis-cil.c
- mono/dis/dump.c
- mono/dis/get.c
- mono/dis/util.c
- mono/dis/util.h
- mono/mini/decompose.c
- mono/mini/interp/interp.c
- mono/mini/jit-icalls.c
- mono/mini/jit-icalls.h
- mono/mini/mini-llvm.c
- mono/mini/mini-runtime.c
- mono/utils/Makefile.am
- mono/utils/mono-compiler.h
- mono/utils/mono-math-c.c
- mono/utils/mono-math.c
- mono/utils/mono-math.h
- msvc/libmonoutils-common.targets
- msvc/libmonoutils-common.targets.filters
- sdks/builds/ios.mk
- winconfig.h
Android was giving quite some problems otherwise, and WebAssembly less so.
> [cxx] Rework C++ linkage to C99 trunc, isnan, isinf, etc. and some cleanup.

- mono/tests/Makefile.am
https://github.com/mono/mono/issues/8997
> Disable some flaky tests

- mono/utils/mono-merp.c
> [2018-02] [merp] Fix return value handling of posix_spawn

- packaging/MacSDK/msbuild.py
This fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/682034
> Bump msbuild to track mono-2018-06

- mcs/class/System.Core/Makefile
- mcs/class/System.Core/System.Core.csproj
> [System.Core] Removes no longer needed reference

- mono/utils/mono-merp.c
> [2018-06] [merp] Fix return value handling of posix_spawn

- mono/utils/mono-merp.c
> [2018-04] [merp] Fix return value handling of posix_spawn

- mono/utils/mono-merp.c
> [2018-08] [merp] Fix return value handling of posix_spawn

- mcs/class/System.Core/Makefile
- mcs/class/System.Core/System.Core.csproj
> [2018-08] [System.Core] Removes no longer needed reference

- sdks/builds/mxe.mk
Backport of #10853.
/cc @luhenry
> [2018-04] [sdks] One more update to get XA PR builds working on Linux

- sdks/builds/mxe.mk
Backport of #10853.
/cc @luhenry
> [2018-06] [sdks] One more update to get XA PR builds working on Linux

- sdks/builds/mxe.mk
Backport of #10853.
/cc @luhenry
> [2018-08] [sdks] One more update to get XA PR builds working on Linux

- mcs/class/corlib/System.Runtime.CompilerServices/PreserveDependencyAttribute.cs
- mcs/class/corlib/System.Runtime.InteropServices/Marshal.cs
- mcs/class/corlib/System.Runtime.InteropServices/MarshalAsAttribute.cs
- mcs/class/corlib/System.Threading/Timer.cs
- mcs/class/referencesource/mscorlib/system/threading/thread.cs
- mcs/class/referencesource/mscorlib/system/threading/threadpool.cs
- mcs/tools/linker/Makefile
- mcs/tools/linker/Tests/mscorlib/test-marshaling.cs
- mcs/tools/linker/Tests/mscorlib/test-reflection-02.cs
> [linker] Adds more reflection tests

- mono/mini/mini-exceptions.c
> [runtime] Disable stack guard for main thread on osx

- mcs/tools/linker/Makefile
> [linker] Reenable accidentally disabled test

- runtime/Makefile.am
- scripts/ci/run-jenkins.sh
- sdks/builds/Makefile
- sdks/builds/android.mk
- sdks/builds/bcl.mk
- sdks/builds/desktop.mk
- sdks/builds/ios.mk
- sdks/builds/llvm.mk
- sdks/builds/runtime.mk
- sdks/builds/wasm.mk
- sdks/desktop/Makefile
- sdks/wasm/Makefile
- sdks/wasm/packager.cs
Backport of #10882.
/cc @luhenry @luhenry
Description of #10882:
> [2018-10] [sdks] Create archive targets for pre-building on CI

- mcs/class/corlib/System.Reflection/Module.cs
- mcs/class/corlib/Test/System.Reflection/ModuleTest.cs
Fixes https://github.com/mono/mono/issues/10876
> [Reflection] Fix issue with finding types in module using an asterisk as filter criteria

- mcs/class/Facades/System.Drawing.Primitives/Facades_System.Drawing.Primitives.csproj
- mcs/class/Facades/System.Drawing.Primitives/Makefile
- mcs/class/Facades/netstandard/Facades_netstandard.csproj
- mcs/class/Facades/netstandard/Makefile
- mcs/class/Facades/subdirs.make
Backport of #10849.
Description:
see https://github.com/mono/mono/pull/10835
> [2018-08] Use Mono.Android as a reference for netstandard facade

- mono/mini/exceptions-mips.c
- mono/mini/exceptions-ppc.c
- mono/mini/exceptions-s390x.c
- mono/mini/exceptions-sparc.c
> [crash] Fixup field name typo on untested arches

- mono/mini/exceptions-arm64.c
> [crash] Make stub for rethrow_preserve_exception on aarch64

- mcs/tools/linker/Makefile
- mcs/tools/linker/Tests/System.Net.Http/test-handler-01.cs
- mcs/tools/linker/Tests/mscorlib/test-calendar-01.cs
- mcs/tools/linker/Tests/mscorlib/test-calendar-02.cs
- mcs/tools/linker/monolinker.csproj
- mcs/tools/linker/monolinker.exe.sources
> [linker] Adds more tests

- mono/mini/mini-llvm.c
Backport of #10750.
Description:
> [2018-08] [llvm] Remove an incorrect assert.

- packaging/MacSDK/msbuild.py
> [2018-08] Bump msbuild

- mono/metadata/class-init.c
- mono/metadata/class-internals.h
- mono/metadata/class.c
- mono/metadata/class.h
- mono/metadata/custom-attrs.c
- mono/metadata/icall.c
- mono/metadata/loader.c
- mono/metadata/object.c
- mono/metadata/verify.c
- mono/mini/aot-compiler.c
- mono/mini/branch-opts.c
- mono/mini/debugger-agent.c
- mono/mini/interp/interp.c
- mono/mini/method-to-ir.c
- mono/mini/mini-generic-sharing.c
FIXME mono_class_is_assignable_from_checked
> mono_class_is_assignable_from to mono_class_is_assignable_from_internal to skip GC mode machinery

- packaging/MacSDK/msbuild.py
Backport of #11087.
Description:
> [master] Bump msbuild

- packaging/MacSDK/msbuild.py
Backport of #11087.
Description:
> [2018-10] Bump msbuild

- mono/metadata/icall.c
> [metadata] Remove unused type caches

- mono/utils/mono-state.c
> [crash] Bump crash reporter static memory size

- mono/mini/aot-compiler.c
- mono/mini/mini-amd64.c
- mono/mini/mini-amd64.h
- mono/mini/mini-arm.c
- mono/mini/mini-arm64.c
- mono/mini/tramp-amd64.c
Backport https://github.com/mono/mono/pull/10978
> [2018-10] [interp] Implement interpreter entry trampolines on amd64

- mono/utils/mono-sigcontext.h
Contributed by @lenoil98. Fixes https://github.com/mono/mono/issues/11020
> [ppc] fix UCONTEXT_REG macros for FreeBSD

- mcs/class/Mono.Messaging.RabbitMQ/Mono.Messaging.RabbitMQ_test_net_2_0.dll.config
- mcs/class/Mono.Messaging/Mono.Messaging/ConnectionException.cs
- mcs/class/Mono.Messaging/Mono.Messaging/MessageUnavailableException.cs
- mcs/class/Mono.Messaging/Mono.Messaging/MonoMessagingException.cs
- runtime/Makefile.am
- scripts/ci/run-test-default.sh
Nothing fancy, just trying to see if it works in the existing Jenkins environment.
> Upstream a few test related commits from my Helix work

- packaging/MacSDK/packaging/resources/preinstall
Fixes https://github.com/mono/mono/issues/11202
> [pkg] Add preinstall which removes existing Mono of the same version

- packaging/MacSDK/packaging/resources/preinstall
Backport of #11203.
Description:
Fixes https://github.com/mono/mono/issues/11202
> [2018-10] [pkg] Add preinstall which removes existing Mono of the same version

- packaging/MacSDK/packaging/resources/preinstall
Backport of #11203.
Description:
Fixes https://github.com/mono/mono/issues/11202
> [2018-06] [pkg] Add preinstall which removes existing Mono of the same version

- packaging/MacSDK/packaging/resources/preinstall
Backport of #11203.
Description:
Fixes https://github.com/mono/mono/issues/11202
> [2018-08] [pkg] Add preinstall which removes existing Mono of the same version

- configure.ac
- mcs/class/corlib/Mono/Runtime.cs
- mcs/class/corlib/Test/System/ExceptionTest.cs
- mono/metadata/class-internals.h
- mono/metadata/debug-helpers.c
- mono/metadata/domain-internals.h
- mono/metadata/icall-def.h
- mono/metadata/icall.c
- mono/metadata/mono-debug.c
- mono/metadata/object-internals.h
- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/mini/aot-runtime.c
- mono/mini/debugger-engine.c
- mono/mini/interp/transform.c
- mono/mini/mini-exceptions.c
- mono/mini/mini-posix.c
- mono/mini/mini-runtime.c
- mono/mini/mini-runtime.h
- mono/mini/mini.c
- mono/mini/seq-points.c
- mono/mini/seq-points.h
- mono/utils/mono-state.c
- mono/utils/mono-state.h
- mono/utils/mono-threads-posix.c
- mono/utils/mono-threads.h
Let's hold off merging this until we have commits from
https://github.com/mono/mono/pull/11133
and
https://github.com/mono/mono/pull/11142
to cherry-pick onto this. These requested changes overlap with the below commits.
> [2018-10] Crash Reporter V2

- mono/mini/aot-runtime.c
Backport of #11190.
Description:
Executing aot code that uses them would crash. Fixes random csc crashes.
> [2018-08] [aot] Ensure shared got entries are initialized before loading methods

- mono/mini/aot-runtime.c
Backport of #11190.
Description:
Executing aot code that uses them would crash. Fixes random csc crashes.
> [2018-10] [aot] Ensure shared got entries are initialized before loading methods

- mono/mini/aot-compiler.c
- mono/mini/mini-amd64.c
- mono/mini/mini-amd64.h
- mono/mini/mini-arm.c
- mono/mini/mini-arm64.c
- mono/mini/tramp-amd64.c
Backport https://github.com/mono/mono/pull/10978
> [2018-08] [interp] Implement interpreter entry trampolines on amd64

- mono/mini/aot-compiler.c
- mono/mini/mini-amd64.c
- mono/mini/mini-amd64.h
- mono/mini/mini-arm.c
- mono/mini/mini-arm64.c
- mono/mini/tramp-amd64.c
Backport https://github.com/mono/mono/pull/10978
> [2018-06] [interp] Implement interpreter entry trampolines on amd64

- scripts/ci/pipeline/sdks-archive.groovy
Backport of #11247.
/cc @luhenry 
Description:
> [2018-10] [pipeline] Ensure only 1 build per-product is executed per-node

- scripts/ci/pipeline/sdks-archive.groovy
Backport of #11247.
/cc @luhenry 
Description:
> [2018-08] [pipeline] Ensure only 1 build per-product is executed per-node

- mcs/class/Facades/System.Drawing.Primitives/Facades_System.Drawing.Primitives.csproj
- mcs/class/Facades/System.Drawing.Primitives/Makefile
- mcs/class/Facades/netstandard/Facades_netstandard.csproj
- mcs/class/Facades/netstandard/Makefile
- mcs/class/Facades/subdirs.make
Backport of #10849.
Description:
see https://github.com/mono/mono/pull/10835
> [2018-10] Use Mono.Android as a reference for netstandard facade

- mono/mini/aot-tests.cs
- mono/mini/mini-amd64.c
- mono/mini/mini-amd64.h
- mono/mini/mini-arm64.c
- mono/mini/mini-arm64.h
> [2018-06] [arm64] Remove the limitation on the number of nullable arguments for dyncalls

- mono/mini/aot-runtime.c
Broken in https://github.com/mono/mono/pull/11190
> [aot] Reenable recursion checking when initing shared got entries

- mono/mini/aot-runtime.c
Backport of #11258.
/cc @BrzVlad 
Description:
Broken in https://github.com/mono/mono/pull/11190
> [2018-06] [aot] Reenable recursion checking when initing shared got entries

- mono/mini/aot-runtime.c
Backport of #11258.
/cc @BrzVlad 
Description:
Broken in https://github.com/mono/mono/pull/11190
> [2018-08] [aot] Reenable recursion checking when initing shared got entries

- mono/mini/aot-runtime.c
Backport of #11258.
/cc @BrzVlad 
Description:
Broken in https://github.com/mono/mono/pull/11190
> [2018-10] [aot] Reenable recursion checking when initing shared got entries

- mono/mini/mini-wasm.c
Fixup for
https://github.com/mono/mono/commit/5e961c6deb27c6bfc46cdba99274bbe02f8f0562
> [wasm] Add missing include

- mono/mini/mini-wasm.c
Fixup for
https://github.com/mono/mono/commit/5756ba4b46f43d4f1c61c0d7dbbcf27a271f24ab
> [2018-08][wasm] Add missing include

- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
- mcs/class/corlib/corlib_xtest.dll.sources
- mcs/class/referencesource/mscorlib/system/io/fileinfo.cs
Merge with https://github.com/mono/corefx/pull/155
Part of #7246
> [corlib] Import System.IO.TextReader/StreamReader from CoreFX

- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
> [corlib] Remove unused files

- mcs/class/corlib/System.Reflection/Binder.cs
- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
> [2018-08][corlib] Adds back accidentaly removed legacy COM API to Binder

- mcs/class/corlib/System.Reflection/Binder.cs
- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
> [2018-10][corlib] Adds back accidentally removed legacy COM API to Binder

- mcs/class/corlib/System.Reflection/Binder.cs
- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
> [corlib] Adds back accidentally removed legacy COM API to Binder

- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
- mono/mini/aot-runtime.h
- mono/mini/interp/transform.c
- mono/mini/jit-icalls.c
- mono/mini/mini-llvm.c
- mono/mini/mini-trampolines.c
Backport of https://github.com/mono/mono/pull/11321
> [2018-08] [aot] add unbox_arbitrary_trampoline for fullaot/interp mixed mode

- mcs/class/corlib/Test/System.Threading/InterlockedTest.cs
- mcs/class/corlib/Test/System.Threading/ThreadTest.cs
- mcs/class/corlib/Test/System/GCTest.cs
probably won't pass on all configurations, I wanna find out on which.
> [interp] enable more BCL tests

- mcs/class/corlib/Test/System.Threading/InterlockedTest.cs
- mcs/class/corlib/Test/System.Threading/ThreadTest.cs
- mcs/class/corlib/Test/System/GCTest.cs
Backport of #11381.
/cc @lewurm 
Description:
probably won't pass on all configurations, I wanna find out on which.
> [2018-08] [interp] enable more BCL tests

- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
> [corlib] Replace few more simple types with corefx

- mono/tests/Makefile.am
https://github.com/mono/mono/issues/11415
https://github.com/mono/mono/issues/11417
https://github.com/mono/mono/issues/11420
> Disable flaky tests finalizer-abort.exe, process-stress-2.exe, process-stress-3.exe.

- mcs/class/corlib/Test/System/ConvertTest.cs
- mono/eglib/glib.h
- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
Backport of https://github.com/mono/mono/pull/9688 and https://github.com/mono/mono/pull/11380
> [2018-06] [interp] Overflow fixes

- packaging/MacSDK/msbuild.py
Backport of #11440.
Description:
- pickup fix for #11214 .
> [2018-10] Bump msbuild to track xplat-master

- .gitignore
in order to avoid this in the future: https://github.com/mono/mono/pull/11362#issuecomment-434239640
> [gitgnore] put .dylib on ignore list

- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/interp/transform.c
This can lead to 4% general speedup
> [interp] Optimise method execution start

- mcs/class/corlib/System.Runtime.Remoting.Messaging/AsyncResult.cs
- mcs/class/corlib/System.Runtime.Remoting.Messaging/MonoMethodMessage.cs
> [corlib] Deletes unused code

- mcs/class/corlib/corlib_xtest.dll.sources
> [corlib] Remove tests which were moved to System.Core

- mcs/class/corlib/LinkerDescriptor/mscorlib.xml
- mcs/tools/linker/Makefile
- mcs/tools/linker/Tests/mscorlib/test-methodimpl-01.cs
> [corlib] Tweaks few linker descriptors to be more precise

- mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs
> Added missing cts.Cancel() in HttpClient Dispose() method

- mcs/class/reference-assemblies/Makefile
- mcs/mcs/ikvm.cs
- mcs/tools/xbuild/Makefile
- mcs/tools/xbuild/frameworks/net_4.7.2.xml
> [2018-10] Add .NET 4.7.2 reference assemblies (#11391)

- mcs/class/corlib/System.Reflection/MonoProperty.cs
> [corlib] Remove incorrectly converted silverlight check

- Makefile.am
Closes: https://github.com/mono/mono/issues/11501
> Clean up .o files from System.Native during `make dist`

- man/mono.1
> [man] Fixes --compile-all sytax

- mcs/class/System/Test/System.Net/HttpWebRequestTest.cs
Backport of #11175.
/cc @baulig 
Description:
> [2018-10] Make the test compile on mobile.

- mono/tests/Makefile.am
- scripts/ci/run-jenkins.sh
- scripts/ci/run-test-testing_aot_full_interp.sh
For now, run the runtime suite and a few bcl tests.
> [ci] Add jenkins script for testing fullaot + interp

- mono/mini/interp/transform.c
Backport of #11528.
/cc @lewurm 
Description:
> [2018-08] [interp] transform delegate invoke in method body too

- mono/mini/interp/transform.c
Backport of #11528.
/cc @lewurm 
Description:
> [2018-06] [interp] transform delegate invoke in method body too

- mono/mini/interp/transform.c
Backport of #11528.
/cc @lewurm 
Description:
> [2018-10] [interp] transform delegate invoke in method body too

- sdks/ios/appbuilder/appbuilder.cs
.NET resource assemblies live in subdirectories named after the culture of the resource. We need to package these assemblies too.
Addresses https://github.com/mono/mono/pull/11547#issuecomment-435688914
> [ios sdk] Package resource assemblies into app bundle

- mono/mini/aot-compiler.c
> [runtime] Fix llvm arm autodetection / fix build

- mcs/class/corlib/Test/System.Resources/ResourceManagerTest.cs
- sdks/android/Makefile
- sdks/android/app/src/main/java/org/mono/android/AndroidRunner.java
- sdks/android/managed/main.cs
Follow up to https://github.com/mono/mono/pull/11575 for android
> [android sdk] Package resource assemblies into app bundle

- mcs/build/common/Consts.cs.in
- mcs/class/System/Assembly/AssemblyInfo.cs
- mcs/class/System/System.csproj
- mcs/class/System/common.sources
- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
implementation code in mscorlib
/cc @alexischr
> [corlib] Move Stack and Queue to mscorlib as we want to used them by

- scripts/ci/run-jenkins.sh
- sdks/Make.config.sample
> [sdks] Document one more build setting

- mcs/class/corlib/System.Reflection/EventInfo.cs
> [corlib] Removes dead code from EventInfo

- mono/mini/arrays.cs
- mono/mini/interp/interp.c
Fixes https://github.com/mono/mono/issues/11603.
> [interp] Add a null check to MINT_LDELEMA.

- .github/CODEOWNERS
> More codeowners updates

- mono/mini/m2n-gen.cs
- mono/mini/wasm_m2n_invoke.g.h
Mentioned by a user here: https://github.com/mono/mono/issues/8711#issuecomment-437638741
> [wasm] add DDI signature to managed2native transitions

- mono/mini/aot-runtime.c
mentioned here: https://github.com/mono/mono/issues/8430#issuecomment-437041383
> [arm] fix --enable-minimal=aot build

- mono/mini/interp/transform.c
> [interp] Small fixes

- mcs/class/Makefile
- mcs/class/System/System.IO.Compression/DeflateStream.cs
- mcs/class/System/System.Net.NetworkInformation/NetworkChange.cs
- mono/metadata/Makefile.am
- mono/metadata/empty.c
- mono/metadata/icall-def.h
- mono/metadata/icall.c
- scripts/ci/run-jenkins.sh
- sdks/android/Makefile
- sdks/ios/Makefile
- sdks/ios/appbuilder/appbuilder.cs
Backport of https://github.com/mono/mono/pull/11599
> [sdks] Compile support/{zlib-helper,nl}.c so XI/XM/XA does not have to cherry-pick them

- mono/metadata/mono-debug.c
Backport of #11672.
/cc @luhenry @vargaz
> [2018-10] [runtime] Fix the size calculation in mono_debug_add_method ().

- mono/metadata/mono-debug.c
Backport of #11672.
/cc @luhenry @vargaz
> [2018-08] [runtime] Fix the size calculation in mono_debug_add_method ().

- mono/mini/builtin-types.cs
- mono/mini/interp/transform.c
discovered when running https://github.com/Clancey/gMusic
> [interp] attempt to intrinsify again after a method is resolved regarding generics

- mono/mini/builtin-types.cs
- mono/mini/interp/transform.c
discovered when running https://github.com/Clancey/gMusic
Backport of #11712.
> [2018-08] [interp] attempt to intrinsify again after a method is resolved regarding generics

- mcs/class/System.Windows.Forms/System.Windows.Forms/GridEntry.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms_test.dll.sources
- mcs/class/System.Windows.Forms/Test/System.Windows.Forms/PropertyGrid_GridEntryTest.cs
> [WinForms] Matching Mono PropertyGrid behaviour with .Net one

- mono/mini/builtin-types.cs
- mono/mini/interp/transform.c
discovered when running https://github.com/Clancey/gMusic
Backport of #11712.
> [2018-10] [interp] attempt to intrinsify again after a method is resolved regarding generics

- mono/mini/builtin-types.cs
- mono/mini/interp/transform.c
discovered when running https://github.com/Clancey/gMusic
Backport of #11712.
> [2018-06] [interp] attempt to intrinsify again after a method is resolved regarding generics

- mcs/class/corlib/Makefile
- mcs/class/corlib/Test/System.Runtime.Serialization.Formatters.Binary/VersionTolerantSerialization/BinarySerializationOverVersionsTest.cs
- mcs/tools/mono-helix-client/MainlineTests.cs
- scripts/ci/run-test-helix.sh
Missed those while converting the tests to Helix.
> [bcl] Add missed Helix tests for vts tests and System.Web.Extensions-standalone

- mcs/class/corlib/Test/System/TypeTest.cs
- mono/metadata/icall.c
> [reflection] Make t.MakeByRefType().IsByRefLike == False

- mcs/tools/linker/wasm-linked-size.csv
Size Diff: https://jenkins.mono-project.com/job/test-mono-mainline-bclsize/143/BCL_20Size_20Diff/
Commits since last run: f63d97d...765f462bb435495ed3f421b9b78773b1a0bae986
> [bcl] Update BCL Linked Size

- mono/mini/interp/interp.c
> [2018-06] [interp] Don\u0027t throw exception on -1 division

- mono/mini/mini-trampolines.c
> [2018-06][mini] use AOT trampolines in interp mixed mode

- mono/mini/mini-runtime.c
Fixes crash in corlib suite on fullaotinterp
> [runtime] Check for error to prevent overwrites

- mcs/class/System.Web.Services/testing_aot_full_interp_System.Web.Services_test.dll.exclude.sources
- scripts/ci/run-test-testing_aot_full_interp.sh
> [interp] Enable System.Web.Services tests on fullaotinterp

- configure.ac
> [arm] Add enough trampolines for fullaotinterp mode

- mono/mini/interp/transform.c
> [interp] Fix interp inline

- mcs/class/System.XML/Test/System.Xml/XmlConvertTests.cs
- scripts/ci/run-test-testing_aot_full_interp.sh
> [interp] Enable System.Xml tests

- docs/Makefile.am
- mcs/build/rules.make
>  [build] Fixes documentation build broken by #9833

- mcs/class/corlib/Test/System.Text/EncodingTest.cs
> [2018-10] Fix Encoding serialization issue

- configure.ac
- mcs/class/corlib/testing_aot_full_interp_corlib_test.dll.exclude.sources
- scripts/ci/run-test-testing_aot_full_interp.sh
> [tests] More test updates for interp/fullaotinterp

- mcs/tools/linker/Makefile
- mcs/tools/linker/Tests/System.Core/test-plinq-01.cs
- sdks/wasm/packager.cs
> [tools] Update linker arguments

- mcs/tools/mkbundle/mkbundle.cs
> [mkbundle] Delete target directory if it exists before downloading runtime

- configure.ac
If you are new to contributing to Mono, please try to do your best at conforming to our coding guidelines http://www.mono-project.com/community/contributing/coding-guidelines/ but don't worry if you get something wrong. One of the project members will help you to get things landed.
Does your pull request fix any of the existing issues? Please use the following format: Fixes #issue-number
-->
> <!-- Thank you for your Pull Request!

- configure.ac
Every user puts one on and the result does not work.
> Remove extra percent from GSIZE_FORMAT.

- packaging/Windows/defs/mono
- packaging/Windows/defs/mono64
- scripts/ci/run-jenkins.sh
Let's not merge this until we see what Jenkins thinks about the whole thing. There's a slight element of confusion around CMake - Cygwin CMake can't generate .vcxproj files, and which CMake you get given seems a bit non-obvious
> [Win32] Enable BTLS in Windows builds

- mono/metadata/marshal.c
Only   mono_array_to_byte_byvalarray and mono_byvalarray_to_byte_array are used.
> Remove mono_array_to_byvalarray      and mono_byvalarray_to_array.

- mono/metadata/w32file-unix.c
https://github.com/mono/mono/issues/11936
> Cleanup boehm/dlopen per https://github.com/mono/mono/pull/11853#discussion_r238861650.

- mono/tests/libtest.c
- mono/tests/libtest.cpp
- mono/tests/pinvoke2.cs
- msvc/libtest.vcxproj
- msvc/libtest.vcxproj.filters
```
CC       libtest_la-libtest.lo
<inline asm>:37:2: error: instruction requires: Not 64-bit mode
popl %eax
^
```
Same error many times.
> Fix cross compile of libtest.

- acceptance-tests/SUBMODULES.json
- mcs/class/corlib/Test/System.IO/TextWriterTest.cs
- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
- mcs/class/corlib/corlib_xtest.dll.sources
> [corlib] Import System.IO.TextWriter/StreamWriter from CoreFX

- mcs/class/corlib/Test/System.Reflection/ParameterInfoTest.cs
- mcs/class/referencesource/mscorlib/system/attribute.cs
Fixes https://github.com/mono/mono/issues/12069
> Fix IndexOutOfRangeException in MethodInfo.ReturnParameter.IsDefined(type)

- mono/utils/mono-merp.c
Fixes https://github.com/mono/mono/issues/11921
> [crash] Fix reported utf encoding

- packaging/MacSDK/nuget.py
> [2018-08] [MacSDK] Bump NuGet to 4.8.1

- packaging/MacSDK/nuget.py
> [2018-10] [MacSDK] Bump NuGet to 4.8.1

- packaging/MacSDK/nuget.py
> [2018-12] [MacSDK] Bump NuGet to 4.8.1

- packaging/MacSDK/nuget.py
> [MacSDK] Bump NuGet to 4.8.1

- mcs/class/System.Drawing/System.Drawing/Graphics.cs
ystem.Exception: Generic Error [GDI+ status: GenericError]
at System.Drawing.GDIPlus.CheckStatus (System.Drawing.Status status) [0x00079] in <bb99ab19679c4cf79f4136bd0faf8b5e>:0 
at System.Drawing.Graphics.FillRectangle (System.Drawing.Brush brush, System.Int32 x, System.Int32 y, System.Int32 width, System.Int32 height) [0x00025] in <bb99ab19679c4cf79f4136bd0faf8b5e>:0 
at System.Drawing.Graphics.FillRectangle (System.Drawing.Brush brush, System.Drawing.Rectangle rect) [0x0002c] in <bb99ab19679c4cf79f4136bd0faf8b5e>:0 
at (wrapper remoting-invoke-with-check) System.Drawing.Graphics.FillRectangle(System.Drawing.Brush,System.Drawing.Rectangle)
at System.Windows.Forms.Control.PaintControlBackground (System.Windows.Forms.PaintEventArgs pevent) [0x002ff] in <69ecb40f27a1431a99620933ba9a8b39>:0 …
> Update Graphics to find err

- acceptance-tests/SUBMODULES.json
Brings in disabling of the ThreadLocalTests.RunThreadLocalTest8_Values_NegativeCases test (https://github.com/xamarin/ms-test-suite/pull/3)
> Bump ms-test-suite

- mcs/class/Facades/subdirs.make
- mcs/tools/mono-helix-client/Makefile
- runtime/mono-test.sh
They added retry logic inside of the SDK to deal with some expected Helix API responses.
> Update Helix SDK to latest version

- packaging/MacSDK/msbuild.py
> [2018-12] Bump msbuild to track xplat-master

- packaging/MacSDK/msbuild.py
> [2018-08] Bump msbuild to track xplat-master

- mono/mini/mini-codegen.c
- mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/12131.
> [2018-08] [llvm] Add support for OP_RCNEQ.

- sdks/README.md
- sdks/wasm/Makefile
- sdks/wasm/README.md
> [wasm] Update build docs

- mono/metadata/handle.h
- mono/metadata/threads.c
https://jenkins.mono-project.com/job/test-mono-pull-request-acceptance-tests/11767/parsed_console/log.html
ves_icall_System_Threading_WaitHandle_Wait_internal_raw USED 107 handles
> Do not build up indefinite coop handles in loops.

- mono/mini/mini-llvm.c
- mono/mini/mini.c
> [llvm] Remove the linkonce code, its not used anymore.

- configure.ac
- mcs/class/corlib/Mono/Runtime.cs
- mono/metadata/icall-def.h
- mono/metadata/icall.c
- mono/tests/merp-json-valid.cs
- mono/utils/mono-merp.c
- mono/utils/mono-merp.h
Fixes https://github.com/mono/mono/issues/11579
> [crash] Support extra merp params

- mono/utils/mono-threads-state-machine.c
* Fix bug in `pulse` transition - the suspend count was lost and incorrectly
swapped to 0.
* `finish_async_suspend` transition - add assertions that the suspend count is
positive. Try to catch incorrect states sooner.
Fixes https://github.com/mono/mono/issues/12235
> [coop] Make sure suspend_count is positive in suspend request states

- mono/utils/mono-threads-state-machine.c
* Fix bug in pulse transition - the suspend count was lost and incorrectly
swapped to 0.
* finish_async_suspend transition - add assertions that the suspend count is
positive. Try to catch incorrect states sooner.
Fixes https://github.com/mono/mono/issues/12235
Backport of #12241 to `2018-10`
> [2018-10] [coop] Make sure suspend_count is positive in suspend request states

- mono/metadata/sgen-mono-ilgen.c
> [sgen] Fix debug build

- mcs/class/System/System.csproj
- mcs/class/System/monodroid_System.dll.sources
- mcs/class/System/unix_net_4_x_System.dll.sources
- mcs/class/corlib/System.IO/FileSystem.NotSupported.cs
- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/unix_build_corlib.dll.sources
Fixes https://github.com/mono/mono/issues/11635.
Main changes are in https://github.com/mono/corefx/pull/225.
Some initial work was done in https://github.com/mono/mono/pull/11945
The idea is to share CFRunLoop for FSEventStreams.
> Fixing FileSystemWatcher problem in VSMac

- configure.ac
- mcs/class/corlib/Mono/Runtime.cs
- mcs/class/corlib/Test/System/ExceptionTest.cs
- mono/metadata/icall-def.h
- mono/metadata/icall.c
- mono/metadata/threads.c
- mono/mini/mini-posix.c
- mono/tests/Makefile.am
- mono/tests/merp-json-valid.cs
- mono/utils/mono-merp.c
- mono/utils/mono-merp.h
- mono/utils/mono-state.c
- mono/utils/mono-state.h
- mono/utils/mono-threads-debug.h
This contains the fixes and tests I'm going to call "service pack 1" for ease of grouping
#11884
#11855
#11636
#11909
#12036
> [2018-08] [merp] Batch of fixes

- mcs/class/System.Windows.Forms/System.Windows.Forms/StatusBar.cs
- mcs/class/System.Windows.Forms/Test/System.Windows.Forms/StatusBarTest.cs
This change implements disposing of the panels of a status bar.
>  [swf] Fix dispose of panels in StatusBar

- mono/mini/ee.h
- mono/mini/interp-stubs.c
- mono/mini/interp/interp-internals.h
- mono/mini/interp/interp.c
- mono/mini/mini-exceptions.c
- mono/mini/mixed.cs
- mono/tests/Makefile.am
- mono/tests/exception21.cs
Backport of https://github.com/mono/mono/pull/12092 + https://github.com/mono/mono/pull/12328
> [2018-12] Fix interp eh backport

- configure.ac
- mcs/class/corlib/Mono/Runtime.cs
- mcs/class/corlib/Test/System/ExceptionTest.cs
- mono/metadata/icall-def.h
- mono/metadata/icall.c
- mono/metadata/threads.c
- mono/mini/mini-exceptions.c
- mono/tests/Makefile.am
- mono/tests/merp-json-valid.cs
- mono/utils/mono-merp.c
- mono/utils/mono-merp.h
- mono/utils/mono-state.c
- mono/utils/mono-state.h
- mono/utils/mono-threads-debug.h
This contains the fixes and tests I'm going to call "service pack 1" for ease of grouping
https://github.com/mono/mono/pull/11884
https://github.com/mono/mono/pull/11855
https://github.com/mono/mono/pull/11636
https://github.com/mono/mono/pull/11909
https://github.com/mono/mono/pull/12036
> [2018-06] [merp] Batch of fixes

- mono/utils/mono-threads-state-machine.c
* Fix bug in `pulse` transition - the suspend count was lost and incorrectly
swapped to 0.
* `finish_async_suspend` transition - add assertions that the suspend count is
positive. Try to catch incorrect states sooner.
Fixes https://github.com/mono/mono/issues/12235
Backport of #12241.
> [2018-12] [coop] Make sure suspend_count is positive in suspend request states

- configure.ac
> Fix cross compile issue introduced in 5.16

- mcs/class/corlib/testing_aot_full_interp_corlib.dll.exclude.sources
- mcs/class/corlib/testing_aot_full_interp_corlib.dll.sources
- mcs/class/corlib/testing_aot_full_interp_llvm_corlib.dll.exclude.sources
- mcs/class/corlib/testing_aot_full_interp_llvm_corlib.dll.sources
> [fullaotinterp/fullaotinterp_llvm] Use CoreFX System.IO

- configure.ac
- mono/metadata/Makefile.am
- mono/metadata/appdomain.c
- mono/mini/Makefile.am.in
- mono/mini/main-core.c
- netcore/sample/HelloWorld/HelloWorld.csproj
- netcore/sample/HelloWorld/Program.cs
- netcore/sample/Makefile
- netcore/sample/README.md
Initial pass on settings this up (it works but using system Mono assemblies only)
Naming nitpicks are welcomed ;-)
> [build] Add dotnet launcher bridge to the runtime

- tools/offsets-tool/MonoAotOffsetsDumper.cs
Backport of: https://github.com/mono/mono/commit/eebe4b52857140ba9dea872c6249960273d222f2 from https://github.com/mono/mono/pull/12454
The latest Android NDK releases no longer ship with per-platform C headers.
Instead they ship with a set of unified headers and require the presence of the
`__ANDROID_API__` macro in order to select the target platform.
The AOT offset dumper doesn't support this new layout and this commit changes
that by adding support for the unified headers (without removing support for the
older NDKs) thus fixing the following error when trying to dump the offsets with
newer NDK:
Processing triple: aarch64-v8a-linux-android
Error parsing '[...]/mono/mono/metadata/metadata-cross-helpers.c'
[...]/mono/mono/metadata/metadata-cross-helpers.c(5,10): fatal: 'stdio.h' file not …
> [2018-08 Android,AOT] Support dumping AOT offsets with Android NDK r17+ (#12454)

- mono/metadata/mono-route.h
- mono/mini/mini-amd64.h
- mono/mini/mini-arm64.h
- mono/native/pal-icalls.c
- mono/utils/mono-context.h
- mono/utils/mono-threads-mach.c
- sdks/builds/ios.mk
- support/serial.c
Fixes https://github.com/mono/mono/issues/11697
> [tvOS] cleanup defines for tvOS

- mcs/class/System/Mono/SystemDependencyProvider.cs
Fix race condition in `SystemDependencyProvider.Initialize()`.
Fixes #12538.
> [System]: Fix race condition in `SystemDependencyProvider.Initialize()`.  #12538.

- mono/utils/memfuncs.c
When doing array copy of 16+ GB.
> [utils] Fix potential overflow

- mcs/class/corlib/ReferenceSources/AppContextDefaultValues.cs
- mcs/class/corlib/ReferenceSources/CultureData.cs
- mcs/class/corlib/Test/System.Globalization/CalendarTest.cs
- mcs/class/corlib/Test/System.Globalization/DateTimeFormatInfoTest.cs
- mcs/class/referencesource/mscorlib/system/AppContext/AppContextSwitches.cs
- mcs/class/referencesource/mscorlib/system/globalization/gregoriancalendarhelper.cs
Adaptation of related changes made in dotnet/coreclr.
Requires https://github.com/mono/corefx/pull/240.
Fixes https://github.com/mono/mono/issues/12300.
> Japanese calendar era change

- mcs/class/System.Net.Http/CFNetworkHandler.cs
The handler receive an `Open` and the a `Close` event but never a
`DataAvailable` event.
So it _hangs_ if only a `200` status is received (since the headers
are not considered _data_) received from the web server.
This is because some initialization only occurs inside
`HandleHasBytesAvailableEvent` which is now called, on `Close`,
to ensure the initialization is done before completing the request.
This, along with a cancellation check, makes the test case from
https://github.com/xamarin/xamarin-macios/issues/5190 work properly
with this handler.
Fixes https://github.com/xamarin/xamarin-macios/issues/5289
> [System.Net.Http] Fix CFNetworkHandler when no data is sent

- mono/utils/mono-dl.c
The netcore native libs are named System.Native.dylib etc. so they don't have the
lib prefix. Add a case for it.
> [runtime] Reorganize mono_dl_build_path () a bit, add a new case for netcore.

- mono/utils/mono-dl.c
> [runtime] Fix #ifdef NETCORE.

- mcs/class/System/System.IO/DefaultWatcher.cs
https://github.com/mono/monodevelop/issues/6898
Not sure if it's the root of the problem but it surely fixes the dead lock on my machine.
> Fixes VS4Mac Issue #6898

- mcs/class/System.Windows.Forms/Makefile
- mcs/class/System.Windows.Forms/samples/issue12402.cs
> Add sample from issue #12402.

- mono/mini/debugger-agent.c
- mono/mini/debugger-engine.h
- mono/mini/mini-wasm-debugger.c
- sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs
- sdks/wasm/library_mono.js
Implemented mono_wasm_get_object_properties to watch object in wasm.
> [Wasm][Debugger] Object inspection.

- mono/metadata/marshal-ilgen.c
- mono/tests/marshal2.cs
Fixes #12568
.NET seems to support this functionality.
> Implement marshaling for generic struct fields

- mono/native/pal_config.h
> [android] Fix inaccurate detection of sendfile()

- mcs/class/System.Net.Http/CFNetworkHandler.cs
* [Network] Fix CVE 2018-8292 on Mac OS X.
* No need to close the obc, it can be reused.
* Small typo.
* Fix error while chaging the request :/
* Minor style changes.
> [2018-04] [Network] Fix CVE 2018-8292 on Mac OS X. (#12153)

- mcs/class/System.Private.CoreLib/System.Runtime.InteropServices/Marshal.cs
> [System.Private.CoreLib] Fix the build

- configure.ac
Fixes #9951 
Backport of #12267.
/cc @alexischr @ShonkyCH
> [2018-10] Fix cross compile issue introduced in 5.16

- packaging/MacSDK/libgdiplus.py
> Bump libgdiplus to mono-2018-12 branch tip

- configure.ac
Fixes #9951 
Backport of #12267.
/cc @alexischr @ShonkyCH
> [2018-12] Fix cross compile issue introduced in 5.16

- mcs/class/corlib/Test/System.Diagnostics/StackFrameTest.cs
Disable test GetFrames_AsynsCalls for wasm only.
> [wasm][tests]Disable test GetFrames_AsynsCalls for wasm only.

- mono/mini/interp/interp.c
> [2019-02] [interp] Add missing write barrier

- mono/metadata/class-init.c
- mono/metadata/class.c
- mono/metadata/metadata-internals.h
- mono/metadata/metadata.c
- mono/tests/Makefile.am
- mono/tests/bug-10834.cs
Fixes #10834 and #12690 
Backport of #10962.
> [2018-10] [runtime] Properly inflate cmods of (m)var.

- mono/mini/mini-wasm-debugger.c
Evaluate properties and generics.
> [wasm][debugger] Evaluate properties and generics.

- scripts/ci/run-test-interpreter.sh
- scripts/ci/run-test-testing_aot_full_interp.sh
- scripts/ci/run-test-testing_aot_full_interp_llvm.sh
> [tests] Enable test suite on interpreter

- mcs/tools/wasm-tuner/tuner.cs
- sdks/wasm/driver.c
> [wasm] Fix icall table linking, generate one table per assembly.

- mono/metadata/marshal.c
- mono/mini/interp/interp-internals.h
- mono/mini/interp/transform.c
- mono/tests/Makefile.am
- mono/tests/dynamic-method-delegate.cs
> [2019-02] [metadata] Fix dynamic delegate

- scripts/ci/run-jenkins.sh
- sdks/wasm/Makefile
- sdks/wasm/packager.cs
> [wasm] Add mixed tests to CI.

- netcore/sample/Makefile
> [netcore] Update to the latest version

- configure.ac
- mono/mini/driver.c
- mono/utils/mono-context.h
- sdks/builds/.gitignore
- sdks/builds/ios.mk
- tools/offsets-tool/MonoAotOffsetsDumper.cs
work in progress, the resulting crosswatch64_32 aot compiler doesn't work yet.
> [ios] add crosswatch64_32 target

- sdks/wasm/README.md
- sdks/wasm/debug.html
Small updates to documentation and debug sample in sdks/wasm
> [WASM] debug documentation and sample updates

- mcs/class/Mono.Cecil/Mono.Cecil.csproj
- mcs/tools/mono-symbolicate/mono-symbolicate.csproj
> [2019-02] Bump cecil submodule

- mcs/class/Mono.Cecil/Mono.Cecil.csproj
- mcs/tools/mono-symbolicate/mono-symbolicate.csproj
> [2018-10] Bump cecil submodule

- mcs/class/Mono.Cecil/Mono.Cecil.csproj
- mcs/tools/mono-symbolicate/mono-symbolicate.csproj
> [2018-12] Bump cecil submodule

- configure.ac
- mono/mini/driver.c
- mono/utils/mono-context.h
- sdks/builds/.gitignore
- sdks/builds/ios.mk
- tools/offsets-tool/MonoAotOffsetsDumper.cs
work in progress, the resulting crosswatch64_32 aot compiler doesn't work yet.
Backport of #12893.
> [2018-12] [ios] add crosswatch64_32 target

- configure.ac
- mono/mini/driver.c
- mono/utils/mono-context.h
- sdks/builds/.gitignore
- sdks/builds/ios.mk
- tools/offsets-tool/MonoAotOffsetsDumper.cs
work in progress, the resulting crosswatch64_32 aot compiler doesn't work yet.
Backport of #12893.
> [2019-02] [ios] add crosswatch64_32 target

- mcs/class/corlib/Test/System/ExceptionTest.cs
- mcs/tools/upload-to-sentry/UploadToSentry.cs
- mono/metadata/object-internals.h
- mono/metadata/threads-types.h
- mono/mini/mini-exceptions.c
- mono/utils/mono-state.c
- mono/utils/mono-state.h
> [crash] Add more detailed reporting for exceptions

- mono/mini/mini-arm.c
consider
```csharp
struct S3
{
public ushort X;
public ushort Y;
public ushort Z;
}
```
this would be 3 * 2 = 6 bytes. Structs, however, are passed around as i32
arrays in LLVM IR between functions. Those, if such a struct is passed, are
split to `int32`s depending on the struct's size. The previous calulation was
wrongly reserving one such i32 slot instead of two for `S3` above.
Additionally increase slot size to i64 so that it aligns with a
slightly different ABI on arm64_32.
Fixes https://github.com/mono/mono/issues/8486
@rolfbjarne I've tested it on a arm64_32 device, please confirm that this fixes the issue on your armv7k device as well
> [bitcode] round up value type size for slot calculation

- configure.ac
- llvm/Makefile.am
- mcs/build/library.make
- mcs/build/rules.make
- mono/mini/Makefile.am.in
- mono/mini/aot-compiler.c
- scripts/ci/run-jenkins.sh
- scripts/ci/run-test-testing_aot_bitcode.sh
- scripts/ci/run-test-testing_aot_bitcode_interp.sh
Backport of #12970.
/cc @akoeplinger @luhenry
> [2019-02] [ci] Fix Linux x64 Bitcode job

- mcs/class/corlib/Test/System/ExceptionTest.cs
- mcs/tools/upload-to-sentry/UploadToSentry.cs
- mono/metadata/object-internals.h
- mono/metadata/threads-types.h
- mono/mini/mini-exceptions.c
- mono/utils/mono-state.c
- mono/utils/mono-state.h
Backport of #12946.
/cc @luhenry @alexanderkyte
> [2018-12] [crash] Add more detailed reporting for exceptions

- mcs/class/corlib/Test/System/ExceptionTest.cs
- mcs/tools/upload-to-sentry/UploadToSentry.cs
- mono/metadata/object-internals.h
- mono/metadata/threads-types.h
- mono/mini/mini-exceptions.c
- mono/utils/mono-state.c
- mono/utils/mono-state.h
Backport of #12946.
/cc @luhenry @alexanderkyte
> [2019-02] [crash] Add more detailed reporting for exceptions

- autogen.sh
- mcs/class/Mono.Messaging.RabbitMQ/Makefile
- mcs/class/Mono.Messaging/Makefile
- mcs/class/System.ComponentModel.Composition.4.5/xammac_net_4_5_System.ComponentModel.Composition_xtest.dll.exclude.sources
- mcs/class/System.Messaging/Makefile
- mcs/class/System.Runtime.Serialization/Makefile
- mcs/class/System.Runtime.Serialization/xammac_net_4_5_System.Runtime.Serialization_test.dll.exclude.sources
- mcs/class/System.Runtime.Serialization/xammac_net_4_5_System.Runtime.Serialization_xtest.dll.exclude.sources
- mcs/class/System.ServiceModel.Web/xammac_net_4_5_System.ServiceModel.Web_test.dll.exclude.sources
- mcs/class/System.Web.Services/xammac_net_4_5_System.Web.Services_test.dll.exclude.sources
- mcs/class/System.XML/Makefile
- scripts/ci/run-jenkins.sh
- sdks/Make.config.sample
- sdks/builds/.gitignore
- sdks/builds/Makefile
- sdks/builds/android.mk
- sdks/builds/bcl.mk
- sdks/builds/ios.mk
- sdks/builds/mac.mk
- sdks/builds/runtime.mk
- sdks/builds/wasm.mk
- sdks/paths.mk
Backport of #12959.
/cc @luhenry
> [2018-12] [sdks] Add mac-{mac32,mac64} targets

- autogen.sh
- mcs/class/Mono.Messaging.RabbitMQ/Makefile
- mcs/class/Mono.Messaging/Makefile
- mcs/class/System.ComponentModel.Composition.4.5/xammac_net_4_5_System.ComponentModel.Composition_xtest.dll.exclude.sources
- mcs/class/System.Messaging/Makefile
- mcs/class/System.Runtime.Serialization/Makefile
- mcs/class/System.Runtime.Serialization/xammac_net_4_5_System.Runtime.Serialization_test.dll.exclude.sources
- mcs/class/System.Runtime.Serialization/xammac_net_4_5_System.Runtime.Serialization_xtest.dll.exclude.sources
- mcs/class/System.ServiceModel.Web/xammac_net_4_5_System.ServiceModel.Web_test.dll.exclude.sources
- mcs/class/System.Web.Services/xammac_net_4_5_System.Web.Services_test.dll.exclude.sources
- mcs/class/System.XML/Makefile
- scripts/ci/run-jenkins.sh
- sdks/Make.config.sample
- sdks/builds/.gitignore
- sdks/builds/Makefile
- sdks/builds/android.mk
- sdks/builds/bcl.mk
- sdks/builds/ios.mk
- sdks/builds/mac.mk
- sdks/builds/runtime.mk
- sdks/builds/wasm.mk
- sdks/paths.mk
Backport of #12959.
/cc @luhenry
> [2019-02] [sdks] Add mac-{mac32,mac64} targets

- mcs/tools/linker/Makefile
> [WASM] Add some blazor binaries to bcl-size-diff

- scripts/ci/run-jenkins.sh
- Chakra install fails: https://github.com/Microsoft/ChakraCore/issues/5945
> [wasm][CI] Reactivate Chakra tests in CI

- mono/mini/mini-arm.c
consider
```csharp
struct S3
{
public ushort X;
public ushort Y;
public ushort Z;
}
```
this would be 3 * 2 = 6 bytes. Structs, however, are passed around as i32
arrays in LLVM IR between functions. Those, if such a struct is passed, are
split to `int32`s depending on the struct's size. The previous calulation was
wrongly reserving one such i32 slot instead of two for `S3` above.
Additionally increase slot size to i64 so that it aligns with a
slightly different ABI on arm64_32.
Fixes https://github.com/mono/mono/issues/8486
@rolfbjarne I've tested it on a arm64_32 device, please confirm that this fixes the issue on your armv7k device as well
Backport of #12992.
/cc @lewurm
> [2018-12] [bitcode] round up value type size for slot calculation

- mcs/class/corlib/Test/System/ExceptionTest.cs
- mono/metadata/object-internals.h
- mono/metadata/threads-types.h
- mono/mini/mini-exceptions.c
- mono/utils/mono-state.c
- mono/utils/mono-state.h
Backport of #12946.
/cc @luhenry @alexanderkyte
> [2018-08] Add more detailed reporting for exceptions 

- mcs/class/corlib/Test/System/ExceptionTest.cs
- mono/metadata/object-internals.h
- mono/metadata/threads-types.h
- mono/mini/mini-exceptions.c
- mono/utils/mono-state.c
- mono/utils/mono-state.h
Backport of #12946.
/cc @luhenry @alexanderkyte
> [2018-10]  Add more detailed reporting for exceptions

- mono/mini/mini-arm.c
consider
```csharp
struct S3
{
public ushort X;
public ushort Y;
public ushort Z;
}
```
this would be 3 * 2 = 6 bytes. Structs, however, are passed around as i32
arrays in LLVM IR between functions. Those, if such a struct is passed, are
split to `int32`s depending on the struct's size. The previous calulation was
wrongly reserving one such i32 slot instead of two for `S3` above.
Additionally increase slot size to i64 so that it aligns with a
slightly different ABI on arm64_32.
Fixes https://github.com/mono/mono/issues/8486
@rolfbjarne I've tested it on a arm64_32 device, please confirm that this fixes the issue on your armv7k device as well
Backport of #12992.
/cc @lewurm
> [2019-02] [bitcode] round up value type size for slot calculation

- mcs/tools/linker/monolinker.csproj
- mcs/tools/linker/monolinker.exe.sources
> [2019-02] Bump linker submodule to latest master

- mono/mini/gshared.cs
- mono/mini/intrinsics.c
- mono/mini/method-to-ir.c
- mono/mini/mini-generic-sharing.c
- mono/mini/mini.h
> [jit] Add a few more unsafe intrinsics.

- man/mono.1
- mono/mini/driver.c
> [2019-02] [mcs] Remove doc about CAS security

- mcs/class/System.Core/winaot_System.Core_test.dll.exclude.sources
- mcs/class/System.Core/winaot_System.Core_test.dll.sources
- mcs/class/System.Web.Services/winaot_System.Web.Services_test.dll.exclude.sources
- mcs/class/System.Web.Services/winaot_System.Web.Services_test.dll.sources
- mcs/tools/linker/Makefile
- runtime/Makefile.am
> Remaining fixes needed to pass rest of CI test suites for windows x64 full AOT.

- scripts/ci/run-test-winaot.sh
> Enable all CI test suites for Windows x64 full AOT.

- mono/tests/libtest.c
To match pinvoke signature from pinvoke-2 test.
> [tests] Fix function signature

- mono/metadata/metadata.c
- mono/mini/mini-runtime.c
- mono/utils/mono-state.c
Compiled with gcc 8.2.0/x86_64-linux-gnu.
> Fix some compiler warnings

- mono/mini/aot-runtime.c
We need the recently introduced "unbox arbitrary" trampolines in one more
scenario: non-mscorlib AOT code calls a method from mscorlib with
interpreter. Before we just relied on the amodule not being available,
but mscorlib amodule is always present due to wrappers, trampolines,
etc.
> [aot] use unbox arbitrary trampolines for "slim" mscorlib

- mono/mini/aot-compiler.c
> [aot] add wrappers to "slim" mscorlib (i.e. --aot=interp)

- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
Backport of https://github.com/mono/mono/pull/13137 & https://github.com/mono/mono/pull/13139
> [2018-12] AOT fixes for interp mixed mode

- mono/mini/aot-compiler.c
- mono/mini/aot-runtime.c
Backport of https://github.com/mono/mono/pull/13137 & https://github.com/mono/mono/pull/13139
> [2018-10] AOT fixes for interp mixed mode

- scripts/ci/run-jenkins.sh
- sdks/wasm/tests/browser/karma.conf.js
- sdks/wasm/tests/browser/package.json
- Runs a series of tests against the HttpClientHandler and blob.
> [wasm] Add browser test suite.

- mono/mini/aot-runtime.c
We need the recently introduced "unbox arbitrary" trampolines in one more
scenario: non-mscorlib AOT code calls a method from mscorlib with
interpreter. Before we just relied on the amodule not being available,
but mscorlib amodule is always present due to wrappers, trampolines,
etc.
Backport of #13139.
/cc @lewurm
> [2019-02] [aot] use unbox arbitrary trampolines for \u0022slim\u0022 mscorlib

- scripts/ci/run-jenkins.sh
> [wasm] Disable chakra tests until its fixed.

- mono/metadata/class-init.c
- mono/metadata/loader.c
- mono/mini/interp/transform.c
- mono/mini/method-to-ir.c
- mono/tests/Makefile.am
- mono/tests/dim-constrained3.il
- mono/tests/dim-constrained3_gm.il
- mono/tests/dim-constrainedcall.il
> [runtime] Default Interface method fixes.

- mono/mini/arrays.cs
- mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/10101.
> [jit] Fix the class of the stack entry for ldelema, it should be the class not its element class.

- mono/mini/interp/transform.c
See https://github.com/mono/mono/pull/13177#discussion_r259872514
> [interp] fix conflict of #13154 and #13177

- mono/mini/interp/interp.c
- mono/mini/mixed.cs
Otherwise we smash the stack.
Contributes to https://github.com/xamarin/xamarin-macios/issues/5622
Backport of #13216.
/cc @lewurm
> [2018-10] [interp] compute size of generic valuetype correctly

- mono/native/pal_config.h
Backport of #12695.
/cc @alexischr
> [2019-02] [android] Fix inaccurate detection of sendfile()

- mcs/class/System.Net.Http/Makefile
- mcs/class/System.Net.Http/NSUrlSessionHandler.cs
- mcs/class/System.Net.Http/RuntimeOptions.cs
- mcs/class/System.Net.Http/System.Net.Http.csproj
- mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs
- mcs/class/System.Net.Http/monotouch_System.Net.Http.dll.sources
- mcs/class/System.Net.Http/monotouch_tv_System.Net.Http.dll.sources
- mcs/class/System.Net.Http/monotouch_watch_System.Net.Http.dll.sources
This allows us to remove the need for a special custom System.Net.Http.dll build in the xamarin-macios repository.
Part of https://github.com/mono/mono/issues/11397
> [System.Net.Http] Move NSUrlSessionHandler from xamarin-macios to mono

- mcs/class/System.Net.Http/Makefile
- mcs/class/System.Net.Http/NSUrlSessionHandler.cs
- mcs/class/System.Net.Http/RuntimeOptions.cs
- mcs/class/System.Net.Http/System.Net.Http.csproj
- mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs
- mcs/class/System.Net.Http/monotouch_System.Net.Http.dll.sources
- mcs/class/System.Net.Http/monotouch_tv_System.Net.Http.dll.sources
- mcs/class/System.Net.Http/monotouch_watch_System.Net.Http.dll.sources
> [2019-02] [System.Net.Http] Move NSUrlSessionHandler from xamarin-macios to mono

- mono/mini/aot-compiler.c
Backport of #13137.
/cc @lewurm
> [2019-02] [aot] add wrappers to \u0022slim\u0022 mscorlib (i.e. --aot=interp)

- mono/mini/intrinsics.c
> [mini] Inline Selector.GetHandle for tvOS and watchOS assemblies as well.

- mcs/build/tests.make
- mcs/class/Makefile
- mcs/class/Mono.Debugger.Soft/Makefile
- mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft.csproj
- mcs/class/Mono.Debugger.Soft/Test/dtest-excfilter.il
- mcs/class/Mono.Debugger.Soft/Test/dtest.cs
- mcs/class/Mono.Runtime.Tests/Test/JitTests.cs
- mcs/tools/mono-symbolicate/Makefile
- mcs/tools/nunit-lite/NUnitLite/AndroidTestAssemblyRunner.cs
- scripts/ci/run-jenkins.sh
- sdks/android/.gitignore
- sdks/android/Makefile
- sdks/android/app/build.gradle
- sdks/android/app/src/main/c/runtime-bootstrap.c
- sdks/android/app/src/main/java/org/mono/android/AndroidRunner.java
- sdks/android/lldb-android.sh
- sdks/builds/android.mk
Depends on https://github.com/mono/NUnitLite/pull/20
> [android] Fix Mono.Debugger.Soft tests with Android SDKs

- mono/mini/intrinsics.c
Backport of #13246.
/cc @luhenry @rolfbjarne
> [2019-02] [mini] Inline Selector.GetHandle for tvOS and watchOS assemblies as well.

- mcs/class/System.Private.CoreLib/AssemblyInfo.cs
- mcs/class/System.Private.CoreLib/System.Reflection/Assembly.cs
- mcs/class/System.Private.CoreLib/System.Reflection/CustomAttributeExtensions.cs
- mono/metadata/appdomain.c
* Implement CustomAttributeExtensions methods.
* Add a AssemblyFileVersion attribute.
* Don't try AppDomain.TypeResolve.
> [netcore] Ongoing work.

- mono/mini/intrinsics.c
Backport of #13246.
/cc @luhenry @rolfbjarne
> [2018-10] [mini] Inline Selector.GetHandle for tvOS and watchOS assemblies as well.

- mono/mini/ee.h
- mono/mini/interp-stubs.c
- mono/mini/interp/interp.c
- mono/mini/interp/transform.c
- mono/mini/mini-runtime.c
Backport of https://github.com/mono/mono/pull/13215
> [2019-02] [interp] mixed mode fixes for delegates

- mono/metadata/object-internals.h
- mono/metadata/object.c
- mono/mini/ee.h
- mono/mini/interp-stubs.c
- mono/mini/interp/interp.c
- mono/mini/interp/transform.c
- mono/mini/mini-runtime.c
- mono/mini/mini.h
Backport of https://github.com/mono/mono/pull/13215
> [2018-10] [interp] mixed mode fixes for delegates

- mcs/class/corlib/System.Reflection.Emit/AssemblyBuilder.cs
- mcs/class/corlib/System.Reflection.Emit/ModuleBuilder.cs
> Get fully qualified name of ModuleBuilder

- mcs/class/System.ServiceModel/System.ServiceModel.Channels/HttpRequestChannel.cs
Concurrent request completions could cause following exception:
FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException:
Index was out of range. Must be non-negative and less than
the size of the collection.
Parameter name: index
at System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) [0x00009] in <4a8a0eaa024f41829d3435c07e5c7edb>:0
at System.Collections.Generic.List`1[T].Remove (T item) [0x0000c] in <4a8a0eaa024f41829d3435c07e5c7edb>:0
at System.ServiceModel.Channels.HttpRequestChannel+HttpChannelRequestAsyncResult.Cleanup () [0x00011] in <28c4695205ef47378f5370502b066592>:0
at System.ServiceModel.Channels.HttpRequestChannel+HttpChannelRequestAsyncResult.set_IsCompleted (System.Boolean value) [0x00034] in <28c4695205ef47378f5370502b066592>:0
at …
>     [System] Fix a race condition in HttpRequestChannel.

- mcs/class/corlib/LinkerDescriptor/mscorlib.xml
> [linker] Only preserve the m_value fields of the primitive types.

- mcs/class/System.Private.CoreLib/System.Runtime.CompilerServices/DependentHandle.cs
- mcs/class/System.Private.CoreLib/System/GC.cs
- mcs/class/referencesource/mscorlib/system/gc.cs
> [netcore] Implement DependentHandle using the existing ephemeron code.

- mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/12307 for 2018-08.
> [2018-08] [llvm] Emit target layout/target triple into bitcode files.

- mcs/tools/linker/Makefile
- mcs/tools/linker/Tests/System.Core/test-queryable-01.cs
- mcs/tools/linker/Tests/System.Runtime.Serialization/test-dcs-01.cs
> Linker test

- mono/mini/debugger-agent.c
Fixes https://github.com/mono/mono/issues/13261.
> [sdb] Avoid stack overflows caused by recursive calls between suspend_current () and invoke_method ().

- mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/13319.
> [jit] Avoid an assert with default interface methods and gsharing.

- mcs/tools/linker/Makefile
> Add Blazor E2E test to wasm bcl-size-diff

- man/mono.1
- mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/12182
> [AOT] add option to control arguments to llc and add fallback for x86

- mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/12307 for 2018-08.
Backport of #13327.
/cc @vargaz
> [2018-10] [llvm] Emit target layout/target triple into bitcode files.

- mono/mini/method-to-ir.c
> [jit] Reenable the EqualityComparer:Default devirt optimization.

- mcs/class/corlib/Test/System.Reflection/EventInfoTest.cs
- mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/13350
Fixes https://github.com/mono/mono/issues/10277
> Add reflected type to event methods

- sdks/wasm/framework/src/WebAssembly.Bindings/Runtime.cs
A few places in in the JS Bindings were using Dictionary.ContainsKey then immediately looking up the object, use TryGetValue instead.
> [wasm] Remove all use of ContainsKey from js bindings

- packaging/MacSDK/nuget.py
Backport of #13421.
/cc @alexischr
> [2018-08] [MacSDK] Bump Nuget to 4.8.2

- packaging/MacSDK/nuget.py
Backport of #13421.
/cc @alexischr
> [2018-10] [MacSDK] Bump Nuget to 4.8.2

- packaging/MacSDK/nuget.py
Backport of #13421.
/cc @alexischr
> [2019-02] [MacSDK] Bump Nuget to 4.8.2

- packaging/MacSDK/nuget.py
> [2018-06] [MacSDK] Bump Nuget to 4.8.2

- mcs/packages/Makefile
- mcs/tools/xbuild/Makefile
- packaging/MacSDK/fsharp.py
- packaging/MacSDK/msbuild.py
- packaging/MacSDK/patches/fsharp-msbuild-16-0.patch
- scripts/ci/run-test-mac-sdk.sh
- tools/nuget-hash-extractor/download.sh
> [msbuild] Update to track upstream vs16.0 branch

- sdks/builds/wasm.mk
> [wasm] Update to emscripten 1.38.29.

- netcore/Makefile
- netcore/excludes-System.Runtime.Tests.rsp
- netcore/sample/Makefile
* Move the sdk download from netcore/sample/Makefile to netcore/Makefile
* Add targets for running the System.Runtime.Tests test suite.
> [netcore] Add support for running tests.

- mono/mini/gshared.cs
- mono/mini/intrinsics.c
- mono/mini/method-to-ir.c
- mono/mini/mini-generic-sharing.c
- mono/mini/mini.h
Backport of #12971.
/cc @akoeplinger @vargaz
> [2019-02] [jit] Add a few more unsafe intrinsics.

- mono/utils/mono-state.c
This is helpful by allowing the crash reporter to work even while unable to write to the working directory.
> [crash] Fallback to MAP_ANONYMOUS for allocator

- mcs/class/System.ServiceModel/System.ServiceModel.Channels/HttpRequestChannel.cs
Concurrent request completions could cause following exception:
FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException:
Index was out of range. Must be non-negative and less than
the size of the collection.
Parameter name: index
at System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) [0x00009] in <4a8a0eaa024f41829d3435c07e5c7edb>:0
at System.Collections.Generic.List`1[T].Remove (T item) [0x0000c] in <4a8a0eaa024f41829d3435c07e5c7edb>:0
at System.ServiceModel.Channels.HttpRequestChannel+HttpChannelRequestAsyncResult.Cleanup () [0x00011] in <28c4695205ef47378f5370502b066592>:0
at System.ServiceModel.Channels.HttpRequestChannel+HttpChannelRequestAsyncResult.set_IsCompleted (System.Boolean value) [0x00034] in <28c4695205ef47378f5370502b066592>:0
at …
> [2019-02] [System.ServiceModel] Fix a race condition in HttpRequestChannel.

- mcs/class/System.ServiceModel/System.ServiceModel.Channels/HttpRequestChannel.cs
Concurrent request completions could cause following exception:
FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException:
Index was out of range. Must be non-negative and less than
the size of the collection.
Parameter name: index
at System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) [0x00009] in <4a8a0eaa024f41829d3435c07e5c7edb>:0
at System.Collections.Generic.List`1[T].Remove (T item) [0x0000c] in <4a8a0eaa024f41829d3435c07e5c7edb>:0
at System.ServiceModel.Channels.HttpRequestChannel+HttpChannelRequestAsyncResult.Cleanup () [0x00011] in <28c4695205ef47378f5370502b066592>:0
at System.ServiceModel.Channels.HttpRequestChannel+HttpChannelRequestAsyncResult.set_IsCompleted (System.Boolean value) [0x00034] in <28c4695205ef47378f5370502b066592>:0
at …
> [2018-10] [System.ServiceModel] Fix a race condition in HttpRequestChannel.

- netcore/excludes-System.Runtime.Tests.rsp
- netcore/gen-xunit-runner/Program.cs
This PR adds ~2200 tests to System.Runtime.Tests and ~1000 to System.Collections.Tests
> [netcore] Initial MemberDataAttribute support

- mcs/class/corlib/System.Runtime.InteropServices/Marshal.cs
Current implementation uses AllocCoTaskMem for secure strings in SecureStringToGlobalAllocAnsi/Unicode, but ZeroFreeGlobalAllocAnsi/Unicode will always free using FreeHGlobal. This will cause memory leaks and corruption on platforms where AllocCoTaskMem and AllocHGlobal are backed by different allocators.
> Fix mixup of Global Free and CoTaskMem Alloc in Marshal's Secure String implementation.

- netcore/gen-xunit-runner/Program.cs
```
RUN: 21756 (+13000)
FAILURES: 90
SKIPPED: 200
```
Output for System.Runtime.Tests: https://gist.github.com/EgorBo/b4f94cea3df38f74b9315ad2ad576d56
For MemberData, gen-xunit-proj now generates:
```csharp
foreach (var row in SomeType.MemberDataMethod())
typeof(SomeType).GetMethod("TestMethod").Invoke(o, (object[])row);
```
> [netcore] better MemberData support

- mcs/class/System.ServiceModel/System.ServiceModel.Channels/HttpRequestChannel.cs
Concurrent request completions could cause following exception:
FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException:
Index was out of range. Must be non-negative and less than
the size of the collection.
Parameter name: index
at System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) [0x00009] in <4a8a0eaa024f41829d3435c07e5c7edb>:0
at System.Collections.Generic.List`1[T].Remove (T item) [0x0000c] in <4a8a0eaa024f41829d3435c07e5c7edb>:0
at System.ServiceModel.Channels.HttpRequestChannel+HttpChannelRequestAsyncResult.Cleanup () [0x00011] in <28c4695205ef47378f5370502b066592>:0
at System.ServiceModel.Channels.HttpRequestChannel+HttpChannelRequestAsyncResult.set_IsCompleted (System.Boolean value) [0x00034] in <28c4695205ef47378f5370502b066592>:0
at …
> [2018-08] [System.ServiceModel] Fix a race condition in HttpRequestChannel.

- mcs/class/System.Windows.Forms/System.Windows.Forms/ContainerControl.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs
- mcs/class/System.Windows.Forms/System.Windows.Forms/Form.cs
- mcs/class/System.Windows.Forms/Test/System.Windows.Forms/FormEventTest.cs
> [WinForms] Related Forms closing issue (#13150)

- man/mono.1
- mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/12182
Backport of #13323.
/cc @lewurm
> [2019-02] [AOT] add option to control arguments to llc and add fallback for x86

- mono/mini/driver.c
> [interp] Enable compile all debug option also on interp

- configure.ac
- mcs/class/System/corefx/Unix/Interop.cs
- mcs/class/System/monodroid_System_xtest.dll.exclude.sources
> Xamarin.Android integration fixes

- configure.ac
- mcs/class/System/corefx/Unix/Interop.cs
- mcs/class/System/monodroid_System_xtest.dll.exclude.sources
Backport of #12940.
Backport of #13589.
/cc @alexischr
> [2019-02] Xamarin.Android integration fixes

- scripts/ci/pipeline/osx-package.groovy
This allows us to get faster results.
> [ci] Build macOS .pkg PR builds on a separate bot

- mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj
- mcs/class/System.Private.CoreLib/System.Threading/Mutex.cs
- netcore/.gitignore
- netcore/Makefile
- netcore/gen-xunit-runner/Program.cs
Needed for xunit console runner tool.
> [netcore] Implement missing bits in Mutex

- mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/13455.
Backport of #13581.
/cc @akoeplinger @vargaz
> [2019-02] [aot] Avoid an assert which can happen in normal usage.

- mcs/class/System.Private.CoreLib/System.Runtime/GCSettings.cs
- mcs/class/System.Private.CoreLib/System.Threading/Semaphore.cs
needed for MSBuild (`./dotnet run`)
> [netcore] Semaphore

- mono/metadata/culture-info.h
It is unusual and not useful.
This was rejected previously.
> Remove const on struct fields.

- mono/metadata/threads.c
> [netcore] Fix thread debugging messages

- mcs/class/corlib/System/TimeZoneInfo.cs
- mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
Port of https://github.com/mono/mono/pull/13553.
> Port 13553 "Fix transition offset logic" to master

- mcs/class/System.Private.CoreLib/System.Threading/Thread.cs
- netcore/Makefile
- netcore/excludes-System.Threading.Thread.Tests.rsp
> [netcore] Fix stack size for new threads

- mcs/class/corlib/System/TimeZoneInfo.cs
- mcs/class/corlib/Test/System/TimeZoneInfoTest.cs
Port of https://github.com/mono/mono/pull/13553.
Backport of #13649.
> [2019-02] Port 13553 \u0022Fix transition offset logic\u0022 to master

- mono/metadata/class.c
- mono/mini/aot-compiler.c
Fixes https://github.com/mono/mono/issues/13607.
> [runtime] Revert daf92b9e62a847d521ae314c320d3502fefe217e.

- mono/mini/mini-llvm.c
> [llvm] Fix the computation of size of gshared instances in another place.

- mono/mini/mini-llvm.c
> [2019-02] [llvm] Fix the computation of size of gshared instances in another place.

- mcs/class/referencesource/System/net/System/Net/cookiecontainer.cs
Fixes issue: https://github.com/mono/mono/issues/12871
> [wasm] Fix System.DllNotFoundException: libc

- netcore/Makefile.am
- netcore/excludes-System.Runtime.Tests.rsp
https://github.com/mono/mono/pull/13731 fixed a bunch of testsuites
Also I found why `System.Runtime.Tests` didn't generate xml/html reports in the end - due to `System.Tests.Types.VoidTests.IsByRef_Get_ReturnsExpected` (it doesn't fail but fails to serialize for reports with error `error: Return type can't be a byref type Parameter name: returnType`).
Current state:
```
make xtestall COREFX_ROOT=/prj/corefx-egor
```
```
System.Memory.Tests                                       - Total: 44975  Failed: 71     Skipped: 0     
System.Runtime.Tests                                      - Total: 30422  Failed: 377    Skipped: 0     
System.Collections.Tests                                  - Total: 30406  Failed: 8      Skipped: 0     
System.Linq.Parallel.Tests                                - …
```
> [netcore] Update tests

- mono/utils/mono-membar.h
- mono/utils/mono-threads-wasm.c
Broken by https://github.com/mono/mono/pull/13712.
/cc @vargaz @marek-safar
> Fix WASM build

- mono/metadata/marshal.h
- mono/mini/mini-llvm.c
Backport of #11014.
/cc @directhex @vargaz
> [2018-10] [llvm] Fix the loaded llvm build.

- mcs/class/corlib/Test/System.Reflection/EventInfoTest.cs
- mono/metadata/icall.c
Fixes https://github.com/mono/mono/issues/13350
Fixes https://github.com/mono/mono/issues/10277
Backport of #13397.
> [2019-02] Add reflected type to event methods

- netcore/Makefile.am
Makes the SDK more aligned with the version of CoreFX test assets. Added workaround for System.Text.Json.Tests until we can properly consume the CoreFX bits. Large number of the failed tests are caused by missing assemblies.
```
System.Memory.Tests                                       - Total: 45032  Failed: 25    
System.Runtime.Tests                                      - Total: 31196  Failed: 330   
System.Linq.Expressions.Tests                             - Total: 31027  Failed: 65    
System.Collections.Tests                                  - Total: 30406  Failed: 8     
System.Linq.Parallel.Tests                                - Total: 28883  Failed: 5     
System.Xml.RW.XmlWriterApi.Tests                          - Total: 23385  Failed: 773   
System.Text.Encoding.Tests …
```
> [netcore] Bump SDK version

- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
Many of these operations are intrinsics on JIT.
> [interp] Add intrinsics for Math operations

- mono/utils/mono-threads-coop.h
Closes https://github.com/mono/mono/issues/13820
> Add MONO_LLVM_INTERNAL to re-fix LLVM AOT with loadedllvm

- mcs/class/System.Private.CoreLib/System.Reflection/Assembly.cs
- mcs/class/System.Private.CoreLib/System.Reflection/RuntimeAssembly.cs
Fixes 15 tests in System.Runtime.Tests.
> [netcore] Implement RuntimeAssembly.InternalLoadAssemblyName

- mono/mini/mini-llvm.c
> [llvm] Fix llvm JIT.

- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
GetHashCode is 2x faster while GetType is 10x faster.
> [interp] Add intrinsics for common object methods

- mcs/tools/upload-to-sentry/UploadToSentry.cs
- mono/mini/mini-exceptions.c
- mono/utils/mono-state.h
Fixes https://github.com/mono/mono/issues/13834
> [merp] Fix image size reported

- mcs/tools/upload-to-sentry/UploadToSentry.cs
- mono/mini/mini-exceptions.c
- mono/utils/mono-state.h
Fixes https://github.com/mono/mono/issues/13834
Backport of #13847.
> [2019-02] [merp] Fix image size reported

- mono/mini/mini-exceptions.c
- mono/utils/mono-state.h
Fixes https://github.com/mono/mono/issues/13834
Backport of #13847.
> [2018-10] [merp] Fix image size reported

- mono/mini/mini-exceptions.c
- mono/utils/mono-state.h
Fixes #13834
Backport of #13847.
> [2018-08] [merp] Fix image size reported

- mcs/class/System.Private.CoreLib/System.Runtime/RuntimeImports.cs
- mono/metadata/icall-decl.h
- mono/metadata/icall-def.h
- mono/metadata/icall.c
Fixes 15 failures in System.Memory.Tests.
> [netcore] Implement RuntimeImports.RhBulkMoveWithWriteBarrier

- mono/metadata/seq-points-data.c
ftell can be a negative value, handle that scenario.
> [metadata] Handle condition in ftell, Coverity 1307192

- mono/metadata/loader.c
[metadata] Fix memory leak for the last iteration of the loop, Coverity #1444258
> [metadata] Fix memory leak for the last iteration of the loop, Coverity #1444258

- netcore/.gitignore
- netcore/Makefile.am
Download the CoreFX binaries and use them for running the tests. This doesn't solve the problem with outbox assemblies yet, but it actually ensures that the test and assembly versions match by downloading the up-to-date CoreFX assets.
Current test summary with the PR:
```
System.Memory.Tests                                       - Total: 45032  Failed: 14    
System.Runtime.Tests                                      - Total: 32229  Failed: 80    
System.Linq.Expressions.Tests                             - Total: 31027  Failed: 65    
System.Collections.Tests                                  - Total: 30406  Failed: 8     
System.Linq.Parallel.Tests                                - Total: 28883  Failed: 5     
System.Xml.RW.XmlWriterApi.Tests                          - Total: 23385  Failed: …
```
> [netcore] Update CoreFX / Runtime versions

- mono/metadata/reflection.c
> [netcore] Remove an assertion which is no longer needed.

- configure.ac
Regression due to https://github.com/mono/mono/pull/13877
> [AOT] fix winaot LLVM profile

- configure.ac
Regression due to https://github.com/mono/mono/pull/13877
Backport of #13909
> [2019-04] [AOT] fix winaot LLVM profile

- scripts/ci/pipeline-netcore-runtime.yml
This builds a runtime nuget, in an Azure Pipeline.
It doesn't upload anywhere yet - need discussion with the relevant stakeholders.
> [netcore] Add a Pipeline yaml for Core build

- mono/metadata/class-internals.h
Closes https://github.com/mono/mono/issues/13974
> Add another symbol for loadedllvm

- sdks/wasm/sdk/WebAssembly.Bindings.Framework/WebAssembly.Bindings.csproj
- sdks/wasm/sdk/WebAssembly.Net.Http.Framework/WebAssembly.Net.Http.csproj
- Add the WebAssembly.Bindings.xml to the package.
- Add the WebAssembly.Net.Http.xml to the package.
> [wasm] Add generated xml doc to sdk build.

- mcs/class/System/System.Net.Sockets/Socket.cs
> Use 	DNS.GetHostAddressesAsync instead of sync version

- packaging/MacSDK/nuget.py
> [nuget] Bump to nuget 5.0.0

- packaging/MacSDK/nuget.py
> [2019-02] [nuget] Bump to nuget 5.0.0

- packaging/MacSDK/nuget.py
> [2019-04] [nuget] Bump to nuget 5.0.0

- sdks/wasm/Makefile
- sdks/wasm/tests/browser/IssuesTestSuite.cs
- sdks/wasm/tests/browser/issues-spec.html
- sdks/wasm/tests/browser/issues-spec.js
- sdks/wasm/tests/browser/karma.conf.js
- Add IssuesTestSuite to test suite make build.
- Add new issues spec and test calls.
- https://github.com/mono/mono/issues/12981
- https://github.com/mono/mono/issues/1388
- https://github.com/mono/mono/issues/13428
> [wasm] Add tests for issues to catch regressions.

- mcs/packages/Makefile
- mcs/tools/xbuild/Makefile
- packaging/MacSDK/fsharp.py
- packaging/MacSDK/msbuild.py
- packaging/MacSDK/patches/fsharp-msbuild-16-0.patch
- scripts/ci/run-test-mac-sdk.sh
- tools/nuget-hash-extractor/download.sh
Bump to get the msbuild 16 update
> Bump msbuild to track mono-2018-08-test

- packaging/MacSDK/nuget.py
Backport of #13815.
/cc @radical
> [2018-08] [nuget] Bump to nuget 5.0.0

- mono/metadata/w32socket-unix.c
> [w32error] Add ENONET error case

- mono/metadata/w32socket-unix.c
Fixes #12821 
Backport of #13994.
> [2019-04] [w32error] Add ENONET error case

- mono/metadata/w32socket-unix.c
Fixes #12821 
Backport of #13994.
> [2019-02] [w32error] Add ENONET error case

- packaging/MacSDK/nuget.py
> [2018-10] [nuget] Bump to nuget 5.0.0

- netcore/.gitignore
- netcore/Makefile.am
- netcore/NuGet.config
- netcore/corefx-restore.csproj
This may not ultimately be the right or best solution to consuming the CoreFX dependencies, but it temporarily resolves the following issues:
- Local CoreFX builds are no longer necessary for running `make xtest*` in `netcore`
- All OOB packages required by tests are restored from NuGet feed
- Dependency on the command line `nuget` tool is removed in favour of `dotnet` command line tool that is available on Windows too
Test results (with current exclusion lists enabled):
```
System.Memory.Tests                                       - Total: 45033  Failed: 14    
System.Runtime.Tests                                      - Total: 32360  Failed: 43    
System.Linq.Expressions.Tests                             - Total: 31027  Failed: 65    
System.Collections.Tests …
```
> [netcore] Switch to msbuild nuget which is available for all platforms

- mcs/class/System.Private.CoreLib/System/Array.cs
- mcs/class/System.Private.CoreLib/System/Attribute.cs
- mcs/class/corlib/System/MonoCustomAttrs.cs
- netcore/corefx-restore.csproj
Test results with master + cherry-picked #14039 + this PR:
```
System.Memory.Tests                                       - Total: 45033  Failed: 14    
System.Runtime.Tests                                      - Total: 32363  Failed: 44    
System.Linq.Expressions.Tests                             - Total: 31027  Failed: 65    
System.Collections.Tests                                  - Total: 30406  Failed: 8     
System.Linq.Parallel.Tests                                - Total: 28883  Failed: 4     
System.Xml.RW.XmlWriterApi.Tests                          - Total: 23385  Failed: 0     
Microsoft.VisualBasic.Core.Tests                          - Total: 19079  Failed: 0     
System.Text.Encoding.Tests                                - Total: 9943   Failed: 23 …
```
> [netcore] Misc. fixes

- mcs/class/System.Private.CoreLib/LinkerDescriptor/System.Private.CoreLib.xml
- mcs/class/System.Private.CoreLib/Mono/MonoDomainSetup.cs
- mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj
- mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs
- mono/metadata/assembly.c
> [netcore] Add linker descriptor for corelib.

- mono/mini/mini-generic-sharing.c
Maybe I misunderstand the code?
Or significant expansion is expected?
> Replace two element hash table with two element array and cheap linear search.

- scripts/ci/run-test-default.sh
- scripts/ci/run-test-helix.sh
We're still seeing some failing tests build sometimes.
> [ci] Workaround races in the tests build

- mcs/build/profiles/build.make
This bit-rotted at some point.
> Fix start-compiler-server

- mono/metadata/exception-internals.h
- mono/metadata/exception.c
- mono/metadata/icall.c
- mono/metadata/w32socket.c
- mono/utils/mono-error-internals.h
- mono/utils/mono-error.c
- mono/utils/mono-error.h
> Make dedicated MonoError for `mono_error_set_argument_out_of_range`

- sdks/wasm/framework/src/WebAssembly.Bindings/Core/Array.cs
- sdks/wasm/tests/browser/BindingsTestSuite.cs
- sdks/wasm/tests/browser/core-bindings-spec.js
- Add test for WebAssembly.Core.Array
- Add tests for WebAssembly.Core.Function Call and Apply.
> [wasm] Fix NRE WebAssembly.Core.Array during initialization

- configure.ac
Looks like monolite was broken somehow. Rebuild it.
> Bump monolite

- mono/mini/interp/transform.c
Fixes https://github.com/mono/mono/issues/14079
> [interp] Fix buffer overflow when incrementing sp

- mono/mini/llvm-jit.cpp
- mono/mini/llvm-jit.h
- mono/mini/mini-llvm.c
> [llvm] Remove unused dlsym_cb.

- mono/metadata/icall-table.h
> [runtime] Fix a warning.

- mcs/class/System.Private.CoreLib/LinkerDescriptor/System.Private.CoreLib.xml
- mcs/class/corlib/LinkerDescriptor/mscorlib.xml
- mcs/class/corlib/corefx/SR.cs
- mcs/class/corlib/corlib.csproj
- mcs/class/corlib/corlib.dll.sources
- mono/mini/mini-trampolines.c
- mono/utils/mono-error-internals.h
- mono/utils/mono-error.c
Adding AmbiguousImplementationException exception and throwing this when there are multiple candidate implementations.
Fixes #13926
> [DIM] Throwing AmbiguousImplementationException on call of multiple candidate implementations.

- mono/mini/interp/transform.c
Fixes https://github.com/mono/mono/issues/14079
Backport of #14142.
/cc @BrzVlad
> [2019-04] [interp] Fix buffer overflow when incrementing sp

- scripts/ci/pipeline-netcore-runtime.yml
Let's see what VSTS thinks of my conditional
> [netcore] Mangle .gitmodules on internal project to internal mirrors

- configure.ac
- mcs/class/System.Private.CoreLib/Makefile
- netcore/Makefile
> [netcore] Convert netcore/Makefile.am to a normal makefile, get the configure variables from config.make.

- external/how-to-bump-roslyn-binaries.md
> Add roslyn bump instructions next to roslyn-binaries

- mono/mini/interp/transform.c
Fixes https://github.com/mono/mono/issues/14079
Backport of https://github.com/mono/mono/pull/14142
> [2019-02] [interp] Fix buffer overflow when incrementing sp

- sdks/wasm/Makefile
- sdks/wasm/tests/browser/karma.conf.js
- Add `.pdb` file support to the karma config.
> [wasm][tests] Fix browser test command line arguments.

- sdks/wasm/Makefile
Package the documentation .xml files when packaging framework directories.
> [wasm] [bindings] Package doc .xml files

- sdks/wasm/Makefile
- sdks/wasm/sdk/Templates/DotNet/.template.config/template.json
- sdks/wasm/sdk/Templates/DotNet/Directory.Build.props
- sdks/wasm/sdk/Templates/DotNet/Program.cs
- sdks/wasm/sdk/Templates/DotNet/WasmTemplate.1.csproj
- sdks/wasm/sdk/Templates/DotNet/WasmTemplate.1.sln
- sdks/wasm/sdk/Templates/DotNet/global.json
- sdks/wasm/sdk/Templates/DotNet/index.html
- sdks/wasm/sdk/Templates/DotNet/server.py
```
Templates                                         Short Name         Language          Tags
----------------------------------------------------------------------------------------------------------------------------
Mono WebAssembly Starter                          wasm               [C#]              Mono/WebAssembly
```
Example use:
```
dotnet new wasm -n Test.WebAssembly -o Test.WebAssembly
```
> [wasm][sdk] Add dotnet new custom template.

- mono/mini/interp/interp.c
Backport of #14086.
/cc @BrzVlad
> [2019-04] [interp] Fix interp strmfld vt

- mono/mini/interp/interp.c
Backport of #14086.
/cc @BrzVlad
> [2019-02] [interp] Fix interp strmfld vt

- mono/metadata/metadata-cross-helpers.c
- sdks/builds/runtime.mk
- sdks/builds/wasm.mk
- sdks/wasm/Makefile
- sdks/wasm/packager.cs
- tools/offsets-tool-py/Makefile
- tools/offsets-tool-py/README.md
- tools/offsets-tool-py/offsets-tool.py
Use it on osx, since the c# version is 32 bits which is going away, and the 64 bit version doesn't work.
> [runtime] Add a python version of the offsets tool.

- mono/mini/interp/transform.c
This field is used by the internal hash table to link nodes and it can be changed during hash table insertion of other imethods. Copying this field back was leading to random hangs in hash table lookup.
Fixes random hangs in delegate-exit.exe and maybe other tests.
> [interp] Don't change next_jit_code_hash during imethod transform

- mono/mini/interp/interp.c
- mono/mini/interp/mintops.def
- mono/mini/interp/transform.c
> [interp] Optimize enum Hasflag

- mono/mini/interp/interp.c
- mono/mini/mini-exceptions.c
- mono/tests/llvmonly-mixed/Makefile.am
- mono/tests/llvmonly-mixed/interponly.cs
- mono/tests/llvmonly-mixed/jitonly.cs
> [runtime] Fix some mixed EH problems.

- mcs/class/System.Windows.Forms/System.Windows.Forms/XplatUIX11.cs
> Correct type and bitness for TARGETS request of X11 clipboard

- configure.ac
- mcs/class/referencesource/mscorlib/system/threading/threadpool.cs
- mono/metadata/icall-def.h
- mono/metadata/icall-table.h
- mono/metadata/threadpool.c
- mono/metadata/threadpool.h
ves_icall_System_Threading_ThreadPool_PostQueuedCompletionStatus
ves_icall_System_Threading_ThreadPool_BindIOCompletionCallbackNative
ves_icall_System_Threading_ThreadPool_IsThreadPoolHosted
> Move three trivial threadpool icalls to C#.

- sdks/wasm/framework/src/WebAssembly.Bindings/Runtime.cs
> Add replace ContainsKey with a consistency check in object registration

- sdks/wasm/tests/browser/core-bindings-spec.js
- sdks/wasm/tests/browser/http-spec.js
- sdks/wasm/tests/browser/issues-spec.js
> [wasm][tests] - fix typos

- mcs/build/tests.make
So we can include it in the SDKs archive.
/cc @mandel-macaque @jonpryor
> [tests] Write nunit/xunit exclude categories to a file

- sdks/wasm/sdk/Mono.WebAssembly.Build/WasmLinkAssemblies.cs
> Fixes #14353

- sdks/wasm/Makefile
> [wasm] Add a mixed target for sample

- .gitignore
- mono/unit-tests/.gitignore
Wasn't sure where in the file to best put the .dylib.dSYM stuff, so suggestions are welcome
> [gitignore] Add crash dump files, .dylib.dSYM directories, and test-path

- mcs/class/corlib/System.Reflection.Emit/AssemblyBuilder.cs
- mcs/class/corlib/Test/System.Reflection.Emit/AssemblyBuilderTest.cs
> [corlib] Implement AssemblyBuilder.get_ReflectionOnly()

- packaging/MacSDK/msbuild.py
- packaging/MacSDK/nuget.py
> Bump msbuild to track mono-2019-04

- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/metadata/w32mutex-unix.c
Backport of https://github.com/mono/mono/pull/14403
> [2019-04] Do not allocate handles in ReleaseMutex.

- mcs/class/corlib/ReferenceSources/TextInfo.cs
- mcs/class/corlib/Test/System.Globalization/CultureInfoTest.cs
Fixes https://github.com/mono/mono/issues/14102
> TextInfo.ChangeCase should not use CultureInfo.CurrentCulture

- mono/metadata/threads-types.h
- mono/metadata/threads.c
- mono/metadata/w32mutex-unix.c
Backport of https://github.com/mono/mono/pull/14403
> [2019-02] Do not allocate handles in ReleaseMutex.
