mcs/class/System.Numerics/Test/System.Numerics/BigIntegerTest.cs, mcs/class/corlib/ReferenceSources/String.cs, mcs/class/corlib/Test/System.IO/PathTest.cs, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/referencesource/mscorlib/system/bitconverter.cs, mcs/class/referencesource/mscorlib/system/timespan.cs
* `CancellationTokenRegistration`: use the CoreFX version.
* `String`: add `implicit operator String (ReadOnlySpan<char> value)`.
* `TimeSpan`: add `TimeSpan operator / (TimeSpan timeSpan, double divisor)`
and `double operator /(TimeSpan t1, TimeSpan t2)`.
* `BitConverter`: add `uint ToUInt32(ReadOnlySpan<byte> value)` and
`ulong ToUInt64(ReadOnlySpan<byte> value)`.
=> [corlib]: Misc updates from CoreFX.

mono/utils/mono-threads-posix.c
Makes it easier to know what thread does what when trying to debug these issues I've been having with things like finalizer threads.
=> Support setting thread names on Haiku

mcs/class/System/ReferenceSources/Logging.cs
Hi Mono Team,
This commit fixes an interesting bug that relates to the  System.Net.Http nuget packages.
So the short story is that System.Net.Http can view the internals of this assembly because of InternalsVisibleTo.  Part of HttpClient references System.Net.Logging's "On" _property_.  The problem is that mono has implemented "On" as a _field_ . When the latest version of System.Net.Http.HttpClient tries to invoke a HttpClient.SyncAsync using Mono, you get a MissingMethodException because:
bool System.Net.Logging.get_On()
does not exist.
This commit is simple and only changes the signature of On to match that of the reference source (property instead of field).  This will cause the Missing Method Exception not to be thrown.
=> "On" field breaks compatibility with System.Net.Http because of "Internals Visible To" & member type mis-match

mono/metadata/debug-mono-ppdb.c
Occasionally due to https://github.com/Microsoft/visualfsharp/issues/4637
Mono will assert if it tries to load a PPDB file that has an incorrect number
of MethodDebugInformation rows:
* Assertion at metadata.c:1117, condition `idx < t->rows' not met
Instead of asserting, check that the method index is in bounds, and print a more informative error.
=> [ppdb] Print some info if looking up an out of range method token

mono/mini/trace.c
Old gcc does not allow pragma diagnostic within function.
Fixes #8572
#if is a deliberate shorter form than #ifdef
- shorter
- allows for #define foo 0
- standardly undefined silently evaluates to 0
- potential for if instead of #if, though that does require #define foo 0, no
silent undefined => 0
=> Build fails on Redhat 6.8 with GCC 4.4.7.

mono/mini/Makefile.am.in
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
=> Don't set LDFLAGS on the libmono-ee library. Fixes this warning:

mcs/class/corlib/System.Reflection/ParameterInfo.cs, mcs/class/corlib/Test/System.Reflection/ParameterInfoTest.cs
Fixes https://github.com/mono/mono/issues/8312
.NET Core behavior: https://github.com/dotnet/coreclr/blob/85374ceaed177f71472cc4c23c69daf7402e5048/src/System.Private.CoreLib/shared/System/Reflection/ParameterInfo.cs#L99
=> [corlib] Match .NET behavior in ParameterInfo.ToString()

mono/metadata/metadata.c
Fixes https://github.com/mono/mono/issues/8250.
=> [runtime] Fix the marshalling of class types using MarshalAs(UnmanagedType.Struct).

mcs/class/Mono.Security/Mono.Security.Interface/CertificateValidationHelper.cs, mcs/class/System/Mono.Net.Security/CallbackHelpers.cs, mcs/class/System/Mono.Net.Security/ChainValidationHelper.cs, mcs/class/System/Mono.Net.Security/LegacySslStream.cs, mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs, mcs/class/System/Mono.Net.Security/MobileTlsContext.cs, mcs/class/System/Mono.Net.Security/NoReflectionHelper.cs, mcs/class/System/System.Net.Security/SslStream.cs
* `SslStream`: Reject attempts of setting conflicting callbacks using both the
Mono-specific `MonoTlsSettings` and the new `SslClientAuthenticationOptions` /
`SslServerAuthenticationOptions`.
This makes it consistent with CoreFx behavior where those callbacks may only be
specified in one of the possible places.
* `ChainValidationHelper` - this internal class has received a major overhaul and
lots of old and unused code removed.
All callbacks are not invoked with the correct `sender` parameter to make it
match the .NET / CoreFx behavior.
* `Mono.Security.Interface.CertificateValidationHelper`: remove unused internal code.
=> [System]: Cleanup `SslStream` callbacks and internal validation code.

mcs/class/corlib/System.Reflection.Emit/ParameterBuilder.cs, mcs/class/corlib/System.Reflection.Emit/TypeBuilder.cs, mcs/class/corlib/Test/System.Reflection.Emit/ParameterBuilderTest.cs
You should be able to do the moral equivalent of the code below using SRE:
```csharp
public enum E {E1, E2};
public interface Itf {
void MyMethod (int? i = null, int? i2 = 42, E? e1 = null, E? e2 = E.E2);
}
```
Fixes https://github.com/mono/mono/issues/8504
Fixes https://github.com/mono/mono/issues/8597
=> [sre] ParameterBuilder.SetConstant for a Nullable<T> parameter

mono/mini/mini-ppc.h
* mini-ppc-os.h doesn't exist. If the OS lacks a define,
give an error instead of a broken include.
* Remove redundant Mac OS case.
* Move AIX define for sigaction above cross-compile case,
so it won't get lost in the noise there.
=> Small cleanups for mini-ppc.h

configure.ac, mono/eglib/eglib-config.h.in, mono/eglib/eglib-config.hw, mono/eglib/glib.h
If C99 zu is not portable enough, then autoconf can find the exact type.
Iu always works on Win64.
Very old Win32 would want plain u.
GINT_TO_POINTER and such need no autoconf, beyond chosing gsize, gssize.
Using size_t provides for an exact match with functions like malloc and pthread_attr_getstack, no warnings.
=> Use size_t for gsize if it matches, else C99 uintptr_t. type-based instead of size-based autoconf printf(size_t)

mono/mini/decompose.c, mono/mini/intrinsics.c, mono/mini/method-to-ir.c, mono/mini/mini-ops.h, mono/mini/mini.h, mono/mini/objects.cs
Also mark the temporary bblocks used by decompose_vtypes () as out-of-line if
the bblock under processing is out-of-line. Make the domainvar as volatile to avoid
optimizing it away since references to it can now be generated later from the
decomposition of OP_BOX.
=> [jit] Decompose CEE_BOX later, to enable more optimization opportunities. Optimize Enum.HasFlags ().

mcs/class/System/System.Net.Sockets/Socket.cs
Fixes: https://github.com/mono/mono/issues/8692
In the following code:
```
var tcpClient = new TcpClient(new IPEndPoint(IPAddress.Any, 0));
tcpClient.BeginConnect("localhost", 51139, _ =>
{
tcpClient.EndConnect(_);
Console.WriteLine("Done");
}, null);
```
`Dns.GetHostAddresses` resolves "localhost"  as two addresess: ipv6 (::1) and ipv4 (127.0.0.1). Currently mono tries the first one and throws an exception (my Socket is ipv4) - `An address incompatible with the requested protocol was used.`
instead of that it should try ipv4 after that and only throw an exception if this second attempt also fails.
so it will match .NET Core behavior for `BeginConnect()`: https://github.com/dotnet/corefx/blob/7a1007f2ef04fd9ec576cdb198ff53af4f18c77b/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L …
=> [System] BeginConnect fails on ipv6 if Socket is ipv4

mono/mini/Makefile.am.in, mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/mini/aot-tests.cs
* [aot] Fix encoding/decoding of types with custom modifiers.
Fixes https://github.com/mono/mono/issues/8701.
* [aot] Add a test, disabling for now because it depends on c# 7.2.
* [aot] Bump AOT file format version.
* [aot] Only disable the test with mcs.
* [aot] Fix compilation of test.
=> [aot] Fix encoding/decoding of types with custom modifiers. (#8729)

mono/mini/llvm-jit.cpp
```
$  cat 1.cs
class B
{
public static void  Main(string[] args)
{
}
}
MONO_PATH=/s/mono/mcs/class/lib/monolite-darwin/1051500005/  /s/mono/mono/mini/mono --llvm 1.exe
Expected<T> must be checked before access or destruction.
Expected<T> value was in success state. (Note: Expected<T> values in success mode must still be checked prior to being destroyed).
Stacktrace:
Native stacktrace:
0   mono                                0x00000001028a00e8 mono_handle_native_crash + 264
1   libsystem_platform.dylib            0x00007fffb3ca2b3a _sigtramp + 26
2   mono                                0x0000000105217860 _ZZN4llvm4dbgsEvE7thestrm + 0
3   libsystem_c.dylib                   0x00007fffb3b27420 abort + 129
4   mono                                0x00000001028f1892 …
```
=> LLVM 6.0 JIT (not AOT) problem?

mono/metadata/monitor.c, mono/metadata/monitor.h, mono/tests/Makefile.am
Replaces semaphore usage with condition variable.
Fixes https://github.com/mono/mono/issues/6834
=> [monitor] Fix monitor aborts

mcs/class/corlib/orbis_corlib_test.dll.exclude.sources, mcs/class/corlib/orbis_corlib_test.dll.sources
Without these we cannot build the corlib test suite against the ORBIS BCL. Would also be great to have this backported to 2018-02 and 2018-04 if possible. We are currently updating to a BCL based on the 2018-02 branch.
=> Added corlib .sources files for the ORBIS profile

mcs/class/corlib/LinkerDescriptor/mscorlib.xml
To make sure that System.Reflection.Emit types in the class libraries
are properly removed by the linker, mark them with the "sre" feature in
the embedded linker descriptor file for mscorlib.
=> Add missing sre features to the mscorlib link.xml

mcs/class/System.Windows.Forms/System.Windows.Forms/PropertyGrid.cs
When ProppertyGrid contains more than one propertyTab it crashes whith NullReferenceException. And when clicking on propertyTab toolstripbutton it didn`t switch to this tab.
=> [System.Windows.Forms] fix PropertyGrid

mono/tests/Makefile.am, mono/tests/pinvoke.cs
Pinvoke signatures need to match the native ones from libtest.c
Fixes https://github.com/mono/mono/issues/7058
=> [tests] Fix pinvoke test

mono/metadata/marshal-ilgen.c
When we switched to the new version of Monitor.Enter, we didn't expand the try block to include the call. This led to unreleased locks when we acquired the lock but were aborted shortly afterwards.
=> [monitor] Fix abort of synchronisation wrapper

mono/metadata/assembly.c, mono/metadata/image-internals.h, mono/metadata/image.c
The "problematic images" are Windows-specific assemblies that are often
included with applications that do not work on Mono, but for which Mono has its
own implementation.
Previously (9ec8ec5389ae9177853442bdadbff3eedcf93000) we changed mono to deny
loading problematic images using Assembly.Load or when one assembly references
another and we find a problematic image using the usual assembly search.
For Assembly.LoadFrom, we used to emit a warning and then load the assembly anyway.
In this commit, we change the behavior: If Assembly.LoadFrom tries to open a
problematic image, we will instead probe for an assembly of that name in the
default context.  That should eventually end up opening Mono's version of that
assembly.
Example:
Suppose a problematic …
=> [loader] LoadFrom of problematic images should reprobe

mono/metadata/assembly.c, mono/metadata/image-internals.h, mono/metadata/image.c
This is a backport of #8737 to `2018-04`.
It's not entirely mechanical but it's pretty close to what's in master.
(The difference is the lack of the load context work in 2018-04, so there's more boolean flags instead of an enum)
----
The "problematic images" are Windows-specific assemblies that are often
included with applications that do not work on Mono, but for which Mono has its
own implementation.
Previously (9ec8ec5) we changed mono to deny
loading problematic images using Assembly.Load or when one assembly references
another and we find a problematic image using the usual assembly search.
For Assembly.LoadFrom, we used to emit a warning and then load the assembly anyway.
In this commit, we change the behavior: If Assembly.LoadFrom tries to open a
problematic image, we will instead …
=> [2018-04][loader] LoadFrom of problematic images should reprobe

mcs/class/corlib/Test/System.Threading/ThreadPrincipalTests.cs
=> [corlib] Disables test which depends on LogicalCallContext for mobile

mono/metadata/marshal-ilgen.c
=> [2018-02] [monitor] Fix abort of synchronisation wrapper

mcs/class/corlib/Test/System.Threading/ThreadPrincipalTests.cs
=> [2018-04] [corlib] Disables test which depends on LogicalCallContext for mobile

mono/mini/cpu-ppc64.md, mono/mini/mini-ppc.c, mono/mini/mini-ppc.h
* use gcc builtin for icache flushing
---------------------------------------------------
* narrow immediate value for relative branches
since we don't know the exact distance yet, we have to guess. sometimes this guess was not defensive enough.
---------------------------------------------------
* use different thunk machinery that works on ppc64
The old thunk machinery was sort of working on 64bit (before f4bd084 ), but it relies on having on
the memory layout of allocated chunks for code. Either the property got lost due to some refactoring, or it was never true on ppc64. Anyway, this patch switches the implementation to something we do on arm32 too: If we potentially need some thunks for the emitted code, we reserve some space for it at the end of the code buffer. That wastes a bit …
=> [ppc] implement machinery for thunks that works on ppc64

mono/metadata/threads.c
Fixes @vargaz crash:
https://gist.github.com/vargaz/f4bc5056efcc172b97b548d82192994b
=> [runtime] Gracefully handle crashes before mono-state dependencies inited

configure.ac, mcs/class/Mono.Security/Mono.Security.Interface/IMonoSslStream.cs, mcs/class/Mono.Security/Mono.Security.Interface/MonoTlsProviderFactory.cs, mcs/class/Mono.Security/Mono.Security.Interface/MonoTlsSettings.cs, mcs/class/System/Mono.AppleTls/AppleTlsContext.cs, mcs/class/System/Mono.Btls/MonoBtlsContext.cs, mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs, mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs, mcs/class/System/Mono.Net.Security/MobileTlsContext.cs
[System]: Epic: Client Certificate Support - Part Two.
This is the second and final part to bring Client Certificate support.  It needs to be landed on top of #8753 and #8756.
* `Mono.Security.Interface.IMonoSslStream`: Add `CanRenegotiate` and `RenegotiateAsync()`.
* `Mono.Security.Interface.MonoTlsSettings`: Add `DisallowUnauthenticatedCertificateRequest`.
* `AppleTlsContext`: fully support renegotiation.
- we may now receive `SslStatus.PeerAuthCompleted` and `SslStatus.PeerClientCertRequested`
during `Read()`.  It should in theory not happen during `Write()`, but I added it there
as well just to be on the safe side.
- `SetSessionOption()` may only be called before the initial handshake.
* `MobileAuthenticatedStream`: this is the major part of the work and the most complex one.
- added …
=> [System]: Epic: Client Certificate Support - Part Two.

mono/metadata/threadpool-io.c
Currently the list elements are allocated in the root domain, while the data can be allocated in other domains. We need to clear the reference when removing the list element so we are not left with hidden cross domain refs.
Ideally we should have per domain lists, so we also would just let the list and elements die, without having to iterate through them at domain unload time.
=> [threadpool] Clear data field of MonoListItem after we are done with it

mcs/build/tests.make, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c, mono/mini/interp/interp.c, mono/mini/mini-exceptions.c
We only used the interpreter on the client side (by mistake). Luckily most tests are working when using the interpreter on the debugee side. 
--------------------------------------------
* [debugger tests] use runtime flags for debugee
------------------------------------------
* [debugger] fix debugger_invoke frame in interp case
fixes DebuggerTests.BreakpointDuringInvoke on the interpreter
------------------------------------------
* [debugger] handle managed-to-native frames
fixes DebuggerTests.InspectThreadSuspenedOnWaitOne on the interpreter
------------------------------------------
* [interp] set SP in monoctx that is passed to exception handling
fixes DebuggerTests.ExceptionFilter on the interpreter
------------------------------------------
Fixes …
=> [Mono.Debugger.Soft.Test] Use interp on debugee

mcs/class/System/System.Net.Sockets/SocketAsyncEventArgs.cs
Fixes #8871
SocketAsyncEventArgs in mono never resets inner in_progress flag while .NET Core does: https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs#L449
=> [System] Make SocketAsyncEventArgs reusable

mcs/build/library.make
We'd get the following warning during the build:
```
'/Users/alexander/dev/mono/mcs/class/System.Data.Services.Client/ONO_PATH' in MONO_PATH doesn't exist or has wrong permissions.
```
The reason is that we didn't escape the $ symbol in the resgen template so the embedded $$MONO_PATH in the RESGEN variable ended up being mangled.
I'm kinda surprised this worked at all for so many years ¯\_(ツ)_/¯
=> [bcl] Fix ONO_PATH warning during resgen

mono/mini/Makefile.am.in
Turns out this is why LLVM is busted on Linux.
=> Fix building of LOADED_LLVM on Linux, from duplicate eglib linking (#8287)

configure.ac, mono/eglib/eglib-config.h.in, mono/utils/mono-logger-internals.h
Change 3 ifdef versions to one portable one.
Remove supporting autoconf that did not work as intended.
See https://github.com/mono/mono/issues/8587.
=> Cleanup varargs -- 3 variations to 1 and no malfunctioning autoconf.

configure.ac
This lets the linker catch any missing symbols, and fixes a problem
I had building AIX with CoreFX PAL. Fixes #8979, though there may
be more cases like this.
dotnet/corefx#30012 is blocking on this.
=> Make the sendfile with 6 args check use AC_TRY_LINK

mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/8972
=> [bitcode] Fix the generation of invalid llvm IR for some Span code.

mono/mini/mini-llvm.c
Backport of #8980.
/cc @vargaz
=> [2018-04] [bitcode] Fix the generation of invalid llvm IR for some Span code.

mono/mini/mini-llvm.c
Backport of #8980.
/cc @vargaz
=> [2018-02] [bitcode] Fix the generation of invalid llvm IR for some Span code.

configure.ac
Backport of https://github.com/mono/mono/pull/8233.
/cc @directhex
=> [2018-04] Add PowerPC configure flags for LLVM, and clean up failover linker flags

mono/metadata/cominterop.c
Multiple threads can see the null, then proceed to lock and create new one.
The check for null needs to be under the lock, either duplicated, or before and within.
Since we take the lock always unconditionally anyway soon afterward, just do it within.
=> Fix race condition in ves_icall_Mono_Interop_ComInteropProxy_AddProxy.

mono/mini/aot-compiler.c
Backport of #8348.
/cc @directhex
=> [2018-04] [runtime] Add llvm aot mode with graceful fallback

mono/utils/checked-build.c
https://jenkins.mono-project.com/job/test-mono-pull-request-coop/4300/testReport/junit/MonoTests/runtime/threadpool_exceptions5_exe_timedout/
`#22 0x000055da5ac70001 in mono_fatal_with_history (msg=<optimized out>) at checked-build.c:331`
=> Add volatile to error message to improve debuggability.

mono/mini/method-to-ir.c
The only reason for the restriction was that handle_alloc previously would not handle generic instances.
This speeded up the following microbenchmark by 19x (3.38s x 0.17s):
```
class Driver {
static T Identity<T> (T t) {
return t;
}
static Func<T,T> MakeDelegate<T> () {
return new Func<T, T> (Identity);
}
static void Main () {
object o = new object ();
for (int i = 0; i < 400 * 1000; ++i) {
MakeDelegate<object>()(o);
}
}
}
```
=> [mini] Remove unneeded restriction on fast delegate creation for context-using generic delegate under gshared.

mono/mini/mini-posix.c
On Unix, if an application block some signals all child processes run with exec would inherit its block. To avoid this problem I add signal into signal set to unblock when adding a handler for a signal.
=> Unblock signal when adding mono signal handler

mcs/build/library.make
Currently if we change for example `corlib.dll.sources` and then execute `make` - the `make` won't rebuild the lib, because it depends only on `net_4_x_corlib.dll.sources` and doesn't depend on all `#include` inside it.
As a temporarily solution we can depend on all *.sources files in the directory so a change in any of them will trigger rebuild. Unfortunately changes in un-related profiles will also trigger the rebuild but it's better than nothing for now I guess. For better experience we should fetch all #includes recursively for the current profile
=> library.make: track changes in *.sources

configure.ac
dotnet/corefx#30012 depends on this.
=> Check for *_CLOEXEC flags used by CoreFX PAL

mcs/build/Makefile
```
06:34:59 DEBUG: make[8]: *** No rule to make target `../../build/gensources.cs', needed by `../../build/gensources.exe'.  Stop.
```
=> [dist] Ensure gensources.cs is included in tarballs

mono/metadata/appdomain.c, mono/metadata/exception-internals.h, mono/metadata/exception.c, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/threads-types.h, mono/metadata/threads.c
Which involves:
`serialize_object`
`deserialize_object`
`mono_object_xdomain_representation`
and then the other users of `mono_object_xdomain_representation`:
`create_unhandled_exception_eventargs`
`call_unhandled_exception_delegate`
=> [Coop] Convert ves_icall_System_Threading_Thread_GetAbortExceptionState.

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/AssemblyMirror.cs, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/metadata/debug-mono-ppdb.c, mono/metadata/debug-mono-ppdb.h, mono/metadata/mono-debug.c, mono/metadata/mono-debug.h, mono/mini/debugger-agent.c
This PR allows debugger clients to retrieve metadata and pdbs as blobs via soft debugger protocol. Debugger may use own metadata/symbol reader which makes possible to extract more information than *Mirror objects provide.
Added commands to get TypeMirror and MethodMirror from assembly by metadata token
=> Reading of Metadata and pdb blobs via Soft debugger protocol

mono/metadata/threads.c
issue detected by cppcheck
[mono/metadata/threads.c:3993] -> [mono/metadata/threads.c:3991]:
(warning) Either the condition 'if(location&&location->source_file)'
is redundant or there is possible null pointer dereference: location.
condition is redundant indeed, it is nested in "if (location) {"
=> cleanup: remove redundant condition

mcs/class/corlib/System.Reflection.Emit/DynamicMethod.cs, mcs/class/corlib/Test/System.Reflection.Emit/DynamicMethodTest.cs
Fixes https://github.com/mono/mono/issues/9033
=> [corlib] Allow DM with an extra param to have the first one bound to null.

mono/utils/networking-posix.c
This fixes #8935.
How do we typically write automated tests for this? It relies on a known canon name for a given IP address, which seems like it could produce test flakiness between the need for working DNS and the need for the address<->cname pairing to remain constant.
=> Fix canon names not being returned from mono_get_address_info

mono/metadata/profiler.c
We can't raise event before that as the profiler depends on too much runtime
infrastructure at this point for it to reliably work.
For example, we need the threading infrastructure to be init'd so we can access the
thread-local profiler state to store events there.
Fixes https://github.com/mono/mono/issues/8866
=> [profiler] Don't raise events until the profiler transitions to the ready state.

mono/mini/mini-runtime.c
When creating dynamic methods, we put those in a queue so they can be collected later via `mono_jit_free_method ()`. the interpreter part was assuming, as soon as we allocate a dynamic method, it will be executed eventually and therefore an InterpMethod must exist in `info.interp_code_hash`, but this isn't necessarily the case.
Fixes https://github.com/mono/mono/issues/9109
=> [interp] check existence of InterpMethod before removing it from interp code hastable

mono/mini/liveness.c, mono/mini/method-to-ir.c, mono/mini/mini-amd64.c
This reduces compilation times for #7809 by 20% on OSX amd64.
It still takes 46 seconds on a good keyboard MBP.
=> [mini] Eliminate some sources of quadratic behavior. Improves on #7809.

sdks/builds/android.mk, sdks/builds/unzip-android-archive.sh
Android NDK supports cmake in addition to the older make-based ndk-build as the
build system and Xamarin.Android is in the process of switching the build of its
native bits to cmake. The reason for this switch is that certain parts of
Xamarin.Android (libmonodroid) are built for both the host system and
the Android target. The host system build currently uses hand-crafted code
directly in .csproj to build the native bits while the Android build uses
ndk-build. This results in duplication of code, compiler parameters are
specified in two locations - it is easy to introduce incompatibilities, bug
fixes may be applied only in one scenario etc.
Using cmake allows us to use a single build "script" for all the targets, thus
making the build more reliable. Android SDK has a cmake package which …
=> [SDKS,Android] Install cmake when provisioning Android SDK

mono/metadata/profiler.c
=> [2018-02] [profiler] Don't raise events until the profiler transitions to the ready state.

mono/mini/helpers.c
[mono/mini/helpers.c:195]: (warning) %d in format string (no. 1)
requires 'int' but the argument type is 'unsigned int'.
[mono/mini/helpers.c:197]: (warning) %d in format string (no. 1)
requires 'int' but the argument type is 'unsigned int'.
=> cleanup: fix string formatting

mono/metadata/icall.c, mono/metadata/image.c, mono/mini/method-to-ir.c, mono/mini/mini-runtime.c
Followup for 9ad5255338386a22e7a861e8bcc7c195dc591b99
Note that on win32 we already did the right thing because of nested
conditionals in mono_image_open_a_lot, but on non-win32 we need the extra
check.
Fixes #9044
=> [loader] Refonly load of problematic image is allowed.

mcs/class/Mono.Profiler.Log/Test/ProfilerTests.cs
See https://github.com/mono/mono/issues/8709.
=> [Mono.Profiler.Log] Disable HeapshotDataIsValid and fix MonitorEventsAreRecorded tests

sdks/builds/determine-linux-flavor.sh, sdks/builds/mxe.mk
Ubuntu Linux (possibly others too, but only Ubuntu is tested thus the
limitation) don't need to build or use `mxe`, they instead use mingw packaged
for the distribution, thus making the build faster.
This commit detects the Linux flavor in use and, if it's Ubuntu, configures the
build so that system mingw is used instead of mxe.
=> [Linux,XA build] Fix building of Windows cross-compilers on Ubuntu Linux

mono/tests/Makefile.am, mono/tests/process-stress-3.cs
The spawned process by the test iterates through the whole mono repo,
including submodules. On a loaded machine with a already slow I/O
device, 10 seconds could be a tight time budget. Instead of increasing
the timeout, let's try to reduce the generated output.
Fixes https://github.com/mono/mono/issues/6947 hopefully.
=> [tests] reduce IO load in process-stress-3

mono/metadata/threadpool-worker-default.c, mono/metadata/threads.c, mono/tests/Makefile.am, mono/tests/thread7.cs, mono/utils/mono-threads.c
(replacement for https://github.com/mono/mono/pull/9042 if it goes well)
regressed back in December with commit 5f5c5e97a08f7086d7c18af37352c4a03dc4c0d1
Because if there is an uncleared AbortRequest, suspend will be skipped, but the interrupt callback will still be called.
The skip is here:
```
request_thread_abort:
if (thread->state & (ThreadState_AbortRequested | ThreadState_Stopped))
return FALSE;
```
The interrupt callback anyway is, well, I debugged it a few days ago and don't see it now, would have to step through it again.
This is also the change that slowed down Alpine/muslc to be unusable. This change should be tested there too to see if it fixes it. The correlation between test/thread6 and anything else is unclear -- i.e. is thread abort so common, in the build?
=> Fix non-interpreter 5-60 second hang at shutdown of thread6 (and thread7).

mono/tests/Makefile.am
Tracked in https://github.com/mono/mono/issues/9000
=> Disable thread7 test for interpreter, like thread6.

mcs/class/corlib/System/Nullable.cs, mcs/class/corlib/Test/System/NullableTest.cs
Our `Nullable` implementation is slightly different regarding `Equals ()`.
mono:
https://github.com/mono/mono/blob/028ff0d34c8e8cbe1e819e49962775841972fc62/mcs/class/corlib/System/Nullable.cs#L111-L130
corefx:
https://github.com/mono/corefx/blob/ab816c3efdb1aedb4baa1b8d2fec8ee2f8e15683/src/Common/src/CoreLib/System/Nullable.cs#L62-L67
Fixes https://github.com/mono/mono/issues/9088
=> [System] align Nullable.Equals behaviour with .NET core

mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2ImplMono.cs, mcs/class/System/Test/System.Security.Cryptography.X509Certificates/X509Certificate2Test.cs
One unit test is removed as part of the commit because it is not consistent with documentation and CoreFX behaviour on non-Windows platforms (https://github.com/dotnet/corefx/issues/30416).
The main goal of this patch is to actually get meaningful error messages when constructing X509Certificate2 from a byte array. Previously PKCS#12/PFX certificate import could fail due to unimplemented features (such as ECDsa support) or bugs. The certificate import would then be retried as PKCS#7 and the original error message was lost.
=> Improve certificate type detection and exception messages on import

mono/metadata/marshal.c, mono/tests/libtest.c, mono/tests/marshal2.cs, mono/tests/pinvoke2.cs
Fixes https://github.com/mono/mono/issues/9010.
=> [runtime] Fix the freeing of BStr members in pinvoke.

mono/metadata/appdomain.c, mono/metadata/assembly.c
Try to catch situations leading to a segv in mono_domain_assembly_search by
checking that we never put NULL into domain_assemblies and that callers of
mono_assembly_names_equal_flags never pass NULL args to it.
=> [loader] Add null checks around domain_assemblies

mcs/class/corlib/System.Reflection.Emit/DynamicMethod.cs, mcs/class/corlib/Test/System.Reflection.Emit/DynamicMethodTest.cs
Backport of #9067.
/cc @luhenry
=> [2018-06] [corlib] Allow DM with an extra param to have the first one bound to null.

mcs/class/corlib/System.Reflection.Emit/DynamicMethod.cs, mcs/class/corlib/Test/System.Reflection.Emit/DynamicMethodTest.cs
Backport of #9067.
/cc @luhenry
=> [2018-04] [corlib] Allow DM with an extra param to have the first one bound to null.

mono/profiler/aot.c
Backport of #9166.
/cc @lewurm
=> [2018-04] [profiler] account for nullbyte in allocated buffer

configure.ac, mono/eglib/goutput.c, mono/eglib/gspawn.c, mono/metadata/appdomain.c, mono/metadata/cominterop.c, mono/metadata/custom-attrs.c, mono/metadata/exception.c, mono/metadata/handle.c, mono/metadata/handle.h, mono/metadata/icall.c, mono/metadata/marshal.c, mono/metadata/marshal.h, mono/metadata/object.c, mono/metadata/reflection-cache.h, mono/metadata/reflection.c, mono/metadata/remoting.c, mono/metadata/sre-encode.c, mono/metadata/sre.c, mono/metadata/threads.c, mono/metadata/w32file.c, mono/metadata/w32socket.c, mono/mini/aot-compiler.c, mono/mini/exceptions-wasm.c, mono/mini/tramp-wasm.c
Make coop handles typesafe.
Type-safe handles are a struct with a pointer to pointer.
The only operations allowed on them are the functions/macros in handle.h, and assignment
from same handle type to same handle type (which cannot be prohibited in C, but are ok anyway).
Type-unsafe handles are a pointer to a struct with a pointer.
Besides the type-safe operations, these can also be:
1. compared to NULL, instead of only MONO_HANDLE_IS_NULL
2. assigned from NULL, instead of only a handle
3. MONO_HANDLE_NEW (T) from anything, instead of only a T*
4. MONO_HANDLE_CAST from anything, instead of only another handle type
5. assigned from any void*, at least in C
6. Cast from any handle type to any handle type, without using MONO_HANDLE_CAST.
7. Cast from any handle type to any pointer type and …
=> Make coop handles typesafe.

mono/metadata/assembly.c, mono/metadata/image-internals.h, mono/metadata/image.c
This reverts commit a2bed67b6bef1bed79dc347cc8ed147096a07987
which itself reverted 9ad5255338386a22e7a861e8bcc7c195dc591b99
Additionally cherrypick 60f06e6ca26c28f874f67503cb58e7fb76095713: refonly load
of problematic image is allowed.
Fixes #8726
=> [2018-06][loader] LoadFrom of problematic images should reprobe (correctly)

mcs/build/gensources.cs, mcs/build/library.make
The gensources.cs currently checked in to master doesn't fail on missing files by default because it didn't work at the time. This turns that behavior on. It is currently only in my other in-progress branch so I'm moving it here.
=> Make gensources.cs fail on missing files or zero-match wildcards

mono/metadata/threads.c
Threads which do things with signals and locks may end up unresponsive to our signals. I cannot get threads that crash in a lock to respond to SIGTERM on Darwin even if I explicitly unmask SIGTERM on those threads.
In order to defensively program against platform bugs around signals and stubborn threads, we need to be able to abandon these threads and continue, dumping other threads.
=> [runtime] Make mono-state dumper abandon stuck threads

mono/mini/mini-exceptions.c
=> [runtime] Move debugger flight recorder printing earlier in crash

mono/metadata/threads.c, mono/metadata/w32process-unix-default.c, mono/metadata/w32process-unix.c, mono/utils/mono-proclib.c
AIX has a procfs with raw structures congruent with Solaris. For i,
which lacks procfs, fall back to a libc call.
This doesn't solve the Process weirdness that bungs up the test
suite, but I hope it's a start.
(I expect a lot of "fun" once CoreFX happens there...)
=> System.Diagnostics.Process improvements for AIX

mcs/class/System/System.Net/HttpWebRequest.cs, mcs/class/System/System.Net/ServicePointScheduler.cs, mcs/class/System/System.Net/WebResponseStream.cs
Manual backport for #9228.
(cherry picked from commit a40aaa4878062a0d739e18719eb1c77c70862851)
(cherry picked from commit 6e4dd9facb546391b6f8abb4c9a72b639b804276)
=> [2018-04][System]: Fix bug in `WebResponseStream.GetResponse()` that will make some people happy. #9228.

mono/metadata/mono-conc-hash.c, mono/tests/Makefile.am, mono/tests/dynamic-method-churn.cs, mono/utils/mono-conc-hashtable.c
Tombstones must be scrubbed as they can end up taking up all space of a hashtable and make lookup fail.
=> [runtime] Implement tombstone scrubbing for our concurrent hashtables.

mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c, mono/tests/Makefile.am
The throwing of the pending exception after the finally blocks are executed was in unreachable code.
Refactor the code a bit and exit the abort protected block directly in endfinally. We throw the abort after all guarding finally blocks were invoked, to avoid throwing from inside a finally block. Guard also fault handler, which are called from EH.
=> [interp] Fix abort after finally block

mono/mini/interp/transform.c, mono/mini/main.c
There are Windows platforms (like UWP) that doesn't support getenv. The implementation of g_getenv makes it possible to replace the implementation at build time on none desktop platforms.
=> Change getenv to g_getenv in sources build on Windows platforms.

configure.ac, mono/metadata/icall.c, mono/mini/aot-compiler.c, mono/mini/llvm-jit.h, mono/mini/mini-exceptions.c, mono/mini/mini-llvm-cpp.h, mono/mini/mini-llvm.c, mono/mini/mini-runtime.c, msvc/build-init.vcxproj, msvc/build-init.vcxproj.filters, msvc/libmini-llvm.targets, msvc/libmini.vcxproj, msvc/libmono-dynamic.vcxproj, msvc/llvm-cmake-config.bat, msvc/mono.props, msvc/mono.vcxproj, winconfig.h
Uses mono LLVM master branch, build using cmake and VisualStudio 2015/2017. Commit adds support for AOT/Full AOT LLVM codegen for Windows x64 Visual Studio build mono runtime. Normal configure/make using cygwin won’t support LLVM and will trigger an error if configured.
In order to build using LLVM first mono LLVM master branch must be build using static linked LLVM configuration (dynamic loading can be added later), NOTE mono LLVM build needs to include the following commit, https://github.com/mono/llvm/commit/9b92b4b87607e137266f84dc307181b8842fe54a in order to successfully build on Windows x64.
Build mono LLVM branch using the following cmake configuration:
-DCMAKE_BUILD_TYPE=Release
-DLLVM_ENABLE_ZLIB=OFF
-DLLVM_TARGETS_TO_BUILD="X86"
-DCMAKE_CROSSCOMPILING=False …
=> Add LLVM AOT/Full AOT support on Windows x64.

mono/mini/debugger-state-machine.c
Somewhere in the daily rebasing to edit the PR, I lost the correct version of the early-exit. This fixes our native crash when we did not use the debugger. It's important to merge, or we'll crash before MERP/gdb dumping happens.
=> [runtime] Fix debugger dumping when unused

mono/dis/get.c, mono/eglib/eglib-remap.h, mono/eglib/glib.h, mono/eglib/gstring.c, mono/eglib/test/string.c
g_string_prepend does not update string->len.
g_string_insert does not update string->len, and copies the wrong number of characters around,
and does not allow for overlapping parameters
g_string_erase does not always update string->len.
=> Remove 3 unused incorrectly written functions.

mono/metadata/class-init.c, mono/metadata/sgen-mono.c, mono/sgen/sgen-conf.h, mono/sgen/sgen-gc.c
Hopefully this should allow us to support nurseries up to 32GB.
https://github.com/mono/mono/issues/9185
=> [sgen] Use longs with nursery array fill

mono/metadata/threads.c
=> [2018-02] [runtime] Make mono-state dumper abandon stuck threads

mono/metadata/threads.c
=> [2018-04] [runtime] Make mono-state dumper abandon stuck threads

mono/metadata/w32event-unix.c, mono/metadata/w32handle.c, mono/metadata/w32handle.h, mono/metadata/w32mutex-unix.c, mono/metadata/w32process-unix.c, mono/metadata/w32semaphore-unix.c
Had additional restructure not been ok, at least typedefing the function pointer
would have helped.
Add const for efficiency -- make the copy-on-write faults count for more and
not take extra readonly data with them.
Remove unused and actually confusing parameter -- it is just zeroed memory
and almost cannot be used for anything (granted, could hash it).
=> Cleanup some confusing code.

mcs/class/System/Mono.AppleTls/AppleTlsContext.cs
Fixes https://github.com/mono/mono/issues/9234
=> [System]: Renegotiation in AppleTls requires OS X 10.12+.  #9234.

mcs/class/System/Mono.AppleTls/AppleTlsContext.cs
Backport of #9254.
/cc @baulig
=> [2018-06] [System]: Renegotiation in AppleTls requires OS X 10.12+.  #9234.

mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs, mcs/class/System/System.Net/HttpWebRequest.cs, mcs/class/System/System.Net/WebResponseStream.cs
Cleanup the internal `HttpWebRequest.RunWithTimeout()` function and use
`GetWebException()` everywhere to throw `WebException` with
`WebExceptionStatus.RequestCanceled` on abort.
New tests for this will be added to the web-tests by extending the existing
`Xamarin.WebTests.HttpInstrumentationTests.AbortDuringHandshake` to check the
synchronous and begin/end async APIs as well, using both `GET` and `POST`.
See https://github.com/xamarin/web-tests/blob/master/Xamarin.WebTests.Tests/Xamarin.WebTests.HttpInstrumentationTests/AbortDuringHandshake.cs.
Fixes issue #9031.
=> [System]: `HttpWebRequest` now throws `WebExceptionStatus.RequestCanceled` on abort.  #9031.

mono/profiler/aot.c
Backport of #9166.
/cc @lewurm
=> [2018-06] [profiler] account for nullbyte in allocated buffer

mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs
Unix-only exception is being thrown on Windows, more info in #9277 
Detecting unix platform as recommended on mono website: http://www.mono-project.com/docs/faq/technical/#how-to-detect-the-execution-platform
=> Fixes #9277

data/gdb-pre7.0/mono-gdb.py, data/gdb/mono-gdb.py
Fixes #9292.
Omitting positional parameters works for gdb linked to python 2.7 / 3.1+. On older systems (e.g. redhat 6, centos 6) gdb might be linked to python 2.4-2.6 or 3.0, adding parameter ordinals enables proper backtraces on those systems.
=> Use positional parameters in calls to .format in gdb python scripts (#9292)

mcs/build/tests.make
Now that we're running more xunit tests it's useful to include those in the babysitter reporting.
=> [ci] Report xunit test results to babysitter

mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/9318.
=> [llvm] Avoid using the preserveall calling convention on watchos, xcode10 asserts on it.

mono/utils/mono-merp.c
After the long wait, we finally got a response from upstream outside of the GDPR officer messages. The below changes were requested. The event type in question is not yet enabled on Watson. As we have been promised a server enablement from the Watson team on the 26th, I'm merging the code required for that now so we can have everything built, backported, packaged, and ready to go for that ship date.
=> Make requested MERP file format changes

mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs, mcs/class/System/System.Net/HttpWebRequest.cs, mcs/class/System/System.Net/WebResponseStream.cs
* [System]: `HttpWebRequest` now throws `WebExceptionStatus.RequestCanceled` on abort.  #9031.
Cleanup the internal `HttpWebRequest.RunWithTimeout()` function and use
`GetWebException()` everywhere to throw `WebException` with
`WebExceptionStatus.RequestCanceled` on abort.
New tests for this will be added to the web-tests by extending the existing
`Xamarin.WebTests.HttpInstrumentationTests.AbortDuringHandshake` to check the
synchronous and begin/end async APIs as well, using both `GET` and `POST`.
See https://github.com/xamarin/web-tests/blob/master/Xamarin.WebTests.Tests/Xamarin.WebTests.HttpInstrumentationTests/AbortDuringHandshake.cs.
Fixes #9031.
* Fix exception checks, setting `TransferEncoding` without `SendChunked` is supposed to throw `InvalidOperationException`.
(cherry picked …
=> [System][2018-04]: `HttpWebRequest` now throws `WebExceptionStatus.RequestCancanceled` on abort.(#9212)

mono/mini/mini.c
workaround for https://github.com/mono/mono/issues/9298
backporting up to 2018-02 would be nice. we should backport to 2018-04 in order to unblock @grendello on his linux box.
=> [mini] add workaround for AMD Ryzen Threadripper issue

scripts/ci/run-jenkins.sh, sdks/builds/android.mk, sdks/builds/mxe.mk
Backport of #9328.
/cc @luhenry
=> [2018-02]  [sdks] Only rebuild MXE when it doesn't exist, not when we just cloned the sources

scripts/ci/run-jenkins.sh, sdks/builds/android.mk, sdks/builds/mxe.mk
Backport of #9328.
/cc @luhenry
=> [2018-04]  [sdks] Only rebuild MXE when it doesn't exist, not when we just cloned the sources

scripts/ci/run-jenkins.sh, sdks/builds/android.mk, sdks/builds/mxe.mk
Backport of #9328.
/cc @luhenry
=> [2018-06]  [sdks] Only rebuild MXE when it doesn't exist, not when we just cloned the sources

mcs/build/tests.make, mcs/class/test-helpers/RemoteExecutorTestBase.Mobile.cs
=> [2018-06] [build] Skips RemoteExecuted bases tests on monodroid

mono/metadata/threads.c, mono/mini/mini-runtime.c, mono/utils/mono-coop-mutex.h
1. Switch to GC Safe thread state in `mono_coop_cond_signal` and `mono_coop_cond_broadcast` because at least on Linux/glibc the underlying implementation can block on a futex (specifically in `__condvar_quiesce_and_switch_g1` in `glibc/ntpl/pthread_cond_common.c`).  If you'd like details:
* glibc NTPL description of the implementation of pthread condition variable signaling [(pthread_cond_wait.c:193 on sourceware.org)](https://sourceware.org/git/?p=glibc.git;a=blob;f=nptl/pthread_cond_wait.c;h=3e1105418210288ef21c37730a59dc8bc619ab3b;hb=HEAD#l193) 
* glibc NTPL implementation of `__condvar_quiesce_and_switch_g1` [(pthread_cond_common.c:341 on sourceware.org)](https://sourceware.org/git/?p=glibc.git;a=blob;f=nptl/pthread_cond_common.c;h=8e425eb01eceabec64e2bad3cfeb2ec51b6f6d72;hb=HEAD#l341) …
=> [coop] mono_coop_cond_signal should switch to GC Safe thread state

mono/metadata/assembly.c, mono/metadata/image-internals.h, mono/metadata/image.c
Backport correct fix for #8726 to `2018-02`
This reverts commit 569bd3bc52fad89536c7aa07f30870d3d8b6603a
which itself reverted efe1fdeb9dedeb2f3aba2efe63a977f3521d04b0.
Additionally, cherrypick 60f06e6ca26c28f874f67503cb58e7fb76095713: refonly load
of problematic image is allowed.
=> [2018-02][loader] LoadFrom of problematic images should reprobe (correctly)

mono/mini/mini.c
Backport of #9321.
/cc @lewurm
=> [2018-04] [mini] add workaround for AMD Ryzen Threadripper issue

configure.ac, mono/metadata/handle.h, mono/metadata/threads.c, mono/metadata/w32file-win32.c, mono/metadata/w32process-win32.c, mono/metadata/w32process.c, mono/metadata/w32semaphore-win32.c, mono/metadata/w32socket-win32.c, mono/mini/exceptions-amd64.c, mono/mini/mini-amd64.h, winconfig.h
And suppress new warnings from typesafe coop handles.
And suppress other warnings.
=> Enable incompatible-pointer warnings on Windows/gcc like the other gcc.

mono/metadata/icall.c, mono/metadata/marshal.c, mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/reflection.c, mono/metadata/sre-save.c, mono/utils/mono-error-internals.h, mono/utils/mono-error.c
Most uses of mono_error_set_argument do not take a format string.
So rename mono_error_set_argument to mono_error_set_argument_format
and provide mono_error_set_argument that just takes one string, not to be formated.
Visit every call to mono_error_set_argument and change just a few to be mono_error_set_argument_format.
While there, notice that method_encode_code forms up extra data and does not use it.
=> Fix many warnings like: icall.c:666:2: warning: format string is not a string literal (potentially insecure) [-Wformat-security]

mono/mini/aot-tests.cs, mono/mini/mini-amd64.c, mono/mini/mini-amd64.h
This PR fixes a couple of issues preventing DYNCALL to work in a couple of scenarios on Windows x64.
Fix incorrect float parameter handling on Winx64 DYNCALL:
The Winx64 calling convention handles parameters in a way that was not correctly implemented in some DYNCALL use cases. When using a method signature like this (double, int, double), the Winx64 ABI dictates that the first parameter goes into first floating point parameter register (XMM0), second parameter goes into second general register (RDX) and third floating point goes into third floating point
parameter register (XMM2). So above call should use registers XMM0, RDX and XMM2, but current DYNCALL implementation will just use next floating-point register, like XMM0, RDX and XMM1 and this will load wrong parameter registers as …
=> Fix a couple of failing DYNCALL scenarios on Windows x64.

mono/mini/exceptions-amd64.c, mono/mini/mini-amd64.h
Using dynamic symbol resolve (LoadLibrary/GetProcAddress) for all unwind info related registration functions enables building the same code on all Windows platforms where JIT is build and included.
=> Add support for dynamic symbol resolve for all JIT unwind info registration functions on Windows

scripts/ci/run-jenkins.sh
We're targeting 10.7 in the bockbuild package build, let's do it in testing builds too.
=> [ci] Add -mmacosx-version-min to OSX builds

scripts/ci/run-test-default.sh
It was fixed by #8497
Fixes #7556
=> [ci] Mono.Profiler.Log tests can run under coop (and hybrid) suspend

mono/mini/mini-llvm.c
Backport of #9322.
/cc @luhenry
=> [2017-12] [llvm] Avoid using the preserveall calling convention on watchos, xcode10 asserts on it.

mono/btls/CMakeLists.txt
These changes will be duplicated on the BoringSSL submodule's side
too; as the options are combined. (Wait for that PR.)
=> Tweaks for AIX in BoringSSL CMake (Mono side)

mono/metadata/decimal-ms.c
This bug has been lurking for four years, being introduced in commit
5b2bb8c9017ab563d7ec819cf249b209c770423e. `BYTE_ORDER != G_BYTE_ORDER`.
Not thoroughly tested, but `System.Decimal` from csharp seems to return
sane results again. (related: is z or AIX CI available for PR checks?
if not, what test suite is `System.Decimal` under?)
Also remove my shoddy workaround from a few months ago, it got the
BCL building, but was incorrect.
cc @nealef (Linux/s390x might have been affected, but maybe not, if glib and glibc had congruent `BYTE_ORDER` and `G_BYTE_ORDER`....)
=> Fix invalid preprocessor check for BE that broke System.Decimal

mono/metadata/image.c, mono/metadata/marshal.c, mono/metadata/metadata-internals.h
depending on `virtual_` and `need_direct_wrapper` we generate slightly
different IL. The interpreter always set `need_direct_wrapper`, but the
JIT doesn't, so this gets problemantic with mixed mode. We need to be
careful when we cache those results.
=> [mini] respect additional flags when caching runtime invoke wrappers

configure.ac, mono/mini/driver.c, mono/utils/mono-state.c, mono/utils/mono-threads-coop.c, mono/utils/mono-threads-coop.h, scripts/ci/run-jenkins.sh
1. If `configure` enables SGen, print the suspend policy (preemptive, cooperative, hybrid) in the summary at the end.
2. Add a way for `configure.ac` to enable hybrid suspend by default based on presets, or arch, etc.  But do not enable it by default on any platform.
3. add a `preemptive-suspend` CI tag that explicitly disables coop and hybrid suspend; explicitly disable hybrid suspend when enabling coop suspend using CI tags.
4. Add `mono_threads_suspend_policy_name()` function that returns a description of the current suspend policy (subject to configure flags and environment variables)
5. Print suspend policy in `mono --version` and MERP error reporting mechanisms.
=> autoconf and CI infrastructure for hybrid suspend

mono/profiler/coverage.c, mono/profiler/log-args.c
similar to https://github.com/mono/mono/pull/9166
=> [profiler] account for nullbyte in allocated buffer in log- and coverageprofiler

mono/utils/mono-threads-state-machine.c
for the same reason as the other cases in this function - if we're in `RUNNING`
or `ASYNC_SUSPEND_REQUESTED` under hybrid suspend we're supposed to cooperatively
suspend.  If we call `backtrace()`, we might block waiting for the low-level
dynamic linker mutex on Linux which may be held by a thread that was
preemptively-suspended already.
=> [checked-build] don't collect state transition backtraces on abort_blocking

mono/metadata/w32file-unix.c
This prevents a test failure when Time Machine partitions are mounted on the
host running the test.
The symptoms are:
```
1) GetDrivesValidInfo (MonoTests.System.IO.DriveInfoTest.GetDrivesValidInfo)
DriveFormat=afpfs
Expected: not Unknown
But was:  Unknown
at MonoTests.System.IO.DriveInfoTest.ValidateDriveInfo (System.IO.DriveInfo d) [0x00045] in /cvs/mono/mcs/class/corlib/Test/System.IO/DriveInfoTest.cs:85 
at MonoTests.System.IO.DriveInfoTest.GetDrivesValidInfo () [0x0000e] in /cvs/mono/mcs/class/corlib/Test/System.IO/DriveInfoTest.cs:73 
at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, …
```
=> Add another Darwin file system

mcs/class/Mono.Security/Mono.Security.X509/X501Name.cs, mcs/class/Mono.Security/Test/Mono.Security.X509/X501NameTest.cs, mcs/class/System/Mono.Btls/MonoBtlsUtils.cs, mcs/class/System/Test/System.Security.Cryptography.X509Certificates/X500DistinguishedNameTest.cs, mcs/class/System/Test/System.Security.Cryptography.X509Certificates/X509Certificate2Test.cs
Extracted from #9250. The SERIALNUMBER name is used on NetFX on Windows 10 (and likely older versions too).
=> System.Security: Fix unit tests to use SERIALNUMBER instead of OID.2.5.4.5.

mcs/class/System.Runtime.Serialization/Makefile, mcs/class/System.Runtime.Serialization/ReferenceSources/JsonFormatReaderGenerator_static.cs, mcs/class/System.Runtime.Serialization/System.Runtime.Serialization_xtest.dll.sources, mcs/class/System.Runtime.Serialization/Test/System.Runtime.Serialization.Json/JsonReaderTest.cs, scripts/ci/run-test-default.sh
Fixes #9332 
Also brings CoreFX xunit tests for System.Runtime.Serialization
Few tests in DataContractJsonSerializer.cs fail but the failures don't relate to my fix. I'll file an issue for them or fix them if they are trivial.
=> [System.Runtime.Serialization] Key should not be null in ReadSimpleDictionary for Dictionary<string, string>

mono/metadata/appdomain.c, mono/metadata/sre-save.c, mono/metadata/w32file-unix.c, mono/metadata/w32file-win32.c, mono/metadata/w32file.c, mono/metadata/w32file.h
It is too easily trashed, e.g. by mono_thread_info_uninstall_interrupt.
See https://github.com/Unity-Technologies/mono/commit/b6f1ba89f7ab285a0990e696e78798f7cf18dafb
Which this should be an alterate fix for, as discussed in https://github.com/mono/mono/pull/9104.
This is a small change, but ultimately we should be able to thread
gint32 *win32error around enough, such as to eliminate the thread local on Unix.
It doesn't appear to take much. Thread locals, it turns out, are not a good mechanism.
They are sensitive to loss as addressed here. They are slower to access than regular globals
or locals. They do have the advantage of "automatic threading through a callgraph", as long
as you are very careful with their use (https://github.com/Unity-Technologies/mono/commit/b6f1ba89f7ab285a0990e696e …
=> Reduce sensitivity to thread local win32 last error.

mcs/class/corlib/CommonCrypto/CommonCrypto.cs, mcs/class/corlib/CommonCrypto/RNGCryptoServiceProvider.cryptor.cs, mcs/class/corlib/System.Security.Cryptography/RNGCryptoServiceProvider.cs, mcs/class/corlib/corefx/Interop.GetRandomBytes.Mono.cs, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/corlib/linux_net_4_x_corlib.dll.exclude.sources, mcs/class/corlib/macos_net_4_x_corlib.dll.exclude.sources, mcs/class/corlib/macos_net_4_x_corlib.dll.sources, mcs/class/corlib/net_4_x_corlib.dll.sources, mcs/class/corlib/unix_net_4_x_corlib.dll.exclude.sources, mcs/class/corlib/win32_net_4_x_corlib.dll.exclude.sources, mcs/class/corlib/winaot_corlib.dll.exclude.sources
* `HashCode` is now enabled in all profiles.
* Added `RNGCryptoServiceProvider` based fallback implementation.
* Added internal `RNGCryptoServiceProvider.GetRandom(byte*,IntPtr)` overload.
* The fallback implementation is enabled by default in `corlib.dll.sources`,
platforms which provide a native implementation need to add it to their
`.exclude.sources`.
=> [corlib]: Enable `HashCode` in all profiles.

mono/mini/mini-llvm.c
Backport of #9322.
/cc @luhenry
=> [2018-04] [llvm] Avoid using the preserveall calling convention on watchos, xcode10 asserts on it.

mono/mini/mini-llvm.c
Backport of #9322.
/cc @luhenry
=> [2018-06] [llvm] Avoid using the preserveall calling convention on watchos, xcode10 asserts on it.

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mono/metadata/icall.c, mono/utils/mono-merp.c, mono/utils/mono-merp.h
This enables the managed code to work with multiple app crash types on MERP, useful as the server side changes. This change was requested from @sgmunn .
=> [runtime] Make merp eventType icall argument

llvm/Makefile.am
Turns out this file was missing.
Haven't tested in-tree llvm from tarballs, I assume it's broken.
Fixes #9456
=> Include build_llvm_config.sh in tarballs

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridViewCell.cs
Implemented like in https://referencesource.microsoft.com/#system.windows.forms/winforms/Managed/System/WinForms/DataGridViewCell.cs
Background: 
With this fix the prototype of XCP-ng Center for Linux works better (Softfork of Citrix XenCenter) -> https://github.com/xcp-ng/xenadmin/issues/23 and https://github.com/xcp-ng/xenadmin/issues/23#issuecomment-401618433
Project: [XCP-ng - XenServer based, Community Powered](https://xcp-ng.org)
=> Return filled FormattedValueType instead of null

mono/metadata/Makefile.am, mono/mini/mini-posix.c, scripts/ci/run-jenkins.sh
fixes regressions introduced by 5e9af502c052 and 2a8fcbd9fe5560de0d4d57d2da6cbb855f284f86. Also adding build targets to CI so we avoid breakages in the future.
parts of this PR need to be backported to `2018-06`
=> [sdks] fix build for watchOS and tvOS

scripts/ci/run-jenkins.sh
=> [sdks] bump timeout for builds on CI

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mono/metadata/icall.c, mono/utils/mono-merp.c, mono/utils/mono-merp.h
This path is not sent to Watson, for the privacy concerned. 
It is the .app that is launched when someone clicks "relaunch" on the MERP dialog box.
=> [runtime] Enable application to register path for MERP restart

mono/mini/mini-arm64.c
=> [2018-06] [arm64] Make OP_CHECK_THIS read only a byte, to prevent unaligned access errors.

mono/mini/mini-arm64.c
=> [2018-04] [arm64] Make OP_CHECK_THIS read only a byte, to prevent unaligned access errors.

mono/mini/mini-arm64.c
=> [2018-02] [arm64] Make OP_CHECK_THIS read only a byte, to prevent unaligned access errors.

mcs/build/Makefile
Backport of #9098.
/cc @lewurm
=> [2018-06] [dist] Ensure gensources.cs is included in tarballs

configure.ac, mono/mini/method-to-ir.c, mono/mini/mini-amd64.c, mono/mini/mini-arm.c, mono/mini/mini-arm64.c, mono/mini/mini-ppc.c, mono/mini/mini-s390x.c, mono/mini/mini-x86.c, mono/mini/mini.h, mono/tests/Makefile.am, mono/tests/split-tailcall-interface-conservestack.cpp, mono/tests/tailcall-interface-conservestack.il, mono/tests/tailcall-interface.cs, mono/tests/tailcall-rgctxb-static.il, mono/tests/tailcall/fsharp-deeptail.il, mono/tests/tailcall/split-fsharp.cpp
Centralize tailcall debugprint.
Tweak tests to account for x86 frame alignment -- this way they pass, and in the real world, we might consume a little stack instead of zero, but not a lot. The test checks for zero.
=> [tailcall] Split up large tests for fine grained enable/disable, instead of large scale disable (F# and interface).

mono/tests/Makefile.am
Fixes https://jenkins.mono-project.com/view/Releases/job/ng-release-generate-rpm-packages/661/console
=> Ensure tailcall tests are in `make dist` tarballs

mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources
backport of https://github.com/mono/mono/pull/9548
=> [2018-06] [corlib] Include all span helpers optimizations (#9548)

mcs/class/System/System.Net.Sockets/Socket.cs
GetCheckedIPs filters out endpoints that do not match the remote endpoint address family, however in the case the remote endpoint is unspecified, we shouldn't do this filtering. Filtering was added in https://github.com/mono/mono/pull/8041
=> Fix issue where GetCheckedIPs filters out addresses, when the AddressFamily is Unspecified

mcs/tools/mono-api-diff/mono-api-diff.cs, mcs/tools/mono-api-diff/mono-api-diff.csproj, mcs/tools/mono-api-diff/mono-api-diff.exe.sources
Rather than always writing to the std out, provide an option to write to a file. This makes things easier for tooling by not requiring `RedirectStandardOutput = true`
=> Add support for an output path in mono-api-diff

mono/metadata/threads.c
The `mono_threads_attach_coop` / `mono_threads_detach_coop` icalls are called from
the wrapper around managed methods that will be called from native code `emit_managed_wrapper_ilgen` https://github.com/mono/mono/blob/cf0895fbb9ebe31c377d5b14101d714005be4d57/mono/metadata/marshal-ilgen.c#L5878-L5886
If the managed method throws an exception, the mono_threads_detach_coop will not
be called, and the checked build `mono_threads_enter_gc_unsafe_region_internal`/`mono_threads_exit_gc_unsafe_region_internal` accounting will be mis-matched which will break later checked mode checks.
(The unbalanced thread state transition is not a problem - the next outermost
exit_gc_unsafe will operate just fine - it's just the checked mode check that's
wrong)
=> [checked,coop] Use unbalanced thread state transitions in mono_threads_attach_coop

mono/metadata/icall.c
This issue was introduced by https://github.com/mono/mono/commit/984f6484666c2ee6fefec949c81fdff1189c9488#diff-eba0fd0052bf3ec9dd60f2f3e90f19e1 which started getting used in Xamarin.Android 8.3.x.
The logger (used by Console.WriteLine on Android) would pass the message string directly to vasprintf, so using anything from the printf formatting logic (like url-encoded strings) would at best print random garbage, and at worst would crash, depending on what's located on the stack at that moment.
Fixes https://github.com/xamarin/xamarin-android/issues/1951
=> Fix LogcatTextWriter writing garbage and/or crashing

mono/mini/mini-posix.c, mono/utils/mono-merp.c
Note that all of these changes that will change control flow and symbol visibility live behind an#ifdef TARGET_OSX. Only OSX CI need be considered here.
=> [runtime] Make sigterm dumper send file to merp

sdks/wasm/debug.html, sdks/wasm/library_mono.js
The mono_load_runtime_and_bcl allows upstream to remap requests and report download progress.
This cb semantics might change in the future when we implement more agressive loading.
=> [wasm] Remove dead code and add fetch callback to mono_load_runtime_and_bcl.

configure.ac, mcs/class/corlib/System/Delegate.cs, mcs/class/corlib/Test/System/DelegateTest.cs, mono/metadata/object-internals.h, mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c, mono/mini/interp/mintops.def, mono/mini/interp/transform.c
Backport of https://github.com/mono/mono/pull/9029 and https://github.com/mono/mono/pull/9409. The former makes backporting of the latter easier.
=> [2018-06] interp delegate fixes

mcs/class/corlib/System/TermInfoReader.cs
16bit vs. 32bit only applies for offsets, not for actual entries in the
file format.
Fixes https://github.com/mono/mono/issues/8340
before / after:
=> [TermInfo] fix reading integer value for new file format

configure.ac, mono/mini/driver.c, mono/mini/trace.c, mono/utils/gc_wrapper.h, mono/utils/mono-state.c, mono/utils/mono-threads.c, mono/utils/mono-tls.c, mono/utils/mono-tls.h, winconfig.h
instead of slower TlsGetValue / TlsSetValue
Alternative proposal would be use fiber locals, which we do sometimes.
=> Use __declspec(thread) with Visual C++, and __thread with Win32/gcc,

mono/mini/interp/interp.c, mono/mini/interp/transform.c
removes this warning in e.g. mcs-tests:
> Object.CallSite.Target: Store local stack type mismatch 0 1
> Object.CallSite.Target: Store local stack type mismatch 0 1
> Object.CallSite.Target: Store local stack type mismatch 0 1
> Object.CallSite.Target: Store local stack type mismatch 0 1
> Object.CallSite.Target: Store local stack type mismatch 0 1
> Object.CallSite.Target: Store local stack type mismatch 0 1
and fixes those warnings in the build
> interp/interp.c:3924:13: warning: unused variable 'valuetype_this' [-Wunused-variable]
>                         stackval valuetype_this;
>                                  ^
> interp/interp.c:3926:13: warning: unused variable 'retval' [-Wunused-variable]
>                         stackval retval;
>                                  ^
> 2 …
=> [interp] fix stack mismatch warning around ldlen and a C compiler warning

mono/mini/mini-runtime.c
the caller will check `error` anyway. It allows the machinery to try the
interpreter instead.
=> [mini] return gracefully from compile_special if a method can not be compiled

configure.ac, mono/metadata/w32file-unix.c
Rebase of #9038 with added fix for the failing unit tests. Note that there's a race condition in the check between `source file == destination file` and the `copyfile` call, but a similar race condition already exists there in the current code except the outcome is different.
=> [MacOS] On Mac, use the copyfile API to copy files

mcs/mcs/cs-parser.jay, mcs/mcs/statement.cs, mcs/tests/ver-il-net_4_x.xml
=> [mcs] Don't wrap exception expression in contextual return.

mono/metadata/w32process-unix.c
For coop, this loop needs to be a separate function. This change reduces that. Or so I thought -- that isn't true, but the change is still ok.
=> Remove excess code -- strings are already nul terminated.

mcs/class/corlib/corlib_xtest.dll.sources
=> [2018-04] [corlib] Disable broken corefx tests

man/mono.1, mono/utils/mono-threads-coop.c
Set to one of `preemptive`, `coop` or `hybrid`.
Unlike the old `MONO_ENABLE_COOP`, `MONO_ENABLE_COOP_SUSPEND`,
`MONO_ENABLE_HYBRID_SUSPEND`, the value of `MONO_THREADS_SUSPEND` will take
priority over the configure flags default.
For compatability the old environment variables will be respected if neither
`MONO_THREADS_SUSPEND` nor a configure flag was set.  A warning will be emitted
unless `MONO_THREADS_SUSPEND` is also set.  (Rationale: maybe the environment set both
because they're not sure which version of Mono they will be running - so don't
nag them).
----
Why do we need this?
With the old system there was no way to compile Mono to use, for example, hybrid suspend by default, and then override at runtime to use preemptive suspend.
----
Questions:
Maybe I should ditch the old …
=> New MONO_THREADS_SUSPEND env var to select suspend policy

configure.ac, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/referencesource/mscorlib/system/globalization/charunicodeinfo.cs
Temporarily switch back to ref-source impl for `CharUnicodeInfo` which contains a few special BE patches while I am trying to upstream them.
Fixes #9684
=> Revert CharUnicodeInfo to reference-sources (Big Endian issue)

man/mono.1, mono/mini/mini.c, mono/tests/Makefile.am, mono/tests/verbose.cs
Given a method spec which looks like:
`MainClass:Do(int,int,int)`
Via f024e820a025aacc1cf80eb82a8aee4552c3ac11 the code would match 3 methods:
`MainClass:Do(int`, `int`, `int)`, crashing the runtime.
Accept the multiple method matches via `;`, rather than `,`.
Now, the behaviour is changed so:
`MainClass:Do(int,int,int);MainClass:Do(int,int)`
Get parsed as:
`MainClass:Do(int,int,int)`
`MainClass:Do(int,int)`
Fixing the behaviour so it would actually support commas, it would mean not to use g_splitenv, which would complicate the PR.
=> Fix up behaviour of verbose method with arguments

mcs/class/System/Test/System.Security.Cryptography.X509Certificates/X509Cert20Test.cs, mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Certificate.cs
They were replaced with PNSE in https://github.com/mono/mono/pull/9650
but that broke xUnit 2.4.0.
=> [corlib] Bring back serialization ctors/methods for X509Certificate

mono/metadata/custom-attrs-internals.h, mono/metadata/custom-attrs.c, mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c
Return objects from load_cattr_value () using an additional out parameter. Add a variant of
mono_reflection_create_custom_attr_data_args () which can only decode a subset of cattr types, but
it doesn't allocate any objects. Use this in marshal.c/marshal-ilgen.c to avoid allocating objects
while decoding FixedBufferAttribute and UnmanagedFunctionPointerAttribute.
=> [runtime] Refactor cattr decoding.

mcs/build/library.make, mcs/class/System.Data/Makefile, mcs/class/System.Runtime.Serialization/Makefile, mcs/class/System.Web/Makefile, mcs/class/System.XML/Makefile, mcs/class/System/Makefile
https://github.com/mono/mono/commit/0f0e31842f1f394c4e95d3726c20af547e706278 added a new pipes_pns.sources file but we forgot to add it to EXTRA_DISTFILES so it gets included in the tarball.
Given that this happens almost all the time when we add a new .sources file we should just always include all *.sources
=> [bcl] Include all .sources files in the tarball

packaging/MacSDK/fsharp.py, packaging/MacSDK/patches/fsharp-debug-pinvoke-fix.patch
It wasn't possible to debug any F# app that contained PInvokes.
The F# compiler omitted MethodDebuginformation for PInvokes which in
turn caused Mono to fail on an assertion.
```
* Assertion at metadata.c:1117, condition `idx < t->rows' not met
```
=> Apply F# portable pdb debug fix for pinvokes & bump

llvm/SUBMODULES.json
Fixes https://github.com/mono/mono/issues/9750.
=> [llvm] Bump llvm to release_60/fc854b8ec5873d294b80afa3e6cf6a88c5c48886.

mono/mini/decompose.c, mono/mini/local-propagation.c, mono/mini/method-to-ir.c, mono/mini/mini-llvm.c, mono/mini/mini-mips.c, mono/mini/mini.c, mono/mini/mini.h
Instead of accessing them using the inst_ls_word/inst_ms_word macros which use the union in MonoInst.data, access them normally using
MonoInst.Data.i8const.
=> [jit] Clean up the handling of the lower/higher parts of long values on 32 bit platforms.

sdks/wasm/Makefile, sdks/wasm/dotnet_support.js, sdks/wasm/driver.c
This adds additional ability to perform unmarshalled calls for advanced but high-performance shared-memory interop.
* Note: * This is only safe in Blazor's case because of its exact usage patterns.
=> Add support for Blazor custom interop support.

mono/metadata/threads.c
This fix is supposed to fix a big performance issue exposed by MERP. The preexisting race doesn't appear to be causing any instability currently, but it looks like it could if hit wrong.
== 
Edit: Elaboration
The function collect_threads returns a pointer to the thread, not a handle. We do pin already. This reference is freed when the thread is detached from the runtime. There is no guarantee that the unmanaged functions interacting with these threads will not run concurrently with threads being detached. In fact, one can observe that being the case when using MERP. 
When we being a dump, we collect a list of active threads. We walk them, and signal each thread one-by-one. While dumping one thread, it is not uncommon to find that a couple of other threads die. We run into a timeout while …
=> [runtime] Make collect_threads helper pin MonoInternalThread objects

mono/metadata/w32file-unix.c
```
w32file-unix.c:2361:7: warning: unused variable 'ret_utime' [-Wunused-variable]
gint ret_utime;
^
w32file-unix.c:2358:15: warning: unused variable 'dest_fd' [-Wunused-variable]
gint src_fd, dest_fd;
^
w32file-unix.c:2358:7: warning: unused variable 'src_fd' [-Wunused-variable]
gint src_fd, dest_fd;
^
w32file-unix.c:2362:7: warning: unused variable 'syscall_res' [-Wunused-variable]
gint syscall_res;
^
4 warnings generated.
```
=> w32file-unix.c fix warnings about unused locals

mcs/class/System.Drawing/System.Drawing/Graphics.cs, mcs/class/System.Drawing/System.Drawing/macFunctions.cs
Carbon implementation now throws exception instead of crashing in the mismatched p/invoke calls.
Cocoa implementation now support 64-bit mode and uses the handle of `NSView` that is passed in instead of relying on `NSGraphicsContext.CurrentContext`. It also fixes handling of flipped views.
Requires up to date libgdiplus.
=> Fix System.Drawing on 64-bit macOS.

mcs/class/corlib/corert/Decimal.cs
The version imported and attempted to patch didn't work fully. This
preserves the .NET representation while converting if directives to
runtime checks, which CoreCLR inlines.
Testing was done poking some values in the REPL and running some
test suites (System.Json, System.Decimal) that broke as a result.
mcs should also properly handle constants; again, the "bits" inside
are consistent with amd64, and just converted as needed.
Unless I fucked up, should fix #9772.
=> Really fix CoreR[FT] version of System.Decimal for big endian

mcs/class/corlib/LinkerDescriptor/mscorlib.xml
Fixes those failures on Xamarin.iOS:
> 2018-07-30 21:16:19.931 monotouchtest[49618:80799179] error: * Assertion at /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/external/mono/mono/metadata/object.c:7896, condition 'init_message_method != NULL' not met
> 2018-07-30 21:16:19.931 monotouchtest[49618:80799179] critical: Stacktrace:
>
> 2018-07-30 21:16:19.932 monotouchtest[49618:80799179] critical:   at <unknown> <0xffffffff>
> 2018-07-30 21:16:19.932 monotouchtest[49618:80799179] critical:   at (wrapper managed-to-native) object.__icall_wrapper_mono_delegate_begin_invoke (object,intptr) <0x00012>
> 2018-07-30 21:16:19.932 monotouchtest[49618:80799179] critical:   at (wrapper delegate-begin-invoke) <Module>.begin_invoke_IAsyncResult__this___AsyncCallback_object …
=> [LinkerDescriptor] remove remoting feature from MonoMethodMessage

mcs/class/corlib/LinkerDescriptor/mscorlib.xml
Backport of #9820.
/cc @lewurm
=> [2018-06] [LinkerDescriptor] remove remoting feature from MonoMethodMessage

mono/utils/mono-state.c
We could alternatively return non-const, but the overwrite seems gratuitious, assuming the length fits in 31 bits.
=> [cxx] g_get_assertion_message returns const; do not write over it

mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/mini/debugger-agent.c
VSTU will try to invoke a generic (uninflated) method in certain
situations, which was causing the Mono debugger to assert and crash
Unity. Added a check for this situation before the invoke so the
debugger can return an error to the client. Previously, this case
wasn't caught until the method was in JIT compilation, which will
assert when this situation is detected.
=> Add check for a generic method when invoking in debugger

mono/mini/debugger-agent.c
This assert was causing Unity to crash when trying to view a local
string variable in the debugger with invalid characters.
=> Remove assert when retrieving value of string with invalid chars

mcs/build/profiles/basic.make
Right now we have a race condition where parallel make on CI will barge ahead and start building things before monolite+basic-profile-check have completed, which results in some weird behavior - gensources silently fails to run, etc. Testing some possible fixes for this.
=> Fix race condition where parallel builds will continue before we are actually done installing monolite

mono/metadata/class.c
We have some example code that gets all the fields via reflection
```foreach (var field in type.GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public))```
Then later when we try to get the field offset, the type hasn't been initialized (unless your C# code does something earlier that initializes the type).
type.GetFields calls mono_class_get_fields_lazy, which doesn't setup all the field info (in this case the offset)
=> Fix issue where get offset could return 0 when the type is uninitialized

mono/mini/interp/mintops.def
=> [interp] distinguish MINT_CALLI_NAT_FAST from MINT_CALLI_NAT in debug output

mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources
Part of #9660.
Previously ExceptionHandlingClauseOptions was placed in referencesource  [methodbody.cs](https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/reflection/methodbody.cs) where other content is hidden by `#if !MONO` condition.
=> [System.Reflection] CoreFX import for ExceptionHandlingClauseOptions

mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLite3.cs
Backport of https://github.com/mono/mono/pull/9800
`MonoCertificatePal.cs` does not exist in this branch yet.
=> [2018-04] Fix comparison of IntPtr with null in Mono

mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLite3.cs
Backport of https://github.com/mono/mono/pull/9800
`MonoCertificatePal.cs` does not exist in this branch yet.
=> [2018-06] Fix comparison of IntPtr with null in Mono

configure.ac, mono/metadata/sgen-mono.c, mono/mini/Makefile.am.in, mono/mini/driver.c, mono/utils/mono-threads-coop.c, mono/utils/mono-threads-coop.h, sdks/builds/android.mk, sdks/builds/ios.mk
Use hybrid suspend by default on x86 and amd64 OSX, Windows and Linux.
Pass `--disable-hybrid-suspend` to configure to disable at build time, or set
the enrivonment variable `MONO_THREADS_SUSPEND=preemptive` when running Mono to use preemptive suspend (the previous default).
Pass `--disable-hybrid-suspend --enable-cooperative-suspend` to configure
cooperative suspend at build time.
=> [coop] Turn hybrid suspend on by default on desktop platforms

mono/metadata/w32file-unix.c
untested so far on i, seems to work on AIX:
```
csharp> System.IO.DriveInfo.GetDrives().Select(x => $"{x.Name}: {x.DriveFormat} {x.DriveType}")
{ "/: jfs2 Fixed", "/usr: jfs2 Fixed", "/var: jfs2 Fixed", "/tmp: jfs2 Fixed", "/home: jfs2 Fixed", "/admin: jfs2 Fixed", "/proc: procfs Ram", "/opt: jfs2 Fixed", "/var/adm/ras/livedump: jfs2 Fixed" }
```
=> System.IO.DriveInfo for AIX

mono/mini/mini-llvm.c
=> [2018-06] [llvm] Fix OP_ABSF.

mono/mini/method-to-ir.c
The issue is that for large enough methods it is relatively easy to get an overflow of 'inline_costs', that will trigger negative value check later in this function, leading to 'Method too complex' exception. The reason for that obviously is that every next call get increasing penalty all the time, as 10 * (n - 1), and that accumulates fast enough when thousands of calls are involved.
=> [mini] Increase inline cost linearly to number of calls.

mcs/class/corlib/System.Globalization/CultureInfo.cs
Every different locale getter in unmanaged attempts to
cache the result from this icall. Some of them fail to do so in a manner
that is correct.
CFLocaleCopyCurrent (); in get_darwin_locale ends up being called
thousands of times. In an app with a few dozen Console.WriteLines, it's easy to see
18mb of leaked memory through this.
Rather than trying to fix them all in unmanaged in a perfect manner, I
thought it better to also avoid the icall overhead and to cache it in
C#.
Without this fix, a memory traffic stress test (debian shootout's pidigits) leads to 66% of
memory pressure being due to this  icall. With this fix, it is 4.3%.
If this caching is wrong for correctness reasons (we expect it to change?),
I would like to point out that we have similar caching done in unmanaged
and that we …
=> [runtime] Cache culture locale name in managed

mono/metadata/class.c
Was accidentally removed in 3780114620cd.
=> Add missing return from the function.

configure.ac, mono/dis/main.c, mono/metadata/appdomain.c, mono/metadata/assembly-internals.h, mono/metadata/assembly.c, mono/metadata/attach.c, mono/metadata/coree.c, mono/metadata/domain.c, mono/metadata/icall.c, mono/metadata/mono-security.c, mono/metadata/reflection-internals.h, mono/metadata/w32socket.c, mono/mini/driver.c, mono/tests/Makefile.am, mono/tests/assembly-load-reference/Makefile.am, mono/tests/assembly-load-reference/README, mono/tests/assembly-load-reference/mainanddep/LoadFileMain.cs, mono/tests/assembly-load-reference/mainanddep/LoadFromMain.cs, mono/tests/assembly-load-reference/samedir/LoadFileMain.cs, mono/tests/assembly-load-reference/samedir/LoadFromMain.cs, mono/tests/assembly-load-reference/separatedir/LoadFileMain.cs, mono/tests/assembly-load-reference/separatedir/LoadFromMain.cs, mono/tests/assembly-load-reference/src/Dep.cs, mono/tests/assembly-load-reference/src/Mid.cs, mono/utils/mono-path.c, mono/utils/mono-path.h, tools/pedump/pedump.c
The assembly loader uses assembly load contexts to determine how referenced assemblies and explict alls to `Assembly.Load`, `Assembly.LoadFrom`, and `Assembly.LoadFile` are resolved.
Previously the assembly load context was determined purely from how an assembly load request originated: for referenced assemblies it was determined by the requesting assembly; for `Assembly.Load` it was the default context, for `LoadFrom` the LoadFrom context, and for `LoadFile` the individual (or "no context") assembly context.
However that doesn't match exactly the observed behavior of .NET Framework.
So this PR adds additional complications:
1. If `Assembly.Load` is called by an executing assembly in `LoadFrom` context, try to load the given assembly in LoadFrom context and probe in the executing …
=> [loader] Determine assembly load context from path

configure.ac, mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs, mcs/class/corlib/ReferenceSources/RuntimeType.cs, mcs/class/corlib/System.Runtime.Remoting/RemotingServices.cs, mcs/class/corlib/Test/System/TypeTest.cs, mcs/class/referencesource/mscorlib/system/rttype.cs, mono/metadata/class-internals.h, mono/metadata/icall.c, mono/mini/debugger-agent.c
e.g (PropertyName*). This matches the refsrc behavior.
I originally found the issue testing an application that used the Telerik OpenAccess ORM.  For certain properties it used the type.GetField("Blah*", ..., ...) in order to get additional info.  It was there that I saw the need for this PR.
=> [corlib] Modified most of the reflection member lookup methods to support prefix searches

configure.ac, mono/dis/main.c, mono/metadata/appdomain.c, mono/metadata/assembly-internals.h, mono/metadata/assembly.c, mono/metadata/attach.c, mono/metadata/coree.c, mono/metadata/domain.c, mono/metadata/icall.c, mono/metadata/mono-security.c, mono/metadata/reflection-internals.h, mono/metadata/w32socket.c, mono/mini/driver.c, mono/tests/Makefile.am, mono/tests/assembly-load-reference/Makefile.am, mono/tests/assembly-load-reference/README, mono/tests/assembly-load-reference/mainanddep/LoadFileMain.cs, mono/tests/assembly-load-reference/mainanddep/LoadFromMain.cs, mono/tests/assembly-load-reference/samedir/LoadFileMain.cs, mono/tests/assembly-load-reference/samedir/LoadFromMain.cs, mono/tests/assembly-load-reference/separatedir/LoadFileMain.cs, mono/tests/assembly-load-reference/separatedir/LoadFromMain.cs, mono/tests/assembly-load-reference/src/Dep.cs, mono/tests/assembly-load-reference/src/Mid.cs, mono/utils/mono-path.c, mono/utils/mono-path.h, tools/pedump/pedump.c
This is a backport of #9858 to `2018-06`
Addresses #9753 #9542 #8575
=> [2018-06][loader] Determine assembly load context from path

sdks/builds/download-llvm36.sh, sdks/builds/ios.mk, sdks/versions.mk
backport of https://github.com/mono/mono/pull/9889
=> [2018-06] [sdks] Switch the 32 bit cross compilers back to the old llvm 3.6, the new version has too many problems.

sdks/README.md, sdks/wasm/binding_support.js, sdks/wasm/bindings-test.cs, sdks/wasm/bindings.cs, sdks/wasm/driver.c, sdks/wasm/test.js
The following PR enhances the WASM bindings.
- Add JSObject property getter and setter
- Make JSObject disposable
- The dispose will remove the object from the tracked object list and will allow the reference counter to be recycled later.
- By keeping a recycled list of references and reusing those will keep the tracked objects array from growing out of hand.
- Modify the way the bindings init works by passing in of the Assembly and Class `[asm]namespace.class`.  This allows for clients to provide their own implementations if need be.
- Fix a problem with Promise implementation that caused intermittent NullReferenceExceptions and Memory Exceptions.
=> Wasm Bindings enhancements

llvm/build.mk, sdks/builds/llvm.mk
Backport of #9919.
/cc @vargaz
=> [2018-08] [sdks] Rename LLVM_VERSION make var to LLVM_RELEASE, LLVM_VERSION is already used by versions.mk.

mono/metadata/threads.c
Observed pthread_getschedparam taking a lock on OSX
=> [threads] switch to GC Safe around pthread calls in mono_thread_internal_set_priority

configure.ac, mono/metadata/object-internals.h, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/mini/mini-exceptions.c, mono/mini/mini-posix.c, mono/mini/mini-runtime.h, mono/utils/mono-state.c, mono/utils/mono-state.h, sdks/builds/runtime.mk, winconfig.h
Everything seemed to be working before on CI before. Let's add the jenkins hooks for the crash files with this PR too.
=> Enable mono-state-based telemetry for crashing on CI

mono/metadata/threads.c
=> [2018-08] [threads] switch to GC Safe around pthread calls in mono_thread_internal_set_priority

mono/utils/lock-free-alloc.c
We might as well just have one more portable form here.
=> Remove gratuitous ifdef and variable-length array.

mono/utils/mono-compiler.h, mono/utils/mono-publib.h
Consider also putting it at start of prototype instead of end, like MONO_API.
Extern "C" recently added to MONO_API broke this.
=> Remove extern "C" from MONO_LLVM_INTERNAL.

mono/utils/mono-compiler.h, mono/utils/mono-publib.h
Backport of #9939.
/cc @jaykrell
=> [2018-08] Remove extern "C" from MONO_LLVM_INTERNAL.

mono/metadata/threads.c, mono/utils/mono-error.c
The icall was converted to use `HANDLES()`, so the icall wrapper will set the
pending exception from the `MonoError`.  If the icall does it, too, the second
use (in the wrapper) will assert that the `MonoError` is being reused after
cleanup without being reinitialized.
Also add an assertion in `mono_error_get_message` that we're not trying to get a
message from a cleaned up `MonoError`.
Fixes https://github.com/mono/mono/issues/9935
=> [coop] Thread.JoinInternal should not call mono_error_set_pending_exception

mono/metadata/gc.c, mono/metadata/threads.c
Alternate method of fixing: 
https://github.com/mono/mono/pull/9486
=> [runtime] Add a reference queue cleanup for MonoInternalThread

sdks/wasm/Makefile, sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs, sdks/wasm/Mono.WebAssembly.DebuggerProxy/Mono.WebAssembly.DebuggerProxy.csproj, sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs, sdks/wasm/Mono.WebAssembly.DebuggerProxy/WsProxy.cs, sdks/wasm/ProxyDriver/Program.cs, sdks/wasm/ProxyDriver/ProxyDriver.csproj, sdks/wasm/ProxyDriver/Startup.cs, sdks/wasm/README.md
This imports github.com/kumpera/ws-proxy into mono.
It facilitates distribution and coordination of upstream as there's a clean version connect between the two bits.
The proxy is currently version locked with the runtime.
=> [wasm] Import the debugger proxy and split it into a pair of projects.

Directory.Build.rsp
By default ```msbuild bcl.sln``` will fail because of our non-standard platform names and the need to restore nuget packages. Add a default response file so it just works. (Response files can be suppressed)
=> Add default msbuild parameters so 'msbuild bcl.sln' will succeed

mono/metadata/w32file-unix.c
Noticed this today when the corlib test which checks for unknown filesystems failed. Turned out it was because of a .dmg I had mounted:
```
$ mount | grep nullfs
/Volumes/Skype Meetings App/Skype Meetings App.app on /private/var/folders/cs/kt8x25p14g9dlk_p192rd7th0000gn/T/AppTranslocation/957CCB05-C113-4897-9C80-700C2CE4809E (nullfs, local, nodev, nosuid, read-only, noowners, quarantine, nobrowse, mounted by alexander)
```
=> [metadata] Add nullfs to list of recognized filesystems

libgc/include/gc.h, libgc/include/gc_gcj.h, libgc/include/gc_local_alloc.h, libgc/include/gc_pthread_redirects.h, libgc/include/private/gc_locks.h, libgc/include/private/gc_priv.h, libgc/mark.c
Add extern "C" correctly to boehm so it can be C, and used by C++.
Change char* to void*  for use by C++ callers.
This tracks mainline but just barely.
https://github.com/ivmai/bdwgc/blob/ae3d724f3645af119e1b2c2cefbb71c97d467546/mark.c#L1337
https://github.com/ivmai/bdwgc/commit/f4fbef0f7f0e3446856d2177535080158e16e403#diff-74e77959a62b8a560274f69789f50a94R1623
https://github.com/ivmai/bdwgc/commit/a825a2d612e749c08c24fca0f11eb2a523ce3b6b
etc.
=> [cxx] [boehm] extern "C" and interface void*  instead of char* for use by  C++

mono/mini/debugger-agent.c
Fixes https://github.com/mono/mono/issues/8848.
Fixes https://github.com/mono/mono/issues/9262.
Fixes https://github.com/mono/mono/issues/8627.
Backport of https://github.com/mono/mono/pull/9983.
=> [sdb] Disable an assert to avoid breaking debugging.

mono/tests/Makefile.am
The test times out due to an issue in hyrbid suspend.  Turn off the test
temporarily while we work on a solution.
https://github.com/mono/mono/issues/9959
https://github.com/mono/mono/issues/9921
=> [ci] Disable sgen-new-threads-collect.exe until #9959 is addressed

sdks/wasm/binding_support.js, sdks/wasm/bindings-test.cs, sdks/wasm/driver.c
This PR adds support for marshalling the high performance TypedArray and ArrayBuffer.
-  The ArrayBuffer object is used to represent a generic, fixed-length raw binary data buffer.   More Info ---> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays#ArrayBuffer
-  JavaScript typed arrays are array-like objects and provide a mechanism for accessing raw binary data. (...).  More Info ---> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays
-  Some examples of API's that use these are Fetch, WebGL, Canvas, Web Audio API, XMLHttpRequests, WebSockets, Web Workers, Media Source API and File APIs.
|        |           |  |  |
|------------|-------------|-----|-----|
| ArrayBuffer		| uint8_t | byte[] | byte or Byte (unsigned byte)  |
| Int8Array 		| int8_t	| …
=> Add support for marshalling ArrayBuffer and TypeArrays

configure.ac, mono/eglib/giconv.c, mono/eglib/gunicode.c
iconv in eglib was broken due to a broken define. Also fix linking
of iconv when iconv isn't in libc.
Also remove the usage of a GNU libcharset specific function and rely
on a standard POSIX function that outputs the same value on every
modern Unixoid I've tried it on. (Ubuntu/macOS/i/FreeBSD)
This comment explains a lot of things for the latter:
```c
/*
* This function used used to use the "locale_charset" call in
* libiconv's libcharset library. However, this isn't always
* available on some systems, including ones with GNU libc. So,
* instead use a function that's a standard part of POSIX2008.
*
* nl_langinfo is in POSIX2008 and should be on any sane modern
* Unix. With a UTF-8 locale, it should return "UTF-8" - this
* has been verified with Ubuntu 18.04, FreeBSD 11, and i 7.3.
*
* The …
```
=> Fix iconv in eglib, remove GNU libiconv-ism

mono/metadata/object.c
(Commit attributed to @kumpera because he wrote this quick fix, thanks!)
Fixes #10070
=> Fix mono_string_from_blob for big endian systems

mono/metadata/boehm-gc.c, mono/metadata/gc-internals.h, mono/metadata/null-gc.c, mono/metadata/sgen-mono.c, mono/sgen/sgen-cardtable.c, mono/sgen/sgen-gc.c, mono/sgen/sgen-gc.h
instead of a void*. And add const on the source of a memcpy.
=> Strengthen the type of mono_gc_get_range_copy_func -- return a typed function pointer.

mono/mini/aot-compiler.c, mono/mini/aot-compiler.h, mono/mini/mini-llvm.c
LLVM was using the helper for the abandoned prototype linkonce work that
much predated when I picked up the project.
This is a problem because it can lead to aot-compiler thinking a method
is dedupable, while llvm thinking it's not. When this happens, the
symbol does not have the Assembly baked into it's name to ensure
uniqueness.
=> [runtime] Make mini-llvm use only mono_aot_can_dedup

mono/eglib/gmarkup.c, mono/metadata/mono-config.c
https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/3652/parsed_console/log.html
invalid enum type
!19255 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus, file: !7355, producer: "clang version 5.0.0  (emscripten 1.37.36 : 1.37.36)", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !19256, retainedTypes: !19257, imports: !19263)
!19256 = !{!7363, !6973, !168}
!7363 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !7364, line: 192, size: 128, elements: !7365, identifier: "_ZTS10ParseState")
/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/builds/toolchains/emsdk/clang/e1.37.36_64bit/llvm-link: error: linked module is broken!
=> [cxx] Types need to be unique in Wasm.

mono/metadata/icall-def.h
Functions added here https://github.com/mono/mono/commit/58efe9419268250709a6694abfa519b9b5d2c05c#diff-eba0fd0052bf3ec9dd60f2f3e90f19e1R8483
but icall-def.h entries missed.
Might need to backport to 8/2018 but let's get it to master first.
=> Move icalls from utils to metadata.

mcs/class/corlib/Test/System.Reflection/ParameterInfoTest.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/4617.
=> [bcl] Disable a test which fails with linking.

mono/metadata/w32file-unix.c
Alternative to #10008.
Note that `copyfile` is completely user-mode API implemented in `/usr/lib/system/libcopyfile.dylib`. As you can see in the [source code](https://opensource.apple.com/source/copyfile/copyfile-146.30.2/copyfile.c.auto.html) in the `copyfile_data` method it does exactly the same read+write loop as Mono and offers no performance benefits by itself.
Someone in Apple decided to break the `copyfile` API in macOS 10.13.2 by cloning simlinks instead of targets despite the fact that passed in flags do not include `COPYFILE_NOFOLLOW_SRC`. The reason for the change is also completely bogus - we don't support copying directories, so let's not follow symlinks because they could point to directories. Well, just before calling `clonefile` they check if the source is a link, so they …
=> Use clonefile instead of copyfile on macOS.

configure.ac
Missed in https://github.com/mono/mono/commit/e26c958f3b8bf0670862b982b37464b5c313f966.
=> bump corlib

mono/metadata/class.h, mono/metadata/object.h
Backport of #9884.
/cc @jaykrell
=> [2018-08] [cxx] MONO_API before MONO_RT_EXTERNAL_ONLY per 58efe9419268250709a6694abfa519b9b5d2c05c.

mono/metadata/threads.h
Backport of #9964.
/cc @jaykrell
=> [2018-08] [cxx] One more MONO_API ahead of MONO_RT_EXTERNAL_ONLY.

mono/metadata/mono-security-windows.c
https://jenkins.mono-project.com/job/x/12802/parsed_console/log.html
ves_icall_System_Security_Principal_WindowsImpersonationContext_DuplicateToken(gpointer, MonoError*)':
mono-security-windows.c:214:62: error: invalid conversion from 'int (*)(int)' to 'gpointer {aka void*}' [-fpermissive]
return DuplicateToken (token, SecurityImpersonation, &dupe) ? dup : NULL;
^
The code is confusing the local variable dupe with an 'e' at the end
with the function dup.
=> [cxx] Fix bug with local variable dupe and global function dup.

mono/mini/interp/interp.c, mono/tests/Makefile.am
EH still uses the original ip for determining whether there are any abort protected blocks to be exited, once the frame is unwinded.
Fixes delegate2.exe
=> [interp] Restore frame ip after running finally handler

mcs/class/System/System.Diagnostics/Process.cs
Dispose rejected ones.
This is https://github.com/mono/mono/issues/10143 and fix is from there.
I considered nulling skipped array elements, and then the tail, to help the GC, but I don't think it really helps, right?
Fixes https://github.com/mono/mono/issues/10143
=> Fix process leak in process enumeration.

mono/metadata/threads.c
Now that https://github.com/mono/mono/pull/9809 is merged so this won't dereference freed objects, I added a speed increase of the timeout. 
Making a test branch first to get a package to make sure this fix works. Don't merge until I've confirmed so.
=> [runtime] Speed-up MERP timeout

mcs/class/System.Xml.Linq/Test/System.Xml.Schema/ExtensionsTest.cs
macOS 10.14 introduces a Network framework, which means Xamarin.Mac now has a Network namespace.
This conflicts with 'using Network = System.Net':
> mono/mcs/class/System.Xml.Linq/Test/System.Xml.Schema/ExtensionsTest.cs(97,27): error CS0576: Namespace '<global namespace>' contains a definition conflicting with alias 'Network'
so just remove the using and use the full 'System.Net' namespace instead.
=> [System.Xml.Linq] Fix namespace conflict with new Xamarin.Mac namespace in test code.

mcs/class/System.Xml.Linq/Test/System.Xml.Schema/ExtensionsTest.cs
=> [2018-08] [System.Xml.Linq] Fix namespace conflict with new Xamarin.Mac namespace in test code.

mcs/class/System.Xml.Linq/Test/System.Xml.Schema/ExtensionsTest.cs
=> [2018-06] [System.Xml.Linq] Fix namespace conflict with new Xamarin.Mac namespace in test code.

mcs/class/System.Xml.Linq/Test/System.Xml.Schema/ExtensionsTest.cs
=> [2018-04] [System.Xml.Linq] Fix namespace conflict with new Xamarin.Mac namespace in test code.

mcs/class/System.Xml.Linq/Test/System.Xml.Schema/ExtensionsTest.cs
=> [2018-02] [System.Xml.Linq] Fix namespace conflict with new Xamarin.Mac namespace in test code.

mcs/class/corlib/System.Runtime.InteropServices.RuntimeInformation/RuntimeInformation.cs, mono/metadata/icall-def.h, mono/metadata/icall.c
* For ProcessArchitecture, use the DllMap arch of the runtime.
* For OSArchitecture, make an educated guess combining ProcessArchitecture and Environment.Is64BitOperatingSystem.
* For non-Intel/ARM architectures, (supported by Mono and not on the chopping block are PPC32/64, z, and WebAssembly) please dogpile onto dotnet/corefx#30706.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=42403
=> Detect Arm/Arm64 in RuntimeInformation

mono/metadata/class.c, mono/tests/Makefile.am, mono/tests/generic-unmanaged-constraint.cs
Generic pointer types are encountered with 'unmanaged' constraint.
Fixes #10144
=> Properly inflate pointer types in inflate_generic_type. 

mono/mini/mini-llvm.c
Backport of #9322.
/cc @luhenry
=> [2018-02] [llvm] Avoid using the preserveall calling convention on watchos, xcode10 asserts on it.

mono/metadata/dynamic-image-internals.h, mono/metadata/dynamic-image.c, mono/metadata/dynamic-stream-internals.h, mono/metadata/dynamic-stream.c, mono/metadata/sre-encode.c, mono/metadata/sre-save.c
=> Change mono_dynamic_image_add_to_blob_cached and mono_dynstream_add_data to accept gconstpointer instead of char* or const char* -- fewer casts.

mono/metadata/w32process-unix-bsd.c, mono/mini/driver.c
Should fix process-leak test on AIX, maybe more. Also tested that it fixes the
same behaviour on FreeBSD. Other OSes may be affected; consult and test with the
files `w32process-unix-*.c`.
From comments:
```c
/*
* XXX: verify if other OSes need it; many platforms seem to have it so that
* mono_w32process_get_path -> mono_w32process_get_name, and the name is not
* necessarily a path instead of just the program name
*/
/*
* mono_w32process_get_path on these can only return a name, not a path;
* which may not be good for us if the mono command name isn't on $PATH,
* like in CI scenarios. chances are argv based is fine if we inherited
* the environment variables.
*/
```
=> Use argv for cli_launcher on OSes that don't return full path for process names; fix mono_w32process_get_path on Free/NetBSD

mono/utils/mono-utils-debug.c
checks self for the "process is traced" flag
=> IsDebuggerPresent for AIX

mcs/class/System/Mono.Btls/MonoBtlsProvider.cs, mcs/class/System/Mono.Btls/MonoBtlsX509StoreCtx.cs, mcs/class/System/Mono.Btls/X509ChainImplBtls.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509ChainImpl.cs, mcs/class/System/System.Security.Cryptography.X509Certificates/X509ChainImplMono.cs
An implementation of the ChainStatus property for Btls. When we execute the certificate verification callback we just don't test for success and set status11. Now we get the error (if any) and map the error code to those defined by ChainStatusFlags and add it to a list of X509ChainStatus objects for that chain. Now when get_ChainStatus is called we convert that list to an array of X509ChainStatus and return it.
=> An implementation of the ChainStatus property for Btls

mono/tests/Makefile.am, mono/utils/mono-threads-mach.c, mono/utils/mono-threads-windows.c, mono/utils/mono-threads.c
So the issue is that calling `begin_suspend_for_blocking_thread` under hybrid
suspend will perform a preemptive suspension of the victim thread.
The preemptive suspend doesn't always succeed.
In particular, `thread_state_init_from_sigctx` or `thread_state_init_from_handle`
could return FALSE and `info->suspend_can_continue` will be set to FALSE.
When the `thread_state_init_*` functions return FALSE, they also set the
`MonoThreadUnwindState:valid` to FALSE.
So it is important to check the value of `MonoThreadInfo:suspend_can_continue`
before proceeding with a suspension.
As a result in `suspend_sync` in the `ReqSuspendInitSuspendRunning` case we call
`check_async_suspend` which checks (for preemptively suspended threads) whether
`suspend_can_continue` is true.  If it isn't, we resume the …
=> [coop] Check async suspend status in ReqSuspendInitSuspendBlocking case

mono/metadata/sgen-stw.c, mono/tests/Makefile.am, mono/utils/mono-threads-state-machine.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
Implement a two-phase hybrid suspend scheme:
1. In the _entente phase_ put all threads in the suspend request state (either `ASYNC_SUSPEND_REQUESTED` or `BLOCKING_SUSPEND_REQUESTED`).  Wait for pending operations (but only wait for the async ones) and let all threads try to self-suspend.
2. In the _aggressive mop-up phase_ - preemptively suspend any threads that are still in `BLOCKING_SUSPEND_REQUESTED`.
=> [hybrid-suspend] Two phase STW

mono/mini/m2n-gen.cs, mono/mini/wasm_m2n_invoke.g.h
Function pointers do not convert silently to void*. Cast them.
Use a typedef to avoid duplicating the type, optionally.
=> [cxx] Make WebAssembly to native transitions valid C++.

mono/metadata/appdomain.c, mono/metadata/domain.c, mono/metadata/image.c, mono/metadata/marshal.c, mono/metadata/marshal.h, mono/metadata/mono-perfcounters.c, mono/metadata/object-internals.h, mono/metadata/object.c, mono/utils/mono-publib.h
https://github.com/mono/mono/commit/675c94ec7a923a40c9e2dfdb098218f30226604b was incomplete.
https://jenkins.mono-project.com/job/x/12791/parsed_console/log.html
icall-windows.c: In function 'MonoStringHandle mono_icall_get_machine_name(MonoError*)':
icall-windows.c:65:75: error: invalid conversion from 'gunichar2* {aka wchar_t*}' to 'const guint16* {aka const short unsigned int*}' [-fpermissive]
return mono_string_new_utf16_handle (mono_domain_get (), buf, len, error);
^
In file included from ../../mono/metadata/icall-internals.h:11:0,
from ../../mono/metadata/icall-windows-internals.h:13,
from icall-windows.c:14:
../../mono/metadata/object-internals.h:1963:1: note:   initializing argument 2 of 'MonoStringHandle mono_string_new_utf16_handle(MonoDomain*, const guint16*, gint32, …
=> [cxx] wchar_t is not guint16, on Windows

configure.ac
=> [runtime] Fix the invocation of update_submodules.sh during configure so it works for out-of-tree builds as well.

mcs/class/corlib/Test/System.Threading/WaitHandleTest.cs, mono/metadata/threads.c
There is a small race condition during the completion of a native thread join call. During that period of time the tid is no longer included on the internal list tracking joinable threads so a thread that will join on the tid while another thread (like the finalizer thread) is waiting on native join to complete for the same tid, will cause the managed Thread.Join call to complete before the native join call has completed. This race could cause issues on some OS:es that clear's up some thread resources, like abandoned mutexes when the thread has exited. This race is hit by WaitAnyWithSecondMutexAbandoned since the call to Thread.Join will return before the thread owning the mutex has terminated meaning that it doesn't get ownership of the abandoned mutex as assumed by the test.
Fix makes …
=> Fix race condition in WaitAnyWithSecondMutexAbandoned test.

configure.ac, mono/utils/networking-posix.c
Fixes https://github.com/mono/mono/issues/7087
=> [runtime] Use getprotobyname_r() where needed and available

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mcs/class/corlib/Test/System/ExceptionTest.cs, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/threads.c, mono/mini/mini-exceptions.c, mono/mini/mini-posix.c, mono/utils/mono-merp.c, mono/utils/mono-merp.h, mono/utils/mono-state.c, mono/utils/mono-state.h
This enables a correctly-configured runtime to convert unhandled exceptions into telemetry-formatted dumps. 
Future readers: The tests / example usage for the MS-Telemetry-side interop are in the commit message for 
```
[runtime] Add test for managed telemetry reporting 
```
at
https://github.com/mono/mono/pull/10133/commits/97a7af3f9733c29e49183247e866d8ad06601c2f
=> [runtime] Add pipeline to convert managed exception into telemetry format

mono/metadata/dynamic-image-internals.h, mono/metadata/dynamic-image.c, mono/metadata/dynamic-stream-internals.h, mono/metadata/dynamic-stream.c, mono/metadata/object.c, mono/metadata/sre-encode.c, mono/metadata/sre-save.c
This  tends to be more C++ compatible, and really is in this case.
=> [cxx] Prefer gpointer/gconstpointer over char*, guint8* for untyped data -- fewer casts generally.

mono/metadata/Makefile.am, mono/metadata/pal-android.c, mono/metadata/pal-android.h, mono/metadata/pal-icalls.c, mono/metadata/pal-icalls.h, sdks/builds/ios.mk
https://github.com/mono/mono/issues/9380
The original PR had a typo (missed ` \` at the end of a line causing a prematurely terminated list of files in `metadata/Makefile.am`), so it had to be reverted
=> [System.Native] Build a reduced library on Android and iOS

llvm/build.mk, sdks/builds/llvm.mk
Backport of #9944.
/cc @vargaz
=> [2018-08] [sdks] Use separate temporary dirs for llvm36/llvm.

mono/mini/Makefile.am.in
The llvm/llvm_config.mk makefile fragment just includes make (not automake)
variable definitions.  So there is no need to regenerate the mini/Makefile.am
file if the fragment updates - the include will pick it up.
=> [mini] Don't regen Makefile.am if llvm/llvm_config.mk changes

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mcs/class/corlib/Test/System/ExceptionTest.cs, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/threads.c, mono/mini/mini-exceptions.c, mono/mini/mini-posix.c, mono/utils/mono-merp.c, mono/utils/mono-merp.h, mono/utils/mono-state.c, mono/utils/mono-state.h
This enables a correctly-configured runtime to convert unhandled exceptions into telemetry-formatted dumps.
https://github.com/mono/mono/pull/10133
=> [2018-08] Add pipeline to convert managed exception into telemetry format

mono/mini/mini-llvm.c
Fixes https://github.com/mono/mono/issues/10035.
=> [llvm] Emit volatile loads in emit_volatile_load (), otherwise llvm might optimize the loads away.

mcs/build/gensources.cs, mcs/class/System.Security/System.Security.csproj, mcs/class/System.Security/win32_net_4_x_System.Security.dll.exclude.sources, mcs/class/System.Security/win32_net_4_x_System.Security.dll.sources, mcs/class/corlib/Test/System.IO/BinaryReaderTest.cs
The commit https://github.com/mono/mono/commit/f602125d107b0966f8045670326124ad988291cc accidentally introduced a (hostplatform)_(libname) style sources file, making it get used for any scenario where the host platform was win32 and we didn't have a more specific sources file. We didn't notice this hazard when adding support for the hostplatform style so this PR changes the format to (hostplatform)_defaultprofile_(libname) to make it explicit that the sources file is intended to behave this way. The hazard is partly a result of us already naming common included sources files in a similar pattern, like win32_foo.sources, and then including them from a bunch of profiles.
This PR also updates the 'load entire folder' path used by genproj to check for any uses of the hazardous hostplatform …
=> Change platform specific sources overrides from hostplatform_libname to hostplatform_defaultprofile_libname

mono/eglib/eglib-remap.h, mono/eglib/glib.h, mono/eglib/gmem.c, mono/eglib/gutf8.c
First one fixes gcc 7/8 warning for misleading indentation.
Second one corrects condition for leading utf-8 byte test - intended bitmask test is 11xxxxxx vs 10xxxxxx.
=> [eglib] Fix compilation warnings.

mcs/class/System/System.Net.NetworkInformation/Win32IPAddressCollection.cs, mcs/class/System/System.Net.NetworkInformation/Win32IPInterfaceProperties.cs, mcs/class/System/System.Net.NetworkInformation/Win32IPv4InterfaceProperties.cs, mcs/class/System/System.Net.NetworkInformation/Win32NetworkInterface.cs, mcs/class/System/System.Net.NetworkInformation/Win32NetworkInterfaceMarshal.cs
GetAllNetworkInterfaces (correctly) returns the loopback, however GetAdaptersInfo does not return information about the loopback 
msdn https://msdn.microsoft.com/en-us/library/windows/desktop/aa365917(v=vs.85).aspx 
The GetAdaptersInfo and GetInterfaceInfo functions do not return information about the IPv4 loopback interface. Information on the loopback interface is returned by the GetIpAddrTable function)
Instead of querying data from GetAdaptersInfo, instead use data from Win32_IP_ADAPTER_ADDRESSES
I've manually tested the output of the script below against .NetFW; If theres a better way to test networking changes to windows please tell me.
```
public void Test()
{
var interfaces = NetworkInterface.GetAllNetworkInterfaces();
foreach (NetworkInterface ni in interfaces)
{
var …
```
=> Fix IndexOutOfRangeException: No adapter found for index when getting network information

mono/mini/debugger-agent.c
Backport of https://github.com/mono/mono/pull/9981.
=> [2018-02] [sdb] Disable an assert to avoid breaking debugging.

mono/mini/method-to-ir.c
Fixes https://github.com/mono/mono/issues/9870.
=> [jit] Disable tail calls from gsharedvt code for now.

mono/mini/method-to-ir.c
=> [2018-06] [jit] Disable tail calls from gsharedvt code for now.

mono/mini/debugger-agent.c
Backport of https://github.com/mono/mono/pull/9981.
=> [2018-04] [sdb] Disable an assert to avoid breaking debugging.

mcs/class/System/Makefile, mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs, mcs/class/System/Mono.Net.Security/MonoTlsStream.cs, mcs/class/System/System.Net/WebConnection.cs, mcs/class/System/System.Net/WebReadStream.cs
When the TLS Handshake fails in `MonoTlsStream.CreateStream()`, then we must dispose
the `SslStream` to avoid a memory leak.
In addition to this, `MonoTlsStream` now implements `IDisposable` and is disposes
in `WebConnection.CloseSocket()`.
Fixes #8689
=> [System]: `MonoTlsStream` is now `IDisposable` and cleans up on error.

configure.ac, mono/eglib/eglib-remap.h, mono/eglib/glib.h, mono/eglib/gmodule.h, mono/eglib/gunicode.c, mono/eglib/test/Makefile.am, mono/eglib/test/enum.cpp, mono/eglib/test/test.c, mono/eglib/test/test.h, mono/eglib/test/tests.h, mono/metadata/domain-internals.h, mono/metadata/sre.c, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/metadata/w32handle.c, mono/utils/checked-build.h, mono/utils/mono-threads.h, mono/utils/os-event-unix.c, msvc/test_eglib.vcxproj, msvc/test_eglib.vcxproj.filters
There are at least three or so approaches to this.
1. Sprinkle around casts.
2. Overload operators.
2a. Bit-only (| & ^ |= &= ^=)   This is this PR and seemingly the consensus.
2b.  Also math (+ - ++ -- == !=)
3. typedef to int instead (https://github.com/mono/mono/pull/10231)
They all have tradeoffs.
1. Casts: The most line damage. Not huge, but the most.
2. Overloads: New idiom to some but an old idiom. Supported in this way by windows.h even.
This is the most "C++y solution".
3. int: Highest level of source compat and semantic compat. Least line damage (just
change the declarations). Least debuggable and least typesafe.
In terms of semantic compat, even in C the guarantees aren't particularly strong.
Some enums will be int, some unsigned, depending on the values and the compiler. …
=> [cxx] int vs. enum -- bit overload version

configure.ac, llvm/Makefile.am, llvm/build_llvm_config.sh
This commit re-enables Windows LLVM mono cross compiler build + adjust to new changes done in mono LLVM build system.
mono Windows cross compiler using LLVM master from https://github.com/mono/llvm.git have been build and successfully linked using x86_64-w64-mingw32 toolchain on the following platforms:
- Linux Ubuntu
- WSL with Linux Ubuntu
- CygWin
=> Fix Windows LLVM mono cross compiler build.

mcs/class/System.Net.Http/Makefile, mcs/class/System.Net.Http/System.Net.Http.csproj, mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs, mcs/class/System.Net.Http/System.Net.Http/HttpClient.wasm.cs, mcs/class/System.Net.Http/wasm_System.Net.Http.dll.sources, sdks/wasm/Makefile, sdks/wasm/bindings-test.cs, sdks/wasm/test.js
- Add a private static variable to HttpClient called `Func<HttpMessageHandler> GetHttpMessageHandler` that will be used to obtain the default message handler and can be set for example as follows:
```
var httpMessageHandler = typeof(HttpClient).GetField("GetHttpMessageHandler", 
BindingFlags.Static | 
BindingFlags.NonPublic);
httpMessageHandler.SetValue(null, (Func<HttpClientHandler>) (() => {
return new MyHttpClientHandler ();
}));
```
- If a handler is not set or returns null the default implementation HttpClientHandler will be returned.
- Add HttpClient.wasm.cs implementation to handle the default HttpClient
- Add simple test to the wasm test harness bindings-test.
- Reference https://github.com/mono/mono/issues/9941
=> [wasm] Modify HttpClient to use a default handler provider.

mono/metadata/loader.c, mono/mini/arch-stubs.c, mono/mini/debugger-agent.c, mono/mini/debugger-engine.c, mono/mini/exceptions-amd64.c, mono/mini/exceptions-arm.c, mono/mini/exceptions-arm64.c, mono/mini/interp/interp.c, mono/mini/mini-exceptions.c, mono/mini/mini-runtime.h, mono/mini/mini-wasm-debugger.c, mono/mini/mini.h, mono/utils/mono-compiler.h, mono/utils/mono-stack-unwinding.h
please look at the single commits. here's a `git log` copy/paste:
---------------------------------
[exceptions] ftnptr_eh_callback test that stresses n2m transitions.
on Xamarin.iOS it happens that the ftnptr_eh_callback calls into managed code, that is yet another native-to-managed transition.
----------------------------------
[exceptions] pop lmf stack before executing ftnptr_eh_callback
----------------------------------
[interp] always set LMF for interp_in wrapper.
partial revert of a33cbb873c487490f2a3c271b24c70c1c3fc0a2c
----------------------------------
[mini] ignore LMF if it isn't initialized
interp_in wrapper serves two purposes:
1) native to interp transition: usually this transition doesn't need a
LMF marker, but in a ftnptr_eh_callback scenario it can be required.
see …
=> [interp] fix ftnptr_eh_callback

mono/mini/mini-posix.c
also, guard for `IP == NULL`: I haven't seen it in the wild, but when messing with EH I have seen it happen and then we have a segfault in the signal handler, which is... bad 😄 
we should backport this to `2018-06` and `2018-08`.
=> [mini] fix memory dumping on devices

mono/mini/method-to-ir.c, mono/tests/Makefile.am
It doesn't really work fully anyway -- some stack is conserved, but the wrappers still consume stack, largely defeating the purpose.
Better would be to avoid gsharedvt by instantiating the generic methods.
=> Disable tailcall of gsharedvt.

mono/mini/method-to-ir.c, mono/tests/Makefile.am
=> [2018-08] Disable tailcall of gsharedvt.

mcs/class/System/Makefile, mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs, mcs/class/System/Mono.Net.Security/MonoTlsStream.cs, mcs/class/System/System.Net/WebConnection.cs, mcs/class/System/System.Net/WebReadStream.cs
=> [2018-08] [System]: `MonoTlsStream` is now `IDisposable` and cleans up on error.

mcs/class/System/Makefile, mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs, mcs/class/System/Mono.Net.Security/MonoTlsStream.cs, mcs/class/System/System.Net/WebConnection.cs, mcs/class/System/System.Net/WebReadStream.cs
=> [2018-06] [System]: `MonoTlsStream` is now `IDisposable` and cleans up on error.

mono/metadata/domain.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
Fixes a crash where pthread_key_clean_all will call destructors that should have been freed before unload.
=> Free the thread_info_key and thread_exited_key during unload

mono/mini/mini-wasm.c
g++/clang++ do have `__restrict` and/or `__restrict__`.
On MacOSX, __restrict is preprocessed out of the headers for C++.
On Linux, __restrict is used and preserved for C++.
I didn't check others.
__restrict does not appear to be part of the function signature.
You cannot overload on it.
It is not in the mangled name.
If you declare one way and implement the other, there is no warning or error.
Therefore, remove restrict.
There are alternatives.
One could preserve it for C only.
One could preserve it for C and for Linux/C++.
One could preserve it based on autoconf, and check/assert autoconf results on Mac and Linux.
Perhaps as well we will autoconf or ifdef wasm away use of these functions?
If we merely if them away, we still need them.
=> [cxx] C++ does not have restrict.

mono/metadata/boehm-gc.c, mono/metadata/gc-internals.h, mono/metadata/null-gc.c, mono/metadata/sgen-mono.c, mono/mini/tasklets.c
Allow mono_gc_alloc_fixed subset outside of metadata (mini/tasklets.c), without breaking due to C++ typesafe linkage.
This enables avoiding externC workaround here:
https://github.com/mono/mono/pull/10160/files#diff-bd3a3d5c2bfd6af46373b3844de9c1d0R163
=> [cxx] Fix typesafe-linkage problem due to varying MonoGCDescriptor.

sdks/builds/llvm.mk
Part of https://github.com/mono/mono/pull/10300 that applies to `mono:2018-06`.
=> [2018-06] [sdks] Allow for overwriting llvm-{llvm32,llvm64} CC and CXX

sdks/builds/llvm.mk
Part of https://github.com/mono/mono/pull/10300 that applies to `mono:2018-08`.
=> [2018-08] [sdks] Allow for overwriting llvm-{llvm32,llvm64} CC, CXX, CFLAGS and CXXFLAGS

man/mono.1, mono/mini/aot-compiler.c
Currently we can override arguments passed to llvm's `opt` via `--aot=llvm,llvmopts="some args"`, this PR introduces a similar capability for `llc` - `llvmllc` parameter.
E.g. for my environment Mono uses the following arguments for llc:
```
-march=x86-64 -mattr=sse4.1 -asm-verbose=false -disable-gnu-eh-frame 
-enable-mono-eh-frame -mono-eh-frame-symbol=_mono_aot_fffff_eh_frame 
-disable-tail-calls -no-x86-call-frame-opt -relocation-model=pic 
-filetype=obj -o "mono_aot_IWvNWm/temp-llvm.o" "mono_aot_IWvNWm/temp.opt.bc"
```
what if I want to test some avx stuff, e.g. `-march=core-avx2 -O2` and test other parameters.
=> Pass arguments to LLVM's LLC via --aot=llvmllc

sdks/builds/llvm.mk
Part of https://github.com/mono/mono/pull/10300 that applies to `mono:master`.
=> [sdks] Allow for overwriting llvm-{llvm32,llvm64} CC, CXX, CFLAGS and CXXFLAGS

mono/metadata/object-internals.h, mono/metadata/object.c, mono/metadata/sgen-client-mono.h
This could lead to crashes when having strings with size at the LOS boundary.
https://github.com/mono/mono/issues/10309
=> [sgen] Fix string size inconsistency between alloc/scan

mono/mini/Makefile.am.in, mono/mini/mini-windows-dlldac.c, mono/mini/mini-windows-dllmain.c
And overlaps with, so:
Cleanup confusing code in Makefile.am.ini. We don't compile/link "mono".
mono is a symlink.
So mono_CFLAGS is just an intermediate, equivalent to AM_CFLAGS, plus the "REMOVE_CXX_FLAGS", which is
a mistake, borne of me thinking mono_CFLAGS is [primary=mono]_CFLAGS like it might appear, but it isn't.
AM_CFLAGS already contains JEMALLOC_CFLAGS.
Adding it to mono_CFLAGS isn't needed.
Adding @CXX_REMOVE_CFLAGS@ to mono_CFLAGS then was unintended, leading to many warnings with g+4.4.
So this should fix those warnings and make the code just a tiny bit simpler.
=> [cxx] Port mono main to  be C++, and externC some Windows exports

mono/metadata/object.c, mono/tests/install_eh_callback.cs, mono/tests/libtest.c
on Xamarin.iOS it happens that the ftnptr_eh_callback calls into managed
code, that is yet another native-to-managed transition.
This fails coop right now, see https://github.com/mono/mono/pull/10224#issuecomment-416646880
=> [exceptions] ftnptr_eh_callback test that stresses n2m transitions

mono/utils/mono-threads.c
Compare with enum values in mono-threads.h https://github.com/mono/mono/blob/d001c5066647df074992b1bb11a6cfb0c1711f4b/mono/utils/mono-threads.h#L128-L154
=> [coop] Fixup dump_threads () legend to match thread state enum values

mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs
Backport of #10393.
/cc @baulig
=> [2018-08] [System]: Make `MobileAuthenticatedStream`s read buffer large enough to hold a full TLS record.

mcs/class/System/Mono.Btls/MonoBtlsProvider.cs
See my comments in https://github.com/mono/mono/pull/10134 for details.
The problem was that
1. It is wrong to assume that `chain != null`.  In fact, it likely won't be if `wantsChain == false`.
2. Similarly, the `storeCtx` should only be used if `storeCtx != NULL && wantsChain == true`.
3. It was missing `MonoBtlsX509Error.HOSTNAME_MISMATCH`.
4. I reformatted and re-indented the method to match Mono's style.
=> [System]: Fix `MonoBtlsProvider.CheckValidationResult ()` logic.

mcs/class/corlib/corlib.csproj, msvc/scripts/corlib.post
This ensures that System.CompilerServices.Unsafe has implemented method bodies, necessary for Span and similar use cases.
=> Update corlib post-build event to run ilasm for Unsafe.il, then pass it to cil-stringreplacer

mono/mini/Makefile.am.in
```
04:07:52 make[3]: Leaving directory `/mnt/jenkins/workspace/release-tarball-mono/mono/mini'
04:07:52 
make[3]: *** No rule to make target `mini-wasm-debugger.c', needed by `distdir'.  Stop.
04:07:52 
make[2]: *** [distdir] Error 1
04:07:52 make[2]: Leaving directory `/mnt/jenkins/workspace/release-tarball-mono/mono'
```
https://jenkins.mono-project.com/view/Releases/job/release-tarball-mono/923/console
=> Fix `make dist`, broken by 6dc01610e5509c5b41a34dc688fb588268b3b0c5

mono/mini/mini-runtime.c
Apparently the standard or implementers would be within their rights to change it to:
double fmod(double, double, double = 1);
which would break this. I don't think they can get away with it.
Taking address is discouraged, so that such evolution can occur compatibilty.
=> [cxx] Wrap fmod in mono_fmod for stronger future-proofing.

mono/mini/method-to-ir.c
(Really just split this out because github is slow linking to within large diff).
=> [cxx] Char literals are now chars, not ints (sizeof changes) and indexing by them warns. Cast.

packaging/MacSDK/mono.py
Fixes https://github.com/mono/mono/issues/10243
=> [MacSDK] Go back to incluging opt/llc after change in LLVM install process

packaging/MacSDK/mono.py
Backport of #10431.
/cc @alexischr
=> [2018-08] [MacSDK] Go back to including opt/llc after change in LLVM install process

mono/metadata/w32file-unix.c
Backport of #10020.
/cc @luhenry
=> [2018-08] Use clonefile instead of copyfile on macOS.

mono/mini/debugger-engine.c
Backport of #9981.
/cc @vargaz
=> [2018-08] [sdb] Disable an assert to avoid breaking debugging.

mcs/tools/mkbundle/mkbundle.cs
Consider doing this only for Windows.
=> Fix mkbundle alignment to work with Windows. See https://github.com/mono/mono/issues/8225.

configure.ac
This doesn't make any functional change right now, but it clears
this up for readers and future users.
=> [runtime] Fix configure flag typos

mcs/tools/mkbundle/bundle-mono-api.inc, mcs/tools/mkbundle/template_common.inc
Without this change, mkbundle cannot be run out-of-tree without using the new API struct
https://github.com/mono/mono/issues/9956
=> [runtime] Declare mono_aot_register_module in mkbundle stub

mcs/tools/mono-api-html/ApiChange.cs, mcs/tools/mono-api-html/FieldComparer.cs, mcs/tools/mono-api-html/HtmlFormatter.cs, mcs/tools/mono-api-html/MarkdownFormatter.cs
When creating a diff on windows, the lines are split on the `\n` so the `\r\n` results in multiple lines:
**START SNIP**
Obsoleted methods:
```diff
[Obsolete ("Use AddRoundRect instead.")]
public void AddRoundedRect (SKRect rect, float rx, float ry, SKPathDirection dir);
```
**END SNIP**
This PR makes sure to use the platform line endings everywhere. When adding line endings, use the same that `StringBuilder` uses - platform endings. This makes it easy to split - just use the platform as that is what everyone is using.
=> [mono-api-tools] Split properly for cross-platform

mono/metadata/coree.h
https://jenkins.mono-project.com/job/w/15083/parsed_console/log.html
assembly.obj : error LNK2001: unresolved external symbol "struct _IMAGE_DOS_HEADER __ImageBase" (?__ImageBase@@3U_IMAGE_DOS_HEADER@@A) [d:\j\workspace\w\msvc\libmono-dynamic.vcxproj]
d:\j\workspace\w\msvc/./build/boehm/Win32\bin\ReleaseCxx\mono-2.0-boehm.dll : fatal error LNK1120: 1 unresolved externals [d:\j\workspace\w\msvc\libmono-dynamic.vcxproj]
Since it is data, extern "C" w/o braces is confusing, but maybe valid, so begin/end form is used.
=> Linker-supplied __ImageBase must be extern "C".

mono/utils/mono-threads.h
See https://jenkins.mono-project.com/job/w/15104/parsed_console/log.html
=> [cxx] mono_thread_info_current extern "C" on Windows.

mono/metadata/attach.c, mono/metadata/attach.h, mono/metadata/w32file.h
[cxx][wasm] Fix mismatched extern "C".
https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/4437/parsed_console/log.html
WASM-ERR: missing function: mono_attach_init
https://jenkins.mono-project.com/job/w/15060/parsed_console/log.html
attach.c:600:1: warning: no previous declaration for 'void mono_attach_parse_options(char*)' [-Wmissing-declarations]
attach.c:605:1: warning: no previous declaration for 'void mono_attach_init()' [-Wmissing-declarations]
attach.c:610:1: warning: no previous declaration for 'gboolean mono_attach_start()' [-Wmissing-declarations]
attach.c:616:1: warning: no previous declaration for 'void mono_attach_maybe_start()' [-Wmissing-declarations]
attach.c:621:1: warning: no previous declaration for 'void mono_attach_cleanup()' [-Wmissing-declarations] …
=> [cxx][wasm] Fix mismatched extern "C".

mono/utils/mono-context.h
See https://jenkins.mono-project.com/job/x/13345/parsed_console/log.html.
=> [cxx] mono_context_get_current is extern "C" because it is assembly.

mono/metadata/handle.h
W/o gcc/clang language extension `__typeof__`. This is not meant to be
long term idiomatic C++, just enough to get us by for now.
The solution does not quite work for type unsafe handles, because
checking for this == NULL is not defined. A non-member function
would be needed.
C++11 decltype could be used instead at the MONO_TYPEOF_CAST level,
but this solution is trivial C++98.
=> [cxx] Adapt typesafe coop handles for standard/Visual C++.

mono/metadata/threads.c
This fixes a bunch of warnings in threads.c. Compare-exchange cast is unfortunate because it would do without if we had platform long sized cas helper around - tid is always u32 on Windows (DWORD), and pthread_t is always long int, which could be 32 or 64 bit.
=> [mono] Compiler warnings fixes

mono/metadata/w32file-unix.c
* Revert of https://github.com/mono/mono/pull/10010 
* Backport of https://github.com/mono/mono/pull/10020
Fixes https://github.com/mono/mono/issues/10447
/cc @filipnavara
=> [2018-06] Use clonefile instead of copyfile on macOS

scripts/ci/run-test-interpreter.sh
New tests were included recently
=> [tests] Bump timeout for System.Numerics with interpreter

mono/metadata/gc-internals.h, mono/metadata/sre.c, mono/mini/aot-runtime.h, mono/mini/jit-icalls.h, mono/mini/mini-exceptions.c, mono/mini/mini-llvm-cpp.h, mono/mini/mini-runtime.c, mono/mini/mini.h, mono/utils/mono-tls.h
Guessing a bit on the extern "C". Will see what CI says.
And what is with this function/name mismatch?
mono/metadata/marshal.c:                register_icall (mono_gc_wbarrier_generic_nostore, "wb_generic", "void ptr", FALSE);
The cast was lost because at the last moment I changed the parameter from argval to void_argval and assign to local, to reduce the semantic change (and then a cast later removed).
=> [cxx] More extern "C" per errors and a missed cast.

mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs, mono/mini/debugger-agent.c
This adds proper versioning to the wire change that was introduced in #9762.
Fixes #10412.
=> [sdb]: Properly version the `CMD_TYPE_GET_METHODS_BY_NAME_FLAGS` change.

mcs/class/corlib/System.Runtime.CompilerServices/ConditionalWeakTable.cs
We can't decrement the size on removal as we use tombstones.
When using tombstones, the invariant to keep is on the number of null entries as those
are used as search stop-marks.
Without this change, it's possible that a long series of add/remove operations could leave the array with no null entries,
just tombstones and filled entries. In that case, search would degenerate into a linear search that would look into all array elements.
This change fixes worst-case perf of not-found searches to be bound to the load factor.
Additionally, clear the array to null entries, otherwise we fall into the above trap even more easily.
=> [corlib] Don't decrement ConditionalWeakTable::size on remove.

msvc/eglib.vcxproj, msvc/libgcmonosgen.vcxproj, msvc/libmini.vcxproj, msvc/libmono-dynamic.vcxproj, msvc/libmono-static.vcxproj, msvc/libmonodac.vcxproj, msvc/libmonoruntime.vcxproj, msvc/libmonoutils.vcxproj, msvc/mono.props, msvc/mono.vcxproj, msvc/monodis.vcxproj, msvc/monograph.vcxproj, msvc/pedump.vcxproj
By default, all projects are build using "default" compiler based on source file extension. There is a property in mono.props, MONO_COMPILE_AS_CPP  that could change this and build selected projects (eglib, libgcmonosgen, libmini, libmono-dynamic, libmono-static, libmonodac, libmonoruntime,
libmonoutils, mono, monodis, monograph and pedump) using C++ compiler.
MONO_COMPILE_AS_CPP property could be set when calling msbuild or through VS property manager IDE. Default value is false building using "default" compiler (current behavior). When setting MONO_COMPILE_AS_CPP=true the build prefix will be altered to make sure the C++ build gets its own build folder, parallel to default build folders.
Example of building using C++ compiler from msbuild:
msbuild /p:PlatformToolset=v140 /p:Platform=x64 …
=> Add C++ compiler support option for some msvc build projects.

llvm/Makefile.am, llvm/build_llvm_config.sh, mono/metadata/Makefile.am, scripts/ci/run-jenkins.sh
Fix Mono Windows cross compiler using mono LLVM release_60 branch.
For scenario where llvm-config.exe can't be run (none WSL/CygWin build target) build will fallback to hard coded libraries not working with mono LLVM release_60 branch.
Added an exact mirror of what llvm-config.exe is returning for different components on mono LLVM master and mono LLVM release_60 branch.
The selected codegen libraries (passed in as extra_libs) was not handled in any cases so added them into the build script as well.
Above successfully builds using mono LLVM master and mono LLVM release_60 branches and links into Windows mono cross compiler build on Linux.
=> Fix Mono Windows cross compiler using mono LLVM release_60 branch.

mono/metadata/object.c, mono/tests/install_eh_callback.cs, mono/tests/libtest.c
=> [2018-08] [exceptions] ftnptr_eh_callback test that stresses n2m transitions

mcs/class/System/System.IO.Compression/DeflateStream.cs
=> [2018-06] Ensure the finalization in DeflateStream is performed in the correct order.

mcs/class/System/System.IO.Compression/DeflateStream.cs
=> [2018-08] Ensure the finalization in DeflateStream is performed in the correct order.

mono/mini/method-to-ir.c
Backport of #9942.
/cc @vargaz
=> [2018-08] [llvmonly] Fix a regression caused by 55950a060838c3d044dc23c9a9a2a99102977146.

tools/monograph/monograph.c
Linux/GCC
Fixes this warning:
``
CC       monograph.o
monograph.c: In function ‘mono_method_find_bblocks’:
monograph.c:755:34: warning: variable ‘start’ set but not used [-Wunused-but-set-variable]
const unsigned char *ip, *end, *start;
^~~~~
CCLD     monograph
``
=> [monograph] Fix unused variable warning.

mcs/class/System/Test/System.IO.Compression/DeflateStreamTest.cs, support/zlib-helper.c
=> [2018-08] Fix DeflateStream handling of zero-length reads from underlying stream.

mono/metadata/w32socket.c
#8775 
when os is busy, calling syscall poll() will return EINTR error. In the current source code, the calculation of timeout of retrying poll() is incorrect. I supposed a better way to solve this problem.
=> fix timeout when poll fail with the error EINTR

llvm/Makefile.am, llvm/build_llvm_config.sh, scripts/ci/run-jenkins.sh
Fix Mono Windows cross compiler using mono LLVM release_60 branch.
For scenario where llvm-config.exe can't be run (none WSL/CygWin build target) build will fallback to hard coded libraries not working with mono LLVM release_60 branch.
Added an exact mirror of what llvm-config.exe is returning for different components on mono LLVM master and mono LLVM release_60 branch.
The selected codegen libraries (passed in as extra_libs) was not handled in any cases so added them into the build script as well.
Above successfully builds using mono LLVM master and mono LLVM release_60 branches and links into Windows mono cross compiler build on Linux.
Backport of https://github.com/mono/mono/pull/10413.
=> [2018-08] Fix Mono Windows cross compiler using mono LLVM release_60 branch.

mcs/class/System.Net.Http/System.Net.Http.Headers/ProductHeaderValue.cs, mcs/class/System.Net.Http/Test/System.Net.Http.Headers/ProductHeaderValueTest.cs
=> [System.Net.Http] Allow empty value in ProductHeaderValue

mono/mini/aot-tests.cs
It works on my machine. Test was introduced by https://github.com/mono/mono/pull/10517/
=> [wasm] enable test_0_arm64_dyncall_vtypebyrefonstack

scripts/ci/run-jenkins.sh, scripts/ci/run-test-default.sh, scripts/ci/run-test-interpreter.sh, scripts/ci/run-test-testing_aot_full.sh, scripts/ci/run-test-testing_aot_hybrid.sh, scripts/ci/run-test-winaot.sh
getconf should work on both, macOS and linux.
Fixes https://github.com/mono/mono/issues/10506
=> [ci] do not hardcode CPU count

mono/metadata/w32file-unix.c
Hopefully fixes #10510. Please backport to 2018-08, 2018-06 and 2018-04.
=> Treat EXDEV from clonefile the same way as ENOTSUP.

mono/metadata/w32file-unix.c
=> [2018-08] Treat EXDEV from clonefile the same way as ENOTSUP.

mono/metadata/w32file-unix.c
=> [2018-06] Treat EXDEV from clonefile the same way as ENOTSUP.

msvc/scripts/genproj.cs
This broke at some point and I didn't notice because it's a behavior divergence between msbuild and devenv (I was busy fixing msbuild-only bugs). As a result of some old broken logic in genproj (my fault probably but I forget), jay.vcxproj was not being set to build and VS would happily skip it even though some .csproj files depended on it, and as a result VS tried to build them and failed.
This should fix it but I'm submitting the PR since make -j + update-solution-files takes an eternity on my machine.
=> Fix forceBuild not working for projects with unknown platform names (i.e. jay)

mono/mini/aot-tests.cs, mono/mini/mini-arm64.c
Fixes https://github.com/xamarin/xamarin-macios/issues/4347.
=> [arm64] Fix the alignment of valuetypes passed after small primitive types on IOS.

mcs/class/System/System.Net/WebResponseStream.cs
We need to call `ToArray()` instead of `GetBuffer()` to truncate the buffer to the amount of bytes that we actually read.
=> [System]: Fix `WebResponseStream.ReadAllAsyncInner()` return value.

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c, mono/mini/debugger-agent.c
Indirectly load ref return values in invoke wrappers and return by value.
Don't share wrappers with ref returns since indirect load is used.
Add soft debugger support for methods with ref returns.
=> Handle ref returns in runtime invoke wrappers.

mono/metadata/w32process-win32.c
It is not clear how this should be represented.
https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa
"Note that an ANSI environment block is terminated by two zero bytes: one for the last string,
one more to terminate the block.
A Unicode environment block is terminated by four zero bytes: two for the last string,
two more to terminate the block."
Is unambiguous however.
=> Empty array is not passed per documentation to CreateProcess.

sdks/README.md, sdks/builds/.gitignore
- Update the gitignore for wasm-runtime
- Document automake 1.16.1 dependency. resolves https://github.com/mono/mono/issues/10446
closes https://github.com/mono/mono/issues/10614
=> [WASM] Update the sdks WebAssembly build instructions after recent AOT changes.

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/mini/mini-trampolines.c
mono_aot_get_unbox_trampoline: amd64 compute unbox trampoline size correctly via runtime disassembly.
This fixes: MonoTests.System.Linq.ParallelEnumerableTests.TestGroupBy frequently crashing on FullAOT/LLVM/Linux/amd64 CI.
https://github.com/mono/mono/issues/10441
https://github.com/mono/mono/issues/9554
https://github.com/mono/mono/issues/9046
Race condition because the code varies in what actually runs.
Sometimes System_Linq_Parallel_WrapperEqualityComparer_1_T_GSHAREDVT_GetHashCode_System_Linq_Parallel_Wrapper_1_T_GSHAREDVT is called,
sometimes not.
FullAOT+LLVM for reasons obvious from the fix.
Very sensitive to exact code presumably because the bug depends on whether the first
unbox trampoline has the same size as the unbox trampoline for …
=> Fix MonoTests.System.Linq.ParallelEnumerableTests.TestGroupBy (Linux/amd64/FullAOT/LLVM).

mcs/class/corlib/Test/System.Reflection/CustomAttributeDataTest.cs, mono/metadata/custom-attrs.c
Fixes https://github.com/mono/mono/issues/10555
=> [Reflection] Use a type of actual argument in case when custom attribute ctor parameter is of System.Object type

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/mini/mini-trampolines.c
=> [2018-08] Fix MonoTests.System.Linq.ParallelEnumerableTests.TestGroupBy (Linux/amd64/FullAOT/LLVM).

mono/mini/simd-intrinsics.c
This simply moves them to conditional block where they are used.
=> [mini] Fix a couple of unused function warnings.

sdks/wasm/driver.c, sdks/wasm/library_mono.js
This saves us from using twice as much memory for assemblies due to emcc filesystem retention polity and it avoid bugs in its
mmap emulation code.
=> [wasm] Switch to mkbundle style mono_register_bundled_assemblies instead of relying on emcc filesystem emulation. Fixes #10603.

mono/mini/mini-s390x.c
OUTARG_VT processing was incorrect - the structure wasn't being used properly on the stack such that things were being overwritten. 
This fix is still incomplete but I'd like to have something for people to examine and comment upon. It fails in the following test case:
```
using System;
using System.Text;
public class main{
static void Main (string[] args)
{
decimal x = 100m;
decimal y = 500m;
var z = 1 / (y / x);
Console.WriteLine("{0} {1} {2}",x,y,z);
}
}
```
Where it gives the results:
```
100 5 0.2
```
If I change the division to:
```
var z = y / x;
```
It gives the expected result of
```
100 500 5
```
=> Fix s390x Outarg_VT

configure.ac, mono/mini/mini-runtime.c, mono/utils/mono-compiler.h, mono/utils/mono-signal-handler.h
It broke Linux WebAssembly.
This reverts commit a6712d05bec184e69e3b175a4bc75cc34185a397.
=> Revert "Get fault_addr in debugger stacks. (#9673)"

mcs/class/corlib/Test/System.Reflection/ModuleTest.cs, mono/metadata/icall.c
Fixes: https://github.com/mono/mono/issues/9604 
`ResolveMember` crashes here https://github.com/mono/mono/blob/master/mono/metadata/metadata.c#L1158-L1159 (comes from [mono_memberref_is_method](https://github.com/mono/mono/blob/362d1d94e11ff0a44bac7aa6830a4783d9c70610/mono/metadata/icall.c#L6297))
All other resolvers such as [module_resolve_field_token](https://github.com/mono/mono/blob/362d1d94e11ff0a44bac7aa6830a4783d9c70610/mono/metadata/icall.c#L6239-L6242) have this kind of check for out-of-bounds.
=> [corlib] Throw AOORE for invalid input in Module.ResolveMember

mono/metadata/gc.c, sdks/builds/wasm.mk
The refqueue change undo part of 87fb34d18a733168a91df8d2358f233a2382a62d.
This is due to how track resurrection weak refs are implemented under boehm and sgen. Sgen natively supports them so we don't
need to emulated it by registering them for finalization. This produces a lot of useless work for the GC.
=> [wasm/gc] It's valid to register for finalization an object without a finalizer. Don't register for fin objects added to refqueues under sgen.

sdks/wasm/Makefile, sdks/wasm/packager.cs
Rename:
- bindings.dll -> WebAssembly.Bindings.dll
- wasmhttp.dll -> WebAssembly.Net.Http.dll
resolves: https://github.com/mono/mono/issues/10620
=> [wasm] Rename sdks WebAssembly framework libraries.

mcs/tools/mono-api-html/FieldComparer.cs
Fixes this warning when comparing Xamarin.iOS.dll:
Comparison resulting in no changes (src: Public, HasFieldMarshal dst: Public) :
<field name="EdgeTessellationFactor" attrib="4102" fieldtype="System.UInt16[]" />
<field name="EdgeTessellationFactor" attrib="6" fieldtype="System.UInt16[]" />
=> [mono-api-html] Render something for fields with marshalling info.

mono/mini/interp/transform.c
Caught by Aleksey Kliger.
transform.c(4251): error C2664: 'MonoReflectionType *mono_type_get_object_checked(MonoDomain *,MonoType *,MonoError *)': cannot convert argument 2 from 'gpointer' to 'MonoType *' [d:\j\workspace\d\msvc\libmono-dynamic.vcxproj]
Cast from void* to non-void*.
=> [cxx] Fix C++ compilation regression.

mcs/class/System/System.Net/WebResponseStream.cs
=> [2018-08] [System]: Fix `WebResponseStream.ReadAllAsyncInner()` return value.

mono/tests/Makefile.am
Only on Windows x86 while investigating root cause of failure (not replicating outside CI).
=> Temporary disable thread-suspend-suspended.exe and thread-suspend-sefsuspended.exe

mcs/class/corlib/Test/System.Runtime.Remoting/RemotingServicesTest.cs
=> [2018-06] [corlib] Makes remoting test more robust (and disable it on mobile)

mcs/class/corlib/Test/System.Runtime.Remoting/RemotingServicesTest.cs
=> [2018-08] [corlib] Makes remoting test more robust (and disable it on mobile)

mcs/class/System.Core/System.Core_xtest.dll.sources, mcs/class/corlib/corlib_xtest.dll.sources
These tests were disabled during https://github.com/mono/mono/pull/9707/files
so this PR is basically a cherry-pick of those.
We'll enable them back once we sync our corefx fork (those tests were changed in the upstream).
Fixes https://github.com/mono/mono/issues/10606
Fixes https://github.com/mono/mono/issues/10607 (needs https://github.com/mono/corefx/pull/140 + "bump corefx")
Fixes https://github.com/mono/mono/issues/10608
Fixes https://github.com/mono/mono/issues/10609
=> [2018-06] Ignore some xunit tests for XA (non compatible with xunit 2.4)

mcs/class/System/System.Net/HttpWebRequest.cs
`HttpWebRequest.RunWithTimeoutWorker()` needs to observe the worker task's exception
on timeout to prevent it from being thrown via the `TaskScheduler.UnobservedTaskException`
event.  Fixes #10488.
=> [System]: Make sure `HttpWebRequest` observes exceptions on timeout.  #10488.

sdks/wasm/Makefile, sdks/wasm/WebAssembly.Framework.nuspec
Add NuGet nuspec for generating the WebAssembly Framework NuGet packages.
The generated nupkg will be copied to the generated package zip under the framework directory.
=> [wasm] Add .nuspec for generating the WebAssembly Framework NuGet package.

mono/metadata/Makefile.am, mono/metadata/system_net_security_native_empty.c
https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx-products-sdks-ios/4837/parsed_console/log.html
ld: warning: -undefined dynamic_lookup is deprecated on tvOS
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
ar -m [-TLsv] archive file ...
ar -m [-abiTLsv] position archive file ...
ar -p [-TLsv] archive [file ...]
ar -q [-cTLsv] archive file ...
ar -r [-cuTLsv] archive file ...
ar -r [-abciuTLsv] position archive file ...
ar -t [-TLsv] archive [file ...]
ar -x [-ouTLsv] archive [file ...]
make[5]: *** [libmono-system-net-security-native.la] Error 1
=> Fix iOS SDK regression due to empty library.

mcs/class/System.Net.Http/System.Net.Http.Headers/ProductHeaderValue.cs, mcs/class/System.Net.Http/Test/System.Net.Http.Headers/ProductHeaderValueTest.cs
=> [2018-08] [System.Net.Http] Allow empty value in ProductHeaderValue

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/threads-types.h, mono/mini/mini-exceptions.c, mono/utils/mono-state.c
In order to make it easier for nunit lite to make managed crashes and native crashes be written to disk with the same logic, I thought I'd expose the helper. 
The consumer of this is in: https://github.com/mono/NUnitLite/pull/13
=> [runtime] Add standardized disk dumper for mono crashes

mcs/class/corlib/corlib_xtest.dll.sources
All tests from `../../../external/corefx/src/System.Reflection/tests` and `../../../external/corefx/src/System.Reflection.Extensions/tests`. Some of them are excluded because the related types has not been imported yet.
Part of #9660.
=> [System.Reflection] Include corefx unit tests.

mcs/build/tests.make, mcs/class/corlib/corlib_xtest.dll.sources
Adds xunit tests for System.Runtime.InteropServices
I commented out some files with failures (~56 failures), going to file an issue for them.
Also fixes https://github.com/mono/mono/issues/10717
=> Add System.Runtime.InteropServices xunit tests

mcs/tools/compiler-tester/compiler-tester.cs
Test result output in xUnit format can be produced by passing -resultXml to compiler-tester
This is part of the Helix work #9099
=> [mcs] Add xUnit xml output option to compiler-tester

acceptance-tests/SUBMODULES.json, acceptance-tests/roslyn.mk
Roslyn submodule was updated to enable more automated tests. This bumps our submodule revision, and uses roslyn's script to run tests instead of ours.
@monojenkins skip
Part of #6991
=> Update roslyn automated tests

mcs/errors/Makefile, mcs/errors/cs1703-2.cs, mcs/tests/Makefile, mcs/tests/gtest-exmethod-23.cs, mcs/tests/test-695.cs, mcs/tests/test-814.cs, mcs/tests/test-937.cs, mcs/tests/test-async-76.cs, mcs/tools/compiler-tester/compiler-tester.cs
We can use this to pass a directory the tests can use for -r or -lib.
Also fix cs1703-2.cs to not rely on binary outside repo during test.
Part of #9099
=> [mcs] Add option to specify reference directory to compiler-tester

mono/tests/test-runner.cs
The default behavior is still to produce an NUnit xml file but we can now produce xunit format too with the --xunit option.
Slightly refactored the xml reporting into distinct methods for NUnit/xunit.
Part of #9099
=> [runtime-tests] Add xunit xml output option to test-runner.exe

mcs/class/System.Windows.Forms/System.Windows.Forms/Line.cs
I don't know if there is a reported bug for that, I just found it and fixed it.
There is wrong cursor placement after the \t character. Example:
textBox1.Multiline = true;
textBox1.Text = "aa\taa\r\nbb\tbb\r\n";
Point pt = textBox1.GetPositionFromCharIndex(4); //pt.X is wrong for index 4 or any other char after \t in the line.
=> Fix the bug with multiline TextBox which contains /t characters in the middle of text.

mono/metadata/icall-internals.h, mono/metadata/icall.c, mono/metadata/loader.h, mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c
Fixes https://github.com/mono/mono/issues/10598.
=> [runtime] Avoid warning about missing icalls when AOTing.

mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/corlib/corlib_xtest.dll.sources
Part of #9660.
The changes:
- included corefx version of RuntimeReflectionExtensions class;
- enabled related xunit tests.
=> [System.Reflection] CoreFX import for RuntimeReflectionExtensions

sdks/builds/mxe.mk
**When/if this PR is accepted, could we backport it to the `2018-{04,06,08}` branches as well? It fixes XA build on our PR bots, thanks!**
Debian and its derivatives include full mingw chain (both 64 and 32-bit) and so
they don't need to build the toolchain at all. However, the current detection of
Linux flavor takes into account only Ubuntu and all other distros are configured
to *require* MXE but they do *not* build them.
This commit fixes detection of distros which provide the mingw toolchain in a
way that makes it easy to extend the set of compatible distributions as needed.
In order to mark a distribution as one with MinGW one has to add the `:Distro:`
string to the `LINUX_WITH_MINGW` make variable in `mxe.mk`. The `Distro` string
is whatever the `determine-linux-flavor.sh` script …
=> [sdks] Debian Linux doesn't need to build MXE

sdks/builds/mxe.mk
Backport of #10817.
/cc @luhenry
=> [2018-04] [sdks] Debian Linux doesn\u0027t need to build MXE

mono/mini/Makefile.am.in, mono/mini/test_op_il_seq_point.sh
Looks like: https://github.com/mono/mono/commit/e8029e1474b701184840f6e0abea51966d048831 caused issues in the parameters for this test since caller was not updated accordingly.
This fixes so that the caller pass needed additional argument + simplify the AOT use case for Windows since different tested versions will need different toolchain versions that in turn will cause additional complexity. Since the test doesn't validate the compile/link of AOT module (and don't handle errors)
anyways, Windows versions of this test will just generate assembler output.
=> Fix parameter problem in test_op_il_seq_point.sh.

mono/tests/Makefile.am
They frequently fail, see https://github.com/mono/mono/issues/10845
=> [tests] Disable bug-80392.2.exe and monitor-wait-abort.exe on OSX

sdks/builds/mxe.mk
Backport of #10817.
/cc @luhenry
=> [2018-06] [sdks] Debian Linux doesn\u0027t need to build MXE

mcs/class/System/System.Net/HttpWebRequest.cs
=> [2018-06] [System]: Make sure `HttpWebRequest` observes exceptions on timeout.  #10488.

configure.ac
Restore sqrtf/-lm accidentally deleted in https://github.com/mono/mono/commit/4259352d3a7d4b8d6b9980c4e2da844957710609
=> Restore sqrtf/-lm accidentally deleted in 4259352

sdks/builds/mxe.mk
**Please port this to the `2018-{04,06,08}` branches, thanks!**
It turns out some Debian versions identify themselves as `Debian GNU/Linux`, add
this string to the list of distributions which have mingw. This *should* fix the
PR builds (fingers crossed)
=> [sdks] One more update to get XA PR builds working on Linux

mono/utils/mono-merp.c
@slluis requested this change be merged by tomorrow to make a release window
=> [merp] Fix return value handling of posix_spawn

mono/metadata/threads.c
At the moment of a safepoint, the runtime can be holding the loader lock. Fixes gsharing-valuetype-layout.exe timeouts.
=> [coop] Fix deadlock when unwinding

mono/tests/Makefile.am
According to @kumpera it should be fixed by https://github.com/mono/mono/pull/10793.
=> [tests] Reenable bug-80392.2.exe

sdks/wasm/Makefile, sdks/wasm/README.md, sdks/wasm/WasmHttpMessageHandler.cs, sdks/wasm/sample.cs, sdks/wasm/sample.html
Extend C# sample to include:
- Calling JavaScript functions from C#
- Calling C# functions from JavaScript.
- Referencing JavaScript objects
- Getting and Setting JavaScrip object properties.
- Invoking JavaScript object functions with parameters.
- Setting up the default HttpClientHandler
- Instantiating a default WasmHttpMessageHandler.
- Setting up HttpClient calls
- Parsing and testing the correct results returned from the HtppClient.
- Obtaining a byte array and string array from response.
- Obtaining a reference to a global script function defined in the .html file and calling it.
- Working with DOM objects using the SDK's WebAssembly.Bindings.dll
resolves issue: https://github.com/mono/mono/issues/7548
Also includes a fix the WasmHttpMessageHandler.cs that fixes: …
=> [wasm] Update sample.cs usage and docs

mcs/class/corlib/ReferenceSources/RuntimeType.cs, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/corlib/corlib_xtest.dll.sources, mcs/class/referencesource/mscorlib/system/type.cs
Part of #9660.
The changes:
- included corefx version of TypeInfo type;
- enabled related xunit tests from corefx System.Reflection;
- excluded DeclaredOnlyLookup const from Type class (now it's located in TypeInfo);
- added IsByRef check to RuntimeType's MakePointerType method.
=> [System.Reflection] CoreFX import for TypeInfo type

mcs/errors/Makefile, mcs/tests/Makefile, mcs/tools/mono-symbolicate/Makefile
Add proper dependencies to the test support files where they were missing.
Compile test files using the standard "make test" target.
=> [mcs] Fix test compilation to use common target and refactor mono-symbolicate test building

scripts/ci/pipeline/osx-package.groovy
We're now using an msbuild version which uses .NET Core 2.x which no longer needs openssl.
=> [packaging] Remove installation of openssl via brew on macOS

mono/metadata/appdomain.c
i.e. to  avoid this crash https://gist.github.com/mhutch/d4e6f7b42e5d0fe31434af316264bd84
Instead it will give the admittedly ambiguous:
```
Corlib not in sync with this runtime: expected corlib string (BEAF66F4-BA36-44C5-974E-83C6F627DF8C) but not found or not string
```
Originally https://github.com/mono/mono/commit/c6b8cecb9d6c547d7c5d58721cbf472caa3aae9f#diff-d51dc4dc4a7d7b173dc78504e0be7fa7R372 but later lost.
=> Restore typecheck to corlib version check, so that mixing old integer with new string errors w/o crash.

mcs/class/corlib/System.Reflection/MonoMethod.cs, mcs/class/corlib/Test/System.Reflection/ConstructorInfoTest.cs, mcs/class/corlib/Test/System.Reflection/MethodInfoTest.cs, mcs/tests/ver-il-net_4_x.xml
Fixes https://github.com/mono/mono/issues/10838.
The new behavior is similar to coreclr's one: https://github.com/dotnet/coreclr/blob/af4ec7c89d0192ad14392da04e8c097da8ec9e48/src/System.Private.CoreLib/src/System/Reflection/RuntimeConstructorInfo.cs#L145
=> [Reflection] Fix the issue with ToString method in MonoCMethod type

sdks/builds/llvm.mk
It would get the wrong LLVM hash otherwise.
=> [sdks] Ensure LLVM is cloned before trying to download

mcs/class/corlib/System.Reflection/Module.cs, mcs/class/corlib/Test/System.Reflection/ModuleTest.cs
Backport of #10922.
Description of #10922:
Fixes https://github.com/mono/mono/issues/10876
=> [2018-06] [Reflection] Fix issue with finding types in module using an asterisk as filter criteria

mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Certificate.cs, mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Helper.cs
Backport of #10865.
/cc @baulig
=> [2018-08] Use passwordless import in the `X509Certificate(byte[])` constructor.

mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2.cs, mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Certificate.cs, mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Helper.cs
The `X509Certificate(byte[])` constructor should call `CertificateProvider.Import(byte[])`
to use the native apple implementation if possible.
Fixes #10805
=> Use passwordless import in the `X509Certificate(byte[])` constructor.

mono/metadata/w32handle.c
Backport of #10910.
/cc @luhenry @lambdageek
Description of #10910:
If another thread locked at least one of the handles, and there is a
cooperative GC STW happening, this function will loop forever.
Add GC Safe transitions around the call to sleep to give this thread a chance
to suspend.
Fixes https://github.com/mono/mono/issues/10863
=> [2018-08] [w32handle] Add coop state transitions in mono_w32handle_lock_handles

mono/mini/mini-exceptions.c, mono/utils/mono-threads-mach.c, mono/utils/mono-threads.h
It is exported only when _DARWIN_C_SOURCE is defined.
=> [runtime] Fix undefined pthread_main_np

mono/metadata/w32handle.c
If another thread locked at least one of the handles, and there is a
cooperative GC STW happening, this function will loop forever.
Add GC Safe transitions around the call to sleep to give this thread a chance
to suspend.
Fixes https://github.com/mono/mono/issues/10863
=> [w32handle] Add coop state transitions in mono_w32handle_lock_handles

mono/metadata/w32handle.c
Backport of #10910.
/cc @lambdageek @lambdageek
Description of #10910:
If another thread locked at least one of the handles, and there is a
cooperative GC STW happening, this function will loop forever.
Add GC Safe transitions around the call to sleep to give this thread a chance
to suspend.
Fixes https://github.com/mono/mono/issues/10863
=> [2018-10] [w32handle] Add coop state transitions in mono_w32handle_lock_handles

mono/tests/Makefile.am, mono/tests/thread-suspend-selfsuspended.cs, mono/tests/thread-suspend-suspended.cs
thread-suspend-suspended and thread-suspend-selfsuspended tests has showed long execution times on low core Windows machines running wow64 (x86 binary on x64 OS). It looks like an OS related issue where ResumeThread Win32 API takes a lot longer time to complete when running a test scenario like thread-suspend-suspended and this additional time adds up over many iterations pushing it over to timeout.
NOTE, the same behavior has been identified running on .NET framework, so it's not a mono specific issue and only reproduce under wow64 on low core machines, like the Jenkins Windows builders that only have 2 cores.
Since the purpose of the test is to run GC when t1 is suspended, doing this more deterministic will fix the ResumeThread issue under wow64 on low core machines as well as making …
=> Fix scheduling problem related to thread-suspend-suspended and thread-suspend-selfsuspended.

mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStrip.cs
ToolStrip and MenuStrip look pretty bad if you use a dark theme (such as Adwaita-dark in Ubuntu):
It doesn't seem to matter whether the app sets ToolStrip.BackColor to a value, it always has the same color.
I was not able to find an existing open issue for this.
ToolStrip has a BackColor property, but aside from a getter/setter, it doesn't appear to be used. When it tries to render its own background, ToolStrip passes a background color of SystemColors.Control instead:
https://github.com/mono/mono/blob/f0921fd850b0c8e61d5954fa71471189d2a55447/mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStrip.cs#L1015-L1024
MenuStrip inherits from ToolStrip, including this behavior.
Now ToolStrip will pass its own BackColor property as the background color to use for rendering. This will allow …
=> Paint ToolStrip background with ToolStrip.BackColor

mcs/class/corlib/System.Reflection/Module.cs, mcs/class/corlib/Test/System.Reflection/ModuleTest.cs
Backport of #10922.
Description of #10922:
Fixes https://github.com/mono/mono/issues/10876
=> [2018-08] [Reflection] Fix issue with finding types in module using an asterisk as filter criteria

mcs/class/corlib/System.Reflection/Module.cs, mcs/class/corlib/Test/System.Reflection/ModuleTest.cs
Backport of #10922.
Description of #10922:
Fixes https://github.com/mono/mono/issues/10876
=> [2018-10] [Reflection] Fix issue with finding types in module using an asterisk as filter criteria

mono/mini/mini-runtime.c, mono/utils/mono-compiler.h, mono/utils/mono-signal-handler.h
This time w/o breaking WebAssembly and w/ working on Mac.
=>  Get fault_addr in debugger stacks.

mono/mini/mini-exceptions.c, mono/utils/mono-threads-mach.c, mono/utils/mono-threads.h
Backport of #10899.
Description of #10899:
=> [2018-04] [runtime] Disable stack guard for main thread on osx

sdks/builds/llvm.mk
Backport of #10913.
/cc @luhenry @luhenry
Description of #10913:
It would get the wrong LLVM hash otherwise.
=> [2018-10] [sdks] Ensure LLVM is cloned before trying to download

sdks/builds/ios.mk
xamarin-macios currently builds zlib-helper.o using mono's source code.
It would be preferrable to use a version built by mono, and since
zlib-helper.o is a byproduct of building libMonoPosixHelper, we need to build
libMonoPosixHelper (we already build it for simulator architectures), even
though we don't need/use libMonoPosixHelper itself.
=> [sdks/ios] Build libMonoPosixHelper for device architectures, so that zlib-helper.o is created.

mono/mini/mini-exceptions.c, mono/utils/mono-threads-mach.c, mono/utils/mono-threads.h
Backport of #10899.
Description of #10899:
=> [2018-06] [runtime] Disable stack guard for main thread on osx

mono/mini/mini-exceptions.c, mono/utils/mono-threads-mach.c, mono/utils/mono-threads.h
Backport of #10899.
Description of #10899:
=> [2018-08] [runtime] Disable stack guard for main thread on osx

mono/mini/mini-exceptions.c, mono/utils/mono-threads-mach.c, mono/utils/mono-threads.h
Backport of #10899.
Description of #10899:
=> [2018-10] [runtime] Disable stack guard for main thread on osx

mcs/class/System.Windows.Forms/System.Windows.Forms/DataGridView.cs, mcs/class/System.Windows.Forms/Test/System.Windows.Forms/DataGridViewTest.cs
`DataGridView`'s default colors are currently as follows:
| Cell | Background | Foreground |
| --- | --- | --- |
| Header | `SystemColors.Control` | `SystemColors.WindowText` |
| Regular row | `SystemColors.Window` | `SystemColors.ControlText` |
For a typical theme, this is fine because both foreground colors are black.
For a dark theme, the `Control` colors are light-on-dark while the `Window` colors are black-on-white, so this results in black-on-dark for the header and light-on-white for the rows.
Now `ControlText` is used as the foreground color for `Control`, and `WindowText` is used as the foreground color for `Window`.
=> Fix default colors for DataGridView

sdks/builds/ios.mk
Backport of #10921.
/cc @luhenry @rolfbjarne
Description of #10921:
xamarin-macios currently builds zlib-helper.o using mono's source code.
It would be preferrable to use a version built by mono, and since
zlib-helper.o is a byproduct of building libMonoPosixHelper, we need to build
libMonoPosixHelper (we already build it for simulator architectures), even
though we don't need/use libMonoPosixHelper itself.
=> [2018-10] [sdks/ios] Build libMonoPosixHelper for device architectures, so that zlib-helper.o is created.

sdks/builds/ios.mk
xamarin-macios currently builds zlib-helper.o using mono's source code.
It would be preferrable to use a version built by mono, and since
zlib-helper.o is a byproduct of building libMonoPosixHelper, we need to build
libMonoPosixHelper (we already build it for simulator architectures), even
though we don't need/use libMonoPosixHelper itself.
This is a backport of #10921.
=> [2018-06] [sdks/ios] Build libMonoPosixHelper for device architectures, so that zlib-helper.o is created. (#10921)

mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mono/metadata/class-internals.h, mono/metadata/class.c, mono/metadata/console-unix.c, mono/metadata/custom-attrs.c, mono/metadata/domain.c, mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c, mono/metadata/marshal.h, mono/metadata/metadata.c, mono/metadata/object.c, mono/mini/intrinsics.c, mono/mini/mini-amd64.c, mono/mini/mini-x86.c
The majes the following classes optional to the runtime:
System.Reflection.CustomAttributeData
System.Text.StringBuilder
System.Math
System.Console
System.Diagnostics.StackTrace
This doesn't change the linker scripts so it's not ready to be merged.
Those are all types that can be clearly made optional. There are a lot of other types
we could, but there are deeper dependencies in places as threadpool or marshal.
=> Make a bunch of classes optional to the runtime.

mcs/class/corlib/Test/System.Reflection/CustomAttributeDataTest.cs
This PR adds several unit tests. The fix is in https://github.com/mono/corert/pull/27.
Fixes https://github.com/mono/mono/issues/10951
=> [Reflection] Use actual type of element if constructor of custom attribute typed argument takes an array of objects.

mono/mini/exceptions-ppc.c
=> [runtime] Fix malformed string selection in exceptions-ppc.c

mcs/class/corlib/Test/System.Reflection/CustomAttributeDataTest.cs
Backport of #10972.
Description:
This PR adds several unit tests. The fix is in https://github.com/mono/corert/pull/27.
Fixes https://github.com/mono/mono/issues/10951
=> [2018-10] [Reflection] Use actual type of element if constructor of custom attribute typed argument takes an array of objects.

mono/metadata/appdomain-icalls.h, mono/metadata/appdomain.c, mono/metadata/file-mmap-posix.c, mono/metadata/file-mmap-windows.c, mono/metadata/file-mmap.h, mono/metadata/icall.c, mono/metadata/object-internals.h, mono/metadata/sre.c, mono/metadata/w32socket-unix.c, mono/metadata/w32socket-win32.c, mono/metadata/w32socket.c, mono/metadata/w32socket.h
Though one of these is an enum, use gint32.
The enums MonoResolveTokenError and MonoProtocolType are also used in icalls, but that is left alone.
There's actually a bunch more of this I found later.
Not sure we want to fix them all, or none, etc. Maybe just leave it alone.
=> [icalls] Replace gboolean and mono_bool by MonoBoolean.

mcs/class/System/System.Net/HttpWebRequest.cs
=> [2018-08] [System]: Make sure `HttpWebRequest` observes exceptions on timeout.  #10488.

mono/mini/ir-emit.h, mono/mini/local-propagation.c, mono/mini/mini-llvm.c
Backport of #10096.
Description of #10096:
=> [2018-08] [jit] Fix a constant propagation problem on 32 bit with iconst+conv.i8, we would be setting inst_imm even for long opcodes.

configure.ac, mono/metadata/w32process-unix.c
On systems with a large file descriptor limit, Mono takes a very
long time to spawn a new process; with informal testing on the AIX
CI builder, (with a POWER7) it took ~30 minutes. This is obviously
very undesirable, but hand our is forced - libraries the user might
be calling could be creating non-CLOEXEC files we're unaware of. As
such, we started from the FD limit and worked our way down until we
hit stdio. Using APIs such as posix_spawn aren't desirable as we do
some fiddling with the child before we exec; and even then, closing
FDs with posix_spawn relies on non-standard file actions like
Solaris' addclosefrom not present on many systems. (All of this is
unnecessary on Windows, of course.)
This presents an alternative way (currently only implemented on AIX
but with notes how for …
=> Mitigation for spawn FD closing taking forever with a big FD limit

mcs/build/tests.make
The directory mcs/class/lib/wasm/tests wouldn't necessarily be created before we would try to copy the file to it.
=> [mcs] Fix dependencies on `mcs/class/lib/<Profile>/tests/<Profile>_corlib_test.dll.nunitlite.config`

mono/mini/aot-compiler.c
So it works when running the 64bit as/ld on the host with a 32bit mono binary.
=> AOT: use 32 bit flags for as/ld when targetting x86 on linux

mcs/build/library.make, mcs/build/tests.make
Also, do not rebuild main library if test.sources were changed
=> Depend on all *_test.dll.sources for `make run-test`

sdks/builds/.gitignore, sdks/builds/llvm.mk, sdks/builds/mxe-Win32.cmake.in, sdks/builds/mxe-Win64.cmake.in, sdks/builds/wasm.mk
We couldn't compile `llvmwin{32,64}` on Linux because we would try to use `{i686,x86_64}-w64-mingw-cmake` but it wouldn't exist.
=> [sdks] Add cmake toolchain file for LLVM MXE builds

mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Certificate.cs
Backport of #11057.
/cc @lambdageek 
Description:
Allow the linker to remove UmAlQuraCalendar and HijriCalendar on mobile devices
Match the CoreFX X509Certificate changes: https://github.com/mono/corefx/commit/4eb1fc2abd2ffa70e402d22415d0209b21725a10
Fixes https://github.com/mono/mono/issues/10448
=> [2018-08] Always use InvariantCulture calendars in X509Certificate on Mobile

mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Certificate.cs
Allow the linker to remove UmAlQuraCalendar and HijriCalendar on mobile devices
Match the CoreFX X509Certificate changes: https://github.com/mono/corefx/commit/4eb1fc2abd2ffa70e402d22415d0209b21725a10
Fixes https://github.com/mono/mono/issues/10448
=> Always use InvariantCulture calendars in X509Certificate on Mobile

mcs/class/corlib/System.Reflection/MonoMethod.cs
It allows to re-enable  [Invoke_OneDimensionalArray_NegativeLengths_ThrowsOverflowException](https://github.com/mono/corefx/blob/master/src/System.Reflection/tests/ConstructorInfoTests.cs#L96) test and enable [TestInvoke_1DArrayWithNegativeLength](https://github.com/mono/corefx/blob/master/src/System.Runtime/tests/System/Reflection/ConstructorInfoTests.cs#L79) test.
Fixes https://github.com/mono/mono/issues/10024
=> [Reflection] Handle overflow exception on constructor invocation

mono/metadata/icall.c
This change unifies exception param name value which is expected in https://github.com/mono/corefx/pull/147
=> [Reflection] Unify exception param name

configure.ac, mono/metadata/domain.c, mono/utils/Makefile.am, mono/utils/mono-experiments.c, mono/utils/mono-experiments.def, mono/utils/mono-experiments.h
Implement the idea from #9729
* A `configure` flag `--enable-experiment=LIST` to define compile-time constants for experiments
* Support for a `MONO_EXPERIMENT=LIST` environment variable and `mono_experiment_enabled` test function.
The idea is that experiments are experimental, unsupported and are not guaranteed to be backward compatible.  For small experiments a compile time check is enough.  Larger experiments can live behind the feature flag.
Each experiment also lists a GitHub tracking issue to disable and remove the experiment - either the experiment graduates to a mainline feature or it becomes gated by a regular `configure` flag or some other opt-in mechanism, or it is dropped.
=> Add ability to add experiments without backward compatibility or support guarantees

llvm/build.mk
Previously:
```
remake[2]: Leaving directory '/home/builder/mono/po'
Making all in llvm
Reading makefiles...
remake[2]: Entering directory '/home/builder/mono/llvm'
Updating goal targets....
File 'all' does not exist.
File 'all-am' does not exist.
File 'all-local' does not exist.
File 'configure-llvm' does not exist.
File '/home/builder/mono/llvm/build/Makefile' does not exist.
Must remake target '/home/builder/mono/llvm/build/Makefile'.
Makefile:604: update target '/home/builder/mono/llvm/build/Makefile' due to: ../external/llvm/CMakeLists.txt
##>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
cd /home/builder/mono/llvm/build && /usr/bin/cmake \
\
-DCMAKE_INSTALL_PREFIX="/home/builder/mono/llvm/usr" \
-DCMAKE_BUILD_TYPE=Release \
-DLLVM_BUILD_TESTS=Off \
-DLLVM_INCLUDE_TESTS=Off …
```
=> [runtime] Fix internal llvm

sdks/builds/.gitignore, sdks/builds/llvm.mk, sdks/builds/mxe-Win32.cmake.in, sdks/builds/mxe-Win64.cmake.in
Backport https://github.com/mono/mono/pull/11008
We couldn't compile llvmwin{32,64} on Linux because we would try to use {i686,x86_64}-w64-mingw-cmake but it wouldn't exist.
=> [2018-06] [sdks] Add cmake toolchain file for LLVM MXE builds

mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Certificate.cs
Backport of #11057.
/cc @lambdageek 
Description:
Allow the linker to remove UmAlQuraCalendar and HijriCalendar on mobile devices
Match the CoreFX X509Certificate changes: https://github.com/mono/corefx/commit/4eb1fc2abd2ffa70e402d22415d0209b21725a10
Fixes https://github.com/mono/mono/issues/10448
=> [2018-10] Always use InvariantCulture calendars in X509Certificate on Mobile

configure.ac, mcs/class/corlib/Mono/Runtime.cs, mcs/class/corlib/Test/System/ExceptionTest.cs, mono/metadata/class-internals.h, mono/metadata/debug-helpers.c, mono/metadata/domain-internals.h, mono/metadata/icall-decl.h, mono/metadata/icall-def.h, mono/metadata/icall.c, mono/metadata/mono-debug.c, mono/metadata/object-internals.h, mono/metadata/threads-types.h, mono/metadata/threads.c, mono/mini/aot-runtime.c, mono/mini/debugger-engine.c, mono/mini/interp/transform.c, mono/mini/mini-exceptions.c, mono/mini/mini-posix.c, mono/mini/mini-runtime.c, mono/mini/mini-runtime.h, mono/mini/mini.c, mono/mini/seq-points.c, mono/mini/seq-points.h, mono/utils/mono-state.c, mono/utils/mono-state.h, mono/utils/mono-threads-posix.c, mono/utils/mono-threads.h
This change set represents a major set of changes to the crash reporting mechanism. 
1) Coordination involving mandatory timeouts and signals have been changed greatly, to instead use semaphores and to end waiting as soon as possible. 
2) Dumping of unmanaged symbols outside of mono has been made possible. Embedders that want to get information on frames outside of mono-sgen can register the library with an icall. This carefully preserves both privacy (opt-in) and resiliency (can't crash/lose more info when misused).
3) The dumper has moved from a workflow that kills the runtime after a long delay into one that can dump individual threads or the entire runtime in a prompt manner. The runtime doesn't die at the end of the dump, but allows threads to resume what they were doing and returns …
=> [crash] Crash Reporter V2

mono/mini/mini-x86.c
I don't know what the specific code is or what changed, etc.
This addresses Mac/x86:
https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/15364/parsed_console/log.html
```Unable to compile method 'int Tests:calli_sig_check_2 ()' due to: 'Invalid IL code in Tests:calli_sig_check_2 (): IL_000b: calli     0x11000044```
which then fails an assert and fails overall.
CI goes deep into bash w/o echoing commands but a repro is:
cd mono/mini
MONO_PATH=./../../mcs/class/lib/net_4_x lldb -- ./mono --aot iltests.exe
The code is meant to be invalid, and meant to raise an exception,
which is catchable/resumable (at least in the JIT case where
executing IL the first time, can raise an exception while caller is
running, vs. AOT where the codegen all happens offline -- leaving what?
A note …
=> x86 mono_arch_get_patch_offset: add support for 0xe9/jmp eip+32b.

mono/mini/TestHelpers.cs
so it doesn't overflow the stack when running on macOS with `clang -O0`.
=> [tests] lower recursion depth of PerformNoPinAction

mono/mini/mini-exceptions.c
Related: https://github.com/mono/mono/issues/10415
=> [exceptions] continue program execution when mapping of stack overflow guard page fails

mono/mini/aot-compiler.c, mono/mini/mini-amd64.c, mono/mini/mini-amd64.h, mono/mini/mini-arm.c, mono/mini/mini-arm64.c, mono/mini/tramp-amd64.c
This makes amd64 have same behaviour as arm and arm64, on the interpreter entry side. Remove the old code.
=> [interp] Implement interpreter entry trampolines on amd64

llvm/SUBMODULES.json, sdks/builds/llvm.mk
Backport of https://github.com/mono/mono/pull/10611.
=> [2018-08] [sdks] Fix llvm-llvm32 build

sdks/builds/.gitignore, sdks/builds/llvm.mk, sdks/builds/mxe-Win32.cmake.in, sdks/builds/mxe-Win64.cmake.in
Backport https://github.com/mono/mono/pull/11008
We couldn't compile llvmwin{32,64} on Linux because we would try to use {i686,x86_64}-w64-mingw-cmake but it wouldn't exist.
=> [2018-08] [sdks] Add cmake toolchain file for LLVM MXE builds

sdks/builds/.gitignore, sdks/builds/llvm.mk, sdks/builds/mxe-Win32.cmake.in, sdks/builds/mxe-Win64.cmake.in, sdks/builds/wasm.mk
Backport https://github.com/mono/mono/pull/11008
We couldn't compile llvmwin{32,64} on Linux because we would try to use {i686,x86_64}-w64-mingw-cmake but it wouldn't exist.
=> [2018-10] [sdks] Add cmake toolchain file for LLVM MXE builds

mono/metadata/class-init.c, mono/metadata/class.c, mono/metadata/class.h, mono/metadata/cominterop.c, mono/metadata/custom-attrs.c, mono/metadata/icall.c, mono/metadata/loader.c, mono/metadata/marshal.c, mono/metadata/metadata-internals.h, mono/metadata/object.c, mono/metadata/verify.c, mono/mini/aot-runtime.c, mono/mini/debugger-agent.c, mono/mini/mini-generic-sharing.c
`MONO_CLASS_IS_INTERFACE` uses `mono_class_get_type`.
`MONO_CLASS_IS_INTERFACE_INTERNAL` uses `m_class_get_byval_arg` instead.
Despite the much different name, the difference is only GC mode transition.
There is no other runtime user of `mono_class_get_type`, so `mono_class_get_type_internal` not introduced. If needed, either introduce `mono_class_get_type_internal`, or use `m_class_get_byval_arg` instead.
=> Replace MONO_CLASS_IS_INTERFACE  with MONO_CLASS_IS_INTERFACE_INTERNAL, remove gc mode transitions.

mcs/class/corlib/System.Reflection/MonoParameterInfo.cs
This PR fixes the bugs caught by [RawDefaultValue](https://github.com/mono/corefx/blob/411def5f278956f3c514c02ab76d9bb89428fef7/src/System.Runtime/tests/System/Reflection/ParameterInfoTests.cs#L22) and [VerifyParameterInfoGetRealObjectWorks](https://github.com/mono/corefx/blob/411def5f278956f3c514c02ab76d9bb89428fef7/src/System.Runtime/tests/System/Reflection/ParameterInfoTests.cs#L91) tests
=> [Reflection] Fixing bugs in MonoParameterInfo caught by xunit tests

mono/mini/mini-ppc.c
Fixes https://github.com/mono/mono/issues/11021
=> [ppc] use G_BYTE_ORDER in order to define patch_load_sequence

mono/metadata/threads-types.h, mono/mini/mini-exceptions.c, mono/utils/mono-state.c
The VS4M team is making a tool that makes a symbolication lookup table. This enables symbolication without access to the relevant binary. 
For unmanaged, it's much harder to precompute things because we were presenting the instruction address. From the address, any lookup needs to find the function enclosing this interior pointer.
To make it easier, this reports the address of the native method as well as the offset. A lookup table can simply key on the function start address with this now. 
ie:
``` 
{
"native_address" : "0x1003a6340",
"native_offset" : "0x00046",
"native_module" : "mono"
}
```
```
$ nm mini/mono-sgen | grep '1003a6340' 
00000001003a6340 t _mono_runtime_run_main_checked
```
```
$ nm mini/mono-sgen | grep ' t ' | sort -n
00000001000a4e90 t _alloc_ireg
00000001000a4eb0 t …
```
=> [crash] Split unmanaged method pointers into method ip + offset

mono/metadata/class-internals.h, mono/metadata/class.c, mono/metadata/icall.c, mono/metadata/sre.c, mono/mini/interp/transform.c, mono/mini/memory-access.c, mono/mini/method-to-ir.c, mono/mini/mini-arm.c, mono/mini/mini-arm64.c, mono/mini/mini-codegen.c, mono/mini/mini-native-types.c, mono/mini/simd-intrinsics.c
But also optimize mono_field_get_type in the common case, to "short circuit"
and skip ditto.
=> mono_field_get_type to mono_field_get_type_internal to skip GC mode machinery

sdks/builds/llvm.mk
This breaks when LLVM is built on 10.13+ and the runtimes are built on 10.12.
=> [2018-06] [sdks] futimens and futimes symbols are missing on anything earlier than 10.13

llvm/build.mk
Backport of #11176.
/cc @luhenry 
Description:
This breaks when LLVM is built on 10.13+ and the runtimes are built on 10.12.
=> [2018-10] [sdks] futimens and futimes symbols are missing on anything earlier than 10.13

llvm/build.mk
Backport of #11176.
/cc @luhenry 
Description:
This breaks when LLVM is built on 10.13+ and the runtimes are built on 10.12.
=> [sdks] futimens and futimes symbols are missing on anything earlier than 10.13

llvm/build.mk
This breaks when LLVM is built on 10.13+ and the runtimes are built on 10.12.
=> [2018-08] [sdks] futimens symbols are missing on anything earlier than 10.13

mcs/Makefile, mcs/build/Makefile, mcs/build/library.make, mcs/build/profiles/build.make, mcs/build/rules.make, mcs/class/Facades/subdirs.make, mcs/class/Makefile, mcs/class/Mono.CompilerServices.SymbolWriter/Makefile, mcs/class/System.Core/basic_System.Core.dll.sources, mcs/class/System/basic_System.dll.sources, mcs/class/corlib/Makefile
The platform specific build got lost in 8d8fd97dbfc6f4213e0fe9fca7574808dd8496d3 but we need it for monolite. The remnants of the "basic" profile are no longer needed.
=> [mcs] Fix platform-specific build of "build" profile and remove more remnants of the "basic" profile

mono/metadata/icall.c, mono/tests/Makefile.am, mono/tests/delegate16.cs
Avoid optimization for Delegate:CreateDelegate when class is Delegate or MulticastDelegate. Fixes #11181.
=> Take fast path only for delegate types not Delegate/MulticastDelegate.

llvm/SUBMODULES.json
Backport of #10983.
/cc @luhenry 
Description:
=> [2018-10] Bump to llvm/release_60/117a508c

configure.ac
Doing what the error says leads to many compilation errors, i.e. building for Cygwin, which is quite 
broken. Following CI is looking promising.
=> Fix configure error message to match scripts/ci.

mcs/class/System.Windows.Forms/System.Windows.Forms/MessageBox.cs
`MessageBox` displays as black-on-dark in a dark theme:
This can be difficult to read.
The text is drawn with a hard coded color of `Color.Black`. This assumes that the background under the text will be light to contrast with black.
Now the color is `SystemColors.ControlText` instead, to match the background of the popup.
In a normal theme this will still be black.
=> Fix MessageBox text color for dark themes

mono/metadata/icall.c, mono/tests/Makefile.am, mono/tests/delegate16.cs
Backport of #11182.
/cc @alexischr @joncham
Description:
Avoid optimization for Delegate:CreateDelegate when class is Delegate or MulticastDelegate. Fixes #11181.
=> [2018-10] Take fast path only for delegate types not Delegate/MulticastDelegate.

mcs/class/corlib/System/Console.cs
The Console class wraps the standard system stream reader/writers on construction so as to expose them as thread-safe. However, the Set-Out/In/Err methods in referencesource do not do the same when they replace default targets.
CoreFX code does: https://github.com/mono/corefx/blob/1748f6492e8b96842f76e1a9e7b5d7e8ccfca480/src/System.Console/src/System/Console.cs#L412-L444
Possible fix for https://github.com/mono/mono/issues/11146
=> [corlib] Ensure that Console Streams are thread-safe

mcs/class/corlib/System.Reflection/MonoMethod.cs
Backport of #11028.
Description:
It allows to re-enable  [Invoke_OneDimensionalArray_NegativeLengths_ThrowsOverflowException](https://github.com/mono/corefx/blob/master/src/System.Reflection/tests/ConstructorInfoTests.cs#L96) test and enable [TestInvoke_1DArrayWithNegativeLength](https://github.com/mono/corefx/blob/master/src/System.Runtime/tests/System/Reflection/ConstructorInfoTests.cs#L79) test.
Fixes https://github.com/mono/mono/issues/10024
=> [2018-10] [Reflection] Handle overflow exception on constructor invocation

mcs/class/corlib/System/Console.cs
Backport of #11205.
Description:
The Console class wraps the standard system stream reader/writers on construction so as to expose them as thread-safe. However, the Set-Out/In/Err methods in referencesource do not do the same when they replace default targets.
CoreFX code does: https://github.com/mono/corefx/blob/1748f6492e8b96842f76e1a9e7b5d7e8ccfca480/src/System.Console/src/System/Console.cs#L412-L444
Possible fix for https://github.com/mono/mono/issues/11146
=> [2018-10] [corlib] Ensure that Console Streams are thread-safe

mono/mini/aot-runtime.c
Backport of #11190.
Description:
Executing aot code that uses them would crash. Fixes random csc crashes.
=> [2018-06] [aot] Ensure shared got entries are initialized before loading methods

mcs/class/corlib/System/Console.cs
Backport of #11205.
Description:
The Console class wraps the standard system stream reader/writers on construction so as to expose them as thread-safe. However, the Set-Out/In/Err methods in referencesource do not do the same when they replace default targets.
CoreFX code does: https://github.com/mono/corefx/blob/1748f6492e8b96842f76e1a9e7b5d7e8ccfca480/src/System.Console/src/System/Console.cs#L412-L444
Possible fix for https://github.com/mono/mono/issues/11146
=> [2018-08] [corlib] Ensure that Console Streams are thread-safe

mono/mini/aot-tests.cs, mono/mini/mini-amd64.c, mono/mini/mini-amd64.h, mono/mini/mini-arm64.c, mono/mini/mini-arm64.h
Fixes https://github.com/xamarin/xamarin-macios/issues/4984.
=> [arm64] Remove the limitation on the number of nullable arguments for dyncalls.

sdks/wasm/packager.cs
packager.exe should not write duplicate assembly entries to the list of assemblies to load when writing the config.js file_list: [].
resolves: https://github.com/mono/mono/issues/11187
=> [wasm] [packager] Fix Duplicate assemblies in `config.js` file_list: [ ... ]

mcs/build/Makefile, mono/eglib/Makefile.am
They require the additional files:
- mono/eglib/eglib-config.h: that's to build `libmonodroid`
- mcs/build/Consts.cs: that's to build `Mono.Posix` and `Mono.Data.Sqlite`
=> [sdks] Package what's missing for XA

mcs/build/Makefile, mono/eglib/Makefile.am
Backport of #11253.
/cc @luhenry 
Description:
They require the additional files:
- mono/eglib/eglib-config.h: that's to build `libmonodroid`
- mcs/build/Consts.cs: that's to build `Mono.Posix` and `Mono.Data.Sqlite`
=> [2018-10] [sdks] Package what’s missing for XA

mcs/build/Makefile, mono/eglib/Makefile.am
Backport of https://github.com/mono/mono/pull/11253.
Description:
They require the additional files:
- mono/eglib/eglib-config.h: that's to build `libmonodroid`
- mcs/build/Consts.cs: that's to build `Mono.Posix` and `Mono.Data.Sqlite`
=> [2018-08] [sdks] Package what's missing for XA

mcs/class/System.Windows.Forms/System.Windows.Forms/TextRenderer.cs
flags to DrawText never reached MeasureText therefore strings with '&' were measured incorrect when drawn with flag TextFormatFlags.NoPrefix.
Fixes #6352
=> [WinForms] Propagate the flags from DrawTextInternal to MeasureTextInternal

mcs/class/System.Windows.Forms/System.Windows.Forms/TextRenderer.cs
Backport of #11251.
/cc @akoeplinger @markusbeth
Description:
flags to DrawText never reached MeasureText therefore strings with '&' were measured incorrect when drawn with flag TextFormatFlags.NoPrefix.
Fixes #6352
=> [2018-08] [WinForms] Propagate the flags from DrawTextInternal to MeasureTextInternal

mcs/class/System.Windows.Forms/System.Windows.Forms/TextRenderer.cs
Backport of #11251.
/cc @akoeplinger @markusbeth
Description:
flags to DrawText never reached MeasureText therefore strings with '&' were measured incorrect when drawn with flag TextFormatFlags.NoPrefix.
Fixes #6352
=> [2018-10] [WinForms] Propagate the flags from DrawTextInternal to MeasureTextInternal

mono/metadata/icall.c
We must not get a TLE if referenced types are in an assembly that can't be
loaded.
Fixes https://github.com/mono/mono/issues/11123
TODO:
=> [runtime] Don't init classes in ves_icall_RuntimeTypeHandle_is_subclass_of

mono/mini/aot-tests.cs, mono/mini/mini-amd64.c, mono/mini/mini-amd64.h, mono/mini/mini-arm64.c, mono/mini/mini-arm64.h
Backport of #11186.
Description:
Fixes https://github.com/xamarin/xamarin-macios/issues/4984.
=> [2018-08] [arm64] Remove the limitation on the number of nullable arguments for dyncalls.

mono/mini/aot-tests.cs, mono/mini/mini-amd64.c, mono/mini/mini-amd64.h, mono/mini/mini-arm64.c, mono/mini/mini-arm64.h
Backport of #11186.
Description:
Fixes https://github.com/xamarin/xamarin-macios/issues/4984.
=> [2018-10] [arm64] Remove the limitation on the number of nullable arguments for dyncalls.

mono/mini/method-to-ir.c, mono/mini/mini-amd64.c, mono/mini/mini-arm.c, mono/mini/mini-arm64.c, mono/mini/mini-mips.c, mono/mini/mini-ppc.c, mono/mini/mini-s390x.c, mono/mini/mini-sparc.c, mono/mini/mini-wasm.c, mono/mini/mini-x86.c, mono/mini/mini.h
FullAOT is hypothetically ok, but FullAOT has other problems (https://github.com/mono/mono/issues/11276).
This addresses https://github.com/mono/mono/issues/11265.
This regressed presumably https://github.com/mono/mono/commit/f5373adc8a89d4b0d1d549fdd6d9adc3ded4b400.
Also enable direct tailcalls to self generally, with tail. prefix, w/o requiring optimization enabled.
=> Disable direct x86 aot tailcalls. Except to self.

mono/mini/builtin-types.cs, mono/mini/interp/transform.c
Backport of #11259.
/cc @lewurm 
Description:
Fixes `MutableDataTest.Constructor` on Xamarin.iOS with interpreter.
monotouch tests are looking good now with interp-only:
😬
=> [2018-06] [interp] use unsigned conversion for nuint

mcs/class/Microsoft.Build.Engine/Makefile
Since we've started embedding test resources inside of the test assembly
we've sometimes seen a strange error on Jenkins during the test run:
```
Msg: Error initializing task StringTestTask: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Msg: Error initializing task StringTestTask: System.TypeLoadException: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
at (wrapper managed-to-native) System.RuntimeType.GetConstructors_native(System.RuntimeType,System.Reflection.BindingFlags)
...
```
However this was from an xbuild_12 run so how come it tried to load xbuild 14 …
=> [Microsoft.Build.Engine] Fix race condition in TestTasks.dll compilation and embedding

mono/metadata/icall-internals.h, mono/metadata/icall.c, mono/metadata/loader.h, mono/metadata/marshal-ilgen.c, mono/metadata/pal-icalls.c, mono/metadata/sgen-toggleref.c, mono/metadata/sgen-toggleref.h, mono/metadata/w32file-unix.c, mono/mini/mini-runtime.c, mono/mini/mini-wasm.c, mono/mini/tasklets.c, mono/profiler/log.c
* Mark `mono_add_internal_call` external only.  Add `mono_add_internal_call_internal` and `mono_add_internal_call_with_flags` for the runtime.
- icalls added using the external-only API are "foreign".
* Add coop transitions around `mono_gc_toggleref_add` (and mark it external only  - it's unused in the runtime).
* Change icall wrappers to call foreign icalls in GC Safe mode.
- foreign icalls are not coop-aware, so if they perform a blocking operation under hybrid suspend they will hang indefinitely - this is bug #11138. With this change, we run them in GC Safe mode and rely on the runtime API to transition back to GC Unsafe (same as other embedder code).
- this will require changes to watchOS support in xamarin-macios.
----
This is the `2018-08` version - `master` version is coming soon …
=> [2018-08][marshal] Emit GC Safe transitions around foreign internal calls.

mono/dis/dump.c, mono/metadata/class-init.c, mono/metadata/class-internals.h, mono/metadata/class.c, mono/metadata/class.h, mono/metadata/custom-attrs.c, mono/metadata/icall.c, mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c, mono/metadata/metadata.c, mono/metadata/object.c, mono/metadata/reflection.c, mono/metadata/sre-encode.c, mono/metadata/sre.c, mono/metadata/verify.c, mono/mini/aot-runtime-wasm.c, mono/mini/dwarfwriter.c, mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c, mono/mini/interp/transform.c, mono/mini/method-to-ir.c, mono/mini/mini-generic-sharing.c, mono/mini/mini-llvm.c, mono/mini/mini-s390x.c, mono/mini/mini.c
Backport of #11079.
Description:
=> [2018-08] mono_class_enum_basetype to mono_class_enum_basetype_internal to skip GC mode machinery.

mono/metadata/class-init.c, mono/metadata/class-internals.h, mono/metadata/class.c, mono/metadata/class.h, mono/metadata/custom-attrs.c, mono/metadata/icall.c, mono/metadata/loader.c, mono/metadata/object.c, mono/metadata/verify.c, mono/mini/aot-compiler.c, mono/mini/branch-opts.c, mono/mini/debugger-agent.c, mono/mini/interp/interp.c, mono/mini/method-to-ir.c, mono/mini/mini-generic-sharing.c
Backport of #11081.
Description:
FIXME mono_class_is_assignable_from_checked
=> [2018-10] mono_class_is_assignable_from to mono_class_is_assignable_from_internal to skip GC mode machinery

mono/metadata/class-init.c, mono/metadata/class-internals.h, mono/metadata/class.c, mono/metadata/class.h, mono/metadata/custom-attrs.c, mono/metadata/icall.c, mono/metadata/loader.c, mono/metadata/object.c, mono/metadata/verify.c, mono/mini/aot-compiler.c, mono/mini/branch-opts.c, mono/mini/debugger-agent.c, mono/mini/interp/interp.c, mono/mini/method-to-ir.c, mono/mini/mini-generic-sharing.c
Backport of #11081.
Description:
FIXME mono_class_is_assignable_from_checked
=> [2018-08] mono_class_is_assignable_from to mono_class_is_assignable_from_internal to skip GC mode machinery

mono/mini/builtin-types.cs, mono/mini/interp/transform.c
Backport of #11259.
/cc @lewurm 
Description:
Fixes `MutableDataTest.Constructor` on Xamarin.iOS with interpreter.
monotouch tests are looking good now with interp-only:
😬
=> [2018-10] [interp] use unsigned conversion for nuint

mono/metadata/class-init.c, mono/tests/Makefile.am, mono/tests/bug-gh-9507.cs
Fixes https://github.com/mono/mono/issues/9507
Background: Monoclass:cast_class is used internally to allow for some interfaces to be assignable to each other if they share a "storage class" instead of the class's element class. This is used to i.e. implement IList<ulong> being assignable from IList<long> (IList<ulong> has cast_class=long)
Consider a GenericClass<T> with a T[] field. On instantiation with e.g. GenericClass<ulong> , the ulong[] array class will be generated. As above, ulong[] has cast_class=long
When mono_class_init() is called on an array class, its element_class is also initialized.
If GenericClass<T>:Method() uses any type/subtype checking (e.g. if (field is double[]) ), those may attempt to use cast_class, which is not ensured as initialized.
=> [class] Ensure 'cast_class' is initialized for array type classes.

mono/metadata/marshal-ilgen.c
Backport PR https://github.com/mono/mono/pull/11106 missed a call
=> [marshal] Fixup missed mono_class_is_assignable_from

mono/metadata/icall-internals.h, mono/metadata/icall.c, mono/metadata/loader-internals.h, mono/metadata/loader.h, mono/metadata/marshal-ilgen.c, mono/metadata/sgen-toggleref.c, mono/metadata/sgen-toggleref.h, mono/metadata/w32file-unix.c, mono/mini/mini-runtime.c, mono/mini/mini-wasm.c, mono/mini/tasklets.c, mono/native/pal-icalls.c, mono/profiler/log.c
* Mark `mono_add_internal_call` external only.  Add `mono_add_internal_call_internal` and `mono_add_internal_call_with_flags` for the runtime.
- icalls added using the external-only API are "foreign".
* Add coop transitions around `mono_gc_toggleref_add` (and mark it external only  - it's unused in the runtime).
* Change icall wrappers to call foreign icalls in GC Safe mode.
- foreign icalls are not coop-aware, so if they perform a blocking operation under hybrid suspend they will hang indefinitely - this is bug #11138. With this change, we run them in GC Safe mode and rely on the runtime API to transition back to GC Unsafe (same as other embedder code).
- this will require changes to watchOS support in xamarin-macios.
----
This is the `master` version.  `2018-08` backport is #11180
=> [marshal] Emit GC Safe transitions around foreign internal calls.

mcs/class/corlib/System.Reflection/MonoParameterInfo.cs, mcs/class/corlib/System.Reflection/MonoProperty.cs, mcs/class/corlib/Test/System.Reflection/ParameterInfoTest.cs, mono/metadata/icall.c
Mono returns custom modifiers in the same order as they appear in the signatures. NetFX/CoreFX returns them in reversed order. So we just reverse the order to follow NetFX/CoreFX behavior.
Fixes https://github.com/mono/mono/issues/11302
=> [Reflection] Fix ParameterInfo's custom modifiers order

mono/mini/mini-wasm.c
Backport of #11335.
/cc @lambdageek 
Description:
Fixup for
https://github.com/mono/mono/commit/5e961c6deb27c6bfc46cdba99274bbe02f8f0562
=> [2018-10] [wasm] Add missing include

mono/metadata/boehm-gc.c, mono/metadata/icall.c, mono/metadata/object.c, mono/metadata/object.h, mono/metadata/remoting.c, mono/metadata/sgen-bridge.c, mono/metadata/sgen-toggleref.c, mono/metadata/threads.c, mono/mini/mini-wasm.c
Replacement for #11105.
Backport of #11077.
=> [2018-10] Replace mono_object_get_class with mono_object_class to avoid gc transitions.

mono/metadata/boehm-gc.c, mono/metadata/icall.c, mono/metadata/object.c, mono/metadata/object.h, mono/metadata/remoting.c, mono/metadata/sgen-bridge.c, mono/metadata/sgen-toggleref.c, mono/metadata/threads.c, mono/mini/mini-wasm.c
Replacement for #11104.
Backport of #11077.
=> [2018-08] Replace mono_object_get_class with mono_object_class to avoid gc transitions.

mono/mini/TestHelpers.cs
Backport of #11065.
/cc @lewurm 
Description:
so it doesn't overflow the stack when running on macOS with `clang -O0`.
=> [2018-08] [tests] lower recursion depth of PerformNoPinAction

mcs/class/corlib/corlib_xtest.dll.sources
MemberInfoTests.cs and TypeInfoTests moved from System.Runtime -> System.Reflection
Also some tests were added to ParameterInfoTests.cs that fail on 2018-10
=> [2018-10] Bump corefx submodule

mono/mini/TestHelpers.cs
Backport of #11065.
/cc @lewurm 
Description:
so it doesn't overflow the stack when running on macOS with `clang -O0`.
=> [2018-10] [tests] lower recursion depth of PerformNoPinAction

mcs/class/corlib/LinkerDescriptor/mscorlib.xml, mcs/class/corlib/Mono/RuntimeStructs.cs, mono/eglib/glib.h, mono/metadata/exception.c, mono/metadata/handle-decl.h, mono/metadata/handle.c, mono/metadata/handle.h, mono/metadata/icall-table.h, mono/metadata/marshal-ilgen.c, mono/metadata/marshal.c, mono/metadata/marshal.h, mono/metadata/metadata-internals.h, mono/metadata/method-builder-ilgen-internals.h, mono/metadata/method-builder-ilgen.c, mono/metadata/object-internals.h, mono/mini/mini.c, mono/utils/monobitset.c, mono/utils/monobitset.h
This builds on the stack-based icall parameter handles in https://github.com/mono/mono/pull/11293, and also drives the managed/native transitions to the ideal one.
Managed doesn't need the handle frame -- native can do it.
And native can also do the MonoError handling.
=> Stack-based icall parameter handles and only one managed/native transition per icall.

mono/tests/TestingReferenceReferenceAssembly.cs, mono/tests/reference-loader.cs
Loading a type that has a field from an assembly that cannot be loaded should
still leave the type usable for some operations such as IsSubclassOf.
Regression test for #11123
=> [tests] Regression test for #11123

mcs/tools/linker/Makefile
The BCL size regression (see https://github.com/mono/mono/pull/11041) was actually caused by changes in linker/Makefile: https://github.com/mono/mono/commit/539b14892000f3c4b13657161819680dd9aa098c#diff-f2d312cb75589935c2b11af219414f48L73
With this fix it's green again:
=> Fix bcl-size-diff command

mono/mini/aot-compiler.c, mono/mini/aot-runtime.c, mono/mini/aot-runtime.h, mono/mini/interp/transform.c, mono/mini/jit-icalls.c, mono/mini/mini-llvm.c, mono/mini/mini-trampolines.c
On a virtual call where the receiver is a value type, the value type is
boxed at the caller's site, but must be unboxed before passed to the
callee. In FullAOT this happens with the help of the `unbox_trampoline`,
which is attached to the AOT'd assembly for every virtual method with a
value type as receiver, so we have a specific `unbox_trampoline` for
each such `MonoMethod`.
In mixed mode it can happen that an FullAOT'd method is calling such a
method which is _not_ FullAOT compiled, therefore it has to be executed
by the interpreter. We have to insert a trampoline between AOT caller
and interp callee (being a native-to-interp entry), that does the
unboxing and has a configurable target address at run-time. So that:
AOT caller -> unbox_arbitrary_trampoline -> native-to-interp entry
Note …
=> [aot] add unbox_arbitrary_trampoline for fullaot/interp mixed mode

sdks/wasm/driver.c
https://jenkins.mono-project.com/job/test-mono-pull-request-wasm-cxx/536/parsed_console/log.html
driver.c:254:11: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
strcpy (&name [len - 3], "dll");
^~~~~~~~~~~~~~~
/mnt/jenkins/workspace/test-mono-pull-request-wasm-cxx/sdks/builds/toolchains/emsdk/emscripten/1.38.11/system/include/libc/string.h:31:31: note: passing argument to parameter here
char *strcpy (char *__restrict, const char *__restrict);
=> Fix const warning. And integer overflow for degenerate input. And C++.

mono/mini/aot-compiler.c
=> Remove errant character from 3bf5c2bd10ff05874ad5e94a8ef98eae61484243 that breaks compile.

mcs/class/System.Core/System.Core.csproj, mcs/class/System.Core/corefx/Interop.cs, mcs/class/System.Core/unix_net_4_x_System.Core.dll.sources
This is a temporary fix; the native side still needs to be ported from c++ and tested.
=> [System.Core]: Stub out `Interop.Sys.GetEUid` and `SetEUid`.

mono/mini/interp/interp.c
```
interp/interp.c:2337:17: warning: unused variable 'entry_funcs_static' [-Wunused-variable]
static gpointer entry_funcs_static [MAX_INTERP_ENTRY_ARGS + 1] = { INTERP_ENTRY_FUNCLIST (static) };
^
interp/interp.c:2338:17: warning: unused variable 'entry_funcs_static_ret' [-Wunused-variable]
static gpointer entry_funcs_static_ret [MAX_INTERP_ENTRY_ARGS + 1] = { INTERP_ENTRY_FUNCLIST (static_ret) };
^
interp/interp.c:2339:17: warning: unused variable 'entry_funcs_instance' [-Wunused-variable]
static gpointer entry_funcs_instance [MAX_INTERP_ENTRY_ARGS + 1] = { INTERP_ENTRY_FUNCLIST (instance) };
^
interp/interp.c:2340:17: warning: unused variable 'entry_funcs_instance_ret' [-Wunused-variable]
static gpointer entry_funcs_instance_ret [MAX_INTERP_ENTRY_ARGS + 1] = { INTERP_ENTRY_FUNCLIST …
```
=> [interp] fix unused variable warnings

mcs/class/System.Core/System.Core.csproj, mcs/class/System.Core/corefx/Interop.cs, mcs/class/System.Core/unix_net_4_x_System.Core.dll.sources
Backport of #11366.
/cc @baulig 
Description:
This is a temporary fix; the native side still needs to be ported from c++ and tested.
=> [2018-10] [System.Core]: Stub out `Interop.Sys.GetEUid` and `SetEUid`.

mono/mini/mini-s390x.c
Two instances were missed when mono_class_from_mono_type was changed to mono_class_from_mono_type_internal
=> A couple of missing mono_class_from_mono_type_internal changes

mcs/class/Facades/netstandard/Facades_netstandard.csproj, mcs/class/Facades/netstandard/Makefile, mcs/class/Facades/netstandard/Stubs.build.cs, mcs/class/Facades/netstandard/TypeForwarders.cs, mcs/class/Facades/netstandard/build_netstandard.dll.sources, mcs/class/Facades/subdirs.make, mcs/class/Makefile
It is necessary for a helix tool which I'm building in this profile and it relies on NS2.0.
Adding full NS2.0 would require building System.Transactions.dll, System.Runtime.Serialization.dll and System.Data.dll too but those in turn rely on a whole bunch of other junk that I don't want to bring
into the build profile. 
Therefore I just added stubs for the types directly into netstandard.dll.
=> [build] Enable netstandard facade in the "build" profile

mcs/class/Mono.Profiler.Log/Test/ProfilerTestRun.cs
So they don't depend on the working dir.
=> [Mono.Profiler.Log] Use full path for temporary .mlpd's

mono/metadata/metadata.c
Fixes #10945
Reverts fix for #6936
https://github.com/mono/mono/issues/10945 appears to have been introduced by https://github.com/mono/mono/commit/9dc6c344ac34a470fa0f4fc411e357f7eaf577fd. Unfortunately it is not possible to revert the commit at this point using git revert, but manually disabling the equality change fixes BinaryFormatter. This should be sufficient to get a lot of the broken roslyn tests working again.
=> Partially exclude custom modifiers from metadata type equality

mcs/class/reference-assemblies/Makefile, mcs/mcs/ikvm.cs, mcs/tools/xbuild/Makefile, mcs/tools/xbuild/frameworks/net_4.7.2.xml
Adding .NET 4.7.2 reference assemblies by updating submodule reference and adding new framework to mcs/tools/xbuild/frameworks and update Makefile to ship as described in #8657.
=> Add .NET 4.7.2 reference assemblies

mono/tests/Makefile.am
https://github.com/mono/mono/issues/11392
=> [runtime] Disables crashing appdomain-threadpool-unload.exe test

mono/metadata/marshal-ilgen.c
`ex_local` and `e_local` were used prior to
https://github.com/mono/mono/commit/b20d5ce1e5d69512242dd42ae6ff1afc2483c16d
in order to store an exception raised by the managed method before passing it
to `ftnptr_eh_callback`.  After that commit, we invoke the callback from the
stack unwinder, rather than from the method wrapper.  As a result both of the
locals are now dead code.
=> [marshal] Delete unused locals in emit_managed_wrapper_ilgen

mcs/class/corlib/Test/System/ConvertTest.cs, mono/mini/interp/interp.c
A comparison with NaN is always `false`.
=> [interp] throw overflow exception when {float,double}.NaN is converted to an int type

mono/profiler/Makefile.am, mono/profiler/ptestrunner.pl
We need xunit xml output for Helix.
The new mode which doesn't rely on build tree paths can be enabled by passing the special value "out-of-tree" as the build dir.
Respects the MONO_EXECUTABLE env variable and bases everything off of that.
Also unified run_test and run_test_sgen since we only have sgen nowadays and we only need one.
=> [profiler] Add xunit xml profiler tests output and allow tests to run from outside the build tree 

mono/mini/mini-llvm.c, mono/mini/objects.cs
Fixes https://github.com/mono/mono/issues/11378
=> [llvm] Fix passing vtypes received by value as arguments, they need to be copied

mono/tests/Makefile.am, mono/tests/threadpool-exceptions1.cs, mono/tests/threadpool-exceptions2.cs, mono/tests/threadpool-exceptions4.cs, mono/tests/threadpool-exceptions5.cs, mono/tests/threadpool-exceptions7.cs
=> [runtime] Fixes threadpool tests not to rely on arbitrary sleep timeout

mcs/class/corlib/Test/System/ConvertTest.cs, mono/mini/interp/interp.c
Backport of #11380.
/cc @lewurm 
Description:
A comparison with NaN is always `false`.
=> [2018-10] [interp] throw overflow exception when {float,double}.NaN is converted to an int type

mcs/class/corlib/Test/System/ConvertTest.cs, mono/mini/interp/interp.c
Backport of #11380.
/cc @lewurm 
Description:
A comparison with NaN is always `false`.
=> [2018-08] [interp] throw overflow exception when {float,double}.NaN is converted to an int type

mono/metadata/icall.c, mono/metadata/w32file-unix.c, mono/metadata/w32file-win32.c, mono/metadata/w32file.h, mono/mini/mini-wasm.c
On Unix and Wasm, mono_w32file_get_volume_information only implements last parameter.
On all platforms, mono_w32file_get_volume_information is only asked for its last parameter.
So replace mono_w32file_get_volume_information with mono_w32file_get_file_system_type that
only takes that parameter.
=> [w32file] Restrict mono_w32file_get_volume_information interface to its actual implementation and usage.

sdks/wasm/WasmHttpMessageHandler.cs
- Adds support for HttpCompletionOption.ResponseHeadersRead by delaying reading of the response body into HttpContent
- Adds optional support for streaming responses in supported browsers
- Adds support for canceling in flight fetch requests
=> Extend WasmHttpMessageHandler

mono/mini/mini-x86.c
Backport of #11089.
/cc @lewurm @jaykrell
Description:
I don't know what the specific code is or what changed, etc.
This addresses Mac/x86:
https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/15364/parsed_console/log.html
```Unable to compile method 'int Tests:calli_sig_check_2 ()' due to: 'Invalid IL code in Tests:calli_sig_check_2 (): IL_000b: calli     0x11000044```
which then fails an assert and fails overall.
CI goes deep into bash w/o echoing commands but a repro is:
cd mono/mini
MONO_PATH=./../../mcs/class/lib/net_4_x lldb -- ./mono --aot iltests.exe
The code is meant to be invalid, and meant to raise an exception,
which is catchable/resumable (at least in the JIT case where
executing IL the first time, can raise an exception while caller is
running, vs. AOT where …
=> [2018-10] x86 mono_arch_get_patch_offset: add support for 0xe9/jmp eip+32b.

mcs/class/Mono.Debugger.Soft/Test/dtest.cs
https://github.com/mono/mono/issues/11416
=> Disable failing assert in failing test DebuggerTests.Threads Assert.AreEqual (ThreadState.Stopped, e.Thread.ThreadState)

configure.ac
Earlier in the 2018-08 branch, Mono on desktop Linux, OSX and Windows would
default to hybrid suspend.  Turn that off for now (revert to preemptive suspend
by default).
Continue hybrid suspend work on 2018-10 and master.
=> [2018-08] Disable hybrid suspend default

mcs/class/System/Mono/SystemCertificateProvider.cs
=> [System]: `lock` protect `SystemCertificateProvider.EnsureInitialize()`.

mono/mini/interp/mintops.def
So that the debug output renders the operand of `MINT_CKNULL_N` correctly.
=> [interp] fix definition of MINT_CKNULL_N

mono/mini/mini-llvm.c, mono/mini/objects.cs
Backport of #11389.
Description:
Fixes https://github.com/mono/mono/issues/11378
=> [2018-08] [llvm] Fix passing vtypes received by value as arguments, they need to be copied

mcs/class/corlib/Test/System/DelegateTest.cs, mono/metadata/marshal-ilgen.c
Backport of #11433.
/cc @lewurm 
Description:
=> [2018-10] [delegates] do not use CEE_CALLVIRT for non-virtual methods

mono/mini/mini-llvm.c, mono/mini/objects.cs
Backport of #11389.
Description:
Fixes https://github.com/mono/mono/issues/11378
=> [2018-10] [llvm] Fix passing vtypes received by value as arguments, they need to be copied

mono/mini/mini-posix.c
Backport of #11435.
/cc @alexanderkyte 
Description:
The change which made the handler return (rather than crashing the
runtime) did not consider this control flow path that causes the sigterm
signal handler to trigger the merp dumper if we return.
We now always return.
This was previously so that a random sigterm could be used to trigger a
dump. This isn't really used, and won't work right now anyways
(we don't register it until right before we dump). My fix is to remove
it, and to make the signal handler only work as part of the dumper
machinery.
@monojenkins skip
=> [2018-10] [crash] Fix merp invocation

mono/mini/mini-posix.c
Backport of #11435.
/cc @alexanderkyte 
Description:
The change which made the handler return (rather than crashing the
runtime) did not consider this control flow path that causes the sigterm
signal handler to trigger the merp dumper if we return.
We now always return.
This was previously so that a random sigterm could be used to trigger a
dump. This isn't really used, and won't work right now anyways
(we don't register it until right before we dump). My fix is to remove
it, and to make the signal handler only work as part of the dumper
machinery.
@monojenkins skip
=> [2018-08] [crash] Fix merp invocation

mono/metadata/icall.c, mono/metadata/threads.c
We were previously only setting it from the icall. The icall was
therefore fine, while invocations associated with actual dumps
caused crashes like this:
```
thread #10, name = 'Thread Pool Worker'
frame #0: 0x00007fff978dac22 libsystem_kernel.dylib`__psynch_mutexwait + 10
frame #1: 0x00007fff979c5dfa libsystem_pthread.dylib`_pthread_mutex_lock_wait + 100
frame #2: 0x00007fff979c3519 libsystem_pthread.dylib`_pthread_mutex_lock_slow + 285
frame #3: 0x0000000108e0d4a9 mono`mono_loader_lock + 73
frame #4: 0x0000000108dc9106 mono`mono_class_create_from_typedef + 182
frame #5: 0x0000000108dc1f2c mono`mono_class_get_checked + 92
frame #6: 0x0000000108e21da2 mono`mono_metadata_parse_type_internal + 1378
frame #7: 0x0000000108e25e11 mono`mono_metadata_parse_mh_full + 1233
frame #8: …
```
=> [crash] Fix async setting for crash reporter

mono/metadata/icall.c, mono/metadata/threads.c
Backport of #11464.
/cc @alexanderkyte 
Description:
We were previously only setting it from the icall. The icall was
therefore fine, while invocations associated with actual dumps
caused crashes like this:
```
thread #10, name = 'Thread Pool Worker'
frame #0: 0x00007fff978dac22 libsystem_kernel.dylib`__psynch_mutexwait + 10
frame #1: 0x00007fff979c5dfa libsystem_pthread.dylib`_pthread_mutex_lock_wait + 100
frame #2: 0x00007fff979c3519 libsystem_pthread.dylib`_pthread_mutex_lock_slow + 285
frame #3: 0x0000000108e0d4a9 mono`mono_loader_lock + 73
frame #4: 0x0000000108dc9106 mono`mono_class_create_from_typedef + 182
frame #5: 0x0000000108dc1f2c mono`mono_class_get_checked + 92
frame #6: 0x0000000108e21da2 mono`mono_metadata_parse_type_internal + 1378
frame #7: 0x0000000108e25e11 …
```
=> [2018-08] [crash] Fix async setting for crash reporter

mono/metadata/icall.c, mono/metadata/threads.c
Backport of https://github.com/mono/mono/pull/11464.
We were previously only setting it from the icall. The icall was
therefore fine, while invocations associated with actual dumps
caused crashes like this:
```
thread #10, name = 'Thread Pool Worker'
frame #0: 0x00007fff978dac22 libsystem_kernel.dylib`__psynch_mutexwait + 10
frame #1: 0x00007fff979c5dfa libsystem_pthread.dylib`_pthread_mutex_lock_wait + 100
frame #2: 0x00007fff979c3519 libsystem_pthread.dylib`_pthread_mutex_lock_slow + 285
frame #3: 0x0000000108e0d4a9 mono`mono_loader_lock + 73
frame #4: 0x0000000108dc9106 mono`mono_class_create_from_typedef + 182
frame #5: 0x0000000108dc1f2c mono`mono_class_get_checked + 92
frame #6: 0x0000000108e21da2 mono`mono_metadata_parse_type_internal + 1378
frame #7: 0x0000000108e25e11 …
```
=> [2018-06] [crash] Fix async setting for crash reporter

mcs/class/corlib/System.Reflection/MonoMethod.cs, mcs/class/corlib/System/MonoCustomAttrs.cs, mcs/class/corlib/corlib.csproj, mcs/class/corlib/corlib.dll.sources, mcs/class/referencesource/mscorlib/system/attribute.cs
Part of #9660.
Related CoreFX tests will be fully enabled after https://github.com/dotnet/corefx/pull/33101 is complete and ported to Mono fork.
=> [Reflection] CoreFX import for MethodInfo type

mcs/class/corlib/Test/System.Threading.Tasks/Task_T_Test.cs
so it doesn't trigger a stack overflow on Xamarin.iOS with interpreter on a debug build (`CFLAGS=-O0`).
=> [tests] reduce recursion depth

mcs/class/corlib/Test/System.Threading.Tasks/Task_T_Test.cs
Backport of #11473.
/cc @lewurm 
Description:
so it doesn't trigger a stack overflow on Xamarin.iOS with interpreter on a debug build (`CFLAGS=-O0`).
=> [2018-08] [tests] reduce recursion depth

mcs/class/corlib/Test/System.Threading.Tasks/Task_T_Test.cs
Backport of #11473.
/cc @lewurm 
Description:
so it doesn't trigger a stack overflow on Xamarin.iOS with interpreter on a debug build (`CFLAGS=-O0`).
=> [2018-10] [tests] reduce recursion depth

mcs/class/corlib/Test/System.Threading.Tasks/Task_T_Test.cs
Backport of #11473.
/cc @lewurm 
Description:
so it doesn't trigger a stack overflow on Xamarin.iOS with interpreter on a debug build (`CFLAGS=-O0`).
=> [2018-06] [tests] reduce recursion depth

mcs/class/corlib/System.Security.Policy/Evidence.cs
Fixes #7750.
This is my first contribution to mono, so please let me know if there's any additional procedure I may have to do for this that I'm not aware of. Thanks!
=> Add missing constructor in System.Security.Policy.Evidence

mcs/class/corlib/LinkerDescriptor/mscorlib.xml
Upcoming changes to monolinker will make additional optimizations when no instance ctors are marked.
To be safe, add preservations for the ctor's of types that are created in the runtime.
The change to preserve the .ctor() of`System.Runtime.Remoting.Messaging.AsyncResult`  was made for more than out of caution.  We have a simple delegate test that hung without this.
=> [corlib] Additional constructor preservations

mono/metadata/marshal-ilgen.c, mono/mini/mini.c, mono/utils/monobitset.c, mono/utils/monobitset.h
Fixes https://github.com/mono/mono/issues/11488, an regression introduced by https://github.com/mono/mono/pull/11294
=> [runtime] allocate volatile_{locals,args} bitset in image mempool

mono/metadata/handle.c, mono/metadata/handle.h
Functions with HANDLE_FUNCTION_ENTER, only call mono_thread_info_current once,
instead of 1 + per-MONO_HANDLE_NEW.
This can be extended in future in multiple potential ways.
1 Macro split from HANDLE_FUNCTION_ENTER.
This is easiest/no downside, i.e. for functions that do not HANDLE_FUNCTION_ENTER
but that do multiple MONO_HANDLE_NEW, call other macro
just to mono_thread_info_current () into local.
2 Pass TLS as separate parameter. Probably not actually, see 4.
3 Store TLS in handles -- too large? Probably not actually, see next.
4 Store TLS in MonoError. i.e. MonoError is "call context", chained
up to "thread context".
=> Reduce TLS accesses.

mono/metadata/icall.c, mono/metadata/threads.c
Backport of #11464.
/cc @alexanderkyte 
Description:
We were previously only setting it from the icall. The icall was
therefore fine, while invocations associated with actual dumps
caused crashes like this:
```
thread #10, name = 'Thread Pool Worker'
frame #0: 0x00007fff978dac22 libsystem_kernel.dylib`__psynch_mutexwait + 10
frame #1: 0x00007fff979c5dfa libsystem_pthread.dylib`_pthread_mutex_lock_wait + 100
frame #2: 0x00007fff979c3519 libsystem_pthread.dylib`_pthread_mutex_lock_slow + 285
frame #3: 0x0000000108e0d4a9 mono`mono_loader_lock + 73
frame #4: 0x0000000108dc9106 mono`mono_class_create_from_typedef + 182
frame #5: 0x0000000108dc1f2c mono`mono_class_get_checked + 92
frame #6: 0x0000000108e21da2 mono`mono_metadata_parse_type_internal + 1378
frame #7: 0x0000000108e25e11 …
```
=> [2018-10] [crash] Fix async setting for crash reporter

mcs/class/System/Mono/SystemCertificateProvider.cs
Backport of #11437.
Description:
Fixes #11434
=> [2018-10] [System]: `lock` protect `SystemCertificateProvider.EnsureInitialize()`.

mcs/class/System/Mono/SystemCertificateProvider.cs
Backport of #11437.
Description:
Fixes #11434
=> [2018-08] [System]: `lock` protect `SystemCertificateProvider.EnsureInitialize()`.

mono/mini/interp/interp.c
happens on fullAOT + interp on mscorlib tests
=> [interp] accept typed-by-ref as return type from a JIT call

mcs/class/corlib/Test/System/GCTest.cs
needed for mscorlibtests on Xamarin.iOS with interpreter
=> [bcl] avoid false pinning in GCTest

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/metadata/marshal-ilgen.c
Use mono_mb_emit_op for CEE_LDOBJ to ensure wrapper data is added for
indirect load of a ref return value as method-to-ir expects this for wrappers.
Follow up to https://github.com/mono/mono/pull/10472
=> Fix ref return for structs in runtime invoke wrapper.

configure.ac, mcs/class/corlib/ReferenceSources/Buffer.cs, mcs/class/corlib/ReferenceSources/String.cs, mono/metadata/icall-decl.h, mono/metadata/icall-def.h, mono/metadata/icall.c
Some observations
- We can't use Unsafe.CopyBlock here because it uses the cpblk instruction which is resolved to call to Buffer.Memcpy (except cpblk with iconst sizes which are unrolled)
- icall to memcpy is very fast compared to the managed implementation, it might even make sense to have cpblk call it directly but that is questionable.
- because native memcpy is so fast it doesn't make sense to optimize the managed implementation for large sizes (like doing block sized copy) because even though it would be faster than the current implementation it would still be much slower than native memcpy.
- aot + llvm doesn't offer any relevant gain
=> [corlib] Use native memcpy for Buffer.Memcpy for larger sizes

mono/mini/interp/interp.c
Backport of #11522.
Description:
happens on fullAOT + interp on mscorlib tests
=> [2018-10] [interp] accept typed-by-ref as return type from a JIT call

mono/mini/interp/interp.c
Backport of #11522.
/cc @lewurm 
Description:
happens on fullAOT + interp on mscorlib tests
=> [2018-06] [interp] accept typed-by-ref as return type from a JIT call

mcs/class/corlib/Test/System/GCTest.cs
Backport of #11521.
/cc @lewurm 
Description:
needed for mscorlibtests on Xamarin.iOS with interpreter
=> [2018-06] [bcl] avoid false pinning in GCTest

mono/mini/interp/interp.c
Backport of #11522.
Description:
happens on fullAOT + interp on mscorlib tests
=> [2018-08] [interp] accept typed-by-ref as return type from a JIT call

scripts/ci/run-upload-sentry.sh
Internal developers looking for access to this server should contact me on Slack.
Accounts should be forthcoming for runtime engineers.
=> [runtime] Enable usage of Runtime team sentry server

mcs/class/corlib/Test/System/GCTest.cs
Backport of #11521.
Description:
needed for mscorlibtests on Xamarin.iOS with interpreter
=> [2018-08] [bcl] avoid false pinning in GCTest

mcs/class/corlib/Test/System/GCTest.cs
Backport of #11521.
Description:
needed for mscorlibtests on Xamarin.iOS with interpreter
=> [2018-10] [bcl] avoid false pinning in GCTest

mcs/class/corlib/System.Reflection/MonoParameterInfo.cs, mcs/class/corlib/Test/System.Reflection/ParameterInfoTest.cs
Backport of #11330.
Description:
Adding checks for `DateTime?` and `decimal?` to `DefaultValue` property getter will allow to retrieve correct values instead of  System.Reflection.Missing
Fixes https://github.com/mono/mono/issues/11303
=> [2018-10] Fixing ParameterInfo.RawDefaultValue for non-null default values of DateTime?` and decimal? 

mcs/class/Mono.Debugger.Soft/Test/dtest-app.cs, mcs/class/Mono.Debugger.Soft/Test/dtest.cs, mono/metadata/marshal-ilgen.c
Use mono_mb_emit_op for CEE_LDOBJ to ensure wrapper data is added for
indirect load of a ref return value as method-to-ir expects this for wrappers.
Backport https://github.com/mono/mono/pull/11514
/cc @joncham
=> [2018-10] Fix ref return for structs in runtime invoke wrapper.

.gitignore, man/mono.1, mono/mini/aot-compiler.c
Currently we can pass custom arguments to LLVM's `opt` and `llc` via:
```
mono --aot=llvm,llvmopts="...",llvmllc="..."
```
but those completely override the default arguments mono uses (some of them are required).
E.g. lets say I need to add `-foo` to both opt and llc, I should do:
```
mono --aot=llvm,llvmllc="**-foo** -march=x86-64 -mattr=sse4.1 -asm-verbose=false 
-disable-gnu-eh-frame -enable-mono-eh-frame -mono-eh-frame-symbol=_mono_aot_p_eh_frame 
-disable-tail-calls -no-x86-call-frame-opt -relocation-model=pic 
-filetype=obj,llvmopts="**-foo** -O2 -disable-tail-calls"
```
So this PR introduces new commands `llvmopts-add` and `llvmllc-add` to be able to simply do:
`mono --aot=llvm,llvmopts-add="-foo",llvmllc-add="-foo"`
PS: let me know if you don't like the `-add` suffix
/cc: …
=> Don't override default LLVM's opt & llc args via llvmopts-add and llvmllc-add commands

mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs
Backport of #11442.
/cc @marek-safar @domino46
Description:
Fixes #11441
=> [2018-10] Added missing cts.Cancel() in HttpClient Dispose() method

mono/tests/Makefile.am
It was fixed by https://github.com/mono/mono/pull/11433
Related: https://github.com/mono/mono/issues/6861
=> [interp] enable delegate-with-null-target.exe

sdks/wasm/Makefile, sdks/wasm/packager.cs
Right now it's in same location as wasm implementation assemblies
which means they are used for execution but they are not .NET desktop
compatible.
=> [wasm] Move bundled linker to different location

sdks/wasm/driver.c
=> Fix wasm mono showing print dialog twice on error

llvm/SUBMODULES.json
Commit list for mono/llvm:
* mono/llvm@c97510286a5 [mono] respect hardfloat/softloat setting in ARM ABI (#16)
@ mono/llvm@8415fd85ce1 Fix the mono calling convention on arm64+linux.
@ mono/llvm@117a508c0ca Merge pull request #15 from mono/android-eh
@ mono/llvm@7dd82303e5e Emit .fnstart/.fnend directives on arm ELF platforms in the mono EH writer since the ARM backends depends on ARMException doing it, and ARMException is not ran when --disable-gnu-eh-frame is given.
Diff: https://github.com/mono/llvm/compare/81376d161cb6c2230834b2dc096ccbdae8d93020...c97510286a58f9aaa116fcfdb8b693d5f61910d2
Backport of https://github.com/mono/mono/pull/11607
=> [2018-08] [llvm] bump for armhf callingconv fix

llvm/SUBMODULES.json
Commit list for mono/llvm:
* mono/llvm@c97510286a5 [mono] respect hardfloat/softloat setting in ARM ABI (#16)
* mono/llvm@8415fd85ce1 Fix the mono calling convention on arm64+linux.
Diff: https://github.com/mono/llvm/compare/117a508c0ca65b754008e94e3eb97e77edfef04b...c97510286a58f9aaa116fcfdb8b693d5f61910d2
Backport of https://github.com/mono/mono/pull/11607
=> [2018-10] [llvm] bump for armhf callingconv fix

sdks/wasm/WasmHttpMessageHandler.cs
- Most of the leaks present themselves during a Cancel of a streaming request.
=> [wasm] Clean up leaks in the WasmHttpMessageHandler.

mcs/Makefile
Bumping api-snapshot submodule which brings in a newly
built GenAPI binaries along with a rename of the exe
to Microsoft.DotNet.GenAPI.exe
=> Updating GenAPI binaries

mono/mini/driver.c
So this is possible now:
```console
$ REGRESSION_FILTER_METHOD=test_0_return ./mono/mini/mono-sgen --single-method=inline ./mono/mini/basic.exe
$ # or
$ REGRESSION_FILTER_METHOD=test_0_return ./mono/mini/mono-sgen --regression --interp ./mono/mini/basic.exe
```
Addresses https://github.com/mono/mono/pull/10740#discussion_r219570904
=> [mini] rename INTERP_FILTER_METHOD to REGRESSION_FILTER_METHOD and accept it for all execution engines

configure.ac, libgc/Makefile.am, mcs/Makefile, mcs/errors/Makefile, mcs/mcs/README, mcs/tests/Makefile, mono/benchmark/Makefile.am, mono/mini/Makefile.am.in, mono/profiler/Makefile.am, mono/tests/Makefile.am, mono/tests/assembly-load-reference/Makefile.am, mono/tests/gc-descriptors/Makefile.am, mono/tests/testing_gac/Makefile.am, mono/tests/tests-config.in, mono/unit-tests/Makefile.am, po/mcs/Makefile.in.in, runtime/Makefile.am, scripts/ci/run-jenkins.sh, scripts/ci/run-test-acceptance-tests.sh, scripts/ci/run-test-default.sh, scripts/ci/run-test-interpreter.sh, scripts/ci/run-test-mac-sdk.sh, scripts/ci/run-test-stress-tests.sh, scripts/ci/run-test-testing_aot_full.sh, scripts/ci/run-test-testing_aot_full_interp.sh, scripts/ci/run-test-testing_aot_hybrid.sh, scripts/ci/run-test-winaot.sh
So we can precompile all tests across the repo using a simple "make test" in the root.
This is necessary for some upcoming Helix work.
=> Add common "test" target for precompiling test assemblies

sdks/builds/ios.mk
It's not really used, and the directory `[...]/SDKs/WatchOS.sdk` always exists.
=> [ios] cosmetic fix for WatchOS Makefile

mono/utils/mono-tls.c
In gcc 4 the GOT register was being setup such that calls to __tls_get_offset would work. However, in later levels of gcc the compiler will not set up that register if GOT variables aren't being accessed. This resulted in SEGV when the offset was being retrieved. Rather than add this code to the macro I found it simpler to reference the GOT variable, then use the address returned for that variable, and then subtract the tls base which is held in access registers 0 and 1 (these being 32-bit registers and used as a convenience by glibc/gcc).
=> Simplify retrieving TLS offset

.gitmodules, configure.ac, libgc/Makefile.am, mcs/class/System.Web/System.Web.Caching/CacheDependency.cs, mcs/errors/Makefile, mcs/packages/Makefile, mcs/tests/Makefile, mcs/tools/Makefile, mcs/tools/mono-helix-client/HelixBase.cs, mcs/tools/mono-helix-client/HelixTestBase.cs, mcs/tools/mono-helix-client/MainlineTests.cs, mcs/tools/mono-helix-client/Makefile, mcs/tools/mono-helix-client/mono-helix-client.cs, mcs/tools/mono-helix-client/mono-helix-client.exe.sources, mcs/tools/mono-symbolicate/Makefile, mono/btls/Makefile.am, mono/mini/Makefile.am.in, mono/native/Makefile.am, mono/profiler/Makefile.am, mono/tests/Makefile.am, po/mcs/Makefile.in.in, runtime/Makefile.am, runtime/mono-test.sh, scripts/ci/run-jenkins.sh, scripts/ci/run-test-helix.sh, scripts/ci/util.sh, support/Makefile.am
- Adding a new client tool for sending jobs which uses the Helix SDK to create jobs in the Helix environment.
- Add targets to bundle tests and add a script to run them in Helix
- Workaround an issue with System.Web tests in the Helix environment due to FileSystemWatcher
https://github.com/mono/mono/issues/9099
=> Add tools/scripts for running tests in Helix environment

mcs/class/System.ServiceModel/System.ServiceModel.Channels/MtomMessageEncoder.cs
Currently, when using MTOM encoding with WCF, the content-type of a response message is not passed to the XmlMtomReader, which results in an error when ensuring that the mediatype is 'multipart' and subtype is 'related'.
Fixes #10895
=> [wcf] pass on the ContentType of MTOM message response

sdks/builds/ios.mk
It's not really used, and the directory `[...]/SDKs/WatchOS.sdk` always exists.
Backport of #11639.
=> [2018-10] [ios] cosmetic fix for WatchOS Makefile

sdks/builds/ios.mk
It's not really used, and the directory `[...]/SDKs/WatchOS.sdk` always exists.
Backport of #11639.
=> [2018-08] [ios] cosmetic fix for WatchOS Makefile

llvm/SUBMODULES.json, mono/mini/mini-arm64.c
Commit list for mono/llvm:
* mono/llvm@f80899cb3eb [mono] respect hardfloat/softloat setting in ARM ABI (#16)
* mono/llvm@f80899cb3eb (HEAD -> master, origin/master) [mono] respect hardfloat/softloat setting in ARM ABI (#16)
* mono/llvm@37e14bd72e6 Fix the mono calling convention on arm64+linux.
* mono/llvm@acb33f3436e Pack 32bits llc, opt and llvm-dis in archive as well
* mono/llvm@9b92b4b8760 Merge pull request #14 from lateralusX/lateralusX/build-llvm-windows-x64
* mono/llvm@e2ae3309b0c Fixes Mono LLVM usage on Windows x64.
* mono/llvm@384caa9849a Build LLVM Windows x64 using CMake + VS2015 or VS2017.
* mono/llvm@0b3cb8ac12c Emit an LSDA for methods without landing pads too since we need the information about the 'this' register.fbbfbae4fea [ci] Enable x86/amd64 backends. (#9)
* …
=> [2018-06] [llvm] bump for armhf callingconv fix

mono/metadata/class-init.c, mono/metadata/class.c, mono/metadata/sre.c, mono/tests/Makefile.am, mono/tests/bug-10837.cs
Say you have;
```c#
interface IBar<T> { T Bla(); }
class Foo<A,B>: IBar<A>, IBar<B> {
int IBar<int>.Bla)() { ... }
}
```
The GTD of Foo will have the following interface offsets table:
```
4: IBar<A>
5: IBar<B>
```
With the existing code, if you have Foo<int,int> the interface offsets table will look like this:
```
4: IBar<int>
```
The problem with that is it will produce a hole in the vtable and subclasses of Foo<int,int> will have not on slot 5.
That would be just wasteful, unless you have this:
```c#
class Sub: Foo<int,int>, IBar<int> {
int IBar<int>.Bla)() { ...  }
}
```
IOW, a subclass that overrides the interface implementation in Foo. The problem is that it's not always reliable to which iface offset
calls to `IBar<int>` will go through and thus it's possible to have calls made …
=> [metadata] Compute interface offsets of ginst by inflating the GTD instead of doing it from the grounds up.

mcs/class/System/System.Diagnostics/Process.cs, mcs/class/System/Test/System.Diagnostics/ProcessTest.cs
This pull request fixes starting a process with an empty environment variable collection in `ProcessStartInfo`. As per the issue it fixes a regression that it used to work but currently an empty environment variable collection works like it was never touched.
I also made a minor fix to remove the `StringBuilder` because a simple `string.Concat` does the job without the `StringBuilder` allocation and overhead.
I've included unit tests. Please let me know if you'd like any changes.
Fixes #8766
Backport of #11630.
/cc @marek-safar @jonorossi
=> [2018-10] Fix starting process with empty environment incorrectly inherits all variables

mcs/class/System/System.Diagnostics/Process.cs, mcs/class/System/Test/System.Diagnostics/ProcessTest.cs
This pull request fixes starting a process with an empty environment variable collection in `ProcessStartInfo`. As per the issue it fixes a regression that it used to work but currently an empty environment variable collection works like it was never touched.
I also made a minor fix to remove the `StringBuilder` because a simple `string.Concat` does the job without the `StringBuilder` allocation and overhead.
I've included unit tests. Please let me know if you'd like any changes.
Fixes #8766
Backport of #11630.
/cc @luhenry @jonorossi
=> [2018-08] Fix starting process with empty environment incorrectly inherits all variables

mcs/class/System/System.Diagnostics/Process.cs, mcs/class/System/Test/System.Diagnostics/ProcessTest.cs
This pull request fixes starting a process with an empty environment variable collection in `ProcessStartInfo`. As per the issue it fixes a regression that it used to work but currently an empty environment variable collection works like it was never touched.
I also made a minor fix to remove the `StringBuilder` because a simple `string.Concat` does the job without the `StringBuilder` allocation and overhead.
I've included unit tests. Please let me know if you'd like any changes.
Fixes #8766
=> Fix starting process with empty environment incorrectly inherits all variables

mono/mini/mini-arm64.c
Backport of #10674. LLVM is already properly bumped on this branch.
Related: https://github.com/mono/mono/issues/11627
=> [2018-08] [arm64] Pass small stack args correctly on linux. Fixes pinvoke.exe with llvm+full aot.

mono/metadata/mono-debug.c
Backport of #11672.
/cc @luhenry @vargaz
=> [2018-06] [runtime] Fix the size calculation in mono_debug_add_method ().

configure.ac
On iOS 6.0 (`-miphoneos-version-min=6.0`), this is needed to get modern C++11
headers like `<type_traits>`.  It does not seem to harm anything to
over-approximate and pass it to clang always when building on Darwin.
=> [configure] Pass -stdlib=libc++ to clang on darwin to build C++ code

mono/utils/mono-state.c
This code is duplicated completely from the code directly above it (github doesn't show in this diff)
=> [crash] Remove duplicated il_offset

mono/utils/mono-state.c
This code is duplicated completely from the code directly above it (github doesn't show in this diff)
Backport of #11700.
=> [2018-10] [crash] Remove duplicated il_offset

mono/utils/mono-state.c
This code is duplicated completely from the code directly above it (github doesn't show in this diff)
Backport of #11700.
=> [2018-08] [crash] Remove duplicated il_offset

mono/utils/mono-state.c
This code is duplicated completely from the code directly above it (github doesn't show in this diff)
Backport of #11700.
=> [2018-06] [crash] Remove duplicated il_offset

mono/mini/aot-runtime.c
=> [2018-10] [aot] image is usable without debug flag when interpreter is used

mono/mini/aot-runtime.c
=> [2018-08] [aot] image is usable without debug flag when interpreter is used

mono/mini/aot-runtime.c
=> [2018-06] [aot] image is usable without debug flag when interpreter is used

mcs/class/System.ServiceModel/System.ServiceModel.Dispatcher/XmlMessagesFormatter.cs
Currently, setting IsWrapped=false on a MessageContract leads to an error in serialization due to an empty element being present where the wrapper element would have been, instead of it being gone entirely.
The serialization then fails because the empty string is not valid localName (which of course is fine).
=> [wcf] do not assume that message body is always Wrapped

mono/utils/mono-hwcap-ppc.c
PASE is the Unix subsystem of IBM i, and is binary compatible with AIX. Since IBM i is not a Unix, there are some subtle differences between both environments.
There is an issue with the way PASE on IBM i 7.2 behaves differently than AIX with regards to the POWER_n_ANDUP defines for CPU compatibility. When trying to build on i as opposed to AIX, the following errors appear which break the build:
```
make[5]: Entering directory '/home/YVANJ/mono-on-i/mono/mono/utils'
CC       libmonoutils_la-mono-hwcap-ppc.lo
mono-hwcap-ppc.c: In function 'mono_hwcap_arch_init':
mono-hwcap-ppc.c:67:6: error: implicit declaration of function '__power_4_andup' [-Werror=implicit-function-declaration]  if (__power_4_andup())
^~~~~~~~~~~~~~~
mono-hwcap-ppc.c:67:2: warning: nested extern declaration of …
```
=> [aix/ibmi] Build broken due to subtle difference between i and AIX

mcs/tools/upload-to-sentry/UploadToSentry.cs
The previous code read all the .dll and .exe files even when there actually wasn't any mono_crash.*.json file to process.
In the happy case of no crash file this cuts the time from 60s to 5s.
We can also use more efficient patterns in Directory.GetFiles() instead of getting _all_ files and filtering in-memory.
Lastly we also ignore printing a message when a debug symbols file wasn't found for an assembly, this is an expected case for a lot of our assemblies.
Using InMemory Cecil reading shaves another 20s off.
=> [upload-to-sentry] Skip reading assemblies without mono_crash.json and silence no symbols error

mono/metadata/sgen-stw.c, mono/utils/mono-threads-coop.h, mono/utils/mono-threads-state-machine.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
This addresses the symptoms (ie invalid thread state transition assertions) from #11403 and #10722, at least for GC Safe threads.
With non-hybrid suspend, a pulse is just a resume.
With hybrid suspend, a `pulse` is a combination of a resume of a preemptively
suspended GC Unsafe thread and a request that it suspend again - as if we
atomically resumed the thread and then applied the initial phase of two-phase
suspend again.  If the now-running thread comes to a GC Safe -> GC Unsafe
transition it will suspend.  If not, we will preemptively suspend it again
during the mop-up phase.
The important thing is that we don't want the thread to transition to GC Unsafe
again: if it does so, it may try to take a lock that some other
async-suspended thread is holding, and it will never reach a safepoint …
=> [threading] Implement 'pulse' transition for two-phase STW

mcs/class/System.Windows.Forms/System.Windows.Forms/ProfessionalColorTable.cs
Dropdown menus have light text on a light background in a dark theme:
The background is rendered here:
https://github.com/mono/mono/blob/4a6b11577fe06a58e6326b1c3a3bb58cfee6185c/mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStripProfessionalRenderer.cs#L372-L375
`this.ColorTable.ToolStripDropDownBackground` is set to either `SystemColors.Window` or various hard coded shades of near-white in `ProfessionalColorTable`.
Now that color comes from `SystemColors.Menu`, defined as "[Gets a Color structure that is the color of a menu's background](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.systemcolors)", which looks better in a dark theme:
It still looks fine in a normal theme as well:
KeePass is not affected by this change, presumably thanks to its custom toolstrip …
=> Draw menu background with SystemColors.Menu to fix dark themes

mcs/class/System.Drawing/System.Drawing/Color.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/ProfessionalColorTable.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/Theme.cs, mcs/class/System.Windows.Forms/System.Windows.Forms/X11DesktopColors.cs
Even after #10942, menus and toolstrips still look awful with a dark theme:
#10942 was a first stab in the dark at what was going on here, before I managed to get mono to compile for testing. I was hopeful that it would address this, but the problem was different.
Later I thought the problem might be that `SystemColors.ButtonFace.IsSystemColor` was `false`. It looked like this might have caused the runtime to interpret `ButtonFace`'s special 168 value as an RGB code instead of a system color marker.
This fix had no effect (see below for true cause), but I'll include it anyway; the lower bound of the upper system colors block needs to decrease from 170 to 168 to allow `ButtonFace` and `ButtonHighlight` to be considered system colors: …
=> Really fix ToolStrip background

mono/metadata/sgen-stw.c, mono/utils/mono-threads-coop.h, mono/utils/mono-threads-state-machine.c, mono/utils/mono-threads.c, mono/utils/mono-threads.h
Backport #11708 to `2018-10`
----
This addresses the symptoms (ie invalid thread state transition assertions) from #11403 and #10722, at least for GC Safe threads.
With non-hybrid suspend, a pulse is just a resume.
With hybrid suspend, a `pulse` is a combination of a resume of a preemptively
suspended GC Unsafe thread and a request that it suspend again - as if we
atomically resumed the thread and then applied the initial phase of two-phase
suspend again.  If the now-running thread comes to a GC Safe -> GC Unsafe
transition it will suspend.  If not, we will preemptively suspend it again
during the mop-up phase.
The important thing is that we don't want the thread to transition to GC Unsafe
again: if it does so, it may try to take a lock that some other
async-suspended thread is holding, …
=> [2018-10] [threading] Implement 'pulse' transition for two-phase STW

sdks/wasm/WasmHttpMessageHandler.cs, sdks/wasm/binding_support.js, sdks/wasm/bindings.cs, sdks/wasm/driver.c, sdks/wasm/sample.cs
- Example: When a delegate is marshalled to JS it is allocated so that it is not GC'd.  Since we do not know when JS is finished with the delegate we need a way, for right now, to tell the Runtime to de-allocate the object and remove the transparent/bridged instance from JS as well.  The side-effect of not doing this is that any local that is captured (used) by a lambda became heap memory and were allocated as fields on the object.  Since the delegate is never a candidate for GC the local that was captured was never released either.
- Fix an error with Windows Edge and Windows IE that threw an exception `Object doesn't support this action` on certain host objects.  This only affected Windows Edge and IE when using the JavaScript delete operator to clean up an object after being disposed. …
=> [wasm][binding] Allow the cleanup of transparent/bridged marshalled objects causing leaks.

mcs/class/reference-assemblies/Makefile, mcs/mcs/ikvm.cs, mcs/tools/xbuild/Makefile, mcs/tools/xbuild/frameworks/net_4.7.2.xml
Backport of https://github.com/mono/mono/pull/11391 to 2018-08
=> [2018-08] Add .NET 4.7.2 reference assemblies

mono/mini/gshared.cs, mono/mini/mini-arm64-gsharedvt.c
Fixes https://github.com/mono/mono/issues/11613.
=> [arm64] Fix passing r4/r8 arguments on the stack in the gsharedvt trampoline.

mono/mini/gshared.cs, mono/mini/mini-arm64-gsharedvt.c
Fixes https://github.com/mono/mono/issues/11613.
Backport of #11741.
=> [2018-08] [arm64] Fix passing r4/r8 arguments on the stack in the gsharedvt trampoline.

mono/mini/gshared.cs, mono/mini/mini-arm64-gsharedvt.c
Fixes https://github.com/mono/mono/issues/11613.
Backport of #11741.
=> [2018-10] [arm64] Fix passing r4/r8 arguments on the stack in the gsharedvt trampoline.

mcs/class/System.Windows.Forms/System.Windows.Forms/ListView.cs
do not access the Items[] in ListView.ToString() in VirtualMode
as this might cause an endless recursion if ToString() is called
from within the RetrieveVirtualItem event handler
Fixes #11049
=> prevent endless recursion in ListView.ToString()

mono/dis/main.c, mono/metadata/appdomain.c, mono/metadata/assembly-internals.h, mono/metadata/assembly.c, mono/metadata/attach.c, mono/metadata/coree.c, mono/metadata/domain.c, mono/metadata/mono-security.c, mono/metadata/w32socket.c, mono/mini/aot-runtime.c, mono/mini/driver.c, tools/pedump/pedump.c
Try to make all entry points into the loader look more uniform by taking a request
struct instead of a big pile of arguments.  Where it makes sense, make the
structs subtypes of each other so that more general arguments are shared.
- Pass assembly load arguments in a struct
- Pass assembly open arguments in a struct
- Push MonoAssemblyOpenRequest creation to some callers
- Drop is_private argument to try_load_from
It's been dead code for ten years since c9e8bac0c3522a05bd08985a76d923b1bbd83b79
- Get rid of mono_assembly_open_a_lot
- Drop dead static function
- Replace mono_assembly_load_full_nosearch by mono_assembly_request_byname_nosearch
- replace mono_assembly_load_full_internal by mono_assembly_request_byname
- Make mono_assembly_request_byname the internal API
pass a …
=> [loader] Use Request structs to pass arguments to the loader

mono/mini/iltests.il, mono/mini/test_op_il_seq_point.sh, mono/mini/test_op_il_seq_point_headerfooter.sh, mono/tests/Makefile.am, mono/tests/calli_sig_check.il
We weren't checking whether the runtime returned a zero exit code which means if the compilation failed we still reported success.
Now the exit code is propagated all the way up and we report an error both to make and to the xml result file.
Since iltests.exe contains a test with expected invalid IL this would now cause a failure. The easiest fix is to just move that test from mono/mini to mono/tests since all other tests are fine.
Fixes https://github.com/mono/mono/issues/11091
=> [tests] Propagate runtime exit code in test_op_il_seq_point.sh

mono/mini/interp/interp-internals.h, mono/mini/interp/interp.c, mono/mini/interp/transform.c
Avoid call overhead by inlining small methods. We replace stinarg opcodes with storing of the arguments in locals allocated in the parent frame (for each argument).
TODO
- support for methods with locals
- maybe add inline costs to prevent over inlining
On microbenchmark inlining can improve up to 3.5x (less than the 5x that I observed with jit).
Contributes to #11531
=> [interp] Add inlining of small methods

mono/metadata/loader.c
Otherwise we emit a noisy warning when doing a lookup of the method.
Fixes https://github.com/mono/mono/issues/11479
=> [loader] ignore 'internalcall' impl attribute on 'abstract' methods

mono/mini/mini-trampolines.c
Fixes this on mscorlib/mixed mode on Xamarin.iOS:
```
[FAIL] NonExceptional.Serialization_Deserialization : System.Runtime.Serialization.SerializationException : An error occurred while deserializing the object. The serialized data is corrupt.Â 
[FAIL] NonExceptional.Serialize_Deserialize_FixedDateRule : System.Runtime.Serialization.SerializationException : An error occurred while deserializing the object. The serialized data is corrupt.Â 
[FAIL] NonExceptional.Serialize_Deserialize_FloatingDateRule : System.Runtime.Serialization.SerializationException : An error occurred while deserializing the object. The serialized data is corrupt.Â 
[FAIL] SerializationTests.Serialization_Deserialization : System.Runtime.Serialization.SerializationException : An error occurred while deserializing the …
```
=> [mini] use AOT trampolines in interp mixed mode

mono/metadata/loader.c
Otherwise we emit a noisy warning when doing a lookup of the method.
Fixes https://github.com/mono/mono/issues/11479
Backport of #11755.
=> [2018-08] [loader] ignore 'internalcall' impl attribute on 'abstract' methods

mono/mini/mini-trampolines.c
Fixes this on mscorlib/mixed mode on Xamarin.iOS:
```
[FAIL] NonExceptional.Serialization_Deserialization : System.Runtime.Serialization.SerializationException : An error occurred while deserializing the object. The serialized data is corrupt.Â 
[FAIL] NonExceptional.Serialize_Deserialize_FixedDateRule : System.Runtime.Serialization.SerializationException : An error occurred while deserializing the object. The serialized data is corrupt.Â 
[FAIL] NonExceptional.Serialize_Deserialize_FloatingDateRule : System.Runtime.Serialization.SerializationException : An error occurred while deserializing the object. The serialized data is corrupt.Â 
[FAIL] SerializationTests.Serialization_Deserialization : System.Runtime.Serialization.SerializationException : An error occurred while deserializing the …
```
=> [2018-08] [mini] use AOT trampolines in interp mixed mode

mono/metadata/loader.c
Otherwise we emit a noisy warning when doing a lookup of the method.
Fixes https://github.com/mono/mono/issues/11479
Backport of #11755.
=> [2018-10] [loader] ignore 'internalcall' impl attribute on 'abstract' methods

mcs/class/System.Runtime.Remoting/Test/RemotingServicesTest.cs, mcs/class/corlib/System.Runtime.Remoting/TypeInfo.cs
This adds any base interfaces to the remoting TypeInfo to match the
behavior of MS.NET
=> Fixes #11779

mono/mini/mini-exceptions.c
For handled exceptions. On unhandled exceptions we leave them for debugging purposes.
Fixes exception18.cs
Partial backport of https://github.com/mono/mono/pull/11760
=> [2018-10] [interp] Don't include internal frames in stack trace

mono/mini/mini-exceptions.c
For handled exceptions. On unhandled exceptions we leave them for debugging purposes.
Fixes exception18.cs
Partial backport of https://github.com/mono/mono/pull/11760
=> [2018-08] [interp] Don't include internal frames in stack trace

mono/mini/mini-exceptions.c
For handled exceptions. On unhandled exceptions we leave them for debugging purposes.
Fixes exception18.cs
Partial backport of https://github.com/mono/mono/pull/11760
=> [2018-06] [interp] Don't include internal frames in stack trace

sdks/wasm/packager.cs
Add the packager `--search-path` parameter
- Adds the ability for the packager to search in additional folders when resolving assemblies.
- Ignore missing symbols when resolving assemblies, which can happen for facade assemblies.
=> [Wasm] Packager search paths adjustments

mono/metadata/object.c
We have a return on [line 3608](https://github.com/mono/mono/blob/892cad1dab3db16c269ae22b0d68b0bd1d5c0668/mono/metadata/object.c#L3608) that doesn't have any assignment to the variable "o" before that. Since it's stack memory, it will be garbage.
=> [runtime] Fix return of uninit value

mcs/class/System/Test/System.Security.Cryptography.X509Certificates/X509StoreTest.cs
While working on PR #11829 I stress-tested the tests by running multiple test
runs in parallel, and it turned out that the X509StoreTest is not parallel-safe.
This fixes the X509StoreTest test to parallel-safe.
=> [System] Use pid-specific X509Store names in tests to make it possible to run multiple System test runs in parallel.

mono/mini/mini-ppc.c
This is a no-op on gcc ppc for AIX, Linux, and FreeBSD, and should
not be used until gcc implements this. (It *does* on ARM, RISC-V,
Alpha, and MIPS, however - but not PowerPC or x86, based on a skim
of gcc source.)
Should fix #11527.
=> Revert usage of gcc builtin for icache flush on ppc

mcs/class/System/System.csproj, mcs/class/System/common.sources, mcs/class/System/corefx.unix.sources, mcs/class/System/corefx.windows.sources
This brings two internal helper classes from CoreFX.
=> Misc corefx sources (ReadOnlyMemoryStream and CertificateHelper).

mcs/class/System/Test/System.Net.Security/SslStreamTest.cs, mcs/class/System/Test/System.Net.Sockets/SocketTest.cs, mcs/class/System/Test/System.Net.Sockets/TcpClientTest.cs, mcs/class/System/Test/System.Net.Sockets/TcpListenerTest.cs, mcs/class/System/Test/System.Net.Sockets/UdpClientTest.cs, mcs/class/System/Test/System.Net.WebSockets/ClientWebSocketTest.cs, mcs/class/System/Test/System.Net/HttpListener2Test.cs, mcs/class/System/Test/System.Net/HttpListenerRequestTest.cs, mcs/class/System/Test/System.Net/HttpListenerTest.cs, mcs/class/System/Test/System.Net/HttpWebRequestTest.cs, mcs/class/System/Test/System.Net/HttpWebResponseTest.cs, mcs/class/System/Test/System.Net/WebClientTest.cs, mcs/class/System/Test/System.Net/WebRequestTest.cs, mcs/class/test-helpers/NetworkHelpers.cs, mcs/class/test-helpers/SocketResponder.cs
Refactor tests to use system-assigned ports whenever possible, so that we
avoid the potential race condition in NetworkHelpers.FindFreePort.
This should make it much less probable to run into spurious "Address already
in use" exceptions.
In some cases I kept the call to NetworkHelpers.FindFreePort:
* When the test is not binding/listening on a port, but instead trying to
connect to an inexistent port (for tests that verifies error handling /
exceptions). In this case there is still a race condition (if a test tries
to verify that a connection fails, it may unexpectedly succeed instead).
* Sometimes the test doesn't actually use the port (the test is verifying
something very different, for instance a ArgumentNullExceptions, which are
thrown before the port is used).
* Some API doesn't …
=> [System] Refactor tests to use system-assigned ports whenever possible.

mono/mini/driver.c
As of https://github.com/mono/mono/pull/11342 the regression tests (builtin-types.cs) call into System.Native incidentally as part of Interop.Sys type initialization. The --regression command line option was causing the --config part of the mono invocation to be ignored, resulting in a buried 'System.DllNotFoundException: System.Native' during the test run
/cc @baulig
=> [driver] Parse config file under --regression mode also

mono/mini/abcremoval.c, mono/mini/aot-compiler.c, mono/mini/driver.c, mono/mini/mini-codegen.c, mono/mini/mini-exceptions.c
abcremoval.c: In function 'process_block':
abcremoval.c:1061:6: warning: variable 'inst_index' set but not used [-Wunused-but-set-variable]
int inst_index;
^
driver.c: In function 'mini_regression_step':
driver.c:514:12: warning: 'func' may be used uninitialized in this function [-Wmaybe-uninitialized]
result = func ();
^
aot-compiler.c: In function 'emit_method_info':
aot-compiler.c:6388:10: warning: variable 'method_index' set but not used [-Wunused-but-set-variable]
guint32 method_index;
^
mini-codegen.c: In function 'mono_print_ins_index_strbuf':
mini-codegen.c:727:3: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'gpointer' [-Wformat=]
g_string_append_printf (sbuf, " %s", ins->inst_p1);
^
CC       libmini_la-mini-exceptions.lo
mini-exceptions.c: In …
=> Fix some warnings. Mostly benign but driver.c looks maybe crashy.

mono/mini/ee.h, mono/mini/interp-stubs.c, mono/mini/interp/interp.c, mono/mini/mini-runtime.c, mono/mini/mini-trampolines.c
Partial backport of https://github.com/mono/mono/pull/10095
This change is also needed for the following situation: On a native-to-managed transition the interpreter executes the `NATIVE_TO_MANAGED` wrapper. This wrapper makes sure that the thread is attached. However, doing `transform` requires an attached thread in some cases (e.g. when you run with `--debug`). This commit makes sure that we transform the `InterpMethod` when the thread is attached, that is, when the entry point for the native-to-managed transition is requested.
FYI: This is already in `2018-08` and up.
=> [2018-06] [interp] Compile method for errors when needed

configure.ac, mcs/class/corlib/ReferenceSources/RuntimeType.cs, mcs/class/corlib/System.Reflection/MonoEvent.cs, mcs/class/corlib/Test/System.Reflection/EventInfoTest.cs, mono/metadata/icall-def.h, mono/metadata/icall.c
This PR fixes #11235 by removing BindingFlags checks from native code to instead
trust the checks made in managed code. This fixes the case when events were incorrectly returned from types that have overridden private or static events.
Fixes #11235
=> Hide detection fixes for events
